Imprv/options selector restyle
weseek/growi pull request #2546
Opened 2020-07-17 05:52 UTC by shukmos

## やったこと
- options selectorのスタイルを新デザインにした

## 懸念点
- コーディングのポリシーを100%キャッチアップできていないので、書く場所/書き方が合っているか不安
- btn-outline-secondaryのクラスのスタイルを上書きしたので、他の箇所にも影響がある。
  - スコープ外なので、ここだけに影響するようにすべきか
  - いや、しかし最終的にはbtn-outline-secondary全てはこのスタイルにしたいのが、デザイナーとしてのの要望

![image](https://user-images.githubusercontent.com/20252919/87752953-7d0fc580-c83c-11ea-92b3-27ed3f8fb3af.png)
![image](https://user-images.githubusercontent.com/20252919/87752996-931d8600-c83c-11ea-90c5-e2acf6692b56.png)

- XD
  - https://xd.adobe.com/view/e529ceaa-c408-4561-97c7-ba52cee9791b-b07a/screen/487d7250-5b76-422a-9bc2-7a1f38cd75e8/specs/

2020-07-17 08:04 UTC, yuki-takei commented
以下、レビュー依頼出す前に毎回やってください。今この PR はレビューできない状態です。

1. Files changed タブを split view で確認
1. 自分が加えた変更以外の差分が出ていないことを確認

2020-07-21 07:28 UTC, yuki-takei commented
scss の修正が多いのでなんとなくダメそう(という感想)

> いや、しかし最終的にはbtn-outline-secondary全てはこのスタイルにしたいのが、デザイナーとしてのの要望

をやるときに今回の編集がゴミになっちゃうのはなんかいやなので、やるならそこまでやってほしい。
そして scss は1行でも少なく、`!important` は極力使わない。

2020-09-02 03:16 UTC, shukmos commented
> 最終的にはbtn-outline-secondary全てはこのスタイルにしたい
から拡張して、「最終的にはbtn-outline-#{$color}はこれにしたい」というモチベーションで変更を加えました。
（スコープは拡大してしまったが、各行数も変わらないと思ったので）


### 変更後の見た目
- hover時/クリック時の見た目が変わってます
- primary
![image](https://user-images.githubusercontent.com/20252919/91927042-964cd280-ed13-11ea-9ee2-21babe36a948.png)
- secondary
![image](https://user-images.githubusercontent.com/20252919/91927078-a369c180-ed13-11ea-8f75-f1ace32939de.png)

2020-09-02 08:13 UTC, yuki-takei requested changes

2020-09-02 08:13 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +    // }
不要なコードは削除してください

2020-09-02 08:13 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +    color: $secondary !important;
important を使わなくてもいいように、セレクタをもっと限定してください。

2020-09-02 08:13 UTC, yuki-takei commented on src/client/styles/scss/_override-bootstrap.scss
> +  }
これは `scss/theme/_reboot_bootstrap-theme-colors.scss` に移動かなあ。

```
@each $color, $value in $theme-colors {
  .btn-outline-#{$color} {
    @include button-outline-variant($value);
  }
}
```

が現在のコード

2020-09-03 04:15 UTC, shukmos commented
FB対応しました。

### やったこと
- 要らないコメントアウトを削除
- !important を使わない記述に変更
- `.btn-outline-#{$color}  ...` の記述を `scss/theme/_reboot_bootstrap-theme-colors.scss`に移動

2020-09-03 05:12 UTC, shukmos commented
- Light時のみ当てはめたいスタイルが、Darkに当てはまっていたので、記述箇所変更しました

![image](https://user-images.githubusercontent.com/20252919/92073737-696ded80-edef-11ea-88be-f767a9a748cf.png)
![image](https://user-images.githubusercontent.com/20252919/92073768-74288280-edef-11ea-8f5b-5c11a9f20312.png)

2020-09-03 05:18 UTC, merged