Imprv/gw 3453 design topoftablecontents
weseek/growi pull request #2650
Opened 2020-08-12 07:09 UTC by oshikishintaro

GW-3453 TopOfTableContentsのデザイン調整
- ウィンドウサイズが小さい時、折り返しに対応
- 見た目をデザインスペックに近くなるよう調整
- アイコンのサイズ指定方法を変更

### ライトモード
<img width="207" alt="スクリーンショット 2020-08-12 15 56 42" src="https://user-images.githubusercontent.com/65531771/89984563-8dd51f00-dcb4-11ea-8ee2-18e182b2d023.png">

### popover展開時
<img width="251" alt="スクリーンショット 2020-08-12 15 56 47" src="https://user-images.githubusercontent.com/65531771/89984571-90377900-dcb4-11ea-843b-ad9ac18176be.png">

### 折り返し時
<img width="181" alt="スクリーンショット 2020-08-12 15 56 56" src="https://user-images.githubusercontent.com/65531771/89984592-9af20e00-dcb4-11ea-8f88-b862b3881857.png">

### ダークモード
<img width="219" alt="スクリーンショット 2020-08-12 15 56 32" src="https://user-images.githubusercontent.com/65531771/89984580-94639680-dcb4-11ea-9d76-d0d48729da5d.png">

## XDデザイン案
<img width="365" alt="スクリーンショット 2020-08-12 16 00 02" src="https://user-images.githubusercontent.com/65531771/89984752-e4425d80-dcb4-11ea-9680-a291b0c8ca03.png">
- 変更点：横幅の都合でアローマークをオミット

2020-08-12 07:36 UTC, yuki-takei commented on src/client/js/components/PageAccessoriesModal.jsx
> +                <svg width="20px" height="20px"><PageListIcon /></svg>
svg アイコンである PageListIcon をさらに svg で囲うという手段は html 的に不正なものになりそう

2020-08-12 07:39 UTC, yuki-takei commented on src/client/styles/scss/_layout.scss
> +  }
## 現状
- svg エレメントの中に書いてある css クラスに対して、width, height を指定している

## 改善点
- svg の中に書いてある css クラス
- jsx に書いてある css クラス

は、概念として別のものとして取り扱ってほしい。

色の変更等は前者に対して色指定をしていいと思うけど、
レイアウト調整を行うなら後者

2020-08-12 07:40 UTC, yuki-takei commented on src/client/styles/scss/_layout.scss
> +  }
PageAccessoriesModal.jsx 向けの記述は専用の scss を作ってください。
_layout.scss はシステム全体に関わる記述のみ入れる。

2020-08-12 07:40 UTC, yuki-takei commented on src/client/styles/scss/_layout.scss
> +}
_layout.scss はシステム全体に関わる記述のみ入れる。

2020-08-12 07:41 UTC, yuki-takei commented
折り返しを許容しないデザインにしたい

2020-08-19 08:32 UTC, oshikishintaro commented on src/client/js/components/PageAccessoriesModal.jsx
> +                <svg width="20px" height="20px"><PageListIcon /></svg>
svg タグを削除し、サイズ指定をscssで行う方式に変更しました。

2020-08-19 08:38 UTC, oshikishintaro commented on src/client/styles/scss/_layout.scss
> +  }
モーダル専用の`_page_accessories_modal.scss`を作成し、
レイアウト指定を移動しました。

また、アイコンのjsx内から不要なクラス指定を削除し、
使用箇所でクラス指定する方式に変更しました。

2020-08-19 09:13 UTC, oshikishintaro commented on src/client/styles/scss/_layout.scss
> +}
メイン画面右（目次）に関する記述ですので、残してあります。

モーダルや別画面に関する記述は前述の`_page_accessories_modal.scss`に移動しました。

2020-08-19 11:10 UTC, oshikishintaro commented
> 折り返しを許容しないデザインにしたい

別ストーリー"GW-3545 記事エリアのデザイン刷新"にて行います。
※目次コンテナ自体を固定幅にすることで折り返しを回避。

2020-08-19 13:09 UTC, yuki-takei requested changes

2020-08-19 13:09 UTC, yuki-takei commented on src/client/styles/scss/_page_accessaries_modal.scss
> +  .grw-modal-head-icons {
https://github.com/weseek/growi/pull/2658/files#r473005744 の形に則った命名(セレクタの構造)にしてください。

2020-08-19 13:09 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +  .grw-table-top-icons {
https://github.com/weseek/growi/pull/2658/files#r473005744 の形に則った命名(セレクタの構造)にしてください。

2020-08-19 13:09 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +  .grw-modal-head-icons {
https://github.com/weseek/growi/pull/2658/files#r473005744 の形に則った命名(セレクタの構造)にしてください。

2020-08-19 13:09 UTC, yuki-takei commented on src/client/js/components/PageAccessoriesModal.jsx
> +          <Nav className="nav-title border-bottom grw-modal-head-icons">
https://github.com/weseek/growi/pull/2658/files#r473005744 の形に則った命名(セレクタの構造)にしてください。

2020-08-19 13:09 UTC, yuki-takei commented on src/client/js/components/TopOfTableContents.jsx
> +        <div className=" pr-2 mr-2 grw-table-top-icons">
この div は不要。代わりにそれぞれの button に `btn-page-list` 等の名前を付けた上で、https://github.com/weseek/growi/pull/2658/files#r473005744 の形に則った命名(セレクタの構造)にしてください。

2020-08-20 04:37 UTC, oshikishintaro commented on src/client/styles/scss/_page_accessaries_modal.scss
> +  .grw-modal-head-icons {
アイコンのクラス名を個別のものに戻し、指定のセレクタ構造にしました。

2020-08-20 04:37 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors.scss
> +  .grw-table-top-icons {
アイコンのクラス名を個別のものに戻し、指定のセレクタ構造にしました。

2020-08-20 04:37 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors.scss
> +  .grw-modal-head-icons {
アイコンのクラス名を個別のものに戻し、指定のセレクタ構造にしました。

2020-08-20 04:37 UTC, oshikishintaro commented on src/client/js/components/PageAccessoriesModal.jsx
> +          <Nav className="nav-title border-bottom grw-modal-head-icons">
アイコンのクラス名を個別のものに戻し、指定のセレクタ構造にしました。

2020-08-20 04:37 UTC, oshikishintaro commented on src/client/js/components/TopOfTableContents.jsx
> +        <div className=" pr-2 mr-2 grw-table-top-icons">
アイコンのクラス名を個別のものに戻し、指定のセレクタ構造にしました。

2020-08-25 03:57 UTC, oshikishintaro commented
コンフリを解消しました

2020-08-25 13:24 UTC, merged