Imprv/add icons for master marge
weseek/growi pull request #2658
Opened 2020-08-17 03:20 UTC by oshikishintaro

自作アイコンを追加
各サイズ、dark/Lightテーマで動作確認済

# 含まれる内容
### fab用アイコン(newpageアイコン、topに戻るアイコン)

<img width="181" alt="スクリーンショット 2020-08-12 16 58 51" src="https://user-images.githubusercontent.com/65531771/89990559-85cdad00-dcbd-11ea-9e06-2af2c980b3fd.png">

<img width="224" alt="スクリーンショット 2020-08-12 16 58 22" src="https://user-images.githubusercontent.com/65531771/89990570-86feda00-dcbd-11ea-8f11-7ce3130f9789.png">

### パーソナルドロップダウン用アイコン(サイドバーモードdrawer/dockアイコン、ライト /ダークモードアイコン)

<img width="179" alt="スクリーンショット 2020-08-12 16 58 48" src="https://user-images.githubusercontent.com/65531771/89990563-86664380-dcbd-11ea-9fdb-093256ddc2bf.png">

<img width="173" alt="スクリーンショット 2020-08-12 16 58 31" src="https://user-images.githubusercontent.com/65531771/89990567-86feda00-dcbd-11ea-9e4b-2f54d6b3af1d.png">

### edit navbar用ボタン

<img width="539" alt="スクリーンショット 2020-08-12 16 58 40" src="https://user-images.githubusercontent.com/65531771/89990564-86664380-dcbd-11ea-800c-591d212f93f7.png">

<img width="535" alt="スクリーンショット 2020-08-12 16 58 58" src="https://user-images.githubusercontent.com/65531771/89990550-849c8000-dcbd-11ea-8090-6044521d96f2.png">

2020-08-17 05:51 UTC, yuki-takei commented on src/client/js/components/Icons/SidebarDockIcon.jsx
> +    <g className="sidebar-dock-icon">
命名があんまりうまくない…
どこで使うかはこのアイコン自身が決めるわけではない。

2020-08-17 05:53 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +  }
lightmode-icon.use-os-settings, .darkmode-icon.use-os-settings はどこから来たんだ？

2020-08-17 06:31 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +  }
これは今 g 要素に対して当たっている

2020-08-17 06:34 UTC, yuki-takei commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +              <DarkIcon id="icon-prefer-dark" />
icon-prefer-dark をどこで使っているのかわからない

2020-08-17 06:37 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +  }
これは理解。`LiteIcon` コンポーネント内に存在する。

2020-08-17 06:38 UTC, yuki-takei commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +      <div id={props.id} className="px-2 sidebar-drawer-icon"><SidebarDrawerIcon /></div>
`.grw-sidebar-drawer-icon-container` にする

2020-08-17 06:38 UTC, yuki-takei commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +      <div id={props.id} className="px-2 sidebar-drawer-icon"><SidebarDrawerIcon /></div>
scss は

```
.grw-sidebar-drawer-icon-container {
  svg.g {
    fill: white;
  }
}
```

とかになる

2020-08-18 12:32 UTC, oshikishintaro commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +      <div id={props.id} className="px-2 sidebar-drawer-icon"><SidebarDrawerIcon /></div>
パーソナルドロップダウン内で使用しているsvgアイコン用の個別クラスネームを廃止、
（`sidebar-drawer-icon` `sidebar-dock-icon` `darkmode-icon` `Lightmode-icon`の４つ）
`personal-dropdown-icons`に統一しました。
命名について、
クラスの使用箇所がばらけていたためcontainerではなくiconsという命名にしています。

2020-08-18 12:39 UTC, oshikishintaro commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +              <DarkIcon id="icon-prefer-dark" />
不要な記述のため削除しました。

2020-08-18 12:45 UTC, oshikishintaro commented on src/client/js/components/Icons/SidebarDockIcon.jsx
> +    <g className="sidebar-dock-icon">
`sidebar-dock-icon` `sidebar-drawer-icon`は本機能のための書き下ろしアイコンなので、この命名にさせてください！

`Light(Dark)ModeIcon`などは汎用的な命名`Sun(Moon)Icon`に変更しました。
また、`EditNewPageIcon`はfab.jsxなどの記述に合わせ`CreatePageIcon`に名前を変更しました。

2020-08-18 12:45 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors.scss
> +  }
アイコンコンポーネント内のクラス指定を削除しました

2020-08-19 12:56 UTC, yuki-takei requested changes

2020-08-19 12:56 UTC, yuki-takei commented on src/client/styles/scss/_layout.scss
> +}
_navbar.scss に移動

2020-08-19 12:56 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +    fill: $color-global;
fill を設定する場合は全て svg も指定するセレクタを書いて。
`.personal-dropdown-icons svg` 等。

2020-08-19 13:04 UTC, yuki-takei requested changes

2020-08-19 13:04 UTC, yuki-takei commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +      <div className="dropdown-menu dropdown-menu-right personal-dropdown-icons">
personal-dropdown-icons クラスは消す。名が体を表していない。
このエレメントの実態は dropdown であり、「personal-dropdown のアイコンの集合」ではない。

2020-08-19 13:04 UTC, yuki-takei commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +    <>
grw-light-icon クラスを付ける

2020-08-19 13:04 UTC, yuki-takei commented on src/client/styles/scss/_layout.scss
> +}
記述対象ファイルはは _navbar.scss に移動

2020-08-19 13:05 UTC, yuki-takei commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +      <div id={props.id} className="px-2 sidebar-drawer-icon"><SidebarDrawerIcon /></div>
命名があまりよくないので具体的に指定するコメントを書いた。

2020-08-20 05:42 UTC, oshikishintaro commented on src/client/styles/scss/_layout.scss
> +}
・クラスネーム`personal-dropdown-icons `を削除し、各アイコンに個別のクラスを設定しました。
・関連する記述を _navbar.scss に移動しました。

2020-08-20 05:43 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors.scss
> +    fill: $color-global;
クラスネームを変更し、セレクタを書き変えました。

2020-08-20 05:43 UTC, oshikishintaro commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +      <div className="dropdown-menu dropdown-menu-right personal-dropdown-icons">
クラスネームを変更し、セレクタを書き変えました。

2020-08-20 05:44 UTC, oshikishintaro commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +    <>
クラスネーム変更を反映しました。

2020-08-24 08:03 UTC, yuki-takei requested changes

2020-08-24 08:03 UTC, yuki-takei commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +              <LightIcon id="icon-prefer-light" />
この id 必要？(不要なら消す)

2020-08-24 08:03 UTC, yuki-takei commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +              <DarkIcon id="icon-prefer-dark" />
この id 必要？(不要なら消す)

2020-08-24 08:03 UTC, yuki-takei commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +              <DrawerIcon id="icon-prefer-drawer" className="grw-drawer-icon" />
この id 必要？(不要なら消す)
className も、ここでの指定は効いていないのではないか？

2020-08-25 04:10 UTC, oshikishintaro commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +              <LightIcon id="icon-prefer-light" />
idはツールチップの指定に使用しています。

```
const DrawerIcon = props => (
    <>
      <div id={props.id} className="px-2 grw-drawer-icon"><SidebarDrawerIcon /></div>
      <UncontrolledTooltip placement="bottom" fade={false} target={props.id}>Drawer</UncontrolledTooltip>
    </>
  );
```

2020-08-25 04:10 UTC, oshikishintaro commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +              <DarkIcon id="icon-prefer-dark" />
idはツールチップの指定に使用しています。

2020-08-25 04:11 UTC, oshikishintaro commented on src/client/js/components/Navbar/PersonalDropdown.jsx
> +              <DrawerIcon id="icon-prefer-drawer" className="grw-drawer-icon" />
クラスネームの指定は不要でしたので、削除しました。

idはツールチップの指定に使用しています。

2020-08-25 14:03 UTC, merged