gw-3225
weseek/growi pull request #2665
Opened 2020-08-18 05:01 UTC by takeru0001

2020-08-18 07:59 UTC, yuki-takei commented
レビュー不能。

* マージ先が master になってしまっている
* 中山くん以外が書いた差分が入ってしまっている

上記はレビュー依頼を出す前に必ず確認を。確認は split view で行う事。
意味が分からない場合は周りの人に聞いてください。

2020-08-18 10:00 UTC, yuki-takei commented on src/client/js/components/PageDuplicateModal.jsx
> +  const [isExist, setIsExist] = useState(false);
## 修正内容
重複しているページのパスのリストを保持する state にしてください。
isExist 相当は、そのリストが空かどうかで判別できる。

## 今後のための参考情報
もし boolean を用意するとしても、isExist では対象が何かわからない。
「重複が存在する」という意味の state 名にすべき。

2020-08-18 10:10 UTC, yuki-takei commented on src/client/js/components/PageDuplicateModal.jsx
> +    });
## 今後のための参考情報
繰り返し処理を行う場合は forEach を使うこと。map は返り値が必要な場合にのみ使う。

ただ、もし今回のように「重複があるかどうか」を見つけるときは Array.some や Array.filter を使うのが望ましい。両方共調べておいて。

2020-08-18 10:13 UTC, takeru0001 commented on src/client/js/components/PageDuplicateModal.jsx
> +    });
承知いたしました。調べておきます！

2020-08-19 07:28 UTC, makotoshiraishi commented
サーバー側で重複検索の処理をするため、ここではサーバーから受け取ったデータを表示するところだけを実装しました。
ダミーデータの中に入っているデータとユーザが入力した複製後の名前をフロントで表示するように実装しました。
サーバーサイドの実装は別タスクでやろうと思います。

2020-08-19 07:31 UTC, makotoshiraishi commented
<img width="809" alt="スクリーンショット 2020-08-19 16 29 12" src="https://user-images.githubusercontent.com/64956659/90605521-6f819d00-e239-11ea-8456-b751e24c83bb.png">

2020-08-19 09:44 UTC, makotoshiraishi commented on src/client/js/components/PageDuplicateModal.jsx
> +  function createSubordinatedList(value) {
この関数によってサーバー側に元ページ名と変更後のページ名を送り返り値として重複したページのリストが返ってくる。

2020-08-19 12:17 UTC, yuki-takei requested changes

2020-08-19 12:17 UTC, yuki-takei commented on src/client/js/components/PageDuplicateModal.jsx
> -  }, [appContainer, path, t]);
getSubordinatedList も将来的に必要になるので消す必要はない。

2020-08-19 12:17 UTC, yuki-takei commented on src/client/js/components/PageDuplicateModal.jsx
> -  }, [props.isOpen, getSubordinatedList]);
この effect なしだと、いつ subordinated list を取得するの？必要に見えるけど…

2020-08-19 12:17 UTC, yuki-takei commented on src/client/js/components/PageDuplicateModal.jsx
> +  function createSubordinatedList(value) {
サーバーから取得するメソッド名なのに create から始まるのはいけてない。
命名規則について調べて。Inner Wiki の開発ガイドもチェック。

2020-08-21 03:47 UTC, makotoshiraishi commented on src/client/js/components/PageDuplicateModal.jsx
>    }, [props.isOpen, getSubordinatedList]);
武井さんのFBに基づいて、useEffectとgetSubordinatedListの記述を戻しました（PRの時はコード自体を消去していた）。
私の認識としては、下の画像のように複製ページの名前を設定するときに既存のパスと重複しているもの**だけ**が表示されると思っていたのですが(市澤さんと確認してもそうでした)、他の場面で将来的にgetSubordinatedListを使用する予定があるという認識で良いでしょうか。
<img width="816" alt="スクリーンショット 2020-08-21 12 44 50" src="https://user-images.githubusercontent.com/64956659/90850379-7e3c9100-e3ac-11ea-94de-223477f87136.png">

2020-08-21 07:35 UTC, yuki-takei commented on src/client/js/components/PageDuplicateModal.jsx
>    }, [props.isOpen, getSubordinatedList]);
だとすると

- GW-3374 移動(リネーム)モーダルを開いた時に、api を叩いて子供のページ情報を取得できる
- GW-3524 移動(リネーム)モーダルの「再帰的」チェックボックスがチェックされた時に子ページを表示する

のゴールはどこなんだという話になる。

2020-08-21 07:46 UTC, merged