Imprv/gw3374
weseek/growi pull request #2666
Opened 2020-08-18 05:25 UTC by makotoshiraishi

2020-08-18 05:46 UTC, makotoshiraishi commented
Move/Renameモーダルで今いるページの子ページを取得して表示するように実装しました（見た目のレイアウトはまだです）。

2020-08-18 05:47 UTC, makotoshiraishi commented
<img width="802" alt="スクリーンショット 2020-08-18 14 46 25" src="https://user-images.githubusercontent.com/64956659/90475104-c4ea7b00-e161-11ea-830d-947af94ecd76.png">

2020-08-18 08:04 UTC, yuki-takei commented on src/client/js/components/PageRenameModal.jsx
> +          </div>
ページ数が超大量(数千ページ)あったときの対処を考えないと、モーダルが縦に長くなりすぎて使いづらくなる。

2020-08-18 08:17 UTC, makotoshiraishi commented on src/client/js/components/PageRenameModal.jsx
> +          </div>
ありがとうございます！
こちらのFBどちらかというと見た目の部分の指摘かなと思っているので、本タスク(子ページの情報の取得飲み)から少し外れるかなと思いました！あくまでも便宜的に取得できることを示すためにとりあえず表示させただけですね。

見た目の整形は次のタスクでやろうと思うのでそちらで反映させても良いでしょうか。

2020-08-18 08:54 UTC, yuki-takei commented on src/client/js/components/PageRenameModal.jsx
> +          </div>
「見た目の問題」と片付けるのは早計。

* 数千件あるとして、全件取ってきて全件スクロールするのか、ページングするのかは現時点でまず検討しておかないといけない
* ただ、「複製先のページ名ではエラーが出るものを、ページングすることによって補足できなくなる」のは避けたい

2020-08-19 09:45 UTC, makotoshiraishi commented on src/client/js/components/PageRenameModal.jsx
> +  function createSubordinatedList(value) {
この関数によってサーバー側に元ページ名と変更後のページ名を送り返り値として重複したページのリストが返ってくる。

2020-08-19 09:51 UTC, makotoshiraishi commented
市澤さんと話した結果実装を複製モーダルのように重複したページだけをサーバ側から取ってきてそれを表示するようにしました。
現段階ではまだサーバ側のAPIが実装できていないため、ダミーデータを入れたときの実装になっています。
また仮に重複が数千件あったとしたらdiv内でスクロールできるような実装にしました。

2020-08-19 09:53 UTC, makotoshiraishi commented
<img width="806" alt="スクリーンショット 2020-08-19 18 51 34" src="https://user-images.githubusercontent.com/64956659/90620333-423eea00-e24d-11ea-98b7-550bdd365cbd.png">

2020-08-28 07:22 UTC, makotoshiraishi commented
「再帰的に移動/名前変更」をチェックすると子ページが表形式で表示されるように実装しました。
また子ページが5件以上あると、表の中でスクロールできるようになっています。

2020-08-28 07:22 UTC, makotoshiraishi commented
<img width="831" alt="スクリーンショット 2020-08-28 16 18 12" src="https://user-images.githubusercontent.com/64956659/91533341-b0209b00-e94a-11ea-97a3-cb6704420a99.png">

2020-08-28 09:15 UTC, yuki-takei requested changes

2020-08-28 09:15 UTC, yuki-takei commented on src/client/styles/scss/_create-page.scss
> +  }
css が多すぎる。Wiki の開発ガイドを確認。

2020-08-28 09:15 UTC, yuki-takei commented on src/client/js/components/ComparePathsTable.jsx
> +    <table className="table table-bordered compare-page-table">
クラス名は開発ガイドを確認の上、他のファイルも参考にする

2020-08-28 09:15 UTC, yuki-takei commented on src/client/js/components/PageRenameModal.jsx
> +  const getSubordinatedList = useCallback(async() => {
中山くんに命名について聞いてください。

2020-08-31 06:57 UTC, makotoshiraishi commented on src/client/styles/scss/_create-page.scss
> +  }
不必要なcssの記述を削除しました。

2020-08-31 06:57 UTC, makotoshiraishi commented on src/client/js/components/ComparePathsTable.jsx
> +    <table className="table table-bordered compare-page-table">
クラス名の先頭に"grw"を付けました！

2020-08-31 07:07 UTC, itizawa commented on src/client/styles/scss/_create-page.scss
> +      width: 50%;
https://bootstrap-guide.com/utilities/display
ユーティリティの `w-50` が使えると思います。

2020-08-31 07:07 UTC, itizawa commented on src/client/styles/scss/_create-page.scss
> +  }
d-flex

2020-08-31 07:07 UTC, itizawa commented on src/client/styles/scss/_create-page.scss
> +      overflow-y: auto;
overflow-auto ?

2020-08-31 07:32 UTC, itizawa commented on src/client/styles/scss/_create-page.scss
> +  }
https://bootstrap-guide.com/utilities/display
ユーティリティの w-50 が使えると思います。

2020-08-31 07:59 UTC, makotoshiraishi commented on src/client/styles/scss/_create-page.scss
> +      overflow-y: auto;
ユーティリティ対応にしました！
ありがとうございます！

2020-08-31 08:53 UTC, merged