Display pagelist on modal body
weseek/growi pull request #2674
Opened 2020-08-19 07:02 UTC by zahmis

2020-08-19 07:05 UTC, zahmis commented on src/client/js/components/PageAccessoriesModal.jsx
> +
PageList という新しいコンポーネントを作成しました。
これは同じ名前のフォルダがあり、どうするべきか悩んでいます。
しかし、この名前以上に正確な名前が現状思いつかないため一旦これで行っています。

2020-08-19 07:30 UTC, zahmis commented on src/client/js/components/PageList.jsx
> +
useEffect を使用しています。
理由は、踏襲しようとした pageAttachment が クラスコンポーネントで、
 componetDidMount 内でserver に接続する処理がなされていました。

ここでの処理がベストであると自分も考えたので、
server に接続する処理を関数コンポーネントでしようとすると、useEffect を使用することになりました。

useCallback を使用しているのは、
useEffect を使用する際に現れる warning を対処したためです。
これによって、一回一回 server に接続しにいくということもなくなると考えました。

2020-08-19 07:30 UTC, zahmis commented on src/server/routes/apiv3/pages.js
> +    const { path } = req.query;
以前実装したダミーデータを実際のものに置き換えています。

2020-08-19 08:09 UTC, zahmis commented on src/client/js/components/PageAccessoriesModal.jsx
> +import PageList from './PageList';
PageList という新しいコンポーネントを作成しました。
これは同じ名前のフォルダがあり、どうするべきか悩んでいます。
しかし、この名前以上に正確な名前が現状思いつかないため一旦これで行っています。

2020-08-19 12:27 UTC, yuki-takei requested changes

2020-08-19 12:27 UTC, yuki-takei commented on src/client/js/components/PageList.jsx
> +  }
ロード中であることを示す spinner を表示させてください。(他のコンポーネントでもよくつかっているのでそれを参考に)
共通化してあったかどうかは覚えていない…市澤くんあたりに聞いてみて。

2020-08-20 13:18 UTC, zahmis commented on src/client/js/components/PageList.jsx
> +  }
spinner を実装しました。
useState ではなく throw(async() => を使う予定でしたが、Growi 内で現在検討中なので、
一旦isLoding を実装することにしました。

この処理でエラーハンドリングをいろいろ考えていたのですが、自分が想定していたエラーはサーバーサイドでキャッチされると考えたので、ここはこのままで良いと判断しました。
実際にサーバーに非常に時間のかかる処理を書いて動かしてみたところ写真のようになりました。

2020-08-20 13:19 UTC, zahmis commented on src/client/js/components/PageList.jsx
> +  }
<img width="1495" alt="スクリーンショット 2020-08-20 22 08 02" src="https://user-images.githubusercontent.com/57100766/90774934-2b72c300-e333-11ea-8bb8-d5982d5993c1.png">

2020-08-20 13:20 UTC, zahmis commented on src/client/js/components/PageList.jsx
> +  }
この後実際にページリストにページ群が表示されたことを確認しています。

2020-08-20 14:40 UTC, merged