Imprv/create three stranded button new
weseek/growi pull request #2680
Opened 2020-08-21 04:55 UTC by kaoritokashiki

2020-08-21 05:19 UTC, kaoritokashiki commented
[XD]
<img width="381" alt="スクリーンショット 0002-08-21 12 40 19" src="https://user-images.githubusercontent.com/59536731/90854913-2eb09200-e3b9-11ea-9883-07d5205b9298.png">
<img width="241" alt="スクリーンショット 0002-08-21 12 40 33" src="https://user-images.githubusercontent.com/59536731/90854916-307a5580-e3b9-11ea-934a-6f860593f272.png">

[default-light]
<img width="491" alt="スクリーンショット 0002-08-21 14 11 06" src="https://user-images.githubusercontent.com/59536731/90854920-34a67300-e3b9-11ea-8923-374ef185e61c.png">

[default-dark]
<img width="472" alt="スクリーンショット 0002-08-21 14 11 22" src="https://user-images.githubusercontent.com/59536731/90854922-35d7a000-e3b9-11ea-9283-fb459fbfcb80.png">

2020-08-21 06:12 UTC, kaoritokashiki commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +  }
bootstrapのしよう上、hover&activeの状態では、text-colorが白色になってしまっていたので、bgcolorと同じに変更しました。
白のままでもいい気はしますが、XD上では黒色になっているのと、そちらの方が目には優しいと感じました。

2020-08-21 08:02 UTC, yuki-takei commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +              </button>
別のコンポーネントにしてください。

2020-08-21 08:04 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +  }
`atoms/_buttons.scss` に移して、 .btn-like で使っている `button-outline-variant` を利用して。

2020-08-25 04:13 UTC, kaoritokashiki commented
<img width="282" alt="スクリーンショット 0002-08-25 13 13 15" src="https://user-images.githubusercontent.com/59536731/91122251-cb827080-e6d4-11ea-9890-5513f788f1d9.png">

<img width="285" alt="スクリーンショット 0002-08-25 13 13 24" src="https://user-images.githubusercontent.com/59536731/91122254-ccb39d80-e6d4-11ea-9844-999a8a66ccd9.png">

2020-08-25 07:15 UTC, yuki-takei requested changes

2020-08-25 07:15 UTC, yuki-takei commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +  t: PropTypes.func.isRequired, //  i18next
実用性を考えると各ボタンをクリックした時のイベントハンドラを割り当てるための props が足りない

2020-08-25 07:15 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +.three-stranded-button {
`.grw-` prefix 付けて

2020-08-26 09:21 UTC, merged

2020-08-26 09:22 UTC, kaoritokashiki commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +  onThreeStrandedButtonClicked: PropTypes.func,
イベントハンドラを割り当てるためのprops追加しました

2020-08-26 09:22 UTC, kaoritokashiki commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +    <div className="btn-group grw-three-stranded-button" role="group " aria-label="three-stranded-button">
prefix `grw-` 追加しました