Imprv/gw 3282 slack button
weseek/growi pull request #2692
Opened 2020-08-25 08:22 UTC by oshikishintaro

## GW-3282 ボタン作成

- 実装中のデザイン
<img width="291" alt="スクリーンショット 2020-08-25 17 08 31" src="https://user-images.githubusercontent.com/65531771/91149115-a8b48400-e6f5-11ea-9a2c-20217313b56d.png">
<img width="269" alt="スクリーンショット 2020-08-25 17 20 36" src="https://user-images.githubusercontent.com/65531771/91150467-6429e800-e6f7-11ea-8abd-5d52e8ceba85.png">
<img width="1917" alt="スクリーンショット 2020-08-25 17 20 56" src="https://user-images.githubusercontent.com/65531771/91150474-668c4200-e6f7-11ea-936a-d3a0cc3aaf19.png">

- デザインスペック
<img width="584" alt="スクリーンショット 2020-08-25 17 09 07" src="https://user-images.githubusercontent.com/65531771/91149159-b1a55580-e6f5-11ea-8766-bb1a701b121a.png">

- カラーの調整（ダークモード対応）/レスポンシブは未対応です。(別タスクに回す予定です)

2020-08-25 09:14 UTC, yuki-takei requested changes

2020-08-25 09:14 UTC, yuki-takei commented on public/images/icons/slack/slack-logo-off.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 448"><defs><style>.cls-1{fill:#9ba5af;}</style></defs><g id="レイヤー_2" data-name="レイヤー 2"><g id="レイヤー_1-2" data-name="レイヤー 1"><path class="cls-1
svg 内のゴミ取り除いてください

2020-08-25 09:14 UTC, yuki-takei commented on src/client/styles/scss/atoms/_custom_control.scss
> +  .custom-switch {
セレクタは `.custom-switch.custom-switch-lg` にする。

atomic design で検索して、「atom」の意味を調べてください。

2020-08-25 09:14 UTC, yuki-takei commented on src/client/styles/scss/_on-edit.scss
> +        border: transparent;
このファイルで指定した内容は、atoms/_custom_control に移してください。
`grw-custom-switch-slack` というクラスを作ってください。

atomic design で検索して、「atom」の意味を調べてください。

因みに、SlackNotification は CommentEditor でも使います。lg サイズでは大きすぎるかもしれない。

2020-08-30 07:32 UTC, zahmis commented on public/images/icons/slack/slack-logo-off.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 448"><defs><style>.cls-1{fill:#9ba5af;}</style></defs><g id="レイヤー_2" data-name="レイヤー 2"><g id="レイヤー_1-2" data-name="レイヤー 1"><path class="cls-1
svg 内に id が重複しているものをゴミだと認識しました。
それを取り除いています。

2020-08-30 08:13 UTC, zahmis commented on src/client/styles/scss/atoms/_custom_control.scss
> +  .custom-switch {
セレクタ修正しました。

atomic design は以下のサイトを参考にしました。

[Atomic Desig をわかったつもりになる](https://design.dena.com/design/atomic-design-%E3%82%92%E5%88%86%E3%81%8B%E3%81%A3%E3%81%9F%E3%81%A4%E3%82%82%E3%82%8A%E3%81%AB%E3%81%AA%E3%82%8B/)

自分の認識としては、デザインを分割する。
それによって、ブロックを解消したり
スモールステップで次のゴールに到達しやすいのかな？と思いました。
いきなり全部はきついので、最小単位（atom）でタスクを分割する。
デザインも他の職種と同様にスタイリングすると解釈しました。

2020-08-31 03:03 UTC, zahmis commented on src/client/styles/scss/_on-edit.scss
> +        border: transparent;
_on-edit.scss に指定されていたものを移行しました。
その際に、新しいクラスである grw-custom-switch-slack を作成しています。

2020-08-31 03:18 UTC, zahmis commented on public/images/icons/slack/slack-logo-off.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 448"><defs><style>.cls-1{fill:#9ba5af;}</style></defs><g id="レイヤー_2" data-name="レイヤー 2"><g id="レイヤー_1-2" data-name="レイヤー 1"><path class="cls-1
押木さんに相談した結果、g tag が不要とのことだったので削除しています。
また、on のバージョンも同様に削除しました。

2020-08-31 03:28 UTC, zahmis commented on src/client/styles/scss/atoms/_custom_control.scss
> +  $input-height-slack: 1.8rem;
新規に作成したクラスです。
_on-edit.scss で指定した内容を移行しています。

2020-08-31 03:28 UTC, zahmis commented on src/client/styles/scss/_on-edit.scss
以下の内容を atom に移行させます。

2020-08-31 03:28 UTC, zahmis commented on src/client/js/components/SlackNotification.jsx
> +      <div className="grw-slack-notification grw-custom-switch-slack">
scssで新規クラスを作成したので、
適用させています。

2020-08-31 03:28 UTC, zahmis commented on public/images/icons/slack/slack-logo-on.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 448">
on バージョンもゴミを取り除いています。

2020-08-31 08:43 UTC, yuki-takei commented on src/client/styles/scss/atoms/_custom_control.scss
> +  .custom-switch.custom-switch-lg {
これは sm を参考に、`.grw-slack-notification` 指定は外す。さもないと、.grw-slack-notification の下でしか使えず汎用性が失われる。

2020-08-31 08:43 UTC, yuki-takei commented on src/client/js/components/SlackNotification.jsx
> +      <div className="grw-slack-notification grw-custom-switch-slack">
適用箇所が違う

2020-08-31 08:43 UTC, yuki-takei commented on src/client/js/components/SlackNotification.jsx
> +            <div className="custom-control custom-switch custom-switch-lg">
`grw-custom-switch-slack` の適用対象はここ

2020-08-31 08:43 UTC, yuki-takei commented on src/client/styles/scss/atoms/_custom_control.scss
> +  }
atom についての理解が足りない。
スイッチに関するスタイルのみをここに書く。

長さの指定や border についての記述は逆に on-edit.scss の「.grw-slack-notification」下に追加する。

分離のさせ方の考え方がわからなければ口頭で説明するので聞きに来て。

2020-08-31 08:43 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +      $color-slack: #4b144c;
$color-slack は 5-16行目付近にデフォルトの variables を定義して、各テーマファイルから変更できるようにする。

2020-08-31 08:43 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +      border-color: $gray-200;
デフォルトの色は `_on-edit.scss` に書いてよい

2020-08-31 08:43 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +      }
デフォルトの色は `_on-edit.scss` に書いてよい

2020-08-31 08:45 UTC, yuki-takei commented
Comment のコンポーネントでの利用について全く考えられていない気がする。

2020-08-31 09:30 UTC, zahmis commented on src/client/styles/scss/atoms/_custom_control.scss
> +  .custom-switch.custom-switch-lg {
了解です。

2020-09-02 07:52 UTC, zahmis commented on src/client/js/components/SlackNotification.jsx
> +      <div className="grw-slack-notification grw-custom-switch-slack">
適用箇所を訂正しました。

2020-09-02 07:53 UTC, zahmis commented on src/client/js/components/SlackNotification.jsx
> +            <div className="custom-control custom-switch custom-switch-lg">
適用させました。

2020-09-02 07:53 UTC, zahmis commented on src/client/styles/scss/atoms/_custom_control.scss
> +  }
atom に関する説明ありがとうございました。

2020-09-02 08:03 UTC, zahmis commented on src/client/styles/scss/theme/_apply-colors.scss
> +      border-color: $gray-200;
このテーマに関しては、当初edit に記載していたのですが、
変更して、molecules/grw-slack-notification に移行しています。
molecules のパーツを comment でも　editor でも使用しています。

理由は、現在のサイズ感で今のところ問題がないため。

また、
レスポンシブル対応に関しては、
今回のタスクのスコープ外ですので、今回は実装していません。

レスポンシブルに関してですが、
押木さんに相談したところ、一応できてはいるが本当にこれでいいのか最終の決が下っていなさそうな感じでした。
なので、その辺りをもう少し詰めた上で、
レスポンシブル対応に取りかかりたいです。

2020-09-02 08:10 UTC, zahmis commented on src/client/styles/scss/_on-edit.scss
>      .grw-grant-selector {
この部分を molecules/slack-notification.scss に移行しています。

2020-09-02 08:20 UTC, zahmis commented on src/client/styles/scss/theme/_apply-colors.scss
> +      $color-slack: #4b144c;
本来 _apply-colors.scss にvariables を定義するはずだったんですが、
この指定が、molecules/slack-notification.scss に移行したので、
そちらに記述すると認識しました。

2020-09-02 15:43 UTC, zahmis commented on src/client/styles/scss/theme/_apply-colors.scss
> +      $color-slack: #4b144c;
本来、`_apply-colors.scss` の `.grw-slack-notification` の色を指定していました。

しかし、molecules/slack-notification を作成することになりました。
この段階では dark mode 対応させていないので、
 $color-slack の属する場所は `atom/_custom_control.scss` の `.custom-switch.custom-switch-slack`だと感じました。

2020-09-02 15:46 UTC, zahmis commented on src/client/styles/scss/theme/_apply-colors.scss
> +      $color-slack: #4b144c;
それとも dark-mode を対応させることを見越して、
`theme/_apply-colors.scss` に記述する方が望ましいのでしょうか？

または、そもそも、これを記述する場所が根本的に違うのでしょうか？

ここをクリアにしたく、ご意見が欲しいです。

2020-09-02 18:47 UTC, yuki-takei requested changes

2020-09-02 18:47 UTC, yuki-takei commented on src/client/js/components/SlackNotification.jsx
> +  id: PropTypes.string,
`.isRequired` を付ける

2020-09-02 18:47 UTC, yuki-takei commented on src/client/styles/scss/atoms/_custom_control.scss
> +  $color-slack: #4b144c;
この変数がここにあるのはおかしい。ライトモード・ダークモード対応のPRに於いて色の指定は全て theme 側に寄せたはず。このファイルで色の指定をする行は必要ない。

2020-09-03 04:25 UTC, zahmis commented on src/client/js/components/SlackNotification.jsx
> +  id: PropTypes.string,
修正しました。

2020-09-03 04:27 UTC, zahmis commented on src/client/styles/scss/atoms/_custom_control.scss
> +  $color-slack: #4b144c;
Dark Mode のPR をマージしました。
その上で、このファイル上の $color-slack を削除しました。

全ての色の指定を theme に移しました。

2020-09-03 04:28 UTC, zahmis commented on src/client/styles/scss/theme/_apply-colors.scss
> +      }
theme 側に移行しました。

2020-09-03 05:15 UTC, yuki-takei requested changes

2020-09-03 05:15 UTC, yuki-takei commented on src/client/js/components/PageComment/CommentEditor.jsx
> +            {/* TODO コメント機能のとき、Slackボタンが適用しない問題は別タスク(gw 3282 slack button)に回す。Dark Mode 対応を先行する。 */}
このTODOコメントは完了しているなら削除する

2020-09-03 05:17 UTC, zahmis commented on src/client/js/components/PageComment/CommentEditor.jsx
> +            {/* TODO コメント機能のとき、Slackボタンが適用しない問題は別タスク(gw 3282 slack button)に回す。Dark Mode 対応を先行する。 */}
修正します。

2020-09-03 05:24 UTC, merged