Imprv/transplant gw3298
weseek/growi pull request #2705
Opened 2020-08-27 05:36 UTC by makotoshiraishi

2020-08-27 05:47 UTC, makotoshiraishi commented
Timelineのモーダルが表示されるように実装しました。
<img width="1662" alt="スクリーンショット 2020-08-27 14 47 27" src="https://user-images.githubusercontent.com/64956659/91390053-3f0eb400-e874-11ea-893a-351d08d74053.png">

2020-08-27 19:24 UTC, yuki-takei requested changes

2020-08-27 19:24 UTC, yuki-takei commented on src/client/js/components/PageAccessoriesModal.jsx
> +                && <PageTimeline pages={JSON.parse(document.getElementById('page-timeline-data').text)} />
**タスクのゴールを着手前に確認してください**

「API をたたいて取得したタイムライン」とあるので、それを満たさないといけない。

2020-08-31 08:55 UTC, yuki-takei requested changes

2020-08-31 08:55 UTC, yuki-takei commented on src/client/js/components/PageTimeline.jsx
> +    }
async/await を使ってください。

2020-08-31 08:55 UTC, yuki-takei commented on src/client/js/components/PageTimeline.jsx
> +  fromModal: PropTypes.bool,
これなんのための変数なのか理解できない(命名的に)

命名規則に関する文書(開発ガイドとか)を読んで。

2020-09-01 04:11 UTC, makotoshiraishi commented on src/client/js/components/PageTimeline.jsx
> +  fromModal: PropTypes.bool,
ifModalに命名を変更しました！

2020-09-01 04:11 UTC, makotoshiraishi commented on src/client/js/components/PageTimeline.jsx
> +    }
async/awaitでの実装に変更しました。

2020-09-01 04:14 UTC, itizawa commented on src/client/js/components/PageTimeline.jsx
> +    }
isModal は必要ない props なので削除お願いします。

2020-09-01 04:53 UTC, itizawa commented on src/client/js/components/PageTimeline.jsx
>      };
今回のタスクとしてはこれで満たしてはいるのですが、html から react に書き換わることによって
以下のコードが消えます。

src/client/js/components/PageTimeline.jsx の
```js
    this.state = {
      isEnabled: appContainer.getConfig().isEnabledTimeline,

      // TODO: remove after when timeline is implemented with React and inject data with props
      pages: this.props.pages,
    };
```

また state に props の値をセットするのは react のいまいちな使い方なので書いてある箇所は怪しんでください(今回は TODO でメモが残っていた)

2020-09-01 04:53 UTC, itizawa commented on src/client/js/components/PageTimeline.jsx
> +    this.updatePages();
関数の名前が実態とあっていない気がします。
ページを取得するのに update ?

2020-09-01 04:53 UTC, itizawa commented on src/client/js/components/PageTimeline.jsx
>      };
https://youtrack.weseek.co.jp/issue/GW-3702
後続タスクを作成したので着手お願いします

2020-09-01 05:08 UTC, merged