Imprv/add transmission method radio
weseek/growi pull request #2716
Opened 2020-08-31 02:45 UTC by itizawa

2020-08-31 02:49 UTC, itizawa commented
migration と initialize のリファクタは
`GW-3689 mail サービスの初期化を選択したオプションで実行する`
で実施。

```
    // Priority 1. SMTP
    if (configManager.getConfig('crowi', 'mail:smtpHost') && configManager.getConfig('crowi', 'mail:smtpPort')) {
      this.mailer = this.createSMTPClient();
    }
    // Priority 2. SES
    else if (configManager.getConfig('crowi', 'mail:sesAccessKeyId') && configManager.getConfig('crowi', 'mail:sesSecretAccessKey')) {
      this.mailer = this.createSESClient();
    }
```

ここの部分を参考にSMTP設定が埋まっている場合、migration で transmissionMethod を smtp にする

2020-08-31 11:28 UTC, yuki-takei requested changes

2020-08-31 11:28 UTC, yuki-takei commented on src/client/js/components/Admin/App/MailSetting.jsx
> +      },
- 固定値なら state に入れる必要はないのでは？
- 有効な method の ID リストは array にすべき
- ID から表示名へのマッピングは別オブジェクト(or getter or i18next)でやる

2020-08-31 11:39 UTC, yuki-takei commented
smtp or ses 選択UIはもうちょっとわかりやすく

- 現在選択中の方式に関連するプロパティしか変更できないように

2020-09-04 02:50 UTC, itizawa commented
<img width="1149" alt="スクリーンショット 2020-09-04 11 43 15" src="https://user-images.githubusercontent.com/48426654/92194049-b364db00-eea4-11ea-813c-a0c3fb38ed30.png">

<img width="1149" alt="スクリーンショット 2020-09-04 11 43 22" src="https://user-images.githubusercontent.com/48426654/92194065-bc55ac80-eea4-11ea-809d-7e4308dd1e64.png">

別タスクで接続テストボタンが入ります

2020-09-04 09:59 UTC, merged