Imprv/refactor validation for smtp
weseek/growi pull request #2725
Opened 2020-09-01 04:02 UTC by itizawa

2020-09-01 04:10 UTC, itizawa commented on src/server/routes/apiv3/app-settings.js
> +
空文字の時は validation を通して保存させる方針にしたいです。

2020-09-01 09:32 UTC, yuki-takei requested changes

2020-09-01 09:32 UTC, yuki-takei commented on src/server/routes/apiv3/app-settings.js
> +
updateMailSettinConfig しなくなるのでこの戦略はNG

2020-09-02 01:07 UTC, itizawa commented
後続タスクでテストメールを送信するためのボタンを配置

2020-09-02 01:10 UTC, itizawa commented
後続タスクで setup 状態が分かる Label か Badge を表示する

2020-09-02 07:48 UTC, yuki-takei commented
> 後続タスクで setup 状態が分かる Label か Badge を表示する

結構目立った方がいいだろうから alert が適切な気もする。

2020-09-02 07:58 UTC, yuki-takei requested changes

2020-09-02 07:58 UTC, yuki-takei commented on src/server/service/mail.js
> +    this.isMailerSetup = true;
ここでもいいんだけど、false を入れてるのが `initialize` だから、true もそっちで入れた方が読みやすいと思う

2020-09-02 08:48 UTC, merged