Imprv/transplant gw3702
weseek/growi pull request #2737
Opened 2020-09-04 03:11 UTC by makotoshiraishi

2020-09-04 03:18 UTC, makotoshiraishi commented
pageTimelineのisEnabledの記述を全部削除しました。

2020-09-04 09:20 UTC, yuki-takei requested changes

2020-09-04 09:20 UTC, yuki-takei commented on src/client/js/components/PageTimeline.jsx
> +      pages: [],
props.pages を入れなくなったら動かなくなるんじゃない？

もし非同期通信で後からデータを取ってくる仕様に変える途中経過としてこうしているのならその旨を書くべきだし、props.pages も不要になるので消すべき。

2020-09-08 03:34 UTC, makoto15 commented on src/client/js/components/PageTimeline.jsx
> +      pages: [],
記載を元に戻しておきました。
ここの変更はタスクの範疇外であったため、本タスクでは元に戻すように判断しました。
注意深さが足りずに申し訳ありません。気をつけます。

2020-09-08 08:16 UTC, merged