imprv/transplant-gw3727
weseek/growi pull request #2741
Opened 2020-09-04 06:00 UTC by makotoshiraishi

2020-09-04 06:11 UTC, makotoshiraishi commented
Presentation ボタンを移動させました。
また従来の実装ではaタグで`href="?presentation=1"`で情報を送り、かつprevent.default()でURLを変更しないような処理がなされていたが、buttonタグで同様な実装ができなかったため、今回はbuttonタグの中にaタグをいれる形にした。

次のタスクでは、プレゼンテーションの実装をになっている,`crowi.js`ファイルからプレゼンテーションの実装を抜き出して、コンポーネントに刷新しようと考えている。

2020-09-04 06:12 UTC, makotoshiraishi commented
<img width="1310" alt="スクリーンショット 2020-09-04 15 11 16" src="https://user-images.githubusercontent.com/64956659/92205635-13697a80-eec1-11ea-95c2-03c6429674c5.png">

2020-09-04 09:52 UTC, yuki-takei requested changes

2020-09-04 09:52 UTC, yuki-takei commented on src/client/js/components/Page/PageManagement.jsx
> +        </button>
button の中に a タグはイレギュラー過ぎる
className も無理矢理感。

2020-09-08 04:28 UTC, makoto15 commented on src/client/js/components/Page/PageManagement.jsx
> +        </button>
buttonタグで実装するように書き換えました。

2020-09-08 08:29 UTC, merged