apiv3
weseek/growi pull request #2742
Opened 2020-09-04 06:47 UTC by zahmis

2020-09-04 06:50 UTC, zahmis commented on src/server/routes/apiv3/attachments.js
>  const loggerFactory = require('@alias/logger');
endpoint は基本的に複数形が望ましいので、名称を変更しています。

2020-09-04 06:50 UTC, zahmis commented on src/server/routes/apiv3/attachments.js
> +      const pageId = req.query.pageId;
当初 page で渡していたのですが、今後の展開（pagination）を考えたとき、
pageId の方が扱いやすいので変更しています。

2020-09-04 10:00 UTC, yuki-takei requested changes

2020-09-04 10:00 UTC, yuki-takei commented on src/server/routes/apiv3/attachments.js
>  const loggerFactory = require('@alias/logger');
他の route も全部単数形なので、そちらに統一してください。

2020-09-04 10:00 UTC, yuki-takei commented on src/client/js/components/PageAttachment.jsx
> +    await this.props.appContainer.apiv3Get('/attachments/list', { pageId })
async/await と promise が混在しているので、リファクタするなら async/await に統一

2020-09-06 04:22 UTC, zahmis commented on src/server/routes/apiv3/attachments.js
>  const loggerFactory = require('@alias/logger');
承知いたしました。
attachments.js に戻します。

2020-09-06 04:22 UTC, zahmis commented on src/client/js/components/PageAttachment.jsx
> +    await this.props.appContainer.apiv3Get('/attachments/list', { pageId })
async await に統一しました。

2020-09-06 06:25 UTC, zahmis commented on src/server/routes/attachment.js
apiv1 を削除しています。」

2020-09-06 06:25 UTC, zahmis commented on src/client/js/components/PageAttachment.jsx
async await に統一。
promise を削除しています。

2020-09-07 08:04 UTC, merged