gw-3705
weseek/growi pull request #2751
Opened 2020-09-08 03:50 UTC by takeru0001

2020-09-08 03:52 UTC, takeru0001 commented
<img width="1220" alt="スクリーンショット 2020-09-08 12 39 49" src="https://user-images.githubusercontent.com/58085267/92431254-fe972a80-f1d1-11ea-9d9a-4ebf87851321.png">

2020-09-08 03:52 UTC, takeru0001 commented
コンパクトモード
<img width="1222" alt="スクリーンショット 2020-09-08 12 40 04" src="https://user-images.githubusercontent.com/58085267/92431316-2b4b4200-f1d2-11ea-8e8a-37f741d80fc3.png">

2020-09-08 04:31 UTC, takeru0001 commented
bookmarkはログインしていなくても見れて良いという指摘をしていただき変更しました。

2020-09-08 08:21 UTC, yuki-takei requested changes

2020-09-08 08:21 UTC, yuki-takei commented on src/server/routes/apiv3/bookmarks.js
> +  const loginRequired = require('../../middlewares/login-required')(crowi, true);
ここを変えてしまうとこのモジュールで `loginRequired` を使っている全ての route に影響が出てしまう

2020-09-09 13:26 UTC, itizawa commented on src/client/js/components/BookmarkButton.jsx
> +          title="Bookmark"
href と title って必要なんですかね...?

2020-09-09 13:26 UTC, itizawa commented on src/server/routes/apiv3/bookmarks.js
> +  router.get('/countBookmarks', accessTokenParser, loginRequired, async(req, res) => {
route は ケバブケースでお願いします

2020-09-09 13:26 UTC, itizawa commented on src/server/routes/apiv3/bookmarks.js
> +  router.put('/', accessTokenParser, loginRequiredStrictly, csrf, validator.bookmarks, apiV3FormValidator, async(req, res) => {
ゲストユーザーでbookmark 関連試してみた方がいいかも
開発者ツールに表示されるエラーに注視

2020-09-09 13:26 UTC, itizawa commented on src/server/routes/apiv3/bookmarks.js
> +  router.get('/countBookmarks', accessTokenParser, loginRequired, async(req, res) => {
swagger を作成お願いします。

2020-09-09 13:26 UTC, itizawa commented on src/client/js/components/BookmarkButton.jsx
> +      sumOfBookmarks: 0,
これは +α ですが、Suspense を用いることで誤解の少ない画面になります。
今回は実装しなくても良いですが要チェック
https://ja.reactjs.org/docs/concurrent-mode-suspense.html

2020-09-09 13:26 UTC, itizawa commented on src/client/styles/scss/_subnav.scss
> +  }
👍

2020-09-09 13:26 UTC, itizawa commented on src/server/routes/apiv3/bookmarks.js
> +    const { pageId } = req.query;
validation があるとさらに良いですね 👍

2020-09-11 05:08 UTC, takeru0001 commented on src/client/js/components/BookmarkButton.jsx
> +          title="Bookmark"
トップページに遷移する必要がないからいらなかったです！

2020-09-11 05:09 UTC, takeru0001 commented on src/client/js/components/BookmarkButton.jsx
> +      sumOfBookmarks: 0,
了解です。理解しておきます！

2020-09-11 06:23 UTC, takeru0001 commented on src/server/routes/apiv3/bookmarks.js
> +  router.put('/', accessTokenParser, loginRequiredStrictly, csrf, validator.bookmarks, apiV3FormValidator, async(req, res) => {
ブラウザのゲストモードでログインしbookmark数の表示、ボタンを押す、一覧表示など見てみましたが開発者ツールではエラーは出ませんでした

2020-09-15 03:11 UTC, itizawa commented on src/server/routes/apiv3/bookmarks.js
> +    ],
小文字スタートでお願いします。
あとMongoId なので `isMongoId` の方がいいですね(66行目も一緒に修正お願いします)

2020-09-15 04:05 UTC, merged