Imprv/transplant gw3735
weseek/growi pull request #2761
Opened 2020-09-09 05:11 UTC by makotoshiraishi

2020-09-09 08:03 UTC, makotoshiraishi commented
Presentationモーダルを実装するコンポーネントを作成して、crowi.jsの記述を消去しました。
ほとんど見た目上ではcrowi.jsを踏襲した形で実装したのですが、1点だけ違うのが、モーダルの背景がぼやけていない点です。

Modalで背景のカスタマイズがDocumentになく(見落としているかもしれない)、またユーザー視点からもそこまでCriticalな問題ではないと判断したため、この状態でプルリクを送っています。
よろしくお願いします。

2020-09-09 08:03 UTC, makotoshiraishi commented
<img width="1849" alt="スクリーンショット 2020-09-09 16 59 07" src="https://user-images.githubusercontent.com/64956659/92571700-675bd100-f2be-11ea-8ab1-e716e3848363.png">

2020-09-09 08:05 UTC, makotoshiraishi commented
<img width="1887" alt="スクリーンショット 2020-09-09 17 04 03" src="https://user-images.githubusercontent.com/64956659/92571843-996d3300-f2be-11ea-9cef-c34ecbbdbbd5.png">

2020-09-09 08:49 UTC, yuki-takei requested changes

2020-09-09 08:49 UTC, yuki-takei commented on src/client/js/components/PagePresentationModal.jsx
> +  onClose: PropTypes.func.isRequired,
onHoge は required を外してください。その代わり null チェックを行う

2020-09-09 08:49 UTC, yuki-takei commented on src/client/styles/scss/_page-presentation.scss
> +  width: 90vw !important;
* modal に `～page` という名前はセンスがない
* ウィンドウサイズが大きいと余白も大きくなるのでこの手はよくない
    * expand-modal-fullscreen で検索、`_handsontable.scss` を参考に

2020-09-10 04:37 UTC, makotoshiraishi commented on src/client/js/components/PagePresentationModal.jsx
> +  onClose: PropTypes.func.isRequired,
required外して、nullチェックを行うように実装を変更しました。

2020-09-10 04:38 UTC, makotoshiraishi commented on src/client/styles/scss/_page-presentation.scss
> +  width: 90vw !important;
`~modal`という名前に変更しました。
また`@include expand-modal-fullscreen`でscssを書き換えました。

2020-09-10 17:50 UTC, yuki-takei requested changes

2020-09-10 17:50 UTC, yuki-takei commented on src/client/styles/scss/_page-presentation.scss
> +    height: 90vh;
この行要らないのでは？

2020-09-13 23:58 UTC, merged