Imprv/modify design of link edit modal
weseek/growi pull request #2764
Opened 2020-09-09 09:18 UTC by yusuketk

2020-09-16 09:38 UTC, yusuketk commented on src/client/js/models/Linker.js
>    constructor(
本タスクの趣旨とは関係ない修正です

2020-09-16 13:01 UTC, yuki-takei requested changes

2020-09-18 13:03 UTC, yusuketk commented on src/client/js/components/PageEditor/LinkEditModal.jsx
> +                      <Popover placement="right" isOpen={this.state.isPreviewOpen} target="preview-btn" toggle={this.toggleIsPreviewOpen}>
https://youtrack.weseek.co.jp/issue/GW-3871 で対応します

2020-09-18 13:44 UTC, yuki-takei requested changes

2020-09-18 13:44 UTC, yuki-takei commented on src/client/styles/scss/_layout.scss
> +}
このファイルに書くのは相応しくない

2020-09-18 13:44 UTC, yuki-takei commented on src/client/styles/scss/_linkedit-preview.scss
> +    }
最上位が .popover なのはよくない

2020-09-18 13:44 UTC, yuki-takei commented on src/client/styles/scss/_linkedit-preview.scss
> +          width: 200%;
200% という指定もよくない

2020-09-18 13:44 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +}
.card という汎用的なクラスの色を統一的に変えてしまうのであれば、その before/after のスクリーンショットがほしい
(本来的にはこのタスクに先立って別タスクでやるべき)

2020-09-18 13:44 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
.card という汎用的なクラスの色を統一的に変えてしまうのであれば、その before/after のスクリーンショットがほしい
(本来的にはこのタスクに先立って別タスクでやるべき)

2020-09-23 05:15 UTC, yusuketk commented on src/client/styles/scss/_layout.scss
> +}
はじめは btn-page-preview は原子レベルのコンポーネントとして扱うもののcssだと判断し、atomsに入れてました。それが違うということで _layout.scss に移してしまいましたが、btn-page-previewというコンポーネントが「ボタン」と「popover」の複合体であるからmolecules 配下に書くべきということでしょうか

もしくはscss/_linkedit-preview.scss に書くべきだったり、他にsvgアイコンのレイアウトを書くのにふさわしいファイルが有るのでしょうか

2020-09-23 05:39 UTC, yusuketk commented on src/client/styles/scss/_linkedit-preview.scss
> +    }
そうですね...linkedit-preview のscssといっておきながら popover内のそれにしか反映されないものになっていました。修正しました。

2020-09-23 07:07 UTC, yusuketk commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +}
.bg-disabled というクラスは、「中身を変更できなさそう」という印象をもたせる色として今回新しく作りました。
<img width="384" alt="Screen Shot 2020-09-23 at 16 05 07" src="https://user-images.githubusercontent.com/38426468/93978407-ebca4b80-fdb6-11ea-9896-efaca87d3440.png">

2020-09-23 07:10 UTC, yusuketk commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +
.bg-disabled というクラスは、「中身を変更できなさそう」という印象をもたせる色として今回新しく作りました。また、ダークモードの場合にbg-クラスを持たないカードは強制的にbg-darkになるのでbg-という接頭辞をつけています
<img width="384" alt="Screen Shot 2020-09-23 at 16 09 58" src="https://user-images.githubusercontent.com/38426468/93978657-41065d00-fdb7-11ea-9e77-17185a4536af.png">

2020-09-23 07:10 UTC, yusuketk commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
.bg-disabled というクラスは、「中身を変更できなさそう」という印象をもたせる色として今回新しく作りました。また、ダークモードの場合にbg-クラスを持たないカードは強制的にbg-darkになるのでbg-という接頭辞をつけています
<img width="384" alt="Screen Shot 2020-09-23 at 16 09 58" src="https://user-images.githubusercontent.com/38426468/93978691-4ebbe280-fdb7-11ea-999e-9c6b06ced264.png">

2020-09-23 07:27 UTC, yusuketk commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
このように変わります。

- before

<img width="853" alt="Screen Shot 2020-09-23 at 16 21 42" src="https://user-images.githubusercontent.com/38426468/93980377-81ff7100-fdb9-11ea-8910-d22d48f864bd.png">
<img width="1285" alt="Screen Shot 2020-09-23 at 16 12 17" src="https://user-images.githubusercontent.com/38426468/93980404-8b88d900-fdb9-11ea-88a5-58fb3ed26f8e.png">
<img width="855" alt="Screen Shot 2020-09-23 at 16 18 02" src="https://user-images.githubusercontent.com/38426468/93980424-93487d80-fdb9-11ea-92ca-576d03e961d2.png">

- after

<img width="853" alt="Screen Shot 2020-09-23 at 16 21 18" src="https://user-images.githubusercontent.com/38426468/93980458-9e031280-fdb9-11ea-9af2-5720b9b50d96.png">
<img width="1282" alt="Screen Shot 2020-09-23 at 16 22 03" src="https://user-images.githubusercontent.com/38426468/93980478-a52a2080-fdb9-11ea-8de3-b0b979c95d3b.png">
<img width="855" alt="Screen Shot 2020-09-23 at 16 17 15" src="https://user-images.githubusercontent.com/38426468/93980498-ab200180-fdb9-11ea-818e-0a9e96dcb4f5.png">

これらのinput-group のボーダーに合わせています。
<img width="451" alt="Screen Shot 2020-09-23 at 16 24 58" src="https://user-images.githubusercontent.com/38426468/93980339-7449eb80-fdb9-11ea-9773-9f0a469736b0.png">

2020-09-23 09:11 UTC, yusuketk commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +
このようになります。

- before

<img width="344" alt="Screen Shot 2020-09-23 at 17 36 57" src="https://user-images.githubusercontent.com/38426468/93990633-52a33100-fdc6-11ea-92ae-6eea9c19ef23.png">
<img width="344" alt="Screen Shot 2020-09-23 at 17 17 05" src="https://user-images.githubusercontent.com/38426468/93990673-5cc52f80-fdc6-11ea-8ff0-e57dbd009434.png">
<img width="344" alt="Screen Shot 2020-09-23 at 17 06 49" src="https://user-images.githubusercontent.com/38426468/93990691-6353a700-fdc6-11ea-80ab-abd70fb36ad8.png">

- after

<img width="344" alt="Screen Shot 2020-09-23 at 17 35 30" src="https://user-images.githubusercontent.com/38426468/93990707-68185b00-fdc6-11ea-81e0-8e15fb9250cd.png">
<img width="344" alt="Screen Shot 2020-09-23 at 18 00 03" src="https://user-images.githubusercontent.com/38426468/93990903-a4e45200-fdc6-11ea-846f-ba173a5460c1.png">
<img width="344" alt="Screen Shot 2020-09-23 at 17 16 12" src="https://user-images.githubusercontent.com/38426468/93990924-aa419c80-fdc6-11ea-8033-d4869031b38e.png">

header の部分の色調整をしていなかったので追加しました(デザインチェック済み)
また、arrow の部分の色は[GW-3904](https://youtrack.weseek.co.jp/issue/GW-3904)で着手するようにし、レビュー前に書いていた変更は削除しました。

2020-09-24 05:18 UTC, yusuketk commented on src/client/styles/scss/_linkedit-preview.scss
> +          width: 200%;
ページプレビューpopoverの縮小用のタスク([GW-3913](https://youtrack.weseek.co.jp/issue/GW-3913))を作成し、今回はtransformとともに削除しました

2020-09-24 09:31 UTC, yuki-takei requested changes

2020-09-24 09:31 UTC, yuki-takei commented on src/client/styles/scss/molecules/page-preview-btn.scss
> +}
_linkedit-preview に移してください。

2020-09-24 09:31 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +}
border も設定しているので `bg-` prefix はあまり相応しくないような。
`.card-disabled` にしてください。

2020-09-24 09:31 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
border も設定しているので `bg-` prefix はあまり相応しくないような。
`.card-disabled` にしてください。

2020-09-24 09:31 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +}
ファイル内で書く順番気を配ってください。

一番上が bootstrap のスタイルを上書きするもの、
その下に GROWI 特有のクラスを割り当てているもの。

.link-edit-modal は .card 系より下に持っていってほしい。

2020-09-24 10:49 UTC, yusuketk commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +}
なるほど、修正しました。

2020-09-24 10:51 UTC, yusuketk commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
これを回避するためだけにこうしてましたが、優先するのを間違えていました。。
> 強制的にbg-darkになるので

.card-disabledに変更し,上記の件はcssを下記のように変更して対応しました.
```
.card:not([class*='bg-']):not(.well):not(.card-disabled) {
  @extend .bg-dark;
}
```

2020-09-24 10:58 UTC, merged