populate path creator
weseek/growi pull request #2765
Opened 2020-09-09 12:52 UTC by zahmis

2020-09-09 12:54 UTC, zahmis commented
pageAttachmentモーダルで添付ファイル投稿者の画像が認識されない問題を解消しました。
<img width="543" alt="スクリーンショット 2020-09-09 21 46 27" src="https://user-images.githubusercontent.com/57100766/92600809-01377400-f2e7-11ea-9976-4110f6be50d8.png">

2020-09-09 17:29 UTC, zahmis commented
postman で確認したところ、
password や emailを非表示に設定してる user の情報は含まれていませんでした。

2020-09-09 17:29 UTC, zahmis commented
<img width="955" alt="スクリーンショット 2020-09-10 2 27 54" src="https://user-images.githubusercontent.com/57100766/92633230-6ef69680-f30d-11ea-9994-b0eec4e730e3.png">

2020-09-09 19:48 UTC, yuki-takei requested changes

2020-09-09 19:48 UTC, yuki-takei commented on src/server/routes/apiv3/attachment.js
> +          },
User の populate は、`User.USER_PUBLIC_FIELDS` を利用してください。

`routes/apiv3/revisions.js` の `/list` 等が参考になると思う。

2020-09-10 04:30 UTC, zahmis commented on src/server/routes/apiv3/attachment.js
> +          },
author はやはりモデルになく、これで動作するのはおかしいのでやめました。
toObject で不必要なデータを削除するようにしました。

2020-09-10 17:31 UTC, yuki-takei requested changes

2020-09-10 17:31 UTC, yuki-takei commented on src/server/routes/apiv3/attachment.js
> +      });
処理内容はいいとしてちょっと冗長。`paginateResult.docs` は差し替える必要がないので、forEach を使った方が簡単に書ける。

```
paginateResult.docs.forEach((doc) => {
  doc.creator = doc.creator.toObject();
});
```

一方、creator が populate できなかった場合、例えばデータエクスポート→インポートした時に、attachment.creator が参照しているユーザー情報が失われた、または敢えてインポートしなかったような状況を加味して実装した方がいいので、最終的には以下のようなコードが望ましいかな。

```
paginateResult.docs.forEach((doc) => {
  if (doc.creator != null && doc.creator instanceof User) {
    doc.creator = doc.creator.toObject();
  }
});
```

2020-09-11 04:14 UTC, zahmis commented on src/server/routes/apiv3/attachment.js
> +      });
ありがとうございます。
そういつ状況にまで考えが及びませんでした。
上のコードに書き換えています。
一応、情報が秘匿になっていることも確認しました。

2020-09-12 10:39 UTC, merged