gw3815
weseek/growi pull request #2768
Opened 2020-09-10 03:42 UTC by makotoshiraishi

2020-09-10 03:46 UTC, makotoshiraishi commented
プレゼンテーションモーダルが表示されるようにバグ修正しました。
原因はプレゼンテーションモーダルを表示させようとすると、`addRenderVarsForPage関数`が実行され、
`renderVars.page.creator.toObject()`がundefinedになっていたことが原因でした。

そこで、もしrenderVars.page.creatorがmongodbのIDなら上記の関数は実行せず、ユーザ情報が格納されているのなら上記の関数を実行するようにif文で処理を分岐させました。

このバグはmasterにも見られたため、masterにプルリクを送っています。
よろしくお願いします。

2020-09-10 03:47 UTC, makotoshiraishi commented
<img width="1622" alt="スクリーンショット 2020-09-10 12 47 03" src="https://user-images.githubusercontent.com/64956659/92679590-d2131800-f363-11ea-8776-fe02d1b0cb26.png">

2020-09-10 17:22 UTC, yuki-takei requested changes

2020-09-10 17:22 UTC, yuki-takei commented on src/server/routes/page.js
> +    }
creator と revision.author は判定処理から分けてください。

2020-09-11 03:32 UTC, itizawa commented on src/server/routes/page.js
> +    }
revision にページ本文の情報が入っているので
`addRenderVarsForPage` は必要でした。

2020-09-11 03:47 UTC, itizawa commented on src/server/routes/page.js
>      page = await page.populateDataToMakePresentation(revisionId);
今までこれは機能していなかったようだ

2020-09-11 03:49 UTC, itizawa commented on src/server/routes/page.js
> +    }
と、思ったが必要な renderVars だけを追加すれば良いと思った

2020-09-11 06:30 UTC, itizawa commented
fix #2766

2020-09-12 10:31 UTC, merged