Imprv/gw3400 add animation for active tab
weseek/growi pull request #2769
Opened 2020-09-10 05:44 UTC by kaoritokashiki

2020-09-10 18:11 UTC, yuki-takei requested changes

2020-09-10 18:11 UTC, yuki-takei commented on src/client/js/components/PageAccessoriesModal.jsx
> +          <hr id="nav_slide_click" className="my-0"></hr>
この ID は `grw-` prefix を付ける。かつ、suffix が `click` なのは違和感なので、`grw-nav-slide-hr` とかでいいと思う。

2020-09-10 18:11 UTC, yuki-takei commented on src/client/js/components/PageAccessoriesModal.jsx
> +      });
肝心のこの部分は react way で置き換えられる。つまり `switchActiveTab` の中で width, marginLeft の取得と設定処理をやればよいので、`if (menu) {` ブロック丸ごと消せると思う。

2020-09-10 18:11 UTC, yuki-takei commented on src/client/js/components/PageAccessoriesModal.jsx
> +      });
## 現在の実装
- 起動時に `navSlider()` が走ることで、全メニューを走査
  - 各メニューアイテムごとに width と marginLeft の相応しい値を取得し、`callback` で `el.onclick` を設定する

## よりベターな実装
- 各メニューアイテムごとに width と marginLeft の相応しい値を取得し、記録しておく(これは useEffect で dom 描画終了後に毎回やる
- `switchActiveTab` の中で、クリック対象の width と marginLeft の相応しい値を取得し、動的に menuSliderClick に対してスタイルをセットする

2020-09-14 02:52 UTC, kaoritokashiki commented on src/client/styles/scss/_layout_growi.scss
> +    }
`@media screen and (min-width: 768px) {`
こちらの記述のことですね。すみません、必要ないと判断したため削除しました

2020-09-14 02:57 UTC, kaoritokashiki commented on src/client/js/components/PageAccessoriesModal.jsx
> +          <hr id="nav_slide_click" className="my-0"></hr>
確かに、`grw-nav-slide-hr`の方がわかりやすいですね。
`grw-` prefix を付けるのは、cssで入れ子にする時にcontainer(親)の役割をするものにだけつけるという認識でしたが違うのでしょか??

2020-09-14 03:09 UTC, kaoritokashiki commented on src/client/js/components/PageAccessoriesModal.jsx
> +      });
FBありがとうございます。
市澤さんが後続タスクでやっていただくということなので、このタスクでは触れていませんが、私も気になるので、空いている時間にやってみます。

2020-09-14 03:16 UTC, kaoritokashiki commented on src/client/js/components/PageAccessoriesModal.jsx
> +  if (menu) {
DevelopersWikiの開発ガイドに何書かれているかなと探したのですが見つけられず、
他のif文を参考にして`if (menu != null) {`　こういうことにするべきだと判断したのですが、当たっていますでしょうか?

2020-09-14 03:17 UTC, kaoritokashiki commented on src/client/js/components/PageAccessoriesModal.jsx
> +    if (menuSliderClick) {
`if (menuSliderClick != null) {`
同上です。

2020-09-14 09:48 UTC, yuki-takei commented on src/client/js/components/PageAccessoriesModal.jsx
> +          <hr id="nav_slide_click" className="my-0"></hr>
そういう取り決めはないので子で省略しても構わないけど、迷ったら付けた方がいい。
「このクラスは GROWI オリジナル」ということがすぐわかるので。

2020-09-14 09:49 UTC, merged

2020-09-16 02:39 UTC, kaoritokashiki commented on src/client/js/components/PageAccessoriesModal.jsx
> +          <hr id="nav_slide_click" className="my-0"></hr>
そういうことでしたか。理解しました!ありがとうございます。