Feat/gw 3797 setup file uploader
weseek/growi pull request #2770
Opened 2020-09-10 06:31 UTC by itizawa

2020-09-10 06:35 UTC, itizawa commented on src/server/service/file-uploader/index.js
> +      // TODO others
方向性が合っていれば タスクを作成し、aws や gcs を実装します

2020-09-10 17:16 UTC, yuki-takei requested changes

2020-09-10 17:16 UTC, yuki-takei commented on src/server/service/file-uploader/index.js
> +      // TODO others
interface がないので分かりづらいんだけど、

`class Gridfs implements FileUploadService`

という考え方の方にしよう。そして `crowi.fileUploadService` は FileUploadService 実装(つまり Gridfs インスタンスとか)のままにすると、上の方で書き換えている

`crowi.fileUploadService.fileUploader.getIsUploadable()`

は、

`crowi.fileUploadService.getIsUploadable()`

のままでよい。

2020-09-10 17:16 UTC, yuki-takei commented on src/server/service/file-uploader/index.js
> +      // TODO others
一方この `file-uploader/index.js` は何かというと、飽くまでも Factory パターンでいいとおもうが、ただしクラス化は賛成で

`class FileUploadServiceFactory extends S2sMessagingServiceDelegator` とした上で、

https://github.com/weseek/growi/blob/4264d562ac6641aa20311cd422d92072263a70e2/src/server/crowi/index.js#L523-L526

の処理が必要。それから一旦 approve したけど

https://github.com/weseek/growi/pull/2750/files#diff-ff30bda87e73da80c9035d0eccc284d5R561

は、第二引数の `true` はあった方がいいね。そこの処理は 

https://github.com/weseek/growi/blob/4264d562ac6641aa20311cd422d92072263a70e2/src/server/routes/apiv3/customize-setting.js#L378-L379

を参考に。

2020-09-25 09:58 UTC, yuki-takei requested changes

2020-09-25 09:58 UTC, yuki-takei commented on src/server/service/file-uploader/uploader.js
> +class Uploader extends S2sMessageHandlable {
S2sMessageHandlable の実装は、FileUploadServiceFactory も Uploader もしっくりこないので、新たに作ろう。

2020-09-28 04:26 UTC, merged