Imprv/reactify subnavbar
weseek/growi pull request #2771
Opened 2020-09-10 06:59 UTC by ryuichi-e

2020-09-10 07:06 UTC, ryuichi-e commented
このタスクでは、edit画面、hackmd画面のsubnavbarをviewの時と同じにしました。

2020-09-10 18:22 UTC, yuki-takei requested changes

2020-09-10 18:22 UTC, yuki-takei commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +      >
このファイルはいじらない。

- 必要な処理は NavigationContainer でやる
- view モードの場合は `#` は消す

2020-09-10 18:22 UTC, yuki-takei commented on src/client/js/app.jsx
> -    'page-editor-path-nav': <PagePathNavForEditor />,
PagePathNavForEditor コンポーネントは不要になると思うので、ファイルも消してください。

2020-09-10 18:22 UTC, yuki-takei commented on src/server/views/layout-growi/base/layout.html
> +<div id="grw-subnav-switcher-container"></div>
こっちは d-edit-none でいいんじゃない？

2020-09-18 06:26 UTC, itizawa commented on src/client/js/components/Page/TagLabels.jsx
> +    if (editorContainer.state.pageId != null) {
新規ページ作成時には pageId の有無で切り替えようかと

2020-09-18 06:29 UTC, itizawa commented on src/client/js/components/Page/TagLabels.jsx
>        await appContainer.apiPost('/tags.update', { pageId, tags });
今までの微妙な挙動(editor でタグを更新したけど view に反映されていない。)が改善されました

2020-09-18 07:12 UTC, yuki-takei requested changes

2020-09-18 07:12 UTC, yuki-takei commented on src/server/views/widget/page_tabs.html
> +<ul class="nav nav-tabs d-print-none d-none" role="tablist">
このファイル残す意味ある？

2020-09-18 07:12 UTC, yuki-takei commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +    navigationContainer.setEditorMode(viewType);
この処理はやるなら onThreeStrandedButtonClicked の中が望ましい。
つまり、NavigationContainer の DI は不要だと思う。

2020-09-18 07:34 UTC, merged