Change position bookmark and recently created button
weseek/growi pull request #2772
Opened 2020-09-10 13:52 UTC by zahmis

2020-09-10 15:24 UTC, zahmis commented
<img width="335" alt="スクリーンショット 2020-09-10 23 00 46" src="https://user-images.githubusercontent.com/57100766/92753716-1da9de00-f3c5-11ea-94a4-28084574f9a9.png">

<img width="345" alt="スクリーンショット 2020-09-10 22 55 48" src="https://user-images.githubusercontent.com/57100766/92753701-1b478400-f3c5-11ea-913b-de50c73bd490.png">

2020-09-10 15:27 UTC, zahmis commented
間隔を徐々に狭めていくと、1620px 縮小する問題が発生しました。
<img width="243" alt="スクリーンショット 2020-09-10 23 01 05" src="https://user-images.githubusercontent.com/57100766/92753957-5ba70200-f3c5-11ea-80af-a78e4c1f8bda.png">

2020-09-10 15:59 UTC, zahmis commented on src/client/styles/scss/_layout_growi.scss
> +    min-width: 260px;
レイアウトが崩れるので、ここを一旦 260px にしています。

2020-09-10 16:22 UTC, zahmis commented
修正した結果
右の TOC が消滅する直前までこの状態で遷移します。
![スクリーンショット 2020-09-11 0 54 42](https://user-images.githubusercontent.com/57100766/92762114-3e763180-f3cd-11ea-8535-ea8daeeeb9b7.png)

2020-09-10 18:28 UTC, yuki-takei requested changes

2020-09-10 18:28 UTC, yuki-takei commented on src/client/js/components/TableOfContents.jsx
> +          <i className="recently-created mr-2"><RecentlyCreatedIcon /></i>
クラス名は `grw-icon-container-recently-created` にする

2020-09-10 18:28 UTC, yuki-takei commented on src/client/styles/scss/_toc.scss
> +}
`.recently-created` は `grw-icon-container-recently-created` に変更し、それごとどこか上位のクラスの配下に入れてください。

2020-09-11 03:07 UTC, zahmis commented on src/client/js/components/TableOfContents.jsx
> +          <i className="grw-icon-container-recently-created mr-2"><RecentlyCreatedIcon /></i>
className を変更しています。

2020-09-11 03:07 UTC, zahmis commented on src/client/styles/scss/_toc.scss
> +
上位のクラスに隷属させました。
上位のクラスは、.revision-toc にしています。

2020-09-11 03:15 UTC, merged