add skips counts' message when it's completed
weseek/growi pull request #2786
Opened 2020-09-15 07:42 UTC by kaoritokashiki

2020-09-15 14:01 UTC, kaoritokashiki commented
<img width="548" alt="スクリーンショット 0002-09-15 23 00 26" src="https://user-images.githubusercontent.com/59536731/93220320-4eb05700-f7a7-11ea-8464-e2de20eb14d2.png">
<img width="470" alt="スクリーンショット 0002-09-15 22 43 49" src="https://user-images.githubusercontent.com/59536731/93220324-507a1a80-f7a7-11ea-9633-21df2c13a694.png">
<img width="440" alt="スクリーンショット 0002-09-15 22 42 35" src="https://user-images.githubusercontent.com/59536731/93220330-51ab4780-f7a7-11ea-9601-369301d35fb8.png">

2020-09-16 10:02 UTC, yuki-takei requested changes

2020-09-16 10:02 UTC, yuki-takei commented on src/client/js/components/Admin/ElasticsearchManagement/RebuildIndexControls.jsx
> +    }
ここは三項演算子使ってよかったのでは。

2020-09-16 10:17 UTC, kaoritokashiki commented on src/client/js/components/Admin/ElasticsearchManagement/RebuildIndexControls.jsx
> +    }
三項演算子に修正しました。

2020-09-16 10:19 UTC, merged