Imprv/editmode slack button responsive
weseek/growi pull request #2787
Opened 2020-09-15 07:44 UTC by sacrrie

2020-09-15 08:50 UTC, yuki-takei commented
before/after のスクリーンショットを載せてください。

2020-09-15 08:50 UTC, yuki-takei requested changes

2020-09-15 08:50 UTC, yuki-takei commented on src/client/js/components/SavePageControls.jsx
> +          }
インデントがおかしいので直す

2020-09-15 08:50 UTC, yuki-takei commented on src/client/js/components/SavePageControls.jsx
> +          }
こちらもインデントしか変わっていないので元に戻す

2020-09-15 09:25 UTC, sacrrie commented
On Desktop:
![image](https://user-images.githubusercontent.com/17376080/93192340-87890580-f780-11ea-92d6-856e20b7378e.png)
On Smartphone:
![image](https://user-images.githubusercontent.com/17376080/93192449-a9828800-f780-11ea-9cb0-40db132f24ee.png)
and if the user clicked:
![image](https://user-images.githubusercontent.com/17376080/93192559-c1f2a280-f780-11ea-8ead-622560350172.png)

2020-09-15 09:39 UTC, yuki-takei requested changes

2020-09-15 09:39 UTC, yuki-takei commented on src/client/js/components/PageEditor/EditorNavbarBottom.jsx
> +        </Collapse>
SavePageControls に slackOnly モードは不要、
Collapse の中には SlackNotification のみを表示すれば良い

2020-09-15 09:39 UTC, yuki-takei commented on src/client/js/components/SlackNotification.jsx
> +    );
smallScreen 時に表示したいコンポーネントは、EditorNavbarBottom.jsx 内部に実装してください。

2020-09-16 10:30 UTC, yuki-takei requested changes

2020-09-16 10:30 UTC, yuki-takei commented on src/client/js/components/PageEditor/EditorNavbarBottom.jsx
> +                id="idForSavePageControl"
id が被ってると後々バグの元になるかもしれないので、別のものにしてください。

2020-09-16 10:30 UTC, yuki-takei commented on src/client/js/components/SlackNotification.jsx
> +        <div className="grw-navbar-bottom-slack input-group extended-setting">
命名があまりよくない。`grw-input-group-slack-notification` にしてください。

2020-09-16 10:30 UTC, yuki-takei commented on src/client/js/components/SlackNotification.jsx
> +            className="grw-navbar-bottom-slack form-control align-top"
命名があまりよくない。`grw-form-control-slack-notification` にしてください。

2020-09-16 10:30 UTC, yuki-takei commented on src/client/styles/scss/molecules/slack-notification.scss
> +    height: 24px;
$input-height-slack は使わないの？

2020-09-18 07:08 UTC, yuki-takei requested changes

2020-09-18 07:08 UTC, yuki-takei commented on src/client/js/components/PageEditor/EditorNavbarBottom.jsx
> +              id="idForSlackNotification"
https://github.com/weseek/growi/pull/2787#discussion_r489331574
このFBが直ってない

2020-09-18 07:08 UTC, yuki-takei commented on src/client/js/components/PageEditor/EditorNavbarBottom.jsx
> +          <nav className={`navbar navbar-expand-lg border-top ${additionalClasses.join(' ')}`}>
nav 要素は消して、独自のクラスを割り当てて適切な見た目になるようにしてください。
GrowiNavbarBottom を参考に。

2020-09-23 08:37 UTC, sacrrie commented on src/client/js/components/PageEditor/EditorNavbarBottom.jsx
> +          <nav className={`navbar navbar-expand-lg border-top ${additionalClasses.join(' ')}`}>
すみませんでした、これは前debugした時残したものです、今改正しました。

2020-09-23 09:42 UTC, yuki-takei requested changes

2020-09-23 09:42 UTC, yuki-takei commented on src/client/js/components/PageEditor/EditorNavbarBottom.jsx
> +              id="idForEditorNavbarBottom"
ここまだ直ってない。

同じ ID の DOM が同時に存在しないように、103行目とは別の ID 文字列を設定してください。

2020-09-23 09:42 UTC, yuki-takei commented on src/client/js/components/PageEditor/EditorNavbarBottom.jsx
> +                id="idForEditorNavbarBottom"
ここまだ直ってない。

同じ ID の DOM が同時に存在しないように、72行目とは別の ID 文字列を設定してください。

2020-09-23 10:26 UTC, merged