Design fix pagination position
weseek/growi pull request #2789
Opened 2020-09-15 17:26 UTC by zahmis

2020-09-15 17:35 UTC, zahmis commented
pagination を中央寄せしました。
<img width="1175" alt="スクリーンショット 2020-09-16 2 34 35" src="https://user-images.githubusercontent.com/57100766/93244843-52eb6d00-f7c5-11ea-837d-c678c9ec9dfa.png">
<img width="1176" alt="スクリーンショット 2020-09-16 2 34 41" src="https://user-images.githubusercontent.com/57100766/93244857-567ef400-f7c5-11ea-9e00-927c14926e2d.png">
![Uploading スクリーンショット 2020-09-16 2.34.48.png…]()

2020-09-16 10:05 UTC, yuki-takei requested changes

2020-09-16 10:05 UTC, yuki-takei commented on src/client/js/components/PageAttachment.jsx
> +        <div className="my-3 d-flex justify-content-center">
ここじゃなくて親の div に`justify-content-center` とか付けるんじゃないかな。
子が PaginationWrapper 1つしかないのに d-flex 付けるのがなんか違和感

2020-09-16 10:05 UTC, yuki-takei commented on src/client/js/components/PageHistory.jsx
> +      <div className="my-3 d-flex justify-content-center">
違和感

2020-09-16 10:05 UTC, yuki-takei commented on src/client/js/components/PageList.jsx
> +      <div className="my-3 d-flex justify-content-center">
違和感

2020-09-16 10:05 UTC, yuki-takei commented on src/client/js/components/PageTimeline.jsx
> +        <div className="my-3 d-flex justify-content-center">
違和感

2020-09-17 05:40 UTC, zahmis commented on src/client/js/components/PageAttachment.jsx
>      return (
親に colunm と align-items-center を適用させています。
その結果として、子供の幅を保たせる必要が出てきたので div を使用しています。

2020-09-17 05:43 UTC, zahmis commented
pageList では 「ul クラスにスタイルを適用させる必要があったため、クラス名を指定している。」
と認識しました。
今回、他のモーダルでは特にデザインの指定はなく、
特に違和感もないので、クラス名を付けていません。
これが、いいか悪いかは判断できなかったので、
余計なコードは書かないという判断で進めました。
これについてご意見をいただきたいです。

2020-09-17 05:53 UTC, zahmis commented
<img width="1053" alt="スクリーンショット 2020-09-17 14 05 51" src="https://user-images.githubusercontent.com/57100766/93425743-92b17200-f8f5-11ea-932a-098806acf219.png">
<img width="1087" alt="スクリーンショット 2020-09-17 14 06 00" src="https://user-images.githubusercontent.com/57100766/93425746-947b3580-f8f5-11ea-88b1-0a1ad2e7156d.png">
<img width="1278" alt="スクリーンショット 2020-09-17 14 06 16" src="https://user-images.githubusercontent.com/57100766/93425749-947b3580-f8f5-11ea-8bf0-66cd6d02a1c9.png">

2020-09-17 06:00 UTC, zahmis commented on src/client/js/components/PageAttachment.jsx
> +        <div className="my-3 d-flex justify-content-center">
親に対して、colunm とalign-items-center を適用させました。

この横幅が full ではなかったので、 w-100 で横幅をとっています。
また、これに付随して、
コンポーネントではclassName が指定できないので,
そこに関しては div を使用しています。

このネストがよくない場合、 
そのコンポーネントでclassName を指定する必要が出てきそうなのですが、
どうするのがベストなのでしょうか？

2020-09-17 06:02 UTC, zahmis commented on src/client/js/components/PageAttachment.jsx
> +        <div className="w-100">
この部分は 子供1に w-100 を適用させたいので、div を使用しています。

2020-09-17 06:02 UTC, zahmis commented on src/client/js/components/PageHistory.jsx
> +      <div className="mt-4 w-100">
この部分は 子供1に w-100 を適用させたいので、div を使用しています。

2020-09-17 06:02 UTC, zahmis commented on src/client/js/components/PageTimeline.jsx
> +        <div className="w-100">
この部分は 子供1に w-100 を適用させたいので、div を使用しています。

2020-09-17 09:53 UTC, yuki-takei commented
PaginationWrapper の align props を指定してください。結果的に親に align-items-center を…という戦略がベストではなかったのは申し訳ない。

2020-09-17 09:54 UTC, yuki-takei commented
オレが書いたコードを参考に、全ての PaginationWrapper 利用部分で align を使う用に変更してください。
UserManagement.jsx で pull-write を使っている部分もこれを機に修正する。

2020-09-17 10:38 UTC, zahmis commented
align を適用しました。

2020-09-17 13:49 UTC, zahmis commented on src/client/js/components/Admin/Security/ShareLinkSetting.jsx
> +            disabled={adminGeneralSecurityContainer.state.shareLinks.length === 0}
押木さんと市澤さんに相談した結果、この部分は、デザイン統制をしています。
本来「ここに全てのリンクを削除します」が存在していました。
なので、それを常に表示させ、
リンクが存在しない時は、disabled にしています。

2020-09-17 13:49 UTC, zahmis commented on src/client/js/components/Admin/Security/ShareLinkSetting.jsx
> +
const pager に<> を代入すると条件式が適用できないので、function化しました。
共有リンクが存在しないときは、pagination を非表示にしています。

2020-09-17 13:49 UTC, zahmis commented on src/client/js/components/Admin/Security/ShareLinkSetting.jsx
> +
shareLinks が存在する時はそれらを表示し、
存在しないときは、本来右上に表示していた「共有リンクが存在しません」を表示するようにしました。中央揃えにしています。

2020-09-17 13:50 UTC, zahmis commented
<img width="1507" alt="スクリーンショット 2020-09-17 22 40 06" src="https://user-images.githubusercontent.com/57100766/93480178-1f7d1f80-f938-11ea-8bcc-3e2d07f60fb6.png">

2020-09-17 14:07 UTC, zahmis commented on src/client/js/components/Admin/Security/ShareLinkSetting.jsx
> +    const {
変数が長いのでリファクタリングしています。

2020-09-18 06:56 UTC, yuki-takei requested changes

2020-09-18 06:56 UTC, yuki-takei commented on src/client/js/components/Admin/ManageExternalAccount.jsx
> +      <div>
この div いらないと思う

2020-09-18 07:08 UTC, merged