Feat/gw 3842 adjust modalheader margin
weseek/growi pull request #2791
Opened 2020-09-16 07:01 UTC by oshikishintaro

# GW-3842 デザイン修正：ヘッダー(nav-title)の表示を修正

# 実装画面
※ボディ部分の見た目は後続タスクで調整。
![image](https://user-images.githubusercontent.com/65531771/93302679-57e80500-f835-11ea-86c3-de5335382bf9.png)
- ヘッダーは左右にマージンを設けず、画面端まで使用して表示
- tabタイトルの上下のアキを、上下1.5rem , 左右1rem に
- nav-slide-hrの太さを3pxに
- border-bottomを追加
- 閉じるボタンを追加

# デザイン
![image](https://user-images.githubusercontent.com/65531771/93302885-9978b000-f835-11ea-89db-f23cbdd95ada.png)
![image](https://user-images.githubusercontent.com/65531771/93302913-a2698180-f835-11ea-85fb-6eeb9bdcf142.png)

2020-09-16 10:23 UTC, yuki-takei requested changes

2020-09-16 10:23 UTC, yuki-takei commented on src/client/styles/scss/_layout_growi.scss
> +      padding: 0rem;
これは削除する。padding を詰める必要な場合はコンテンツ側でユーティリティクラスを付けるなどすればよい。

2020-09-16 10:23 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +    border-bottom: 3px solid $color-link;
border の太さやタイプは theme から外す。
このファイルでは基本的に指定するのは色のみ。

2020-09-16 10:23 UTC, yuki-takei commented on src/client/styles/scss/_layout_growi.scss
> +    }
このファイルで書いてる内容、`_page_accessaries_modal.scss` に移すべきではないか。二重管理になってる気がする。

2020-09-17 04:03 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors.scss
> +    border-bottom: 3px solid $color-link;
太さやタイプの指定を`_page_accessaries_modal.scss`に移動しました

2020-09-17 04:06 UTC, oshikishintaro commented on src/client/styles/scss/_layout_growi.scss
> +      padding: 0rem;
`PageAccessoriesModal.jsx`内、モーダルボディに`p-0`を追加し、この記述を削除しました

2020-09-17 04:06 UTC, oshikishintaro commented on src/client/styles/scss/_layout_growi.scss
> +    }
`_layout_growi.scss` 内の `.grw-page-accessories-modal {`以下の内容を
`_page_accessaries_modal.scss`に移動しました

2020-09-17 08:25 UTC, yuki-takei requested changes

2020-09-17 08:25 UTC, yuki-takei commented on src/client/styles/scss/_page_accessaries_modal.scss
> +  #grw-nav-slide-hr {
クラスで実装して。id は実装上必要なのであればそのまま存在していてよい。

2020-09-17 11:02 UTC, oshikishintaro commented on src/client/styles/scss/_page_accessaries_modal.scss
> +  #grw-nav-slide-hr {
可能な範囲で、スタイル指定をクラスに書き換えました。

2020-09-18 07:32 UTC, yuki-takei requested changes

2020-09-18 07:32 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +    border-color: $color-link;
クラスに対して指定して

2020-09-18 07:32 UTC, yuki-takei commented on src/client/styles/scss/_page_accessaries_modal.scss
> +  #grw-nav-slide-hr {
クラスに対して指定して

2020-09-18 11:33 UTC, oshikishintaro commented on src/client/styles/scss/_page_accessaries_modal.scss
> +  #grw-nav-slide-hr {
id `grw-nav-slide-hr`は使っている箇所が見当たらなかったため削除。
クラス`grw-nav-slide-hr`を新規作成し、スタイルシートも合わせて書き換えました。

2020-09-18 11:33 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors.scss
> +    border-color: $color-link;
こちらもidを削除、クラスに書き換えました。

2020-09-18 12:24 UTC, merged