Imprv/gw3843 add scrol on each modal body
weseek/growi pull request #2792
Opened 2020-09-16 07:04 UTC by kaoritokashiki

2020-09-16 07:18 UTC, kaoritokashiki commented
[ページリスト]
[タイムライン]
[更新履歴]
[添付データ]
[共有リンク管理]

2020-09-16 07:30 UTC, kaoritokashiki commented on src/client/styles/scss/_page_accessaries_modal.scss
> +    position: static;
<img width="89" alt="スクリーンショット 0002-09-16 16 29 52" src="https://user-images.githubusercontent.com/59536731/93305743-e65e8580-f839-11ea-9e35-edf2aef0b9e0.png">
<img width="127" alt="スクリーンショット 0002-09-16 16 29 59" src="https://user-images.githubusercontent.com/59536731/93305744-e78fb280-f839-11ea-84f2-a0af4dedfdfb.png">

2020-09-16 07:35 UTC, kaoritokashiki commented on src/client/styles/scss/_page_accessaries_modal.scss
> +  }
<img width="89" alt="スクリーンショット 0002-09-16 16 29 52" src="https://user-images.githubusercontent.com/59536731/93306276-98964d00-f83a-11ea-9a07-566555765358.png">
<img width="127" alt="スクリーンショット 0002-09-16 16 29 59" src="https://user-images.githubusercontent.com/59536731/93306283-99c77a00-f83a-11ea-8b6e-cf9c2562799b.png">

2020-09-16 10:49 UTC, yuki-takei requested changes

2020-09-16 10:49 UTC, yuki-takei commented on src/client/styles/scss/_page_accessaries_modal.scss
> +  }
なんとなくトリッキーな解っぽくてやだなあ

2020-09-16 10:49 UTC, yuki-takei commented on src/client/styles/scss/_page_accessaries_modal.scss
> +  }
`d2h-code-side-linenumber` に関しては要リサーチ

2020-09-17 10:05 UTC, kaoritokashiki commented on src/client/js/components/PageAccessoriesModal.jsx
> +        <ModalBody className="overflow-auto grw-modal-body-style">
後続タスクをGW-3890 モーダル内部のリファクタを作成しました

2020-09-17 10:30 UTC, yuki-takei requested changes

2020-09-17 10:30 UTC, yuki-takei commented on src/client/styles/scss/_page_accessaries_modal.scss
> +    max-height: 80vh;
80という割合じゃなくて、 `calc(100vh - XXXpx)` みたいな感じにして。`@mixin expand-editor` で同じようなテクニックを使っている。

2020-09-17 13:24 UTC, kaoritokashiki commented on src/client/styles/scss/_page_accessaries_modal.scss
> +  }
calcを使用し、修正しました。

2020-09-17 13:28 UTC, merged