gw-3777
weseek/growi pull request #2799
Opened 2020-09-17 05:13 UTC by takeru0001

2020-09-17 07:57 UTC, yuki-takei requested changes

2020-09-17 07:57 UTC, yuki-takei commented on src/client/js/components/BookmarkButton.jsx
> +      }
このロジックって、API から返ってきた数にできない？
このままだとDBの実際の値と乖離が出る。

2020-09-18 03:48 UTC, takeru0001 commented on src/client/js/components/BookmarkButton.jsx
> +      }
handleClick内でgetのbookmarks APIでsumOfBookmarksを取得するようにしました。
likeの方も同じロジックなのですが、直したほうがよろしいでしょうか?

2020-09-18 03:50 UTC, takeru0001 commented on src/client/js/components/BookmarkButton.jsx
> +      }
また、自分がbookmarkしていないときにsumOfBookmarksが表示されないことにしてしまっていたので、改善いたしました。

2020-09-18 07:01 UTC, yuki-takei requested changes

2020-09-18 07:01 UTC, yuki-takei commented on src/client/js/services/PageContainer.js
> +    const bookmark = await this.appContainer.apiv3Get('/bookmarks', { pageId: this.state.pageId });
一次変数の名前がいけてないのはこちらも同様なのだが、この通信してからの setState のフロー、メソッドに切り出して、BookmarkButton.jsx からもそのメソッドを呼んで欲しい。

2020-09-18 07:58 UTC, yuki-takei requested changes

2020-09-18 07:58 UTC, yuki-takei commented on src/client/js/services/PageContainer.js
> +  async setBookmarkInfo() {
retrieveBookmarkInfo

2020-09-25 09:50 UTC, yuki-takei requested changes

2020-09-25 09:50 UTC, yuki-takei commented on src/client/js/services/PageContainer.js
> +    }
もっと完結に。

```
const { isBookmarked } = response.data;
if (isBookmarked != null) {
  this.setState({ isBookmarked });
}
```
`this.setState({ isBookmarked:

2020-09-25 09:50 UTC, yuki-takei commented on src/client/js/services/PageContainer.js
> +    const bool = !this.state.isBookmarked;
名前を `toggleBookmark` にしてください。

別の解として、bool をこのメソッドの引数で取るようにするという選択肢もある。その場合は `update...` でもよさそう。

2020-09-25 09:50 UTC, yuki-takei commented on src/client/js/services/PageContainer.js
> +    this.retrieveBookmarkInfo();
promise を返すために `return this.retrieveBookmarkInfo();` としてください。

2020-09-29 03:58 UTC, takeru0001 commented on src/client/js/services/PageContainer.js
> +    const bool = !this.state.isBookmarked;
変更しました。

2020-09-29 03:58 UTC, takeru0001 commented on src/client/js/services/PageContainer.js
> +    this.retrieveBookmarkInfo();
変更しました。

2020-09-29 04:16 UTC, takeru0001 commented on src/client/js/services/PageContainer.js
> +    }
念のため確認させてください。
命名が悪いと思うのですが、responseのisBookmarkedはbooleanではなくbookmarkの情報がオブジェクトで入っており、PageContainerのisBookmarkedはbooleanで管理しようと思っているのですが
`const { isBookmarked } = response.data;
if (isBookmarked != null) {
  this.setState({ isBookmarked });
}`
と書くべきですか?
stateのisBookmarkedにboolean以外をセットしてよいのかの確認です。

2020-09-29 07:41 UTC, yuki-takei requested changes

2020-09-29 07:41 UTC, yuki-takei commented on src/client/js/services/PageContainer.js
> +    }
is で始まるものは boolean のみにすべき

2020-10-01 03:37 UTC, merged