Imprv/gw3790 show alert when the version different
weseek/growi pull request #2807
Opened 2020-09-23 13:20 UTC by kaoritokashiki

2020-09-23 13:25 UTC, kaoritokashiki commented on src/server/routes/apiv3/import.js
> +      }
インポート時のvalidation(画面右上に出てくる赤いエラー)とは別に、アップデート時のvalidationを加えました。
両者の違いは、returnする内容です。

2020-09-23 13:26 UTC, kaoritokashiki commented on src/client/js/components/Admin/ImportData/GrowiArchiveSection.jsx
> +      isTheSameVersion: true,
isTheSameVersionを初期値でtrueにしておき、アップデートをした際に、validateをしてversionが違ったらfalseにするという実装をしようとしています。

2020-09-23 13:29 UTC, kaoritokashiki commented on src/client/js/components/Admin/ImportData/GrowiArchiveSection.jsx
> +            {isTheSameVersion === false && this.renderDefferentVersionAlert()}
`isTheSameVersion`がtrueだったらalert(warning)を表示しない。falseだったら表示するというような感じです。

2020-09-23 13:36 UTC, kaoritokashiki commented
[理想] うまくstateが切り替わればこういうふうにアラートが表示されます。
<img width="890" alt="スクリーンショット 0002-09-23 15 04 56" src="https://user-images.githubusercontent.com/59536731/94019773-2058fa00-fded-11ea-9a2b-29848611a680.png">

2020-09-23 13:42 UTC, kaoritokashiki commented on src/server/service/import.js
> +
インポート時のvalidation(画面右上に出てくる赤いエラー)とは別に、アップデート時のvalidationを加えました。
両者の違いは、returnする内容です。
もしversionが違ったら、その情報をフロント側にも伝えて、state(`isTheVersionSame`)の値を変更したいと考えているのですが、ここでどういうふうに書けばいいか詰まっています。

2020-09-23 13:46 UTC, kaoritokashiki commented on src/server/routes/apiv3/import.js
> +      }
もしversionが違ったら、その情報をフロント側にも伝えて、state(`isTheSameVersion`)の値を変更したいと考えているのですが、ここでどういうふうに書けばいいか詰まっています。
やりたいことは、dataの取得と、versionErrorの有無の情報の保持

2020-09-24 07:51 UTC, yuki-takei requested changes

2020-09-24 07:51 UTC, yuki-takei commented on src/client/js/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
> +    const { data } = await this.props.appContainer.apiv3Post('/import/upload', formData); // ここにアップロードしたデータが渡ってきている
コード内コメントも、テンポラリなものだったとしても英語に統一してほしい

2020-09-24 07:51 UTC, yuki-takei commented on src/server/routes/apiv3/import.js
> +      }
サーバーサイドで新しいメソッドを作るのではなく、例外処理時の error の種類を増やすことで、クライアントサイドでのハンドリングのバリエーションを増やす

2020-09-24 09:59 UTC, kaoritokashiki commented
参考に
<img width="936" alt="スクリーンショット 0002-09-24 18 59 03" src="https://user-images.githubusercontent.com/59536731/94130762-0b857080-fe98-11ea-8376-c7e7babdb791.png">

2020-09-25 07:15 UTC, kaoritokashiki commented on src/client/js/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
> +    const { data } = await this.props.appContainer.apiv3Post('/import/upload', formData); // ここにアップロードしたデータが渡ってきている
失礼しました。了解です。

2020-09-29 05:05 UTC, kaoritokashiki commented
すみません、現状まだ完全にはこのタスクのゴールを満たしていませんが再度FBお願いします。

同じバージョンのファイルをアップデートした時に、isTheSameVersionがtrueに置き換わらず、nullのままでcollectionsが表示されません。
リロードしたらアラートなしで正常に表示されます。
```
    try {
      const { data } = await this.props.appContainer.apiv3Post('/import/upload', formData);
      // TODO: toastSuccess, toastError
      this.props.onUpload(data);
    }
    catch (err) {
      if (err[0].code === 'versions-are-not-met') {
        this.props.onCheckVersion(err[0].code);
      }
    }
```
この例外処理の`this.props.onUpload(data);`の前に
1. `this.props.onCheckVersion(xxx);`で値を渡す
2. 渡ってきたデータをもとにGrowiArchiveSection fileでsetstateする
をしようとしましたが、そもそも`onCheckVersion`が実行されていないでした。


まだ完全にはこのタスクのゴールを満たしていませんが、結構時間をかけてしまったので、一旦PRを出そうと思います。

2020-09-29 07:45 UTC, yuki-takei requested changes

2020-09-29 07:45 UTC, yuki-takei commented on .devcontainer/docker-compose.yml
> +    image: mongo:4.4
これは元に戻して。master をマージしていたらこの差分は出ないはず。

2020-09-29 07:48 UTC, yuki-takei requested changes

2020-09-29 07:48 UTC, yuki-takei commented on src/client/js/components/Admin/ImportData/GrowiArchiveSection.jsx
> +  }) {
handleUpload 時にも isTheSameVersion を更新しないとじゃない？

2020-09-29 12:08 UTC, kaoritokashiki commented on .devcontainer/docker-compose.yml
> +    image: mongo:4.4
masterをマージして差分を消しました。

2020-09-29 14:22 UTC, kaoritokashiki commented on src/server/routes/apiv3/import.js
> -      return res.apiv3(data);
このreturn文を間違えて消してしまっていたことによって、dataがクライアントに渡ってきておらずfile nameやinnnerFileStatus がnullの状態のままだったことが問題でした。これを復活させることにより、アップロードした時にちゃんとdataが入ってくるようになっています。

2020-09-29 14:25 UTC, kaoritokashiki commented on src/client/js/components/Admin/ImportData/GrowiArchiveSection.jsx
> +      isTheSameVersion: true,
isTheSameVersionをtrueにすることによって、同じバージョンのファイルがアップロードされた時にstateが切り替わり、collectionsが表示されるようにしました。

2020-09-29 14:26 UTC, kaoritokashiki commented
[isTheSameVersion === true]
<img width="885" alt="Screen Shot 2020-09-29 at 23 25 24" src="https://user-images.githubusercontent.com/59536731/94571618-25b1bb00-02ab-11eb-97bf-2a2942ae23ca.png">

[isTheSameVersion === false]
<img width="882" alt="Screen Shot 2020-09-29 at 23 25 44" src="https://user-images.githubusercontent.com/59536731/94571610-23e7f780-02ab-11eb-9abb-767551e389e9.png">

2020-09-29 14:48 UTC, yuki-takei requested changes

2020-09-29 14:48 UTC, yuki-takei commented on src/client/js/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
> +  onCheckVersion: PropTypes.func,
onVersionMismatch という名前に変えてください

2020-09-29 14:48 UTC, yuki-takei commented on src/client/js/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
> +        this.props.onCheckVersion(err[0].code);
onCheckVersion は nullable なので存在チェックをする

2020-09-29 14:48 UTC, yuki-takei commented on src/client/js/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
> +      }
versions-are-not-met 以外の例外の場合は toastError を出す

2020-09-29 14:48 UTC, yuki-takei commented on src/client/js/components/Admin/ImportData/GrowiArchiveSection.jsx
> +    if (err === 'versions-are-not-met') {
このメソッドはバージョンミスマッチ時のみ呼ばれるはずなので、この if 文はいらない。
名前ももう少し相応しいものに変える。

2020-09-29 15:57 UTC, kaoritokashiki commented on src/client/js/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
> +      }
onVersionMismatch のnull checkとtoastErrorを追加しました。

2020-09-29 15:59 UTC, kaoritokashiki commented on src/client/js/components/Admin/ImportData/GrowiArchiveSection.jsx
> +    });
`handleVersion`→`handleMismatchedVersions`に名前を変更しました。

2020-09-30 06:30 UTC, yuki-takei requested changes

2020-09-30 06:30 UTC, yuki-takei commented on src/client/js/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
> +      else {
if ブロックの条件を A && B にしてしまうと、A が true, B が false の時も else ブロックに入ってしまう

2020-09-30 06:43 UTC, kaoritokashiki commented on src/client/js/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
> +      else {
すみません、変更しました...!!!

2020-09-30 10:12 UTC, merged