Reactify page form in page content.html
weseek/growi pull request #2808
Opened 2020-09-23 17:23 UTC by zahmis

2020-09-23 17:44 UTC, zahmis commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +    <>
三連ボタンの発火は、最終的に navigationContainer.js の state.editorMode の状態に関与します。
今回はこれを利用しました。

2020-09-23 17:48 UTC, zahmis commented
ボタンを押すと切り替わることを確認しています。
<img width="1386" alt="スクリーンショット 2020-09-24 2 39 00" src="https://user-images.githubusercontent.com/57100766/94049775-5a87c300-fe10-11ea-9cbd-c30b0be164a3.png">
<img width="1391" alt="スクリーンショット 2020-09-24 2 39 13" src="https://user-images.githubusercontent.com/57100766/94049801-5f4c7700-fe10-11ea-9e64-b63a24114c52.png">
<img width="1387" alt="スクリーンショット 2020-09-24 2 39 26" src="https://user-images.githubusercontent.com/57100766/94049803-607da400-fe10-11ea-8c9d-9f4c620ec5df.png">

2020-09-24 08:01 UTC, yuki-takei requested changes

2020-09-24 08:01 UTC, yuki-takei commented on src/server/views/widget/page_content.html
> +</div>
_form.html も消せないかな？
タスクが重くなりすぎるとやらないほうがいいとは思うんだけど、ここを react 化するなら消せるんじゃないかなとか…

一度検討して欲しい

2020-09-24 08:01 UTC, merged

2020-09-24 08:02 UTC, yuki-takei commented on src/server/views/widget/page_content.html
> +</div>
間違えてマージしてしまったので後続タスクで検討を…

2020-09-24 08:02 UTC, yuki-takei commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +      {navigationContainer.state.editorMode === 'hackmd' && 'hackmd'}
間違えてマージしてしまったのでいつかやっといて