gw-3757
weseek/growi pull request #2810
Opened 2020-09-24 04:50 UTC by takeru0001

2020-09-24 06:57 UTC, takeru0001 commented
<img width="1040" alt="スクリーンショット 2020-09-24 13 46 28" src="https://user-images.githubusercontent.com/58085267/94111192-acffc880-fe7e-11ea-97ee-cb343c58436f.png">

2020-09-24 06:59 UTC, takeru0001 commented
ユーザーページのsubnavigationにあったユーザー情報をユーザーページの一番上に配置しました

2020-09-24 09:40 UTC, yuki-takei requested changes

2020-09-24 09:40 UTC, yuki-takei commented on src/client/js/components/User/UserInfo.jsx
> +export default (UserInfoWrapper);
せっかくなので functional component で書いてください

2020-09-24 09:40 UTC, yuki-takei commented on src/client/js/app.jsx
> +    'user-info': <UserInfo />,
`'grw-subnav-container': <GrowiSubNavigation />,` と同条件でマッピングしないといけないんじゃないかな。

2020-09-25 05:45 UTC, takeru0001 commented on src/client/js/app.jsx
> +    'user-info': <UserInfo />,
ページデータが存在しなくても表示するべきでした。修正しました。

2020-09-25 05:45 UTC, takeru0001 commented on src/client/js/components/User/UserInfo.jsx
> +export default (UserInfoWrapper);
functional component に修正しました。

2020-09-27 16:47 UTC, yuki-takei requested changes

2020-09-27 16:47 UTC, yuki-takei commented on src/server/views/layout-kibela/user_page.html
> +{% endblock %}
kibela layout は廃止されるからこのファイルいらないんじゃないかな。
master に追従している feat/gw3604-userhome-renovation ブランチでは既に layout-kibela ディレクトリが消されていると思う。マージしてみて。

2020-09-29 03:50 UTC, merged