Imprv/gw3399 form adjustment
weseek/growi pull request #2816
Opened 2020-09-24 14:06 UTC by kaoritokashiki

2020-09-25 02:43 UTC, kaoritokashiki commented on src/client/js/services/AdminCustomizeContainer.js
>        pageListLimitForUserPage: 10,
こちらは、元々実装されていたものですが、名前を変えるとなると他のいろいろなファイルに影響が出てしまうので、別タスクとしました。
『GW-3920 pageListLimitForUserPageを適切な値に変更』で着手します。

2020-09-25 02:49 UTC, kaoritokashiki commented on src/client/js/components/Admin/Customize/CustomizeFunctionSetting.jsx
>                      <span className="float-left">{adminCustomizeContainer.state.pageListLimitForUserPage}</span>
こちらも　『GW-3920 pageListLimitForUserPageを適切な値に変更』で着手します

2020-09-25 02:50 UTC, kaoritokashiki commented on resource/locales/ja_JP/admin/admin.json
> +
キー名もグループに分けて変更しました。

2020-09-25 03:21 UTC, kaoritokashiki commented on resource/locales/ja_JP/admin/admin.json
> +
英語、中国語が正常に表示されているかは確認済みです。

2020-09-25 08:49 UTC, yuki-takei requested changes

2020-09-25 08:49 UTC, yuki-takei commented on src/client/js/components/Admin/Customize/CustomizeFunctionSetting.jsx
> +                </Dropdown>
Dropdown 共通化してください(後続タスクでも可)

2020-09-27 03:15 UTC, kaoritokashiki commented on src/client/js/components/Admin/Customize/CustomizeFunctionSetting.jsx
> +                </Dropdown>
GW-3957 4つのドロップダウンボタンを共通化させる
後続タスク作成しました。そちらで着手したいと思います。

2020-09-27 03:17 UTC, merged