Display expected page selected buttons
weseek/growi pull request #2827
Opened 2020-09-29 08:13 UTC by zahmis

2020-09-29 09:22 UTC, yuki-takei requested changes

2020-09-29 09:22 UTC, yuki-takei commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +        id="view"
id は削除

2020-09-29 09:22 UTC, yuki-takei commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +        id="edit"
id は削除

2020-09-29 09:22 UTC, yuki-takei commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +        id="hackmd"
id は削除

2020-09-29 09:22 UTC, yuki-takei commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +  });
- ThreeStandedButton に移してください
- threeStrandedButtonClickedHandler で処理

2020-09-29 09:22 UTC, yuki-takei commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +          <EditorNavbarBottom />
EditorNavbarBottom は edit と hackmd で共通化する(つまり TabContent の外に出す)

2020-09-29 09:22 UTC, yuki-takei commented on src/server/views/widget/page_content.html
> +<div id="content-main" class="content-main container col"
container に col を付けるのは bootstrap 的におかしい

2020-09-29 09:22 UTC, yuki-takei commented on src/server/views/widget/page_content.html
> +  <div class="tab-content" id="display-switcher">
tab-content クラスは削除

2020-09-30 08:28 UTC, zahmis commented on src/client/js/services/NavigationContainer.js
> +    if (editorMode === 'view') {
onThreeStrandedButtonClicked の責務はeditorMode の状態を変化させることだと認識しました。
その結果、この処理は NavigationContainer.js に任せることが最適だと判断し、
ここに配置しています。

2020-09-30 08:28 UTC, zahmis commented on src/client/styles/scss/_mixins.scss
> +      #edit,
tab-pane を fb で削除したので _mixins.scss も削除しています。

2020-09-30 08:28 UTC, zahmis commented on src/server/views/widget/page_content.html
> +<div id="display-switcher">
container の支配下にいると 横幅が調節できないと考えました。
当初 container を削除することを考えたのですが、それでは今後不都合が出てきそうなのでやめました。
 container を削除せずに display-switcher のみを除外させることを考えた結果、
この div のみを隷属から外すことにしました。

2020-09-30 08:29 UTC, zahmis commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +        id="view"
承知しました。

2020-09-30 08:29 UTC, zahmis commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +        id="edit"
承知しました。

2020-09-30 08:29 UTC, zahmis commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +        id="hackmd"
承知しました。

2020-09-30 08:29 UTC, zahmis commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +  });
承知しました。

2020-09-30 08:29 UTC, zahmis commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +          <EditorNavbarBottom />
承知しました。

2020-09-30 08:30 UTC, zahmis commented on src/server/views/widget/page_content.html
> +<div id="content-main" class="content-main container col"
col を外しました。

2020-09-30 08:30 UTC, zahmis commented on src/server/views/widget/page_content.html
> +  <div class="tab-content" id="display-switcher">
承知しました。

2020-09-30 10:23 UTC, yuki-takei requested changes

2020-09-30 10:23 UTC, yuki-takei commented on src/server/views/widget/page_content.html
> +<div id="display-switcher">
display-switcher は content-main の中に配置すべきなので元に戻してください。

on-edit 時に `.container` の影響で横幅が制限されることが問題なので、これに関しては scss でその効果を無効化してください。
これは必ずしも正道ではないが、Next.js 化された暁には `.container` の着脱を含め react で管理できるようになるので、それまでの暫定対処という扱いで。

2020-09-30 10:25 UTC, zahmis commented on src/server/views/widget/page_content.html
> +<div id="display-switcher">
承知しました。

2020-09-30 12:23 UTC, merged