Feat/gw 3916 move content aboud drafts
weseek/growi pull request #2828
Opened 2020-09-30 05:53 UTC by yusuketk

2020-09-30 10:29 UTC, yuki-takei requested changes

2020-09-30 10:29 UTC, yuki-takei commented on src/client/js/components/MyDraftList/MyDraftList.jsx
> +    this.props.editorContainer.initDrafts();
この処理、MyDraftList の constructor で必要なのはなぜ？そもそも EditorContainer の初期化時に一度呼んでいるはずで、外から呼ばれる必要性がわからない。不要なら消してほしい。

必要ならその「必要なタイミング」に適した場所に配置すべき。MyDraftList というコンポーネントの constructor は、そのタイミングとしては相応しくない。

2020-09-30 10:30 UTC, yuki-takei requested changes

2020-09-30 10:30 UTC, yuki-takei commented on src/client/js/services/EditorContainer.js
> +        }
MyDraftList の constructor で initDrafts を呼んでしまった弊害としてこの修正内容になったのであれば元に戻す。

2020-10-01 07:06 UTC, yusuketk commented on src/client/js/components/MyDraftList/MyDraftList.jsx
> +    this.props.editorContainer.initDrafts();
EditorContainer の Constructor だけ読んで、#content-mein を「（編集可能な）ページコンテンツ(/hoge/fugaページ等)の要素に使うもの」と勘違いしていました。

```
  constructor(appContainer, defaultEditorOptions, defaultPreviewOptions) {
    super();
...
    const mainContent = document.querySelector('#content-main');

    if (mainContent == null) {
      logger.debug('#content-main element is not exists');
      return;
    }
...
    this.initDrafts();
...
}
```

2020-10-01 07:17 UTC, yusuketk commented on src/client/js/components/MyDraftList/MyDraftList.jsx
> +    this.props.editorContainer.initDrafts();
MyDraftListのconstructor内でやるべきでないのも理解しました。もしやるとしたらドラフトページのレンダーを司る部分

2020-10-01 07:24 UTC, yusuketk commented on src/client/js/components/MyDraftList/MyDraftList.jsx
> +    this.props.editorContainer.initDrafts();
ドラフト一覧ページに id="content-main"を追加することで対応しました

2020-10-01 07:47 UTC, merged