Imprv/omit if page path is too long on edit mode
weseek/growi pull request #2857
Opened 2020-10-06 06:42 UTC by zahmis

2020-10-06 09:04 UTC, yuki-takei requested changes

2020-10-06 09:04 UTC, yuki-takei commented on src/client/styles/scss/_on-edit.scss
> +  }
一旦これは1案として、`calc(100vh - XXXpx)` で表現できないかな？
その際、この breakpoint ごとの記述が少しでもまとめられるならそうしてほしい。

2020-10-06 16:51 UTC, zahmis commented on src/client/styles/scss/_on-edit.scss
> +  }
calc でやってみました。 
位置調整などを見直した結果、不必要なところもあり、
そこは削減（一緒にした）しています。

2020-10-07 04:14 UTC, yuki-takei requested changes

2020-10-07 04:14 UTC, yuki-takei commented on src/client/styles/scss/_on-edit.scss
> +    }
xs 用の指定は media-breakpoint-up に入れずにそのまま書けばいいんじゃないかな。

2020-10-07 04:35 UTC, merged