Imprv/article area gw4006
weseek/growi pull request #2868
Opened 2020-10-07 09:30 UTC by makotoshiraishi

2020-10-07 09:37 UTC, makotoshiraishi commented
not_found_contentで「ページを編集」アラートがでるようにReactのコンポーネントを作成し、ラフな実装だけ作成しました。今後のタスクで目標の状態に近づけていく予定です。

2020-10-07 09:51 UTC, makotoshiraishi commented
<img width="1585" alt="スクリーンショット 2020-10-07 18 37 35" src="https://user-images.githubusercontent.com/64956659/95315883-0bd92f00-08ce-11eb-98f7-aeedf20e45d3.png">

2020-10-07 09:51 UTC, makotoshiraishi commented
上記の「ページを作成するボタンを押すと」

2020-10-07 09:52 UTC, makotoshiraishi commented
<img width="1593" alt="スクリーンショット 2020-10-07 18 52 04" src="https://user-images.githubusercontent.com/64956659/95316075-4e027080-08ce-11eb-9aa5-e011b4063b65.png">

2020-10-07 16:35 UTC, yuki-takei requested changes

2020-10-07 16:35 UTC, yuki-takei commented on src/client/js/components/Page/NotFoundAlert.jsx
> +};
NotFoundAlert は NavigationContainer に依存させず、「ページを作成する」ボタンのイベントハンドラを porps で入れられるようにしてください。

2020-10-07 16:35 UTC, yuki-takei commented on src/client/js/components/Page/NotFoundAlert.jsx
> +    );
NotFoundAlert の責務はアラートのみに限るべき。Editor, EditorNavbarBottom を含むのはおかしい。

2020-10-08 04:13 UTC, makotoshiraishi commented on src/client/js/components/Page/NotFoundAlert.jsx
> +};
propsで入れてnullチェックするように実装しました。

2020-10-08 04:14 UTC, makotoshiraishi commented on src/client/js/components/Page/NotFoundAlert.jsx
> +    );
Editor,EditorNavbarBottomはこのコンポーネント には含めないようにしました。

2020-10-08 04:15 UTC, makotoshiraishi commented on src/client/js/services/NavigationContainer.js
> +    this.setEditorMode = this.setEditorMode.bind(this);
bindしないと、propsに入れた後の動作がうまく行かなたったので、bindしました。
ちょっとJSのBIndやthisについて知識がわかったようでやっぱりわかってないので、勉強します...💦

2020-10-08 08:08 UTC, yuki-takei requested changes

2020-10-08 08:08 UTC, yuki-takei commented on src/client/js/components/Page/NotFoundAlert.jsx
> +    if (props.onPageCreateClicked) {
null チェックはガイドライン通りに

2020-10-08 08:08 UTC, yuki-takei commented on src/server/views/widget/not_found_content.html
> +    <script type="text/template" id="raw-text-original">{{ revision.body.toString() | encodeHTML }}</script>
`revision.body.toString()` は不要なんじゃない？not found ってことは空文字列でいいんだよね？

2020-10-08 08:08 UTC, yuki-takei commented on src/server/views/widget/not_found_tabs.html
> +  </ul>
XD のデザインスペック的には、ここはタブの見た目として生き残るんだっけ？
確認してください。

残す場合はここも React 化する後続タスクを作ってください。

2020-10-08 10:07 UTC, makotoshiraishi commented on src/server/views/widget/not_found_tabs.html
> +  </ul>
タブはデザインが変わって生き残ります。
タスク4052(https://youtrack.weseek.co.jp/issue/GW-4052)でコンポーネント化される予定です。

2020-10-08 10:16 UTC, makotoshiraishi commented on src/server/views/widget/not_found_content.html
> +    <script type="text/template" id="raw-text-original">{{ revision.body.toString() | encodeHTML }}</script>
こちら記述を削除いたしました。

2020-10-08 10:40 UTC, merged