Imprv/gw3957 dropdown buttons commonization
weseek/growi pull request #2871
Opened 2020-10-08 03:28 UTC by kaoritokashiki

2020-10-08 03:39 UTC, kaoritokashiki commented on src/client/js/components/Admin/Customize/CustomizeFunctionSetting.jsx
> +    };
GW-3912 [4つのドロップダウンメニュー] 選択できる数字の査定
で決まった数字をdropdownMenuの中に入れました。

- S
ページコンテンツモーダル
10, 20, 50, 100

- M
ユーザーページ
5, 10, 20, 50, 100

- L
検索 Draft
20, 50, 100, 200


- XL
Notfound Trash
5, 10, 20, 50, 100

2020-10-08 03:50 UTC, kaoritokashiki commented on src/client/js/services/AdminCustomizeContainer.js
> +      pageLimitationXL: 20,
ドロップダウンメニューの値を変更したのでdefaultの値も変更しました。
defaultの数字を20にしたのは私の判断なので、他の値がいい場合ご指摘ください。

2020-10-08 03:53 UTC, kaoritokashiki commented on src/client/js/services/AdminCustomizeContainer.js
> +    this.switchPageListLimitationXL = this.switchPageListLimitationXL.bind(this);
bindに関しては、忘れていたようなので追加しました

2020-10-08 03:56 UTC, kaoritokashiki commented on src/client/js/services/AdminCustomizeContainer.js
> +    this.switchPageListLimitationXL = this.switchPageListLimitationXL.bind(this);
こちらも共通化できる??
もしこれもでしたら別タスクで対応させて下さい

2020-10-08 08:02 UTC, yuki-takei requested changes

2020-10-08 08:02 UTC, yuki-takei commented on src/client/js/components/Admin/Customize/CustomizeFunctionSetting.jsx
> +                  </div>
その外側の `dropdownGroupMapping` を使ってイテレートしてる部分は粒度としては organism だよね。それはそのまま書いてもいいかと思ったけど…まあ今のように共通化するのもありといえばありかな。

2020-10-08 08:03 UTC, yuki-takei requested changes

2020-10-08 08:03 UTC, yuki-takei commented on src/client/js/services/AdminCustomizeContainer.js
> +    this.switchPageListLimitationXL = this.switchPageListLimitationXL.bind(this);
bind は `PagingSizeUncontrolledDropdown` の attribute に渡すときにやればいい。

2020-10-12 04:31 UTC, kaoritokashiki commented on src/client/js/services/AdminCustomizeContainer.js
> +    this.switchPageListLimitationXL = this.switchPageListLimitationXL.bind(this);
`JSX props should not use .bind()`
attribute に渡すときにbindしようとしたらeslintで怒られたのでやめました。

2020-10-12 04:33 UTC, kaoritokashiki commented on src/client/js/components/Admin/Customize/CustomizeFunctionSetting.jsx
> +            />
propsで渡すように変更しました。

2020-10-12 04:49 UTC, kaoritokashiki commented on src/client/js/components/Admin/Customize/PagingSizeUncontrolledDropdown.jsx
> +  }
`onChangeDropdownItem: PropTypes.func,` なので
null checkを行いました。

2020-10-12 04:53 UTC, kaoritokashiki commented
見た目はそのまま、ドロップダウンボタンをfunctional componentにしてpropsで各値を渡すようにしました。
<img width="776" alt="Screen Shot 2020-10-12 at 13 51 43" src="https://user-images.githubusercontent.com/59536731/95706548-1dd21d80-0c92-11eb-9911-82d93cad8131.png">

2020-10-12 07:52 UTC, yuki-takei requested changes

2020-10-12 07:52 UTC, yuki-takei commented on src/client/js/components/Admin/Customize/CustomizeFunctionSetting.jsx
> +              desc="admin:customize_setting.function_options.list_num_desc_s"
translate 後の文字列を入れよう

2020-10-12 07:52 UTC, yuki-takei commented on src/client/js/components/Admin/Customize/PagingSizeUncontrolledDropdown.jsx
> +                  })}
インデント整頓してください

2020-10-12 09:21 UTC, kaoritokashiki commented on src/client/js/components/Admin/Customize/PagingSizeUncontrolledDropdown.jsx
> +                  })}
失礼しました、整理しました。

2020-10-12 09:21 UTC, kaoritokashiki commented on src/client/js/components/Admin/Customize/CustomizeFunctionSetting.jsx
> +              desc={t('admin:customize_setting.function_options.list_num_desc_s')}
translate後の文字を挿入しました。

2020-10-12 09:24 UTC, merged