Imprv/article area gw4051
weseek/growi pull request #2874
Opened 2020-10-09 01:48 UTC by makotoshiraishi

2020-10-09 01:54 UTC, makotoshiraishi commented
NotFoundアラートの色を補正しました。
基本は`$info`で行くのですが、テーマがdefaultの時だけ`$accent`でいくということでそのように実装しました。
またアラートのメッセージ「このページは存在しません。・・・」の文字の大きさもXDに合わせて少し小さく変更しました。

2020-10-09 01:58 UTC, makotoshiraishi commented
default[light]
<img width="1413" alt="スクリーンショット 2020-10-09 10 56 39" src="https://user-images.githubusercontent.com/64956659/95533444-1e627e00-0a1e-11eb-9554-c598ec62ece5.png">


default[dark]
<img width="1387" alt="スクリーンショット 2020-10-09 10 57 02" src="https://user-images.githubusercontent.com/64956659/95533461-2c180380-0a1e-11eb-8a1e-ea793f75f2b8.png">


その他のテーマ
（写真ではisland）

<img width="1397" alt="スクリーンショット 2020-10-09 10 57 58" src="https://user-images.githubusercontent.com/64956659/95533513-4d78ef80-0a1e-11eb-9ad8-b9b6dfb1cbae.png">

2020-10-09 04:43 UTC, yuki-takei commented on src/client/styles/scss/theme/default.scss
> +  }
こういうイレギュラーなのは気持ち悪いので、テーマで別の色にするコードは書かない。

2020-10-09 04:43 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +}
これくらいのものはユーティリティークラスで代用できない？

2020-10-09 04:45 UTC, yuki-takei requested changes

2020-10-09 04:45 UTC, yuki-takei commented on src/client/styles/scss/theme/default.scss
> +  }
default theme 全体で $info 自体を $accent で上書きするというのは検討してもいいかも。

2020-10-13 06:52 UTC, makotoshiraishi commented on src/client/styles/scss/theme/default.scss
> +  }
こちら全部$infoで統一した実装にしました。

2020-10-13 07:20 UTC, yuki-takei requested changes

2020-10-13 07:20 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +}
https://github.com/twbs/bootstrap/blob/v4.5.0/scss/utilities/_borders.scss

を参考に、 `_reboot-bootstrap-border-colors` で `.border-#{$color}` も再設定してください。それでユーティリティクラスだけでいけるようになるはず。

2020-10-13 07:38 UTC, merged