Imprv/article area gw4054
weseek/growi pull request #2875
Opened 2020-10-09 02:34 UTC by makotoshiraishi

2020-10-09 02:37 UTC, makotoshiraishi commented
元々は二連ボタンを入れる予定のタスクでしたが三連ボタンにするということで、コードの変更点は少なくなりました。
NotFoundページで三連ボタンを表示するように実装しました。

2020-10-09 02:39 UTC, makotoshiraishi commented
<img width="1586" alt="スクリーンショット 2020-10-09 11 38 34" src="https://user-images.githubusercontent.com/64956659/95535719-1b6a8c00-0a24-11eb-880d-ea2c69c1730f.png">

2020-10-09 08:23 UTC, yuki-takei requested changes

2020-10-09 08:23 UTC, yuki-takei commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +        {isPageNotFound && <ThreeStrandedButton onThreeStrandedButtonClicked={onThreeStrandedButtonClicked} />}
この if ブロック自体消して、下の方の reutnr ブロックを整頓してほしい。

DrawerToggler は notfound, forbidden でもあっていいし。

2020-10-13 02:29 UTC, makoto15 commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +        {isPageNotFound && <ThreeStrandedButton onThreeStrandedButtonClicked={onThreeStrandedButtonClicked} />}
ここのifブロック自体を消しました。
forbiddenページは現段階では下の写真のようになっています。
ここは本タスクのスコープ外であるのと、まだデザインチームの方でもどのような表示にするか決まっていないため、この状態でプルリクを送ることにしました。
よろしくお願いします。

2020-10-13 02:30 UTC, makoto15 commented
<img width="1664" alt="スクリーンショット 2020-10-13 11 29 23" src="https://user-images.githubusercontent.com/33254944/95808488-7d3e3500-0d47-11eb-942f-871dfec832a8.png">

2020-10-13 02:30 UTC, makoto15 commented
not foundページの見た目

2020-10-13 02:32 UTC, makoto15 commented
<img width="1661" alt="スクリーンショット 2020-10-13 11 31 33" src="https://user-images.githubusercontent.com/33254944/95808590-c0000d00-0d47-11eb-922e-9d7ae654f070.png">

2020-10-13 02:34 UTC, makoto15 commented
またNotfoundページを編集しようとするとDrawerTogglerが表示されるようになりました。

<img width="1674" alt="スクリーンショット 2020-10-13 11 33 11" src="https://user-images.githubusercontent.com/33254944/95808705-0ce3e380-0d48-11eb-98ca-f1e61ebf0464.png">

2020-10-13 07:08 UTC, merged