Imprv/gw4065 create component for trash and not found
weseek/growi pull request #2877
Opened 2020-10-09 04:04 UTC by kaoritokashiki

2020-10-09 04:20 UTC, kaoritokashiki commented on src/client/styles/scss/_navbar.scss
> +}
これは、pageAccesoriesModalのnavtabと同じ指定です。

2020-10-09 04:21 UTC, kaoritokashiki commented on src/client/styles/scss/theme/_apply-colors.scss
> +}
同上

2020-10-09 04:22 UTC, kaoritokashiki commented on src/client/js/components/TrashPage.jsx
> +};
これはオブジェクトの方が見やすいと考えたのでこのようにしました。

2020-10-09 04:23 UTC, kaoritokashiki commented on src/client/js/components/CustomNavbar.jsx
> +  navTabMapping: PropTypes.object,
propsにオブジェクトが渡ってくる仕様にしました。

2020-10-10 01:36 UTC, kaoritokashiki commented on src/client/js/components/CustomNavbar.jsx
> +  const navTabId = `custom-navtab-${Math.random().toString(32).substring(2)}`;
Math.randomを使用することで固有のidを作成しました。

2020-10-10 01:46 UTC, kaoritokashiki commented on src/client/js/components/CustomNavbar.jsx
> +  const navTabId = `custom-navtab-${random}`;
`Math.random()`を使うことで固有のidを作成しました。

2020-10-10 03:06 UTC, yuki-takei requested changes

2020-10-10 03:06 UTC, yuki-takei commented on src/client/js/components/CustomNavbar.jsx
> +      </TabContent>
Nav と TabContent が別のコンポーネントに配置されないのなら、CustomNavbarContainer の存在は不要では？

2020-10-10 03:06 UTC, yuki-takei commented on src/client/js/components/TrashPage.jsx
> +    i18n: 'page_list',
これは理想はキーを渡すのではなく、すでに `t()` で取得したラベルを渡すべきかな。
そうすると必然的に withTranslation した中のコンポーネントで作らないといけない。

2020-10-11 17:56 UTC, yuki-takei requested changes

2020-10-11 17:56 UTC, yuki-takei commented on src/client/js/components/CustomNavbar.jsx
> +            })}
この辺りのインデント揃えて

2020-10-11 17:56 UTC, yuki-takei commented on src/client/js/components/CustomNavbar.jsx
> +                <NavItem key={key} type="button" className={`p-0 ${navTabId} ${activeTab === key && 'active'}`}>
navTabId という名前なのにクラスにも入れてるのはなぜ？不要に思える。

2020-10-11 17:56 UTC, yuki-takei commented on src/client/js/components/CustomNavbar.jsx
> +      </TabContent>
逆に追加したい機能で言えば、モーダルでの配置モードを追加できないかな。そうすると PageAccessoriesModal もこのコンポーネントを使えるようになって共通化できるし、将来的に複数タブを持つモーダルを作りたい場合にも流用できる。

2020-10-13 02:31 UTC, kaoritokashiki commented on src/client/js/components/CustomNavigation.jsx
> +              <NavLink onClick={() => { switchActiveTab(key) }}>
変数名を変更しました。
これはなぜ必要なのかというと、
`<CustomNavigation>`以外の部分でli.nav-linkが存在した場合に、期待に反した棒線の長さになってしまうことの対処法です。

### 背景
元々は、`nav-link`と指定していましたが、そうするとpageAccessoriesModal上のアニメーション棒線が短くなってしまうという現象が起きてしまっていました。その問題を回避するためにオリジナルのクラス名を作成しました。

2020-10-13 02:41 UTC, kaoritokashiki commented on src/client/js/components/TrashPage.jsx
> +  };
withTranslationで翻訳されたものを指定するようにしました。

2020-10-13 02:44 UTC, kaoritokashiki commented on src/client/js/components/CustomNavbar.jsx
> +            })}
失礼しました。揃えました。

2020-10-13 02:47 UTC, kaoritokashiki commented
## TODO 後続タスクを作成しました。

GW-4097 CustomNavigationコンポーネントを使用し、PageAccessoriesModalを表示できるようにする
GW-4079 【CustomNavbar】defaultでactiveTabを設定できるようにする

2020-10-13 03:04 UTC, kaoritokashiki commented on src/client/js/components/CustomNavbar.jsx
> +      </TabContent>
CustomNavbarContainerを削除し、CustomNavigation.jsxに集約させました。

2020-10-13 03:06 UTC, kaoritokashiki commented on src/client/js/components/CustomNavigation.jsx
> +  }
CustomNavbarContainerを削除し、CustomNavigation.jsxに集約させました。

2020-10-13 07:12 UTC, yuki-takei requested changes

2020-10-13 07:12 UTC, yuki-takei commented on src/client/js/components/CustomNavigation.jsx
> +  const grwNavTab = `grw-custom-navtab-${random}`;
ランダム値でクラス名(key？)を作成するコードを消してください。

2020-10-13 09:41 UTC, merged