Imprv/paging correctly if not exist paging size in db
weseek/growi pull request #2882
Opened 2020-10-11 09:02 UTC by zahmis

2020-10-12 09:45 UTC, yuki-takei requested changes

2020-10-12 09:45 UTC, yuki-takei commented on src/server/routes/apiv3/bookmarks.js
> +        throw new Error('You should set less than 100 or not to set pageLimitationM.');
throw の結果どうなるかが想像できないが、express-validator のマニュアルにこのようなやり方で、とあればそれでよい。HTTP status は 400 であってほしい。

2020-10-12 09:45 UTC, yuki-takei commented on src/server/routes/apiv3/bookmarks.js
> +      if (value > 100) {
100は少ないので、300くらいにする。

2020-10-12 09:45 UTC, yuki-takei commented on src/server/routes/apiv3/bookmarks.js
> +    query('selectPageNumber').isInt({ min: 1 }),
page にする

2020-10-12 09:45 UTC, yuki-takei commented on src/server/routes/apiv3/bookmarks.js
> +    query('pageLimitationM').custom((value) => {
limit にする

2020-10-12 09:45 UTC, yuki-takei commented on src/client/js/components/PageList.jsx
> +    const res = await appContainer.apiv3Get('/pages/list', { path, activePage });
activePage というクエリ名は違和感

2020-10-12 09:45 UTC, yuki-takei commented on src/client/js/components/PageTimeline.jsx
> +      limit: Infinity,
これはサーバー側の実装が正しければ400になってしまわない？

2020-10-12 09:45 UTC, yuki-takei commented on src/server/routes/apiv3/bookmarks.js
> +      if (value === undefined) {
null チェックは `== null`

2020-10-12 10:08 UTC, zahmis commented on src/server/routes/apiv3/bookmarks.js
> +        throw new Error('You should set less than 100 or not to set pageLimitationM.');
status code 400 を確認しました。
この状態でいきます。

2020-10-12 10:09 UTC, zahmis commented on src/server/routes/apiv3/bookmarks.js
> +      if (value > 100) {
承知しました。

2020-10-12 11:30 UTC, zahmis commented on src/server/routes/apiv3/bookmarks.js
> +    query('selectPageNumber').isInt({ min: 1 }),
修正します。

2020-10-12 11:31 UTC, zahmis commented on src/server/routes/apiv3/bookmarks.js
> +    query('pageLimitationM').custom((value) => {
修正します。

2020-10-12 11:31 UTC, zahmis commented on src/client/js/components/PageList.jsx
> +    const res = await appContainer.apiv3Get('/pages/list', { path, activePage });
ここは page にしました。

2020-10-12 11:31 UTC, zahmis commented on src/client/js/components/PageTimeline.jsx
> +      limit: Infinity,
確認します。

2020-10-12 11:32 UTC, zahmis commented on src/server/routes/apiv3/bookmarks.js
> +      if (value === undefined) {
修正します。

2020-10-12 11:59 UTC, zahmis commented on src/client/js/components/PageTimeline.jsx
> +      limit: Infinity,
検証した結果、Infinity でも正常に動作することがわかりました。

この理由の自分なりの見解は、クライアントサイドで最初に実装しても、
bookmark をブラウザで開くときに api が叩かれ、そのときに limit 値が更新されるため、
validation に引っかからないと考えました。

しかし、limit に制限を設けているのに Infinity は違和感があるので、
limit を各コンテンツモーダルごとに適切な値に再設定し直しました。

2020-10-12 12:15 UTC, yuki-takei commented on src/client/js/components/PageTimeline.jsx
> +      limit: Infinity,
> リクエストに指定があればそれを使うが、validation で max は設ける
> リクエストに指定がなければ、DB 内の値を使う
> DB 内にも値がなければ、各APIエンドポイントで適当なデフォルト値を使う
これのどのシーケンスに入るのか要検証

2020-10-12 12:18 UTC, yuki-takei requested changes

2020-10-12 12:18 UTC, yuki-takei commented on src/server/routes/apiv3/attachment.js
> +        }
この null だったら return 10 はそもそも要らないのでは？
なぜなら
```
    const limit = req.query.limit || await crowi.configManager.getConfig('crowi', 'customize:showPageLimitationS') || 10;
```
で一番右の `|| 10` に落ちるので

2020-10-12 13:53 UTC, zahmis commented on src/server/routes/apiv3/attachment.js
> +        }
この設定を外したのですが、|| 10 に落ちなかったです。

2020-10-12 18:17 UTC, zahmis commented on src/client/js/components/PaginationWrapper.jsx
> +  pagingLimit: PropTypes.number,
isRequired を外しています。

2020-10-12 18:17 UTC, zahmis commented on src/server/routes/apiv3/attachment.js
> +        }
post man で検証したところ、limit を設定しない場合、
値が undefined で返ってくることがわかりました。
null の場合は 落ちるが、 undefined の場合は値として区別するのだと考えました。

この validation を設定すると、null と undefined 双方に対して働くと考えられるので、
この validation が必要だと判断しました。

2020-10-13 07:06 UTC, yuki-takei requested changes

2020-10-13 07:06 UTC, yuki-takei commented on src/server/routes/apiv3/attachment.js
> +        }
市澤くんに聞いて if を使ってください

2020-10-13 08:25 UTC, zahmis commented on src/server/routes/apiv3/attachment.js
> +        }
修正しました。
無事バリデーションが機能するようになりました。
しかし、validation に引っかかった際 Invalid value だけではあまりに不親切なので、
この場合は withMessage() で上限値をお知らせしています。

2020-10-13 08:33 UTC, merged