feat/gw-3968
weseek/growi pull request #2883
Opened 2020-10-12 04:59 UTC by takeru0001

2020-10-12 04:59 UTC, takeru0001 commented
<img width="986" alt="スクリーンショット 2020-10-12 13 50 40" src="https://user-images.githubusercontent.com/58085267/95706932-2414c980-0c93-11eb-9838-c57b7afbb933.png">

2020-10-12 05:00 UTC, takeru0001 commented
LikeButtonとBookmarkButtonのデザイン修正完了しました。

2020-10-12 07:56 UTC, yuki-takei requested changes

2020-10-12 07:56 UTC, yuki-takei commented on src/client/styles/scss/_subnav.scss
> +    width: 100%;
width: 100% を使わずにできない？

2020-10-12 07:56 UTC, yuki-takei commented on src/client/styles/scss/_subnav.scss
> +    border-radius: 5px;
bs4 の既定の変数を使って

2020-10-12 07:56 UTC, yuki-takei commented on src/client/styles/scss/_subnav.scss
> +    font-weight: 600;
$font-weight-bold

2020-10-12 07:56 UTC, yuki-takei commented on src/client/styles/scss/_subnav.scss
> +    font-size: 17px;
font-size はOK

2020-10-12 07:56 UTC, yuki-takei commented on src/client/styles/scss/_subnav.scss
> +      width: 100%;
width: 100% を使わずにできない？

2020-10-12 07:56 UTC, yuki-takei commented on src/client/styles/scss/_subnav.scss
> +      border-radius: 5px;
bs4 の既定の変数を使って

2020-10-12 09:06 UTC, takeru0001 commented on src/client/styles/scss/_subnav.scss
> +    border-radius: 5px;
修正しました。

2020-10-12 09:06 UTC, takeru0001 commented on src/client/styles/scss/_subnav.scss
> +    font-weight: 600;
`$font-weight-bold`を作成し適応させました。

2020-10-12 09:07 UTC, takeru0001 commented on src/client/styles/scss/_subnav.scss
> +      border-radius: 5px;
修正しました。

2020-10-12 09:49 UTC, takeru0001 commented on src/client/styles/scss/_subnav.scss
> +    width: 100%;
widthの設定を削除しました

2020-10-12 09:49 UTC, takeru0001 commented on src/client/styles/scss/_subnav.scss
> +      width: 100%;
widthの設定を削除しました

2020-10-16 09:55 UTC, yuki-takei requested changes

2020-10-16 09:55 UTC, yuki-takei commented on src/client/styles/scss/_override-bootstrap-variables.scss
> +$font-weight-bold: bold;
違う。もう存在する。
https://github.com/twbs/bootstrap/blob/v4.5.0/scss/_variables.scss#L295

2020-10-19 06:56 UTC, merged