Imprv/show trash page list new
weseek/growi pull request #2890
Opened 2020-10-13 10:29 UTC by kaoritokashiki

2020-10-13 10:36 UTC, kaoritokashiki commented on src/client/styles/scss/_navbar.scss
>  .grw-trash-page {
現在クラス名が.grw-trash-pageになっていますが、trashページ意外にも適用されるように以下のタスクで白石さんが変更します
(GW-4052 【not found】ページリストのタブを作成（コンポーネント化）)

2020-10-13 10:37 UTC, kaoritokashiki commented on src/client/styles/scss/_navbar.scss
> +  }
ulに特有のドットを削除しました。

2020-10-13 10:50 UTC, yuki-takei requested changes

2020-10-13 10:50 UTC, yuki-takei commented on src/client/styles/scss/_navbar.scss
> +  }
`_page_list.scss` の `.page-list-ul > li` が効くようにすべきではないか

2020-10-13 10:50 UTC, yuki-takei commented on src/server/routes/apiv3/pages.js
> +    if (path === '/trash') {
1. `import { isTrashPage } from '@commons/util/path-utils';` を使う
2. `path-utils` の `isTrashPage` を使う( growi-commons とかぶってる…)

2020-10-15 01:12 UTC, kaoritokashiki commented on src/server/routes/apiv3/pages.js
> +    };
path-utilsに定義されている `isTrashPage` を用いて、trashページの場合`includeTrash`にするようにしました。

2020-10-15 01:15 UTC, kaoritokashiki commented on src/server/views/layout-growi/page.html
> +
これは`/trash`ページ上でtrash page listを表示するための記述です

2020-10-15 01:17 UTC, kaoritokashiki commented on src/server/views/layout-growi/page_list.html
> +  {% endif %}
こちらは`/trash/xxx`  trashページ配下のページで page listを表示するための記述です。

2020-10-15 01:20 UTC, kaoritokashiki commented on src/server/views/layout-growi/page_list.html
> +  {% endif %}
pages.jsで`{ isTrashPage }`の判別しているのでここではvalidationいらないですかな

2020-10-15 02:23 UTC, kaoritokashiki commented on src/client/styles/scss/_page_list.scss
> +
page_list.scss内で記述しました。

2020-10-15 09:02 UTC, yuki-takei requested changes

2020-10-15 09:02 UTC, yuki-takei commented on src/client/styles/scss/_page_list.scss
> +
- 13行目の `list-style: none;` があれば不要なはずでは？
    - page-list-ul 以下が moleculus や organism 相当の汎用デザインになっているはず
- `page-list-container-create` クラスは上記の外側のクラスで、そもそもいろんな箇所に付いているのがおかしいような気はする

2020-10-15 09:05 UTC, yuki-takei requested changes

2020-10-15 09:05 UTC, yuki-takei commented on src/server/routes/apiv3/pages.js
> +    };
動作確認してないんじゃない？ `isTrashPage` はメソッドだよ。

2020-10-15 09:05 UTC, yuki-takei commented on src/server/views/layout-growi/page_list.html
> +  {% endif %}
trash 配下ページは PageAccessoriesModal を使うのでは？

2020-10-15 09:05 UTC, yuki-takei commented on src/server/views/layout-growi/page.html
> +
id が不適切

2020-10-15 09:49 UTC, kaoritokashiki commented on src/server/views/layout-growi/page_list.html
> +  {% endif %}
すみません....その通りでした。

2020-10-15 13:38 UTC, kaoritokashiki commented on src/server/routes/apiv3/pages.js
> +    };
動作確認はちゃんとしてあります。そして正常に表示されます...

2020-10-16 04:32 UTC, kaoritokashiki commented on src/client/js/components/TrashPageList.jsx
> +const TrashPageList = (props) => {
名前をTrashPageListに変更しました。

2020-10-16 04:33 UTC, kaoritokashiki commented on src/server/routes/apiv3/pages.js
> +    };
isTrashPage はメソッドなので、引数にpathを渡してあげてtrueだったらtrash pagelist を表示させるというふうにしましたがいかがでしょうか。

2020-10-16 04:37 UTC, kaoritokashiki commented on src/server/views/layout-growi/page_list.html
> +  {% endif %}
id名を変更しました

2020-10-16 04:41 UTC, kaoritokashiki commented on src/client/js/components/PageList.jsx
> -      <ul className="page-list-ul page-list-ul-flat ml-n4">
`page-list-container-create`classは、cssでの指定がどこにもなかったので削除しました。

2020-10-16 09:58 UTC, yuki-takei requested changes

2020-10-16 09:58 UTC, yuki-takei commented on src/server/routes/apiv3/pages.js
> +    let includeTrashed;
false で初期化

2020-10-16 09:58 UTC, yuki-takei commented on src/server/routes/apiv3/pages.js
> +    }
else ブロック不要

2020-10-18 14:02 UTC, kaoritokashiki commented on src/server/routes/apiv3/pages.js
> +    }
なるほどです。勉強になりました

2020-10-19 03:46 UTC, yuki-takei requested changes

2020-10-19 03:46 UTC, yuki-takei commented on src/client/styles/scss/_page_list.scss
> -        }
これ消しちゃって大丈夫なの？

2020-10-19 07:57 UTC, kaoritokashiki commented on src/client/styles/scss/_page_list.scss
> -        }
<img width="609" alt="Screen Shot 2020-10-19 at 16 55 34" src="https://user-images.githubusercontent.com/59536731/96417315-1976a900-122c-11eb-8779-83e8e4586273.png">
<img width="1135" alt="Screen Shot 2020-10-19 at 16 55 18" src="https://user-images.githubusercontent.com/59536731/96417328-1c719980-122c-11eb-8e38-2ab0782dd84d.png">

2020-10-19 07:58 UTC, kaoritokashiki commented on src/client/styles/scss/_page_list.scss
> -        }
```
      > a {
        padding: 0px;
        color: inherit;

        &:hover {
          color: inherit;
        }
      }
```
デザインチーム&武井さんとの話し合いの結果、textColorに戻しました。

2020-10-19 07:59 UTC, merged