implemented the hackmd for not found page
weseek/growi pull request #2896
Opened 2020-10-15 04:56 UTC by makotoshiraishi

2020-10-15 05:01 UTC, makotoshiraishi commented
Not foundページから「HackMD」ボタンを押した時の遷移ページを実装しました。
以下のような見た目になっています。

2020-10-15 05:02 UTC, makotoshiraishi commented
<img width="1912" alt="スクリーンショット 2020-10-15 14 00 41" src="https://user-images.githubusercontent.com/64956659/96079140-fcba3880-0eee-11eb-8b19-8d704c9fe114.png">

2020-10-15 05:03 UTC, makotoshiraishi commented
英語バージョン

<img width="1913" alt="スクリーンショット 2020-10-15 14 03 24" src="https://user-images.githubusercontent.com/64956659/96079226-3428e500-0eef-11eb-8a32-df8d0bad3ce9.png">

2020-10-15 14:16 UTC, yuki-takei requested changes

2020-10-15 14:16 UTC, yuki-takei commented on resource/locales/ja_JP/translation.json
> +    "used_for_not_found": "存在しないページでHackMDを利用することはできません",
「HackMD は新しいページの作成には利用できません」に変えてください。

2020-10-15 14:16 UTC, yuki-takei commented on resource/locales/ja_JP/translation.json
> +    "used_for_not_found": "存在しないページでHackMDを利用することはできません",
他の訳文を踏襲し、英単語の両サイドは半角スペースが空けてください。

2020-10-15 14:16 UTC, yuki-takei commented on resource/locales/ja_JP/translation.json
> +    "need_to_make_page": "HackMDを利用するためには、新しいページを作成してください。"
「HackMDを利用するためには、ビルトインエディタで新しいページを作成してください。」に変えて、エディタを開くリンクを付けてください。

2020-10-20 02:41 UTC, makotoshiraishi commented
翻訳を変えてまたビルトインエディタを開くリンクを付けるように実装しました。
<img width="1668" alt="スクリーンショット 2020-10-20 11 40 31" src="https://user-images.githubusercontent.com/64956659/96533648-2dbcb380-12c9-11eb-9801-8e8c5f59a201.png">

2020-10-20 08:20 UTC, yuki-takei requested changes

2020-10-20 08:20 UTC, yuki-takei commented on resource/locales/ja_JP/translation.json
> +    "need_to_make_page": "HackMD を利用するためには、ビルトインエディタで新しいページを作成してください。",
「HackMD を利用するためには、ビルトインエディタで新しいページを作成してください。」
の文中の「ビルトインエディタ」をリンクにしてください。

2020-10-20 08:20 UTC, yuki-takei commented on resource/locales/ja_JP/translation.json
> +    "open_editor": "ビルトインエディタを開く"
これは不要

2020-10-22 04:22 UTC, merged