Imprv/three stranded button design fb
weseek/growi pull request #2902
Opened 2020-10-15 13:00 UTC by shukmos

## やったこと: 3連ボタンのデザインのFB対応
- ボタンの幅を均一にした
  - HackMDはXDと同様、font-sizeとletter-spacingを調整した
- 仕切りのボーダーをやや短くした

## スクショ
![グループ 1281](https://user-images.githubusercontent.com/20252919/96129363-7f63e780-0f31-11eb-8b99-033e240d2b52.png)

2020-10-15 14:27 UTC, yuki-takei requested changes

2020-10-15 14:27 UTC, yuki-takei commented on src/client/styles/scss/_mixins.scss
> +  }
この量はちょっと…誰も触れなくなってしまう。

2020-10-15 14:27 UTC, yuki-takei commented on src/client/styles/scss/_mixins.scss
> +  }
提案としては、`three-stranded-button` という mixin ではなくて、合間のボーダーだけ短くする mixin とか、効果別に分けたら少しはメンテナンス性上がらないだろうか。

2020-10-15 14:28 UTC, yuki-takei requested changes

2020-10-15 14:28 UTC, yuki-takei commented on src/client/styles/scss/style-app.scss
> +  }
このファイルに書いてある内容と mixin はなぜ分けてるんだっけ？

2020-10-16 05:21 UTC, shukmos commented on src/client/styles/scss/style-app.scss
> +  }
分けてる理由もないので、mixinの方に入れ込みます

2020-10-16 05:22 UTC, shukmos commented on src/client/styles/scss/_mixins.scss
> +  }
合間のボーダーだけ短くする mixin…たしかに。
さらにそのmixinだけである程度の汎用性はあるかも知れないですね。
やってみます

2020-10-16 06:55 UTC, shukmos commented
- 合間の短いボーダーを表現する箇所(`short-border-vertical`)と`three-stranded-button `を別々のmixinにしました。
- ↓ また、試しにshort-border-verticalが単体で使えそうな箇所があったので、入れ込んでみました（見た目も改善した）
![image](https://user-images.githubusercontent.com/20252919/96222666-a7058f00-0fc7-11eb-8349-6ab12eaeebc5.png)

2020-10-16 10:18 UTC, yuki-takei requested changes

2020-10-16 10:18 UTC, yuki-takei commented on src/client/styles/scss/_mixins.scss
> +  }
ここは消しましょうか…
それかもうちょっと綺麗になるならば…

2020-10-19 06:52 UTC, shukmos commented
Afterの記述をinclude を使うことで10行ほどを削減できました。

2020-10-19 06:54 UTC, shukmos commented
![画面収録-2020-10-19-15 40 21](https://user-images.githubusercontent.com/20252919/96411392-54c0aa00-1223-11eb-8bd6-4a633afd7315.gif)
Afterなしにすると4行分さらに削減できます。
ただし、やや見た目が見劣る（Gifを参照）

2020-10-19 07:19 UTC, yuki-takei requested changes

2020-10-19 07:19 UTC, yuki-takei commented on src/client/styles/scss/_mixins.scss
> +  }
border-vertical の before 時に入れる

2020-10-19 07:19 UTC, yuki-takei commented on src/client/styles/scss/_mixins.scss
> +  }
border-vertical の after 時に入れる

2020-10-19 07:19 UTC, yuki-takei commented on src/client/styles/scss/_mixins.scss
> +@mixin border-vertical($beforeOrAfter, $borderColor, $borderLength, $zIndex: initial) {
button group 用途なのかどうかを boolean でセットして if statement を使おう

2020-10-19 11:17 UTC, merged