Imprv/link view,edit,hackmd anchor tag
weseek/growi pull request #2904
Opened 2020-10-15 13:40 UTC by zahmis

2020-10-15 18:17 UTC, zahmis commented on src/client/js/services/NavigationContainer.js
> +      window.history.replaceState(null, '', window.location.pathname);
アンカータグの状態を NavigationContainer.js に持たせるようにしました。

2020-10-15 18:17 UTC, zahmis commented on src/client/js/legacy/crowi.js
> +      $('a[href="#edit"]').tab('show');
data-toggle="tab" は使用していないと判断したので削除しています。

2020-10-15 18:17 UTC, zahmis commented on src/client/js/legacy/crowi.js
> -    else if (window.location.hash === '#revision-history' && $('.tab-pane#revision-history').length > 0) {
#revision-history は使用していないと判断したので、削除しています

2020-10-15 18:17 UTC, zahmis commented on src/client/js/legacy/crowi.js
> -    else if (window.location.hash === '#hackmd' && $('.tab-pane#hackmd').length > 0) {
条件の変更により、ここを削除しています

2020-10-15 18:17 UTC, zahmis commented on src/client/js/legacy/crowi.js
> -    if ((window.location.hash === '#edit' || window.location.hash === '#edit-form') && $('.tab-pane#edit').length > 0) {
条件の変更により、削除しています。

2020-10-16 09:49 UTC, yuki-takei requested changes

2020-10-16 09:49 UTC, yuki-takei commented on src/client/js/legacy/crowi.js
> +      $('a[href="#edit"]').tab('show');
これって jquery 使わないと無理なやつ？
改修コストが高くなるのであればこのままでもいいけど、一旦検討してほしい。

2020-10-16 16:36 UTC, zahmis commented on src/client/js/legacy/crowi.js
> +      navigationContainer.setEditorMode('edit');
この部分は jquery ではなく、navigationContainer.setEditMode を使用しています。

2020-10-16 16:36 UTC, zahmis commented on src/client/js/legacy/crowi.js
> -
navigationContaienr.setEditorMode('hackmd') を実行で代用できるため、削除しています。

2020-10-16 16:36 UTC, zahmis commented on src/client/js/legacy/crowi.js
> -      $('a[data-toggle="tab"][href="#revision-history"]').tab('show');
使っていないので削除しています。

2020-10-17 17:08 UTC, zahmis commented on src/client/js/legacy/crowi.js
> +      Crowi.setCaretLineAndFocusToEditor();
tab 削除に伴いここに setCaretLineAndFocusToEditor を仕込んでいます。
anchor タグが edit になったときにきちんと発動するようになりました。

2020-10-18 17:18 UTC, zahmis commented on src/client/js/components/Hotkeys/Subscribers/EditPage.jsx
> -    // show editor
tab の表示でこの行を表示していたと思われますが、
今回からは tab  の表示で表示するわけではないと考えられるので削除しています。

2020-10-18 17:18 UTC, zahmis commented on src/client/js/legacy/crowi.js
> -  else {
revision-body は DisplaySwitcher に代用されたので、これは必要ないと判断しました。

2020-10-18 17:18 UTC, zahmis commented on src/server/views/widget/forbidden_content.html
> -      <a class="nav-link active" role="tab" href="#revision-body" data-toggle="tab">
crowi.js legacy において revision-body の部分削除に伴い、
forbidden_content.html でも不要と考えたので、この部分を削除しています。

2020-10-19 03:43 UTC, merged