feat/gw-3524
weseek/growi pull request #2918
Opened 2020-10-19 08:23 UTC by takeru0001

2020-10-19 08:25 UTC, takeru0001 commented
<img width="914" alt="スクリーンショット 2020-10-19 17 20 14" src="https://user-images.githubusercontent.com/58085267/96420088-fea63380-122f-11eb-94e1-9145061fd801.png">

<img width="914" alt="スクリーンショット 2020-10-19 17 20 24" src="https://user-images.githubusercontent.com/58085267/96420109-0534ab00-1230-11eb-9fa7-107ad84cea54.png">

<img width="607" alt="スクリーンショット 2020-10-19 17 20 47" src="https://user-images.githubusercontent.com/58085267/96420120-0960c880-1230-11eb-9969-55f057fd4e3c.png">

2020-10-19 08:28 UTC, takeru0001 commented
画像は`/test`から`/test9にrename`する場面です。
`/test9`というページは存在しないが`/test9/test2`,`test9/test/test/test`はすでに存在するので下のテーブルで表示しています。

2020-10-19 08:32 UTC, takeru0001 commented
三枚目はdebounceによって`/test9`で一回apiをたたき、連続で`999999999`と入力してもapi は合計二回しか叩かれていないことを示す画像です。

2020-10-19 11:21 UTC, yuki-takei requested changes

2020-10-19 11:21 UTC, yuki-takei commented on src/client/js/components/PageRenameModal.jsx
> +      const res = await appContainer.apiv3Get('/page/exist-paths', { newParentPath: pageNameInput, toPaths });
get param に無制限に文字列がくっつくこの方式ではそもそも API 呼び出しに失敗する可能性がある(通信で url として受け付けられる最長の長さが決められている)

get body を受け取れる/投げられるようにするなど、API 側と apiv3Get 両方の改修が必要。

2020-10-19 11:21 UTC, yuki-takei commented on src/client/js/components/PageRenameModal.jsx
> +      const res = await appContainer.apiv3Get('/page/exist-paths', { newParentPath: pageNameInput, toPaths });
あとそもそもの話、上記の get param の最大長の問題を棚上げにしたとして、ここで頼りにしてる `/page/exist-paths` は、GW-3028 の説明にある仕様を満たしている？

2020-10-20 04:15 UTC, takeru0001 commented on src/client/js/components/PageRenameModal.jsx
> +      const res = await appContainer.apiv3Get('/page/exist-paths', { newParentPath: pageNameInput, toPaths });
## 重複チェックの仕様について

- サーバー側で重複しているかどうかを判別する
- クライアントは、fromPath と toPath、それから isRecursively をサーバーに送る
- サーバー側の API (新規実装) で、to 側に既に存在するパスリストを作ってクライアントに返す
- クライアントは上記を受け取り、重複しているパスのリストを表示する

GW-3028の使用は満たいていると思っていますが、念の為確認お願いします。

一点だけ上記の仕様と違うのはクライアントは`newParentPath`として新しい親のパスと`toPaths`として配列で変化後のパスたちを送っている点は違います。

`router.get('/exist-paths', loginRequired, validator.exist, apiV3FormValidator, async(req, res) => {
    const { newParentPath, toPaths } = req.query;

    try {
      const { pages } = await Page.findListByStartWith(newParentPath, req.user);

      const duplicationPaths = pages.map((page) => {
        if (toPaths.includes(page.path)) {
          return page.path;
        }
        return null;
      });
      const existPaths = duplicationPaths.filter(path => path != null);

      return res.apiv3({ existPaths });

    }
    catch (err) {
      logger.error('Failed to get exist path', err);
      return res.apiv3Err(err, 500);
    }

  });`

2020-10-20 07:21 UTC, takeru0001 commented
<img width="698" alt="スクリーンショット 2020-10-20 16 11 49" src="https://user-images.githubusercontent.com/58085267/96553590-56a46f00-12f0-11eb-8bb3-6d08b189caf3.png">

2020-10-20 07:22 UTC, takeru0001 commented
fromPathとtoPathをクライアントから渡して検索する方法に変更しました。

2020-10-20 08:36 UTC, yuki-takei requested changes

2020-10-20 08:36 UTC, yuki-takei commented on src/server/routes/apiv3/page.js
> +    const { fromPath, toPath } = req.query;
jsdoc も書き換えてください

2020-10-20 08:36 UTC, yuki-takei commented on src/server/routes/apiv3/page.js
> +      const fromPathDescendantsArray = fromPageDescendants.map((subordinatedPage) => {
- fromPage 自体が入ってないのではないか
- かつ、fromPage が managable ではない場合の対処が必要

2020-10-20 08:36 UTC, yuki-takei commented on src/server/routes/apiv3/page.js
> +      const toPathDescendantsArray = toPageDescendants.pages.map(page => page.path);
このロジックは無駄なので、DB に対して `fromPathDescendantsArray` の中で存在するものだけを探すようにする。おそらく models/page.js に専用のメソッドはないので、PageQueryBuilder を使う。

2020-10-20 09:10 UTC, takeru0001 commented on src/server/routes/apiv3/page.js
> +    const { fromPath, toPath } = req.query;
書き換えました

2020-10-20 12:31 UTC, takeru0001 commented
<img width="662" alt="スクリーンショット 2020-10-20 21 28 35" src="https://user-images.githubusercontent.com/58085267/96586177-9765ad80-131b-11eb-922e-cdfdff7d448b.png">

2020-10-20 12:33 UTC, takeru0001 commented
`fromPath`から取得した`fromPathDescendantsArray`がDBの中に存在するかを見つけるロジックに変更しました。

2020-10-20 12:34 UTC, takeru0001 commented on src/server/routes/apiv3/page.js
> +      const toPathDescendantsArray = toPageDescendants.pages.map(page => page.path);
作成し、適応させました。

2020-10-20 12:36 UTC, takeru0001 commented on src/server/routes/apiv3/page.js
> +      const fromPathDescendantsArray = fromPageDescendants.map((subordinatedPage) => {
`fromPage`が`fromPathDescendants`に含まれていることを確認したので、問題解消しました。

2020-10-22 04:04 UTC, itizawa commented on src/server/routes/apiv3/page.js
> +      const fromPageDescendants = await Page.findManageableListWithDescendants(fromPage, req.user);
findListByStartWith が使えないかどうかの確認。
そのユーザーが見れないページを持ってこれたら使えない。

2020-10-22 04:40 UTC, takeru0001 commented on src/server/models/page.js
> +  }
解決しました。

2020-10-22 05:17 UTC, takeru0001 commented on src/server/models/page.js
> +  }
解決済み

2020-10-22 05:17 UTC, takeru0001 commented on src/server/routes/apiv3/page.js
> +      const fromPageDescendants = await Page.findManageableListWithDescendants(fromPage, req.user);
<img width="529" alt="スクリーンショット 2020-10-22 14 16 24" src="https://user-images.githubusercontent.com/58085267/96827823-60091500-1471-11eb-9f95-965bcd1bea5c.png">

2020-10-22 05:18 UTC, takeru0001 commented on src/server/routes/apiv3/page.js
> +      const fromPageDescendants = await Page.findManageableListWithDescendants(fromPage, req.user);
<img width="971" alt="スクリーンショット 2020-10-22 14 15 18" src="https://user-images.githubusercontent.com/58085267/96827852-6e573100-1471-11eb-95ff-66c71a627344.png">

<img width="597" alt="スクリーンショット 2020-10-22 14 17 04" src="https://user-images.githubusercontent.com/58085267/96827863-73b47b80-1471-11eb-9324-07ceaa011140.png">

2020-10-22 05:19 UTC, takeru0001 commented on src/server/routes/apiv3/page.js
> +      const fromPageDescendants = await Page.findManageableListWithDescendants(fromPage, req.user);
`/test9/test/test3`は閲覧できないが、パスは取ってきてしまうことを確認しました。

2020-10-22 05:25 UTC, merged