feat/GW-4166-refactor-setup-uploader
weseek/growi pull request #2930
Opened 2020-10-20 13:10 UTC by yusuketk

2020-10-21 02:40 UTC, yuki-takei requested changes

2020-10-21 02:40 UTC, yuki-takei commented on src/server/service/file-uploader/index.js
> +    const method = envToModuleMappings[crowi.configManager.getConfig('crowi', 'app:fileUploadType')] || 'aws';
`aws` がデフォルトで返るのも config-loader に任せられそう

2020-10-22 06:04 UTC, yusuketk commented on src/server/service/file-uploader/index.js
> +    const method = envToModuleMappings[crowi.configManager.getConfig('crowi', 'app:fileUploadType')] || 'aws';
config-loader でデフォルト値が `aws` になるように変更しました

2020-10-22 06:33 UTC, yuki-takei requested changes

2020-10-22 06:33 UTC, yuki-takei commented on src/server/service/config-manager.js
> +      || KEYS_FOR_FIEL_UPLOAD_USE_ONLY_ENV_OPTION.includes(key)
`&& this.defaultSearch('crowi', 'security:passport-saml:useOnlyEnvVarsForSomeOptions')`
にあたるものとセットじゃないといけない。このままでは DB の値よりも env var の `FILE_UPLOAD` の方が常に強くなってしまう。

2020-10-22 06:45 UTC, yusuketk commented on src/server/service/config-manager.js
> +      || KEYS_FOR_FIEL_UPLOAD_USE_ONLY_ENV_OPTION.includes(key)
今回のストーリーではおっしゃったとおりの挙動のままで、GW-4172の中で対応するつもりでした。GW-3658ストーリーでのファイルアップロード設定フォームの挙動に合わせた方が良いと思い(環境変数が最優先のようなアラートが表示される）。
なのでコメントを追記しました.

2020-10-22 07:00 UTC, merged