Imprv/4079 set default ative tab
weseek/growi pull request #2935
Opened 2020-10-22 05:48 UTC by kaoritokashiki

2020-10-22 06:29 UTC, yuki-takei requested changes

2020-10-22 06:29 UTC, yuki-takei commented on src/client/js/components/CustomNavigation.jsx
> +  const [defaultActiveTab, setDefaultActiveTab] = useState('');
defaultActiveTab などという state はいらないなあ

2020-10-22 06:29 UTC, yuki-takei commented on src/client/js/components/CustomNavigation.jsx
> +  const [defaultActiveTab, setDefaultActiveTab] = useState('');
defaultActiveTab などという state はいらないなあ

2020-10-22 06:29 UTC, yuki-takei commented on src/client/js/components/CustomNavigation.jsx
> +  const mounted = useRef(false);
useRef の使い方が違う

2020-10-28 15:42 UTC, yuki-takei requested changes

2020-10-28 15:42 UTC, yuki-takei commented on src/client/js/components/CustomNavigation.jsx
> +    const navTabs = tabs;
この局所変数の再定義、無意味では？

2020-10-28 15:42 UTC, yuki-takei commented on src/client/js/components/CustomNavigation.jsx
> +      <div ref={nav}>
nav-container とかにしよう

2020-10-29 03:41 UTC, kaoritokashiki commented on src/client/js/components/CustomNavigation.jsx
> +      <div ref={nav}>
囲む範囲をnavBarに変更したので変数名はnavBarにしました。

2020-10-29 03:43 UTC, kaoritokashiki commented on src/client/js/components/CustomNavigation.jsx
> +    const navTabs = tabs;
navとtabsの変数名をそれぞれnavBar, navTabsに変更しました。
よって再定義は削除しました。

2020-10-29 03:46 UTC, merged