Imprv/gw4156 layout adjustment for bookmarks and recentchanges
weseek/growi pull request #2936
Opened 2020-10-22 06:50 UTC by kaoritokashiki

2020-10-22 06:58 UTC, kaoritokashiki commented on src/client/styles/scss/_layout_growi.scss
> +      margin-bottom: 6px;
これは、アイコンとh1タグのテキストとずれていたために、margin-buttomを使用することで修正しました。

bootstrapのvertical-middleなど、色々試してみましたが、変わらず。
おそらくsvgアイコンなので他の要素と同じようにうごえてくれないと認識しました。

2020-10-22 07:08 UTC, yuki-takei requested changes

2020-10-22 07:08 UTC, yuki-takei commented on src/client/styles/scss/_layout_growi.scss
> +      margin-bottom: 6px;
そもそもこのブロックなんで `_layout_growi` にあるんだっけ…
kibela レイアウトには適用しない独立した指定なのか？

そうじゃなければ `_page_list` に移すべき。

2020-10-22 07:08 UTC, yuki-takei commented on src/client/styles/scss/_page_list.scss
> +      margin: 10px;
これは今回の編集箇所以外、全ての `.page-list` に影響が出ても問題ないことを確認済み？

2020-10-23 06:35 UTC, kaoritokashiki commented on src/client/styles/scss/_layout_growi.scss
> +      margin-bottom: 6px;
確かにそうですね。ただ現状Kibelaもtheme化されているからかわかりませんが、layout_growinのみでもちゃんと適用はされています。

2020-10-23 08:40 UTC, kaoritokashiki commented on src/client/styles/scss/_page_list.scss
> +}
page_list.scssの方に移動させました。

2020-10-23 08:42 UTC, kaoritokashiki commented on src/client/styles/scss/_page_list.scss
> +      margin: 0.5rem;
mosさんと話し合いの結果、全体的に統一させた方がありがたいということでした。
また、px→remでの記述に変更しました。

2020-10-23 08:42 UTC, kaoritokashiki commented
<img width="970" alt="Screen Shot 2020-10-23 at 12 24 56" src="https://user-images.githubusercontent.com/59536731/96976730-24e11180-1557-11eb-939e-5b1387cf0e91.png">
<img width="441" alt="Screen Shot 2020-10-23 at 15 36 55" src="https://user-images.githubusercontent.com/59536731/96976735-26123e80-1557-11eb-8183-e21cb65c5e7b.png">
<img width="733" alt="Screen Shot 2020-10-23 at 15 54 36" src="https://user-images.githubusercontent.com/59536731/96976737-26123e80-1557-11eb-8982-983cca2a284d.png">
<img width="546" alt="Screen Shot 2020-10-23 at 15 55 09" src="https://user-images.githubusercontent.com/59536731/96976739-26aad500-1557-11eb-9d1f-cfe5d1a92634.png">

2020-10-26 07:25 UTC, merged