rename env var
weseek/growi pull request #2943
Opened 2020-10-23 04:22 UTC by yusuketk

2020-10-28 15:30 UTC, yuki-takei requested changes

2020-10-28 15:30 UTC, yuki-takei commented on src/server/routes/apiv3/app-settings.js
> +      useOnlyEnvVarsForFileUploadType: crowi.configManager.getConfigFromEnvVars('crowi', 'app:useOnlyEnvVarsForFileUploadType'),
これって単純に getConfig でいいんじゃないの？

2020-10-28 15:30 UTC, yuki-takei commented on src/server/service/config-loader.js
> +  FILE_UPLOAD_USES_ONLY_ENV_VARS_FOR_SOME_OPTIONS: {
これは 'app:fileUploadType' について env var を優先するかどうか、なのでは？
そうだとすると「FOR_SOME_OPTIONS」という表現はおかしい。

2020-10-29 04:56 UTC, yusuketk commented on src/server/service/config-loader.js
> +  FILE_UPLOAD_USES_ONLY_ENV_VARS_FOR_SOME_OPTIONS: {
そうでした。。変更しました。

2020-10-29 04:57 UTC, yusuketk commented on src/server/routes/apiv3/app-settings.js
> +      useOnlyEnvVarsForFileUploadType: crowi.configManager.getConfigFromEnvVars('crowi', 'app:useOnlyEnvVarsForFileUploadType'),
そうですね。。修正しました。

2020-10-29 08:54 UTC, merged