Feat/4172 4175 expand form for local gridfs
weseek/growi pull request #2952
Opened 2020-10-26 05:12 UTC by itizawa

2020-10-26 07:41 UTC, yuki-takei requested changes

2020-10-26 07:41 UTC, yuki-takei commented on resource/locales/en_US/admin/admin.json
> +    "gridfs_label": "GridFS",
MongoDB(GridFS) という表記で

2020-10-26 07:41 UTC, yuki-takei commented on src/client/js/services/AdminAppContainer.js
> +    return this.updateFileUploadTypeHandler();
このメソッドのロジックちょっと違和感がある…

aws/gcp じゃなければ、タイプを更新するハンドラーを実行する必要があるのか？
もしくは aws/gcp の時には、タイプを更新する必要はないのか？

2020-10-28 17:38 UTC, itizawa commented
https://dev.growi.org/5f99a08e9d9ead0049f0ab80
外部仕様

2020-10-28 17:43 UTC, itizawa commented on src/server/routes/apiv3/app-settings.js
> +      gcsUseOnlyEnvVars: crowi.configManager.getConfig('crowi', 'gcs:isGcsEnvPrioritized'),
typo

2020-10-29 12:43 UTC, merged