imprv/gw4178
weseek/growi pull request #2955
Opened 2020-10-26 06:06 UTC by makotoshiraishi

2020-10-26 06:16 UTC, makotoshiraishi commented
「Bookmarks」ボタンと「Recently Created」ボタンの位置が画面からはみ出ていたため、`.grw-page-content-container`の幅を小さくすることによりスタイルを修正しました。
幅の指定は`.col-lg-9`にして次の`.col-lg-3`と合わせて12になるように設定しました。

2020-10-26 06:23 UTC, makotoshiraishi commented
<img width="1652" alt="スクリーンショット 2020-10-26 15 20 03" src="https://user-images.githubusercontent.com/64956659/97139894-da51d600-179e-11eb-8cca-73304a73b869.png">

<img width="1645" alt="スクリーンショット 2020-10-26 15 22 47" src="https://user-images.githubusercontent.com/64956659/97140049-30bf1480-179f-11eb-8966-4ae46412d508.png">

2020-10-26 06:26 UTC, makotoshiraishi commented on src/server/views/layout-growi/page.html
下記の col-lg-3に合わせました。
col-xl-2に合わせなかったのは、それだとコンテンツモーダルが右にはみ出たままになるからです。

原因はおそらく、コンテンツモーダルの幅がcol-xs-2に収まらないくらい横幅をとっているからだと推測しています(各Iconや左右のマージンにより)。

2020-10-26 07:33 UTC, yuki-takei commented
デザインスペック的には 9:3 で分けるような思想だったんだっけ？確認を。

2020-10-29 04:41 UTC, makotoshiraishi commented
TakeiさんのFBについて：
デザインスペックは確認したところ、9:3で分けるのではなく、col-`hoge`というのは使わないで、TOCの幅は固定(250px)で真ん中のページが画面幅に合うように調整する設計にする意向だったのでそのように実装しました。
具体的には`col,row`は全部削除して、`display:flex` をしようするようにしました。

2020-10-29 04:48 UTC, makotoshiraishi commented on src/server/views/layout-growi/page_list.html
> +  <div class="grw-page-content d-flex">
page_list.htmlも表示のバグがあったので、変更を加えました。

2020-10-29 05:06 UTC, makotoshiraishi commented
![weseek](https://user-images.githubusercontent.com/64956659/97527955-eed8dd00-19ef-11eb-9708-03c6eaa82a08.gif)

2020-10-29 07:47 UTC, yuki-takei requested changes

2020-10-29 07:47 UTC, yuki-takei commented on src/server/views/layout-growi/page.html
> +    <div class="grw-page-content-container w-100">
flexbox を使うのであれば、伸縮は w-100 ではない

2020-10-29 07:47 UTC, yuki-takei commented on src/server/views/layout-growi/page.html
> +    <div class="d-none d-lg-block revision-toc-container">
こちらは OK

2020-10-29 09:20 UTC, makotoshiraishi commented on src/server/views/layout-growi/page.html
> +    <div class="grw-page-content-container w-100">
w-100ではなく、flexで余白の使い方を指定できるflex-growに変更しました。

2020-10-29 09:26 UTC, merged