Imprv/gw3983 border dark theme
weseek/growi pull request #2966
Opened 2020-10-27 08:15 UTC by oshikishintaro

# GW-3983 dark系テーマのボーダー色調整
## 作業内容
- ダークテーマにおいて、規定した3種以外のボーダー変数が効いていない箇所を洗い出し、変数を適用。
- ボーダー色を　デザインスペックに合わせ明るいものに（変数の兼ね合いで完全再現ではない）
※全テーマを通しての確認は後続タスクにて
## 変更後の見た目
<img width="1440" alt="スクリーンショット 2020-10-27 16 42 28" src="https://user-images.githubusercontent.com/65531771/97273803-21ab9580-1877-11eb-8ada-43635b38b04d.png">

2020-10-27 09:47 UTC, yuki-takei requested changes

2020-10-27 09:47 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +$border-color: $secondary;
secondary をグレーだと思い込むのはまず間違い

2020-10-27 09:47 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
apply-colors-light と同じ記述なら、分ける必要がない

2020-10-27 09:47 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
border-color を適用する行を書くのではなく、bs4 の variables を上書きすることで適用させる(極力)

2020-10-27 09:47 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +    @include border-vertical('before', $border-color, 70%);
これは元に戻す($bordercolor-toc の存在意義がなくなってしまう)

2020-10-30 07:35 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors.scss
> +    @include border-vertical('before', $border-color, 70%);
$bordercolor-tocという変数がこの箇所しか使われていなかったので、存在意義 無いなと思い削除しました。（BS4の変数とかでもない）
カラー的にも本来$border-colorが当たるべき場所でしたので、このような変更になっています。

2020-10-30 07:47 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
apply-colors-dark以前に読み込まれるscssで`$border-color`という変数が指定されている箇所なので、
apply-colors-darkで再定義しないと別の色（override-bootstrap-variablesで指定した$gray-300）が入ってしまいます。
そのため、この行は必要だと考えます。

2020-10-30 07:50 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
こちらも
apply-colors-dark以前に読み込まれるscssで`$border-color`という変数が指定されている箇所なので、
apply-colors-darkで再定義しないと別の色（override-bootstrap-variablesで指定した$gray-300）が入ってしまいます。

2020-10-30 09:29 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +$border-color: $secondary;
$gray-500に変更しました。

2020-10-30 10:32 UTC, yuki-takei requested changes

2020-10-30 10:32 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
そういう意味ではなく、

https://github.com/twbs/bootstrap/blob/v4.5.0/scss/_modal.scss#L146

を参考に、`_reboot-bootstrap-modal.scss` を作って、

```
.modal-header {
  border-bottom-color: $modal-header-border-color;
}
```

を書くべきではないかと。`_apply-colors-dark.scss` には `$modal-header-border-color: $border-color;` を入れる。

2020-10-30 13:23 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
`reboot-bootstrap-modal.scss`を作成し、$grw-moda-headの色指定方法を変更しました。
`reboot-bootstrap-modal.scss`にはborderに関するものしか書いていませんが、
layout.scssの内容 など、modalに関する記述をこちらに引越した方が良いでしょうか？

2020-11-02 10:03 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
## 完成形

`_apply-colors-*.scss` に対して

```
.grw-modal-head {
  border-color: ;
}
```

を書くところまではよい。

2020-11-02 10:13 UTC, yuki-takei requested changes

2020-11-02 10:13 UTC, yuki-takei commented on src/client/styles/scss/_layout_growi.scss
> +    border-bottom: 1px solid $border-color;
theme でやるべき、元に戻す

2020-11-02 10:13 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +@import 'reboot-bootstrap-modal';
これは不要だったごめん

2020-11-02 10:13 UTC, yuki-takei commented on src/client/styles/scss/_layout.scss
> +  border-bottom: 1px solid $modal-header-border-color;
layout では色は決めない、theme に任せるので transparent

2020-11-02 10:13 UTC, yuki-takei commented on src/client/styles/scss/_layout_growi.scss
> +    border-bottom: 1px solid $border-color;
layout では色は決めない、theme に任せるので transparent

2020-11-02 10:13 UTC, yuki-takei commented on src/client/styles/scss/_layout.scss
> +  border-bottom: 1px solid $modal-header-border-color;
`$modal-header-border-color;` を上書きするのは勘違いだったので、`$border-color` でよい。

2020-11-02 10:13 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +$modal-header-border-color: $border-color;
これは不要だったごめん

2020-11-02 10:13 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +  border-color: $border-color;
:+1:

2020-11-02 10:13 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +  border-color: $border-color;
:+1:

2020-11-02 10:48 UTC, oshikishintaro commented on src/client/styles/scss/_layout.scss
> +  border-bottom: 1px solid $modal-header-border-color;
カラーをtransparentに変更し`apply-colors-light`と`apply-colors-dark`にカラー指定を追加しました

2020-11-02 11:13 UTC, oshikishintaro commented on src/client/styles/scss/_layout_growi.scss
> +    border-bottom: 1px solid $border-color;
カラーをtransparentに変更しapply-colors-lightにカラー指定を追加しました

2020-11-02 11:48 UTC, merged