add fill in svg
weseek/growi pull request #2972
Opened 2020-10-28 15:42 UTC by zahmis

2020-10-29 07:57 UTC, yuki-takei requested changes

2020-10-29 07:57 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
_reboot-bootstrap-theme-colors を改修して、svg アイコンの色が付くようにしてください。

2020-10-29 07:57 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
## 理想型

```
@each $color, $value in $theme-colors {
  .btn-#{$color} {
    @include button-variant($value, $value);
    @include button-svg-icon-variant($value, $value);
  }
}
@each $color, $value in $theme-colors {
  .btn-outline-#{$color} {
    @include button-outline-variant($value, $color-hover: $value, $active-background: rgba($value, 0.1), $active-border: $value);
    @include button-outline-svg-icon-variant($value, $color-hover: $value);

    &:not(:disabled):not(.disabled):active,
    &:not(:disabled):not(.disabled).active,
    .show > &.dropdown-toggle {
      color: $value;
    }
  }
}

```

2020-10-29 16:22 UTC, zahmis commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
修正します。

2020-10-29 16:35 UTC, zahmis commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
この問題の修正することによって、GW-4242 も解消しました。

2020-10-29 18:09 UTC, yuki-takei requested changes

2020-10-29 18:09 UTC, yuki-takei commented on src/client/styles/scss/theme/_reboot-bootstrap-theme-colors.scss
> +}
違うね…これでは引数が全く意味を成していないじゃないか。
これでは `.btn-outline-primary` も、 `.btn-outline-danger` も、アイコンの色だけ `$secondary` になってしまうよ。

2つめに、hover 時や active 時のケアができていない。ちゃんと button-variant や vutton-outline-variant のソースを見て。

2020-10-30 05:09 UTC, zahmis commented on src/client/styles/scss/theme/_reboot-bootstrap-theme-colors.scss
> +}
すみません。再び改修しました。
@mixin button-svg-icon-variant ... は今回直接は関係ないのですが、
理想型を参考に改修しました。
これによって、使用されている場所での active 状態を確認することができました。

2020-10-30 06:16 UTC, yuki-takei requested changes

2020-10-30 06:16 UTC, yuki-takei commented on src/client/styles/scss/theme/_reboot-bootstrap-theme-colors.scss
> +    border-color: $bordercolor;
border-color 必要なの？

2020-10-30 06:42 UTC, zahmis commented on src/client/styles/scss/theme/_reboot-bootstrap-theme-colors.scss
> +    border-color: $bordercolor;
影響がなかったので削除します。

2020-10-30 06:54 UTC, yuki-takei requested changes

2020-10-30 06:54 UTC, yuki-takei commented on src/client/styles/scss/theme/_reboot-bootstrap-theme-colors.scss
> +}
```
@mixin button-svg-icon-variant($background, $hover-background: darken($background, 7.5%), $active-background: darken($background, 10%)) {
  svg {
    fill: color-yiq($background);
  }

  @include hover() {
    svg {
      fill: color-yiq($hover-background);
    }
  }

  &:focus,
  &.focus {
    svg {
      fill: color-yiq($hover-background);
    }
  }

  // Disabled comes first so active can properly restyle
  &.disabled,
  &:disabled {
    svg {
      color: color-yiq($background);
    }
  }

  &:not(:disabled):not(.disabled):active,
  &:not(:disabled):not(.disabled).active,
  .show > &.dropdown-toggle {
    svg {
      color: color-yiq($active-background);
    }
  }
}
```

2020-10-30 06:54 UTC, yuki-takei requested changes

2020-10-30 06:54 UTC, yuki-takei commented on src/client/styles/scss/theme/_reboot-bootstrap-theme-colors.scss
> +    @include button-svg-icon-variant($value);
```
@include button-svg-icon-variant($value, $value);
```

2020-10-30 07:22 UTC, merged