imprv/userhome-renovation-gw4212
weseek/growi pull request #2977
Opened 2020-10-29 06:06 UTC by makotoshiraishi

2020-10-29 06:23 UTC, makotoshiraishi commented
XDに合わせて、ユーザページのBookmarksのstyleを微修正しました。
具体的には以下の画像を修正しました。

<img width="1043" alt="スクリーンショット 2020-10-29 15 19 01" src="https://user-images.githubusercontent.com/64956659/97532912-abd03700-19fa-11eb-92f6-87260418f864.png">

2020-10-29 09:00 UTC, yuki-takei requested changes

2020-10-29 09:00 UTC, yuki-takei commented on src/client/js/components/PageList/Page.jsx
> +    let pagePathElem = <PagePathLabel page={page} additionalClassNames={['mx-1', 'align-middle']} />;
この align-middle は、Page から PagePathLabel を利用する場合にのみ追加したいということ？

2020-10-29 09:00 UTC, yuki-takei commented on src/client/js/components/PageList/PageListMeta.jsx
> +      <span className="page-list-meta align-middle">
この align-middle は、PageListMeta 自体に対して常に指定して問題ない？(他でレイアウト崩れがなければよさそうではある)

2020-10-29 09:00 UTC, yuki-takei commented on src/client/styles/scss/_page_list.scss
> +}
1. MyBookmarkList で使っている `page-list-container-create` という名前が微妙なので変えてください
1. 上記の利用状況だけで margin-bottom が必要なのであれば、_page_list.scss に追加するのは相応しくない

2020-10-30 05:18 UTC, yusuketk commented on src/client/js/components/PageList/PageListMeta.jsx
> +      <span className="page-list-meta align-middle">
検索窓で若干変わりますね
- align-middle なし
<img width="223" alt="Screen Shot 2020-10-30 at 14 14 33" src="https://user-images.githubusercontent.com/38426468/97662467-89055780-1aba-11eb-9618-8b6d3a99daef.png">

- align-middle あり
<img width="223" alt="Screen Shot 2020-10-30 at 14 14 06" src="https://user-images.githubusercontent.com/38426468/97662464-87d42a80-1aba-11eb-9529-2b304f328a31.png">

2020-10-30 07:55 UTC, yusuketk commented on src/server/views/layout-growi/user_page.html
> +    <div class="grw-page-list-m mt-5 pb-5">
.page-list-container-create { margin-bottom: 130px; } の代わりにbookmarks list と recent changes list に .mt-5 .pb-5を付けました

2020-10-30 07:55 UTC, yusuketk commented on src/server/views/layout-growi/widget/comments.html
> +    <h2 class="border-bottom pb-2 mb-3"><i class="icon-fw icon-bubbles"></i> Comments</h2>
タスクの詳細にこの部分もh2にすると書いてあったため追加変更しました

2020-10-30 07:55 UTC, yusuketk commented on src/server/views/layout-growi/user_page.html
> +      <h2 class="grw-page-list-title-m border-bottom pb-2 mb-3">
タスクの詳細にこの部分もh2にすると書いてあったため追加変更しました

2020-10-30 07:55 UTC, yusuketk commented on src/server/views/layout-growi/user_page.html
> +      <h2 class="grw-page-list-title-m border-bottom pb-2 mb-3">
タスクの詳細にこの部分もh2にすると書いてあったため追加変更しました

2020-10-30 08:08 UTC, yusuketk commented
[GW-4249 Recent Created list の文字サイズ調整] もついでに行いました
タスクの詳細のもと以下の画像になるように変更しました。mosさん(今タスクの提案者)によるデザインチェックは済んでいます。
アイコンとページパスの上下位置の調整のみ修正に行き詰まったためmakoto-s さんの修正方法のままにし別タスクに切り分けました。(https://youtrack.weseek.co.jp/issue/GW-4268)

<img width="1569" alt="Screen Shot 2020-10-30 at 17 04 03" src="https://user-images.githubusercontent.com/38426468/97675267-5b2c0d00-1ad2-11eb-9e80-b4abef7c8590.png">

2020-10-30 08:39 UTC, merged