Imprv/link bookmark and recently created with anchor tag
weseek/growi pull request #2979
Opened 2020-10-29 06:28 UTC by zahmis

2020-10-29 07:02 UTC, zahmis reviewed
bug
#Bookmark  からの #hackmd へ飛んだとき、
 
<img width="1988" alt="スクリーンショット 2020-10-29 15 27 23" src="https://user-images.githubusercontent.com/57100766/97536115-0324d600-1a00-11eb-9678-c1a9a0d36cef.png">

↓

<img width="2032" alt="スクリーンショット 2020-10-29 15 42 52" src="https://user-images.githubusercontent.com/57100766/97536187-218ad180-1a00-11eb-9757-39e8dc0ed338.png">

2020-10-29 07:02 UTC, zahmis commented on src/server/views/layout-growi/user_page.html
> +    <div class="grw-page-list-m my-5 d-edit-none">
bug を発見して、それの処理です。

2020-10-29 09:04 UTC, yuki-takei requested changes

2020-10-29 09:04 UTC, yuki-takei commented on src/client/js/components/TableOfContents.jsx
> +        <a className="btn btn-outline-secondary btn-sm" href="#bookmarks-list">
NavigationContainer の smoothScrollIntoView を使ってください。

2020-10-30 09:18 UTC, itizawa commented on src/client/js/components/TableOfContents.jsx
> +  const getRecentlyCreatedListHeaderDom = useMemo(() => { return document.getElementById('recently-created-list') }, []);
一度だけ取得すればいいので dependency array は 空。

2020-10-30 09:30 UTC, merged