improve could'nt create page
weseek/growi pull request #3027
Opened 2020-11-05 04:44 UTC by kaoritokashiki

2020-11-09 07:15 UTC, kaoritokashiki commented
`couldn't creage page`を作成しようとした際にはedit modenにならないようにしました。

<img width="1209" alt="Screen Shot 2020-11-09 at 16 14 10" src="https://user-images.githubusercontent.com/59536731/98510539-a7333a80-22a6-11eb-8c0d-73272a8b4f35.png">

2020-11-09 07:16 UTC, kaoritokashiki commented on src/client/js/legacy/crowi.js
> +    if (window.location.hash === '#edit' && isPageExist && !isPageForbidden && !isNotCreatable && !isTrashPage) {
```
・ページがある
　・かつログイン済み
・forbidden ではない
・not creatable ではない
・ゴミ箱に入っていない
```

2020-11-09 07:19 UTC, kaoritokashiki commented on src/server/views/widget/not_creatable_content.html
> -<div class="row not-found-message-row mb-4">
` Couldn't create path` の下にはコンテンツがないのでmargin付けなくても変化ありませんでしたので削除しました。

2020-11-09 07:36 UTC, kaoritokashiki commented on src/client/js/legacy/crowi.js
> +    if (window.location.hash === '#edit' && isPageExist && (currentUser != null) && !isPageForbidden && !isNotCreatable && !isTrashPage) {
```
・ページがある
　・かつログイン済み
・forbidden ではない
・not creatable ではない
・ゴミ箱に入っていない
```

2020-11-09 07:41 UTC, yuki-takei requested changes

2020-11-09 07:41 UTC, yuki-takei commented on src/client/js/legacy/crowi.js
> +    if (window.location.hash === '#edit' && isPageExist && (currentUser != null) && !isPageForbidden && !isNotCreatable && !isTrashPage) {
上記を満たす getter を pageContainer に新設してください。

2020-11-10 06:49 UTC, yuki-takei requested changes

2020-11-10 06:49 UTC, yuki-takei commented on src/client/js/services/PageContainer.js
> +  get editablePages() {
`get isEditable()` にしてください

2020-11-10 06:49 UTC, yuki-takei commented on src/client/js/services/PageContainer.js
> +    const { currentUser } = appContainer;
`this.appContainer` から取得する

2020-11-10 06:49 UTC, yuki-takei commented on src/client/js/legacy/crowi.js
> +  const editablePages = pageContainer;
この行おかしい

2020-11-10 08:06 UTC, kaoritokashiki commented on src/client/js/legacy/crowi.js
> +  const { isEditable } = pageContainer;
修正しました。

2020-11-10 08:09 UTC, kaoritokashiki commented on src/client/js/services/PageContainer.js
> +    const { currentUser } = this.appContainer;
windowから持ってくる必要なかったですね。修正しました。

2020-11-10 08:17 UTC, merged