Imprv/gw3918 border redesign for master marge
weseek/growi pull request #3044
Opened 2020-11-06 06:19 UTC by oshikishintaro

# ストーリー GW-3918 デザインリファクタ：ボーダー色の整理
- このプルリクでの新規 変更点：なし
- デザインチェック通過済み
## 変更後スクリーンショット
- Default-light
![image](https://user-images.githubusercontent.com/65531771/98333027-3a6c3600-2043-11eb-8a02-32fcbca69569.png)
- Default-dark
![image](https://user-images.githubusercontent.com/65531771/98333060-4952e880-2043-11eb-8a12-8664dfcedb8a.png)
- island
![image](https://user-images.githubusercontent.com/65531771/98331993-232c4900-2041-11eb-8e83-3bce51029e2f.png)
- spling
![image](https://user-images.githubusercontent.com/65531771/98333128-68ea1100-2043-11eb-82aa-89e3e3c204d8.png)

2020-11-06 07:26 UTC, yuki-takei requested changes

2020-11-06 07:26 UTC, yuki-takei commented on src/client/styles/scss/_override-bootstrap-variables.scss
> +$border-color: $gray-300 !default;
これはそもそもオフィシャルの _variables.scss で設定されてるけど必要？

https://github.com/twbs/bootstrap/blob/v4.5.0/scss/_variables.scss#L243

2020-11-06 07:26 UTC, yuki-takei commented on src/client/styles/scss/_override-bootstrap-variables.scss
> +$input-border-color: $border-color;
オフィシャルでは $border-color とは濃さを変えてるけど、一緒にするの？
https://github.com/twbs/bootstrap/blob/v4.5.0/scss/_variables.scss#L482

2020-11-06 07:26 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +$border-color: $gray-500;
apply-colors-dark からはこの変数自体消した方がいいかも…
このファイルで設定している border-color 以外には新たに設定した `$border-color: $gray-500;` は適用されないのに、あたかもシステム全体の `$border-color` を書き換えてくれるんじゃないかと混乱しそう。

2020-11-06 07:29 UTC, yuki-takei requested changes

2020-11-06 07:29 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +  border-color: $border-color;
独自の変数名じゃなく `$border-color` を使うのやっぱやだなあ

2020-11-06 07:29 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +      border-right-color: $border-color;
独自の変数名じゃなく `$border-color` を使うのやっぱやだなあ

2020-11-06 07:29 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +.top-of-table-contents {
このクラスなくなったはず

2020-11-06 07:29 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +  .top-of-table-contents {
このクラスなくなったはず

2020-11-09 08:51 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +  .top-of-table-contents {
`.top-of-table-contents`該当クラスを削除し、セレクタの指定を変更しました。

2020-11-09 08:51 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors.scss
> +.top-of-table-contents {
`.top-of-table-contents`該当クラスを削除し、セレクタの指定を変更しました。

2020-11-10 08:14 UTC, oshikishintaro commented on src/client/styles/scss/_override-bootstrap-variables.scss
> +$border-color: $gray-300 !default;
$border-colorの使用箇所縮小に伴い必要なくなったため、削除しました

2020-11-10 08:26 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +$border-color: $gray-500;
$border-colorの !defaultの書き換えのためにここでの指定は必要だと考えています

2020-11-10 08:27 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors.scss
> +  border-color: $border-color;
bordercolor-tocを復活させ、toc関連の色の記述をを整理しました。

2020-11-10 08:29 UTC, oshikishintaro commented on src/client/styles/scss/theme/_apply-colors.scss
> +      border-right-color: $border-color;
$border-color-theme;に戻しました。
ただ、border-color-themeに色味がついており、想定したデザインにならないテーマがあるので、
今後個別対応を考えています。

2020-11-10 08:50 UTC, yuki-takei requested changes

2020-11-10 08:50 UTC, yuki-takei commented on src/client/js/components/PageAccessoriesModalControl.jsx
> +      <span className="grw-border-vr mx-1">&nbsp;</span>
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/_admin.scss
> +    border-bottom: 1px solid transparent;
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/_override-bootstrap-variables.scss
> +
NG

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/_page-accessories-control.scss
> +    border-left: solid 1px transparent;
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +$border-color: $gray-500;
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +$border-color-toc: $gray-300 !default;
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +  border-color: $border-color;
NG

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +  border-color: $border-color;
NG

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> -
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +  }
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +    }
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +  }
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
NG

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-dark.scss
> +}
NG

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +$border-color-toc: $gray-300 !default;
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> -$border-color: $gray-200;
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +  }
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +    }
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +  }
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +}
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +}
NG

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors-light.scss
> +}
NG

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> -$bordercolor-toc: $bordercolor-nav-tabs !default;
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> -
OK

2020-11-10 08:50 UTC, yuki-takei commented on src/client/styles/scss/theme/mixins/_list-group.scss
> +      border-color: $border-color;
NG

2020-11-10 12:09 UTC, merged