Support/gc 6972 modify workflow yml to push image to ghcr
weseek/growi pull request #3048
Opened 2020-11-06 08:36 UTC by yamagai

2020-11-06 10:45 UTC, yuki-takei requested changes

2020-11-06 10:45 UTC, yuki-takei commented on .github/workflows/release.yml
> +        tags: ghcr.io/weseek/growi:${{ needs.github-release.outputs.RELEASE_VERSION }}${{ env.SUFFIX }}
この書き方だと、4.2.1 は 4.2.1 だけしか push されないはずで、要求としては 4.2.1, 4.2, 4 全部必要。
なので、weseek/ghaction-docker-tags-by-semver を使うのが楽だと思う。イメージも dockerhub 版と github 版で差異があってはいけないので、再ビルドしない方がいい。。

2020-11-10 06:50 UTC, yamagai commented on .github/workflows/release.yml
> +        tags: ghcr.io/weseek/growi:${{ needs.github-release.outputs.RELEASE_VERSION }}${{ env.SUFFIX }}
docker-tags-by-semver を使うようにして、再ビルドもしないよう修正しました

2020-11-10 07:16 UTC, merged

2020-11-10 07:16 UTC, yuki-takei approved these changes