Imprv/gw 4349 me setting layout
weseek/growi pull request #3049
Opened 2020-11-06 09:16 UTC by yusuketk

2020-11-06 09:45 UTC, yuki-takei requested changes

2020-11-06 09:45 UTC, yuki-takei commented on src/client/js/components/Me/PersonalSettings.jsx
> +    };
アイコンは functional component として PersonalSettings クラスの外に定義してください

2020-11-06 09:45 UTC, yuki-takei commented on src/client/js/components/Me/PersonalSettings.jsx
> +    };
というか、 `Icon: () => <i className=""></i>` でもよい

2020-11-06 09:45 UTC, yuki-takei commented on src/server/views/me/index.html
> +<div class="content-main container" id="personal-setting"></div>
他の template を参考に。container-lg を使ってなかったっけ。

2020-11-06 12:35 UTC, yuki-takei commented on src/server/views/me/index.html
> +<div class="content-main container" id="personal-setting"></div>
この部分は GW-4358 で修正済み

2020-11-06 13:37 UTC, yuki-takei requested changes

2020-11-06 13:37 UTC, yuki-takei commented on src/client/js/components/Me/PersonalSettings.jsx
> +    };
CustomNav の適用は GW-4335 で終わっているらしい

2020-11-09 02:49 UTC, yusuketk commented
すみません。本来4335マージ後にPR出すべきが急いでしまい先に出してしまいました。すみません。

2020-11-10 05:02 UTC, yusuketk commented on src/server/views/me/index.html
> -<header class="py-3">
src/client/js/components/Me/PersonalSettings.jsx に移動しました

2020-11-10 05:04 UTC, yusuketk commented
![ScreenShot 2020-11-10 14 03 23](https://user-images.githubusercontent.com/38426468/98630037-9396db00-235d-11eb-8a74-8ebd12e81ffd.png)

2020-11-10 07:02 UTC, yuki-takei requested changes

2020-11-10 07:02 UTC, yuki-takei commented on src/server/views/me/index.html
> -<header class="py-3">
admin や trash, draft のページと揃えるべき

2020-11-10 07:02 UTC, yuki-takei commented on src/server/views/me/index.html
> -<header class="py-3">
もしバラバラだったら統一を。

2020-11-11 13:17 UTC, kaoritokashiki commented on src/client/js/components/Me/PersonalSettings.jsx
> +    </>
headerのみをPersonalSettingsに持って行っていたので、headerと bodyの記述がごっちゃになっていたという問題がありました。なのでbodyもこのファイルに移動しました。

2020-11-11 13:18 UTC, kaoritokashiki commented
[GrowiSubNavigationがあるページ]
<img width="705" alt="Screen Shot 2020-11-11 at 21 56 47" src="https://user-images.githubusercontent.com/59536731/98816245-b57e8380-246b-11eb-95db-1827dcdc4b59.png">

[今回修正した /me のページ]
<img width="704" alt="Screen Shot 2020-11-11 at 21 57 21" src="https://user-images.githubusercontent.com/59536731/98816247-b6afb080-246b-11eb-8086-85063949d9be.png">

2020-11-11 13:20 UTC, kaoritokashiki commented on src/client/js/components/Me/PersonalSettings.jsx
> +    </>
参考にした`drafts.html` file
```
{% extends '../layout/layout.html' %}

{% block html_title %}{{ customizeService.generateCustomTitleForFixedPageName(t('My Drafts')) }}{% endblock %}

{% block layout_main %}

{% block content_header_wrapper %}
<header class="py-3">
  <div class="container-fluid">
    <h1 class="title">{{ t('My Drafts') }}</h1>
  </div>
</header>
<div id="grw-fav-sticky-trigger" class="sticky-top"></div>
{% endblock %}

<div id="main" class="main">
  <div id="content-main" class="content-main container-lg">
    <div id="my-drafts"></div>
  </div>
</div>
{% endblock %}

```

2020-11-11 13:32 UTC, yuki-takei requested changes

2020-11-11 13:32 UTC, yuki-takei commented on src/client/js/components/Me/PersonalSettings.jsx
> +    </>
drafts.html と同様にしてください。container は swig に残す

2020-11-11 19:14 UTC, merged