Fix/push edit fab button on disabled
weseek/growi pull request #3063
Opened 2020-11-09 10:18 UTC by zahmis

2020-11-09 10:38 UTC, yuki-takei requested changes

2020-11-09 10:38 UTC, yuki-takei commented on src/client/js/components/Fab.jsx
> +    const classes = event.detail.isSticky ? 'animated fadeInUp faster' : 'animated fadeOut faster not-push-btn';
.disabled でいいんじゃない？

2020-11-10 02:55 UTC, zahmis reviewed
BS4 の disabled を使えるようにしました。

2020-11-10 02:55 UTC, zahmis commented on src/client/styles/scss/atoms/_buttons.scss
> +
汎用的な disabled ボタンを 追加しています。

2020-11-10 07:50 UTC, yuki-takei approved these changes

2020-11-10 07:50 UTC, yuki-takei commented on src/server/views/layout-growi/base/layout.html
> +    <div id="grw-fav-sticky-trigger" class="sticky-top"></div>
BugFix

2020-11-10 07:52 UTC, merged