change btn-outline color
weseek/growi pull request #3067
Opened 2020-11-10 03:16 UTC by kaoritokashiki

2020-11-10 03:26 UTC, kaoritokashiki commented on src/client/styles/scss/theme/spring.scss
> +  }
`btn-outline-primary`のみ`accent-color`を適用しています。
気持ち悪いのはわかっています

2020-11-10 06:56 UTC, yuki-takei requested changes

2020-11-10 06:56 UTC, yuki-takei commented on src/client/styles/scss/theme/spring.scss
> +  }
outline button 専用の mixin を使ってください

2020-11-11 07:53 UTC, kaoritokashiki commented on src/client/styles/scss/theme/spring.scss
> +  }
button-outline-variantを使用して色指定をしました。

2020-11-11 08:33 UTC, merged