Imprv/gw 4457 add test routes apiv3 healthcheck
weseek/growi pull request #3081
Opened 2020-11-11 11:02 UTC by haruhikonyan

2020-11-11 11:15 UTC, yuki-takei requested changes

2020-11-11 11:15 UTC, yuki-takei commented on package.json
> +    "babel-preset-env": "^1.7.0",
babel 関連ってなんで必要なの？

2020-11-11 11:15 UTC, yuki-takei commented on src/test/routes/healthcheck.test.js
> +    app.use('/', require("~/server/routes/apiv3/healthcheck")(crowi));
beforeEach である必要はないと思う

2020-11-13 09:28 UTC, haruhikonyan commented on package.json
> +    "babel-preset-env": "^1.7.0",
サンプルにあったのそのままaddしたものでした
無くても動いたので remove

2020-11-13 11:30 UTC, haruhikonyan commented on src/test/routes/healthcheck.test.js
> +    app.response.apiv3Err = function(errors, status = 400, info) { // not arrow function
他テストでも使うだろうから別ファイルに出しても良さそう

2020-11-13 11:35 UTC, yuki-takei requested changes

2020-11-13 11:35 UTC, yuki-takei commented on src/test/routes/healthcheck.test.js
> +    app.response.apiv3Err = function(errors, status = 400, info) { // not arrow function
これは mock 化して、正常系の場合は apiv3Err が呼ばれないことを expect すべき

2020-11-13 12:22 UTC, mizozobu commented on src/test/routes/healthcheck.test.js
> +    app.response.apiv3Err = function(errors, status = 400, info) { // not arrow function
__mock__/express作ってもいいじゃないですかね

2020-11-13 21:18 UTC, yuki-takei requested changes

2020-11-13 21:18 UTC, yuki-takei commented on src/test/routes/healthcheck.test.js
> +const { getInstance } = require('../setup-crowi');
lint error は順序の問題

2020-11-13 21:24 UTC, yuki-takei commented
`Unnable to resolve` は他のソースを参考に修正してください。

一例を挙げると、

- `Unable to resolve path to module '@commons/util/path-utils'`
    - `~/utils` あたりに移っている
- `Unable to resolve path to module '@root/config/migrate'`
    - `^/config` 表記に変更
- `Unable to resolve path to module 'module-alias/register'`
    - module-alias は使わなくなったので削除

みたいな。

2020-11-16 05:30 UTC, merged