implemented the confidential render for mobile
weseek/growi pull request #3086
Opened 2020-11-12 05:01 UTC by makotoshiraishi

2020-11-12 05:08 UTC, makotoshiraishi commented
モバイル版でConfidentialアイコンをクリックしたときに、Confidentialに設定されている言葉が表示されるように実装しました。(以前にkaori-tが実装していたが、何かしらのアップデートの時に消えてしまっていたため、再度実装することにしました)

2020-11-12 05:12 UTC, makotoshiraishi commented
下図は

## 文字数が少ない時(iPhone5/SE)
<img width="323" alt="スクリーンショット 2020-11-12 14 09 36" src="https://user-images.githubusercontent.com/64956659/98898397-e1901800-24f0-11eb-9cac-46f7128bc019.png">

## 文字数が多い時(iPhone5/SE)
<img width="323" alt="スクリーンショット 2020-11-12 14 12 01" src="https://user-images.githubusercontent.com/64956659/98898469-0c7a6c00-24f1-11eb-989f-49f2fd4eca84.png">

2020-11-12 05:13 UTC, makotoshiraishi commented on src/client/js/components/Navbar/GrowiNavbar.jsx
> +import { Tooltip } from 'reactstrap';
reactstrapの"Tooltip"を用いて実装しました。
それに伴い、data-toggleとtitleのattributeを削除しました。

2020-11-12 05:16 UTC, makotoshiraishi commented on src/client/js/components/Navbar/GrowiNavbar.jsx
> +        <i id="confidentialTooltip" className="icon-info d-md-none" />
reactstrapの"Tooltip"を用いて実装しました。
それに伴い、data-toggleとtitleのattributeを削除しました。

2020-11-12 05:23 UTC, makotoshiraishi commented
ちなみに現段階だと、confidentialの言葉があまりにも長いと画面が大きいところで見ると以下のように表示されちゃいます...

![Uploading スクリーンショット 2020-11-12 14.22.16.png…]()

2020-11-12 07:06 UTC, yuki-takei requested changes

2020-11-12 07:06 UTC, yuki-takei commented on src/client/js/components/Navbar/GrowiNavbar.jsx
> +        <Tooltip
UncontrolledTooltip を使ってください

2020-11-13 04:40 UTC, makotoshiraishi commented on src/client/js/components/Navbar/GrowiNavbar.jsx
> +        <Tooltip
Uncontrolledtooltipを使ってコードをより簡潔にしました。

2020-11-13 07:42 UTC, merged