feat/gw-4461
weseek/growi pull request #3088
Opened 2020-11-12 06:12 UTC by takeru0001

2020-11-12 08:46 UTC, takeru0001 commented
<img width="886" alt="スクリーンショット 2020-11-12 17 40 41" src="https://user-images.githubusercontent.com/58085267/98916854-01cecf80-250f-11eb-90cc-20e322a8325a.png">

2020-11-12 08:47 UTC, takeru0001 commented
↑LikeButtonにhover時の見た目です。

2020-11-12 08:52 UTC, takeru0001 commented
現状、ボタンに全体適応の方法がわからなかったため、ボタン全体にUncontrolledTooltipが適応されているわけではなくicon,sumOfLikeの数字をhover時にNot acailable for guestのメッセージが出ます。

2020-11-12 18:18 UTC, yuki-takei requested changes

2020-11-12 18:18 UTC, yuki-takei commented on src/client/js/components/LikeButton.jsx
> -const LikeButtonWrapper = withUnstatedContainers(LikeButton, [AppContainer, PageContainer]);
withUnstatedContainers の利用はそのまま

2020-11-12 18:18 UTC, yuki-takei commented on src/client/js/components/BookmarkButton.jsx
> -const BookmarkButtonWrapper = withUnstatedContainers(BookmarkButton, [PageContainer]);
withUnstatedContainers の利用はそのまま、
props の crowi は appContainer に変更

2020-11-12 18:18 UTC, yuki-takei commented
/資料/外部仕様/クライアント側で可能な操作一覧 の整理が終わってから再度その仕様に則ってリファクタしてください。

2020-11-12 18:18 UTC, yuki-takei commented
> 現状、iconとsumOfLikeの数字をhover時にNot available for guestのメッセージが出ます。
> reactstrapのボタンではないボタンの場合のUncontrolledTooltipのボタン全体適応の方法がわからなかったため。

この挙動は中途半端なので直す

2020-11-13 04:44 UTC, takeru0001 commented on src/client/js/components/LikeButton.jsx
> -const LikeButtonWrapper = withUnstatedContainers(LikeButton, [AppContainer, PageContainer]);
戻しました。

2020-11-13 04:45 UTC, takeru0001 commented on src/client/js/components/BookmarkButton.jsx
> -const BookmarkButtonWrapper = withUnstatedContainers(BookmarkButton, [PageContainer]);
対応しました。

2020-11-13 06:30 UTC, takeru0001 commented
> boolean 周りに関しては、
/資料/外部仕様/クライアント側で可能な操作一覧
の整理が終わって、Wiki 通りの変数がシステム共通で使えるようになるのを待ってから、再度その仕様に則ってリファクタしてください。
は一回タスクを止めとくと言うことでしょうか？

2020-11-13 06:32 UTC, takeru0001 commented
> この挙動は中途半端なので直す。
ボタンも reactstrap にするか、またはツールチップを素の bs4 にしてみるとか(未検証)。
> 
boostrrap4のtooltipに変更し対応しました。

2020-11-13 07:50 UTC, yuki-takei requested changes

2020-11-13 07:50 UTC, yuki-takei commented on src/client/js/components/BookmarkButton.jsx
> +    const isUserLoggedIn = this.props.appContainer.currentUser != null;
wiki の仕様通りか？

2020-11-13 07:50 UTC, yuki-takei commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +        <LikeButton appContainer={appContainer} pageContainer={pageContainer} />
戻す

2020-11-13 07:50 UTC, yuki-takei commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +        <BookmarkButton appContainer={appContainer} pageContainer={pageContainer} />
attr 消す

2020-11-13 07:50 UTC, yuki-takei commented on src/client/js/components/LikeButton.jsx
> +      <div className="d-inline-block" tabIndex="0" data-toggle="tooltip" title={isUserLoggedIn ? 'Like' : t('Not available for guest')}>
isUserLoggedIn は仕様通りか？

2020-11-16 04:13 UTC, takeru0001 commented on src/client/js/components/BookmarkButton.jsx
> +    const isUserLoggedIn = this.props.appContainer.currentUser != null;
pageContainerのisGuestUserを使用しました

2020-11-16 04:14 UTC, takeru0001 commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +        <LikeButton appContainer={appContainer} pageContainer={pageContainer} />
戻しました

2020-11-16 04:15 UTC, takeru0001 commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +        <BookmarkButton appContainer={appContainer} pageContainer={pageContainer} />
消しました

2020-11-16 04:15 UTC, takeru0001 commented on src/client/js/components/LikeButton.jsx
> +      <div className="d-inline-block" tabIndex="0" data-toggle="tooltip" title={isUserLoggedIn ? 'Like' : t('Not available for guest')}>
pageContainerのisGuestUserを使用しました

2020-11-16 16:38 UTC, merged