add overflow-x unset
weseek/growi pull request #3091
Opened 2020-11-12 07:39 UTC by zahmis

2020-11-12 07:40 UTC, zahmis commented on src/client/js/components/Admin/Users/UserTable.jsx
> +        <div className="admin-user-table">
admin-user-table というクラスを新規で追加しています。
理由は、scss で可読性を上げるためです。

2020-11-13 07:40 UTC, yuki-takei requested changes

2020-11-13 07:40 UTC, yuki-takei commented on src/client/styles/scss/_admin.scss
> +      overflow-x: unset;
親の overflow に影響を受けない dropdown-menu で実装してください

2020-11-16 06:48 UTC, yuki-takei requested changes

2020-11-16 06:48 UTC, yuki-takei commented on src/client/styles/scss/_admin.scss
> +      position: fixed;
この方式はNG

素のbs4で無理なら reactstrap 化してください

2020-11-16 10:05 UTC, zahmis commented on src/client/js/components/Admin/Users/UserMenu.jsx
> +        <div className="btn-group admin-user-menu position-absolute" role="group">
position-absolute で実装しています。
position-fixed だと setting ボタンがスクロールしても残置されるのでこちらで実装しています。

2020-11-16 10:05 UTC, zahmis commented on src/client/styles/scss/_admin.scss
> +      position: fixed;
bs4 の position-xxxxx を使用することにしました。

2020-11-16 10:16 UTC, merged