Fix/gw 4460 enable view only attachment for shared user
weseek/growi pull request #3092
Opened 2020-11-12 08:34 UTC by yusuketk

2020-11-12 08:38 UTC, yusuketk commented on src/client/js/components/PageAccessoriesModalControl.jsx
> +  const {
ボタン共通化しました

2020-11-12 08:38 UTC, yusuketk commented on src/client/js/services/AppContainer.js
> -    const isSharedPageElem = document.getElementById('is-shared-page');
isSharedUser の条件を修正しました。current user が必要なので下に持って行きました。isSharedUserを使っている箇所(sidebar コンテンツの表示)での挙動も確認済みです。

2020-11-12 18:30 UTC, yuki-takei requested changes

2020-11-12 18:30 UTC, yuki-takei commented on src/client/js/components/PageAccessories.jsx
> +      <PageAccessoriesModalControl isGuestUserMode={isGuestUserMode} isSharedUserMode={isSharedUserMode} />
mode を表す props が2つ有るのは違和感。
素直に `isGuestUser` と `isSharedUser` をそのままの名前で入れればいいのではないか。

boolean 周りに関しては、
[/資料/外部仕様/クライアント側で可能な操作一覧](https://dev.growi.org/5fabddf8bbeb1a0048bcb9e9)
の整理が終わって、Wiki 通りの変数がシステム共通で使えるようになるのを待ってから、再度その仕様に則ってリファクタしてください。

2020-11-13 05:52 UTC, yusuketk commented on src/client/js/components/PageAccessories.jsx
> +      <PageAccessoriesModalControl isGuestUserMode={isGuestUserMode} isSharedUserMode={isSharedUserMode} />
変数名変更しました。
また後者に対応するタスクを作成しました。
https://youtrack.weseek.co.jp/issue/GW-4488

2020-11-13 05:59 UTC, yusuketk commented
slack で takeru-n が言ってた以下の件に関しては自分の変更箇所には関係ないことを確認済みです
> 細かいが`UncontrolledTooltip` がiconと数字にしかついていないな、ボタンのiconか数字以外の部分ではメッセージが表示されない

2020-11-13 07:46 UTC, merged