success to show sub navigation in edit mode normally
weseek/growi pull request #3108
Opened 2020-11-13 12:29 UTC by kaoritokashiki

2020-11-13 12:37 UTC, kaoritokashiki commented on src/client/js/components/Page/TagLabels.jsx
> +        <form className="grw-tag-labels form-inline flex-nowrap">
これはたタグアイコンと、「Add tags for this page」がずれていたのを直すために`flex-nowrap`をつけました
<img width="166" alt="Screen Shot 2020-11-13 at 21 36 42" src="https://user-images.githubusercontent.com/59536731/99072954-5a2dcc00-25f8-11eb-8cab-d398b6796b26.png">

2020-11-17 04:13 UTC, kaoritokashiki commented
### GW-4454 モバイル用に三連ボタンを二連ボタンに置き換える
タスク名変更しました。
### View
### Edit
### HackMD
<img width="491" alt="Screen Shot 2020-11-17 at 13 03 35" src="https://user-images.githubusercontent.com/59536731/99345834-8dad7680-28d6-11eb-85f2-4526ec8c9218.png">

<img width="510" alt="Screen Shot 2020-11-17 at 13 03 29" src="https://user-images.githubusercontent.com/59536731/99345833-8dad7680-28d6-11eb-880c-c561c68ceb2f.png">

<img width="534" alt="Screen Shot 2020-11-17 at 13 03 23" src="https://user-images.githubusercontent.com/59536731/99345828-8be3b300-28d6-11eb-99bf-ebb34ba9b88d.png">

2020-11-17 07:41 UTC, yuki-takei requested changes

2020-11-17 07:41 UTC, yuki-takei commented on src/client/js/components/Navbar/ThreeStrandedButton.jsx
> +        {editorMode === 'hackmd' && <>{viewButton()} {editButton()}</>}
edit と hackmd は、編集モードの時は表示しなくてよい(view に戻れるだけでいい)

2020-11-17 08:07 UTC, merged