Imprv/display pageaccessoriesmodal in case of mobile
weseek/growi pull request #3132
Opened 2020-11-17 11:05 UTC by zahmis

2020-11-17 11:31 UTC, yuki-takei requested changes

2020-11-17 11:31 UTC, yuki-takei commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +            <PageAccessories />
PageAccessories はそこそこ重い PageAccessoriesModal を含むので、単純に数を増やしてはいけない。

2020-11-19 03:10 UTC, zahmis commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +
最上部に mobile 版の条件分岐を入れています。

2020-11-19 03:10 UTC, zahmis commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +            <div className="flex-grow-1">
UserInfo をこちらに移動しています。
理由は、xd 通りのレイアウトにするためです。

2020-11-19 03:10 UTC, zahmis commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +            {!isDeviceSmallerThanMd && (
<Page /> の下に lg 以上で toc を表示する条件を分岐しています。 flex-grow-1 を用いることで <Page /> と <PageAccessoriesModalControl> が元通りに配置するようにしています。

2020-11-19 03:10 UTC, zahmis commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +            <PageAccessoriesModal
こちら共通化しています。

2020-11-19 03:17 UTC, zahmis commented on src/client/js/app.jsx
> -import TableOfContents from './components/TableOfContents';
toc, userinfo を DisplaySwitcher に移動させた影響で削除しています。

2020-11-19 03:28 UTC, zahmis commented
master をmerged する前は 表示されていたのですが、
merged した後に消えてしまいました。
こちらを表示させるタスクは本タスクが終わり次第 task 化します。
優先順位として、このストーリー内に入れるべきでしょうか？
<img width="828" alt="スクリーンショット 2020-11-19 12 24 47" src="https://user-images.githubusercontent.com/57100766/99617329-79968000-2a62-11eb-9363-4ea2ffd9d395.png">

2020-11-19 08:34 UTC, yuki-takei commented
- PageAccessories はまだ必要なの？
- DisplaySwitcher の中、複雑にやり過ぎてる気がする
- 以下の戦略で要求を満たせないか
    - sm 以下では Page と PageAccessories 相当を上下に並べる (flex-row)
        - control は justify-content-end
        - toc を隠す
    - md 以上では Page と PageAccessories 相当が左右に並べる (flex-md-column)
        - control は justify-content-md-center
        - width を 250px に制限する(これは現在指定済みだが、md 以上に限る)

2020-11-19 08:44 UTC, zahmis commented
PageAccessories は消し忘れでした。

2020-11-19 08:44 UTC, zahmis commented
提示された戦略を試してみます。

2020-11-19 23:41 UTC, zahmis commented on src/client/js/app.jsx
> -import TableOfContents from './components/TableOfContents';
PageAccessories も削除しています。

2020-11-19 23:41 UTC, zahmis commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +          <div className="d-flex d-md-none justify-content-end border-bottom">
d-flex を仕様しています。
武井さんの指示とは異なると思うのですが、想定した構図は以下の通りです。

![スクリーンショット 2020-11-20 8 34 05](https://user-images.githubusercontent.com/57100766/99737649-1103dd80-2b0c-11eb-9c0a-350e122af6f7.png)

2020-11-20 08:12 UTC, merged