refs GW-4457 Add test routes apiv3 healthcheck
weseek/growi pull request #3133
Opened 2020-11-17 11:55 UTC by haruhikonyan

- Add test
- Add manual mock for res.apiv3
- Fix selectedStatusList validater

2020-11-17 11:55 UTC, haruhikonyan commented on src/server/routes/apiv3/users.js
> +        if (value !== 'all' && !Object.keys(statusNo).includes(status)) {
ロジックおかしかったの修正

2020-11-17 11:56 UTC, haruhikonyan commented on src/test/routes/users.test.js
> +    crowi.models.User.STATUS_REGISTERED = 1;
必要なところだけで値を入れたかったがここに書かないと上書きされなかった

2020-11-17 11:56 UTC, haruhikonyan commented on src/test/routes/users.test.js
> +      crowi.models.User.paginate = jest.fn();
これはここでもいけるの不思議

2020-11-17 11:57 UTC, haruhikonyan commented on src/test/routes/users.test.js
> +    test('respond 200 when valid queries', async() => {
とりあえず正常系をやっているが
中でロジックを書いているもの
例えば sortOrders が asc の時と desc の時でのパラメータの違いとかすべてなめたほうがいいですかね？

2020-11-17 12:23 UTC, haruhikonyan commented on src/server/routes/apiv3/users.js
> +        if (status !== 'all' && !Object.keys(statusNo).includes(status)) {
ロジックおかしかったので修正

2020-11-17 12:25 UTC, haruhikonyan commented on src/test/routes/users.test.js
> +    describe('when normal execution User.paginate', () => {
とりあえず正常系をやっているが
中でロジックを書いているもの
例えば sortOrders が asc の時と desc の時でのパラメータの違いとかすべてなめたほうがいいですかね？

2020-11-17 12:38 UTC, yuki-takei requested changes

2020-11-17 12:38 UTC, yuki-takei commented on src/test/routes/users.test.js
> +    crowi.models.User.USER_PUBLIC_FIELDS = 'fields';
20～24 はなくなるはず

2020-11-17 12:38 UTC, yuki-takei commented on src/test/routes/users.test.js
> +                sort: { id: 1 },
parameterized test をしましょう

2020-11-18 09:29 UTC, haruhikonyan commented
https://github.com/weseek/growi/pull/3133/files#diff-2702218e8b600bef5e4fc2e1df18e12b0b624572c62e1e26c8876cf5b94971abL254-R256
エラーは出ないんですが、pageのバリデーションが無く、pageを無しで送った場合計算できず offset が NaN になる

2020-11-18 14:24 UTC, merged