Imprv/gw4577 editmode subnavigation
weseek/growi pull request #3144
Opened 2020-11-19 07:23 UTC by kaoritokashiki

2020-11-19 07:54 UTC, kaoritokashiki commented on src/client/js/components/BookmarkButton.jsx
> +  pageContainer: PropTypes.instanceOf(PageContainer).isRequired,
appContainerとpageContainerのproptypesが違うという旨のwarningがconsole上に出ていたのでついでに修正しました。

2020-11-19 08:45 UTC, yuki-takei commented
変更箇所多すぎるなあ。

NavigationContainer の isViewMode を利用するにしても、3つのコンポーネントを wrap するコンポーネントを作って、そちらで一括して show/hide を管理してほしい。

2020-11-20 02:49 UTC, kaoritokashiki commented on src/client/js/components/Navbar/SubNavButtons.jsx
> +};
`isCompactMode`はバケツリレーでpropsが渡ってきます

2020-11-20 02:51 UTC, kaoritokashiki commented on src/client/js/components/Navbar/SubNavButtons.jsx
> +import PageManagement from '../Page/PageManagement';
これら3つのコンポーネントを合わせて一つのコンポーネントにまとめました。

2020-11-20 08:27 UTC, yuki-takei requested changes

2020-11-20 08:27 UTC, yuki-takei commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +            <SubnavButtons isCompactMode={isCompactMode} />
editor mode で表示しないなら dom がもっとシンプルになるはず

2020-11-20 13:55 UTC, kaoritokashiki commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +          <div className="mt-2">
![Screen Shot 2020-11-20 at 22 53 35](https://user-images.githubusercontent.com/59536731/99807894-77781280-2b83-11eb-8088-83215b3892bd.png)
見た目は変わらずです

2020-11-20 13:55 UTC, merged