feat/gw-4602
weseek/growi pull request #3152
Opened 2020-11-20 09:49 UTC by takeru0001

2020-11-20 09:51 UTC, takeru0001 commented
ページ作成時のエラー内容
```
08:12:01.254Z ERROR growi:
  Unhandled Rejection: Promise: Promise {
    <rejected> TypeError: pageService.serializeToObj is not a function
        at /workspace/growi/src/server/routes/apiv3/pages.js:233:40
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
  } Reason: TypeError: pageService.serializeToObj is not a function
      at /workspace/growi/src/server/routes/apiv3/pages.js:233:40
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: pageService.serializeToObj is not a function
    at /workspace/growi/src/server/routes/apiv3/pages.js:233:40
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

2020-11-20 09:51 UTC, takeru0001 commented
解決後
<img width="694" alt="スクリーンショット 2020-11-20 18 23 12" src="https://user-images.githubusercontent.com/58085267/99786088-6918ff00-2b61-11eb-83ee-3175fab630c6.png">

2020-11-20 09:55 UTC, takeru0001 commented
masterをトピックブランチに取り込んだ際に出るようになったエラーです。
以前このトピックブランチでcreateをapiv3化した際にcreate内でPageServis.serializeToObj()を使っていたがmasterでは削除されていたので出たエラーだと考えています。

2020-11-26 11:02 UTC, yuki-takei requested changes

2020-11-26 11:02 UTC, yuki-takei commented on src/server/service/page.js
> +  }
master ブランチに追従すると、PageService.serializeToObj は不要になっているはず。
page-serializer.js の serializePageSecurely を使ってください。

2020-11-27 04:35 UTC, takeru0001 commented
変更後

<img width="583" alt="スクリーンショット 2020-11-27 13 30 55" src="https://user-images.githubusercontent.com/58085267/100411505-50ef3580-30b5-11eb-8ec7-0e77de8c43cc.png">

2020-11-27 04:39 UTC, takeru0001 commented on src/server/service/page.js
> +  }
serializePageSecurelyに変更しました。
念の為serializeObjを全検索し他に使われていないことを確認しました。

2020-11-27 07:32 UTC, merged