Fix/vulnerability #5
weseek/growi pull request #3160
Opened 2020-11-25 07:37 UTC by zahmis

2020-11-26 04:37 UTC, yusuketk commented on src/server/service/import.js
> +      const checkFileName = /[!-\-/:-@[-`{-~¥]/g;
他で正規表現を扱っているところを参考に https://regex101.com へのリンクのコメントを追記してください。
checkFileName という変数名も他のを参考に調整してください

2020-11-26 04:37 UTC, yusuketk commented on src/server/service/import.js
> +        return logger.error('File path is not appropriate.');
logger を return しているのはなぜ？

2020-11-26 04:56 UTC, yusuketk commented on src/server/service/import.js
> +      const checkFileName = /[!-\-/:-@[-`{-~¥]/g;
`.` 一つは許容して良いが `..` のように二つ連続している場合は引っかかるようにしないと `../../../../../../tmp/a` のようなファイルは通ってしまうのでは？

2020-11-26 05:00 UTC, zahmis commented on src/server/service/import.js
> +        return logger.error('File path is not appropriate.');
logger を表示しているのは、もし誤ってしようしてはいけない記号を含めてしまった場合に警告を出しているだけです。

2020-11-26 05:01 UTC, zahmis commented on src/server/service/import.js
> +      const checkFileName = /[!-\-/:-@[-`{-~¥]/g;
修正します。

2020-11-26 05:01 UTC, yusuketk commented on src/server/service/import.js
> +        return logger.error('File path is not appropriate.');
return しなくても良いはず

2020-11-26 05:21 UTC, zahmis commented on src/server/service/import.js
> +        return logger.error('File path is not appropriate.');
return は必要だと思っていて、retrun ;  をしなければそれ以下の動作が実行されてしまい、脆弱性を許容することになると考えています。 return; で何も返さなければそこで攻撃は停止するため必要だと考えています。

2020-11-26 06:16 UTC, zahmis commented on src/server/service/import.js
> +      const checkFileName = /[!-\-/:-@[-`{-~¥]/g;
修正しました。
２つ以上連続している場合は、引っ掛かるようにしています。

2020-11-26 06:19 UTC, zahmis commented on src/server/service/import.js
> +      const checkFileName = /[!-\-/:-@[-`{-~¥]/g;
checkFileName という変数を作成することをやめました。
理由は、１箇所しかしようしないのに無駄に変数を作成する必要がないと考えたからです。

2020-11-26 06:27 UTC, zahmis commented
https://regex101.com/r/v1BIiV/1

正規表現のリンクです。
ここで一点補足があります。

regex101のサイト上では \/ となっていますが, vscode では この\が不必要だったので外しています。
`[!-\-\/:-@[-`{-~¥]|(\.\.)+`

2020-11-26 08:11 UTC, yusuketk commented on src/server/service/import.js
> +        return logger.error('File path is not appropriate.');
return で何も返さないような書き方にしてください。現状だとlogger.error()の返り値を返すようになっています。

2020-11-26 08:13 UTC, yusuketk commented
これってマージ先master であってますか？
 > 4.2.0 以上では 攻撃ファイルが効かなくなる
ということはこのPRがマージされなくとも 4.2.0 ではこの脆弱性は解消されているということ?

2020-11-26 08:19 UTC, zahmis commented
merge 先は master で良いと思っています。
4.2.0 以上では根本的には解消されていません。
攻撃ファイルのなかに仕込んでいる もともと growi にあった file がなくなって or 名称が変更されたため、
この攻撃ファイルでは再現性が取れなくなっただけで、大元の問題は解決されたわけではないです。

この問題に関しては、以前武井さんから、脆弱性が検出されるバージョンで修正するように指示を受けています。

2020-11-26 10:28 UTC, zahmis commented
4.1.x 系 に対して merge が行われたのちに
4.2.0 で同様の実装をおこないます。

2020-11-26 11:00 UTC, yusuketk commented on src/server/service/import.js
> +      //https://regex101.com/r/v1BIiV/2
`/` のescape に関しては今の対応で良いと思います。

2020-11-26 11:07 UTC, yusuketk commented
何のためのチェックかをソースコードないにコメントとして書いておいてください。

2020-11-26 11:11 UTC, yusuketk commented
File changes が、今回変更したい場所だけになっているようにしてください

2020-11-26 12:05 UTC, zahmis commented
承知しました。

2020-11-26 14:35 UTC, zahmis commented
コメントを追加しました。
ご確認願います。

2020-11-27 05:15 UTC, yusuketk commented on src/server/service/import.js
> +      if (fileName.match(/[/~:;¥$%,&-]|(\.\.)+/g)) {
`(\.\.\/|\.\.\\)` にしましょう。
https://regex101.com/r/mD4eZs/3

追加調査で `C:\\` とか `/hoge` とか `~/hoge` では攻撃できないかを確かめて攻撃できる場合はその対策の正規表現を追加してください。

2020-11-27 06:03 UTC, zahmis commented on src/server/service/import.js
> +      if (fileName.match(/[/~:;¥$%,&-]|(\.\.)+/g)) {
調査した結果、攻撃できないことが判明しました。

2020-11-27 07:46 UTC, yuki-takei requested changes

2020-11-27 07:46 UTC, yuki-takei commented on src/server/service/import.js
> +      if (fileName.match(/(\.\.\/|\.\.\\)/gm)) {
- m オプションはいるのか？

2020-11-27 07:47 UTC, yuki-takei requested changes

2020-11-27 07:47 UTC, yuki-takei commented on src/server/service/import.js
> +        logger.error('File path is not appropriate.');
fileName も第二引数で出力してください。

2020-11-27 15:06 UTC, zahmis commented on src/server/service/import.js
> +        logger.error('File path is not appropriate.');
修正します。

2020-11-27 15:17 UTC, zahmis commented on src/server/service/import.js
> +      if (fileName.match(/(\.\.\/|\.\.\\)/gm)) {
自分の認識違いでした。
なくても問題なさそうです。

2020-11-27 15:18 UTC, zahmis commented
wiki のコメントいただいたものは、 baseDir が存在するため問題なしとのことだったのでこのままでいきます。

2020-11-27 15:20 UTC, zahmis commented on src/server/service/import.js
> +        logger.error('File path is not appropriate.');
ファイル名も出力されています。
![スクリーンショット 2020-11-28 0 20 13](https://user-images.githubusercontent.com/57100766/100463636-7f99fa00-310f-11eb-9700-aa0a28b9bdda.png)

2020-11-28 19:06 UTC, merged