add validation
weseek/growi pull request #3164
Opened 2020-11-27 06:33 UTC by zahmis

2020-11-28 19:03 UTC, yuki-takei requested changes

2020-11-28 19:03 UTC, yuki-takei commented on src/server/routes/admin.js
> +      return res.status(422).json({ errors: 'Unprocessable entity' });
Unprocessable entity であることは status 422 であることから自明なので、エラー内容はもう少し詳細を入れてください。errors をそのまま入れたらだめなのかな？

2020-11-30 05:19 UTC, zahmis commented on src/server/routes/admin.js
> +      return res.status(422).json({ errors: 'Unprocessable entity' });
errors をそのまま代入すると、以下のようになります。
これは適切なのでしょうか？
<img width="1049" alt="スクリーンショット 2020-11-30 14 16 07" src="https://user-images.githubusercontent.com/57100766/100571636-f3f2ba00-3316-11eb-916c-541ff4afee5e.png">

2020-11-30 07:31 UTC, zahmis commented on src/server/routes/admin.js
> +      return res.status(422).json({ errors: 'Unprocessable entity' });
不十分であれば、修正します。

2020-11-30 16:14 UTC, itizawa commented on src/server/routes/admin.js
> +  api.validators.export.download = function() {
validation を function で定義する必要ってあるんでしたっけ？

2020-11-30 16:14 UTC, itizawa commented on src/server/routes/admin.js
> +      param('fileName').not().matches(/(\.\.\/|\.\.\\)/, 'mg'),
mg ってなんでしたっけ...

2020-11-30 16:35 UTC, zahmis commented
mg は m オプションと g オプションをくっつけたものです。
すみません。 m オプション入らなかったですね。
忘れていました。

2020-12-01 05:46 UTC, zahmis commented on src/server/routes/admin.js
> +  api.validators.export.download = function() {
v1 が function で統一されているのでそちらでいきます。

2020-12-01 05:46 UTC, zahmis commented on src/server/routes/apiv3/export.js
> +      param('fileName').not().matches(/(\.\.\/|\.\.\\)/),
g オプションはよく考えたら不要だったので削除します。

2020-12-01 05:46 UTC, zahmis commented on src/server/service/import.js
> +      if (fileName.match(/(\.\.\/|\.\.\\)/)) {
こちらも g オプションを削除しています。

2020-12-01 05:51 UTC, zahmis commented on src/server/routes/admin.js
> +      param('fileName').not().matches(/(\.\.\/|\.\.\\)/, 'mg'),
mg オプション削除しています。

2020-12-01 08:29 UTC, merged