feat/gw-4274
weseek/growi pull request #3165
Opened 2020-11-27 07:49 UTC by takeru0001

2020-12-03 06:08 UTC, takeru0001 commented
PageServiceにduplicateを移動させました。

2020-12-03 06:16 UTC, takeru0001 commented
混ざってしまって申し訳ないのですが、renameでapiを叩く側に返す値の変更を行いました。

変更した理由: itizawaさんと相談していた時にgrowi以外からapiを叩く時にrename後のページ情報はほしいのではないかという結論になったため。
今までのrename: 親ページのパス名だけをapiを叩く側に返していた
変更後: rename後のページ情報を(子ページも含め)をすべてapiを叩く側に返すようにした。

2020-12-03 08:33 UTC, yuki-takei requested changes

2020-12-03 08:33 UTC, yuki-takei commented on src/server/service/page.js
> +    return Promise.allSettled(promise);
allSettled の返り値の形式をそのままこのメソッドの返り値にするのはあまり綺麗ではない。

2020-12-03 08:33 UTC, yuki-takei commented on src/server/routes/apiv3/pages.js
> +      result = await crowi.pageService.duplicate(page, newPagePath, req.user);
duplicate と duplicateRecursively で、返り値の型は異なっているのではないか？

この API の今の実装だとサービス層の返り値をそのまま返しているが、 recursive オプションの有無で API が返却するデータの型が異なる(しかも Promise.allSettled の形)のは API 利用側に対してユーザーフレンドリーでない。

2020-12-03 11:54 UTC, takeru0001 commented on src/server/service/page.js
> +    return Promise.allSettled(promise);
returnする値はページ情報に変更しました。

2020-12-04 05:40 UTC, takeru0001 commented on src/server/service/page.js
> +    return Promise.allSettled(promise);
duplicate後のページの情報を返すように変更しました。

2020-12-04 05:41 UTC, takeru0001 commented on src/server/routes/apiv3/pages.js
> +      result = await crowi.pageService.duplicate(page, newPagePath, req.user);
duplicateとrenameどちらも異なっていたのでそれぞれで返り値を統一しました。

2020-12-04 05:43 UTC, takeru0001 commented on src/server/routes/apiv3/pages.js
> +      result = await crowi.pageService.duplicate(page, newPagePath, req.user);
duplicate:

not recursive
<img width="827" alt="singleDuplicate" src="https://user-images.githubusercontent.com/58085267/101126508-033b7580-363f-11eb-82fe-e12097a81f28.png">


recursive
<img width="827" alt="recurcivDuplicate" src="https://user-images.githubusercontent.com/58085267/101126524-0afb1a00-363f-11eb-9cc2-1815f23080b8.png">

2020-12-04 05:44 UTC, takeru0001 commented on src/server/routes/apiv3/pages.js
> +      result = await crowi.pageService.duplicate(page, newPagePath, req.user);
rename:

not recursive

<img width="828" alt="singleRename" src="https://user-images.githubusercontent.com/58085267/101126591-2a924280-363f-11eb-81fe-4b24b07991f9.png">


recursive
<img width="828" alt="renameRecursively" src="https://user-images.githubusercontent.com/58085267/101126611-32ea7d80-363f-11eb-8458-a433394085d3.png">

2020-12-08 09:19 UTC, yuki-takei requested changes

2020-12-08 09:19 UTC, yuki-takei commented on src/server/models/page.js
> +    pageEvent.emit('create', result, user, socketClientId);
この書き方違和感ある(何型のインスタンスかわからない)ので、`updatedPageData` という変数名は変えない。

2020-12-08 09:19 UTC, yuki-takei commented on src/server/models/page.js
> +    return { result };
`return { result: updatedPageData };`

2020-12-08 09:19 UTC, yuki-takei commented on src/server/routes/apiv3/pages.js
> +      body('isDuplicateRecursively').if(value => value != null).isBoolean().withMessage('isDuplicateRecursively must be boolean'),
これは変える必要がない。renamePage の方も `isRecursively` だし。

2020-12-08 09:19 UTC, yuki-takei commented on src/server/routes/apiv3/pages.js
> +    return res.apiv3({ result, page });
result と page ってなんで分かれてるの？

2020-12-08 09:19 UTC, yuki-takei commented on src/server/service/page.js
> +    return result;
このサービスの duplicate メソッドが扱うのは単数なのに array を返すのはおかしい。

2020-12-10 04:05 UTC, takeru0001 commented on src/server/models/page.js
> +    return { result };
変更しました。

2020-12-10 04:05 UTC, takeru0001 commented on src/server/routes/apiv3/pages.js
> +      body('isDuplicateRecursively').if(value => value != null).isBoolean().withMessage('isDuplicateRecursively must be boolean'),
変更しました。

2020-12-10 04:07 UTC, takeru0001 commented on src/server/routes/apiv3/pages.js
> +    return res.apiv3({ result, page });
renameのモーダル内で親ページのパスが必要なので、分けて返していましたが、resultの中にparentPageとして入れることにしました。

2020-12-10 06:23 UTC, takeru0001 commented on src/server/service/page.js
> +    return result;
配列を返すのではなく、オブジェクトを返すように変更しました。

2020-12-10 09:28 UTC, takeru0001 commented
duplicate: 単体もrecursively も下の画像のreturnに直しました。
<img width="642" alt="スクリーンショット 2020-12-10 18 25 23" src="https://user-images.githubusercontent.com/58085267/101752782-3b4a2900-3b15-11eb-9a34-2b8012992414.png">

rename: 単体もrecursively も下の画像のreturnに直しました。
<img width="626" alt="スクリーンショット 2020-12-10 18 25 45" src="https://user-images.githubusercontent.com/58085267/101752954-6fbde500-3b15-11eb-9b62-4948c6255631.png">

2020-12-10 09:32 UTC, yuki-takei requested changes

2020-12-10 09:32 UTC, yuki-takei commented on src/server/service/page.js
> +    });
- この find は無駄
    - 親ページと子孫ページで duplicate 処理を分ける

2020-12-10 11:47 UTC, takeru0001 commented on src/server/service/page.js
> +    });
修正しました。

2020-12-10 11:47 UTC, merged