vulnerability-gw6477
weseek/growi pull request #3175
Opened 2020-11-30 07:26 UTC by makotoshiraishi

2020-11-30 07:37 UTC, makotoshiraishi commented
# 症状

[Wiki](https://growi.weseek.co.jp/Projects/GROWI/GROWI/%E8%84%86%E5%BC%B1%E6%80%A7%E5%AF%BE%E5%BF%9C/JVN/94169589%20%E5%86%8D%E7%8F%BE%E7%A2%BA%E8%AA%8D)の方に記載されております。

要約しますと、ページのタグが例えば以下のような場合
<img width="953" alt="スクリーンショット 2020-11-30 16 32 43" src="https://user-images.githubusercontent.com/64956659/100580695-c5caa580-3329-11eb-85bc-60385b557c36.png">

この時タグ検索を以下のように入力する
`(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((([a-z]*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*$`


そうすると、検索文字が正規表現の特殊文字として認識され、数十分待って**タイムアウトエラー**が帰ってきてしまいます。


# 解決策

正規表現における特殊文字は`\^$/.*+?()[\]{}|`である([参考サイト](https://techacademy.jp/magazine/34367))ためそれらをエスケープするように実装を施しました。

2020-11-30 09:33 UTC, itizawa commented on src/server/routes/tag.js
> +    const escapeRegExp = req.query.q.replace(/[\\^$/.*+?()[\]{}|]/g, '\\$&');
https://github.com/weseek/growi/pull/3160/files#diff-e6806e6738318b4b7fa0beee96a3de2fde1e6c2b4e01dc121d1afe3a64b0a922R372
のように、正規表現を使った時は https://regex101.com で作成し、
リンク貼るようにお願いします。

2020-11-30 09:39 UTC, itizawa commented on src/server/routes/tag.js
> +    let tags = await Tag.find({ name: new RegExp(`^${escapeRegExp}`) }).select('-_id name');
この select の書き方ってあってるんですかね...?
`-_id` って `_id` の間違いでないのかなと

2020-11-30 10:20 UTC, makotoshiraishi commented on src/server/routes/tag.js
> +    let tags = await Tag.find({ name: new RegExp(`^${escapeRegExp}`) }).select('-_id name');
両方の書き方でタグ検索してみたのですが、挙動は変わらなかったのですね。
一応`_id`の書き方の方が統一性があるので直しました！！

2020-12-01 04:46 UTC, makotoshiraishi commented
市澤さんからFB済み

2020-12-01 08:33 UTC, yuki-takei requested changes

2020-12-01 08:33 UTC, yuki-takei commented on src/server/routes/tag.js
> +    const escapeRegExp = req.query.q.replace(/[\\^$/.*+?()[\]{}|]/g, '\\$&');
`\\$&` に replace するとどうなるのか、なぜ安全になるのかをコメントで書く
参考URLを載せるでもOK

2020-12-03 04:08 UTC, makotoshiraishi commented on src/server/routes/tag.js
> +    const escapeRegExp = req.query.q.replace(/[\\^$/.*+?()[\]{}|]/g, '\\$&');
`
// Search for regular expressions as normal characters
// e.g. user*$ -> user\*\$ (escape a regular expression)
`

と記載することによって、`\\$&`にreplaceするとどのように置換されるかを例示して記述しました。

2020-12-03 08:25 UTC, merged