Fix/vul #2 4.1.x
weseek/growi pull request #3182
Opened 2020-12-01 12:23 UTC by zahmis

2020-12-01 12:26 UTC, zahmis commented on src/server/service/import.js
> +      if (fileName.match(/(\.\.\/|\.\.\\)/)) {
これは前回の修正(vul # 5 を 4.1.x 系で修正)の時に g オプションをつけたままでした。
4.2 系で いらないことに気づいたので、4.2 系では消しています。
それに伴って、今回の 4.1.x 系でも削除しています.

2020-12-02 09:26 UTC, yuki-takei requested changes

2020-12-02 09:26 UTC, yuki-takei commented on src/server/service/import.js
> +      // https://regex101.com/r/mD4eZs/4
参照させる例は m option で複数行に跨がって match の判定をさせるように

2020-12-03 04:41 UTC, zahmis commented on src/server/service/import.js
> +      // https://regex101.com/r/mD4eZs/4
修正します。

2020-12-03 05:44 UTC, merged