replace < and >
weseek/growi pull request #3184
Opened 2020-12-02 07:16 UTC by zahmis

2020-12-02 20:11 UTC, zahmis commented
code を追跡した結果
`Crowi.prototype.init が実行されるときにおそらく 
`await Promise.all([this.setUpXss])`が実行されると思われます。
このときに`XssService が(this.configManager)を引数にとり、インスタンス化されそうです。

configManager を使用しています。
当初は null ですが、 setUpSesstionConfig() が実行されるときに、configManager を config を model としてインスタンス化しています。
インスタンス化した configManager を xssService クラスの constructor の引数に与え、
さらにその method では getConfig() を使用することで xssOption をConfig.js から取得しています。

これによって,
setUpXss によって生み出される this.xssService インスタンスは生まれながらにして、オプションを持っているので
crowi.xssService.process(page.revision.body) で適切に xss 対策ができると考えられます。

2020-12-04 12:05 UTC, zahmis commented on src/server/routes/page.js
> +    if (crowi.configManager.getConfig('markdown', 'markdown:xss:isEnabledPrevention')) {
admin 画面の markdown 設定で決定された xss 対策設定に presentation mode も対応させました。

その際に xss の option を決定する必要があったので、lib から呼び出してインスタンス化しています。

仮に xss 対策をしない場合は今まで通り、 presentation で script tag などが実行できるようにしています。

2020-12-04 12:05 UTC, zahmis commented on src/lib/service/xss/xssOption.js
> +  constructor(config, crowi) {
第一引数の config はおそらくなんですが、client 側で使用される引数だと思いました。
crowi.xssService.getTagWhiteList() や getAttrWhiteList() を取得したかったので、第二引数に crowi を追加しています。

2020-12-04 12:14 UTC, itizawa commented on src/server/routes/page.js
> +    const xssOption = new XssOption(crowi.config, crowi);
```suggestion
    const initializedConfig =  {
        tagWhiteList:    crowi.xssService.getTagWhiteList()
        attrWhiteList:  crowi.xssService.getAttrWhiteList() 
    }
    
    // crowi.config is empty.
    const xssOption = new XssOption(initializedConfig);
```

2020-12-04 12:20 UTC, zahmis commented on src/lib/service/xss/xssOption.js
> +  constructor(config, crowi) {
```suggestion
  constructor(config, growi) {
```

2020-12-04 13:10 UTC, zahmis commented on src/server/routes/page.js
> +    const xssOption = new XssOption(crowi.config, crowi);
適用させました。

2020-12-07 11:25 UTC, yuki-takei requested changes

2020-12-07 11:25 UTC, yuki-takei commented on src/server/routes/page.js
> +      const xss = new Xss(xssOption);
addRenderVarsForPresentation が呼ばれる度に new Xss するのはよくない。

2020-12-07 13:29 UTC, zahmis commented on src/server/routes/page.js
> +      const xss = new Xss(xssOption);
module exports にて実行することにしました。

2020-12-07 13:31 UTC, zahmis commented on src/server/routes/page.js
module.exports 冒頭で一回呼び出して使い回すように変更しました。

2020-12-09 10:05 UTC, yuki-takei approved these changes

2020-12-09 10:05 UTC, merged