refs GW-4652 utils/project-dir-utils.ts
weseek/growi pull request #3197
Opened 2020-12-04 08:50 UTC by haruhikonyan

2020-12-04 08:51 UTC, haruhikonyan commented on src/test/util/project-dir-utils.test.js
> +// TODO: Make mock changes for each test.
テストファイルのトップに書かなければ反映されない
おそらくテスト対象のトップで書いている処理だからグローバルに対応させなきゃいけないからか？

2020-12-04 10:19 UTC, yuki-takei requested changes

2020-12-04 10:19 UTC, yuki-takei commented on src/test/util/project-dir-utils.test.js
> +import { projectRoot, resolveFromRoot } from '~/utils/project-dir-utils';
isCurrentDirRoot に応じて projectRoot が変わるのもテストしてほしい。

2020-12-04 10:19 UTC, yuki-takei commented on src/test/util/project-dir-utils.test.js
> +  });
これは mock を用意するのではなく、結果を検証する parameterized テストにしてほしい。

2020-12-07 08:54 UTC, haruhikonyan commented on src/test/util/project-dir-utils.test.js
> +  });
対応

2020-12-07 08:54 UTC, haruhikonyan commented on src/test/util/project-dir-utils.test.js
> +import { projectRoot, resolveFromRoot } from '~/utils/project-dir-utils';
したいが方法を編み出せなかったのでペンディング。。。
https://github.com/weseek/growi/pull/3197/files#diff-2e83726a26aaab4bb538d50efeaeea55725bdc7103f82a0a4bceafb3ac12c8e5R29

2020-12-07 11:47 UTC, yuki-takei requested changes

2020-12-07 11:47 UTC, yuki-takei commented on src/test/util/project-dir-utils.test.js
> +  });
対応してないね。
fs.existsSync 含め、いろんなパターンを入れてくれないと。

https://qiita.com/bearII/items/d24b798ea3434c3dd0d7

2020-12-08 08:42 UTC, merged