fix state in revision loader
weseek/growi pull request #3204
Opened 2020-12-07 09:59 UTC by zahmis

2020-12-07 11:49 UTC, yuki-takei requested changes

2020-12-07 11:49 UTC, yuki-takei commented on src/client/js/components/Page/RevisionLoader.jsx
> +      this.setState({ markdown: error[0].message });
apiv3Get のエラーは複数個来ることもあるので対応してください。

2020-12-08 08:46 UTC, zahmis commented on src/client/js/components/Page/RevisionLoader.jsx
> +      this.setState({ markdown: error[0].message });
処理する場所を変更しています。
返答する error は複数になるので errors に変更しました。

2020-12-08 08:48 UTC, zahmis commented on src/client/js/components/Page/RevisionLoader.jsx
> +    if (this.state.errors != null) {
こちらで配列を作成し、errorsMessages に代入しています。
その後、型を合わせて markdown に代入しています。
これによって複数の error に対応できると考えました。

2020-12-08 09:34 UTC, merged