added an URL about the user API specification
weseek/growi pull request #3235
Opened 2020-12-14 11:38 UTC by kaoritokashiki

2020-12-14 11:39 UTC, kaoritokashiki commented on src/server/routes/apiv3/users.js
> +
[/資料/外部仕様/ユーザーAPI](https://dev.growi.org/5fd7466a31d89500488248e3)

2020-12-14 14:09 UTC, yuki-takei requested changes

2020-12-14 14:09 UTC, yuki-takei commented on src/server/routes/apiv3/users.js
> +
親切ではあるんだけど、ソースコード内に日本語を入れたくないので URL のみにしてください。
(飛んだ先が日本語なのはドキュメント生成コストてきにしょうがないとして、せめてソースコード内だけでも英語のみを保つ)

2020-12-15 05:42 UTC, kaoritokashiki commented
日本語消しました。マージします。

2020-12-15 05:49 UTC, merged