Fix/remain get help element in case of mobile
weseek/growi pull request #3236
Opened 2020-12-14 12:55 UTC by zahmis

2020-12-14 14:16 UTC, yuki-takei requested changes

2020-12-14 14:16 UTC, yuki-takei commented on src/client/js/components/SearchForm.jsx
> +      isCloseHelp: null,
- boolean の初期値は null ではなく false を入れる
- 初期値が false で都合が悪い場合、変数の命名(意味づけ)が大抵おかしい

2020-12-14 14:16 UTC, yuki-takei commented on src/client/js/components/SearchForm.jsx
> +    if (!isCloseHelp) {
isCloseHelp で return null しているなら、!isCloseHelp の判定は無駄では？

2020-12-15 03:34 UTC, zahmis commented on src/client/js/components/SearchForm.jsx
> +      isCloseHelp: null,
承知しました false でも問題なかったです。

2020-12-15 03:39 UTC, zahmis commented on src/client/js/components/SearchForm.jsx
> +    if (!isCloseHelp) {
認識が甘かったです。修正します。

2020-12-15 06:28 UTC, yusuketk commented on src/client/js/components/SearchForm.jsx
> +      isCloseHelp: null,
初期値 false (検索窓のヘルプの初期状態は閉じていない、すなわち開いている状態）でいいんですか？

個人的に最初のFBから読み取れるのは、初期値を false にすべきだが、(きっと)初期状態は閉じている状態のため isCloseHelp の初期値は true になるはず、だがやはり初期値は原則 false にして欲しいので、変数が表す意味自体を変えるべき

2020-12-15 06:32 UTC, zahmis commented on src/client/js/components/SearchForm.jsx
> +      isCloseHelp: null,
@yusuketk 
fb 確認しました。
「検索窓の ヘルプは 閉じている状態 」
が正しい挙動です。
isCloseHelp : false は ヘルプを閉じていますか？ いいえ
となってしまうのですね。
自分の中で混乱していました。

ここは変数名を変更します。

2020-12-16 03:49 UTC, merged