implemented the header for iphone6 plus
weseek/growi pull request #3239
Opened 2020-12-15 07:00 UTC by makotoshiraishi

2020-12-15 08:05 UTC, makotoshiraishi commented
古いOSでnavbarが消滅する問題を解決しました。

# 原因
原因を調査したところ、`src/client/styles/scss/_navbar.scss`の2行目`top: -$grw-navbar-height !important;`が悪さをしていることがわかりました。(なぜこの記述で古いOSだけnavbarが消滅するかは不明)

# 解決手法
古いOSだけを指定してスタイルを変更することはできないため、Bootstrapのグリッドシステム(sm|md|lgなど)を用いて解決を図りました。
具体的には

>   @include media-breakpoint-down(sm) {
>    top: initial !important;
>  }

により、nativeに対してだけ、topの値をinitalに変更した。

# 副作用

この変更により、iphone6plus でnavbarが表示されるようになったのですが、任意のページの`editor`Modeでスタイルが若干崩れてしまいました。
そもそもEditorModeではNavbarは必要ではないと判断したため、`src/client/js/components/Navbar/GrowiNavbar.jsx`のrenderの内容を`view`モードだったらrenderして、その他の場合はなにもRenderしないという風に実装を変更しました。

よろしくお願いします。

2020-12-15 08:32 UTC, makotoshiraishi commented on src/client/js/components/Navbar/GrowiNavbar.jsx
> +          <>
たくさん変更を加えたように見えますが、実際変更した部位はこの3行(editorModeの値によってRenderする内容を変更するコード)と

2020-12-15 08:32 UTC, makotoshiraishi commented on src/client/js/components/Navbar/GrowiNavbar.jsx
> +        }
ここの3行だけです。

2020-12-15 08:33 UTC, makotoshiraishi commented on src/client/styles/scss/_navbar.scss
> +  }
グリッドシステムより`sm` より幅が小さいデバイスに対して、topの値を変更しました。

2020-12-16 04:46 UTC, yuki-takei requested changes

2020-12-16 04:46 UTC, yuki-takei commented on src/client/styles/scss/_navbar.scss
> +  }
top は sticky のために設定しているわけなので、そもそもこれでは sm 以下の sticky の動作としておかしなことになるし、副作用まで出るので解決策になってない。

2020-12-16 04:58 UTC, yuki-takei requested changes

2020-12-16 04:58 UTC, yuki-takei commented on src/client/styles/scss/_navbar.scss
> +  }
原因はおそらくこれ
https://stackoverflow.com/questions/54646939/why-is-my-positionsticky-not-working-on-ios

2020-12-16 04:58 UTC, yuki-takei commented on src/client/styles/scss/_navbar.scss
> +  }
AppContainer で
`this.isMobile = /iphone|ipad|android/.test(userAgent);`
とやっているように、User Agent を見て挙動を変えることは可能なので、editorMode が view かつ古いOSだったら `sticky-top` を使わないといった解を検討する。

別の案もあるかもしれない。

2020-12-24 10:03 UTC, closed without merging