Imprv/reduce the load of the delete process
weseek/growi pull request #3255
Opened 2020-12-18 07:35 UTC by zahmis

2020-12-19 11:43 UTC, zahmis commented on src/server/service/search-delegator/elasticsearch.js
> +      return await this.deletePages(pages);
配列化する必要がなくなりました。

従来、Promise.all  で pages の中の各要素( page )に対して、適用したい method において、
map を使用するため、配列化していたのだと考えました。

2020-12-21 05:29 UTC, yuki-takei requested changes

2020-12-21 05:29 UTC, yuki-takei commented on src/server/service/page.js
> +    return deleteData;
`this.removeAllAttachments(pageId),` も行うようにしてください(パフォーマンスアップしていなくても構わないので)

2020-12-21 05:29 UTC, yuki-takei commented on src/server/service/page.js
> +    return deleteData;
Promise.all の結果を return する必要はあるのか？

2020-12-21 05:29 UTC, yuki-takei commented on src/server/service/page.js
> +    return pagesData;
pagesData を return する必要はあるのか？
延いては、 completelyDeletePage でも return の必要はあるのか？

2020-12-21 05:29 UTC, yuki-takei commented on src/server/service/search-delegator/elasticsearch.js
> -    pages.map((page) => {
forEach でよいです。

2020-12-21 05:32 UTC, zahmis commented on src/server/service/page.js
> +    return deleteData;
this.removeAllAttachments は次のタスクで行う予定です。

2020-12-21 06:06 UTC, zahmis commented on src/server/service/page.js
> +    return pagesData;
completelyDeletePage を調査したところ必要なさそうでした。
よって削除します。

2020-12-21 06:15 UTC, zahmis commented
また補足なんですが、「元に戻す」操作も task 分割しています。
これも機能的にできなくなったら困ることなので、今回の pr に含めます。

2020-12-21 07:08 UTC, zahmis commented on src/server/service/page.js
> +    return deleteData;
なかったので削除します。

2020-12-22 05:01 UTC, zahmis commented on src/server/service/search-delegator/elasticsearch.js
> +  async syncPageDeleted(pages, user) {
logger.info で確認したところ、正常に動作することを確認しました。
<img width="890" alt="スクリーンショット 2020-12-21 18 26 08" src="https://user-images.githubusercontent.com/57100766/102843664-fd220300-444c-11eb-9571-3f1babcd7b4b.png">

2020-12-22 05:06 UTC, zahmis commented on src/server/models/page.js
> +    // The reason using array is to match the types in elasticsearch.js ( deletePages )
単にページを deletePage する場合、rename 処理になります。(/trash/hoge)
その場合、elasticsearch.js の deletePages(pages) で 型の不一致が発生します。
理由は deletePage の引数を配列で渡していないからです。
よってこの部分を配列化して渡します。

2020-12-22 07:54 UTC, yuki-takei requested changes

2020-12-22 07:54 UTC, yuki-takei commented on src/server/service/page.js
> +    attachmentService.removeAttachment(attachments);
Promise を返すために return が必要

2020-12-22 07:54 UTC, yuki-takei commented on src/server/service/attachment.js
> +    await attachments.forEach(attachment => attachment.remove());
処理は forEach で書いてもいいし map で書いてもいいけど、最終的に Promise の return が必要

2020-12-22 07:54 UTC, yuki-takei commented on src/server/service/attachment.js
> +    await attachments.forEach(attachment => attachment.remove());
ちゃんと return する Promise は、これらの終了とリンクしたものであるかどうかを考えてコーディングする

2020-12-22 07:54 UTC, yuki-takei commented on src/server/service/page.js
> +    // In case of recursively
ここは再帰処理ではない

2020-12-22 07:54 UTC, yuki-takei commented on src/server/service/page.js
> +  async completelyDeletePage(pagesData, user, options = {}) {
複数ページを消せるメソッドであることがわかる名前に変更する

2020-12-22 07:54 UTC, yuki-takei commented on src/server/service/page.js
> +      pageEvent.emit('delete', [pagesData], user, socketClientId); // update as renamed page
123～133までは不要なはず

2020-12-23 03:51 UTC, zahmis commented on src/server/service/page.js
> +  // delete multiple pages
`completeDeletePageRecursively`で Promise.all と map をやめて、
塊の配列で渡すことにした結果、
[単一ページを完全に削除する] のと [ 再起的完全削除]  の method を分離しました。

理由は、map で回していた時は、 `completelyDeletePage` にオブジェクトで渡していて、
以下オブジェクトを引数にとるような処理がされていました。

今回これを改修して、`completelyDeletePageRecursively` -> `completeDeletePage` には引数に配列を持たせ、配列で処理をするように改修しました。

しかし、**１ページだけ完全削除する場合**は、
completelyDeletePage の引数に オブジェクトがわたり、配列で処理を行うように改修したので、型の不一致が発生しました。

そこで、１つの method で無理に型を合わせようとせず 
[単一ページを完全に削除する] のと [ 再起的完全削除]  の method を分離しました。

2020-12-23 03:51 UTC, zahmis commented on src/server/service/page.js
単一ページ削除の場合、ここで配列化をしています。

2020-12-23 03:51 UTC, zahmis commented on src/server/service/page.js
> +  // revert pages recursively
revert [元に戻す] の method も 2つに分けました。
従来は、`completeDeletePage` の method を使用していました。
しかし、今回 `completeDeletePage` を改修したため 適切に revert できなくなりました。
この理由も、従来の`completeDeletePage`は オブジェクトを想定しているのに、
改修によって配列を使用することになったため、型の不一致が生じたからです。

今回  ` completeDeleteSinglePage` と `completeDeletePages` に分離させています。

再起的に revert する場合の method は `completeDeletePages` を使用し、
単一ページを revert する場合の method は `completeDeleteSinglePage` を使用することで、

両方の revert に対応しています。

また後続タスクで、revert 処理も高速化させます。

2020-12-23 03:51 UTC, zahmis commented on src/server/service/page.js
> +        return this.completelyDeletePages(pages);
`handlePrivatePagesForDeletedGroup`が抜けていたので追加で書いています。

2020-12-23 03:51 UTC, zahmis commented on src/server/service/search.js
> +    pageEvent.on('deleteCompletely', this.delegator.syncPageDeletedCompletely.bind(this.delegator));
[完全削除の場合(再起的含む)]と[単なる削除(rename)(再起的含む)] は 共通で pageEvent.emit("delete"..) をしようしていました。

今回共通の pageEvent を使用するのが駄目な理由は、
emit した結果の引数が、今回の改修で異なるからです。

改修前は全てオブジェクトでしたので、よかったのですが、
今回の改修で、完全削除の場合は配列を渡すことになりました。

当然共通の event を使用するので、型の不一致が生じます。

よって、event を新規で作成し、
[完全削除の場合] と [rename の場合] に分けています。

2020-12-23 03:54 UTC, zahmis commented on src/server/service/page.js
> +    // In case of recursively
修正します。

2020-12-23 08:40 UTC, zahmis commented on src/server/service/attachment.js
> +    return attachments.forEach((attachment) => {
この部分は await が不要だと考えています。
理由は、await 以下のPromise の処理が完了しなければ次の処理で困るということがないからです。

しかし、疑問も発生しました。
internal server error などが発生した場合、ページを削除した人は削除したと思っているが、実際は消されていない。という問題が発生しそうに感じました。

そのパターンはあり得るのでしょうか？

try-catch でエラーを補足する必要があると感じましたが、不要でしょうか？

2020-12-23 10:09 UTC, yuki-takei requested changes

2020-12-23 10:17 UTC, zahmis commented on src/server/service/attachment.js
> +    return attachments.forEach((attachment) => {
なるほど。
承知しました。

2020-12-23 10:17 UTC, zahmis commented on src/server/service/page.js
> +    const id = [pageData._id];
修正します。

2020-12-23 10:17 UTC, zahmis commented on src/server/service/page.js
> +    const path = [pageData.path];
修正します。

2020-12-23 10:18 UTC, zahmis commented on src/server/service/search-delegator/elasticsearch.js
> +  async syncPageDeletedCompletely(pages, user) {
修正します。

2020-12-23 16:19 UTC, zahmis commented on src/client/js/components/EmptyTrashModal.jsx
> +      await appContainer.apiv3Delete('/pages/empty-trash', { socketclientId: socketIoContainer.getSocketClientId() });
client から socketclientId を渡しています。
これによって options を設定することができ、socketclientId が 入ることによって、
pageEvent を発火することが可能になります。

2020-12-23 16:19 UTC, zahmis commented on src/server/routes/apiv3/pages.js
> +      const pages = await crowi.pageService.completelyDeletePageRecursively({ path: '/trash' }, req.user, options);
従来は options を追加していませんでした。
それゆえ「ゴミ箱を空にする」という api を叩くと、socketclinetId が入らず pageEvent.emit が発火しない仕様になっていました。

2020-12-23 16:25 UTC, zahmis commented
delete の動作は問題ありませんでした。
pageEmit は従来と同じ挙動をするといえばします。
しかし、おかしい挙動を発見したので、修正しました。
ご確認願います。

2020-12-24 08:46 UTC, yuki-takei requested changes

2020-12-24 08:46 UTC, yuki-takei commented on src/server/routes/apiv3/pages.js
> +    const socketClientId = req.query.socketClientId;
validation 書いてください

2020-12-24 10:13 UTC, merged