Reduce the load of revert delete
weseek/growi pull request #3277
Opened 2020-12-28 01:29 UTC by zahmis

2021-01-05 10:33 UTC, yuki-takei requested changes

2021-01-05 10:33 UTC, yuki-takei commented on src/server/service/page.js
> +    const updatedPage = await Page.renameRecursively(page, newPath, user, {});
revertDeletedPages は単数なのか複数なのか親ページのみ指定する recursive な操作をしてくれるのか？

このメソッドに対して Page.renameRecursively という再帰処理を行うメソッド呼び出しは正しいのか？

2021-01-07 08:53 UTC, zahmis commented on src/server/service/page.js
無駄な関数を削除

2021-01-07 09:20 UTC, zahmis commented
大幅に task の解決方法を変更しました。

merge 先ブランチを変更しています。
理由は、renameRecursively の不具合があったので、それを解消する必要がありました。
改修した branch の内容を踏襲して、task を解決しています。

修正した branch は imprv/gw-4857 (takeru-n) です。

2021-01-07 09:26 UTC, zahmis commented on src/server/models/page.js
> +
消せないページの時の処理を追加しました。

2021-01-07 09:26 UTC, zahmis commented on src/server/service/page.js
>    async revertDeletedPageRecursively(targetPage, user, options = {}) {
[再起的にページを復元する] を大改修しました。

従来は targetPage に対して revertDeletePage の map 処理をしていました。

今回は db にアクセスする回数を減らすことで、高速化を実現しました。

2021-01-07 10:17 UTC, zahmis commented on src/server/service/page.js
>    async revertDeletedPageRecursively(targetPage, user, options = {}) {
4546 page 分で
- master での revert 処理 2分26秒
- この処理を施したあと   14 秒

2021-01-07 10:43 UTC, yuki-takei requested changes

2021-01-07 10:43 UTC, yuki-takei commented on src/server/models/page.js
> +
早期リターンの考え方では、isDeletableName の結果が false の場合に throw Error する処理を先に書く。1134 行目のゴミ箱内のチェックと一緒。

2021-01-07 10:43 UTC, yuki-takei commented on src/server/models/page.js
> +    return Promise.reject(new Error('Page is not deletable.'));
1135 行目と同様、throw Error でよい。
async function の中では基本的に Promise.reject は使わない。

2021-01-07 10:43 UTC, yuki-takei commented on src/server/models/page.js
> +      }
## 懸念1: パフォーマンス
unorderedBulkOp の挙動をあまり把握できていないけれど、これだと 1239行目 or 1242行目処理と合わせて2回走るんじゃない？

.update() に渡す $set の内容を条件に応じて組み替えて呼び出しを1回にできないだろうか。

現状の書き方で1回しか走らないのであれば問題ない。

2021-01-07 10:43 UTC, yuki-takei commented on src/server/models/page.js
> +      }
## 懸念2: status 更新のシチュエーション

renameRecursively は汎用的なメソッドなので、実際に GROWI でそういう操作が可能かはさておき、

- 通常ページから通常ページ
- 通常ページからゴミ箱内
- ゴミ箱内から通常ページ
- ゴミ箱内からゴミ箱

の操作はどれも正常に処理してほしい。その場合、子孫ページの status に何をセットするのは、 `newPagePathPrefix` によるのではないか？

2021-01-07 10:43 UTC, yuki-takei commented on src/server/service/page.js
> +    const originalParentPath = Page.getRevertDeletedPageName(targetPage.path);
この辺りの変数の命名センスが悪い。

from と to でいうと、targetPage は to にあたるはずだが、「original」というものが付くとなんなのかよくわからなくなる。

2021-01-07 10:43 UTC, yuki-takei commented on src/server/service/page.js
> +    await this.completelyDeletePages(originPages, options);
completelyDeletePages を先にやるのは不安

2021-01-07 10:43 UTC, yuki-takei commented on src/server/service/page.js
> +    await this.completelyDeletePages(pages, options);
completelyDeletePages を先にやるのは不安。

2021-01-08 12:13 UTC, zahmis commented on src/server/service/page.js
> +    const originalParentPath = Page.getRevertDeletedPageName(targetPage.path);
修正します。

2021-01-08 12:13 UTC, zahmis commented
この方法では revision が元通りにならないという欠陥が発生しました。

なので、この方法を取りやめます。

2021-01-09 18:35 UTC, zahmis commented on src/server/models/page.js
> +
承知しました。

2021-01-09 18:35 UTC, zahmis commented on src/server/service/page.js
> +    const pageCollection = mongoose.connection.collection('pages');
ページを削除する処理に bulk を適用させました。

2021-01-09 18:35 UTC, zahmis commented on src/server/service/page.js
> +    for (let i = 0; i < pages.length; i++) {
各ページに対して、path が等しいかどうかをチェックし、エラーハンドリングをしていました。
pages と originPages 双方を使いました。
さらに、順序を合わせるために、 166 行目で sort しています。

2021-01-10 05:21 UTC, zahmis commented on src/server/service/page.js
> +    for (let i = 0; i < pages.length; i++) {
各ページに対して、path が等しいかどうかをチェックし、エラーハンドリングをしていました。
pages と originPages 双方を使いました。
さらに、順序を合わせるために、 166 行目で sort しています。

2021-01-12 07:08 UTC, yuki-takei commented
duplicateRecursively の改修はスコープ外では？

2021-01-12 07:08 UTC, yuki-takei requested changes

2021-01-12 07:08 UTC, yuki-takei commented on src/server/models/page.js
> +    const newStatus = newPagePathPrefix.match(/^\/trash/) ? STATUS_DELETED : STATUS_PUBLISHED;
trash 内かどうかは、ここで正規表現を使うのではなくシステム共通で用意している util を使って判断する

2021-01-12 07:08 UTC, yuki-takei commented on src/server/models/page.js
> +        unorderedBulkOp.find({ _id: page._id }).update({ $set: { path: newPagePath, status: newStatus } });
status の更新は、else の中だけでいいの？

2021-01-12 07:12 UTC, zahmis commented on src/server/models/page.js
> +        unorderedBulkOp.find({ _id: page._id }).update({ $set: { path: newPagePath, status: newStatus } });
すみません修正します。

2021-01-12 07:12 UTC, zahmis commented on src/server/models/page.js
> +    const newStatus = newPagePathPrefix.match(/^\/trash/) ? STATUS_DELETED : STATUS_PUBLISHED;
修正します

2021-01-12 07:25 UTC, zahmis commented on src/server/models/page.js
>          unorderedBulkOp.find({ _id: page._id }).update([{ $set: { path: newPagePath, lastUpdateUser: user._id, updatedAt: { $toDate: Date.now() } } }]);
ゴミ箱ないで rename することは不可能なので、metadata の場合に status をセットする必要はないと判断しました。

2021-01-12 07:25 UTC, zahmis commented on src/server/models/page.js
> +        unorderedBulkOp.find({ _id: page._id }).update({ $set: { path: newPagePath, status: newStatus } });
必要そうなのは else だけだと判断しました。
もしくは、明示的にするべきでしょうか？

2021-01-12 08:36 UTC, yuki-takei requested changes

2021-01-12 08:36 UTC, yuki-takei commented on src/server/models/page.js
> +        unorderedBulkOp.find({ _id: page._id }).update({ $set: { path: newPagePath, status: newStatus } });
もし

「updateMetadata オプションは rename では使われるが delete/revert では使われないはずなので、status の更新は必要ない」

という判断を行ったのであれば、renameRecursively がrename/delete/revert で使われる汎用的なメソッドという意味をまだわかっていない。もしそうなのであれば updateMetadata 時にも status が正しくセットされるようにしてください。そうでないのであれば必要なのが else だけだと判断した根拠の説明を。

2021-01-12 09:05 UTC, zahmis commented
すみません。
duplicate は 完全にミスです。

2021-01-12 09:16 UTC, zahmis commented on src/server/models/page.js
> +        unorderedBulkOp.find({ _id: page._id }).update({ $set: { path: newPagePath, status: newStatus } });
**updateMetadata オプションは rename では使われるが delete/revert では使われないはずなので、status の更新は必要ない」
という判断を行ったのであれば、renameRecursively がrename/delete/revert で使われる汎用的なメソッドという意味をまだわかっていない。**

自分の理解はこっちでした。
なので、 status をセットします。


これについての自分の再認識は、汎用的な method を語るのであれば、
updateMetadata があろうが無かろうが、status の更新は必要である。

となったのですが、いまいちよくわかっていないです。

わざわざつける必要がないと思っていたのですが、page を rename するというという状態変更がなされるに当たって、古いままの status の状態というのが理にかなっていないからでしょうか？

2021-01-12 10:14 UTC, yuki-takei requested changes

2021-01-12 10:14 UTC, yuki-takei commented on src/server/service/page.js
> +      if (originPages[i].redirectTo !== pages[i].path) {
元の実装の通りにするなら、

1. originPage の存在チェック
2. 存在するなら、redirectTo のチェック

を両方やる必要がある。この if 句はそれを満たさない。
i 番目の要素が、revert した先のページパスと同じだという保証がない。また欠落がある場合、例えばpagesが100件で、originPages が 90件しかなかった場合に破綻する。

2021-01-13 06:05 UTC, zahmis commented on src/server/service/page.js
> +      if (originPages[i].redirectTo !== pages[i].path) {
わかりました。
実装を修正します。

2021-01-14 15:44 UTC, closed without merging