imprv: removeAllAttachment
weseek/growi pull request #3278
Opened 2020-12-31 14:25 UTC by zahmis

2021-01-05 09:35 UTC, zahmis commented
処理前と処理後の メモリ使用量を掲載します
- 処理前
<img width="295" alt="スクリーンショット 2021-01-05 18 34 18" src="https://user-images.githubusercontent.com/57100766/103630156-a22bf800-4f84-11eb-8668-313f6be25d8c.png">

- 処理後
<img width="332" alt="スクリーンショット 2021-01-05 18 34 54" src="https://user-images.githubusercontent.com/57100766/103630214-b7088b80-4f84-11eb-9904-aeddf2f0b115.png">

2021-01-05 10:44 UTC, yuki-takei requested changes

2021-01-05 10:44 UTC, yuki-takei commented on src/server/service/page.js
> +    return;
ここに stream を使う戦略があまりよくない。
タスクに as is と to be を書いておいたので確認してください。

2021-01-12 08:50 UTC, zahmis commented on src/server/service/attachment.js
>        fileUploadService.deleteFile(attachment);
fileUploadService 関連は type ごとに aws gcp gridfs local の4 つの deleteFile が存在します。

gridfs.js では bulk 化してまとまりで消せるかもしれないですが、
local.js  などは fs.unlinkSync で ファイルを削除しています。

同じ deleteFile を使用していそうなので、  
引数に複数形の attachments を渡して動作させるのは難しいと感じました。

この後の方法として、以下のことを考えています。
ご意見が欲しいです。

- type ごとに deleteFile の処理を分ける改修をする。
- deleteFile は共通で 各 type の lib.deleteFile で頑張る。
- ここはいじらなくてもOK。

2021-01-12 10:17 UTC, yuki-takei requested changes

2021-01-12 10:17 UTC, yuki-takei commented on src/server/service/attachment.js
>        fileUploadService.deleteFile(attachment);
「type ごとに deleteFiles (複数) を実装する」が正しい道です。

2021-01-12 14:51 UTC, zahmis commented on src/server/service/attachment.js
>        fileUploadService.deleteFile(attachment);
ありがとうございます。
了解しました。タスクを分割します。

2021-01-12 14:51 UTC, zahmis commented on src/server/service/attachment.js
>        fileUploadService.deleteFile(attachment);
本タスクは ’attachment’ を bulk 化して削除するところまで行い、
fileUploadService.deleteFile(attachment) => fileUploadService.deleteFiles を 各 type ごとで実装するのは後続タスク化します。

2021-01-12 15:11 UTC, yuki-takei requested changes

2021-01-12 15:11 UTC, yuki-takei commented on src/server/service/attachment.js
>        fileUploadService.deleteFile(attachment);
deleteFiles のインターフェースまで作成してください。

つまり:
AttachmentService からは deleteFiles を呼ぶ。それぞれの file upload 系モジュールでは、bulk ではなく forEach を用いた削除を行うところまでこのタスクで実装する。
後続タスクではそれぞれのモジュールの deleteFiles を bulk 化する。

2021-01-12 15:12 UTC, yuki-takei requested changes

2021-01-12 15:12 UTC, yuki-takei commented on src/server/service/attachment.js
>        fileUploadService.deleteFile(attachment);
効能としては、後続タスクを分担作業してもコンフリクトが起こらなくなる。

2021-01-13 16:41 UTC, zahmis commented on src/server/service/file-uploader/uploader.js
> +  deleteFiles() {
インターフェイスを作成。
それに伴い、各ファイルで deleteFile => deleteFiles に名称変更。

2021-01-13 17:41 UTC, zahmis commented on src/server/service/attachment.js
> +    attachments.forEach((attachment) => {
attachment 自体はこの attachment.js service で bulk 化して消す方向にしています。
fileUpload 系 (files, chunks) は各type で消すように後続タスクを作成します。

2021-01-13 17:41 UTC, zahmis commented on src/server/service/page.js
> +    if (attachments.length > 0) {
deleteFiles を interface として実装した結果、削除するときに必ず bulk の中身が必要になり、
attachment.js において以下の部分で error が発生するようになりました。
```js
     unorderAttachmentsBulkOp.find({ _id: attachment._id }).remove();
    });	    });
    await unorderAttachmentsBulkOp.execute();
    return;
```

回避策として、attachments が存在する場合は 削除するように改修しています。

2021-01-13 17:52 UTC, zahmis commented on src/server/routes/attachment.js
> +    await fileUploadService.deleteFiles(attachment);
interface を実装した結果、名称を変更しています。

2021-01-13 17:52 UTC, zahmis commented on src/server/service/file-uploader/aws.js
> +  lib.deleteFiles = async function(attachment) {
interface を実装した結果、名称を変更しています。

2021-01-13 17:52 UTC, zahmis commented on src/server/service/file-uploader/gcs.js
> +  lib.deleteFiles = async function(attachment) {
interface を実装した結果、名称を変更しています。

2021-01-13 17:52 UTC, zahmis commented on src/server/service/file-uploader/gridfs.js
> +  lib.deleteFiles = async function(attachment) {
interface を実装した結果、名称を変更しています。

2021-01-13 17:52 UTC, zahmis commented on src/server/service/file-uploader/local.js
> +  lib.deleteFiles = async function(attachment) {
interface を実装した結果、名称を変更しています。

2021-01-13 17:55 UTC, zahmis commented on src/server/service/attachment.js
>        fileUploadService.deleteFile(attachment);
承知しました。

2021-01-14 00:14 UTC, itizawa commented on src/server/service/attachment.js
> +    return;
await しなくて良いのでは

2021-01-14 04:44 UTC, zahmis commented on src/server/routes/attachment.js
> +    await fileUploadService.deleteFiles(attachment);
単一の場合を考えていませんでした。
deleteFile はそのまま残し使えるように修正します。

2021-01-14 04:44 UTC, zahmis commented on src/server/service/file-uploader/aws.js
> +    });
良いですね・・・
修正します。

2021-01-14 05:13 UTC, zahmis commented on src/server/routes/attachment.js
routes で removeAttachment が作成されていましたが、 attachmentService でもあるのでそちらを使います

2021-01-14 05:13 UTC, zahmis commented on src/server/service/attachment.js
> +  async removeAllAttachments(attachments) {
名称を変更しました

2021-01-14 05:13 UTC, zahmis commented on src/server/service/attachment.js
> +  async removeAllAttachments(attachments) {
単一の削除、(userImage や 単純に 添付ファイルを削除する場合など) と分けることにしました

2021-01-14 05:13 UTC, zahmis commented on src/server/service/page.js
> +      attachmentService.removeAllAttachments(attachments),
removeAllAttachment に処理させることで 余計な関数を減らしました。

2021-01-14 06:40 UTC, merged