imprv/gw-4776
weseek/growi pull request #3281
Opened 2021-01-04 08:19 UTC by takeru0001

2021-01-04 09:50 UTC, takeru0001 commented on src/server/models/page.js
> +    }
すでに存在するパスがある場合、`unorderedBulkOp`で処理は実行されますがエラーがはかれるためパス重複のエラーコード(11000)だった場合はエラーを出さなくしました。

2021-01-05 11:21 UTC, yuki-takei requested changes

2021-01-05 11:21 UTC, yuki-takei commented on src/server/models/page.js
> +    pageEvent.on('createMany', pageEvent.onCreateMany);
delete と同じように、create も array 対応にする

2021-01-05 11:21 UTC, yuki-takei commented on src/server/service/search-delegator/elasticsearch.js
> +  async syncDescendantsPagesUpdated(page, user) {
第一引数を array 対応にする

2021-01-05 11:21 UTC, yuki-takei commented on src/server/service/search-delegator/elasticsearch.js
> +    const pages = await Page.findManageableListWithDescendants(page, user);
この操作は不要になる

2021-01-07 05:05 UTC, takeru0001 commented on src/server/service/search-delegator/elasticsearch.js
> +    const pages = await Page.findManageableListWithDescendants(page, user);
削除しました

2021-01-07 05:06 UTC, takeru0001 commented on src/server/service/search-delegator/elasticsearch.js
> +  async syncDescendantsPagesUpdated(page, user) {
対応しました。

2021-01-07 05:15 UTC, takeru0001 commented on src/server/models/page.js
> +    pageEvent.emit('createMany', renamedPages, user, newParentPage);
socketによる別ブラウザへの通知は実装していないので引数の`socketClientId`を削除し、新たに必要になったnewParentPageに変更しました。

2021-01-07 05:16 UTC, takeru0001 commented on src/server/models/page.js
> +    pageEvent.on('createMany', pageEvent.onCreateMany);
対応しました。

2021-01-07 09:54 UTC, merged