Support/3808 4827 is able to show page reaction buttons swr
weseek/growi pull request #3284
Opened 2021-01-05 05:55 UTC by itizawa

2021-01-05 11:44 UTC, yuki-takei requested changes

2021-01-05 11:44 UTC, yuki-takei commented on src/pages/[[...path]].tsx
> +  props.isAbleToShowPageReactionButtons = (!props.isTrash && !props.isNotFound && !isSharedUser);
この名前の変数がサーバーサイドに出てくるのはおかしい

2021-01-05 11:44 UTC, yuki-takei commented on src/pages/[[...path]].tsx
> +  props.isShared = isSharedPage(props.currentPagePath);
この2つはクライアントのみで判断できるのでは？

2021-01-06 10:07 UTC, itizawa commented on src/pages/[[...path]].tsx
> +  const isSharedUser = (props.currentUser == null && isSharedPage(props.currentPagePath));
isSharedUser は、`useIsAbleToShowXXXXX` でしか使わないと思いますが swr 化すべきでしょうか

2021-01-06 10:51 UTC, yuki-takei commented on src/pages/[[...path]].tsx
> +  const isSharedUser = (props.currentUser == null && isSharedPage(props.currentPagePath));
複数コンポーネントで参照する場合は必要になりそう。

2021-01-07 05:25 UTC, merged