After setting the mixin using css animation, I applied the style of e…
weseek/growi pull request #3285
Opened 2021-01-05 07:07 UTC by shukmos

## やったこと
- 消えるcss アニメーションを作成
  - mixin で設定した
  - 各テーマのスタイルシートでincludeで呼び出して実装

## XD
- https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/855d549a-082d-468a-a3e3-cd62f7e7e0a7

2021-01-05 12:13 UTC, yuki-takei requested changes

2021-01-05 12:13 UTC, yuki-takei commented on src/client/styles/scss/theme/christmas.scss
> +      @include highlighted($primary, 0.5);
引数の2つの変数を各テーマで指定するだけでよいようにしてください。mixin の適用は apply-colors でやる。

2021-01-05 12:13 UTC, yuki-takei commented on src/client/styles/scss/_mixins.scss
> +  }
多すぎる

2021-01-08 02:19 UTC, kaoritokashiki commented on src/client/styles/scss/_mixins.scss
> +  @keyframes vanishing {
変数名を`fadeout`に変更してください。

2021-01-08 02:33 UTC, kaoritokashiki requested changes

2021-01-08 02:33 UTC, kaoritokashiki commented on src/client/styles/scss/_mixins.scss
> +  @keyframes vanishing {
`vanishing`を`fadeout`に変更してください。

2021-01-08 02:33 UTC, kaoritokashiki commented on src/client/styles/scss/_mixins.scss
> +    animation: vanishing 1s ease-in 1.5s forwards;
ここも同じくfadeoutに変更

2021-01-12 10:30 UTC, yuki-takei requested changes

2021-01-12 10:30 UTC, yuki-takei commented on src/client/styles/scss/_wiki.scss
> +    padding: 1rem 0.25rem;
highlight 時ではない通常状態にも影響が出てしまうと思う。before/after のスクリーンショットを見たい。

2021-01-13 08:24 UTC, shukmos commented on src/client/styles/scss/_wiki.scss
> +    padding: 1rem 0.25rem;
- padding-top: 0.5em; がある場合
![image](https://user-images.githubusercontent.com/20252919/104425423-0160bc80-55c4-11eb-87d5-3155a0ec5b76.png)
- padding-top: 0.5em; がない場合
![image](https://user-images.githubusercontent.com/20252919/104425505-1b020400-55c4-11eb-9125-2149dc4fa8aa.png)

2021-01-13 08:26 UTC, shukmos commented
- padding-top: 0.5em; がある場合
![image](https://user-images.githubusercontent.com/20252919/104425800-73390600-55c4-11eb-8fcf-6e84f4897b10.png)
- padding-top: 0.5em; がない場合
![image](https://user-images.githubusercontent.com/20252919/104425820-77652380-55c4-11eb-8b99-6fc3f45038e4.png)

2021-01-13 08:27 UTC, shukmos commented on src/client/styles/scss/_wiki.scss
> +    padding: 1rem 0.25rem;
よく考えたらここまで細かく修正しなくてもいな思ったので、最小限の変更にとどめます。

2021-01-13 09:53 UTC, merged