Imprv/make is able to show tag label swr
weseek/growi pull request #3293
Opened 2021-01-07 07:38 UTC by kaoritokashiki

2021-01-07 07:56 UTC, kaoritokashiki commented on src/client/js/services/PageContainer.js
> +  // }
pageContainerで宣言されていたisAbleToShowTagLabelをコメントアウトし、swr化されたよという旨ののコメントを追加しました。

2021-01-07 10:26 UTC, yuki-takei requested changes

2021-01-07 10:26 UTC, yuki-takei commented on src/stores/context.tsx
> +
これはあえて context として用意する必要はないかな。`src/utils/path-utils` の `isUserPage` メソッドを使えばよい。

2021-01-07 10:26 UTC, yuki-takei commented on src/stores/ui.tsx
> +};
[/資料/外部仕様/クライアント側で可能な操作一覧](https://dev.growi.org/5fabddf8bbeb1a0048bcb9e9) によると、isAbleToShowTagLabel の条件ってもっと複雑じゃない？

`GrowiSubNavigation.jsx` の125行目にも追加の条件があるのは認識しているけれど、このままだと wiki と整合性取れてない気がするので、コードまたはwikiまたは両方、よしなに修正してください。

2021-01-07 10:26 UTC, yuki-takei commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +import { useIsAbleToShowTagLabel } from '../../../../stores/ui';
`~` 使った方が読みやすい

2021-01-08 15:52 UTC, kaoritokashiki commented on src/stores/ui.tsx
> +};
> GrowiSubNavigation.jsx の125行目にも追加の条件がある
それらの追加の条件を合わせて`isAbleToShowTagLabel `としようとすると時間がかかりそうなので、タスクを新たに作成し、TODOコメントを記載しました。以下のタスクで着手します
GW-4881 swr化されたisAbleToShowTagLabelの拡張

2021-01-08 16:15 UTC, merged