Imprv/4685 4870 use stream for duplicate pages
weseek/growi pull request #3295
Opened 2021-01-08 04:59 UTC by itizawa

2021-01-08 08:11 UTC, itizawa commented on src/server/service/page.js
> +
stream の改修によって、複製後のリダイレクト先にページが存在しない状況が発生しうるので 親ページと子ページの複製は分けて実行する戦略を取りました。

2021-01-08 09:54 UTC, yuki-takei requested changes

2021-01-08 09:54 UTC, yuki-takei commented on src/server/service/page.js
> +    const pages = await Page.findManageableListWithDescendants(page, user, { onlyDescendants: true });
findManageableListWithDescendants は query ではなく page の全件の実体を返すので、stream を使う意味がない。
PageQueryBuilder でクエリを組み立てて stream を得る必要がある。

2021-01-08 09:54 UTC, yuki-takei commented on src/server/service/page.js
> +          await Revision.insertMany(newRevisions, { ordered: false });
async write() 内のロジックのうち、ここまでの部分は別メソッドに切り出して。

2021-01-08 09:54 UTC, yuki-takei commented on src/server/models/page.js
> +    const onlyDescendants = option.onlyDescendants || false;
こういうオプション、実装の混乱の元なので、これまでは削減してきた。あまり新たに作りたくはない。
(ts になったらだいぶましにはなるのだが)

2021-01-12 08:21 UTC, yuki-takei requested changes

2021-01-12 08:21 UTC, yuki-takei commented on src/server/service/page.js
> +  async duplicateStream(page, newPagePath, user) {
このメソッドも descendants のみを複製することには変わりないので、duplicateDescendantsWithStream とする。

2021-01-12 08:21 UTC, yuki-takei commented on src/server/service/page.js
> +      .lean()
lean ってやらないほうがいいみたいなのなかったっけ…
外部からPR来て消した記憶。

2021-01-12 08:21 UTC, yuki-takei commented on src/server/service/page.js
> +          logger.info(`Adding pages progressing: (count=${count})`);
debug レベルでいいかなあ

2021-01-12 08:55 UTC, merged