Imprv/make is able to show like button swr
weseek/growi pull request #3296
Opened 2021-01-08 09:21 UTC by kaoritokashiki

2021-01-08 12:37 UTC, kaoritokashiki commented on src/stores/ui.tsx
> +  const { path } = page as Page;
```
const { path } = page
```
だけだと、型推論が効かず、`path: any`とみなされて
`Property ‘path’ does not exist on type ‘Page | undefined’.`
というエラーが表示されてしまうのを修正しました。

2021-01-08 16:14 UTC, yuki-takei requested changes

2021-01-08 16:14 UTC, yuki-takei commented on src/stores/ui.tsx
> +  const { path } = page as Page;
null チェックの問題と言うことがまだわかっていない。
エラーが出るのは、Page 型だと断定できず undefined の可能性を潰せてないのが問題。

## 解1
```
if (page == null) {
  throw new Error('page must not be null');
}
```
を入れるとそのエラーは消えると思う。なぜだか考えてみよう。

## 解2
```
  const isCurrentPageUserPage = page == null ? false : !isUserPage(page.path);
```
でもエラーは出ない。なぜだか考えてみよう。

2021-01-09 05:40 UTC, kaoritokashiki commented on src/stores/ui.tsx
> +  const { path } = page as Page;
```
/**
 * Whether path belongs to the user page
 * @param path
 */
export const isUserPage = (path: string): boolean => {
  // https://regex101.com/r/SxPejV/1
  if (path.match(/^\/user(\/.*)?$/)) {
    return true;
  }

  return false;
};
```
`path-utils.ts`で定義された`isUserPage()`関数は引数にstring型であるpathが渡って来るのにもかかわらず、
`ui.tsx`で`isUserPage()`を呼び出す時にundefinedを渡してしまう可能性があるから....
だと認識しました。

2021-01-12 07:03 UTC, yuki-takei commented on src/stores/ui.tsx
> +  const { path } = page as Page;
:+1:

2021-01-12 07:03 UTC, merged