Imprv/4685 4874 duplicate tags
weseek/growi pull request #3298
Opened 2021-01-12 03:08 UTC by itizawa

2021-01-12 09:07 UTC, itizawa commented on src/server/service/page.js
> +      });
PageTagRelation の性質上内部で find せざるを得ない気がします...
mongo に bulkCopy 的なのがないので

2021-01-12 09:47 UTC, yuki-takei requested changes

2021-01-12 09:47 UTC, yuki-takei commented on src/server/service/page.js
> +      });
1. forEach で、「コピー元ページID と コピー先ページID の対応」の map を作っておく
2. aggregation を使って relatedTag をキーにして、どのタグにどのコピー元ページIDが紐付くのかを得る
3. 2 で得た結果を走査し、1で作った map と突合させて bulk insert する PageTagRelation を作る

ちょっとめんどくさいけど、上記手順で MongoDB へのアクセスは aggregation 1発で済む。
別メソッドに切り出せると綺麗。

2021-01-13 06:03 UTC, yuki-takei requested changes

2021-01-13 06:03 UTC, yuki-takei commented on src/server/service/page.js
> +    });
131行目でも走査してるから、一緒にしてしまえば？2回回す意味はないよね？

2021-01-13 08:00 UTC, merged