Imprv/make is able to show page authors swr
weseek/growi pull request #3299
Opened 2021-01-12 05:09 UTC by kaoritokashiki

2021-01-12 05:12 UTC, kaoritokashiki commented on src/stores/ui.tsx
> +};
isCompactModeは見た目に関するものだと判断したため、bool判定式を`ui.tsx`に記載しました。
もし認識が違っていたら教えてください。

2021-01-12 05:29 UTC, kaoritokashiki commented on src/pages/[[...path]].tsx
> +  isCompactMode: boolean,
`isCompactMode`はpropsで渡すので、ここにも追加しました。

ちなみに、このGrowiPageは初期値(コンストラクタ)のようなものと教えていただき、その認識でいます。
```
const GrowiPage: NextPage<Props> = (props: Props) => {
  const router = useRouter();
```

2021-01-12 05:44 UTC, kaoritokashiki commented on src/pages/[[...path]].tsx
> +  isCompactMode?: boolean,
`isCompactMode`はpropsでも渡すので、ここにも追加しました。
また、optionalだと判断したため、`?`をつけました。

ちなみに、このGrowiPageに羅列されているカスタムフックは初期値(コンストラクタ)のようなものと教えていただき、その認識でいます。
(認識が違うと後々大変なことになりそうなのと、教えてもらったことを間違って解釈していないかの確認で言っています。)
```
const GrowiPage: NextPage<Props> = (props: Props) => {
  const router = useRouter();

  useCurrentUser(props.currentUser != null ? JSON.parse(props.currentUser) : null);
  useCurrentPagePath(props.currentPagePath);
  useOwnerOfCurrentPage(props.pageUser != null ? JSON.parse(props.pageUser) : null);
  useForbidden(props.isForbidden);
  useNotFound(props.isNotFound);
  useCompactMode(props.isCompactMode);
  useTrash(isTrashPage(props.currentPagePath));
  useShared(isSharedPage(props.currentPagePath));
  useIsAbleToDeleteCompletely(props.isAbleToDeleteCompletely);
  useIsSharedUser(props.currentUser == null && isSharedPage(props.currentPagePath));
```

2021-01-12 09:31 UTC, yuki-takei requested changes

2021-01-12 09:31 UTC, yuki-takei commented on src/pages/[[...path]].tsx
> +  isCompactMode?: boolean,
62行目以下が「ページ表示に於ける初期値のセット」という認識は合っている。

2021-01-12 09:31 UTC, yuki-takei commented on src/pages/[[...path]].tsx
> +  useCompactMode(props.isCompactMode);
isCompactMode を props で受け取るコンポーネントが compact mode なのかどうかは、ページ表示の度に一意に決まる値ではないので、swr (ステートのグローバルストア) を使うのは間違っている。

2021-01-12 09:31 UTC, yuki-takei commented on src/stores/ui.tsx
> +};
isCompactMode を props で受け取るコンポーネントが compact mode なのかどうかは、ページ表示の度に一意に決まる値ではないので、swr (ステートのグローバルストア) を使うのは間違っている。

2021-01-12 09:31 UTC, yuki-takei commented on src/client/js/components/Navbar/GrowiSubNavigation.jsx
> +        { (isAbleToShowPageAuthors) && (
isCompactMode は props から受け取る必要がある。

2021-01-13 01:25 UTC, kaoritokashiki commented on src/stores/ui.tsx
> +};
何をグローバルストアで管理するかの認識が曖昧でした。

あるコンポーネントAに、isCompactModeがtrueのコンポーネントBと、falseのコンポーネントCの二つがある場合、コンポーネントAは一概にcompactModeがtrueかfalseかは言えない。(それぞれのコンポーネントでisCompactModeがtrueかfalseかは変わってくるので)ということですね。

したがって、グローバルステート として管理するのは、
コンポーネントのpropsにuiを左右されないものであると認識しました。

2021-01-13 03:13 UTC, yuki-takei requested changes

2021-01-13 03:13 UTC, yuki-takei commented on src/stores/ui.tsx
> +  const { data: isNotFountPage } = useNotFound();
typo

2021-01-13 03:14 UTC, yuki-takei commented
wiki の `isAbleToShowPageAuthors = !isCompactMode && !isUserPage && isPageExist` は誤りだと思うので書き換えてください。
加えて `!isCompactMode && isAbleToShowPageAuthors` でのみ表示する仕様になっていることも明記。

2021-01-13 09:37 UTC, kaoritokashiki commented on src/stores/ui.tsx
> +  return useStaticSWR('isAbleToShowPageReactionButtons', !isTrashPage && !isNotFoundPage && !isSharedUser);
既にマージ済(スコープ外)の部分ですが、ついでにtypo修正しました。

2021-01-13 09:38 UTC, kaoritokashiki commented
WIkiを正しく修正しました。 
- [/資料/外部仕様/クライアント側で可能な操作一覧](https://dev.growi.org/5fabddf8bbeb1a0048bcb9e9)

2021-01-13 09:41 UTC, kaoritokashiki commented on src/stores/ui.tsx
> +};
`isNotFountPage` →`isNotFoundPage`
typoを修正しました。

2021-01-13 09:55 UTC, merged