imprv/gw-4871
weseek/growi pull request #3305
Opened 2021-01-14 06:17 UTC by takeru0001

2021-01-14 06:22 UTC, takeru0001 commented
確認のために`[[...path]].tsx`で`useDecendantsCount`を呼び出したときに配下ページ数が取得できていました。

<img width="782" alt="スクリーンショット 2021-01-14 13 46 02" src="https://user-images.githubusercontent.com/58085267/104552341-fcf7da80-567b-11eb-8816-b4d583639a6b.png">

2021-01-14 08:00 UTC, yuki-takei requested changes

2021-01-14 08:00 UTC, yuki-takei commented on src/server/routes/apiv3/pages.js
> +      const result = pages.length;
* 2回DBオペレーションが走る
* MongoDB の count オペレーションではなく find が走るかつ不要な populate が行われる

で効率が悪いので、count 専用の countManageableListWithDescendants メソッドを作ってください。

2021-01-14 08:48 UTC, takeru0001 commented on src/server/routes/apiv3/pages.js
> +    decendantsCcount: [
確認ミスでした。修正しました。

2021-01-15 04:54 UTC, takeru0001 commented on src/server/routes/apiv3/pages.js
> +      const result = pages.length;
メソッドを作成しました

2021-01-15 08:25 UTC, merged