Imprv/bulk chunks and files in gridfs
weseek/growi pull request #3317
Opened 2021-01-18 03:47 UTC by zahmis

2021-01-18 08:35 UTC, yuki-takei requested changes

2021-01-18 08:35 UTC, yuki-takei commented on src/server/service/attachment.js
> +    await unorderAttachmentsBulkOp.execute();
ここちょっとついでのリファクタになるんだけれど、以下をやってください。

- Attachments の remove を先にやって、その後で deleteFiles
- deleteFiles も await する

2021-01-18 08:35 UTC, yuki-takei commented on src/server/service/file-uploader/gridfs.js
> +    attachmentFileIds.forEach((attachmentFileId) => { unorderChunkBulkOp.find({ files_id: attachmentFileId }).remove() });
forEach 4回も回すのは効率が悪すぎる。

データを取得してきて unorderedBulkOp 組み立てが必要な場合もあるけれど、$in などを使って find と remove を MongoDB に任せることができるケースかどうか検討してください。

2021-01-18 08:40 UTC, zahmis commented on src/server/service/file-uploader/gridfs.js
> +    attachmentFileIds.forEach((attachmentFileId) => { unorderChunkBulkOp.find({ files_id: attachmentFileId }).remove() });
わかりました。
試してみます。

2021-01-18 12:35 UTC, zahmis commented on src/server/service/file-uploader/gridfs.js
> +    attachmentFileIds.forEach((attachmentFileId) => { unorderChunkBulkOp.find({ files_id: attachmentFileId }).remove() });
$in を使用した find remove のしようを検討したのですが、
無駄な forEach を2 つ消すことができ、整ったと感じています。
$ in find() remove の組み合わせを考えたのですが、今の状態がベストだと考えました。

2021-01-18 12:50 UTC, yuki-takei requested changes

2021-01-18 12:50 UTC, yuki-takei commented on src/server/service/file-uploader/gridfs.js
> +    attachments.forEach(attachment => filenameValues.push(attachment.fileName));
- この forEach 内で fileName を取れるなら、この時点で unorderFilesBulkOp に突っ込めばいい
- もっと言えば、unorderFilesBulkOp を使わなくても $in と remove の組み合わせで消してもよい
    - そうすると forEach より map が適切

2021-01-18 12:50 UTC, yuki-takei commented on src/server/service/file-uploader/gridfs.js
> +    const attachmentFiles = await AttachmentFile.find({ filename: { $in: filenameValues } });
- ここでは select で _id のリストを得る
- unorderChunkBulkOp は必要ない、なぜなら上記で得た _id リストを $in で指定すれば単に remove を1回実行すればいいだけなので
- そうすると58～60行目の forEach は不要

2021-01-20 08:00 UTC, zahmis commented on src/server/service/file-uploader/gridfs.js
> +    const attachmentFiles = await AttachmentFile.find({ filename: { $in: filenameValues } });
修正します。

今回 bulk を用いずに削除することにしました。

2021-01-20 08:30 UTC, yuki-takei requested changes

2021-01-20 08:30 UTC, yuki-takei commented on src/server/service/file-uploader/gridfs.js
> +  // const FILES_COLLECTION_NAME = `${COLLECTION_NAME}.files`;
不要な行は消す

2021-01-20 08:30 UTC, yuki-takei commented on src/server/service/file-uploader/gridfs.js
> +  // const filesCollection = mongoose.connection.collection(FILES_COLLECTION_NAME);
不要な行は消す

2021-01-20 08:30 UTC, yuki-takei commented on src/server/service/file-uploader/gridfs.js
> +      return;
map の使い方がおかしい

2021-01-20 08:30 UTC, yuki-takei commented on src/server/service/file-uploader/gridfs.js
> +    const idsRelatedFiles = fileIds.map((file) => { return file._id });
そんなに重要なことではないが、Query.map を使える。

https://mongoosejs.com/docs/api/query.html#query_Query-map

2021-01-20 08:30 UTC, yuki-takei commented on src/server/service/file-uploader/gridfs.js
> +    await AttachmentFile.find({ filename: { $in: filenameValues } }).remove();
find and remove はやめよう

2021-01-20 10:35 UTC, zahmis commented on src/server/service/file-uploader/gridfs.js
> +    await AttachmentFile.find({ filename: { $in: filenameValues } }).remove();
deleteMany に変更します。

2021-01-20 10:35 UTC, zahmis commented on src/server/service/file-uploader/gridfs.js
> +    const idsRelatedFiles = fileIds.map((file) => { return file._id });
使ってみます。

2021-01-20 10:35 UTC, zahmis commented on src/server/service/file-uploader/gridfs.js
> +      return;
修正しました。

2021-01-20 10:35 UTC, zahmis commented on src/server/service/file-uploader/gridfs.js
> +  // const filesCollection = mongoose.connection.collection(FILES_COLLECTION_NAME);
すみません。

2021-01-20 10:35 UTC, zahmis commented on src/server/service/file-uploader/gridfs.js
> +  // const FILES_COLLECTION_NAME = `${COLLECTION_NAME}.files`;
すみません。

2021-01-20 10:52 UTC, yuki-takei requested changes

2021-01-20 10:52 UTC, yuki-takei commented on src/server/service/file-uploader/gridfs.js
> +    });
https://github.com/weseek/growi/pull/3317#discussion_r560762504
に戻しましょう。ごめんなさい。

2021-01-20 10:52 UTC, yuki-takei commented on src/server/service/file-uploader/gridfs.js
> +    return;
上記2つの promises を Promise.all するとベスト、Promise.all の呼び出し自体を return

2021-01-21 03:03 UTC, merged