Imprv/gw4932 add endpoint
weseek/growi pull request #3323
Opened 2021-01-19 03:33 UTC by kaoritokashiki

2021-01-19 05:24 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-bot.js
> +  });
ひとまず、`/_api/v3/slack-bot`を叩いたらjsonが返ってくるようにしました。
<img width="480" alt="Screen Shot 2021-01-19 at 14 22 45" src="https://user-images.githubusercontent.com/59536731/104991343-d9f56e00-5a61-11eb-9a28-5b3e5a79215b.png">

2021-01-19 14:03 UTC, yuki-takei requested changes

2021-01-19 14:03 UTC, yuki-takei commented on src/server/routes/apiv3/slack-bot.js
> +  router.get('/', async(req, res) => {
route の URL はこれで合っている？つまり、slackbot 側に GROWI のサーバーを登録した際に、`/_api/v3/slack-bot` を叩いてくれるような設定が可能？

2021-01-20 02:49 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-bot.js
> +  router.get('/', async(req, res) => {
slack botの機能の一つである`slash command`の`Request URL`に`~~/_api/v3/slack-bot`を指定すれば良さそうです。
ただ、後続タスクでgetではなくpostになりそうなのと、`/`だけじゃなくて`/command`の方がいいのかなと思いました。

2021-01-20 02:49 UTC, merged