Imprv/show admin markdown page
weseek/growi pull request #3334
Opened 2021-01-20 07:41 UTC by yusuketk

2021-01-20 08:34 UTC, yuki-takei requested changes

2021-01-20 08:34 UTC, yuki-takei commented on src/pages/admin/markdown.tsx
> +import BasicLayout from '../../components/BasicLayout';
Admin 用のレイアウト作ってください。他の画面でも必要になると思うので。
タスクは分割してもよい。

2021-01-20 08:34 UTC, yuki-takei commented on src/pages/admin/markdown.tsx
> +  confidential: string,
appTitle は CommonProps に入ってる。
confidential は入っていないけど含めてしまってもいいかも。

2021-01-21 04:52 UTC, yusuketk commented on src/components/AdminLayout.tsx
> +import dynamic from 'next/dynamic';
Admin画面用のレイアウトを作成しました

2021-01-21 04:52 UTC, yusuketk commented on src/pages/admin/index.tsx
>  import {
admin home 画面はタスクの管轄外ですが、AdminLayout の適用と、appTitleおよびconfidential を CommonPropsのを使うように修正しました

2021-01-21 11:20 UTC, yuki-takei requested changes

2021-01-21 11:20 UTC, yuki-takei commented on src/components/AdminLayout.tsx
> +  const AdminNavigation = dynamic(() => import('~/client/js/components/Admin/Common/AdminNavigation'), { ssr: false });
- navigation は重要なのでユニバーサル化して SSR する
- AdminNavigation が `window.location` から自律的に current active item を決定する仕組みをやめて、props から指定させる

2021-01-22 05:58 UTC, yusuketk commented on src/components/AdminLayout.tsx
> +import AdminNavigation from '~/client/js/components/Admin/Common/AdminNavigation';
dynamic は使わず ssr 
props にselected option を渡すようにしています

2021-01-22 07:24 UTC, merged