feat/add environment viriable #4975
weseek/growi pull request #3341
Opened 2021-01-21 07:50 UTC by kntowd

2021-01-21 08:32 UTC, Yohei-Shiina requested changes

2021-01-21 08:32 UTC, Yohei-Shiina commented on src/server/service/config-loader.js
> +    default: null,
これだと GROWI_CLOUD_URL を参照したときに null が返るのでは。

default 値は、GROWI_CLOUD_URLの値が渡ってきていればその値を返して、なければ null じゃないかな

process.env で参照できた値は、サーバー起動時に渡したものを直接見ただけであって、ここに追記した環境変数は関係ないと思う(違ってたらごめん)

ここに追記してセットした環境変数の値を確認したいということであれば、これはチームの人にその確認方法を聞いてみてほしい

2021-01-22 04:10 UTC, kntowd commented on src/server/service/config-loader.js
> +    default: null,
これ初期値はnullで環境変数がGROWI.cloud側から送られてきたら送られてきた値で上書きされるみたいなことだと思います。FILE_UPLOADとかをみてみた限りだと

2021-01-22 07:54 UTC, kntowd reviewed
環境変数が読み込めるかどうかは、以下の記述を src/server/routes/admin に仕掛けて確認しました。
```
console.log('環境変数', configManager.getConfig('crowi', 'growiCloud:growiCloudUrl'));
```

以下の記述をenv.dev.jsに
```
GROWI_CLOUD_URL: 'https://growi.cloud',
```

追記をした時は
```
https://growi.cloud
```
がログに表示され、

コメントアウトすると null がログに表示されました。

2021-01-22 07:54 UTC, kntowd commented on config/env.dev.js
> +  // GROWI_CLOUD_URL: 'https://growi.cloud',
staffクレジットの開発をする時用に環境変数をコメントアウトして追記しました。（スタッフクレジットの開発するときだけコメントアウトする予定）必要無かったら消します。

2021-01-22 07:54 UTC, kntowd commented on src/server/service/config-loader.js
> +    default: null,
dbのconfigsに ns: 'crowi', key: 'growiCloud:growiCloudUrl'に該当する、documentが無ければenv.dev.jsの値を参照してくれるみたいです。env.dev.js に GROWI_CLOUD_URLがない場合はnullが帰ってきます（default値）

2021-01-22 08:37 UTC, Yohei-Shiina commented on src/server/service/config-loader.js
> +    default: null,
このコードがマージされたら、アプリ側で環境変数の値を取得できるという認識？

2021-01-22 08:39 UTC, kntowd commented on src/server/service/config-loader.js
> +    default: null,
そうだと思ってます。このコード＋env.dev.jsに環境変数の値をいれたらGROWI_CLOUD_URLを取得できたので本番の環境変数ファイルでも同じ挙動になるかと思います。後でマージされてから確認必要ですが。

2021-01-25 02:48 UTC, Yohei-Shiina commented on src/server/service/config-loader.js
> +    default: null,
理解した。ここのコード自体は良いと思う

2021-01-25 09:48 UTC, yuki-takei requested changes

2021-01-25 09:48 UTC, yuki-takei commented on src/server/service/config-loader.js
> +    key:     'growiCloud:growiCloudUrl',
`app:growiCloudUri` にしてください。

2021-01-25 12:23 UTC, yuki-takei requested changes

2021-01-25 12:23 UTC, yuki-takei commented on src/server/service/config-loader.js
> +  GROWI_CLOUD_URL: {
直すならこっちもだよねー

2021-01-25 14:18 UTC, merged