Imprv/fetch admin markdown settings page data
weseek/growi pull request #3346
Opened 2021-01-22 07:12 UTC by yusuketk

2021-02-01 05:46 UTC, yusuketk commented on src/client/js/components/Admin/MarkdownSetting/LineBreakForm.jsx
> +const LineBreakForm = (props) => {
functional componentにして MarkDownSettingContents から受け取ったLineBreakに関するpropsをstateで管理するようにしました。
更新ボタンを押すとこのコンポーネント自身がapiv3Putを送信します

2021-02-01 05:46 UTC, yusuketk commented on src/client/js/components/Admin/MarkdownSetting/PresentationForm.jsx
> +const PresentationForm = (props) => {
functional componentにして MarkDownSettingContents から受け取ったPresentationに関するpropsをstateで管理するようにしました。
更新ボタンを押すとこのコンポーネント自身がapiv3Putを送信します

2021-02-01 05:46 UTC, yusuketk commented on src/client/js/components/Admin/MarkdownSetting/WhiteListInput.jsx
> +    this.props.onTagWhiteListChange(tags);
adminMarkdownContainerではなく親コンポーネントのXssFormのstateをコントロールするようにしました

2021-02-01 05:46 UTC, yusuketk commented on src/client/js/components/Admin/MarkdownSetting/XssForm.jsx
> +const XssForm = (props) => {
functional componentにして MarkDownSettingContents から受け取ったLineBreakに関するpropsをstateで管理するようにしました。
更新ボタンを押すとこのコンポーネント自身がapiv3Putを送信します

2021-02-01 05:46 UTC, yusuketk commented on src/client/js/util/apiv3-client.ts
> +    const opts = {
XHR + preflight での csrf 対策とのことでリクエストヘッダに 'X-Requested-With': 'XMLHttpRequest' を付けました

2021-02-01 05:46 UTC, yusuketk commented on src/server/routes/apiv3/markdown-setting.js
> +  router.put('/lineBreak', loginRequiredStrictly, adminRequired, validator.lineBreak, apiV3FormValidator, async(req, res) => {
'X-Requested-With': 'XMLHttpRequest' ヘッダによりcsrfはXHR + preflight的に対策できているため、csrf ミドルウェアは不要と判断しています。

2021-02-01 10:05 UTC, yuki-takei requested changes

2021-02-01 10:05 UTC, yuki-takei commented on src/client/js/components/Admin/MarkdownSetting/PresentationForm.jsx
> +const PresentationForm = (props) => {
- react-hook-form を使う
    - InstallerForm で使ってる
    - GROWI.cloud チームにも知見が貯まっているのでそちらもあてにする
- onClick ではなく、form の submit に対して onClickSubmit でやっている処理がトリガーされるようにする
    - これは react-hook-form を正しく使えば自然にそうなる
- `useMarkdownSettingsSWR` で一括して値を取るのではなく、GET /markdown-setting/presentation 用の swr を作る
    - そうすることで、PresentationForm では state 管理の必要がなくなる
- 値を更新したあとの swr の再発火は少し考える必要がある
    - 明示的に再発火させる必要があるばあいは useEffect を使うことになるだろう

2021-02-04 01:17 UTC, yusuketk commented on src/client/js/components/Admin/MarkdownSetting/PresentationForm.jsx
> +const PresentationForm = (props) => {
useForm, useEffect を利用し値を管理するようにしました

2021-02-04 01:17 UTC, yusuketk commented on src/client/js/util/apiv3-client.ts
> +    const opts = {
了解です。

2021-02-04 06:58 UTC, yuki-takei commented on src/client/js/components/Admin/MarkdownSetting/XssForm.jsx
> +const XssForm = (props) => {
XSS 関連は、今使っている設定値(config)もまるっと再設計になるかもしれない。
もう決行やっちゃってるところ申し訳ないんだけど、一旦適当でいいです。完全再現できなくてもOK。

2021-02-05 06:24 UTC, itizawa commented on src/client/js/components/Admin/MarkdownSetting/LineBreakForm.jsx
> +  });
分割代入を使って `const {register}` としても良さそう

2021-02-05 06:30 UTC, itizawa commented on src/client/js/components/Admin/MarkdownSetting/LineBreakForm.jsx
> +            name="isEnabledLinebreaks"
`const isEnabledLinebreaks InputName = 'isEnabledLinebreaks';`

上で name を変数で固定した方が良さそうです

2021-02-05 06:30 UTC, itizawa commented on src/client/js/components/Admin/MarkdownSetting/PresentationForm.jsx
> +  }, [data?.pageBreakCustomSeparator]);
mutate で更新後に値を再取得、 setValue で再設定する戦略ってどうなんですかね...
security がやばいことになりそうで... もし解決策とかあれば模索したいですね

2021-02-05 06:32 UTC, itizawa commented on src/client/js/components/Admin/MarkdownSetting/LineBreakForm.jsx
> +const LineBreakForm = (props) => {
default を使った export で起きる typo を防げると思うので、named export を用いた方が良さそうです。

2021-02-09 05:53 UTC, yusuketk commented on src/client/js/components/Admin/MarkdownSetting/PresentationForm.jsx
> +  }, [data?.pageBreakCustomSeparator]);
今は代替案が思いつかないので保留でお願いします

2021-02-09 05:53 UTC, yusuketk commented on src/client/js/components/Admin/MarkdownSetting/LineBreakForm.jsx
> +const LineBreakForm = (props) => {
修正しました

2021-02-09 05:53 UTC, yusuketk commented on src/client/js/components/Admin/MarkdownSetting/LineBreakForm.jsx
> +            name="isEnabledLinebreaks"
修正しました

2021-02-09 05:55 UTC, yusuketk commented on src/client/js/components/Admin/MarkdownSetting/LineBreakForm.jsx
> +  });
修正しましたが、XssFormのみ useForm を 子コンポーネントの WhiteListInput に引き継いでるので元のままです

2021-02-09 06:03 UTC, itizawa commented on src/client/js/components/Admin/MarkdownSetting/LineBreakForm.jsx
> +  const submitHandler = async(formValues) => {
```
import { SubmitHandler} from 'react-hook-form';
const submitHandler: SubmitHandler<FormValues> = async(formValues:FormValues) => {
```
で型をつけられるらしいです。

参考：https://react-hook-form.com/jp/ts#SubmitHandler

2021-02-09 06:59 UTC, yusuketk commented on src/client/js/components/Admin/MarkdownSetting/LineBreakForm.jsx
> +  const submitHandler = async(formValues) => {
ts化してファイル移動しました

2021-02-09 06:59 UTC, merged