Imprv/gw4933 install bolt and use customed reciever
weseek/growi pull request #3357
Opened 2021-01-26 06:40 UTC by kaoritokashiki

2021-01-26 07:26 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-bot.js
> +      await client.chat.postMessage('hogehoge');
宣言した ReceiverClass のインスタンス(receiver)を、BoltのAppインスタンスのreceiverに指定しました。

2021-01-26 07:35 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-bot.js
> +    })();
一旦port8080を立ち上げてみようかと思いましたが、これではserver上でエラーが発生してしますので、引き続き原因追及していこうと思います。
```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:704:16)
    at Object.exports.send (/workspace/growi/node_modules/node-dev/lib/ipc.js:14:23)
    at process.<anonymous> (/workspace/growi/node_modules/node-dev/lib/wrap.js:45:7)
    at process.emit (events.js:326:22)
    at process._fatalException (internal/process/execution.js:156:25)
07:30:26.180Z ERROR growi:
  Uncaught Exception:  Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
      at process.target.send (internal/child_process.js:704:16)
      at Object.exports.send (/workspace/growi/node_modules/node-dev/lib/ipc.js:14:23)
      at process.<anonymous> (/workspace/growi/node_modules/node-dev/lib/wrap.js:45:7)
      at process.emit (events.js:326:22)
      at process._fatalException (internal/process/execution.js:156:25) {
    code: 'ERR_IPC_CHANNEL_CLOSED'
  }
```

2021-01-26 07:47 UTC, kaoritokashiki commented
このPRでは、環境変数の宣言はコミットしていません。
武井さんが先日おっしゃっていたように、一旦app.startで別portを立ち上げることができるか確認する予定です。

2021-01-26 07:57 UTC, yuki-takei requested changes

2021-01-26 07:57 UTC, yuki-takei commented on src/server/routes/apiv3/slack-bot.js
> +const { App } = require('@slack/bolt');
App のインスタンスは BoltService を新たに作ってそちらで保持すべき

2021-01-26 07:57 UTC, yuki-takei commented on src/server/routes/apiv3/slack-bot.js
> +        this.server = createServer(this.app);
この辺がそのままだとこの PR でどこまでを許容して良いのかわからん…

2021-01-26 07:57 UTC, yuki-takei commented on src/server/routes/apiv3/slack-bot.js
> +            });
この辺がそのままだとこの PR でどこまでを許容して良いのかわからん…

2021-01-28 09:07 UTC, kaoritokashiki commented on src/server/service/bolt-reciever.js
> +    await this.bolt.processEvent(event);
現状、このthis.boltが`undefined`であることによって
` <rejected> TypeError: Cannot read property 'processEvent' of undefined`
上記のエラーがサーバー上で発生しています。

公式のdocsでは `init` メソッドが実行されることによってthis.boltにboltのインスタンスが代入されるという認識でいますが、これは、routes配下で実行で認識当たっていますでしょうか?

2021-01-28 09:34 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-bot.js
> +            });
削除しました

2021-01-28 09:34 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-bot.js
> +        this.server = createServer(this.app);
削除しました

2021-01-28 09:35 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-bot.js
> +const { App } = require('@slack/bolt');
servicesディレクトリの配下にBoltService, BoltRecieverServiceの二つのファイルを作成しました。

2021-01-28 12:02 UTC, yuki-takei requested changes

2021-01-28 12:02 UTC, yuki-takei commented on src/server/service/bolt-reciever.js
> +class BoltRecieverService extends EventEmitter {
Receiver の実装はグローバルに扱えるようにする必要はないので、サービス化はいらない。従って BoltService と BoltReceiverService を、別のファイルに分ける必要はない気がする。それのせいで混乱しているのでは。
クラスを分けるかどうかはたぶん好み。

2021-02-02 06:17 UTC, yusuketk commented on src/server/service/bolt.js
> +      token: process.env.SLACK_BOT_TOKEN,
token の設定周りは[GW-5083](https://youtrack.weseek.co.jp/issue/GW-5083) で着手

2021-02-02 07:18 UTC, yuki-takei requested changes

2021-02-02 07:18 UTC, yuki-takei commented on src/server/service/bolt.js
> +  }
一旦のマイルストーンとしてはOK、やりたいことはできていると思う。

## 後続の改修案
この requestHandler は、実体としては middleware function である。分解してサービス層と router に分けるのが望ましい。

- 34行目の res.send は間違いなく router の責務
- 10行目からの、body, ack といった構造のイベントオブジェクトを作るのは service の責務
- ack の中でエラーが起こった際の res.send は router の責務

2021-02-02 07:28 UTC, merged