Feat/get contributors with gc api #4572
weseek/growi pull request #3359
Opened 2021-01-26 08:59 UTC by ryohi15

2021-01-26 09:03 UTC, TatsuyaIse commented on src/server/routes/apiv3/growi-cloud.js
> +  router.get('/growi-cloud', async(res) => {
ここのパスは `staff-credit` になるべきではないかな
今の設計だと `this.props.appContainer.apiv3Get('/growi-cloud/growi-cloud')` じゃないとこのルートには来ない

2021-01-28 01:49 UTC, Yohei-Shiina commented on src/server/routes/apiv3/growi-cloud.js
> +    const growiCloudUrlBase = await crowi.configManager.getConfig('crowi', 'app:growiCloudUri');
Url じゃなくて Uri じゃない？取得してるものに合わせるべき

あとBase はいらないと思う。

2021-01-28 01:51 UTC, Yohei-Shiina commented on src/server/routes/apiv3/growi-cloud.js
> +    const gcRes = await axios.get(url.toString());
gcRes という名前わかりづらい

2021-01-28 01:53 UTC, Yohei-Shiina commented on src/server/routes/apiv3/growi-cloud.js
> +    const growiCloudContributors = gcRes.data;
res.data をわざわざ変数に取らなくてもそのまま渡してあげればよさそう

2021-01-28 04:26 UTC, Yohei-Shiina commented on src/client/js/components/StaffCredit/StaffCredit.jsx
> +      this.setState({ gcContributors: res.data });
json で返されてるから JSON.parse() でパースする必要があるかな。

2021-01-28 04:35 UTC, ryohi15 commented
問題点
- state に gcContributors （初期値：｛｝）を用意して
- componentDidMount で api 叩いて返り値を state にセットしているんですけど、
- コンポーネントの mount 時に state の初期値を参照しちゃってエラーはかれて Staffcredit コンポーネントを表示することができないでいます。

悩んでるところ
- 問題を解決できるベターなアイデアが思いつかないとこです、、、

2021-01-28 05:46 UTC, ryohi15 commented
上記の問題解決しました。

2021-01-28 11:51 UTC, yuki-takei requested changes

2021-01-28 11:51 UTC, yuki-takei commented on src/client/js/components/StaffCredit/StaffCredit.jsx
> +    });
## 現状
- GROWI Contributors は `./Contributor.js` からオフラインで取得
- GROWI.cloud Contributors は、GROWI の API を経て取得

## 改善後
- マージが完了している Contributors を、GROWI の API を経て取得

2021-01-28 11:51 UTC, yuki-takei commented on src/server/routes/apiv3/growi-cloud.js
> +      const gcContributorsRes = await axios.get(url.toString());
この API にアクセスがある度に axios.get するのではなく、一定期間キャッシュするように変更してください。

2021-01-28 11:51 UTC, yuki-takei commented on src/server/routes/apiv3/index.js
> +  router.use('/growi-cloud', require('./growi-cloud')(crowi));
endpoint は `/staffs` に変更

2021-01-28 11:51 UTC, yuki-takei commented on src/server/routes/apiv3/growi-cloud.js
> +  router.get('/staff-credit', async(req, res) => {
- エンドポイントは `/staffs` になるように変更(なので、このファイルでは `/` でよい)
- GROWI Contributors と GROWI.cloud Contributors をマージしたあとのデータを返す

2021-02-08 07:15 UTC, yuki-takei requested changes

2021-02-08 07:15 UTC, yuki-takei commented on src/server/routes/apiv3/staffs.js
> +const contributors = require('../../../client/js/components/StaffCredit/Contributor');
`/src/client` の中身を require するのはいけてないので移動させて。`/resources` あたりに。

2021-02-08 07:15 UTC, yuki-takei commented on src/server/routes/apiv3/staffs.js
> +        return res.apiv3Err(err, 500);
エラー発生時は logger.warn を吐いて、レスポンスとしては最低限 gcContributors が入らない contributors を返す。

2021-02-08 07:15 UTC, yuki-takei commented on src/server/routes/apiv3/staffs.js
> +        expiredAt = addMonths(now, 1);
1ヶ月はやりすぎ。1時間とかでよい。

2021-02-08 07:15 UTC, yuki-takei commented on src/server/routes/apiv3/staffs.js
> +        if (contributors[1].sectionName !== 'GROWI-cloud') {
ここの if の判定文がいけてない。

gcContributors とマージ後のオブジェクトは分けてキャッシュすればいいよね。splice とかやってるところもすっきりしそう。

2021-02-08 07:15 UTC, yuki-takei commented on src/server/routes/apiv3/staffs.js
> +    }
ここの早期リターンあまり意味ないのでいらない。url の null チェックは 21 行目の判定に混ぜ込めば良い。

2021-02-08 08:17 UTC, ryohi15 commented on src/server/routes/apiv3/staffs.js
> +const contributors = require('../../../client/js/components/StaffCredit/Contributor');
承知です。

2021-02-08 08:18 UTC, ryohi15 commented on src/server/routes/apiv3/staffs.js
> +        expiredAt = addMonths(now, 1);
1時間承知です。

2021-02-09 07:44 UTC, yuki-takei requested changes

2021-02-09 07:44 UTC, yuki-takei commented on src/client/js/components/StaffCredit/StaffCredit.jsx
> +      gcContributors: null,
gcContributors って、名前おかしいんじゃない？サーバーから受け取るのは gc とか本体とか関係なく contributors だよね？

2021-02-09 07:47 UTC, yuki-takei commented
master へのマージは望ましくないので、feature ブランチを作ってください。

2021-02-09 08:04 UTC, ryohi15 commented on src/client/js/components/StaffCredit/StaffCredit.jsx
> +      gcContributors: null,
あ、確かに、、、、そうでしたぁ

2021-02-09 08:14 UTC, merged