Imprv/gw5111 label buttons of language settings
weseek/growi pull request #3403
Opened 2021-02-08 06:44 UTC by kaoritokashiki

2021-02-08 06:47 UTC, kaoritokashiki commented on src/client/js/components/Admin/App/AppSetting.tsx
> -                  <label className="custom-control-label" htmlFor={`radioLang${lang}`}>{t('meta.display_name')}</label>
`meta.display_name`は他のところでも使用されていたので、translation.json fileからは消していません。

2021-02-08 06:48 UTC, kaoritokashiki commented on public/static/locales/zh_CN/admin.json
> +    "zh_CN": "中文",
翻訳機を使用しました。

2021-02-08 09:50 UTC, yuki-takei requested changes

2021-02-08 09:50 UTC, yuki-takei commented on src/client/js/components/Admin/App/AppSetting.tsx
> +                  <label className="custom-control-label" htmlFor={`radioLang${lang}`}>{t(`admin:app_setting.${lang}`)}</label>
InstallerForm を参考に、 allLanguages を走査して、ラベル名は `meta.display_name` で得てください。

2021-02-09 07:52 UTC, kaoritokashiki commented
## 途中経過
### 問題点
-  設定している言語以外の言語が正常に表示されない
<img width="664" alt="Screen Shot 2021-02-09 at 16 49 36" src="https://user-images.githubusercontent.com/59536731/107331909-d56b2500-6af6-11eb-9136-ae7c7786f9f7.png">

2021-02-09 07:53 UTC, kaoritokashiki commented on public/static/locales/zh_CN/admin.json
> +    "zh_CN": "中文",
こちらのtranslationの記述は後ほど消す予定です。

2021-02-09 08:13 UTC, kaoritokashiki commented
![Screen Shot 2021-02-09 at 17 13 15](https://user-images.githubusercontent.com/59536731/107334499-24668980-6afa-11eb-82fe-982826856aad.png)

2021-02-09 09:23 UTC, kaoritokashiki commented on src/client/js/components/Admin/App/AppSetting.tsx
> +class AppSetting extends React.Component<Props, MyState> {
これは、tsエラーを解消するために宣言しました。

2021-02-09 09:26 UTC, kaoritokashiki commented on src/client/js/components/Admin/App/AppSetting.tsx
> +      i18n.loadLanguages(nextI18NextConfig.allLanguages);
translationするための`i18n.loadLanguages`は、AppSetting.tsxで宣言してます。

2021-02-09 09:29 UTC, itizawa commented on src/client/js/components/Admin/App/AppSetting.tsx
> +class AppSetting extends React.Component<Props, MyState> {
MyState の名前が微妙かも
今回 Props が一つなので `React.Component<Props, { isMounted: boolean }>` でも良さそうですね

2021-02-09 09:32 UTC, itizawa commented on src/client/js/components/Admin/App/AppSetting.tsx
> +    this.renderRadioButtonsForDefaultLanguage = this.renderRadioButtonsForDefaultLanguage.bind(this);
bind って必要なんでしたっけ

2021-02-09 11:06 UTC, kaoritokashiki commented on src/client/js/components/Admin/App/AppSetting.tsx
> +class AppSetting extends React.Component<Props, MyState> {
なるほどです。修正しました。

2021-02-09 13:26 UTC, merged

2021-02-09 13:28 UTC, kaoritokashiki commented on src/client/js/components/Admin/App/AppSetting.tsx
> +    this.renderRadioButtonsForDefaultLanguage = this.renderRadioButtonsForDefaultLanguage.bind(this);
dev5ブランチからこのブランチをマージした際に、クラスから関数コンポーネント変更していたため、そもそもbindの必要はなくなりました。

2021-02-09 13:31 UTC, kaoritokashiki commented on src/client/js/components/Admin/App/AppSetting.tsx
> +class AppSetting extends React.Component<Props, MyState> {
最初Domがmountされていないので、ラジオボタンのテキストが正常に表示されていないのかと思っていました。
しかし原因は`i18n.loadLanguages(config.allLanguages);`この一文の不足によるものでありisMountedかどうかで表示を左右する必要はないと考えたため削除しました。