Fix/duplicate and rename alert
weseek/growi pull request #3404
Opened 2021-02-08 12:06 UTC by zahmis

2021-02-08 16:44 UTC, zahmis commented on resource/locales/ja_JP/translation.json
>        "version": "これは現在の版ではありません。",
表現を統一しています。

2021-02-08 16:44 UTC, zahmis commented on resource/locales/en_US/translation.json
>        "version": "This is not the current version.",
translation.json で <code>%s</code> を埋め込むと、ここで脆弱性を晒すとの指摘を受けたので、
jsx に元の path を持たせることにしました。

2021-02-09 07:20 UTC, yuki-takei requested changes

2021-02-09 07:20 UTC, yuki-takei commented on resource/locales/en_US/translation.json
>        "version": "This is not the current version.",
要望1: 表現をあまり変えたくない

「移動しました。移動元>>」はださい。

2021-02-09 07:20 UTC, yuki-takei commented on src/client/js/components/Page/DuplicatedAlert.jsx
> +  pageContainer: PropTypes.instanceOf(PageContainer).isRequired,
要望2: PageContainer に依存させたくない

2021-02-09 07:20 UTC, yuki-takei commented on src/server/views/widget/page_content.html
> +  data-page-path-before-redirected="{% if req.query %}{{req.query.redirectFrom}}{% endif %}"
要望(というか意見)3: swig で `data-*` attribute に書き出すのもあまりいい手だと思えない。

req.query が元のデータなのであれば、ユーザーはXSS可能な文字列を入れ込むことができる。
DuplicatedAlert.jsx で直接 req.query から値を取っても、一度 swig を介しても、出力時に対策が必要なのはかわらない。

2021-02-09 09:40 UTC, zahmis commented on resource/locales/en_US/translation.json
>        "version": "This is not the current version.",
戻します

2021-02-10 08:27 UTC, merged