Feat/4573 show staff credit
weseek/growi pull request #3405
Opened 2021-02-09 01:01 UTC by kntowd

2021-02-09 01:25 UTC, kntowd commented
```
yarn server 
```

で起動をしたときは、cloud以外のメンバーのスタッフクレジットが流れるようになり、

```
GROWI_CLOUD_URI=https://growi.cloud yarn server
```

で起動をしたときは、cloudメンバーも含めたスタッフクレジットが流れるようになった。

2021-02-09 02:55 UTC, Yohei-Shiina commented on src/client/js/components/Hotkeys/Subscribers/ShowStaffCredit.jsx
> +    return <></>;
これは空のブロックが返る？

2021-02-09 02:55 UTC, Yohei-Shiina commented on src/client/js/components/Hotkeys/Subscribers/ShowStaffCredit.jsx
> +  // do not render staffCredit if first render
これがあるのとないので挙動にどんな差が出ますか？

2021-02-09 02:58 UTC, kntowd commented on src/client/js/components/Hotkeys/Subscribers/ShowStaffCredit.jsx
> +  // do not render staffCredit if first render
これがないと、スタッフクレジットの表示が途中で止まってしまいます

2021-02-09 02:58 UTC, kntowd commented on src/client/js/components/Hotkeys/Subscribers/ShowStaffCredit.jsx
> +    return <></>;
そうです！

2021-02-09 03:00 UTC, Yohei-Shiina commented on src/client/js/components/Hotkeys/Subscribers/ShowStaffCredit.jsx
> +    return <></>;
空文字ではだめ？

2021-02-11 02:03 UTC, kntowd commented on src/server/routes/apiv3/staffs.js
> +    if (growiCloudUri === null) {
サーバのコンソールでのエラー内容一部抜粋
```
01:59:47.835Z ERROR growi:
  Unhandled Rejection: Promise: Promise {
    <rejected> TypeError [ERR_INVALID_URL]: Invalid URL: null
        at onParseError (internal/url.js:258:9)
        at new URL (internal/url.js:334:5)
        at new URL (internal/url.js:331:22)
        at /workspace/growi/src/server/routes/apiv3/staffs.js:28:19
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at runNextTicks (internal/process/task_queues.js:62:3)
        at processImmediate (internal/timers.js:434:9) {
      input: 'null',
      code: 'ERR_INVALID_URL'
    }
```

2021-02-11 13:42 UTC, yuki-takei requested changes

2021-02-11 13:42 UTC, yuki-takei commented on src/client/js/components/Hotkeys/Subscribers/ShowStaffCredit.jsx
> +  }, [props.appContainer]);
このファイルはホットキーの定義と「どのコンポーネントをレンダリングするか」のマッピングのみを行うのが責務なので、API との通信などは書いてはいけない。

src/client/js/components/StaffCredit/StaffCredit.jsx

側に実装してください。

2021-02-11 13:42 UTC, yuki-takei commented on src/server/routes/apiv3/staffs.js
> +    if (growiCloudUri === null) {
growiCloudUri が null の場合は、そもそもこの route がセットされないようにするのが正しい。
ただこのタスクのスコープではないはずなので、元に戻して後続タスクにしてください。

2021-02-12 01:51 UTC, kntowd commented on src/server/routes/apiv3/staffs.js
> +    if (growiCloudUri === null) {
元に戻して後続に作りました。
GW-5164 GROWI_CLOUD_URIがnullのときcontributorsを取得するapiを実行しない
https://youtrack.weseek.co.jp/issue/GW-5164

2021-02-12 01:51 UTC, kntowd commented on src/client/js/components/Hotkeys/Subscribers/ShowStaffCredit.jsx
> +  }, [props.appContainer]);
修正しました

2021-02-12 06:44 UTC, yuki-takei approved these changes

2021-02-12 06:44 UTC, yuki-takei commented on src/client/js/components/StaffCredit/StaffCredit.jsx
> +    const contributors = res.data.contributorsCache;
`contributorsCache` という名前がいけてないなあ。キャッシュしてるデータなのかどうかはクライアントには関係のない話だ。
バックエンド改修はこのタスクのスコープではないと思うので、他のタスクに混ぜ込んでここのキーは変更してください。

2021-02-12 06:45 UTC, merged