Feat/show search result on slack only me
weseek/growi pull request #3411
Opened 2021-02-10 03:19 UTC by zahmis

2021-02-10 08:35 UTC, yuki-takei requested changes

2021-02-10 08:35 UTC, yuki-takei commented on src/server/service/bolt.js
> +    const userId = process.env.SLACK_USER_ID;
環境変数の取得は ConfigManager を通す。

- そもそも49-50行目の token, signeingSecret に関して変更する必要がある
- 逆に channelId, userId は環境変数で入れるものではないような
    - channelId はボットのインストール先 かつ コマンドが叩かれた場所では？
    - userId はコマンドを叩いたユーザーのIDでは？

2021-02-12 09:58 UTC, zahmis commented on src/server/service/bolt.js
> +    const userId = process.env.SLACK_USER_ID;
承知しました。

- channelId と userId は command に含まれていたのでそちらを使用します。

2021-02-12 10:01 UTC, yuki-takei requested changes

2021-02-12 10:01 UTC, yuki-takei commented on src/server/service/config-loader.js
> +    key:     'slack:signingSecret',
`slackbot:signingSecret` にしよう。

2021-02-12 10:01 UTC, yuki-takei commented on src/server/service/config-loader.js
> +    key:     'slack:botToken',
`slackbot:token` にしよう。

2021-02-12 10:08 UTC, merged