give order to contributors
weseek/growi pull request #3415
Opened 2021-02-12 03:59 UTC by ryohi15

2021-02-12 07:51 UTC, yuki-takei requested changes

2021-02-12 07:51 UTC, yuki-takei commented on resource/Contributor.js
> +    order: 20,
100

2021-02-12 07:51 UTC, yuki-takei commented on resource/Contributor.js
> +    order: 30,
200

2021-02-12 07:51 UTC, yuki-takei commented on src/server/routes/apiv3/staffs.js
> +      };
- 冗長。もっと短く書ける。
- module.exports の外に function として切り出して

2021-02-12 07:51 UTC, yuki-takei commented on src/server/routes/apiv3/staffs.js
> +          gcContributors.order = 2;
`gcContributorsRes.data` には、GROWI.cloud 側で order をセットしておく想定なので、ここではセットしない

2021-02-12 07:54 UTC, ryohi15 commented on src/server/routes/apiv3/staffs.js
> +      };
> 冗長。もっと短く書ける。

wow 頑張ります！！

2021-02-15 04:55 UTC, ryohi15 commented on src/server/routes/apiv3/staffs.js
> +          gcContributors.order = 2;
> GROWI.cloud 側で order をセットしておく想定なので、ここではセットしない

承知しました。
別タスクで GROWI.cloud 側でセットする実装をしました。
https://youtrack.weseek.co.jp/issue/GW-5185

2021-02-15 09:48 UTC, merged