Imprv/gw 5116 page duplicate modal
weseek/growi pull request #3420
Opened 2021-02-14 07:45 UTC by kaoritokashiki

2021-02-15 06:43 UTC, kaoritokashiki commented on src/components/PageManagement/PageDuplicateModal.tsx
> +              )}
ここの部分をコメントアウトしたことによって、必要になるメソッド、ステートたちを追加しました。

2021-02-15 06:55 UTC, kaoritokashiki commented on src/components/PageManagement/PageDuplicateModal.tsx
> +      // window.location.href = encodeURI(`${pageNameInput}?duplicated=${path}`);
こちらは後続タスク
「GW-5117 【PageDuplicateModal】isDuplicateRecursivelyを使えるようにする」
で着手予定です。

2021-02-15 07:42 UTC, yuki-takei requested changes

2021-02-15 07:42 UTC, yuki-takei commented on src/client/js/components/PagePathAutoComplete.jsx
> +  const emptyLabel = (searchError !== null)
厳密な比較演算子は使う必要がある？
あるならコメントを追加、ないならガイドライン通りに。

2021-02-15 11:44 UTC, kaoritokashiki commented on src/client/js/components/PagePathAutoComplete.jsx
> +  const emptyLabel = (searchError !== null)
厳密な比較演算子に気づかなかったですね...。
SearchFormからコピペで取ってきたので、SearchFormの方も
```
const emptyLabel = (searchError != null)
```
に書き換えました。

同様にPageRenameModalの方も変更しときました。

2021-02-15 16:40 UTC, kaoritokashiki commented on src/components/PageManagement/PageRenameModal.tsx
>                onSearchError={setSearchError}
PageDuplicateModal を触ったところ`<SearchTypeahead />` ではなく、`<PagePathAutoComplete />`を使用する方が適切であると気付いたのでtodoコメントを残しておきました。
→ GW-5194 【PageRenameModal】SearchTypeahead を PagePathAutoCompleteに変更

2021-02-15 16:40 UTC, kaoritokashiki commented on src/components/PageManagement/PageRenameModal.tsx
> +            {/* TODO: using PagePathAutoComplete not SearchTypeahead by GW 5194 */}
PageDuplicateModal を触ったところ`<SearchTypeahead />` ではなく、`<PagePathAutoComplete />`を使用する方が適切であると気付いたのでtodoコメントを残しておきました。
→ GW-5194 【PageRenameModal】SearchTypeahead を PagePathAutoCompleteに変更

2021-02-15 16:47 UTC, kaoritokashiki commented on src/client/js/components/PagePathAutoComplete.jsx
> +  };
### 参考
- https://stackoverflow.com/questions/56888888/how-to-hide-empty-label-in-react-bootstrap-typeahead
- https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md

2021-02-15 16:48 UTC, kaoritokashiki commented on src/client/js/components/SearchForm.tsx
> +  const emptyLabel = (searchError != null)
ここではemptyLabelがnullを返しているわけではないので、renderMenuを使うことはせずにそのまま`emptyLabel `を使用しています。
ただ、厳密な比較演算子はやめました。

2021-02-15 16:51 UTC, kaoritokashiki commented on src/client/js/components/PagePathAutoComplete.jsx
> +      renderMenu={renderMenu}
emptyLabelがnullを返す仕様は推奨されておらず、代わりに`renderMenu`を使いなさい
とのエラーが出たため、renderMenuを使用することにしました。

2021-02-15 16:59 UTC, kaoritokashiki commented on src/client/js/components/PagePathAutoComplete.jsx
> +      renderMenu={renderMenu}
pathのresultに何もない場合nullを返す仕様に変更したので、labelMenuは表示されないようになりました。

<img width="829" alt="Screen Shot 2021-02-16 at 1 56 42" src="https://user-images.githubusercontent.com/59536731/107974706-53996100-6ffa-11eb-998b-30fc67c26716.png">

2021-02-16 04:15 UTC, yuki-takei approved these changes

2021-03-12 09:34 UTC, merged