Support/3506 3511 implement migrate mongo by ts node
weseek/growi pull request #3423
Opened 2021-02-15 03:38 UTC by itizawa

2021-02-15 03:39 UTC, itizawa commented on package.json
> +    "migrate:up": "ts-node --project tsconfig.server.json -r ts-node/register -r tsconfig-paths/register src/server/util/mongoose-utils.ts node_modules/.bin/migrate-mongo up -f config/migrate.ts",
ts-node/register を使うために ts-node で migrate up を実行

2021-02-15 03:41 UTC, itizawa commented on package.json
> +    "migrate:up": "ts-node --project tsconfig.server.json -r ts-node/register -r tsconfig-paths/register src/server/util/mongoose-utils.ts node_modules/.bin/migrate-mongo up -f config/migrate.ts",
isolatedModules を false にして実行すると動くは動くが何も変化がない

```
node ➜ /workspace/growi (support/3809-5168-display-revision-list ✗) $ yarn migrate
yarn run v1.22.5
$ npm run migrate:up
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1613359139902-0.13357420002467202/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> growi@4.2.8-RC migrate:up /workspace/growi
> ts-node --project tsconfig.server.json -r ts-node/register -r tsconfig-paths/register src/server/util/mongoose-utils.ts node_modules/.bin/migrate-mongo up -f config/migrate.ts

Done in 4.20s.
```

2021-02-18 07:50 UTC, yuki-takei requested changes

2021-02-18 07:50 UTC, yuki-takei commented on src/migrations/20200915035234-rename-s3-config.ts
> +};
migration file は原理上 js でも実行できるはず。
理想は js, ts 両方動かせることだが、とりあえず後続タスクで js -> ts 変換するコストを削減したい。

2021-02-19 08:39 UTC, merged