Feat/add try catch in growi search
weseek/growi pull request #3425
Opened 2021-02-15 04:17 UTC by zahmis

2021-02-15 05:17 UTC, zahmis commented on src/server/service/bolt.js
>      // for verification request URL on Event Subscriptions
slack app 上にて Event Subscription を変更した際に、
`res.send('req.body')` がないと、変更されませんでした。
しかし、それでは slack で command を打ったときに以下のエラーが発生します。
```
Unhandled Rejection: Promise: Promise {
    <rejected> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
        at ServerResponse.setHeader (_http_outgoing.js:543:11)
```

この回避策として、以下のように実装しました。

Event Subscription が再発行されると challenge と type が生成されます。
通常のコマンドでは生成されません。
なのでこの有無によって `res.send(req.body)`  を実行するかを決めています。

- event subscription 変更時
```
{
  token: 'xkS7MQPN2Yw...
  challenge: 'NGz1GGMsabcuZ6dEGBzX52mZgOLKreIZtOu...
  type: 'url_verification'
}
```

- 通常時 ( slack で コマンドを叩いたとき )
```
 {
  token: 'xkS7M..
  team_id: 'T4V7GA7CM',
  team_domain: 'wsgrowi',
  channel_id: 'C01J..
  channel_name: 'growi_bot',
  user_id: 'U0150..
  user_name: 'shizuma-y',
  command: '/growi',
  text: 'search hoge',
  api_app_id: 'A01KC..
  is_enterprise_install: 'false',
  response_url: 'https://hooks.slack.com/commands/T4V7GA7CM/1748072489957/TmH0DeWcIXKOQNw...
  
```

2021-02-15 05:57 UTC, yuki-takei requested changes

2021-02-15 05:57 UTC, yuki-takei commented on src/server/service/bolt.js
> +    }
ここの if ブロックの位置を早期リターンに変えてください。

2021-02-15 05:57 UTC, yuki-takei commented on src/server/service/bolt.js
> +      if (firstArg === 'search' && secondArg != null) {
`this.bolt.command('/growi', async({ command, ack }) => {` から始まるブロックが長すぎるのでリファクタして。

- firstArg が search だったら別メソッドに処理を委譲
    - その中で secondArg の有無のチェックや postEphemeral を実行

2021-02-15 07:59 UTC, zahmis commented on src/server/service/bolt.js
第一引数が 入力されていない場合は、新たに関数を作らずに直書きしています。

2021-02-16 04:07 UTC, yuki-takei requested changes

2021-02-16 04:07 UTC, yuki-takei commented on src/server/service/bolt.js
> +          },
generateBlock を切り出し

2021-02-16 04:07 UTC, yuki-takei commented on src/server/service/bolt.js
> +  notCommand(command) {
可変 args を取る

2021-02-16 07:53 UTC, zahmis commented on src/server/service/bolt.js
> +
inputSlack を渡しています。
理由は、slack上で入力された文字が space 区切りで配列となっており、
[keyword]の有無の判別に最適だったからです。

2021-02-16 07:53 UTC, zahmis commented on src/server/service/bolt.js
> +  notCommand(command) {
可変 args を使わずに 生の command.text をそのまま使おうと思います。

2021-02-16 08:25 UTC, merged