Feat/impl design of comparing section in revision modal
weseek/growi pull request #3441
Opened 2021-02-17 18:35 UTC by zahmis

2021-02-18 07:58 UTC, yuki-takei commented
- before のスクリーンショットがない

2021-02-18 07:58 UTC, yuki-takei requested changes

2021-02-18 07:58 UTC, yuki-takei commented on src/client/styles/scss/_page-history.scss
> +  }
色関係はテーマ対応させないといけないと思う。

2021-02-18 07:58 UTC, yuki-takei commented on src/client/js/components/RevisionComparer/RevisionComparer.jsx
> +        <CopyToClipboard text={pagePathUrl()} />
これの意味がわからない

2021-02-18 16:04 UTC, zahmis commented on src/client/js/components/RevisionComparer/RevisionComparer.jsx
> +        <CopyToClipboard text={pagePathUrl()} />
Dropdown が必要でした。
restore します。

2021-02-19 04:42 UTC, zahmis commented on src/client/js/components/RevisionComparer/RevisionComparer.jsx
> +        <CopyToClipboard text={pagePathUrl()} />
xd からは Dropdown が消されていますが、必要とのことです。

2021-02-19 04:46 UTC, zahmis commented on src/client/styles/scss/_page-history.scss
> +  }
apply-colors に移植させます。

2021-02-19 08:42 UTC, yuki-takei requested changes

2021-02-19 08:42 UTC, yuki-takei commented on src/client/styles/scss/theme/_apply-colors.scss
> +}
ごめん、各テーマ毎に変えなくていいのであれば元に戻してください。

2021-02-19 12:01 UTC, zahmis commented on src/client/styles/scss/theme/_apply-colors.scss
> +}
restore しました。

2021-02-20 12:09 UTC, yuki-takei requested changes

2021-02-20 12:09 UTC, yuki-takei commented on src/client/js/components/RevisionComparer/RevisionComparer.jsx
> -        </div>
この機能を削除するにあたって不要になる translation や container のメソッドがあれば消してください。

2021-02-20 14:16 UTC, zahmis commented on src/client/js/components/RevisionComparer/RevisionComparer.jsx
> -        </div>
すみません。
見落としていました。
不要なコードを削除します。

2021-02-20 14:16 UTC, zahmis commented on src/client/js/services/RevisionComparerContainer.js
> -    this.toggleCompareWithLatest = this.toggleCompareWithLatest.bind(this);
不要になったコードです

2021-02-20 14:16 UTC, zahmis commented on src/client/js/services/RevisionComparerContainer.js
不要になったコードです。

2021-02-22 05:50 UTC, merged