Feat/error ocation to submit in modal
weseek/growi pull request #3447
Opened 2021-02-20 17:18 UTC by zahmis

2021-02-20 17:20 UTC, zahmis commented on src/server/service/bolt.js
> +    const contentsBody = view.state.values.contents.contents_input.value;
error でも使うので外に出しています。

2021-02-20 17:20 UTC, zahmis commented on src/server/service/bolt.js
> +      if (e instanceof Error) {
path が存在するときに page が作成できないように処理しています。

2021-02-22 05:52 UTC, yuki-takei requested changes

2021-02-22 05:52 UTC, yuki-takei commented on src/server/service/bolt.js
> +      if (e instanceof Error) {
`e instanceof Error` っていう判定は必要なの？不要なら消す。必要ならこの条件に引っかからなかった場合も最低限ログだけは出す。

2021-02-22 09:38 UTC, merged