Imprv/gw5223 showing search results
weseek/growi pull request #3449
Opened 2021-02-21 14:15 UTC by kaoritokashiki

2021-02-22 02:44 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +  async getSearchResultPaths(command, args) {
`searchResults`メソッドの中にある、reultsPathsを取得する部分を別の関数に分けました。

2021-02-22 02:46 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +                  text: 'Share the results.',
テキストが長いと、ボタンの文字が全部表示されず省略されて`...`が表示されるので、`Share the results`だけにしました。

2021-02-22 05:54 UTC, yuki-takei requested changes

2021-02-22 05:54 UTC, yuki-takei commented on src/server/service/bolt.js
> +                  text: 'Share the results.',
i18n
「share」とか「共有」だけで良さそう

2021-02-22 05:54 UTC, yuki-takei commented on src/server/service/bolt.js
> +  async searchResults(command, args) {
メソッド名が微妙

2021-02-23 11:38 UTC, merged

2021-02-23 11:39 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +                  text: 'Share the results.',
「Share」のみにしました

2021-02-23 11:40 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +  async searchResults(command, args) {
「showEphemeralSearchResults」に変更しました。