add command to yarn build alias
weseek/growi pull request #3468
Opened 2021-02-26 03:55 UTC by yusuketk

2021-03-02 09:27 UTC, yuki-takei requested changes

2021-03-02 09:27 UTC, yuki-takei commented on package.json
> +    "prebuild": "yarn clean:app && yarn plugin:def && dotenv -e .env.development yarn resource",
- 位置を `//// The following lines are not maintained` の行より上に移す必要がある
- 当然 production を意識した script である必要がある
    - yarn resource 実行時にも next と同様の挙動を再現したいが、どうしたらいいんだろうね
    - https://github.com/kerimdzhanov/dotenv-flow とか？
        - next では何を使っているんだろう

2021-03-03 05:41 UTC, yusuketk commented on package.json
> +    "prebuild": "yarn clean:app && yarn plugin:def && dotenv -e .env.development yarn resource",
> 位置を //// The following lines are not maintained の行より上に移す必要がある
この文に気付きませんでした。。修正しました

> 当然 production を意識した script である必要がある
> yarn resource 実行時にも next と同様の挙動を再現したいが、どうしたらいいんだろうね
僕が勘違いしてる気がするので確認ですが、build scriptは production 用コマンドでしょうか?(next buildがそうなのでそうなのかなと思いました)
最初はてっきり resource:prod なるscriptを用意するのかと思っていました。

2021-03-03 05:43 UTC, yusuketk commented on package.json
> +    "prebuild": "yarn clean:app && yarn plugin:def && dotenv -e .env.development yarn resource",
見るとこあってるか微妙なんですが、nextでは内部で文字列で判定してるような感じでした
https://github.com/vercel/next.js/blob/canary/packages/next-env/index.ts#L81

2021-03-03 09:06 UTC, yusuketk commented
dotenv-flow-cli を使い、 `plugin:def` scriptと `source` script の実行時に NODE_ENVをもとに .env ファイルをロードするようにしました。

2021-03-03 09:08 UTC, merged