Make it possible to change indent size / インデント幅を変更可能にする
weseek/growi pull request #3473
Opened 2021-02-27 16:26 UTC by tats-u

Closes #3439

- ユーザが自分で変更可能にする
  - [x] ページエディタ
  - [ ] コメントエディタ
- 管理者がデフォルト値を変更可能にする
  - デフォルト値
    - [x] ロジック
    - [ ] 管理画面UIレイアウト完成度 (help wanted)
- 管理者がユーザによる変更を禁止する
  - [x] ロジック
  - [x] UI
  - [ ] stateや設定値の名前がイケている 
- [ ] 初期内容からインデント幅を推測

インデント値は、`editorContainer`と`CodeMirrorEditor`に持たせています。
管理者側の値をエディタに反映させるには、`appContainer.config`を経由させています。

管理者設定のインデント幅のドロップダウンは突貫工事です。

2021-03-01 08:11 UTC, yuki-takei commented
@tats-u 

タスク化までしていただいて大変ありがたいです。所感を書いておきます。

- 管理画面、適当でも構わないです(毎日使うものじゃないし)
- stateや設定値の名前は、もしいけてなかったらこちらでマージ後に改修します！
- 中国語は一旦適当で構わないと思っています
    - インターン生で中国語できる人が入ってくるタイミングがありそうではあるので、その時に見直しを行います
    - 「インデント幅候補の直値回避」はどこのことだろう 🙄 

既存機能改修の場合はデグレが起こるかどうかを慎重に見ますが、完全新規機能なので完璧じゃなくとも master へのマージは可能かと思います。きりがいいと思われたタイミングでメンションいただければレビュー・マージを行いますのでお声かけください。

2021-03-02 16:20 UTC, tats-u commented
@yuki-takei 

> stateや設定値の名前は、もしいけてなかったらこちらでマージ後に改修します！

お願いします。候補は以下の通りです。

- インデント幅→ `indentSize`（現行） or `indentWidth`
- インデント幅強制→`isIndentSizeForced`（現行・API/状態）・`disallowIndentChange`（翻訳用・メソッド用の命名なので却下か）・`isIndentChangeDisallowed`（左の変形）・`isIndentChangeAllowed`（真偽逆にする）など

> 「インデント幅候補の直値回避」はどこのことだろう 🙄

インデント幅候補の`[2, 4]`がソースの何箇所かに直書きになっているので、どこかにまとめて変数で参照したいところです。

> きりがいいと思われたタイミングでメンションいただければレビュー・マージを行いますのでお声かけください。

こちらではひとまずキリがついております。お願いいたします。

2021-03-06 14:34 UTC, yuki-takei requested changes

2021-03-06 14:34 UTC, yuki-takei commented on src/client/js/components/Admin/MarkdownSetting/IndentForm.jsx
> +class IndentForm extends React.Component {
v5.0.x に向けて Next.js 化を進めているのですが、その際 Class component だと移植がちょっとめんどうになってしまいます。そのため、新規コンポーネントは Functional component で実装したいところです。リファクタ可能でしょうか？

2021-03-06 14:34 UTC, yuki-takei commented on src/client/js/components/Admin/MarkdownSetting/IndentForm.jsx
> +import AppContainer from '../../../services/AppContainer';
AppContainer 使ってなさそうなので消してください。

2021-03-06 14:34 UTC, yuki-takei commented on src/client/js/components/PageEditor.jsx
> +    // Detect indent size from contents (only when users are allowed to change it)
`// TODO: https://youtrack.weseek.co.jp/issue/GW-5368` というコメントを追加していただけますでしょうか

2021-03-06 14:34 UTC, yuki-takei commented on src/client/js/components/PageComment/CommentEditor.jsx
> +              <OptionsSelector />
これを入れる場合、レスポンシブ対応についてもう少し考慮が必要ですね。

- エディタ同様のスタイルの適用
- 小さいデバイスでは DropdownMenu の alignment を右に

など。

2021-03-06 14:34 UTC, yuki-takei commented
@itizawa 
AdminMarkDownContainer および EditorContainer での初期値の決め方について意見もらいたい

2021-03-06 14:38 UTC, yuki-takei commented on src/client/js/components/PageComment/CommentEditor.jsx
> +              <OptionsSelector />
![image](https://user-images.githubusercontent.com/1638767/110210433-0ca1db80-7ed5-11eb-980d-4347191e7c60.png)

2021-03-07 07:40 UTC, tats-u commented on src/client/js/components/Admin/MarkdownSetting/IndentForm.jsx
> +import AppContainer from '../../../services/AppContainer';
消しました。

2021-03-07 07:41 UTC, tats-u commented on src/client/js/components/PageEditor.jsx
> +    // Detect indent size from contents (only when users are allowed to change it)
すぐ下に追加いたしました。

2021-03-07 07:41 UTC, tats-u commented on src/client/js/components/Admin/MarkdownSetting/IndentForm.jsx
> +class IndentForm extends React.Component {
書き換えました。

2021-03-07 07:56 UTC, tats-u commented on src/client/js/components/PageComment/CommentEditor.jsx
> +              <OptionsSelector />
エディタ同様、`navigationContainer.state.isDeviceSmallerThanMd` が `false` の時のみ表示させない設定だと不十分です。
ブラウザの横幅が751～960pxの時だと、`OptionsSelector`自体が右側にはみ出ます。
`OptionsSelector`ははみ出ないが`DropdownMenu`がはみ出る横幅の条件は、およそ961～1080pxです。

> 小さいデバイスでは DropdownMenu の alignment を右に
これをやろうと思うと、`OptionsSelector`に新しいプロパティを追加しなければなりません。

2021-03-08 01:26 UTC, itizawa reviewed
@tats-u 
コメントしました。お手数おかけしますが確認お願いします 🙏

2021-03-08 01:26 UTC, itizawa commented on src/client/js/services/EditorContainer.js
> +      indentSize: this.appContainer.config.adminPreferredIndentSize || 4,
後の Next.js 化時に改修しますが、現在の構成では appContainer.config で良さそうです

2021-03-08 01:26 UTC, itizawa commented on src/client/js/components/Admin/MarkdownSetting/IndentForm.jsx
> +          />
`PagingSizeUncontrolledDropdown`
は pagination を設定するための dropdown なので今回使うのは適切でないと思います

2021-03-08 01:26 UTC, itizawa commented on src/client/js/components/Admin/MarkdownSetting/IndentForm.jsx
> +            checked={isIndentSizeForced}
null が入ってくる場合もあるので念のため `checked={isIndentSizeForced || false}` と指定していただけると助かります

2021-03-11 15:25 UTC, tats-u commented on src/client/js/services/EditorContainer.js
> +      indentSize: this.appContainer.config.adminPreferredIndentSize || 4,
ありがとうございます。
そのままにしておきます。

2021-03-11 15:26 UTC, tats-u commented on src/client/js/components/Admin/MarkdownSetting/IndentForm.jsx
> +          />
`PagingSizeUncontrolledDropdown`ベースで再実装しました。レイアウトもよい感じにしました。

2021-03-11 15:26 UTC, tats-u commented on src/client/js/components/Admin/MarkdownSetting/IndentForm.jsx
> +            checked={isIndentSizeForced}
修正しました。

2021-03-11 15:38 UTC, tats-u commented on src/client/js/components/PageComment/CommentEditor.jsx
> +              <OptionsSelector />
コメントエディタ中でインデント幅を選択できなくても、本文エディタより悪影響は小さいため、表示されないようにしました。
追加する場合は別のPRで行うのがよいかと思います。

2021-03-12 00:44 UTC, itizawa approved these changes

2021-03-12 00:46 UTC, itizawa commented
@yuki-takei
Approve しました

2021-03-16 10:32 UTC, yuki-takei approved these changes

2021-03-16 11:06 UTC, merged

2021-03-16 11:06 UTC, yuki-takei commented
@tats-u Thank you