Support/3506 5242 remove dependency on crowi fron page
weseek/growi pull request #3491
Opened 2021-03-02 06:52 UTC by itizawa

2021-03-03 06:43 UTC, yuki-takei requested changes

2021-03-03 06:43 UTC, yuki-takei commented on src/server/models/new-page.ts
> +import { USER_PUBLIC_FIELDS, IUser } from '~/server/models/new-user';
new-user ってもうあるの？

2021-03-03 06:43 UTC, yuki-takei commented on src/server/models/new-page.ts
> +}
`src/interfaces` は使わないの？後々置き換える？

2021-03-04 10:37 UTC, itizawa commented
https://stackoverflow.com/a/36661990
を参考に type の定義と mongoose の Document は分けました

2021-03-04 10:51 UTC, merged