Imprv/gw5283 show next 10 results
weseek/growi pull request #3500
Opened 2021-03-04 01:08 UTC by kaoritokashiki

2021-03-04 06:48 UTC, yuki-takei requested changes

2021-03-04 06:48 UTC, yuki-takei commented on src/server/service/bolt.js
> +    };
全然だめ。
BoltService はサービス層である。
state, setState はどこの世界のもので何層でやること？

2021-03-04 14:27 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +    };
`server/service`という名前のディレクトリがあって、その下に機能が詰め込まれたファイルたちが存在するのは知っていましたが、
〇〇層に関する知識がなかったです。

> state, setState はどこの世界のもので何層でやること？
クライアントとやりとりする世界?のもので、プレゼンテーション(UI)層でやること

という回答で当たっていますでしょうか?

2021-03-11 05:24 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +    args.unshift(shiftedValue);
Nextボタンで再検索する際に、argsの第一要素に `search` が入っていないとエラーになるので、
再度配列の先頭に追加しました。

2021-03-11 05:35 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +    const keywordsAndDesc = `keyword(s) : "${keywords}" \n ${searchResultsDesc}.`;
`args.unshift(shiftedValue);`
を追加したことによって、`search hoge`が取れてしまうので、
`keywords`に変更しました。

2021-03-11 09:34 UTC, yuki-takei requested changes

2021-03-11 09:34 UTC, yuki-takei commented on src/server/service/bolt.js
> +  }
このメソッドを切り出す意味はなさそうなので、`showNextResults` action の実装の中に入れる。

2021-03-11 09:34 UTC, yuki-takei commented on src/server/service/bolt.js
> +    args.unshift(shiftedValue);
`args.shift()` という破壊的変更を行うからそんな辻褄合わせのようなコードになる。

2021-03-11 09:34 UTC, yuki-takei commented on src/server/service/bolt.js
> +    const keywordsAndDesc = `keyword(s) : "${keywords}" \n ${searchResultsDesc}.`;
🙅

2021-03-11 17:28 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +      this.showEphemeralSearchResults(command, args, newOffset);
メソッドで切り出さずに、showNextResults action の中に入れました。

2021-03-11 17:31 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +
shiftメソッドを使用するのではなく、
第二引数以降の要素をfor文で取得して、keywords用の配列を作成することにしました。

2021-03-11 17:34 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +    const keywordsAndDesc = `keyword(s) : "${keywords}" \n ${searchResultsDesc}.`;
shift, unshiftのやり方は排除しました。

args: `search` `hoge`
keywords: `hoge`
が取得できます。

2021-03-11 18:07 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +  }
修正しました

2021-03-11 18:08 UTC, kaoritokashiki commented on src/server/service/bolt.js
> +    args.unshift(shiftedValue);
なるほど、そこから懐疑的になる必要があったのですね。

2021-03-12 09:13 UTC, yuki-takei requested changes

2021-03-12 09:13 UTC, yuki-takei commented on src/server/service/bolt.js
> +  async getSearchResultPaths(command, args, offset = 0) {
このメソッドの責務は、search した結果の resultPaths を返すこと。

2021-03-12 09:13 UTC, yuki-takei commented on src/server/service/bolt.js
> +
これこそ別メソッドにする。

2021-03-12 09:13 UTC, yuki-takei commented on src/server/service/bolt.js
> +    };
return に余計なものは含めない

2021-03-12 09:13 UTC, yuki-takei commented on src/server/service/bolt.js
> +    } = await this.getSearchResultPaths(command, args, offsetNum);
keywords は args から抽出できるはず。

2021-03-12 09:36 UTC, merged

2021-03-17 02:10 UTC, kaoritokashiki commented
GW-5412 GW5283 の FB修正
後続タスク　でFB修正します