Feat/show seen user info
weseek/growi pull request #3512
Opened 2021-03-06 19:12 UTC by zahmis

2021-03-08 06:40 UTC, itizawa commented on src/components/User/SeenUserInfo.tsx
> +      </Button>
reactstrap の Button は非推奨です

2021-03-08 11:13 UTC, yuki-takei requested changes

2021-03-08 11:13 UTC, yuki-takei commented on src/server/routes/user.js
> +    const userIds = req.query.user_ids.join(',') || null; // TODO: handling
list で入ってくるならわざわざ join する必要はない

2021-03-08 11:13 UTC, yuki-takei commented on src/stores/page.tsx
> +    '/users.list',
キーは array にして、user_ids に指定する中身も含むべき

https://swr.vercel.app/docs/arguments#passing-objects

取得対象は上限15件でフィルタしないといけない。過去の実装でどうなっていたのか、`data-page-ids-of-seen-users` で grep して。

2021-03-08 11:13 UTC, yuki-takei commented on src/components/User/SeenUserInfo.tsx
> +  const countOfSeenUsers:number = (seenUsers == null ? 0 : seenUsers.length);
countOfSeenUsers はトータルで閲覧した人を表示する仕様になっていたはず。過去の実装でどうなっていたのか、`data-page-count-of-seen-users` で grep して。

2021-03-09 07:08 UTC, zahmis commented on src/components/User/SeenUserInfo.tsx
> +  const countOfSeenUsers:number = (seenUsers == null ? 0 : seenUsers.length);
過去の実装を参考にしました.

page_content.html にて以下のように seenUsers を制限していました
```
  data-page-ids-of-seen-users="{{ page.seenUsers|slice(-15)|default([])|reverse|join(',') }}"
  data-page-count-of-seen-users="{{ page.seenUsers.length|default(0) }}"
```

これを元に フロントの txs で 
seenUsers.length は countOfSeenUsersn とし
seenUsers は seenUsers?.slice(-15) で 表しました。

2021-03-09 07:09 UTC, zahmis commented on src/server/routes/user.js
> +    const userIds = req.query.user_ids.join(',') || null; // TODO: handling
承知しました

2021-03-09 07:15 UTC, zahmis commented on src/stores/page.tsx
> +    '/users.list',
「user_ids に指定する中身も含むべき」の意味を currentPage だと思っています.

これは swr は全てのレンダリングで引数を浅く比較するとあったので、
その変更がない場合は、更新しない。だと思っています。

今回、currentPage と比較した結果、
変更がなければ 「currentPage の情報を返す」だと思っています。

2021-03-09 10:41 UTC, yuki-takei requested changes

2021-03-09 10:41 UTC, yuki-takei commented on src/components/User/SeenUserInfo.tsx
> +  const countOfSeenUsers:number = (seenUsers == null ? 0 : seenUsers.length);
seenUsers が null なら、そもそも何もレンダリングする必要はない。(おそらく SWR 的に isValidating 状態)

2021-03-09 10:41 UTC, yuki-takei commented on src/stores/page.tsx
> +export const useSeenUsersSWR = ():responseInterface<User[], Error> => {
- useCurrentPageSeenUsers に名前を変えてください
- 引数で取得する数をとって、クエリに反映させてください

2021-03-09 12:54 UTC, yuki-takei requested changes

2021-03-09 12:54 UTC, yuki-takei commented on src/interfaces/page.ts
> +  seenUsers: User[]
これって `User[]` でいいの？実態を確認している？

2021-03-09 12:58 UTC, yuki-takei requested changes

2021-03-09 13:21 UTC, zahmis commented on src/components/User/SeenUserInfo.tsx
> +            <UserPictureList users={seenUsersLimit} />
これは逆になっていそうです。
<img width="268" alt="スクリーンショット 2021-03-09 22 19 02" src="https://user-images.githubusercontent.com/57100766/110476679-97791500-8125-11eb-944c-97cc89ad4ea5.png">
「○○○○○○○○...」
　←新しい 古い→

2021-03-09 16:38 UTC, merged