Imprv/5308 5088 implement page rename modal
weseek/growi pull request #3517
Opened 2021-03-10 09:48 UTC by itizawa

2021-03-12 09:38 UTC, itizawa commented on src/server/routes/apiv3/pages.js
> +    if (!isCreatablePage(newPagePath)) {
util のを使用

2021-03-12 13:13 UTC, yuki-takei requested changes

2021-03-12 13:13 UTC, yuki-takei commented on src/stores/page.tsx
> +  const key = pagePath != null ? endpoint : null;
key の設計がおかしい。pagePath arg があるときは配列になるはず。

2021-03-15 02:35 UTC, itizawa commented on src/stores/page.tsx
> +    (endpoint, pageId) => apiv3Get(endpoint, { pageId }).then(response => response.data),
pageId を key に含めなければ、違うページID が与えられた場合でも同じものを返してしまう

https://swr.vercel.app/docs/arguments#multiple-arguments

2021-03-15 02:36 UTC, itizawa commented on src/stores/page.tsx
> -      ? endpoint => apiGet(endpoint, { user_ids: currentPage?.seenUsers }).then(response => response.users.slice(limit).reverse())
key に object を渡さず、安定した `seenUsers :Array<string>` を与える

2021-03-15 02:54 UTC, itizawa commented on src/stores/page.tsx
> +    (endpoint, toPath) => apiv3Get(endpoint, { fromPath: pagePath, toPath }).then(response => response.data.existPaths),
key が null の場合 fetcher も実行されない。

https://github.com/weseek/growi/pull/3517/files#diff-08cd093bbdc2d9406c88601e0d4453061305833bcda868dfb4224c7fcdd8e127R179
を見ると、key が null になる状況では store が 空の配列を返しています。

自分がやった方法では key が null なら store は undefined を返す。
表示のコンポーネントの default 値で空の配列を設定するようにしています。
`const { data: subordinatedList = [] } = useSubordinatedList(currentPagePath);`

useHoge からは常に undefined が返ってくる可能性 (fetch 完了前など) があるため、store がよしなに値を返さないほうがいいという理由です。

これに関して useCurrentPageSeenUsersSWR の戦略の方をとった理由があれば教えて欲しいです

2021-03-15 07:50 UTC, yuki-takei requested changes

2021-03-15 07:50 UTC, yuki-takei commented on src/stores/page.tsx
> +    (endpoint, toPath) => apiv3Get(endpoint, { fromPath: pagePath, toPath }).then(response => response.data.existPaths),
この辺のは引数で undefined を許容しない、でいいね

2021-03-15 08:10 UTC, itizawa commented on src/stores/ui.tsx
> +  const { data: descendantsCount } = useDescendantsCount(currentPagePath as string);
https://github.com/weseek/growi/blob/dev/5.0.x/src/components/Navbar/GrowiSubnavButtons.tsx#L14-L16
同様 as を使って currentPagePath の型を `string | undefined` から undefined をなくしていますが、この戦略を使わざること得ないのでしょうか。

currentPagePath が undefined になることはあり得ない前提に限って as での矯正がアリみたいな感じですかね

2021-03-15 08:49 UTC, merged