Imprv/hide next button less than 10
weseek/growi pull request #3525
Opened 2021-03-12 11:28 UTC by zahmis

2021-03-13 14:51 UTC, yuki-takei requested changes

2021-03-13 14:51 UTC, yuki-takei commented on src/server/service/bolt.js
> +  }
これは共通化しなくていいです

2021-03-13 14:51 UTC, yuki-takei commented on src/server/service/bolt.js
> +              this.generateElementsSectionBlock('Share', 'shareSearchResults', `${keywordsAndDesc} \n\n ${urls.join('\n')}`, 'primary'),
share ボタン表示させるロジックが 260 行目とかぶってるのは NG

2021-03-13 14:51 UTC, yuki-takei commented on src/server/service/bolt.js
> +      if (searchResultsNum < 10 || resultsTotal === 10) {
10というマジックナンバーを直接書くのはよくない。
ページサイズを表す static な変数として定義しておく。(同じファイル内でよい)

また、この条件判定式では想定する挙動にはならない。offset とページサイズ、それから resultsTotal の3つを使った比較式で表して。

2021-03-15 06:12 UTC, zahmis reviewed
修正します

2021-03-15 07:56 UTC, yuki-takei requested changes

2021-03-15 07:56 UTC, yuki-takei commented on src/server/service/bolt.js
> +        return await this.client.chat.postEphemeral({
if, else 共にこの行は1回だけ呼ぶ(278行目と重複)

2021-03-15 11:07 UTC, zahmis commented on src/server/service/bolt.js
>        await this.client.chat.postEphemeral({
この method を共通化させました。

2021-03-15 13:27 UTC, yuki-takei requested changes

2021-03-15 13:27 UTC, yuki-takei commented on src/server/service/bolt.js
> +            },
share ボタンかぶってるよ

2021-03-16 03:44 UTC, zahmis commented on src/server/service/bolt.js
両方とも切り出しました。
理由は一つだけ直書きが気持ち悪かったからです。

2021-03-16 03:44 UTC, zahmis commented on src/server/service/bolt.js
> +            },
😭

2021-03-16 09:49 UTC, yuki-takei requested changes

2021-03-16 09:49 UTC, yuki-takei commented on src/server/service/bolt.js
> +      }
```
const actionBlocks: array = [{ ...shareBlock の中身 }];
if (次ページがあったら) {
  actionBlocks.push({ ...nextBlock の中身 };
}
```

2021-03-16 11:11 UTC, zahmis commented on src/server/service/bolt.js
> +      }
承知しました

2021-03-16 11:16 UTC, zahmis commented on src/server/service/bolt.js
> +      }
actionBlocks は配列にしていません
(Next を加えるべき場所は actionBlocks の element のため)

2021-03-16 11:21 UTC, merged