Imprv/create endpoint for setting slackbot
weseek/growi pull request #3538
Opened 2021-03-18 11:56 UTC by zahmis

2021-03-18 19:51 UTC, yuki-takei requested changes

2021-03-18 19:51 UTC, yuki-takei commented on src/server/routes/apiv3/slack-bot-setting.js
> +      slackBotToken: await crowi.configManager.getConfig('crowi', 'slackbot:token'),
bot のどのタイプを選んでいるかも必要なのではないか？
つまり「カスタムボット」の設定に限らないのでは。

2021-03-18 19:51 UTC, yuki-takei commented on src/server/routes/apiv3/index.js
> +  router.use('/slack-bot-setting', require('./slack-bot-setting')(crowi));
- https://wsgrowi.slack.com/archives/C01JZJP1J58/p1616091076175700 あたりの議論の答えを待つ必要がある
    - incoming webhook や旧 Slack App の設定がここに入ってくるのであれば、 `/slack-settings` 等にしたほうがしっくりくる

2021-03-19 03:00 UTC, zahmis commented on src/server/routes/apiv3/slack-bot-setting.js
> +      slackBotToken: await crowi.configManager.getConfig('crowi', 'slackbot:token'),
ここは エンドポイントを分けて実装するもの(/official-bot-setting などを作って) だと認識していました。

「1 つのエンドポイントでそれぞれの場合に分けて実装せよ。」
ということでしょうか？

2021-03-19 10:53 UTC, zahmis commented on src/server/routes/apiv3/index.js
> +  router.use('/slack-bot-setting', require('./slack-bot-setting')(crowi));
Incoming webhook と 旧 Slack App は **通知**に分類するため、このエンドポイント(Slack bot)には含見ません。
名称はこのままでいきます。

2021-03-19 11:41 UTC, yuki-takei commented on src/server/routes/apiv3/index.js
> +  router.use('/slack-bot-setting', require('./slack-bot-setting')(crowi));
slack-integration にしましょう

2021-03-22 04:09 UTC, zahmis commented on src/server/routes/apiv3/index.js
> +  router.use('/slack-bot-setting', require('./slack-bot-setting')(crowi));
承知しました

2021-03-22 11:53 UTC, yuki-takei requested changes

2021-03-22 11:53 UTC, yuki-takei commented on src/server/service/config-loader.js
> +    default: 'custom-non-proxy', // If impl Official bot, set official in default
これは初期値は null (未セットアップ)

2021-03-22 11:53 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +        await updateSlackBotSettings(requestParams);
タイプを変更したときは、別のタイプで必要なコンフィグは全てリセット(消去)されるのが望ましい気がする。custom bot without proxy から official bot に切り替えた時に、token/secret のような情報をいつまでも保持し続けるべきではない。

2021-03-22 11:53 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +  router.put('/custom-bot-setting',
後述のコンフィグリセットに対応するため、custom-bot-without-proxy 専用にすべき。

2021-03-23 09:35 UTC, yuki-takei requested changes

2021-03-23 09:35 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +   */
swagger だけ直して

2021-03-23 13:06 UTC, merged