Imprv/slack notification from slack bot
weseek/growi pull request #3554
Opened 2021-03-24 11:41 UTC by zahmis

2021-03-24 11:56 UTC, zahmis commented on package.json
> +    "@slack/web-api": "^6.1.0",
@slack/web-api を導入しています。
理由は 
[公式](https://api.slack.com/methods/chat.postEphemeral/code)では、これを使用して slack api を使用しています。
また、slack-node では legacy token が必要で、新規に作成した slack bot で わざわざ legacy token を発行させるのは逆行していると考えました。

2021-03-24 11:56 UTC, zahmis commented on src/server/util/slack.js
> +      if (configManager.getConfig('crowi', 'slackbot:token')) {
Slack bot , Incoming Webhook, 旧 slack app どれを優先させるのか？
という仕様はまだ固まっておらず、仕様が確定し次第 task 化して進めようと思っています。

2021-03-24 12:02 UTC, zahmis commented on src/server/util/slack.js
> +      if (configManager.getConfig('crowi', 'slackbot:token')) {
今回は、Incoming webhooks を優先する場合は Incoming webhooks 最優先にしています。

2021-03-24 12:06 UTC, zahmis commented on package.json
> +    "@slack/web-api": "^6.1.0",
また slack-node は 5年更新されていませんでした...

2021-03-24 18:14 UTC, yuki-takei requested changes

2021-03-24 18:14 UTC, yuki-takei commented on src/server/util/slack.js
> +      if (configManager.getConfig('crowi', 'slackbot:token')) {
slack-node と @slack/web-api の関係は理解した。

util/slack.js を、以下のようにリファクタしてください

1. slack.js は slack-legacy.js としてコピー
2. 既存コードは slack-legacy.js を参照して動くように
3. 元の slack.js は、@slack/web-api を利用して動くように
    - slack-node を使うコードは消して良い
4. slack-legacy.js と slack.js の共通部分(つまり重複コード)は slack.js のものを export して slack-legacy.js からも利用できるようにする

2021-03-26 07:08 UTC, zahmis commented on src/server/service/global-notification/global-notification-slack.js
村議で話し合った結果、この条件分岐は修正しました

2021-03-26 07:09 UTC, zahmis commented on src/server/service/user-notification/index.js
>        if (mode === 'comment') {
両方通知するようにしています

2021-03-26 07:09 UTC, zahmis commented on src/server/service/global-notification/global-notification-slack.js
> +      return [
両方通知するようにしています

2021-03-26 08:16 UTC, merged