Feat/4937 5495 implement access token without user
weseek/growi pull request #3564
Opened 2021-03-26 02:56 UTC by itizawa

2021-03-26 02:56 UTC, itizawa commented on src/server/routes/apiv3/slack-bot.js
> +  router.post('/', accessTokenParserForSlackBot, async(req, res) => {
req にセットする必要がないので error を投げる？

2021-03-26 03:04 UTC, itizawa commented on src/server/service/bolt.js
> +      await Page.create(path, contentsBody, slackUserId, {});
slackUserId は永続化すべき...?

2021-03-26 04:04 UTC, yuki-takei requested changes

2021-03-26 04:04 UTC, yuki-takei commented on src/server/service/bolt.js
> +      await Page.create(path, contentsBody, slackUserId, {});
ダミーのIDを作っていることがわかるように変数名の変更とコメント追加を。

2021-03-29 08:41 UTC, yuki-takei requested changes

2021-03-29 08:41 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +    hasher.update(`${new Date().getTime()}`);
sha256 では強度が不十分らしい。
https://github.com/weseek/growi/security/code-scanning/15?query=ref%3Arefs%2Fheads%2Fmaster

加えて salt もないので、もう少し工夫したほうがよさそう。

2021-03-29 08:41 UTC, yuki-takei commented on src/server/service/bolt.js
> +  }
- メソッドの名前的に boolean を返しそう
- postEphemeral するかどうかは使う側に任せよう
- Express の middleware 側(bolt.command に入ってくる前)にこのチェックってできないかな
    - bolt.command の第二引数で何が取れるのかによって、そのアプローチが有効かどうかは変わるだろう

2021-03-29 09:38 UTC, itizawa commented on src/server/service/bolt.js
> +  }
> Express の middleware 側(bolt.command に入ってくる前)にこのチェックってできないかな
可能ですが、その場合だと何が間違っているのかのレスポンスができない問題があります。
Access token is inValid を伝える postEphemeral を使いたくてここに置いています。

2021-03-29 09:49 UTC, itizawa commented on src/server/routes/apiv3/slack-integration.js
> +    hasher.update(new Date().getTime() + user._id);
ログインしていないと実行できないので、solt として user id を与える。

2021-03-29 11:07 UTC, yuki-takei requested changes

2021-03-29 11:07 UTC, yuki-takei commented on src/server/service/bolt.js
> +  }
>Access token is inValid を伝える postEphemeral

は、express で文字列を res.send してもできる。

また、検証のみ middleware で行い、検証結果に応じて postEphemeral する内容を変えるという処理の実装でもよい

2021-03-29 11:30 UTC, itizawa commented
<img width="760" alt="スクリーンショット 2021-03-29 20 29 31" src="https://user-images.githubusercontent.com/48426654/112830485-8a6c9780-90cd-11eb-8e5f-670e13a8c362.png">

2021-03-30 09:51 UTC, yuki-takei requested changes

2021-03-30 09:51 UTC, yuki-takei commented on src/client/styles/scss/theme/spring.scss
> +    @include btn-page-editor-mode-manager(darken($primary, 50%), darken($primary, 50%), lighten($primary, 10%));
これスコープ外のような…

2021-03-30 09:51 UTC, yuki-takei commented
関係ないものいっぱい入ってる気がする

2021-03-31 13:33 UTC, merged