Imprv/set state signing secret and token by hitting api
weseek/growi pull request #3569
Opened 2021-03-29 09:01 UTC by zahmis

2021-03-29 09:12 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotNonProxySettings.jsx
> +            defaultValue={secretEnv || null}
ここは 一時的に代入しています。
後ほど テーブルになります。

2021-03-29 09:12 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotNonProxySettings.jsx
> +            defaultValue={tokenEnv || null}
こちらも上記と同様です。

2021-03-29 10:52 UTC, yuki-takei requested changes

2021-03-29 10:52 UTC, yuki-takei commented on src/server/service/config-manager.js
> +const KEYS_FOR_SLACK_SINING_SECRET_OPTION = [
この const の意図が名前からはわからない。他のと同様、`..._USE_ONLY_ENV_...` なものを列挙しているのではないの？そうであれば命名を揃えて。

2021-03-30 01:54 UTC, zahmis commented on src/server/service/config-manager.js
> +const KEYS_FOR_SLACK_SINING_SECRET_OPTION = [
すみません。
消し忘れです...
意味はありません。

2021-03-30 02:48 UTC, merged