Feat/show table secret and token set in environment variable
weseek/growi pull request #3575
Opened 2021-03-30 08:49 UTC by zahmis

2021-03-30 08:51 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotNonProxySettings.jsx
> +            {t('admin:slack_integration.non_proxy.create_bot')}
前回 merged した時の コンフリクト解消で謝って消してしまったので復活させています。

2021-03-30 08:51 UTC, zahmis commented on src/server/service/config-loader.js
>      ns:      'crowi',
wiki 管理トップに表示しないように改修

2021-03-30 08:59 UTC, zahmis commented on resource/locales/en_US/admin/admin.json
> +    "use_env_var_if_empty": "If the value in the database is empty, the value of the environment variable <code>{{variable}}</code> is used.",
偶然タイポを発見しました

2021-03-31 02:35 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +            {t('admin:slack_integration.without_proxy.create_bot')}
以前 merge の際コンフリクト解消で誤ってmerge したものを修正しています。

2021-03-31 13:37 UTC, yuki-takei requested changes

2021-03-31 13:37 UTC, yuki-takei commented on src/server/service/config-loader.js
>      ns:      'crowi',
スコープ外なので元に戻してください。
以下を考慮すると、変更前も変更後もベストではない気がする。

- token を「wiki 管理トップに表示しないように」という要求はあるのか？(必要なのか？)
- もしそういった要求があるとして、key の prefix を `security:` にするというのは理に適っているのか？

2021-03-31 14:08 UTC, zahmis commented on src/server/service/config-loader.js
>      ns:      'crowi',
承知しました。

- token を「wiki 管理トップに表示しないように」という要求はあるのか？(必要なのか？)
そう言った要求はないのですが、Signing secret と token は秘匿にすべきだと判断して security にしました。

2021-04-01 02:22 UTC, merged