Feat/4937 5532 re setup bolt after update secret
weseek/growi pull request #3576
Opened 2021-03-30 08:54 UTC by itizawa

2021-03-30 08:55 UTC, itizawa commented on src/server/routes/apiv3/slack-integration.js
> +
設定を更新したときにセットアップし直す

2021-03-30 09:45 UTC, yuki-takei requested changes

2021-03-30 09:45 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +
redundant 対応してください。

2021-03-30 09:45 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +
customize-setting.js の `router.put('/customize-title', ` を参考に

2021-04-01 05:17 UTC, yuki-takei requested changes

2021-04-01 05:17 UTC, yuki-takei commented on src/server/service/bolt.js
> +    const { s2sMessagingService } = this;
このフィールドないよね？動かないのでは？

2021-04-01 06:41 UTC, merged