Feat/get slack work space name
weseek/growi pull request #3580
Opened 2021-04-01 04:01 UTC by zahmis

2021-04-01 04:17 UTC, zahmis commented on src/server/routes/apiv3/slack-integration.js
> +    const slackBotToken = crowi.configManager.getConfig('crowi', 'slackbot:token');
slackbot:token から WS を取得します。
official (or with proxy) の場合 => インストールした時点で token がはいるはず。
without の場合 => 自分で入力する。

切り替えた際は、他の token は削除されるように設計されている。

現状は 1 つの WS しか取得することができませんが、将来的に複数 WS を持つように改修する必要があります。

2021-04-01 04:17 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const [siteName, setSiteName] = useState('');
フロント側のコーディングの前段階として用意しています。（今は使っていません）

この siteName は without-proxy であれば、事足りますが、
他の site を将来的に持つのであれば、他の GROWI サーバーから取得してくる必要があります。

今回のタスクのスコープは without-proxy もしくは  1 つのGROWI と連携するところまでです。

2021-04-01 05:24 UTC, yuki-takei requested changes

2021-04-01 05:24 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +    const slackWorkSpaceName = slackTeamInfo.team.name;
いま、token が手に入る前(ワークスペース名を取得できない状態)でもこのコードが走るので、おかしなことになる

2021-04-02 03:32 UTC, zahmis commented on src/server/routes/apiv3/slack-integration.js
> +    const slackWorkSpaceName = slackTeamInfo.team.name;
なるほど。
トークン取得後に ws 名を取得できるように改良します

2021-04-02 06:11 UTC, zahmis commented
今回のタスクのスコープは Custom Bot Without Proxy の場合の slack WS 名の取得にしました。
なので test の段階の導通は含まれません。

手順として、token が存在しない場合は slack WS を取得しない。
token を入力し、更新を実行すると、 WS 名を取得し反映するようしています。

2021-04-02 09:58 UTC, yuki-takei requested changes

2021-04-02 09:58 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  const [slackWSNameInWithoutProxy, setSlackWSNameInWithoutProxy] = useState(null);
親は関係ないので子供の中で完結させてください

2021-04-02 09:58 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +  router.get('/custom-bot-without-proxy-slack-workspace', async(req, res) => {
API のエンドポイント名がよくない(よくわからない)

2021-04-02 09:58 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +  router.get('/custom-bot-without-proxy-slack-workspace', async(req, res) => {
- 進捗状況を図示する部分の情報だけを扱うならば、それを表す名前に
- ページ下部のフォームにも影響する API なのであればそれを表す名前に

2021-04-02 10:53 UTC, zahmis commented on src/server/routes/apiv3/slack-integration.js
> +  router.get('/custom-bot-without-proxy-slack-workspace', async(req, res) => {
承知しました

2021-04-02 11:07 UTC, zahmis commented on src/server/routes/apiv3/slack-integration.js
> +  router.get('/custom-bot-without-proxy-slack-workspace', async(req, res) => {
このエンドポイントで取得する値はページ下部( おそらく消えるであろう Access token) には関係ないので、
図示している部分を表す名称にします。

2021-04-02 11:14 UTC, yuki-takei requested changes

2021-04-02 11:14 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  adminAppContainer: PropTypes.instanceOf(AdminAppContainer).isRequired,
これ使ってないなら消そう

2021-04-02 11:17 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  adminAppContainer: PropTypes.instanceOf(AdminAppContainer).isRequired,
すみません
消し忘れていました...

2021-04-02 11:33 UTC, merged