Feat/create endpoint growi register
weseek/growi pull request #3585
Opened 2021-04-05 04:27 UTC by zahmis

2021-04-05 04:39 UTC, zahmis commented on packages/slack/src/utils/slash-command-parser.ts
> +    growiCommandType: splitted[0],
ここ多分 [0] だと思います。

2021-04-05 04:39 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +  @Inject()
Inject() することで、他のプロバイダ(RegisterService.ts) が使えるようになるという認識です。
(これによって、インスタンス化してくれていると思ってます)

2021-04-05 04:39 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +  handleEvent(@BodyParams() body:{[key:string]:string}, @Res() res: Res): string {
body の型は 全て stirng でした。
以下例
```
{
  token: 'XQ1TDp6XjwSjA.........',
  team_id: 'T01BRKEFZQS',
  team_domain: 'w1601537891-m9q891389',
  channel_id: 'C01BAT2LXHV',
  channel_name: 'general',
  user_id: 'U01BNGTJYJZ',
  user_name: 'meda829ratteru86',
  command: '/growi',
  text: 'register',
  api_app_id: 'A01RFMW2KGQ',
  is_enterprise_install: 'false',
  response_url: 'https://hooks.slack.com/commands/T01BRKEFZQS/1933187971492/Zc03zFkwKkjTcGzR6SennXez',
  trigger_id: '1939638921729.1399660543842.1a20c26a3c254a002b4eed476c9dcc8a'
}
```

2021-04-05 04:39 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const slackInput = this.receiveService.receiveContentsFromSlack(body);
/events のエンドポイントで slack の情報を受け取ります。
その後 receiveService で受け取り後の処理を行う設計にしています。

2021-04-05 04:39 UTC, zahmis commented on packages/slackbot-proxy/src/services/RecieveService.ts
> +  receiveContentsFromSlack(body:{[key:string]:string}) : string {
ここで コマンドごとの 処理を各 service に任せるつもりです。

search や create その他できるであろうコマンドは slack ディレクトリに書く認識です。

register は slack-proxy に処理を書いても良いのでしょうか？(うろ覚えなんですが,
前の bot ミーティングでそんなことを聞いた記憶があります。)

2021-04-05 06:59 UTC, zahmis commented on packages/slackbot-proxy/src/services/RecieveService.ts
> +    if (body.text === 'register') {
ここで コマンドごとの 処理を各 service に任せるつもりです。

2021-04-05 07:09 UTC, zahmis commented on packages/slack/src/utils/slash-command-parser.ts
> +import { GrowiCommand } from '../interfaces/growi-command';
module not found だったので一旦 ~ 使わずに記載しています。
後ほど、修正します

2021-04-05 07:22 UTC, zahmis commented on packages/slack/src/utils/slash-command-parser.ts
> +  if (splitted.length < 1) {
ここも多分 1 だと思っています。

2021-04-05 07:23 UTC, zahmis commented on packages/slack/src/utils/slash-command-parser.ts
> +    growiCommandType: splitted[0],
```
/growi register hoge と打ち込んだ時の結果
parseBody {
  text: 'register hoge',
  growiCommandType: 'register',
  growiCommandArgs: [ 'hoge' ]
}
```

2021-04-05 07:23 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +  handleEvent(@BodyParams() body:SlashCommand, @Res() res: Res): string {
body の型が存在したので SlashCommand を使います

2021-04-05 07:41 UTC, yuki-takei commented
`data/sqlite.db` いらないです

2021-04-05 07:45 UTC, yuki-takei requested changes

2021-04-05 07:45 UTC, yuki-takei commented on packages/slack/src/utils/slash-command-parser.ts
> +    growiCommandType: splitted[0],
slash-command-parser-test.ts って通ってる？

2021-04-05 07:45 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +  handleEvent(@BodyParams() body:SlashCommand, @Res() res: Res): string {
eslint error 出てないかな

2021-04-05 07:45 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RecieveService.ts
> +import { parse } from '../../../slack/src/utils/slash-command-parser';
ここは `slack/src/utils/slash-command-parser` にならないといけない(yarn workspaces の機能による resolve)

2021-04-05 07:55 UTC, zahmis commented on packages/slack/src/utils/slash-command-parser.ts
> +    growiCommandType: splitted[0],
test は 通ってそうですね。
warning は console.log と never used のみっぽいです

```

/workspace/growi/packages/slackbot-proxy/src/Server.ts
  88:5  warning  Unexpected console statement  no-console
  91:5  warning  Unexpected console statement  no-console

/workspace/growi/packages/slackbot-proxy/src/controllers/slack.ts
  67:5  warning  Unexpected console statement  no-console
  70:5  warning  Unexpected console statement  no-console

/workspace/growi/packages/slackbot-proxy/src/services/InstallerService.ts
  41:11  warning  Unexpected console statement              no-console
  50:34  warning  'installQuery' is defined but never used  @typescript-eslint/no-unused-vars

/workspace/growi/packages/slackbot-proxy/src/services/RecieveService.ts
  11:7  warning  Unexpected console statement  no-console

✖ 7 problems (0 errors, 7 warnings)
```

2021-04-05 07:55 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +  handleEvent(@BodyParams() body:SlashCommand, @Res() res: Res): string {
出ていなさそうですね。

2021-04-05 07:55 UTC, zahmis commented on packages/slackbot-proxy/src/services/RecieveService.ts
> +import { parse } from '../../../slack/src/utils/slash-command-parser';
なるほど
承知しました

2021-04-06 07:33 UTC, zahmis commented on packages/slack/src/utils/slash-command-parser.ts
>  import { SlashCommand } from '@slack/bolt';
ここは、bolt から剥がすために独自で interface を作成する方針なのですがいかがでしょうか？

2021-04-06 07:38 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +  handleEvent(@BodyParams() body:SlashCommand, @Res() res: Res): string {
SlashCommand は @slack/bolt のものでした。
bolt から剥がす方針なので、ここは改善しようと思います。
body のvalue の型は 全て string だったのでそれを満たすように型を定義します。

2021-04-06 16:40 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +  handleEvent(@BodyParams() body:{[key:string]:string}, @Res() res: Res): string {
value が全て string だったので string としています。

2021-04-07 11:37 UTC, yuki-takei requested changes

2021-04-07 11:37 UTC, yuki-takei commented on packages/slack/src/utils/slash-command-parser.ts
> +    growiCommandType: splitted[0],
- テストがおかしいのか実装がおかしいのか、謎を解いて
- 追加実装の話で、trim もしないといけないかも
    - 両端にスペースがある場合とかにうまく動かない
    - これもテスト追加してほしい

2021-04-07 11:37 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const slackInput = this.receiveService.receiveContentsFromSlack(body);
モジュール分割の観点からはベストな設計だとは思わないが、このタスクのスコープ外なのでとりあえずこのままでよい。

2021-04-07 11:46 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const slackInput = this.receiveService.receiveContentsFromSlack(body);
なるほど。承知しました。

2021-04-07 11:46 UTC, zahmis commented on packages/slack/src/utils/slash-command-parser.ts
> +    growiCommandType: splitted[0],
`  const splitted = slashCommand.text.split(' ');`

text に入ってくるのが /growi register hoge ではありませんでした 
text に入ってくるのは register hoge となっています。
command に /growi  が入るようになっていますね。

なので split した結果 [0] を入れる必要がありそうです。

```
...
 user_name: 'meda829ratteru86',
  command: '/growi',
  text: 'register hoge',
...
```

2021-04-08 02:54 UTC, zahmis commented on packages/slack/src/utils/slash-command-parser.ts
> +  if (splitted.length < 1) {
`/growi register waimatu` と入力した場合
slashCommand.text.split(' ') は `[ 'register', 'waimatu' ]` が入ります。
以下のエラーの想定は, `/growi `としか入力しないときに発生すると思っていて、その場合は
`if(splitted[0] === '') ` と考えました。
length で処理するのは難しいと思っています。
理由は、`/growi ` と`/growi register` を入力した時に,両方とも length が同じになるため判別できないからです。(text に入ってくるものは, /growi は [''], /growi register は['register'])

2021-04-08 02:54 UTC, zahmis commented on packages/slack/src/utils/slash-command-parser.ts
> +  const trimmedText = slashCommand.text.trim();
text を trim しています

2021-04-08 02:57 UTC, zahmis commented on packages/slack/src/utils/slash-command-parser.ts
> +  if (splitted[0] === '') {
/growi register waimatu と入力した場合
slashCommand.text.split(' ') は [ 'register', 'waimatu' ] が入ります。
以下のエラーの想定は, /growi としか入力しないときに発生すると思っていて、その場合は
if(splitted[0] === '') と考えました。
length で処理するのは難しいと思っています。
理由は、/growi と/growi register を入力した時に,両方とも length が同じになるため判別できないからです。(text に入ってくるものは, /growi は [''], /growi register は['register'])

2021-04-08 08:23 UTC, merged