Feat/5544 5554 implement order model
weseek/growi pull request #3595
Opened 2021-04-07 11:01 UTC by itizawa

2021-04-07 11:53 UTC, yuki-takei requested changes

2021-04-07 11:53 UTC, yuki-takei commented on packages/slackbot-proxy/src/entities/order.ts
> +  teamId: string;
order テーブル内では unique ではないんじゃ？

2021-04-07 11:53 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const order = await this.orderRepository.findOrCreateByTeamId(teamId);
- Installation の存在は確認すべき
    - 存在しなければ 400
- find -> expire チェック -> expire してたら新規作成 という流れにしよう
    - つまり findOrCreateByTeamId は「なければ作成」ルールで repository にインスタンスを用意させるということなのでおかしい
    - findOrCreateActiveOrder みたいな、expire してたら自動で作らせる、ならわかるけれど、使う側は expire してるかどうかで処理を分けるかもしれないのでやはり一つずつ段階を踏むのがよい

2021-04-07 11:53 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const order = await this.orderRepository.findOrCreateByTeamId(teamId);
因みにワークスペースに紐付かせるのは teamId だけでは不足。Enterprise Grid の場合もあるので。
Installation と many-to-one にするのが手軽かも。

2021-04-08 06:40 UTC, itizawa commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const installation = await this.installationRepository.findByID('1');
一旦仮で ID を用いて検索しています。

2021-04-08 08:37 UTC, yuki-takei requested changes

2021-04-08 08:37 UTC, yuki-takei commented on packages/slackbot-proxy/src/entities/installation.ts
> +  orders?: Order[];
双方向参照は本当に必須の場合にのみ入れるべきで、one-to-many の参照が必要なケースは少ない。
今回も Installer -> Order への参照は不要。

2021-04-09 02:46 UTC, merged