Feat/create modal after typing growi register
weseek/growi pull request #3596
Opened 2021-04-07 11:09 UTC by zahmis

2021-04-07 11:21 UTC, zahmis commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +  // tmp use process.env
一時的に process.env.~~~ を使用しています。
適切に DB に保存されるようになったのち改修します

2021-04-07 11:59 UTC, yuki-takei requested changes

2021-04-07 11:59 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RecieveService.ts
> +      await openRegisterModal(body);
コマンド毎に処理の委譲先を変えるのは必要なんだけど、controller でやればいいと思う。ReceiveService の存在意義をあまり感じない。

振り分けは if 文や switch 文を書く必要がないようにしたい。理想的には

1. ファイル(モジュール)を追加
2. growiCommandType の文字列(今回だと `register`)と上記モジュールの関連付けをどこかに書く

をやったら対応するコマンドが増えるイメージ。

1で作ったファイル中に Decorator を書くことで2番の関連付けができたらめちゃくちゃかっこいいのだが、今回はそこまでは求めない。

2021-04-08 06:21 UTC, itizawa commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const targetModule = require(modulePath);
```
const { registerService } = require(modulePath);
or 
targetModuleFile.registerService()
```
で動くんですかね... 🤔

2021-04-08 07:55 UTC, zahmis commented on packages/slackbot-proxy/src/services/RecieveService.ts
> +      await openRegisterModal(body);
やってみます

2021-04-08 08:08 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const growiCommandsMappings = {
mapping によってそれぞれのファイルに振り分けています。

2021-04-08 08:42 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const growiCommandsMappings = {
handleEvent 内で宣言するのはおかしいな

2021-04-08 08:42 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +      register: () => this.registerService.openRegisterModal(body),
ここももうちょっと汎用的にできないものか…
サービスクラス全体に利用するインターフェース設計とかがあるとよい。Bootcamp を思い出して。

2021-04-08 13:29 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
>    @Get('/testsave')
ここはいじっていないです。

2021-04-08 13:29 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +   growiCommandsMappings = {
マッピングを handleEvent 内から外に出しています。

2021-04-08 13:29 UTC, zahmis commented on packages/slackbot-proxy/src/interfaces/growi-commands-mappings.ts
> +export interface GrowiCommandsMappings{
新規にinterface を作成して method を各 service で決定するようにしました。

2021-04-13 08:07 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +  growiCommandsMappings = {
マッピングを handleEvent 内から外に出しています。

2021-04-13 11:34 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const growiCommandsMappings = {
なるほど。外に出します

2021-04-13 11:34 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +      register: () => this.registerService.openRegisterModal(body),
インターフェイスを作成します。

2021-04-14 08:37 UTC, merged