Feat/create readme jp version
weseek/growi pull request #3615
Opened 2021-04-13 04:01 UTC by zahmis

2021-04-13 04:05 UTC, zahmis commented on README.md
> +# GROWI
自動保存で変更されました。
基本的に元の README の変更は 言語追加とコメント追加した以外ありません。

2021-04-13 04:05 UTC, zahmis commented on README.md
> +- [日本語](./README_JP.md)
日本語の導入を一旦ここにしています。

2021-04-13 04:05 UTC, zahmis commented on README.md
> +<!-- The following links do not exist -->
コメント追加しました。以下のリンクが 404 でした。改修しようと思ったのですが、スコープ外で調査が必要だったので別タスクにします。

2021-04-13 04:05 UTC, zahmis commented on README.md
> +<!-- The following links do not exist -->
コメント追加しました。以下のリンクが 404 でした。改修しようと思ったのですが、スコープ外で調査が必要だったので別タスクにします。

2021-04-14 07:57 UTC, yuki-takei requested changes

2021-04-14 07:57 UTC, yuki-takei commented on README_JP.md
> +- [さっそくはじめてみる](#さっそくはじめてみる)
ちょっと口語的すぎるかな

2021-04-14 07:57 UTC, yuki-takei commented on README_JP.md
> +| `yarn run server:prod` | サーバーを立ち上げます。                                         |
起動します

2021-04-14 08:43 UTC, merged