Feat/move verifying is slack request to slack package
weseek/growi pull request #3620
Opened 2021-04-14 08:14 UTC by zahmis

2021-04-16 08:38 UTC, zahmis commented on packages/slack/src/utils/verifying-is-slack-request.ts
> +  // take out slackSignature and timestamp from header
ここ一旦 any にいています。
理由は以下の warning に詰まったため
```
この呼び出しに一致するオーバーロードはありません。
  4 中 1 のオーバーロード, '(arrayBuffer: WithImplicitCoercion<ArrayBuffer | SharedArrayBuffer>, byteOffset?: number | undefined, length?: number | undefined): Buffer' により、次のエラーが発生しました。
    型 'string | string[] | undefined' の引数を型 'WithImplicitCoercion<ArrayBuffer | SharedArrayBuffer>' のパラメーターに割り当てることはできません。
      型 'undefined' を型 'WithImplicitCoercion<ArrayBuffer | SharedArrayBuffer>' に割り当てることはできません。
  4 中 2 のオーバーロード, '(str: WithImplicitCoercion<string> | { [Symbol.toPrimitive](hint: "string"): string; }, encoding?: BufferEncoding | undefined): Buffer' により、次のエラーが発生しました。
    型 'string | string[] | undefined' の引数を型 'WithImplicitCoercion<string> | { [Symbol.toPrimitive](hint: "string"): string; }' のパラメーターに割り当てることはできません。
      型 'undefined' を型 'WithImplicitCoercion<string> | { [Symbol.toPrimitive](hint: "string"): string; }' に割り当てることはできません。
```

2021-04-16 09:56 UTC, zahmis commented on packages/slack/src/utils/verifying-is-slack-request.ts
> +  if (slackSignature == null || slackSignature == null) {
型ガードするのと同時に slack 以外からの request で上記のものがない場合　Verification failed の文言で何が必要かを特定させないようにしています

2021-04-17 12:36 UTC, zahmis commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v2
自動保存で差分が出ていますがここは変更していません

2021-04-17 12:36 UTC, zahmis commented on .github/workflows/ci.yml
> +          npx lerna bootstrap
実際に追加した箇所

2021-04-17 12:36 UTC, zahmis commented on .github/workflows/ci.yml
> +          npx lerna bootstrap
実際に追加した箇所

2021-04-19 08:55 UTC, yuki-takei requested changes

2021-04-19 08:55 UTC, yuki-takei commented on src/server/routes/apiv3/slack-bot.js
> +  const slackBotSigningSecret = (req, res, next) => {
- 命名がいまいち
    - **名が体を表すように**
- middleware も function なので、そのような命名がよい

2021-04-19 08:55 UTC, yuki-takei commented on packages/slack/src/utils/verifying-is-slack-request.ts
> +    return res.send('Verification failed');
これって status 400 になるんだっけ？(なるならOK)

2021-04-19 08:55 UTC, yuki-takei commented on packages/slack/src/utils/verifying-is-slack-request.ts
> +};
このメソッドは middleware になるので、`src/middlewares` に移してください

2021-04-19 12:29 UTC, zahmis commented on src/server/routes/apiv3/slack-bot.js
> +  router.post('/', verificationRequestUrl, addSlackBotSigningSecret, verificationSlackRequest, verificationAccessToken, async(req, res) => {
ミドルウエアの命名を変更しています。

2021-04-19 12:29 UTC, zahmis commented on packages/slack/src/utils/verifying-is-slack-request.ts
> +};
承知しました

2021-04-19 12:29 UTC, zahmis commented on src/server/routes/apiv3/slack-bot.js
> +  const slackBotSigningSecret = (req, res, next) => {
修正しまsつ

2021-04-19 12:37 UTC, zahmis commented on packages/slack/src/utils/verifying-is-slack-request.ts
> +    return res.send('Verification failed');
確認しました結果、200 が 返ってきます。bad reqest ではありませんでした。

200 になる場合はもっと前の段階で 検証するべきなのでしょうか？

(  経緯 )
- slack 以外の インターフェースで api を叩いた時の対処として 攻撃者に slackSignature と timestamp が必要であるのを特定させないために res.send('Verification failed') としています。
- slackSignature が存在しない場合ここで return することにより 後の slackSignature の型ガードを行っております。

2021-04-20 04:07 UTC, zahmis commented on packages/slack/src/middlewares/verification-slack-request.ts
> +    return res.status(401).send({ message: 'Unauthorized. Enter from Slack workspace' });
status code を追加しています。
403 というよりは そもそも認証するわけには行かないので 401 にしています。

2021-04-20 08:29 UTC, yuki-takei commented on packages/slack/src/middlewares/verification-slack-request.ts
> +    return res.status(401).send({ message: 'Unauthorized. Enter from Slack workspace' });
いや403が相応しいような気がする。
https://developer.mozilla.org/ja/docs/Web/HTTP/Status

2021-04-20 09:50 UTC, merged