Feat/create input slack ws for test
weseek/growi pull request #3625
Opened 2021-04-15 04:35 UTC by zahmis

2021-04-15 04:42 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +                <span className="card-text">
browser で出現する error を修正
`<div> cannot appear as descendant of <p>`

2021-04-15 04:42 UTC, zahmis commented on src/client/styles/scss/_admin.scss
> +  .slack-connection-log {
成功時も log を出現させるので 名称を変更

2021-04-15 04:42 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +  const [testChannel, setTestChannel] = useState('');
null は許容してくれないので 空の string を初期値で設定

2021-04-15 04:42 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
>              </div>
i18n は steven-f さんが実装してくれてます

2021-04-15 04:42 UTC, zahmis commented on src/server/routes/apiv3/slack-integration.js
> +      body('channel').not().isIn(['']).isString(),
空文字の状態を初期値にしています。
その状態で送信されるのは不適切なので validation を追加しています。

2021-04-15 04:42 UTC, zahmis commented on src/server/routes/apiv3/slack-integration.js
> +        await this.client.chat.postMessage({
await 必要でした

2021-04-15 04:42 UTC, zahmis commented on src/server/routes/apiv3/slack-integration.js
> +        const msg = `Error: ${error.data.error}. Needed:${error.data.needed}`;
すみません...
error 詳細以前取得していなかったので修正しました。

2021-04-15 07:23 UTC, yuki-takei requested changes

2021-04-15 07:23 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +                )}
textarea にしよう。複数行ログ入れるかもだし、コピペできるようにしたい。
管理画面なので、見た目の再現度(どの程度XDに寄せるか)は優先度低くて良い。

2021-04-15 07:23 UTC, yuki-takei commented on src/client/styles/scss/_admin.scss
> +    .slack-connection-log-title {
border も、textarea にした時に見た目の再現が難しければそこまでこだわらなくてもよい

2021-04-16 03:53 UTC, zahmis commented on src/client/styles/scss/_admin.scss
> +    .slack-connection-log-title {
承知しました

2021-04-19 07:09 UTC, itizawa reviewed
コメントしました。確認お願いします

2021-04-19 07:09 UTC, itizawa commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +              )}
textarea の style が変わらないのであれば value だけを切り替えればいいのでは...?

2021-04-19 07:09 UTC, itizawa commented on src/server/routes/apiv3/slack-integration.js
> +      body('channel').not().isIn(['']).isString(),
これだと `' '`(スペース) が通ってしまうのでは

2021-04-19 09:02 UTC, itizawa commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +              {connectionSuccessMessage != null && (value = { connectionSuccessMessage })}
return の中で 表示の value を組み立てるのは... なかなかやらないですね

2021-04-19 09:02 UTC, itizawa commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +              {connectionSuccessMessage != null && (value = { connectionSuccessMessage })}
そして connectionErrorMessage != null がかぶっていてリーダブルでないかも

2021-04-19 10:56 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +                disabled={testChannel.trim() === ''}
space を許容していません

2021-04-19 10:56 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +              <span className="input-group-text" id="slack-channel-addon"><i className="fa fa-hashtag" /></span>
slack 記号を追加

<img width="553" alt="スクリーンショット 2021-04-19 19 51 28" src="https://user-images.githubusercontent.com/57100766/115225638-4824fc00-a149-11eb-9c54-24fd2d1b9d4c.png">

2021-04-20 01:51 UTC, itizawa reviewed
コメントしました。確認お願いします

2021-04-20 01:51 UTC, itizawa commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +                className="btn btn-info m-3 font-weight-bold"
button が縦方向に margin を持つ理由はありますか

2021-04-20 01:51 UTC, itizawa commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +              <label><p className="border-info slack-connection-log-title mb-1 pl-2">Logs</p></label>
mb-1 は label が持つべきだと思います

2021-04-20 01:51 UTC, itizawa commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +          <div className="row m-3 justify-content-center">
row が 横方向の margin を持つのは微妙な気がします

2021-04-20 01:51 UTC, itizawa commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +         && <p className="text-info text-center m-4">{t('admin:slack_integration.without_proxy.send_message_to_slack_work_space')}</p>}
p が 横方向の margin を持つのは微妙な気がします

2021-04-20 01:51 UTC, itizawa commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +                className="form-control card border-info slack-connection-log-body rounded-lg pl-3"
left にだけ padding が存在しているのはどういった理由ですか

2021-04-20 01:51 UTC, itizawa commented on src/server/routes/apiv3/slack-integration.js
> +        .isString(),
これって not() が trim() にかかっている気がしますが正しく動作するんですかね
`body('channel').trim().notEmpty(),`
こちらの方が読みやすそうです

2021-04-20 02:01 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +              <label><p className="border-info slack-connection-log-title mb-1 pl-2">Logs</p></label>
承知しました

2021-04-20 02:03 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +                className="form-control card border-info slack-connection-log-body rounded-lg pl-3"
消し忘れですね...
消します

2021-04-20 02:13 UTC, zahmis commented on src/server/routes/apiv3/slack-integration.js
> +        .isString(),
正しく動作します。
notEmpty() は legacy な仕様でした。
以下のように変更します。

` body('channel').trim().not().isEmpty(),`

[notEmpty() not working #476](https://github.com/express-validator/express-validator/issues/476)

2021-04-20 03:22 UTC, merged