Fix/5753 5754 check editor mode
weseek/growi pull request #3661
Opened 2021-04-23 01:20 UTC by itizawa

fix #3638

2021-04-23 03:31 UTC, yuki-takei requested changes

2021-04-23 03:31 UTC, yuki-takei commented on src/client/js/components/PageEditor.jsx
> +    }
判定手法として相応しい順で言うと、

1. Editor or CodeMirrorEditor/TextEditor 側で、ユーザー操作によらない変更であれば onChange を発火しない
    - → これは handsontable とか LinkEditModal 等のツールによる書き換えも考慮すると判別が難しそう
2. PageEditor.onMarkdownChanged が発火するが、「最新リビジョンと同じかどうか」をチェックする
    - → **3 よりも本質に近いので検討する**
    - body が完全一致するかどうかは、量が多いときにパフォーマンスが懸念されるが、問題ないならそれでもいい
3. (現在のPRの実装) PageEditor.onMarkdownChanged が発火するが、「view モードかどうか」をチェックする

2021-04-26 05:44 UTC, itizawa commented on src/client/js/components/PageEditor.jsx
> +    }
markdown の変更を検知して、pageContainer の markdown と違うのかを確認する。
Modal で更新した場合、PageEditor の state も更新される。

2021-04-26 06:32 UTC, yuki-takei requested changes

2021-04-26 06:32 UTC, yuki-takei commented on src/client/js/components/PageEditor.jsx
> +import NavigationContainer from '../services/NavigationContainer';
NavigationContainer はいらないのでは

2021-04-26 08:03 UTC, merged