Imprv/gw5547 updating order document
weseek/growi pull request #3673
Opened 2021-04-26 06:50 UTC by kaoritokashiki

2021-04-26 08:33 UTC, yuki-takei requested changes

2021-04-26 08:33 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    }
エラーハンドリングが微妙だな。
AuthorizeInteractionMiddleware を通過してるのに body.payload が null って有り得るの？
null だった場合は何もおこらないけどいいの？
try-catch はまたその中で例外処理してるけど、controller の責務として throw new Error で投げっぱなしなのはだめなのでは？

2021-04-26 08:33 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +      if (order) {
この書き方はNG

2021-04-27 06:14 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    }
なるほど、`AuthorizeInteractionMiddleware`でreq.bodyからpayloadを取得していたので必要ありませんでした。

2021-04-27 06:16 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/controllers/slack.ts
> +      if (order != null) {
修正しました

2021-04-27 06:58 UTC, yuki-takei requested changes

2021-04-27 06:58 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +      res.send();
Slackからリクエストが来てから処理完了までの流れをちゃんと考えたい。

https://github.com/weseek/growi/pull/3673/files?diff=split&w=1#diff-356915a866173c837a5a683f782f371488a2e67cb1914ca907a3ac64197b3a02R89-R91

が参考になるが、正常系での res.send() はそこそこ序盤に持ってきたい。

悩みどころだけど、今回は AuthedReq が取れることが確定したら res.send() していいと思う。なので、このメソッドでは installation の**取得前**で構わない(middleware を通過していれば installation も存在しているはずで、正常系だと見なす)。

2021-04-27 06:58 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    }
逆にこれは try-catch の結果、res.send してはいけない。上のFB通に実装するとなると、handleViewSubmission の実行前にもう response は送っちゃうので。

その後の処理に問題があったら、ロガーに出して、もっと親切にするなら Slack 側 API を叩いてエラーメッセージを届けるというのが恐らく正しい。

2021-04-30 02:02 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    res.send();
AuthedReqの取得後、installation の取得前で`res.send()`するよう変更しました。

2021-04-30 02:03 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    }
ロガーに変更しました

2021-04-30 10:22 UTC, merged