Imprv/create reset button
weseek/growi pull request #3690
Opened 2021-05-06 06:47 UTC by zahmis

2021-05-06 10:15 UTC, yuki-takei requested changes

2021-05-06 10:15 UTC, yuki-takei commented on resource/locales/en_US/admin/admin.json
> +    "credentials_notice": "Remove Signing Secret and Bot Token",
何をリセットするかまでは書く必要がないかな
それに bot のタイプも含めリセットすることになるのでは？

2021-05-06 10:15 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +  isSetupSlackBot: PropTypes.bool.isRequired,
このカードがなぜ `isSetupSlackBot` を必要としているのかわからない。
オールリセットされているならこのカードもろとも表示されないはず。

2021-05-06 10:15 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const { appContainer, isSlackScopeSet, isSetupSlackBot } = props;
Slack bot のスコープが期待する値ではなという事象は数ある異常系シチュエーションの一つに過ぎないので、`errors: []` のような array を用意する

2021-05-06 10:15 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +      await appContainer.apiv3.put('slack-integration/custom-bot-without-proxy', {
なくても動くけど頭に `/` を付けて

2021-05-06 10:15 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +      <DeleteSlackCredentialsModal
リセット対象は credentials だけではなくなるので改名する

2021-05-06 10:15 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  onSetIsSlackScopeSet: PropTypes.func,
このメソッドはどこで使われているんだ…

2021-05-06 10:15 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +      fetchSlackIntegrationData();
この `fetchSlackIntegrationData` は外から注入する必要があるのか？

2021-05-06 10:18 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  onSetIsSlackScopeSet: PropTypes.func,
すみません消し忘れです...

2021-05-06 10:19 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +      fetchSlackIntegrationData();
これを注入しないと値が更新されないと思っています

2021-05-06 10:19 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +      <DeleteSlackCredentialsModal
承知しました

2021-05-06 10:19 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +      await appContainer.apiv3.put('slack-integration/custom-bot-without-proxy', {
承知しました

2021-05-06 10:19 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const { appContainer, isSlackScopeSet, isSetupSlackBot } = props;
ナルホド

2021-05-06 10:20 UTC, zahmis commented on resource/locales/en_US/admin/admin.json
> +    "credentials_notice": "Remove Signing Secret and Bot Token",
確認します

2021-05-06 10:40 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +  isSetupSlackBot: PropTypes.bool.isRequired,
ナルホド。
完全に思い違いしてました。
となるとこれはいらないですね

2021-05-06 10:40 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +      fetchSlackIntegrationData();
と思っていた時期が僕にもありました。

2021-05-07 02:59 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +        {props.slackSettingsErrors.includes(false) ? (
slackSettingsErrors という errors の配列を作成しました。
この有無で通信成功か否かを判断しています。

2021-05-07 02:59 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  onSetIsSlackScopeSet: PropTypes.func,
最初使っていなかったんですが、deleteSlackSettingsHandler を実行するときに isSlackScopeSet も false にするのが適切なのでメソッドを 28 行目に追加しました。

2021-05-07 02:59 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> -          isConnectedToSlack={isConnectedToSlack}
いらないので消しました

2021-05-07 02:59 UTC, zahmis commented on resource/locales/en_US/admin/admin.json
> +    "credentials_notice": "Remove Signing Secret and Bot Token",
他の Modal を参考に以下のようにしました。
<img width="645" alt="スクリーンショット 2021-05-07 11 58 03" src="https://user-images.githubusercontent.com/57100766/117391707-7c5f3180-af2b-11eb-968b-8c939953f82a.png">

2021-05-10 09:10 UTC, yuki-takei requested changes

2021-05-10 09:10 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +        {props.slackSettingsErrors.includes(false) ? (
true, false の配列というのも仕様的に怪しい

2021-05-10 09:10 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  };
- 想定通りの挙動になっていない疑惑(true, false を引数に渡していない)
- true, false を引数に渡す、という仕様も怪しい
    - 親が管理する責務を持っているなら、子供(CustomBotWithoutProxySettings)はそれを知らなくて良い
    - ただ、**子供に責務を移す方がよさそう**

2021-05-10 09:12 UTC, yuki-takei commented
## PR わけたい

- OK
    - translation
    - モーダル作成、モーダル表示まで
    - モーダルのキャンセルまで
- NG
    - Delete ボタンを押した時の挙動
         - それに付随する state, props, event handler 一式

2021-05-10 09:51 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const deleteSlackSettingsHandler = async() => {
delete アクションは次のタスクで実装します。

2021-05-10 09:51 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +        {!props.isSlackScopeSet ? (
without proxy の errors は子供に持たせることにします。(次回タスクで)
現状一旦戻しています。

2021-05-10 10:00 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const deleteSlackSettingsHandler = async() => {
GW-5895 リセットボタンを押したときの挙動を修正する

2021-05-10 10:07 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  const [isSetupSlackBot, setIsSetupSlackBot] = useState(false);
これも消してください

2021-05-10 10:07 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +        {!props.isSlackScopeSet ? (
この変数再設計対象として消してください

2021-05-10 10:09 UTC, yuki-takei commented on src/server/service/slackbot.js
> +    this.isSetupSlackBot = false;
isConnectedToSlack, isSetupSlackBot 共に消してください

2021-05-10 10:31 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +        {!props.isSlackScopeSet ? (
承知しました

2021-05-10 10:31 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +
ws 名を取得するのは with withoutproxy official にもたせ、それぞれの state で条件分岐します。

2021-05-10 10:31 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> -        isConnectedToSlack,
承知しました

2021-05-10 10:35 UTC, merged