Imprv/gw5834 proxy url when undefined
weseek/growi pull request #3699
Opened 2021-05-07 12:02 UTC by kaoritokashiki

2021-05-07 12:06 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +    };
`client.chat.postEphemeral()`の処理を共通化したんですけど、しない方が見やすい感じでしたら元に戻します

2021-05-09 04:18 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +        generateMarkdownSectionBlock(`Proxy URL: ${serverUri}`),
XDでは、Proxy URL としているので、ここはそのままにしましたが、こちらも`Server URI`に変更した方が良いのであればXD含め修正します。
<img width="655" alt="Screen Shot 2021-05-09 at 13 18 08" src="https://user-images.githubusercontent.com/59536731/117560470-0690cc80-b0c9-11eb-8106-46acbfcb3e8b.png">

2021-05-09 09:13 UTC, yuki-takei requested changes

2021-05-09 10:07 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/Server.ts
> +
修正しました。
```
Error: The environment variable 'SERVER_URI' must be defined.
    at Object.<anonymous> (/workspace/growi/packages/slackbot-proxy/src/Server.ts:31:9)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (/workspace/growi/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-0721232013465074.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-0721232013465074.js:71:20)
    at Object.nodeDevHook [as .ts] (/workspace/growi/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/workspace/growi/packages/slackbot-proxy/src/index.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (/workspace/growi/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-0721232013465074.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
```

2021-05-09 17:26 UTC, merged