5882 put error
weseek/growi pull request #3708
Opened 2021-05-10 06:55 UTC by stevenfukase

2021-05-11 06:43 UTC, yuki-takei requested changes

2021-05-11 06:43 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +
- invalid_auth のエラーは誰が出しているのか？
    - おそらく initialize の sendAuthTest
- settings の保存時にテストが同時に走るのがそもそもシチュエーションとしておかしい

2021-05-11 06:43 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +        return res.apiv3Err(new ErrorV3('Invalid Secret or Token', 'get-SlackWorkSpaceName-failed'), 400);
- この API が呼ばれるのは、前提として slack との接続テストがうまくいっている場合
    - フロント側で制御されるはず
- バックエンドとしての対処をするならば、try-catch の前に接続テスト済みかどうかをチェックし、問題があれば 400 を返すべき

2021-05-12 03:01 UTC, stevenfukase commented on src/server/routes/apiv3/slack-integration-settings.js
> -
WSを取ってくるエンドポイントを削除しました。

2021-05-12 10:27 UTC, yuki-takei requested changes

2021-05-12 10:27 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +      if (data.connectionStatuses) {
null チェックはガイドライン通りに

2021-05-12 14:05 UTC, merged