Feat/create endpoint to save slack bot tokens
weseek/growi pull request #3715
Opened 2021-05-11 11:19 UTC by zahmis

2021-05-11 11:30 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +  router.put('/access-tokens', loginRequiredStrictly, adminRequired, csrf, async(req, res) => {
validator を入れなくて良いと思っています。
理由は、発行すると 2 つの tokenが自動で作成される予定だからです。
req.body は一時的に作成する便宜上実装しただけなので、今後消える予定です。

2021-05-11 11:45 UTC, yuki-takei requested changes

2021-05-11 11:45 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +      const slackAppTokens = await SlackAppIntegration.create({ tokenGtoP, tokenPtoG });
滅多にないと思うけど、tokenGtoP, tokenPtoG は unique じゃないといけないので、create を実行する前に存在チェックをしてください

2021-05-12 10:12 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +      const slackAppTokens = await SlackAppIntegration.create({ tokenGtoP, tokenPtoG });
存在した場合、token を regenerate するようにしています。

2021-05-12 10:43 UTC, yuki-takei requested changes

2021-05-12 10:43 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +      const slackAppTokens = await SlackAppIntegration.create({ tokenGtoP, tokenPtoG });
冗長だね。findOne は1行あれば十分(tokenGtoPとtokenPtoGのどちらかが一致するものが1件でもあればNG、というロジック)

ステートメント的には do while 使えばもうちょっと綺麗になるかな。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/do...while

2021-05-12 12:27 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +      const slackAppTokens = await SlackAppIntegration.create({ tokenGtoP, tokenPtoG });
なるほど

2021-05-12 14:26 UTC, yuki-takei requested changes

2021-05-12 14:26 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +  const SlackAppIntegration = crowi.model('SlackAppIntegration');
`mongoose.model('SlackAppIntegration')` で参照してください。

2021-05-12 14:26 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +      if (checkTokens !== null) {
null チェックはガイドライン通りに

2021-05-12 14:26 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +    let { tokenGtoP, tokenPtoG } = req.body;
この初回の generate も do while の中に入れられるよね

2021-05-13 02:30 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +    const SlackAppIntegration = mongoose.model('SlackAppIntegration');
初回の token 発行を do 内に入れることで、最終的な checkTokens の null check は不要と考えました。
理由は, checkTokens が見つからなければ、null になるためです。

2021-05-13 02:37 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +    let { tokenGtoP, tokenPtoG } = req.body;
なるほど

2021-05-13 02:37 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +      if (checkTokens !== null) {
すみません
修正します

2021-05-13 02:37 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +  const SlackAppIntegration = crowi.model('SlackAppIntegration');
承知しました

2021-05-13 08:54 UTC, yuki-takei requested changes

2021-05-13 08:54 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +    } while (checkTokens);
この while の条件内、ガイドライン通りに

2021-05-13 09:09 UTC, merged