Fix/behavior when clicked reset button
weseek/growi pull request #3718
Opened 2021-05-12 05:43 UTC by zahmis

2021-05-12 10:22 UTC, yuki-takei requested changes

2021-05-12 10:22 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +      fetchSlackIntegrationData();
without Proxy タイプ選択時にやりたいリセット処理は、親が行うフルリセットと挙動がほとんど同じ。
であれば親にやってもらえばいい。(フルリセットした上で currentBotType を改めて without Proxy にセットすればOK)

加えて、fetchSlackIntegrationData を再度実行する責務も親である。

このコンポーネントが行う責務は、

- リセットをしてほしいことを親に通知する
    - そういう意味では fetchSlackIntegrationData が不要になる代わりに、代替となる props (func) は必要
- リセットが正常終了した場合は toastSuccess 表示する

2021-05-13 06:11 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +      fetchSlackIntegrationData();
なるほど

2021-05-13 06:21 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const { appContainer, onResetSettings } = props;
親で汎用的な resetSettings を作成しました。
all reset は次回のタスクで作成します。

2021-05-13 06:21 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> -      await appContainer.apiv3.put('/slack-integration-settings/bot-type', {
「更新する」は必要なので restore させています。

2021-05-13 06:21 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +      toastSuccess(t('admin:slack_integration.bot_reset_successful'));
成功は一番最後に出したいので移動させました。

2021-05-13 06:21 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +    if (currentBotType === null) {
botType が null の場合を追加しています。

2021-05-13 06:21 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +  router.put('/update-settings', async(req, res) => {
「更新する」のはbotType 問わず必要だと思っています。
今考えているのは, get('/) と同様に botType ごとに処理を記述するのがいいと思っています。
理由は、エンドポイントを分けなくて済むからです。

2021-05-13 09:06 UTC, yuki-takei requested changes

2021-05-13 09:06 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +  router.put('/update-settings', async(req, res) => {
全く昨日話した仕様通りじゃない

2021-05-13 14:47 UTC, yuki-takei requested changes

2021-05-13 14:47 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +      await appContainer.apiv3.put('/slack-integration-settings/bot-type', { currentBotType: 'customBotWithoutProxy' });
55行目だけでいいのでは？

2021-05-14 05:40 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +      await appContainer.apiv3.put('/slack-integration-settings/bot-type', { currentBotType: 'customBotWithoutProxy' });
そうします

2021-05-14 05:43 UTC, zahmis commented
「更新する」ボタン の restore は次回タスクにします。

2021-05-14 08:59 UTC, yuki-takei requested changes

2021-05-14 08:59 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +      settings.slackBotToken = null;
これら消してください

2021-05-14 09:19 UTC, merged