Imprv/gw5917 save bot type to mongodb
weseek/growi pull request #3720
Opened 2021-05-12 10:47 UTC by kaoritokashiki

2021-05-12 11:14 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
> -          slackBotToken: crowi.configManager.getConfig('crowi', 'slackbot:token'),
slackSigningSecret, slackBotTokenに関しては、どこからも参照されていなかったので削除しています。

2021-05-12 11:32 UTC, yuki-takei requested changes

2021-05-12 11:32 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +      }
このエンドポイントはタイプの変更なので、この辺のをクライアントから受け取る必要がない
(全て消せばいい)

2021-05-12 11:45 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
> +      }
なるほどです。

2021-05-12 13:03 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +      await appContainer.apiv3.put('/slack-integration-settings/bot-type', {
'/custom-bot-without-proxy'は無くなったので一応rename

2021-05-12 13:05 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
> +  }
これは追加したのではなく、元々存在したメソッドです。

2021-05-12 13:06 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
> +  router.put('/defaults',
reset all 用のエンドポイントは`/defaults`にしました。

2021-05-12 13:09 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
> +    accessTokenParser, loginRequiredStrictly, adminRequired, csrf, apiV3FormValidator, async(req, res) => {
validatorは新規に作成する必要ないと考えたので、`validator.hoge`のような指定はないです。

2021-05-12 13:09 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
> +    accessTokenParser, loginRequiredStrictly, adminRequired, csrf, validator.BotType, apiV3FormValidator, async(req, res) => {
botTypeを変更する用のエンドポイントは`validator.BotType`を新規作成して追加しました。

2021-05-12 13:10 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
>      ],
validator.BotTypeでは、`currentBotType`の追加を必須にしています。

2021-05-12 13:23 UTC, yuki-takei requested changes

2021-05-12 13:23 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +    };
後続タスクで with proxy 環境下で設定させる config および token 等を保管するモデルの中身を全て消してください。

2021-05-12 13:23 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +      'slackbot:token': '',
これって空文字列指定じゃなきゃだめ？null 指定だと正常動作しない？

2021-05-12 13:23 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +  router.put('/defaults',
PUT /slack-integration-settings/defaults は違和感だな～
DELETE /slack-integration-settings/bot-type でいいような。

2021-05-13 03:58 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
> +    };
GW-5932 with proxy 環境下で設定する config ・token 等を保管するモデルの中身を全て消す
後続タスクを作成しました。

2021-05-13 04:20 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
> +  router.put('/defaults',
なるほど、修正しました。

2021-05-13 04:21 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
> +      'slackbot:token': '',
空文字ではなく、nullに変更しました。

2021-05-13 04:21 UTC, merged