Fix/problem not reflected when selected bot type at first
weseek/growi pull request #3744
Opened 2021-05-18 06:35 UTC by zahmis

2021-05-18 07:49 UTC, yuki-takei requested changes

2021-05-18 07:49 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  const handleBotTypeSelect = async(clickedBotType) => {
- changeCurrentBotSettingsHandler の中身を、changeCurrentBotSettings として再実装する
- このメソッドは botTypeSelectHandler に改名、changeCurrentBotSettings  を呼ぶ
- changeCurrentBotSettingsHandler の中身を消して、changeCurrentBotSettings  を呼ぶ

2021-05-20 03:48 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  const handleBotTypeSelect = async(clickedBotType) => {
- このメソッドは botTypeSelectHandler に改名、changeCurrentBotSettings を呼ぶ
この部分の意味が自分の中で理解できていないです。

`botTypeSelectHandler` は bot タイプが変更されたときに Modal を呼び出します(setSelectedBotType(clickedBotType)
)
これによって Modal が開かれると思っています。
そして開かれた Modal の変更するボタンを押すと `changeCurrentBotSettingsHandler` が実行され、その中身の`changeCurrentBotSettings`  を実行すると思っています。

なので、`botTypeSelectHandler` で `changeCurrentBotSettings` を呼び出すことが理解できていません。

2021-05-20 03:58 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  const changeCurrentBotSettings = async() => {
> changeCurrentBotSettingsHandler の中身を、changeCurrentBotSettings として再実装する

2021-05-20 03:58 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  const botTypeSelectHandler = async(clickedBotType) => {
> このメソッドは botTypeSelectHandler に改名、changeCurrentBotSettings を呼ぶ

2021-05-20 03:58 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  const changeCurrentBotSettingsHandler = async() => {
> changeCurrentBotSettingsHandler の中身を消して、changeCurrentBotSettings を呼ぶ

2021-05-20 07:17 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  const handleBotTypeSelect = async(clickedBotType) => {
やりたいことは、「重複コードを共通化する」リファクタ。

changeCurrentBotSettings が共通のコード。

2021-05-20 10:20 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +    if (currentBotType == null) {
初期状態では currentBotType は null です。
Modal を開かないために clickedBotType を渡しています。

2021-05-20 10:20 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +    setSelectedBotType(clickedBotType);
他の type から変更する場合は trigger を発動させます。

2021-05-20 10:20 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +  const changeCurrentBotSettingsHandler = async() => {
Modal を開いて変更するをクリックしたときの挙動です。
toast はこちらに移動しています。

2021-05-20 10:20 UTC, zahmis commented
関数を 2つにする方法がちょっと思いつかなかったので 3つで実装しています。

2021-05-20 11:16 UTC, yuki-takei requested changes

2021-05-20 11:16 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +        currentBotType: selectedBotType || clickedBotType,
これは引数の値固定にする。clicked という名前もおかしいので単に `botType` でよい。
場合分けが必要なら呼び出し側で変える。

2021-05-20 12:03 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +        currentBotType: selectedBotType || clickedBotType,
承知しました。

2021-05-20 12:48 UTC, merged