Feat/create endpoint without proxy relation test
weseek/growi pull request #3754
Opened 2021-05-20 07:18 UTC by zahmis

2021-05-21 00:35 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +      // TODO impl return response after imple 5996, 6002
relationTestToSlack は実装途中です。
これは slack パッケージにあり、steeven-f が現在実装中です。

2021-05-24 03:09 UTC, yuki-takei requested changes

2021-05-24 03:09 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +  router.post('/without-proxy/relation-test', loginRequiredStrictly, adminRequired, csrf, validator.SlackChannel, apiV3FormValidator, async(req, res) => {
with proxy と違い relation というモデルはないので、単に /test でよい

2021-05-24 03:09 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +      return res.apiv3Err(new ErrorV3(msg, 'send-message-to-slack-failed'), 500);
ここのメッセージ等が限定的すぎる。catch している error の中身がわかるように。

2021-05-24 03:14 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +  router.post('/without-proxy/relation-test', loginRequiredStrictly, adminRequired, csrf, validator.SlackChannel, apiV3FormValidator, async(req, res) => {
なるほど。
承知しました。

2021-05-24 03:15 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +      return res.apiv3Err(new ErrorV3(msg, 'send-message-to-slack-failed'), 500);
改修します。

2021-05-24 04:39 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +      return res.apiv3Err(new ErrorV3(error.message, 'send-message-to-slack-failed'));
複数 error が考えられるため、error.message を代入しています。
status code も複数あり、そのために条件分岐するのは苦しいので 入れていません。

2021-05-24 04:53 UTC, yuki-takei requested changes

2021-05-24 04:53 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +      return res.apiv3Err(new ErrorV3(error.message, 'send-message-to-slack-failed'));
- まず第一に「テストが失敗した」ということを言いたい
- 原因はなにか？← error に入っているので、その message を添付する

2021-05-24 05:38 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +      await relationTestToSlack(slackBotToken);
責務を考えると、slack package から呼び出している この method の名称はおかしいと思われます。
この名称変更は、実際に return の処理を実装するときに変更します。

2021-05-24 05:42 UTC, yuki-takei requested changes

2021-05-24 05:42 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +      return res.apiv3Err(new ErrorV3(error.message, 'test-failed'));
```
new ErrorV3(`Error occured. Cause: ${error.message}`, 'test-failed', error.stack);
```
としてください。

2021-05-24 07:15 UTC, merged