5921 test bot api
weseek/growi pull request #3755
Opened 2021-05-20 08:36 UTC by stevenfukase

2021-05-20 11:19 UTC, itizawa commented on packages/slack/src/utils/check-communicable.ts
> +};
すいません relationTestToSlack と同じことをしたいので統合してもらえると...
with proxy でも pingSlack を叩きたいです

2021-05-20 11:19 UTC, itizawa commented on packages/slack/src/utils/check-communicable.ts
> +};
pingSlack を実行する場所は後ほど実装でしょうか？

2021-05-21 02:19 UTC, stevenfukase commented on packages/slack/src/utils/check-communicable.ts
> +};
> pingSlack を実行する場所は後ほど実装でしょうか？
はい。5921で実装予定です。

2021-05-21 10:13 UTC, yuki-takei requested changes

2021-05-21 10:13 UTC, yuki-takei commented on packages/slack/src/utils/check-communicable.ts
> +};
testSlackApiServer とかぶっている

2021-05-21 10:13 UTC, yuki-takei commented on packages/slack/src/utils/check-communicable.ts
> +};
これは本体側からのみ使うのであれば、本体に実装すればいい内容

2021-05-21 10:13 UTC, yuki-takei commented on packages/slack/src/utils/check-communicable.ts
> +};
そうすると、postMessage も check-communicable には必要ないのではないか？
疎通できたことが確定したら chat.post すればいいよね。

2021-05-24 03:59 UTC, stevenfukase commented on packages/slack/src/utils/check-communicable.ts
> +};
`api.test()`と違いScopeが取得できる`auth.test()`が必要なので作りました。
`api.test()`を`auth.test()`に移行する作業を後続で対応する予定です。

2021-05-24 04:42 UTC, yuki-takei requested changes

2021-05-24 04:42 UTC, yuki-takei commented on packages/slack/src/utils/check-communicable.ts
> +export const newRelationTestToSlack = async(token: string): Promise<WebAPICallResult> => {
testSlackApiServer  があるのにこれを作る必要性がわからない。

2021-05-24 04:42 UTC, yuki-takei commented on packages/slack/src/utils/check-communicable.ts
> + * @param channel channel name
channel param なんてないよね？

2021-05-24 06:51 UTC, closed without merging