Imprv/gw6009 check growi url
weseek/growi pull request #3758
Opened 2021-05-20 13:54 UTC by kaoritokashiki

2021-05-21 05:03 UTC, yuki-takei commented
## 仕様の話
> slack-integration.jsにて、↑だとresponseが帰ってこないのですが、↓このような感じで修正する必要がありますでしょうか?

返って来るのが正しい挙動だね。

https://api.slack.com/apis/connections/events-api#the-events-api__subscribing-to-event-types__events-api-request-urls__request-url-configuration--verification

は考慮しないといけない。`{ message: body.challenge }` は example と外れるのでよくない。

## syntax の話
`status(200)` はデフォルトでそうなるので書く必要はない

2021-05-24 02:55 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +        message: 'url verification was successful',
`challange`ではなく`message`に変更しました。

2021-05-24 02:59 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration.js
> +      return res.send({ message: body.message });
<img width="1354" alt="Screen Shot 2021-05-24 at 11 58 30" src="https://user-images.githubusercontent.com/59536731/119290467-81d8ad80-bc87-11eb-95f7-73717b360004.png">

2021-05-24 03:12 UTC, yuki-takei requested changes

2021-05-24 03:12 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +      return res.send({ message: body.message });
このメソッドの実装は変えてはいけない。
see: https://api.slack.com/apis/connections/events-api#the-events-api__subscribing-to-event-types__events-api-request-urls__request-url-configuration--verification

2021-05-24 03:12 UTC, yuki-takei requested changes

2021-05-24 03:12 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +        message: 'url verification was successful',
こっちは url_verification に合わせたリクエストを行う。

2021-05-24 04:24 UTC, kaoritokashiki commented
FB修正しました。
<img width="1414" alt="Screen Shot 2021-05-24 at 13 24 20" src="https://user-images.githubusercontent.com/59536731/119296156-64114580-bc93-11eb-997b-9d710169474f.png">

2021-05-24 04:48 UTC, merged

2021-05-24 04:49 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +      logger.error(err);
ここが logger.error だけだと不十分