Imprv/6029 6030 fetch language from browser
weseek/growi pull request #3770
Opened 2021-05-24 03:59 UTC by itizawa

2021-05-24 05:57 UTC, yuki-takei requested changes

2021-05-24 05:57 UTC, yuki-takei commented on src/client/js/util/i18n.js
> +        order: ['userSettingDetector', 'userBrowserDetector'],
localStorage は消してOK、
querystring は使い処ありそうなので残しましょう。

2021-05-24 05:57 UTC, yuki-takei commented on src/client/js/util/i18n.js
> +      return browserLanguageIdMapping[found.find(v => Object.keys(browserLanguageIdMapping).includes(v))];
mapping のためだけにこれだけのコードを追加するのは嫌なので、他の手を考えてください。
i18n.use で、自作の converter 設定できそうではある。

2021-05-24 05:57 UTC, yuki-takei commented on src/client/js/util/i18n.js
> +  en: 'en_US',
alias はここではなく resources/locales 内のファイルに設定したい。

```
import locales from '@root/resource/locales';
```

しているので、locales から alias の map を生成しよう。

2021-05-24 05:57 UTC, yuki-takei commented on src/client/js/components/InstallerForm.jsx
> +    this.setState({ selectedLang: meta });
react-i18next か、あるいは i18next パッケージから取得できないかな？

2021-06-01 07:23 UTC, yuki-takei requested changes

2021-06-01 07:23 UTC, yuki-takei commented on resource/locales/en_US/meta.json
> +  "browserLanguageId":"en"
`aliases: string[]` にしてください

2021-06-01 07:23 UTC, yuki-takei commented on src/client/js/util/LanguageDetectorWrapper.js
> +    });
aliases から locale へのマッピングのデータは、すくなくとも detect メソッドの外で作ってください。なんならクラス外でもよい。

2021-06-01 07:23 UTC, yuki-takei commented on src/client/js/util/LanguageDetectorWrapper.js
> +class LanguageDetectorWrapper {
AliasToLocaleMapper という名前にしてください。

2021-06-01 07:23 UTC, yuki-takei commented on src/client/js/util/LanguageDetectorWrapper.js
> +    this.langDetector.init(services, { order: ['userSettingDetector', 'navigator', 'querystring'] });
この辺りの全ての設定を wrap する存在ではなく、飽くまでも alias を locale に置換する単機能のものにできないかな？

2021-06-01 08:12 UTC, itizawa commented on src/client/js/util/LanguageDetectorWrapper.js
> +    this.langDetector.init(services, { order: ['userSettingDetector', 'navigator', 'querystring'] });
document を調べていたのですが、detection した後に設定言語を置き換えする plugin を実行できるような type は存在しないようです。
そのため、検出を wrap する方向にしました。
https://www.i18next.com/overview/plugins-and-utils#extraction-tools

2021-06-01 08:36 UTC, yuki-takei requested changes

2021-06-01 08:36 UTC, yuki-takei commented on src/client/js/util/AliasToLocaleMapper.js
> +    this.langDetector.init(services, { order: ['userSettingDetector', 'navigator', 'querystring'] });
外側で作成している userSettingDetector がここに入ってくるのはおかしい。

2021-06-01 08:36 UTC, yuki-takei commented on src/client/js/util/AliasToLocaleMapper.js
> +    this.langDetector.init(services, { order: ['userSettingDetector', 'navigator', 'querystring'] });
alias 変換に対応した navigator を自作できないだろうか。(オリジナルコードは少なく、navigator を wrap するようなものとして)

2021-06-01 09:46 UTC, yuki-takei requested changes

2021-06-01 09:46 UTC, yuki-takei commented on src/client/js/util/i18n.js
> +  locale.meta.aliases.forEach((aliase) => {
aliases が null の場合に対応してください。

2021-06-01 09:46 UTC, yuki-takei commented on src/client/js/util/i18n.js
> +      }
ちょっと読みづらい。
`return aliasesMapping[lang] || lang` でいいのでは？

2021-06-01 09:46 UTC, yuki-takei commented on src/client/js/util/i18n.js
> +  locale.meta.aliases.forEach((aliase) => {
あと aliases の単数形は alias.

2021-06-01 09:56 UTC, merged