Imprv/switch display by passing test
weseek/growi pull request #3777
Opened 2021-05-25 03:34 UTC by zahmis

2021-05-25 03:54 UTC, zahmis commented on packages/slack/src/utils/check-communicable.ts
> +const checkSlackScopes = (result: any) => {
scope が適切かを確認するメソッドを新たに作成しました。

slack のscope は testSlackApiServer の result に入っているので、引数に result を使用しています。

2021-05-25 03:54 UTC, zahmis commented on packages/slack/src/utils/check-communicable.ts
> +  if (correctScopes.every(e => slackScopes.includes(e))) {
ここの条件分岐が気になっています。
if 文は throw new Error を入れるべきでしょうか？
```
if (!correctScopes.every(e => slackScopes.includes(e))) {
  throw new Error('Scope error')
}

```

2021-05-25 03:54 UTC, zahmis commented on packages/slack/src/utils/check-communicable.ts
> +export const testToSlack = async(token:string): Promise<void> => {
proxy を使おうが without であろうがやることは同じなので testToSlack と名称を変更しました。

2021-05-25 03:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +          {props.isIntegrationSuccess && props.slackWSNameInWithoutProxy != null && (
テストボタンを押した結果、scope まで通過したら isIntegrationSuccess を true にして ws 名 と導通成功を表示させています。

2021-05-25 03:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const { appContainer, onResetSettings, isIntegrationSuccess } = props;
親 SlackIntegration に isIntegrationSuccess と setIsIntegrationSuccess を持たせています。

2021-05-25 03:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +        isIntegrationSuccess={isIntegrationSuccess}
導通の表示を表すのが` <CustomBotWithoutProxyIntegrationCard />` コンポーネントです。
テストボタン(testConnection()の実行)を支配しているのが
 ```
<CustomBotWithoutProxySettingsAccordion
  {...props}
   activeStep={botInstallationStep.CREATE_BOT}
/>
```
コンポーネントです。

2021-05-25 03:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +      onSetIsIntegrationSuccess(true);
テストボタンを押したときに webClient が実行されて、その度に情報を get してきます。

scope まで確認が取れたら onSetIsIntegrationSuccess を ture にします。

そのときに error が発生した場合に onSetIsIntegrationSuccess をfalse にします。

2021-05-25 03:54 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +      const client = generateWebClient(slackBotToken);
generateWebClient を slack パッケージから読んできました。
今のところ postMessage はここだけで使うので slack パッケージにこの処理を書いていません。

しかし、今後のことを考えて util などの配下に post-message.ts 的なファイルを作成するべきでしょうか？

2021-05-25 13:58 UTC, yuki-takei requested changes

2021-05-25 13:58 UTC, yuki-takei commented on packages/slack/src/utils/check-communicable.ts
> +  if (correctScopes.every(e => slackScopes.includes(e))) {
一旦 every の結果(bool)を変数に入れて、if で判定しよう。
ブロックとしては false の時に throw Error の方が読みやすいね。

2021-05-25 13:58 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +      await testToSlack(token);
try-catch が必要。

2021-05-25 13:58 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +    await testToSlack(token);
try-catch が必要。

2021-05-25 13:58 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +        }
長いので success or not でコンポーネントを分けてください。
ファイルは分ける必要はなく、このファイル内で inner component 的に宣言すればよい。

2021-05-25 13:58 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +      const client = generateWebClient(slackBotToken);
そこまで汎用的なものにする必要はないけれど、
「この URL の GROWI とのテストが成功した」というメッセージにしてほしい。

そしてそれは with proxy と without proxy 両方で使うと思うので、 slack パッケージに共通化する。

2021-05-25 13:58 UTC, yuki-takei commented on packages/slack/src/utils/check-communicable.ts
> +const checkSlackScopes = (result: any) => {
引数の一時変数名が result はおかしい

2021-05-25 13:58 UTC, yuki-takei commented on packages/slack/src/utils/check-communicable.ts
> +  throw new Error('Scope error');
エラーの情報が不親切すぎる

2021-05-26 04:07 UTC, zahmis commented on packages/slack/src/utils/check-communicable.ts
> +  if (!isPassedScopeCheck) {
**fb内容**
一旦 every の結果(bool)を変数に入れて、if で判定しよう。
ブロックとしては false の時に throw Error の方が読みやすいね。

2021-05-26 04:07 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +        {props.isIntegrationSuccess ? <IntegrationSuccess /> : <IntegrationFailed />}
**fb 内容**
長いので success or not でコンポーネントを分けてください。
ファイルは分ける必要はなく、このファイル内で inner component 的に宣言すればよい。


上の方に `<IntegrationSuccess />` と `<IntegrationFailed />` コンポーネントを作成しました。

2021-05-26 04:07 UTC, zahmis commented on packages/slack/src/utils/check-communicable.ts
> +    throw new Error('The scopes is not appropriate. Required scopes is [Rcommands], [team:read], and [chat:write].');
**fb 内容**
エラーの情報が不親切すぎる

ここでは message のみ入れています。
理由は 表示する時に message の部分さえ入れれば適切な形になるからです。
<img width="575" alt="スクリーンショット 2021-05-26 11 26 59" src="https://user-images.githubusercontent.com/57100766/119600997-3529d980-be23-11eb-9eed-095e56bf3b44.png">

2021-05-26 04:11 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +const IntegrationSuccess = () => {
※ 1

2021-05-26 04:11 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +const IntegrationFailed = () => {
※ 2

2021-05-26 08:29 UTC, yuki-takei requested changes

2021-05-26 08:29 UTC, yuki-takei commented on packages/slack/src/utils/check-communicable.ts
> +    throw new Error('The scopes is not appropriate. Required scopes is [Rcommands], [team:read], and [chat:write].');
> Required scopes is [Rcommands], [team:read], and [chat:write].

Required scopes is `['commands', 'team:read', 'chat:write']`

2021-05-26 08:29 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  onSetIsSendTestMessage: PropTypes.func,
この props いらないのでは？必要だとしても名前も違和感。

onHoge という props の命名がどうあるべきかよく考えてください。js標準で用意されているイベントハンドラ(onClick とか)がどういう命名規則でつけられているのか。でないとこの類いの FB が永久になくならない。

2021-05-26 08:29 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +  onSetTestChannel:  PropTypes.func,
この2つの props の用途を名前から想像できない。
onHoge という props の命名がどうあるべきかよく考えてください。js標準で用意されているイベントハンドラ(onClick とか)がどういう命名規則でつけられているのか。でないとこの類いの FB が永久になくならない。

2021-05-26 12:31 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  isIntegrationSuccess: PropTypes.bool,
**fb 内容**
```
この props (onSetIsSendTestMessage) いらないのでは？必要だとしても名前も違和感。
onHoge という props の命名がどうあるべきかよく考えてください。
js標準で用意されているイベントハンドラ(onClick とか)がどういう命名規則でつけられているのか。
でないとこの類いの FB が永久になくならない。
```

再考した結果 、いらなかったです。
理由は 、onSetIsSendTestMessage というものは
`テストボタンをクリックし、成功したらチェックマークの状態にするという func の props` でしたが、
テストボタンをクリックするたびに チェックマークの表示非表示の表現は isIntegrationSuccess で管理すれば良いと思い直しました。

2021-05-26 12:31 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +  testConnection: PropTypes.func,
**fb 内容**
```
この2つの props (ontTestConnection と onSetTestChannel)の用途を名前から想像できない。
onHoge という props の命名がどうあるべきかよく考えてください。
js標準で用意されているイベントハンドラ(onClick とか)がどういう命名規則でつけられているのか。
でないとこの類いの FB が永久になくならない。

```

on の使い方を理解していませんでした。
on という接頭辞をつけるのは **~した時**と理解を改めました。(だから イベントハンドラで使われる)
今回の testConnection は導通を確認する method なので on をつけるのがおかしく、このまま渡しています。

onSetTestChannel を渡したのは 子供の inputTestChannelHandler で状態を変更したかったからです。
しかし、そもそも状態変更関数を 渡して子供で変更するのは良くないですし、on~ をつけて **テスト用にメッセージを送る channel をセットした時** と解釈するのも無理がありました。

状態変更関数を渡すことをやめて、親に 子供の inputTestChannelHanlder を持ってきて、親で状態を管理するように変更しています。
子供に inputTestChannelHandler を渡し、子供の onChange に渡すように変更しました。

2021-05-26 17:16 UTC, yuki-takei requested changes

2021-05-26 17:16 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +  testConnection: PropTypes.func,
## イベントハンドラとは？
イベントハンドラというのは「Aが起きたときにBしてほしい」を設定するもの。

## 今回のケース
「テストが実行された(form が submitされた)時にテスト処理を実行してほしい」になる。
一見Aを命名に使おうがBを命名に使おうがどちらも「テスト」に関わるため違和感がない**かのように見える**。

しかし B を命名に使うのは実は誤り。

## 原則
少なくとも js では、命名は `on(Aが起きる)` となるべき。

極端な例を挙げると、「カラスが鳴いたときに街を爆破する」場合、カラスコンポーネントのイベント名に town や bom を関与させるのはおかしい。

## 結論
よって今回は onTestTriggered または onTestFormSubmitted などが相応しい。

2021-05-27 02:28 UTC, merged