Imprv/gw6067 add accordion when button clicked
weseek/growi pull request #3788
Opened 2021-05-25 14:18 UTC by kaoritokashiki

2021-05-26 05:36 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +          fetchSlackIntegrationData={fetchSlackIntegrationData}
`fetchSlackIntegrationData`をpropsで渡して、子供のコンポーネントで実行させるようにしました。

2021-05-26 08:31 UTC, yuki-takei requested changes

2021-05-26 08:31 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
> +  fetchSlackIntegrationData: PropTypes.func,
onHoge という命名にしてください。

その際、onHoge という props の命名がどうあるべきかよく考えてください。js標準で用意されているイベントハンドラ(onClick とか)がどういう命名規則でつけられているのか。でないとこの類いの FB が永久になくならない。

2021-05-27 02:12 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
> +  fetchSlackIntegrationData: PropTypes.func,
理解しました。

2021-05-27 02:13 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
> +  onClickAddAccordionBtn: PropTypes.func,
アコーディオンを追加するボタンを押した時に、このイベントハンドラが実行されるので
`onClickAddAccordionBtn`としました。

2021-05-27 02:23 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> +  onClickAddSlackWorkspaceBtn: PropTypes.func,
アコーディオンを追加するボタンを押した時に、このイベントハンドラが実行されるので
`onClickAddSlackWorkspaceBtn`としました。

2021-05-27 06:27 UTC, yuki-takei requested changes

2021-05-27 06:27 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> +      onClickAddSlackWorkspaceBtn();
このコンポーネント内部では onClickAddSlackWorkspaceBtn の実行だけでよい。

1. ボタンがクリックされる
2. 親から渡されたイベントハンドラを実行する
    - この中で `PUT /slack-integration-settings/slack-app-integrations`
    - 他のタイプの場合も共通

2021-05-27 06:27 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +          onClickAddSlackWorkspaceBtn={fetchSlackIntegrationData}
fetch ではなく create がいいだろうね。もちろん create 後にデータ取得も必要。

2021-05-27 11:22 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> +      onClickAddSlackWorkspaceBtn();
修正しました。

2021-05-27 11:23 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +          onClickAddSlackWorkspaceBtn={createSlackIntegrationData}
`createSlackIntegrationData`にしました。

2021-05-27 11:42 UTC, kaoritokashiki commented on src/server/routes/apiv3/slack-integration-settings.js
> +  router.put('/slack-app-integrations', loginRequiredStrictly, adminRequired, csrf, async(req, res) => {
swagger も更新しました

2021-05-27 11:48 UTC, yuki-takei requested changes

2021-05-27 11:48 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
> +      await appContainer.apiv3.put('/slack-integration-settings/slack-app-integrations');
ここは仮のコードなら何もしないのが正解

2021-05-27 12:01 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
> +      await appContainer.apiv3.put('/slack-integration-settings/slack-app-integrations');
TODOコメントを残しました。

2021-05-27 12:04 UTC, merged