Imprv/refactor conduction at without proxy
weseek/growi pull request #3814
Opened 2021-05-28 17:23 UTC by zahmis

2021-05-28 17:33 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +        <IntegrationStatus workspaceNames={workspaceNames} isWithoutProxy />
withoutProxy の時はプロキシマークを表示させてはいけないので props で isWithoutProxy を渡します。

2021-05-28 17:33 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/IntegrationStatus.jsx
> +        {isWithoutProxy ? (
without proxy の時と with proxy(official) の時で若干表示に違いが出ます。

isWithoutProxy で分岐させることにしました。

2021-05-28 17:33 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/IntegrationStatus.jsx
> +IntegrationStatus.defaultProps = {
defaultProps で 基本 false にしています。
without の場合だけ true にするようにしました。

2021-05-29 06:20 UTC, yuki-takei requested changes

2021-05-29 06:20 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +          {workspaceNames[0] && (
ここのロジックころころ変わってレビューするのがだるい…
そして workspaceNames の index: 0 が存在するかどうかでの出し分けはナンセンス。

slack で先に相談して。

- 何を判定したいのか(どういうときに出し分けたいのか)
- このコンポーネントへの input として、workspaceNames は必要なのか
    - 本当に必要な時以外、workspaceNames というワークスペース名の配列はいらないはず。(connectionStatuses に token 紐付きで入ってるわけだから)

2021-05-29 06:20 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  });
これほとんどの場合でいらないと思われる。
IntegrationStatus 内のロジックも見たけど workspaceNames いらないと思う。

2021-05-29 06:20 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/IntegrationStatus.jsx
> +              </p>
この辺の要素の重複が気になる

2021-05-29 11:07 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const connectionStatusArray = Object.values(connectionStatuses);
**FB 内容**
```
 const workspaceNameObjects = Object.values(connectionStatuses); 
 const workspaceNames = workspaceNameObjects.map((w) => {    return w.workspaceName;  });
```
これほとんどの場合でいらないと思われる。
IntegrationStatus 内のロジックも見たけど workspaceNames いらないと思う。

**修正点**
workspageNames はいらないと判断しました。
しかし以下は必要だと思っています。
 ```
 const connectionStatusArray = Object.values(connectionStatuses);
 const isConnectedFailed = connectionStatusArray.some(e => e.error);
```

理由は、
token が間違っている際に、isConnectedFailed を元に、Settings #1 を表示させるためです。
もしこれが不要の場合は、`Object.values(connectionStatuses); ` は不要で、connectionStatuses を子供に渡せば良いと思っています。

2021-05-29 11:10 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
> +          {isEmptyconnectionStatusValues ? '' : (
**FB 内容**
ここのロジックころころ変わってレビューするのがだるい…
そして workspaceNames の index: 0 が存在するかどうかでの出し分けはナンセンス。

slack で先に相談して。

何を判定したいのか(どういうときに出し分けたいのか)
このコンポーネントへの input として、workspaceNames は必要なのか
本当に必要な時以外、workspaceNames というワークスペース名の配列はいらないはず。(connectionStatuses に token 紐付きで入ってるわけだから)

**修正点**
- 何を判定したいのか(どういうときに出し分けたいのか)
- 
connectionStatuses の内容を使って判定することにしました。
判定とその結果は以下のようにします。
- token が入っていない状態
  - カードを表示しない 
  - isEmptyConnectionStatusValues を作成し、これで判断する。
- token が入っているが間違っている場合
  - カードを表示するが、ws 名は Setting #1 とする
  - isConnectedFailed を作成し、これで判断する。
- token が入っていて正解の場合
  - カードと ws 名を表示する  

- このコンポーネントへの input として、workspaceNames は必要なのか
workspaceName はこのコンポーネントへの input として不適だと考えました。
このコンポーネントの責務は、**カードを表示することと、内包する IntegraitonStatus に必要な情報を渡すこと**。
確かに workspaceNames は必要ですが、表示を判断するのは workspaceName の有無ではなく、connectionStatuses の責務だと考えました。

2021-05-29 11:10 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const connectionStatusValues = Object.values(connectionStatuses);
**FB 内容**
```
 const workspaceNameObjects = Object.values(connectionStatuses); 
 const workspaceNames = workspaceNameObjects.map((w) => {    return w.workspaceName;  });
```
これほとんどの場合でいらないと思われる。
IntegrationStatus 内のロジックも見たけど workspaceNames いらないと思う。

**修正点**
workspageNames はいらないと判断しました。
しかし以下は必要だと思っています。
 ```
 const connectionStatusArray = Object.values(connectionStatuses);
 const isConnectedFailed = connectionStatusArray.some(e => e.error);
```

理由は、
token が間違っている際に、isConnectedFailed を元に、Settings #1 を表示させるためです。
もしこれが不要の場合は、`Object.values(connectionStatuses); ` は不要で、connectionStatuses を子供に渡せば良いと思っています。

2021-05-29 11:12 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/IntegrationStatus.jsx
> +              </p>
<ProxyCircle /> を内部に作成しました

2021-05-29 11:38 UTC, yuki-takei requested changes

2021-05-29 11:38 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const isConnectedFailed = connectionStatusValues.some(e => e.error);
e.error は boolean ではないので、some の内部の判定式としてこのような書き方をしてはいけない

2021-05-30 22:54 UTC, merged