Feat/5907 6185 imprv accordion header
weseek/growi pull request #3830
Opened 2021-06-01 06:57 UTC by itizawa

2021-06-01 07:00 UTC, itizawa commented on src/server/routes/apiv3/slack-integration-settings.js
> +
slackAppIntegration の特定のために token を保存するようにしました

2021-06-01 07:40 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +
これはNG。

with proxy に於いては、bot token の保持は proxy の責務。

2021-06-01 07:41 UTC, yuki-takei requested changes

2021-06-01 07:41 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> +                </h2>
こっちも CustomBotWithoutProxySettings みたいな変更に寄せた方がいいんじゃないかな？

むしろ OfficialBotSettings は CustomBotWithoutProxySettings の wrapper みたいな感じに簡素化できないのかなと思っているが…まあそのリファクタは後続タスクでよい。

2021-06-03 02:26 UTC, itizawa commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> +                </h2>
## 問題点
- connectionStatuses の value の特定をするのに slackBotToken を使っている
  - without は DB or env で設定する slackBotToken  を用いる
  - with は slackBotToken を Proxy が持つため特定の方法がない

## 解決策
- connectionStatuses: {[key:string]: {error?: Error, workspaceName?: string,}} であることを踏まえ以下の方法を検討した
  - connectionStatuses を受け取ったGROWIサーバーが key に 紐づく slackAppIntegration をセットしてクライアントに返す
  - クライアントでは、 with Proxy の場合に accordion 毎に存在する slackAppIntegration の id を用い workspace を表示、なければ番号を表示する

2021-06-03 02:27 UTC, itizawa commented on src/server/routes/apiv3/slack-integration-settings.js
> +            });
## 問題点
- connectionStatuses の value の特定をするのに slackBotToken を使っている
  - without は DB or env で設定する slackBotToken  を用いる
  - with は slackBotToken を Proxy が持つため value 特定の方法がない

## 解決策
- connectionStatuses: {[key:string]: {error?: Error, workspaceName?: string,}} であることを踏まえ以下の方法を検討した
  - connectionStatuses を受け取ったGROWIサーバーが key に 紐づく slackAppIntegration をセットしてクライアントに返す
  - クライアントでは、 with Proxy の場合に accordion 毎に存在する slackAppIntegration の id を用い workspace を表示、なければ番号を表示する

2021-06-03 02:35 UTC, itizawa commented on src/server/routes/apiv3/slack-integration-settings.js
> +            });
これだと、tokenGtoPs と Object.values(result.connectionStatuses) の順番が同じでないと正常動作しないという問題点がありそうです

2021-06-03 08:10 UTC, yuki-takei requested changes

2021-06-03 08:10 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +            });
`ckeck-communicable.ts` の `getConnectionStatuses` を改修しよう。

## 現状

`export const getConnectionStatuses = async(tokens: string[]): Promise<{[key: string]: ConnectionStatus}> => {`

## 改修後
- 引数を、`keys: string[], botTokenResolver?: (key: string) => string` に変える
- without proxy の場合
    - 第一引数のみ指定、keys をそのまま従来の tokens として扱う
- with proxy の場合
    - 第二引数に closure をセット、第一引数の key から bot token に当たるものを解決し、generateWebClient に渡す
    - ただし返り値の key は keys 通り

2021-06-03 13:06 UTC, merged