Fix/input form of secret and token
weseek/growi pull request #3838
Opened 2021-06-01 13:37 UTC by zahmis

2021-06-01 13:51 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySecretTokenSection.jsx
> +  useEffect(() => {
すでに登録されている場合、入力画面に登録された値が入るようにしています。

2021-06-01 13:51 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> -  isRgisterSlackCredentials: PropTypes.bool,
不要なので消去

2021-06-01 13:51 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> -  slackWSNameInWithoutProxy: PropTypes.string,
不要なので消去

2021-06-01 13:51 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> -  const onChangeSigningSecretHandler = (signingSecretInput) => {
不要なので消去

2021-06-01 13:51 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +          onUpdatedSecretToken={changeSecretAndToken}
CustomBotWithoutProxySecretTokenSection の `updatedSecretToken` で `onUpdatedSecretToken `を使います。

2021-06-01 13:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +        title={<><span className="mr-2">③</span>{t('admin:slack_integration.accordion.register_secret_and_token')}{isEnterdSecretAndToken && <i className="ml-3 text-success fa fa-check"></i>}</>}
`GW-6126 secret token を登録すると チェックマークを表示する` の主な実装はこちらです。

2021-06-01 13:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +  if ((slackSigningSecret != null && slackBotToken != null) || (slackSigningSecretEnv != null && slackBotTokenEnv != null)) {
`GW-6126 secret token を登録すると チェックマークを表示する` の主な実装はこちらです。

2021-06-01 13:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySecretTokenSection.jsx
> +  const [inputSigningSecret, setInputSigningSecret] = useState(null);
入力した値を一時的に保持する state を作成。

2021-06-01 16:09 UTC, yuki-takei requested changes

2021-06-01 16:09 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySecretTokenSection.jsx
> +  useEffect(() => {
useState の初期値ではだめなの？

2021-06-01 16:09 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySecretTokenSection.jsx
> +      onUpdatedSecretToken(inputSigningSecret, inputBotToken);
onUpdatedSecretToken が not null の場合に呼び出すべき。
今のコードでは onUpdatedSecretToken が指定されているかどうかによって toastSuccess のスキップが発生する。

2021-06-01 16:09 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +  if ((slackSigningSecret != null && slackBotToken != null) || (slackSigningSecretEnv != null && slackBotTokenEnv != null)) {
`((slackSigningSecret != null || slackSigningSecretEnv  != null) && (slackBotToken != null || slackBotTokenEnv != null))`
が適切だと思う。

2021-06-03 01:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySecretTokenSection.jsx
> +      onUpdatedSecretToken(inputSigningSecret, inputBotToken);
なるほど。
修正します。

2021-06-03 01:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySecretTokenSection.jsx
> +  useEffect(() => {
それやってみたんですが、だめそうでした。
`const [inputSigningSecret, setInputSigningSecret] = useState(slackSigningSecret)` とした場合、
最初に null が set されるので表示されません。
なので useEffect を使用しています。

2021-06-03 01:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySecretTokenSection.jsx
> +  useEffect(() => {
やってみた実装
```:js
const CustomBotWithoutProxySecretTokenSection = (props) => {
  const {
    appContainer, slackSigningSecret, slackBotToken, slackSigningSecretEnv, slackBotTokenEnv, onUpdatedSecretToken,
  } = props;

  const [inputSigningSecret, setInputSigningSecret] = useState(slackSigningSecret);
  ...
  console.log(slackSigningSecret);
   ...

  const updatedSecretToken = async() => {
    try {
...
   }

  // useEffect(() => {
  //   setInputSigningSecret(slackSigningSecret);
  //   setInputBotToken(slackBotToken);
  // }, [slackSigningSecret, slackBotToken]);
```

2021-06-03 01:54 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +  if ((slackSigningSecret != null && slackBotToken != null) || (slackSigningSecretEnv != null && slackBotTokenEnv != null)) {
修正します。

2021-06-03 07:38 UTC, yuki-takei requested changes

2021-06-03 07:38 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySecretTokenSection.jsx
> +  useEffect(() => {
> それやってみたんですが、だめそうでした。
> const [inputSigningSecret, setInputSigningSecret] = useState(slackSigningSecret) とした場合、
> 最初に null が set されるので表示されません。

これどういうことなんだろう。今 PR 投げてくれている
```
const [inputSigningSecret, setInputSigningSecret] = useState(null);
```
でも、初期値 null だよね？しかも使う側 `value={inputSigningSecret || ''}` だから、null なら空文字列が入る。

2021-06-04 04:59 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySecretTokenSection.jsx
> +  useEffect(() => {
`const [inputSigningSecret, setInputSigningSecret] = useState(null);` で最初 `null` を入れて空文字列が入ります。

slackSigningSecret の初期値は null です。
しかし、SlackIntegration コンポーネント内にある fetchSlackIntegrationData  が発火することで slackSigningSecret の値が入ります。
useEffect を使い、その瞬間を察知して <CustomBotWithoutProxySecretTokenSection> コンポーネントをレンダリングをしなおした結果、inputSigningSecret に値が入ると思っています。

2021-06-04 15:26 UTC, merged