Fix/6034 6232 create 404 page blow admin
weseek/growi pull request #3846
Opened 2021-06-03 06:37 UTC by itizawa

![スクリーンショット 2021-06-03 15 37 18](https://user-images.githubusercontent.com/48426654/120598729-97b55200-c481-11eb-893f-39158f8a4184.png)

2021-06-03 12:58 UTC, yuki-takei requested changes

2021-06-03 12:58 UTC, yuki-takei commented on src/server/views/admin/not_found.html
> +<h1 class="title">{{ t('not_found_page.page_not_exist') }}</h1>
このメッセージはタイトルじゃなくてコンテンツ部の方に出してほしいな

タイトルは何を入れたらいいのか、はちょっと思いつかないんだけど、空文字列でいいのかどうか…

2021-06-03 12:58 UTC, yuki-takei commented on src/server/views/admin/not_found.html
> +{% block html_title %}{{ customizeService.generateCustomTitleForFixedPageName(t('Import Data')) }}{% endblock %}
Import Data は変じゃない？

2021-06-04 03:16 UTC, itizawa commented
![スクリーンショット 2021-06-04 12 15 12](https://user-images.githubusercontent.com/48426654/120740658-955d0180-c52e-11eb-880e-7e1dde08eac5.png)

content_header に指定する必要はなさそうなので消しました

2021-06-04 08:58 UTC, merged