Imprv/gw6162 delete accordons in official bot
weseek/growi pull request #3862
Opened 2021-06-07 01:22 UTC by kaoritokashiki

2021-06-07 04:30 UTC, yuki-takei requested changes

2021-06-07 04:30 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +          fetchSlackIntegrationData={fetchSlackIntegrationData}
[/Tips/JavaScript/命名規則#イベントハンドラ](https://tips.weseek.co.jp/60ae84d41091010049bed55d#イベントハンドラ)

2021-06-07 04:30 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +          fetchSlackIntegrationData={fetchSlackIntegrationData}
CustomBotWithProxySettings の方も直して

2021-06-08 02:19 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +          fetchSlackIntegrationData={fetchSlackIntegrationData}
`onClickDeleteSlackAppIntegrationBtn`に修正しました。

2021-06-08 03:17 UTC, yuki-takei requested changes

2021-06-08 03:17 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> +  const fetchSlackIntegrationData = () => {
このメソッド消そう

2021-06-08 03:17 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> +      fetchSlackIntegrationData();
ここに onClickDeleteSlackAppIntegrationBtn を書くとすると、「ボタンがクリックされたイベント」ではないよね。「削除されたイベント」のはず。名前を体に揃えてください。

2021-06-08 05:05 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
> +      }
`fetchSlackIntegrationData()`メソッドを削除して、`deleteSlackAppIntegrationHandler`の中で`props.onDeleteSlackAppIntegration();`を実行させました。

2021-06-08 05:05 UTC, kaoritokashiki commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> +      fetchSlackIntegrationData();
確かに....`onDeleteSlackAppIntegration`に修正しました。

2021-06-08 05:49 UTC, merged