Imprv/add test log every test
weseek/growi pull request #3863
Opened 2021-06-07 07:28 UTC by zahmis

2021-06-07 07:34 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +    if (connectionMessage == null) {
初期状態が null です。
なので最初の log 表示では null と表示されてしまいます。
その場合は newLog のみを表示するようにしています。

2021-06-07 16:18 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> -  const [isIntegrationSuccess, setIsIntegrationSuccess] = useState(false);
この state 不要につき削除

2021-06-07 16:18 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +        title={<><span className="mr-2">④</span>{t('admin:slack_integration.accordion.test_connection')}{connectionMessage === '' && <i className="ml-3 text-success fa fa-check"></i>}</>}
connectionMessage で判別

2021-06-08 19:29 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const [isLatestConnectionSuccess, setIsLatestConnectionSuccess] = useState(false);
with proxy のやり方を踏襲しています。

- islatestConnectionSuccess
- latestConnectionMessage
- testConnection
- inputTestChannelHandler
これらを ~~Settings コンポーネントにもたす意味がないと思えてきました。
test を行うのは accordion コンポーネントなので それに伴って必要な state と method をまとめて アコーディオンコンポーネントに移行しようと思っているのですが、良いでしょうか？
よければ 後続タスクでリファクタします。

2021-06-08 19:42 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +  let logsValue = null;
後続タスクでリファクタをする際に useState を適用しようと思っています。

testConnection method 内で state を変更することにより、表示をかえる予定です。

2021-06-08 19:42 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +                value={logsValue || ''}
textarea は null を許容しないため || '' としています。

2021-06-09 08:44 UTC, yuki-takei requested changes

2021-06-09 08:44 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +                value={logsValue || ''}
logsValue の初期値を空文字列にすればいいのでは？

2021-06-09 08:44 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +    logsValue = latestConnectionMessage;
addLogs を用いて latestConnectionMessage が logsValue に追加されるようにしてください。

2021-06-09 08:44 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +    logsValue = null;
通信成功のメッセージが logsValue に追加されるようにしてください。

2021-06-09 08:44 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> +  const [isLatestConnectionSuccess, setIsLatestConnectionSuccess] = useState(false);
今回 FB したように addLogs 利用箇所の改修も必要なので、後続タスクではなくこのタスクのスコープでリファクタしてください。

2021-06-09 17:11 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
> -          {...props}
...props をやめました。
理由はなにを渡しているかが不透明だからです。

2021-06-09 17:11 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +  const [logsValue, setLogsValue] = useState('');
logsValue は string で統一します。

2021-06-09 17:11 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> -  const [isRegisterSlackCredentials, setIsRegisterSlackCredentials] = useState(false);
不要物削除

2021-06-09 17:11 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> -      setIsRegisterSlackCredentials(false);
不要物削除

2021-06-09 17:11 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> -          isRegisterSlackCredentials={isRegisterSlackCredentials}
不要物削除

2021-06-09 17:19 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +        onTestConnectionInvoked();
FB 内容
> addLogs を用いて latestConnectionMessage が logsValue に追加されるようにしてください。

logsValue という state を用意しました。
addLogs で取得した log を set しています。

addLogs の引数 `addLogs(log, newLogMessage, newLogCode)`

2021-06-10 10:01 UTC, merged