Imprv/apply add logs at with proxy
weseek/growi pull request #3876
Opened 2021-06-09 02:38 UTC by zahmis

2021-06-09 02:46 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> -  let logsValue = null;
これ不要でした。
setLatestConnectionMessage で判断します。

2021-06-09 08:47 UTC, yuki-takei requested changes

2021-06-09 08:47 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> +      setLatestConnectionMessage(addLogs(latestConnectionMessage, error[0].code, error[0].message));
ここなんかおかしい。latestConnectionMessage は、最後に行ったテスト結果(1回分)のメッセージ。

2021-06-09 08:47 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> +              value={latestConnectionMessage || ''}
latestConnectionMessage の初期値を空文字列にしてください

2021-06-10 06:03 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> +  const [logsValue, setLogsValue] = useState('');
latestConnectionMessage をやめ、logsValue に変更。
logsValue は string  でと統一。

2021-06-10 06:03 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> +  const successMessage = 'Successfully sent to Slack workspace.';
成功メッセージは固定

2021-06-10 06:04 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> +      setLatestConnectionMessage(addLogs(latestConnectionMessage, error[0].code, error[0].message));
👀

2021-06-10 06:05 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> +              value={latestConnectionMessage || ''}
logsValue にしています。
logsValue の初期値を '' にしました。

2021-06-10 12:11 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> +      <MessageBasedOnConnection isLatestConnectionSuccess={isLatestConnectionSuccess} logsValue={logsValue} />
MessageBasedOnConnection、似たようなのが複数の jsx にあるよね？後続タスクで共通化してほしい。

2021-06-10 12:11 UTC, yuki-takei approved these changes

2021-06-10 12:11 UTC, merged