Imprv/gw6231 add url validation to register modal
weseek/growi pull request #3883
Opened 2021-06-10 12:28 UTC by kaoritokashiki

2021-06-10 13:09 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +    };
slack のmodal では、inputの前後に空白を入れたとしても勝手にtrimされるのでその処理は入れていません。

2021-06-10 13:12 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +  ): Promise<any> {
ここを定義するとなると
void もしくは
```
{
        response_action: 'errors',
        errors: {
          growiUrl: 'Please enter a valid URL',
        },
      };
```
となりますが`<void | object>`は使えないので、厳密に定義する必要があれば修正します。

2021-06-10 13:31 UTC, yuki-takei requested changes

2021-06-10 13:31 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +    };
string の match で判断するのではなく、URL インスタンスを作ってエラーが発生するかどうかを見てください

https://developer.mozilla.org/ja/docs/Web/API/URL/URL

2021-06-10 13:31 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +      }
## やりたいこと
res.send を早くしたい(installation の存在チェックは非同期通信なので、サーバー負荷に応じて遅くなる可能性がある)

## 実装方法の変更
https://api.slack.com/surfaces/modals/using#displaying_errors のような処理の実装は諦め、エラーは RegisterService が postEphemeralMessage することで知らせる

2021-06-10 14:14 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/controllers/slack.ts
> +      }
postEphemeralMessageに変更しました。
<img width="521" alt="Screen Shot 2021-06-10 at 23 06 35" src="https://user-images.githubusercontent.com/59536731/121540600-949e0100-ca41-11eb-9fb4-c5ed00f8f7ba.png">

2021-06-10 17:48 UTC, yuki-takei requested changes

2021-06-10 17:48 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +      }
サービス側では throw error してください。
こちら側は catch したら logger に出力して return。

2021-06-10 17:48 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +  ): Promise<any> {
errors を返す必要はないので void に戻す

2021-06-10 17:48 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +    };
このメソッドをここで定義する意味はあまりなく、catch 内に入れた方が読みやすい。

```
try {
  url = new URL()
}
catch (error) {
  logger.error(error)
  client.chat.postEphemeral()
  throw new CustomError(error)
}
```

ts のカスタム例外については
https://qiita.com/shibukawa/items/ffe7264ecff78f55b296

2021-06-11 06:15 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +      throw new InvalidUrlError('Invalid URL', error);
![Uploading Screen Shot 2021-06-11 at 15.13.22.png…]()

2021-06-11 06:16 UTC, kaoritokashiki commented on packages/slack/src/models/errors.ts
> +export class InvalidGrowiCommandError extends ExtensibleCustomError {}
<img width="613" alt="Screen Shot 2021-06-11 at 15 15 19" src="https://user-images.githubusercontent.com/59536731/121639737-f30dc280-cac7-11eb-9991-cf12959b22f1.png">

2021-06-11 06:20 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +    };
`extensible-custom-error` を`packages/slack`と`packages/slackbot-proxy`でインストールしました。

2021-06-11 06:33 UTC, yuki-takei requested changes

2021-06-11 06:33 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +      authorizeResult:AuthorizeResult, payload: any,
AuthorizeResult 型ではなく botToken を渡すべきかな

2021-06-11 06:33 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +      throw new InvalidUrlError('Invalid URL', error);
システム側のエラーというよりユーザー入力が不正なだけなので、やっぱり `logger.info` に変更してください。stack trace も不要なので、第二引数は入力された文字列を表示するために `{ growiUrl }` を渡すだけで構わない。

2021-06-11 06:33 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +    const postInvalidUrlErr = async() => {
lint warn 出てるよね。assigned a value but never used.

2021-06-11 06:33 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +      authorizeResult:AuthorizeResult, payload: any,
notifyServerUriToSlack も同様かも。

2021-06-11 07:18 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +      authorizeResult:AuthorizeResult, payload: any,
確かにそうですね、気づきませんでした。修正しました。

2021-06-11 08:21 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +    const postInvalidUrlErr = async() => {
失礼しました。このメソッドは削除しました。

2021-06-11 08:34 UTC, kaoritokashiki commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +      throw new InvalidUrlError(`'${growiUrl}' is an invalid URL`, error);
`${growiUrl}`msgに追加しました。

2021-06-11 09:14 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +          logger.info(err);
ここの出力を簡潔にする(stack trace いらない)

2021-06-11 09:14 UTC, yuki-takei commented on packages/slackbot-proxy/src/models/errors.ts
> +export class InvalidUrlError extends ExtensibleCustomError {}
constructor で super() を呼んで、message は固定にしよう。引数に取るのは growiUrl だけでよい。
InvalidGrowiCommandError と違って、発生するケースは限定的なので。

2021-06-11 11:04 UTC, merged