Feat/6285 6286 response growi url
weseek/growi pull request #3899
Opened 2021-06-17 05:04 UTC by itizawa

2021-06-17 07:52 UTC, yuki-takei requested changes

2021-06-17 07:52 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    let relations = await this.relationRepository.find({ installation });
interaction は必ず連携先の GROWI が確定してるはずなので、private_metadata の parse を先にやって、installation と growiUri の組みで installation を find する。見つからなければ 400。

2021-06-17 11:41 UTC, itizawa commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +    return opt;
困っていること
proxy がurlをセットしておける private_metadata にあたるものが、Modal ではない interaction では存在していない。

2021-06-17 12:46 UTC, yuki-takei requested changes

2021-06-17 12:46 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    }
- middleware 化してください
- middleware は view の有無とか type が何かを判断しない
- middleware から呼ぶ delegator などが extract してくれる
    - 一つでも growiUri あったよ！って言ってくれたら extract 完了

2021-06-17 12:46 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +    return opt;
こちらは middleware にはならないが、カプセル化する。つまり modal の処理を請け負うモジュールのユーティリティが inject してくれるように。

2021-06-18 03:51 UTC, yuki-takei requested changes

2021-06-18 03:51 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/growi-uri-injector/index.ts
> +  }
インスタンス化はここでやりたい

2021-06-18 03:51 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/growi-uri-injector/index.ts
> +export const DelegatorType = {
複数形に

2021-06-18 03:51 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/growi-uri-injector/index.ts
> +export const factory = new GrowiUriInjectorFactory();
index.ts ではなく、それぞれ相応しいモジュールに分解。
index は作るとしたら export するだけの存在にしよう。今回は他パッケージから参照しないし、作らなくていいと思う。

2021-06-18 03:51 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/growi-uri-injector/GrowiUriInjectionModalDelegator.ts
> +    parsedView.private_metadata = JSON.stringify({ growiUri });
private_metadata が既にセットされていても(また、どんなデータが入っていても)対応できるようにしたい。
パケットみたいにマトリョーシカ構造にしては？

```
const originalPrivateMetadata = JSON.stringify(parsedView.private_metadata);
private_metadata = JSON.stringify({
  growiUri,
  originalPrivateMetadata,
};
```

2021-06-18 03:51 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/growi-uri-injector/GrowiUriInjectionModalDelegator.ts
> +  extract(body: any): string|void {
返り値はマトリョーシカを展開した型、つまり growiUri: string と originalPrivateMetadata の parse されたものになる。

2021-06-18 03:51 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/growi-uri-injector/GrowiUriInjectionButtonDelegator.ts
> +export class GrowiUriInjectionButtonDelegator implements GrowiUriInjector {
button 以外のコンポーネント、例えば select とかでもう一種類作ってみて。そうすると [block_actions payloads グループ](https://api.slack.com/reference/interaction-payloads/block-actions) に対して共通化できる部分が見えると思う。
(ただ、そのまえに GrowiUriInjectionModalDelegator.ts でFBしてるマトリョーシカ構造化を先にやった方がいい)

2021-06-18 03:51 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/growi-uri-injector/GrowiUriInjectionModalDelegator.ts
> +export class GrowiUriInjectionModalDelegator implements GrowiUriInjector {
こちらは [View interaction payloads グループ](https://api.slack.com/reference/interaction-payloads/views) だが、まあ view_submission タイプしか取り扱わないだろうとは思うので共通化の必要はあまりない。

2021-06-21 08:43 UTC, yuki-takei requested changes

2021-06-21 08:43 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +            const growiUriInjector = growiUriInjectorFactory[type]();
この iteration ここは読みにくいなあ。簡素化してほしい。

## 使う側
ある block に対して injectors.find で handleInject が true を返すものは、最大で1つ見つかる。
それを使って handle/extract すればよい。

2021-06-21 11:34 UTC, itizawa commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +        });
growiUriInjector を type を元に見つけてくる。なければ inject しない

2021-06-21 12:24 UTC, itizawa commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +        });
type が存在する場合のみ inject する

2021-06-21 12:43 UTC, yuki-takei requested changes

2021-06-21 12:43 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +          const growiUriInjector = growiUriInjectorFactory[element.type]();
このコードは疑念を持ってしまう。`growiUriInjectorFactory[element.type]` が not null であるという保証がない。(GrowiUriInjectorFactory のコードを見に行けばわかるが、その保証も GrowiUriInjectorFactory 側の実装次第である)

2021-06-21 12:52 UTC, itizawa commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +          }
type で find あれば実行

2021-06-21 13:00 UTC, yuki-takei requested changes

2021-06-21 13:01 UTC, yuki-takei requested changes

2021-06-21 13:01 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/growi-uri-injector/GrowiUriInjectorFactory.ts
> +};
DelegatorTypes に何かを追加したら growiUriInjectorFactory にも同様の key に対応する value を追加しないと、findInjectorByType で undefined 参照になってしまう。

2021-06-21 13:17 UTC, itizawa commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +          }
各 element に inject するため問題ないのでは

2021-06-21 13:18 UTC, itizawa commented on packages/slackbot-proxy/src/services/growi-uri-injector/GrowiUriInjectorFactory.ts
> +};
growiUriInjectorFactory の key を見るようにしました

2021-06-21 13:34 UTC, merged