Fix/not delete proxy url
weseek/growi pull request #3905
Opened 2021-06-18 22:19 UTC by zahmis

2021-06-18 22:25 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +    const params = {
delete を実行する際に proxy-uri をリセットする操作を追加しています。
resetAllBotSettings は諸々削除してしまうので、部分的に proxy-uri だけを null にする仕様にしています。

2021-06-21 08:19 UTC, yuki-takei requested changes

2021-06-21 08:19 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration-settings.js
> +    const params = {
ボットタイプ変更と all reset 時に消すべき

2021-06-21 08:40 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +    const params = {
理解しました。

2021-06-21 11:37 UTC, yuki-takei requested changes

2021-06-21 11:37 UTC, yuki-takei commented on src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
> +    setNewProxyServerUri(proxyServerUri);
23行目の上に `// componentDidUpdate` とコメント追加してください。
OfficialBotSettings.jsx も同様。

2021-06-21 11:43 UTC, merged