wip path
weseek/growi pull request #3908
Opened 2021-06-22 03:24 UTC by stevenfukase

2021-06-23 06:42 UTC, itizawa commented on src/client/js/components/PageCreateModal.jsx
> +  function joinAndRedirect(...path) {
editor に遷移することが 関数名からわかる方が良さそうです

2021-06-23 06:42 UTC, itizawa commented on src/client/js/components/PageCreateModal.jsx
> +  function joinAndRedirect(...path) {
path は複数形で paths ですかね

2021-06-23 06:42 UTC, itizawa commented on src/client/js/components/PageCreateModal.jsx
> +  function joinAndRedirect(...path) {
templateModal も editor に遷移するような処理があるので path-util にあってもいいのかもしれないですね...

2021-06-24 03:34 UTC, stevenfukase commented on src/client/js/components/PagePathAutoComplete.jsx
> +      behaviorOfResetBtn="clear"
[**「GW-6429 New PageのModalのクリアボタンが押せないバグを修正」**](https://youtrack.weseek.co.jp/agiles/84-39/current?issue=GW-6429)対応箇所
`emptyLabelExceptError={null}`はdeprecatedでエラーが出てました。
SearchTypeaheadのResetボタンの挙動として、`clear`と`reset`がありますが、`reset`が上手く機能してないので`clear`にしました。

2021-06-24 03:41 UTC, stevenfukase commented on src/client/js/components/PageCreateModal.jsx
> +    try {
Utilからtoastを呼び出すのはどうかなー、と思いこういう書き方にしました

2021-06-24 03:50 UTC, itizawa commented on src/lib/util/path-utils.js
> +  }
`isCreatablePage` を util がチェックしてエラーを投げると、`joinAndRedirectToEditor` を使う側は毎回エラーを想定して try catch しないといけなくなってしまいます。

なので、`isCreatablePage` は使う側で先にチェックして util は `#edit` を末尾につけて返すだけの関数にした方が良さそうです。

2021-06-24 05:01 UTC, stevenfukase commented on src/client/js/components/PageCreateModal.jsx
> +
DRY(Don't Repeat Yourself)に基づいてこちらに3箇所の処理をまとめました。

2021-06-24 05:04 UTC, itizawa approved these changes

2021-06-24 06:16 UTC, yuki-takei requested changes

2021-06-24 06:16 UTC, yuki-takei commented on src/lib/util/path-utils.js
> +}
urljoin はとても簡易なユーティリティなので、極力今後利用する箇所は減らして行きたい。というのは、基本文字列操作を行っているので、path に入ってくる文字列によっては望みの挙動にはならない可能性がある。例えば  query や hash が含まれていたらどうなるかがよくわからない。

https://github.com/jfromaniello/url-join

path-utils は共通化されたモジュールとしてもっときちんとした動作をさせたいので、以下のどちらかの対策を行ってください。両方やれたらベスト。

- URL module を使う
- テストを追加して、path に query や hash が含まれていても望みの挙動になることを確認する

2021-06-24 06:16 UTC, yuki-takei commented on src/client/js/components/PageCreateModal.jsx
> +  function joinCheckRedirect(...paths) {
メソッド名が join と check と redirect という3つの動詞からなっていて、何をするメソッドなのかよくわからない。名が体を表すように改名してください。

2021-06-24 06:16 UTC, yuki-takei commented on src/client/js/components/PageCreateModal.jsx
> +    const joinedUrl = encodeURI(urljoin(...paths));
こちらもできれば urljoin の利用はやめたいが、今回は必須にはしない。

2021-06-28 11:27 UTC, yuki-takei requested changes

2021-06-28 11:27 UTC, yuki-takei commented on src/client/js/components/PageCreateModal.jsx
> +      .map(str => str.replace(/^\/+|\/+$|\s/g, ''))
- そもそもこの機能は path-utils に実装した方がいいような気はする
- あと実装方法、なぜ文字列操作？最初から URL つかえばいいのでは？
- 元々あった encodeURI の処理なくなってるけど大丈夫？

2021-06-29 02:25 UTC, stevenfukase commented on src/lib/util/path-utils.js
> +
- 文字列操作は最低限の`.join('/')`のみにしました。
- URLからはencodeされた値が帰ってくるので、encodeURIは外しました。
- Encodeしてから`isCreatablePage()`を通すと`%`等で引っかかるので、Encodeする前に通してます。

2021-06-29 11:22 UTC, merged