Feat/6285 6287 display modal for select growi
weseek/growi pull request #3910
Opened 2021-06-22 06:21 UTC by itizawa

2021-06-22 06:29 UTC, itizawa commented on src/server/service/slackbot.js
> +        text: `The page <${decodeURI(`${growiUri}/${page._id} | ${decodeURI(growiUri + path)}`)}> has been created.`,
表示が逆になっていたので修正

2021-06-22 08:28 UTC, yuki-takei requested changes

2021-06-22 08:28 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/SelectRequestService.ts
> +    const client = new WebClient(botToken, { logLevel: isProduction ? LogLevel.DEBUG : LogLevel.INFO });
generateWebClient を使って

2021-06-22 08:28 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    }
## 最終形態
1. relation に、各 GROWI の対応可能コマンドを記録する
    - broadcastCommands: string[] と singlePostCommands: string[] の array を持つ
    - キャッシュ的な持ち方をする(expire したらまた当該 GROWI から取得し直す)
2. ここの `singlePostCommands.includes` は、全 GROWI から集めた singlePostCommands にひっかかるものがあるか？を見るようにする

## 現時点で到達すべきマイルストーン

- relation.siglePostCommands を実装するが、静的に `['create']` を返すようにする
- 2 のロジックはこのタスクで実装し、1に関しては後続ストーリーを作る

2021-06-22 08:28 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/SelectRequestService.ts
> +  async forwardRequest(relationRepository:RelationRepository, installation:Installation | undefined, payload:any):Promise<void> {
このメソッド、slack.ts でやってるコードと重複するよね。共通化を。(後続タスクでもよい)

2021-06-23 11:15 UTC, itizawa commented on packages/slackbot-proxy/src/services/SelectRequestService.ts
> +  async forwardRequest(relationRepository:RelationRepository, installation:Installation | undefined, payload:any):Promise<void> {
このメソッドでやっていること

- slash コマンド時の情報を privateMetadata から取り出してセットする
- triggerId を更新する
- proxied/command でリクエストをフォワードする

slack.ts でやってることと結構違うと思いますが、共通化したほうが良いのでしょうか。

2021-06-23 12:47 UTC, yuki-takei requested changes

2021-06-23 12:47 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/SelectRequestService.ts
> +  async forwardRequest(relationRepository:RelationRepository, installation:Installation | undefined, payload:any):Promise<void> {
考えてみて。
少なくとも `/_api/v3/slack-integration/proxied/commands` をたたく、forward するという挙動は重複する。
あと postEphemeralErrors はなんのためにやっているのか。

2021-06-23 12:47 UTC, yuki-takei approved these changes

2021-06-23 12:52 UTC, merged