Imprv/gw 6474 6431 update endpoints
weseek/growi pull request #3928
Opened 2021-06-24 14:00 UTC by miya

## タスク
- [GW-6474](https://youtrack.weseek.co.jp/agiles/84-39/current?issue=GW-6474) users/invite エンドポイントの修正
- [GW-6431](https://youtrack.weseek.co.jp/agiles/84-39/current?issue=GW-6431)メール送信に失敗した場合、適切なエラーメッセージを管理者に返す]

##  概要
- `/users/invite` の修正を行いました。ユーザー作成プロセスと招待メールの送信プロセスを分け、ユーザーの作成成功かつメールの送信に失敗した場合は作成したユーザーをフロントに渡すようにしました。
- メールの送信に失敗した場合は `Failed to send mail` というメッセージを返すようにしました。

2021-06-24 17:49 UTC, yuki-takei requested changes

2021-06-24 17:49 UTC, yuki-takei commented on src/server/models/user.js
> +  userSchema.statics.createUsersByInvitation = async function(emailList) {
このメソッド廃止して、createUsersByEmailList を直接 route から使っていいと思う。

2021-06-24 17:49 UTC, yuki-takei commented on src/server/routes/apiv3/users.js
> +      afterWorkEmailList = await User.createUsersByInvitation(req.body.shapedEmailList);
ここで createUsersByEmailList を直接使うことにしていいと思うが、そちらも改修した方がよい(どんどんスコープが広くなってしまうが…)

- createUsersByEmailList 内で existingEmailList を除外するところまではいいと思うが、creationEmailList のメアドリストの内どれかが失敗すると catch に入ってしまう
    - Promise.allSettled を使って必ず正常系に戻るようにする
    - つまりここの try-catch は不要となる

2021-06-24 17:49 UTC, yuki-takei commented on src/server/routes/apiv3/users.js
> +        await User.sendEmailbyUserList(afterWorkEmailList.createdUserList);
- Promise.allSettled の結果、成功したもののみメール送信を行う
- sendEmailbyUserList はこの users.js に移植しよう
    - model から mailService への依存もなくなって一石二鳥
    - sendEmailbyUserList もやはり現在は Promise.all で実装されているので、こちらも Promise.allSettled を使う
    - その結果、ここでも try-catch は不要となる

2021-06-24 17:49 UTC, yuki-takei commented on src/server/routes/apiv3/users.js
> +        await User.sendEmailbyUserList(afterWorkEmailList.createdUserList);
最終的には、以下のようなデータが手に入る

- createUsersByEmailList の結果
    - 既に存在していたメアドリスト
    - 存在しておらず、作成の成功した
    - 存在しておらず、作成失敗したメアドリストとその失敗理由
- sendEmailbyUserList の結果
    - メール送信成功したメアドリスト
    - メール送信失敗したメアドリストとその失敗理由

2021-06-24 17:49 UTC, yuki-takei commented on src/server/routes/apiv3/users.js
> +        await User.sendEmailbyUserList(afterWorkEmailList.createdUserList);
上記を、API の返り値として成形する

- 作成も送信も成功したメアドリスト
- エラーのリスト
    - メールアドレス、何の操作で失敗したのか

2021-06-25 08:54 UTC, miya commented on src/server/routes/apiv3/users.js
> +      return res.apiv3Err(new ErrorV3('Failed to create user', afterWorkEmailList.failedToCreateUserEmailList));
ユーザーの作成に失敗した場合は `Failed to create user` というメッセージと作成しようとしていたユーザーのメールアドレスを返すようにしました。

2021-06-25 08:54 UTC, miya commented on src/server/routes/apiv3/users.js
> +        return res.apiv3Err(new ErrorV3('Failed to send email', failedToSendEmailList));
ユーザーの作成に成功かつメールの送信に失敗した場合は `Failed to send email` というメッセージと、メールを送信しようとしていたメールアドレスを返すようにしました。

2021-06-25 08:54 UTC, miya commented on src/server/routes/apiv3/users.js
> +    return res.apiv3({ afterWorkEmailList }, 201);
ユーザーの作成成功かつメール送信に成功した場合は、作成されたユーザーデータと、既存のメールアドレスのリストを返すようにしました。

2021-06-25 09:10 UTC, miya commented
フロント上では、作成も送信も成功した場合に、作成されたアドレスを success で toast 、既存のメアドだった場合に、warning で toast させます。これ以外の場合は、エラーメッセージと、それに対応するメアドを error の toast として列挙する予定です。

2021-06-25 10:25 UTC, yuki-takei requested changes

2021-06-25 10:25 UTC, yuki-takei commented on src/client/js/services/AdminUsersContainer.js
> +    return afterWorkEmailList;
afterWork っていう名前、ちょっとなんの結果なのか、どういうものが入ってるのか想像し辛い。

2021-06-25 10:25 UTC, yuki-takei commented on src/server/models/user.js
> +      .then((results) => {
await と Promise.then が混在しているので async/await に統一

2021-06-25 10:25 UTC, yuki-takei commented on src/server/routes/apiv3/users.js
> +      return res.apiv3Err(new ErrorV3('Failed to create user', afterWorkEmailList.failedToCreateUserEmailList));
ここで return するのは早い。作成成功したユーザーは、メール送信までやるべきだよね。

2021-06-26 05:08 UTC, miya commented on src/server/routes/apiv3/users.js
> +      return res.apiv3Err(new ErrorV3('Failed to create user', afterWorkEmailList.failedToCreateUserEmailList));
確かにそうですね。作成に失敗したユーザー数が0より上かつ、作成されたユーザーが0だった場合にエラーを出すようにしました。

2021-06-26 11:40 UTC, miya commented on src/server/routes/apiv3/users.js
> +    const emailList = Array.from(new Set(req.body.shapedEmailList));
入力されたメールアドレス群の重複を削除させるようにしました。現状の仕様（masterでも）では重複するメールアドレスが入力されると `createdUserList` に入ってしまっている（作成はされていない）のでフロントでは画像のように表示が崩れていました。

<img width="496" alt="スクリーンショット 2021-06-26 18 49 23" src="https://user-images.githubusercontent.com/34241526/123511641-6a914380-d6bd-11eb-9681-84a530d446da.png">

2021-06-27 17:07 UTC, yuki-takei requested changes

2021-06-27 17:07 UTC, yuki-takei commented on src/server/routes/apiv3/users.js
> +    const emailList = Array.from(new Set(req.body.shapedEmailList));
迷う場合は、大抵はフロントエンドで対応しなくてもバックエンドでは確実に対応されるように、つまり「バックエンドでは必須の責務、フロントエンドではオプショナルな責務」として実装するとうまくいくことが多いです。このPRの実装でいいと思う。

2021-06-27 17:07 UTC, yuki-takei commented on src/server/routes/apiv3/users.js
> +        return res.apiv3Err(new ErrorV3('Failed to send email', failedToSendEmailList));
前回のFB通りの仕様・挙動になっていない。もういちど熟読して。
https://github.com/weseek/growi/pull/3928#discussion_r658156692

409行目で return するのもあまりよくない。createdUserList.length がゼロだろうが failedToSendEmailList.length が 1 以上だろうが、この API で返るモデルは全シチュエーションで同じ形をしているのが望ましい。

2021-06-28 05:29 UTC, miya commented on src/server/models/user.js
> +          failedToCreateUserEmailList.splice(index, 1);
rejected された results に email が入らないのでこのような処理になっています。。。

2021-06-28 07:27 UTC, miya commented on src/server/routes/apiv3/users.js
> +    return res.apiv3({ createUser, failedEmailList }, 201);
API の戻り値として createUser（作成成功したuser、既存のメアド）と failedEmailList（ユーザー作成に失敗したメアドとその理由、メールの送信に失敗したメアドとその理由）を返すようにしました。

また、createUsersByEmailList と sendEmailByUserList ですが、Promise.allsettled を採用していましたが、promise が rejected した際に メールアドレスの取得ができないため、従来の Promise.all で TryCatch するように変更しました。

2021-06-28 08:33 UTC, miya commented on src/server/routes/apiv3/users.js
> +    }, 201);
API の戻り値として createUser（作成成功したuser、既存のメアド）と failedEmailList（ユーザー作成に失敗したメアドとその理由、メールの送信に失敗したメアドとその理由）を返すようにしました。

また、createUsersByEmailList と sendEmailByUserList は Promise.allsettled を採用していましたが、promise が rejected した際に メールアドレスの取得ができないため、従来の Promise.all で TryCatch するように変更しました。

2021-06-28 11:42 UTC, yuki-takei requested changes

2021-06-28 11:42 UTC, yuki-takei commented on src/server/models/user.js
> +        });
これじゃだめ。Promise.all の使い方も、array.map の使い方も違う。ぐちゃぐちゃ…
以下のどちらかでやって。

- 実装1
    - creationEmailList.map で promises を収集し、Promise.allSettled で成否全ての結果を取得、その後 createdUserList と failedToCreateUserEmailList に分ける
- 実装2
    - creationEmailList.forEach して、その中で今実装しているような try-catch を行い、 createdUserList と failedToCreateUserEmailList に分ける
    - こっちの方が大量のメアド処理する時に promise でメモリ食い潰さなくていいかもしれない

2021-06-28 11:42 UTC, yuki-takei commented on src/server/routes/apiv3/users.js
> +    await Promise.all(userList.map(async(user) => {
こっちも実装2でいいかな。

2021-06-29 06:09 UTC, miya commented on src/server/models/user.js
> +        });
実装2を採用しました。forEach の中で await が使えないので for of を使いました。

2021-06-29 11:53 UTC, merged