Feat/growi bot reshape slack conversation for create command
weseek/growi pull request #3943
Opened 2021-06-29 04:01 UTC by hakumizuki

2021-06-29 04:09 UTC, hakumizuki commented
GW-6560を実装しました。ご確認よろしくお願いします。
GW-6560 create Modalから送られてきたテキストの内容を、名前と時間の部分をもとに検知し、Header, Sectionに変更を加えてからPage.createする+改行削除など

以下動画と説明です。
デザインは後続タスクで行います。
今回のタスクでは、divタグで囲う、Headerを検知してマークする、時間を--で囲う、リアクションを取り除く、を行いました。
名前の部分からコピペしなくても大丈夫なようになっています。
普通のmarkdownとしてもそのまま使えます。

https://user-images.githubusercontent.com/58432773/123735644-8faecd80-d8da-11eb-9756-e97361188837.mov

2021-06-29 11:46 UTC, yuki-takei requested changes

2021-06-29 11:46 UTC, yuki-takei commented on src/server/service/slackbot.js
> +      const regexpReaction = new RegExp(/^:[+\w-]+:$/);
ここも regex101.com を使ったコメントを追加。

2021-06-29 11:46 UTC, yuki-takei commented on src/server/service/slackbot.js
> +    const reshape = (str) => {
これは別メソッドに

2021-06-29 11:46 UTC, yuki-takei commented on src/server/service/slackbot.js
> +      const regexpSectionHeader = new RegExp(/.+\s\s[\d]{1,2}:[\d]{2}(\s[AP]{1}M)?$/);
regex101.com を使ったコメントを追加して。リポジトリ内にそのようなコメントあると思うので参考に。

2021-06-29 11:46 UTC, yuki-takei commented on src/server/service/slackbot.js
> +    const removeLinesBeforeFirstHeader = (array) => {
これは別メソッドに

2021-06-29 11:46 UTC, yuki-takei commented on src/server/service/slackbot.js
> +    contentsBody = this.reshapeContentsBody(contentsBody);
reshapeContentsBody は、packages/slack 内に TypeScript で独立したモジュール(ファイル)として実装してください。

2021-06-30 05:59 UTC, yuki-takei requested changes

2021-06-30 05:59 UTC, yuki-takei commented on packages/slack/src/utils/reshape-contents-body.ts
> +const devideLinesBeforeAfterFirstHeader = (array: string[]) => {
引数の一時変数を lines: string[] に変更
(名が体を表すように)

2021-06-30 05:59 UTC, yuki-takei commented on packages/slack/src/utils/reshape-contents-body.ts
> +};
このメソッド意味なくない？reshape をそのまま reshapeContentsBody にすればいいような。

2021-06-30 07:06 UTC, merged