Feat/gw 6496 toast error
weseek/growi pull request #3949
Opened 2021-06-29 17:19 UTC by miya

## 概要
- エンドポイント `users/invite` の戻り値の軽微な修正を行いました。
- 新規ユーザー仮発行のエラー時の toast を作成しました。

<img width="262" alt="スクリーンショット 2021-06-30 2 17 58" src="https://user-images.githubusercontent.com/34241526/123840535-64af9280-d949-11eb-9254-dbda07d4ab0b.png">

2021-06-29 17:28 UTC, miya commented on src/server/routes/apiv3/users.js
>      }
フロント側で値を扱いやすくするために、failedEmailList に push する値を
これから
```javascript
[
[{email: 'hoge1@co.jp', reason: 'hogehoge'}, {email: 'hoge1@co.jp', reason: 'hogehoge2'}], 
[{email: 'hoge2@co.jp', reason: 'hogehoge'}, {email: 'hoge3@co.jp', reason: 'hogehoge2'}], 
]
```

このようになるように修正しました。
```javascript
[{email: 'hoge1@co.jp', reason: 'hogehoge'}, {email: 'hoge2@co.jp', reason: 'hogehoge'}, {email: 'hoge3@co.jp', reason: 'hogehoge'}]
```

2021-06-29 17:28 UTC, miya commented on src/server/routes/apiv3/users.js
> +        });
こちらも同様

2021-06-30 05:52 UTC, yuki-takei requested changes

2021-06-30 05:52 UTC, yuki-takei commented on src/server/routes/apiv3/users.js
> +      });
array.concat を使ってください

2021-06-30 06:12 UTC, merged