Imprv/set proxy uri in case of official
weseek/growi pull request #3969
Opened 2021-07-01 09:46 UTC by zahmis

2021-07-01 09:50 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> -  const [newProxyServerUri, setNewProxyServerUri] = useState();
必要ないので削除

2021-07-01 09:50 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> -  const updateProxyUri = async() => {
これも更新する必要がないので削除

2021-07-01 09:50 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +      if (botType === 'officialBot') {
Bot type を変更するとき

2021-07-01 09:50 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
> +    if (botType === 'officialBot') {
(最初に) botType を選択するとき

2021-07-01 09:50 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> -      title: 'set_proxy_url_on_growi',
不要につき削除

2021-07-01 12:43 UTC, zahmis commented on src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
> -          <div className="form-group row my-4">
そもそも proxy uri を表示する必要がないので削除

2021-07-01 12:43 UTC, zahmis commented on src/server/routes/apiv3/slack-integration-settings.js
> +    if (currentBotType === 'officialBot') {
officialbot が選択された時には proxy uri を固定

2021-07-02 12:11 UTC, yuki-takei requested changes

2021-07-02 12:11 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +    }
blocks 以外は116行目以降と重複している

2021-07-05 09:06 UTC, merged