Feat/gw 6653 6664 mark out
weseek/growi pull request #3982
Opened 2021-07-04 09:35 UTC by miya

## 概要
- GW-6653 招待メールの送信に成功したらマークを消すためのステートを用意する

- GW-6664 調整
  - ファイル名の rename （SendInvitationMaliButton.jsx -> SendInvitationEmailButton.jsx）
  - UserInviteModal.jsx の toastError
  - ユーザーを作成した際の文言を変更

2021-07-04 09:38 UTC, miya reviewed
文言の変更

Before
<img width="499" alt="スクリーンショット 2021-07-04 16 12 22" src="https://user-images.githubusercontent.com/34241526/124380281-dc3d4300-dcf6-11eb-8052-10c0d300e4a1.png">

After
<img width="498" alt="スクリーンショット 2021-07-04 16 44 43" src="https://user-images.githubusercontent.com/34241526/124380282-de070680-dcf6-11eb-898f-407a9d72b0e4.png">

2021-07-04 09:40 UTC, miya commented on resource/locales/ja_JP/admin/admin.json
> +      "send_temporary_password": "招待メールを送っていない場合、この画面で仮パスワードをコピーし、招待者へ連絡してください。ユーザー一覧のドロップダウンから招待メールの送信または再送信を行うこともできます。",
文言の変更

Before
<img width="499" alt="スクリーンショット 2021-07-04 16 12 22" src="https://user-images.githubusercontent.com/34241526/124380281-dc3d4300-dcf6-11eb-8052-10c0d300e4a1.png">

After
<img width="498" alt="スクリーンショット 2021-07-04 16 44 43" src="https://user-images.githubusercontent.com/34241526/124380282-de070680-dcf6-11eb-898f-407a9d72b0e4.png">

2021-07-04 09:40 UTC, miya commented on src/client/js/components/Admin/Users/UserInviteModal.jsx
> +        toastError({ message: msg });
toastError を使用

2021-07-05 08:07 UTC, yuki-takei requested changes

2021-07-05 08:07 UTC, yuki-takei commented on src/client/js/components/Admin/Users/SendInvitationEmailButton.jsx
> +  updateIsInvitationEmailSended: PropTypes.func.isRequired,
onHoge にする
- [/Tips/JavaScript/命名規則](https://tips.weseek.co.jp/60ae84d41091010049bed55d)

2021-07-05 10:57 UTC, merged