Imprv/gw 5883 error handling using http errors implementation
weseek/growi pull request #4001
Opened 2021-07-08 03:45 UTC by hakumizuki

2021-07-08 03:48 UTC, hakumizuki commented
GW-5883 エラーハンドリングの改善 を実装しました。
ご確認お願いします。

コメント：
controller の res.status(XXX).send('something') はすべてthrow createError()におきかえました。
置き換えることによってレスポンスが変わってしまいそうなところはそのままにしました。

2021-07-08 04:01 UTC, yuki-takei commented
本体側にも改修を入れてください

2021-07-09 05:50 UTC, hakumizuki commented
こんな感じで切り替えて試しました。built-inのErrorインスタンスのときはexpressのデフォルトがハンドリングし、createError()のときはhttp-error-handlerがハンドリングします。
<img width="770" alt="切り替えて試しました" src="https://user-images.githubusercontent.com/58432773/125029458-a3211c00-e0c4-11eb-8add-4b1aa3d35c9f.png">

レスポンスが返ってきました。
<img width="666" alt="Screen Shot 2021-07-09 at 14 37 43" src="https://user-images.githubusercontent.com/58432773/125029464-a4eadf80-e0c4-11eb-85a0-df54dd62819f.png">

2021-07-09 05:51 UTC, hakumizuki commented
本体はhttp-errors@1.6.2に合わせています。コミットメッセージに@1.7.2と書いてありますが1.6.2の間違いです。

2021-07-16 11:45 UTC, yuki-takei requested changes

2021-07-16 11:45 UTC, yuki-takei commented on src/server/middlewares/http-error-handler.js
> +module.exports = (err, req, res, next) => {
async 付けた方がいい

2021-07-17 14:47 UTC, merged