Imprv/create page editor substacne
weseek/growi pull request #4005
Opened 2021-07-09 03:44 UTC by zahmis

2021-07-09 05:31 UTC, zahmis commented on src/client/js/components/PageEditor.jsx
> +import PageContainer from '../services/PageContainer';
現状 pageContainer と editorContainer が生きているのでそのまま使っています。

2021-07-09 05:31 UTC, zahmis commented on src/client/js/components/PageEditor.jsx
> +  //   scrollSyncHelper.scrollPreview(this.previewElement, line);
scrollSyncHelper の hiElement が undefined になることで error が発生するので一時的に コメントアウトしています。
別のタスクで改修します。

2021-07-09 08:34 UTC, yuki-takei requested changes

2021-07-09 08:34 UTC, yuki-takei commented on src/client/js/components/PageEditorSubstance.tsx
> +export default PageEditorSubstance
これは PageEditor の中に作る

2021-07-09 08:34 UTC, yuki-takei commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +  const PageEditorSubstance = dynamic(() => import('../PageEditorSubstance'), { ssr: false });
この行と PageEditor の名前は変えずに同じ事を実現してください。

2021-07-12 06:32 UTC, zahmis commented on src/client/js/components/PageEditor.jsx
> +
PageEditorSubstance を PageEditor.jsx に内包しています。

2021-07-12 06:35 UTC, zahmis commented on src/client/js/components/Page/DisplaySwitcher.jsx
> +  const PageEditorSubstance = dynamic(() => import('../PageEditorSubstance'), { ssr: false });
PageEditorSubstance はやめて、PageEditor を import することにしました。 
PageEditor では PageEditorSubstance という FC を export することで同様のことを実現しています。

2021-07-12 06:35 UTC, zahmis commented on src/client/js/components/PageEditorSubstance.tsx
> +export default PageEditorSubstance
承知しました

2021-07-12 10:32 UTC, yuki-takei commented on src/client/js/components/PageEditor.jsx
> +const PageEditorSubstance = () => {
こっちが PageEditor、
元の `class PageEditor extends React.Component` を PageEditorSubstance にする

2021-07-12 11:02 UTC, zahmis commented on src/client/js/components/PageEditor.jsx
> +const PageEditorSubstance = () => {
なるほど。
承知しました。

2021-07-12 14:31 UTC, merged