Imprv/gw6757 create mail submit route and the UI
weseek/growi pull request #4014
Opened 2021-07-13 04:30 UTC by kaoritokashiki

2021-07-13 05:10 UTC, kaoritokashiki commented on src/client/js/components/LoginForm.jsx
> +                    <a href={passwordResetRequestPageurl} id="reset-password" className="d-block link-switch mb-1">
パスワード再設定をリクエストするためのリンクを追加
`http://localhost:3000/_api/v3/password`

2021-07-13 05:12 UTC, kaoritokashiki commented on src/server/routes/apiv3/password.js
> +};
routes/apiv3 配下に password のフォルダを新設しました。
このエンドポイントは、Forgot password? のリンクをクリックしたときに飛ぶpathです。

2021-07-13 10:41 UTC, yuki-takei requested changes

2021-07-13 10:41 UTC, yuki-takei commented on src/server/routes/apiv3/password.js
> +};
- PasswordResetRequestForm は空でもいいので、そのレンダリングまでこの PR のスコープに入れた方がいいね
- view の表示は API とは呼ばないので、apiv3 下に作るのはよくない

2021-07-13 10:41 UTC, yuki-takei commented on src/server/routes/apiv3/password.js
> +    return res.apiv3({ hoge: 'hoge' });
- view の表示では res.apiv3 はつかわない
- v4.x 系では swig を使う他ない
    - 他の route を参考に

2021-07-13 10:41 UTC, yuki-takei commented on src/client/js/components/LoginForm.jsx
> +                    <a href={passwordResetRequestPageUrl} id="reset-password" className="d-block link-switch mb-1">
growiUrlHost との join は必要ない。ただ `/forgot-password` みたいなリンク先をハードコードすればいいだけ

2021-07-13 13:16 UTC, kaoritokashiki commented on src/server/routes/apiv3/password.js
> +};
畏まりました!

2021-07-14 11:19 UTC, kaoritokashiki commented on src/client/js/components/PasswordResetRequestForm.jsx
> +      Password Reset Request Form
見た目は以下の後続タスクで着手します。
GW-6789 PasswordResetRequestページにフォームを追加する(見た目のみ)

2021-07-14 11:40 UTC, yuki-takei requested changes

2021-07-14 11:40 UTC, yuki-takei commented on src/server/routes/password.js
> +};
ファイル名を forgot-password.js にしましょう

2021-07-14 11:49 UTC, kaoritokashiki commented on src/server/routes/password.js
> +};
そのように修正しました。

2021-07-14 11:52 UTC, merged