TS for UserGroupPage
weseek/growi pull request #4020
Opened 2021-07-14 03:54 UTC by stevenfukase

2021-07-14 07:39 UTC, itizawa commented on src/client/js/components/Admin/UserGroup/UserGroupCreateForm.jsx
> +    if (process.browser) {
これってどういったコードですか...?
もし存在チェックするなら 
```suggestion
    if (process.browser != null) {
```
でお願いします。

2021-07-14 07:39 UTC, itizawa commented on src/stores/admin.tsx
> +    (endpoint) => apiv3Get(endpoint, { pagination })
pagination が正しく使えてないですね
```suggestion
    (endpoint,pagination) => apiv3Get(endpoint, { pagination })
```

2021-07-14 07:39 UTC, itizawa commented on src/stores/admin.tsx
> +    (endpoint, path) => apiv3Get(endpoint, { path }).then(result => result.data.userGroupRelationsParams),
path はどこから入ってきてますか。
多分これ null で送られている気がします

2021-07-14 07:39 UTC, itizawa commented on src/components/Admin/UserGroup/UserGroupPage.tsx
> +const UserGroupPage = (): JSX.Element => {
```suggestion
export const UserGroupPage = (): JSX.Element => {
```

FC にするのであれば named export の方がいいと思います

2021-07-14 07:39 UTC, itizawa commented on src/components/Admin/UserGroup/UserGroupPage.tsx
> +const UserGroupPage = (): JSX.Element => {
元の jsx を使わなくなったのであれば削除お願いします 🙏

2021-07-14 07:39 UTC, itizawa commented on src/components/Admin/UserGroup/UserGroupPage.tsx
> +  }
ここら辺の state 管理を見直した方が良さそうです

2021-07-14 07:39 UTC, itizawa commented on src/components/Admin/UserGroup/UserGroupPage.tsx
> +  }
そもそも UserGroup を state 管理する必要があるのか?
swr 使うのであれば mutate してデータを refetch した方が良いのではないのか

2021-07-14 07:39 UTC, itizawa commented on src/components/Admin/UserGroup/UserGroupPage.tsx
> +  }
例えばここの部分は全て swr で置き換えられる

2021-07-14 07:39 UTC, itizawa commented on src/components/Admin/UserGroup/UserGroupPage.tsx
> +      })
swr の mutate で良い

2021-07-14 07:39 UTC, itizawa commented on src/components/Admin/UserGroup/UserGroupPage.tsx
> +        userGroupRelations={userGroupRelations}
SWR から受け取ったものをここに流して良さそう

2021-07-26 03:59 UTC, itizawa commented
You have not declared a namespacesRequired array on your page-level component: ErrorPage. This will cause all namespaces to be sent down to the client, possibly negatively impacting the performance of your app. For more info, see: https://github.com/isaachinman/next-i18next#4-declaring-namespace-dependencies
GET /admin/isDeviceSmallerThanMd 500 66.658 ms - -

別の問題が発生していました。確認お願いします。

2021-07-26 12:09 UTC, yuki-takei requested changes

2021-07-26 12:09 UTC, yuki-takei commented on src/client/js/components/Admin/UserGroup/UserGroupTable.jsx
> +                      <td><a href={`/admin/user-group-detail/${group._id}`}>{group.name}</a></td>
ここの xss 処理って外しても問題ないの？

2021-07-26 12:09 UTC, yuki-takei commented on src/stores/admin.tsx
> +export const useUserGroupSWR = ({ pagination }): responseInterface<IUserGroup[], Error> => {
- type GetUserGroupsOptions を作ってください
    - このファイル内でよいです

2021-07-27 14:42 UTC, yuki-takei requested changes

2021-07-27 14:42 UTC, yuki-takei commented on src/client/js/components/Admin/UserGroup/UserGroupTable.jsx
> +                      <td><a href={`/admin/user-group-detail/${group._id}`}>{group.name}</a></td>
これは jsx 内の要素として書いてる部分なので問題なさそう。

2021-07-27 14:42 UTC, yuki-takei commented on src/client/js/components/Admin/UserGroup/UserGroupPage.jsx
> +      toastSuccess(`Deleted group "${res.data.userGroup.name}"`);
こっちは react で処理されないので xss 処理外すのは問題がある

2021-07-28 08:59 UTC, merged