Imprv/gw6802 generate unique token
weseek/growi pull request #4038
Opened 2021-07-19 03:28 UTC by kaoritokashiki

2021-07-19 04:51 UTC, kaoritokashiki commented on src/server/models/password-reset-order.js
> +    const hasher = crypto.createHash('sha384');
ハッシュ値はsha-2の'sha384'にしました。

>The security of the process is entirely reliant on an attacker not being able to guess or brute-force a token. The tokens should be generated with a Cryptographically Secure Pseudo-Random Number Generator (CSPRNG), and should be sufficiently long that it is impractical for an attacker to guess or brute-force. At least 128 bits (or 32 hex characters) is a sufficient minimum to make such an online attack impractical.

2021-07-19 13:34 UTC, yuki-takei requested changes

2021-07-19 13:34 UTC, yuki-takei commented on src/server/models/password-reset-order.js
> +    const hasher = crypto.createHash('sha384');
- ユニークである必要があるので、slackbot-proxy の tokenPtoG 等でもやっていると思うけれど do-while してください
- generate するだけじゃなくて token フィールドに入れて save するところまでやった方がいいんじゃないかな

2021-07-20 06:50 UTC, yuki-takei requested changes

2021-07-20 06:50 UTC, yuki-takei commented on src/server/models/password-reset-order.js
> +  }
generate するだけじゃなくて token フィールドに入れて save するところまでやった方がいい

2021-07-20 07:49 UTC, kaoritokashiki commented on src/server/routes/forgot-password.js
> +      await PasswordResetOrder.create({ token, email });
この書き方だとダメでしょうか...??

2021-07-20 10:22 UTC, shield-9 commented on src/server/models/password-reset-order.js
> +    const token = hasher.update((new Date()).getTime().toString()).digest('base64');
現実的に、攻撃として成立しうるのかという議論はあると思いますが、この実装だと理論的には脆弱です。
ハッシュ関数ではなく、 `crypto.randomBytes` のようなCSPRNGを使った方が安全です。

----

### 前提条件
* 攻撃者は利用者のメールアドレスを入手している
* 攻撃者はGROWIにアクセスできる

### 詳細
利用者のメールアドレスを入力したパスワードリセットのフォームを**ある時刻に**送信する。
このとき、フォームの送信者は、GROWIがフォームを受信した時刻を推測し、トークンやそれが組み込まれたURLを再現できる。そして、再現したURLにアクセスすることで、メールアドレスに紐づく利用者のパスワードをリセットできてしまう。

※現実問題として、受信時間をDate型のような細かい単位で推測できる可能性はかなり低いですが。

2021-07-20 13:01 UTC, yuki-takei requested changes

2021-07-20 13:01 UTC, yuki-takei commented on src/server/routes/forgot-password.js
> +      await PasswordResetOrder.create({ token, email });
36行目で手に入れた token が、40行目が処理されるまでにユニークであり続ける保証はないので、「unique token を作って永続化するまで」を model の責務として扱った方がよいです。

実際は現状のコードだとほとんど一瞬だけど、今後 38行目とかに誰かが `sleep(1000)` とかその他の少し時間がかかるコードを挿入したら、と考えてほしい。

2021-07-21 09:35 UTC, kaoritokashiki commented on src/server/models/password-reset-order.js
> +    const token = hasher.update((new Date()).getTime().toString()).digest('base64');
コメントありがとうございます! 修正します。

2021-07-27 04:48 UTC, kaoritokashiki commented on src/server/models/password-reset-order.js
> +    return passwordResetOrderData;
method 名を `genarateOnetimeoken` -> `createPasswordResetOrderRecord`に変更しました。
ここでcreateして、DBに保存しています。

2021-07-27 04:54 UTC, kaoritokashiki commented on src/server/models/password-reset-order.js
> +  }
`crypto.randomBytes`を使用しましたが、この記述でよろしかったでしょうか....??

- tokenの一例
```
"JU5vr0rCRs9DxREIRKQjXLLylCSpPzsWV0KpIo1fmC4IkWlkTJVxC9l82oe5/94R6EoK2sl3krubbCvtAF8IXPUpqR+9jQXJhFxpbav5WceK6vVtbpmqYg/oT3Aauqi6mYoAW+WiRKZCw/JUVKLVdr2agQ+/yeTBspTdsyXxuBpojp/abB5ZYrPvdEgDAqh20BVbrQ/j8KKVSsqDgu4QIx5PiwgvgeYfBEC2mmMEB6fioRK+92FFewVOC8LZfV2R3sCgzpvRhRMH018cXfSzJiVlfU7NcCvjwMUrBuzHK/UQuVrFxq2t+dbt+3ao4zTRqVJUYmtzDfbz/+2wyrJSYw=="
```

2021-07-27 04:57 UTC, kaoritokashiki commented on src/server/routes/forgot-password.js
> +    const email = 'foo@example.com';
email は仮で入れています。

2021-07-27 05:24 UTC, shield-9 commented on src/server/models/password-reset-order.js
> +  }
Goodだと思います!

2021-07-27 07:21 UTC, merged