apply i18n
weseek/growi pull request #4039
Opened 2021-07-19 05:27 UTC by kaoritokashiki

2021-07-19 13:36 UTC, yuki-takei requested changes

2021-07-19 13:36 UTC, yuki-takei commented on src/server/routes/forgot-password.js
> +    await sendPasswordResetEmail(i18n);
- req.language が存在しない場合のケアをしないといけない
    - ただしデフォルト値は GROWI 全体で既に決まっているので、ここには`|| 'en_US'` のようなコードは書かないこと

2021-07-20 02:37 UTC, kaoritokashiki commented on src/server/routes/forgot-password.js
> +    await sendPasswordResetEmail(i18n);
なるほどです、修正しました。

2021-07-20 06:55 UTC, yuki-takei requested changes

2021-07-20 06:55 UTC, yuki-takei commented on src/server/routes/forgot-password.js
> +    await sendPasswordResetEmail(i18n);
globalLang の決定の仕方、これじゃない気がする..

i18next の設定から取れないかな。
v5.0.x で使ってる nexti18next じゃないと静的な設定は取れない、であればこれで合ってるということになるが。

2021-07-26 05:03 UTC, kaoritokashiki commented on src/server/routes/forgot-password.js
> +    await sendPasswordResetEmail(i18n);
他のところでも、この方法で`globalLang`が取得しているので、これかな...?と思うのですが
> i18next の設定から


![Screen Shot 2021-07-26 at 13 45 12](https://user-images.githubusercontent.com/59536731/126934267-aec59404-f302-4e62-9d35-138902da0753.png)


```
  flash: [Function: _flash],
  lng: 'en_US',
  locale: 'en_US',
  language: 'en_US',
  languages: [ 'en_US' ],
  i18n: I18n {
    observers: { languageChanged: [Array] },
    options: {
      debug: false,
      initImmediate: false,
      ns: [Array],
      defaultNS: [Array],
      fallbackLng: [Array],
      fallbackNS: false,
      whitelist: [Array],
      nonExplicitWhitelist: false,
      supportedLngs: [Array],
      nonExplicitSupportedLngs: false,
      load: 'all',
      preload: false,
      simplifyPluralSuffix: true,
      keySeparator: '.',
      nsSeparator: '::',
      pluralSeparator: '_',
      contextSeparator: '_',
      partialBundledLanguages: false,
      saveMissing: false,
      updateMissing: false,
      saveMissingTo: 'fallback',
      saveMissingPlurals: true,
      missingKeyHandler: false,
      missingInterpolationHandler: false,
      postProcess: false,
      postProcessPassResolved: false,
      returnNull: true,
      returnEmptyString: true,
      returnObjects: false,
      joinArrays: false,
      returnedObjectHandler: false,
      parseMissingKeyHandler: false,
      appendNamespaceToMissingKey: false,
      appendNamespaceToCIMode: false,
      overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
      interpolation: [Object],
      backend: [Object],
      detection: [Object],
      ignoreJSONStructure: true,
      isClone: true
    },

```

2021-07-26 11:36 UTC, merged