added elasticsearchmanagement page
weseek/growi pull request #4047
Opened 2021-07-20 05:45 UTC by stevenfukase

2021-07-26 04:01 UTC, itizawa approved these changes

2021-07-26 04:01 UTC, itizawa commented on src/interfaces/search.ts
> +{"mode":"full","isActive":false}
消し忘れ...?

2021-07-26 11:30 UTC, yuki-takei requested changes

2021-07-26 11:30 UTC, yuki-takei commented on src/stores/search.tsx
> +export const useIndicesSWR = (): responseInterface<ISearchIndicesInfo, Error> => {
useSearchIndicesInfoSWR に名前を変えよう

2021-07-26 11:30 UTC, yuki-takei commented on src/client/js/components/Admin/ElasticsearchManagement/ElasticsearchManagement.jsx
> +        mutateIndices={mutate}
onEventName にしましょう

2021-07-26 11:30 UTC, yuki-takei commented on src/client/js/components/Admin/ElasticsearchManagement/ElasticsearchManagement.jsx
> +  const { data, mutate } = useIndicesSWR();
SWR の結果に応じて、もう status の中身は決定できるのでは？

2021-07-26 11:30 UTC, yuki-takei commented on src/client/js/components/Admin/ElasticsearchManagement/ElasticsearchManagement.jsx
> +        status={status}
status の中身はまとめて入れずにばらして入れよう。

2021-07-27 06:45 UTC, stevenfukase commented on src/stores/search.tsx
> +};
エラーコード 'search-service-unconfigured'を取得したいので、throw errorしてます。

2021-07-27 07:50 UTC, yuki-takei requested changes

2021-07-27 07:50 UTC, yuki-takei commented on src/client/js/components/Admin/ElasticsearchManagement/ElasticsearchManagement.jsx
> +  let isNormalized = false;
ちょっと読みにくい。
初期値は全部 false にして、SWR が返す値に応じて変更してください。

2021-07-27 07:50 UTC, yuki-takei commented on src/stores/search.tsx
> +    }
このコードだったらわざわざ fetcher 再定義する必要ないんじゃないかな。そのまま throw されると思う。

2021-07-27 07:50 UTC, yuki-takei commented on src/stores/search.tsx
> +};
search-service-unconfigured から isConfigured の T/F を返す SWR メソッドを別途用意しましょう。

```
    if (error[0].code === 'search-service-unconfigured') {
      isConfigured = false;
    }
```
この判断を sotres 側で肩代わりする。

2021-07-28 09:22 UTC, yuki-takei requested changes

2021-07-28 09:22 UTC, yuki-takei commented on src/client/js/components/Admin/ElasticsearchManagement/ElasticsearchManagement.jsx
> +  }
このブロックいらないんじゃないかな

2021-07-29 03:58 UTC, merged