Feat/6450 6845 check expire
weseek/growi pull request #4070
Opened 2021-07-27 08:47 UTC by itizawa

2021-07-27 14:10 UTC, yuki-takei requested changes

2021-07-27 14:10 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +    const result = await Promise.all(relations.map(async(relation) => {
Promise.all ではどれかに例外が発生したときに弱い。
無関係の GROWI の状況に引っ張られて他の GROWI の機能を利用できないのはいけてない。

(が、後述の isSupportedGrowiCommandForSingleUse の改修を行うとこのメソッドは使わなくなるので今回はこの問題は気にしなくて良くなる)

2021-07-27 14:10 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +    return relation.supportedCommandsForSingleUse.includes(growiCommandType);
この中で以下を行う

1. 期限が切れていなければ T/F を返す
2. 期限が切れている場合、sync してから T/F を返す
    - 例外が発生した場合は false を返す(logger には出す)
3. 期限までに24時間を切っていたら **await せず sync を行う**
    - 例外が発生した場合も**なにもしない**(logger には出す)

名前に違和感があるなら syncAndHoge みたいな名前に変えてもよい。

2021-07-28 11:03 UTC, itizawa commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +    }
expired していたら、GrowiCommand を取得しにいく。
これは await を用いて処理を待ち、更新後の relation を見て support されているかを確認する。

2021-07-28 11:05 UTC, itizawa commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +    }
expired していなくても 24時間以内だった場合 GrowiCommand を sync する。
この処理は await を用いず、裏側で実行する。
-> ユーザーは GrowiCommand を sync する時間を待たないため UX が良い

2021-07-28 11:22 UTC, yuki-takei requested changes

2021-07-28 11:22 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +  async syncAndReturnIsSupported(relation:Relation, baseDate:Date, discriminantWhetherRelationIsSupported:(relation:Relation)=>boolean):Promise<boolean> {
ここまで来ると超細かいのだが…

## 違和感
- メソッド名に「ReturnIsSupported」とあるにも関わらず、現状このメソッドは「サポートしているかどうかの判定」を責務として持っていない
- discriminantWhetherRelationIsSupported を外部から注入できるようになってはいるが、今のところ利用シーンとして array.includes しか使っていないし、今後の拡張予定もない
- つまり名前とのミスマッチを許容してまで汎用性をもたせる意味を見いだせない(レビュー時に「ん？」と思う程には readable さを損なっている)

## 代案A
- 素直にこのメソッドの中で includes を使った判定を行う

## 代案B
- このメソッドの返り値は `Relation | null` にする
    - 同期が必要だった場合は syncedRelation を返し、不要だった場合は relation を返す
    - catch 時にはnull を返す
    - メソッド名は適切に変更する
- isSupportedGrowiCommandFor*Use 側で、null だった時は false を返す

2021-07-30 02:10 UTC, merged