Imprv/slackbot commands arch
weseek/growi pull request #4082
Opened 2021-07-30 08:33 UTC by hakumizuki

2021-07-30 08:40 UTC, hakumizuki commented
GW-6856 [相談済] slackコマンドを モジュールベースで扱えるようにし、各モジュールが command, block_actions, view_submission のハンドリングをできるようにする

の実装をしました。ご確認お願いします。動作確認は軽くしてますが、動作確認タスクでガッツリやります。

2021-07-30 10:20 UTC, yuki-takei requested changes

2021-07-30 10:20 UTC, yuki-takei commented on src/server/util/createPageInGrowi.js
> +  const pathUtils = require('growi-commons').pathUtils;
require は module.exports の外に出す

2021-07-30 10:20 UTC, yuki-takei commented on src/server/util/createPageInGrowi.js
> +    const page = await Page.create(normalizedPath, reshapedContentsBody, dummyObjectIdOfUser, {});
DB 操作があるので util には入れたくない。service/slack-command-handler の中に入れた方がいいな。
あとファイル名は kebab-case がよい。

2021-07-30 10:24 UTC, yuki-takei requested changes

2021-07-30 10:24 UTC, yuki-takei commented on src/server/service/slack-command-handler/slack-command-handler.js
> +  handleBlockActions(client, payload, handlerMethodName) { throw new Error('Implement this') }
このメソッド名、至る所にあるけど第三引数があるやつとないやつがあって追いかけづらい。(たぶんたまたま名前が同じメソッドとかあるよね)

2021-08-02 09:40 UTC, yuki-takei requested changes

2021-08-02 09:40 UTC, yuki-takei commented on src/server/service/slack-command-handler/slack-command-util.js
> +class SlackCommandUtil {
- CreatePageService でいいかな
    - logger の namespace の prefix も `growi:util:` から `growi:service：` に変える

2021-08-03 02:07 UTC, merged