Imprv/gw6805 be able to switch pasword reset func
weseek/growi pull request #4085
Opened 2021-07-31 12:36 UTC by kaoritokashiki

2021-07-31 12:38 UTC, kaoritokashiki commented on src/client/js/nologin.jsx
> +  const isPasswordResetEnabled = loginFormElem.dataset.isPasswordResetEnabled === 'true';
stringで true / falseが渡ってくるので　`xxxxx === 'true'`を追加しました。

2021-07-31 12:51 UTC, kaoritokashiki commented on src/client/js/services/AdminLocalSecurityContainer.js
> +      isPasswordResetEnabled: true,
default はtrueにしていますが、falseの方が適切でしたら言ってください。

2021-07-31 16:20 UTC, yuki-takei requested changes

2021-07-31 16:20 UTC, yuki-takei commented on src/server/service/config-loader.js
> +    key:     'security:isPasswordResetEnabled',
prefix は `security:passport-local:`

2021-07-31 16:20 UTC, yuki-takei commented on src/client/js/services/AdminLocalSecurityContainer.js
> +      isPasswordResetEnabled: true,
- boolean の初期値は false が望ましい
- true だろうが false だろうが、サーバーサイドから受け取る値で初期化されるはず(94行目)
    - システム的な初期値は config-loader で true してくれているはずで、それでOK

2021-08-01 13:41 UTC, kaoritokashiki commented on src/client/js/services/AdminLocalSecurityContainer.js
> +      isPasswordResetEnabled: true,
修正しました。

2021-08-01 13:41 UTC, kaoritokashiki commented on src/server/service/config-loader.js
> +    key:     'security:isPasswordResetEnabled',
修正しました。

2021-08-01 13:55 UTC, kaoritokashiki commented on src/server/models/config.js
> +      'security:passport-local:isPasswordResetEnabled'  : true,
- クリーンインストール時
<img width="1261" alt="Screen Shot 2021-08-01 at 22 54 16" src="https://user-images.githubusercontent.com/59536731/127773442-99be5b44-1768-4447-a8f0-d7138c087d1f.png">

![Uploading Screen Shot 2021-08-01 at 22.53.57.png…]()

2021-08-01 18:13 UTC, yuki-takei commented on src/server/models/config.js
> +      'security:passport-local:isPasswordResetEnabled'  : true,
そう、以前のバージョンからアップグレードした際は、migration script を書かない限りは config collectionにはisPasswordResetEnabled に相当する document が存在しない。

> isPasswordResetEnabledがDBに存在しない前提を作るにはどうすれば良いのでしょうか....??

Robo 3T で消してからサーバー起動したらいいんじゃない？

2021-08-01 18:14 UTC, merged