Fix/gw6934 redirect path when token is null
weseek/growi pull request #4086
Opened 2021-08-01 12:14 UTC by kaoritokashiki

2021-08-01 12:53 UTC, kaoritokashiki commented on src/server/middlewares/password-reset.js
> +    if (token == null || email == null) {
「tokenがnullの場合にエラーメッセージを出す」は親切ですが、セキュリティにNGではないかと思いました。

2021-08-01 18:11 UTC, yuki-takei requested changes

2021-08-01 18:11 UTC, yuki-takei commented on src/server/middlewares/password-reset.js
> +    if (token == null || email == null) {
こちらはいいとして、passwordResetOrder が見つからなかった場合や expire 時はエラーメッセージ表示させた方がいいと思う。コピペミスすることもあるし、expire した時に何もないと再発行するという考えが及ばないかもしれないし。

2021-08-01 18:11 UTC, yuki-takei commented on src/server/middlewares/password-reset.js
> +    if (token == null || email == null) {
逆に email を query から取るのをやめたほうがいいような。
passwordResetOrder が手に入ってから、そちらを手かがりに username or email を取れるんじゃないかな。

2021-08-02 05:06 UTC, kaoritokashiki commented on src/server/middlewares/password-reset.js
> +    if (token == null || email == null) {
なるほど、その発想はありませんでした

2021-08-02 07:29 UTC, kaoritokashiki commented on src/server/views/login/error.html
> +          </a>
![Screen Shot 2021-08-02 at 16 28 47](https://user-images.githubusercontent.com/59536731/127821194-ba76a0cd-7f19-4e7e-b3c0-3478fc4e8430.png)

2021-08-02 07:33 UTC, kaoritokashiki commented on src/server/routes/forgot-password.js
> +    return res.render('reset-password', { email });
`middleware/password-reset.js`で取得した passwordResetOrder からemailを取得しました。

2021-08-02 13:08 UTC, yuki-takei requested changes

2021-08-02 13:08 UTC, yuki-takei commented on src/server/views/login/error.html
> +          </a>
このファイルはログイン失敗した時用なので、相乗りせずに専用のファイルを作ってください。

2021-08-02 20:28 UTC, kaoritokashiki commented on src/server/views/login/error.html
> +          </a>
新しく `/forgot-password/error/password-reset-order` ファイルを作成しました。

2021-08-02 20:28 UTC, merged