position views comments tags
weseek/growi pull request #4090
Opened 2021-08-02 07:15 UTC by kaho819

左寄せ，サイズ，余白の調整
タグの折り返しは後続タスクでやる予定です。

<img width="278" alt="スクリーンショット 2021-08-02 16 12 15" src="https://user-images.githubusercontent.com/46134198/127819054-eb3d470d-87fb-4387-9aca-3361b1b3802e.png">

2021-08-02 08:03 UTC, yuki-takei requested changes

2021-08-02 08:03 UTC, yuki-takei commented on src/client/js/components/Sidebar/RecentChanges.jsx
> +            <div className="text-left">
text-left ってデフォルトだから書く必要ないのでは？

2021-08-02 08:03 UTC, yuki-takei commented on src/client/styles/scss/theme/mixins/_list-group.scss
> +      }
この中のほとんどは bs4 のユーティリティクラスでどうにかなる。

2021-08-02 08:03 UTC, yuki-takei commented on src/client/js/components/Sidebar/RecentChanges.jsx
> +              <div className="float-right small">
float はなるべく使わない

2021-08-03 09:16 UTC, yuki-takei requested changes

2021-08-03 09:16 UTC, yuki-takei commented on src/client/styles/scss/theme/mixins/_list-group.scss
> +      }
分量は適切になった。

- この mixin は list-group を拡張するものなので、Recent Changes 専用ではない
    - 別のファイルに追加してください
    - 必要であれば新規にファイルを作成してもよい
- mr-2 に font-size を充てるのは名が体を成していないことになる
    - カスタムクラスを用意して

2021-08-05 04:30 UTC, kaoritokashiki commented on src/client/styles/scss/_recent-changes.scss
> +    }
カスタムクラスを作成するときは prefixに `grw-`をつけてください

2021-08-05 04:35 UTC, kaoritokashiki commented on src/client/styles/scss/_recent-changes.scss
> +    }
カスタムクラスを作成するときは prefixに `grw-`をつけてください。
(このクラスがGROWIオリジナルなものだとわかるように)

2021-08-05 04:52 UTC, kaoritokashiki requested changes

2021-08-05 04:52 UTC, kaoritokashiki commented on src/client/js/components/Sidebar/RecentChanges.jsx
> +              <span className="seen-user-count mr-2 list-counts">{page.seenUsers.length}</span>
`seen-user-count`は消していただけると。

2021-08-05 05:11 UTC, merged