Imprv/6815 ssr sidebar
weseek/growi pull request #4099
Opened 2021-08-03 12:25 UTC by shinichi0617

2021-08-04 01:27 UTC, shinichi0617 commented on src/stores/ui.tsx
> +  return useStaticSWR(key);
TODO call save api

2021-08-04 01:27 UTC, shinichi0617 commented on src/components/BasicLayout.tsx
> -  const Sidebar = dynamic(() => import('../client/js/components/Sidebar'), { ssr: false });
↑に移動

2021-08-04 01:29 UTC, shinichi0617 commented on src/stores/ui.tsx
> +  const sidebarDefaultWidth = 320;
デフォルト値みたいなのをこいつが持ってて良いものか

2021-08-04 01:31 UTC, shinichi0617 commented on src/stores/ui.tsx
> +  const isServer = typeof window === 'undefined';
バックエンドが整備されたらisServerとかで出し分ける必要もないかな？（ssrだろうがなんだろうがAPI callして保存されてる幅を取得する）

2021-08-04 01:32 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +const SkeltonSidebar = (props: Props) => {
スケルトンSidebarを定義。
いまのところglobal-navigationの部分をSidebarNav入れつつコンテンツは入れ込んでない

2021-08-04 01:33 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +  return (showSkelton ? <SkeltonSidebar {...props} />
↓の変更はslekton常態かどうかで出し分けたのでその文インデントがずれただけ

2021-08-04 03:55 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +  const [showSkelton, setSkelton] = useState(true);
skelton用に定義

2021-08-04 03:56 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +  const [sidebarWidthCached, setSidebarWidthCached] = useState(productNavWidth);
画面初期化時に用意したproductNavWidthでサイズを初期化

2021-08-04 03:57 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +    mutateProductNavWidth(newWidth);
dragによるサイズ変更時にmuteteを呼び出す

2021-08-05 12:35 UTC, shinichi0617 commented on src/stores/ui.tsx
> +  if (isServer) {
Sidebarのdynamic importを変えた際にそのままだとLocalstorageにアクセスしにいこうとして結果エラーになっちゃうので一旦回避のために条件追加した。
本来的にはSSRのタイミングではこれ自体が呼ばれないのが正しいと思うのでSidebarの方後続タスクで見直す予定

2021-08-05 12:35 UTC, shinichi0617 commented on src/stores/ui.tsx
> +  if (isServer) {
上と同じく
Sidebarのdynamic importを変えた際にそのままだとLocalstorageにアクセスしにいこうとして結果エラーになっちゃうので一旦回避のために条件追加した。
本来的にはSSRのタイミングではこれ自体が呼ばれないのが正しいと思うのでSidebarの方後続タスクで見直す予定

2021-08-10 08:59 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +  return (showSkelton ? <SkeltonSidebar {...props} />
てのとhtml構造は、 https://youtrack.weseek.co.jp/issue/GW-7078 タスクで対応するので、ステートの管理とイベントハンドラが問題なさそうであれば一旦マージしてもらったほうが良いかもしれない。

2021-08-10 09:06 UTC, shinichi0617 commented on src/client/styles/scss/_sidebar.scss
> +    &:hover .ak-navigation-resize-button.resizable.normal-state {
resizableというクラスをつけることで、drawerモードの挙動を表現した（といってもボタンのマウスカーソルをポインタにしたのみだけど）ただし7078のタスクで多少構造変わるのでそっちで改めて見てもらったほうが良いかもしれない。

2021-08-10 09:06 UTC, shinichi0617 commented on src/client/styles/scss/_sidebar.scss
> +      .resizable.grw-navigation-draggable-hitarea {
↑と同様。

2021-08-10 09:55 UTC, yuki-takei requested changes

2021-08-10 09:55 UTC, yuki-takei commented on src/client/js/components/Sidebar.tsx
> +  const [showSkelton, setSkelton] = useState(true);
`isMounted` として、default false の変数にする。

2021-08-10 09:55 UTC, yuki-takei commented on src/stores/ui.tsx
> +  const isServer = typeof window === 'undefined';
isServer かどうかで場合分けする実装はなくていい。ssr 時に初期値がはいる見込み。
https://swr.vercel.app/docs/with-nextjs

逆にそれまではデフォルト値が必要なので、それを page 側でハードコードしておくのがよい。

2021-08-10 09:55 UTC, yuki-takei commented on src/client/js/components/Sidebar.tsx
> +  return (showSkelton ? <SkeltonSidebar {...props} />
isCollapsed とか isDrawerMode という外郭は共用するんじゃないかな。スケルトン表示だろうが開閉状態とかは再現するはずなので。コンテンツ側がスケルトンになるかどうかで場合分けになる。

2021-08-10 09:55 UTC, yuki-takei commented on src/client/js/components/Sidebar.tsx
> +  const [sidebarWidthCached, setSidebarWidthCached] = useState(productNavWidth);
これは不要かも

2021-08-12 14:43 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +      <div>Skelton Contents!!!</div>
一旦ただのdivにまでシュリンク

2021-08-12 14:46 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +                    { isMounted ? <SidebarContents></SidebarContents> : <SidebarSkeltonContents {...props} /> }
Skeltonで置き換えるのはここのみに狭めた

2021-08-12 15:23 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> -const sidebarDefaultWidth = 320;
定義場所変えたのでここでは不要

2021-08-12 15:24 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +  productNavWidth: number
将来のために定義しておく

2021-08-12 15:25 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +  const { data: currentProductNavWidth, mutate: mutateProductNavWidth } = useCurrentProductNavWidth(productNavWidth);
propsで渡ってきたものを引数に渡す

2021-08-12 15:26 UTC, shinichi0617 commented on src/client/js/components/Sidebar.tsx
> +      // TODO call API and save DB
このタイミングでAPI呼んでDBに保存予定

2021-08-12 15:29 UTC, shinichi0617 commented on src/stores/ui.tsx
> +  return useStaticSWR(key);
↑やっぱり違った。こっちはあくまでstaticにキャシュするのみ

2021-08-12 15:30 UTC, shinichi0617 commented on src/pages/admin/[[...path]].tsx
> +  productNavWidth: number;
pageのpropsとして定義

2021-08-12 15:31 UTC, shinichi0617 commented on src/pages/admin/[[...path]].tsx
> +  productNavWidth: number;
と思ったけどこれ/adminの方だな。pages/[...path].tsxに定義が正しい？

2021-08-12 15:33 UTC, shinichi0617 commented on src/pages/admin/[[...path]].tsx
> +  props.productNavWidth = 320;
定義場所怪しいけど、propsに変数定義して、DBから直接取得して渡す。
それらが回り回ってSidebarコンポーネントのpropsに渡ってそれがuseCurrentProductNavWidthの引数に渡って初期化される。

2021-08-12 15:44 UTC, yuki-takei requested changes

2021-08-12 15:44 UTC, yuki-takei commented on src/client/js/components/Sidebar.tsx
> +                    { isMounted ? <SidebarContents></SidebarContents> : <SidebarSkeltonContents {...props} /> }
GlobalNavigation もスケルトン用意してほしい

2021-08-12 15:44 UTC, yuki-takei commented on src/pages/admin/[[...path]].tsx
> +  productNavWidth: number;
- admin はサイドバーないからいらない。`pages/[[...path]].tsx` が正しい
- `/share/*` など、サイドバーを読み込まない画面もあるので全体に適用はできない
- `/user/*` とかはサイドバーが必要なので入れる必要がある
    - SidebarProps とかを新設して交差型(Intersection types)にするのがいいかも(後続タスクでよい)

2021-08-12 17:06 UTC, shinichi0617 commented
一旦マージ🐟

2021-08-12 17:06 UTC, merged