Fix/gw 6897 behavior when moving recursively
weseek/growi pull request #4101
Opened 2021-08-04 04:08 UTC by miya

## 概要
再起的にページを移動したときに親ページが意図しないページに作成されてしまう問題を修正しました。

## 再現
parent/ --> parent/child2 に rename しようとするとき

### Before
<img width="202" alt="スクリーンショット 2021-08-04 13 06 53" src="https://user-images.githubusercontent.com/34241526/128120740-03d6b3a2-e53c-498b-92a7-1763f998917c.png">

### After
<img width="140" alt="スクリーンショット 2021-08-04 13 07 41" src="https://user-images.githubusercontent.com/34241526/128120750-d9a082ee-27b3-4ef1-8e39-195cef75d246.png">

2021-08-04 05:48 UTC, yuki-takei commented
gitの歴史をちょっと調べてほしい。

今回のPRって、同じような修正を前にやっていたけれどそれが先祖返りしたのを元に戻す修正？

2021-08-04 09:23 UTC, yuki-takei commented
以下の手順を踏んでください

1. page.test.js に、今回のケースを追加し、修正前のコードでテストする(fail するはず)
2. このPRの修正を施してテスト(success するはず)
3. テストコード込みで再度 PR

2021-08-22 03:30 UTC, miya commented on packages/app/src/server/service/page.js
> +    await streamToPromise(readStream);
stream-to-promise に stream 持たせたことにより、stream が終了するまで待たせるようにしました。

2021-08-22 03:30 UTC, miya commented on packages/app/src/server/service/page.js
> +
親ページのリネームより先に、子供のページのリネームを先に実行させるようにしました。master のコードでは renamePage で先に親の path がリネームされます。この時点では意図している path にリネームされている。次に renameDescendantsWithStream で子供の path がリネームされます。ここでリネームする対象の path を正規表現でクエリしているが先にリネームされた親の path がこのクエリに含まれてしまっているため、子供とみなされ再リネームされてしまっていると思っています。

2021-08-22 19:55 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +
逆のケースを考えてもう少しだけ実装を工夫しないといけないかもしれない。

# より深い階層への移動(今回のケース)
`/level1` とその子孫全てを `/level1/level2` に移動させる場合。  
これは子孫を先に処理することで解消することがわかっている

# より浅い階層への移動
`/level1` が存在しない状態で、`/level1/level2` とその子孫全てを `/level1` に移動させる場合を考える。
この時、`/level1/level2/level2` というページがもし存在していたら、先に処理をすることで確実にエラーが発生してしまう気がする。  
これもテストがほしい。

# その他の懸念点

```new RegExp(`^${escapeStringRegexp(targetPage.path)}`, 'i');```
これって、trailing slash いらないのかな？全然無関係なはずの `/level1-2021H1` みたいなのも一緒に処理されないだろうか

2021-08-22 20:09 UTC, yuki-takei requested changes

2021-08-22 20:09 UTC, yuki-takei commented on packages/app/src/test/service/page.test.js
> +      });
renameDescendantsWithStreamSpy を使うテストと使わないテストに分けてください。

これまでのテストはメソッド単体の動きをテストするもので、「renameDescendantsWithStream が想定する挙動をするならば、このメソッドの動きはこうなるはず」というテストだった。これはこれで意味があるので、そのままにしておけばよい。

一方、そのタイプのテストしかなかったために、今回の問題のように親ページの移動と子孫ページの移動が連動した際に発生する問題をカバーするテストが存在しなかった。これは renameDescendantsWithStream の spy を用意しない test suite (describe から始まるブロック)を、このファイルに新たに作れば良い。

2021-08-24 17:43 UTC, miya commented on packages/app/src/test/service/page.test.js
> +      const expectPage3 = await Page.findOne({ path: '/level1/level2/level2' });
リネーム後期待されるページの path を一部修正しました。下記の画像の通り、`存在するパス以外を名前変更する` にチェックマークが入っている場合 `重複したパス` はリネームされるべきでは無いと判断しました。

[before]
level1/level2

[after]
level1/level2/level2

<img width="799" alt="スクリーンショット 2021-08-25 2 29 40" src="https://user-images.githubusercontent.com/34241526/130663467-303fdb0e-9db6-4ee8-90fc-b5651d34fbf3.png">

2021-08-25 03:17 UTC, yuki-takei approved these changes

2021-08-25 03:19 UTC, merged