Feat/6450 growi side validation
weseek/growi pull request #4102
Opened 2021-08-04 11:33 UTC by hakumizuki

GW-6922 サポートしていないコマンドが実行された時に本体側がリクエストを弾く　を実装しました。

**コミットNo. b4890cd：**
ミドルウェアを追加して権限をチェックするようにしました。

https://user-images.githubusercontent.com/58432773/128173754-a9db3c6f-3926-4439-b1b9-4e4eee885dee.mov

**コミットNo. 7be00a2 :**
今まではコマンドのパーミッションがないときは何も起こらずにただ実行できないだけでしたが、ユーザーにメッセージを送信するようにしました。新ストーリーに向けて急ぎたかったのでこのタスクでついでに実装しました。

https://user-images.githubusercontent.com/58432773/128173430-d56c01cd-2e40-4a77-b8ed-ca1b8d269030.mov

2021-08-04 12:09 UTC, yuki-takei requested changes

2021-08-04 12:09 UTC, yuki-takei commented on src/server/routes/apiv3/slack-integration.js
> +    }
```
export const supportedGrowiActions: RegExp[] = [
  /^search:/,
  
];
```
的なもの(またはそれを自動生成して返すユーティリティ)を作ろう。

2021-08-04 12:09 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    let didAnyCommandRun = false;
名前をもっとシンプルに

2021-08-04 12:09 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +          generateMarkdownSectionBlock(`It is not allowed to run *'${growiCommand.growiCommandType}'* command from this channel.`),
この実装ではどのチャンネルからコマンドを打っても受け付けないので、それとわかるメッセージに

2021-08-04 12:51 UTC, hakumizuki commented on packages/slackbot-proxy/src/controllers/slack.ts
> +          generateMarkdownSectionBlock(`It is not allowed to run *'${growiCommand.growiCommandType}'* command from this channel.`),
from this channel -> to this GROWI に変更しました。

2021-08-04 12:57 UTC, hakumizuki commented on src/server/routes/apiv3/slack-integration.js
> +  router.post('/proxied/commands', verifyAccessTokenFromProxy, CheckCommandPermission, async(req, res) => {
without proxyの権限設定に関しては後続タスクで新ストーリーを作成して実装します。

後続タスク: GW-7028 without Proxyでもコマンドごとの権限の設定を可能にするストーリーを作成する

2021-08-04 13:01 UTC, hakumizuki commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    let didAnyCommandRun = false;
isCommandPermitted にしました。

2021-08-06 05:40 UTC, hakumizuki commented on src/server/routes/apiv3/slack-integration.js
> +    }
packages/slack/src/utils/get-supported-growi-actions-regexps.ts

にユーティリティを作りました。

2021-08-06 09:20 UTC, hakumizuki commented
block_actionでの動作確認動画を撮りました。

https://user-images.githubusercontent.com/58432773/128488321-23c8b811-7bc4-4ed4-9db0-21f8d9d79589.mov

2021-08-06 11:00 UTC, yuki-takei approved these changes

2021-08-06 11:00 UTC, merged