Imprv/gw6778 hit an api to change password
weseek/growi pull request #4103
Opened 2021-08-04 13:11 UTC by kaoritokashiki

## Task
GW-6778 [back]「パスワードを再設定する」ボタンを押したときに、apiを叩いてパスワードを更新することができる

2021-08-04 13:19 UTC, kaoritokashiki commented on src/server/routes/index.js
> +  app.put('/_api/forgot-password'      , applicationInstalled, forgotPassword.api.put);
`/personal-setting/password` では、middlewareにvalidatorを挟んでいますね。

```
    password: [
      body('oldPassword').isString(),
      body('newPassword').isString().not().isEmpty()
        .isLength({ min: 6 })
        .withMessage('password must be at least 6 characters long'),
      body('newPasswordConfirm').isString().not().isEmpty()
        .custom((value, { req }) => {
          return (value === req.body.newPassword);
        }),
    ],
```

2021-08-04 13:34 UTC, kaoritokashiki commented on src/client/js/services/AppContainer.js
>      }
re.data から okが取得できませんでしたので、res.statusText === 'OK'を追加しました。

2021-08-04 13:35 UTC, kaoritokashiki commented on src/client/js/components/PasswordResetExecutionForm.jsx
> +  const email = passwordResetElem.textContent;
`getElementById`で emailを取得

2021-08-04 13:41 UTC, yuki-takei requested changes

2021-08-04 13:41 UTC, yuki-takei commented on src/client/js/services/AppContainer.js
> +  }
apiPost 同様、csrf token を送ってください

2021-08-04 13:41 UTC, yuki-takei commented on src/server/routes/forgot-password.js
> +  api.put = async(req, res) => {
名前変えてください

2021-08-04 13:41 UTC, yuki-takei commented on src/server/routes/forgot-password.js
> +      return res.apiv3({ userData });
他の api v1 系エンドポイント実装に倣って、`res.json(ApiResponse.success());` を使ってください

2021-08-04 13:41 UTC, yuki-takei commented on src/client/js/services/AppContainer.js
> +    if (res.data.ok || res.statusText === 'OK') {
ApiResponse.success を使えば res.data.ok のチェックで統一できるはず。

2021-08-04 13:41 UTC, yuki-takei commented on src/server/routes/index.js
> +  app.put('/_api/forgot-password'      , applicationInstalled, forgotPassword.api.put);
サーバー側でもやる必要があります。

2021-08-05 07:06 UTC, kaoritokashiki commented on src/server/routes/apiv3/forgot-password.js
> +  };
## 参考
`/personal-settings`の `validator.password`

```
    password: [
      body('oldPassword').isString(),
      body('newPassword').isString().not().isEmpty()
        .isLength({ min: 6 })
        .withMessage('password must be at least 6 characters long'),
      body('newPasswordConfirm').isString().not().isEmpty()
        .custom((value, { req }) => {
          return (value === req.body.newPassword);
        }),
    ],
```

2021-08-05 07:08 UTC, kaoritokashiki commented on src/client/js/components/PasswordResetExecutionForm.jsx
> +      });
サーバー側でもvalidation checkをするために `newPasswordConfirm`も渡しています。

2021-08-05 07:10 UTC, kaoritokashiki commented on src/server/routes/forgot-password.js
> -
## FB対応
api関連の処理は `apiv3`配下に移動しました。

2021-08-05 07:12 UTC, kaoritokashiki commented on src/server/routes/index.js
> +  app.put('/_api/forgot-password'      , applicationInstalled, forgotPassword.api.put);
`validator.password`をmiddlewareに追加しました。

2021-08-05 07:12 UTC, kaoritokashiki commented on src/server/routes/forgot-password.js
> +  api.put = async(req, res) => {
apiv3配下に移動したので、この記述は消しました。

2021-08-05 07:12 UTC, kaoritokashiki commented on src/server/routes/forgot-password.js
> +      return res.apiv3({ userData });
apiv3配下に移動したので、この記述は消しました。

2021-08-05 07:13 UTC, kaoritokashiki commented on src/client/js/services/AppContainer.js
> +    if (res.data.ok || res.statusText === 'OK') {
なるほどです。
apiPutは必要なくなったので削除しました。

2021-08-05 07:15 UTC, kaoritokashiki commented on src/server/routes/apiv3/forgot-password.js
> +  router.put('/', validator.password, apiV3FormValidator, async(req, res) => {
パスワードリセットを実行するときは、ユーザーはログインしていないので
middlewareに `accessTokenParser `, `csrf`は入れていません。

2021-08-05 08:13 UTC, yuki-takei commented on src/server/routes/apiv3/forgot-password.js
> +  router.put('/', validator.password, apiV3FormValidator, async(req, res) => {
csrf はログインしているかどうかは関係なく入れる必要がある。

2021-08-05 08:21 UTC, yuki-takei requested changes

2021-08-05 08:21 UTC, yuki-takei commented on src/client/js/components/PasswordResetExecutionForm.jsx
> +      });
クライアントからサーバーに渡すのは、token と newPassword と newPasswordConfirm。
サーバーは token から email を得る。

2021-08-05 08:21 UTC, yuki-takei commented on src/server/routes/apiv3/forgot-password.js
> +  router.put('/', validator.password, apiV3FormValidator, async(req, res) => {
クライアントからサーバーに渡すのは、token と newPassword と newPasswordConfirm。
サーバーは token から PasswordResetOrder を得て、そこから email を得る。
また、その前に PasswordResetOrder が expire していないかどうかをチェックする必要がある。
また、PasswordResetOrder を失効させる後続タスクも必要。

2021-08-05 15:57 UTC, kaoritokashiki commented on src/server/routes/apiv3/forgot-password.js
> +  router.put('/', validator.password, apiV3FormValidator, async(req, res) => {
memo:
csrfはそのリクエストがフォームを通して送られてることを保証するためのもの

2021-08-05 16:01 UTC, kaoritokashiki commented on src/client/js/components/PasswordResetExecutionForm.jsx
> +      });
修正しました。

2021-08-05 16:08 UTC, kaoritokashiki commented on src/server/routes/apiv3/forgot-password.js
> +  router.put('/', csrf, validator.password, apiV3FormValidator, async(req, res) => {
FB: middlewareにcsrfを挿入

2021-08-05 16:35 UTC, yuki-takei requested changes

2021-08-05 16:35 UTC, yuki-takei commented on src/server/routes/apiv3/forgot-password.js
> +    const passwordResetOrder = await PasswordResetOrder.findOne({ token });
見つからなかった場合と失効した場合の対応が必要(後続タスクでも良い)

2021-08-05 16:35 UTC, yuki-takei commented on src/server/routes/apiv3/forgot-password.js
> +    const user = await User.findOne({ email });
見つからなかった場合とユーザーの状態がアクティブではなかった場合の対応が必要(後続タスクでも良い)

2021-08-05 16:35 UTC, yuki-takei commented on src/server/routes/apiv3/forgot-password.js
> +    const appUrl = appService.getSiteUrl();
order を作る時も、該当するユーザーが見つからなかった場合とユーザーの状態がアクティブではなかった場合の対応が必要だな(後続タスクでも良い)

2021-08-05 16:43 UTC, yuki-takei requested changes

2021-08-05 16:43 UTC, yuki-takei commented on src/server/routes/apiv3/forgot-password.js
> +      return res.apiv3({ userData });
serializeUserSecurely を通す必要がある

2021-08-08 05:31 UTC, kaoritokashiki commented on src/server/routes/apiv3/forgot-password.js
> +      return res.apiv3({ userData });
修正しました。

2021-08-08 05:31 UTC, kaoritokashiki commented on src/server/routes/apiv3/forgot-password.js
> +    const appUrl = appService.getSiteUrl();
後続タスクで着手します。

2021-08-08 05:31 UTC, kaoritokashiki commented on src/server/routes/apiv3/forgot-password.js
> +    const user = await User.findOne({ email });
後続タスクで着手します。

2021-08-08 05:31 UTC, kaoritokashiki commented on src/server/routes/apiv3/forgot-password.js
> +    const passwordResetOrder = await PasswordResetOrder.findOne({ token });
承知です、後続タスクで着手します。

2021-08-09 10:57 UTC, merged