added isTextLintEnabled key in user collection
weseek/growi pull request #4109
Opened 2021-08-06 05:59 UTC by kaoritokashiki

2021-08-06 07:01 UTC, yuki-takei commented
> ユーザー設定のタブに「編集設定」といった項目を追加する場合新しくモデルを作成するべきではと思ってきましたがいかがでしょうか。

完全に collection が別の model じゃなくてもいいけど、embed なオブジェクトとして持つのは悪くないアイデア。
今 localStorage に保存してる keymap とか indent size とか Mathjax rendering ON/OFF とかもそこに押し込めたり…

相談させて欲しい。

2021-08-24 15:02 UTC, kaoritokashiki commented on packages/app/src/server/models/user.js
> +    defaultSettingsForNewPage: defaultSettingsForNewPageSchema,
新しくページを作成したときのdefaultの設定は user collectionに追加しましたが、
各ページごとの現在の設定(currentSettings)はpage collectionに格納する感じになりますかね。

2021-08-24 15:25 UTC, kaoritokashiki commented on packages/app/src/server/models/user.js
> +    defaultSettingsForNewPage: defaultSettingsForNewPageSchema,
GW-7209 currentEditorSettingsをpage collectionに追加する
後続タスクです。

2021-08-25 03:08 UTC, yuki-takei requested changes

2021-08-25 03:08 UTC, yuki-takei commented on packages/app/src/server/models/user.js
> +    defaultSettingsForNewPage: defaultSettingsForNewPageSchema,
> Editor画面で切り替えられる現在の設定(currentSettings)はpage collectionに格納する感じになりますかね。

No.
ユーザー毎の設定なんだからこれも user collection

2021-08-25 03:08 UTC, yuki-takei commented on packages/app/src/server/models/user.js
> +    defaultSettingsForNewPage: defaultSettingsForNewPageSchema,
- defaultSettingsForNewPage の名前が悪いし defaultSettingsForNewPageSchema の名前も悪い
    - あとから更新するんだから default ではないよね

2021-08-25 03:08 UTC, yuki-takei commented on packages/app/src/server/models/user.js
> +  };
このメソッドはあえて用意する必要はないかなあ。save も呼び出し側でやればいいし。

2021-08-25 08:58 UTC, kaoritokashiki commented on packages/app/src/server/models/user.js
> +  };
削除しました。

2021-08-25 08:59 UTC, kaoritokashiki commented on packages/app/src/server/models/user.js
> +
とりあえずTextLintを有効にするかしないかのみ追加しました。

2021-08-25 09:03 UTC, kaoritokashiki commented on packages/app/src/server/models/user.js
> +    defaultSettingsForNewPage: defaultSettingsForNewPageSchema,
- editorCurrentSettings
- editorDefaultSettingsForNewPage
`editor`をつけた方がわかりやすいと思いつけました。

2021-08-25 09:30 UTC, merged