Feat/7073 remove hard coded settings
weseek/growi pull request #4123
Opened 2021-08-10 06:53 UTC by stevenfukase

codemirror-textlint.jsでhard codedだった設定をCodeMirrorEditorから取得できるように改修しました。

2021-08-10 06:57 UTC, stevenfukase commented on packages/app/src/client/util/codemirror/codemirror-textlint.js
> +  }, {});
ruleModulesListを使わず、rules[rule.name] = require(`textlint-rule-${rule.name}`)だとエラーが出ます。

2021-08-10 07:32 UTC, yuki-takei requested changes

2021-08-10 07:32 UTC, yuki-takei commented on packages/app/src/client/util/codemirror/codemirror-textlint.js
> +};
クライアントサイドでは import 文を使ってください

2021-08-10 07:32 UTC, yuki-takei commented on packages/app/src/client/util/codemirror/codemirror-textlint.js
> +  }, {});
- なんのエラー？
    - おそらく require を使っているから出るものだと思うが

2021-08-10 07:39 UTC, yuki-takei requested changes

2021-08-10 07:39 UTC, yuki-takei commented on packages/app/src/client/util/codemirror/codemirror-textlint.js
> +export default function createValidator(rulesConfigArray) {
default export ではなく named export に変更

2021-08-10 07:39 UTC, yuki-takei commented on packages/app/src/client/util/codemirror/codemirror-textlint.js
> +export default function createValidator(rulesConfigArray) {
このユーティリティ、TypeScript で書いてください。

2021-08-10 07:39 UTC, yuki-takei commented on packages/app/src/client/util/codemirror/codemirror-textlint.js
> +    rules[rule.name] = ruleModulesList[rule.name];
- ruleModulesList 側に対応するものがない場合はログに出力してください
    - 存在しなくても正常動作するように

2021-08-11 08:29 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +      },
このようにインストールされていないルールを代入した際、codemirror-textlint.tsでFilterを掛けた上でlogを出すように改修しました

2021-08-11 11:07 UTC, merged