Imprv/7091 refactoring middleware
weseek/growi pull request #4131
Opened 2021-08-11 12:40 UTC by kaoritokashiki

2021-08-15 16:32 UTC, kaoritokashiki commented
増山さんから助言いただきましたが、どうすれば正解かわからずなので一旦PR出します。
<img width="800" alt="Screen Shot 2021-08-15 at 23 20 29" src="https://user-images.githubusercontent.com/59536731/129485515-8911131e-f1dd-4bc4-a049-edb0b23b37bd.png">

2021-08-15 16:47 UTC, kaoritokashiki commented on packages/app/src/components/PasswordResetExecutionForm.jsx
> +        /* token, */ newPassword, newPasswordConfirm,
21行目でtokenを取り出して、セットしているんですけど、
- `window.location.pathname` も `/forgot-password/${token}`と同じ値を取得できることが判明しました。
どっちの方がいいとかありますかね...?

2021-08-15 16:50 UTC, kaoritokashiki commented on packages/app/src/components/PasswordResetExecutionForm.jsx
> +        newPassword, newPasswordConfirm,
21行目でURLからtokenのみを取り出して、セットしているんですけど、
- `window.location.pathname` だと `/forgot-password/${token}`(`/forgot-password`も含まれる)と同じ値を取得できることが判明しました。
どっちの方がいいとかありますかね...?

2021-08-15 17:31 UTC, yuki-takei requested changes

2021-08-15 17:31 UTC, yuki-takei commented on packages/app/src/components/PasswordResetExecutionForm.jsx
> +        newPassword, newPasswordConfirm,
大差ないけどどちらかといえば元のコードのように put の body に埋め込んだ方がいい

2021-08-15 17:31 UTC, yuki-takei commented on packages/app/src/server/middlewares/password-reset.js
> +      return next(createError(400, 'Token not found'));
res.redirect しながら next(err) するという選択肢はない

- この middleware の名前を InjectResetOrderByTokenMiddleware に変える
- redirect はせず、next(err) だけ活かす方でよい
    - エラーは forgot-password.js 側で inner middleware function を作り、そちらで条件分岐させてリダイレクトする
- token が無い場合は `/login` にリダイレクトではなく、400 エラー画面を表示
    - 攻撃者に対しては rate limit で対応

2021-08-15 17:31 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/forgot-password.js
> +    const passwordResetOrder = req.DataFromPasswordResetOrderMiddleware;
middleware 側で req に付けている変数名がおかしい。あと camelCase に。

2021-08-15 17:31 UTC, yuki-takei commented on packages/app/src/server/middlewares/password-reset.js
> +      return next(createError(400, 'passwordResetOrder is null or expired or revoked'));
こちらも同じく next(err) だけ活かして、リダイレクトは forgot-password.js 側の inner middleware function

2021-08-24 06:44 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/forgot-password.js
> +    const { passwordResetOrder } = req;
middlewareで取得したpasswordResetOrderを使用しています。

2021-08-24 06:46 UTC, kaoritokashiki commented on packages/app/src/server/middlewares/inject-reset-order-by-token-middleware.js
> +    }
middlewareで処理を中断(return)せずに、req.errorにエラー用のオブジェクトを挿入しました。

2021-08-24 08:40 UTC, yuki-takei requested changes

2021-08-24 08:40 UTC, yuki-takei commented on packages/app/src/server/middlewares/inject-reset-order-by-token-middleware.js
> +  const forgotPassword = require('../routes/forgot-password')(crowi, app);
この require いらないよね？

2021-08-24 08:50 UTC, merged

2021-08-24 08:51 UTC, kaoritokashiki commented on packages/app/src/server/middlewares/inject-reset-order-by-token-middleware.js
> +  const forgotPassword = require('../routes/forgot-password')(crowi, app);
すみません、見落としです。削除しました。