Feat/7018 p2g validation
weseek/growi pull request #4148
Opened 2021-08-13 04:00 UTC by hakumizuki

2021-08-13 04:14 UTC, hakumizuki commented
GW-7018 GROWI 本体で proxy からのリクエストを適切に制限できる　を実装しました。

今回のタスクは P to G に限っているので、if 文を強制で true にするなどして必ず P から通信が飛ぶようにして検証動画を撮りました。

https://user-images.githubusercontent.com/58432773/129303966-d5fcea39-dc1c-4abf-867d-1be28764e8ae.mov

2021-08-16 21:19 UTC, yuki-takei requested changes

2021-08-16 21:19 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +    // MOCK DATA DELETE THIS GW-6972 ---------------
69行目の `// when /relation-test` のコードが早期リターンになるので、DBアクセスが必要なコードはその後ろに持ってくる

2021-08-16 21:19 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +      if (commandName === '_id') continue;
この iteration ちょっと不可解。

`channelsObject` attribute はどこにいったの？`_id` と並列に commandName が並ぶ想定のデータにするからこんな変な continue が必要になるんだと思う。モデル側を工夫してこの iteration block をもっと綺麗に。

2021-08-17 03:22 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +    // MOCK DATA DELETE THIS GW-6972 ---------------
上に持っていきました。

2021-08-17 03:23 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +      if (commandName === '_id') continue;
確かに、、。channelsObj を Mapで扱う形にしました。

2021-08-17 13:43 UTC, merged