Lintが無効のときにGutterwo
weseek/growi pull request #4149
Opened 2021-08-13 04:26 UTC by stevenfukase

<img width="92" alt="Screen Shot 2021-08-13 at 13 13 51" src="https://user-images.githubusercontent.com/66785624/129304742-78d375b7-f47e-4491-8594-31185c980050.png">
<img width="71" alt="Screen Shot 2021-08-13 at 13 14 51" src="https://user-images.githubusercontent.com/66785624/129304743-a40dd4e4-fce8-4744-ac27-6607a1abdb33.png">

2021-08-13 04:32 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    const textlintConfig = [
この2つがDBから来ることを想定

2021-08-16 21:02 UTC, yuki-takei requested changes

2021-08-16 21:02 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    }
ここから上の処理に関しては、render が走るごとに初期化されてしまうのは冗長。

2021-08-19 02:29 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +
render()の中からこちらの処理を移しました。
問題なく動きました。

2021-08-19 11:32 UTC, yuki-takei requested changes

2021-08-19 11:32 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +
クラスコンポーネントなのにここに this とか出てくるのはとても気持ちが悪いな。
initTextlintSettings みたいなメソッドに押し込んで、constructor とか componentWillMount から呼んでください。

2021-08-20 07:05 UTC, merged