apply rate limit
weseek/growi pull request #4154
Opened 2021-08-15 16:29 UTC by kaoritokashiki

2021-08-15 16:53 UTC, kaoritokashiki commented on packages/app/src/server/routes/index.js
> +});
ここに記述するのは微妙かなぁ...

15分以内に パスワードリセット実行フォームのページのリクエストがあった場合、上記のメッセージが表示されます。

2021-08-15 17:34 UTC, yuki-takei requested changes

2021-08-15 17:34 UTC, yuki-takei commented on packages/app/src/server/routes/index.js
> +});
このファイルではとりあえずここしか書けないからいいかなあ…
apiv3 側(put 用のエンドポイント)もケアが必要。そっちは各ファイルに書く感じで。

2021-08-16 14:16 UTC, kaoritokashiki commented on packages/app/src/server/routes/index.js
> +});
承知です。
>apiv3 側(put 用のエンドポイント)
に関しては、`password-reset.js`のmiddlewareで`passwordResetOrder.isRevoked`の場合、putの中の処理が実行されないことになっているので、apiLimiterのケアは不要かなと考えたのですがその場合はいかがでしょうか??

2021-08-16 16:03 UTC, yuki-takei requested changes

2021-08-16 16:03 UTC, yuki-takei commented on packages/app/src/server/routes/index.js
> +});
revoke して1つの token を無効化したとしてもブルートフォースアタックされたら `PasswordResetOrder.findOne({ token });` が繰り返し実行さるので、レート制限しておくにこしたことはないです。

2021-08-16 23:00 UTC, kaoritokashiki commented on packages/app/src/server/routes/index.js
> +});
なるほどです!!!!

2021-08-16 23:54 UTC, merged