Feat/7017 restrict request from slack on slack proxy side
weseek/growi pull request #4163
Opened 2021-08-19 05:44 UTC by zahmis

2021-08-24 04:38 UTC, zahmis commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +    const fromChannel = req.body.channel_name; /* || payload.channel.name; */
こちら現在 taichi-m が改修中です

2021-08-24 04:38 UTC, zahmis commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +    const relation = await SlackAppIntegrationMock.findOne({ tokenPtoG });
mock 化

2021-08-24 04:38 UTC, zahmis commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +      const SlackAppIntegrationMock = mongoose.model('SlackAppIntegrationMock');
mock 化

2021-08-24 04:38 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +    const relations = await this.relationMockRepository.createQueryBuilder('relation_mock')
mock 化

2021-08-24 04:38 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/growi-to-slack.ts
> +        // HARD CORDING
relation-test 時に mock 化
後ほど、適切な ui を作成し、そこから操作する予定

2021-08-24 04:38 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +      switch (growiCommand.growiCommandType) {
ch が権限を持つかを判断

2021-08-24 04:38 UTC, zahmis commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +import { RelationMock } from '~/entities/relation-mock';
mock 化

2021-08-24 04:38 UTC, zahmis commented on packages/slackbot-proxy/src/services/SelectGrowiService.ts
> +import { RelationMock } from '~/entities/relation-mock';
mock 化

2021-09-02 02:56 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> -    if (!isCommandPermitted) {
relationService に委譲

2021-09-02 10:48 UTC, yuki-takei requested changes

2021-09-02 10:48 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const channelName = payload.channel?.name || privateMeta?.body?.channel_name || privateMeta?.channelName;
privateMeta の parse など、後回しにしてもいい処理は後の方(register や unregister の後)でやる

2021-09-03 03:37 UTC, merged