Fix/respone slack reviews
weseek/growi pull request #4175
Opened 2021-08-23 13:09 UTC by zahmis

2021-08-23 13:25 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +import { AuthorizeCommandMiddleware, AuthorizeInteractionMiddleware, AuthorizeEventsMiddleware } from '~/middlewares/slack-to-growi/authorizer';
新規 Middleware を追加

2021-08-23 13:25 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> -    if (body.type === 'url_verification') {
url_verification の処理は middlware に移動
理由は、この challenge を返答する処理は middleware よりも先に実行する必要があるため。
流れとしては、
- slack app 設定側で request url を入力
- challenge パラメータが返答 => 200 ok と (slack app 側)でなる
- 晴れて、body に team_id などの params が渡る。
- この team_id などの値を使って、AuthorizeEventsMiddeware にて token 情報を取得できる。

2021-08-23 13:25 UTC, zahmis commented on packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
> +class AuthorizerService {
共通化

2021-08-24 08:14 UTC, yuki-takei requested changes

2021-08-24 08:14 UTC, yuki-takei commented on packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
> +   setAuthorizedData = async(req:SlackOauthReq, res:Res):Promise<InstallationQuery<boolean>|void> => {
- 共通化が中途半端
    - やるなら interaction 用の middleware の後半部分も別に切り出して
- 名前がよくない
    - setter に見える
- 返り値のタイプ指定が不可解

2021-08-24 08:14 UTC, yuki-takei commented on packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
> +    }
- 更に別の middleware に切り出す
- authorizer.ts にあるのは違和感

2021-08-28 01:11 UTC, yuki-takei requested changes

2021-08-28 01:11 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    await postWelcomeMessage(client, req.body.event.channel);
全ての種類のイベントで postWelcomeMessage してはいけないんじゃないかな

2021-08-28 01:11 UTC, yuki-takei commented on packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
> +const getCommomMiddleware = (installerService, logger) => {
typo: commom -> common

2021-08-28 01:11 UTC, yuki-takei commented on packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
> +    }
common と名が付くならこういう分岐が必要な処理はここには含まないように

2021-08-28 06:48 UTC, zahmis commented on packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
> +const extractInstallationQueryFromBody = (body): InstallationQuery<boolean> => {
body から teamId,enterpriseId, isEnterpriseInstall を取得する method を新規作成しました。

2021-08-30 04:32 UTC, yuki-takei requested changes

2021-08-30 04:32 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    if (req.body.event.type) {
条件を限定して

2021-08-30 04:32 UTC, yuki-takei commented on packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
> +    isEnterpriseInstall = payload.is_enterprise_install === 'true';
interaction 固有の処理

2021-08-30 05:08 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    if (req.body.event.type === 'app_home_opened') {
すみません。条件抜けてました。

2021-08-30 06:29 UTC, yuki-takei requested changes

2021-08-30 06:29 UTC, yuki-takei commented on packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
> +const getCommonMiddleware = (query, installerService, logger) => {
引数と返り値の型を書いて

2021-08-30 07:24 UTC, zahmis commented on packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
> +const getCommonMiddleware = (query:InstallationQuery<boolean>, installerService:InstallerService, logger:Logger) => {
返り値苦戦したので、省略しています。

2021-08-30 07:30 UTC, yuki-takei approved these changes

2021-08-30 07:30 UTC, merged