Feat/7004 frontend slackbot permission settings
weseek/growi pull request #4199
Opened 2021-08-26 08:25 UTC by hakumizuki

GW-7004 [フロント] 許可するチャンネルを入力する欄を作成する

を実装しました。

## コメント
* デザインのFBが来たら後続タスク作って修正します。
* State の更新が textarea の変化に応じて動くことは log で確認しました。
* GW-7006 [コントローラー実装] slackAppIntegration のモデルを mongoose 化 <- で実際のデータによる処理を追加します。

見た目:

https://user-images.githubusercontent.com/58432773/130928505-ee57c101-bbbe-4420-baa7-f9fb96b627ef.mov

2021-08-30 08:02 UTC, hakumizuki commented
最終決定した DB の形で実装しました。
ドロップダウンになりました。
デザインは後続タスクで決定します。(GW-7266 [Design] デザインを相談して修正する 7004の後続)

https://user-images.githubusercontent.com/58432773/131306176-417cafbf-dc0b-4e80-a86e-0182c1c6f9d6.mov

2021-08-31 08:38 UTC, yuki-takei requested changes

2021-08-31 08:38 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const permissionTypes = {
ts 的に考えると enum にするだろうから PascalCase がいいかな

2021-08-31 08:38 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +      }
isArray の場合を先に処理して、その後は三項演算子ってのがスマートかと。

2021-08-31 08:38 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +                  <div className="row-6 my-1 mb-2" key={commandName}>
`row-6` なんてないと思うんだけど

2021-08-31 08:38 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +                  <div className="row-6 my-1 mb-2" key={commandName}>
コードの重複があると思うので、ここから下の UI 群を同じファイル内で別コンポーネントとして定義するなり、別 tsx として切り出すなりして。

2021-09-01 10:11 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const permissionTypes = {
PascalCase になりました

2021-09-01 10:12 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +      }
boolean の方をチェックしてから三項演算子にしました

2021-09-01 10:12 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +                  <div className="row-6 my-1 mb-2" key={commandName}>
row-5 にしました

2021-09-01 10:13 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +                  <div className="row-6 my-1 mb-2" key={commandName}>
2つのコンポーネントに分けてリファクタしました

2021-09-01 10:14 UTC, hakumizuki commented
8d5ab90 のコミットの内容はこのタスクで必須ではありませんが、フロントエンドのタスク中にやっておいた方がいいと判断したので変更を加えました

2021-09-01 14:10 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const getInitialCurrentPermissionTypes = () => {
useMemo を使って

2021-09-01 14:12 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const getUpdatedPermissionSettings = (prevState, commandName, value) => {
これはステートに依存しないユーティリティメソッドなので、component の外に出す

2021-09-01 14:12 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const updatePermissionsForBroadcastUseCommandsState = (e) => {
useCallback を使って

2021-09-01 14:13 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +    });
setPermissionsForBroadcastUseCommandsState にはメソッドを渡すんじゃなくて getUpdatedPermissionSettings の結果の値をそのまま渡しちゃだめなのかな

2021-09-01 14:13 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const updatePermissionsForSingleUseCommandsState = (e) => {
useCallback を使って

2021-09-01 14:14 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  };
これもユーティリティメソッド

2021-09-01 14:14 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const updateChannelsListForBroadcastUseCommandsState = (e) => {
useCallback を使って

2021-09-01 14:14 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const updateChannelsListForSingleUseCommandsState = (e) => {
useCallback を使って

2021-09-01 14:15 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  };
defaultValue に突っ込む値は、この時点で計算しておいてよい(このメソッドを作る意味があまりない)

2021-09-02 02:54 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +                  <div className="row-6 my-1 mb-2" key={commandName}>
row にしました

2021-09-02 02:54 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +      <div className="row-5 my-1 mb-2" key={commandName}>
ないです。row にしました。

2021-09-02 03:01 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const getUpdatedPermissionSettings = (prevState, commandName, value) => {
Calculate the initial value in advance da1723a で外に出しました

2021-09-02 03:01 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  };
Calculate the initial value in advance da1723a で外に出しました

2021-09-02 03:02 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  };
Calculate the initial value in advance da1723a で外に出しました

2021-09-02 04:22 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const getInitialCurrentPermissionTypes = () => {
この関数は必要なくなりました

2021-09-02 04:24 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  };
Calculate the default value in advance 9f120de で修正しました

2021-09-02 04:25 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const getUpdatedPermissionSettings = (prevState, commandName, value) => {
Moved utility functions to the outside of the component 6a7eec9 で外に出しました

2021-09-02 04:26 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  };
Moved utility functions to the outside of the component 6a7eec9 で外に出しました

2021-09-02 05:32 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const updatePermissionsForSingleUseCommandsState = (e) => {
使うようにしました

2021-09-02 05:32 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const updateChannelsListForSingleUseCommandsState = (e) => {
使うようにしました

2021-09-02 05:37 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +    });
getUpdatedPermissionSettings はそもそも prevState から newState を生成するためのユーティリティです。
なので引数に prevState が欲しいのですが、prevState は setHogeState の callback に渡されるので直接 getUpdatedPermissionSettings を setPermissionsForBroadcastUseCommandsState に渡すようにはできないと思っています。

2021-09-02 10:18 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +    });
最終的にこの setState() の使い方は 3種類に分かれると思っていて、

1. 直接値を渡しちゃう setState('value')
2. 前の state を使って計算する setState(prev => prev + 1)
3. 前の state と identical なオブジェクトを return する setState(prev => prev) <- prev はオブジェクトなど

で、基本的に、直前の state の値を使って計算を行う場合は必ず 2 or 3 にした方がいいと思います。完全に上位互換だと思うので。

2と3の使い分けは、レンダリングして欲しいかしてほしくないかだと思っています。(2は再レンダリングされる)
今回、2 と 3 を使っている箇所は、
2. getUpdatedPermissionSettings
3. getUpdatedChannelsList
です。
2. はドロップダウンの表示を変えるために再レンダリングが必要なので新しいオブジェクトを返していて、
3. は textarea が再レンダリングされるとフォーカスが外れてしまうので prev と同一のオブジェクトを返しています。

2021-09-02 12:06 UTC, merged