removed throwing err
weseek/growi pull request #4204
Opened 2021-08-27 09:11 UTC by kaoritokashiki

入力したemailから
そのユーザーが存在しない場合もしくはアクティブではない場合には登録されていないよというemailを送信するようにしました。
(正常系で返す)

<img width="673" alt="Screen Shot 2021-08-27 at 18 50 32" src="https://user-images.githubusercontent.com/59536731/131108989-68593d1b-3de3-47fb-b094-b7b4674deda6.png">

2021-08-28 01:18 UTC, yuki-takei requested changes

2021-08-28 01:18 UTC, yuki-takei commented on packages/app/resource/locales/ja_JP/notifications/notActiveUser.txt
> +{{ appTitle }} からパスワード再設定のリクエストがありましたが、このemailは登録されておりません。
タイトルだけでなく、siteUrl を入れてください

2021-08-28 01:18 UTC, yuki-takei commented on packages/app/resource/locales/ja_JP/notifications/notActiveUser.txt
> +GROWI開発チームより
「GROWI 開発チームより」はおかしい

2021-08-30 02:57 UTC, kaoritokashiki commented on packages/app/resource/locales/ja_JP/notifications/notActiveUser.txt
> +{{ appTitle }} からパスワード再設定のリクエストがありましたが、このemailは登録されておりません。
siteUrlも挿入しました。

2021-08-30 02:57 UTC, kaoritokashiki commented on packages/app/resource/locales/ja_JP/notifications/notActiveUser.txt
> +GROWI開発チームより
削除しました。

2021-08-30 03:00 UTC, merged