codemirror-textlintパッケージ化
weseek/growi pull request #4205
Opened 2021-08-27 09:53 UTC by stevenfukase

**8/30 - FB対応後動作確認済み**

- Depの数を考えてブランチはfeat/7189-add-japanese-rulesから生やしました
- 動作確認済み
<img width="221" alt="Screen Shot 2021-08-27 at 19 08 22" src="https://user-images.githubusercontent.com/66785624/131111164-dac50631-4495-40ce-928c-1dcdd2aba4be.png">

- 本体側から間違ったRuleを渡した場合のLoggerも正常に動きました
<img width="202" alt="Screen Shot 2021-08-27 at 19 10 11 1" src="https://user-images.githubusercontent.com/66785624/131111574-9d672958-7903-46aa-816c-ac46466bba61.png">
<img width="450" alt="Screen Shot 2021-08-27 at 19 10 34" src="https://user-images.githubusercontent.com/66785624/131111581-d0e7d810-63e9-4f1f-9cab-812b5a4457ff.png">

2021-08-28 01:25 UTC, yuki-takei requested changes

2021-08-28 01:25 UTC, yuki-takei commented on packages/codemirror-textlint/package.json
> +  "dependencies": {
devDependencies よりも上に置いてください

2021-08-28 01:25 UTC, yuki-takei commented on packages/codemirror-textlint/package.json
> +  "version": "1.0.0",
app のバージョンと揃える

2021-08-28 01:25 UTC, yuki-takei commented on packages/codemirror-textlint/package.json
> +    "universal-bunyan": "^0.9.2"
universal-bunyan の peerDependencies は全て入れてください

2021-08-28 01:25 UTC, yuki-takei commented on packages/codemirror-textlint/package.json
> +    "codemirror": "^5.62.3",
codemirror だけ peerDependencies にしてください。

2021-08-28 01:26 UTC, yuki-takei commented
production 向けに足りないものがいくつかあります

- build script の追加
- packages/app/docker/Dockerfile の修正

2021-08-30 03:20 UTC, stevenfukase commented on packages/codemirror-textlint/package.json
> +  },
すべてエラーが出ず実行できました

2021-08-30 03:21 UTC, stevenfukase commented on packages/codemirror-textlint/src/index.ts
> +import { loggerFactory } from './utils/logger';
utilをsrcの中に移動しました

2021-08-30 04:51 UTC, merged