Feat/7247 add japanese and common schema
weseek/growi pull request #4208
Opened 2021-08-30 05:29 UTC by stevenfukase

2021-08-30 06:58 UTC, yuki-takei requested changes

2021-08-30 06:58 UTC, yuki-takei commented on packages/app/src/server/models/user.js
> +    },
- このデフォルト値は textlint パッケージ側に移動
- User モデルにはデフォルト設定の値は保存しない

2021-08-31 05:03 UTC, stevenfukase commented on packages/codemirror-textlint/src/index.ts
> +  }
8/31: ルールが指定されてない場合、デフォルトでインストールされてるすべてのルールを適応するように改修しました。

2021-08-31 05:06 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    this.textlintConfig = [];
ここが空だとデフォルトを適応

2021-08-31 05:43 UTC, yuki-takei requested changes

2021-08-31 05:43 UTC, yuki-takei commented on packages/app/src/server/models/user.js
> +    },
common はいいとしても、言語が増えた時にフィールドがどんどん増えていくのはいやだなあ。

2021-09-02 04:00 UTC, closed without merging