[WIP] Performance optimization for large drawio diagrams
weseek/growi pull request #4221
Opened 2021-09-01 01:10 UTC by kaishuu0123

# Problem
If you paste the contents of the following text file into the edit screen, editing will be too slow.

[growi_drawio_becomeheavy.txt](https://github.com/weseek/growi/files/7087520/growi_drawio_becomeheavy.txt)

# Summary
* Add enable/disable toggle for drawio rendering. (similar Mathjax Option)
* Add drawio block fold extension for CodeMirror.

# ToDO
* Always keep the drawio block closed.
    * When start page edit.
    * When edit of drawio is finished.

2021-12-15 09:48 UTC, yuki-takei requested changes

2021-12-15 09:48 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    // drawio セクション(:::drawio)の更新完了後にセクションを fold する
日本語 NG

2021-12-15 09:48 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    const endDrawio = /^:::$/;
RegExp はメソッド外で予め作っておきたい

2021-12-15 09:48 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +  }
MarkdownDrawioUtil に逃がすべきロジックがありそう。

2021-12-15 09:48 UTC, yuki-takei commented on packages/app/src/client/util/codemirror/drawio-fold.ext.js
> +    let endDrawio = /^:::/;
foldDrawioSection で必要な RegExp と共通化したい

2021-12-16 02:27 UTC, kaishuu0123 commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    // drawio セクション(:::drawio)の更新完了後にセクションを fold する
対応しました

2021-12-16 02:28 UTC, kaishuu0123 commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    const endDrawio = /^:::$/;
なるべく MarkdownDrawioUtil を使うように修正しましたが、
https://github.com/weseek/growi/pull/4221/files#diff-7e637cf1547428225fa66dc99b0dddf308d7cdc5250d8676d8418add999aa830R3
という ext.js の中で import しても大丈夫か若干不安です。
(グローバル汚染はなかったはずなので、多分大丈夫だろう、とは思っています)

2021-12-16 02:30 UTC, kaishuu0123 commented on packages/app/src/client/util/codemirror/drawio-fold.ext.js
> +    let endDrawio = /^:::/;
https://github.com/weseek/growi/pull/4221#discussion_r770179103 と同様の対応 (なるべく MarkdownDrawioUtil を使うように修正)

2021-12-17 13:21 UTC, merged