refactor
weseek/growi pull request #4251
Opened 2021-09-05 14:34 UTC by zahmis

2021-09-05 14:48 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> -
以下の部分を relationService へ移しました。

2021-09-05 14:48 UTC, zahmis commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +    // initialize params
interactions 操作のたびに初期化を行います。

そうしなければ、前回の interactions の内容(relation など)が残ってしまい、
Next や Share などの interaction を実行した時、
1 つだけ Share されたり Next ページを表示されることはなく、
relation の数だけ表示されるという現象が発生します。

2021-09-05 20:58 UTC, yuki-takei requested changes

2021-09-05 20:58 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +    // initialize params
service をステートフルにしてはいけない。つまり、allowedRelations 等のフィールドを用意してはいけない。

ビジネスロジックをなるべく service 層に移すという考え方は間違っていないけれど、まずはインスタンスのスコープというものを理解しよう。以下は Java/Spring の文書だけれど、DI の祖であり Ts.ED も近い考えで実装されているので、「Spring」を全て「Ts.ED」に置き換えても意味は通じるはず。

https://qiita.com/NagaokaKenichi/items/34bc62e572256c5710e1

因みに、SlackCtrl も RelationService もどちらも Singleton インスタンスであることに留意。

2021-09-06 09:15 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +  let payload:any;
interactions の場合必要です

2021-09-06 09:15 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> -      const linkUrlList = Array.from(disallowedGrowiUrls).map((growiUrl) => {
こちら postNotAllowedMessage を適用させてなかったので適用

2021-09-06 17:01 UTC, yuki-takei requested changes

2021-09-06 17:01 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +  ):Promise<checkPermissionForInteractionsResults> {
1 relation に対応するメソッドはそのまま残せばよい。
複数 relations に対応するメソッドは、上記の 1 relation 対応メソッドを呼び出す。

2021-09-06 17:01 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +    await Promise.all(relations.map(async(relation) => {
Promise.all では、GROWI A のチェックでエラーが起こった場合に GROWI B のチェックの結果もろとも reject されてしまう。

2021-09-07 05:16 UTC, zahmis commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +    const results = await Promise.allSettled(relations.map(async(relation) => {
Promise.allSettled を使用します。
relations に reject が含まれる場合は rejectedResults に入れます。
rejectedResults をもとに controller 層で postEphemeralErrors を投げます。

2021-09-07 05:16 UTC, zahmis commented on packages/slackbot-proxy/src/controllers/slack.ts
> +      await postEphemeralErrors(rejectedResults, body.channel_id, body.user_id, authorizeResult.botToken!);
ここで return してません。
理由は 不良 relation があっても他の relation が適正な場合は、
以下で行う postNotAllowedMessage や allowedRelations.map を行いたいからです。

2021-09-07 05:16 UTC, zahmis commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +  ):Promise<checkPermissionForInteractionsResults> {
切り出します。

2021-09-07 10:37 UTC, yuki-takei requested changes

2021-09-07 10:37 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +  async relationsResult(
これって後続タスク？
第一引数が `relation: Relation` のメソッドがどこかにないといけない。

2021-09-08 03:51 UTC, zahmis commented on packages/slackbot-proxy/src/services/RelationsService.ts
> +  async relationsResult(
後続タスクで 1 relation に対応する method 作成します。

2021-09-08 03:51 UTC, merged