Imprv/gw7221 get io method
weseek/growi pull request #4256
Opened 2021-09-06 06:18 UTC by kaoritokashiki

2021-09-06 06:31 UTC, kaoritokashiki commented on packages/app/src/server/models/notification.ts
> +    }
crowi code

```
  start = () => {
    if (this.app === null) {
      throw new Error('Must call init() before start().')
    }

    const server = http.createServer(this.app).listen(this.port, () => {
      console.log('[' + this.node_env + '] Express server listening on port ' + this.port)
    })
    const io = socketIO(server, { transports: ['websocket'] })
    if (this.redisOpts) {
      io.adapter(socketIORedis(this.redisOpts))
      debug('Using socket.io-redis')
    }
    io.sockets.on('connection', (socket) => {
      debug('Websocket CONNECTED, socket.id:', socket.id)
    })

    this.io = io

    return this.app
  }

```

2021-09-06 06:47 UTC, kaoritokashiki commented on packages/app/src/server/models/notification.ts
> +    }
```
  getDefaultSocket() {
    if (this.io == null) {
      throw new Error('Http server has not attached yet.');
    }
    return this.io.sockets;
  }
```

2021-09-06 16:37 UTC, yuki-takei requested changes

2021-09-06 16:37 UTC, yuki-takei commented on packages/app/src/server/models/notification.ts
> +    }
まずは [多層アーキテクチャ](https://ja.wikipedia.org/wiki/%E5%A4%9A%E5%B1%A4%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%81%E3%83%A3) を読んでください。

層ごとに参照して良い方向がある。今の登場人物で言うと、

```
[User に近い] => Controller => Service => Model => [Data に近い]
```

で、左側の層は右側の層を参照してよいが、逆は NG。  
つまり、model の中で socketIoService に依存してはいけない。

2021-09-07 06:05 UTC, kaoritokashiki commented on packages/app/src/server/crowi/index.js
> +
modelからservice層のアクセスはNGなので、crowi配下のindex.jsにてget methodを定義し、
それをmodel側で呼び出しています。

2021-09-07 10:49 UTC, yuki-takei requested changes

2021-09-07 10:49 UTC, yuki-takei commented on packages/app/src/server/crowi/index.js
> +
crowi を何でも屋として頼るのは古い実装方式なのでやめよう。

頭の整理が必要だと思うので口頭 or meet で相談してください。

## memo

- サービス層を利用する
    - `pageEvent.on` で grep、models/page.js は一旦無視で、PageService, SearchService  を参考にする
- イベントシステムの整理
    - EventEmitter は node システム内でのイベント伝播に使う
    - SocketIoService はサーバークライアント間でのイベント伝播に使う
    - 今回はたぶん両方必要

2021-09-08 11:04 UTC, kaoritokashiki commented on packages/app/src/server/models/notification.ts
> -  });
NotificationServiceに移動させました。

2021-09-08 11:12 UTC, kaoritokashiki commented on packages/app/src/server/service/notification.ts
> +    }
- notificationServiceにて、発火されたイベントを検知する
- socketIoServiceにて発火

2021-09-08 11:14 UTC, kaoritokashiki commented on packages/app/src/server/crowi/index.js
> +    notification: new (require('../events/notification'))(this),
eventにnotificationを追加

2021-09-08 11:24 UTC, kaoritokashiki commented on packages/app/src/server/service/notification.ts
> +  }
- notificationServiceにて、発火されたイベントを検知する
- socketIoServiceにて発火

2021-09-08 11:36 UTC, yuki-takei requested changes

2021-09-08 11:36 UTC, yuki-takei commented on packages/app/src/server/events/notification.ts
> +module.exports = NotificationEvent;
NotificationEvent 自体いらないと思う。

EventEmittor を使うのは、離れた場所へのイベント伝播を行うケースで、今回は pageEvent とか commentEvent で emit されたイベントを観測する。Notification Model が CRUD されたことをどこかに伝える必要は今のところなさそう(もちろん今後必要になったら作る)。

2021-09-08 17:08 UTC, kaoritokashiki commented on packages/app/src/server/service/in-app-notification.ts
> +      // }
## TODO
- GW-7402 Client側でsocketをlistenできる
こちらは後続タスクで着手します。

2021-09-08 17:10 UTC, kaoritokashiki commented on packages/app/src/server/events/comment.ts
> +};
イベントの発火のメッセージは、logger.infoを使用しています。

2021-09-09 09:15 UTC, yuki-takei requested changes

2021-09-09 09:15 UTC, yuki-takei commented on packages/app/src/server/models/comment.js
> +    commentEvent.emit('update', savedComment.creator);
この hook、async メソッドにするか emit を then の中に入れるかしないといけない。(もちろん async 化の方が望ましい)

2021-09-09 09:15 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification.ts
> +      commentEvent.emit('update', inAppNotification.user);
これはおかしい。意味を考えて。
crowi 実装に引きずられず、wiki に書いた指針通りに。

2021-09-09 09:15 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification.ts
> +    if (inAppNotification) {
判定式はガイドライン通りに

2021-09-09 09:15 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification.ts
> +  inAppNotificationSchema.statics.removeActivity = async function(activity) {
サービス層に移そう

2021-09-09 09:15 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification.ts
> +      commentEvent.emit('update', inAppNotification.user);
これはおかしい。意味を考えて。
crowi 実装に引きずられず、wiki に書いた指針通りに。

2021-09-09 09:15 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification.ts
> +    if (inAppNotification) {
判定式はガイドライン通りに

2021-09-10 04:30 UTC, kaoritokashiki commented on packages/app/src/server/models/comment.js
> +    commentEvent.emit('update', savedComment.creator);
post hook全体を async 化 しました。

2021-09-12 16:48 UTC, kaoritokashiki commented on packages/app/src/server/models/in-app-notification.ts
> +    if (inAppNotification) {
すみません、失念していました。修正しました。

2021-09-13 02:22 UTC, kaoritokashiki commented on packages/app/src/server/models/in-app-notification.ts
> +  inAppNotificationSchema.statics.removeActivity = async function(activity) {
サービス層(inAppNotificationService)に移動しました。

2021-09-13 04:08 UTC, kaoritokashiki commented on packages/app/src/server/models/in-app-notification.ts
> +      commentEvent.emit('update', inAppNotification.user);
commentEventは model/comment.js のupdateCommentsByPageIdに移動しました。

2021-09-13 04:10 UTC, kaoritokashiki commented on packages/app/src/server/models/in-app-notification.ts
> +  inAppNotificationSchema.statics.removeActivity = async function(activity) {
removeByActivityを移すとなると、upsertByActivityもserviceに移すというとこでしょうか??

2021-09-13 04:26 UTC, kaoritokashiki commented on packages/app/src/server/events/notification.ts
> +module.exports = NotificationEvent;
削除し、comment Eventfileを作成しました。

2021-09-13 04:27 UTC, kaoritokashiki commented on packages/app/src/server/models/in-app-notification.ts
> +      commentEvent.emit('update', inAppNotification.user);
commentEventは model/comment.js のupdateCommentsByPageIdに移動しました。

2021-09-13 14:15 UTC, yuki-takei requested changes

2021-09-13 14:15 UTC, yuki-takei commented on packages/app/src/server/models/comment.js
> +    }
post save hook で Page モデルが更新されるのは、あまり良くはないけれど昔のコードの名残なのでここでリファクタしないのは許容する。

2021-09-13 14:15 UTC, yuki-takei commented on packages/app/src/server/models/comment.js
> +    await commentEvent.emit('update', savedComment.creator);
post save は、create の場合もあれば update の場合もある。ここでどちらかに絞って emit するのは違うんじゃないかな。

2021-09-13 14:15 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification.ts
> +      .populate({ path: 'activities', populate: { path: 'user' } })
GROWI では populate は使う側で行うやり方に統一している。
なのでこのメソッドは消して、このメソッドを使っている箇所ではそのまま find を使う形にしてよい。
skip/limit を使うにしても paginate 使う方が望ましい。

2021-09-13 14:15 UTC, yuki-takei commented on packages/app/src/server/service/in-app-notification.ts
> +  updateCommentEvent(): void {
initCommentEvent にしよう

2021-09-13 14:15 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification.ts
> +    const Activity = crowi.model('Activity');
Activity は直接 import すれば crowi は必要ない

2021-09-13 14:15 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification.ts
> +export default (crowi: Crowi) => {
crowi を引数にとる形式は不要な依存を増やしてしまうのでやめる

2021-09-13 14:15 UTC, yuki-takei commented on packages/app/src/server/service/in-app-notification.ts
> +    const InAppNotification = require('../models/in-app-notification')(this.crowi);
crowi を引数にとる形式は不要な依存を増やしてしまうのでやめる。
直接 import すればよい。

2021-09-15 15:09 UTC, kaoritokashiki commented on packages/app/src/server/models/comment.js
> +    }
承知しました。

2021-09-15 15:10 UTC, kaoritokashiki commented on packages/app/src/server/models/comment.js
> +    await commentEvent.emit('update', savedComment.creator);
create とupdateで処理を分けました。

2021-09-15 16:27 UTC, kaoritokashiki commented on packages/app/src/server/service/in-app-notification.ts
> +  updateCommentEvent(): void {
修正しました。

2021-09-15 16:27 UTC, kaoritokashiki commented on packages/app/src/server/models/in-app-notification.ts
> +    const Activity = crowi.model('Activity');
importを使って crowi 依存を解消しました。

2021-09-15 16:28 UTC, kaoritokashiki commented on packages/app/src/server/models/in-app-notification.ts
> +export default (crowi: Crowi) => {
消しました。

2021-09-15 16:28 UTC, kaoritokashiki commented on packages/app/src/server/service/in-app-notification.ts
> +    const InAppNotification = require('../models/in-app-notification')(this.crowi);
修正しました。

2021-09-15 16:43 UTC, kaoritokashiki commented on packages/app/src/server/models/in-app-notification.ts
> +      .populate({ path: 'activities', populate: { path: 'user' } })
GW-7482 [FB対応] populateをGROWI wayに置き換える
後続で着手します

2021-09-15 16:44 UTC, kaoritokashiki commented on packages/app/src/server/events/comment.ts
> +};
create / updateで分けてます。

2021-09-15 16:45 UTC, kaoritokashiki commented on packages/app/src/server/models/activity.ts
> +// });
GW-7481 removeActivityの実装
後続タスクで着手します。

2021-09-15 18:27 UTC, merged