Imprv/gw7228 create activity parameter
weseek/growi pull request #4257
Opened 2021-09-06 07:54 UTC by kaoritokashiki

2021-09-06 08:09 UTC, kaoritokashiki commented on packages/app/src/server/models/activity.ts
> +  // });
こちらは現状使用できないので、後続タスクで着手します。
GW-7345 events配下にActivityを定義し、crowi.eventで呼び出せるようにする

2021-09-06 08:11 UTC, kaoritokashiki commented on packages/app/src/server/models/comment.js
> +      .catch((err) => {});
元のコードは
https://github.com/crowi/crowi/blob/eecf2bc821098d2516b58104fe88fae81497d3ea/lib/models/comment.ts#L70-L75

2021-09-06 08:23 UTC, kaoritokashiki commented on packages/app/src/server/models/activity.ts
> +      // await Promise.all(notificationUsers.map(user => Notification.upsertByActivity(user, savedActivity)));
GW-7346 getNotificationTargetUsersを使用できるようにする
後続タスクで着手します。

2021-09-06 16:55 UTC, yuki-takei requested changes

2021-09-06 16:55 UTC, yuki-takei commented on packages/app/src/server/models/comment.js
> +      .catch((err) => {});
この実装、ベストではないがとりあえず crowi をなぞるという戦略が早いと思うので今はこれでよいです。
本来的には CommentService を作って、そちらから Comment, Activity モデルを操作したほうがいい。

2021-09-06 16:55 UTC, yuki-takei commented on packages/app/src/server/models/index.js
> +  Activity,
新しいモデルはここには追加しない。

2021-09-07 13:41 UTC, kaoritokashiki commented on packages/app/src/server/models/comment.js
> +      .catch((err) => {});
> comment が save される
post hook で commentEvent.emit する
NotificationService で観測して Notification にバラして永続化するとともに、socketIoService.emit する

ようにする。

2021-09-19 06:34 UTC, closed without merging