get config from db
weseek/growi pull request #4268
Opened 2021-09-07 08:25 UTC by stevenfukase

2021-09-07 08:51 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> -
コンテナに移行

2021-09-07 08:52 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +  lintRules: PropTypes.array,
空の状態で渡ってくるのを許容する(DBが空のときにエラーが出ていた)

2021-09-07 08:52 UTC, stevenfukase commented on packages/codemirror-textlint/src/index.ts
> +export const createValidator = (rulesConfigArray: RulesConfigObj[] | null): AsyncLinter<RulesConfigObj[] | null> => {
nullを許容

2021-09-07 08:54 UTC, stevenfukase commented on packages/codemirror-textlint/src/index.ts
> +        return (ruleModulesList[rule.name] != null && rule?.isEnabled !== false);
渡ってきたルールObjにisEnabled: falseがついてた場合、弾く

2021-09-07 11:25 UTC, yuki-takei requested changes

2021-09-07 11:25 UTC, yuki-takei commented on packages/app/src/components/PageEditor/Editor.jsx
> +                        retrieveEditorSettings={editorContainer.retrieveEditorSettings}
イベントの命名規則確認して

2021-09-07 11:25 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    await this.props.retrieveEditorSettings();
retrieveEditorSettings は CodeMirrorEditor で呼ぶのではなく、親が呼べばいいのではないか…？TextAreaEditor で使うデータも入ってるかもしれないし。

2021-09-08 08:22 UTC, yuki-takei requested changes

2021-09-08 08:22 UTC, yuki-takei commented on packages/codemirror-textlint/src/index.ts
> +        return (ruleModulesList[rule.name] != null && rule?.isEnabled !== false);
- optional chaining 使いすぎ
    - `data: any` の中身をチェックするときに使うならわかるけど、普通に ts 書いてたらこんなには使う必要ないはず
- filter 内でこの `rule` が null なことってあり得ないのでは？
    - もし配列に null が入ってしまうようであれば、先に別途 null 値だけ取り除く filter を通すとかそういう操作をすべき

2021-09-08 08:40 UTC, merged