Feat/setting permission in slack integration
weseek/growi pull request #4281
Opened 2021-09-08 10:57 UTC by zahmis

2021-09-10 23:07 UTC, yuki-takei requested changes

2021-09-10 23:07 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +const getPermissionTypeFromValue = (value) => {
どこからも参照されていないので、使わないなら消す

2021-09-13 04:37 UTC, zahmis commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +  }, [commandPermission]);
- commandPermission == null の場合を外に出しています。
- forEach を使わず、reduce を使うことによってスリムにしました。

2021-09-13 04:38 UTC, zahmis commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +const getUpdatedPermissionSettings = (prevState, commandName, value) => {
prevState => commandPermissionObj に変更

2021-09-13 04:38 UTC, zahmis commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +const getUpdatedChannelsList = (prevState, commandName, value) => {
prevState => commandPermissionObj に変更

2021-09-13 04:38 UTC, zahmis commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +  const [permissionsCommandsState, setPermissionsCommandsState] = useState({});
承知しました

2021-09-13 08:03 UTC, yuki-takei requested changes

2021-09-13 08:03 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +  const hiddenClass = Array.isArray(editingCommandPermission[commandName]) ? '' : 'd-none';
`editingCommandPermission[commandName]` をこの時点で一時変数に入れよう。

2021-09-13 08:03 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +              onClick={onPermissionTypeClicked}
null チェック

2021-09-13 08:03 UTC, yuki-takei commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +      }, {});
`const updatedState = {...commandPermission};` じゃだめなのかな

2021-09-13 08:44 UTC, zahmis commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +      }, {});
いけそうでした...
修正します

2021-09-13 08:44 UTC, zahmis commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +  const hiddenClass = Array.isArray(editingCommandPermission[commandName]) ? '' : 'd-none';
修正します

2021-09-13 08:44 UTC, zahmis commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +  function permissionTypeClickHandler(e) {
null check を追加しています

2021-09-13 08:44 UTC, zahmis commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
> +              onClick={onPermissionTypeClicked}
追加します

2021-09-13 08:51 UTC, yuki-takei requested changes

2021-09-13 08:51 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/slack-integration-settings.js
> +      'slackbot:withoutProxy:commandPermission': JSON.stringify(commandPermission),
JSON.parse ってどこでやってるんだろう

2021-09-13 10:44 UTC, zahmis commented on packages/app/src/server/routes/apiv3/slack-integration-settings.js
> +      'slackbot:withoutProxy:commandPermission': JSON.stringify(commandPermission),
ここでは不要でした。
config-loader に stirng で値を保持させるため。

2021-09-13 10:47 UTC, merged