Imprv/7376 user rooms
weseek/growi pull request #4290
Opened 2021-09-13 03:13 UTC by hakumizuki

2021-09-13 03:30 UTC, hakumizuki commented
GW-7376 ユーザーごと の room に適切なタイミングで join できる & join できているか確認できる
GW-7385 Page ごとの room に適切なタイミングで join&leave できる & growi server は Page.CRUD 時にその room に対して通知を飛ばすことができるか確かめる
GW-7390 [続・7385] Page.CRUD 時の通知が正常に動作する

を実装しました。

ブランチの名前に page 入ってませんが、ページの部分も一緒にやりました。

確認したこと：
* ページの編集、削除によって自分以外のユーザーに通知が送信され、ポップアップが表示される
* ユーザーごとの Room に join できる

今後の後続タスクでは、socketClientId の廃止をします。

2021-09-13 03:32 UTC, hakumizuki commented
socketIoService 用のユーティリティはいま service/utils/socket-io-helpers.ts に書いていますが、service/socket-io/socket-io.js 、service/socket-io/utils/socket-io-helpers.ts のように socket-io.js(サービスのファイル) ごと移動した方がいいですか？

2021-09-13 07:10 UTC, yuki-takei requested changes

2021-09-13 07:10 UTC, yuki-takei commented on packages/app/src/server/service/system-events/sync-page-status.ts
> +        .except(getRoomNameWithId(RoomPrefix.USER, user._id))
```
      socketIoService.getDefaultSocket()
        .except(getRoomNameWithId(RoomPrefix.USER, user._id))
```
この部分を簡単に取得するユーティリティメソッドって作れないかな？

自身も含め通知したいケースってほぼないだろうから、getDefaultSocketWithoutUser みたいなの作ってそれに `.in().emit()` 付けられたらいいなと。

2021-09-14 06:35 UTC, yuki-takei requested changes

2021-09-14 06:35 UTC, yuki-takei commented on packages/app/src/server/service/socket-io.js
> +  }
このメソッドを、「イベントハンドラ設定」と「ルームへの join 」とで分ける

2021-09-14 06:55 UTC, merged