bug fix
weseek/growi pull request #4291
Opened 2021-09-13 03:53 UTC by stevenfukase

2021-09-13 03:54 UTC, stevenfukase commented on packages/app/src/components/PageEditor/Editor.jsx
> -
Editor.jsxでは呼ばない

2021-09-13 03:54 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    this.initializeTextlint();
Rename

2021-09-13 03:57 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
>      this.textlintValidator = createValidator(rulesForValidator);
必ずonInitializeTextlintの後にcreateValidatorを呼ぶ必要がある。
逆で呼ばれていたことがバグの原因。

2021-09-14 07:57 UTC, yuki-takei requested changes

2021-09-14 07:57 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    await this.props.onInitializeTextlint();
null チェックが必要。
他のイベントハンドラ用 props も確認を。

2021-09-15 02:38 UTC, merged