Feat/restrict command each channel
weseek/growi pull request #4295
Opened 2021-09-13 08:01 UTC by zahmis

2021-09-13 14:34 UTC, yuki-takei requested changes

2021-09-13 14:34 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +      const commandRegExp = new RegExp(`(^${command}$)|(^${command}:\\w+)`);
この処理共通化したはずでは？

2021-09-13 14:34 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +    });
この Object.entries の中身まるごと共通化の対象だと思う。with proxy と同じことやってるし。

2021-09-13 14:34 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +  }
ここは以下の理由で今後リファクタの対象になるがとりあえずこのタスクではこのままでよい。

- middleware は next() or next(err) のみを行う
    - not allowed の旨を res.json するとしたらエラーハンドリングを行う別の middleware
- ベストは https://youtrack.weseek.co.jp/issue/GW-7441 のリファクタ方針に則り、response_url で not allowed の旨を返す

GW-7441 ストーリーの下に後続タスクだけ作っといてください。

2021-09-15 08:33 UTC, zahmis commented on packages/app/src/server/routes/apiv3/slack-integration-settings.js
> -            supportedCommandsForBroadcastUse: slackAppIntegration.supportedCommandsForBroadcastUse,
こちらおそらく修正もれ

2021-09-15 08:33 UTC, zahmis commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +    return res.send(`It is not allowed to run '${command}' command to this GROWI.`).status(403);
`    return res.status(403).send(`It is not allowed to run '${command}' command to this GROWI.`);`
上のコードでは、without で権限を制限すると GROWI sever 上では 403 が表示されるものの Slack 上では dispatch failed が発生しました。
status を後ろに持ってくると 発生しなかったので、res.send を先に実行しました

2021-09-15 08:33 UTC, zahmis commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +    return res.status(403).send('It is not allowed to run the command to this GROWI.');
こちら 適切に res.send されないため原因調査中
別タスクでやります

2021-09-15 10:49 UTC, yuki-takei requested changes

2021-09-15 10:49 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +    return res.send(`It is not allowed to run '${command}' command to this GROWI.`).status(403);
そんなことあるのか…？俄には信じがたい。

が、そもそも status 403 で返答するか、response_url を用いるかは、with proxy と without proxy で処理を分ける必要がありそう。

https://youtrack.weseek.co.jp/issue/GW-7441
ストーリー内の後続タスクになるかな。

2021-09-15 10:49 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +    return res.send(`It is not allowed to run '${command}' command to this GROWI.`).status(403);
それとは関係なく、Code scanning - Reflected cross-site scripting が表示されてると思うので、これは対応してください。必ずしも command を入れる必要ないと思う。

2021-09-15 11:23 UTC, zahmis commented on packages/app/src/server/routes/apiv3/slack-integration.js
> +    return res.send(`It is not allowed to run '${command}' command to this GROWI.`).status(403);
後続タスクで応用篇を実施します

2021-09-15 14:23 UTC, merged