Imprv/gw7410 refactoring to functional component
weseek/growi pull request #4300
Opened 2021-09-14 05:45 UTC by kaoritokashiki

2021-09-14 06:23 UTC, yuki-takei commented on packages/app/src/components/PageEditor/InAppNotificationDropdown.tsx
>    // }
いらないコードの整理は後続タスクを作って

2021-09-14 06:23 UTC, yuki-takei commented on packages/app/src/components/PageEditor/InAppNotificationDropdown.tsx
> +      // TODO: error handling
エラーハンドリングは後続タスクで

2021-09-15 06:19 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/InAppNotificationDropdown.tsx
> +      // TODO: error handling
GW-7472 通知をクリックすると、該当ページに遷移することができる
GW-7473 Notification Statusを fatch できる
GW-7474 Notification list をfetchできる

後続タスクを作成しました。

2021-09-15 06:20 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/InAppNotificationDropdown.tsx
>    // }
GW-7472 通知をクリックすると、該当ページに遷移することができる
GW-7473 Notification Statusを fatch できる
GW-7474 Notification list をfetchできる

後続タスクを作成しました。

2021-09-15 06:20 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/InAppNotificationDropdown.tsx
> +      // TODO: error handling
「GW-7473 Notification Statusを fatch できる」　にて行います。

2021-09-15 09:16 UTC, yuki-takei requested changes

2021-09-15 09:16 UTC, yuki-takei commented on packages/app/src/components/PageEditor/InAppNotificationDropdown.tsx
> +  isOpen: boolean
この interface 参照しなくなった？
もしそうなら削除を

2021-09-15 09:48 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/InAppNotificationDropdown.tsx
> +  isOpen: boolean
そうですね、削除しました。

2021-09-15 09:51 UTC, merged