GW-7469 デフォルトでonになってしまっているBugを修正
weseek/growi pull request #4308
Opened 2021-09-15 03:58 UTC by stevenfukase

2021-09-15 04:06 UTC, stevenfukase commented on packages/app/src/client/services/EditorContainer.js
> +    const textlintRules = data.textlintSettings?.textlintRules;
ついでに不要なOptional chainingを外す

2021-09-15 04:17 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    const lint = this.props.isTextlintEnabled === true ? this.codemirrorLintConfig : false;
バグ修正箇所

2021-09-15 06:27 UTC, yuki-takei requested changes

2021-09-15 06:27 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    const lint = this.props.isTextlintEnabled === true ? this.codemirrorLintConfig : false;
prop type が boolean ならこの判定はいらないはず

2021-09-16 04:31 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +  textlintRules: PropTypes.array,
Renameし忘れ

2021-09-16 04:31 UTC, stevenfukase commented on packages/app/src/server/models/editor-settings.ts
> +  isTextlintEnabled: { type: Boolean, default: false },
Bugの原因

2021-09-16 04:32 UTC, stevenfukase commented on packages/app/src/client/services/EditorContainer.js
> +
ついでにOptional Chainingを減らす処理

2021-09-16 04:37 UTC, stevenfukase commented on packages/app/src/client/services/EditorContainer.js
> +    if (data?.textlintSettings == null) {
ここのoptional chainingは取っちゃうとエラー出る
<img width="856" alt="Screen Shot 2021-09-16 at 11 44 19" src="https://user-images.githubusercontent.com/66785624/133550187-f6fb6289-6ccb-43cb-a63f-10d6214ebee6.png">

2021-09-16 08:10 UTC, merged