display growi bot version in footer
weseek/growi pull request #4310
Opened 2021-09-15 06:55 UTC by yuto-oweseek

変更点

- 画像のページの version の箇所に growi bot versionを表示
- 開発、プロダクション、どちらでも同じバージョンナンバーで問題ないと思ったため、共通化してあります

![footerにversion表示](https://user-images.githubusercontent.com/83065937/133385187-ed82d076-a94f-4609-bf8d-6f8f5282ba60.png)

2021-09-15 09:20 UTC, yuki-takei requested changes

2021-09-15 09:20 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/top.ts
> +    const growiBotVersion = process.env.GROWI_BOT_VERSION;
バージョンは環境変数を用意するのではなく、
`packages/slackbot-proxy/package.json` から読む

## 参考
https://github.com/weseek/growi/blob/61d8a0acd66d45962eb8c69a84368bee34dcf764/packages/app/src/server/crowi/index.js#L32-L32

2021-09-15 09:26 UTC, yuki-takei approved these changes

2021-09-16 04:28 UTC, yuto-oweseek commented on packages/slackbot-proxy/src/controllers/top.ts
> +    const growiBotVersion = process.env.GROWI_BOT_VERSION;
package.jsonから読み込む方法に変更しました。

2021-09-16 11:53 UTC, yuki-takei requested changes

2021-09-16 11:53 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/top.ts
> +import pkg from '@growi/slackbot-proxy/package.json';
この書き方だと本番では動かなくなるね(っていうのは結構高度な落とし穴なので申し訳ないが)

相対パスで書けなかった？
無理だったら、import じゃなくて require を使うとか、
それでもダメなら fs アクセスする or [read-pkg-up](https://www.npmjs.com/package/read-pkg-up) みたいなのを使うことになるのかも。

2021-09-17 10:02 UTC, yuto-oweseek commented on packages/slackbot-proxy/src/controllers/top.ts
> +import pkg from '@growi/slackbot-proxy/package.json';
相対パスだとciが通らず、`require`はできなかったため、fsを利用しました。

また、jsでは普通に`require`できたんですが、tsだとrequireでciが通らなかったため、コメント文を追加して`await import` を使いました。

2021-09-17 10:09 UTC, merged