Imprv/7495 commands interactions processors
weseek/growi pull request #4322
Opened 2021-09-17 06:57 UTC by hakumizuki

GW-7495 GrowiCommandProcessor, GrowiInteractionProcessor 実装 & 改修

を実装しました。

unregister, register, search で一応動作確認済みです。

2021-09-17 07:33 UTC, yuki-takei requested changes

2021-09-17 07:33 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +export class RegisterService {
implements GrowiInteractionProcessor してください

2021-09-17 10:40 UTC, hakumizuki commented on packages/slackbot-proxy/src/services/RegisterService.ts
> +export class RegisterService {
implements しました

2021-09-17 10:47 UTC, hakumizuki commented
InteractionHandledResult の実装方法が service 層で初期化したり、object.result、object.isTerminate で操作したりとやることが多いんですが、この実装の改善策ってありますか？

2021-09-17 12:11 UTC, yuki-takei requested changes

2021-09-17 12:11 UTC, yuki-takei commented on packages/slack/src/interfaces/growi-interaction-processor.ts
> +  isTerminate: boolean;
改めて見ると isTerminated か isTerminal かな。

2021-09-17 12:11 UTC, yuki-takei commented on packages/slack/src/interfaces/growi-interaction-processor.ts
> +export const initializeInteractionHandledResult = (): any => {
このメソッドの存在意義がよくわからない。
shouldHandle...の結果が false だった時に返すオブジェクトを作るにしても、any ではないだろう。

2021-09-18 13:39 UTC, hakumizuki commented on packages/slack/src/interfaces/growi-interaction-processor.ts
> +  isTerminate: boolean;
isTerminated にしました。

2021-09-18 13:41 UTC, hakumizuki commented on packages/slack/src/interfaces/growi-interaction-processor.ts
> +export const initializeInteractionHandledResult = (): any => {
関数である理由が自分もよくわからなくなったので、ただの定数オブジェクトにしました。
InteractionHandledResult はインターフェイスでコンストラクタを持たないので、その代わりに初期値を export しました。この方が使いやすいかなと思っているのですが、FB ください。

2021-09-19 13:23 UTC, yuki-takei requested changes

2021-09-19 13:23 UTC, yuki-takei commented on packages/slack/src/interfaces/growi-interaction-processor.ts
> +};
> 関数である理由が自分もよくわからなくなったので、ただの定数オブジェクトにしました。
> InteractionHandledResult はインターフェイスでコンストラクタを持たないので、その代わりに初期値を export しました。この方が使いやすいかなと思っているのですが、FB ください。

`InteractionHandledResult<V>` の性質が generics の V で決まる以上、初期値をここで定義するのは無意味ではないか？例えば V が boolean だったら初期値は false にしたくなるはず。

初期値は使う際にその場で object を生成すればいいだけでは？

2021-09-19 13:23 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/SelectGrowiService.ts
> +    const interactionHandledResult: any = initialInteractionHandledResult;
```
const result: InteractionHandledResult<SelectedGrowiInformation | null> = {
  result: null,
  isTerminated: false,
}
```
でいいんじゃないかな。`| null` を消したければ InteractionHandledResult を定義している側の `result` を `result?` にする必要がある。

2021-09-19 13:23 UTC, yuki-takei commented on packages/slack/src/interfaces/growi-command-processor.ts
> +  processCommand(growiCommand: GrowiCommand, authorizeResult: AuthorizeResult, body: {[key:string]:string}): Promise<void>
第三引数、もうちょっと汎用的にできるな。

UnregisterService で

> 'body' is defined but never used

が出ているので、回避のために `body?: {[key:string]:string}` がベター。

更に言えば渡したいものの型は各実装で違うので、`body: {[key:string]:string} & T` あるいはいっそのこと `context?: T` にするのがいいかな。

2021-09-19 16:41 UTC, hakumizuki commented on packages/slack/src/interfaces/growi-interaction-processor.ts
> +};
>InteractionHandledResult<V> の性質が generics の V で決まる以上、初期値をここで定義するのは無意味ではないか？例えば V が boolean だったら初期値は false にしたくなるはず。

確かにその通りです。
初期値は使う時に定義するようにしました。

2021-09-19 16:43 UTC, hakumizuki commented on packages/slackbot-proxy/src/services/SelectGrowiService.ts
> +    const interactionHandledResult: any = initialInteractionHandledResult;
今回はわざわざ null 型を明示的に示す意味がないのと、result? のほうが、result: V | null になるより管理が楽という理由で result? を選択しました。

2021-09-19 18:10 UTC, hakumizuki commented on packages/slack/src/interfaces/growi-command-processor.ts
> +  processCommand(growiCommand: GrowiCommand, authorizeResult: AuthorizeResult, body: {[key:string]:string}): Promise<void>
- body は必須のパラメータではないので body? にしました
- 利便性を保つためにデフォルトの型を {[key: string]: string} にして、汎用性向上と型システムの恩恵を生かすためにジェネリクスにしました
- デフォルトが {[key: string]: string} なので迷いましたが、ジェネリクスの時点で汎用性が高いので名前を body から context に変更しました

2021-09-19 18:33 UTC, merged