feat: make default selection of search range customizable
weseek/growi pull request #4332
Opened 2021-09-19 13:27 UTC by nakashimaki

#4331 の提案実装です。

`isAllReplyShown`が性格的に近いかと思い、参考にしながら実装してみました。  
[開発環境構築手順](https://docs.growi.org/ja/dev/startup-v2/launch-system.html#%E5%88%9D%E5%9B%9E%E8%B5%B7%E5%8B%95)を参考に「フロントエンド・バックエンドサーバーの起動」を実施しての動作確認は実施しています。

Web開発・GitHubともに不慣れですので不足している部分がありましたらご指摘ください。（Pullが難しいようでしたらCloseしていただいても構いません）

2021-09-20 17:18 UTC, yuki-takei requested changes

2021-09-20 17:18 UTC, yuki-takei commented on packages/app/resource/locales/zh_CN/admin/admin.json
> +      "select_search_scope_children_as_default_desc": "When the setting value is off, 'All pages' is used as default value of search range."
https://www.deepl.com/ 等で翻訳したものを入れていただけると助かります。

2021-09-20 17:22 UTC, yuki-takei commented
@nakashimaki PRありがとうございます:grinning:

全体的には問題なさそうです。
1箇所フィードバックで、zh_CN に関してこちら機械翻訳で構わないので入れてください。よろしくお願いします。

2021-09-20 22:12 UTC, nakashimaki commented on packages/app/resource/locales/zh_CN/admin/admin.json
> +      "select_search_scope_children_as_default_desc": "When the setting value is off, 'All pages' is used as default value of search range."
ご確認いただきありがとうございます。DeelL翻訳をベースに文言を周囲に合わせて整えたものを入れました。

2021-09-21 09:57 UTC, yuki-takei approved these changes

2021-09-21 09:57 UTC, merged