Imprv/7496 7444 payload accessor select service
weseek/growi pull request #4334
Opened 2021-09-20 11:23 UTC by hakumizuki

GW-7496 InteractionPayloadAccessor を使って any から値を取り出す処理を書いている箇所を減らす
GW-7444 SelectGrowiService の改修 [上記タスクと同時進行可]

を実装しました。

今回も変更多めです。次から変更ファイル数減らすように細かくします。

## 変更箇所
- InteractionPayloadAccessor を実装しました
- payload.hoge としていたところを accessor のメソッドを使うようにしました
- Select growi コマンドを動くようにしました
  - create コマンドが送られるところまでは確認済みですが、その後の挙動でバグがあるので本体改修と同時に直していきます

2021-09-20 17:11 UTC, yuki-takei requested changes

2021-09-20 17:11 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/SelectGrowiService.ts
> +  sendCommandBody: any,
入れすぎじゃないかなと。button の value に JSON.stringify して引き回すものなので、handleSelectInteraction で必要とされる最小限にしたい。

2021-09-20 17:11 UTC, yuki-takei commented on packages/slackbot-proxy/src/services/growi-uri-injector/block-elements/ButtonActionPayloadDelegator.ts
> +    return JSON.parse(action.value);
growi-uri-injector は GROWI の URL をマトリョーシカ構造で wrap/restore するものなので、今回のリファクタとは無関係に動作するはず。手を入れなくて良い。

もっとも、今回のリファクタでは responseUrl を引き回す構造になるので、本質的に growi-uri-injector は今後不要になる説はある。その場合、growi-uri-injector 自体を使わないようにする(消す)リファクタを別タスクでやればよいが、なんにせよこの PR での修正は中途半端なのでやめたい。

この変更を行わないと正常動作させることができない場合は別途相談してください。

2021-09-21 02:15 UTC, hakumizuki commented on packages/slack/src/interfaces/growi-interaction-processor.ts
> +  shouldHandleInteraction(interactionPayloadAccessor: any): boolean;
その通りです。修正しました。

2021-09-21 02:18 UTC, hakumizuki commented on packages/slackbot-proxy/src/services/growi-uri-injector/block-elements/ButtonActionPayloadDelegator.ts
> +    return JSON.parse(action.value);
select_growi アクションを処理する時に action.value が undefined になってしまうので、ここを変更する必要がありました。
この PayloadDelegator 群が何のために存在するのかインプットいただきたいです。

2021-09-21 03:34 UTC, hakumizuki commented on packages/slackbot-proxy/src/services/growi-uri-injector/block-elements/ButtonActionPayloadDelegator.ts
> +    return JSON.parse(action.value);
一旦 GW-7508 で見直すという旨のコメントをつけました。

2021-09-21 03:34 UTC, hakumizuki commented on packages/slackbot-proxy/src/services/SelectGrowiService.ts
> +  sendCommandBody: any,
sendCommandBody について見直した結果、本体で必要なパラメーターは SelectValue に含める必要がなかったので元の形に戻しました。

2021-09-21 08:52 UTC, merged