Imprv/gw7511 create in app notification file under apiv3
weseek/growi pull request #4336
Opened 2021-09-21 01:29 UTC by kaoritokashiki

2021-09-21 08:12 UTC, yuki-takei requested changes

2021-09-21 08:12 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/in-app-notification.ts
> +  router.get('/list', (req, res) => {
適切な middleware, validator の設定を(他の action でも同じ)

2021-09-21 08:12 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/in-app-notification.ts
> +  });
なぜ今更 promise の then/catch

2021-09-21 08:12 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/in-app-notification.ts
> +  });
ページング関連は mongoose-paginate-v2 を使う

2021-09-21 17:23 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/in-app-notification.ts
> +  });
GW-7482 [FB対応] populateをGROWI wayに置き換える(7346の後)
こちらで着手します。

2021-09-22 10:53 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/in-app-notification.ts
> +  router.get('/list', (req, res) => {
accessTokenParser, loginRequiredStrictly, csrf, をそれぞれのmiddlewareに設定しました。

2021-09-22 11:32 UTC, merged