Feat/7497 put ogp endpoints in meta tags
weseek/growi pull request #4339
Opened 2021-09-21 06:39 UTC by miya

## Task
GW-7497 public な wiki かつ public な ページの view（meta tag）に ogp/$(pageId) を挿入できるようにする

2021-09-21 08:56 UTC, yuki-takei requested changes

2021-09-21 08:56 UTC, yuki-takei commented on packages/app/src/server/views/layout/layout.html
> +  {% endif %}
`layout/layout.html` は適用範囲が広すぎる。
page インスタンスが存在しないページのことも考慮して。

2021-09-22 03:03 UTC, yuki-takei requested changes

2021-09-22 03:03 UTC, yuki-takei commented on packages/app/src/server/views/layout-growi/page.html
> +  <meta property="og:site_name" content="{{ appService.getAppTitle() }}">
他でやっているように
`{{ appService.getAppTitle() | preventXss }}`

2021-09-22 03:03 UTC, yuki-takei commented on packages/app/src/server/views/layout-growi/page.html
> +  <meta property="og:url" content="{{ appService.getSiteUrl() }}/{{ page.id }}" />
こちらも preventXss を入れる

2021-09-22 03:03 UTC, yuki-takei commented on packages/app/src/server/views/layout-growi/page.html
> +  <meta property="og:title" content="{{ page.path }}"/>
page_content.html でやっているように `{{ encodeURI(page.path) }}` にしたいんだけど、そうすると生成された画像側どうなる？

2021-09-22 09:41 UTC, miya commented on packages/app/src/server/views/layout-growi/page.html
> +  <meta property="og:title" content="{{ page.path }}"/>
- { page.path }}
```html
```

{{ encodeURI(page.path) }}
```html
```

2021-09-27 07:30 UTC, merged