imprv: fix tag count problem
weseek/growi pull request #4340
Opened 2021-09-21 07:18 UTC by yuto-oweseek

2021-09-21 09:00 UTC, yuki-takei requested changes

2021-09-21 09:00 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    });
- この処理はパフォーマンス的に問題がある

2021-09-22 07:18 UTC, yuto-oweseek commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    });
2回のupdateManyに変更し、bulkwriteに変更しました。

2021-09-22 09:37 UTC, yuki-takei requested changes

2021-09-22 09:37 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    const deletedPages = await Page.find({ status: Page.STATUS_DELETED });
まだパフォーマンス的に問題がある

2021-09-24 05:47 UTC, yuki-takei requested changes

2021-09-24 05:47 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    const OFFSET = 1000;
これは limit とかでいいと思う

2021-09-24 05:47 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +      deletedPagesPromises.push(Page.find(deletedPageStatusQuery).select('_id').skip(skip).limit(OFFSET));
一番問題があるのはここ(惜しい)

- promise を作って、走らせてる間に、メモリ使用量が上がる可能性がある

2021-09-27 04:22 UTC, yuto-oweseek commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +      deletedPagesPromises.push(Page.find(deletedPageStatusQuery).select('_id').skip(skip).limit(OFFSET));
cursorを利用する方針にしました。

2021-09-27 04:23 UTC, yuto-oweseek commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    const OFFSET = 1000;
消しましたが、承知です。

2021-09-27 06:14 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +      deletedPagesPromises.push(Page.find(deletedPageStatusQuery).select('_id').skip(skip).limit(OFFSET));
まだだめですねえ。

「今何件処理してるか」「何件のデータがここに溜まるか」っていう視点で自分が書いたコードを見ないとだめだよ。

2021-09-29 10:41 UTC, yuki-takei requested changes

2021-09-29 10:41 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    const LIMIT = 1000;
この定数は module.exports の外に出す

2021-09-29 10:41 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +      counter += 1;
updateDeletedPageIds.length を使えば counter は不要。

2021-09-29 10:41 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +        }
この部分は共通化しよう

2021-09-30 04:47 UTC, yuto-oweseek commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    const LIMIT = 1000;
承知です

2021-09-30 04:47 UTC, yuto-oweseek commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +      counter += 1;
使わさせていただきました。

2021-09-30 04:47 UTC, yuto-oweseek commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +        }
共通化させていただきました。

2021-10-04 09:11 UTC, yuki-takei requested changes

2021-10-04 09:11 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    logger.info(`${OPERATION_MESSAGE_SUBJECT} has successfully applied`);
この logger 出力は up/down の度に1度でいい

2021-10-04 09:11 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +const setIsPageTrashedToPageTagRelationInList = async(db, updateIdList) => {
メソッド名を `updateIsPageTrashed` に変更

2021-10-04 09:11 UTC, yuki-takei commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    logger.info(`${OPERATION_MESSAGE_SUBJECT} has failed`);
この logger 出力も同じだが、現在の実装だと fail 時に処理が止まらないのでよくない。

2021-10-04 09:21 UTC, yuto-oweseek commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    logger.info(`${OPERATION_MESSAGE_SUBJECT} has successfully applied`);
1度に変更しました

2021-10-04 09:21 UTC, yuto-oweseek commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +const setIsPageTrashedToPageTagRelationInList = async(db, updateIdList) => {
名前を変更しました

2021-10-04 09:22 UTC, yuto-oweseek commented on packages/app/src/migrations/20210921173042-add-is-trashed-field.js
> +    logger.info(`${OPERATION_MESSAGE_SUBJECT} has failed`);
例外のキャッチを外しました。

2021-10-04 10:04 UTC, merged