Imprv/77591 show modal
weseek/growi pull request #4373
Opened 2021-09-24 02:15 UTC by stevenfukase

2021-09-28 08:19 UTC, yuki-takei requested changes

2021-09-28 08:19 UTC, yuki-takei commented on packages/app/src/components/PageEditor/DownloadDictModal.tsx
> +  isDontAskAgainChecked: boolean;
isDontAskAgainChecked は不要。なぜなら「二度と聞かない」を ON にしたあとは、このモーダルは開かれることすらないから。

2021-09-28 08:19 UTC, yuki-takei commented on packages/app/src/components/PageEditor/DownloadDictModal.tsx
> +  onCancel: () => void;
onHoge は nullable にする。呼び出すときは null チェックをする。

onConfirmEnableTextlint を呼んだ時は、isDontAskAgainChecked にあたる boolean も引数に入れる。
ただし、dont ask という否定系の名前は避ける。代案はパッといいのは思いつかないけど例えば isSkipCheckingAfterThis とか。

2021-09-28 08:19 UTC, yuki-takei commented on packages/app/src/components/PageEditor/DownloadDictModal.tsx
> +  dontAskAgainCheckboxHandler: (isChecked: boolean) => void;
dontAskAgainCheckboxHandler は不要

2021-09-28 08:19 UTC, yuki-takei commented on packages/app/src/components/PageEditor/OptionsSelector.jsx
> +    }
ここまではいい。

ここを通過してモーダルを開かなかった場合は、新規メソッドを作ってそれを呼ぶ。  
confirmEnableTextlintHandler からもそれを呼ぶことになる。

2021-09-28 08:19 UTC, yuki-takei commented on packages/app/src/components/PageEditor/OptionsSelector.jsx
> +        <DownloadDictModal
isDontAskAgainChecked が true になったら、レンダリングすらしなくていい。

2021-10-04 03:28 UTC, stevenfukase commented on packages/app/src/components/PageEditor/DownloadDictModal.tsx
> +  isDontAskAgainChecked: boolean;
対応しました

2021-10-04 03:29 UTC, stevenfukase commented on packages/app/src/components/PageEditor/DownloadDictModal.tsx
> +  dontAskAgainCheckboxHandler: (isChecked: boolean) => void;
対応済

2021-10-04 03:35 UTC, stevenfukase commented on packages/app/src/components/PageEditor/DownloadDictModal.tsx
> +  onCancel: () => void;
対応済

2021-10-04 05:35 UTC, stevenfukase commented on packages/app/src/components/PageEditor/OptionsSelector.jsx
>    }
`this.toggleTextlint()`をcallbackに入れずに実行しようとするとsetStateの前に走ってしまう。
`setState`はasyncではあるがPromiseを返しているわけではないのでasync awaitは使えない。
参考: [StackOverflow | React setState not updating state](https://stackoverflow.com/questions/41446560/react-setstate-not-updating-state)

2021-10-04 05:35 UTC, stevenfukase commented on packages/app/src/components/PageEditor/OptionsSelector.jsx
> +        )}
`isSkipAskingAgainChecked: true`の場合、Renderしない

2021-10-04 09:41 UTC, merged