feat: Include setting button
weseek/growi pull request #4375
Opened 2021-09-24 04:06 UTC by maow89126

xd : https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/dad28d9f-d727-45e4-9853-bdcb9c083914/specs/

かきき途中

2021-09-24 06:48 UTC, yuki-takei requested changes

2021-09-24 06:48 UTC, yuki-takei commented on packages/app/resource/locales/en_US/translation.json
> +    "include_trash_path": "Include /trash path "
user 用と trash 用と 2 つも用意する必要はない。path のパラメータを取るようにしよう。

2021-09-24 06:48 UTC, yuki-takei commented on packages/app/src/components/SearchPage/IncludeSpecificPathButton.jsx
> +  const [checked, setChecked] = useState(true);
これは state ではなく props にする

2021-09-27 02:27 UTC, maow89126 commented on packages/app/resource/locales/en_US/translation.json
> +    "include_trash_path": "Include /trash path "
直しました。

2021-09-27 02:35 UTC, maow89126 commented on packages/app/src/components/SearchPage/IncludeSpecificPathButton.jsx
> +  const [checked, setChecked] = useState(true);
変更しました。

2021-09-27 02:37 UTC, maow89126 commented on packages/app/src/components/SearchPage/IncludeSpecificPathButton.jsx
> +  const [checked, setChecked] = useState(true);
自分用メモ

userを含む時はurlの状態で判断するのでcheckedはstateではなくpropsで親コンポーネントから渡して使用することになる。

2021-09-27 02:52 UTC, merged