fix: Add dictionary file to public
weseek/growi pull request #4381
Opened 2021-09-24 09:38 UTC by stevenfukase

2021-09-27 03:05 UTC, stevenfukase commented on THIRD-PARTY-NOTICES.md
> +```
辞書ファイルはAtilika社のKuromojiではなくそちらをもとに作られたKuromoji.jsから取ってきています

https://www.jsdelivr.com/package/npm/kuromoji
https://github.com/takuyaa/kuromoji.js/

2021-09-27 04:20 UTC, stevenfukase commented on .gitattributes
> +*.gz filter=lfs diff=lfs merge=lfs -text
git lfs

2021-09-27 04:21 UTC, stevenfukase commented on packages/app/.gitignore
> -/public/static/dict
jsやstylesのNo CDNモードと違い、辞書ファイルはアップロードしたいので、gitignoreから削除

2021-09-27 08:31 UTC, stevenfukase commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    window.kuromojin = { dicPath: '/static/dict' };
init()から外すとView画面に強制的に戻るBugが発生します。

2021-09-27 10:32 UTC, yuki-takei requested changes

2021-09-27 10:32 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    window.kuromojin = { dicPath: '/static/dict' };
これはタイミングをもう少し吟味したい。
componentWillMount とか componentDidMount あたりでどこが相応しいかテストして。

2021-09-28 06:58 UTC, yuki-takei approved these changes

2021-09-28 07:00 UTC, merged