Feat: save subscription model
weseek/growi pull request #4425
Opened 2021-09-30 05:33 UTC by miya

## Task
77830 Subscribe ボタンを押すと Subscription モデルが保存される

2021-10-03 16:04 UTC, yuki-takei requested changes

2021-10-03 16:04 UTC, yuki-takei commented on packages/app/src/components/SubscribeButton.tsx
> +      const res = await appContainer.apiv3Put('page/subscribe', { pageId: pageContainer.state.pageId, status: !isWatching });
pageId は props で入れるようにしてほしい

2021-10-03 16:04 UTC, yuki-takei commented on packages/app/src/server/models/subscription.ts
> +  STATUS_UNWATCH(): string
method にする必要はないと思う

2021-10-03 16:04 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/page.js
> +      const subscription = await Subscription.watchByPageId(userId, pageId, status);
watch という動詞は駆逐して subscribe/unsubscribe に統一しよう

2021-10-04 04:49 UTC, miya commented on packages/app/src/server/models/subscription.ts
> +  STATUS_UNWATCH(): string
ないですね...

以下のエラーで ci が通らなかったのでメソッドにしていました。

<img width="834" alt="スクリーンショット 2021-10-04 11 37 42" src="https://user-images.githubusercontent.com/34241526/135795893-e2b4845f-ac9b-4d57-b30c-f64919b829a7.png">
..

2021-10-04 05:27 UTC, miya commented on packages/app/src/server/models/subscription.ts
> +  STATUS_UNWATCH(): string
[in-app-notification.tx](https://github.com/weseek/growi/blob/feat%2Fnotification/packages/app/src/server/models/in-app-notification.ts#L138:L146) でも同様に書かれていたのでこれで良いと判断しました。

2021-10-04 05:28 UTC, miya commented on packages/app/src/components/SubscribeButton.tsx
> +      const res = await appContainer.apiv3Put('page/subscribe', { pageId: pageContainer.state.pageId, status: !isWatching });
修正しました。

2021-10-04 05:28 UTC, miya commented on packages/app/src/server/routes/apiv3/page.js
> +      const subscription = await Subscription.watchByPageId(userId, pageId, status);
修正しました。

2021-10-04 09:31 UTC, yuki-takei requested changes

2021-10-04 09:31 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/page.js
> +    const status = req.body.status ? Subscription.STATUS_SUBSCRIBE() : Subscription.STATUS_UNSUBSCRIBE();
`Subscription.STATUS_SUBSCRIBE()` というメソッドは消してください

2021-10-04 09:31 UTC, yuki-takei commented on packages/app/src/server/models/subscription.ts
> +  return STATUS_UNSUBSCRIBE;
このメソッド不要

2021-10-04 09:31 UTC, yuki-takei commented on packages/app/src/server/models/subscription.ts
> +  STATUS_UNSUBSCRIB: string
この2行不要

2021-10-04 11:25 UTC, yuki-takei requested changes

2021-10-04 11:25 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.jsx
> +  pageId: PropTypes.string,
こっちは props にしなくてよいです

2021-10-04 12:27 UTC, merged