Feat/77515 79940 highlight page path
weseek/growi pull request #4542
Opened 2021-10-26 02:09 UTC by ryohi15

2021-11-01 13:34 UTC, ryohi15 commented
## 見た目(改)
![image](https://user-images.githubusercontent.com/61174410/139680026-6a08fd24-5115-4ce6-845e-ab933da28cf4.png)

2021-11-01 13:39 UTC, ryohi15 commented on packages/ui/src/components/PagePath/PagePathLabel.jsx
> +      ? <></>
### ここの差分の理由
`/math` のようにトップページ配下に math というページがあった場合に
math というワード検索すると検索結果画面のパスに `/` が表示されてしまうため削除(元々表示されてなかった)



![image](https://user-images.githubusercontent.com/61174410/139680545-db671c48-2e12-4470-8384-9884688ef4e2.png)

2021-11-02 06:32 UTC, yuki-takei requested changes

2021-11-02 06:32 UTC, yuki-takei commented on packages/core/src/models/devided-page-path.js
> +const PATTERN_PATH_WITH_ANY_HTML_TAGS = /<("[^"]*"|'[^']*'|[^'">])*>/g;
これを PATTERN_DEFAULT でつかってください
https://regex101.com/r/HJNvMW/1

ついでに re2 使ってください
https://github.com/uhop/node-re2/

2021-11-02 06:32 UTC, yuki-takei commented on packages/ui/src/components/PagePath/PagePathLabel.jsx
> +  const highlightedPath = props.page.elasticSearchResult.highlightedPath;
elasticSearchResult があるかないかをこのコンポーネントは知らなくても動くようにしたい。
そうなるように props を変えてください。pagePath: string だけをとるようにする。

2021-11-02 06:32 UTC, yuki-takei commented on packages/ui/src/components/PagePath/PagePathLabel.jsx
> +      ? <></>
仕様なので変更しないくていいです。

2021-11-02 06:34 UTC, yuki-takei requested changes

2021-11-02 06:34 UTC, yuki-takei commented on packages/ui/src/components/PagePath/PagePathLabel.jsx
> +    return <span dangerouslySetInnerHTML={{ __html: reactElement.props.children }}></span>;
XSS の原因になるので、HTML をレンダリングするモードにする props (boolean) を新設してください。検索結果で使うときだけそのフラグを true にする。

2021-11-02 08:19 UTC, ryohi15 commented on packages/ui/src/components/PagePath/PagePathLabel.jsx
> +  const highlightedPath = props.page.elasticSearchResult.highlightedPath;
done

2021-11-02 08:19 UTC, ryohi15 commented on packages/ui/src/components/PagePath/PagePathLabel.jsx
> +      ? <></>
done

2021-11-04 09:32 UTC, yuki-takei requested changes

2021-11-04 09:32 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  const pagePathElem = <PagePathLabel path={props.page.elasticSearchResult.highlightedPath} isFormerOnly isPathHighlighted={isPathHighlighted} />;
isPathHighlighted という名前がよくない。HTML を含むかどうかでしょ？

2021-11-04 09:32 UTC, yuki-takei commented on packages/core/src/models/devided-page-path.js
> +const PATTERN_PATH_WITH_ANY_HTML_TAGS = /<("[^"]*"|'[^']*'|[^'">])*>/g;
PATTERN_PATH_WITH_ANY_HTML_TAGS はもはや不要なのでは？

2021-11-05 06:14 UTC, yuki-takei requested changes

2021-11-05 06:14 UTC, yuki-takei commented on packages/ui/src/components/PagePath/PagePathLabel.jsx
> +    return <span className={classNames.join(' ')}>{reactElement.props.children}</span>;
あえて children 抽出しなくてもそのまま入れればいいと思う。
displayPath に渡すものももっとシンプルに。

2021-11-05 06:16 UTC, yuki-takei requested changes

2021-11-05 06:16 UTC, yuki-takei commented on packages/ui/src/components/PagePath/PagePathLabel.jsx
> +  const displayPath = (reactElement) => {
useMemo を使うか、PagePathLabel の外に出して

2021-11-05 06:16 UTC, yuki-takei commented on packages/ui/src/components/PagePath/PagePathLabel.jsx
> +    return displayPath(<>{dPagePath.latter}</>);
displayPath に渡すものももっとシンプルに。この行とか frangment で囲う意味はあまりない。

2021-11-05 10:19 UTC, yuki-takei approved these changes

2021-11-05 10:24 UTC, merged