feat:select revision and copy it to text area
weseek/growi pull request #4553
Opened 2021-10-27 06:03 UTC by yuto-oweseek

# タスク

https://estoc.weseek.co.jp/redmine/issues/78639
https://estoc.weseek.co.jp/redmine/issues/78643

# 行ったこと
-  revisionId が最新でないときに 編集から保存をしたときにコンフリクト解消モーダルが表示され、コンフリクトを解消して、サーバーサイドへ post できるようにしました
- select ~~~ のボタンを押すと、下の CodeMirror（編集可能） にコピペされます
- モーダルの上3画面は readonly 下の画面(選ばれた revision )は、編集可能です

![when conflict](https://user-images.githubusercontent.com/83065937/139632493-aadea43e-79fe-4f38-8f7e-5158d1335eff.PNG)

![conflict initial state](https://user-images.githubusercontent.com/83065937/139633977-14dfe2b7-5348-4c3e-9688-458bde8e19d0.PNG)

↓ ボタンを押すとコピペされる

![resolve conflict image](https://user-images.githubusercontent.com/83065937/139632264-123551a9-aee5-44f2-a028-c3f88d2417f7.PNG)

![resolve and save](https://user-images.githubusercontent.com/83065937/139632498-cf9e757b-d039-41f0-b05f-be0f38fa788b.PNG)

2021-11-04 09:52 UTC, yuki-takei requested changes

2021-11-04 09:52 UTC, yuki-takei commented on packages/app/src/components/PageEditor/ConflictDiffModal.tsx
> +import { UnControlled as CodeMirror } from 'react-codemirror2';
CodeMirrorEditor 使いたいなあ。

- theme, key bind, indent size あたりの設定
- gfm mode

あたりの通常エディタの設定を引き継がないのは使い勝手悪い。
そのままは使えなくても共通化できないものか…

(重ければ後続タスク化)

2021-11-04 09:52 UTC, yuki-takei commented on packages/app/src/components/PageEditor/ConflictDiffModal.tsx
> +    });
saveAndReload をそのまま使うのかどうかを検討したほうがよさそう

- saveAndReload を呼ぶなら、pageContainer の state を事前に変更するのはおかしい
- location.href でジャンプするなら toastr は不要 (ユーザーへのレスポンスとしては両者は排他であるべき)
    - というか、saveAndReload の処理の中にその挙動は含まれているはず

pageContainer.resolveConflict メソッドを新たに作った方がいいかもしれない(要検討)。ただ、既存メソッドで流用できるならそうすべき。

2021-11-08 10:15 UTC, yuki-takei requested changes

2021-11-08 10:15 UTC, yuki-takei commented on packages/app/resource/locales/en_US/translation.json
> +    "reload": "Reload",
`t('Load latest');` ではだめ？

2021-11-08 10:15 UTC, yuki-takei commented on packages/app/src/components/PageEditor/ConflictDiffModal.tsx
> +import { UnControlled as CodeMirror } from 'react-codemirror2';
この件どうなった？

2021-11-08 10:15 UTC, yuki-takei commented on packages/app/src/components/PageEditor/ConflictDiffModal.tsx
> +  const resolvedRevision = useRef<string>(t('modal_resolve_conflict.resolve_conflict_message'));
初期値は空文字列にして、上部で未選択の場合は別途レンダリングする

2021-11-08 10:15 UTC, yuki-takei commented on packages/app/src/components/PageEditor/ConflictDiffModal.tsx
> +                  value={resolvedRevision.current}
placeholder で指示を入れる

2021-11-10 12:28 UTC, yuki-takei requested changes
unresolved なコメントについて何かしら修正か説明をください。

2021-11-11 05:42 UTC, yuto-oweseek commented
> unresolved なコメントについて何かしら修正か説明をください。

↑なんですが、以下の件のことですか？
もし以下の件の場合は、後続タスクで対応します。

https://github.com/weseek/growi/blob/0842103cd293fb446c6e1f49f924445c28699bc0/packages/app/src/components/PageEditor/ConflictDiffModal.tsx#L8-L9

2021-11-11 07:44 UTC, yuki-takei requested changes

2021-11-11 07:44 UTC, yuki-takei commented on packages/app/src/client/services/PageContainer.js
> +    window.location.href = this.state.path;
一旦 reload に直してください

2021-11-11 07:53 UTC, yuto-oweseek commented on packages/app/src/client/services/PageContainer.js
> +    window.location.href = this.state.path;
reloaにしました。

2021-11-11 08:06 UTC, merged