Feat/with proxy unfurl
weseek/growi pull request #4557
Opened 2021-10-28 05:31 UTC by stevenfukase

## タスク
https://estoc.weseek.co.jp/redmine/issues/78978

## やったこと
Unfurlの設定画面のフロント側を実装しました。
#### 日本語
![Capture](https://user-images.githubusercontent.com/66785624/139619858-03dffe4c-84ab-4a1e-b74a-6cae4fc8a443.PNG)
#### 英語
![Capture1](https://user-images.githubusercontent.com/66785624/139619861-608fe03a-4687-493f-9c41-acbee1853d2f.PNG)

2021-11-01 12:31 UTC, hakumizuki requested changes

2021-11-01 12:31 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const PermissionSettingsForEachCommandTypeComponent = ({ usageType }) => {
コンポーネントの名前を Command, Event 両用にした方がわかりやすいと思います。

2021-11-01 12:31 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +      unfurl: permissionsForEventsState,
unfurl ではなくて event では？

2021-11-01 12:31 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +  const PermissionSettingForEachCommandComponent = ({
コンポーネントの名前を Command, Event 両用にした方がわかりやすいと思います。そうなると commandName は keyname とかでしょうか

2021-11-01 12:31 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +    const currentMenu = menuItems[usageType];
menuItems から currentMenu を取得するこの処理は親コンポーネントである ManageCommandProcess でやって、currentMenu を props で渡す形にしたらいいと思います

2021-11-02 07:01 UTC, stevenfukase commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +      allowedChannelsDescription: 'admin:slack_integration.accordion.allowed_channels_description',
上のdescriptionと同様にi18nするとエラーが出るので、使うところでi18nすることにしました

2021-11-02 07:01 UTC, stevenfukase commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +            {t(allowedChannelsDescription, { keyName })}
使うところでi18n

2021-11-02 08:24 UTC, hakumizuki requested changes

2021-11-02 08:24 UTC, hakumizuki commented on packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
> +            />
menuMap 自体を渡して PermissionSettingsForEachCategoryComponent のなかで展開した方がいいと思います

2021-11-02 10:13 UTC, merged