feat: page migration remove unique constraint
weseek/growi pull request #4560
Opened 2021-10-29 03:58 UTC by hakumizuki

Redmine: https://estoc.weseek.co.jp/redmine/issues/80257

マイグレーション完了後にユニーク制約を取り除く処理を実装しました

## 後続について
Page スキーマの以下の部分についての動作確認は Page.create の改修後の方が楽なのでそのタスクの時におこないます

```typescript
// TODO: test this after modifying Page.create
// ensure v4 compatibility using partial index
pageSchema.index({ path: 1 }, { unique: true, partialFilterExpression: { parent: null } });
```

2021-10-31 22:31 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/pages.js
> +            crowi.pageService.v5RecursiveMigration(Page.GRANT_PUBLIC);
通知するように変更しました。本処理は private method にしてサービス層に socket 通知のメソッドを作ってそれを route で呼ぶようにしました

後続タスクは https://estoc.weseek.co.jp/redmine/issues/80310 ストーリーにチケット作りました

2021-11-01 05:23 UTC, yuki-takei requested changes

2021-11-01 05:23 UTC, yuki-takei commented on packages/app/src/server/models/page.js
> +pageSchema.index({ path: 1 }, { unique: true, partialFilterExpression: { parent: null } });
parent: null のものだけしかインデックス対象にならないと困る。

2021-11-01 05:23 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +    }
このブロックは
「システム管理者による初回の v5 compatible にする操作」
とその後の
「ユーザーによる特定ページ群を v5 compatible にする操作」
の場合分けで作用するように作られているが、そもそもメソッドを別にして呼び出す or not をわけるべき。

2021-11-01 05:23 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +    const pathIndexStatus = indexStatus.filter(status => status.name === 'path_1')?.[0]?.spec?.unique;
読みにくい。
`indexStatus.filter(status => status.name === 'path_1')?.[0]` までを一時変数にいれ、isUnique も一時変数として用意しよう。

2021-11-01 05:23 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +    if (pathIndexStatus == null || pathIndexStatus === true) {
- 存在しないなら早期 return
- unique でないならやはり早期 return

2021-11-01 06:27 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +    }
別メソッドにしました。名前は v5Migration -> v5InitialMigration に変更しました

2021-11-01 06:29 UTC, hakumizuki commented on packages/app/src/server/models/page.js
> +pageSchema.index({ path: 1 }, { unique: true, partialFilterExpression: { parent: null } });
後続タスクで改修しました

2021-11-01 06:29 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +    const pathIndexStatus = indexStatus.filter(status => status.name === 'path_1')?.[0]?.spec?.unique;
変数を二つに分けました

2021-11-01 06:36 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +    if (pathIndexStatus == null || pathIndexStatus === true) {
ここの処理は `_v5ModifyPagePathIndex` に移動しました。

DropIndex, CreateIndex の順番で２つの処理があって、「 DropIndex then CreateIndex 」「 CreateIndex のみ 」という処理の流れなので早期 return は使えませんでした

2021-11-01 09:58 UTC, yuki-takei requested changes

2021-11-01 09:58 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +    if (isUnique) {
この if block は、「存在するなら」という条件でよい
ユニークかどうかは気にしない(引数にも入ってこない)

2021-11-01 09:58 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +  async _v5ModifyPagePathIndex(isUnique) {
責務は normalize、
「あるべき姿」じゃない場合に呼ばれて、呼ばれた後はあるべき姿にしてくれる。

2021-11-01 09:58 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +    const isUnique = pathIndexStatus?.spec?.unique;
```
const pathIndexStatus = indexStatus.filter(status => status.name === 'path_1')?.[0];
const isPathIndexExists = pathIndexStatus  != null;
const isUnique = isPathIndexExists && pathIndexStatus.spec?.unique === true;
```

2021-11-01 11:56 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +    if (isUnique) {
「存在するなら」という条件にしました

2021-11-01 11:56 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +  async _v5ModifyPagePathIndex(isUnique) {
Normalize という責務のみになるようにしました

2021-11-01 11:57 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +    const isUnique = pathIndexStatus?.spec?.unique;
「index が存在するか」と「index が unique か」の条件を作ってから if 文を組み立てました。リーダブルになりました

2021-11-01 12:33 UTC, merged