search result right part
weseek/growi pull request #4561
Opened 2021-10-29 08:00 UTC by maow89126

# task
https://estoc.weseek.co.jp/redmine/issues/78782
# やったこと
- 検索画面の右側専用なnavbarを作理ました。
- SubNavButtonにisSearchPagemodeを追加しました。
    - のちにpageContainerの依存が取れた時に [ここら辺](https://github.com/weseek/growi/blob/81b021d29e5b5bf359b6c7e03eec0f906865587c/packages/app/src/components/Navbar/SubNavButtons.jsx#L46-L47)に追加してconditional renderingする予定。
# 確認したいこと
[TODO](https://github.com/weseek/growi/pull/4561/files#diff-3e37d54e172950e22c791520656d2445fc4b6224250400f17b271554133106fbR12)
に一旦軽く記載したのですが、今後のプランとしてタスクを2つ作り後追いで対応する予定です。以下の流れを考えているのですが、何か意見があればいただきたいです。
問題なさそうならタスク作成＋todoにタスク番号記載します。
1.  like と bookmarkのmethodをpageContainerに依存しなくする。
2.  ３点ボタンの中のmethodでpageContainerに依存してるものを依存しないようにする。　これは、80335とで一部対応されてるのでやる箇所はcreateTemplateModalのみ。

# 今の見た目：
<img width="1920" alt="Screen Shot 2021-10-29 at 17 32 02" src="https://user-images.githubusercontent.com/60797707/139440411-461439c9-c119-417d-9dc0-78184e83bde4.png">

2021-11-02 06:25 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> +export default SearchResultContentSubNavigation;
共用できるように変更しました。

後継タスクでTagLabelsの依存はがし＋SubNavButtons内の依存はがし（like button、bookmark button, createTemplatePageModal）をやります。
[後追い](https://estoc.weseek.co.jp/redmine/issues/80623)
[後追い](https://estoc.weseek.co.jp/redmine/issues/80481)

2021-11-02 06:25 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> +export default SearchResultContentSubNavigation;
一応スクショです
<img width="1920" alt="Screen Shot 2021-11-02 at 15 19 30" src="https://user-images.githubusercontent.com/60797707/139796484-109313d8-65f4-4836-97f4-d29263b097a5.png">

<img width="1920" alt="Screen Shot 2021-11-02 at 15 19 37" src="https://user-images.githubusercontent.com/60797707/139796488-d9a67412-e952-4e1b-ac85-f357739e1915.png">

2021-11-02 07:24 UTC, yuki-takei requested changes

2021-11-02 07:24 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.jsx
> +    appContainer, navigationContainer, pageContainer, isCompactMode, isSearchPageMode,
isSearchPageMode という名前が気に食わない。何用途かをこのコンポーネントで定義する必要はない。

そして今実装がないなら削除して。

2021-11-02 07:24 UTC, yuki-takei commented
## メモ
- 本当に必要なものだけを共用可能にする
    - TagLabels
    - page path 表示部分
    - コントロール群

2021-11-04 03:28 UTC, maow89126 commented on packages/app/src/components/Navbar/SubNavButtons.jsx
> +    appContainer, navigationContainer, pageContainer, isCompactMode, isSearchPageMode,
消しました。

2021-11-04 03:32 UTC, maow89126 commented
>本当に必要なものだけを共用可能にする
TagLabels
page path 表示部分
コントロール群

この案で進めてます。このタスクではSearchREsultConenteSubNavigation（検索用のsubnav）作成、
PagePathNavをコンポーネント化してGrowiSubNavigation、SearchResultContentSubNavigation内で使えるようにしました。

後継タスクでTagLables,SubNavButton(like, bookmark, などの所謂コントロール部分)をpageContainerの依存なく使えるように改修します。

2021-11-04 09:36 UTC, yuki-takei requested changes

2021-11-04 09:36 UTC, yuki-takei commented on packages/app/src/components/PagePathNav.tsx
> +  isEditorMode:boolean,
- isSigleLineMode に変えてください
- isEditorMode, isCompactMode 共に nullable にしてください。
    `isEditorMode?: boolean`

2021-11-04 20:40 UTC, maow89126 commented on packages/app/src/components/PagePathNav.tsx
> +  isEditorMode:boolean,
直しました。

2021-11-04 20:58 UTC, merged