Feat/77543 80335 detach page control from page container
weseek/growi pull request #4563
Opened 2021-10-29 09:19 UTC by TatsuyaIse

### task
- https://estoc.weseek.co.jp/redmine/issues/80335

2021-11-08 08:50 UTC, yuki-takei requested changes

2021-11-08 08:50 UTC, yuki-takei commented on packages/app/src/components/BookmarkButton.jsx
> +      await this.appContainer.apiv3Put('/bookmarks', { pageId, bool });
apiv3Put は utility モジュールから直接インポートできる

2021-11-08 08:50 UTC, yuki-takei commented on packages/app/src/components/PageDeleteModal.jsx
> +  appContainer: PropTypes.instanceOf(AppContainer).isRequired,
appContainer への依存は不要

2021-11-08 08:50 UTC, yuki-takei commented on packages/app/src/components/PutbackPageModal.jsx
> +      const response = await appContainer.apiPost('/pages.revertRemove', {
appContainer への依存は不要

2021-11-08 08:50 UTC, yuki-takei commented on packages/app/src/components/PageDeleteModal.jsx
> +  const { pageId, revisionId } = pageContainer.state;
modal からも依存剥がさないと結局使い回しできないんじゃない？

2021-11-11 06:20 UTC, TatsuyaIse commented on packages/app/src/components/PageDeleteModal.jsx
> +  appContainer: PropTypes.instanceOf(AppContainer).isRequired,
依存解消済んでいます。

2021-11-11 06:22 UTC, merged