Feat/80098 appearance of in app notification settings
weseek/growi pull request #4569
Opened 2021-11-01 04:18 UTC by miya

## Task
[80097](https://estoc.weseek.co.jp/redmine/issues/80097): [front] UserSettings に自分で作成したページをデフォルトで subscribe するかどうかの on/off ができるスイッチを作成する

2021-11-04 11:58 UTC, yuki-takei requested changes

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/resource/locales/en_US/translation.json
> +    "in_app_notification_settings": "InAppNotification Settings",
InAppNotification というモデル名そのままでは通じない

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    const retrievedRules: SubscribeRule[] = data?.defaultSubscribeRules;
モデルの attribute から `default` という prefix を消そう

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    if (retrievedRules != null && retrievedRules.length > 0) {
retrievedRules は not nullable

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +];
enum から自動生成する

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    }
else 句は不要そう

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +  );
FC の外に出す

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    ));
filter の結果存在してしまった場合、同じ ruleName のものが重複しそう

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    ));
Set collection に変換して入れる方が確実かつ readable

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    ));
- isChecked を反映させるロジックは FC の外に出して、ここでは setState だけを行う
- useCallback

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +  };
useCallback

2021-11-04 11:58 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +      const { data } = await appContainer.apiv3Put('/personal-setting/in-app-notification-settings', { defaultSubscribeRules });
appContainer 不要、apiv3-client を利用して。

2021-11-05 07:22 UTC, miya commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    const retrievedRules: SubscribeRule[] = data?.defaultSubscribeRules;
消しました。

2021-11-05 07:28 UTC, miya commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    if (retrievedRules != null && retrievedRules.length > 0) {
null を許容しないような if文 にしました。

2021-11-05 08:28 UTC, miya commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +  );
FC の外に出しました

2021-11-05 09:03 UTC, miya commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +      const { data } = await appContainer.apiv3Put('/personal-setting/in-app-notification-settings', { defaultSubscribeRules });
apiv3-client を利用して、appContainer を削除 & withUnstatedContainers を剥がしました

2021-11-05 09:10 UTC, miya commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +  };
使いました。

2021-11-05 11:03 UTC, miya commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    if (retrievedRules != null && retrievedRules.length > 0) {
`const retrievedRules: SubscribeRule[] = data?.subscribeRules;` 
subscribeRules がなかったときは null が入るので、nullable でいいと思います。

2021-11-05 11:04 UTC, miya commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    }
不要だったので削除しました。

2021-11-05 11:35 UTC, miya commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +];
これはちょっと自信がないのですが、enum を使って生成できるようにしました...

2021-11-05 11:45 UTC, miya commented on packages/app/resource/locales/en_US/translation.json
> +    "in_app_notification_settings": "InAppNotification Settings",
`In-App Notifications` に変更しました

2021-11-07 09:40 UTC, miya commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +
subscribeRules から name が ruleName のオブジェクトを全て削除、更新された SubscribeRule を concat して返すようにしました

2021-11-08 05:59 UTC, yuki-takei requested changes

2021-11-08 05:59 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +];
二重管理しないように

2021-11-08 05:59 UTC, yuki-takei commented on packages/app/src/components/Me/InAppNotificationSettings.tsx
> +    const retrievedRules: SubscribeRule[] = data?.subscribeRules;
型を nullable にする必要がある。

2021-11-08 06:53 UTC, merged