Feat/80098 create in app notification settings model
weseek/growi pull request #4571
Opened 2021-11-01 06:42 UTC by miya

## Task
[80098](https://estoc.weseek.co.jp/redmine/issues/80098): [server] in-app-notification-settings モデルを作成する

2021-11-02 07:58 UTC, yuki-takei requested changes

2021-11-02 07:58 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification-settings.ts
> +  name: string,
enum を使った実装にしてください。
https://stackoverflow.com/a/65627210

2021-11-02 07:58 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification-settings.ts
> +  name: string,
interface は `src/interfaces` 下に移動させてください。

2021-11-02 09:13 UTC, miya commented on packages/app/src/server/models/in-app-notification-settings.ts
> +  name: string,
- enum を使って、バリデーションできるようにしました。
- `IDefaultSubscribeRule` と `IInAppNotificationSettings` を src/interface に移動させました

2021-11-02 10:28 UTC, yuki-takei requested changes

2021-11-02 10:28 UTC, yuki-takei commented on packages/app/src/interfaces/in-app-notification-settings.ts
> +  name: string,
こっちも enum になるように

2021-11-03 05:03 UTC, miya commented on packages/app/src/interfaces/in-app-notification-settings.ts
> +  name: string,
`subscribeRules` を src/interface に移動させました

2021-11-04 08:22 UTC, yuki-takei approved these changes

2021-11-04 08:22 UTC, merged