Feat/80324 80388 change bg color on selected
weseek/growi pull request #4574
Opened 2021-11-01 08:04 UTC by Yohei-Shiina

https://estoc.weseek.co.jp/redmine/issues/80388

2021-11-01 09:22 UTC, yuki-takei requested changes

2021-11-01 09:22 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +        .selected-list-item {
ネストが深いので最小限に
https://growi.weseek.co.jp/開発ガイドライン/スタイルガイド#アンチパターン

2021-11-01 09:22 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +          border-left: 3px solid #122c55;
色はテーマ側で指定する

2021-11-01 09:22 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +        .selected-list-item {
.active を上書きするんじゃないかなあ
https://getbootstrap.jp/docs/4.5/components/list-group/#links-and-buttons

2021-11-02 02:53 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +          border-left: 3px solid #122c55;
テーマ側のというのは/app/src/styles/theme のことでしょうか？

2021-11-02 04:04 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +          border-left: 3px solid #122c55;
そうです

2021-11-02 08:41 UTC, yuki-takei requested changes

2021-11-02 08:41 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultList.jsx
> +          selectedPageId={this.props.selectedPage.id}
props の nullable or required の意識が激甘。(直して)

id を渡すなら null チェック or optional chaining が必要。
しかし SearchResultListItem.tsx では required になっているので、このままでは optional chaining は利用不可。

2021-11-02 08:41 UTC, yuki-takei commented on packages/app/src/styles/theme/default.scss
> +  }
これだと default テーマでしか適用されない。apply-colors に書いて。

2021-11-02 08:41 UTC, yuki-takei commented on packages/app/src/styles/_variables.scss
> +$grw-search-active-item-left-border: 3px solid #122c55;
これも apply-colors でデフォルト値を定義し、各テーマで上書きできるようにする。

あらかじめ言っておくけれど、`#eff5ff` と `#122c55` が全てのテーマでしっくりくる保証はどこにもないので、他の例に倣って色を借りてきて生成するなど工夫すること。

2021-11-02 08:41 UTC, yuki-takei commented on packages/app/src/styles/_variables.scss
> +$grw-search-active-item-left-border: 3px solid #122c55;
`3px solid` 部分はテーマ側ではなく本体側 (_search.scss) で定義する。

2021-11-02 08:44 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.jsx
> +          selectedPageId={this.props.selectedPage.id}
これレビュー依頼前に、なければ空文字をい入れていたのですが、使う側が id の比較しかしていないので null でも問題ないと思ったのですが、そういうことではないのですかね

2021-11-02 09:04 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.jsx
> +          selectedPageId={this.props.selectedPage.id}
typescript で型定義するときにoptionalなものは ? 付けるというのは知らずに漏れていたので追加します

2021-11-02 10:39 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultList.jsx
> +          selectedPageId={selectedPage.id != null ? selectedPage.id : ''}
まだ不足している。
実際 SearchResultList の selectedPage に null 入れて実験してみて。

2021-11-02 10:39 UTC, yuki-takei commented on packages/app/src/styles/theme/_apply-colors.scss
> +$search-active-item-bgcolor: lighten($search-active-item-left-border-color, 76%);
21行目以降は override bootstrap variables なので19行目付近に入れてください。
あと19行目以前の変数と命名規則揃えて。bgcolor- とか color- から始まるように。

2021-11-02 10:39 UTC, yuki-takei commented on packages/app/src/styles/theme/_apply-colors.scss
> +}
589 行目から始まるブロックに入れられるんじゃないかな。
以前の実装でしか使わなかったクラスがあれば消して欲しい。

2021-11-04 05:00 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.jsx
> +          selectedPageId={selectedPage.id != null ? selectedPage.id : ''}
たしかに、null や undefined を参照してしまいますね

2021-11-04 05:24 UTC, Yohei-Shiina commented on packages/app/src/styles/theme/_apply-colors.scss
> +}
ネスト深くなると思ったので分けたのですがこれは入れて問題ないのですね

まだどこから深いと言えるのか感覚がつかめていないです

2021-11-04 05:26 UTC, Yohei-Shiina commented on packages/app/src/styles/theme/_apply-colors.scss
> +}
いやちがうな。行数は増えたけどより深くなったわけではないですね

2021-11-04 10:22 UTC, yuki-takei requested changes

2021-11-04 10:22 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultList.jsx
> +  selectedPage: PropTypes.object,
他のプログラマから見たら、「この下の selectedPages は何用途なのか？」っていう疑問を持つだろう。

命名を考えて。selectedPages の側を変えるでもいいとは思う。

2021-11-04 10:22 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +    <li key={page._id} className={`page-list-li w-100 border-bottom pr-4 list-group-item-action ${page._id === selectedPageId ? 'active' : ''}`}>
isSelected: boolean を props で入れる方が綺麗かなあ。

2021-11-05 09:19 UTC, yuki-takei approved these changes

2021-11-08 03:18 UTC, merged