Imprv/80106 show notifications to all in app notifiactions page
weseek/growi pull request #4581
Opened 2021-11-02 07:47 UTC by kaoritokashiki

2021-11-02 08:12 UTC, kaoritokashiki commented on packages/app/src/server/views/me/all-in-app-notifications.html
> +{% block html_title %}{{ customizeService.generateCustomTitleForFixedPageName(t('All In-App Notifications')) }}{% endblock %}
タグが `My Drafts`のままになっていたので、ついでに修正しました。

2021-11-02 08:33 UTC, yuki-takei requested changes

2021-11-02 08:33 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/AllInAppNotifications.tsx
> +  };
SWR 使ってください。`stores/notification.ts` 新規に作ってよいです。

2021-11-02 08:33 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/InAppNotificationList.tsx
> +  isLoaded: boolean;
isLoaded は消して、notifications が null だったら isLoading 扱い、という形にしよう。

2021-11-02 08:33 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/AllInAppNotifications.tsx
> +  };
InAppNotificationDropdown.tsx の fetchNotificationList も同様。

2021-11-05 06:38 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationList.tsx
> +  isLoaded: boolean;
なるほど、ありがとうございます

2021-11-05 07:23 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationList.tsx
> +};
notificationsは空の配列のprops で渡ってくるので、
以下のように書くと、以下のif文の処理は実行されず、

```
  if (notifications == null) {
    return <RenderUnLoadedInAppNotification />;
  }
```


RenderInAppNotificationListの`notifications.length === 0`の処理が実行されてしまうので、やはりisLoadedは必要だと考え、残したままにしています。
```
  const RenderInAppNotificationList = () => {
    if (notifications.length === 0) {
      return <RenderEmptyInAppNotification />;
    }
    const notificationList = notifications.map((notification: IInAppNotification) => {
      return (
        <div className="d-flex flex-row" key={notification._id}>
          <InAppNotification notification={notification} onClick={notificationClickHandler} />
        </div>
      );
    });
    return <>{notificationList}</>;
  };
```

2021-11-05 11:39 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/AllInAppNotifications.tsx
> +  };
`revalidateOnFocus`、デフォルトで有効になっているみたいです。

>この機能はデフォルトで有効になっています。revalidateOnFocus オプションで無効にできます。
- https://swr.vercel.app/ja/docs/revalidation

2021-11-05 14:15 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/AllInAppNotifications.tsx
> +  };
SWR のデフォルトで ON になってるのはわかっている。それを GROWI ではグローバルオプションの設定を変更して false にしている。リポジトリ内を `swrGlobalConfiguration` で検索して。

ただし今後以下のブランチがマージされた暁には revalidateOnFocus はデフォルトで有効化されるように戻す予定なので、今回に限ってはこの PR で対応しなくとも問題はない。

https://github.com/weseek/growi/pull/4598/files#diff-ea249ced27015e598a6feab7d4a21867e2ce5709bf0e2500557beb85396c59edL7

2021-11-05 14:21 UTC, yuki-takei requested changes

2021-11-05 14:21 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/AllInAppNotifications.tsx
> +  appContainer: AppContainer,
appContainer 必要ないのでは？

2021-11-05 14:21 UTC, yuki-takei commented on packages/app/src/stores/in-app-notification.ts
> +  limit: number,
ページングに対応するにはオフセット(とかページナンバー)が必要。
後続タスクでやるならそれでもいいけど、それならそれで補足してほしい。

2021-11-08 05:17 UTC, kaoritokashiki commented on packages/app/src/stores/in-app-notification.ts
> +  limit: number,
失礼しました。
後続タスクでやる予定でしたのでTODO コメントを追加しました。
- [#80107](https://estoc.weseek.co.jp/redmine/issues/80107)「See All」の遷移先に、ページネーションを追加し、ページ遷移することができる

2021-11-08 05:19 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/AllInAppNotifications.tsx
> +  };
なるほどです。そうなんですね。
そしたら、このPRでは対応しないの方針ででいきます。

2021-11-08 05:26 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/AllInAppNotifications.tsx
> +  appContainer: AppContainer,
その通りです。すみません修正しました。

2021-11-08 05:35 UTC, merged