feat: Switch pathlink and permalink
weseek/growi pull request #4589
Opened 2021-11-04 01:36 UTC by hakumizuki

Redmine: https://estoc.weseek.co.jp/redmine/issues/80349, https://estoc.weseek.co.jp/redmine/issues/80350

パス付きリンクとパーマリンクを入れ替えました。

## 動作例
1. `redirectTo` が `/A` であるページ `/B` にアクセス
2. `res.redirect('/A?redirectFrom=/B');`
3. `/A` からページ探す
  - １つしかない場合 => `'/Aのid?redirectFrom=/B'` にリダイレクト
  - ２つ以上ある場合 => `redirectFrom = /B` を `renderVars` に入れた上でページ遷移先選択ページを render (後続で実装)
    - 選択した遷移先 URL に `?redirectFrom=` を添加
  - ない場合 => `page.notFound` の挙動

## コメント
`pageSchema.statics.findByPathAndViewer` は path がユニーク前提で findOne していたので、一旦新規に `findByPathAndViewerV5` を追加して find するようにしました

## 後続タスクについて
- `findByPathAndViewer` が使われているところが正常に動くように改修して、最終的に `findByPathAndViewerV5` を `findByPathAndViewer` にマージします
- 複数のページが見つかった時に遷移先選択ページをレンダーするようにします。(UI はほぼ白紙)

2021-11-04 01:37 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +    const query = redirectFrom == null ? '' : `?redirectFrom=${redirectFrom}`;
redirectFrom はバケツリレーしています

2021-11-04 08:45 UTC, yuki-takei requested changes

2021-11-04 08:45 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +};
コードの重複をあまり作りたくないので、findByPathAndViewerV5 に findOne モードのようなものを作ろう

2021-11-04 08:45 UTC, yuki-takei commented on packages/app/src/server/routes/page.js
> +      return res.redirect(`/${pages[0]._id}${query}`);
query とリダイレクト先を文字列操作で作っているのが気になる。
res.safeRedirect とか使うべきなのかな。

あと `req.query` の他のものを全無視でいいのかとか。

2021-11-04 08:58 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +};
useFindOne: boolean を追加して共通化しました

2021-11-04 09:59 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +      return res.redirect(`/${pages[0]._id}${query}`);
- safeRedirect 使うようにしました
- その他の query parameter も渡るようにしました

2021-11-04 11:29 UTC, yuki-takei requested changes

2021-11-04 11:29 UTC, yuki-takei commented on packages/app/src/server/routes/page.js
> +    });
文字列操作はいけてない。URL module 使って。

https://nodejs.org/api/url.html

2021-11-05 03:09 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +    });
URLSearchParams を使いました

2021-11-05 03:16 UTC, merged