feat: adjust search result page item content
weseek/growi pull request #4591
Opened 2021-11-04 07:15 UTC by yuto-oweseek

## タスク

https://estoc.weseek.co.jp/redmine/issues/80545

## 行ったこと

- 検索結果の page の item に対して、css で高さを指定（統一化）
- ES から取れている snippet の文字を正規表現などの文字列操作で表示する最大の文字数を指定

![result1](https://user-images.githubusercontent.com/83065937/140272436-5824d905-97e8-4b3f-a4a7-de4e4126c4ce.PNG)

![result2](https://user-images.githubusercontent.com/83065937/140272447-c43b6159-8061-4f74-b2ce-9d713c38bf0b.PNG)

## 後続タスク

画面幅に応じて、 page の item の高さを変更する必要があります（左右のページ分割幅なども修正を行ってから）

2021-11-04 10:26 UTC, yuki-takei requested changes

2021-11-04 10:26 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +}
SP 対応はこのタスクのスコープでやってください。

2021-11-04 10:26 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  };
.text-truncate で対応できないかな。
https://getbootstrap.jp/docs/4.5/utilities/text/#text-wrapping-and-overflow

2021-11-05 11:41 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +}
画面幅を変えた際にも対応しました。

2021-11-05 11:43 UTC, yuto-oweseek commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  };
.text-truncate は1行のみのようだったので、 css で複数行対応のものにしました。

対応ブラウザは IE 以外で、 IE でも、 ... が出現しないだけのようです( IE で growi が開けなかっため未確認)

2021-11-05 14:07 UTC, yuki-takei requested changes

2021-11-05 14:07 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +  -webkit-box-orient: vertical;
こちらも vendor prefix でしか解決できないのだとすると別の解を模索したい。

2021-11-10 12:44 UTC, yuki-takei requested changes

2021-11-10 12:44 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  };
第四の選択肢
https://www.npmjs.com/package/react-multiline-clamp

2021-11-10 12:44 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +const MAX_SNIPPET_LENGTH = 180;
この length って仮当て？レスポンシブ対応可能なの？

2021-11-11 07:53 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +  height: 130px;
高さは 130px で PC  から mobile までで崩壊しません。

2021-11-11 07:53 UTC, yuto-oweseek commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +const MAX_SNIPPET_LENGTH = 180;
使わない方針にしました。

2021-11-11 07:53 UTC, yuto-oweseek commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  };
react-multiline-clamp を使用させていただきました。

2021-11-11 07:53 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +  -webkit-box-orient: vertical;
削除済みです。

2021-11-11 08:12 UTC, yuki-takei approved these changes

2021-11-11 09:23 UTC, merged