Feat/77525 80783 control selected pages
weseek/growi pull request #4592
Opened 2021-11-04 07:36 UTC by ryohi15

使われてなった function を使用

2021-11-04 10:30 UTC, yuki-takei requested changes

2021-11-04 10:30 UTC, yuki-takei commented on packages/app/src/components/SearchPage.jsx
> +        toggleCheckBox={this.toggleCheckBox}
refs: [/Tips/JavaScript/命名規則](https://tips.weseek.co.jp/60ae84d41091010049bed55d)

2021-11-04 10:30 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  }) => void,
IPage を継承した interface を作ってください。
誰か他のブランチでやってたと思う。

2021-11-08 08:51 UTC, ryohi15 commented
## タスク
https://estoc.weseek.co.jp/redmine/issues/80783

2021-11-09 03:34 UTC, Yohei-Shiina requested changes

2021-11-09 03:34 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  onChangedInvoked: (page: ISearchedPage) => void,
nullableにしてください

2021-11-09 03:34 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +              onClick={() => { onChangedInvoked(page) }}
null checkしてください

2021-11-11 07:59 UTC, yuki-takei requested changes

2021-11-11 07:59 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +                if (props.onChangedInvoked == null) { logger.error('onClickInvoked is null') }
この logger はいらない

2021-11-11 07:59 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +          if (props.onClickInvoked == null) { logger.error('onClickInvoked is null') }
この logger はいらない

2021-11-12 07:30 UTC, merged