wip 80481
weseek/growi pull request #4594
Opened 2021-11-04 09:47 UTC by maow89126

2021-11-11 07:09 UTC, yuki-takei requested changes

2021-11-11 07:09 UTC, yuki-takei commented on packages/app/src/client/services/PageContainer.js
> +  async updateStateAfterLike() {
update というメソッド名にするなら引数を取るべき。
中身がこのままなら toggle というメソッド名の方がしっくり来る。(normal page だけで search page では使わないよっていうコメントはそのままにする。名前からではわからないので。)

2021-11-11 07:09 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> +  const SearchResultSubNavButtonTypeAny: any = SearchResultSubNavButton;
このワークアラウンド禁止

2021-11-11 07:09 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.jsx
> +      }
ここの異常系処理がこれでいいと思えない

2021-11-11 07:09 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultSubNavButton.tsx
> +const SearchResultSubNavButton : FC<Props> = (props: Props) => {
SearchResultSubNavButton コンポーネントの存在はこのままでよい。appContainer に依存するのも OK。

2021-11-11 07:09 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultSubNavButton.tsx
> +const PageReactionButtons : React.FC<PageReactionButtonsProps> = (props: PageReactionButtonsProps) => {
PageReactionButtons は AppContainer に依存しない形で共通化できるはず。

- SubNavButtons にも似たようなのが重複して存在している
- onChangeInvoked の中のロジックも PageContainer の中身と重複している

2021-11-12 07:07 UTC, maow89126 commented on packages/app/src/components/Navbar/SubNavButtons.jsx
> +      }
この処理はPageReactionButtons作成により無くなりました。

2021-11-12 07:08 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultSubNavButton.tsx
> +const PageReactionButtons : React.FC<PageReactionButtonsProps> = (props: PageReactionButtonsProps) => {
はい。

2021-11-12 07:09 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultSubNavButton.tsx
> +const PageReactionButtons : React.FC<PageReactionButtonsProps> = (props: PageReactionButtonsProps) => {
PageReactionButtonsはlikeのみ表示されてます。

Bookmarkは [ここで](https://redmine.weseek.co.jp/issues/81076)のっけます

2021-11-12 07:14 UTC, maow89126 commented on packages/app/src/components/SearchPage.jsx
> +      focusedPage: null,
統合を追従したときにエラーが出たので一時的に対応。
#77515storyで同様のことをしてある。
https://redmine.weseek.co.jp/issues/79012

2021-11-12 07:57 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> +  const SearchResultSubNavButtonTypeAny: any = SearchResultSubNavButton;
直しました。wrrapper使いました。

2021-11-12 09:25 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> +  const SearchResultSubNavButtonTypeAny: any = SearchResultSubNavButton;
TypeAnyのところは対応中です。

2021-11-12 10:31 UTC, yuki-takei requested changes

2021-11-12 10:31 UTC, yuki-takei commented on packages/app/src/components/BookmarkButton.jsx
> +      }
この else block は不要

2021-11-12 10:31 UTC, yuki-takei commented on packages/app/src/components/LikeButtons.jsx
> +      }
else block は不要

2021-11-12 10:31 UTC, yuki-takei commented on packages/app/src/components/LikeButtons.jsx
> +          onClick={async() => { await this.handleClick() }}
`onClick={this.handleClick}` のままでいいと思う

2021-11-12 10:31 UTC, yuki-takei commented on packages/app/src/components/PageReactionButtons.tsx
> +  const LikeButtonsTypeAny: any = LikeButtons;
このワークアラウンドは禁止

2021-11-12 10:31 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  focusedPage : null | any,
`focusedPage?: IPage,`
にする。(IPage ではなくそのサブタイプかもしれないが)

2021-11-12 10:31 UTC, yuki-takei commented on packages/app/src/components/PageReactionButtons.tsx
> +  }, []);
- SWR 化してください
- データ取得はこのコンポーネントで行わず、親で行ってください

2021-11-15 14:54 UTC, maow89126 commented
コメント頂いてないところでもtypeAnyのワークアラウンド残ってたので一部直しました。
SearchResultContent内です。

2021-11-16 04:14 UTC, maow89126 commented on packages/app/src/components/PageReactionButtons.tsx
> +  }, []);
SWR化しました。
swr methodを置くところが自信なかったのですが一応/pagesから始まるapi叩いていたので/stores/pageに置きました。

2021-11-16 09:23 UTC, yuki-takei requested changes

2021-11-16 09:23 UTC, yuki-takei commented on packages/app/src/components/LikeButtons.jsx
> +      }
APIを叩く処理はこのコンポーネントではやらない。

2021-11-18 07:25 UTC, maow89126 commented on packages/app/src/components/LikeButtons.jsx
> +      }
mutateを使いました。

2021-11-18 07:25 UTC, maow89126 commented on packages/app/src/components/PageReactionButtons.tsx
> +  };
swr勘違いしてました。。

2021-11-18 07:26 UTC, maow89126 commented on packages/app/src/stores/page.tsx
> +  return useSWR(`page/info?pageId=${pageId}`, endpoint => apiv3Get(endpoint).then((response) => {
直しました。

2021-11-18 08:15 UTC, maow89126 commented
swrかして気づいたのですが、subNavButtons.tsxを完全に共通化できることに気づいたのでSearchResultSubNavButtonは無くしてSubNavButtonsを引き続き使用しました。

2021-11-18 10:23 UTC, yuki-takei requested changes

2021-11-18 10:23 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +};
これじゃだめ。TS に正面から向き合って。

2021-11-18 10:23 UTC, yuki-takei commented on packages/app/src/components/PageReactionButtons.tsx
> +};
これもだめ。

2021-11-18 10:23 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +          }}
`onLikeClicked={likeClickedHandler}`

2021-11-18 10:23 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  const onLikeClicked = useCallback(async(isLiked) => {
`const likeClickedHandler = ...`
にする

2021-11-18 10:23 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +      await apiv3Put('/page/likes', { pageId, bool: !isLiked });
`!isLiked` は、`pageInfo` から取れる。

2021-11-19 00:02 UTC, maow89126 commented
コメントいただいたところ以外でも
SubNavButtonsとSearchResultContentSubNavigationでも同様のworkaroundしてたので直しました。
この二つはtsxコンポーネントなので普通に使えると思ったのですが、withUnstatedしてるので props.hoge does not exst on ...
と出てたのでwrappingしました。

2021-11-19 00:28 UTC, yuki-takei approved these changes

2021-11-19 00:28 UTC, merged