feat: Add PageTree sidebar
weseek/growi pull request #4603
Opened 2021-11-04 21:34 UTC by takayuki-t

## refs

## 画面イメージ

![image](https://user-images.githubusercontent.com/52646333/140423035-a3b9c056-ae15-4cd9-924d-af123840684f.png)

2021-11-05 06:03 UTC, yuki-takei requested changes

2021-11-05 06:03 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree.jsx
> +class PageTree extends React.Component {
新しく作るコンポーネントは functional component かつ tsx で

2021-11-08 01:51 UTC, hakumizuki commented
ここから巻き取りました。TS 化、FC 化しました

2021-11-08 06:00 UTC, yuki-takei approved these changes

2021-11-08 06:00 UTC, merged