[WIP] feat: Api get pages around target
weseek/growi pull request #4608
Opened 2021-11-05 03:30 UTC by hakumizuki

[WIP]

Redmine: https://estoc.weseek.co.jp/redmine/issues/80359

ターゲットページから、「兄弟、ターゲット、祖先全て」を取得する API を実装しました。

2021-11-05 03:32 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
>  };
下でも使うので Viewer に関する条件を切り出しました

2021-11-05 09:17 UTC, yuki-takei requested changes

2021-11-05 09:17 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/page-tree.ts
> +  router.get('/pages', accessTokenParser, loginRequiredStrictly, ...validator.getPagesAroundTarget, async(req: AuthorizedRequest, res: ApiV3Response): Promise<any> => {
## モジュール設計
ファイル名を pages-listing.ts にしよう


## API 設計
- children 取得 API
    - siblings 取得 API
- ancestors 取得 API
- ancestors + siblings 取得 API

に分ける

2021-11-05 09:17 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +  let regexp = new RegExp(`^${parentPath}(\\/[^/]+)\\/?$`);
- regex101 の example を載せよう
- re2 を利用しよう

2021-11-05 09:17 UTC, yuki-takei commented on packages/app/src/interfaces/page.ts
> +type Ref<T> = string | T;
共通化

2021-11-06 06:53 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/page-tree.ts
> +  router.get('/pages', accessTokenParser, loginRequiredStrictly, ...validator.getPagesAroundTarget, async(req: AuthorizedRequest, res: ApiV3Response): Promise<any> => {
この PR では ancestors 取得と siblings 取得に分けました
別タスクで children 取得、ancestors siblings 取得の API を実装します

2021-11-06 06:53 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +  let regexp = new RegExp(`^${parentPath}(\\/[^/]+)\\/?$`);
しました

2021-11-06 06:53 UTC, hakumizuki commented on packages/app/src/interfaces/page.ts
> +type Ref<T> = string | T;
しました

2021-11-06 08:02 UTC, merged