feat: select background of parent
weseek/growi pull request #4613
Opened 2021-11-05 10:33 UTC by yuto-oweseek

## タスク

https://estoc.weseek.co.jp/redmine/issues/80533

## 行ったこと

- 左側ページの検索ボックス周辺をXDの見た目に近づけました
- 
![search page left pane](https://user-images.githubusercontent.com/83065937/140497209-7cd20460-3fd2-4533-8651-c838c7f898fb.PNG)

## 後続タスク（既に別ブランチで行われている可能性あり）

- button の見た目や配置の調整

2021-11-05 14:03 UTC, yuki-takei requested changes

2021-11-05 14:03 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +    }
vendor prefix 付きのスタイルは scss には記述せず、webpack の postcss により自動生成すべき。

…と書かれてもわけがわからないと思うので、バグ報告と同じレギュレーションで「どうなっているべきなのか」を示すタスクを作ってください。レギュレーションがなんのことか分からない場合は社員に確認。

2021-11-11 11:42 UTC, yuto-oweseek commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +        </div>
flex-grow を利用した リギッドデザインに変更しました。

2021-11-11 11:42 UTC, yuto-oweseek commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +        <div className="col-5"></div>
こちらもグリッドから、リギッドデザインに変更しました。

2021-11-11 11:42 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +  }
@extend の記述を利用して共通化しました。

2021-11-11 11:42 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +    border-radius: 16rem !important;
すみません、ぼくのコメントが Pending になっていました。

ここは共通化されているコンポーネント内部に対して、無理やりスタイルをあてているため、この記述です。

また、 `_override-bootstrap-variables.scss` にある border-radius では丸っこさが足りなかったので、16px を直接指定しています。

2021-11-11 11:42 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +    }
> vendor prefix 付きのスタイルは scss には記述せず、webpack の postcss により自動生成すべき。

↑の実装方法が全くの謎なので、バグストーリーを参考にして、以下のタスクを作成しました。

https://estoc.weseek.co.jp/redmine/issues/81328

2021-11-11 11:51 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +    border-radius: 16rem !important;
共通化されているコンポーネント内部のスタイルを無理やり上書きしているため、この記述です。

2021-11-12 10:05 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +    border-radius: 16rem !important;
この input での角丸やめるかもしれないので、この記述なしでよいです(一旦見た目中途半端でもよい)

2021-11-12 10:08 UTC, yuki-takei requested changes

2021-11-12 10:08 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +  }
消す

2021-11-12 10:08 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +  color: $gray-400;
theme でやるべきなので一旦消す。

2021-11-12 10:08 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +    }
消す

2021-11-12 10:14 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +    }
削除

2021-11-12 10:14 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +  color: $gray-400;
削除

2021-11-12 10:24 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +  }
クリックした後に以下の画像みたくなるので、ここは残してます。

![shodow-shown](https://user-images.githubusercontent.com/83065937/141451685-2c5e797a-8bd8-4914-b22a-2e9b103281ef.PNG)

2021-11-12 10:25 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +    border-radius: 16rem !important;
削除

2021-11-12 10:50 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +    border-radius: 16rem !important;
四角くなりました

2021-11-12 10:50 UTC, yuto-oweseek commented on packages/app/src/styles/_search.scss
> +    border-radius: 16rem !important;
![square](https://user-images.githubusercontent.com/83065937/141455308-b1c16226-dbd0-48ad-aa8a-ee0c2f291593.PNG)

2021-11-12 11:47 UTC, merged