Feat/77543 80875 refactoring
weseek/growi pull request #4614
Opened 2021-11-08 02:06 UTC by ryohi15

## したこと
- jsx ファイルを tsx 化

2021-11-08 03:15 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +          <PagenationWrapperAny
IPagniationWrapper の interface を作成して、それを呼び出し時に指定して解決できるならそれでもよさそうだが、無理なら他と同じように work around で any のままでよさそう

```
interface IPagenationWrapper{
    activePage: number
    ....
}
```

```
<PaginationWrapper<IPagenationWrapper>
/>
```

2021-11-08 03:29 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +          <PagenationWrapperAny
PaginationWrapper 側で type を受け取るよういなっていないからダメそう

2021-11-08 03:39 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +            activePage={props.activePage}
required な値に null / undefined かもしれない値を渡すのはよくないので対応が必要

totalItemsCount を参考にしてください

2021-11-08 03:50 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +  searchResultCount: number,
これは required にした方がいいかもしれない

2021-11-08 03:51 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +      {props.searchResultCount != null && props.searchResultCount > 0 && (
searchResultCount を required にしたらこれが不要になる

2021-11-08 03:51 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +            totalItemsCount={props.searchResultCount || 0}
searchResultCount を required にしたらこれも不要になる

2021-11-08 06:39 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +  activePage: number,
pagination がない時は不要なので nullable が正しい

2021-11-08 06:49 UTC, Yohei-Shiina requested changes

2021-11-08 06:49 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +  searchResultCount?: number,
SearchPage.jsxの方も修正お願いします

たとえば pages はこの type 定義内では required になっているけれど、このコンポーネントの呼び出し側である SearchPage からpages を渡すときに  null check がされていない

2021-11-08 07:24 UTC, Yohei-Shiina approved these changes

2021-11-08 08:45 UTC, yuki-takei requested changes

2021-11-08 08:45 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +  const PagenationWrapperAny: any = PaginationWrapper;
こういうワークアラウンド増えていくのは受け入れられない。

2021-11-09 08:52 UTC, yuki-takei approved these changes

2021-11-09 09:01 UTC, merged