Imprv/jump to page when notification clicked
weseek/growi pull request #4619
Opened 2021-11-08 07:15 UTC by kaoritokashiki

2021-11-08 08:02 UTC, yuki-takei requested changes

2021-11-08 08:02 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/NotificationContent.tsx
> +    </div>
前に FB したと思うけど、コンポーネントが量産されるのはよくないので統合してください。
後続タスクにするといつまでも解決しないので、このタスクのスコープでやって。

2021-11-09 11:43 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationList.tsx
> +    </>
この中でnotificationがある場合とない場合分けるのではなく、renderInAppNotificationListの中で分けた方がいいですかね...?

2021-11-09 11:45 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/NotificationContent.tsx
> +    </div>
修正しました。

2021-11-09 19:33 UTC, yuki-takei requested changes

2021-11-09 19:33 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
> +  const notificationClickHandler = async() => {
useCallback を使う

2021-11-09 19:33 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
> +      await apiv3Post('/in-app-notification/open', { id: notification._id });
await せず投げっぱなしでよいです。try-catch も消す。

2021-11-09 19:33 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/InAppNotificationList.tsx
> +    </>
ここで大丈夫

2021-11-10 03:00 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
> +  const notificationClickHandler = async() => {
使用しました。

2021-11-10 03:01 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
> +      await apiv3Post('/in-app-notification/open', { id: notification._id });
了解です。修正しました。

2021-11-10 03:06 UTC, merged