Feat/80103 check subscribe rule of in app notification settings when creating a page
weseek/growi pull request #4624
Opened 2021-11-08 09:22 UTC by miya

## Task
[#80103](https://estoc.weseek.co.jp/redmine/issues/80103) [server] ページを作成する際に in-app-notification-settings ドキュメントの subscribe rule を参照し、PAGE_CRETE の isEnabled が true だったら Subscription ドキュメントを作成できる

2021-11-08 10:17 UTC, yuki-takei requested changes

2021-11-08 10:17 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/pages.js
> +      if (inAppNotificationSettings) {
`!= null`

2021-11-08 10:17 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/pages.js
> +        }
このロジックはサービス層に移動

2021-11-08 10:20 UTC, miya commented on packages/app/src/server/routes/apiv3/pages.js
> +      if (inAppNotificationSettings) {
何度もすいません。。修正しました。

2021-11-09 07:08 UTC, yuki-takei commented on packages/app/src/server/service/in-app-notification-settings.ts
> +  createSubscription = async(userId, pageId, targetRuleName) => {
in-app-notification.ts への実装でよいです。
eslint の warning 出ないようにして。

2021-11-09 07:10 UTC, yuki-takei requested changes

2021-11-09 07:10 UTC, yuki-takei commented on packages/app/src/server/service/in-app-notification-settings.ts
> +      if (subscribeRule !== undefined && subscribeRule.isEnabled) {
`!= null`

2021-11-09 08:59 UTC, yuki-takei requested changes
FB

2021-11-11 04:54 UTC, merged