Feat/78837 77804 display icons
weseek/growi pull request #4630
Opened 2021-11-09 09:48 UTC by Yohei-Shiina

[#77804](https://estoc.weseek.co.jp/redmine/issues/77804)
足跡を表示

![image](https://user-images.githubusercontent.com/35527421/140901402-00ad0f61-2123-44f8-8548-fb97d2b900da.png)

2021-11-09 10:47 UTC, Yohei-Shiina commented on packages/ui/src/components/PagePath/PageListMeta.jsx
> +    if (page.seenUserCount > 0) {
PageListMeta コンポーネントを利用しているすべての箇所に影響しないように
検索時に追加される `page.seenUserCount` が存在するときのみ表示する

2021-11-09 10:49 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +    }
足跡は icon がなく svg 表示のため、個別に調整を入れた

2021-11-09 10:51 UTC, Yohei-Shiina commented on packages/app/src/styles/theme/_apply-colors.scss
> +      }
_reboot-bootstrap-colors.scss で svg の色が青に指定されているため、
他アイコンと同様の色で検索結果一覧の足跡アイコンのみ上書きするように変更

2021-11-09 19:27 UTC, yuki-takei requested changes

2021-11-09 19:27 UTC, yuki-takei commented on packages/ui/src/components/PagePath/PageListMeta.jsx
> +import FootstampIcon from '../../../../app/src/components/FootstampIcon';
from の対象がおかしい

2021-11-09 19:27 UTC, yuki-takei commented on packages/app/src/styles/theme/_apply-colors.scss
> +$svg-fill-color: #3f474e;
- 命名NG
- 値が妥当だと思えない
    - 他の例に倣ってどこかから借りてくる
    - `!default` を付けてテーマ毎に上書きできるように

2021-11-11 05:54 UTC, Yohei-Shiina commented on packages/app/src/styles/theme/_apply-colors.scss
> +$bgcolor-search-item-active: lighten($bordercolor-search-item-left-active, 76%) !default;
別タスクで付けていなかったのでついでに !default を追加

2021-11-11 07:54 UTC, yuki-takei requested changes

2021-11-11 07:54 UTC, yuki-takei commented on packages/app/src/styles/theme/_apply-colors.scss
> +$color-pagelist-meta: $gray-500 !default;
`.page-list-meta` を適用する全箇所に使うなら他にも書き換える箇所があるはず。  
search item に限るならそういう名前にする。

2021-11-11 13:11 UTC, merged