feat: Pt fetch initial data (client)
weseek/growi pull request #4632
Opened 2021-11-09 10:36 UTC by hakumizuki

Redmine: https://estoc.weseek.co.jp/redmine/issues/80791

## 変更内容
- isPartialChildren は不要になったので削除しました
- １回目の SWR で ancestors のみを取得していたのを target と ancestors 両方を取得するように書き換えました
- ２回目の SWR で target 以外の node の children をサーバーから取得し、各 node を更新してからレンダリングするようにしました
- 正しく動けば計３回 ItemsTree がレンダリングされるようになっています (null, target & ancestors, target & ancestors & ancestors-children)

## 後続について
- ancestors-children API を実装します
- ItemsTree コンポーネントに props で path と id を渡すようにします

2021-11-09 19:19 UTC, yuki-takei requested changes

2021-11-09 19:19 UTC, yuki-takei commented on packages/app/src/stores/page-listing.tsx
> +};
こっちはページロード時に1度だけ必要となるデータなので、サーバーサイドで取得して swig 経由で渡そう。

1. routes/page.js の showTopPage と showPageForGrowiBehavior で addRenderVarsForXXX を追加する
    - ツリーを描画できる最小限のデータにする 
2. page_content.html の `data-*` attribute に入れる
3. stores/context.tsx で useStaticSWR を使って初期化

因みに Next.js 化した暁には、2までは getServerSideProps 相当で行うことになるので、いずれ消すコードである。そこまでは汚くても妥協する。

2021-11-09 19:19 UTC, yuki-takei commented on packages/app/src/interfaces/page.ts
> +  _id?: string,
Mongoose の Document で追加されるプロパティなので、ここでは追加してはいけない。
代わりに [HasObjectId](https://github.com/weseek/growi/pull/4598/files#diff-3deec91e1b5656d0ce0175959d163cebd6fb4b601553dcd3fdae38e7c7b7bcf0R10) をこのブランチへも移植する。

2021-11-09 19:19 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +export interface PageDocument extends Omit<IPage, '_id'>, Document {}
元に戻す

2021-11-10 03:50 UTC, hakumizuki commented on packages/app/src/interfaces/page.ts
> +  _id?: string,
移植しました

2021-11-10 03:50 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +export interface PageDocument extends Omit<IPage, '_id'>, Document {}
戻しました

2021-11-10 06:34 UTC, hakumizuki commented on packages/app/src/stores/page-listing.tsx
> +};
移植してきて useStaticSWR を使いました

2021-11-10 07:06 UTC, merged