Feat/77525 81100 check if selected pages has page
weseek/growi pull request #4637
Opened 2021-11-10 11:15 UTC by ryohi15

## タスク
https://estoc.weseek.co.jp/redmine/issues/81100

## したこと
selectedPages に値が入れば SearchresultListItem の checkbox にチェックが入るようにした  
これにより検索結果一覧のアイテムを全選択したときに、全選択 or 全選択解除ができるようになった

2021-11-11 07:03 UTC, TatsuyaIse requested changes

2021-11-11 07:03 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +    page, isSelected, onClickInvoked, onChangedInvoked, isChecked,
今指摘することじゃないかもだけど、 onChangedInvoked の名前ってなんか変じゃないかな、  
この辺の命名を大リファクタするタスクが欲しい、、、

2021-11-11 07:03 UTC, TatsuyaIse commented on packages/app/src/interfaces/page.ts
> +import { IUser } from './user';
これは、何の差分？？

2021-11-11 07:42 UTC, ryohi15 commented on packages/app/src/interfaces/page.ts
> +import { IUser } from './user';
コンフリクト解消の際に UTF-8 with BOM になってたのでそれを解消した差分ですね

2021-11-11 07:43 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +  },
解決

2021-11-11 07:43 UTC, ryohi15 commented on packages/app/src/components/SearchPage.jsx
> +      this.forceUpdate();
done

2021-11-11 07:47 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +    page, isSelected, onClickInvoked, onChangedInvoked, isChecked,
todo コメント書きました

2021-11-12 02:31 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +    });
if ... else のままだった方がよくないか？  
ってか if ... else をやめたらダメなんじゃないか？

2021-11-12 02:31 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +    this.forceUpdate();
`forceUpdate()` 実行のタイミングって `this.updateCheckboxState()` を呼んだ後の方が適切なんじゃない？

2021-11-12 02:31 UTC, TatsuyaIse commented on packages/app/src/interfaces/page.ts
> +import { IUser } from './user';
> コンフリクト解消の際に UTF-8 with BOM になってた

ツールの設定がおかしいと思うので見直しておいてください。

2021-11-16 04:45 UTC, TatsuyaIse requested changes

2021-11-16 04:45 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +      this.forceUpdate();
if ... else ... の分岐処理が終わったあとにまとめてやってるからここには不要だよね？  
っというところ辺り (その処理周辺を見れば気づけるハズな部分) のチェックがまだ甘いですねぇ～  
気を付けてみてみよう。

2021-11-16 12:12 UTC, yuki-takei requested changes

2021-11-16 12:12 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +        const isChecked = selectedPages.has(page);
オブジェクト同士の比較ってパフォーマンス的に問題出ないのかな？ID 比較の方が早そう。

2021-11-16 12:12 UTC, yuki-takei commented on packages/app/src/components/SearchPage.jsx
> +    this.forceUpdate();
forceUpdate が必要になることってあまりないと思うんだけど、今回のケースは必須なの？
`setState({ selectedPages })` せずに敢えて `this.state.selectedPages = ...` にしているのは理由がある？

2021-11-17 03:35 UTC, merged

2021-11-17 06:40 UTC, ryohi15 commented
> forceUpdate が必要になることってあまりないと思うんだけど、今回のケースは必須なの？
setState({ selectedPages }) せずに敢えて this.state.selectedPages = ... にしているのは理由がある？

理由としては、Set の中身の要素を削除したり追加したりするのに Set クラスの add() や clear() を使いたくて setState() は使ってないです。
(Set クラスの add() や clear() を使いたい理由としては、state の selectedPages の初期値を new Set() にしてるので、せっかくだしクラスで用意されてるメソッド使いたいという理由です。)
そうなると、state の値に変更が加わったことをコンポーネントが知ることができないので forceUpdate() して知らせてます。