Imprv/80107 add pagination to all in app notifications
weseek/growi pull request #4642
Opened 2021-11-10 17:53 UTC by kaoritokashiki

2021-11-11 07:14 UTC, yuki-takei requested changes

2021-11-11 07:14 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/in-app-notification.ts
> +    };
API 仕様は変更せず、page/limit と offset/limit の相互変換はコンポーネント側または SWR 側で吸収してください。

2021-11-12 07:05 UTC, kaoritokashiki commented on packages/app/src/stores/in-app-notification.ts
> +  offset?: number,
ドロップダウンの方ではページネーションをしないので `offset`はoptionalにしています。

2021-11-12 07:30 UTC, yuki-takei requested changes

2021-11-12 07:30 UTC, yuki-takei commented on packages/app/src/stores/in-app-notification.ts
> +    `/in-app-notification/list?limit=${limit}&offset=${offset}`,
offset が optional だとこの key 指定は微妙。

key は array にして。
https://swr.vercel.app/ja/docs/arguments

param は apiv3Get の第二引数で渡せるはず。

2021-11-12 07:32 UTC, yuki-takei requested changes

2021-11-12 07:32 UTC, yuki-takei commented on packages/app/src/server/service/in-app-notification.ts
> +    const offset = queryOptions.offset || 0;
offset の初期値は route 側で設定してない？

2021-11-14 17:54 UTC, kaoritokashiki commented on packages/app/src/stores/in-app-notification.ts
> +    `/in-app-notification/list?limit=${limit}&offset=${offset}`,
ありがとうございます。修正しました。

2021-11-14 18:11 UTC, kaoritokashiki commented on packages/app/src/server/service/in-app-notification.ts
> +    const offset = queryOptions.offset || 0;
その通りですね。すみません削除しました。

2021-11-14 23:13 UTC, yuki-takei approved these changes

2021-11-14 23:13 UTC, merged