Feat/77525 80785 implement select all
weseek/growi pull request #4645
Opened 2021-11-11 05:41 UTC by ryohi15

## タスク
https://estoc.weseek.co.jp/redmine/issues/80785

## したこと
検索結果一覧のアイテムの CheckBox の状態によって一括選択ボタンの状態を変える

2021-11-11 07:07 UTC, TatsuyaIse commented
PR の説明の ↓↓ この記載 ↓↓ は正しい？

## 注意
マージは #4637 と #4592 がマージされてからでお願いします

2021-11-11 07:41 UTC, TatsuyaIse requested changes

2021-11-11 07:41 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +        break;
let を使いたくないので、この switch 文を部分的に **内部** メソッドに切り出す
このメソッド本体では、そのメソッドを呼び出して得た値で checkboxState の state を更新させる
切り出したメソッドの実態としては、 selectedPages.size と searchedPages.length を引数に CheckboxType の適切な何かしらを return させるという

2021-11-11 07:41 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +  }
これは何用？？

2021-11-11 07:41 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  onClickAllSelectButton?: () => void,
これ使ってる？？  
(不要になった認識)

2021-11-11 07:41 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +    else { props.onClickInvoked() }
onCheckAllPagesInvoked をわざわざ定義せずに props をそのまま子コンポーネントに横流ししたら？？

2021-11-11 07:41 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +                  onChangedInvoked(page);
`onChangedInvoked` って名前は適切じゃないね。(onChange じゃないので、、、)

2021-11-11 07:51 UTC, ryohi15 commented
> PR の説明の ↓↓ この記載 ↓↓ は正しい？
注意
マージは #4637 と #4592 がマージされてからでお願いします

上記は消しました

2021-11-11 07:53 UTC, ryohi15 commented on packages/app/src/components/SearchPage.jsx
> +  }
不要でした

2021-11-11 08:07 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  onClickAllSelectButton?: () => void,
不要でした

2021-11-12 01:54 UTC, TatsuyaIse requested changes

2021-11-12 01:54 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +  getCheckboxType = (selectedPagesCount) => {
前回のレビュー時に

> この switch 文を部分的に **内部** メソッドに切り出す

って書いていたんだけど、その通りになっていないのに回答もないのはなんで？  
言ってることが分からなかったらその時に聞いてほしい。

2021-11-12 01:54 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +            logger.error(error);
function の props の null check で例外を throw して、catch したところで logger.error だけさせるのはダメじゃんって話だったよね？  
適切な分岐処理にしよう

2021-11-12 01:54 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +                }
こっちも

2021-11-16 04:25 UTC, TatsuyaIse requested changes

2021-11-16 04:25 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +    if (onClickInvoked == null) { throw new Error('onClickInvoked is null') }
例外 throw するだけっていうのはナシ
前回レビューしたときのコメントをよく読んで

2021-11-16 04:25 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +    if (onClickCheckboxInvoked == null) { throw new Error('onClickCheckboxInvoked is null') }
こちらも  
適切に **分岐処理** してください。  
  
- 渡された props のメソッドが null ならエラーログを出力  
- null 以外なら呼び出し

2021-11-16 04:25 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +  }
関数コンポーネントだったら、 React Hooks の useMemo を使って実現できるのにね。  
これはただの垂れ流しコメントなので見たら自分で Resolve しといて

2021-11-16 09:34 UTC, yuki-takei requested changes

2021-11-16 09:34 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +    else onClickInvoked(page._id);
- if-else ブロックが読みにくい
- null チェックは必要だが、null だった場合の logger.error はいらない

2021-11-16 09:34 UTC, yuki-takei commented on packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> +    else { onCheckInvoked() }
- if-else ブロックが読みにくい
- null チェックは必要だが logger.error は不要

2021-11-16 09:34 UTC, yuki-takei commented on packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> +        onClick={onCheckAllPages}
onClick 時に onCheckAllPages がトリガーされるのはおかしいのでは？チェックが外される場合もあるよね？

2021-11-16 09:34 UTC, yuki-takei commented on packages/app/src/components/SearchPage.jsx
> +  updateCheckboxState = () => {
名前が不明瞭。どのチェックボックスの state のアップデート？
全てなら all 等の単語を名前に入れて

2021-11-17 01:46 UTC, TatsuyaIse requested changes

2021-11-17 01:46 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +    if (this.state.selectedPages.size === this.state.searchedPages.length) {
これ、改めて見たら state の `checkboxState` が `ALL_CHECKED` かどうか の判断でよさそうだなという気づき

2021-11-17 01:46 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +      checkboxState: CheckboxType.NONE_CHECKED,
何の checkboxState なのか？が不明瞭  
・・・というかそもそも checkboxState なのか？  
このコンポーネントには checkbox なんて存在しないよね？  
命名で大事なのは、こいつが何者なのか正しくハッキリ言い表せられる言葉に当たるまでちゃんと突き詰めて考えること。

2021-11-17 01:46 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +    function getCheckboxType(selectedPagesCount, searchedPagesCount) {
正直、 checkboxState って不要で、  
このタイプ (checkbox という命名は外してほしいが、) を取得できる getter があればいいんではないかと思っている。  
(何か理由があってできないんだったっけ？)

2021-11-17 01:46 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> +        onClick={onCheckAllPages}
`onClickAllPageCheckbox` の意図だと認識していたけれど、見直したら良くない命名だったなと思う。  
名前が長くなるかもしれないけど、素直にそのまま命名していいかと

2021-11-17 01:46 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> +        checked={checkboxState !== CheckboxType.NONE_CHECKED}
`checkboxState` という命名も良くないね。  
(上位のコンポーネントでも見直すし、ついでに) 見直そう。  
選択状態がどうか？というところに着目するのが大事

2021-11-17 02:42 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +    if (this.state.selectedPages.size === this.state.searchedPages.length) {
ココからはその state が消えるので今のままで大丈夫

2022-01-28 04:12 UTC, closed without merging