imprv: Use swr to extract context from DOM
weseek/growi pull request #4660
Opened 2021-11-12 11:53 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/81414, https://redmine.weseek.co.jp/issues/81432

PageContainer の DOM から取得している context を全て static swr 化しました。他にも getter などありますが、PT のブロックは解消できたので一旦ここまでにします

## その他のコード
- useStaticSWR を移植してきました
  - PT の方と全く同じ実装

2021-11-12 12:03 UTC, yuki-takei requested changes

2021-11-12 12:03 UTC, yuki-takei commented on packages/app/src/client/services/ContextExtractor.tsx
> +      なに
削除

2021-11-12 12:03 UTC, yuki-takei commented on packages/app/src/client/services/ContextExtractor.tsx
> +  usePath(path);
https://github.com/weseek/growi/blob/dev/5.0.x/src/stores/context.tsx

にあるものは名前揃えといてください。useCurrentPagePath とか。

2021-11-13 05:05 UTC, hakumizuki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  usePath(path);
揃えました

2021-11-13 05:05 UTC, hakumizuki commented on packages/app/src/client/services/ContextExtractor.tsx
> +      なに
削除しました

2021-11-13 05:06 UTC, hakumizuki commented
currentUser も加えました

2021-11-13 05:48 UTC, merged