Fix/80942 hit api multi times when page scrolled
weseek/growi pull request #4663
Opened 2021-11-12 22:26 UTC by kaoritokashiki

2021-11-12 22:37 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/SubNavButtons.jsx
> +const SubnavButtons = React.memo((props) => {
`React.memo`を使用することで、親コンポーネント(`GrowiSubNavigation`) のレンダリング時に、子コンポーネントが無駄にレンダリングされることを防ぐしました。

2021-11-12 22:44 UTC, kaoritokashiki commented on packages/app/src/components/SubscribeButton.tsx
> +    );
dataがnullの時は初期値のsubscribe iconを返すようにしています。

2021-11-14 23:10 UTC, yuki-takei requested changes

2021-11-14 23:10 UTC, yuki-takei commented on packages/app/src/components/SubscribeButton.tsx
> +    );
これではクリック時に動作しなくない？
今回のは早期リターンに適さないと思う。

2021-11-14 23:10 UTC, yuki-takei commented on packages/app/src/components/SubscribeButton.tsx
> +  switch (subscriptionData.status) {
ここを `subscriptionData?.status` にすればよいだけでは？

2021-11-14 23:10 UTC, yuki-takei commented on packages/app/src/interfaces/in-app-notification-settings.ts
> +}
使われてなさそう

2021-11-14 23:10 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    'page/subscribe',
- 挙動は変わらないけど endpoint の頭には slash 付けて
- pageId も key に入れる必要がある
    - https://swr.vercel.app/ja/docs/arguments

2021-11-15 05:05 UTC, kaoritokashiki commented on packages/app/src/components/SubscribeButton.tsx
> +  switch (subscriptionData.status) {
なるほどです.......!!! ありがとうございます。

2021-11-15 05:20 UTC, kaoritokashiki commented on packages/app/src/stores/page.tsx
> +    'page/subscribe',
畏まりました。

2021-11-15 05:20 UTC, kaoritokashiki commented on packages/app/src/stores/page.tsx
> +    ['/page/subscribe', pageId],
keyにpageIdも含めました。

2021-11-15 05:21 UTC, kaoritokashiki commented on packages/app/src/interfaces/in-app-notification-settings.ts
> +}
すみません、削除しました。

2021-11-15 05:21 UTC, kaoritokashiki commented on packages/app/src/components/SubscribeButton.tsx
> +    );
こちらは削除しました。

2021-11-15 08:39 UTC, yuki-takei requested changes

2021-11-15 08:39 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    endpoint => apiv3Get(endpoint, { pageId }).then((response) => {
こっちでも pageId を closure の引数として取らないといけない

2021-11-15 09:25 UTC, kaoritokashiki commented on packages/app/src/stores/page.tsx
> +    endpoint => apiv3Get(endpoint, { pageId }).then((response) => {
修正しました。

2021-11-15 09:25 UTC, merged