wip: Feat/80623 TagLabel refactor
weseek/growi pull request #4665
Opened 2021-11-15 03:35 UTC by maow89126

# やったこと
TagLableのpageContainer依存を剥がして、
通常のSubNavでも検索pageのSearchResultContenSubNavでも使えるようにしました。

一旦方向確認、動作確認のためswr化や型付けは雑の状態です。
wip: type厳しくする、swrでdata取得。

動作確認ずみ

![Screen Shot 2021-11-15 at 12 32 29](https://user-images.githubusercontent.com/60797707/141718123-98bb231e-a8b0-4aec-99f0-4004104c1953.png)

2021-11-19 06:52 UTC, hakumizuki requested changes

2021-11-19 06:52 UTC, hakumizuki commented on packages/app/src/stores/page.tsx
> +  // apiGet():Promise<unknown>
このコメントは必要ないと思います

2021-11-19 06:52 UTC, hakumizuki commented on packages/app/src/components/Navbar/GrowiSubNavigation.jsx
> +  const tagsUpdatedHandler = async(newTags) => {
useCallback を使うといいと思います

2021-11-22 01:25 UTC, maow89126 commented on packages/app/src/stores/page.tsx
> +  // apiGet():Promise<unknown>
コミット前に消し損ねてました。消しました。

2021-11-22 01:34 UTC, maow89126 commented on packages/app/src/components/Navbar/GrowiSubNavigation.jsx
> +  const tagsUpdatedHandler = async(newTags) => {
pageIdをdepにしてuseCallBackを使用しました。今回editorContainerやpageContainerも入れないのかとwarning出ましたが、pageId一つで十分なのでwarning消すcomment 入れてあります。

2021-11-22 01:37 UTC, maow89126 commented
一応slackでも答えましたが、
先生がコメントで質問されてた [ここの部分](https://github.com/weseek/growi/pull/4665/files/11be99a61e5e201762ce65b064c5f0214ca7f309#diff-10b0922eb9736007beee0f3a54ae9cd4abe2a624af8178a68f51eb1ba8d1bcb3R50)なのですが、これは編集画面のtagの情報をupdateするためにしてあります
![Screen Shot 2021-11-22 at 10 37 04](https://user-images.githubusercontent.com/60797707/142788642-107cd22c-41b4-4b67-b553-3a3adf3d8a5d.png)
。

2021-11-22 03:04 UTC, hakumizuki commented on packages/app/src/components/Navbar/GrowiSubNavigation.jsx
> +  const tagsUpdatedHandler = async(newTags) => {
LGTM

2021-11-22 03:05 UTC, merged