feat: Enable drawer mode
weseek/growi pull request #4670
Opened 2021-11-15 11:36 UTC by hakumizuki

Redmine(２つ): https://redmine.weseek.co.jp/issues/81539, https://redmine.weseek.co.jp/issues/81157

Drawer <-> Dock の切り替えを SWR でできるようにしました。

## コメント
- ci の lint の警告は https://redmine.weseek.co.jp/issues/81609 で修正するので一旦スルーしてください
  - `Error: src/components/Sidebar.tsx(306,17): error TS2322: Type '(event: MouseEvent) => void' is not assignable to type 'MouseEventHandler<HTMLDivElement>'.`

## 後続タスク
- DB と sync できる
  - 現在は sessionStorage のみです
- 切り替え時の見た目を正常にする

2021-11-15 12:08 UTC, hakumizuki commented on packages/app/src/stores/ui.tsx
> +  return useSWR(IS_DRAWER_MODE, calcDrawerMode, { fallback: calcDrawerMode });
fetcher のなかでは hook が使えないので cache から取ってきてます。デフォルト値は swr で取ってきたものを使っています。デフォルト値は実質 fallbackData です

2021-11-15 12:16 UTC, yuki-takei requested changes

2021-11-15 12:16 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +    const _isDeviceSmallerThanMd = cache.get(IS_DEVICE_SMALLER_THAN_MD);
cache は使わない。

[他の SWR hook に依存する実装例](https://github.com/weseek/growi/blob/dev/5.0.x/src/stores/page.tsx#L51)

2021-11-16 03:05 UTC, hakumizuki commented on packages/app/src/stores/ui.tsx
> +    const _isDeviceSmallerThanMd = cache.get(IS_DEVICE_SMALLER_THAN_MD);
swr  hook を使うようにしました

2021-11-16 09:13 UTC, merged