81405 use customizeParams for the default liimit number for pages to …
weseek/growi pull request #4677
Opened 2021-11-16 07:02 UTC by Yohei-Shiina

[https://redmine.weseek.co.jp/issues/81405](#81403)

default で50件が選択されている

![image](https://user-images.githubusercontent.com/35527421/141936840-bdeb01b2-9ff6-407d-b338-4e85442767bb.png)

2021-11-16 12:20 UTC, yuki-takei requested changes

2021-11-16 12:20 UTC, yuki-takei commented on packages/app/src/components/SearchPage.jsx
> +    }
この API は admin 向けなので叩くのは違う。

2021-11-16 12:20 UTC, yuki-takei commented on packages/app/src/components/SearchPage.jsx
> +  }
onPagingNumberChanged, searchHandler, onPagingLimitChanged と散らかってきてるので綺麗にしてください。

2021-11-18 07:13 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.jsx
> +  }
searchHandler => onSearchInvoked に変更しました

2021-11-18 10:10 UTC, merged