Feat/77525 80785 implement select all checkbox
weseek/growi pull request #4684
Opened 2021-11-17 05:39 UTC by ryohi15

## タスク
https://estoc.weseek.co.jp/redmine/issues/80785

## したこと
検索結果一覧のアイテムの CheckBox の状態によって一括選択ボタンの状態を変える

2021-11-17 10:23 UTC, TatsuyaIse requested changes
一つ命名が気になった。

2021-11-17 12:32 UTC, yuki-takei requested changes

2021-11-17 12:32 UTC, yuki-takei commented on packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> +        checked={checkboxType !== CheckboxType.NONE_CHECKED}
流れが逆。

この input をクリックしたら状態が変わる(props に依らず、このコンポーネントが ALL_CHECKED なのか NONE_CHECKED なのかを決める)
それを onClickXXX で親に通知し、List 内の全てのチェックボックスの ON/OFF を変える。

2021-11-17 12:32 UTC, yuki-takei commented on packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> +          }
onClickInvoked の名前がよくない

2021-11-17 12:32 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +        }}
onClickInvoked の名前がよくない

2021-11-17 12:32 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +        }}
ついでに言うと、click がコンポーネントに対する操作そのものを表してるのに invoked っているのか？
onRenameOperationInvoked とかならわかるけど。

2021-11-17 14:00 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +        }}
ここは、以下のタスクで対応しました。
https://github.com/weseek/growi/pull/4691/files#diff-37c67316e549a6c1ca19b4dcf9f4736c0208b5f971b91860cd9f1fd6f5d08b3aL93

2021-11-17 14:40 UTC, yuki-takei requested changes

2021-11-17 14:40 UTC, yuki-takei commented on packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> +        checked={checkboxType !== CheckboxType.NONE_CHECKED}
両方満たしてください

2021-11-17 14:42 UTC, yuki-takei requested changes

2021-11-17 14:42 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  // refs: https://estoc.weseek.co.jp/redmine/issues/81100
この URL 存在しない

2021-11-17 14:42 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  // refs: https://estoc.weseek.co.jp/redmine/issues/81100
onClickInvoked の名前を変えることをタスクに明記して

2021-11-18 09:12 UTC, yuki-takei requested changes

2021-11-18 09:12 UTC, yuki-takei commented on packages/app/src/components/SearchPage.jsx
> +    const getNextSelectAllCheckboxType = () => {
この closure、宣言する必要なさそう

2021-11-18 11:13 UTC, merged