fix: Interactions from private channels not working
weseek/growi pull request #4688
Opened 2021-11-17 09:15 UTC by stevenfukase

## タスク
https://redmine.weseek.co.jp/issues/81429

## やったこと
Private channelからのinteractionsはchannel_nameが一律で"privategroup"になっていたため、interactionsが失敗していました。
channel_nameだけでなく、channel_idでも判別できるようにしました。

2021-11-17 09:18 UTC, stevenfukase commented on packages/slack/src/utils/interaction-payload-accessor.ts
>      }
getChannelNameを使っている箇所はgetChannelに移行しましたが、private_metadataを読み取ってる箇所は、modalを今後使う可能性があるので、消さずに一旦コメントアウトしました。

2021-11-17 09:19 UTC, stevenfukase commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    // const permission = await this.relationsService.checkPermissionForInteractions(relations, actionId, callbackId, channelName);
private_metadataを読み取ってる箇所は、modalを使うinteractionsでのみ使用しますので、一旦コメントアウトしました。

2021-11-17 09:21 UTC, stevenfukase commented on packages/slack/src/interfaces/channel.ts
> +}
packages/appとpackages/slackbot-proxyの両方で使用しますので、このファイルに定義しました。

2021-11-17 11:40 UTC, yuki-takei requested changes

2021-11-17 11:40 UTC, yuki-takei commented on packages/app/src/server/util/slack-integration.ts
> +    if (Array.isArray(permission) && (permission.includes(fromChannel.name) || permission.includes(fromChannel.id))) {
これだと name が null の場合に includes が2回走る

2021-11-17 11:40 UTC, yuki-takei commented on packages/slack/src/utils/interaction-payload-accessor.ts
>      }
コメントアウトすると modal を使う実装をしたときになぜこの getChannel が動かないのかがわからなくなるので、throw Error して未対応である旨をメッセージに入れてください。

2021-11-17 11:40 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    // const permission = await this.relationsService.checkPermissionForInteractions(relations, actionId, callbackId, channelName);
一旦コメントアウトはやめよう

2021-11-18 09:21 UTC, stevenfukase commented on packages/app/src/server/util/slack-integration.ts
> +
FB対応箇所
こういった形で良かったですか？

2021-11-18 09:22 UTC, stevenfukase commented on packages/slack/src/utils/interaction-payload-accessor.ts
> +      throw new Error('PrivateMetaDatas are not implemented after removal of modal from slash commands. Use payload instead.');
FB対応箇所

2021-11-18 09:22 UTC, stevenfukase commented on packages/slackbot-proxy/src/controllers/slack.ts
> -    const permission = await this.relationsService.checkPermissionForInteractions(relations, actionId, callbackId, channelName);
FB対応箇所
コメントアウトをやめ、削除しました

2021-11-18 11:12 UTC, yuki-takei requested changes

2021-11-18 11:12 UTC, yuki-takei commented on packages/slackbot-proxy/src/controllers/slack.ts
> +    const channel: IChannel = interactionPayload.channel;
単純削除ではだめ。今まで対応していた`privateMeta?.channelName`に非対応になってしまう。(public channel でのモーダル向けの実装が単純に消えてしまう)

2021-11-18 11:12 UTC, yuki-takei commented on packages/app/src/server/util/slack-integration.ts
> +
違う。

`id || name` を一時変数に入れて、null じゃなければ includes のチェックを行う

2021-11-19 08:21 UTC, stevenfukase commented on packages/slackbot-proxy/src/controllers/slack.ts
> +
単純削除はやめ、channelNameのみが渡ってきた場合でも対応しました

2021-11-19 09:10 UTC, yuki-takei approved these changes

2021-11-19 09:10 UTC, yuki-takei commented on packages/app/src/server/util/slack-integration.ts
> +      }
この処理、ここと RelationsService.ts で 2 回と計 3 回出てくるのでユーティリティ化したい。

2021-11-19 09:10 UTC, merged