wip: 81762 repalce grid with flex
weseek/growi pull request #4689
Opened 2021-11-17 09:49 UTC by Yohei-Shiina

[#81762](https://redmine.weseek.co.jp/issues/81762)
![image](https://user-images.githubusercontent.com/35527421/142177266-e62082c4-44f4-4bc4-a5ae-06894dd5226d.png)

2021-11-17 09:51 UTC, Yohei-Shiina commented on packages/app/src/server/views/search.html
> +  <div class="" id="search-page"></div>
漏れてたのでclassは後ほど削除する

2021-11-18 09:32 UTC, yuki-takei commented
この辺の border おかしいよね
![image](https://user-images.githubusercontent.com/1638767/142389108-1e2feff8-4165-45c9-834d-73b9234f05e0.png)

2021-11-18 09:33 UTC, yuki-takei requested changes

2021-11-18 09:33 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchPageLayout.tsx
> +        <div className="w-50 flex-grow-1 page-list search-result-list pr-0" id="search-result-list">
SP レイアウトも一緒にやってください

2021-12-22 09:51 UTC, closed without merging