feat: Enable to edit empty pages
weseek/growi pull request #4694
Opened 2021-11-18 02:13 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/81693

Empty ページを編集できるようにしました。
notFound と Page.create を改修して、isEmpty: true のページが存在した場合は create の代わりに update するようにしました。

## その他の改修
- app.jsx で ContextExtractor が null のときに対応しました

2021-11-18 09:04 UTC, yuki-takei requested changes

2021-11-18 09:04 UTC, yuki-takei commented on packages/app/src/server/routes/page.js
> +      return next(); // to page.notFound
コメント書くくらいなら next に任せずこの中で `actions.notFound` に処理を委譲する方がわかりやすそう

2021-11-18 09:04 UTC, yuki-takei commented on packages/app/src/server/models/obsolete-page.js
> +    }
後続タスクでもよい

2021-11-18 09:14 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +    const path = req.pagePath || getPathFromRequest(req);
isEmpty の場合は req.pagePath を入れ込んでいるので追加しました。query に追加するのは違うかなと

2021-11-18 09:15 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +    }
確かにその方がいいと思うので isV5Compatible による比較は取り除きました

2021-11-18 09:33 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +      return next(); // to page.notFound
関数にしてリファクタしました

2021-11-18 11:23 UTC, yuki-takei requested changes

2021-11-18 11:23 UTC, yuki-takei commented on packages/app/src/server/routes/page.js
> +    const path = req.pagePath || getPathFromRequest(req);
normalize する方がよさそうなので、getPathFromRequest を改修してください。

ref: https://github.com/weseek/growi/issues/850

2021-11-19 02:37 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +    const path = req.pagePath || getPathFromRequest(req);
改修しました

2021-11-19 02:43 UTC, merged