imprv: Define item area css
weseek/growi pull request #4695
Opened 2021-11-18 03:13 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/80787

Item の大まかなエリアをつけました。icon などはまだ確定ではないです

https://user-images.githubusercontent.com/58432773/142345117-14dcce75-34c8-4426-be32-55550f74a19b.mov

2021-11-18 09:28 UTC, yuki-takei requested changes

2021-11-18 09:28 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      <div style={opacityStyle} className="grw-pagetree-item row align-items-center">
Grid Layout は適さないと思うので Flexbox で

2021-11-18 09:57 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      <div style={opacityStyle} className="grw-pagetree-item row align-items-center">
Flexbox にしました

2021-11-18 11:26 UTC, yuki-takei requested changes

2021-11-18 11:26 UTC, yuki-takei commented on packages/app/src/styles/_page-tree.scss
> +      }
- ネストを深くし過ぎないように

2021-11-18 11:26 UTC, yuki-takei commented on packages/app/src/styles/_page-tree.scss
> +        margin: auto;
`m-auto` なかったっけ

2021-11-19 02:47 UTC, hakumizuki commented on packages/app/src/styles/_page-tree.scss
> +      }
一段下げました

2021-11-19 02:47 UTC, hakumizuki commented on packages/app/src/styles/_page-tree.scss
> +        margin: auto;
取り除きました

2021-11-19 02:53 UTC, merged