Feat/77543 79026 search delete button
weseek/growi pull request #4698
Opened 2021-11-18 06:57 UTC by TatsuyaIse

### Task
- https://redmine.weseek.co.jp/issues/79026

### やっている事
- 検索結果一覧から削除操作できるようにした
- 完全削除に関しては、ページの権限設定まわりによって変わってくるかつ、権限周りの改修が改めて必要なため、 TODO を残している

2021-11-18 10:04 UTC, yuki-takei requested changes

2021-11-18 10:04 UTC, yuki-takei commented on packages/app/src/components/Page/PageManagement.jsx
> +          onDeleteCompleted={redirectToDeletedPage}
このモーダル再利用しないほうがよさそうだなあ。

検索結果画面での削除後は、APIアクセス(with SWR)で検索結果取り直してほしい

2021-11-18 10:04 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +  return <PageDeleteModal {...props}></PageDeleteModal>;
ここで自前の PageDeleteModal を作ってるんだったら、PageManagement.jsx の方の改修はいらないと思うけれど…

2021-11-22 06:40 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +  return <PageDeleteModal {...props}></PageDeleteModal>;
自前の別コンポーネントは作っていないです！  
既存の PageDeleteModal コンポーネントを、呼び出し元からページ削除完了後の処理を与えられるように改修してしています。

2021-11-22 08:30 UTC, yuki-takei requested changes

2021-11-22 08:30 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +              console.log('onClickPageDeleteBtnInvoked is invoked');
console.log は消す

2021-11-22 08:30 UTC, yuki-takei commented on packages/app/src/components/PageDeleteModal.jsx
> +        };
option いらなさそう

2021-11-22 08:30 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> +};
wrapper はいらないと思う。ts のエラーを回避するためのワークアラウンドなんだとしたら禁止。

2022-01-28 04:11 UTC, closed without merging