feat/#81076 Bookmark&PageManagement
weseek/growi pull request #4711
Opened 2021-11-19 08:19 UTC by maow89126

wip
Bookmark : done
PageManagement: wip

2021-11-24 09:51 UTC, yuki-takei requested changes

2021-11-24 09:51 UTC, yuki-takei commented on packages/app/src/stores/bookmark.ts
> +// TODO response type
この PR で解決してください

2021-11-24 09:51 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> +  const isTrashPage = path.substr(0, 7) === '/trash/';
この判定を行うユーティリティがあるはず

2021-11-24 09:51 UTC, yuki-takei commented on packages/app/src/components/Page/PageManagement.jsx
> +  const presentationHref = new URL(urljoin(window.location.origin, path, '?presentation=1')).href;
URL モジュールを使うなら urljoin は不要

2021-11-24 14:33 UTC, maow89126 commented on packages/app/src/components/Navbar/GrowiSubNavigation.jsx
> +              isAbleToDeleteCompletely={isAbleToDeleteCompletely}
ここではpageContainerから持ってきたものを渡しています。

2021-11-24 14:55 UTC, maow89126 commented on packages/app/src/components/Page/PageManagement.jsx
> +  const presentationHref = new URL(urljoin(window.location.origin, path, '?presentation=1')).href;
直しました。

2021-11-24 14:55 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> +  const isTrashPage = path.substr(0, 7) === '/trash/';
utils使用しました。

2021-11-24 14:55 UTC, maow89126 commented on packages/app/src/stores/bookmark.ts
> +// TODO response type
すいません。todoにしっぱなしで忘れてました。

type作りました。

2021-11-24 19:46 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> +          isAbleToDeleteCompletely
何故使えないのだ？
使ってもいいし、SearchPage で取得して props で入れてもいいと思う。

2021-11-25 01:37 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> +          isAbleToDeleteCompletely
pageContainerのisAbleToDeleteCompletely stateってdata-page-is-able-to-delete-completely attiributeをもとに決まると思うのですが、それってpage_contents.htmlで user.canDeleteCompletely(page.creator._id)によって決まってる理解です。
なので検索page内ではこのpage.creator._idが存在してないのでpageContainerは使えない理解でした。

>SearchPage で取得して props で入れてもいいと思う。

なのでこの案で行くことになると思いますが、一応あとで方法間違ってないか口頭で確認させて下さい。

2021-11-26 02:49 UTC, maow89126 commented on packages/app/src/components/PageDeleteModal.jsx
> +          disabled
一次対策です

2021-11-26 07:01 UTC, merged