Feat/77545 81664 display filter option
weseek/growi pull request #4719
Opened 2021-11-22 04:08 UTC by ryohi15

## タスク
https://redmine.weseek.co.jp/issues/81664

## したこと
モーダルの見た目の実装

![image](https://user-images.githubusercontent.com/61174410/142799785-7dbccd1e-7f8b-427b-9a1e-6049b2f30c69.png)

### todo 
- 「絞り込む」を押したときに検索結果にフィルターをかける
    -  at https://redmine.weseek.co.jp/issues/81845

2021-11-22 05:20 UTC, TatsuyaIse requested changes

2021-11-22 05:20 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  const switchIncludingUnderTrashPage = () => {
この命名変更のリファクタって、元の名前では進められないほどダメなので変更する必要があるよね。ってチームで話し合った結果？  
少なくとも今の PR では必要のない差分だと思っている。  
不用意な改修はコンフリクトを誘発するので、やるとしても TODO コメント残すくらいでリファクタは別でまとめてやった方がよいです。

2021-11-22 05:20 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  const closePageRenameModalHandler = () => {
リネーム・・・？ 🤔

2021-11-22 05:20 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/FilterOptionModal.tsx
> +  onClose: () => void,
`?` は要らん？

2021-11-22 05:20 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/FilterOptionModal.tsx
> +              <input
trash の方も含め checked は親から渡さなくていいんだろか？  
そもそも #81845 でやる予定であえて入れていないのであれば大丈夫だが、  
そうでないのであれば今のうちにその実装を入れておいた方がいい

2021-11-22 05:20 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/FilterOptionModal.tsx
> +          className="btn btn-secondary"
空の onClick (できればモーダルを閉じるところまで) は実装しておこう。

2021-11-22 05:20 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +        switchIncludingUnderTrashPage={this.switchIncludingUnderTrashPage}
SearchControl にも書いたけれど、命名変更のリファクタはあとでまとめてやる

2021-11-22 05:20 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage.jsx
> +    this.setState({ isExcludeUnderUserPage: !this.state.isExcludeUnderUserPage });
include と exclude 混ぜたらわかりづらくなるので統一したほうがいいんじゃないかな、、、

2021-11-22 05:32 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  const switchIncludingUnderTrashPage = () => {
一旦は、setState するところのメソッドの命名は変更するまでとします。

2021-11-24 01:47 UTC, ryohi15 commented on packages/app/src/components/SearchPage/FilterOptionModal.tsx
> +              <input
今回はあえて入れなかったです。

2021-11-24 03:05 UTC, ryohi15 commented on packages/app/src/components/SearchPage/FilterOptionModal.tsx
> +          className="btn btn-secondary"
モーダル閉じるのは `toggle={onClose}` で実装されてますね。

2021-11-26 10:07 UTC, TatsuyaIse approved these changes
2段階目へどうぞ

2021-11-26 12:11 UTC, yuki-takei requested changes

2021-11-26 12:11 UTC, yuki-takei commented on packages/app/src/components/SearchPage/FilterOptionModal.tsx
> +  switchExcludingUnderTrashPage?: () => void,
[/Tips/JavaScript/命名規則](https://tips.weseek.co.jp/60ae84d41091010049bed55d)

2021-11-26 12:11 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  switchExcludingUnderTrashPage?: () => void,
[/Tips/JavaScript/命名規則](https://tips.weseek.co.jp/60ae84d41091010049bed55d)

2021-11-26 12:11 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +                onClick={() => switchExcludingUnderUserPage()}
`onClick={switchExcludingUnderUserPage}` でよいのでは？

2021-11-29 03:09 UTC, ryohi15 commented on packages/app/src/components/SearchPage/FilterOptionModal.tsx
> +  onSwitchExcludingUnderUserPageInvoked?: () => void,
命名のチェックお願いします。@yohei

2021-11-29 03:09 UTC, ryohi15 commented on packages/app/src/components/SearchPage/FilterOptionModal.tsx
> +  onSwitchExcludingUnderTrashPageInvoked?: () => void,
命名のチェックお願いします。@yohei

2021-11-29 03:10 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  onSwitchExcludingUnderUserPageInvoked?: () => void,
命名のチェックお願いします。@yohei

2021-11-29 03:10 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  onSwitchExcludingUnderTrashPageInvoked?: () => void,
命名のチェックお願いします。@yohei

2021-11-29 03:10 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  const switchExcludingUnderUserPageHandler = () => {
命名のチェックお願いします。@yohei

2021-11-29 03:10 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  const switchExcludingUnderTrashPageHandler = () => {
命名のチェックお願いします。@yohei

2021-11-29 06:31 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.jsx
> +      excludeUnderTrashPage: true,
元のものから変える必要もないかなと思った

2021-11-29 06:31 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.jsx
> +    this.switchExcludingUnderTrashPageHandler = this.switchExcludingUnderTrashPageHandler.bind(this);
state 名側を直している前提で、switchExclude○○Handler かな

2021-11-29 06:31 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.jsx
> +        onSwitchExcludingUnderTrashPageInvoked={this.switchExcludingUnderTrashPageHandler}
switch と invoked は共存してるとおかしい気がする

invoked が具体的になったのが onSwitch だよね

2021-11-29 06:31 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/FilterOptionModal.tsx
> +  onSwitchExcludingUnderUserPageInvoked?: () => void,
SearchPage側に倣って修正を

2021-11-29 06:31 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/FilterOptionModal.tsx
> +  onSwitchExcludingUnderTrashPageInvoked?: () => void,
SearchPage側に倣って修正を

2021-11-29 06:31 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  onSwitchExcludingUnderUserPageInvoked?: () => void,
SearchPage側に倣って修正を

2021-11-29 06:31 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  onSwitchExcludingUnderTrashPageInvoked?: () => void,
SearchPage側に倣って修正を

2021-11-29 06:31 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  const switchExcludingUnderUserPageHandler = () => {
SearchPage側に倣って修正を

2021-11-29 06:31 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  const switchExcludingUnderTrashPageHandler = () => {
SearchPage側に倣って修正を

2021-11-29 07:04 UTC, ryohi15 commented on packages/app/resource/locales/en_US/translation.json
> +    "narrow_donw" : "Narrow down"
mos さんと相談し、絞り込む → 再検索 というワードに切り換えることにしました

2021-11-29 07:04 UTC, ryohi15 commented on packages/app/resource/locales/ja_JP/translation.json
> +    "narrow_donw" : "絞り込む"
mos さんと相談し、絞り込む → 再検索 というワードに切り換えることにしました

2021-11-29 07:04 UTC, ryohi15 commented on packages/app/resource/locales/zh_CN/translation.json
> +    "narrow_donw" : "细化您的搜索"
mos さんと相談し、絞り込む → 再検索 というワードに切り換えることにしました

2021-11-29 11:00 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.jsx
> +        onSwitchExcludingUnderTrashPageInvoked={this.switchExcludingUnderTrashPageHandler}
これがなおってない

on○○Switched にするのか on○○Invoked にするのか。

[/Tips/JavaScript/命名規則](https://tips.weseek.co.jp/60ae84d41091010049bed55d)を見直してください

2021-11-29 11:02 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.jsx
> +        onSwitchExcludingTrashPagesInvoked={this.switchExcludingTrashPagesHandler}
Excluding は Exclude でよさそう

2021-11-29 11:03 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  onSwitchExcludingTrashPagesInvoked?: () => void,
Excluding は Exclude でよさそう

2021-11-29 11:03 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  const switchExcludingUserPagesHandler = () => {
Excluding は Exclude でよさそう

2021-11-29 11:03 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  const switchExcludingTrashPagesHandler = () => {
Excluding は Exclude でよさそう

2021-11-29 11:05 UTC, Yohei-Shiina commented
これも忘れずに
https://github.com/weseek/growi/pull/4719#discussion_r758252084

2021-11-30 03:45 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.jsx
> +        onExcludeTrashPagesSwitch={this.switchExcludeTrashPagesHandler}
Switch"ed" が正しいのでは

よく読みましょう[命名規則](https://tips.weseek.co.jp/60ae84d41091010049bed55d#修正案)

2021-11-30 04:34 UTC, merged