Feat/77524 81110 show liker icon
weseek/growi pull request #4723
Opened 2021-11-22 06:25 UTC by Yohei-Shiina

[#81110](https://redmine.weseek.co.jp/issues/81110)

![likers](https://user-images.githubusercontent.com/35527421/142810442-6b031beb-2842-46e2-9dbd-a278f8d1d115.gif)

やったこと
- 表示されなかった like したユーザの画像表示（メイン）
- LikeButton.jsx の ts化
- バケツリレーしていた値のいくつかを、それらが必要コンポーネントでSWRをつかって取得するように変更

2021-11-22 08:46 UTC, yuki-takei requested changes

2021-11-22 08:46 UTC, yuki-takei commented on packages/app/src/components/LikeButtons.tsx
> +// task : https://estoc.weseek.co.jp/redmine/issues/81110
81110 ってこの PR の対象タスクだと思うんだけど、このコメントはなんだ？

2021-11-22 08:46 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +      const res: any = await props.appContainer.apiGet('/users.list', { user_ids: [...pageInfo.likerIds].join(',') });
apiGe では update できないのでは？

2021-11-22 08:46 UTC, yuki-takei commented on packages/app/src/components/LikeButtons.tsx
> +            {props.likers.length ? <UserPictureList users={props.likers} /> : t('No users have liked this yet.')}
useSWRPageInfo の結果とこの props.likers に相関がないのは正しい実装なのか？

2021-11-22 08:50 UTC, yuki-takei requested changes

2021-11-22 08:50 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  }, [pageInfo]);
https://github.com/weseek/growi/pull/4723/files#r754053130 のコメントと併せて違和感。
データの流れを整頓して。

2021-11-24 08:07 UTC, Yohei-Shiina commented on packages/app/src/components/LikeButtons.tsx
> +            {props.likers.length ? <UserPictureList users={props.likers} /> : t('No users have liked this yet.')}
このコンポーネントではSWR使はないように変更しました

2021-11-24 08:07 UTC, Yohei-Shiina commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  }, [pageInfo]);
このコンポーネントのSWRで取得した値をバケツリレーでLikeButtonsまで渡すようにしました

2021-11-24 09:46 UTC, yuki-takei requested changes

2021-11-24 09:46 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  }, [pageInfo]);
`'/users.list'` を叩くのも SWR 化してください。

2021-11-25 17:56 UTC, Yohei-Shiina commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +import { useSWRxLikerList } from '../../stores/user';
SWR

2021-11-25 17:56 UTC, Yohei-Shiina commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  }, [pageInfo]);
SWR mutate に変更しました

2021-11-25 17:56 UTC, Yohei-Shiina commented on packages/app/src/stores/user.tsx
> +const userFetcher = (endpoint:string, userIds:string) => {
汎用的になるように切り分け

2021-11-26 06:55 UTC, yuki-takei requested changes

2021-11-26 06:55 UTC, yuki-takei commented on packages/app/src/stores/user.tsx
> +const userFetcher = (endpoint:string, userIds:string) => {
これは引数がこの形してる key にしか使えないから微妙。

2021-11-26 06:55 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  }, [pageInfo]);
この useEffect ないと revalidate されないかな？なくても行けるんじゃないかと思ってる。

2021-11-26 10:45 UTC, Yohei-Shiina commented on packages/app/src/stores/user.tsx
> +  });
fetcher は外に切らず一つにまとめました

2021-11-26 12:20 UTC, merged