feat: Implement named query model
weseek/growi pull request #4726
Opened 2021-11-22 09:49 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/81970

NamedQuery モデルを実装しました

2021-11-23 10:32 UTC, yuki-takei requested changes

2021-11-23 10:32 UTC, yuki-takei commented on packages/app/src/server/models/named-query.ts
> +  creator: { type: ObjectId, ref: 'User', index: true },
system によるプリセットの NamedQuery の場合はここを null にするか、あるいはそれとわかる boolean が必要ではないかな。

2021-11-23 10:32 UTC, yuki-takei commented on packages/app/src/server/models/named-query.ts
> +  resolverName: { type: String, index: true },
enum 化しよう。

2021-11-24 03:35 UTC, hakumizuki commented on packages/app/src/server/models/named-query.ts
> +  resolverName: { type: String, index: true },
enum 化しました

2021-11-24 03:35 UTC, hakumizuki commented on packages/app/src/server/models/named-query.ts
> +  creator: { type: ObjectId, ref: 'User', index: true },
interface, スキーマ共に null を入れられるようにしました

2021-11-24 07:46 UTC, merged