imprv: Create interfaces for search query feature
weseek/growi pull request #4730
Opened 2021-11-24 09:19 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/81978

新サーチに必要な interface を作成しました

CI は lint 以外無視で大丈夫です

## その他
- SearchService に SearchQueryParser と SearchResolver を implements させました
- elasticsearch.js, searchbox.js を .ts にして SearchDelegator インターフェースを implements しました
- PageModel interface に必要なものを追加しました

2021-11-24 09:48 UTC, hakumizuki commented on packages/app/src/server/interfaces/search.ts
> +export type Result<T> = {
PaginateResult でなくていいと思ったので、offset と limit は除外して Result にしました

2021-11-24 11:59 UTC, yuki-takei requested changes

2021-11-24 11:59 UTC, yuki-takei commented on packages/app/src/server/interfaces/search.ts
> +export type Result<T> = {
内容が `data: T` だけだったら type 定義する必要もないような…

2021-11-24 11:59 UTC, yuki-takei commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +    const notTags: string[] = [];
この辺の parse 結果の概念は elasticsearch に依らず全文検索の結果。
つまり今後作られる MongoDB での全文検索風の処理でも使う。

2021-11-24 11:59 UTC, yuki-takei commented on packages/app/src/server/service/search-delegator/searchbox.ts
> +class SearchboxDelegator extends ElasticsearchDelegator implements SearchDelegator {
Searchbox の実装は消してもいい(Heroku にはもう対応しなくなったので)

2021-11-25 03:28 UTC, hakumizuki commented on packages/app/src/server/service/search-delegator/searchbox.ts
> +class SearchboxDelegator extends ElasticsearchDelegator implements SearchDelegator {
searchbox に関する処理は削除しました

2021-11-25 03:47 UTC, hakumizuki commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +    const notTags: string[] = [];
ParsedQuery に terms を追加して delegator 共通のものにするようにしました
```typescript
type QueryTerms = {
  match: string[],
  not_match: string[],
  phrase: string[],
  not_phrase: string[],
  prefix: string[],
  not_prefix: string[],
  tag: string[],
  not_tag: string[],
}

type ParsedQuery = {
  queryString: string // original query string in request
  terms: QueryTerms // terms found in query string
  nqNames: string[] // possible NamedQuery names found in query string
}
```

2021-11-25 03:51 UTC, hakumizuki commented
>内容が data: T だけだったら type 定義する必要もないような…

type 定義せずに `Result<T>` 自体を `T` にするみたいなことしてもアリではありますが、`{ data: T }` という形で統一感出せると思ったので残しました

2021-11-25 07:59 UTC, hakumizuki commented on packages/app/src/server/interfaces/search.ts
> +export interface SearchResolver{
もともと Resolver は delegator を決定するためだけのものだったのですが、aliasOf で queryString を concat することや delegatorName を持つ NamedQuery が存在するかどうか確かめるなどの処理と同じスコープ内でやりたいので、返り値を `[SearchDelegator, SearchableData]` に変更しました

2021-11-25 07:59 UTC, hakumizuki commented on packages/app/src/server/interfaces/search.ts
> +  resolve(parsedQuery: ParsedQuery): Promise<[SearchDelegator, SearchableData]>
もともと Resolver は delegator を決定するためだけのものだったのですが、aliasOf で queryString を concat することや delegatorName を持つ NamedQuery が存在するかどうか確かめるなどの処理と同じスコープ内でやりたいので、返り値を [SearchDelegator, SearchableData] に変更しました

2021-11-25 08:00 UTC, hakumizuki commented on packages/app/src/server/interfaces/search.ts
> +}
queryString と terms 両方が必要な delegator が存在するので SearchableData を定義しました

2021-11-25 08:05 UTC, hakumizuki commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +    const notTags: string[] = [];
このパースの処理は resolve の中に入る予定です。

補足しておくと、今回の処理の中でパースは「queryString から [nq:named_query] を探すためだけのパース」と「NamedQuery の aliasOf が展開し終わった後の queryString => QueryTerms へのパース」の２つができる予定です。resolve の前に前者のパース、resolve 内で後者のパースをします

2021-11-25 10:15 UTC, merged