Feat/77525 80678 delete selected pages
weseek/growi pull request #4735
Opened 2021-11-25 08:14 UTC by Yohei-Shiina

### タスク
[80678](https://redmine.weseek.co.jp/issues/80678)

削除・完全削除、共に動作確認済み
![image](https://user-images.githubusercontent.com/35527421/143404101-30401a49-174a-4526-8d32-052a38ecfe47.png)

2021-11-25 11:40 UTC, yuki-takei requested changes

2021-11-25 11:40 UTC, yuki-takei commented on packages/app/src/components/SearchPage.jsx
> +  }
削除処理は現時点では未実装にする

## やらないこと(後続ストーリーを作る)
- Promise.all がパフォーマンス的によくない
- bulk remove したい
    - とはいえ API がないので、それとセットで実装する必要がある

## やること
- 削除処理後、location.reload() はしないで検索結果の再取得を行う

2021-11-26 07:41 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/DeletePageListModal.jsx
> +  onChangeDeleteCompletely: PropTypes.func.isRequired, // for delete completely check event handling
命名変更のみ

2021-11-26 07:41 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> +  onClickDeleteAllButton?: () => void,
命名変更のみ

2021-11-26 07:41 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> +    onClickDeleteAllButton, onClickSelectAllCheckbox, selectAllCheckboxType,
命名変更のみ

2021-11-26 07:41 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +        <button className="dropdown-item" type="button" onClick={() => toastr.warning(t('search_result.currently_not_implemented'))}>
トースター表示

2021-11-26 07:41 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.jsx
> +      // **************************************************************************************************
現在の Promise.all 削除の部分をコメントアウト

2021-11-26 07:41 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.jsx
> +      this.search({ keyword: this.state.searchedKeyword });
検索結果の再取得

2021-11-26 07:41 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.jsx
> +      this.onCloseDeleteConfirmModal();
モーダルを閉じる

2021-11-26 11:47 UTC, merged