feat: display conflict alert on any page mode
weseek/growi pull request #4738
Opened 2021-11-25 10:11 UTC by yuto-oweseek

## タスク

https://redmine.weseek.co.jp/issues/81268

## 行ったこと

- edit 画面 view 画面でも、 pageStatusAlert.jsx で socket.io 経由で、コンフリクトを通知できるようにしました。
- サーバーサイドからの response を使ってコンフリクトした revisions をフロントに渡す方法を廃止しました。

## 画像

![load latest in view](https://user-images.githubusercontent.com/83065937/143421951-1b17c5c1-7fdc-4f4d-8a60-b6bbc3da47fb.PNG)

![resolve conflict in edit](https://user-images.githubusercontent.com/83065937/143421973-8b09c908-a0a9-43b1-8fd6-a0eeec8efa76.PNG)

## 後続タスク

- コンフリクト解消モーダルの見た目のブラッシュアップ

2021-11-25 11:20 UTC, yuki-takei requested changes

2021-11-25 11:20 UTC, yuki-takei commented on packages/app/src/components/PageStatusAlert.jsx
> +      revisionsOnConflict: {
このモデル必要ないのでは？

2021-11-25 11:20 UTC, yuki-takei commented on packages/app/src/components/PageStatusAlert.jsx
> +          createdAt: format(new Date(pageContainer.state.remoteRevisionUpdateAt), 'yyyy/MM/dd HH:mm:ss'),
date のフォーマットは、表示する側のコンポーネントで行う

2021-11-25 11:20 UTC, yuki-takei commented on packages/app/src/server/models/vo/s2c-message.js
> +      this.lastUpdateUserImagePath = user.imageUrlCached;
これは user を remoteLastUpdateUser として管理して、最終的には UserPicture に入れて使う

2021-11-26 06:43 UTC, yuto-oweseek commented on packages/app/src/components/PageStatusAlert.jsx
> +      revisionsOnConflict: {
ConflictDiffModal.tsx 側へ移動しました。

2021-11-26 06:43 UTC, yuto-oweseek commented on packages/app/src/components/PageStatusAlert.jsx
> +          createdAt: format(new Date(pageContainer.state.remoteRevisionUpdateAt), 'yyyy/MM/dd HH:mm:ss'),
ConflictDiffModal.tsx 側へ移動しました。

2021-11-26 08:34 UTC, yuto-oweseek commented on packages/app/src/server/models/vo/s2c-message.js
> +      this.lastUpdateUserImagePath = user.imageUrlCached;
UserPicture を使用しました。

2021-11-26 09:30 UTC, yuto-oweseek commented on packages/app/src/components/PageEditor/ConflictDiffModal.tsx
> +        <div className="row mx-2">
Codemirror 周辺の箇所で差分が多く出ていますが、以下の2つを変更しているだけです。

-  UserPicture コンポーネントを使用した箇所
- revision に対する ~~.user.usernam と、 format(parseISO(request.createdAt), 'yyyy/MM/dd HH:mm:ss')} 


(Codemirror などのフロント改修作業は行っていません)

2021-11-26 12:05 UTC, yuki-takei requested changes

2021-11-26 12:05 UTC, yuki-takei commented on packages/app/src/components/PageEditor/ConflictDiffModal.tsx
> +  const markdownOnEdit: string = pageEditor.getMarkdown();
この2行ここに入れたくない…
なんとかならないものか。

2021-11-29 05:58 UTC, yuto-oweseek commented on packages/app/src/components/PageEditor/ConflictDiffModal.tsx
> +  const markdownOnEdit: string = pageEditor.getMarkdown();
Editor.jsx 側に render (update) が走った時に、isConflictDiffModalOpen が true だった場合、 markdown を取得する方法に変更しました。

2021-11-29 11:49 UTC, merged