[After #4744] feat: Impl custom delegator and initialization
weseek/growi pull request #4749
Opened 2021-11-26 08:00 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/82098

## 実装したところ
- Private legacy pages 用 delegator
- SearchService の delegator の初期化処理
- SearchService のテストをリファクタ & 追加

2021-11-28 19:25 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +
これ今更作ったのですが、そもそもページツリー表示用にページを取得するときにはこれをクエリにつけるべきなので後続でつけます

2021-11-28 19:28 UTC, hakumizuki commented on packages/app/src/server/service/search-delegator/private-legacy-pages.ts
> +      .exec();
マイグレーション処理で万が一抜け漏れしてても救済できるようにここで public なページも検索の対象にしました

2021-11-29 09:21 UTC, yuki-takei requested changes

2021-11-29 09:21 UTC, yuki-takei commented on packages/app/src/server/service/search-delegator/private-legacy-pages.ts
> +    }
user, userGroups 両方が null の場合このメソッドは動作してはいけないと思うので、安全のため throw error しましょう。(そのような状況は route 側で排除されるべきだとは思うが)

2021-11-29 10:14 UTC, hakumizuki commented on packages/app/src/server/models/index.js
> +  NamedQuery,
確かにそうなのでそうしました

2021-11-29 10:21 UTC, hakumizuki commented on packages/app/src/server/service/search-delegator/private-legacy-pages.ts
> +    }
しました

2021-11-29 12:00 UTC, merged