Feat: add pagetree item contol
weseek/growi pull request #4751
Opened 2021-11-28 14:36 UTC by takayuki-t

## task
https://redmine.weseek.co.jp/issues/81436

## イメージ
![pagetree-ctrl](https://user-images.githubusercontent.com/52646333/143772358-b09690d8-fee8-48d8-bc04-a0d08af0f23c.gif)

## 補足

- +ボタンとメニューアイコン、バッジを実装
- 各ボタンやバッジはハリボテ

2021-11-28 20:05 UTC, yuki-takei requested changes

2021-11-28 20:05 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +        <i className="fa fa-ellipsis-v text-muted"></i>
アイコンは [simple-line-icoms](https://thesabbir.github.io/simple-line-icons/) が優先順一位。
テイストに合うものがなければデザイナーに相談を。

2021-11-28 20:05 UTC, yuki-takei commented on packages/app/src/styles/_page-tree.scss
> +        display: none;
`d-none` をデフォルトで付けておいていいと思う。

2021-11-28 20:05 UTC, yuki-takei commented on packages/app/src/styles/_page-tree.scss
> +    a {
クラスで指定してください。

2021-12-01 15:58 UTC, takayuki-t commented on packages/app/src/styles/_page-tree.scss
> +        display: none;
対応しました

2021-12-01 15:58 UTC, takayuki-t commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +        <i className="fa fa-ellipsis-v text-muted"></i>
対応しました

2021-12-01 15:58 UTC, takayuki-t commented on packages/app/src/styles/_page-tree.scss
> +    a {
対応しました。

2021-12-01 16:08 UTC, merged