Feat/79579-commonize-editor-component
weseek/growi pull request #4764
Opened 2021-11-30 03:00 UTC by stevenfukase

2021-12-01 06:41 UTC, stevenfukase commented on packages/app/src/components/PageEditor/ConflictDiffModal.tsx
> +                <p className="my-0">updated by {request.user?.username}</p>
userがない場合Errorが起きるので応急処置を行いましたがyuto-oが対応中です。

2021-12-01 06:42 UTC, stevenfukase commented on packages/app/src/components/UncontrolledCodeMirror.tsx
> +));
公式のWithUnstatedContainersとやってることは一緒ですがforwardRefに型を入れないとTSのエラーが出るのでこういった形で対応しました。

2021-12-01 06:43 UTC, stevenfukase commented on packages/app/src/components/UncontrolledCodeMirror.tsx
> +        }}
もしこれで足りないようでしたら追加するものをご教示いただきたいです。

2021-12-01 06:47 UTC, stevenfukase commented on packages/app/src/components/PageEditor/AbstractEditor.tsx
> +export default class AbstractEditor<T extends AbstractEditorProps> extends React.Component<T, Record<string, unknown>> {
Genericsを使用したかったのでTS化しました。

2021-12-01 09:49 UTC, yuki-takei requested changes

2021-12-01 09:49 UTC, yuki-takei commented on packages/app/src/components/PageEditor/AbstractEditor.tsx
> +  onPasteFiles?: (event: Event) => void;
他の props (onScrollCursorIntoView とか)も optional で追加しないとだめじゃない？Editor.jsx がそれらを受け取って CodeMirrorEditor や TextAreaEditor にも流すので。

2021-12-02 03:28 UTC, stevenfukase commented on packages/app/src/components/PageEditor/AbstractEditor.tsx
> +  onPasteFiles?: (event: Event) => void;
UncontrolledCodeMirrorでICodeMirrorをExtendsしましたが、こちらでExtendsするようにし、ICodeMirrorにないものをこちらにOptionalで追加しました。

2021-12-02 03:34 UTC, merged