Feat/80324 82319 hide growi navbar in search page
weseek/growi pull request #4767
Opened 2021-11-30 08:32 UTC by maow89126

# タスク内容
PR: https://redmine.weseek.co.jp/issues/82319
search pageの時はsubnavwoを表示しないようにしました。

Task: https://redmine.weseek.co.jp/issues/82319

2021-11-30 08:47 UTC, maow89126 commented on packages/app/src/server/views/layout/search-layout.html
> +<!DOCTYPE html>
これはlayout.htmlのgrw-subnavbar内verです。
subnavのfooterの方もなくしてます。

2021-11-30 08:47 UTC, maow89126 commented on packages/app/src/styles/theme/_apply-colors.scss
> +  border-top: 3.3333px solid;
subnavbarについてたborderのサイズを参考。

2021-12-02 12:00 UTC, yuki-takei requested changes

2021-12-02 12:00 UTC, yuki-takei commented on packages/app/src/server/views/layout/search-layout.html
> +<!DOCTYPE html>
layout ファイル追加は NG

2021-12-09 10:56 UTC, closed without merging