Feat/77544 82628 fix es sort
weseek/growi pull request #4773
Opened 2021-12-01 09:24 UTC by TatsuyaIse

https://redmine.weseek.co.jp/issues/82628

2021-12-01 10:05 UTC, yuki-takei requested changes

2021-12-01 10:05 UTC, yuki-takei commented on packages/app/src/server/service/search-delegator/elasticsearch.js
> +  createSearchQuery(sort, order, option) {
createSearchQuerySortedByScore を消して、これをソート対応にしてください。
sort, order は enum (or union) を用意する。

2021-12-01 10:05 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  order: string,
enum or union にする

2021-12-02 09:40 UTC, TatsuyaIse commented on packages/app/src/utils/search-axis-utils.ts
> +};
util 配下に用意してみました。

2021-12-02 13:50 UTC, yuki-takei requested changes

2021-12-02 13:50 UTC, yuki-takei commented on packages/app/src/utils/search-axis-utils.ts
> +};
src/interfaces/search 下にしてほしい

2021-12-02 13:50 UTC, yuki-takei commented on packages/app/src/utils/search-axis-utils.ts
> +  updatedAt: 'updated_at',
これちょっと違うんだよな。
score キーの値が仮に「hoge」でも問題なく動くようにしてほしい。つまり、SORT_AXIS_CONSTS から本当に指定しないといけない `_score` とか `created_at` っていう文字列を解決するのは、search に関するサービスの領分。

2021-12-02 13:50 UTC, yuki-takei commented on packages/app/src/utils/search-axis-utils.ts
> +type SORT_AXIS = typeof SORT_AXIS_CONSTS[keyof typeof SORT_AXIS_CONSTS];
この行に export を付けてしまえばいい

2021-12-02 13:50 UTC, yuki-takei commented on packages/app/src/utils/search-axis-utils.ts
> +type SORT_AXIS = typeof SORT_AXIS_CONSTS[keyof typeof SORT_AXIS_CONSTS];
https://weseek.co.jp/tech/?p=1609&preview=1&_ppp=a0f93391c1
の最後のテンプレート通りにするのが楽。

2021-12-02 13:50 UTC, yuki-takei commented on packages/app/src/server/service/search-delegator/elasticsearch.js
> +        sort: [{ [sort]: { order } }],
enum (union) の値をそのまま使うのは NG。
SORT_AXIS_CONSTS から本当に指定しないといけない _score とか created_at っていう文字列を解決するのは、search に関するサービスの領分。

2021-12-02 13:50 UTC, yuki-takei commented on packages/app/src/utils/search-axis-utils.ts
> +const SORT_AXIS_CONSTS = {
`const SORT_AXIS = {` でよい

2021-12-02 13:52 UTC, yuki-takei requested changes

2021-12-02 13:52 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  };
ここもなんか違う。dropdown はただただ enum (union) だけを見て挙動を変えればいい。

2021-12-08 02:08 UTC, TatsuyaIse commented
ドロップダウンの実装もこの PR 上でしました。
![image](https://user-images.githubusercontent.com/8895367/145135638-c33c014d-ab49-40f5-b493-39285e1d9f35.png)

2021-12-08 02:10 UTC, TatsuyaIse commented
操作時の挙動はこんな感じです。
![growi-search-sort-change](https://user-images.githubusercontent.com/8895367/145135961-e4129f36-d73b-49c2-aa9e-70af782f1acb.gif)

2021-12-08 11:54 UTC, merged