Imprv/82502 update status when move to notification list page
weseek/growi pull request #4776
Opened 2021-12-01 15:02 UTC by kaoritokashiki

2021-12-01 17:29 UTC, yuki-takei requested changes

2021-12-01 17:29 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
>        logger.error(err);
toastr 表示させよう。

2021-12-01 17:29 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
> +      mutateInAppNotificationStatusData();
revalidate 前に updateNotificationStatus の応答は待ったほうがよさそうなので await して。

2021-12-01 17:29 UTC, yuki-takei commented on packages/app/src/stores/in-app-notification.ts
> +  (): SWRResponse<{ count: number }, Error> => {
response の型は object ではなく単に number でよい

`<number, Error>(): SWRResponse<number, Error> => {`

2021-12-02 06:05 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
>        logger.error(err);
`toastError`のみ追加しました。

2021-12-02 06:20 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
> +      mutateInAppNotificationStatusData();
確かに...修正しました。ありがとうございます。

2021-12-02 06:44 UTC, kaoritokashiki commented on packages/app/src/stores/in-app-notification.ts
> +  (): SWRResponse<{ count: number }, Error> => {
`useSWRxInAppNotificationStatus`は、`response.data.count`を返すようにしました。

2021-12-02 06:46 UTC, kaoritokashiki commented on packages/app/src/stores/in-app-notification.ts
> +};
`count` を返すように修正しました。

2021-12-02 06:46 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
> +  const { data: inAppNotificationUnreadStatusCount, mutate: mutateInAppNotificationUnreadStatusCount } = useSWRxInAppNotificationStatus();
dataの名前を `inAppNotificationUnreadStatusCount`にしています。

2021-12-02 12:24 UTC, merged