Feat/82389-82533 title with highlighted keyword
weseek/growi pull request #4779
Opened 2021-12-02 00:22 UTC by maow89126

やったこと：
タイトルにもきーわーどにヒットした場合ハイライトを追加しました。
Task : https://redmine.weseek.co.jp/issues/82533

<img width="1440" alt="Screen Shot 2021-12-02 at 9 15 03" src="https://user-images.githubusercontent.com/60797707/144335248-7b504474-9792-4016-a361-899154790a28.png">

2021-12-02 00:25 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  const isPathIncludedHtml = pageMeta.elasticSearchResult.highlightedPath !== '';
elasticSearchResultのdata見たらhighlightedPathが空のときは""で帰ってきてたので !== ’’に変更しました。

{"bookmarkCount":0,"elasticSearchResult":{"snippet":"## <em class=\"highlighted-keyword\">Test</em>\n\nTT","highlightedPath":""}}

2021-12-02 02:31 UTC, ryohi15 requested changes

2021-12-02 02:31 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  let pageTitle = '';
let を使わないように実装してみて。

2021-12-02 05:17 UTC, ryohi15 requested changes

2021-12-02 05:17 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +    ? new DevidedPagePath(pageMeta.elasticSearchResult.highlightedPath, false, true).latter : dPagePath.latter;
ごめん。最初のレビューの時点で気づければよかったんだけど、サーバー側で処理してパスを渡してあげたほうがいいんじゃないかな？
フロントでやる必要のない処理(サーバー側でもできる処理)はなるだけサーバー側にしてもらったほうがいいから。

2021-12-03 00:19 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  let pageTitle = '';
done

2021-12-03 00:24 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +    ? new DevidedPagePath(pageMeta.elasticSearchResult.highlightedPath, false, true).latter : dPagePath.latter;
対応しました。
が、、elasticSearchResult.highligtedPath（命名シンプルにpath）に
1. matchした場合はhighlightedPath。
2. matchしていない場合はpageのpathを入れておく。

2021-12-03 01:42 UTC, ryohi15 requested changes

2021-12-03 01:42 UTC, ryohi15 commented on packages/app/src/server/service/search.js
> +      // as for path, if no keyword in it , simply page's path
コメントの位置って 169 行目の上のほうがいいんじゃないかな？

2021-12-03 01:42 UTC, ryohi15 commented on packages/app/src/server/service/search.js
> +        path: filterXss.process(pathMatch),
`displayPath` とかどうだろうか？

2021-12-03 01:44 UTC, ryohi15 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +    ? new DevidedPagePath(pageMeta.elasticSearchResult.highlightedPath, false, true).latter : dPagePath.latter;
そうだな、、もうハイライトされてるされてないは気にせず表示用のパスっていう命名で `displayPath` とかどうだろうか？

2021-12-03 02:24 UTC, maow89126 commented on packages/app/src/server/service/search.js
> +      // as for path, if no keyword in it , simply page's path
確かにです。

2021-12-03 02:24 UTC, maow89126 commented on packages/app/src/server/service/search.js
> +        path: filterXss.process(pathMatch),
その案いただきます。

2021-12-03 12:10 UTC, yuki-takei requested changes

2021-12-03 12:10 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  const isPathIncludedHtml = displayPath.includes('<em class="highlighted-keyword">');
isPathIncludedHtml って、elasticSearchResult から判断できない？もしくはできるようにならない？

どうしても無理なら文字列に対して includes でチェックになるけど、
それにしても includes で判定するのは `<em ` だけでいいと思う。クラス名まで入れると柔軟性がない。

2021-12-03 12:10 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +                <span className="mx-2" dangerouslySetInnerHTML={{ __html: pageTitle }}></span>
PagePathLabel 使えない？

2021-12-06 06:02 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  const isPathIncludedHtml = displayPath.includes('<em class="highlighted-keyword">');
serive/search.jsでformatResult methodで今やってることと全くおなじ方法で判定してisPathIncludedHhml: boolean をesResultに追加するくらいしか思い付いていないです。
とりあえずkeyword includeの部分は`<em`のみにしました。

2021-12-06 06:03 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +                <span className="mx-2" dangerouslySetInnerHTML={{ __html: pageTitle }}></span>
使えました。

2021-12-07 06:37 UTC, yuki-takei requested changes

2021-12-07 06:37 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  const isPathIncludedHtml = displayPath.includes('<em');
この判定がここに入っているのは責務を超越している

2021-12-08 03:57 UTC, maow89126 commented on packages/app/src/server/service/search.js
> +      const pathMatch = 'path.en' in highlightData || 'path.ja' in highlightData
ここは
```
const snippet = highlightData['body.en'][0] || highlightData['body.ja'][0] || '';
```

でもいいのではと思いました。
chromeのconsoleで試すと問題なく値入るのですが、
ここで試すとtoastorで`type error can not read 0 of undefined `が出ます。

なのでこういう書き方にしました。

2021-12-08 11:50 UTC, yuki-takei requested changes

2021-12-08 11:50 UTC, yuki-takei commented on packages/app/src/server/service/search.js
> +      const pathMatch = 'path.en' in highlightData || 'path.ja' in highlightData
169～171行目までが読みにくい。工夫して。

2021-12-08 11:57 UTC, yuki-takei commented on packages/app/src/server/service/search.js
> +      const pathMatch = 'path.en' in highlightData || 'path.ja' in highlightData
悲報: もうこのファイル ts になってるらしい…

2021-12-09 10:03 UTC, closed without merging