feat: Pt item open create page modal
weseek/growi pull request #4780
Opened 2021-12-02 01:41 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/82548

+ ボタンからページ作成モーダルが開くように実装しました
もともと window.location.pathname などからデフォルトのパスを計算していましたが、ui swr 化しました

## 外部仕様
A. 画面右上の new ボタンからモーダルを開くと、useCurrentPagePath の値になる
B. ページツリーのアイテムの + ボタンから開くと、アイテムが持つ pagepath の値になる

## 内部仕様
A. useCurrentPagePath の data を使う
B. + ボタンを押したときにアイテムが持つ pagepath で usePageCreateModalPagePath の mutate を モーダルを開く前に await 実行して変更する

2021-12-03 02:11 UTC, hakumizuki commented
path が textInput の部分だけ正常に反映されないですがそれは後続にします。(https://redmine.weseek.co.jp/issues/82885)

2021-12-03 07:25 UTC, hakumizuki commented on packages/app/src/components/PageCreateModal.jsx
> +  const pathname = selectedPagePath || currentPagePath;
サポートありがとうございました。get 用、set 用の SWR に分けて管理することで対応しました

2021-12-03 11:52 UTC, yuki-takei requested changes

2021-12-03 11:52 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +type ModalStatus = {
名前を CreateModalState にしよう

2021-12-03 11:52 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +  return useStaticSWR('modalStatus', status || null);
return するものの中に、ユーティリティメソッドを含めよう。その方が親切だ。

```
const swrResponse = useStaticSWR('modalStatus', status || null);

return {
  ...swrResponse,
  open: (path?: string) => swrResponse.mutate(...),
  close: () => swrResponse.mutate(...),
}
```

2021-12-05 09:23 UTC, hakumizuki commented on packages/app/src/stores/ui.tsx
> +  return useStaticSWR('modalStatus', status || null);
含めるようにしました

2021-12-05 09:30 UTC, merged