feat: 82461 create page snapshot
weseek/growi pull request #4785
Opened 2021-12-02 08:16 UTC by miya

## Task
- [#82461](https://redmine.weseek.co.jp/issues/82461) [server] inappnotificationドキュメントにアクションが行われた時点のpageIdを保存できるようにする
- [#82528](https://redmine.weseek.co.jp/issues/82528) [client] 通知ドロップダウンに表示されるパスをスナップショットに保存されているパスに変更する

2021-12-02 12:53 UTC, yuki-takei requested changes

2021-12-02 12:53 UTC, yuki-takei commented on packages/app/src/server/models/in-app-notification.ts
> +  pageIdSnapshot: string
これは targetModel 相当の内容を JSON.stringify して保存して。
Page の情報全部入れると大きすぎるから、適宜削ってもいいとは思う。

2021-12-02 12:53 UTC, yuki-takei commented on packages/app/src/server/service/comment.ts
> +  private createAndSendNotifications = async function(activity, pagePath) {
snapshot の作り方は、targetModel によって(またはイベントによって？)違うはず。汎用的な作りにしてください。

2021-12-03 06:55 UTC, miya commented on packages/app/src/server/models/in-app-notification.ts
> +  pageIdSnapshot: string
ひとまず path、creator、lastUpdateUser を入れるようにしました。

2021-12-03 07:12 UTC, miya commented on packages/app/src/server/service/comment.ts
> +  private createAndSendNotifications = async function(activity, pagePath) {
snapshot には page の path が必須となるのでこれでいいのかと。。

2021-12-03 12:53 UTC, yuki-takei requested changes

2021-12-03 12:53 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
> +  const pagePath = { path: snapshot.path };
parse をこのコンポーネントがやるのは責務の範囲外。
User model やその他の全く関係の無いモデルが targetModel に入ってくるような例を考えよう。

2021-12-06 10:44 UTC, miya commented on packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
> +  };
renderPageModelNotification というコンポーネントを作成し、targetModel が Page のものをレンダリングするようにしました。

2021-12-06 10:44 UTC, miya commented on packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
> +
notificationClickHandler は targetModel が Page の時にのみ利用されるので renderPageModelNotification 内に移動しました。

2021-12-06 10:44 UTC, miya commented on packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
各 targetModel のコンポーネントで使いまわすために、renderNotificationDate（通知が行われた時間をレンダリングするためのコンポーネント）を作成しました

2021-12-06 16:39 UTC, yuki-takei requested changes

2021-12-06 16:39 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
> +
惜しい。悪くはないんだけど、snapshot を「作る(stringify)」する部分とこういった「表示する(parse, 整形する)」部分は同じ module か、全く同じじゃなくても近くにあると尚良い。

## 現状の問題点
- targetModel に新たなモデルを増やそうとすると、`createAndSendNotifications` を増やし、それに対応する RenderHogeModelNotification をこの tsx 内に増やすことになるが、記述箇所が遠いので何を snapshot に入れるか約束事の確認が難しい


## 代替案A (同じモジュールにする案: たぶん無理)

単純に、stringify するメソッドと jsx (component) を返すモジュールとを同じモジュールに置き、server side からは前者を import、client side からは後者を import する。おそらく後者は問題がないが、前者は commonjs として扱った時におそらく問題が出る。esm にすれば jsx 部は無視されるかもしれないけど、今はそこに取り組む時ではない。まあ実験してみてほしい。やってみて上手くいけばそれでもいい。

## 代替案B (同じモジュールにする案: 現実的だが柔軟性が低い)
stringify するメソッドと、client 向けの「表示文字列、リンク、アイコン」など共通で必要そうな部品(component ではなく、string 等のプリミティブ値を返す function)を export するモジュールを実装する。

## 代替案C: 2つのモジュールを近くに置く
案Bよりは案Aのほうが表示のチューニングを考えると柔軟であることが分かると思う。
Aを無理なく実装するには、要するに「stringify する function」と「jsx(component)」が近くにあればいい。

```
- 適当なディレクトリ
    - page
        - stringify
        - component
    - comment
        - stringify
        - component
```

2021-12-07 09:22 UTC, miya commented on packages/app/src/components/InAppNotification/TargetModel/Page/snapshot.ts
> +};
代替案Cを採用しました。snapshot を stringify するメソッド（server side で使用）と snapshot を parse するメソッド（client side で使用）を同一のファイルで行えるようにしました。

2021-12-07 09:22 UTC, miya commented on packages/app/src/components/InAppNotification/TargetModel/Page/PageModelNotification.tsx
> +export default PageModelNotification;
`components/InAppNotification` の中に `TargetModel/Page` というディレクトリを作成して、TargetModel ごとに通知のレンダリングを行うようにしました。

2021-12-07 11:31 UTC, yuki-takei requested changes

2021-12-07 11:31 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/TargetModel/Page/snapshot.ts
> +};
場所ちょっと変えよう。

`src/models/serializers/in-app-notification-snapshot/page.ts`

2021-12-07 11:31 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/TargetModel/Page/snapshot.ts
> +export const stringifyPageModel = (page: IPage): string => {
`export const stringifySnapshot = (page: IPageSnapshot): string => {`

IPageSnapshot はこのファイルで定義、export

2021-12-07 11:31 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/TargetModel/Page/snapshot.ts
> +export const getSnapshotPagePath = (snapshot: string): string => {
export const parseSnapshot = (snapshot: string): IPageSnapshot => {

2021-12-07 11:31 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/TargetModel/Page/PageModelNotification.tsx
> +export default PageModelNotification;
これは案Bと案Cのハイブリッドになったね。いいと思う。

場所ちょっと変えよう。serializer とはバラバラになってもいい。

`src/components/InAppNotification/PageNotification`

2021-12-07 12:57 UTC, miya commented on packages/app/src/components/InAppNotification/TargetModel/Page/snapshot.ts
> +export const getSnapshotPagePath = (snapshot: string): string => {
修正しました。

2021-12-07 12:58 UTC, miya commented on packages/app/src/components/InAppNotification/TargetModel/Page/snapshot.ts
> +export const stringifyPageModel = (page: IPage): string => {
IPageSnapshot を作成、stringifySnapshot の引数の型、parseSnapshot の戻り値の型に指定しました。

2021-12-07 12:59 UTC, miya commented on packages/app/src/components/InAppNotification/TargetModel/Page/PageModelNotification.tsx
> +export default PageModelNotification;
ディレクトリの場所を移動させました。

2021-12-07 13:15 UTC, yuki-takei requested changes

2021-12-07 13:15 UTC, yuki-takei commented on packages/app/src/models/serializers/in-app-notification-snapshot/page.ts
> +  });
ごめん、ここちょっとおかしかった。

`export const stringifySnapshot = (page: IPage): string => {` だね。IPage をそのまま入れてよくて、そこから snapshot を作る。

2021-12-07 13:15 UTC, yuki-takei commented on packages/app/src/models/serializers/in-app-notification-snapshot/page.ts
> +};
こっちは OK

2021-12-07 15:03 UTC, miya commented on packages/app/src/models/serializers/in-app-notification-snapshot/page.ts
> +  });
自分も見落としていました。。。修正しました。

2021-12-07 15:07 UTC, merged