Imprv/82510 mutate notification data
weseek/growi pull request #4786
Opened 2021-12-02 08:38 UTC by kaoritokashiki

2021-12-02 08:47 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
> -      mutate();
この`mutate`だけだと、「未読」のカテゴリーのみに反映されるので、
`useSWRConfig`の`mutate`を使用して、「全て既読する」ボタンを押した時に「全て」「未読」両カテゴリーでmutateされるように修正しました。

2021-12-02 09:51 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
> +      mutate(['/in-app-notification/list', limit, offset, undefined]);
useSWRのキーに含まれるstatusはoptionなので、カテゴリーに指定がない場合(-> ALL)、statusはundefinedになります。

2021-12-02 13:38 UTC, yuki-takei requested changes

2021-12-02 13:38 UTC, yuki-takei commented on packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
> -      mutate();
カプセル化されていないコードになってしまうのでよくない。

useSWRxInAppNotifications をつかった、categoryStatus を問わない mutate を別途作ればいいのでは。

2021-12-03 04:53 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
> -      mutate();
そのように修正しました。確認お願いします。

2021-12-03 06:17 UTC, kaoritokashiki commented on packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
> -      mutate();
念の為共有なんですが、
`const { data: notificationData, mutate: mutateNotificationData } = useSWRxInAppNotifications(limit, offset, categoryStatus);`
このnotificationDataは共通化されているので、statusがallの時もunopenedの時もこのdataが使われます。

2021-12-03 12:14 UTC, merged