Feat/80324 82891 search page left part design
weseek/growi pull request #4791
Opened 2021-12-03 06:58 UTC by maow89126

# やったこと
task : https://redmine.weseek.co.jp/issues/82891 

- include /hoge buttonのデザイン修正
- search result list タイトルの色修正

xd: https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/95c9e65a-742a-4f45-a75c-96561baefceb/



2021-12-06 08:18 UTC, yuki-takei requested changes

2021-12-06 08:18 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +        <div className="d-none d-lg-flex align-items-center mr-4 font-weight-lighst">
- font-weight-lighst って typo では？
- font-weight-light を上書き指定しなければならないシチュエーションがおかしい
    - bold 指定されている箇所を解除すればいいのでは？

2021-12-07 04:21 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +        <div className="d-none d-lg-flex align-items-center mr-4 font-weight-lighst">
これ通常サイズだとダメなんでしたっけ

普通に解除したらこうなった。
![image](https://user-images.githubusercontent.com/35527421/144965477-0986d6bf-d4cc-47b5-a022-16d3b2df431f.png)

2021-12-07 04:24 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +        <div className="d-none d-lg-flex align-items-center mr-4 font-weight-lighst">
値の解除の方法として正しいのかわからないけど font-weight: initial にすれば初期値解除っぽいことはできるみたい

2021-12-07 09:27 UTC, TatsuyaIse requested changes
FB です。

2021-12-07 09:27 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +            <label className="search-include-path-btn px-3 py-2 mb-0 d-flex align-items-center" htmlFor="flexCheckDefault">
まず、あててる対象のタグに対してクラスの名前もよくないし、名前に対して当ててるスタイルもあえて CSS でスタイルを記述するようなものじゃないように見える。。。  
secondary color も含め、 bootstrap に用意されてるクラスをあてるだけで完結できる。  
  
そして、本当に `<label>` タグ自身に太字のスタイル (`font-weight: 700`) が当たってしまって、その問題を解消することが目的なのであれば、  
その旨をここにコメントで残して label タグに直接 text-light クラスをあてる方がまだよい。  

問題に対する、対策が場当たり的なのが良くないです。  
分からないことがあったら聞いて

2021-12-07 09:27 UTC, TatsuyaIse commented on packages/app/src/styles/theme/_apply-colors.scss
> +            color: $color-global;
`$color-global` をあてる共通クラスって無いんだろうか？？

2021-12-07 09:27 UTC, TatsuyaIse commented on packages/app/src/styles/theme/_apply-colors.scss
> +            color: $gray-600;
こっちも、  
色をあてるだけでこの構造を持ったセレクタにしないといけないものなのだろうか？？  
不用意なネストは複雑化を助長するので、たとえば共通クラスとして用意するとか、  
ネストを浅くさせる努力をしてください。

2021-12-09 03:18 UTC, maow89126 commented on packages/app/src/styles/theme/_apply-colors.scss
> +            color: $color-global;
現状なさそうです。

2021-12-09 03:18 UTC, maow89126 commented on packages/app/src/styles/theme/_apply-colors.scss
> +            color: $gray-600;
ひとつ意見をお聞きしたいです。
meetで話したとおり、
```
// Text color
.text-color-global {
  color: $color-global;
}
```
のように共通クラすを作ることも考えたのですが、それをやるとgray-600, gray-500, gray-400...も作ることになると思いました。それはあまり美しくないのではないかと思ったのですが、いかがでしょうか？
growiのscssの書き方眺めて思ったのは必要な時に　[ここら辺](https://github.com/weseek/growi/blob/de9a3205565c9c5da08b0728a965d7ebe1fcfabb/packages/app/src/styles/theme/_apply-colors.scss#L6-L22)にスタイル名追加して書いていくスタイルなのかなと思ったのですが、
なので今の今までglray-600やcolor-globalに対する共通クラスがなかったのではないのかなと考えてました。
いかがでしょうか？

2021-12-09 03:18 UTC, maow89126 commented on packages/app/src/styles/theme/_apply-colors.scss
> +            color: $gray-600;
ネストのけんは外に出しました。

2021-12-09 07:00 UTC, TatsuyaIse requested changes

2021-12-10 04:29 UTC, TatsuyaIse requested changes

2021-12-10 04:29 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchControl.tsx
>                <input
これは、？？  
今回は対応しない？  
回答をください。

2021-12-10 04:29 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +            {/* By defualt font weight is 700 (_override-bootstrap.scss) */}
それを当てないようにクラスを用意したので、コメントは不要です。

2021-12-10 04:29 UTC, TatsuyaIse commented on packages/app/src/styles/_override-bootstrap.scss
> +  label:not(.with-no-font-weight) {
`with-no-font-weight` についてのコメントを付けようか。  
その場合、ひとつネストさせた方が読みやすいかも

2021-12-10 04:29 UTC, TatsuyaIse commented on packages/app/src/styles/theme/_apply-colors.scss
> +}
これは？  
変えちゃって大丈夫だった？？  
回答をください。

2021-12-10 06:59 UTC, maow89126 commented on packages/app/src/styles/_override-bootstrap.scss
> +  label:not(.with-no-font-weight) {
承知です

2021-12-10 06:59 UTC, maow89126 commented on packages/app/src/styles/_override-bootstrap.scss
> +  label:not(.with-no-font-weight) {
コメント一応つけましたがここでコメントは不要かと思ったのですが、いかがでしょう？

2021-12-10 09:18 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchControl.tsx
>                <input
そういう手段があるのか、なるほどな、
文字をクリックしたときもチェックの操作ができるようにするってだけなら、単純に並列で並べればいいんだけど、
それだとチェックボックスと文字との間にある空白がクリックできない領域になる。
その領域をクリッカブルにするために input を label で挟むということ
理解した。
https://quartet-communications.com/info/topics/7165

2021-12-10 09:18 UTC, TatsuyaIse commented on packages/app/src/styles/theme/_apply-colors.scss
> +}
外に出したので page-list-meta のクラスをあててる要素にスタイルが当たっているっていうのはその通りでいいんだけど、  
自分が想定している箇所のほかに、 `page-list-meta` というクラスをネストから外に出したことによる影響は発生していないか？ということを確認してほしい。
その影響範囲の確認有無が大事

2021-12-10 09:18 UTC, TatsuyaIse commented on packages/app/src/styles/_override-bootstrap.scss
> +  label:not(.with-no-font-weight) {
```
// search control include path btn
```
これは何のためのコメント？？
ちなみに、欲していたコメントの内容としては、
> 「もし、label タグにデフォルトで当たってしまう `font-weight` のスタイルをあてたくない場合にはこのクラスを指定してね」
というのが、他の実装者にも分かるようにするためのコメント

2021-12-10 09:19 UTC, TatsuyaIse reviewed
Resolve するものはして、追加でコメントしました。

2021-12-13 01:14 UTC, maow89126 commented on packages/app/src/styles/_override-bootstrap.scss
> +  label:not(.with-no-font-weight) {
あ、伊勢さんが求めてたコメントの趣旨勘違いしてました。理解しました。つけました。

2021-12-13 01:28 UTC, maow89126 commented on packages/app/src/styles/theme/_apply-colors.scss
> +    fill: $color-search-item-pagelist-meta !important;
今回の修正によってでたとかではないのですが、ひとつ気づいてしまったので修正です。

ここなのですが、足跡のみ iconではなくsvgを使ってます（FootStampIcon componentというsvgのみを返すcompponent.）。他のアイコンはicon-hogeです。

で_reboo-bootstrap-colors.scssの [ここで](https://github.com/weseek/growi/blob/f4fc5ed1fa2c145bcbf518b8f96ce54f5445a517/packages/app/src/styles/theme/_reboot-bootstrap-colors.scss#L48)　svgのhoverじのカラーを指定してます。

なのでこんな感じになってました。
![Screen Shot 2021-12-13 at 10 20 49](https://user-images.githubusercontent.com/60797707/145738435-faa64fa6-5632-4ff2-ab60-caf392717f02.png)
で、lableの時同様notを使って対処しようか考えたのですが、このsvgにクラスをつけるには FootStampIconにpropsを渡してclassを差し込むことになります。
class名をpropsとして入れるのは良くなかったはず？共通ではないものになるから。
実際そのcomponent使うときにclassを入れるべきなのか意識しなければいけなくなるという問題もあると思うのでここはコメント付けてimportantにしました。
ちなみにもうひとつ考えたのはFootStamIconみたいなcomponentをもうひとつ作るのも考えたのですが、classあるかないかだけでcomponent作るのモイマイチだなと思いやめました。

この判断が正しいか意見いただきたいです。

2021-12-13 02:26 UTC, TatsuyaIse commented on packages/app/src/styles/theme/_apply-colors.scss
> +    fill: $color-search-item-pagelist-meta !important;
今回入れた差分と関係ない部分であれば、バグストーリーかタスクを作って別途対処する。  
今のタスクのスコープ外のことには手を広げない。

2021-12-13 02:35 UTC, TatsuyaIse commented on packages/app/src/styles/theme/_apply-colors.scss
> +    fill: $color-search-item-pagelist-meta !important;
ちなみに、どういった症状が発生しているのか、何が問題なのかがいまいちわかってないです。  
あと、 svg の fill の指定なら、構造セレクタで解決できると思うのでそんなに悩むところじゃないと思う。  
詰まってしまった問題について自分で悩んで、出した答えを PR にコメント書いてレビュアーに確認してもらう・・・。って割と非効率なので、  
詰まった時は、さくっと dev チャンネルなりで垂れ流しして解決しよう。

2021-12-13 02:40 UTC, TatsuyaIse commented on packages/app/src/styles/theme/_apply-colors.scss
> +    fill: $color-search-item-pagelist-meta !important;
安易に important つけてはだめです。

2021-12-13 05:46 UTC, maow89126 commented on packages/app/src/styles/theme/_apply-colors.scss
> +    fill: $color-search-item-pagelist-meta !important;
slackで会話した通り元に戻しました。

2021-12-13 06:15 UTC, TatsuyaIse requested changes
直したら自分でマージして OK です

2021-12-13 06:15 UTC, TatsuyaIse commented on packages/app/src/styles/_override-bootstrap.scss
> +
余分な改行

2021-12-13 06:23 UTC, merged