87894 make path path scrollable
weseek/growi pull request #4814
Opened 2021-12-06 09:48 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/82894

PC版
![image](https://user-images.githubusercontent.com/35527421/144824451-19f96fbf-bd36-46cd-ae8c-08ded3cb1262.png)

SP版
![image](https://user-images.githubusercontent.com/35527421/144824301-3b6e2efc-3ad4-40e3-865c-913837b59091.png)

2021-12-06 10:28 UTC, yuki-takei requested changes

2021-12-06 10:28 UTC, yuki-takei commented on packages/app/src/styles/_layout.scss
> +  max-height: 300px;
300px っていうのも根拠がないよなあ。画面の高さが200pxしかなかったら結局大きすぎるよね。

2021-12-07 03:22 UTC, Yohei-Shiina commented on packages/app/src/styles/_layout.scss
> +  max-height: 300px;
vh にしましたvh にしました

2021-12-07 06:50 UTC, yuki-takei requested changes

2021-12-07 06:50 UTC, yuki-takei commented on packages/app/src/styles/_layout.scss
> +}
100vh - 数百px 的なのが max っていうのがちょうどいいんじゃない？

2021-12-07 07:48 UTC, Yohei-Shiina commented on packages/app/src/styles/_layout.scss
> +}
パスのリストの高さの合計値が 100vh - 330px の縦幅を超えるまでは、本来的にはスクロール不要な範囲でも以下のようにスクロールバーは表示されます。
![image](https://user-images.githubusercontent.com/35527421/144985476-b3a72780-2e7b-4491-9b56-c44d58c73ebe.png)

2021-12-07 07:54 UTC, Yohei-Shiina commented on packages/app/src/components/PageDeleteModal.tsx
> +        <div className="form-group grw-scrollable-modal-body pb-1">
以下のように overflow-y: scroll でパス名の下が若干埋もれてしまうので、pb-1 で回避してます
![image](https://user-images.githubusercontent.com/35527421/144988415-9c3539f8-1db5-4d02-8d92-5a8e26b006b4.png)

回避後
![image](https://user-images.githubusercontent.com/35527421/144988651-281cef4f-abbf-47dd-ab8d-b1d5cb0c154c.png)

2021-12-07 11:10 UTC, merged