Imprv/82973 replace createdAt to swr
weseek/growi pull request #4819
Opened 2021-12-06 17:45 UTC by kaoritokashiki

2021-12-06 17:59 UTC, kaoritokashiki commented on packages/app/src/server/views/widget/page_content.html
> +  data-page-created-at="{{ page.createdAt|datetz('Y/m/d H:i:s') }}"
1行目に `{% if page %}`があるので、 if文必要なさそうと思い削除しました。

2021-12-06 18:02 UTC, kaoritokashiki commented on packages/app/src/stores/context.tsx
> +  return useStaticSWR<Nullable<Date>, Error>('createdAt', initialData ?? null);
`useCreatedAt` -> `useCurrentCreatedAt`にrenameしました。

2021-12-06 18:12 UTC, yuki-takei requested changes

2021-12-06 18:12 UTC, yuki-takei commented on packages/app/src/client/services/ContextExtractor.tsx
> +  const createdAt = new Date(mainContent?.getAttribute('data-page-created-at') || dateNull);
Invalid Date error が起こると思うんだけど、そうなったとき使う側はどうなってしまうのだろうか…
その前に ContextExtractor がここで止まってしまいそう。

2021-12-20 06:15 UTC, kaoritokashiki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  const createdAt = new Date(mainContent?.getAttribute('data-page-created-at') || dateNull);
`dateNull` = 'null' を指定した場合は、そもそもstringを受け入れていないので
65行目でエラーが出ますね。

`null`になった場合は、以下のような`Invalid time value`エラーが出ます。

<img width="440" alt="Screen Shot 2021-12-20 at 15 12 05" src="https://user-images.githubusercontent.com/59536731/146720126-ce7c0508-b6c6-4778-8f21-b1cf0fee0636.png">

2021-12-20 06:29 UTC, kaoritokashiki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  const createdAt = new Date(mainContent?.getAttribute('data-page-created-at') || dateNull);
ブラウザ側では、`createdAt`がnullの場合、dateFnsFormatの引数に空のstring`''`を渡していますね。

```
{relatedUser.createdAt ? dateFnsFormat(new Date(relatedUser.createdAt), 'yyyy-MM-dd') : ''}
```

2021-12-20 06:49 UTC, kaoritokashiki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  const createdAt = new Date(mainContent?.getAttribute('data-page-created-at') || dateNull);
そもそもContextExtractorの内部で `  const updatedAt = null;` になった時点でダメってことか.........

2021-12-20 07:01 UTC, kaoritokashiki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  const createdAt = new Date(mainContent?.getAttribute('data-page-created-at') || dateNull);
これではダメでしょうか?
`date={updatedAt || null}`

以下のように表示されます。(1970/01/01になる)
<img width="458" alt="Screen Shot 2021-12-20 at 16 00 47" src="https://user-images.githubusercontent.com/59536731/146725481-a7b343b7-988c-4067-9451-22688f1e8487.png">

2021-12-20 08:42 UTC, yuki-takei commented on packages/app/src/client/services/ContextExtractor.tsx
> +  const createdAt = new Date(mainContent?.getAttribute('data-page-created-at') || dateNull);
Invalid time value を catch して null 入れる感じになるんじゃないかと。

2021-12-20 17:32 UTC, kaoritokashiki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  }
三項演算子で書こうとすると以下のようになります。

```
const createdAt: Date | null = (createdAtAttribute != null) ? new Date(createdAtAttribute) : null;
```

2021-12-20 17:37 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/AuthorInfo.jsx
> +    }
errがある場合は、`Created by ユーザー名`　になるようにしていますが、`err`の要因がdate以外にもあるかもしれないのでこの書き方は微妙かもしれません....。

2021-12-20 17:38 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/AuthorInfo.jsx
> +  };
subNavBarの部分です。
errがある場合は、日付が表示されないようにしました。
<img width="156" alt="Screen Shot 2021-12-21 at 2 38 10" src="https://user-images.githubusercontent.com/59536731/146809056-807dc420-4d92-45d6-83e5-9b7e60da6b14.png">

2021-12-20 17:52 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/AuthorInfo.jsx
> +    }
## Fotterの部分
errが存在してなおかつRangeErrorの場合は、
dateを省いて`Created by ユーザー名`が表示されるようにしました。
<img width="150" alt="Screen Shot 2021-12-21 at 2 52 21" src="https://user-images.githubusercontent.com/59536731/146810811-340ff9da-ad1f-4ec2-a298-dc75c91fb8d0.png">

2021-12-20 18:12 UTC, yuki-takei requested changes

2021-12-20 18:12 UTC, yuki-takei commented on packages/app/src/client/services/ContextExtractor.tsx
> +  }
三項演算子の方がいいね。

やめたほうがいいのは条件が2つ以上混じってるような場合ね。

`const hoge = isA ? b : (isC ? d : e);`

みたいな。

2021-12-20 18:12 UTC, yuki-takei commented on packages/app/src/components/Navbar/AuthorInfo.jsx
> +    }
infoLabelForSubNav が紛れ込んでる。

2021-12-21 04:18 UTC, kaoritokashiki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  }
おけです! ありがとうございます!

2021-12-21 18:16 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/AuthorInfo.jsx
> +    }
失礼しました。ここは 他の部分と同様 i18n対応せずに`Created by`を追加しました。

2021-12-21 19:01 UTC, merged