Bug/83040 83073 fix dot button design
weseek/growi pull request #4825
Opened 2021-12-07 05:51 UTC by maow89126

# TASK 

https://redmine.weseek.co.jp/issues/83073

# やったこと
- アイコンをxd同様にする。
- 削除ボタンにborderつける。
- ボタンの順番ならべかえ

備考: 
- xdだとadd to favourites になってますが、ここはadd to bookmarkのままで良いです。
xd: https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/9aa528ff-a75e-4e9a-adb9-b4b942647f29/

見た目
<img width="2032" alt="Screen Shot 2021-12-07 at 14 45 08" src="https://user-images.githubusercontent.com/60797707/144973395-2a5663bd-f186-47ca-b843-78bc77dcbb02.png">

2021-12-07 05:51 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +          <i className="icon-trash mr-1"></i>{t('Delete')}
simple iconだと若干上のfont-awesomとかと幅かんが違ったのでmr-1入れて調節しました。

2021-12-07 07:05 UTC, yuki-takei requested changes

2021-12-07 07:05 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +          <i className="icon-trash mr-1"></i>{t('Delete')}
icon-fw を入れるんだと思う。

2021-12-07 08:12 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +          <i className="icon-trash mr-1"></i>{t('Delete')}
icon-fwってicon-awesomeの何かだと思ってました。。。。
確認したらstyleあったてました。

修正しました。

2021-12-07 11:16 UTC, yuki-takei requested changes

2021-12-07 11:16 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +        <button className="dropdown-item text-danger border-top pt-2" type="button" onClick={deleteButtonHandler}>
border-top はおかしくないかな。bootstrap に devider があるはず。

2021-12-08 11:28 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +        <button className="dropdown-item text-danger border-top pt-2" type="button" onClick={deleteButtonHandler}>
対応しました。

2021-12-08 11:29 UTC, merged