imprv: Normalize pt rendering condition
weseek/growi pull request #4828
Opened 2021-12-07 08:23 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/83061

ページツリーをレンダリングする際、Page の情報がないページではルートページがターゲットになるようにしました
rootPage を別で持ってくる必要があったのでそれ用の swr を追加で実装しました

## その他
- 将来的に Modal の中でも ItemsTree.tsx, Item.tsx が使えるように Props を見直してリファクタしました

2021-12-07 08:32 UTC, hakumizuki commented on packages/app/src/stores/page-listing.tsx
> +    shouldFetch ? '/page-listing/root' : null,
条件付きにしたいケースもあるかと思うので shouldFetch をつけました

2021-12-07 11:14 UTC, yuki-takei requested changes

2021-12-07 11:14 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree.tsx
> +  const { data: targetId } = usePageId();
useCurrentPageId にリネームしてください

2021-12-07 11:14 UTC, yuki-takei commented on packages/app/src/stores/page-listing.tsx
> +    shouldFetch ? '/page-listing/root' : null,
どういうときに使うのかよくわからない

2021-12-08 03:35 UTC, hakumizuki commented
shouldFetch は自分の勘違いで付け加えていたので削除しました

2021-12-08 03:36 UTC, merged