fix: fix tag search
weseek/growi pull request #4832
Opened 2021-12-08 09:49 UTC by yuto-oweseek

## タスク

https://redmine.weseek.co.jp/issues/82980

## 行ったこと

- page に tag を付けた際に、 revision が outdated となり、ページ更新が行えなくなる挙動を修正
- duplicate した際に、 elasticsearch 側に tag が保存されず、検索にひっかからないバグを修正

## 後続

- 動作確認
- master へマージ

2021-12-08 10:02 UTC, yuto-oweseek commented on packages/app/src/components/Page/TagLabels.jsx
> +      pageContainer.updateStateAfterSave(savedPage, tags, savedPage.revision);
tag を update した際に、サーバーサイドで page が update されるため使用してます。

2021-12-09 10:29 UTC, yuki-takei requested changes

2021-12-09 10:29 UTC, yuki-takei commented on packages/app/src/components/Page/TagLabels.jsx
> +      pageContainer.updateStateAfterSave(savedPage, tags, savedPage.revision);
## 要調査
ちょっと気になるのが、以下のようなシーケンス

1. editor で markdown を編集
2. 保存せずに view へ
3. view でタグを編集、保存

この時、編集中だった PageEditor の markdown が書き換わってしまうんじゃないかと。

モデル的には PageTagRelation と Revision との間には相関がないので、タグの編集はその辺に影響を及ぼさないのが理想。

2021-12-10 08:37 UTC, yuto-oweseek commented on packages/app/src/components/Page/TagLabels.jsx
> +      pageContainer.updateStateAfterSave(savedPage, tags, savedPage.revision);
完全にぼくの顧慮もれでした....

2021-12-10 09:45 UTC, yuto-oweseek commented on packages/app/src/client/services/PageContainer.js
> +      revisionAuthor: revision.author,
今回の改修と関係ないメソッド内ですが、足りなかったので追加しました。

2021-12-10 09:45 UTC, yuto-oweseek commented on packages/app/src/client/services/PageContainer.js
> +  updatePageMetaData(page, revision, tags) {
- markdown 以外の meta data のみを更新するメソッドを作成しました
- これによって、 tag をつけたあとに revision outdated にならず、かつ、編集中の markdown も変わりません

- ↓メソッド追加背景
https://github.com/weseek/growi/pull/4832#discussion_r766474634

2021-12-10 09:45 UTC, yuto-oweseek commented on packages/app/src/client/services/PageContainer.js
> +    $('input[name="revision_id"]').val(newState.revisionId);
`$('input[name="revision_id"]').val(newState.revisionId);` は、ぼくが理解できていないですが、`updateStateAfterSave`  メソッドにもあり、 revisionId も変わるため、一応追加しました。

不要でしたら消します。

2021-12-10 09:51 UTC, yuto-oweseek commented on packages/app/src/components/Page/TagLabels.jsx
> +      pageContainer.updateStateAfterSave(savedPage, tags, savedPage.revision);
`updatePageMetaData` メソッドを作りました。

2021-12-10 12:09 UTC, yuki-takei requested changes

2021-12-10 12:09 UTC, yuki-takei commented on packages/app/src/client/services/PageContainer.js
> +    $('input[name="revision_id"]').val(newState.revisionId);
これもう存在しないね。updateStateAfterSave からも消して良さそう。

2021-12-13 07:22 UTC, merged