imprv/swr-slack-channels
weseek/growi pull request #4846
Opened 2021-12-09 08:43 UTC by stevenfukase

2021-12-09 10:20 UTC, yuki-takei requested changes

2021-12-09 10:20 UTC, yuki-takei commented on packages/app/src/components/Page.jsx
> +      {...props}
ちょっと記憶が曖昧だけど、`{...props}` は先に書かないとバグの原因にならないかな。後から書いた props で上書きされるとかなかったっけ…(要調査)

ないならこれでいいです。

2021-12-09 10:20 UTC, yuki-takei commented on packages/app/src/components/Page.jsx
> +  if (editorMode == null || isSlackEnabled == null || slackChannels == null) {
isSlackEnabled と slackChannels は editorMode ほど重要な要素ではないので、初期化されてなくてもレンダリングしてしまいたい。

2021-12-09 10:20 UTC, yuki-takei commented on packages/app/src/components/Page.jsx
> +  }
この TODO が残されたロジックのまま master にはマージしがたい。
中間地点となる feature ブランチ作った方がよさそう。

2021-12-09 10:20 UTC, yuki-takei commented on packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
> +              isSlackEnabled={isSlackEnabled || false}
`??` でいいと思う

2021-12-09 10:20 UTC, yuki-takei commented on packages/app/src/components/SavePageControls.jsx
> +  if (isEditable == null || editorMode == null || isSlackEnabled == null || slackChannels == null) {
こちらも isSlackEnabled と slackChannels が初期化されてなくてもレンダリングしてしまいたい。
GrantSelector とか DropdownToggle とかを個別にレンダリング抑制するのはアリだと思う。

2021-12-13 05:33 UTC, stevenfukase commented on packages/app/src/components/Page.jsx
> +      {...props}
修正しました

2021-12-13 10:28 UTC, yuki-takei requested changes

2021-12-13 10:28 UTC, yuki-takei commented on packages/app/src/components/Page.jsx
> +    const optionsToSave = editorContainer.getCurrentOptionsToSave();
これは undefined になりそう…

2021-12-14 05:36 UTC, merged