[WIP] fix: Pt for guest user
weseek/growi pull request #4854
Opened 2021-12-10 03:10 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/83407

ゲストユーザーもページツリーを表示できるようにしました

WIP: isGuestUser 流し中

2021-12-10 03:39 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +          )}
ゲストユーザーの場合はレンダリングしないようにしました

2021-12-10 03:39 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      )}
ゲストユーザーの場合はレンダリングしないようにしました

2021-12-10 12:01 UTC, yuki-takei requested changes

2021-12-10 12:01 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      )}
表示はさせて、アイテムを表示させない(もしくは disabled)に

2021-12-10 13:17 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      )}
リンクコピー実装などを考えると disable ではなく非表示にするのがいいと思ったので非表示にしました。ただ現状だと全て非表示で見栄えとしてはただの白いボックスになってしまうので、仮置きのメッセージをおきました。

<img width="279" alt="Screen Shot 2021-12-10 at 22 14 50" src="https://user-images.githubusercontent.com/58432773/145579634-c5b2ca63-a259-4141-9ab2-9cb6cd2fef45.png">

2021-12-10 14:32 UTC, yuki-takei requested changes

2021-12-10 14:32 UTC, yuki-takei commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  isGuestUser: boolean
すごい細かい話なんだけど、この粒度のコンポーネントは「ゲストユーザーか」というコンテキストを示す boolean よりは「ページが operatable か」(例えばの話ね) というこのコンポーネントの状態を指定する boolean を持つ方がいいと思う。

比較的大きめのコンポーネントが isGuestUser という名前で boolean を持つのはいいと思う。

境界に位置するコンポーネントはどちらにすべきか…は感覚に任せます。

2021-12-12 13:17 UTC, hakumizuki commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  isGuestUser: boolean
確かにその通りですね
境界に位置するコンポーネントは、isGuestUser それ自体が必要になりそうかで判断しました

2021-12-12 14:02 UTC, merged