83048 83415 adjust form input design
weseek/growi pull request #4868
Opened 2021-12-13 04:08 UTC by Yohei-Shiina

上部ナビバーと同じように、検索ページのナビバー内の「✕(クローズ)ボタン」の位置を虫眼鏡アイコンの左に移動

![image](https://user-images.githubusercontent.com/35527421/145750788-ddab13d1-5302-40aa-9981-4aa2bb8ae6d1.png)

2021-12-13 04:10 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +}
.search-clear だけにスタイルを充てると別ページの検索フォームに影響を与えるので .search-page を親セレクタに指定してスタイル適用

2021-12-13 10:11 UTC, yuki-takei requested changes

2021-12-13 10:11 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +}
https://github.com/weseek/growi/pull/4835 をマージしたので、追従して再調整してください。

角丸が取れたので `.grw-global-search` と同じ値でいけないか？というのももう一度見て欲しい。

2021-12-15 03:37 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +}
すみません指摘の意味がたぶん理解できていないです。

ただ最新を追従した状態でも、現状のスタイルがちょうどよいくらいの見た目にはなっています。
![image](https://user-images.githubusercontent.com/35527421/146118671-218a4961-c3e4-4729-9a5a-1f4b091fa8e1.png)

2021-12-15 03:38 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +}
`.grw-global-search` 内の `.search-clear` と数値をあわせると見た目がずれます

![image](https://user-images.githubusercontent.com/35527421/146118806-085371ac-3761-40ac-a210-1d6762bc1990.png)

2021-12-15 03:41 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +}
この場合は既存のコードで問題ないですか？

2021-12-15 10:16 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +    top: 4px;
一応アイコンの高さのみ調節した
![image](https://user-images.githubusercontent.com/35527421/146167307-7d12bd70-5f72-4be9-89df-f0af2a5f5fe0.png)

2021-12-15 10:38 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchPageForm.jsx
> +              className="text-decoration-none"
デザインが上部ナビバーとずれていたので、同じように `span` と `i` で構成し、必要なクラスのみ適用

2021-12-15 10:39 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +    top: 4px;
アイコン同士の高さ合わせ

2021-12-15 20:06 UTC, yuki-takei requested changes

2021-12-15 20:06 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchPageForm.jsx
> +      <div className="grw-global-search grw-search-form-in-search-result-page d-flex align-items-center">
このコンポーネントは global search では使わないのにこのクラス付けちゃだめでしょ。`grw-global-search` というクラスが、名が体を表さなくなる。

2021-12-15 20:06 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchPageForm.jsx
> +              className="text-decoration-none"
btn クラスか type="button" によってロールオーバー時のポインタが変化する効果が付いてたと思うんだけど、それなくならない？

2021-12-15 20:37 UTC, yuki-takei requested changes

2021-12-15 20:37 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +    top: 4px;
.grw-global-search 外でもこのスタイルを指定したいわけなので、scss の構造を見直さないといけない。

.grw-global-search の外に出して、.search-typeahead の下の .search-clear に対してこれを設定して。

今回修正方針まで指示したけど、本来ここまで細かく指示はしたくない。
常にこの意識を持って scss の整理を行ってほしい。

2021-12-16 05:00 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchPageForm.jsx
> +              className="text-decoration-none"
これを追加しました
https://getbootstrap.com/docs/4.5/content/reboot/#pointers-on-buttons

2021-12-16 05:06 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +      top: 7px;
これも少し位置が高かったのでついでに修正

2021-12-16 05:34 UTC, merged