Feat/83696 83702 fix search result item
weseek/growi pull request #4882
Opened 2021-12-13 11:47 UTC by Yohei-Shiina

2021-12-13 13:41 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +  }
margin padding 等を適用させるための position:relative

2021-12-13 13:42 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +            padding-left: 4px;
.search-item-checkbox で適用しているpadding-left のサイズから追加した border のサイズをマイナスして、ボーダー追加時もコンテンツが横に動かないように調節

2021-12-13 13:42 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchPageLayout.tsx
> +              <ul className="page-list-ul page-list-ul-flat px-md-4 nav nav-pills"><SearchResultList></SearchResultList></ul>
SP版の時は px-4もいらないので md 以上に変更

2021-12-13 13:55 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +                    <div dangerouslySetInnerHTML={{ __html: pageMeta.elasticSearchResult.snippet }}></div>
margin, padding 等の spacing が正しくなかったので必要な個所にクラスをあててXD通りに調節

2021-12-13 13:56 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +              <div className="position-absolute item-control">
3点ボタンの位置を正しくするために position で指定

2021-12-13 13:56 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +            <div className="d-flex align-items-center mb-2 position-relative">
81行目で position 指定するための relative

2021-12-13 13:58 UTC, Yohei-Shiina commented on packages/ui/src/components/PagePath/PageListMeta.jsx
> +      bookmarkCount = <span className="meta-icon"><i className="icon-star" />{this.props.bookmarkCount}</span>;
>span のようなアンチパターンの書きあk他になっていたのでそれぞれ共通クラスをつけてcssで調節

2021-12-13 13:58 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +            margin-right: 14px;
アンチパターンになっていたので`> span` に該当するものに共通クラスを付けてスタイルを適用

2021-12-13 13:59 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +  }
XD通りの値をぞれぞれ適用

2021-12-13 21:51 UTC, yuki-takei requested changes

2021-12-13 21:51 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +            <div className="d-flex align-items-center mb-2 position-relative">
relative, absolute 共に利用すべきケースではない

2021-12-13 21:51 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +  }
CSS 指定が多すぎる

2021-12-14 03:31 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +        padding: 7px;
別ページにも参照されているので、css で調節

2021-12-14 03:33 UTC, Yohei-Shiina commented on packages/app/src/styles/_search.scss
> +            padding-left: 4px !important;
動的に変えたいのでcssで調整。bootstrap の spacingに負けるので !important を付与

2021-12-14 03:34 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +            <h6 className="item-path mb-1">
XDでは margin-bottom 4px だが bootstrap で指定し、 3.5px になっている

2021-12-14 10:18 UTC, Yohei-Shiina commented on packages/app/src/styles/theme/_apply-colors.scss
> +            }
SP版ではタップでページ遷移するため不要と判断

2021-12-14 12:00 UTC, yuki-takei requested changes

2021-12-14 12:00 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +          }
ここは OK

2021-12-14 12:02 UTC, yuki-takei requested changes

2021-12-14 12:02 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +        padding: 7px;
これはどういうことかわからない。もし「別ページ＝検索関連以外」に影響させるべくここに記述しているなら NG

2021-12-15 09:08 UTC, Yohei-Shiina commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +        className="btn-link dropdown-toggle dropdown-toggle-no-caret border-0 rounded grw-btn-page-management py-0 px-2"
padddingをもつ nav-link を消して、個別に px-2 を付与

2021-12-15 09:36 UTC, Yohei-Shiina commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +        className="btn-link dropdown-toggle dropdown-toggle-no-caret border-0 rounded grw-btn-page-management py-0 px-2"
`.nav-link` に padding 当たっているのと、そのクラスがここにあるのは適切ではなさそうなのではずし。

代わりに`.px-2` を付与

2021-12-15 09:36 UTC, Yohei-Shiina commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +        <i className="fa fa-ellipsis-v text-muted p-1"></i>
親クラスの `px-2` を合わせて、XDで求められているボタンの大きさ(20px) に近づけるために付与

2021-12-15 09:37 UTC, Yohei-Shiina commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +        <i className="fa fa-ellipsis-v text-muted p-1"></i>
![image](https://user-images.githubusercontent.com/35527421/146161561-2f15620b-4b52-4df9-b573-f8469b7194e3.png)

2021-12-15 20:14 UTC, yuki-takei requested changes

2021-12-15 20:14 UTC, yuki-takei commented on packages/app/src/styles/theme/_apply-colors.scss
> +            }
これ対応されていない。

https://getbootstrap.jp/docs/4.5/components/list-group/

SP で `list-group-item-action` を外す

2021-12-16 06:03 UTC, merged