feat: Backend search show snippet
weseek/growi pull request #4885
Opened 2021-12-13 13:29 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/83733

検索結果のスニペット表示のバックエンドを実装しました

## コメント
- mongo の $substr operator で実装しました
- 他にもっと簡単な方法あるか模索しましたが現状これしか発見できていません

2021-12-13 13:30 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +export const generateGrantConditions = async(
Page.aggregation 用にユーティリティーとして実装しました。既存の PageQueryBuilder の処理を踏襲しています

2021-12-13 13:33 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +                },
まず WHERE $_id = $$localRevision

2021-12-13 13:33 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +                },
ここで $body に $substr を適用

2021-12-13 21:47 UTC, yuki-takei requested changes

2021-12-13 21:47 UTC, yuki-takei commented on packages/app/src/components/SearchPage.jsx
> +    const res = await this.props.appContainer.apiv3Get('/page-listing/short-bodies', { pageIds });
apiv3Get は appContainer を介さず直接 import して

2021-12-13 21:47 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +export const generateGrantConditions = async(
返り値の型が `Promise<{[key:string]: any | number | null}[]>` というプリミティブ値で構成されているあたりが、既存のPageQueryBuilder のクラスメソッド実装と比べて制約が緩い。mongoose が用意しているタイプを指定しよう。

https://github.com/Automattic/mongoose/blob/master/index.d.ts#L2947

2021-12-14 02:35 UTC, hakumizuki commented on packages/app/src/components/SearchPage.jsx
> +    const res = await this.props.appContainer.apiv3Get('/page-listing/short-bodies', { pageIds });
しました

2021-12-14 02:51 UTC, hakumizuki commented
mongoose ^6.0.13 時点では該当する型が存在しなかったので、現行 master と中身が全く同じ方を定義しました

```
type PipelineStageMatch = {
  $match: AnyObject
};
```

2021-12-14 08:10 UTC, merged