84033 btn click color
weseek/growi pull request #4929
Opened 2021-12-17 06:06 UTC by maow89126

# Task
https://redmine.weseek.co.jp/issues/84033

mosさんに口頭でもらったdesin checkの修正。

# 内容
- ぼたんclick時にhover時よりさらに濃くする。
- buttonをborder-radius 2pxとあったが、現状4px. 2pxにしてみても目に見える違いはなかったの2pxのコードは追加しなかったです。

https://user-images.githubusercontent.com/60797707/146497105-01795264-70bf-4dca-8da0-0bc5994971dc.mp4

https://user-images.githubusercontent.com/60797707/146497111-5a11a64c-83a6-4e82-bf05-d5a3a0cadec8.mp4

2021-12-17 07:56 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors.scss
> +
dark theme でもこの指定で大丈夫ですかね??

2021-12-20 03:16 UTC, kaoritokashiki requested changes

2021-12-20 03:16 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors.scss
> +
`grw-btn-page-management`を一つのブロックとして、その中に`hover``focus`, `active`の指定をしてください。

2021-12-20 03:18 UTC, kaoritokashiki commented
あと、定期的に`dev/5.0.x` を自分のブランチにマージした方が良さそうです。icon hover時の形など修正されているので

2021-12-20 04:13 UTC, maow89126 commented on packages/app/src/styles/theme/_apply-colors.scss
> +
対応しました。

2021-12-20 04:40 UTC, kaoritokashiki requested changes

2021-12-20 04:40 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors.scss
> +    background-color: rgba($color-link, 0.2);
:hoge の前に `&`つけてください

2021-12-20 05:02 UTC, maow89126 commented on packages/app/src/styles/theme/_apply-colors.scss
> +    background-color: rgba($color-link, 0.2);
対応しました。

2021-12-20 05:08 UTC, kaoritokashiki approved these changes

2021-12-20 08:33 UTC, merged