Feat/81920 83419 fix search right pane
weseek/growi pull request #4933
Opened 2021-12-17 08:36 UTC by TatsuyaIse

### task
- https://redmine.weseek.co.jp/issues/83419

### images
![image](https://user-images.githubusercontent.com/8895367/146514486-adb0c99a-9c77-4e6e-92fb-82c695144ff8.png)

gif
![search-result-right-page](https://user-images.githubusercontent.com/8895367/146514097-5a93bbdf-de07-49d7-866c-da8aa5dbc4b3.gif)

right pane with long title( with tiny body)
![image](https://user-images.githubusercontent.com/8895367/146513706-7c766dd7-2feb-4bfc-8727-e447fe7608e5.png)

right pane with long title( with large body)
![right-page-long-title](https://user-images.githubusercontent.com/8895367/146514636-d53732d8-84aa-44d0-a6f1-400fff4dc382.gif)

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/components/PagePathNav.tsx
> +  const copyDropdownToggleClassName = 'd-block text-muted bg-transparent btn-copy shadow-none border-0 py-0';
URL コピーのドロップダウンに影が付いていたので消去

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/components/Page/PageManagement.jsx
> +          <i className="text-muted icon-options"></i>
文字色をデザインに合わせて変更

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/components/Page/PageManagement.jsx
> +          <i className="text-muted icon-options"></i>
文字色をデザインに合わせて変更

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +    <div key={page._id} className="search-result-page grw-page-path-text-muted-container d-flex flex-column">
適切なクラスが既にあったのでそれをあてる。
右ペインで立て並びの flex を構成するため flex-colum

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +      <div className="search-result-page-content">
overflow したらスクロールできるように RevisionLoader を wrap してスタイルをあてる

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> -  }, [pageId, mutateTagInfo]);
タグを付ける UI が不要になったため削除

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> +    <div className="position-sticky fixed-top shadow-sm search-result-content-nav">
sticky 化

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
> -        )}
タグを付ける UI が不要になったため削除してます

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/styles/_search.scss
> +      min-height: 90px;
デザインに合わせて右ペインの最低高さを指定

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/styles/_search.scss
> +      overflow: auto;
ページタイトルが長すぎる場合にスクロールすることがあるので auto にしている

2021-12-17 09:00 UTC, TatsuyaIse commented on packages/app/src/styles/_search.scss
> +        overflow-y: auto;
スクロールできるように auto

2021-12-17 09:22 UTC, yuki-takei requested changes

2021-12-17 09:22 UTC, yuki-takei commented on packages/app/src/components/PagePathNav.tsx
> +  const copyDropdownToggleClassName = 'd-block text-muted bg-transparent btn-copy shadow-none border-0 py-0';
これはそのままでいいです。

2021-12-17 09:22 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +      min-height: 90px;
マジックナンバーいやだな

2021-12-17 09:22 UTC, yuki-takei commented on packages/app/src/styles/_search.scss
> +          min-height: 50%;
50%というのもなにか引っかかる

2021-12-20 03:48 UTC, TatsuyaIse commented on packages/app/src/styles/_search.scss
> +          min-height: 50%;
50% 不要でした

2021-12-20 03:49 UTC, TatsuyaIse commented on packages/app/src/styles/_search.scss
> +      min-height: 90px;
`$grw-navbar-height` 等と同様に、定数化しました。

2021-12-20 03:57 UTC, TatsuyaIse commented on packages/app/src/components/PagePathNav.tsx
> +  const copyDropdownToggleClassName = 'd-block text-muted bg-transparent btn-copy shadow-none border-0 py-0';
戻しました。

2021-12-20 07:52 UTC, merged