84092 hide search page
weseek/growi pull request #4952
Opened 2021-12-20 04:48 UTC by maow89126

# Task 
https://redmine.weseek.co.jp/issues/84092

# やったこと
SearchPageかではGlobalSearchを表示しないようにする。
Navバーにあるのと、spサイズ時画面下にも出てきてた。

# 写真

<img width="1920" alt="Screen Shot 2021-12-20 at 13 46 49" src="https://user-images.githubusercontent.com/60797707/146713289-a5e03962-9978-45b3-b0be-f2131e5ad147.png">

<img width="251" alt="Screen Shot 2021-12-20 at 13 47 33" src="https://user-images.githubusercontent.com/60797707/146713306-00118204-1559-4874-afd6-688cfcfd9973.png">

2021-12-20 08:30 UTC, yuki-takei requested changes

2021-12-20 08:30 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiNavbar.tsx
> +  const isNotSearchPage = document.getElementById('search-page') == null;
コンポーネントで dom を探す手段は raw すぎる。

- ContextExtractor でその state を作るようにして
- GrowiNavbar と GrowiNavbarBottom は、`hideSearchInput: boolean` を props に持つようにする

2021-12-20 08:30 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiNavbarBottom.jsx
> +            {isNotSearchPage
隠すのはボタンだけじゃだめ

2021-12-21 04:11 UTC, maow89126 commented
>隠すのはボタンだけじゃだめ

このコメント意図理解できてるか微妙だったのでまだfb対応してないのですが、意味としては li ごと消した方がいいという意味でしたか？

2021-12-21 04:13 UTC, maow89126 commented on packages/app/src/components/Navbar/GrowiNavbar.tsx
> +  const isNotSearchPage = document.getElementById('search-page') == null;
対応しました

2021-12-21 04:13 UTC, maow89126 commented on packages/app/src/components/Navbar/GrowiNavbarBottom.jsx
> +              !hideSearchInput && (
>隠すのはボタンだけじゃだめ

ここに関してのコメント意図理解できてるか微妙だったのでまだfb対応してないのですが、意味としては li ごと消した方がいいという意味でしたか？

2021-12-21 04:15 UTC, maow89126 commented on packages/app/src/components/Navbar/GrowiNavbarBottom.jsx
> +            {isNotSearchPage
このコメントの意図が理解できてるか微妙だったのでまだfb対応してないのですが、意味としては li ごと消した方がいいという意味でしたか？

2021-12-21 08:14 UTC, yuki-takei requested changes

2021-12-21 08:14 UTC, yuki-takei commented on packages/app/src/client/services/ContextExtractor.tsx
> +  const isSearchPage = document.getElementById('search-page') || null;
これだと element が変数に入る。boolean になるように。存在するかどうかなので null も許容しない。

2021-12-21 08:14 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiNavbar.tsx
> +  const { appContainer, hideSearchInput } = props;
ここで useIsSearchPage 使っていいと思う。

2021-12-21 08:14 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiNavbarBottom.jsx
> +  const { hideSearchInput } = props;
ここで useIsSearchPage 使っていいと思う。

2021-12-21 08:15 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiNavbarBottom.jsx
> +            {isNotSearchPage
li が何を意味してるのかわからない。

意図は、トリガーとなるボタンだけではなく、GlobalSearch のインスタンスそのまま作らないようにしてほしい。

2021-12-21 08:56 UTC, maow89126 commented on packages/app/src/client/services/ContextExtractor.tsx
> +  const isSearchPage = document.getElementById('search-page') || null;
booleanになるようにしました。

2021-12-21 08:56 UTC, maow89126 commented on packages/app/src/components/Navbar/GrowiNavbar.tsx
> +  const { appContainer, hideSearchInput } = props;
そうしました。

2021-12-21 08:56 UTC, maow89126 commented on packages/app/src/components/Navbar/GrowiNavbarBottom.jsx
> +  const { hideSearchInput } = props;
そうしました。

2021-12-21 08:56 UTC, maow89126 commented on packages/app/src/components/Navbar/GrowiNavbarBottom.jsx
> +      { isDeviceSmallerThanMd && !isSearchPage && (
>意図は、トリガーとなるボタンだけではなく、GlobalSearch のインスタンスそのまま作らないようにしてほしい。

対応しました。

2021-12-21 09:36 UTC, merged