84265 adjast to changes from dev5
weseek/growi pull request #4955
Opened 2021-12-20 06:25 UTC by maow89126

# Task
https://redmine.weseek.co.jp/issues/84265

#　内容
dev5を統合にマージしたら、buttonのクリックした時の幅が調整されていたが、84265storyで button内のfont-awesomeからsimple-iconに変えたのでdev5での変更が意図した通りに動いていなかった為の対応タスク。

<img width="241" alt="Screen Shot 2021-12-20 at 15 23 33" src="https://user-images.githubusercontent.com/60797707/146721342-360b2288-212a-4f7f-8c88-a9d48e6047d7.png">

<img width="1166" alt="Screen Shot 2021-12-20 at 15 23 17" src="https://user-images.githubusercontent.com/60797707/146721326-9b7d322a-b511-4eeb-811d-c24fdbee1404.png">

2021-12-20 06:27 UTC, maow89126 commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
>          <i className="icon-options fa fa-rotate-90  text-muted p-1"></i>
このストーリでfont-awesomeからsimple-line-iconに変更したためdev5のボタンはばと統一するためにpaddingを少しいじりました。

2021-12-20 07:48 UTC, kaoritokashiki commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
>          <i className="icon-options fa fa-rotate-90  text-muted p-1"></i>
現状classに`btn-link` が指定されていますが、実際のところ`link-color`を適用していないので、`btn-link`自体を外して、paddingをbootstrapで調整する方がいいいのでは?と思ってきました。

2021-12-20 09:51 UTC, kaoritokashiki commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
>          <i className="icon-options fa fa-rotate-90  text-muted p-1"></i>
そもそも`btn-link`の指定いらそうですね。
btn-link 外してbootstrap の paddingで幅調整で良さそう。

↓bootstrapのbtn-link
https://getbootstrap.jp/docs/4.5/components/buttons/#examples

2021-12-20 09:52 UTC, kaoritokashiki requested changes

2021-12-21 01:56 UTC, maow89126 commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
>          <i className="icon-options fa fa-rotate-90  text-muted p-1"></i>
確かに不要でした。
外しました。ちなみに、btn-link外しても特に見た目に影響はなかったのでpaddingなどはいじってないです。

2021-12-21 04:37 UTC, kaoritokashiki approved these changes

2021-12-21 04:37 UTC, merged