imprv: Remove unrunnable mongo methods
weseek/growi pull request #4965
Opened 2021-12-20 11:28 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/84294

Mongo で dbOwner の権限しかない場合にパブリックマイグレーションが開始できない不具合を修正しました

2021-12-20 11:31 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +    }
連打されると何が起こるのかわからなかったので、`processable` `processing` `done` で状態を管理して、`processable` の時のみ index 変更処理が走り、`processing` の時はリターンし、`done` の時のみ本当のページマイグレーションに進めるようにしました

2021-12-20 11:32 UTC, hakumizuki commented on packages/app/src/server/service/config-loader.ts
> +    default: 'done',
デフォルトは `done`
アップグレードしてくるユーザーは null なのでインデックスを変更できる

2021-12-20 11:56 UTC, yuki-takei requested changes

2021-12-20 11:56 UTC, yuki-takei commented on packages/app/src/server/service/config-loader.ts
> +    default: 'done',
この config 値を用意するよりは、同一 path のダミーページを2つ永続化して unique 制約エラーが出るかどうかでインデックス状態をチェックするメソッドを実装する

2021-12-20 13:34 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +    }
config は boolean にして、連打された時に何回も走るのを防ぐようにしました

2021-12-20 14:29 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +    }
そもそも状態をDBに保持する config いらないんじゃない？

2021-12-21 03:33 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +    }
削除して、isUnique のみによって判断しました

2021-12-21 08:11 UTC, yuki-takei requested changes

2021-12-21 08:11 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +      if (err?.code === 11000) {
11000 が表すエラーのサマリ or URL をコメントに書いておいて

2021-12-21 08:11 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +    await Page.deleteMany({ path: { $regex: new RegExp('growi_check_is_path_index_unique', 'g') } });
この delete は finally でやるべきだね。

2021-12-21 08:11 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +        throw err;
throw し直すなら利用側でも try-catch が必要になる。
個人的にはここで投げ直さず、ログ吐いて飲み込むでもいいんじゃないかと思う。

2021-12-21 08:24 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +    await Page.deleteMany({ path: { $regex: new RegExp('growi_check_is_path_index_unique', 'g') } });
finnaly で行いました

2021-12-21 08:25 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +      if (err?.code === 11000) {
サマリを追加しました

2021-12-21 08:27 UTC, hakumizuki commented on packages/app/src/server/service/page.js
> +        throw err;
isUnique が不正に false になると本当は unique インデックスあるのにマイグレーションが開始されてしまって正常に終了できない可能性があるので今回は throw しました。使う側に try-catch と logger を移動しました

2021-12-21 08:31 UTC, merged