use brighter gray
weseek/growi pull request #4967
Opened 2021-12-21 03:21 UTC by Yohei-Shiina

2021-12-21 03:43 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +      className={`w-100 page-list-li border-bottom ${responsiveListStyleClass}`}
page-list-li と search-result-item の独自スタイルが２つあたっていたので一つ消してまとめた

2021-12-21 03:45 UTC, Yohei-Shiina commented on packages/app/src/styles/theme/_apply-colors.scss
> +$bgcolor-search-page-list-hover: $gray-50 !default;
デザイナー要望で 検索結果一覧のリストのホバー時の背景色を `$gray-50` に設定

2021-12-21 07:46 UTC, kaoritokashiki requested changes

2021-12-21 07:46 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors.scss
> +    }
dark themeの場合も考慮しないといけないですね

2021-12-21 07:46 UTC, kaoritokashiki commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +      className={`w-100 page-list-li border-bottom ${responsiveListStyleClass}`}
`page-list-li` ってGROWI 独自のclassですかね??
その場合はprefixにgrwをつけるようお願いします!

また、search result独自のクラスの場合は`search` をclass名に含めた方が良さそうです。

2021-12-22 13:55 UTC, Yohei-Shiina commented on packages/app/src/styles/theme/_apply-colors.scss
> -  .search-result-page-title {
このクラスは使われていないので削除

2021-12-22 13:55 UTC, Yohei-Shiina commented on packages/app/src/styles/theme/_apply-colors-light.scss
> -$bgcolor-subnav: darken($bgcolor-global, 3%) !default;
_apply-colorsに移動

2021-12-22 14:12 UTC, yuki-takei requested changes

2021-12-22 14:12 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultListItem.tsx
> +  const responsiveListStyleClass = `${isDeviceSmallerThanLg ? '' : `grw-search-result-item-hover list-group-item-action ${isSelected ? 'active' : ''}`}`;
bootstrap の list を使って hover 等の表現を行っているのに、grw-search-result-item-hover を付ける必要はないように思う。

2021-12-22 14:12 UTC, yuki-takei commented on packages/app/src/styles/theme/_apply-colors-dark.scss
> +  }
`&.text-muted` を `.input-group-text` の中に置いた方が上書きしたいということがよくわかる。

2021-12-22 14:12 UTC, yuki-takei commented on packages/app/src/styles/theme/_apply-colors.scss
> +$bgcolor-search-page-list-hover: $gray-50 !default;
どのテーマでも灰色になるのはよくない。`$bgcolor-global` などのテーマに合った色を選択しよう。

2021-12-23 03:35 UTC, merged