fix: 84367 error that occurs when a page is completely deleted
weseek/growi pull request #4970
Opened 2021-12-21 06:51 UTC by miya

## Task
[#84367](https://redmine.weseek.co.jp/issues/84367) 修正

## Memo
ページを完全に削除したときに以下のようなエラーがでる問題、完全に削除したページの path を検索したときに検索結果画面に `Cannot  read proety '_doc' of undifined` というエラーが表示される問題を修正しました。

```
 deletePages:ES Error TypeError: pages.forEach is not a function
      at ElasticsearchDelegator.deletePages (/workspace/growi/packages/app/src/server/service/search-delegator/elasticsearch.ts:575:11)
      at ElasticsearchDelegator.syncPagesDeletedCompletely (/workspace/growi/packages/app/src/server/service/search-delegator/elasticsearch.ts:967:25)
      at PageEvent.emit (events.js:412:35)
      at PageService.deleteCompletely (/workspace/growi/packages/app/src/server/service/page.js:661:20)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at api.remove (/workspace/growi/packages/app/src/server/routes/page.js:1091:9)
```

2021-12-21 08:08 UTC, miya commented on packages/app/src/server/service/page.js
> +    this.pageEvent.emit('deleteCompletely', [page], user, isRecursively); // update as renamed page
`service/page.js` の deleteMultipleCompletely でも deleteCompletely というイベントを使用していたため、isRecursively という引数を新しく追加して親ページの完全削除のみ Activity / InAppNotification を作成するようにしました。

`service/elasticsearch.ts` で syncPagesDeletedCompletely の引数で pages という配列で渡す必要があったので修正しました。

2021-12-21 08:34 UTC, yuki-takei commented on packages/app/src/server/service/page.js
>        }
- 単数(isRecursively: false)の完全削除
- 単数の親(isRecursively: true)の完全削除
- 複数の完全削除

の3パターンにこの一つのイベントタイプで対応してしまっているので読みにくい。
具体的には `pages[0]` に違和感。「if 単数削除なら `pages[0]`」ならまだ理解できるが、「if !isRecursively なら `pages[0]`」はおかしい。

2021-12-21 10:05 UTC, miya commented on packages/app/src/server/service/search.ts
> +    pageEvent.on('deleteCompletely', this.fullTextSearchDelegator.syncPageDeleted.bind(this.fullTextSearchDelegator));
- 単体の完全削除の場合は、既存の `syncPageDeleted`  を利用するようにしました
- 複数削除の場合は新たに `deleteMultipleCompletely` というイベントを作成して、`service/elasticsearch` の `syncPageDeleteMultipleCompletely` というメソッドを実行するようにしました。

2021-12-21 10:54 UTC, miya commented on packages/app/src/server/service/page.js
>        }
新しいイベントを作成して対応しました。

2021-12-21 12:38 UTC, yuki-takei requested changes

2021-12-21 12:38 UTC, yuki-takei commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +  async syncPageDeleteMultipleCompletely(pages, user) {
syncPageDeleted と syncPageDeleteMultipleCompletely はカバーできてるとして、
単数の完全削除と、複数の完全じゃない削除はカバーできているのか？

2021-12-22 04:41 UTC, miya commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +  async syncPageDeleteMultipleCompletely(pages, user) {
- 単数の削除、単数の完全削除 の場合は `syncPageDeleted` でカバー
- 複数の削除、複数の完全削除 の場合は `syncDescendantsPagesDeleted` でカバー するようにしました

2021-12-22 05:56 UTC, miya commented on packages/app/src/server/service/page.js
> +    }
複数の削除がカバーされていなかったので対応しました。

- 単数の削除 / 単数の完全削除 の場合は `syncPageDeleted` でカバー
- 複数の削除 / 複数の完全削除 の場合は `syncDescendantsPagesDeleted` でカバー 
するようにしました。

検索結果ページからの 削除 / 完全削除 は `components/SearchPage/SearchResult.jsx` から map で1ページずつ （isRecursively が false）`POST: /pages.remove` が叩かれるため、`syncPageDeleted` でカバーできています。

2021-12-22 05:56 UTC, miya commented on packages/app/src/server/service/search.ts
> +    pageEvent.on('syncDescendantsUpdate', this.fullTextSearchDelegator.syncDescendantsPagesUpdated.bind(this.fullTextSearchDelegator));
`syncDescendantsDelete` と合わせるためにリネームしました。

2021-12-22 08:59 UTC, merged