fix alert message
weseek/growi pull request #4978
Opened 2021-12-21 15:03 UTC by kaoritokashiki

2021-12-21 17:03 UTC, kaoritokashiki commented on packages/app/src/components/Admin/AdminHome/AdminHome.jsx
> +        (migrationStatus != null && !migrationStatus.isV5Compatible)
`migrationStatus != null`を条件式に追加しました

2021-12-21 18:57 UTC, yuki-takei requested changes

2021-12-21 18:57 UTC, yuki-takei commented on packages/app/src/components/Admin/AdminHome/AdminHome.jsx
> +      fetchAdminHomeData();
`await adminHomeContainer.retrieveAdminHomeData();` をそのまま書けばいいと思う

2021-12-21 19:03 UTC, kaoritokashiki commented on packages/app/src/components/Admin/AdminHome/AdminHome.jsx
> +      fetchAdminHomeData();
useEffect内でそれをしようとする(async)をそこにかくなワーニングが出るんですよね、、試してみたらわかると思います。

2021-12-21 19:05 UTC, yuki-takei approved these changes

2021-12-21 19:09 UTC, yuki-takei commented on packages/app/src/components/Admin/AdminHome/AdminHome.jsx
> +      fetchAdminHomeData();
だとすると別の方法を探さないとだけど、このままだと try-catch 効かないんじゃないかな。

2021-12-21 19:12 UTC, yuki-takei commented on packages/app/src/components/Admin/AdminHome/AdminHome.jsx
> +      fetchAdminHomeData();
これ試してみて。

```
  const fetchAdminHomeData = useCallback(async() => {
    try {
      await adminHomeContainer.retrieveAdminHomeData();
    }
    catch (err) {
      toastError(err);
      adminHomeContainer.setState({ retrieveError: err });
      logger.error(err);
    }
  }, [adminHomeContainer]);

  useEffect(() => {
    fetchAdminHomeData();
  }, [fetchAdminHomeData]);
```

2021-12-22 20:15 UTC, kaoritokashiki commented on packages/app/src/client/services/AdminHomeContainer.js
> +      throw new Error('Failed to retrive AdminHome data');
Container側では、throw new Errorをし、toasterは AdminHome componentにて表示

2021-12-22 20:28 UTC, kaoritokashiki commented on packages/app/src/components/Admin/AdminHome/AdminHome.jsx
> -      adminHomeContainer.setState({ retrieveError: err });
`adminHomeContainer`の`state`に定義されている`retrieveError`は使われている場所がなかったので削除しました。

2021-12-22 21:37 UTC, merged