Imprv/tags swr
weseek/growi pull request #4987
Opened 2021-12-22 08:22 UTC by stevenfukase

2021-12-23 09:55 UTC, stevenfukase commented on packages/app/src/client/services/EditorContainer.js
> -
contextExtractorでやってることなので不要

2021-12-23 09:56 UTC, stevenfukase commented on packages/app/src/client/services/EditorContainer.js
> -
pageTagsのSWR化によって不要

2021-12-23 09:58 UTC, stevenfukase commented on packages/app/src/client/services/TagContainer.js
> +    // editorContainer.setState({ tags });
packages/app/src/stores/editor.tsxに移行
pageContainerでの影響範囲は不明なのでTagContainerは残してあります

2021-12-23 10:01 UTC, stevenfukase commented on packages/app/src/client/util/apiv1-client.ts
> +export async function apiRequest<T>(method: string, path: string, params: unknown): Promise<T> {
一律でUnknownだとTSでエラー出る(packages/app/src/stores/editor.tsxの28行目参照)のでGenericsを受け付けるようにしました。

2021-12-23 10:02 UTC, stevenfukase commented on packages/app/src/stores/editor.tsx
> +      const res = await apiGet<GetPageTagResponse>(endpoint, { pageId });
apiGetをGenericsを受け付けるようにしました。

2021-12-23 10:04 UTC, stevenfukase commented on packages/app/src/components/SavePageControls.jsx
> +import { useIsSlackEnabled, usePageTags } from '~/stores/editor';
こちらのファイルではgetOptionsToSaveにpageTageを流し込むようにしただけです。

2021-12-23 10:04 UTC, stevenfukase commented on packages/app/src/components/Page.jsx
> +import { useIsSlackEnabled, usePageTags } from '~/stores/editor';
こちらのファイルではgetOptionsToSaveにpageTageを流し込むようにしただけです。

2021-12-23 10:05 UTC, stevenfukase commented on packages/app/src/components/PageEditor.jsx
> +import { useIsSlackEnabled, usePageTags } from '~/stores/editor';
こちらのファイルではgetOptionsToSaveにpageTagsを流し込むようにしただけです。

2021-12-23 10:05 UTC, stevenfukase commented on packages/app/src/components/PageEditorByHackmd.jsx
> +import { useIsSlackEnabled, usePageTags } from '~/stores/editor';
こちらのファイルではgetOptionsToSaveにpageTagsを流し込むようにしただけです。

2021-12-23 10:12 UTC, stevenfukase commented on packages/app/src/components/Page/TagLabels.jsx
> +      appContainer, pageContainer, editorMode, mutateEditorContainerTags,
pageContainerのTagとSWR化したものが共存してますが表示・編集は問題ありませんでした。

2021-12-23 11:35 UTC, yuki-takei requested changes

2021-12-23 11:35 UTC, yuki-takei commented on packages/app/src/stores/editor.tsx
> +  return useSWR('/pages.getPageTag', fetcher);
PageContainer で管理する tags は、サーバーから取ってくる方式でよい。
editor で使う tags データは、useStaticSWR で上記を初期値として設定して mutate していく方がいいんじゃないかな。

2021-12-23 11:35 UTC, yuki-takei commented on packages/app/src/components/Page/TagLabels.jsx
> +class TagLabelsCore extends React.Component {
この行数なら TS 化 および FC 化までやってほしいな。

2021-12-24 03:23 UTC, stevenfukase commented on packages/app/src/components/Page/RenderTagLabels.tsx
> +/* eslint-disable react/prop-types */
FB対応: TSのエラーを防ぐため、TagLabelsの子コンポーネントであるこちらのコンポーネントもTS化しました

2022-03-30 01:38 UTC, stevenfukase commented
こちら、進んでいないためクローズします。すみません。

2022-03-30 01:38 UTC, closed without merging