feat: upgrade conflict modal
weseek/growi pull request #5012
Opened 2021-12-24 10:20 UTC by yuto-oweseek

# master へマージ

↓ master へのマージタスク
https://redmine.weseek.co.jp/issues/81442

2021-12-26 14:27 UTC, yuki-takei requested changes

2021-12-26 14:27 UTC, yuki-takei commented on packages/app/src/client/util/apiv1ErrorHandler.js
> +module.exports = Apiv1ErrorHandler;
このファイルいらないのでは？
apiv1-client.ts の中身と重複してるね。

2021-12-26 14:27 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +import { UncontrolledCodeMirror } from '../UncontrolledCodeMirror';
8 行目の `import { UnControlled as ReactCodeMirror } from 'react-codemirror2';` を整理した方がいいね。

2022-01-04 09:46 UTC, yuto-oweseek commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +import { UncontrolledCodeMirror } from '../UncontrolledCodeMirror';
> 8 行目の import { UnControlled as ReactCodeMirror } from 'react-codemirror2'; を整理した方がいいね。

↑ 完全に使われなかったので、削除しました。

2022-01-04 09:46 UTC, yuto-oweseek commented on packages/app/src/client/util/apiv1ErrorHandler.js
> +module.exports = Apiv1ErrorHandler;
> このファイルいらないのでは？
> apiv1-client.ts の中身と重複してるね。

どこからも読み込まれていなかったので、削除しました。

2022-01-05 19:20 UTC, yuki-takei approved these changes

2022-01-05 19:21 UTC, merged