feat: Revision v5 migration
weseek/growi pull request #5020
Opened 2022-01-04 01:39 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/84859

Revision の path を pageId に変換するマイグレーションファイルを実装しました

2022-01-04 01:43 UTC, hakumizuki commented on packages/app/src/server/models/revision.js
>    revisionSchema.statics.prepareRevision = function(pageData, body, previousBody, user, options) {
ついでに変更しました

2022-01-04 01:43 UTC, hakumizuki commented on packages/app/src/server/models/revision.js
> -  revisionSchema.statics.removeRevisionsByPath = function(path) {
使われてなかったので消しました

2022-01-04 09:21 UTC, yuki-takei requested changes

2022-01-04 09:21 UTC, yuki-takei commented on packages/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration.js
> +    const updateManyOperations = pages.map((page) => {
Page 数分の map ってめちゃくちゃ数多いのでは…

2022-01-04 11:48 UTC, hakumizuki commented on packages/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration.js
> +    const updateManyOperations = pages.map((page) => {
再帰関数で 300 ページずつやるようにしました

2022-01-04 17:09 UTC, yuki-takei requested changes

2022-01-04 17:09 UTC, yuki-takei commented on packages/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration.js
> +    };
単なる可読性の話でしかないけど、これはあえて recursive なコードにする必要はないなあ。

要は query, offset, limit の3つを引数に取るメソッドがあればそこから cursor を作って bulkWrite はできるわけで。
それを最初に取得した total count 分だけ回せばいいだけだよね。

2022-01-05 04:29 UTC, hakumizuki commented on packages/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration.js
> +    };
total count 取って回すのもありでしたが、慣れてる方の stream でやるようにしました

2022-01-05 04:30 UTC, hakumizuki commented on packages/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration.js
> +    };
テストは revision に関する改修が全て終わった後に書き直しますので、CI はスルーします

2022-01-05 05:54 UTC, merged