84856
weseek/growi pull request #5054
Opened 2022-01-11 04:40 UTC by maow89126

Task:

2022-01-11 05:52 UTC, maow89126 commented on packages/app/src/components/LegacyPage.tsx
> +// 1. set excluded hoge based on props
現状legacy pageはinclude user , include trashがtrueじゃないと表示されないので、propsで設定する。
将来的にはどちらでも動くことになるのでこのprops入らなくなる。

2022-01-11 05:52 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +                  checked={!props.excludeUserPages}
今までなぜchekcedなしでcheckが昨日していたのか謎なのですが今回気づいたのでcheckedをconditionalで追加.

2022-01-11 05:52 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +                  checked={!props.excludeTrashPages}
今までなぜchekcedなしでcheckが昨日していたのか謎なのですが今回気づいたのでcheckedをconditionalで追加.

2022-01-11 05:52 UTC, maow89126 commented on packages/app/src/server/service/page.js
> +    return Page.count({ parent: null, creator: user });
今回のタスクとは関係ないが、public pageでmigrate済んでないものも含むべきため変更。
増山くんに確認済みです。

2022-01-13 08:03 UTC, maow89126 commented on packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> +        {t('search_result.delete_all_selected_page')} */}
ここは一旦後継タスク85465ででやります。

2022-01-13 13:53 UTC, hakumizuki requested changes

2022-01-14 03:35 UTC, hakumizuki requested changes
1. Delete => Action にした部分はそれに関する引数などの名前も改名してください
2. あと、依存配列をもう一度チェックしてください依存がめちゃくちゃあるやつはむしろメモ化しないほうがいいかもしれません(メモ化のコストの方が高くなると予想している)
3. `Modal` は見た目から機能までがっつり変わる一方、`SearchControl` は機能が変わらずにボタン部分のパーツだけが変わるものなので、`renderSearchControl`を外から流すのではなくボタンのパーツを外から流せばいいと思います

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/LegacyPage.tsx
> +  const renderActionsToPageModal = (isDeleteConfirmModalShown, getSelectedPagesToDelete, closeDeleteConfirmModalHandler) => {
isDeleteConfirmModalShown, getSelectedPagesToDelete, closeDeleteConfirmModalHandler を改名しましょう

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchCore.tsx
> +  renderActionToPagesModal: (isDeleteConfirmModalShown, getSelectedPagesToDelete, closeDeleteConfirmModalHandler) => React.FunctionComponent,
isDeleteConfirmModalShown, getSelectedPagesToDelete, closeDeleteConfirmModalHandler を改名しましょう

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchPage/ActionToPageGroup.tsx
> +  actionType : ActionToPagesType,
actionType ではなく、実際にレンダーする DOM or renderDOM 関数を Props に渡すほうがいいと思います。(ActionToPageGroup はどんな actionType が存在するか知る必要がない)

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +  actionType: ActionToPagesType
ActionToPageGroup の変更に伴ってここも同じように変更

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchCore.tsx
> +  renderSearchControl:any, // (searchingKeyword, sort, order, searchResultCount, appContainer, onSearchInvoked, toggleAllCheckBox, selectAllCheckboxType, actionToAllPagesButtonHandler, switchExcludeU
ここは SearchControl に渡すボタン部分の DOM or renderDOM 関数でいい

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchCore.tsx
> +  const [actionTargetPageIds, sestActionToTargetPageIds] = useState<Set<unknown>>(new Set());
unknown の型が既にわかっていればその型に

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchCore.tsx
> +  }, []);
setSort, setOrder が依存配列に欲しいのでは？

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchCore.tsx
> +  }, [excludeUserPages]);
setExcludeUserPages を依存配列に入れるほうがいいと思います

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchCore.tsx
> +  }, [excludeTrashPages]);
ここも set 関数の方かと

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchCore.tsx
> +  }, [search]);
ここの依存配列は足りてますか？

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchCore.tsx
> +  }, [currentSearchedKeyword, search]);
ここの依存配列は足りてますか？

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchCore.tsx
> +  }, [currentSearchedKeyword, search]);
ここの依存配列は足りてますか？

2022-01-14 03:35 UTC, hakumizuki commented on packages/app/src/components/SearchPage.tsx
> +  const renderActionsToPageModal = (isDeleteConfirmModalShown, getSelectedPagesToDelete, closeDeleteConfirmModalHandler) => {
ここの引数も改名

2022-01-17 02:35 UTC, maow89126 commented on packages/app/src/components/SearchCore.tsx
> +  renderSearchControl:any, // (searchingKeyword, sort, order, searchResultCount, appContainer, onSearchInvoked, toggleAllCheckBox, selectAllCheckboxType, actionToAllPagesButtonHandler, switchExcludeU
直しました.

2022-01-17 02:53 UTC, maow89126 commented on packages/app/src/components/SearchCore.tsx
> +  }, [setActivePage, currentSearchedKeyword, search]);
こことかってsearchを依存配列に入れる必要ありますかね？？
searchを入れるのにあまりしっくり来てないのですが、 auto fixで入ってたので放置してました。
この依存はいれつにsearchが入っているせいで 依存配列多めのsearchのuseCallbackを外せず困ってます。。

2022-01-17 11:13 UTC, hakumizuki commented
Delete じゃないのに名前が Delete になってる部分はいずれ改名してください

2022-01-17 17:53 UTC, yuki-takei requested changes

2022-01-17 17:53 UTC, yuki-takei commented on packages/app/src/components/LegacyPage.tsx
> +// 3. onAfterSearchInvoked should be refactored in LegacyPage
renderSearchForm はどこでも使ってないようだ。必要なの？何を実装するの？
icon migrate もどういうゴールにするのかわからない。アイコン選定？アイコン自作？
onAfterSearchInvoked は呼んでるので実装する必要があるのはわかるけどどんな処理を実装するつもりなのかがわからない。

2022-01-17 17:53 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +          </div>
今の実装では `actionIconAndText` だけを外から注入しているが、むしろ 122-140 行目までをまるっと注入できてよさそう。DeleteSelectedPageGroup も消す必要はない。

2022-01-18 09:23 UTC, maow89126 commented
TODO 書き直しました。
確認お願いします。

2022-01-18 09:23 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchControl.tsx
> +          </div>
DeleteSelectedPageGroupを改名して復活させました。
SearchPage,LegacyPageでrender methodを作り、流し込みました。

2022-01-18 13:26 UTC, yuki-takei commented on packages/app/src/components/LegacyPage.tsx
> +// 3. onAfterSearchInvoked should be refactored in LegacyPage
1, 2 は理解した。3はよくは理解できなかった。

「なにもしない」ようにしたいなら、SearchCore の onAfterSearchInvoked という props 自体を optional にするという選択肢もありそうだと思うんだけど。

2022-01-18 13:29 UTC, yuki-takei commented
コンフリクト解消して。

2022-01-20 02:50 UTC, maow89126 commented on packages/app/src/components/LegacyPage.tsx
> +// 3. onAfterSearchInvoked should be refactored in LegacyPage
すいません、その思考抜けてました。
おっしゃる通りです。

onAfterSearchInvoked optionalにしました。

2022-01-20 05:46 UTC, merged