[PENDING] imprv: Group list table
weseek/growi pull request #5055
Opened 2022-01-11 05:06 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/85178

グループ表示リストを改善しました。
UserGroupPage.tsx の取得処理は SWR 化しました

2022-01-11 09:37 UTC, hakumizuki commented on packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +};
ChildGroups 表示用です

2022-01-11 09:37 UTC, hakumizuki commented on packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +  return (
スタイルは適当です

2022-01-11 09:39 UTC, hakumizuki commented on packages/app/src/stores/middlewares/serialize.ts
> +};
key が object になるとレンダリング回数が増えるので serializer を実装しました。今 swr 1.1.0 にあげるのにはまだ調査が足りてないので調査後にバージョンアップしようと思います

2022-01-11 13:12 UTC, yuki-takei requested changes

2022-01-11 13:12 UTC, yuki-takei commented on packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
> +      }, false);
mutate 呼ぶだけにした方がいいね

2022-01-11 13:12 UTC, yuki-takei commented on packages/app/src/stores/middlewares/serialize.ts
> +};
1.1 系を採用したい

2022-01-12 07:30 UTC, hakumizuki commented
swr を 1.1.2 に上げて、mutate もシンプルにしました

2022-01-12 08:09 UTC, yuki-takei requested changes

2022-01-12 08:09 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +export const useCreateModalPath = (): SWRResponse<Nullable<string | undefined>, Error> => {
元のインターフェースになるように実装を変更する

2022-01-12 08:09 UTC, yuki-takei commented on packages/app/src/stores/user-group.tsx
> +      fallbackData: initialData,
型が UserGroupListResult じゃないような

useSWRImmutable 利用時に Generics 使ってください。

2022-01-12 08:09 UTC, yuki-takei commented on packages/app/src/stores/user-group.tsx
> +export const useSWRxChildUserGroupList = (parentIds?: string[], initialData?: IUserGroupHasId[]): SWRResponse<ChildUserGroupListResult, Error> => {
parentIds が null の場合も利用できていいのか？

2022-01-12 08:09 UTC, yuki-takei commented on packages/app/src/stores/user-group.tsx
> +export const useSWRxUserGroupRelationList = (groupIds?: string[], initialData?: IUserGroupRelationHasId[]): SWRResponse<UserGroupRelationListResult, Error> => {
groupIds が null の場合も利用できていいのか？

2022-01-12 08:09 UTC, yuki-takei commented on packages/app/src/stores/user-group.tsx
> +      fallbackData: initialData,
型が変

2022-01-12 08:09 UTC, yuki-takei commented on packages/app/src/stores/user-group.tsx
> +      fallbackData: initialData,
型が変

2022-01-12 12:51 UTC, hakumizuki commented
型システムが活かせるように修正しました

2022-01-12 16:14 UTC, merged