[wip] imprv: 85389 Retrieve page info with SWR
weseek/growi pull request #5057
Opened 2022-01-11 06:47 UTC by miya

## Task
[#85389](https://redmine.weseek.co.jp/issues/85389) isLiked, likers, sumOfLikers, seenUserIds, sumOfSeenUsers, isSeen を SWR で取得できる

2022-01-11 13:04 UTC, miya commented on packages/app/src/components/LikeButtons.tsx
> +  };
`LikeButtons` の責務ではないと思うのですが、`checkAndUpdateImageUrlCached` は PageContainer 内で like ボタンが押された時に呼ばれていたメソッドだったのでここに移動させました。自信がないのでここはアドバイスいただきたいです。

2022-01-11 13:41 UTC, yuki-takei requested changes

2022-01-11 13:41 UTC, yuki-takei commented on packages/app/src/components/LikeButtons.tsx
> +  };
SWR の middleware で副作用的に実行しましょう

2022-01-11 13:41 UTC, yuki-takei commented on packages/app/src/components/User/LikerList.tsx
> +  const { data: pageId } = usePageId();
props から取得

2022-01-11 13:41 UTC, yuki-takei commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const { data: pageId } = usePageId();
props から取得

2022-01-11 13:41 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    ['page/info', pageId],
エンドポイントのURL、`/` から始めてください

2022-01-11 13:41 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +      };
return するのって response.data そのままじゃだめなの？

2022-01-11 13:41 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/page.js
> +      }
populate のコストが高すぎる

2022-01-11 13:41 UTC, yuki-takei commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const { data: pageInfo } = useSWRxPageInfo(pageId);
ここで手に入るのは全ユーザーの ID リスト( total count を手に入れるため)

その後、users.list API を叩いて UserPictureList 用のデータを手に入れる
その際、取得する対象ユーザーは seenUsers と liker と混ぜたリストを指定した方が SWR のキャッシュがよく効く。

2022-01-11 13:44 UTC, miya commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const { data: pageInfo } = useSWRxPageInfo(pageId);
## memo 
`users.list` を SWR化する際に引数を `IPageInfo` の型を入れる

2022-01-12 03:44 UTC, miya commented on packages/app/src/components/User/LikerList.tsx
> +  const { data: pageId } = usePageId();
親コンポーネントから pageId を渡すようにしました。

2022-01-12 03:44 UTC, miya commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const { data: pageId } = usePageId();
親コンポーネントから pageId を渡すようにしました。

2022-01-12 03:48 UTC, miya commented on packages/app/src/stores/page.tsx
> +      };
そのままで大丈夫です！修正しました！

2022-01-12 04:10 UTC, miya commented on packages/app/src/components/User/LikerList.tsx
> +  const { data: pageId } = usePageId();
親コンポーネントから pageId を渡すようにしました。

2022-01-14 09:44 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +export const useSWRxPageInfo = <Data, Error>(pageId: Types.ObjectId): SWRResponse<IPageInfo, Error> => {
クライアント側で ObjectId を扱いたくないので、引数は string にしてください。

2022-01-14 09:45 UTC, yuki-takei commented on packages/app/src/stores/user.tsx
> +    (endpoint, userIds) => apiv3Get(endpoint, { userIds }).then(response => response.data.users),
`userIds.join(',')` はここでやる

2022-01-14 09:46 UTC, yuki-takei commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const { data: usersList } = useSWRxUsersList([...likerIds, ...seenUserIds].join());
カンマ区切りの string にならなくない？

2022-01-14 09:47 UTC, yuki-takei commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const { data: usersList } = useSWRxUsersList([...likerIds, ...seenUserIds].join());
likerIds と seenUserIds、それぞれ 15件に絞ってから concat し、最大30件データ取得する。

2022-01-14 12:38 UTC, miya commented on packages/app/src/components/LikeButtons.tsx
> +  const isLiked = pageInfo?.isLiked != null ? pageInfo.isLiked : false;
修正しました。

2022-01-17 08:52 UTC, yuki-takei requested changes

2022-01-17 08:52 UTC, yuki-takei commented on packages/app/src/components/User/LikerList.tsx
> +  const likers = usersList != null ? usersList.filter(({ _id }) => likerIds.includes(_id)).slice(0, 15) : [];
https://github.com/weseek/growi/pull/5057#discussion_r784702752
が考慮されていない。

20行目で `[...likerIds, ...seenUserIds]` の結果が 1000 人分とかになるケースを考えて。

2022-01-17 08:52 UTC, yuki-takei commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const { data: usersList } = useSWRxUsersList([...likerIds, ...seenUserIds]);
こっちは最大30件になるのでOK

2022-01-17 08:52 UTC, yuki-takei commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const seenUsers = usersList != null ? usersList.filter(({ _id }) => seenUserIds.includes(_id)).slice(0, 30) : [];
slice は15件じゃない？

2022-01-17 08:52 UTC, yuki-takei commented on packages/app/src/stores/user.tsx
> +    ['/users/list'],
キーにも distinctUserIds を入れないと。SWR のドキュメント読んで。

2022-01-17 08:52 UTC, yuki-takei commented on packages/app/src/components/User/LikerList.tsx
> +const LikerList: FC<Props> = (props: Props) => {
もしかしてだけど、LikerList ってどこにも使ってないことない？

2022-01-17 08:52 UTC, yuki-takei commented on packages/app/src/components/LikeButtons.tsx
> +  const likers = usersList != null ? usersList.filter(({ _id }) => likerIds.includes(_id)).slice(0, 15) : [];
#5057 (comment)
が考慮されていない。

32行目で [...likerIds, ...seenUserIds] の結果が 1000 人分とかになるケースを考えて。

2022-01-18 13:07 UTC, yuki-takei commented on packages/app/src/components/User/LikerList.tsx
> +const LikerList: FC<Props> = (props: Props) => {
`liker-list` という ID の DOM 自体、どこにもないのでは？

2022-01-18 13:10 UTC, yuki-takei requested changes

2022-01-18 13:10 UTC, yuki-takei commented on packages/app/src/stores/user.tsx
> +  const distinctUserIds = userIds != null ? Array.from(new Set(userIds)).sort() : [];
userIds が null だったら、この SWR 自体が機能しないようにキーを null にする。

2022-01-20 05:59 UTC, merged