show children
weseek/growi pull request #5066
Opened 2022-01-11 13:06 UTC by kaoritokashiki

## Task
- [85173](https://redmine.weseek.co.jp/issues/85173) Drag中の要素が、他のページ要素に重なった時にchildrenも表示されるようにする

## ScreenRecording

2022-01-11 13:10 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      timerId.current = window.setInterval(() => {
`setInterval()`を使おうとすると、`Type 'Timeout' is not assignable to type 'number'.`(null もundefinedも)と怒られるので、以下のコメントを参考に`window.setInterval()`を使用しました。
https://github.com/TypeStrong/atom-typescript/issues/1053#issuecomment-321126192

2022-01-11 13:48 UTC, yuki-takei requested changes

2022-01-11 13:48 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      timerId.current = window.setInterval(() => {
- setTimeout を使う
- 1000ms 後に「もし isOver が true のままなら open 状態にする」という条件付きの処理を入れる

2022-01-12 05:56 UTC, yuki-takei requested changes

2022-01-12 05:56 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  const timerId = useRef(0);
いらないね

2022-01-12 09:41 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  const timerId = useRef(0);
すみません、削除いたしました。

2022-01-12 09:47 UTC, merged