imprv: User group update parent
weseek/growi pull request #5067
Opened 2022-01-11 13:50 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/85464

UserGroup の更新処理を実装しました
ルールは https://dev.growi.org/%E8%B3%87%E6%96%99/%E5%A4%96%E9%83%A8%E4%BB%95%E6%A7%98/%E3%83%9A%E3%83%BC%E3%82%B8v5 の通りです(話し合った通り)

2022-01-13 10:21 UTC, hakumizuki commented on packages/app/src/server/models/user-group.js
> +
この時点で parent が子孫のグループを指していた場合に throw するべきなのですが忘れていたので後続タスクでやります

2022-01-13 11:08 UTC, hakumizuki commented on packages/app/src/server/models/user-group.js
> +    }
ここで親と子でユーザーを比べて包含関係を担保してます

2022-01-13 11:15 UTC, yuki-takei commented
元のソース 150 行なんで、TS化も一緒にやりましょう。その方が新規実装コードが安全になる。

2022-01-13 11:24 UTC, yuki-takei requested changes

2022-01-13 11:24 UTC, yuki-takei commented on packages/app/src/server/models/user-group.js
> +  static async updateGroup(id, name, description, parentId, forceUpdateParents = false) {
wiki 化したルールのURLをコメントで入れてください

2022-01-13 11:24 UTC, yuki-takei commented on packages/app/src/server/models/user-group.js
> +    const parent = await this.findById(parentId);
parent が null 値の時(トップレベルへの移動)にも対応する必要がある。

2022-01-13 11:24 UTC, yuki-takei commented on packages/app/src/server/models/user-group.js
> +    }
いいオプションだと思う。
Wiki の方にそれも書いておいて。

2022-01-13 11:24 UTC, yuki-takei commented on packages/app/src/server/models/user-group.js
> +    const UserGroupRelation = mongoose.model('UserGroupRelation');
UserGroupRelation を UserGroup から参照するのは NG

2022-01-13 11:35 UTC, hakumizuki commented on packages/app/src/server/models/user-group.js
> +    const parent = await this.findById(parentId);
これは後続でやります

2022-01-13 11:36 UTC, hakumizuki commented on packages/app/src/server/models/user-group.js
> +  static async updateGroup(id, name, description, parentId, forceUpdateParents = false) {
いれました

2022-01-13 12:23 UTC, hakumizuki commented
.js => .ts にはしましたが、statics は any で妥協しているので [後続](https://redmine.weseek.co.jp/issues/85723) で any 排除します

2022-01-13 12:24 UTC, hakumizuki commented on packages/app/src/server/models/user-group.ts
> +  };
このメソッドは後続でサービス層に移します

2022-01-13 12:25 UTC, hakumizuki commented on packages/app/src/server/service/user-group.ts
> +    }
null にセットするのは後続でやります

2022-01-13 12:26 UTC, hakumizuki commented on packages/app/src/server/service/user-group.ts
> +  async updateGroup(id, name, description, parentId, forceUpdateParents = false) {
サービス層に移しました

2022-01-14 06:53 UTC, hakumizuki commented on packages/app/src/server/models/user-group.js
> +    const UserGroupRelation = mongoose.model('UserGroupRelation');
サービス層に逃しました

2022-01-14 06:54 UTC, hakumizuki commented on packages/app/src/server/models/user-group.js
> +    }
入れました

2022-01-14 07:15 UTC, merged