WIP: Update descendant count
weseek/growi pull request #5086
Opened 2022-01-13 12:14 UTC by Yohei-Shiina

2022-01-13 12:15 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.js
> +    const updatedPageIds = []; // 既に更新されたページ
日本語後ほど修正

2022-01-13 12:17 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.js
> +    const findSelfAndDescendant = await this.findSelfAndDescendant(path, grant);
変数がメソッド名みたいなので後ほど修正

2022-01-13 12:25 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.js
> +    // this.recountPage().then(res => logger.info(res)).catch(err => logger.warn(err));
後ほど消す

2022-01-13 12:31 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.js
> +  async recountPage(targetIds) {
特定パス以下すべての descendantCount を更新するメソッドです

2022-01-13 13:12 UTC, yuki-takei requested changes

2022-01-13 13:12 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +schema.statics.findAllDescendantsByPath = async function(path, grant = 1) {
grant の指定は対応する必要がない。カウントはプライベートなページも全てやってしまってよいので。

2022-01-13 13:12 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +      // https://regex101.com/r/8R3Meh/1
regex101を見たけどこれではだめ。実際のパスと同じような文字列でテストしないと。

https://regex101.com/r/9CjsI6/1 を用意したので見て。

2022-01-13 13:12 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +};
これどこからも使われてないじゃん…

2022-01-13 13:12 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +    // this.recountPage().then(res => logger.info(res)).catch(err => logger.warn(err));
このコード、消し忘れあると怖いから、手元で使う時だけ有効化するっていう方法で開発して欲しい。つまり、PR ではコメントアウトされている状態にして。

2022-01-13 13:26 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +        return !updatedPageIds.map(_ => _.toString()).includes(id.toString());
ここは計算量が無駄に多い気がする

2022-01-13 13:26 UTC, yuki-takei commented on packages/app/src/server/service/page.js
> +      });
recountTargetIds が何を表しているのかがちょっと理解できない(コメントの意味はわかるけど、変数名がしっくりこないのとコードが表す実態を想像できない)。

口頭で説明してほしい。

2022-01-14 04:16 UTC, Yohei-Shiina commented on packages/app/src/server/models/page.ts
> +schema.statics.findAllDescendantsByPath = async function(path, grant = 1) {
退避所にあるページは parent を持たないのでここで grant つけて回避してましたが parent を持つものだけ match するようにすれば良さそうなのでそうします

2022-01-17 11:51 UTC, yuki-takei requested changes

2022-01-17 11:51 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +schema.statics.getAggrConditionForPagesStartingWithProvidedPath = function(path:string) {
starting with ではだめだよね。

2022-01-17 11:51 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +    // https://regex101.com/r/Nax9Ms/1
このコメントは regexp のすぐそばに置いて

2022-01-17 12:15 UTC, merged