Imprv/create page user validation
weseek/growi pull request #5095
Opened 2022-01-17 06:46 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/84202

ページの Create に grant, grantedGroup のバリデーションを追加しました

## この PR での変更
- UserGroup の仕様変更によって親子関係を維持するようにバリデーションを追加
  - https://dev.growi.org/61b2cdabaa330ce7d8152844

2022-01-17 06:52 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +     */
これ以下は v4 の create です

2022-01-17 06:53 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +      page.parent = options.grant === GRANT_RESTRICTED ? null : parentId;
GRANT_RESTRICTED では parent が確実に null になるようにしました

2022-01-17 07:05 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +      }
ここで権限が条件を満たしているかチェックしてます

2022-01-17 08:23 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  }
口頭で説明したいくらいですが一応文章化。

### / ... / New に作成する場合
1. 作成予定のページの権限を持つユーザーのセットを用意
2. 作成予定ページの「空ではなく、最も近い」ページの権限を持つユーザーのセットを用意
3. 「2 が 1 を含む」なら `true`, 含まなければ `false` をリターン

### / ... / New / ... に作成する場合
1. 上と同じ
2. 上と同じ
3. 子孫ページ全てに関して権限を持つユーザーのセットを用意
4. 「2 が 1 を含む」かつ「3 が 2 を含む」なら `true`, それを満たさないなら `false` をリターン

2022-01-17 08:24 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  private async generateDescendantsGrantedUsers(targetPath: string): Promise<ObjectId[]> {
子孫ページ全てに関して権限を持つユーザーのセットを用意

2022-01-17 08:24 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  private async generateAncestorsGrantedUsers(targetPath: string): Promise<ObjectId[]> {
作成予定ページの「空ではなく、最も近い」ページの権限を持つユーザーのセットを用意

2022-01-17 08:24 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  private async generateTargetsGrantedUsersForCreate(user, grant, grantedUserIds: ObjectId[], grantedGroupId: ObjectId): Promise<ObjectId[]> {
作成予定のページの権限を持つユーザーのセットを用意

2022-01-17 08:25 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  validateByGrantUsers(targetUsers: ObjectId[], ancestorsUsers: ObjectId[], descendantsUsers?: ObjectId[]): boolean {
ユーザーのセットを比較するメソッド

2022-01-17 09:26 UTC, yuki-takei requested changes

2022-01-17 09:26 UTC, yuki-takei commented on packages/app/src/server/service/page-grant.ts
> +  async pageValidationForCreate(pathToCreate: string, user, grant, grantedUserIds: ObjectId[], grantedGroupId: ObjectId): Promise<boolean> {
メソッド名 boolean を返しそうな名前にしましょう

2022-01-17 09:26 UTC, yuki-takei commented on packages/app/src/server/service/page-grant.ts
> +  }
決めた外部仕様から外れちゃだめなやつ
https://dev.growi.org/61b2cdabaa330ce7d8152844

2022-01-17 09:26 UTC, yuki-takei commented on packages/app/src/server/models/obsolete-page.js
> +    const isV5Compatible = crowi.configManager.getConfig('crowi', 'app:isV5Compatible');
このファイルで分岐するのはやめて、極力 page.ts に v5 で使う処理を書こう

2022-01-17 09:26 UTC, yuki-takei commented on packages/app/src/server/models/obsolete-page.js
> +      page.parent = options.grant === GRANT_RESTRICTED ? null : parentId;
そのロジックは update でも使うはずなのでメソッドに切り出す

2022-01-18 05:33 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  }
使用通りにしました

2022-01-18 05:34 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +      page.parent = options.grant === GRANT_RESTRICTED ? null : parentId;
後続でやります

2022-01-18 05:34 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  async pageValidationForCreate(pathToCreate: string, user, grant, grantedUserIds: ObjectId[], grantedGroupId: ObjectId): Promise<boolean> {
しました

2022-01-18 05:35 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +    const isV5Compatible = crowi.configManager.getConfig('crowi', 'app:isV5Compatible');
後続で移動します

2022-01-18 05:44 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +    const isV5Compatible = crowi.configManager.getConfig('crowi', 'app:isV5Compatible');
page.ts に移動しました

2022-01-18 05:45 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +  pageSchema.statics.createV4 = async function(path, body, user, options = {}) {
master からそのまま持ってきました

2022-01-18 05:46 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +  ancestors.forEach(page => !ancestorsMap.has(page.path) && ancestorsMap.set(page.path, page._id)); // the earlier element should be the true ancestor
null の要素が入ってくることがあったので修正しました

2022-01-18 05:47 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +  schema.statics.create = async function(path, body, user, options = {}) {
v5 用 create はここに持ってきました

2022-01-18 05:47 UTC, hakumizuki commented on packages/app/src/server/models/user-group.ts
> +schema.statics.findGroupsWithDescendantsById = async function(groupId) {
findGroupsWithDescendantsRecursively を直接使うより使いやすいメソッドを作りました

2022-01-18 05:50 UTC, hakumizuki commented on packages/app/src/server/util/compare-objectId.ts
>  type IObjectId = mongoose.Types.ObjectId;
### このファイルの修正
- string も引数として許容できるように改善しました

2022-01-18 05:56 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +    }
ここで今回実装したメソッドを呼んで、権限チェックしてます

2022-01-18 06:03 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  async isGrantNormalized(targetPath: string, grant, grantedUserIds: ObjectId[], grantedGroupId: ObjectId): Promise<boolean> {
外で使われるメソッドです

2022-01-18 06:12 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  async isGrantNormalized(targetPath: string, grant, grantedUserIds: ObjectId[], grantedGroupId: ObjectId, shouldCheckDescendants = false): Promise<boolean> {
これが外で使われるメソッドです。`shouldCheckDescendants` で下まで見る必要があるかを決められます

2022-01-18 06:15 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +    }
ここで今回実装した `isGrantNormalized` を実行しています

2022-01-18 06:17 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  private processValidation(target: ComparableTarget, ancestor: ComparableAncestor, descendants?: ComparableDescendants): boolean {
if 文の塊です。ここに必要な情報(`ComparableTarget`, `ComparableAncestor`, `ComparableDescendants?`)が渡ってきて、結果が出ます

2022-01-18 06:18 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  ): Promise<ComparableTarget> {
`ComparableTarget` を準備します

2022-01-18 06:19 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  private async generateComparableAncestor(targetPath: string): Promise<ComparableAncestor> {
`ComparableAncestor` を準備します

2022-01-18 06:19 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +  private async generateComparableDescendants(targetPath: string): Promise<ComparableDescendants> {
`ComparableDescendants` を準備します

2022-01-18 06:20 UTC, hakumizuki commented
結局、グループ下でのみ `Only me` は使えるようにしました

2022-01-18 12:48 UTC, yuki-takei requested changes

2022-01-18 12:48 UTC, yuki-takei commented on packages/app/src/server/util/compare-objectId.ts
> +  return castToString(id1) === castToString(id2);
いらないなら消す

2022-01-18 13:01 UTC, hakumizuki commented on packages/app/src/server/util/compare-objectId.ts
> +  return castToString(id1) === castToString(id2);
消しました

2022-01-18 13:03 UTC, hakumizuki commented on packages/app/src/server/util/compare-objectId.ts
> +};
toString を呼ぶようにしました

2022-01-18 13:08 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +    if (ancestor.grant === Page.GRANT_OWNER) {
else if にしました

2022-01-18 13:08 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +    if (ancestor.grant === Page.GRANT_USER_GROUP) {
else if にしました

2022-01-18 13:35 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
> +    });
後続でやります

2022-01-18 19:28 UTC, yuki-takei requested changes

2022-01-18 19:28 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +};
実態はただの findOneByPath で、parent という単語がメソッド名及び引き数名に入っているのは違和感。

2022-01-19 04:38 UTC, merged