feat: send title username and buffered image to ogp server but needs refactor
weseek/growi pull request #5096
Opened 2022-01-17 07:11 UTC by yuto-oweseek

WIP

## 別リポジトリ同一 PR

## タスク

https://redmine.weseek.co.jp/issues/84597

## 行ったこと

## 後続

- userimage を丸くして表示
- lint 導入
- ci 修正
- jest 導入

2022-01-17 12:10 UTC, yuki-takei requested changes

2022-01-17 12:10 UTC, yuki-takei commented on packages/app/src/server/routes/ogp.ts
> +        }
この処理は else 扱い。つまり default image でもなく attachment でもない場合は全て axios.get を試みる

2022-01-17 12:10 UTC, yuki-takei commented on packages/app/src/server/util/user-image-url.ts
> +};
これは不要になる

2022-01-17 12:10 UTC, yuki-takei commented on packages/app/src/server/util/user-image-url.ts
> +};
これも不要になる

2022-01-17 12:10 UTC, yuki-takei commented on packages/app/src/server/util/user-image-url.ts
> +};
このファイルで必要なのはこのメソッドだけなので、あえて util module にする必要はない気がする。
routes/ogp.ts に定義してしまえばいいのではないか。

2022-01-17 12:10 UTC, yuki-takei commented on packages/app/src/server/routes/ogp.ts
> +        pageTitle = generatePageTitleFromPagePath(page.path);
ページ名だけを表示するより親までのパスを表示した方がわかりやすくなるかもしれない。

現時点ではとりあえず DevidedPagePath を使ってページタイトルだけを表示して。
後続タスクで親までのパスを表示するかどうかを検討する。

2022-01-17 12:10 UTC, yuki-takei commented on packages/app/src/server/routes/ogp.ts
> +        return res.status(500).send(ApiResponse.error(`error: ${err}`));
API v1 ではないで、ApiResponse を利用するのはやめよう。

この route はちょっと特殊かもしれない。独自の形式でレスポンスしていいと思う。

2022-01-17 12:10 UTC, yuki-takei commented on packages/app/src/server/routes/ogp.ts
> +        return res.status(500).send(ApiResponse.error(`error: ${err}`));
API v1 ではないで、ApiResponse を利用するのはやめよう。

この route はちょっと特殊かもしれない。独自の形式でレスポンスしていいと思う。

2022-01-19 11:15 UTC, yuto-oweseek commented on packages/app/src/server/routes/ogp.ts
> +        return res.status(500).send(ApiResponse.error(`error: ${err}`));
クライアント側に想定されるもの以外（ページが見つからないなど）は、 エラー内容を表示することにしました。

2022-01-19 11:15 UTC, yuto-oweseek commented on packages/app/src/server/routes/ogp.ts
> +        return res.status(500).send(ApiResponse.error(`error: ${err}`));
クライアント側に想定されるもの以外（ページが見つからないなど）は、 エラー内容を表示することにしました。

2022-01-19 11:15 UTC, yuto-oweseek commented on packages/app/src/server/routes/ogp.ts
> +        pageTitle = generatePageTitleFromPagePath(page.path);
`DevidedPagePath` を使用しました。

2022-01-19 11:16 UTC, yuto-oweseek commented on packages/app/src/server/util/user-image-url.ts
> +};
この util は消しました。

2022-01-19 11:16 UTC, yuto-oweseek commented on packages/app/src/server/util/user-image-url.ts
> +};
この util は消しました。

2022-01-19 11:16 UTC, yuto-oweseek commented on packages/app/src/server/util/user-image-url.ts
> +};
この util は消しました。

2022-01-19 11:16 UTC, yuto-oweseek commented on packages/app/src/server/routes/ogp.ts
> +        }
変数に収納しました。

2022-01-19 11:17 UTC, yuto-oweseek commented on packages/app/src/server/routes/ogp.ts
> +        }
else にいきました。

2022-01-19 11:35 UTC, yuki-takei requested changes

2022-01-19 11:35 UTC, yuki-takei commented on packages/app/src/server/routes/ogp.ts
> +  });
20行目の module.exports より上に書いてください。

なぜそれがベターなのかは、node module cache 等で検索。

2022-01-20 06:06 UTC, yuto-oweseek commented on packages/app/src/server/routes/ogp.ts
> +  });
移動しました。

2022-01-20 06:19 UTC, merged