Imprv/85804 add bookmark from pagetree
weseek/growi pull request #5101
Opened 2022-01-17 11:00 UTC by kaoritokashiki

2022-01-17 11:08 UTC, kaoritokashiki commented on packages/app/src/stores/bookmark.ts
> +export const useSWRBookmarkInfo = (pageId: string | null | undefined): SWRResponse<IBookmarkInfo, Error> => {
`useSWRBookmarkInfo(page._id);` にてundefinedがくる可能性があるので、 `undefined`を追加しました。

2022-01-17 11:09 UTC, kaoritokashiki commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  }
もっといい書き方があるような気がしています。

2022-01-18 08:30 UTC, kaoritokashiki commented on packages/app/src/stores/bookmark.ts
> +    pageId != null && isOpen
`pageId != null && isOpen` 条件付きフェッチに isOpenを追加しました。

2022-01-18 13:20 UTC, yuki-takei requested changes

2022-01-18 13:20 UTC, yuki-takei commented on packages/app/src/stores/bookmark.ts
> +export const useSWRBookmarkInfo = (pageId: string | null | undefined, isOpen = true): SWRResponse<IBookmarkInfo, Error> => {
引数の isOpen のデフォルト値は true にしない方がよさそう

2022-01-18 15:57 UTC, merged