WIP: Imprv/79824 85465 legacy page UI 2
weseek/growi pull request #5121
Opened 2022-01-20 05:26 UTC by maow89126

Task: https://redmine.weseek.co.jp/issues/85465

2022-01-21 11:56 UTC, yuki-takei commented on packages/app/src/components/LegacyPage.tsx
> +    return <SearchPageForm keyword={keyword} appContainer={appContainer} onSearchFormChanged={onSearchInvoked} isDisabled></SearchPageForm>;
わざわざ isDisabled: true なフォームを表示する必要はないのでは？

2022-01-21 12:04 UTC, yuki-takei requested changes

2022-01-21 12:04 UTC, yuki-takei commented on packages/app/src/components/SearchCore.tsx
> +  const [excludeTrashPages, setExcludeTrashPages] = useState<boolean>(props.shouldExcludeTrashPages);
この exclude* state は SearchCore で管理されていない(書き換えられたりしていない)ので両方不要。

2022-01-21 12:04 UTC, yuki-takei commented on packages/app/src/components/SearchTypeahead.tsx
> +  isDisabled? : boolean,
不要

2022-01-21 12:04 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchPageForm.jsx
> +  isDisabled: PropTypes.bool,
不要

2022-01-25 06:35 UTC, maow89126 commented on packages/app/src/components/LegacyPage.tsx
> +    return <SearchPageForm keyword={keyword} appContainer={appContainer} onSearchFormChanged={onSearchInvoked} isDisabled></SearchPageForm>;
変更しました。

2022-01-25 06:35 UTC, maow89126 commented on packages/app/src/components/SearchCore.tsx
> +  const [excludeTrashPages, setExcludeTrashPages] = useState<boolean>(props.shouldExcludeTrashPages);
外に出しました。SearchControlの propsたちも整理しました。

2022-02-01 05:50 UTC, closed without merging