[WIP] imprv: Single rename implementation and test code
weseek/growi pull request #5122
Opened 2022-01-20 06:53 UTC by hakumizuki

Redmine(２つ): https://redmine.weseek.co.jp/issues/84909, https://redmine.weseek.co.jp/issues/86024

WIP

## 変更
- 単体の Rename を実装しました
- テストコードも今回の実装箇所分は書きました
- 再帰的な Rename の実装とテストは後続でやります

2022-01-20 10:13 UTC, hakumizuki commented on packages/app/src/server/crowi/index.js
> +import PageService from '../service/page';
import 修正しました

2022-01-20 10:17 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +schema.statics.getParentAndFillAncestors = async function(path: string): Promise<PageDocument> {
もともと ObjectId を返すメソッドでしたが使い勝手が悪かったので PageDocument を返すように書き換えました

2022-01-20 10:19 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +      parentId = parent._id;
getParentAndFillAncestors の改修と同時に改修しました

2022-01-20 10:20 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
v4 なら古いメソッドを実行

2022-01-20 10:22 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
ここで権限のチェックします。子孫は見る必要ないので `const shouldCheckDescendants = false;` としています

2022-01-20 10:23 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    await Page.replaceTargetWithPage(page, pageToReplaceWith);
redirect ページまたはからページでリネームによって空いた場所を埋めています

2022-01-20 10:24 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    const newParent = await Page.getParentAndFillAncestors(newPagePath);
`/A` しかないところに `/A/ ...... /New` を作るときなどには ` ...... ` をからページで埋める必要があるので `const newParent = await Page.getParentAndFillAncestors(newPagePath);` としています

2022-01-20 10:25 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
ここは後続でやります

2022-01-20 10:26 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +schema.statics.replaceTargetEmptyPage = async function(exPage, pageToReplaceWith?): Promise<void> {
単体の Rename, Delete でツリーに穴ができるところを空ページか `pageToReplaceWith` で埋めるメソッドです

2022-01-20 18:33 UTC, yuki-takei requested changes

2022-01-20 18:33 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +schema.statics.createEmptyPage = async function(path: string, parent) {
parent も型指定を

2022-01-20 18:33 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +schema.statics.createEmptyPage = async function(path: string, parent) {
返り値も宣言する

2022-01-20 18:33 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +schema.statics.replaceTargetEmptyPage = async function(exPage, pageToReplaceWith?): Promise<void> {
どこからも使われてないように見える。

2022-01-20 18:33 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +  }
この異常系はどういうケース？
oparations を bulkWrite した後に異常系に遷移させるケースが思い浮かばない。

2022-01-20 18:33 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
>    async renamePage(page, newPagePath, user, options, isRecursively = false) {
v5 の rename は必ず子孫も再起的に処理されるから、isRecursively オプションは不要なんじゃないかな。

2022-01-20 18:33 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +    await Page.replaceTargetWithPage(page, pageToReplaceWith);
redirectTo は廃止することにしたはず。

https://dev.growi.org/616423a731d2966da895a5d6#付随して生まれる仕様変更

この時の議論を忘れてそうだったらもう一度壁打ちしよう。
熟慮した上でこの決定を変えたい場合もやはりもう一度相談をしてほしい。

2022-01-21 00:35 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +  }
確かに bulkWrite した後でした、、必要ないというか無意味なので消しました

2022-01-21 00:37 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
>    async renamePage(page, newPagePath, user, options, isRecursively = false) {
単体も必要かと勘違いしていました。マイグレーションをしないユーザーも rename は再帰のみで行います

2022-01-21 00:50 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +schema.statics.createEmptyPage = async function(path: string, parent) {
この parent の型を指定するには IPage の parent で ObjectId の型を使えるようにする必要があるので、後続で interface 改善をすることになると思います。あと [mongoose doc](https://mongoosejs.com/docs/typescript.html#using-extends-document) を見る限り Document を extends する方法は推奨されていないみたいなので、[単純に IHoge を Schema にジェネリクスとして渡す方法](https://mongoosejs.com/docs/typescript.html#objectids-and-other-mongoose-types) がいいかなと思っています。

2022-01-21 00:50 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +schema.statics.createEmptyPage = async function(path: string, parent) {
返り値の型は改善しました

2022-01-21 00:58 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +schema.statics.replaceTargetEmptyPage = async function(exPage, pageToReplaceWith?): Promise<void> {
改名し損ねてました。`replaceTargetWithPage` に直しました

2022-01-21 12:15 UTC, hakumizuki commented
redirectTo は廃止 => PageRedirectモデル(仮) でリダイレクトは管理することとします。後続は https://redmine.weseek.co.jp/issues/86577 (Slack でシェア済み)

2022-01-21 12:16 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +schema.statics.replaceTargetWithPage = async function(exPage, pageToReplaceWith?): Promise<void> {
こちらのメソッドは rename では使用されなくなりましたが、Delete で使われることになるのでこのまま行きます

2022-01-21 12:19 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +    path: string, parent: any, // TODO: improve type including IPage at https://redmine.weseek.co.jp/issues/86506
こちらはモデルのインターフェイス改善時に any を取り除きます

2022-01-21 12:20 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +schema.statics.replaceTargetWithPage = async function(exPage, pageToReplaceWith?): Promise<void> {
redirectTo が新実装になったことで rename では不要になりましたが、Delete で使うことになるのでこのまま行きます

2022-01-21 12:21 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +  // TODO: rewrite recursive rename
再帰的な rename の本実装は次の PR でされています

2022-01-21 12:22 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +     */
後続で redirectTo を再実装します

2022-01-21 12:28 UTC, merged