[WIP] feat: 85860 Create middleware
weseek/growi pull request #5124
Opened 2022-01-20 09:02 UTC by miya

## Task
[#85860](https://redmine.weseek.co.jp/issues/85860) /page/info が叩かれた時に、/users/update.imageUrlCache を叩く middleware を実装する

2022-01-20 09:39 UTC, miya commented on packages/app/src/server/routes/apiv3/users.js
> +      const users = await User.find({ _id: { $in: userIds }, imageUrlCached: null });
[CommentContainer](https://github.com/weseek/growi/blob/feat/85860-create-middleware/packages/app/src/client/services/CommentContainer.js#L80:L98) のようにフロント側で予め User ドキュメントの `imageUrlCached` の値が取得できている場合以外（imageUrlCached の値をチェックしないで id のみをそのままクエリに含める場合）を想定して、バック側で`imageUrlCached` が null のユーザーを取得できるようにしました。

2022-01-20 18:10 UTC, yuki-takei requested changes

2022-01-20 18:10 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    { use: [checkAndUpdateImageUrlCached] },
`/page/info` が叩かれたタイミングじゃなくて、`/users/list` が叩かれたタイミングだね。
元の PageContainer の仕様と一致させて欲しい。

2022-01-21 10:44 UTC, miya commented on packages/app/src/stores/middlewares/user.ts
> +        .map((user: IUserHasId) => user._id);
`useSWRxUsersList` の middleware として利用する場合 user オブジェクトのデータを取ることができるため、imageUrlCached が null のユーザーでフィルターし、map で id を取得するようにしました。AppContainer の仕様とほぼ同等になっていると思います。

## AppContainer - checkAndUpdateImageUrlCached
https://github.com/weseek/growi/blob/ad27c8ab304abf35c9aae371dcf1f3f6b2c784ea/packages/app/src/client/services/PageContainer.js#L319:L333

2022-01-21 10:44 UTC, miya commented on packages/app/src/stores/page.tsx
> +    { use: [checkAndUpdateImageUrlCached] },
修正しました。

2022-01-21 12:13 UTC, merged