show duplicate modal
weseek/growi pull request #5127
Opened 2022-01-20 11:24 UTC by kaoritokashiki

2022-01-24 04:46 UTC, kaoritokashiki commented on packages/app/src/components/PageDuplicateModal.jsx
> -export default withTranslation()(PageDuplicateModallWrapper);
`useTranslation` の内部で `withTranslation` を使用すると、PageDuplicateModalを使用している部分で、tsエラーが表示されたので
```
<PageDuplicateModal
        isOpen={isPageDuplicateModalShown}
        onClose={() => setIsPageDuplicateModalShown(false)}
        pageId={page._id}
        path={page.path}
      />

```
`PageDuplicateModal.jsx `の内部で使われていた`withTarnslation`を`useTranslation`に変更しました。

2022-01-24 04:48 UTC, kaoritokashiki commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +    );
ここに記述するのが好ましくない場合は、理由を添えて教えていただきたいです。:pray:

2022-01-24 09:43 UTC, yuki-takei requested changes

2022-01-24 09:43 UTC, yuki-takei commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +    );
理由はいくつかある

- 今の実装だと closed 状態の PageDuplicateModal インスタンスが item の数だけ増える
    - 一応条件付きでレンダリングすることにより回避はできるが、それでも state によって PageDuplicateModal が同時に2つオープンになる可能性は排除できない
- atomic design 的に PageItemControl はかなり粒度の小さいコンポーネントなので、Modal を持つのに適さない
    - あるいは責務の観点からも

2022-01-24 09:43 UTC, yuki-takei commented on packages/app/src/components/PageDuplicateModal.jsx
> +  const { t } = useTranslation('');
引数に空文字列渡さなくていいのでは？(渡すとどういう副作用があるのか知らずに書いてるけど)

2022-01-24 09:43 UTC, yuki-takei commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +          {!isEnableActions && (
isEnableActions にあたる条件ってもっと細かくないかな？

https://dev.growi.org/5fabddf8bbeb1a0048bcb9e9

棚卸ししてほしい。
必要なら後続タスクを作る。

2022-01-25 05:21 UTC, kaoritokashiki commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +    );
なるほど!! 理解しました。ありがとうございます

2022-01-26 12:33 UTC, kaoritokashiki commented on packages/app/src/components/PageDuplicateModal.jsx
> +  const { t } = useTranslation('');
これは、コピペしてそのままにしていました。確かにいらないですね。消しますありがとうございます。

2022-01-27 12:35 UTC, yuki-takei requested changes

2022-01-27 12:35 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree.tsx
> +  const [pagePathToDuplicate, setPagePathToDuplicate] = useState('');
この辺の state、PageTree が持っていて ItemsTree に渡してるの必要なのか？って気がする。
Modal を持っているコンポーネントが管理すればいいだけでは？

2022-02-11 13:30 UTC, closed without merging