feat: 86348 create rename operation
weseek/growi pull request #5130
Opened 2022-01-21 08:49 UTC by miya

## Task
[#86348](https://redmine.weseek.co.jp/issues/86348) ページアイテムの三点リーダーdropdownから rename 操作ができる（見た目のみ）

## Appearance
https://user-images.githubusercontent.com/34241526/150494310-06c2e608-11c5-467c-90ef-3025dcba850f.mov

2022-01-21 11:45 UTC, yuki-takei commented
open/close に伴って下側のアイテムの位置が変わるのがいけてないので調整してほしい

2022-01-21 11:49 UTC, yuki-takei requested changes

2022-01-21 11:49 UTC, yuki-takei commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  const renameButtonHandler = () => {
renameButtonClickedHandler にしよう。
useCallback

2022-01-21 11:49 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  onClickRenameButtonHandler?(): void
onClickRenameButton でよい。(もっと言えば他の onClickDeleteButtonHandler とかも…)

2022-01-21 11:49 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  const onClickRenameButton = () => {
こっちは onClickRenameButtonHandler。

2022-01-24 04:52 UTC, miya commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  const renameButtonHandler = () => {
修正しました

2022-01-24 04:53 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  onClickRenameButtonHandler?(): void
`onClickPlusButton`、`onClickDeleteButton`、`onClickRenameButton` に修正しました。

2022-01-24 04:53 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  const onClickRenameButton = () => {
修正しました。

2022-01-24 05:06 UTC, miya commented on packages/app/src/components/Common/ClosableTextInput.tsx
> -        className="form-control my-1"
rename 時の input が開かれたときに上下の高さが変わらないように margin を消しました。

2022-01-24 05:06 UTC, miya commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  onClickRenameButtonHandler?: (pageId: string) => void
メソッド名の命名を統一しました。

2022-01-24 05:06 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  onClickRenameButton?(): void
メソッド名の命名を統一しました。

2022-01-24 09:45 UTC, merged