imprv: Rename descendants
weseek/growi pull request #5136
Opened 2022-01-21 12:37 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/86383

再帰的な rename を v5 向けに実装しました

2022-01-21 12:40 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +      },
このメソッドはまだ使われてないですが修正しました。Delete で使います

2022-01-21 12:41 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/pages.js
> +      body('revisionId').optional().isMongoId().withMessage('revisionId is required'), // required when v4
empty page から rename する際に revisionId 取れないので optional にしました。v4 の場合は route の中でバリデーションしてます

2022-01-21 12:42 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/pages.js
> +    }
v4 の場合には revisionId が必須

2022-01-21 12:45 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +        isGrantNormalized = await this.crowi.pageGrantService.isGrantNormalized(newPagePath, grant, grantedUserIds, grantUserGroupId, shouldCheckDescendants);
間違っていたので修正

2022-01-21 12:48 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +  private async renameDescendants(pages, user, options, oldPagePathPrefix, newPagePathPrefix, isV5Compatible) {
既存の処理を bulkWrite に置き換えて redirectTo に関する処理を消しただけです

2022-01-21 12:52 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +          parentPath = escapeStringRegexp(parentPath);
escapeStringRegexp を使うようにしました。ちなみに _v5RecursiveMigration の改修が混じってしまっているのは、redirectTo ページを作る前提で実装していてその際に _v5RecursiveMigration を使っていたからです。今は使ってないです

2022-01-21 12:52 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +            path: { $regex: new RegExp(`^${parentPath}(\\/[^/]+)\\/?$`, 'gi') },
パスは case insensitive なので i つけました

2022-01-21 19:24 UTC, yuki-takei requested changes

2022-01-21 19:24 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/pages.js
> +      page = await Page.findByIdAndViewer(pageId, req.user, null, true) || await Page.findOne({ _id: pageId });
この行どういうこと？Viewer 無視して取得できてしまう気がする。

2022-01-21 19:24 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +    const isV5Compatible = this.crowi.configManager.getConfig('crowi', 'app:isV5Compatible') && page.parent != null;
`page.parent != null` は、この間話していた「リンクを知っている人のみのページ」の場合に v5 compatible とは見なさない、という条件？
もしそうなのであればそれがわかる一時変数を作って入れて。そうでないのであれば説明を。

2022-01-22 05:27 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/pages.js
> +      page = await Page.findByIdAndViewer(pageId, req.user, null, true) || await Page.findOne({ _id: pageId });
検証用のコードで消し忘れてましたので消しました

2022-01-22 05:29 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    const isV5Compatible = this.crowi.configManager.getConfig('crowi', 'app:isV5Compatible') && page.parent != null;
対象ページがマイグレートされていない場合は v4 の処理をするのでこの条件が必要です。
isPageMigrated という変数に入れました。

2022-01-23 08:20 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
!!ここみて欲しいです!!
rename のターゲットとなるページが Empty ページだった場合は元の親の grant, grantedUsers, grantedGroup を grant のバリデーションに使用するようにしました

2022-01-24 09:18 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +    const isV5Compatible = this.crowi.configManager.getConfig('crowi', 'app:isV5Compatible') && page.parent != null;
「リンクを知っている人のみのページ」と `/` の分岐を明示的に書く

2022-01-24 09:25 UTC, yuki-takei requested changes

2022-01-24 09:25 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +    }
「リンクを知っている人のみのページ」と `/`、それから「migration が済んでいない(parent が null)なページ」のケアって大丈夫かな？

renameDescendantsWithStream 側で
```
    if (!isV5Compatible || !isPageMigrated) {
      return this.renameDescendantsWithStreamV4(targetPage, newPagePath, user, options);
    }
```
となっているからある程度考慮されている気はするけど念のため。

2022-01-24 09:38 UTC, merged