Imprv/duplicate descendants
weseek/growi pull request #5144
Opened 2022-01-24 00:07 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/86388

再帰的な Duplicate を v5 用に改善しました

2022-01-24 12:07 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +            batch, user, options, pathRegExp, newPagePathPrefix, shouldUseV4Process,
targetPage.grant, targetPage.grantedUsers, targetPage.grantedGroup, この部分は redirectPage 用に必要でしたが廃止になったので消しました

2022-01-24 12:08 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +
rename と同じように、`page.isEmpty` が true なら代わりに親ページの grant を `crowi.pageGrantService.isGrantNormalized()` に渡しています

2022-01-24 12:12 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    const pageIdRevisionMapping = {};
revision の path は pageId になったので変更しています

2022-01-24 12:12 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      }
空ページには属性を持たせないようにしてます

2022-01-24 12:15 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +        }
ここで parent をまとめて更新

2022-01-26 06:01 UTC, yuki-takei requested changes

2022-01-26 06:01 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +        const shouldNormalize = page.grant !== Page.GRANT_RESTRICTED && page.grant !== Page.GRANT_SPECIFIED;
この判定は共通化しよう

2022-01-26 07:44 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    return this._v5RecursiveMigration(null, regexps);
改名しました

2022-01-26 07:45 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +        const shouldNormalize = page.grant !== Page.GRANT_RESTRICTED && page.grant !== Page.GRANT_SPECIFIED;
しました

2022-01-26 08:11 UTC, merged