imprv: Delete single page & Delete recursively
weseek/growi pull request #5146
Opened 2022-01-24 02:21 UTC by hakumizuki

Redmine(２つ): https://redmine.weseek.co.jp/issues/84912, https://redmine.weseek.co.jp/issues/86389

ページの単体・再帰的な削除を v5 用に改善しました

## 削除に関する後続
- deleteCompletely の改善

2022-01-26 09:59 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +schema.statics.replaceTargetWithEmptyPage = async function(exPage): Promise<void> {
pageToReplaceWith は必要ないので削除しました

2022-01-26 10:01 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +  }
切り出しました

2022-01-26 10:03 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
単体が対象で、そのページが末端ではない場合はからページでつなぎ直します

2022-01-26 10:04 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
空ページはトラッシュにせず削除します

2022-01-26 10:06 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      deletePageOperations.push(operation);
再帰的な処理も同じで、Empty なら削除、じゃないならトラッシュにします

2022-01-26 20:00 UTC, yuki-takei requested changes

2022-01-26 20:00 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +    }
この処理は delete の本筋の処理が全て成功してからかな。本来的には transaction の対象にしたいものだが、今はスコープ外でよい。

2022-01-27 04:15 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
これ自分のコードがリーダブルじゃなかったです。
`await Page.replaceTargetWithEmptyPage(page);` は単体の Delete の時しか走らないです。else 文の中に入れました

2022-01-27 08:03 UTC, merged