Elm depes on page conatiner
weseek/growi pull request #5156
Opened 2022-01-24 13:04 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/86487
![tag](https://user-images.githubusercontent.com/35527421/150787786-13bf9be8-0899-4ae3-b840-31048af014a1.gif)

2022-01-24 13:32 UTC, Yohei-Shiina commented on packages/app/src/components/Navbar/GrowiSubNavigation.jsx
> +      const { tags } = await apiPost('/tags.update', { pageId, revisionId, tags: newTags });
revisionId がなく tag追加できないバグがあったのでここで修正

2022-01-24 13:34 UTC, Yohei-Shiina commented on packages/app/src/components/Navbar/GrowiSubNavigation.jsx
> +  const isAbleToShowPageAuthors = (isPageExist && !isUserPage);
ここもSWR化した方がよいででしょうか？

2022-01-25 10:29 UTC, Yohei-Shiina commented on packages/app/src/components/Page/TagLabels.tsx
> +import React, { FC, Suspense, useState } from 'react';
無理でした

2022-01-26 01:39 UTC, yuki-takei requested changes

2022-01-26 01:39 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiSubNavigation.jsx
> +  const isAbleToShowPageAuthors = (isPageExist && !isUserPage);
ui.tsx に SWR 化するって指示しなかったっけ？

https://github.com/weseek/growi/tree/support/apply-nextjs

を示した記憶がある。

2022-01-26 13:18 UTC, Yohei-Shiina commented on packages/app/src/components/Navbar/GrowiSubNavigation.jsx
> +  const isAbleToShowPageAuthors = (isPageExist && !isUserPage);
あまり自信ないですが対応しました

2022-01-26 20:42 UTC, yuki-takei requested changes

2022-01-26 20:42 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +};
https://github.com/weseek/growi/tree/support/apply-nextjs
を参考にしてとは言ったものの、今見るとあまり良くないコードにも見える。

## メモ
- isEditorMode はこの値を決めるのに必要なんだろうか？
- isEditorMode が不要だとすると、context からの値だけで決まる訳なので、利用の都度 mutate したくない
- ただ useIsPageExist は将来的に useCurrentPageSWR に変わるわけで、そうすると context からは外れる

2022-01-26 20:42 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +};
ページがない場合(元のコードだと useCurrentPageSWR のデータが null の場合)に対応していないのでNG。
ただし useIsPageExist を使うようになると今度は useIsAbleToShowPageManagement と同じ問題を抱えることになる。

2022-01-26 20:42 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +};
ページがない場合(元のコードだと useCurrentPageSWR のデータが null の場合)に対応していないのでNG。
ただし useIsPageExist を使うようになると今度は useIsAbleToShowPageManagement と同じ問題を抱えることになる。

2022-01-26 20:42 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +};
なぜかこれだけはちゃんと useIsPageExist を使っているのでそこは良さそう。
ただし useIsAbleToShowPageManagement と同じ問題を抱えている。

2022-01-26 20:42 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +};
条件式自体これでいいのかどうか不安。

/資料/外部仕様/クライアント側で可能な操作一覧
https://dev.growi.org/5fabddf8bbeb1a0048bcb9e9

の history を見ると迷走しているが、kaori が詳しそう。

2022-01-31 00:51 UTC, yuki-takei commented
#5200 に引き継いだため close

2022-01-31 00:51 UTC, closed without merging