feat: 85445 SWRize user group detail page
weseek/growi pull request #5165
Opened 2022-01-25 08:58 UTC by miya

## Task
- [#85445](https://redmine.weseek.co.jp/issues/85445) UserGroupDetailPage の SWR化
- [#86808](https://redmine.weseek.co.jp/issues/86808) [Front] UserGroupPage.tsx の mutate の引数を改善する

2022-01-25 09:57 UTC, hakumizuki requested changes

2022-01-25 09:57 UTC, hakumizuki commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  const { data: userGroupRelations, mutate: mutateUserGroupRelations } = useSWRxUserGroupRelationList([userGroup._id]);
`useSWRxUserGroupPages` が新設されているので、apiv3Get(`/user-groups/${userGroup._id}/pages`).then(res => res.data.pages) このエンドポイント用にも SWR 作ったほうがいいかと思います

2022-01-25 09:57 UTC, hakumizuki commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +    mutateUserGroupRelations();
Pages の方の再検証はいらなそうに見えます。元々ありますが ..
あと mutate には shouldRevalidate というパラメーターが渡せるのでそれも考慮した上でお願いします

2022-01-25 09:57 UTC, hakumizuki commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +    mutateUserGroupRelations();
ここも shouldRevalidate のことを考えた方がいいです

2022-01-27 12:30 UTC, yuki-takei requested changes

2022-01-27 12:30 UTC, yuki-takei commented on packages/app/src/stores/user-group.tsx
> +    groupId != null ? [`user-groups/${groupId}/user-group-relations`] : null,
エンドポイント URL は `/` で始めて

2022-01-27 13:20 UTC, merged