feat: 86741 Rename when press enter
weseek/growi pull request #5168
Opened 2022-01-25 12:11 UTC by miya

## Task
[#86741](https://redmine.weseek.co.jp/issues/86741) エンターキーを押した時に rename できる

https://user-images.githubusercontent.com/34241526/150974620-0f14daac-4642-4e5d-b83b-d9fa60cffe8c.mov

2022-01-25 12:15 UTC, miya commented on packages/app/src/components/Common/ClosableTextInput.tsx
> +  const [inputText, setInputText] = useState('');
入力した文字を state で持たせるようにしました。

2022-01-25 12:15 UTC, miya commented on packages/app/src/components/Common/ClosableTextInput.tsx
> +    props.onPressEnter(inputText.trim());
エンターキーを押した時に前後の空白を除去した文字列を入れるようにしました。

2022-01-25 12:15 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    }
空の文字列が渡された時に warning を出しています。

2022-01-25 12:15 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    }
`/` が含まれた文字列が渡された時に warning を出しています。

2022-01-26 01:44 UTC, yuki-takei commented
![image](https://user-images.githubusercontent.com/1638767/151089305-e5c409c3-b6e0-4929-a700-6b193c3d17fd.png)

カウントが張り付いてるの直してほしい

2022-01-26 01:52 UTC, yuki-takei requested changes

2022-01-26 01:52 UTC, yuki-takei commented on packages/app/resource/locales/en_US/translation.json
> +    "cannot_rename_a_title_that_contains_slash": "Cannot rename a title that contains '/'"
`/` が入る名前、VSCode では対応してるんだよね。
なので、「まだ対応していない」という表現にしよう。

2022-01-26 01:52 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      await apiv3Put('pages/rename', { newPagePath, pageId: page._id, revisionId: page.revision });
エンドポイントは `/` から始める (後々プロジェクト内検索しやすくするため)

2022-01-26 01:52 UTC, yuki-takei commented on packages/app/src/components/Common/ClosableTextInput.tsx
> +  const [inputText, setInputText] = useState('');
rename する時は初期値は rename 前の名前である「child」が入らないといけないと思う。

2022-01-26 01:52 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    }
ClosableTextInput の直下にも同じ意味のが出てるよね。どっちかでいいと思っている。
以下ルールで。

- API を叩いてサーバーから返ってきたエラーに関しては toastr を使う
- API を叩く前の validating のようなものは ClosableTextInput の下に出す(toastr は出さない)

2022-01-26 01:52 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    }
API 叩く前後の考慮が足りない。

- API を叩いたら(というか `/pages/rename` を叩く直前で)すぐ ClosableTextInput は見えなくなってよい
    - この時、API の結果待ちになるわけなので、再びリネーム処理はできないようにしないといけない
- API を叩いてエラーだったらリネーム処理前の状態に戻らないといけない
- API を叩いてエラーが出なかったら、再びリネーム処理を受け付けてよい

2022-01-26 08:11 UTC, miya reviewed
挙動が確認できる動画を更新したので、再生お願いします。

2022-01-26 08:11 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    }
API にリクエストする前に `setPageTitle` と `setRenameInputShown` を実行するようにしました。

↓ の順番で実行されると、エンターがおされ input が閉じると以前のタイトルが表示されており、リクエストが成功した段階で新しいタイトルに変わる挙動がいけていないため今回のような順番で実行されるようにしました。

1. setRenameInputShown
1. apiv3Put
1. setPageTitle

つまりエンターが押されたタイミングで input が閉じられ、PageTree のページタイトルは入力されたタイトルに変更されており、rename のリクエストが失敗した時に以前のタイトルに戻るような仕様になっています。

2022-01-26 08:11 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    }
修正しました。

2022-01-26 08:12 UTC, miya commented on packages/app/src/components/Common/ClosableTextInput.tsx
> +  const [inputText, setInputText] = useState('');
input が表示された段階で子ページのタイトルが表示されるようにしました。

2022-01-26 08:12 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    }
修正しました

2022-01-26 08:13 UTC, miya commented on packages/app/resource/locales/en_US/translation.json
> +    "cannot_rename_a_title_that_contains_slash": "Cannot rename a title that contains '/'"
修正しました。

2022-01-26 08:13 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      await apiv3Put('pages/rename', { newPagePath, pageId: page._id, revisionId: page.revision });
すいません、以前にも頂いたFBでした。修正しました。

2022-01-26 09:19 UTC, merged