refs #84709: add test and lint
weseek/growi pull request #5171
Opened 2022-01-26 02:12 UTC by TatsuyaIse

add eslint plugin regex
add eslint rule for regex negative lookahead and positive lookahead.

2022-01-26 09:15 UTC, yuki-takei commented
ci で lint error 出てるままだとマージできない

2022-01-26 09:16 UTC, hakumizuki commented
既に実装されていた後読みの正規表現に関してはエラーハンドリングされているので強制的に lint を無効化して OK です

2022-01-27 12:28 UTC, yuki-takei requested changes

2022-01-27 12:28 UTC, yuki-takei commented on packages/codemirror-textlint/package.json
> +  },
devDependencies  でしょ

2022-01-28 04:00 UTC, TatsuyaIse commented on packages/codemirror-textlint/package.json
> +  },
ライブラリ追加においてどの dependencies にするかを考慮する。という認識が足りてなかったです。
対応しました！

2022-01-28 08:12 UTC, merged