Feat/gw7652 remove emoji auto complete helper
weseek/growi pull request #5173
Opened 2022-01-26 10:03 UTC by mudana-grune

https://youtrack.weseek.co.jp/issue/GW-7652
- Remove implementation of EmojiAutoCompleteHelper

2022-01-28 08:53 UTC, mudana-grune commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +      this.setState({ searchEmojiTimeout: timeout });
This timeout actually aims to detect if the user stops typing at a certain time. If the emoji picker appears instantly, maybe the user can only type 1 letter. Please give me suggestions for this.

2022-02-02 05:02 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +      this.setState({ searchEmojiTimeout: timeout });
なるほどです。
https://user-images.githubusercontent.com/59536731/152095871-a28a0753-0ce9-4d93-b04d-399d45bd9f92.mov

2022-02-02 10:38 UTC, yuki-takei requested changes

2022-02-02 10:38 UTC, yuki-takei commented on packages/app/src/components/PageEditor/EmojiPicker.jsx
> +  }
Convert to a functional component please.

2022-02-02 10:38 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +  }
Transplant to an utility module like EmojiAutoCompleteHelper please.

I think it's better not to write such emoji specific processes to CodeMirrorEditor component.

2022-02-02 10:38 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +      this.setState({ searchEmojiTimeout: timeout });
これは一旦OKです

2022-02-16 09:10 UTC, yuki-takei requested changes

2022-02-16 09:10 UTC, yuki-takei commented on packages/app/resource/locales/ja_JP/translation.json
> +    }
Please fill these value in Japanese with the help of others.

2022-02-16 09:10 UTC, yuki-takei commented on packages/app/resource/locales/zh_CN/translation.json
> +    }
Please fill these value in Chinese. It's enough to use machine translation.

2022-02-16 09:10 UTC, yuki-takei commented on packages/app/src/components/PageEditor/Emoji.jsx
> +export default withTranslation()(Emoji);
- Unify this file with EmojiPicker.jsx
- Convert to TypeScript (tsx)
- Convert to a Functional Component

2022-02-16 09:10 UTC, yuki-takei commented on packages/app/src/components/PageEditor/EmojiPickerHelper.js
> +export default EmojiPickerHelper;
- Convert to TypeScript

2022-02-21 20:03 UTC, merged