feat: Custom readable stream using parent
weseek/growi pull request #5179
Opened 2022-01-26 14:16 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/86890

parent で再帰的に子孫を取得できるようにしました

ReadableStream という形は残したかったので、generator を駆使して実装しました

2022-01-26 15:35 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +  }
なかったので作りました

2022-01-26 15:36 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +// TODO: improve type
any の部分に関しては、mongoose のアップデートか、Model のインターフェイスが改善された後に修正します

2022-01-26 15:45 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    const readStream = Readable.from(iterable);
Iterable から Readable を作っています

2022-01-27 08:14 UTC, yuki-takei requested changes

2022-01-27 08:14 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +class PageOnlyDescendantsIterableFactory {
PageCursorsForDescendantsFactory とかが適切かな。
メソッド名にも何を generate するのかを入れて欲しい。

2022-01-27 08:25 UTC, merged