imprv: Normalize legacy pages parent
weseek/growi pull request #5181
Opened 2022-01-27 06:40 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/84864

単体・複数・再帰で指定されたページのみマイグレーションできるようにしました。

2022-01-28 09:54 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/pages.js
> +        crowi.pageService.v5InitialMigration(Page.GRANT_PUBLIC); // not await
初回のマイグレーションとその後のマイグレーションは route 分けました

2022-01-30 20:48 UTC, yuki-takei requested changes

2022-01-30 20:48 UTC, yuki-takei commented on packages/app/src/server/service/page-grant.ts
> +  async validatePageIdsByIsGrantNormalized(pageIds: ObjectIdLike[]): Promise<[ObjectIdLike[], string[]]> {
このメソッドについて説明がほしい

- 名前の意味がよくわからない
    - validate なのに返り値が boolean や void じゃないあたりも関係している
- 途中に 非同期処理を含む Promise.all があるが、コスト的に問題ないことを説明してほしい

2022-01-30 21:15 UTC, hakumizuki commented
直近の2つの commit (373d84b, 5106eee) 確認お願いします。
- 373d84b
  - `Promise.all` から `for await` を使うようにしました

- 5106eee
  - まず名前の前に返り値が分かりづらかったので変更しました
  - その後名前も変更しました

2022-01-30 21:41 UTC, hakumizuki commented
最新のコミット確認お願いします。一回の find にしました

2022-01-31 00:46 UTC, merged