fix: 86680 fetching child user group error
weseek/growi pull request #5188
Opened 2022-01-27 13:27 UTC by miya

## Task
[#86680](https://redmine.weseek.co.jp/issues/86680) [Front] admin/user-groups を開いた時に fetching child user group list Error となるバグを修正する

2022-01-28 04:01 UTC, miya commented on packages/app/src/server/routes/apiv3/user-group.js
> +    query('parentIds', 'parentIds must be an string').optional().isString(),
parentIds は join された string が入るようにしました。

2022-01-28 04:01 UTC, miya commented on packages/app/src/server/routes/apiv3/user-group.js
> +      }
空の配列を split(',') とすると空の文字列が入るので、filter して消しています。

2022-01-28 04:28 UTC, hakumizuki commented on packages/app/src/stores/user-group.tsx
>        endpoint, { parentIds, includeGrandChildren },
今回は id なので join で OK だと思います。これだけだとサーバーサイド側は配列で届くと勘違いするかもしれないので、`parentIdsJoinedByComma` とかいう名前にしちゃっていいと思います。あと join する理由もコメントでつけておいた方がいいですね

2022-01-28 04:28 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/user-group.js
> +    query('parentIds', 'parentIds must be an string').optional().isString(),
ここも `parentIdsJoinedByComma` 的な名前がいいかなと思います

2022-01-28 08:09 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/user-group.js
> +      }
それをコメントでつけておくといいと思います

2022-01-28 09:21 UTC, miya commented on packages/app/src/server/routes/apiv3/user-group.js
> +      if (parentIdsJoinedByComma != null && parentIdsJoinedByComma !== '') { // null check & trim empty string
null チェック時に空文字かどうかのチェックをするようにしました。

2022-01-28 09:21 UTC, miya commented on packages/app/src/stores/user-group.tsx
> +      endpoint, { parentIdsJoinedByComma: parentIds.join(','), includeGrandChildren },
Axios でリクエストを行う場合、空の配列をクエリに含めてしまうと null になってしまうので string を入れてリクエストするようにしました。

2022-01-28 09:47 UTC, miya commented on packages/app/src/stores/user-group.tsx
>        endpoint, { parentIds, includeGrandChildren },
parentIdsJoinedByComma にリネームしました。

2022-01-30 20:40 UTC, yuki-takei requested changes

2022-01-30 20:40 UTC, yuki-takei commented on packages/app/src/stores/user-group.tsx
> +      endpoint, { parentIdsJoinedByComma: parentIds.join(','), includeGrandChildren },
- parentIds は join で string にせず array で入れるほうが綺麗(string 化はちょっと mad)
- 「空の配列をクエリに含めてしまうと null になってしまうので」については、そもそも parentIds が空だったらこの SWR 動かないようにすれば問題ないんじゃない？
    - shouldFetch はそのようにしようとしているように見える

2022-01-30 20:40 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/user-group.js
> +      }
parentIds が null とか空配列の場合ってこの API 動かす意味ある？ないなら異常系として処理してしまえばいいんじゃないのかな。

2022-01-31 04:18 UTC, miya commented on packages/app/src/stores/user-group.tsx
> +      endpoint, { parentIdsJoinedByComma: parentIds.join(','), includeGrandChildren },
- array を入れるように修正しました
- 確かに shouldFetch が null のときに SWR を動かないようにするためのものでした

2022-02-03 04:28 UTC, yuki-takei requested changes

2022-02-03 04:28 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/user-group.js
> +      }
express-validator に処理を移してください。

2022-02-03 04:53 UTC, merged