78924 85465 new branch legacy page UI 2
weseek/growi pull request #5191
Opened 2022-01-28 02:19 UTC by maow89126

wip

2022-01-28 08:20 UTC, yuki-takei requested changes

2022-01-28 08:20 UTC, yuki-takei commented on packages/app/src/components/SearchCore.tsx
> +  renderLegacyPageControl?: ()=> React.FunctionComponent,
- renderSearchControl 側の返り値が any なのはなぜだ
- props を renderSearchControl, renderLegacyPageControl に分ける必要はなく、どちらのタイプも取れるようにすればよい

2022-01-28 08:20 UTC, yuki-takei commented on packages/app/src/components/SearchCore.tsx
> +  excludeTrashPages : boolean,
exclude* は Control だけが持てばよくて、SearchCore には不要なのでは？(多少自信がないが)

2022-01-28 08:20 UTC, yuki-takei commented on packages/app/src/components/SearchCore.tsx
> +  order : SORT_ORDER,
sort, order も exclude* と同じ気がする。

2022-01-28 08:20 UTC, yuki-takei commented on packages/app/src/components/SearchPage.tsx
> +  const [order, setOrder] = useState<SORT_ORDER>(SORT_ORDER.DESC);
この 4 つは Control が持てばいいだけでは？

2022-02-01 14:35 UTC, maow89126 commented on packages/app/src/components/SearchCore.tsx
> +  renderLegacyPageControl?: ()=> React.FunctionComponent,
なおしました。

2022-02-02 01:45 UTC, maow89126 commented on packages/app/src/components/SearchCore.tsx
> +  excludeTrashPages : boolean,
SearchControlに移しました。

2022-02-02 01:45 UTC, maow89126 commented on packages/app/src/components/SearchCore.tsx
> +  order : SORT_ORDER,
SearchControlに移しました。

2022-02-02 01:45 UTC, maow89126 commented on packages/app/src/components/SearchPage.tsx
> +  const [order, setOrder] = useState<SORT_ORDER>(SORT_ORDER.DESC);
SearchControlに移しました。

2022-02-02 01:54 UTC, maow89126 commented on packages/app/src/components/LegacyPage.tsx
> -// TODO
ここらへんは無視で大丈夫です。

2022-02-03 03:05 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchPageLayout.tsx
> +  Control: React.ReactNode,
React.FunctionComponentとしてうけとると

const {Hoge} = props
return <><Hoge></>のようにあった場合都度あたらしいHoge instanceがrenderされてしまうのでここでは ReactNodeとして同じinstanceのものが上から流れてくるようにしました。

2022-02-03 03:05 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchPageLayout.tsx
> +    SearchResultList, Control, SearchResultContent, searchResultMeta, searchingKeyword, pagingLimit, activePage,
LegacyControlもできたのでControlに改名

2022-02-03 03:05 UTC, maow89126 commented on packages/app/src/components/LegacyPage.tsx
> -  const renderSearchForm = () => {
過去の実装方針のものなのですが無視で大丈夫です

2022-02-03 03:05 UTC, maow89126 commented on packages/app/src/components/LegacyPage.tsx
> -  const renderSortBar = () => {
過去の実装方針のものなのですが無視で大丈夫です

2022-02-03 03:05 UTC, maow89126 commented on packages/app/src/components/SearchCore.tsx
> +        Control={props.renderControl(searchResultCount, selectAllCheckboxType, actionToAllPagesButtonHandler, toggleAllCheckBox, searchingKeyword, onSearchInvoked)}
SearchPageLayoutのほうにもcommentしましたが、

~~~ 
React.FunctionComponentとしてうけとると

const {Hoge} = props
return <></>のようにあった場合都度あたらしいHoge instanceがrenderされてしまうのでここでは ReactNodeとして同じinstanceのものが上から流れてくるようにしました。
~~~

2022-02-03 06:55 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage.tsx
> +  const renderActionToPageModal = useCallback((getSelectedPagesForAction) => {
既存でそうだったのかもしれないんだけど、命名からして何なのか全くわからない

renderActionToPageModal ってPageModal というものがあるみたいに読めるんだけど実態は PageDeleteModal を render するものっぽくて混乱する

2022-02-03 11:52 UTC, Yohei-Shiina commented on packages/app/resource/locales/en_US/translation.json
> +    "legacy_page_alert" : "This is legacy pages",
文法おかしい

2022-02-03 11:55 UTC, Yohei-Shiina commented on packages/app/resource/locales/en_US/translation.json
>    "See_more_detail_on_new_schema": "See more detail on <a href='#'>{{url}}</a> <i class='icon-share-alt'></i> ",
more detail`s` になおしておいてほしい

2022-02-03 12:03 UTC, Yohei-Shiina commented on packages/app/resource/locales/en_US/translation.json
> +    "migrate_help": "You can chose pages by marknig a checkbox and click 'Convert to new schema' above to do so."
`choose`

2022-02-03 12:11 UTC, Yohei-Shiina commented on packages/app/resource/locales/en_US/translation.json
> +    "legacy_page_alert" : "This is legacy pages",
あと legacy pages と言われても正直よくわからないので、 old schema という方がまだいいかなと思った

2022-02-03 12:14 UTC, Yohei-Shiina commented on packages/app/resource/locales/ja_JP/translation.json
> +    "legacy_page_alert" : "旧形式のページです" ,
一方で新スキーマと言いもう一方では旧型式と言ったり統一感がない
旧スキーマとか古いスキーマという言い方にすべきだと思う

2022-02-03 12:18 UTC, Yohei-Shiina commented on packages/app/resource/locales/ja_JP/translation.json
> +    "migrate_help":"チェックボックスでページを選択して画面上部”新スキーマへ変換する”ボタンから新スキーマへ切り替えることが可能です。"
これも、切り替える、変換する、移行する、どれなのか統一したほうがいい

例えばこんな感じ。
新スキーマへ変換するには、対象ページをチェックボックスで選択し、画面上部の ”新スキーマへ変換する” ボタンを選択してください

2022-02-03 12:19 UTC, Yohei-Shiina commented on packages/app/src/components/DuplicatePage.tsx
> +};
この差分はなんでここにあるの？

2022-02-03 12:41 UTC, Yohei-Shiina commented on packages/app/src/components/SearchCore.tsx
>    const [actionTargetPageIds, sestActionToTargetPageIds] = useState<Set<string>>(new Set());
スペルミスしている

2022-02-07 00:22 UTC, maow89126 commented on packages/app/src/components/DuplicatePage.tsx
> +};
コンフリクト解消ミスでした。IdenticalPathPage.tsxに既に存在しているのでこのfileは消しました。

2022-02-07 03:32 UTC, maow89126 commented on packages/app/src/components/SearchPage.tsx
> +  // const [isActionToPageModalShown, setIsActionToPageModalShown] = useState<boolean>(false);
もともとこのタスク始めたときは DeleteModalをswrでglobalにする話がなかったのでこういうかたちになってましたが、dev5 mergeしたら既にdeleteModal globalかの下地がすでに用意されていたので一旦ここではここの実装をコメントアウトしておき
87569で対応します。

2022-02-07 10:35 UTC, yuki-takei requested changes

2022-02-07 10:35 UTC, yuki-takei commented on packages/app/src/components/SearchCore.tsx
> +  excludeUserPages: boolean,
https://github.com/weseek/growi/pull/5191#discussion_r794285460

2022-02-07 10:35 UTC, yuki-takei commented on packages/app/src/components/SearchCore.tsx
> +  renderActionToPageModal?: (pages : string[]) => React.FunctionComponent,
この2ついらない

2022-02-16 11:57 UTC, closed without merging