feat: Page redirect crud
weseek/growi pull request #5197
Opened 2022-01-30 19:23 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/86762

PageRedirect の作成削除を実装しました

2022-01-31 01:58 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      PageRedirect.deleteMany({ $or: [{ toPath: { $in: pagePaths } }] }),
deleteCompletely の時に消したいリダイレクトは、「消えるページの path が toPath の PageRedirect」だと思うのでこうしました

2022-01-31 02:09 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      await PageRedirect.deleteMany({ fromPath: { $in: fromPathsToDelete } });
revert 先は、rename 先と同じく PageRedirect が存在していたら削除します

2022-01-31 02:11 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +
rename のときは、空じゃないページに関しては PageRedirect を作ります
createRedirectPage が false の場合は作りません

2022-01-31 02:12 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +        });
delete のときは createRedirectPage オプションはありません。空ページじゃないなら PageRedirect を作成します

2022-01-31 12:08 UTC, yuki-takei requested changes

2022-01-31 12:08 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +      await PageRedirect.bulkWrite(insertPageRedirectOperations);
こっちは try block 分けなくてもいいような気がする。(要検討)

2022-01-31 12:08 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +      await PageRedirect.deleteMany({ fromPath: { $in: fromPathsToDelete } });
こっちは try block 分けなくてもいいような気がする。(要検討)

2022-02-01 02:24 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      await PageRedirect.bulkWrite(insertPageRedirectOperations);
確かに try を分けた方がほぼ上位互換なので分けました。仮にリネームできていないページの PageRedirect が作成されても、ルートではページが見つかればそれを優先して表示するので

2022-02-01 02:28 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      await PageRedirect.bulkWrite(insertPageRedirectOperations);
PageRedirect を insert する方は分けた方がいいと思うので分けました

2022-02-01 02:32 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      await PageRedirect.deleteMany({ fromPath: { $in: fromPathsToDelete } });
PageRedirect を削除する方は理由は同じで try は同じにしました

2022-02-01 13:12 UTC, merged