imprv: change button position to check tags and refactor tags
weseek/growi pull request #5203
Opened 2022-01-31 06:10 UTC by yuto-oweseek

wip

2022-02-01 13:19 UTC, yuki-takei requested changes

2022-02-01 13:19 UTC, yuki-takei commented on packages/app/src/interfaces/tag.ts
> +}
ITag と同一のものを表しているので統一したい

2022-02-01 13:19 UTC, yuki-takei commented on packages/app/src/interfaces/tag.ts
> +export type ITagDataHasId = ITagData & HasObjectId
状況に応じて特別な property が必要だったり不要だったりするのであれば、HasObjectId のようなものを作って解決する。

2022-02-02 12:20 UTC, yuto-oweseek commented on packages/app/src/interfaces/tag.ts
> +}
`ITag` をベースにして除去&追加をしました。

2022-02-02 12:20 UTC, yuto-oweseek commented on packages/app/src/interfaces/tag.ts
> +export type ITagDataHasId = ITagData & HasObjectId
おｋでした。

2022-02-03 04:34 UTC, merged