Imprv/81351 81439 pt smooth scroll
weseek/growi pull request #5207
Opened 2022-02-01 05:32 UTC by maow89126

TASK : https://redmine.weseek.co.jp/issues/81439

2022-02-01 09:44 UTC, TatsuyaIse commented on packages/app/src/client/util/smooth-scroll.ts
> +  startFrom.scrollTo({
yohei の方でも指摘したけど、 `startFrom` ってなんか違うんだよなぁ、名前的に

2022-02-01 09:44 UTC, TatsuyaIse commented on packages/app/src/client/util/smooth-scroll.ts
> +  startFrom.scrollTo({
あ？何か勘違いしている可能性がある

2022-02-01 09:44 UTC, TatsuyaIse commented on packages/app/src/client/util/smooth-scroll.ts
> +  startFrom.scrollTo({
コチラ要確認 > https://github.com/weseek/growi/pull/5208/files#r796415816

2022-02-01 09:44 UTC, TatsuyaIse commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +  const startFrom = document.getElementById('grw-sidebar-contents-scroll-target');
ココに命名の答えがある気がする。
`grw-sidebar-contents- **scroll-target** `

2022-02-01 09:44 UTC, TatsuyaIse commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +    smoothScrollIntoView(targetElem[0] as HTMLElement, 0, startFrom);
ちょっと気になった程度なんだけど、 `startFrom` の方は
`as HTMLElement` って要らんの？？

2022-02-03 02:33 UTC, maow89126 commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +  const startFrom = document.getElementById('grw-sidebar-contents-scroll-target');
scroll-targetだと上で
const targetElement = element || window.document.body;
もあってどのtargetか紛らわしくなるという理由でyoheiさんと相談してscrollElementに変更しました。

2022-02-03 03:09 UTC, TatsuyaIse approved these changes
tatsuya Approve です。

2022-02-03 05:22 UTC, yuki-takei requested changes

2022-02-03 05:22 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +  }
少なくとも useEffect を使う。

2022-02-08 04:41 UTC, merged