scroll into highlighted word
weseek/growi pull request #5208
Opened 2022-02-01 05:33 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/87211

![scroll](https://user-images.githubusercontent.com/35527421/151917643-c6aee155-3758-4e9a-84a0-764f4b10f09c.gif)

2022-02-01 09:30 UTC, TatsuyaIse reviewed
一通り見てコメントしたけれど、一部適切じゃない指摘もあるかもしれない

2022-02-01 09:30 UTC, TatsuyaIse commented on packages/app/src/client/util/smooth-scroll.ts
> +  startFrom.scrollTo({
startFrom ってスクロールする先の HTMLElement なんだよね？？  
なんだかしっくりこない名前だな。  
 target みたいな名前の方が良さそう。

2022-02-01 09:30 UTC, TatsuyaIse commented on packages/app/src/components/Page/RevisionBody.jsx
> +    }
この辺はちょっと疎い部分なので僕のレビューではスルーします。

2022-02-01 09:30 UTC, TatsuyaIse commented on packages/app/src/components/Page/RevisionLoader.jsx
> +        onRevisionBodyRendered={this.props.onRevisionBodyRendered}
`RevisionBody.jsx` と同じく

2022-02-01 09:30 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +const SCROLL_OFFSET_TOP = 150;
この数値の根拠をコメントに残す

2022-02-01 09:30 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +    if (isRevisionBodyRendered) {
これってどういうからくり、、、？？  
`setIsRevisionBodyRendered(false);` が非同期だから直後の if 文が効いてくるみたいな感じ？？  
そんなこわいコードは許容できないので、フラグのリセットは if 文の下 (処理がおわったあと) に持って行ってください。

2022-02-01 09:30 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  }, [isRevisionBodyRendered]);
`contentRef` もここに入れないとじゃない？？  
そんなことない？？

2022-02-01 09:34 UTC, TatsuyaIse commented on packages/app/src/client/util/smooth-scroll.ts
> +  startFrom.scrollTo({
何か勘違いをしているようだ。

2022-02-01 09:39 UTC, TatsuyaIse commented on packages/app/src/client/util/smooth-scroll.ts
> +  startFrom.scrollTo({
スクロールさせたい対象 (現 startFrom) と、スクロールする先のターゲット要素 (targetElement)  
ということだな。  
であれば、 `scrollElement` とかになるんじゃないかな？とおもう  
少なくとも startFrom という名前ではないということは分かる。

2022-02-01 10:50 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +    if (isRevisionBodyRendered) {
確かにこれはわけわからないことしてました。修正

2022-02-01 10:51 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  }, [isRevisionBodyRendered]);
依存してる値なので必要でしたね

2022-02-02 08:15 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  }, [isRevisionBodyRendered, contentRef]);
`contentRef.current` にしといた方がいいかもしれん。  
それができなければ今のまま `contentRef` でよい。

2022-02-03 14:20 UTC, Yohei-Shiina commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  }, [isRevisionBodyRendered, contentRef]);
対応済

2022-02-04 02:38 UTC, TatsuyaIse requested changes

2022-02-04 02:38 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +        const highlightedWord = searchResultPageContent?.querySelector('.highlighted-keyword') as HTMLElement | null;
`searchResultPageContent?.querySelector` ここの `?` って要らなくない？  
`searchResultPageContent != null` なので、

2022-02-04 02:38 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  }, [isRevisionBodyRendered, contentRef.current]);
そもそも思ったんだけど、 `isRevisionBodyRendered` って、 `setIsRevisionBodyRendered` を RevisionBody までバケツリレーしてガチガチにやる必要あるかい？？    
currentRef.current と、その中身を判別して見ていくっていう if のネストを useEffect の中でやっていってるので、この useEffect のスコープは、むしろ contentRef.current だけでいいような、、、

2022-02-04 02:38 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  }, [isRevisionBodyRendered, contentRef.current]);
ってか、気づいてしまった。  
スムーススクロールするたびに isRevisionBodyRendered ってリセットする必要あるのだろうか？  
スクロールしたところで、リビジョンのボディーはレンダーされているのに、、、  
むしろ isRevisionBodyRendered をこうやってリセット管理することで、余計な副作用が発生することがありそう。

2022-02-04 02:38 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  }, [isRevisionBodyRendered, contentRef.current]);
すごく buggy なコードに見えてきぞ。  
細かい変数であっても、あるべき姿・役割をしっかり考えて実装しよう。

2022-02-04 02:38 UTC, TatsuyaIse commented on packages/app/src/components/Page/RevisionBody.jsx
> +    }
ココは、スルーしてはいけない部分だったということが分かった。

2022-02-04 02:40 UTC, TatsuyaIse commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +      const highlightedWord = searchResultPageContent?.querySelector('.highlighted-keyword') as HTMLElement | null;
前回の反映漏れが今回コメント追加されてしまったので、こちらは resolve しておく

2022-02-08 09:17 UTC, yuki-takei requested changes

2022-02-08 09:17 UTC, yuki-takei commented on packages/app/src/components/Page/RevisionBody.jsx
> +    }
わざわざ RevisionBody の componentDidUpdate を捕捉しなくても、レンダリングされたことを捕捉したいコンポーネントで useEffect とか useRef を使えばいいんじゃないかな

2022-02-09 14:20 UTC, yuki-takei requested changes

2022-02-09 14:20 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  };
pure js は functional component 外に出す

2022-02-09 14:20 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +    const highlightedKeyword = scrollElement.querySelector('.highlighted-keyword') as HTMLElement;
querySelector で最初に出現する1つを取っているという旨をコメントに残してください。

2022-02-09 14:20 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +    const scrollElement = document.querySelector('.search-result-page-content') as HTMLElement;
ここは useRef がいいかな。

2022-02-10 08:28 UTC, yuki-takei requested changes

2022-02-10 08:28 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +    };
observerCallback も functional component の外に出してください。引数とかに型をちゃんと付けて。

2022-02-10 08:28 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  });
第二引数って指定なしで lint error とか出ないっけ？(問題なければOK)

2022-02-10 12:06 UTC, yuki-takei requested changes

2022-02-10 12:06 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  };
react に関連するコードは fc 内に残しましょう

2022-02-10 13:06 UTC, merged