feat: Updating descendant count for delete, deleteCompletely, revert method
weseek/growi pull request #5235
Opened 2022-02-03 13:57 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/87623

Delete, DeleteCompletely, Revert をした時に子孫数を更新できるようにしました

2022-02-03 14:00 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +  const newTarget = pageToReplaceWith == null ? await this.createEmptyPage(exPage.path, parent, exPage.descendantCount) : pageToReplaceWith;
descendantCount も引き継げるようになりました

2022-02-03 14:01 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +};
`parent` のみを使って祖先ページを取ってこれるようにしました

2022-02-04 06:40 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
>    // update descendantCount of all pages that are ancestors of a provided path by count
コメント変えたほうが良いかもですね

2022-02-04 06:44 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
>    // update descendantCount of all pages that are ancestors of a provided path by count
path => pageId に変更しました

2022-02-04 07:05 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +  async updateDescendantCountOfAncestors(pageId: ObjectIdLike, inc: number, shouldIncludeTarget: boolean): Promise<void> {
path だと parent 違いが起こる可能性があるので、pageId で取得するように改善しました

2022-02-04 07:07 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      })();
`revertDeletedDescendantsWithStream` と `updateDescendantCountOfAncestors` だけで考えた時には同期処理にしてます

2022-02-04 07:08 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      })();
この中は同期処理です

2022-02-04 07:09 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +        // TODO https://redmine.weseek.co.jp/issues/87667 : delete leaf empty pages here
後続で末端の空ページを削除します

2022-02-04 07:09 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      })();
この中は同期処理です

2022-02-04 07:10 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +        }
空ページ単体にたいして、completely でない(=トラッシュにする)delete は notfound と同じ扱いにしました

2022-02-04 07:11 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +schema.statics.findAncestorsUsingParentRecursively = async function(pageId: ObjectIdLike, shouldIncludeTarget: boolean) {
parent のみを使って祖先を取得できます

2022-02-04 07:11 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +            $sum: { $cond: { if: { $eq: ['$isEmpty', true] }, then: 0, else: 1 } }, // exclude isEmpty true page from sumOfDocsCount
空ページは子孫数としてカウントしません

2022-02-04 07:11 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +  await this.updateMany({ _id: { $in: pageIds } }, { $inc: { descendantCount: increment } });
１行でできたので書き換えました

2022-02-04 16:35 UTC, yuki-takei requested changes

2022-02-04 16:35 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +            $sum: { $cond: { if: { $eq: ['$isEmpty', true] }, then: 0, else: 1 } }, // exclude isEmpty true page from sumOfDocsCount
読みにくいので適度に改行してください

2022-02-04 16:39 UTC, yuki-takei requested changes

2022-02-04 16:39 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +        // TODO https://redmine.weseek.co.jp/issues/87667 : delete leaf empty pages here
今 isRecursively かどうかの if - else があってその中でよく話をしている「前半部分」「後半部分」をそれぞれ書いているけれど、前後半をまとめた方がよい。なぜなら resume で後半部分だけを実施したいので、後半部分はいずれ独立させることになるから。

…というのをうっすら考えながら実装しましょう。(今リファクタせよということではない)

2022-02-05 07:55 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +        // TODO https://redmine.weseek.co.jp/issues/87667 : delete leaf empty pages here
一旦、 resume できる処理はメソッドの最後の方に持ってきました。細かい設計は後日考えます

2022-02-05 07:55 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +            $sum: { $cond: { if: { $eq: ['$isEmpty', true] }, then: 0, else: 1 } }, // exclude isEmpty true page from sumOfDocsCount
改行しました

2022-02-05 10:33 UTC, merged