open pageDuplicateModal with swr
weseek/growi pull request #5241
Opened 2022-02-04 07:42 UTC by kaoritokashiki

2022-02-04 07:47 UTC, kaoritokashiki commented on packages/app/src/client/base.jsx
> +  'page-delete-modal': <PageDeleteModal />,
typoしていたので修正しました。

2022-02-04 16:53 UTC, yuki-takei requested changes

2022-02-04 16:53 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +  return useSWR(
ここは useSWRImmutable を使ってください。

2022-02-05 07:15 UTC, kaoritokashiki commented on packages/app/src/stores/ui.tsx
> +  return useSWR(
そのように修正しました。

2022-02-05 07:16 UTC, kaoritokashiki commented on packages/app/src/stores/ui.tsx
> +  return useSWRImmutable(
ついでに、deleteのhookにも`useSWRImmutable`を使用しました。

2022-02-05 07:19 UTC, kaoritokashiki commented on packages/app/src/stores/ui.tsx
> +  return useSWRImmutable(
`useSWRImmutable` を使用しています。

2022-02-05 10:32 UTC, yuki-takei approved these changes

2022-02-05 11:35 UTC, merged