feat: ogp
weseek/growi pull request #5242
Opened 2022-02-04 07:58 UTC by yuto-oweseek

## タスク

https://redmine.weseek.co.jp/issues/87012

## 備考

本体側の OGP コードを master へマージ

2022-02-04 17:11 UTC, yuki-takei requested changes

2022-02-04 17:11 UTC, yuki-takei commented on packages/app/src/server/routes/ogp.ts
> +      }
express-validator を使って

2022-02-04 17:11 UTC, yuki-takei commented on packages/app/src/server/routes/ogp.ts
> +        }
ユーザーのイメージ取得部分は別のメソッドに切り出して。

それから `fileUploadService.getIsUploadable()` もチェックする必要がある。

2022-02-04 17:11 UTC, yuki-takei commented on packages/app/src/server/routes/ogp.ts
> +        return res.status(400).send('OGP URI for GROWI has not been setup');
400番台はクライアントが原因という意味になるので違うんだろうなあ。204か500番台か。

2022-02-09 11:27 UTC, yuto-oweseek commented on packages/app/src/server/routes/ogp.ts
> +      }
DONE

https://github.com/weseek/growi/pull/5291

2022-02-09 11:27 UTC, yuto-oweseek commented on packages/app/src/server/routes/ogp.ts
> +        }
DONE  ↓の middleware

https://github.com/weseek/growi/pull/5291

2022-02-17 12:47 UTC, yuki-takei requested changes

2022-02-17 12:47 UTC, yuki-takei commented on packages/app/src/server/views/layout-growi/page.html
> +{% endblock %}
https://github.com/weseek/growi/issues/5367
の問題を修正する必要がある。

2022-05-20 10:57 UTC, closed without merging