feat: 87568 Use SWR to display delete modal
weseek/growi pull request #5247
Opened 2022-02-04 10:36 UTC by miya

## Task
[#87568](https://redmine.weseek.co.jp/issues/87568) [ItemsTree] SWRを使用してModalを表示させる

2022-02-04 11:02 UTC, miya commented on packages/app/src/client/base.jsx
> +  'page-delete-modal': <PageDeleteModal />,
typo していたので修正しました

2022-02-04 11:02 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +  };
ここで削除モーダルをオープンさせています。

2022-02-04 17:23 UTC, yuki-takei requested changes

2022-02-04 17:23 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree.tsx
> +  };
これ今表示してるページ固定になるよね

2022-02-05 00:54 UTC, miya commented on packages/app/src/components/Sidebar/PageTree.tsx
> +  };
誤解していました。delete item がクリックされたページのモーダルを開くように修正しました。

2022-02-05 10:27 UTC, merged