Imprv/87696 show PageDuplicateModal when clicking DuplicateMenuItem
weseek/growi pull request #5251
Opened 2022-02-05 08:49 UTC by kaoritokashiki

2022-02-05 09:44 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  }, [onClickDuplicateMenuItem, page]);
`pageId` と `path`のセットは、Item Componentにて行っています。

2022-02-05 15:13 UTC, yuki-takei requested changes

2022-02-05 15:13 UTC, yuki-takei commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  if (pageId == null || path == null) {
path は不要

2022-02-06 15:21 UTC, kaoritokashiki commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  if (pageId == null || path == null) {
すみません、削除しました。

2022-02-06 15:43 UTC, kaoritokashiki commented on packages/app/src/components/PageList/PageList.tsx
> +    <PageListItemL key={page.pageData._id} page={page} isEnableActions={isEnableActions} />
コンフリクト解消に加え、
PageListを表示した際に出ていた `each child should have a unique key` のwarningを解消しました。

2022-02-06 15:52 UTC, merged