update descendant count on duplication
weseek/growi pull request #5252
Opened 2022-02-05 09:05 UTC by Yohei-Shiina

2022-02-05 09:31 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +    }
この null check はこのメソッドの一番最初にやるべきですね

2022-02-05 09:34 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    })();
`if (isRecursively) {` が `(async() => {})()` の外にあった方が読みやすそうですね。あと、ここの部分の処理は今後追加される「再開(resume)」の機能のことを考えると、`async duplicate()` の return の直前くらいにあった方がいいです

2022-02-05 10:16 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
この部分をメソッドの一番下の方に持ってきておいていただけると後日楽なのでお願いします

2022-02-07 00:23 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +          nNonEmptyDuplicatedPages += (batch.filter(page => !page.isEmpty)).length;
`(batch.filter(page => !page.isEmpty))` の外の `()` はなくてもいいかなと思います

2022-02-07 00:30 UTC, hakumizuki commented
現状、ページが末端に作成された場合の子孫数カウントのみ実装されているのですが、実はもう１パターンあります。それは、`/A/Empty/B` の Empty の部分に作成する場合で、この場合は自身の descendantCount に子の descendantCount を入れる必要があります。ので、こちらの実装を追加でお願いします！

2022-02-07 11:50 UTC, yuki-takei requested changes

2022-02-07 12:14 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +  }
現状では対応不要になった

2022-02-07 12:15 UTC, merged