show rename modal
weseek/growi pull request #5259
Opened 2022-02-06 19:12 UTC by kaoritokashiki

2022-02-06 19:23 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  // }, []);
このコメントアウトされた部分は、input formを表示するためのものです。
将来的にinputformからのrenameができるようにするとのことなので、現時点ではコメントアウトをしておきました。

2022-02-06 19:32 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  // }, []);
https://redmine.weseek.co.jp/issues/87757
バックログにそれ用のストーリーを作成しています。

2022-02-07 06:57 UTC, yuki-takei requested changes

2022-02-07 06:57 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +    onClickRenameMenuItem?: (pageId: string, reevisionId: string, path: string) => void,
IPageForPageDeleteModal もばらしたほうがいいかも。(このタスクのスコープではないが)

2022-02-07 06:57 UTC, yuki-takei commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  onClickRenameMenuItem?: () => Promise<void> | void,
引数はそのままにする(今回使わないとしても)

2022-02-07 07:06 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +    onClickRenameMenuItem?: (pageId: string, reevisionId: string, path: string) => void,
リファクタ用の後続タスク作成します。

2022-02-07 07:45 UTC, kaoritokashiki commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  onClickRenameMenuItem?: () => Promise<void> | void,
承知です。そのように修正しました。

2022-02-07 08:10 UTC, merged