feat: 86349 Delete operation from the delete modal
weseek/growi pull request #5261
Opened 2022-02-07 02:39 UTC by miya

## Task
[#86349](https://redmine.weseek.co.jp/issues/86349) モーダルで削除ボタンを押してdelete操作をする

2022-02-07 03:56 UTC, miya commented on packages/app/src/components/PageDeleteModal.tsx
> +        const result = await apiPost('/pages.removeMany', {
現状 pages を受け取るエンドポイント（/pages.removeMany）が存在しないので、TODO を書きました。

2022-02-07 03:56 UTC, miya commented on packages/app/src/components/PageDeleteModal.tsx
> +        const result = await apiPost('/pages.removeMany', {
現状 pages を受け取るエンドポイント（/pages.removeMany）が存在しないので、TODO を書きました。

2022-02-07 03:56 UTC, miya commented on packages/app/src/components/PageDeleteModal.tsx
> -  isOpen: boolean,
使用されていない props だったので削除しました。

2022-02-07 10:14 UTC, yuki-takei requested changes

2022-02-07 10:14 UTC, yuki-takei commented on packages/app/src/components/PageDeleteModal.tsx
> +        window.location.href = encodeURI(trashPagePath);
ページ遷移はモーダルの責務ではない

2022-02-07 10:14 UTC, yuki-takei commented on packages/app/src/server/routes/page.js
> +    body('recursively').optional().custom(v => v === 'true' || v === true || v === null).withMessage('The body property "recursively" must be "true" or true.'),
- そもそも optional() で undefined を許容するはず
    - クライアント側で undefined にしたほうがよいのでは？

2022-02-07 15:24 UTC, miya commented on packages/app/src/server/routes/page.js
> +    body('recursively').optional().custom(v => v === 'true' || v === true || v === null).withMessage('The body property "recursively" must be "true" or true.'),
確かに、クライアント側で、true か undefined になるようにしました

2022-02-08 04:37 UTC, miya commented on packages/app/src/components/PageDeleteModal.tsx
> +        window.location.href = encodeURI(trashPagePath);
昨夜アドバイス頂いたように修正しました。
https://wsgrowi.slack.com/archives/C02JG9U7NNQ/p1644206241763439

2022-02-08 07:09 UTC, yuki-takei requested changes

2022-02-08 07:09 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +export const usePageDeleteModalOpened = (): SWRResponse<(DeleteModalOpened | null), Error> => {
この SWR いらない気がしてきたな…
usePageDeleteModalStatus を usePageDeleteModal という名前にすればいいような。

2022-02-08 09:05 UTC, miya commented on packages/app/src/stores/ui.tsx
> +export const usePageDeleteModalOpened = (): SWRResponse<(DeleteModalOpened | null), Error> => {
リネームしました。

2022-02-08 09:28 UTC, merged