feat: 87839 Go to edit page after pressing enter key
weseek/growi pull request #5265
Opened 2022-02-07 12:37 UTC by miya

## Tsak
[#87839](https://redmine.weseek.co.jp/issues/87839) + ボタン押してインプットを表示させた後、エンターを押すことでページ作成画面に遷移できる

2022-02-07 13:23 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  };
エディットページ用の path の生成と遷移を行います。

2022-02-07 13:23 UTC, miya commented on packages/app/src/components/Common/ClosableTextInput.tsx
> +    alertInfo == null ? setCanKeyDownHandler(true) : setCanKeyDownHandler(false);
若干 ClosableTextInput の汎用性が落ちますが、バリデーションで warning が出ている場合はエンターキーを押しても `onPressEnter()` が実行されないようにしました。

2022-02-08 02:58 UTC, miya commented on packages/app/src/components/Common/ClosableTextInput.tsx
> +  };
フォーカス時にもバリデーションを効かせるためにこのように改修しました。

2022-02-08 02:58 UTC, miya commented on packages/app/src/components/Common/ClosableTextInput.tsx
> +      onPressEnter();
バリデーションに引っかかっている時に onPressEnter を実行させないようにしました。

2022-02-08 02:58 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    // TODO: https://redmine.weseek.co.jp/issues/87943
87943 で ページ作成の為のエンドポイントの作成及び、エンドポイントを叩いてページ作成できるようにしようと思います。

2022-02-08 02:58 UTC, miya commented on packages/app/src/components/Common/ClosableTextInput.tsx
> +    alertInfo == null ? setCanKeyDownHandler(true) : setCanKeyDownHandler(false);
修正しました。

2022-02-08 02:59 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  };
作成できるようにしようと思っています。

2022-02-08 03:00 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  };
既存コードで代替しました。

2022-02-08 07:00 UTC, yuki-takei requested changes

2022-02-08 07:00 UTC, yuki-takei commented on packages/app/src/components/Common/ClosableTextInput.tsx
> +  };
「バリデーションを行う」名前のメソッドを呼ぼう。

2022-02-08 07:45 UTC, merged