show delete modal
weseek/growi pull request #5267
Opened 2022-02-07 16:54 UTC by kaoritokashiki

2022-02-07 17:29 UTC, kaoritokashiki commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  }, [openDeleteModal]);
SearchResultContent コンポーネントにて `openDeleteModal` を実行しています。

2022-02-07 17:32 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +    }
`pageId` と `revisionId` は確実にstringで渡ってくるので、ここでは、pathのみのnull checkをしています。

2022-02-07 21:53 UTC, yuki-takei requested changes

2022-02-07 21:53 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +      onClickDeleteMenuItem={deleteItemClickedHandler}
冗長。props の onClickDeleteMenuItem をそのまま渡せばよい。

2022-02-07 21:53 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +    }
path が null なら何もしなくてよい。(91 行目の条件に追加すればOK)

2022-02-09 11:09 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +      onClickDeleteMenuItem={deleteItemClickedHandler}
理解いたしました。ありがとうございます!

2022-02-09 11:09 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +    }
承知です。そのように修正しました。

2022-02-09 11:12 UTC, merged