Imprv/87816 show presentation modal
weseek/growi pull request #5270
Opened 2022-02-07 21:08 UTC by kaoritokashiki

2022-02-07 21:49 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +    }
現在の最新のマスターブランチを見てみると、currentUserがnull の時にはnullを返していたのですが、null じゃなくて何も返さないように変更しました。(もし認識違いあったら教えてください。)

2022-02-07 21:51 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +      // TODO: show template modal by https://redmine.weseek.co.jp/issues/87815
後続タスクにて「テンプレートモーダル」もこちらに追加する予定です。

2022-02-07 21:58 UTC, yuki-takei requested changes

2022-02-07 21:58 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +      // TODO: show template modal by https://redmine.weseek.co.jp/issues/87815
テンプレートを選ぶモーダルはここに追加してもいい。
PagePresentationModal はここではないと思う。一旦グローバルな存在にするのがいいかなあ。

2022-02-10 01:57 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const { open: openAccessoriesModal } = usePageAccessoriesModal();
ついでに`PageAccessoriesModal` のmethod open を `openAccessoriesModal`に変更しました。

2022-02-10 01:59 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +      // TODO: show template modal by https://redmine.weseek.co.jp/issues/87815
PagePresentationModal をグローバル化しました。

2022-02-10 08:19 UTC, yuki-takei requested changes

2022-02-10 08:19 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +};
usePagePresentationModalOpened は消して、usePagePresentationModalStatus を usePagePresentationModal にしてください。他のモーダル関連の SWR もそういう使い方統一でいいと思う。

2022-02-10 11:35 UTC, kaoritokashiki commented on packages/app/src/stores/ui.tsx
> +};
他全てのModal関連は、以下のタスクにて一気に行います。(見通しにいれています。)
https://redmine.weseek.co.jp/issues/88215

2022-02-10 11:41 UTC, merged