Imprv: 85777 87756 rename modal with swr
weseek/growi pull request #5281
Opened 2022-02-08 10:28 UTC by maow89126

2022-02-09 04:20 UTC, kaoritokashiki requested changes

2022-02-09 04:20 UTC, kaoritokashiki commented on packages/app/src/components/PageList/PageListItemL.tsx
> +
1. method名を統一させたいので、`renameMenuItemClickHandler` としてください。

2. openRenameModalの処理の前に以下のように宣言すると、引数に渡す値が綺麗になると思います
```
const { _id: pageId, revision: revisionId, path } = pageData;
````

2022-02-09 04:21 UTC, kaoritokashiki commented
マージ先が`master`になってしまっているので、`dev/5.0.x`に変更お願いします...!!

2022-02-10 02:38 UTC, maow89126 commented on packages/app/src/components/PageList/PageListItemL.tsx
> +
あざます。
２つとも直しました。
2こめのobject destructuring って変数の名前変えることも可能だったのですね。学びました。

2022-02-10 02:50 UTC, maow89126 commented
"コンフリクト解消お願いします"とありましたが、github上でも確認できずmasterをmergeしてきてもコンフリクトなかったので、
結論コンフリクトしてなかったみたいです。

2022-02-10 04:22 UTC, kaoritokashiki approved these changes

2022-02-10 04:25 UTC, merged