imprv: add ogp middleware
weseek/growi pull request #5291
Opened 2022-02-09 10:33 UTC by yuto-oweseek

## タスク

## 行ったこと
- このPR ( https://github.com/weseek/growi/pull/5242 ) の FB 対応をしました

## お願いします

- この PR が feat/ogp にマージされた場合に、feat/ogp → master へのマージ依頼内容の確認
    - 問題なければ、 master へマージお願いします
    - まだ問題がありそうでしたら、FB ください

2022-02-09 11:59 UTC, yuki-takei requested changes

2022-02-09 11:59 UTC, yuki-takei commented on packages/app/src/server/middlewares/ogp-validator.ts
> +};
関連なので、routes/ogp.ts 内に定義してください。

2022-02-10 06:37 UTC, yuto-oweseek commented on packages/app/src/server/routes/ogp.ts
> +        const page = await Page.findByIdAndViewer(req.params.pageId);
renderOgp 側にあった、` const page = await Page.findByIdAndViewer(req.params.pageId);` を ogpValidator 側に移動しました。

- 理由
    - validation を行って、request をはじくのは validator 側にまとめたほうがコードがスッキリとするため
    - また、 validator 内で `req.body.page = page;` を行うのは若干責務外に思えたんですが、`Page.findByIdAndViewer(req.params.pageId)` を renderOgp 側でも行うのは効率が悪いため validator 内で行うことにしました

2022-02-10 06:40 UTC, yuto-oweseek commented on packages/app/src/server/middlewares/ogp-validator.ts
> +};
:octocat: 🆗 です

2022-02-10 10:36 UTC, merged