[WIP] feat: 87970 List child groups
weseek/growi pull request #5295
Opened 2022-02-10 03:28 UTC by miya

## Task
[#87970](https://redmine.weseek.co.jp/issues/87970) 詳細画面で子グループを一覧表示できる

2022-02-11 17:25 UTC, miya commented on packages/app/src/stores/user-group.tsx
>    );
孫ユーザーグループも取得できるようにしました。

2022-02-11 17:25 UTC, miya commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +            isAclEnabled
`isAclEnabled` が現状機能していない（必ず true を返すようになっている）のでひとまず true を入れています。

## 参考
https://github.com/weseek/growi/blob/59fddae01963c14ddf61d0513ef3c352478316e6/packages/app/src/server/service/acl.js#L25:L29

2022-02-11 17:25 UTC, miya commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +        forceUpdateParents: true, //  TODO 87748: Make forceUpdateParents optionally selectable
現状 `forceUpdateParents` を true にしていないと子供を追加できないのでこのようにしました。

2022-02-11 17:25 UTC, miya commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> -import AppContainer from '~/client/services/AppContainer';
omit unstated

2022-02-14 02:50 UTC, miya commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +            isAclEnabled
バックログに作成しました。
https://redmine.weseek.co.jp/issues/88287

2022-02-14 02:51 UTC, miya commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +        forceUpdateParents: true, //  TODO 87748: Make forceUpdateParents optionally selectable
false に戻しました。
今のところ下記以外でのバグは観測していません。
> ユーザーが全くいないときに false だと動かない感じですかね

2022-02-14 02:51 UTC, miya commented on packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
> +  const childUserGroups = childUserGroupsList != null ? childUserGroupsList.childUserGroups : [];
修正しました。

2022-02-14 02:52 UTC, miya commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  const deleteUserGroupById = useCallback(async(deleteGroupId: string, actionName: string, transferToUserGroupId: string) => {
修正しました。

2022-02-14 02:52 UTC, miya commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  }, [mutateChildUserGroups]);
修正しました。

2022-02-14 02:53 UTC, miya commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  }, []);
修正しました。

2022-02-14 04:54 UTC, miya commented on packages/app/src/server/service/user-group.ts
> +    const usersBelongsToTargetButNotParent = excludeTestIdsFromTargetIds(targetGroupUsers, parentGroupUsers);
targetGroupUsers から parentGroupUsers に含まれているユーザーを除外する処理ですが、id が取得できず正常に動作しないバグがあったので修正しました。

2022-02-14 05:41 UTC, miya commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  const childUserGroupRelations = userGroupRelationList != null ? userGroupRelationList : [];
使用する SWR が間違っていたため修正しました。
useSWRxUserGroupRelations  --> useSWRxUserGroupRelationList

2022-02-14 18:49 UTC, yuki-takei commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +            isAclEnabled
問題ない気がする。acl.test.js を読んで、改修が本当に必要かどうか確認を。

2022-02-15 09:33 UTC, yuki-takei requested changes

2022-02-15 09:33 UTC, yuki-takei commented on packages/app/src/server/views/admin/user-group-detail.html
> +</div>
swig に寄せてもいいことはない。
整頓するならちゃんとやる。

ContextExtractor に寄せて、actions.userGroup.index からも消す。

2022-02-15 10:41 UTC, miya commented on packages/app/src/client/admin.jsx
> +}
admin ページでも ContextExtractor を使えるようにしました。

2022-02-15 10:41 UTC, miya commented on packages/app/src/client/services/ContextExtractor.tsx
> +  useIsAclEnabled(adminSettings?.isAclEnabled);
dom から isAclEnabled を取得して SWR で fetch できるようにしました。

2022-02-15 10:41 UTC, miya commented on packages/app/src/server/routes/admin.js
> -      isAclEnabled,
不要なコードを消しました。

2022-02-15 12:52 UTC, merged