feat: 87943 Create page from PageTree
weseek/growi pull request #5298
Opened 2022-02-10 05:51 UTC by miya

## Task
- [#87943](https://redmine.weseek.co.jp/issues/87943)[Front] + ボタンを押してインプットを表示させた後、エンターを押すとこでページを保存できる
- [#88052](https://redmine.weseek.co.jp/issues/88052) [Front] ClosableTextInput.tsx で input に文字を入力した時に出る uncontrolled input of type text to be controlled という warning を解消する

2022-02-10 06:00 UTC, miya commented on packages/app/src/components/Common/ClosableTextInput.tsx
> +        value={inputText || ''}
[#88052](https://redmine.weseek.co.jp/issues/88052) ClosableTextInput.tsx で input に文字を入力した時に出る uncontrolled input of type text to be controlled という warning を解消する

2022-02-10 10:33 UTC, yuki-takei requested changes

2022-02-10 10:33 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    const initialBody = `# ${newPagePath}`;
initialBody は固定値ではなく、管理画面に関係する設定があるのでそちらを読む必要がある。
クライアント側で決めるかサーバー側で決めるかはどちらでもよい。

2022-02-10 13:12 UTC, miya commented on packages/app/src/server/routes/apiv3/pages.js
> +      grant, grantUserGroupId, overwriteScopesOfDescendants, isSlackEnabled, slackChannels, pageTags, createFromPageTree,
`createFromPageTree` という boolean を受け取れるようにしました。名前が微妙だと思うので、ここはアドバイスをいただきたいです。

2022-02-10 13:12 UTC, miya commented on packages/app/src/server/routes/apiv3/pages.js
> +    }
isEnabledAttachTitleHeade が true かつ createFromPageTree が true だった時にページパスをヘッダーにした body をあらかじめ保存できるようにしました。

2022-02-10 13:12 UTC, miya commented on packages/app/src/server/routes/page.js
> +    const pageBody = (typeof (req.body.body) === 'string' || req.body.body instanceof String) ? req.body.body : null;
ページを更新する際に空文字列を許容できるようにしました。

2022-02-10 13:12 UTC, miya commented on packages/app/src/server/models/revision.js
> -      required: true,
空文字列を許容できるようにしました。

2022-02-10 13:51 UTC, yuki-takei requested changes

2022-02-10 13:57 UTC, miya commented on packages/app/src/server/routes/page.js
> +    const pageBody = (typeof (req.body.body) === 'string' || req.body.body instanceof String) ? req.body.body : null;
修正しました。

2022-02-10 13:58 UTC, miya commented on packages/app/src/server/models/revision.js
> -      required: true,
すいません、バリデーションで null をしていなかったためエラーが出ていました。
required: true でも空文字列を入れることができました 🙌

2022-02-11 09:13 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    }
app.jsx からバケツリレーしてきた appContainer.getConfig を使って `isEnabledAttachTitleHeader` の boolean を取得しています。

2022-02-11 09:13 UTC, miya commented on packages/app/src/server/models/revision.js
> +  mongoose.Schema.Types.String.checkRequired(v => v != null);
not nullable かつ 空の文字列を許容

## 参考
https://mongoosejs.com/docs/api/schematype.html#schematype_SchemaType-checkRequired

2022-02-11 09:13 UTC, miya commented on packages/core/src/utils/path-utils.js
> +}
ヘッダー付きのパスを返すための処理を共通化

2022-02-11 09:13 UTC, miya commented on packages/app/src/server/util/swigFunctions.js
> +  };
not_found_content.html で使用

2022-02-11 09:13 UTC, miya commented on packages/app/src/server/views/widget/not_found_content.html
>      {% endif %}
isEnabledAttachTitleHeader が true の時に [PageContainer の initStateMarkdown](https://github.com/weseek/growi/blob/feat/87943-create-page-from-page-tree/packages/app/src/client/services/PageContainer.js#L167:L177) で raw-text-original の値を取得している

2022-02-11 22:11 UTC, yuki-takei requested changes

2022-02-11 22:11 UTC, yuki-takei commented on packages/app/src/components/Sidebar.tsx
> +}
悪いんだけどサイドバー関連を AppContainer で汚染させたくはないので、このバケツリレーはNGとします。

2022-02-11 22:11 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    }
この config の値自体をまず context.tsx でやっているような SWR 管理 にする必要がある。

2022-02-11 22:11 UTC, yuki-takei commented on packages/app/src/server/views/widget/not_found_content.html
>      {% endif %}
if template が true になる方、書き換え間違えてると思う

2022-02-12 03:57 UTC, miya commented on packages/app/src/server/views/widget/not_found_content.html
>      {% endif %}
`#` が消えてなかったですね... 修正しました。

2022-02-12 03:58 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    }
修正しました。

2022-02-12 19:23 UTC, yuki-takei approved these changes

2022-02-14 02:43 UTC, merged