imprv: show delete modal in PageListItemLwith swr
weseek/growi pull request #5299
Opened 2022-02-10 08:43 UTC by maow89126

PR: https://redmine.weseek.co.jp/issues/88175

2022-02-10 09:09 UTC, kaoritokashiki requested changes

2022-02-10 09:09 UTC, kaoritokashiki commented on packages/app/src/components/PageList/PageListItemL.tsx
> -                  onClickDeleteMenuItem={props.onClickDeleteButton}
これは、元のコードの残骸で、
`PageListItemL`を持つ親コンポーネントたちにpropsが渡されてしまっているので、その該当部分を消す必要がありますね。

【一例】
- `SearchResultList`
    -  `SearchPage`


その結果、SearchPage.jsxに置かれているdeleteModalのインスタンスは削除する必要があります。
```
<PageDeleteModal
          isOpen={this.state.isDeleteConfirmModalShown}
          onClose={this.closeDeleteConfirmModalHandler}
          pages={this.getSelectedPagesToDelete()}
        />
```

2022-02-13 07:58 UTC, maow89126 commented on packages/app/src/components/PageList/PageListItemL.tsx
> -                  onClickDeleteMenuItem={props.onClickDeleteButton}
onClickDeleteButtonのみたらSearchResultListのみでした。

あとSearchPageでは一応 actionToAllPage(一括削除の方）がまだ残っているのでPageDeleteModalもけしていないです。
85465の方でけすrefactorしてます。（現在武井さん巻取りになりましたが、)

2022-02-13 07:58 UTC, maow89126 commented on packages/app/src/components/SearchPage.jsx
> +        {/* TODO: show PageDeleteModal with usePageDeleteModal for delete all pages 85465 */}
comment 変更

2022-02-14 04:43 UTC, kaoritokashiki approved these changes

2022-02-15 03:33 UTC, maow89126 commented on packages/app/src/components/IdenticalPathPage.tsx
> -                // Todo: add onClickDeleteButton when delete feature implemented
PageListItemLにdeleteHandler的なもの渡す必要ないのでコメント消し。

2022-02-15 03:33 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultList.tsx
> -  const clickDeleteButtonHandler = useCallback((pageId: string) => {
同じくPageListItemLにわたす必要ないのでけし。

2022-02-15 03:33 UTC, maow89126 commented on packages/app/src/components/SearchPage/SearchResultList.tsx
>              isSelected={page.pageData._id === selectedPageId}
このisEnableActions={isGuestUser}っ　[ここで書かれた](https://github.com/weseek/growi/pull/5315/files#diff-6ff47e539b0418480ebd22ea8c2294fa7258667a0d36f56d89f7907bf93b00a7R93)ようなのですがあってますか？

意図的に3点ボタン一旦非表示にするために入れた感じですか？

2022-02-15 09:14 UTC, merged