Imprv: 87936 switch page delete modal
weseek/growi pull request #5307
Opened 2022-02-11 21:45 UTC by kaoritokashiki

2022-02-11 21:50 UTC, kaoritokashiki commented on packages/app/src/stores/modal.tsx
> +  isDeleteCompletelyModal?: boolean,
`isAbleToDeleteCompletely`と `isDeleteCompletelyModal` を追加してます

2022-02-11 22:27 UTC, yuki-takei requested changes

2022-02-11 22:27 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> -  };
実装者の増山くんと相談してください。

2022-02-11 22:27 UTC, yuki-takei commented on packages/app/src/components/PageDeleteModal.tsx
> +  const isDeleteCompletelyModal = deleteModalData?.isDeleteCompletelyModal != null ? deleteModalData.isDeleteCompletelyModal : false;
書き方が冗長

2022-02-11 22:27 UTC, yuki-takei commented on packages/app/src/stores/modal.tsx
> +  isDeleteCompletelyModal?: boolean,
isDeleteCompletelyModal ってなんだっけ？

isAbleToDeleteCompletely の方はページ毎に決まってるわけだから、IPageForPageDeleteModal に入れるんじゃないかな。
複数ページが渡された場合、UI としては「全てのページで完全削除が可能か？」という判定を行って、可能であればチェックボックスを有効化する。

2022-02-14 05:01 UTC, kaoritokashiki commented on packages/app/src/stores/modal.tsx
> +  isDeleteCompletelyModal?: boolean,
## 通常のdeleteModal
完全削除にチェックを入れるか入れないかでmodalが切り替わります

https://user-images.githubusercontent.com/59536731/153802589-0218d360-86da-4506-9d1f-94d5f5fc2243.mov

- TrashPage
完全削除のモーダルのみが開きます
<img width="1362" alt="Screen Shot 2022-02-14 at 13 57 29" src="https://user-images.githubusercontent.com/59536731/153802670-8efc5a85-76e1-41f4-ba91-1b5c67a68f9f.png">

つまり、trashPageAlertでPageDeleteModalを開く際にpropsに`isDeleteCompletelyModal`挿入する必要がありました。

2022-02-14 05:54 UTC, closed without merging