imprv: add move with create redirect option
weseek/growi pull request #5311
Opened 2022-02-13 14:03 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/88278

2022-02-14 03:08 UTC, yuki-takei requested changes

2022-02-14 03:08 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +    await PageRedirect.create({ fromPath: page.path, toPath: newPagePath });
options の中にリダイレクトするかどうかのフラグなかったっけ

2022-02-14 04:16 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +    await PageRedirect.create({ fromPath: page.path, toPath: newPagePath });
optionalなの抜けてました。（if文追加）

2022-02-17 12:21 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(pageRedirect.length).toBeGreaterThan(0);
ここもそれに伴って変更

2022-02-17 12:21 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
修正ありがとうございます

2022-02-17 12:21 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +      await PageRedirect.deleteOne({ fromPath: path });
修正ありがとうございます

2022-02-18 01:32 UTC, merged