feat : vrt test for  create page modal
weseek/growi pull request #5326
Opened 2022-02-14 13:19 UTC by maow89126

2022-02-14 19:15 UTC, yuki-takei requested changes

2022-02-14 19:15 UTC, yuki-takei commented on packages/app/test/cypress/integration/2-basic-features/create-page.spec.ts
> +    cy.wait(1000);
ちょっと発展として、モーダルの存在を確かめるコードを書いてください。そしたら wait 不要になるかも。

2022-02-14 20:13 UTC, yuki-takei commented on packages/app/test/cypress/integration/2-basic-features/create-page.spec.ts
> +    cy.screenshot(`${ssPrefix}-open-page-create-modal`)
他のスクリーンショット撮ってるコードと見比べて。

2022-02-15 04:04 UTC, maow89126 commented on packages/app/test/cypress/integration/2-basic-features/create-page.spec.ts
> +    cy.wait(1000);
あと、modalの存在確かめる (=create押せるか確認)してもwaitしないと modalが表示されている部分の写真がとれていなかったのでwait残しました。

2022-02-15 04:04 UTC, maow89126 commented on packages/app/test/cypress/integration/2-basic-features/create-page.spec.ts
> +    cy.wait(1000);
![create-page-open-page-create-modal](https://user-images.githubusercontent.com/60797707/153990630-26cf6ad6-d59d-4d16-8af6-ba61602e7ba2.png)

2022-02-15 22:19 UTC, merged