switch delete modal ui of GrowiContextualSubNavigation
weseek/growi pull request #5339
Opened 2022-02-15 08:19 UTC by kaoritokashiki

GrowiContextualSubNavigation

2022-02-15 09:42 UTC, yuki-takei requested changes

2022-02-15 09:42 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +    console.log('pageInfo.isAbleToDeleteCompletely', pageInfo.isAbleToDeleteCompletely);
console.log は消す

2022-02-15 09:42 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +    mutateChildren();
これは Next 化した後を考えるとOK

2022-02-15 09:42 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        toastSuccess(t('deleted_single_page_recursively_completely', { path }));
削除成功時は toastSuccess ではなくページリロードが必要なのでは？

2022-02-16 06:17 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +    console.log('pageInfo.isAbleToDeleteCompletely', pageInfo.isAbleToDeleteCompletely);
すみません、削除しました。

2022-02-16 06:17 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        toastSuccess(t('deleted_single_page_recursively_completely', { path }));
確かにそうですね。onDeletedが実行されたときにトースターではなくリロードさせるように修正しました。ありがとうございます。

2022-02-16 08:21 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +    }
- 完全削除ではない場合は、reload
- 完全削除の場合は、ページパスでリダイレクトさせるようにしました。

2022-02-16 08:37 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +    }
- 完全削除ではない場合は、reload
- 完全削除の場合は、ページパスでNotFoundページとしてリダイレクトさせるようにしました。

2022-02-16 08:53 UTC, merged