support: Separate DB for v4 and v5 test
weseek/growi pull request #5347
Opened 2022-02-15 15:25 UTC by Yohei-Shiina

Redmine: https://redmine.weseek.co.jp/issues/88532

テストコードを isV5Compatible の値で分けました。それに伴って CI のステージと yarn コマンドを分割しました

2022-02-15 15:27 UTC, Yohei-Shiina commented on packages/app/jest.config.js
> +                  '!<rootDir>/test/integration/service/pagev5.test.ts', '!<rootDir>/test/integration/service/pagev5.test.js'],
除外できていなさそうだったので修正必要そう

2022-02-15 19:06 UTC, hakumizuki commented on .github/workflows/ci-app.yml
> +        MONGO_URI_TEST_V5: mongodb://localhost:${{ job.services.mongodb.ports['27017'] }}/growi_test_v5
テスト用に分けました

2022-02-15 19:07 UTC, hakumizuki commented on packages/app/jest.config.js
> +                  '?!<rootDir>/test/integration/service/v5.*.test.ts', '?!<rootDir>/test/integration/service/v5.*.test.js'],
`<rootDir>/test/integration/service/v5.*.test.js` (tsも) のファイルを isV5Compatible: true でテストできるものとして区別しました

2022-02-15 19:07 UTC, hakumizuki commented on packages/app/jest.config.js
> +      testMatch: ['<rootDir>/test/integration/service/v5.*.test.ts', '<rootDir>/test/integration/service/v5.*.test.js'],
`<rootDir>/test/integration/service/v5.*.test.js` (tsも) のファイルを isV5Compatible: true でテストできるものとして区別しました

2022-02-15 19:08 UTC, hakumizuki commented on packages/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
> +    }
接続されていない場合にのみ mongoose.connect を走らせるようにしました。safeConnect みたいなメソッドを作ってもいいかなとも思っています

2022-02-15 19:09 UTC, hakumizuki commented on packages/app/test/integration/global-setup.js
> +  }]);
トップページがテストコードのバグの下になっているので、global-setup で用意するようにしました

2022-02-15 19:09 UTC, hakumizuki commented on packages/core/src/utils/mongoose-utils.ts
> +
テスト用に MONGO_URI を分けました

2022-02-16 03:52 UTC, hakumizuki commented on packages/app/package.json
> +    "test-v5": "cross-env NODE_ENV=test jest --selectProjects server-v5 --passWithNoTests -- ",
`--selectProjects` オプションで分けました

2022-02-16 03:53 UTC, hakumizuki commented on packages/app/jest.config.js
> +      testMatch: ['<rootDir>/test/integration/**/v5.*.test.ts', '<rootDir>/test/integration/**/v5.*.test.js'],
`v5.*.test.js` の命名規則で DB を分けられるようにしました

2022-02-16 03:56 UTC, hakumizuki commented on .github/workflows/ci-app.yml
> +        yarn test-v5
`yarn test-v5`

2022-02-16 06:49 UTC, yuki-takei requested changes

2022-02-16 06:49 UTC, yuki-takei commented on packages/app/test/integration/v5-global-setup.js
> +  }]);
v5 じゃなくてもこの処理やってしまえばいい

2022-02-16 06:49 UTC, yuki-takei commented on packages/app/test/integration/v5-setup.js
> +module.exports = {};
このファイルもいらない

2022-02-16 06:49 UTC, yuki-takei commented on packages/app/package.json
> +    "test-v5": "cross-env NODE_ENV=test jest --selectProjects server-v5 --passWithNoTests -- ",
test はそのままにする(手元でのテストで使えるように)

新たに `test:ci` を作って、workflow のファイルから selectProjects に文字列を渡せるようにする。そのためには `--passWithNoTests --` が邪魔かもしれないので、その場合は消して良い。

2022-02-16 06:49 UTC, yuki-takei commented on .github/workflows/ci-app.yml
> +        yarn test-v5
job を追加しなくても、この step だけ追加して縦列実行すればよい。

## 以下別の案

将来並列実行したくなった場合でも、job を作るのではなく matrix で selectProjects に渡す文字列を列挙したほうがメンテナンス性が高い。MONGO_URI には bash で連結した文字列を作って "/unit-server" 等として DB 名をセットする。

2022-02-16 06:52 UTC, hakumizuki commented on packages/app/test/integration/v5-global-setup.js
> +  }]);
消しました

2022-02-16 06:52 UTC, hakumizuki commented on packages/app/test/integration/v5-setup.js
> +module.exports = {};
消しました

2022-02-16 07:00 UTC, hakumizuki commented on .github/workflows/ci-app.yml
> +        yarn test-v5
なるほど。メモっておきます

2022-02-16 09:02 UTC, yuki-takei approved these changes

2022-02-16 09:02 UTC, merged