imprv: switch delete modal ui of pageListItemL
weseek/growi pull request #5355
Opened 2022-02-16 10:47 UTC by kaoritokashiki

2022-02-16 12:03 UTC, yuki-takei commented on packages/app/src/components/PageList/PageListItemL.tsx
> +  const { data: pageInfo } = useSWRxPageInfo(pageData._id ?? null, shareLinkId);
このコンポーネントでは PageInfo を取得する必要はない

2022-02-16 18:04 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> -    mutateChildren();
- mutateChildrenが実行される条件として
親のページにページ遷移した後 & その子供を削除した時
- > ページツリーから子供が削除される

2022-02-16 18:16 UTC, kaoritokashiki commented on packages/app/src/components/PageList/PageListItemL.tsx
> +  }, []);
完全削除かどうかに関わらず、削除された時にブラウザをリロードするようにしました。

2022-02-17 17:10 UTC, kaoritokashiki commented on packages/app/src/components/PageList/PageListItemL.tsx
> +  const { data: pageInfo } = useSWRxPageInfo(pageData._id ?? null, shareLinkId);
PageItemControlから`onClickDeleteMenuItem`を通してpropsで渡すようにしました。

2022-02-17 17:12 UTC, kaoritokashiki commented on packages/app/src/components/SearchPage.tsx
> +      onPageOperated={mutateSWRxFullTextSearch}
deleteした時にonPageOperatedが渡ってきて、`SearchPage`にて、mutateSWRxFullTextSearchが実行されるようにしました。

2022-02-17 17:35 UTC, kaoritokashiki commented on packages/app/src/components/SearchPage.tsx
> +      onPageOperated={mutateSWRxFullTextSearch}
## 現在の挙動
mutateしてもtrashページがそのまま表示されてしまう。

https://user-images.githubusercontent.com/59536731/154535409-430f8a77-8489-41ac-849d-e4fbff22ce12.mov

sprint103にバグストーリーを追加しました。
https://redmine.weseek.co.jp/issues/88774

2022-02-17 18:41 UTC, yuki-takei requested changes

2022-02-17 18:49 UTC, yuki-takei requested changes

2022-02-17 18:49 UTC, yuki-takei commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +    if (onClickDeleteMenuItem == null || fetchedPageInfo == null) {
shouldFetch が true じゃなかったら fetchedPageInfo は null のままなので、この条件はどうなんだろう…

2022-02-17 18:58 UTC, yuki-takei commented
膨らんだスコープ整理

- isAbleToDeleteCompletely を渡すために、IPageInfo ごと渡している
    - boolean だけ渡せばいい
- 削除後に再検索したい

2022-02-17 19:44 UTC, kaoritokashiki commented on packages/app/src/stores/modal.tsx
>      ) => swrResponse.mutate({
onDeletedは第3引数に渡すようにしました。

2022-02-17 19:46 UTC, merged