show delete compreatly modal on trash page
weseek/growi pull request #5359
Opened 2022-02-16 12:39 UTC by kaoritokashiki

2022-02-16 19:30 UTC, yuki-takei requested changes

2022-02-16 19:30 UTC, yuki-takei commented on packages/app/src/components/Page/TrashPageAlert.jsx
> +  const { data: pageInfo } = useSWRxPageInfo(pageId ?? null, shareLinkId);
useSWRxPageInfo はこのコンポーネントでは利用禁止。
安易にどこからでも SWR を呼ぶという手段に走らないようにして。

SWR は「通信を行うもの」または「グローバル変数を取得(格納)するもの」なので、
利用する側も「通信を行う責務を持って良い粒度のコンポーネント」または「グローバル変数を取得(格納)して良い粒度のコンポーネント」に限る。
(PageItemControl では isIPageInfoForOperation を使って本当に情報が足りない場合に限っている)

TrashPage が useSWRxPageInfo するのが筋。

2022-02-16 19:53 UTC, kaoritokashiki commented on packages/app/src/components/Page/TrashPageAlert.jsx
> +  const { data: pageInfo } = useSWRxPageInfo(pageId ?? null, shareLinkId);
理解しました。

現状、`TrashPageAlert` コンポーネントは、app.jsxでMappingされており、 `page_alerts.html`で使われています。

```
 {% if isTrashPage(page.path) %}
      <div id="trash-page-alert"></div>
{% endif %}
```

2022-02-16 20:08 UTC, merged

2022-02-17 06:41 UTC, kaoritokashiki commented on packages/app/src/components/Page/TrashPageAlert.jsx
> +  const { data: pageInfo } = useSWRxPageInfo(pageId ?? null, shareLinkId);
- Next 化するまで棚上げ
することに決定