fix: disable move option for user
weseek/growi pull request #5363
Opened 2022-02-16 17:26 UTC by Yohei-Shiina

ページ操作のオプション表示の仕方が統一されてなさそうだったので非表示ではなくdisable にしました

<img width="470" alt="image" src="https://user-images.githubusercontent.com/35527421/154321216-7727319f-c914-4852-ae24-6d60a1eca9f8.png">

<img width="491" alt="image" src="https://user-images.githubusercontent.com/35527421/154321283-0b1e028a-a765-4a70-b823-35c23e971c11.png">

2022-02-16 19:50 UTC, yuki-takei requested changes

2022-02-17 07:08 UTC, yuki-takei requested changes

2022-02-17 07:08 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/page.js
> +      const isMovable = !isTopPage(page.path) && !isUserPage(page.path) && !isUserNamePage(page.path);
constructBasicPageInfo側があればこの行要らないね。(たぶん)

2022-02-17 08:06 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +        isMovable,
`isEmpty: true` なページでも、トップページ、ユーザー関連ページは操作できてはいけないはずなので
無条件に true が入らないように最初に isMovable 条件を持っていきました

2022-02-17 08:06 UTC, Yohei-Shiina commented on packages/app/src/server/routes/apiv3/page.js
> -      const isMovable = !isTopPage(page.path);
const pageInfo = pageService.constructBasicPageInfo(page, isGuestUser);

で作成したdataで十分だったので削除

2022-02-17 08:59 UTC, merged