fix: 88635 Show presentation modal in top page
weseek/growi pull request #5370
Opened 2022-02-17 06:35 UTC by miya

## Task
[#88635](https://redmine.weseek.co.jp/issues/88635) [5.x][bug]ホーム画面でプレゼンテーションモーダルを表示した際に、ブラウザ全体が表示されてしまう

2022-02-17 07:12 UTC, yuki-takei requested changes

2022-02-17 07:12 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const hrefForPresentationModal = `${pageId}/?presentation=1`;
この相対パスでの指定、応急処置的でなんか不安になるな。
URL に hash とかその他の GET param が含まれている場合でも大丈夫？

2022-02-17 07:12 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const hrefForPresentationModal = `${pageId}/?presentation=1`;
あと VRT 追加してください。

2022-02-21 06:29 UTC, miya commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const hrefForPresentationModal = `${pageId}/?presentation=1`;
/、/Sandbox/Bootstrap4、/Sandbox/Bootstrap4#Cards でプレゼンテーションモーダルを開いた際の VRT を追加しました。

2022-02-21 07:19 UTC, miya commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +    <Dropdown isOpen={isOpen} toggle={() => setIsOpen(!isOpen)} data-testid={dataTestId}>
Dropdown の開閉ボタンに `data-testid` を付与しました

2022-02-21 07:19 UTC, miya commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        data-testid="open-presentation-modal-btn"
プレゼンテーションモーダルを開くためのボタンに `data-testid` を付与しました。

2022-02-21 07:19 UTC, miya commented on packages/app/test/cypress/integration/2-basic-features/open-presentation-modal.spec.ts
> +});
VRT を追加しました。

2022-02-21 19:48 UTC, yuki-takei requested changes

2022-02-21 19:48 UTC, yuki-takei commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  dataTestId?: string
これ props で外から注入するのはいやだな。
SubNavigation が含む PageItemControl みたいに特定する必要があるからこうしているのだろうか？だとしても cypress 側のコードの工夫でなんとかなるはず。

2022-02-22 05:55 UTC, miya commented on packages/app/test/cypress/integration/2-basic-features/open-presentation-modal.spec.ts
> +    });
- `grw-subnav-container` の要素内に存在する `open-page-item-control-btn` はひとつのみだったのでこのような実装になりました。

- `/Sandbox/Bootstrap4#Cards` に遷移する際に、あらかじめスクロールされた位置にあり、`grw-subnav-container` が隠れ通常はクリックできないため `force: true` にしています。（一貫性を持たせるために全て force: true ）にしています。

2022-02-22 05:55 UTC, miya commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  dataTestId?: string
修正しました。

2022-02-22 05:59 UTC, miya commented on packages/app/test/cypress/integration/2-basic-features/open-presentation-modal.spec.ts
> +    });
- `grw-subnav-container` の要素内に存在する `open-page-item-control-btn` はひとつのみだったのでこのような実装になりました。

- `/Sandbox/Bootstrap4#Cards` に遷移する際に、あらかじめスクロールされた位置にあり、`grw-subnav-container` が隠れ通常はクリックできないため `force: true` にしています。（一貫性を持たせるために全て force: true ）にしています。

2022-02-22 07:59 UTC, yuki-takei commented on packages/app/test/cypress/integration/2-basic-features/open-presentation-modal.spec.ts
> +    cy.wait(1500);
後続タスクでいいので、presentation modal の要素の存在チェックを入れてください。そうすると cy.wait 不要になる。

2022-02-22 07:59 UTC, yuki-takei approved these changes

2022-02-22 07:59 UTC, merged