Imprv/89046 reload page after page has been duplicated on growi contextual subnavgation
weseek/growi pull request #5435
Opened 2022-02-25 14:57 UTC by kaoritokashiki

2022-02-25 15:12 UTC, kaoritokashiki commented on packages/app/src/interfaces/ui.ts
> +export type OnDuplicatedFunction = (fromPath: string, toPath: string) => void;
第一引数: 複製したいページパス
第二引数: 複製先のページパス
を渡すようにしました。

2022-02-27 17:14 UTC, yuki-takei requested changes

2022-02-27 17:14 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +      window.location.href = toPath;
v4.5 だと alert で「fromPath から複製されました」みたいなの出すための GET param 付けてなかったっけ？

2022-02-27 18:39 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +      window.location.href = toPath;
#5436 にて削除されます。

2022-02-27 18:41 UTC, merged