Fix: 89241 Custom Sidebar
weseek/growi pull request #5455
Opened 2022-03-01 05:03 UTC by miya

## Task
[#89241](https://redmine.weseek.co.jp/issues/89241) /Sidebar が存在しない時に <SidebarNotFound> が表示されない

2022-03-01 09:58 UTC, yuki-takei requested changes

2022-03-01 09:58 UTC, yuki-takei commented on packages/app/src/components/Sidebar/CustomSidebar.tsx
> +      }
isLoading: true なら spinner 表示するとかの方が親切

2022-03-01 09:58 UTC, yuki-takei commented on packages/app/src/components/Page/RevisionRenderer.jsx
> +  isRenderable: PropTypes.bool,
これは消しましょう

2022-03-03 08:41 UTC, miya commented on packages/app/src/components/Page/RevisionRenderer.jsx
> +  isRenderable: PropTypes.bool,
消しました。

2022-03-03 08:42 UTC, miya commented on packages/app/src/components/Sidebar/CustomSidebar.tsx
> +      }
Spinner を表示できるようにしました。

2022-03-03 08:48 UTC, miya commented on packages/app/src/components/Page/RevisionRenderer.jsx
> +  isRenderable: PropTypes.bool,
以下の Lint エラーが出るため追加しています。後続で  isRenderable を剥がすタスクをやろうと思います。

```
src/components/Sidebar/CustomSidebar.tsx(66,15): error TS2322: Type '{ growiRenderer: any; markdown: string; additionalClassName: string; isRenderable: true; }' is not assignable to type 'IntrinsicAttributes & InferPropsInner<Pick<{ growiRenderer: Validator<GrowiRenderer>; markdown: Validator<string>; highlightKeywords: Requireable<...>; additionalClassName: Requireable<...>; }, RequiredKeys<...>>> & Partial<...>'.
```

2022-03-03 08:52 UTC, miya commented on packages/app/src/components/Sidebar/CustomSidebar.tsx
> +      }
isLoading: true の時に Spinner を表示できるようにしました。

2022-03-03 08:52 UTC, miya commented on packages/app/src/components/Sidebar/CustomSidebar.tsx
> +  const isLoading = page === undefined && error == null;
エラー時に `true` になっていなかったため、修正しました。

2022-03-03 13:25 UTC, merged