Imprv: 89859 Omit renderable boolean
weseek/growi pull request #5474
Opened 2022-03-04 04:50 UTC by miya

## Task
[#89859](https://redmine.weseek.co.jp/issues/89859) isRenderable という boolean を剥がす

2022-03-04 10:54 UTC, miya commented on packages/app/src/components/Page.jsx
> +        <RevisionRenderer growiRenderer={this.growiRenderer} markdown={isRenderable ? markdown : ''} />
`!(revisionId == null && isEnabledAttachTitleHeader && editorMode === EditorMode.View)` この条件の時に markdown をレンダリングさせないようにしました

2022-03-07 03:46 UTC, yuki-takei requested changes

2022-03-07 03:46 UTC, yuki-takei commented on packages/app/src/components/Page.jsx
> +        <RevisionRenderer growiRenderer={this.growiRenderer} markdown={isRenderable ? markdown : ''} />
isEnabledAttachTitleHeader の T/F に関わらず他2条件によってレンダリング不要なのでは？
もっと言えば Page.jsx コンポーネントの使い処を考えると `editorMode === EditorMode.View` すら不要なんじゃないかと疑っている。

2022-03-07 05:40 UTC, miya commented on packages/app/src/components/Page.jsx
> +        <RevisionRenderer growiRenderer={this.growiRenderer} markdown={isRenderable ? markdown : ''} />
> isEnabledAttachTitleHeader の T/F に関わらず他2条件によってレンダリング不要なのでは？
> editorMode === EditorMode.View すら不要なんじゃないかと疑っている。

確かにその通りでしたので修正しました。

2022-03-07 08:48 UTC, merged