fix: auto scroll pagetree
weseek/growi pull request #5476
Opened 2022-03-04 10:00 UTC by Yohei-Shiina

2022-03-04 11:41 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> -
この段階でスクロールイベントの発火は早いので削除

2022-03-04 11:47 UTC, Yohei-Shiina commented on packages/app/src/client/util/smooth-scroll.ts
> +
特定の要素の top の位置にスクロールする
or
特定の要素が画面中央にくるようにスクロールする

2022-03-04 11:49 UTC, Yohei-Shiina commented on packages/app/src/client/util/smooth-scroll.ts
> +
特定の要素の top の位置にスクロールする
or
特定の要素が画面中央にくるようにスクロールする

2022-03-04 11:56 UTC, Yohei-Shiina commented on packages/app/src/client/util/smooth-scroll.ts
> +};
特定の要素の top の位置にスクロールする
or
特定の要素が画面中央にくるようにスクロールする

2022-03-04 11:56 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +  });
スクロール発火用のリスナー登録

2022-03-04 11:56 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +  }, [isRenderedCompletely]);
ページツリーアイテムが完全にレンダーされたら JQuery の slimscroll を reset する

2022-03-04 11:56 UTC, Yohei-Shiina commented on packages/app/src/components/StickyStretchableScroller.jsx
> +    }
スクロール可能かつ、scrollTargetSelector が `#grw-sidebar-contents-scroll-target` の場合の時だけ
ページツリーをスクロールするイベントを発火

2022-03-04 11:56 UTC, Yohei-Shiina commented on packages/app/src/components/StickyStretchableScroller.jsx
> +  }, []);
scroller を resetするための リスナー登録

2022-03-04 19:16 UTC, yuki-takei requested changes

2022-03-04 19:16 UTC, yuki-takei commented on packages/app/src/client/util/smooth-scroll.ts
> +  const windowCenter = window.innerHeight / 2;
- 仮に要求仕様が「サイドバーの真ん中に target element が来るようにスクロールしたい」だったとしても、サイドバーの真ん中は windowCenter ではない(たまたま近いというだけ)
- そもそも要求仕様としては、サイドバーのほぼ上端に target element の top が来てくれるほうがありがたいのではないだろうか

2022-03-04 19:16 UTC, yuki-takei commented on packages/app/src/components/StickyStretchableScroller.jsx
> +    }
StickyStretchableScroller は汎用的なコンポーネントなので、このコードは責務の観点から NG。
汎用的なコードとはどういうものかを考えて書いて。

2022-03-04 19:23 UTC, yuki-takei requested changes

2022-03-04 19:23 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +  }, [isRenderedCompletely]);
- CustomEvent の利用自体は必ずしも NG ではないが、使うのであれば最低限イベント名は enum (union) で管理する
- 現状のコードは典型的なスパゲッティコード
    - ItemsTree と StickyStretchableScroller が scrollPageTree と resetScroller を相互に dispatch して、それを listen しあっている

2022-03-07 10:59 UTC, yuki-takei requested changes

2022-03-07 10:59 UTC, yuki-takei commented on packages/app/src/components/StickyStretchableScroller.jsx
> +  }, []);
このコンポーネントは汎用的なものなので、「Sidebar」と名前の付く何かに依存してはいけない

2022-03-07 10:59 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +      document.dispatchEvent(new CustomEvent(SidebarScrollerEvent.RESET_SCROLLBAR));
できればこのコードを消したい。他のコンテンツの場合はこの明示的措置が必要ないので、何故 PageTree だけ必要なのかを説明して欲しい。

2022-03-08 22:27 UTC, yuki-takei commented on packages/app/package.json
> +    "simplebar-react": "^2.3.6",
slimscroll の代替

2022-03-08 22:27 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree.tsx
> +  const targetPathOrId = targetId || notFoundTargetPathOrId;
ここよくわかってない

2022-03-08 22:27 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +  const { data: sidebarScrollerRef } = useSidebarScrollerRef();
global state として管理されている scroller (実体は SimpleBar インスタンスを取得できる RefObject)を利用

2022-03-08 22:27 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +    scrollElement.scrollTo({ top: scrollTop });
スクロール手法自体は PureJS

2022-03-08 22:27 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +    }
初回以外は ignore。
「どのタイミングが初回か」は、scroller と scroll target の両方が揃っており、かつこのメソッドの呼びだしが debounce によって収束した(最後の呼び出しから 100ms 経った時)。

2022-03-08 22:27 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +    }
scroller と scroll target の両方が揃っていなければ ignore。

2022-03-08 22:27 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
> +    observer.observe(rootElement, { childList: true, subtree: true });
検知には MutationObserver を使う。
子要素全ての変更を検知し、都度 scrollOnInitDebounced を呼ぶ。

2022-03-08 22:27 UTC, yuki-takei commented on packages/app/package.json
> +    "simplebar-react": "^2.3.6",
slimscroll は StaffCredit で使っているのでまだ消せない。

2022-03-08 22:29 UTC, yuki-takei commented on packages/app/src/interfaces/page-listing-results.ts
> -}
ここよくわかってない (2/2)

2022-03-10 14:21 UTC, merged