feat: 89895 Show spinner until rename request is complete
weseek/growi pull request #5479
Opened 2022-03-05 08:43 UTC by miya

## Task
[#89895](https://redmine.weseek.co.jp/issues/89895) rename リクエストが走っている間はタイトルの箇所に spinner を表示させる

2022-03-07 09:00 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +        )}
スピナーを表示

2022-03-09 16:39 UTC, yuki-takei requested changes

2022-03-09 16:39 UTC, yuki-takei commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +        await onRenamed();
これ待つのはやめよう。apiv3Put の間だけ spinner 表示でよいです。
通信終了してからももう少し表示させ続けたいなら、固定値で 100ms～200ms 待って `setRenaming(false)` を呼ぼう。

理由の説明は難しいんだけど、onRenamed の実行は本筋の処理から離れた「副作用」なので、という感覚かな。ピンとこなかったら口頭で説明するから暇な時に話しかけて。

2022-03-09 16:39 UTC, yuki-takei commented on packages/app/src/stores/use-static-swr.tsx
> +      });
この advance を await 可能にするかどうかは、Item で onRename を await 可能にするかどうかとは別の議論である。

こちらを await できるように返り値を Promise にすること自体は意味があるのであればやってもいいかもしれないが、現状の mutate を await するだけではそれほど意味がなさそう。

2022-03-10 10:18 UTC, miya commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +        await onRenamed();
apiv3Put のみの間だけ spinner を表示するようにしました。100ms 〜 200ms だと足りない感じがしたので 1000ms 待つようにしました。ワクチンの副反応でダウンしているので、次回出社した時にお聞きするかもです。

2022-03-10 16:41 UTC, merged