imprv: add space btw page list meta and page view control
weseek/growi pull request #5502
Opened 2022-03-08 06:35 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/89981

2022-03-08 06:36 UTC, Yohei-Shiina commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        <div className={`${className} ${isCompactMode ? '' : 'mt-2'}`}>
`isCompactMode:true` の時は gap: 5px が入っているのでそれ以上の余白は追加しないようにしました

2022-03-08 18:37 UTC, kaoritokashiki requested changes

2022-03-08 18:37 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        <div className={`${className} ${isCompactMode ? '' : 'mt-2'}`}>
このストーリーの元々の問題として
- ユーザーページだと、`ControlComponents` と3点ボタン(View/Edit/HackMd)の感覚が狭くなってしまっている
- ただ通常画面だと綺麗に表示されている
というのが挙げられました

この解決策だと、期待通りに表示されている「通常ページ」では上下の要素の間隔が広がってしまいますね

なので、最初にやるべきこととしては「通常ページ」と「ユーザーページ」では何が異なるのかの原因を探っていかないといけないと思っています。

- 通常ページ↓
<img width="828" alt="Screen Shot 2022-03-09 at 3 36 06" src="https://user-images.githubusercontent.com/59536731/157303268-76286473-91ce-4ca4-bd5b-bcb84e920218.png">

- ユーザーページ↓
<img width="824" alt="Screen Shot 2022-03-09 at 3 35 55" src="https://user-images.githubusercontent.com/59536731/157303259-195ad25c-a86d-4d7c-9e65-75352884f537.png">

2022-03-08 18:37 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        <div className={`${className} ${isCompactMode ? '' : 'mt-2'}`}>
## わかったこと
- ユーザーページではサブナビゲーションの右側に
「作成者/作成日時/更新者/更新日時」を表す要素がある
┗その要素には`py-2`がついている

<img width="392" alt="Screen Shot 2022-03-09 at 3 27 38" src="https://user-images.githubusercontent.com/59536731/157302124-c20f905c-3433-45ba-9d96-a1f32cfe9117.png">

- このpaddingの影響で、`ControlComponents`と3点ボタンのheightが高くなる

- 親要素のheightが高くなったことによって`flex-column` で縦並びになった要素のheight(h-50)も長くなる

- 結果として`ControlComponents` と3点ボタン(View/Edit/HackMd)の感覚が広がって綺麗に表示される

2022-03-08 18:39 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        <div className={`${className} ${isCompactMode ? '' : 'mt-2'}`}>
この問題の解決策は武井さんと相談でお願いします

2022-03-09 03:56 UTC, Yohei-Shiina commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        <div className={`${className} ${isCompactMode ? '' : 'mt-2'}`}>
これ気づけていなかった、ありがとうございます
> この解決策だと、期待通りに表示されている「通常ページ」では上下の要素の間隔が広がってしまいますね

右にある 「作成者/作成日時/更新者/更新日時」の py-2 を取り除けば「通常ページ」でもユーザのページでも`PageListMeta`+`PageControlView` の高さは同じになる

右にある 「作成者/作成日時/更新者/更新日時」の py-2 が上下中央揃えを目的にしているなら flex で対応できるので不要にできる

2022-03-10 07:37 UTC, Yohei-Shiina commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        <div className={`${className} ${isCompactMode ? '' : 'mt-2'}`}>
「ユーザのページ」
<img width="316" alt="image" src="https://user-images.githubusercontent.com/35527421/157611623-aa447f14-c6b9-4a25-b347-63e1bd9de6fe.png">

<img width="334" alt="image" src="https://user-images.githubusercontent.com/35527421/157611590-910d1e02-bbea-4527-a4d7-2b4b79400be5.png">

「通常ページ」
<img width="294" alt="image" src="https://user-images.githubusercontent.com/35527421/157611817-c3cc418b-8229-4c83-82c3-c1d336970099.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/35527421/157611797-f644762a-f978-4680-a889-052e2d408092.png">

2022-03-10 10:41 UTC, kaoritokashiki approved these changes

2022-03-10 10:41 UTC, merged