Feat/82575 89919 display comment in search page
weseek/growi pull request #5503
Opened 2022-03-08 07:35 UTC by yuto-oweseek

## タスク

## 行ったこと

2022-03-09 07:59 UTC, yuto-oweseek commented on packages/app/src/components/PageComment/CommentEditorLazyRenderer.tsx
> +import React, { FC } from 'react';
- ts 化 & withUnstatedContainers を除去した差分です

2022-03-09 07:59 UTC, yuto-oweseek commented on packages/app/src/components/PageCommentList.tsx
> +import React, {
- `PageComment.jsx` と `PageCommentList.tsx` を後続ストーリーで共通化するときれいになります
- 一旦は、検索結果ページの右ペインで出しても問題ない、最低限の機能を持った（コメントを表示）コンポーネントです

2022-03-09 07:59 UTC, yuto-oweseek commented on packages/app/src/components/PageContentFooter.tsx
> +import React, { FC, memo } from 'react';
- こちらも ts 化 & `withUnstatedContainers` を除去

2022-03-09 16:51 UTC, yuki-takei requested changes

2022-03-09 16:51 UTC, yuki-takei commented on packages/app/src/server/models/obsolete-page.js
> +    const builder = new this.PageQueryBuilder(this.find({ _id: { $in: ids } }).populate('creator'), shouldIncludeEmpty);
model での populate は NG

2022-03-10 05:39 UTC, yuto-oweseek commented on packages/app/src/server/models/obsolete-page.js
> +    const builder = new this.PageQueryBuilder(this.find({ _id: { $in: ids } }).populate('creator'), shouldIncludeEmpty);
https://github.com/weseek/growi/commit/f2766e3c8491986da20572e2dd42accf176b6c2e

↑ で service 層へ moved 🌍

2022-03-10 09:44 UTC, yuki-takei requested changes

2022-03-10 09:44 UTC, yuki-takei commented on packages/app/src/server/service/search.ts
> +    });
無駄が多いので、findListByPageIds は廃止しよう。(幸いここでしか使ってないみたいだし)

- findListByPageIds 相当を、search.ts 側に作る
- query.exec を1回実行したら必要なものが全て populate されている状態にする

2022-03-14 06:44 UTC, yuto-oweseek commented on packages/app/src/server/service/search.ts
> +    });
https://github.com/weseek/growi/pull/5503/commits/1079e7b6779f0b4593568de008e4bb60cc70a292

↑ commit で 修正 💇‍♂️

2022-03-14 08:18 UTC, merged