Imprv/vrt delete bootstrap4
weseek/growi pull request #5547
Opened 2022-03-14 04:32 UTC by asami-n

2022-03-15 09:18 UTC, kaoritokashiki requested changes

2022-03-15 09:18 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/2-basic-features/bootstrap4-open-delete-modal.spec.ts
> +     cy.screenshot(`${ssPrefix}-bootstrap4`,{ capture: 'viewport' });
`open-page-delete-modal-btn` をクリックしてからモーダルを開くまでに少し時間がかかるみたいなので
```
cy.wait(1500);
````
を33行目に追加お願いします。
(モーダルが開かれるのを待ってから、スクリーンショットをとる)

## Note
上記のコードを追加するとエラーが表示されると思うので、ホバー -> `QuickFix`をクリックで エラーが出ないように修正お願いします。

2022-03-15 09:59 UTC, kaoritokashiki requested changes

2022-03-15 09:59 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/2-basic-features/open-page-delete-modal.spec.ts
> +});
1. このファイルは使わないと思うので削除
2. bootstrap4-open-delete-modal.spec.ts のfile名を `open-page-delete-modal.spec.ts` に変更
お願いします

2022-03-15 09:59 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/2-basic-features/bootstrap4-open-delete-modal.spec.ts
> +     cy.screenshot(`${ssPrefix}-bootstrap4`,{ capture: 'viewport' });
```suggestion
     cy.screenshot(`${ssPrefix}-open-bootstrap4`,{ capture: 'viewport' });
```

2022-03-15 10:01 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/2-basic-features/bootstrap4-open-delete-modal.spec.ts
> +     cy.screenshot(`${ssPrefix}-bootstrap4`,{ capture: 'viewport' });
`{ capture: 'viewport' }`っているのかな....?

2022-03-15 18:21 UTC, yuki-takei requested changes

2022-03-15 18:21 UTC, yuki-takei commented on packages/app/test/cypress/integration/2-basic-features/open-page-delete-modal.spec.ts
> +     cy.wait(1500);
他のテストでもやってる存在チェック (`.should('be.visible')`) を書いて wait は消してください。

2022-03-16 08:33 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/2-basic-features/open-page-delete-modal.spec.ts
> +  });
不要なコメントは削除お願いします。

2022-03-16 09:24 UTC, merged