Fix/show page tree properly
weseek/growi pull request #5548
Opened 2022-03-14 04:55 UTC by Yohei-Shiina

2022-03-16 23:14 UTC, hakumizuki requested changes

2022-03-16 23:14 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +    else if (shouldMinusUpdateDescCount) {
このブロックは

```typescript
await crowi.pageService.updateDescendantCountOfAncestors(exParent, -1, true);
```

これだけだと動かないですかね？

```typescript
await crowi.pageService.updateDescendantCountOfAncestors(newPageData._id, -1, false);
```

これとかは見た感じ必要ない気もしてます

2022-03-16 23:14 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +    if (wasOnTree && !isChildrenExist) {
```typescript
const shouldRemoveLeafEmpPages = wasOnTree && !isChildrenExist;
```

に入れてあげると統一感でそうです

2022-03-17 03:50 UTC, Yohei-Shiina commented on packages/app/src/server/models/page.ts
> +      let parentId: IObjectId | string | null = null;
これ自体不要そうなので消し
`let parentId: IObjectId | string | null = null;`

2022-03-17 05:35 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +  };
Typescript !!!!!!!!

2022-03-17 06:26 UTC, merged