imprv: show error message in case page path is set directory under user page
weseek/growi pull request #5553
Opened 2022-03-14 14:17 UTC by kaoritokashiki

## Task
- [90506](https://redmine.weseek.co.jp/issues/90506) PageRenameModalで、/user/hoge にrenameしようとした時に、エラーの表示をし、submitボタンをdisabledにする

## ScreenRecording
https://user-images.githubusercontent.com/59536731/158578902-d94f6518-034a-4cb6-aaf0-09a5021fb35f.mov

## ScreenShots
- user page直下にパスをrenameしようとした時
┗rename不可能
<img width="745" alt="Screen Shot 2022-03-14 at 23 39 52" src="https://user-images.githubusercontent.com/59536731/158195375-62d6542a-35fe-472e-9555-d1ab4c1c68e6.png">

- user page直下にパスをrenameしようとした時
かつ
- 重複したページパスになってしまっている時
┗rename不可能
<img width="774" alt="Screen Shot 2022-03-14 at 23 39 57" src="https://user-images.githubusercontent.com/59536731/158195386-34217754-e630-4562-b73c-f80a39ffcd29.png">

- `/user/${user_name}/hoge` の場合
┗rename可能
<img width="681" alt="Screen Shot 2022-03-14 at 23 40 11" src="https://user-images.githubusercontent.com/59536731/158195391-9e115eb6-6ae7-44ff-831d-46b77e6cb1d8.png">

2022-03-14 16:26 UTC, kaoritokashiki commented on packages/app/src/components/PageRenameModal.tsx
> +  const isSubmitButtonDisabledV4orV5 = isV5Compatible(page.meta)
`isSubmitButtonDisabledV4orV5` この変数名は良くないかもしれません

2022-03-15 08:31 UTC, yuki-takei requested changes

2022-03-15 08:31 UTC, yuki-takei commented on packages/app/src/components/PageRenameModal.tsx
> +  const isSubmitButtonDisabled = isDirectoryUnderUserPage || isSubmitButtonDisabledV4orV5;
195 - 199 行目の変数名整理してください。

2022-03-16 11:19 UTC, kaoritokashiki commented on packages/app/src/components/PageRenameModal.tsx
> +  }
三項演算子等ではなく if block に書き換えました。

2022-03-16 11:20 UTC, kaoritokashiki commented on packages/app/src/components/PageRenameModal.tsx
> +  const [isMatchedWithUserHomePagePath, setIsMatchedWithUserHomePagePath] = useState(false);
debounceを使って1秒後にエラーを表示させるために、変数を定義しています。

2022-03-16 11:29 UTC, merged