fix: enable to reflect like and bookmark count
weseek/growi pull request #5566
Opened 2022-03-17 04:38 UTC by ryohi15

## task
https://redmine.weseek.co.jp/issues/89536

2022-03-22 11:01 UTC, yuki-takei requested changes

2022-03-22 11:03 UTC, yuki-takei requested changes

2022-03-22 11:03 UTC, yuki-takei commented on packages/ui/src/components/PagePath/PageListMeta.jsx
> +      likerCount = <span className={`${shouldSpaceOutIcon ? 'mr-3' : ''}`}><i className="fa fa-heart-o" />{this.props.likerCount}</span>;
このコンポーネントいろんなところで使ってると思うけど、影響ないのかな？

2022-03-23 10:04 UTC, ryohi15 commented on packages/app/src/components/PageList/PageListItemL.tsx
> +  const { data: pageInfo } = useSWRxPageInfo(shouldFetch ? pageData?._id : null);
`isSelected を条件に入れてるから起こらない？` でした

2022-03-25 13:02 UTC, yuki-takei requested changes

2022-03-25 13:02 UTC, yuki-takei commented on packages/app/src/components/PageList/PageListItemL.tsx
> +  if (isSelected && pageInfo != null && 'likerIds' in pageInfo) {
likerIds, bookmarkCount を持つのは IPageInfoForEntity なので、isIPageInfoForEntity を使ってください。

2022-03-28 03:07 UTC, ryohi15 commented on packages/app/src/components/PageList/PageListItemL.tsx
> +  if (isSelected && pageInfo != null && 'likerIds' in pageInfo) {
承知です

2022-03-28 03:07 UTC, ryohi15 commented on packages/ui/src/components/PagePath/PageListMeta.jsx
> +      likerCount = <span className={`${shouldSpaceOutIcon ? 'mr-3' : ''}`}><i className="fa fa-heart-o" />{this.props.likerCount}</span>;
してました

2022-03-28 05:52 UTC, merged