Imprv: vrt move rename bootstrap4
weseek/growi pull request #5589
Opened 2022-03-23 03:07 UTC by asami-n

## Task
[GW-7755](https://youtrack.weseek.co.jp/issue/GW-7755) サブナビゲーションからのPageMoveRenameModalの表示
┗ VRT化

2022-03-23 04:35 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/2-basic-features/open-page-move-rename-modal.spec.ts
> +  });
rename と move 別れてるので、 どっちもつけた方がわかりやすいですよね。
PageRenameModal コンポーネントを PageMoveRenameModalにするべきなんじゃないかって思ってきた

2022-03-23 07:38 UTC, yuki-takei requested changes

2022-03-23 07:38 UTC, yuki-takei commented on packages/app/test/cypress/integration/2-basic-features/open-page-move-rename-modal.spec.ts
> +      cy.visit('/');
この visit いらないのでは？
今確認したら open-page-create-modal.spec.ts と open-page-delete-modal.spec.ts にもあったけど。

この操作があるとテストが地味に長くなりそう。

2022-03-24 04:23 UTC, kaoritokashiki commented
スコープ外になってしまいますが、ついでに open-page-create-modal.spec.ts と open-page-delete-modal.spec.ts の方の削除もお願いします。:pray:

2022-03-30 04:07 UTC, kaoritokashiki requested changes

2022-03-30 04:07 UTC, kaoritokashiki commented on packages/app/src/components/PageRenameModal.tsx
> +    <Modal size="lg" isOpen={isOpened} toggle={closeRenameModal} data-testid="page-rename-modal" className="grw-pagerename-page" autoFocus={false}>
すみません、これなんでclassName追加してるんでしょうか?? 必要なければ削除お願いします。

2022-03-30 07:53 UTC, kaoritokashiki approved these changes

2022-03-30 08:32 UTC, merged