feat: Remove child group
weseek/growi pull request #5600
Opened 2022-03-24 04:19 UTC by miya

## Task
[#91115](https://redmine.weseek.co.jp/issues/91115) [UserGroup] 詳細画面の子グループ一覧の歯車ドロップダウンから親を解除できる
┗ [#91119](https://redmine.weseek.co.jp/issues/91119) 実装

https://user-images.githubusercontent.com/34241526/159841134-3bd35056-ee4d-4d5c-a72a-f48a40c2e7dd.mov

2022-03-24 04:24 UTC, miya commented on packages/app/src/server/routes/apiv3/user-group.js
> +      body('parentId', 'ParentId must be a string or null').optional({ nullable: true }).isString(),
null 許容

2022-03-24 04:24 UTC, miya commented on packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +  };
remove ボタンが押された時に発火 parent を null にする

2022-03-24 04:24 UTC, miya commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +      mutateSelectableChildUserGroups();
子グループアップデート後、子供として選択可能なグループ（SelectableChildUserGroups）を mutate

2022-03-24 05:00 UTC, yuki-takei requested changes

2022-03-24 05:00 UTC, yuki-takei commented on packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +    userGroup.parent = null;
これは本来はクライアントが「タイミング」「処理内容」共に決めていいことではない。

ただ、「処理内容」を反映させるのが難しい事情があるのは理解した。(DOM を更新して読み直すことなどできないので)
そのため、せめて「タイミング」だけは修正する。少なくとも onRemove が正常終了してからこの処理を行う。

2022-04-04 16:53 UTC, miya commented on packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +    const requestParams = Object.assign({ ...userGroup }, { parent: null });
`userGroup` を shallow copy したオブジェクトと `{ parent: null }` をマージしたものを props.onRemove() に渡すようにしました。

2022-04-04 16:54 UTC, miya commented on packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +    userGroup.parent = null;
修正しました。
https://github.com/weseek/growi/pull/5600#discussion_r841953036

2022-04-05 07:28 UTC, yuki-takei requested changes

2022-04-05 07:28 UTC, yuki-takei commented on packages/app/resource/locales/ja_JP/translation.json
> +  "Remove": "解除",
parent の remove が「解除」っていう意味になるのは、UserGroup 編集だからだよね？
この K/V を定義する位置がグローバル過ぎると思う。

2022-04-05 07:28 UTC, yuki-takei commented on packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +    const requestParams = Object.assign({ ...userGroup }, { parent: null });
null を入れてあげないといけない責務は、onRemove イベントハンドラ(つまり UserGroupDetailPage.tsx)にある

2022-04-05 08:07 UTC, miya commented on packages/app/resource/locales/ja_JP/translation.json
> +  "Remove": "解除",
確かにユーザーグループ特有の言い回しだったので、`admin:user_group_management.remove_child_group` に作成しました。

2022-04-05 08:08 UTC, miya commented on packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +    const requestParams = Object.assign({ ...userGroup }, { parent: null });
UserGroupDetailPage.tsx に removeChildUserGroup を作成し、それを渡すように修正しました。

2022-04-05 08:50 UTC, yuki-takei requested changes

2022-04-05 08:50 UTC, yuki-takei commented on packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +      //
エラーが起こった時のことをよく考えて。これでは remove 失敗しても `userGroup.parent = null;` が実行される。
UserGroupDetailPage.tsx 側で catch してから再度 throw が必要。

2022-04-05 09:49 UTC, miya commented on packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +      //
以下のコミットで修正しました。
https://github.com/weseek/growi/pull/5600/commits/1f5500a1c659f7484da5520d87af2f861b3d37a1

2022-04-06 05:42 UTC, yuki-takei approved these changes

2022-04-06 05:43 UTC, merged