imprv: Security Setting UI
weseek/growi pull request #5611
Opened 2022-03-28 04:20 UTC by miya

## Task

[#90945](https://redmine.weseek.co.jp/issues/90945) 管理画面のページの削除に関する権限の UI を整理して見やすくする
┗ [#91052](https://redmine.weseek.co.jp/issues/91052) その他のオプションを開いた時に、注意書きを表示させる
┗ [#91283](https://redmine.weseek.co.jp/issues/91283) その他のオプションを強制変更する際に、隠れている Dropdown を表示させる

2022-03-28 11:29 UTC, miya commented on packages/app/src/client/services/AdminGeneralSecurityContainer.js
> +    this.setState({ expandOtherOptionsForCompleteDeletion: bool });
引数で bool を受け取るように変更

2022-03-28 11:29 UTC, miya commented on packages/app/src/components/Admin/Security/SecuritySetting.jsx
> -      : adminGeneralSecurityContainer.state.expandOtherOptionsForCompleteDeletion;
this.expandOtherOptions で取得できるように変更

2022-03-28 11:29 UTC, miya commented on packages/app/src/components/Admin/Security/SecuritySetting.jsx
> -    };
this.setExpantOtherOptions で setState できるように修正

2022-03-28 11:29 UTC, miya commented on packages/app/src/components/Admin/Security/SecuritySetting.jsx
> +      this.setExpantOtherDeleteOptionsState(deletionType, true);
shouldForceUpdate === true の時に強制的に collapse を open できるようにしました

2022-03-29 09:55 UTC, yuki-takei requested changes

2022-03-29 09:55 UTC, yuki-takei commented on packages/app/src/components/Admin/Security/SecuritySetting.jsx
> +        </div>
アラートは常に表示させず、注意を促さないといけないときにのみ表示する

2022-03-29 09:55 UTC, yuki-takei commented on packages/app/src/components/Admin/Security/SecuritySetting.jsx
> +        </div>
変更前の値も表示できたらしたい…

2022-03-31 07:55 UTC, miya reviewed
FB 修正後の新たな動画を撮ったので、PR の説明欄の確認をお願いします。

2022-03-31 07:55 UTC, miya commented on packages/app/src/components/Admin/Security/SecuritySetting.jsx
> +};
withTranslation 用のメソッド

2022-03-31 07:56 UTC, miya commented on packages/app/src/components/Admin/Security/SecuritySetting.jsx
> +        </div>
- Collapse が open になった時に、注意書きを表示できるように修正しました
- 設定が強制変更された場合、その旨と前回の設定を表示できるようにしました

2022-03-31 10:08 UTC, yuki-takei requested changes

2022-03-31 10:08 UTC, yuki-takei commented on packages/app/src/components/Admin/Security/SecuritySetting.jsx
> +    }
空文字列を null 値の代わりに使ってるのなんかいやだな

2022-03-31 10:29 UTC, miya commented on packages/app/src/components/Admin/Security/SecuritySetting.jsx
> +    }
null を入れるように修正しました。
state の初期値も null に修正しました。

2022-03-31 13:38 UTC, merged