WIP
weseek/growi pull request #5638
Opened 2022-03-31 09:39 UTC by Yohei-Shiina

2022-04-04 09:35 UTC, yuki-takei requested changes

2022-04-04 09:35 UTC, yuki-takei commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +        { !pageInfo.isEmpty && AdditionalMenuItems && (
ここは AdditionalMenuItems があれば表示、なければ非表示っていう単純なルールでいいと思うんだけど。
ここを弄らないと今回の目的達成できない？別の手段ないかな。

2022-04-04 09:35 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +      }
詳細設計変えよう。

- `page.data._id` が null じゃなければそこに遷移でよい
- なければ reload

2022-04-04 09:35 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +      {!pageInfo.isEmpty && !isCompactMode && (
revisionId を見る条件に統一するか、逆に pageInfo.isEmpty を見る条件に統一するか

2022-04-04 09:35 UTC, yuki-takei commented on packages/app/src/server/views/layout-growi/not_found.html
> +    data-empty-page-id="{%if emptyPageId %}{{emptyPageId|json}}{% endif %}"
`emptyPageId` っていうあたらしい概念を入れたくないな。実体がある場合と同じようにページIDがあるという情報を入れたい。

2022-04-06 05:02 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +      if (identicalPathPages.length < 2) return;
ここは return せずに length 1 の場合のような処理が走るようにしてください。

2022-04-06 05:03 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +      if (identicalPathPages.length < 2) return;
ここは return せずに length 1 の場合のような処理が走るようにしてください。

2022-04-06 05:03 UTC, hakumizuki requested changes
１箇所とりあえず修正お願いします。そのあともう一度見ます

2022-04-07 09:20 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +      if (identicalPathPages.length >= 2) {
これだと今度は pages.length === 1 の分岐を超えてしまいますね。

2022-04-08 06:27 UTC, Yohei-Shiina commented on packages/app/src/server/routes/page.js
> +  }
- 空ページを除いて、複数ページ該当した場合のリダイレクト処理

口頭でメソッドに切り出してほしいというFBだったので切り分け

2022-04-08 06:27 UTC, Yohei-Shiina commented on packages/app/src/server/routes/page.js
> +  async function redirectOperationForSinglePage(page, req, res) {
- 空ページを除いて、１ページのみ該当した場合のリダイレクト処理

口頭でメソッドに切り出してほしいというFBだったので切り分け

2022-04-08 06:27 UTC, Yohei-Shiina commented on packages/app/src/server/routes/page.js
> +  }
- 空ページを除いて、１ページのみ該当した場合のリダイレクト処理

口頭でメソッドに切り出してほしいというFBだったので切り分け

2022-04-08 06:29 UTC, Yohei-Shiina commented on packages/app/src/server/routes/page.js
> +    if (nonEmptyPageCount >= 1) { // Perform the operation only if nonEmptyPage(s) exist
空でないページが1つ以上ある時の処理

中身
- ページが2つ以上ある時の処理
- ページが一つのみの時の処理

2022-04-08 06:30 UTC, Yohei-Shiina commented on packages/app/src/server/routes/page.js
> +      const nonEmptyPage = pages.find(p => !p.isEmpty); // find the nonEmpty Page
pages には空と空でないページが混ざっている可能性があるので find

2022-04-08 06:30 UTC, Yohei-Shiina commented on packages/app/src/server/routes/page.js
> +    // Processing of nonEmptyPage is finished by the time this code is read
空でないページの処理はこの時点で終わっているので後続は、空ページへの処理

2022-04-08 09:16 UTC, yuki-takei requested changes

2022-04-08 09:16 UTC, yuki-takei commented on packages/app/src/server/service/page.ts
> +        isAbleToDeleteCompletely: true, // Todo: Restrict who can delete a page
このままじゃだめじゃない？

2022-04-18 14:04 UTC, hakumizuki commented
修正後に申し訳ないんですが、空ページの URL に関して仕様がまとまったのでそれに応じて再修正お願いします。
# 仕様
## 空ページのパーマリンクにアクセスした場合
### 前
- パスリンクにリダイレクト
- これによって今回クエリパラメータを使った修正をしようとしていた
### 後
- パーマリンクのままレスポンスを返す
- レスポンスを受け取ったクライアントは `location.history` API を使って URL バーの値をパスリンクに書き換える

これによって、クエリパラメータで情報を伝える機構は必要なくなります。
`_notFound` の空ページパーマリンク版みたいなのができる感じかなと思います(多分)

2022-06-15 12:06 UTC, Yohei-Shiina commented on packages/app/src/components/NotFoundPage.tsx
> +  }, [pageId, path, notFoundTargetPathOrId]);
空ページにパーマリンクでアクセスしてきた場合に、フロント側でパスリンクに変更する箇所

pageId は 存在するページへのアクセスの時に値が入る
notFoundTargetPathOrId はパスリンクでアクセスしてきたら Page の path, permalink でアクセスしてきた場合は permalink が入る

2022-06-16 06:22 UTC, hakumizuki requested changes

2022-06-16 06:22 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +      const nonEmptyPage = pages.find(p => !p.isEmpty); // find the nonEmpty Page
これ `nonEmptyPages[0]` じゃだめなんですか？

2022-06-16 06:22 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +      return redirectOperationForSinglePage(nonEmptyPage, req, res);
これもはやなんでメソッドに区切るべきだと言ったのかわからないんですが、区切らない方がみやすい&統一されてていいですね

2022-06-16 06:22 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +  }
これもはやなんでメソッドに区切るべきだと言ったのかわからないんですが、区切らない方がみやすい&統一されてていいですね

2022-06-16 06:22 UTC, hakumizuki commented on packages/app/src/components/NotFoundPage.tsx
> +    if (pageId != null && path != null && !notFoundTargetPathOrId?.includes('/')) {
これって `!notFoundTargetPathOrId?.includes('/')` この条件だけじゃだめなんですかね？
NotFound なら絶対 path で replaceURLHistory するってコードの方が簡潔&より意味にあってる気がするんですが

あと変数に入れた方がいいですね。あとなぜ includes を使ってるんでしょう？

2022-06-16 06:22 UTC, hakumizuki commented on packages/app/src/server/routes/page.js
> +      req.pagePath = page.path;
ファイル名がどっちも違うような気が ...

2022-06-17 04:50 UTC, Yohei-Shiina commented on packages/app/src/server/routes/page.js
> +      const nonEmptyPage = pages.find(p => !p.isEmpty); // find the nonEmpty Page
ダメじゃないですね。1しかないのは完全確定しているので `nonEmptyPages[0]` に書き直します

2022-06-17 04:51 UTC, Yohei-Shiina commented on packages/app/src/server/routes/page.js
> +  }
切り出した方は消しました

2022-06-20 06:47 UTC, hakumizuki requested changes

2022-06-20 06:47 UTC, hakumizuki commented on packages/app/src/components/NotFoundPage.tsx
> +    const isPathLink = notFoundTargetPathOrId?.includes('/');
`isPathExist` って `path != null` と全く同じ意味を持ってるので変数に入れる意味ないと思います。むしろ Exist の方が厳密性が失われている気も。
また、`isPathLink` よりも `isPermalink` が欲しいですよね？
なので増山ならこうします↓

```typescript
if (path == null {
  return;
}

const isEmptyPage = pageId != null;
const isPermalink= !notFoundTargetPathOrId?.includes('/');
if (isEmptyPage && isPermalink) {
  replaceURLHistory(path);
}
```

2022-06-20 06:47 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +schema.statics.findNotEmptyClosestAncestor = async function(path: string): Promise<PageDocument> {
このメソッド、トップページのとき undefined が帰ってくるのではないでしょうか？

2022-06-20 06:47 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/page-listing.ts
> +        const basicPageInfo = await pageService.constructBasicPageInfo(page, req.user);
これ今気づいたんですが一気に DB との通信増えちゃってますね。おそらく 1クエリで実現できるので改善お願いします。

2022-06-20 10:58 UTC, Yohei-Shiina commented on packages/app/src/server/routes/apiv3/page-listing.ts
> +        const basicPageInfo = await pageService.constructBasicPageInfo(page, req.user);
ブランチの管理（関連ブランチのマージ先）等をミスしてしまったかもで、見なくてよい差分かもしれません。

こちら優先で #6075 を優先でレビューお願いします

2022-06-21 04:53 UTC, Yohei-Shiina commented on packages/app/src/components/NotFoundPage.tsx
> +    const isPathLink = notFoundTargetPathOrId?.includes('/');
これで対応しました

2022-06-21 05:39 UTC, Yohei-Shiina commented on packages/app/src/server/models/page.ts
> +schema.statics.findNotEmptyClosestAncestor = async function(path: string): Promise<PageDocument> {
undefined の型も追加しました

2022-06-21 06:56 UTC, Yohei-Shiina commented on packages/app/src/stores/ui.tsx
> +    (includesUndefined || isEmptyPageInNotFoundContext) ? null : key,
これで対応するので無視してください
https://redmine.weseek.co.jp/issues/98424

2022-06-21 06:56 UTC, Yohei-Shiina commented on packages/app/src/stores/ui.tsx
> +  useCurrentPageId, useCurrentPagePath, useIsEditable, useIsTrashPage, useIsUserPage, useIsGuestUser, useIsEmptyPageInNotFoundContext,
無視で大丈夫です

2022-06-21 06:57 UTC, Yohei-Shiina commented on packages/app/src/stores/context.tsx
> +};
これで対応するので無視してください
https://redmine.weseek.co.jp/issues/98424

2022-06-21 07:04 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +    }
`constructBasicPageInfo` 内で実行されていた、実態のある祖先ページの creatorId の取得を外にだした。

2022-06-21 08:39 UTC, hakumizuki requested changes

2022-06-21 08:39 UTC, hakumizuki commented on packages/app/src/stores/ui.tsx
> +    (includesUndefined || isEmptyPageInNotFoundContext) ? null : key,
これって何が問題で、どんな対応する感じですか？

2022-06-21 08:39 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> -    await this.updateDescendantCountOfAncestors(page._id, -page.descendantCount, false);
このメソッド自体解体してください。責務ぐちゃぐちゃすぎて目も当てられないですね(著: 増山)

2022-06-22 05:07 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> -    await this.updateDescendantCountOfAncestors(page._id, -page.descendantCount, false);
`deleteEmptyTarget` のこと

2022-06-22 05:26 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> -    await this.updateDescendantCountOfAncestors(page._id, -page.descendantCount, false);
解体した

2022-06-22 05:40 UTC, merged