imprv: vrt create edit template bootstrap4
weseek/growi pull request #5644
Opened 2022-04-01 02:58 UTC by asami-n

## Task
[GW-7766](https://youtrack.weseek.co.jp/issue/GW-7766) サブナビゲーションからのCreate/Edit Template Modalの表示
┗ VRT化
![access-to-page-template-modal-open-bootstrap4](https://user-images.githubusercontent.com/97593712/161186456-9f72912c-a8fc-44a2-9d61-fe117228fb0c.png)

2022-04-01 06:53 UTC, kaoritokashiki approved these changes

2022-04-01 08:31 UTC, yuki-takei requested changes

2022-04-01 08:31 UTC, yuki-takei commented on packages/app/test/cypress/integration/2-basic-features/open-page-create-edit-template-modal.spec.ts
> +});
1. 既存の .spec.ts に追加してください。(ファイルが増えると CI にかかる時間が大きく増加するので)
1. before, beforeEach 周りが最新の master ではスリム化されているので、そちらを参考にアップデートしてください
1. モーダル内のボタンをクリックした時に、テンプレートページの URL に遷移することを assertion してください

2022-04-01 09:20 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/2-basic-features/open-page-create-edit-template-modal.spec.ts
> +});
>既存の .spec.ts に追加してください。
- presentation と同じファイルに追加で良いと思います。ファイル名はよしなに変える必要があります

2022-05-30 19:51 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/2-basic-features/moving-to-presentation-modal-and-templete-editor-mode.spec.ts
> +  });
同一階層のtemplete page

2022-05-30 19:51 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/2-basic-features/moving-to-presentation-modal-and-templete-editor-mode.spec.ts
> + });
子孫を含むtemplete page

2022-05-31 01:07 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/2-basic-features/open-page-create-edit-template-modal.spec.ts
> +});
> 1. 既存の .spec.ts に追加してください。(ファイルが増えると CI にかかる時間が大きく増加するので)
thempleteは、 `20-basic-features/access-to-modal.spec.ts`に追加

plesentation modal は、`20-basic-features/access-to-modal.spec` を作成して、そちらに移動させたのですがよかったでしょうか? これも`20-basic-features/access-to-modal.spec.ts`の中で良いということであればFB対応にて移動させます。

2022-05-31 01:08 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
> +     cy.screenshot();
> 3. モーダル内のボタンをクリックした時に、テンプレートページの URL に遷移することを assertion してください
編集画面までをassertionしました。

2022-05-31 01:19 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
> +  it('Access to Template Editor mode for only child pages successfully', () => {
**同一階層**のtemplete page 編集画面へ行くまでのtest

2022-05-31 01:19 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
> +  it('Access to Template Editor mode including decendants successfully', () => {
**子孫ページを含む** templete page 編集画面へ行くまでのtest

2022-05-31 05:06 UTC, yuki-takei requested changes

2022-05-31 05:06 UTC, yuki-takei commented on packages/app/test/cypress/integration/20-basic-features/access-to-modal.spec.ts
> +});
こちらも access-to-page.spec.ts にマージ

2022-05-31 21:49 UTC, kaoritokashiki commented on packages/app/test/cypress/integration/20-basic-features/access-to-modal.spec.ts
> +});
presentation modal は既に `use-tools.spec.ts` にありましたので、削除いたしました。

2022-05-31 22:10 UTC, merged