Imprv/remove toc in empty page
weseek/growi pull request #5661
Opened 2022-04-05 04:13 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/91999

2022-04-05 04:15 UTC, Yohei-Shiina commented on packages/app/src/client/services/ContextExtractor.tsx
> +  useIsEmptyPageContext(notFoundContent != null && pageId != null);
notFoundContext 内で、pageId が存在する = empty なページを表示している

という判定

2022-04-06 05:14 UTC, hakumizuki commented on packages/app/src/components/Page/DisplaySwitcher.tsx
>                      <ContentLinkButtons />
`ContentLinkButtons` は外さなくて OK ですか？

2022-04-06 05:28 UTC, hakumizuki requested changes
修正必要だったら修正お願いします

2022-04-06 05:28 UTC, hakumizuki commented on packages/app/src/components/Page/DisplaySwitcher.tsx
>                      <ContentLinkButtons />
`ContentLinkButtons` は外さなくて OK ですか？

2022-04-06 05:28 UTC, hakumizuki commented on packages/app/src/stores/ui.tsx
> +    includesUndefined || isEmptyPageInNotFoundContext ? null : key,
`(includesUndefined || isEmptyPageInNotFoundContext) ? null : key` にするとさらに読みやすくなりそうな気がしています

2022-04-06 06:09 UTC, Yohei-Shiina commented on packages/app/src/components/Page/DisplaySwitcher.tsx
>                      <ContentLinkButtons />
各userのページでしか表示されないのでこのままで大丈夫です

2022-06-17 07:43 UTC, merged