Imprv/gw7770 closing eoji picker
weseek/growi pull request #5675
Opened 2022-04-06 11:46 UTC by kaoritokashiki

2022-04-06 12:08 UTC, kaoritokashiki commented
blur結局使ってないですね...

2022-04-06 13:34 UTC, yuki-takei requested changes

2022-04-06 13:34 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    document.addEventListener('click', this.handleDocumentClick);
- onBlur を使わなかった理由は？
- 設定したイベントリスナーは、componentWillUnmount で removeEventListener する必要がある

2022-04-06 14:44 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    document.addEventListener('click', this.handleDocumentClick);
## onBlur を使わなかった理由は？
blur を使おうとすると、conponentDidMountに以下のような記述をすると思うのですが、
```
const emojiPickerElm = document.querySelector('.emoji-mart');
emojiPickerElm. addEventListener('blur', handleHoge)
```
この時
`emojiPickerElm` のnull checkを挟まないといけなくなります。
conponentDidMount は一度しか実行されないので、emojiPickerElmは必ずnull となり、addEventListenerが動作しないです。

## 設定したイベントリスナーは、componentWillUnmount で removeEventListener する必要がある
失念していました。追加しました。

2022-04-06 14:56 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    document.addEventListener('click', this.handleDocumentClick);
ん、conponentDidMount じゃなくて componentDidUpdate に記述すれば解決か...?

2022-04-06 15:13 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    document.addEventListener('click', this.handleDocumentClick);
componentDidUpdate x blurで試してみましたが、そもそも 何を持ってfocusされているのかがわからないですね。

```
  componentDidUpdate() {
    const emojiPickerElm = document.querySelector('.emoji-mart');
    if (emojiPickerElm != null) {
      emojiPickerElm.addEventListener('blur', this.hoge);
    }
  }

  componentWillUnmount() {
    const emojiPickerElm = document.querySelector('.emoji-mart');
    emojiPickerElm.removeEventListener('blur', this.handleDocumentClick);
  }

  hoge(event) {
    const emojiBtnElm = document.getElementById('emoij-btn');
    console.log('blur実行されてる?'); //実行されない

    if (!emojiBtnElm.contains(event.target)) {
      this.setState({ isEmojiPickerShown: false });
    }
  }

```

2022-05-13 05:57 UTC, kaoritokashiki commented
別タスクで対応済みなのでcloseします。

2022-05-13 05:57 UTC, closed without merging