feat: Implement method to find non-empty ancestor page to determine whether empty page is deletable
weseek/growi pull request #5698
Opened 2022-04-12 07:40 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/92721

2022-04-13 04:45 UTC, Yohei-Shiina commented on packages/app/src/server/routes/apiv3/page-listing.ts
> +
自動整形による修正

2022-04-13 04:48 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +
自動整形による修正

2022-04-13 04:53 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +      // Use creator id of ancestor page to determine whether the empty page is deletable
空ページは creator を持たないので 一番近い空でない祖先の creator を見るようにする

2022-04-13 04:54 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +    const isAbleToDeleteCompletely = isGuestUser && isMovable ? false : this.canDeleteCompletely(page.creator, operator, false); // use normal delete config
第1引数のみ上と異なる

2022-04-13 05:19 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +  canDeleteCompletely(creatorId: ObjectIdLike | Ref<IUserHasId>, operator:IUserHasId, isRecursively: boolean): boolean {
引数の名前と `| Ref<IUserHasId>` この部分の型はマッチしてなさそうです。 ObjectIdLike だけでいいと思うのですがどうでしょうか？

2022-04-13 05:30 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +  async findNotEmptyClosestAncestor(path: string): Promise<PageDocument> {
これは Model 層にあった方がいいレベルのメソッドですね。特別な理由がなければ移動お願いします。

2022-04-13 05:34 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      const isAbleToDeleteCompletely = isGuestUser && !isMovable ? false : this.canDeleteCompletely(creatorId, operator, false); // use normal delete config
ここは `!isGuestUser` じゃなくて OK ですか？

2022-04-13 05:44 UTC, hakumizuki requested changes
いくつかきになるところコメントしてみました。回答お願いします

2022-04-14 02:39 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +      const isAbleToDeleteCompletely = isGuestUser && !isMovable ? false : this.canDeleteCompletely(creatorId, operator, false); // use normal delete config
isGuestUserはいらなかったですね

isMovable がない場合、ゲストユーザーでページにアクセスすると　operator がいないので以下のエラーになります
```
02:37:26.102Z ERROR growi:routes:apiv3:page:
  get-page-info TypeError: Cannot read properties of undefined (reading 'admin')
      at PageService.canDeleteLogic (/workspace/growi/packages/app/src/server/service/page.ts:243:30)
      at PageService.canDelete (/workspace/growi/packages/app/src/server/service/page.ts:233:17)
      at PageService.constructBasicPageInfo (/workspace/growi/packages/app/src/server/service/page.ts:2123:30)
      at PageService.findPageAndMetaDataByViewer (/workspace/growi/packages/app/src/server/service/page.ts:307:33)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at /workspace/growi/packages/app/src/server/routes/apiv3/page.js:367:28
```

2022-04-14 02:42 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +  canDeleteCompletely(creatorId: ObjectIdLike | Ref<IUserHasId>, operator:IUserHasId, isRecursively: boolean): boolean {
page.creator が Ref<IUser> になってるので id 持ってることも考慮して `Ref<IUserHasId>` にしました

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/35527421/163303258-2de33b01-2999-4668-8804-f4dcd685cd4e.png">

2022-04-14 02:54 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +  canDeleteCompletely(creatorId: ObjectIdLike | Ref<IUserHasId>, operator:IUserHasId, isRecursively: boolean): boolean {
IPage の creator の型指定にObjectIdLikeが足りないのかな

<img width="216" alt="image" src="https://user-images.githubusercontent.com/35527421/163304216-28786b00-1f97-4fc8-824a-0802427eddfe.png">

2022-04-14 02:57 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +  canDeleteCompletely(creatorId: ObjectIdLike | Ref<IUserHasId>, operator:IUserHasId, isRecursively: boolean): boolean {
IUserHasId については使わない方向にします。

2022-04-14 02:59 UTC, Yohei-Shiina commented on packages/app/src/interfaces/page.ts
> +import { IUser } from './user';
自動整形による修正なので無視でよい

2022-04-14 03:00 UTC, Yohei-Shiina commented on packages/app/src/interfaces/page.ts
> +import { ObjectIdLike } from '~/server/interfaces/mongoose-utils';
これだけ新規

2022-04-14 03:01 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +  canDeleteCompletely(creatorId: ObjectIdLike | Ref<IUserHasId>, operator:IUserHasId, isRecursively: boolean): boolean {
アプリが動作しなくなるわけではないです

2022-04-15 08:11 UTC, hakumizuki commented on packages/app/src/interfaces/page.ts
> +import { ObjectIdLike } from '~/server/interfaces/mongoose-utils';
mongoose のコードはフロントエンドには持ち込めないので、このファイル内でこのインポートはダメです。これが解決されるのは前にお伝えした Model 層の TS 化が完全に済んだ時になるので、IHogeModel 系のインターフェースは使わない方向で大丈夫です(any で妥協しても良い)

2022-04-15 08:19 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      const isDeletable = !isMovable ? false : this.canDelete(creatorId, operator, false);
isMovable はなくしたいですねこの行から

2022-04-18 15:50 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +  const { PageQueryBuilder } = Page;
ここの行不要ですね

2022-06-17 07:44 UTC, merged