fix: Page view count stops at 15
weseek/growi pull request #5705
Opened 2022-04-13 04:42 UTC by miya

## Task

[#92069](https://redmine.weseek.co.jp/issues/92069) [bug] ページ右上の足跡アイコンの数値と、画面左メニューの「最近の更新」で表示される足跡アイコンの数値が、同じページでも異なる場合がある
┗ [#92805](https://redmine.weseek.co.jp/issues/92805) 修正

2022-04-13 09:15 UTC, yuki-takei requested changes

2022-04-13 09:15 UTC, yuki-takei commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const sumOfSeenUsers = pageInfo?.sumOfSeenUsers != null ? pageInfo.sumOfSeenUsers : 0;
slice したリストの length を入れてるのがおかしいのでそれを直す

2022-04-15 02:41 UTC, miya commented on packages/app/src/server/routes/apiv3/page.js
> +        seenUserIds: page.seenUsers,
バックエンドで slice したものを返していたので、そのまま返す

2022-04-15 02:41 UTC, miya commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const sumOfSeenUserIds = pageInfo?.seenUserIds.length || 0;
seenUserIds の length と一致するようにしました

2022-04-15 02:41 UTC, miya commented on packages/app/src/components/User/SeenUserInfo.tsx
> +  const sumOfSeenUsers = pageInfo?.sumOfSeenUsers != null ? pageInfo.sumOfSeenUsers : 0;
修正しました。

2022-04-15 04:34 UTC, merged