imprv: Add testcode for page model user-group
weseek/growi pull request #5706
Opened 2022-04-13 08:30 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/92670

2022-06-10 08:19 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +        test('successfully change to GRANT_USER_GROUP from GRANT_PUBLIC if parent page is GRANT_PUBLIC', async() => {
GRANT_PUBLIC なページ配下のページの権限をGRANT_USER_GROUPに変更することができること

2022-06-10 08:19 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +        test('successfully change to GRANT_USER_GROUP from GRANT_RESTRICTED if parent page is GRANT_PUBLIC', async() => {
GRANT_PUBLIC なページ配下のページの権限を GRANT_RESTRICTED から GRANT_USER_GROUPに変更することができること

2022-06-10 08:42 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +        test('successfully change to GRANT_USER_GROUP if the group to set is the child or descendant of the parent page group', async() => {
GRANT_USER_GROUP なページ配下のページの権限を GRANT_RESTRICTED から GRANT_USER_GROUPに変更することができること

2022-06-10 08:49 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +        test('Fail to change to GRANT_USER_GROUP if the group to set is NOT the child or descendant of the parent page group', async() => {
以下条件では、GRANT_USER_GROUP なページ配下のページの権限を GRANT_USER_GROUPに変更できないこと
- 変更先のグループが、親グループの子孫ではない

2022-06-10 08:50 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +        test('Fail to change to GRANT_USER_GROUP if the group to set is an ancestor of the parent page group', async() => {
以下条件では、GRANT_USER_GROUP なページ配下のページの権限を GRANT_USER_GROUPに変更できないこと
- 変更先のグループが、親グループの祖先である

2022-06-10 08:51 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +        test('Fail to change from GRNAT_OWNER', async() => {
GRANT_OWNERなページ配下のページの権限を GRNAT_OWNER からそれ以外に変更することができないこと

2022-06-10 08:51 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +      },
↑ここまでで1セット

2022-06-10 08:52 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +      },
↑ここまでで1セット

2022-06-10 08:53 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +      },
↑ここまでで1セット

2022-06-10 08:53 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +      },
↑ここまでで1セット

2022-06-10 08:53 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +      },
↑ここまでで1セット

2022-06-10 08:53 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +      },
↑ここまでで1セット

2022-06-10 08:53 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +      },
↑ここまでで1セット

2022-06-21 08:22 UTC, hakumizuki requested changes

2022-06-21 08:22 UTC, hakumizuki commented on packages/app/test/integration/models/v5.page.test.js
>            expect(_page2).toBeTruthy();
ここも parent お願いします

2022-06-21 08:22 UTC, hakumizuki commented on packages/app/test/integration/models/v5.page.test.js
>            expect(_page2).toBeTruthy();
ここも parent お願いします

2022-06-21 08:22 UTC, hakumizuki commented on packages/app/test/integration/models/v5.page.test.js
>            expect(_page2).toBeTruthy();
ここも parent お願いします

2022-06-21 08:29 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +        const path = '/mup40';
コンフリクト解消の結果新しい箇所で `mup24` 使うことになったので、既存のものを mup40 に変更しました

https://github.com/weseek/growi/pull/5706/files#diff-da75b559bdbc148fa9b2aab2a968d49165303f78aa6b2eec62ef55d617fe25caR478

2022-06-27 02:34 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +          const _page2 = await Page.findOne({ path: path2, grant: Page.GRANT_PUBLIC }); // update target
条件に入れました

2022-06-27 02:44 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +        test('successfully change to GRANT_USER_GROUP if the group to set is the child or descendant of the parent page group', async() => {
すみませんこれはコメントを間違えました。
 owner からが正しいです

2022-06-27 02:55 UTC, Yohei-Shiina commented on packages/app/test/integration/models/v5.page.test.js
> +          expect(secondRoundUpdatedPage.grantedGroup._id).toStrictEqual(groupIdC);
grantUserGroupId はページを作成するときの引数名でページモデルが持つ値ではないです。
正しい値で更新されているかは↓のexpectでしています。
`expect(secondRoundUpdatedPage.grantedGroup._id).toStrictEqual(groupIdC);`

2022-07-01 03:57 UTC, hakumizuki approved these changes

2022-07-01 04:17 UTC, merged