Support/92828 test for force update of user group
weseek/growi pull request #5707
Opened 2022-04-13 11:08 UTC by kaoritokashiki

2022-04-18 08:04 UTC, kaoritokashiki commented on packages/app/test/integration/service/v5.user-groups.test.ts
> +  }, 80000);
`Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."` 
のエラー解消のため、timeoutの時間を `80000`にしてみたが、エラーがで続けてしまう

2022-04-18 08:04 UTC, kaoritokashiki commented on packages/app/test/integration/service/v5.user-groups.test.ts
> +  }, 80000);
`Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."` 
のエラー解消のため、timeoutの時間を `80000`にしてみたが、エラーがで続けてしまう

2022-04-27 03:00 UTC, kaoritokashiki commented on packages/app/test/integration/service/v5.user-groups.test.ts
> +  }, 80000);
解決しました。

2022-04-27 03:02 UTC, kaoritokashiki commented on packages/app/test/integration/service/user-groups.test.ts
> +        relatedUser: user1,
id をそのままセットしているtest fileと、 find したものをセットしているtest fileがあってどっちの方法がいいのかな? と思いつつfind 使いました。

2022-04-27 03:07 UTC, kaoritokashiki commented on packages/app/test/integration/service/user-groups.test.ts
> +  test('Should throw an error when users in child group do not include in parent group', async() => {
この説明で伝わるかな....?

2022-04-28 05:52 UTC, hakumizuki requested changes
すみません一個追加があります。

- groupA(user1)
  - groupB()

- groupC(user1)

がいるときに

groupC のを forceUpdate true で groupB にしたときに、
- groupA(user1 が一つのみ)
- groupB(user1)
- groupC(user1)

の状態になることを確認するテストをお願いします。

2022-04-28 05:52 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +        relatedUser: user1,
結果は同じなので groupId4 を使ったらいいと思います。find 使ってるとこはむしろ直して欲しいくらいです

2022-04-28 05:52 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +  test('Should throw an error when users in child group do not include in parent group', async() => {
do not include => do not exist ですかね

2022-04-28 05:52 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +    const userGroup4Relation = await UserGroupRelation.findOne({ relatedGroup:  userGroup4 });
テストコード増やしてったときにこれだと relation document が確定しないので、relatedUser も指定してください

2022-05-06 09:16 UTC, kaoritokashiki commented on packages/app/test/integration/service/user-groups.test.ts
> +  });
🆕 新しく追加しました。

2022-05-06 09:18 UTC, kaoritokashiki commented on packages/app/test/integration/service/user-groups.test.ts
> +    const userGroup4Relation = await UserGroupRelation.findOne({ relatedGroup:  userGroup4 });
追加しました!

2022-05-09 06:28 UTC, hakumizuki requested changes

2022-05-09 06:28 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +    const userGroup4 = await UserGroup.findOne({ _id: groupId4 });
ここにクエリを加えて、parent がもともとあるのかどうかを見せておくとさらに読みやすくなるかと思います

2022-05-09 06:28 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +    const relatedGroup = await UserGroupRelation.findOne({ relatedGroup: groupId5, relatedUser: userGroup4Relation.relatedUser });
変数名は UserGroupRelation のドキュメントであることがわかるようにしてください

2022-05-09 06:28 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +    const relatedGroup8 = await UserGroupRelation.findOne({ relatedGroup: groupId8, relatedUser: userId1 });
変数名は UserGroupRelation のドキュメントであることがわかるようにしてください

2022-05-09 06:28 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +    const userGroup8 = await UserGroup.findOne({ _id: groupId8 });
ここも上と同じようにクエリを足しておくといいと思います

2022-05-09 06:28 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +    const userGroup4Relation = await UserGroupRelation.findOne({ relatedGroup:  userGroup4, relatedUser: userId1 });
`updateGroup`  実行前後の両方でなんの relation が存在しているのかいないのかを expect しておくといいと思います

2022-05-09 06:28 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +
`updateGroup`  実行前後の両方でなんの relation が存在しているのかいないのかを expect しておくといいと思います

2022-05-10 07:20 UTC, hakumizuki requested changes

2022-05-10 07:20 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +    expect(userGroupRelation5BeforeUpdate).toBeNull();
細かい話なんですが、`userGroupRelation4`, `userGroupRelation5BeforeUpdate` で BeforeUpdate が付いてたりついてなかったりするのは理由ありますか？

あと、他のテストコードと統一感出すならば、

```typescript
const hoge1 = find()
const hoge2 find()

expect(hoge1).toBeNull()
expect(hoge2).not.toBeNull()
```

のようなコード構成にすると読みやすいと思います

2022-05-10 07:20 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +    expect(userGroupRelation7BeforeUpdate).toBeNull();
6, 7, 8 を updateGroup の後に expect してるので、 updateGroup の前にもチェックして欲しいです

2022-05-12 03:40 UTC, kaoritokashiki commented on packages/app/test/integration/service/user-groups.test.ts
> +    expect(userGroupRelation5BeforeUpdate).toBeNull();
>細かい話なんですが、userGroupRelation4, userGroupRelation5BeforeUpdate で BeforeUpdate が付いてたりついてなかったりするのは理由ありますか？

あああ、userGroupRelation4 に関しては、UpdateのBeforeとAfterでexpectを実行しているので、異なる変数になるように Before/Updateをつけました。
他のもBeforeUpdateつけますね 

>expect(hoge2).not.toBeNull()
なるほどです。　そのように修正しました

2022-05-12 04:11 UTC, merged