feat: gr84030 add count badge in toc
weseek/growi pull request #5724
Opened 2022-04-18 08:12 UTC by yukendev

https://redmine.weseek.co.jp/issues/84030

2022-04-18 10:21 UTC, yukendev commented on packages/app/src/components/Page/DisplaySwitcher.tsx
> +
自動成型で修正が入っています

2022-04-18 12:11 UTC, yuki-takei requested changes

2022-04-18 12:11 UTC, yuki-takei commented on packages/app/src/components/Common/CountBadge.tsx
> +      <span className="grw-count-badge px-2 badge badge-pill badge-light">
DisplaySwitcher で使う場合の badge の色を css で指定しないといけない。

2022-04-19 03:14 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors-light.scss
> +
## 前提
他のテーマにも影響する色指定にgray系カラーを使用するのはNGとされています。(以下リンク参照)
https://redmine.weseek.co.jp/issues/90386


また、XD 見た感じ、gray系カラーではないので修正お願いします！

<img width="685" alt="Screen Shot 2022-04-19 at 12 03 00" src="https://user-images.githubusercontent.com/59536731/163912157-89804b30-d450-4155-ae00-860012c51fdc.png">

## Note

2022-04-19 03:25 UTC, kaoritokashiki requested changes

2022-04-19 03:25 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors-light.scss
> +
## 前提
他のテーマにも影響する色指定にgray系カラーを直に指定するのはNGとされています。(以下リンク参照)
https://redmine.weseek.co.jp/issues/90386

また、XD 見た感じ、colorは gray系カラーではないので修正お願いします！
<img width="685" alt="Screen Shot 2022-04-19 at 12 03 00" src="https://user-images.githubusercontent.com/59536731/163912157-89804b30-d450-4155-ae00-860012c51fdc.png">
bgcolorは $ lightで良さそう

2022-04-19 03:25 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors-dark.scss
> +
dark themeの配色は、light themeと同じでいいのかmosさんに確認する必要がありそうです。
(NGな気がしている....:eyes:)

2022-04-20 04:50 UTC, yukendev commented
このストーリーではいったんgray系の直接指定でいいとのことです。
https://wsgrowi.slack.com/archives/C0111HG81GB/p1650376381513609?thread_ts=1650357683.050379&cid=C0111HG81GB

2022-04-20 04:58 UTC, kaoritokashiki approved these changes

2022-04-20 04:58 UTC, merged