fix: Get attachment list api without "page" parameter returns 500 response
weseek/growi pull request #5726
Opened 2022-04-18 09:40 UTC by miya

## Task

[#93137](https://redmine.weseek.co.jp/issues/93137) [GROWI][issue][5.0.x] Bug: Get attachment list API without "page" parameter returns 500 response
┗ [#93138](https://redmine.weseek.co.jp/issues/93138) 修正

2022-04-18 09:52 UTC, miya commented on packages/app/src/components/PageAttachment.jsx
> +import PageAttachmentList from './PageAttachment/PageAttachmentList';
自動整形

2022-04-18 09:52 UTC, miya commented on packages/app/src/server/routes/apiv3/attachment.js
> +const { serializeUserSecurely } = require('../../models/serializers/user-serializer');
自動整形

2022-04-18 09:52 UTC, miya commented on packages/app/src/server/routes/apiv3/attachment.js
> +      query('page').isInt({ min: 1 }).withMessage('page is required and must be set to a number greater than 1'),
`page` クエリを必須にしました。

2022-04-18 16:27 UTC, miya commented on packages/app/src/server/routes/apiv3/attachment.js
> +      query('page').isInt({ min: 1 }).withMessage('page must be a number greater than or equal to 1'),
`page` を必須かつ、最低1以上の数値を入力するようなバリデーションを追加しました。

2022-04-19 11:07 UTC, yuki-takei requested changes

2022-04-19 11:07 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/attachment.js
> +      query('page').isInt({ min: 1 }).withMessage('page must be a number greater than or equal to 1'),
必須にする必要はない

2022-04-19 12:08 UTC, miya commented on packages/app/src/server/routes/apiv3/attachment.js
> +      query('page').isInt({ min: 1 }).withMessage('page must be a number greater than or equal to 1'),
optional にしました。

2022-04-19 12:09 UTC, miya commented on packages/app/src/server/routes/apiv3/attachment.js
> +      query('page').optional().isInt().withMessage('page must be a number'),
optional に修正

2022-04-19 12:09 UTC, miya commented on packages/app/src/server/routes/apiv3/attachment.js
> +      query('limit').optional().isInt({ max: 100 }).withMessage('You should set less than 100 or not to set limit.'),
(value => value != null) というのが不自然だったので optional() に書き換えました

2022-04-19 12:09 UTC, miya commented on packages/app/src/server/routes/apiv3/attachment.js
> +    const page = req.query.page || 1;
undefined だったら 1 を代入

2022-04-19 14:19 UTC, merged