imprv: Redesign tags
weseek/growi pull request #5730
Opened 2022-04-19 05:19 UTC by miya

2022-04-22 13:25 UTC, yuki-takei requested changes

2022-04-22 13:25 UTC, yuki-takei commented on packages/app/src/components/Sidebar/Tag.tsx
> +    setOffset((selectedPageNumber - 1) * 10);
マジックナンバー(10)を消す

2022-04-22 13:25 UTC, yuki-takei commented on packages/app/src/components/Sidebar/Tag.tsx
> +            activePage={1 + (offset / 10)} // activePage = 1 + offset / 10
マジックナンバー(10)を消す

2022-04-24 16:40 UTC, miya commented on packages/app/src/components/Sidebar/Tag.tsx
> +    setOffset((selectedPageNumber - 1) * 10);
定数を利用したもに修正しました。

2022-04-24 16:40 UTC, miya commented on packages/app/src/components/Sidebar/Tag.tsx
> +            activePage={1 + (offset / 10)} // activePage = 1 + offset / 10
定数を利用したもに修正しました。

2022-04-24 17:43 UTC, merged

2022-04-25 22:32 UTC, yuki-takei commented on packages/app/src/components/TagList.tsx
> +          <div className="ml-4 my-auto py-1 px-2 list-tag-count badge badge-secondary text-white">{tag.count}</div>
どうなんだろうね、badge-secondary がテーマに依らず変化しないものというルールを改めて定めるなら大丈夫なのかもしれない。

2022-04-26 01:02 UTC, kaoritokashiki commented on packages/app/src/components/TagList.tsx
> +          <div className="ml-4 my-auto py-1 px-2 list-tag-count badge badge-secondary text-white">{tag.count}</div>
darkテーマに white #fff ?が当たってしまうのはうーん、って思ってしまいますね。