feat: add method to restart rename page operation
weseek/growi pull request #5739
Opened 2022-04-20 11:35 UTC by Yohei-Shiina

2022-04-21 02:15 UTC, Yohei-Shiina commented on packages/app/test/integration/global-setup.js
> +    },
global なユーザーとグループを作成した

2022-04-21 03:18 UTC, Yohei-Shiina commented on packages/app/src/server/crowi/index.js
>  const PluginService = require('../plugins/plugin.service');
eslint 自動修正

2022-04-21 03:20 UTC, Yohei-Shiina commented on packages/app/src/server/crowi/index.js
> +
サーバー起動時に残っている Rename の PageOperation を残して他はすべて削除

残った PageOperation の `isFailure` を全て`true`にセット

2022-04-21 03:21 UTC, Yohei-Shiina commented on packages/app/src/server/models/page-operation.ts
> +
eslint による自動修正

2022-04-21 03:21 UTC, Yohei-Shiina commented on packages/app/src/server/models/page-operation.ts
> +};
引数のActionTypeを除いたすべてのPageOperation削除

2022-04-21 03:22 UTC, Yohei-Shiina commented on packages/app/src/server/models/page-operation.ts
> +};
PageOperation 全ての isFailure を true

2022-04-21 03:38 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +import { HasObjectId } from '~/interfaces/has-object-id';
eslint による自動修正

2022-04-21 03:38 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +import Subscription from '../models/subscription';
eseslint による自動修正

2022-04-21 03:38 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +    const pageOp = await PageOperation.findOneAndUpdate(filter, update, option); // set isFailure to false before rename operation
見つけたPageOperationドキュメントの `isFailure` を `true` に更新しつつ、更新後のものを返す

`isFailure: false` な状態にしてから rename を再実行

2022-04-21 03:39 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +    const pageOp = await PageOperation.findOneAndUpdate(filter, update, { new: true }); // set isFailure to false before rename operation
見つけたPageOperationドキュメントの `isFailure` を `false` 、`actionStage` を `Main` に更新しつつ、更新後のものを返す

`isFailure: false` な状態にしてから rename を再実行

2022-04-21 03:42 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      await restartPageRenameOperation(_pageOperation._id);
`/renamePOP1` 以降 3つのうち、最初の1つのみ rename され、そこで中断された状態からの 再rename を想定

2022-04-21 07:56 UTC, hakumizuki requested changes
一旦テストコード以外のレビューしました。修正お願いします！

2022-04-21 07:56 UTC, hakumizuki commented on packages/app/src/server/models/page-operation.ts
> +};
"全て" という意味をメソッド名に込めた方がいいですね

2022-04-21 07:56 UTC, hakumizuki commented on packages/app/src/server/models/page-operation.ts
> +  isFailure: { type: Boolean, default: false, required: true },
default があるので required は不要ですね

2022-04-21 07:56 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    const pageOp = await PageOperation.findOneAndUpdate(filter, update, { new: true }); // set isFailure to false before rename operation
restart の対象は Main じゃなくて Sub です
descendantCount が 0 になっちゃう問題に関しては、フロントに渡すデータの属性を工夫すればできることになったので OK です
actionStage は Sub のままで OK です

2022-04-21 07:56 UTC, hakumizuki commented on packages/app/src/server/crowi/index.js
> +  await PageOperation.cleanup(excludeList);
ここさらに ActionStage でもフィルタリングしたいですね。Sub のみで

2022-04-21 07:56 UTC, hakumizuki commented on packages/app/src/server/crowi/index.js
> +
models の方でコメントしましたが、"全部"感がほしいです

2022-04-21 09:45 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +    await this.renameMainOperation(page, toPath, user, options, _id);
FBを受けて、この後SubOperationに変更予定

2022-04-28 06:00 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +    });
マッチするPageOperationが存在しないと失敗する

2022-05-18 08:04 UTC, merged