feat: 93173 93282 add all delete button and modal in trash
weseek/growi pull request #5741
Opened 2022-04-21 10:15 UTC by yukendev

93282: https://redmine.weseek.co.jp/issues/93282
93173: https://redmine.weseek.co.jp/issues/93173

[93162](https://redmine.weseek.co.jp/issues/93162)のUI作成のタスクのみのブランチ
削除機能は未実装

2022-04-25 06:27 UTC, yuki-takei commented
CustomNav は汎用的なコンポーネントのはずなので、trash 関連のコードがはいるのは何かおかしい

2022-04-25 06:30 UTC, yuki-takei requested changes

2022-04-25 06:30 UTC, yuki-takei commented on packages/app/src/components/PageDeleteModal.tsx
> +        { emptyTrash && renderCompletelyDeleteAlert() }
条件が入り組んでるので、emptyTrash の true or false でまず条件分岐して。false だったらその中で renderDeleteRecursivelyForm, renderDeleteCompletelyForm するかどうか(元のコード)を書く。

2022-04-26 02:18 UTC, yukendev commented on packages/app/src/stores/modal.tsx
> +  emptyTrash?: true,
これはtrueのリテラル型のつもりでした。このプロパティは持つなら絶対に値がtrueという意味でこういう実装にしたんですが、良くなかったですかね？

2022-04-26 02:22 UTC, yukendev commented on packages/app/src/components/CustomNavigation/CustomNav.jsx
> +  emptyTrashButton: PropTypes.element,
下の箇所も同様ですが、もともとCustomNav.jsxに直接trash関連の処理を書いていて指摘されたので、TrashPageList.tsxで処理を書いて、バケツリレーで渡すように実装した結果このようにCustomNav.jsxとCustomNavAndContents.jsxが「ゴミ箱を空にする」ボタンを受け取るためのプロパティを持つようにしました。

2022-04-26 03:01 UTC, miya commented on packages/app/src/components/CustomNavigation/CustomNav.jsx
> +  emptyTrashButton: PropTypes.element,
`CustomNav.jsx` という汎用的なコンポーネントに `emptyTrashButton` というような具体的な名前が入っていいのかというのがちょっと疑問でした。ここから先は自分では判断できないので、2段階目のレビューに行ってください！

2022-04-26 10:07 UTC, yuki-takei requested changes

2022-04-26 10:07 UTC, yuki-takei commented on packages/app/src/components/CustomNavigation/CustomNav.jsx
> +  emptyTrashButton: PropTypes.element,
> CustomNav.jsx という汎用的なコンポーネントに emptyTrashButton というような具体的な名前が入っていいのかというのがちょっと疑問でした。ここから先は自分では判断できないので

だめです

2022-04-27 12:35 UTC, yuki-takei requested changes

2022-04-27 12:35 UTC, yuki-takei commented on packages/app/src/components/TrashPageList.jsx
> +      <CustomNavAndContents navTabMapping={navTabMapping} navRightElement={EmptyTrashButton()} />
`EmptyTrashButton()` でレンダリングするのはあまり react らしくない。

`<EmptyTrashButton />` を useMemo で変数 `emptyTrashButton` に入れて、それを `navRightElement={emptyTrashButton}` のように使ってください。

2022-04-27 12:35 UTC, yuki-takei commented on packages/app/src/components/PageDeleteModal.tsx
> +  const renderCompletelyDeleteAlert = () => {
useCallback または useMemo 使ってください

2022-04-27 12:35 UTC, yuki-takei commented on packages/app/src/components/PageDeleteModal.tsx
> +  const renderDeleteModalOptions = () => {
useCallback または useMemo 使ってください

2022-04-28 10:58 UTC, merged