feat: Viewing AuditLog
weseek/growi pull request #5750
Opened 2022-04-22 07:11 UTC by miya

## Task

[#93429](https://redmine.weseek.co.jp/issues/93429) [GROWI] [AuditLog] 管理画面に AuditLog の view を追加して、Activity をテーブルに一覧表示できる
└ [#93528](https://redmine.weseek.co.jp/issues/93528) /admin/audit-log にアクセスできる

## ScreenShot
<img width="1440" alt="ScreenShot 2022-04-22 16 06 02" src="https://user-images.githubusercontent.com/34241526/164624844-c8d902fa-2cd5-4902-a6a3-a83d9829d293.png">

2022-04-22 07:16 UTC, miya commented on packages/app/src/client/admin.jsx
> +import ErrorBoundary from '../components/ErrorBoudary';
lint 自動修正

2022-04-22 07:16 UTC, miya commented on packages/app/src/components/Admin/Common/AdminNavigation.jsx
> +
eslint 自動修正

2022-04-22 07:16 UTC, miya commented on packages/app/src/server/routes/admin.js
> +import loggerFactory from '~/utils/logger';
eslint 自動修正

2022-04-22 07:16 UTC, miya commented on packages/app/src/server/routes/index.js
> +const rateLimit = require('express-rate-limit');
eslint 自動修正

2022-04-22 07:16 UTC, miya commented on packages/app/src/server/routes/index.js
> +
`/admin/audit-log` にリクエストされると `admin/audit-log.html` がレンダリングされる

2022-04-22 07:29 UTC, miya commented on packages/app/src/components/Admin/Common/AdminNavigation.jsx
> +      case 'audit-log':                return <><i className="icon-fw fa fa-paw"></i>            { t('AuditLog')}</>;
仮に fa-paw にしています。なにかおすすめがあったら教えていただきたいです。
master にマージまでにアイコンを確定させるで良いと思うので、却下の場合もスルーでお願いします。

2022-04-22 13:16 UTC, yuki-takei requested changes

2022-04-22 13:16 UTC, yuki-takei commented on packages/app/src/components/Admin/Common/AdminNavigation.jsx
> +      case 'audit-log':                return <><i className="icon-fw fa fa-paw"></i>            { t('AuditLog')}</>;
とりあえず simple line icon 縛りで、

- [.icon-layers](https://simplelineicons.github.io/#)
- [.icon-feed](https://simplelineicons.github.io/#)

あたりかなあ

2022-04-22 13:20 UTC, yuki-takei requested changes

2022-04-22 13:20 UTC, yuki-takei commented on packages/app/src/components/Admin/Common/AdminNavigation.jsx
> +        <MenuLink menu="audit-log"    isListGroupItems isActive={isActiveMenu('/audit-log')} />
細かいんだけど順番がしっくりこない(だからといってどこが適切かってピンとくる箇所はないんだけど)

customize の下か、
user-groups の下か、
その他…？

2022-04-24 16:13 UTC, miya commented on packages/app/src/components/Admin/Common/AdminNavigation.jsx
> +      case 'audit-log':                return <><i className="icon-fw fa fa-paw"></i>            { t('AuditLog')}</>;
`icon-feed` にしました。

2022-04-24 16:13 UTC, merged