imprv: change GET method to POST for logout method
weseek/growi pull request #5751
Opened 2022-04-22 07:38 UTC by kaoritokashiki

2022-04-26 02:46 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/index.js
> +  routerForAdminAndAuth.use('/healthcheck', require('./healthcheck')(crowi));
/login をv3 に 移動したことにより、メンテナンスモード時に以下のmiddleware で処理がブロックされてしまうという問題がありました。
```
  // API v3
  app.use('/_api/v3', unavailableWhenMaintenanceModeForApi, apiV3Router);
``
その問題を解決するために、
`routerForAdmin` -> `routerForAdminAndAuth` に名前を変更し、`/logout`を追加するようにしました。

2022-04-26 02:47 UTC, kaoritokashiki commented on packages/app/src/server/views/maintenance-mode.html
> +            <div id="maintenance-mode-content"></div>
`MaintenanceModeContent`component を作成しました。

2022-04-26 02:48 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/logout.js
> +};
`/logout`を apiv3 に移動してます

2022-04-26 02:49 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/index.js
> +  routerForAdminAndAuth.use('/logout', require('./logout')(crowi));
/logout 追加

2022-04-26 09:18 UTC, yuki-takei requested changes

2022-04-26 09:18 UTC, yuki-takei commented on packages/app/src/components/MaintenanceModeContent.tsx
> +      appContainer.apiv3Post('/logout');
appContainer 使わないでください

2022-04-26 09:18 UTC, yuki-takei commented on packages/app/src/components/MaintenanceModeContent.tsx
> +      appContainer.apiv3Post('/logout');
await が必要。

2022-04-26 09:18 UTC, yuki-takei commented on packages/app/src/components/MaintenanceModeContent.tsx
> +            <a href="#" onClick={logoutHandler} id="maintanounse-mode-logout">{ t('maintenance_mode.logout') }</a>
`href="#"` なしで。role か type か設定すれば hand cursor になった気がする。

2022-04-26 09:18 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/index.js
> +  routerForAdminAndAuth.use('/healthcheck', require('./healthcheck')(crowi));
routerForAuth とか新設すればよかったんじゃ

2022-04-26 09:18 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/logout.js
> +const logger = loggerFactory('growi:routes:apiv3:forgotPassword'); // eslint-disable-line no-unused-vars
namespace 直してください

2022-04-26 09:20 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/index.js
> +  routerForAdminAndAuth.use('/healthcheck', require('./healthcheck')(crowi));
確かにです。そうします。

2022-04-26 20:30 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/index.js
> +const routerForAuth = express.Router();
`routerForAuth` を新設しました。

2022-04-26 20:32 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/logout.js
> +const logger = loggerFactory('growi:routes:apiv3:forgotPassword'); // eslint-disable-line no-unused-vars
`'growi:routes:apiv3:logout'` に修正

2022-04-27 02:56 UTC, kaoritokashiki commented on packages/app/src/components/MaintenanceModeContent.tsx
> +      appContainer.apiv3Post('/logout');
appContainerの削除、 await をつけました

2022-04-27 08:55 UTC, yuki-takei requested changes

2022-04-27 09:10 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/PersonalDropdown.jsx
> +      await appContainer.apiv3Post('/logout');
1. appContainerの削除、
ついでに
2. withTranslation -> useTranslation を使うよう変更しました。

2022-04-27 09:22 UTC, merged