feat: SWRize Activity list and show on table
weseek/growi pull request #5775
Opened 2022-04-27 06:01 UTC by miya

## Task

[#93429](https://redmine.weseek.co.jp/issues/93429) [GROWI] [AuditLog] 管理画面に AuditLog の view を追加して、Activity をテーブルに一覧表示できる
└ [#93691](https://redmine.weseek.co.jp/issues/93691) [Front] /activity/list の SWR 化 
└ [#93694](https://redmine.weseek.co.jp/issues/93694) [Front] SWR を用いて取得した activity をテーブルに一覧表示する

## ScreenShot

<img width="1427" alt="ScreenShot 2022-04-27 15 00 25" src="https://user-images.githubusercontent.com/34241526/165451398-9a59dd96-3cb0-46b2-bb50-0728ce036d34.png">

2022-04-27 06:11 UTC, miya commented on packages/app/src/components/Admin/AuditLog.tsx
> +  const activityList = activityListData?.docs != null ? activityListData.docs : [];
SWR を利用して Activity ドキュメントの取得

2022-04-27 06:11 UTC, miya commented on packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
> +export default ActivityTable;
Activity をテーブルに一覧表示

2022-04-27 06:11 UTC, miya commented on packages/app/src/interfaces/activity.ts
> +export type IActivityHasId = IActivity & HasObjectId;
Activity ドキュメントの型

2022-04-27 06:11 UTC, miya commented on packages/app/src/interfaces/mongoose-utils.ts
> +}
`mongoose-paginate-v2` 用の型

2022-04-27 06:11 UTC, miya commented on packages/app/src/server/models/activity.ts
> +      populate: 'user',
user ドキュメントを populate

2022-04-27 06:11 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +    'Too many requests sent from this IP, please try again after 15 minutes.',
文言の修正

2022-04-27 06:11 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +      });
user ドキュメントのシリアライズ

2022-04-27 06:11 UTC, miya commented on packages/app/src/stores/activity.ts
> +};
`/activity` の SWR 化

2022-04-27 09:33 UTC, yuki-takei requested changes

2022-04-27 09:33 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLog.tsx
> +  const activityList = activityListData?.docs != null ? activityListData.docs : [];
loading 時は spinner 表示したい。後続タスクでも可。

2022-04-27 09:33 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLog.tsx
> +    </div>
ファイル名とコンポーネント名、AuditLogManagement がいいかなあ。

2022-04-27 09:33 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
> +                <td>{activity.user?.username}</td>
InAppNotification の時に似たような議論があったと思うけど、ユーザーが削除されてたとしても最低限のデータは残るべきだから、モデル設計的に `activity.user` は ref じゃだめなのかも。

2022-04-27 09:33 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
> +export default ActivityTable;
新しく作るコンポーネントは default export 避けて named export にしてください。

2022-04-27 10:44 UTC, miya commented on packages/app/src/components/Admin/AuditLog.tsx
> +  const activityList = activityListData?.docs != null ? activityListData.docs : [];
後続で実装します

2022-04-27 10:44 UTC, miya commented on packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
> +export default ActivityTable;
修正しました

2022-04-27 12:02 UTC, kaoritokashiki commented on packages/app/src/interfaces/mongoose-utils.ts
> +}
in-app-notificationで定義されている interface PaginateResult ついでに消していただけると助かります

2022-04-27 12:04 UTC, kaoritokashiki commented on packages/app/src/interfaces/mongoose-utils.ts
> +}
in-app-notificationで定義されている interface PaginateResult
ついでに消していただけると助かります 🙏

2022-04-27 12:07 UTC, kaoritokashiki commented on packages/app/src/interfaces/mongoose-utils.ts
> +}
TODO コメントは　mongoose-utils.ts の方に追加でお願いします 🙏

2022-04-27 16:36 UTC, miya commented on packages/app/src/interfaces/mongoose-utils.ts
> +}
了解です〜 `feat/auditlog` が master にマージされたらやります

2022-04-28 10:51 UTC, miya commented on packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
> +                <td>{activity.user?.username}</td>
[後続タスク](https://redmine.weseek.co.jp/issues/94090) で対応します

2022-04-28 11:04 UTC, merged