support: typescriptize tag model
weseek/growi pull request #5778
Opened 2022-04-27 12:46 UTC by kaoritokashiki

2022-05-10 04:20 UTC, kaoritokashiki commented on packages/app/src/interfaces/tag.ts
> +  count: number;
ITag、IDがstringもObjectIdも使えるように改修しました。
それに伴い、type `ITagCount` `ITagCountHasId` を削除したのでこれでいいか確認お願いします。

2022-05-11 11:08 UTC, hakumizuki requested changes

2022-05-11 11:08 UTC, hakumizuki commented on packages/app/src/interfaces/tag.ts
> +  count: number;
ITag は Tag Model のスキーマと属性の数を合わせてください。 createdAt って多分存在しないですよね

count に関してはおそらくバックエンドのコードで注入されているだけなのでこれも ITag からは外したいです

2022-05-13 07:54 UTC, kaoritokashiki commented on packages/app/src/interfaces/tag.ts
> +export type IDataTagCount = IResTag & {count: number}
IDataTagCount を復活させました。

2022-05-13 08:21 UTC, merged