wip
weseek/growi pull request #5782
Opened 2022-04-28 11:07 UTC by Yohei-Shiina

2022-05-09 00:57 UTC, Yohei-Shiina commented on packages/app/src/server/routes/apiv3/page-listing.ts
> +import { ApiV3Response } from './interfaces/apiv3-response';
lint 自動修正

2022-05-09 02:02 UTC, hakumizuki requested changes

2022-05-09 02:02 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +export const hasSlash = (str: string): boolean => {
`hasSlash`, `generateChildrenRegExp` は utility にあった方が良さそうですね

2022-05-09 02:02 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +export const addViewerCondition = async(queryBuilder: PageQueryBuilder, user, userGroups = null): Promise<void> => {
あと `addViewerCondition` はもはや PageQueryBuilder or PageModel が持っててもいい気がしますね。どこがいいか検討してみてください

2022-05-10 06:36 UTC, Yohei-Shiina commented on packages/app/src/server/models/page.ts
> +export const addViewerCondition = async(queryBuilder: PageQueryBuilder, user, userGroups = null): Promise<void> => {
PageQueryBuilder に追加しました

2022-05-10 07:27 UTC, hakumizuki requested changes

2022-05-10 07:27 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +  }
これは `addConditionToListByPathsArray` これでできちゃいますね

今回は消すことになりますが、メソッドの引数と返り値の型を定義することを忘れないでください！

2022-05-10 07:27 UTC, hakumizuki commented on packages/core/src/utils/page-path-utils.ts
> + */
ここ jsdoc にしてください

2022-05-10 10:20 UTC, merged