feat: 93172 empty trash function
weseek/growi pull request #5784
Opened 2022-04-28 12:39 UTC by yukendev

https://redmine.weseek.co.jp/issues/93172

ゴミ箱の中身を空にする処理を追加

2022-04-28 14:15 UTC, yuki-takei requested changes

2022-05-08 16:44 UTC, yuki-takei requested changes

2022-05-08 16:44 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/pages.js
> +    }
この状況って結構起こり得るんじゃないかな。そしてそうなったら最後、 `/empty-trash` は機能不全になってしまう。

2022-05-09 04:36 UTC, yukendev commented on packages/app/src/server/routes/apiv3/pages.js
> +    }
[94400](https://redmine.weseek.co.jp/issues/94400)にタスクを切ったのでエラーハンドリングに関してはこちらのタスクでやります

2022-05-09 11:12 UTC, merged