fix: Error when renaming
weseek/growi pull request #5793
Opened 2022-04-29 09:26 UTC by miya

## Task

[#94219](https://redmine.weseek.co.jp/issues/94219) [S社FB] 検索ページで移動/名前変更した際にエラーが表示される(ページは移動できている)
└ [#94229](https://redmine.weseek.co.jp/issues/94229) 修正

2022-04-29 09:43 UTC, miya commented on packages/app/src/server/routes/apiv3/page.js
> +      }
バグの再現条件は、`/page/exist-paths` へのリクエストが完了していない状態で、リネームボタンを押すことだと思っています。なので、リネームモーダルの input に適当な文字列を入力し、`/page/exist-paths` へのリクエストが完了したことを確認したあとに、リネームボタンを押してもエラーになりません。

`/page/exist-paths` のクエリパラメーターである `fromPath` のページパスが存在しない（リネームされてしまっている）ため、`fromPage` が null になり、`findManageableListWithDescendants` の第一引数で null を入れてしまっていることでエラーになっています。

2022-04-29 09:43 UTC, miya commented on packages/app/src/server/routes/apiv3/page.js
> +import loggerFactory from '~/utils/logger';
eslint 自動修正

2022-05-06 06:26 UTC, miya commented on packages/app/src/components/PageRenameModal.tsx
> +import ApiErrorMessageList from './PageManagement/ApiErrorMessageList';
eslint 自動修正

2022-05-06 06:26 UTC, miya commented on packages/app/src/components/PageRenameModal.tsx
> +    return debounce(1000, true, checkExistPaths);
バグの原因はリネームが行われた後に、`checkExistPaths` が走ってしまうことが原因だと思っています。`throttle-debounce` の `debounce` には連続処理が行われた後1秒後に checkExistPaths が走るようになっていたため、リネームの input に適当なパスを入力した後すぐにリネームボタンを押すことでバグが再現します。つまり input に適当なパスを入力してから1秒間待ってからリネームボタンを押せばバグは再現しません。修正内容としては、debunce に atBegin = true を入れることで、最初の debunce 関数が呼び出された時に、checkExistPaths が呼び出されるようにしました。

参考
https://github.com/niksy/throttle-debounce#atbegin

2022-05-06 06:26 UTC, miya commented on packages/app/src/server/routes/apiv3/page.js
> +      if (fromPage == null) throw new Error('fromPage is Null');
`findManageableListWithDescendants` の第一引数に null を入れるとエラーが出るため、 `fromPage` が null の時にエラーをスローさせるようにしました。

2022-05-08 17:11 UTC, yuki-takei requested changes

2022-05-08 17:11 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/page.js
> +      if (fromPage == null) throw new Error('fromPage is Null');
route は API の窓口なので、むやみに throw error してはいけない。なぜならドメイン層やサービス層と違って、上流で catch してくれる先を期待できないから。400 bad request を返すようにするのが正しい。

2022-05-08 17:11 UTC, yuki-takei commented on packages/app/src/components/PageRenameModal.tsx
> +    return debounce(1000, true, checkExistPaths);
ちょっと要領を得ない。なぜ atBegin = true にすることで、

> リネームが行われた後に、checkExistPaths が走ってしまうこと

が抑止されるの？

2022-05-09 06:50 UTC, miya commented on packages/app/src/components/PageRenameModal.tsx
> +  const [isRenameButtonPushed, setIsRenameButtonPushed] = useState(false);
リネームボタンを押した際に `true` になるステートを追加しました

2022-05-09 06:50 UTC, miya commented on packages/app/src/components/PageRenameModal.tsx
> +            <form className="flex-fill" onSubmit={(e) => { setIsRenameButtonPushed(true); e.preventDefault(); rename() }}>
リネームボタンが押された時に、setIsRenameButtonPushed(true) にする

2022-05-09 06:50 UTC, miya commented on packages/app/src/components/PageRenameModal.tsx
> +    if (page == null || !isCheckable) {
isCheckable（!isRenameButtonPushed を受け取る）という引数を追加しました。
リネームボタンが押された後だった場合は `/page/exist-paths` に対してリクエストさせないために、早期リターンするような実装にしました。

2022-05-09 06:50 UTC, miya commented on packages/app/src/server/routes/apiv3/page.js
> +      if (fromPage == null) throw new Error('fromPage is Null');
修正しました！

2022-05-09 11:42 UTC, yuki-takei requested changes

2022-05-09 11:42 UTC, yuki-takei commented on packages/app/src/components/PageRenameModal.tsx
> +    if (page == null || !isCheckable) {
魔改造に近づいていくな…

以下のような仕様に変更してください。

- 「rename API をたたいていいかどうか」を表す boolean の state を用意する(仮に A とする)
    - 初期値は false
- textinput への入力し始めに必ず A を false にする
    - つまり、check の結果が手に入る前(debounce の待ち時間含む)の間は UI 的に rename ボタンを押せないようにする
- チェックの結果、existingPaths や err の状態で rename の API を叩いてもいい状態かどうかが決まるはず
    - 条件が揃えば A は true になる
    - 上記の条件が false の間は、rename API を叩いてはいけない

2022-05-10 05:28 UTC, miya commented on packages/app/src/components/PageRenameModal.tsx
> +  }, [pageNameInput]);
input にテキストが入力されている時は常に false にする

2022-05-10 05:28 UTC, miya commented on packages/app/src/components/PageRenameModal.tsx
> +      setCanRename(true);
`/page/exist-paths` へのリクエストが完了して初めて、true（rename 可能になる）

2022-05-10 05:28 UTC, miya commented on packages/app/src/components/PageRenameModal.tsx
> +    if (page == null || !isCheckable) {
ありがとうございます、そのような実装に修正しました。

2022-05-10 06:58 UTC, yuki-takei requested changes

2022-05-10 06:58 UTC, yuki-takei commented on packages/app/src/components/PageRenameModal.tsx
> +      setCanRename(true);
existPaths の中身を調べないと判断できないのでは？

2022-05-10 07:43 UTC, miya commented on packages/app/src/components/PageRenameModal.tsx
> +      setCanRename(true);
existPaths.length で true にするか判断するようにしました。

2022-05-10 07:54 UTC, yuki-takei approved these changes

2022-05-10 07:54 UTC, merged