imprv: Put snapshot in activity document
weseek/growi pull request #5794
Opened 2022-04-29 16:35 UTC by miya

## Task

[#93429](https://redmine.weseek.co.jp/issues/93429) [GROWI] [AuditLog] 管理画面に AuditLog の view を追加して、Activity をテーブルに一覧表示できる
└ [#94090](https://redmine.weseek.co.jp/issues/94090) activity document を生成する際に audit log の表示に必要なデータの snapshot を入れる

2022-05-02 00:36 UTC, miya commented on packages/app/src/interfaces/activity.ts
> -
使用されておらず不要だと思ったので削除

2022-05-02 00:36 UTC, miya commented on packages/app/src/server/events/comment.ts
eslint 自動修正

2022-05-02 00:36 UTC, miya commented on packages/app/src/server/models/activity.ts
> +  snapshot: string
snapshot を保存できるようにしました

2022-05-02 00:36 UTC, miya commented on packages/app/src/server/models/activity.ts
> +  },
`updatedAt` は不要なので保存させないようにしました

2022-05-02 00:36 UTC, miya commented on packages/app/src/server/service/comment.ts
>      const activity = await this.activityService.createByParameters(parameters);
activity を作成する際に、action を行ったユーザーの username の snapshot を保存できるようにしました。

2022-05-02 00:36 UTC, miya commented on packages/app/src/server/service/page.ts
> +        await this.createAndSendNotifications(user, page, SUPPORTED_ACTION_TYPE.ACTION_PAGE_UPDATE);
`user` と `page` の順番を変更しました

2022-05-02 00:36 UTC, miya commented on packages/app/src/server/events/comment.ts
> +  logger.info('onDelete comment event fired');
文言をメソッド名と合わせるように修正しました。

2022-05-08 16:55 UTC, yuki-takei requested changes

2022-05-08 16:55 UTC, yuki-takei commented on packages/app/src/models/serializers/activity-snapshot/user.ts
> +};
このモジュールの実装、もう少し議論してより良くしたい。

現状 parseSnapshot では stringifySnapshot の返り値をそのまま入れても機能しないだろうし、もう少し設計思想よく見えるようにしてほしい。

2022-05-09 10:09 UTC, miya commented on packages/app/src/server/models/activity.ts
> +    },
snapshot をオブジェクトで持てるようにしました

2022-05-09 10:09 UTC, miya commented on packages/app/src/interfaces/activity.ts
> +}
IUser から `username` を pick した ISnapshot という type を作成しました

2022-05-09 10:10 UTC, miya commented on packages/app/src/models/serializers/activity-snapshot/user.ts
> +};
管理画面から username を検索しやすくするために、snapshot をオブジェクトで持つように修正しました。

<img width="767" alt="ScreenShot 2022-05-09 19 09 35" src="https://user-images.githubusercontent.com/34241526/167388943-720fd7fa-8594-491d-96db-4d1d574a2b13.png">

2022-05-12 08:24 UTC, yuki-takei requested changes

2022-05-12 08:24 UTC, yuki-takei commented on packages/app/src/server/models/activity.ts
> +    },
ここは流石に ISnapshot 使っては書けないか…mongoose の syntax だもんな。
そうすると embed model の方が typescript との相性がいい気がする。

このまま行くならせめて ISnapshot と互換性があることをコメントで書いておいて。

2022-05-16 05:01 UTC, miya commented on packages/app/src/server/models/activity.ts
> +    },
snapshot を embed model にしました

2022-05-16 05:02 UTC, miya commented on packages/app/src/server/models/activity.ts
> +
snapshot を embed model にしました

2022-05-16 06:11 UTC, yuki-takei requested changes

2022-05-16 09:37 UTC, merged