fix/display admin link only with logged in
weseek/growi pull request #5799
Opened 2022-05-02 06:43 UTC by hirokei-camel

メンテナンスモードにて、ログアウトした状態でも管理画面へのリンクが表示されてしまうバグを修正。

ログインした状態でのみ、管理画面へのリンクを表示するようにしました。

タスク：https://redmine.weseek.co.jp/issues/94252

2022-05-09 02:19 UTC, kaoritokashiki requested changes

2022-05-09 02:19 UTC, kaoritokashiki commented on packages/app/src/components/MaintenanceModeContent.tsx
> +            </p>
管理者ページは管理者しか見れないので、ログイン中のユーザーが管理者である場合は、管理者ページのリンクを表示するように修正お願いします 🙏

2022-05-11 04:33 UTC, kaoritokashiki requested changes

2022-05-11 04:33 UTC, kaoritokashiki commented on packages/app/src/components/MaintenanceModeContent.tsx
> +      }
細かいですが、 `)}` 
になるように修正お願いします 🙏

2022-05-11 04:34 UTC, hirokei-camel commented on packages/app/src/components/MaintenanceModeContent.tsx
> +      }
丁寧なご指摘、ありがとうございます！
修正します！！

2022-05-11 04:57 UTC, kaoritokashiki approved these changes

2022-05-11 05:12 UTC, merged