feat: 94310 suggest function for page rename modal
weseek/growi pull request #5805
Opened 2022-05-06 03:04 UTC by kaoritokashiki

2022-05-06 03:09 UTC, kaoritokashiki commented on packages/app/src/components/PageDuplicateModal.tsx
> +                    onInputChange={inputChangeHandler}
inputChangeHandler と ppacInputChangeHandler のメソッドで同じ処理が記述されていたので、`ppacInputChangeHandler`の方を削除し、`inputChangeHandler` が実行されるように変更しました。

2022-05-06 03:10 UTC, kaoritokashiki commented on packages/app/src/components/PageCreateModal.jsx
> +                    onInputChange={inputChangeHandler}
[PageCreate] `onChangePageNameInputHandler` と `ppacInputChangeHandler` のメソッドで同じ処理が記述されていたので、ppacInputChangeHandlerの方を削除し、どちらも同じ関数を実行するように変更しました。

2022-05-08 17:05 UTC, yuki-takei requested changes

2022-05-08 17:05 UTC, yuki-takei commented on packages/app/src/components/PageCreateModal.jsx
> +                    onInputChange={inputChangeHandler}
そこまでこだわるところでもないが、中途半端であまりよくない。

onChangePageNameInputHandler と ppacInputChangeHandler は別のコンポーネントのイベントハンドラだったわけだから処理内容が一緒なのはたまたまである。別々に存在していたのは一応意味があった。

それを冗長だと感じるのもわかるので簡素化するのもいいとは思うんだけど、それならそれでいっそ inputChangeHandler もなくしてしまって、

`e => inputChangeHandler(e.target.value)` のように closure をその場で作ってその中で setPageNameInput を直接使った方がいい。

2022-05-09 02:49 UTC, kaoritokashiki commented on packages/app/src/components/PageCreateModal.jsx
> +                    onInputChange={inputChangeHandler}
理解しました。そのように修正しました。

2022-05-09 04:21 UTC, kaoritokashiki commented
> onChangePageNameInputHandler と ppacInputChangeHandler は別のコンポーネントのイベントハンドラだったわけだから処理内容が一緒なのはたまたまである。別々に存在していたのは一応意味があった。

なるほどです.......!!! 理解しました。
安易に共通化してはいけないのですね。

pageRenameの方は　処理が複数あるので、 handlerの処理を別々に参照するようにしました。

2022-05-09 04:29 UTC, merged