feat: Inject isGrantNormalized to renderVars
weseek/growi pull request #5808
Opened 2022-05-06 06:51 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/94122

権限の修正が必要であるという情報をrenderVars に格納できるようにしました

2022-05-08 17:26 UTC, yuki-takei requested changes

2022-05-08 17:26 UTC, yuki-takei commented on packages/app/src/server/views/layout/layout.html
> +{% endif %}
Next.js 化の事も考えると、

- swig に新しい ID の DOM を作りたくない
    - PageInfo 取得 API に統合するのはどうか？(検討してほしい)
- 必要だとしても layout.html に作りたくない
    - page 表示する部分限定にならないだろうか？

2022-05-09 09:38 UTC, hakumizuki commented on packages/app/src/server/views/layout/layout.html
> +{% endif %}
DOM は増えたことに変わりありませんが、swig 経由では何もデータを渡さず、React のレンダー実行時に api を叩いて描画するかを決定するような設計にしました

2022-05-09 10:28 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/page.js
> +  router.get('/is-grant-normalized', loginRequiredStrictly, validator.isGrantNormalized, apiV3FormValidator, async(req, res) => {
api 追加しました

2022-05-09 11:45 UTC, merged