feat: Search by specific action
weseek/growi pull request #5811
Opened 2022-05-07 08:01 UTC by miya

## Task
[#93975](https://redmine.weseek.co.jp/issues/93975) [GROWI] [AuditLog] 特定の action を指定して検索できる
└ [#94131](https://redmine.weseek.co.jp/issues/94131) 実装

## ScreenRecord
https://user-images.githubusercontent.com/34241526/167244989-6b0bb41d-30bd-4ce5-9309-a4500739a368.mov

2022-05-07 09:28 UTC, miya commented on packages/app/src/components/Admin/AuditLog/SelectQueryItemsDropdown.tsx
> +};
`mongoose-paginate-v2` に渡す query を選択するための汎用的なドロップダウンを実装しました

2022-05-07 09:28 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +  const [actionName, setActionName] = useState<string | undefined>(undefined);
ドロップダウンから選択される action 名を入れる state

2022-05-07 09:28 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +  const { data: activityListData, error } = useSWRxActivityList(PAGING_LIMIT, offset, query);
`mongoose-paginate-v2` に渡すクエリ

2022-05-07 09:28 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +  }, []);
ドロップダウンアイテムが選択された時に、PaginationWrapper に渡すための `ActivePage` を初期値である 1 に戻す

2022-05-07 09:28 UTC, miya commented on packages/app/src/server/models/activity.ts
> +    query,
mongoose のクエリを渡せるようにしました

2022-05-07 09:28 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +  max: 30, // limit each IP to 30 requests per windowMs
少なすぎたので 30 にあげました

2022-05-07 09:28 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +      const paginationResult = await Activity.getPaginatedActivity(limit, offset, JSON.parse(query));
JSON.stringify された req.query.query を JSON.parse

2022-05-07 09:28 UTC, miya commented on packages/app/src/stores/activity.ts
> +  const stringifiedQuery = JSON.stringify(query);
query を JSON.stringify してリクエストパラメーターに入れる

2022-05-09 11:11 UTC, yuki-takei requested changes

2022-05-09 11:11 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/activity.ts
> +      const paginationResult = await Activity.getPaginatedActivity(limit, offset, JSON.parse(query));
クライアントから渡ってきた query 文字列をそのまま ORM に渡すのはNG。
sql injection または nosql injection 等で検索。

責務の観点からも、フロントエンドが ORM である mongoose のクエリの文法を正確に知っている必要はない(というか知っていたらおかしい)。

2022-05-09 11:11 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLog/SelectQueryItemsDropdown.tsx
> +        <button className="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown">
後続タスク化で構わないが、ドロップダウンで唯一を選ぶというのは使い勝手がよくない。

参考: Notion
https://www.youtube.com/watch?v=qvFRKC5Ft88

やっつけで実装するなら、textinput で自由入力(その内容が username にも event name にも引っかかる)とかの方が汎用的。

2022-05-11 05:41 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +      const paginationResult = await Activity.getPaginatedActivity(limit, offset, JSON.parse(query));
API 側で、クライアントから渡ってきたクエリパラメーターを検証して、ORM に渡すようにしました。

2022-05-11 05:42 UTC, miya commented on packages/app/src/components/Admin/AuditLog/SelectQueryItemsDropdown.tsx
> +        <button className="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown">
チェックボックスで action を選択するような実装にしました。PR の説明欄の動画を更新したのでご確認お願いします。

2022-05-11 05:56 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +  );
`[[action, boolean]]` のように Map でチェックされているかの状態を持つようにしました。

2022-05-11 05:56 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +  const searchFilter = { action: selectedActionList };
チェックされた action を配列で API に渡すようにしました。

2022-05-11 05:56 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +  }, [actionMap, setActionMap]);
チェックされた action を更新

2022-05-11 05:56 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +  }, [actionMap, setActionMap]);
渡された action[] を全て更新

2022-05-11 05:56 UTC, miya commented on packages/app/src/components/Admin/AuditLog/SelectActionDropdown.tsx
> +  dropdownItems: Array<{actionCategory: string, actionNames: SupportedActionType[]}>
action カテゴリー（activity.targetModel ではない）と、ドロップダウンにレンダリングする actionNames[]

2022-05-11 05:56 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +    const canContainActionFilterToQuery = parsedSearchFilter.action.every(a => AllSupportedActionType.includes(a));
クライアントから渡された、parsedSearchFilter.action の配列の値全てが AllSupportedActionType に含まれているか検証

2022-05-11 05:56 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +    };
↑ がでの検証の結果 true だったら `getPaginatedActivity` に渡すクエリに含める

2022-05-11 08:54 UTC, yuki-takei requested changes

2022-05-11 08:54 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/activity.ts
> +    };
`req.query.searchFilter` に対する異常系チェックが弱い。API エンドポイントは性悪説で実装する必要がある。parse 可能な文字列が入ってくるとは限らないし、parse 失敗するかもしれないし、pase 成功しても action という要素があるかどうかわからない。

2022-05-11 09:11 UTC, merged