Feat/testcode for resume rename operation
weseek/growi pull request #5831
Opened 2022-05-12 07:59 UTC by Yohei-Shiina

2022-06-06 10:30 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +    test('it should successfully restart rename operation', async() => {
正常に rename を再開できること

2022-06-06 10:31 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +    test('it should fail and throw error if the current time is behind unprocessableExpiryDate', async() => {
現在時刻が、PageOperation の `unprocessableExpiryDate` よりも後ろ（`unprocessableExpiryDate` が未来）の時、例外を投げること

2022-06-06 10:32 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +    test('Missing property(toPath) for PageOperation should throw error', async() => {
PageOperation の property `toPath` が存在しない時、例外を投げること

2022-06-08 04:55 UTC, hakumizuki requested changes

2022-06-08 04:55 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      await expect(resumeRenameSubOperation({}))
```typescript
async resumeRenameSubOperation(renamedPage: PageDocument): Promise<void> {}
```

この型に合うようなデータでテストしてください

2022-06-08 04:55 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      const _path0 = '/POP0';
POP0 って renamePOP0 じゃだめなんですか？何か意味があるのでしょうか？

renamePOP0 も POP に特に意味がないなら resume_rename_A とかでいいと思いますが。

2022-06-08 04:55 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      const page0 = await Page.findOne({ path: path0 });
これ過去の自分のテストコードや、FB で漏れてしまったんですが、resumeRenameSubOperation の後の `findOne({path: hoge})` は `findById(pageHoge._id)` の方が厳密で良いです。ただし id が変わっている場合は path でやるしかないです。ただしその場合は `count` などでページ数も expect したいです

2022-06-08 04:55 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(pageOperation).toBeNull(); // should not exist
この行、上に持ってってもいいんじゃないでしょうか？

2022-06-08 04:55 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      const _pageOperation = await PageOperation.findOne({ 'page._id': _page1._id, actionType: PageActionType.Rename });
これは Sub じゃなくていいんでしたっけ？

2022-06-08 04:55 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(_pageOperation).toBeTruthy();
この expect は findOne の後じゃだめなんですかね？

2022-06-08 04:55 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      await expect(promise).rejects.toThrow(new Error(`Property toPath is missing which is needed to resume page operation(${_pageOperation._id})`));
toThrow の中身は文字列だけで良さそうです

2022-06-08 09:02 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      await expect(promise).rejects.toThrow(new Error(`Property toPath is missing which is needed to resume page operation(${_pageOperation._id})`));
これについては若干の違いがあって、厳密なのは error オブジェクトを渡す方法になります。

https://jestjs.io/ja/docs/27.x/expect#tothrowerror
> - 文字列:エラーメッセージが文字列を含む か検証します
> - error オブジェクト: エラーメッセージがオブジェクトのmessageプロパティと等しいかを検証します

2022-06-08 09:03 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(_pageOperation).toBeTruthy();
問題はないです。 expect をまとめたほうが見た目上整って可読性が高いかと思いそのようにしてました

2022-06-08 09:04 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      const _pageOperation = await PageOperation.findOne({ 'page._id': _page1._id, actionType: PageActionType.Rename });
これは sub 抜けてたので追加します

2022-06-08 09:09 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      await expect(resumeRenameSubOperation({}))
修正しました

2022-06-08 09:21 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      const _path0 = '/POP0';
リネームされるページにだけ rename という PREFIX をつけてましたが、かえって疑問を抱かせてしまうあたり良くなさそうなので統一します

2022-06-08 09:39 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      const page0 = await Page.findOne({ path: path0 });
_id で取得できるので _id に変更しました

2022-06-08 09:40 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(pageOperation).toBeNull(); // should not exist
他の箇所含め修正しました

2022-06-08 09:41 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      const path3 = '/resume_rename_0/resume_rename_1/resume_rename_2/resume_rename_3';
もともとrename処理後に書いてたpathをあえてrename前の位置に移動してみました。
もし見にくい場合は戻します。

2022-06-09 07:05 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      await expect(promise).rejects.toThrow(new Error(`Property toPath is missing which is needed to resume page operation(${_pageOperation._id})`));
ああ〜こっちの方が良いですね。ありがとうございます

2022-06-09 09:47 UTC, hakumizuki requested changes
成功するパターンが１こしかないですが、これで十分カバーされていますか？

2022-06-09 09:47 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +    // ***********************************************************************************************************
いいコメントですね

2022-06-10 04:31 UTC, hakumizuki requested changes

2022-06-10 04:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(page3.parent).toStrictEqual(page2._id);
これは renameSubOperation が考えなくていいことなのでいらないですね

2022-06-10 04:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(page1.descendantCount).toBe(4); // originally 2
originally の部分も事前に expect してあるといいと思います

2022-06-10 04:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +    test(`it should succeed but 2 extra descendantCount should be added
renameSubOperation をみたらこのテストで確かめている部分の処理はほぼ必ず成功するレベルの軽さでしたね。
子孫ページ全部の descendantCount 更新させる処理が走ってると勘違いしてました。ただテストあることに越したことないのでこのままで

2022-06-10 04:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(page2.parent).toStrictEqual(page1._id);
これは renameSubOperation が考えなくていいことなので必要ないです

2022-06-10 04:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(page3.parent).toStrictEqual(page2._id);
これは renameSubOperation が考えなくていいことなので必要ないです

2022-06-10 04:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(page3.descendantCount).toBe(0);
これ resume 前にも expect したいですね

2022-06-10 04:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      const _pageOperation = await PageOperation.findOne({ 'page._id': _page1._id, actionType: PageActionType.Rename, actionStage: PageActionStage.Sub });
これの findOne の条件に _id も含めてほしいです。`'page._id'` にユニーク制約が付いていないので

2022-06-10 04:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      const _pageOperation = await PageOperation.findOne({ 'page._id': _page1._id, actionType: PageActionType.Rename, actionStage: PageActionStage.Sub });
これの findOne の条件に _id も含めてほしいです。`'page._id'` にユニーク制約が付いていないので

2022-06-10 04:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      const pageOperation = await PageOperation.findOne({ 'page._id': _page1._id, actionType: PageActionType.Rename, actionStage: PageActionStage.Sub });
これの findOne の条件に _id も含めてほしいです。`'page._id'` にユニーク制約が付いていないので

2022-06-10 04:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +      const _pageOperation = await PageOperation.findOne({ 'page._id': _page2._id, actionType: PageActionType.Rename, actionStage: PageActionStage.Sub });
これの findOne の条件に _id も含めてほしいです。`'page._id'` にユニーク制約が付いていないので

2022-06-10 05:57 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      const pageOperation = await PageOperation.findOne({ 'page._id': _page1._id, actionType: PageActionType.Rename, actionStage: PageActionStage.Sub });
追加しました

PageOperation.findOne に _id 追加できるように pageOpId(num) を ファイル上の方で定義してます

2022-06-10 05:57 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      const _pageOperation = await PageOperation.findOne({ 'page._id': _page2._id, actionType: PageActionType.Rename, actionStage: PageActionStage.Sub });
追加しました

PageOperation.findOne に _id 追加できるように pageOpId(num) を ファイル上の方で定義してます

2022-06-10 05:57 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      const _pageOperation = await PageOperation.findOne({ 'page._id': _page1._id, actionType: PageActionType.Rename, actionStage: PageActionStage.Sub });
追加しました

PageOperation.findOne に _id 追加できるように pageOpId(num) を ファイル上の方で定義してます

2022-06-10 05:57 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(page3.descendantCount).toBe(0);
追加しました

2022-06-10 05:57 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(page3.parent).toStrictEqual(page2._id);
parentチェックは全て消しました

2022-06-10 05:57 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(page2.parent).toStrictEqual(page1._id);
parentチェックは全て消しました

2022-06-10 05:57 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(page3.parent).toStrictEqual(page2._id);
parentチェックは全て消しました

2022-06-10 05:57 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +      expect(page1.descendantCount).toBe(4); // originally 2
expect追加しました

2022-06-10 05:57 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +    test(`it should succeed but 2 extra descendantCount should be added
コメント気づかなくてこれを残しつつさらに追加してました。

追加したのは祖先の子孫数をマイナスした直後に中断されたパターンのテストです

2022-06-10 06:30 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +
追加漏れ

2022-06-10 06:32 UTC, Yohei-Shiina commented
#6018 のマージでテストが失敗するようになった（想定通り）ので修正しました
https://github.com/weseek/growi/pull/5831/commits/14c8ad8fb5c5f32fd48f12c5d112de494ffc71b1

内容：MainOperation で Rename 後のページの親に+1されるようになったのでそれの対応

2022-06-10 06:57 UTC, hakumizuki requested changes

2022-06-10 06:57 UTC, hakumizuki commented on packages/app/test/integration/service/v5.page.test.ts
> +        descendantCount: 1,
この箇所じゃないんですが、L121 の `parent: pageId0._id,` これって undefined にならないですか？

2022-06-10 07:03 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.page.test.ts
> +        descendantCount: 1,
id に _id やってましたね
他にもあったので修正しました

2022-06-10 07:17 UTC, merged