Should throw an error when trying to choose parent from descendant gr…
weseek/growi pull request #5838
Opened 2022-05-13 06:00 UTC by kaoritokashiki

…oups.

2022-05-13 06:43 UTC, kaoritokashiki commented on packages/app/test/integration/service/user-groups.test.ts
> +  });
>GroupA(user1),GroupB(user2, parent=GroupA)がいる状態で、GroupA の親を GroupB にしようとすると throw される」


以下のif文ブロックが実行されない
```
    // throw if parent was in self and its descendants
    const descendantsWithTarget = await UserGroup.findGroupsWithDescendantsRecursively([userGroup]);
    if (isIncludesObjectId(descendantsWithTarget, parent._id)) {
      throw Error('It is not allowed to choose parent from descendant groups.');
    }
```

2022-05-13 08:02 UTC, hakumizuki commented on packages/app/test/integration/service/user-groups.test.ts
> +  });
ごめんなさい if のコンディションが間違ってました修正お願いします

2022-05-16 12:15 UTC, kaoritokashiki commented on packages/app/src/server/service/user-group.ts
> +
apiv3/routes からservise層に移動しました。

2022-05-16 12:51 UTC, hakumizuki requested changes

2022-05-16 12:51 UTC, hakumizuki commented on packages/app/src/server/service/user-group.ts
> +  async removeUserByUsername(id: Types.ObjectId, username: string) {
id がなんの id なのかわかるような名前にしてください！あと、型は `ObjectIdLike` がいいですね。

さらに、返り値の型も定義できたらしてください

2022-05-16 12:51 UTC, hakumizuki commented on packages/app/src/server/service/user-group.ts
> +    const serializedUser = serializeUserSecurely(user);
判断は任せるんですが、

```typescript
const serializedUser = serializeUserSecurely(user);
```

この部分は router がやった方が責務的にはいい気がしてます。
メソッドが持つ責務はできるだけ少なくすると綺麗でテストコードが書きやすくなります。

2022-05-16 17:05 UTC, merged