feat: Enable to convert pages by path for admin users
weseek/growi pull request #5852
Opened 2022-05-16 12:35 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/91872

待避所からパスによるコンバートで、入力されたパスにページが存在しなくてもページを自動作成することでコンバートできるようにしました

# 後続
- フロントエンドの改修
  - 確認モーダルの実装
  - エンドポイント修正

2022-05-17 06:39 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/pages.js
> +  router.post('/convert-pages-by-path', accessTokenParser, loginRequiredStrictly, adminRequired, csrf, validator.convertPagesByPath, apiV3FormValidator, async(req, res) => {
管理ユーザー専用のパスで変換できるエンドポイント

2022-05-17 06:39 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +
後続で実装

2022-05-17 06:40 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      }
空ページの場合でもコンバートできるようにしました

2022-05-17 06:49 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +      this.grantedUsers.push(options.isSystematically ? grantedUsers[0] : user._id);
`isSystematically` によって値を変えてます

2022-05-17 06:49 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +    aggregationPipeline.push({ $match: grantCondition });
オプションにしました

2022-05-17 07:53 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
`Page.createSystematically` でページを作成

2022-05-17 07:54 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    })();
コンバートが発生しなかったら (count = 0) だったら `systematicallyCreatedPage` を削除

2022-05-17 07:55 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +    if (!isSystematically && grant !== GRANT_RESTRICTED) {
`isSystematically` が `true` なら権限のチェックは行わない

2022-05-17 07:57 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +// TODO: implement this method
後続

2022-05-17 10:02 UTC, yuki-takei requested changes

2022-05-17 10:02 UTC, yuki-takei commented on packages/app/src/server/models/obsolete-page.js
> +      this.grantedUsers.push(options.isSystematically ? grantedUsers[0] : user._id);
ここも isSystematically による場合分けなしで、元のコードでいきたい。

2022-05-17 11:13 UTC, hakumizuki commented on packages/app/src/server/models/obsolete-page.js
> +      this.grantedUsers.push(options.isSystematically ? grantedUsers[0] : user._id);
元のコードは

```typescript
this.grantedUsers.push(user._id);
```

ですが、システムによる操作の場合は `grantedUsers[0]` からしか必要なユーザーを取得できないので、

```typescript
this.grantedUsers.push(grantedUsers[0] ?? user._id);
```

こうしました。

2022-05-17 11:44 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +    const user = null;
`dummyUser` でカバーできるところからは isSystematically をとりのぞきました

2022-05-17 17:12 UTC, yuki-takei requested changes

2022-05-17 17:12 UTC, yuki-takei commented on packages/app/src/server/models/page.ts
> +    page.applyScope(user, grant, grantUserGroupId, grantedUserIds);
この変更やっぱりいやだなあ。
create の肥大化を許し続けることで、本来 createSystematically っていう名前のメソッドが吸収してくれるはずの部分が applyScope や getParentAndFillAncestors のモード増という形で波及していってしまっている気がする。

2022-05-18 10:21 UTC, hakumizuki commented on packages/app/src/server/models/page.ts
> +  pageData.lastUpdateUser = user._id;
修正しました

2022-05-19 08:08 UTC, hakumizuki commented
リファクタから実装までだとコードの変更が多すぎるのでいったんモデル層からサービス層に移したいメソッドたちを３つ移動してきました。
isSystematically による分岐などはそれらの元モデル層のメソッドたちからは排除しました。

後続でメソッドをリファクタしながら実装していきます

2022-05-19 08:22 UTC, merged