feat: Find activities between two dates
weseek/growi pull request #5853
Opened 2022-05-17 04:04 UTC by miya

## Task
[#93976](https://redmine.weseek.co.jp/issues/93976) [GROWI] [AuditLog] from, to を指定して、特定の期間を指定して検索できる
└ [#94792](https://redmine.weseek.co.jp/issues/94792) 実装

2022-05-17 05:58 UTC, miya commented on packages/app/src/components/Admin/AuditLog/DateRangePicker.tsx
> +};
react-datepicker を使って activity を表示するための期間を指定できるようにしました。

2022-05-17 05:58 UTC, miya commented on packages/app/src/components/Admin/AuditLog/DateRangePicker.tsx
> +  registerLocale(dateFnslocal[0], dateFnslocal[1]);
currentUser の言語設定に基づいてカレンダーの言語を変更
ref: https://github.com/Hacker0x01/react-datepicker#localization

2022-05-17 05:58 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +    }
react-datepicker に startDate を null にするためのメソッドがなかったため、同一の日付が入力された時に、startDate と endDate を null にする

2022-05-17 05:58 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +      const endDate = parse(parsedSearchFilter.date.endDate, 'yyyy/MM/dd', new Date());
文字列で受け取り、Date オブジェクトに変換

2022-05-17 05:58 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +      if (isValid(startDate) && isValid(endDate)) {
startDate と endDate が有効なものだったら期間を指定して検索

2022-05-17 05:58 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +      else if (isValid(startDate) && !isValid(endDate)) {
startDate が有効で、endDateが無効な時（datepicker で選択されなかった場合）に、startDateの 00:00 から 23:59 の範囲で検索

2022-05-17 05:58 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +};
api に渡す際に文字列かつ yyyy/MM/d のフォーマットに変換して渡す

2022-05-17 06:43 UTC, yuki-takei requested changes

2022-05-17 06:43 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLog/DateRangePicker.tsx
> +  registerLocale(dateFnslocal[0], dateFnslocal[1]);
言語の概念を入れず、GMT からのずれを入力できるようにしたほうが柔軟。もしくは JST とかのタイムゾーンを選べるようにするとか。

2022-05-17 06:43 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +    }
この辺の react-datepicker の仕様を吸収するロジックは DateRangePicker に閉じ込めよう。AuditLogManagement からの使い勝手を良くしたい。

2022-05-17 06:43 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/activity.ts
> +      const endDate = parse(parsedSearchFilter.date.endDate, 'yyyy/MM/dd', new Date());
try-catch が大きすぎる。HTTP status 400 にすべき箇所と 500 になりそうな箇所で分けて。

2022-05-18 01:48 UTC, miya commented on packages/app/src/components/Admin/AuditLog/DateRangePicker.tsx
> +  registerLocale(dateFnslocal[0], dateFnslocal[1]);
言語の概念は入れないようにしました

2022-05-18 01:49 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +    }
DateRangePicker に react-datepicker 特有のロジックを閉じ込めました

2022-05-18 02:03 UTC, merged