Imprv/93933 typescriptize page tag relation model
weseek/growi pull request #5857
Opened 2022-05-17 16:07 UTC by kaoritokashiki

2022-05-18 02:33 UTC, kaoritokashiki commented on packages/app/src/server/models/page-tag-relation.ts
> +pageTagRelationSchema.statics.updatePageTags = async function(pageId: ObjectIdLike, tagNames: string[])
第二仮引数を tags -> tagNamesに変更

2022-05-18 09:59 UTC, hakumizuki requested changes

2022-05-18 09:59 UTC, hakumizuki commented on packages/app/src/server/models/page-tag-relation.ts
> +export type PageIdToTagNamesMap = {[key:string]: ObjectIdLike[]}
これ型多分間違ってますね

あとこの場合、

```typescript
type PageIdToTagNamesMap = {
    [pageId:string]: string[]
}
```

か、

```typescript
type Name = string
type PageIdToTagNamesMap = {
    [pageId:string]: Name[]
}
```

とかがいいかなと思います。key を pageId にすることで情報量増やせます

2022-05-18 09:59 UTC, hakumizuki commented on packages/app/src/server/models/page-tag-relation.ts
> +: Promise<[{deletedCount: number}, PageTagRelationDocument[]]> {
多分型違います。特に `PageTagRelationDocument[]` の方確認してみてください

あと、今 this って何型になってますかね？`PageTagRelationModel` 型なのが理想なんですが

2022-05-18 09:59 UTC, hakumizuki commented on packages/app/src/server/models/tag.ts
> +export type TagIdToTagNameMap = {[key: string] : string }
ここも `key` の部分改善できそうです

2022-05-18 09:59 UTC, hakumizuki commented on packages/app/src/server/models/tag.ts
> +  getIdToNameMap(tagIds: ObjectIdLike[]): TagIdToTagNameMap
これ返り値の型 `Promise` じゃなくて大丈夫でしょうか？

逆になぜこれで動いてるのかも探って欲しいです

2022-05-18 09:59 UTC, hakumizuki commented on packages/app/src/server/models/tag.ts
>    const idToNameMap = {};
これは `TagIdToTagNameMap` 型を指定しなくて大丈夫でしょうか？

あとこのファイルも `this` の型がワークしているかみて欲しいです

2022-05-18 15:56 UTC, kaoritokashiki commented on packages/app/src/server/models/page-tag-relation.ts
> +  relatedTag: TagDocument,
Types.ObjectIdにしてしまうと、`relation.relatedTag.name` の部分で` Property 'name' does not exist on type 'ObjectId'.`とnameにアクセスできずエラーが出てしまいます。


>mongoose の populate らへんの型
このリンクの部分のことですかね?
https://mongoosejs.com/docs/typescript/populate.html

2022-05-19 02:30 UTC, kaoritokashiki commented on packages/app/src/server/models/tag.ts
>    const idToNameMap = {};
TagModelが参照されています。
<img width="181" alt="Screen Shot 2022-05-19 at 11 30 06" src="https://user-images.githubusercontent.com/59536731/169191597-4817bbf5-07df-41cd-b326-5c894358f0be.png">

2023-03-06 16:24 UTC, closed without merging