Imprv/omit login after registration
weseek/growi pull request #5860
Opened 2022-05-18 05:07 UTC by hiroki-hgs

94057 「90064 [GROWI] ユーザー新規登録後に自動ログインできる」の実装

2022-05-18 09:21 UTC, yuki-takei requested changes

2022-05-18 09:21 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +          return registerSuccessHandler(req, res, userData);
135 行目付近のコメント読んだかな？当時とは状況が変わっているなら、この辺も整理して欲しい。

2022-05-18 09:21 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +  };;
session が絡むコードを全て削除しても問題ないという結論に至った説明がほしい。口頭でよいので話しかけて。

2022-05-18 12:10 UTC, hiroki-hgs commented on packages/app/src/server/routes/login.js
> +          return registerSuccessHandler(req, res, userData);
セッション情報が保存されない場合に備えて、flashはそのまま残しました。
registerSuccessHandlerの中だと、flashの内容が関数の内容とマッチしないので、この場所に残しました。

2022-05-18 12:24 UTC, yuki-takei requested changes

2022-05-18 12:24 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +          return registerSuccessHandler(req, res, userData);
- req.login を最初にやった方がいい
- 正常系の場合
    - updateLastLoginAt と password チェックをやってほしい
    - password がセットされていたら、元々行きたかった `req.session.redirectTo` へ
- 異常系の場合
    - flash メッセージのセット
    - `req.session.redirectTo` へ
        - flash メッセージが表示されたログインページに飛ばされるはずなので、そこからユーザー自身にログインさせる
        - ログイン成功すれば、晴れて `req.session.redirectTo` に行ける

2022-05-18 13:10 UTC, yuki-takei requested changes

2022-05-18 13:10 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +        debug(err);
新しく書くコードでは `debug()` を使わず、`logger.debug()` を使ってください

2022-05-18 13:10 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +      } else {
eslint で修正されるべき箇所

2022-05-18 13:10 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +  };;
eslint で修正されるべき箇所

2022-05-19 01:50 UTC, hiroki-hgs commented on packages/app/src/server/routes/login.js
> -    });
パスワードがない場合のコードを復活させ、コメントを追加しました。
このリダイレクト先を新しく作ったほうがいいのか、意見をいただきたいです。

2022-05-24 09:18 UTC, yuki-takei requested changes

2022-05-24 09:18 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> -    });
1. パスワードがない場合のコードが必要だというのは、誰かと相談した結果？
    - もしそうならその相談の内容を教えてほしい (口頭でも可)
1. リダイレクト先は新しく作るのではなく、既に存在している `/me` ページにリダイレクトさせて、かつパスワード設定タブが選択されるように改修した方がいいのでは？
    - このタスクのスコープには入れず、後続タスクでもいいとは思う

2022-05-24 13:39 UTC, merged