feat: Get Snapshot username API
weseek/growi pull request #5864
Opened 2022-05-19 02:45 UTC by miya

## Task
[#93768](https://redmine.weseek.co.jp/issues/93768) [GROWI] [AuditLog] 特定の username を指定して検索できる
└ [#93768](https://redmine.weseek.co.jp/issues/93768) [GROWI] [AuditLog] 特定の username を指定して検索できる

2022-05-19 03:33 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +  });
bootstrap-typeahead に文字を入力した時に、username 候補を返却する API を実装しました。（routes/apiv3/users.js にするか迷いましたが...）

2022-05-19 03:33 UTC, miya commented on packages/app/src/server/routes/apiv3/activity.ts
> +      }).distinct('username');
user collection から、削除されていない user の username を配列で取得

2022-05-19 04:47 UTC, yuki-takei requested changes

2022-05-19 04:47 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/activity.ts
> +  router.get('/usernames', loginRequiredStrictly, adminRequired, async(req: Request, res: ApiV3Response) => {
Slack で話した FB 内容整理

https://youtrack.weseek.co.jp/issue/GW-7773 で必要な改修とかぶっているので、要件を整理して master 向けに先に実装完了させる


## 共通で必要な機能
- active user 取得
- inactive user 取得オプション
- ページング

## Audit log 向けに必要な機能
- snapshot からも取得するオプション

## コメント入力時のサジェストで必要な機能
- 部分一致オプション
- display name でも引っかけるオプション

2022-05-19 04:57 UTC, yuki-takei requested changes

2022-05-19 04:57 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/activity.ts
> +      }).distinct('snapshot.username');
「上記で取得した username が含まれない username」である必要はないと思う。ページング実装すると除外が難しいというのもある。

2022-05-19 04:57 UTC, yuki-takei commented on packages/app/src/stores/activity.ts
> +};
q が不正な値の場合はキーを null に

2022-05-24 06:34 UTC, miya commented on packages/app/src/server/routes/apiv3/users.js
> +      }
activity.snapshot.username を配列で返却

2022-05-24 06:34 UTC, miya commented on packages/app/src/server/models/user.js
> +    return result.limit(limit);
クエリを追加できるように拡張しました。

2022-05-24 06:34 UTC, miya commented on packages/app/src/server/models/activity.ts
> +};
activity document 内の snapshot.username の 配列（string[]）を重複なしで取得できるメソッドを作成しました

2022-05-24 06:34 UTC, miya commented on packages/app/src/stores/user.tsx
> +};
`users/username` を SWR で取得できるようにしました

2022-05-24 09:36 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/users.js
> +    const limit = +req.query.limit || 10;
limit と返り値の型を再設計したい。
各10件ずつで30件返って来るというのが直感的ではないので…

2022-05-25 08:48 UTC, miya commented on packages/app/src/components/PageEditor/CommentMentionHelper.ts
> +      displayText: username,
`users/list` -> `users/usernames` を利用するに修正しました

2022-05-25 08:48 UTC, miya commented on packages/app/src/server/models/activity.ts
> +};
sort、offset、limit をカスタムしたもを入れることができるようにし、それぞれにデフォルト値を入れました。
戻り値には、username の配列と、q にマッチした総数が totalCount に入ります。

2022-05-25 08:48 UTC, miya commented on packages/app/src/server/models/user.js
> +    return { users, totalCount };
sort、offset、limit をカスタムしたもを入れることができるようにし、それぞれにデフォルト値を入れました。
戻り値には、username の配列と、q にマッチした総数が totalCount に入ります。

2022-05-25 08:48 UTC, miya commented on packages/app/src/server/routes/apiv3/users.js
> +      const options = JSON.parse(req.query.options || '{}');
options をオプショナルで受け取れるようにしています。

2022-05-25 08:48 UTC, miya commented on packages/app/src/server/routes/apiv3/users.js
> +      }
`options.isIncludeActiveUsernames` に明示的に false を渡さない限り、activeUser を返すようにしました。

2022-05-25 08:48 UTC, miya commented on packages/app/src/server/routes/apiv3/users.js
> +      }
全てのカテゴリーの username をまとめて返すようにしました。

2022-05-25 09:07 UTC, yuki-takei requested changes

2022-05-25 09:07 UTC, yuki-takei commented on packages/app/src/server/models/activity.ts
> +activitySchema.statics.findSnapshotUsernamesByUsernameRegex = async function(q: string, option) {
ts なので型を付けて(option も)

2022-05-25 09:07 UTC, yuki-takei commented on packages/app/src/server/models/activity.ts
> +  const sortOpt = opt.sortOpt || { _id: 1 };
これが username 昇順の指定であることをコメントで書いて

2022-05-25 09:07 UTC, yuki-takei commented on packages/app/src/server/models/activity.ts
> +    .limit(limit);
この aggregation、パフォーマンスが心配。

- snapshot.username ってインデックス付けるのは無理かな？検討を
- activity ってドキュメント数かなりの数になりそうなので、その対策をしたい
    - conditions で検索範囲の期間を絞ったほうがよさそう
        - これは、全走査は諦める方向

別ストーリーで、activity の保持期間を設定可能にしたいね。

2022-05-25 09:07 UTC, yuki-takei commented on packages/app/src/stores/user.tsx
> +};
stringify する必要ある？

2022-05-25 10:02 UTC, miya commented on packages/app/src/components/PageEditor/CommentMentionHelper.ts
> +      displayText: username,
hook を使うことができないためこのままで良いということになりました（口頭で話した）

2022-05-25 10:12 UTC, miya commented on packages/app/src/stores/user.tsx
> +};
そのまま渡せば、勝手に string になってくれるの不要でした...

2022-05-25 12:59 UTC, miya commented on packages/app/src/server/models/activity.ts
> +activitySchema.statics.findSnapshotUsernamesByUsernameRegex = async function(q: string, option) {
型つけました

2022-05-25 12:59 UTC, miya commented on packages/app/src/server/models/activity.ts
> +  const sortOpt = opt.sortOpt || { _id: 1 };
書きました

2022-05-26 09:44 UTC, yuki-takei requested changes

2022-05-26 09:44 UTC, yuki-takei commented on packages/app/src/server/models/activity.ts
> +    .limit(limit)
opt で入ってくる offset, limit は、findSnapshotUsernamesByUsernameRegex メソッドを使う側としてはページングの指定値として渡してくるよね。

一方ここで指定してるのは、`.match(conditions)` を適用する母集団を限る目的なので、opt.limit をそのまま使うのはおかしい。

2022-05-26 13:26 UTC, miya commented on packages/app/src/server/models/activity.ts
> +    .limit(limit)
- ひとまず母集団を絞るための limit は固定値で 10000 を入れました

2022-05-27 07:56 UTC, yuki-takei requested changes

2022-05-27 07:56 UTC, yuki-takei commented on packages/app/src/server/models/activity.ts
> +    .limit(limit);
offset の使い方が違うのでやり直してください

2022-05-27 09:18 UTC, yuki-takei approved these changes

2022-05-27 09:18 UTC, merged