feat: Delete all PageOperation documents except ones with actionType set to Rename
weseek/growi pull request #5877
Opened 2022-05-23 07:35 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/95517

2022-05-23 22:03 UTC, hakumizuki requested changes

2022-05-23 22:03 UTC, hakumizuki commented on packages/app/src/server/models/page-operation.ts
> +schema.statics.clearAll = async function(
若干実装が冗長に見えるのはわかりますが、これは exclude を指定するより、消す対象の actionType を指定してあげる方が将来的にはわかりやすくなると思います

今のままだと、

```typescript
await PageOperation.clearAll([PageActionType.Rename]);
```

ここをみた時に Rename が消えるのかな？と思ってしまうかもです

2022-05-23 22:03 UTC, hakumizuki commented on packages/app/src/server/crowi/index.js
> -    await this.pageOperationService.init();
タイミングを init では無くした理由はなんですか？

2022-05-24 04:16 UTC, Yohei-Shiina commented on packages/app/src/server/crowi/index.js
> -    await this.pageOperationService.init();
過去に、「もろもろの service setup が終わってからPageOperationを削除をした方がいいかもですね、セットアップに時間かかってしまうので」、という話をした憶えがあってここには書かない方法でやりました

個人的には削除処理は 1query だけなので init の中でいいとは思ってます

2022-05-24 04:16 UTC, Yohei-Shiina commented on packages/app/src/server/models/page-operation.ts
> +schema.statics.clearAll = async function(
たしかにそうですねそっちの書き方にします

2022-05-24 05:10 UTC, hakumizuki requested changes

2022-05-24 05:10 UTC, hakumizuki commented on packages/app/src/server/models/page-operation.ts
> +  deleteAllByPageActionType(deleteTypeList: PageActionType[]): Promise<void>
`deleteByActionTypes` はどうでしょうか？

引数名は `actionTypes` で良いと思います

2022-05-24 06:08 UTC, merged