Fix/issue 5754 1 change var
weseek/growi pull request #5884
Opened 2022-05-24 03:42 UTC by jam411

対象ストーリ: https://redmine.weseek.co.jp/issues/95622
対象issue: https://github.com/weseek/growi/issues/5754

＜原因＞
・search-result-contentなどの検索画面のCSSクラス'on-search'が読み込めていない.
・private-legacy-pages.htmlとsearch.htmlにて, additionalBodyClass変数に'on-search'がsetされ,
body classにadditionalBodyClassで読み込まれることによって検索画面のCSSが実現している.
・「コンテンツ幅100%」に設定した場合, layout.htmlでadditionalBodyClass変数に'growi-layout-fluid'クラスがsetされるため, additionalBodyClassが上書きされていた.

＜前提＞
・現状でadditionalBodyClassは'on-search', 'growi-layout-fluid'のみの代入用で使用されている.
・'on-search'と'growi-layout-fluid'両方のCSSクラスが必要なページがない前提.
・layout.htmlはレイアウトテンプレートのため不要なクラスは読み込まないようにしたい.

＜変更箇所＞
layout.html
62行目 （条件分岐を追加）

＜説明＞
前提より, 「コンテンツ幅100%」設定でもadditionalBodyClassにすでに何かがsetされていたら'growi-layout-fluid'をsetしない.
・growi-layout-fluidは優先されない.
・この実装では, additionalBodyClassで使用するクラスを同時に使いたい場合に対応できない.

2022-05-24 09:10 UTC, yuki-takei commented
> ・この実装では, additionalBodyClassで使用するクラスを同時に使いたい場合に対応できない.

両方対応させてください。つまり上書きするような実装ではだめだということだね。

2022-05-26 02:35 UTC, jam411 commented
両方対応させられるように、'growi-layout-fluid'用の変数を新しく作成する実装としました。

2022-05-26 06:09 UTC, yuki-takei requested changes

2022-05-26 06:09 UTC, yuki-takei commented on packages/app/src/server/views/layout/layout.html
> +  class="{% block html_base_css %}{% endblock %} growi {{ additionalBodyClass }} {{ additionalFluidBodyClass }}"
- additionalBodyClass を additionalBodyClasses として、配列型に
- layout.html では、配列を展開する
- private-legacy-pages.html と search.html では、配列に値を追加する

2022-05-27 03:52 UTC, jam411 commented
- 配列で処理しました.

- [packages/app/src/server/util/middlewares.js](https://github.com/weseek/growi/pull/5884/commits/8b3ab987a1ec5f1fdcffa16753d0fa59bb595da3#diff-6f3ce59c2d6af14682876f78d21eb6e8e7f6b97fa92e34fe1048b462617096f7)にpushフィルターを作成しました.
7-10行目は自動フォーマットです.

2022-05-27 08:09 UTC, yuki-takei approved these changes

2022-05-27 08:09 UTC, merged