feat: Inject PageOperation info to page items for page tree
weseek/growi pull request #5888
Opened 2022-05-24 10:49 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/93516

2022-05-24 10:57 UTC, Yohei-Shiina commented on packages/app/src/interfaces/page.ts
> +export type IPageOperationProcessInfo = Partial<Record<IPageActionType, {isProcessing: boolean}>>
```
{
    "Rename": { 
        isProcessing: boolean 
    },
    ... 将来的にここに Delete とかが入ることを想定
}
```

2022-05-24 11:00 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +    const pageOpTargetPageIds = pageOperations.map(op => op.page._id.toString());
pageOpTargetPageIds は PageOperation doc の持つ Page の Id

2022-05-24 11:01 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +    const pageOpTargetPageIds = pageOperations.map(op => op.page._id.toString());
- `copyPages` は ページツリーに表示するページのデータ
- `pageOpTargetPageIds` は PageOperation doc の持つ Page の Id

2022-05-25 04:50 UTC, hakumizuki requested changes

2022-05-25 04:50 UTC, hakumizuki commented on packages/app/src/interfaces/page-operation.ts
> +export const IPageActionType = {
`I` は interface を意味するので、いわゆる enum 的なものにつけると違和感がありますね

2022-05-25 04:50 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    const pageOpTargetPageIds = pageOperations.map(op => op.page._id.toString());
.toString() は比較寸前までやらなくていいと思います。

あとここで id に変換する必要まだないんじゃないですかね？

あと target ってどういう意味ですかね？

2022-05-25 05:39 UTC, Yohei-Shiina commented on packages/app/src/interfaces/page-operation.ts
> +export const IPageActionType = {
Iだけ消しました

2022-05-27 05:49 UTC, hakumizuki requested changes

2022-05-27 05:49 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +  async injectProcessInfoIntoPages(
関数名から Rename 専門の inject だとはわからないですね。この関数はなにをとって何をして何を返す関数なのかコメントをつけてみてください。で、名前も再検討してみてください

2022-05-27 05:49 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    }
ここの処理も Rename 専門になっているのですが、もし将来的にどんなアクションでも使用可能なメソッドにするには、`[PageActionType.Rename]` この部分を動的に変えるような実装にしないとですね。

もちろんこの場合は `const pageOperations = await PageOperation.find({ actionType: PageActionType.Rename });` ここも actionType でフィルタかけないようになります

2022-06-02 07:42 UTC, hakumizuki requested changes

2022-06-02 07:42 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    const markedPages = _pages.map((page: PageDocument & { isTarget?: boolean }) => {
こっちも inject 方式でいいかもですね
新しい配列できちゃってるので
いやもう何なら `injectMetadataIntoPagesForPageTree` っていうメソッド作ってまとめてインジェクトしたいですね
どうせここでしか使われないし

2022-06-02 07:42 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +      if (operatingPageids.includes(pageId)) {
i => I

2022-06-02 10:04 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    const operatingPageIds: ObjectIdLike[] = Object.keys(processInfo);
これ `string[]` ですかね？

2022-06-02 10:04 UTC, hakumizuki approved these changes

2022-06-02 10:05 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +    const operatingPageIds: ObjectIdLike[] = Object.keys(processInfo);
です！

2022-06-02 10:21 UTC, Yohei-Shiina commented on packages/app/src/server/service/page.ts
> +    const markedPages = _pages.map((page: PageDocument & { isTarget?: boolean }) => {
isTarget を付与する用の private メソッドを作成
一旦それ以上は対応しないことになった

2022-06-02 10:22 UTC, merged