feat: 95830 implement rate limiter
weseek/growi pull request #5908
Opened 2022-05-27 03:21 UTC by yukendev

- 環境変数を設定することでapiのリクエストの回数制限を設定可能にする
設定例
API_RATE_LIMIT_010_FOO_ENDPOINT=/_api/v3/foo
API_RATE_LIMIT_010_FOO_METHODS=GET,POST
API_RATE_LIMIT_010_FOO_CONSUME_POINTS=10

後続タスクでやること
- メモリではなく、DBで回数制限をかける(https://redmine.weseek.co.jp/issues/96274)
- ユーザーが消費ポイントではなく、一定時間の回数で制限を設定できるようにする(https://redmine.weseek.co.jp/issues/96275)

2022-05-27 08:07 UTC, yuki-takei requested changes

2022-05-27 08:07 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +module.exports = (rateLimiter, defaultPoints: number) => {
型を明示してください

2022-05-27 08:07 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    const endpoint = req.url.replace(/\?.*$/, '');
これどういう操作？例がほしい。

2022-05-27 08:07 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    };
module.exports 外に書いて共通化して

2022-05-27 08:07 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    });
process.env から予め再利用可能な dictionary (hashmap 的なもの) を作っておこう

2022-05-27 08:07 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    }
早期リターンの考え方は OK

2022-05-27 08:07 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    await consumePoints(Number(customizedConsumePoints));
カスタム値の取得はメソッド切り出して共通化して。

2022-05-27 09:03 UTC, yukendev commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +module.exports = (rateLimiter, defaultPoints: number) => {
修正済み

2022-05-27 09:14 UTC, yukendev commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    const endpoint = req.url.replace(/\?.*$/, '');
url: /_api/v3/page/info?pageId=628c64f2b78c8d7e084ee979
endpoint: /_api/v3/page/info
こんなイメージです。
間違えてkeyをip+endpointにしていたので、ip+urlに修正しました。

2022-05-27 09:39 UTC, yukendev commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    await consumePoints(Number(customizedConsumePoints));
修正済み

2022-05-27 09:46 UTC, yukendev commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    };
修正済み

2022-05-27 10:34 UTC, yuki-takei requested changes

2022-05-27 10:34 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    const endpoint = req.url.replace(/\?.*$/, '');
これだとハッシュは除去できないと思う。pathname って req から取れない？
取れなければ URL module 使うとか。

2022-05-27 10:34 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    const envVarDic = process.env;
- `const settings = envVarDic['/_api/v3/healthcheck']` で、settings には healthcheck エンドポイントのための設定(max や対応 method)が入っていてほしい
- そのためのデータ(envVarDic)はミドルウェアの外で作っておく
    - サーバー起動時に一回だけ作成する
    - 39行目の正規表現マッチや43行目の filter 処理のようなコストがかかる処理をリクエストがくる度に実行する日宇町が必要ないように

2022-05-27 12:32 UTC, yuki-takei requested changes

2022-05-27 12:32 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    const key = req.ip + req.url;
endpoint が入ってない

2022-05-27 12:32 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    });
これがもうパフォーマンス悪い

2022-05-27 12:39 UTC, yuki-takei requested changes

2022-05-27 12:39 UTC, yuki-takei commented on packages/app/src/server/routes/index.js
> +const envVarDicForApiRateLimiter = generateEnvVarDicForApiRateLimiter();
これを呼ぶ処理は api-rate-limiter.ts に閉じ込めて良い。index.js でやることではない。

2022-05-27 12:39 UTC, yuki-takei commented on packages/app/src/server/util/generateEnvVarDicForApiRateLimiter.ts
> +};
このメソッドでもっと加工を施し、apiRateEndpointDic を便利にする必要がある。優先度の低い設定は全て捨てて構わない。

2022-05-27 14:46 UTC, yuki-takei requested changes

2022-05-27 14:46 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +    });
forEach 回す必要ないよね

2022-05-27 14:52 UTC, yuki-takei requested changes

2022-05-27 14:52 UTC, yuki-takei commented on packages/app/src/server/util/generateApiRateLimitConfig.ts
> +  });
ここまではいいとして

ここから、

## メインルーティン

1. API_RATE_LIMIT_.*_ENDPOINT のリストを昇順ソート
2. 上から順に、「IApiRateLimitConfig 構築メソッド」を呼んで登録する

これで後勝ちになる。

## 「IApiRateLimitConfig 構築メソッド」について
- `API_RATE_LIMIT_HOGE_ENDPOINT` から、`API_RATE_LIMIT_HOGE_METHODS` や `API_RATE_LIMIT_HOGE_CONSUME_POINTS` などを取得して、IApiRateLimitConfig を返す

2022-05-30 11:23 UTC, yuki-takei commented on packages/app/src/server/util/generateApiRateLimitConfig.ts
> +    const target = key.replace('API_RATE_LIMIT_', '').replace('_ENDPOINT', '');
`API_RATE_LIMIT_ENDPOINT_API_RATE_LIMIT_ENDPOINT` みたいな文字列だったら変なことになるね

2022-05-30 12:14 UTC, yukendev commented
リクエストが来た時に、メソッドによって分岐する処理を書き忘れていたので加えました。

2022-05-30 14:34 UTC, yuki-takei requested changes

2022-05-30 14:34 UTC, yuki-takei commented on packages/app/src/server/util/generateApiRateLimitConfig.ts
> +    }
`== null` で統一

2022-05-30 14:34 UTC, yuki-takei commented on packages/app/src/server/util/generateApiRateLimitConfig.ts
> +    const endpointRegExp = /^API_RATE_LIMIT_.*_ENDPOINT/;
- `.*` だと1文字もない場合も引っかかる
- 利用できる文字種もうちょっと絞ったほうがよさそう

2022-05-30 14:34 UTC, yuki-takei commented on packages/app/src/server/util/generateApiRateLimitConfig.ts
> +    const priorityB = Number(targetB.split('_')[0]);
この辺のコード、33 行目の replace とやってることかぶってない？もっと効率良くできる。

2022-05-30 14:42 UTC, yukendev commented on packages/app/src/server/util/generateApiRateLimitConfig.ts
> +    const priorityB = Number(targetB.split('_')[0]);
修正済み

2022-05-30 18:22 UTC, yuki-takei requested changes

2022-05-30 18:22 UTC, yuki-takei commented on packages/app/src/server/util/generateApiRateLimitConfig.ts
> +    }
getTargetFromKey で取得できる文字列の頭に数字を入れるかどうかは運用者の自由なので、priorityA, priorityB は切り出さなくていいし Number かどうかもチェックしなくていいと思うな。単純にソートすればそれでよい。

2022-05-30 18:22 UTC, yuki-takei commented on packages/app/src/server/util/generateApiRateLimitConfig.ts
> +    const endpointRegExp = /^API_RATE_LIMIT_.+_.+_ENDPOINT/;
現状 `.+_.+` となっている部分を、`\w+` に変えてください。

2022-05-31 04:29 UTC, yukendev commented on packages/app/src/server/util/generateApiRateLimitConfig.ts
> +    const endpointRegExp = /^API_RATE_LIMIT_.+_.+_ENDPOINT/;
修正済み

2022-05-31 05:27 UTC, merged