fix: Slack channels are not automatically filled after setting user trigger notification
weseek/growi pull request #5911
Opened 2022-05-27 07:00 UTC by kaoritokashiki

2022-05-30 12:01 UTC, yuki-takei requested changes

2022-05-30 12:01 UTC, yuki-takei commented on packages/app/src/server/views/layout-growi/identical-path-page.html
> -      data-slack-channels="{% if page %}{{ page.slackChannels }}{% endif %}"
「data-slack-channels」で grep してほしい。CommentContainer にも影響がありそう。

2022-06-02 12:47 UTC, kaoritokashiki commented on packages/app/src/server/service/user-notification/index.ts
> -
ブラウザのslack channelsに値が入力されていなくとも、管理画面で設定されているchannelに通知がいく仕様を廃止しました。

2022-06-02 12:48 UTC, kaoritokashiki commented on packages/app/src/server/views/layout-growi/identical-path-page.html
> -      data-slack-channels="{% if page %}{{ page.slackChannels }}{% endif %}"
packages/app/src/components/PageComment/CommentEditor.jsx
影響があったので修正しました。

2022-06-02 13:03 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
> +  const [slackChannelsStr, setSlackChannelsStr] = useState<string>('');
## state管理が必要な理由
元々、UserTriggerNotification で設定した`slackChannels`が反映されていないことがバグとして挙がっていました。
(`UpdatePost` collection に格納されているslackChannelsをフロント側で取得するコードの記載が何らかの理由で失われていた)

このPRでは、`useSWRxSlackChannels` でapiを叩き、`UpdatePost` からslackChannels (string[]) を取得する操作を追加したので、配列をstringに変換する必要があります。

2022-06-02 13:12 UTC, kaoritokashiki commented on packages/app/src/components/PageComment/CommentEditor.jsx
> +    }
最初は propsで取得する `slackChannels` は null が変えてくるので、データが返ってくる場合に stateを更新するように `componentDidUpdate` を使用しています。

2022-06-02 13:27 UTC, kaoritokashiki commented on packages/app/src/client/services/ContextExtractor.tsx
> -  const slackChannels = mainContent?.getAttribute('data-slack-channels') || '';
`data-slack-channels` を取得するのを廃止しています。

2022-06-02 13:28 UTC, kaoritokashiki commented on packages/app/src/stores/context.tsx
> -
UpdatePost collectionからslackChannelsのデータを取得するという処理をしていないので、削除しました。

2022-06-02 13:46 UTC, kaoritokashiki commented on packages/app/src/server/crowi/index.js
> +  allModels.UpdatePost = UpdatePost;
そちらはcrowiに依存しないModel達を allModelsに挿入しています。
https://github.com/weseek/growi/blob/d94000f0bd5f7d31cd314a0e2b9f27196dc94766/packages/app/src/server/crowi/index.js#L276-L291

2022-06-02 13:59 UTC, kaoritokashiki commented on packages/app/test/integration/models/update-post.test.js
> +import UpdatePost from '../../../src/server/models/update-post';
crowiへの依存を廃止しました。

2022-06-02 14:26 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
> +                isSlackEnabled={isSlackEnabled || false}
修正いたしました

2022-06-02 14:49 UTC, yuki-takei requested changes

2022-06-02 14:49 UTC, yuki-takei commented on packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
> +  const { data: slackChannelsData } = useSWRxSlackChannels();
## 現状
useSWRxSlackChannels が currentPagePath に依存する(context を自律的に取ってくる)

## 改善案
useSWRxSlackChannels pagePath を引数に取る

2022-06-02 14:49 UTC, yuki-takei commented on packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
> +      setSlackChannelsStr(slackChannelsData.toString());
isSlackEnabled も false で初期化してください

2022-06-03 05:33 UTC, merged