feat: 96375-darktheme-pagelist-bg
weseek/growi pull request #5920
Opened 2022-05-30 04:42 UTC by shukmos

# やったこと
- ページリストの色が真っ白で変だったので修正した
- task: https://redmine.weseek.co.jp/issues/96375
## Before
![image](https://user-images.githubusercontent.com/20252919/170916294-d4f94a60-0e5c-4f46-bc13-5a754a60e247.png)

## After
![image](https://user-images.githubusercontent.com/20252919/170916279-944865cd-3268-4ac3-bfeb-fa69feee06bd.png)

2022-05-30 05:45 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors-dark.scss
> +      background-color: transparent;
これは、dark mode関係なく、ページリストにて `list-group-flush`を使用している部分は　bootstrap4 のdefault値である`#fff`が適用されてしまってますね。

light / dark 関係なく全てのテーマにて transparent が設定されるように修正お願いします。

https://getbootstrap.jp/docs/4.3/components/list-group/#flush
<img width="1362" alt="Screen Shot 2022-05-30 at 14 43 17" src="https://user-images.githubusercontent.com/59536731/170924888-16571320-cb11-40df-ac21-1b503e836e68.png">

2022-05-30 06:02 UTC, kaoritokashiki requested changes

2022-05-30 06:10 UTC, shukmos commented on packages/app/src/styles/theme/_apply-colors-dark.scss
> +      background-color: transparent;
## override-list-group-item の指定が適用されていない原因
- 検索結果一覧及び管理者設定画面の左メニューではli要素に`list-group`が親要素に使われている
  - これはBootstrapの書き方
- ページリストでは`list-group`が使われておらず`page-list`のクラスがあたっている。
- override-list-group-itemは`list-group`に対して作用するので、page-listの方には影響がない。

2022-06-01 08:30 UTC, shukmos commented
- ulに対して`.list-group`が当たるようにしました。

2022-06-02 06:56 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors-dark.scss
> +  // on serch
コメントを `on serch` に変更した理由が知りたいです!
クラス名的に検索以外にも適用されていそうなので。

2022-06-02 06:56 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors.scss
> +          fill: $link-color;
これってどこの色ですかね? 👀  足跡アイコンとかですか??

2022-06-02 06:56 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors.scss
> -        color: $color-global;
一応確認です! 
<img width="388" alt="Screen Shot 2022-06-02 at 15 55 34" src="https://user-images.githubusercontent.com/59536731/171571087-6d974555-3e80-48b2-8952-61766fbc34a3.png">

<img width="559" alt="Screen Shot 2022-06-02 at 15 54 15" src="https://user-images.githubusercontent.com/59536731/171571197-7e2db0c5-69bd-4559-8ccf-bae83a5239e2.png">



XDでの指定とは異なるけど、link-color の方がいいという判断をしたということであっています??
https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/9aa528ff-a75e-4e9a-adb9-b4b942647f29/

2022-06-02 06:58 UTC, kaoritokashiki commented on packages/app/src/components/PageList/PageList.tsx
> +      <ul className="page-list-ul list-group list-group-flush">
🥇

2022-06-03 05:21 UTC, shukmos commented on packages/app/src/styles/theme/_apply-colors.scss
> -        color: $color-global;
そうです。一旦Link-colorのほうが良いと判断しました。そこは認識しております。

2022-06-03 05:34 UTC, kaoritokashiki commented on packages/app/src/styles/theme/_apply-colors.scss
> -        color: $color-global;
畏まりました!

2022-06-03 05:40 UTC, shukmos commented on packages/app/src/styles/theme/_apply-colors.scss
> +          fill: $link-color;
足跡ですね。よく考えたらcolor-globalが正しいので、そっちに戻します。

2022-06-03 05:46 UTC, shukmos commented on packages/app/src/styles/theme/_apply-colors-dark.scss
> +  // on serch
最初は検索にしか使われていない記述だったのでそのようにコメントしておいたのですが。
作業の中で検索以外にも使われるように記述し直したので、on serchは正しくないですね。List groupに戻します。

2022-06-03 06:10 UTC, kaoritokashiki approved these changes

2022-06-03 06:10 UTC, merged