feat: 96274 96275 connect to mongo and refactor config system
weseek/growi pull request #5935
Opened 2022-05-31 05:50 UTC by yukendev

- apiの制限をmongoDBで管理する
- 利用者が一定時間の回数でリクエストを制限できるようにする
現在のデフォルト設定
1秒間に10回

2022-05-31 18:08 UTC, yuki-takei requested changes

2022-05-31 18:08 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +  await rateLimiter.consume(key, consumePoints)
## syntax について
ここ前のタスクで指摘しないといけなかった点だけど、この行以降で使っている then/catch は Promise の世界の関数。これと async/await を混在させるのはよくない。async/await + try/catch を利用するコードに寄せてください。

## エラーハンドリングについて
それから catch で logger.error しているけれど、これだけじゃだめだね。リクエストを拒否するレスポンスを返さないといけない。

consumePoints では catch をせず、consumePoints を使っている側で catch してください。

2022-06-01 04:56 UTC, yukendev commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +  await rateLimiter.consume(key, consumePoints)
修正済み

2022-06-01 09:04 UTC, yuki-takei requested changes

2022-06-01 09:04 UTC, yuki-takei commented on packages/app/src/server/middlewares/api-rate-limiter.ts
> +      logger.error(`too many request at ${key}`);
- key は hash 化してください
- logger.error では key をそのまま載せず、ip と path を含むメッセージにしてください

2022-06-01 10:24 UTC, merged