support: testcode for calc applicable grant data
weseek/growi pull request #5941
Opened 2022-05-31 22:26 UTC by kaoritokashiki

2022-06-03 07:09 UTC, hakumizuki requested changes

2022-06-03 07:09 UTC, hakumizuki commented on packages/app/test/integration/service/page-grant.test.js
> +      await expect(result[PageGrant.GRANT_PUBLIC]).toBeNull();
`result` のまんまで expect して欲しいです！

```typescript
expect(result).toStrictEqual({
  [PageGrant.GRANT_PUBLIC]: null
})
```

下のやつもこんな感じでお願いします

あと `await` 必要ですかね？どっちでもいいっちゃいいんですが。

2022-06-03 11:12 UTC, kaoritokashiki commented on packages/app/test/integration/service/page-grant.test.js
> +      await expect(result[PageGrant.GRANT_PUBLIC]).toBeNull();
そのように修正いたしました!
`await`も不要だったので削除しました。

2022-06-07 06:45 UTC, hakumizuki requested changes

2022-06-07 06:45 UTC, hakumizuki commented on packages/app/test/integration/service/page-grant.test.js
> +      expect(result).toStrictEqual({ [PageGrant.GRANT_PUBLIC]: null, [PageGrant.GRANT_RESTRICTED]: null });
これ `GRANT_RESTRICTED` 入ってきてるのバグですね。。。
入ってきている = トップページをリンク知ってる人のみのページにできる
ということなので。

```typescript
    // -- Public only if top page
    const isOnlyPublicApplicable = isTopPage(page.path);
    if (isOnlyPublicApplicable) {
      data[Page.GRANT_PUBLIC] = null;
      return data;
    }
```

この部分を

```typescript
    // -- Public only if top page
    const isOnlyPublicApplicable = isTopPage(page.path);
    if (isOnlyPublicApplicable) {
      return {
          [PageGrant.GRANT_PUBLIC]: null,
      };
    }
```

こうしてください ....

で、`const data` を下げてください。お願いします

2022-06-07 06:45 UTC, hakumizuki commented on packages/app/test/integration/service/page-grant.test.js
> +          [PageGrant.GRANT_PUBLIC]: null, [PageGrant.GRANT_RESTRICTED]: null, [PageGrant.GRANT_OWNER]: null, [PageGrant.GRANT_USER_GROUP]: userGroupRelation,
細かいんですが、toStrictEqual のなかの object 改行してみやすく欲しいです。将来増えたときにどうせ改行されるので

2022-06-07 06:45 UTC, hakumizuki commented on packages/app/test/integration/service/page-grant.test.js
> +      const AnyoneWithTheLinkRes = await pageGrantService.calcApplicableGrantData(rootAnyoneWithTheLinkPage, user1);
最初の A を a にしましょう

2022-06-07 06:45 UTC, hakumizuki commented on packages/app/test/integration/service/page-grant.test.js
> +      // Public
これ追加で、user1 じゃないユーザーが実行したときに `[PageGrant.GRANT_OWNER]: null` が入ってこないことを expect して欲しいです

test() を分けてもいいと思います

2022-06-07 12:02 UTC, kaoritokashiki commented on packages/app/test/integration/service/page-grant.test.js
> +      expect(result).toStrictEqual({ [PageGrant.GRANT_PUBLIC]: null, [PageGrant.GRANT_RESTRICTED]: null });
なるほどです。修正いたしました!

2022-06-07 12:10 UTC, kaoritokashiki commented on packages/app/test/integration/service/page-grant.test.js
> +    });
- parent page のgrantUserでない場合は、` PageGrant.GRANT_OWNER` が選択できない
のテストを追加いたしました。

2022-06-07 12:12 UTC, kaoritokashiki commented on packages/app/test/integration/service/page-grant.test.js
> +      expect(result).toStrictEqual({ [PageGrant.GRANT_PUBLIC]: null, [PageGrant.GRANT_RESTRICTED]: null });
```
   // -- Public only if top page
    const isOnlyPublicApplicable = isTopPage(page.path);
    if (isOnlyPublicApplicable) {
      return {
          [Page.GRANT_PUBLIC]: null,　// not [PageGrant.GRANT_PUBLIC]: null,
      };
    }
```
で修正いたしました

2022-06-08 05:05 UTC, hakumizuki requested changes

2022-06-08 05:05 UTC, hakumizuki commented on packages/app/src/server/service/page-grant.ts
>      // -- Public only if top page
この関数の

```typescript
    // Increment an object (type IRecordApplicableGrant)
    // grant is never public, anyone with the link, nor specified
    const data: IRecordApplicableGrant = {
      [Page.GRANT_RESTRICTED]: null, // any page can be restricted
    };
```

この部分を L424 あたりに移動お願いします orz

2022-06-09 04:22 UTC, merged