fix/create new component that validate url has compare param
weseek/growi pull request #5945
Opened 2022-06-01 10:40 UTC by hirokei-camel

タスクURL: https://redmine.weseek.co.jp/issues/96427

URLがクエリ文字列'compare'を持つか否かの検証をし、モーダルを表示するコンポーネントを新規作成しました。

2022-06-01 12:00 UTC, yukendev commented on packages/app/src/client/services/ShowPageAccessories.tsx
> +function hasURLQueryParamValue(key: string): string | null {
やっぱりメソッド名が「has」で始まるとbooleanが返ってくるから、getとかで命名した方がよさそう。
あと、返り値の型がstring | nullなのにあえて空文字を入れるのはなぜか。paramがない場合はnullを返せば良さそう。

2022-06-01 12:08 UTC, hirokei-camel commented on packages/app/src/components/PageAccessoriesModal.tsx
>  import React, { useEffect, useMemo, useState } from 'react';
コンポーネント内で検証するコードを書いたときの残りが消せてませんでした！
必要ないので消します。

2022-06-01 12:09 UTC, hirokei-camel commented on packages/app/src/client/services/ShowPageAccessories.tsx
> +function hasURLQueryParamValue(key: string): string | null {
なるほど！getの方が適切ですね！
nullに関しては深く考えずに記述していました。。。ありがとうございます！！
修正します。

2022-06-01 13:53 UTC, hirokei-camel commented
PageAccessoriesModalの差分に関しては、一度コードを変更してから取り消した際、自動的に発生したものです。
自分で施した変更に関しては削除済です。

2022-06-02 07:13 UTC, yuki-takei requested changes

2022-06-02 07:13 UTC, yuki-takei commented on packages/app/src/client/services/ShowPageAccessories.tsx
> +      if (pageIdParams.split('...').length > 1) {
split して length が 2 以上って条件、微妙なので、
厳密に `${ObjectId}...${ObjectId}` というパターンになることをチェックしよう。

2022-06-08 03:58 UTC, hirokei-camel commented
ページIDの文字数が24文字として指定しているのは、mongoDBのobjectIdの生成規則を確認してから記述しました！
ご了承ください！
https://toshitanian.hatenablog.com/entry/2014/02/14/015314

2022-06-08 04:03 UTC, yukendev commented on packages/app/src/client/services/ShowPageAccessories.tsx
> +      if (pageIdParams.search(/.{24}\.{3}.{24}/) !== -1) {
正規表現がパターンにマッチするかを知りたいときにsearchメソッドを使うのは適切ではない気がする。
あと。ページIDも「数字と小文字の24文字」に絞ったほうがいいかも

2022-06-08 06:11 UTC, merged