imprv: Convert withTranslation to useTranslation 10 jsx files 00
weseek/growi pull request #5946
Opened 2022-06-01 11:26 UTC by jam411

(imprv: convert withTranslation to useTranslation 10 jsx files #5921 
 imprv/96331ブランチのPRを作り直し. 旧ブランチは削除済み.)

https://redmine.weseek.co.jp/issues/96331

withTranslationからuseTranslationへの変更, 10ファイル.

[GrowiContextualSubNavigation.tsx](https://github.com/weseek/growi/compare/imprv/convert-withTranslation-to-useTranslation...imprv/96331-2?expand=1#diff-bff97a028b4693c3ea67c50abd3f05eb149e65fe7978c6867b092bb3712177fa)はimportライブラリの移動のみ

2022-06-02 07:24 UTC, yuki-takei requested changes

2022-06-02 07:24 UTC, yuki-takei commented on packages/app/src/components/CreateTemplateModal.jsx
> +  // t: PropTypes.func.isRequired, //  i18next // avoided type error
useTranslation にすることで t は外からは入れる形式ではなくなった。よってこの行は消してOK。

2022-06-02 07:24 UTC, yuki-takei commented on packages/app/src/components/CreateTemplateModal.jsx
> +  path: PropTypes.string,
こっちは勝手に変えちゃだめ。

2022-06-02 07:24 UTC, yuki-takei commented on packages/app/src/components/Drawio.jsx
> +export default DrawioWrapper;
master ブランチでは既に ts 化、FC 化が済んでいる。
imprv/convert-withTranslation-to-useTranslation と imprv/96331-2 の両方で master に追従する必要がある。

git 上でどういう状態にすべきか想像できなかったら分かる人に質問してください。

2022-06-02 07:24 UTC, yuki-takei commented on packages/app/src/components/PageAccessoriesModalControl.jsx
>    t: PropTypes.func.isRequired, //  i18next
この行不要になるよね

2022-06-06 00:59 UTC, jam411 commented on packages/app/src/components/CreateTemplateModal.jsx
> +  path: PropTypes.string,
context.tsxで定義されているuseCurrentPagePathフックの型がNullableのため以下のESlintエラーがでます。
`
Error: src/components/Navbar/GrowiContextualSubNavigation.tsx(290,13): error TS2322: Type 'Nullable<string> | undefined' is not assignable to type 'string'.
`
CreateTemlateModal.jsxでもnullとundefinedを許可するようにしました。

2022-06-06 02:25 UTC, yuki-takei requested changes

2022-06-06 02:25 UTC, yuki-takei commented on packages/app/src/components/CreateTemplateModal.jsx
> +  path: PropTypes.string,
CreateTemplateModal を利用している GrowiContextualSubNavigation 側で対処するようにしてください。

2022-06-06 05:02 UTC, jam411 commented on packages/app/src/components/CreateTemplateModal.jsx
> +  path: PropTypes.string,
GrowiContextualSubNavigation側へ、nullの場合の条件文を導入しました。

2022-06-06 05:04 UTC, jam411 commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +    }
CreateTemplateModal.jsxでの型エラーのため

2022-06-06 05:16 UTC, jam411 commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        {path != null && currentUser != null && (
GrowiContextualSubNavigation.tsx側で条件式を加えました。

2022-06-06 08:17 UTC, merged