feat: Fire resume rename operation from client side
weseek/growi pull request #5967
Opened 2022-06-03 05:44 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/93222

2022-06-03 07:30 UTC, hakumizuki requested changes

2022-06-03 07:30 UTC, hakumizuki commented on packages/app/src/client/services/page-operation.ts
> +  }
catch する意味ないですね

2022-06-03 07:30 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  const pathRecoveryMenuItemClickHandler = async(pageId: string): Promise<void> => {
この関数の実装がなぜそうなっているのかのコメントをつけて欲しいです。

具体的には、
- なぜ `setRenaming(true)` が一番初めに呼ばれるのか？
- なぜ `mutateChildren()` がこの行で呼ばれるのか？
- なぜ修復自体が成功したかわからなくても成功したと表示するのか？
- なぜ `toastError(err)` は i18n しないのか？
- なぜ `setTimeout` の第二引数は `1000` なのか？

2022-06-06 04:01 UTC, hakumizuki requested changes

2022-06-06 04:39 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      mutateChildren();
消し忘れていたので消しました

2022-06-06 04:42 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      toastError(t(err[0].message));
エラーメッセージを見てユーザーが対応できるものでもないので汎用的なメッセージを表示するように変更

2022-06-06 05:01 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  const pathRecoveryMenuItemClickHandler = async(pageId: string): Promise<void> => {
考え直して
- 「Renameが終了していない」という印象を与えてしまう
- ユーザーがRenameの進捗度を知る必要はない
という理由で表示しないことにしました

2022-06-06 05:14 UTC, Yohei-Shiina commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +    const shouldFixPath = operationProcessData?.Rename != null ? operationProcessData?.Rename.isProcessable : false;
既に処理中であれば スピナーを表示する必要はなくなったので
isProcessable が存在して true の時だけ「パスの修復」を選択できるように変更

2022-06-06 06:09 UTC, hakumizuki requested changes
`operationProcessData` を PageItemControl にどう渡してくるべきか後続でより良い方法を模索したいので TODO つけておいてください

2022-06-06 06:09 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +    catch (e) {
e は使わない場合は省略できます

2022-06-06 06:09 UTC, hakumizuki commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +    const shouldFixPath = operationProcessData?.Rename != null ? operationProcessData?.Rename.isProcessable : false;
shouldShowPathRecoveryButton に変更しましょう

2022-06-06 10:21 UTC, merged