show draw attention icon based on condition
weseek/growi pull request #5969
Opened 2022-06-03 06:52 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/93522

![showicon](https://user-images.githubusercontent.com/35527421/171802678-c03fe2b6-8729-4b6f-b804-09ae9ec2ebf3.gif)

2022-06-03 07:43 UTC, hakumizuki requested changes

2022-06-03 07:43 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  const existRenameProcessData = page.processData?.Rename != null;
boolean の変数名は is, has, can, should のどれかから始めてください

あとこれそもそも入りますかね？`isRenameProcessable` が含んでいるように見えますが

2022-06-03 07:43 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +      setRenaming(false);
この部分に関してはもう一個の PR の説明次第かなあと

2022-06-06 05:58 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> -    }
名前変更が処理中であることをユーザーが知る必要はないので削除した

2022-06-06 05:59 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> -      setRenaming(true);
同じ理由
https://github.com/weseek/growi/pull/5969/files#r889844848

2022-06-06 06:00 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +                <i className="fa fa-warning mr-2 text-warning"></i>
同じ理由で、スピナーは削除し、パスの修復が必要な時のみ 警告アイコンを表示
https://github.com/weseek/growi/pull/5969/files#r889844848

2022-06-07 06:12 UTC, hakumizuki approved these changes

2022-06-07 06:12 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  const shouldShowAttentionIcon = page.processData?.Rename != null ? page.processData.Rename.isProcessable : false;
これこうでもかけますね。お任せしますが

```typescript
const shouldShowAttentionIcon = !!page.processData?.Rename.isProcessable;
```

2022-06-07 06:31 UTC, merged