feat: Activity Event Emitter
weseek/growi pull request #5977
Opened 2022-06-03 13:34 UTC by miya

## Task
[#96622](https://redmine.weseek.co.jp/issues/96622) [GROWI] [AuditLog] activity ドキュメントを生成する Express Middleware を実装する
└ [#96900](https://redmine.weseek.co.jp/issues/96900) activity の更新、inAppNotification を作成する EventEmitter を実装する

2022-06-03 13:42 UTC, miya commented on packages/app/src/server/events/activity.ts
> +module.exports = ActivityEvent;
ActivityEvent を実装しました。
以下の activity の更新処理を Event Emitter を使った実装に置き換えました。
- ログイン
- ログイン失敗
- ログアウト
- ページリネーム

2022-06-03 13:57 UTC, yuki-takei requested changes

2022-06-03 13:57 UTC, yuki-takei commented on packages/app/src/server/service/activity.ts
> +      }
ActivityService は InAppNotificationService への参照を持ってはならない。

2022-06-03 14:27 UTC, miya commented on packages/app/src/server/service/activity.ts
> +      }
ActivityEvent.prototype.onUpdate へ処理を移しました。

2022-06-06 08:16 UTC, yuki-takei requested changes

2022-06-06 08:16 UTC, yuki-takei commented on packages/app/src/server/events/activity.ts
> +module.exports = ActivityEvent;
違うねえ…

ActivityEvent への on の設定を InAppNotificationService 内でやるならいいけど、このファイル内で InAppNotification が出てきてはだめ。

2022-06-06 09:02 UTC, miya commented on packages/app/src/server/events/activity.ts
> +module.exports = ActivityEvent;
InAppNotificationService で on の設定をするように修正しました...

2022-06-07 06:31 UTC, yuki-takei requested changes

2022-06-07 06:31 UTC, yuki-takei commented on packages/app/src/server/service/activity.ts
> +      // create inAppNotification
inAppNotification という文字列がある時点でもう責務的にだめ

2022-06-07 06:31 UTC, yuki-takei commented on packages/app/src/server/service/activity.ts
> +        this.activityEvent.emit('createInAppNotification', activity, target);
例えばここを 'updated' event にするとか

2022-06-07 06:42 UTC, miya commented on packages/app/src/server/service/activity.ts
> +      // create inAppNotification
inAppNotificationService の `on('updated` で受け取れるようにしました

2022-06-07 07:20 UTC, merged