imprv: omit ustated-> RevisionComparerContainer
weseek/growi pull request #5982
Opened 2022-06-06 08:00 UTC by Shunm634-source

95893 [Omit Unstated] [SWR化] RevisionComparerContainer
https://redmine.weseek.co.jp/issues/95893 

RevisionComparerContainer.jsをなくし、RevisionComparerをFC化させる。

2022-06-07 04:51 UTC, yukendev commented on packages/app/src/components/PageHistory.jsx
> +const PageHistory = () => {
FCに型を付けたい

2022-06-07 04:52 UTC, yukendev commented on packages/app/src/components/PageHistory.jsx
>  import React, { useState, useCallback, useEffect } from 'react';
useCallbackは使われてないなら消してもよさそう？

2022-06-07 04:56 UTC, yukendev commented on packages/app/src/components/PageHistory/PageRevisionTable.jsx
>    renderRow(revision, previousRevision, latestRevision, oldestRevision, hasDiff, isContiguousNodiff) {
isContiguousNodiffは使われてないなら消す

2022-06-07 04:58 UTC, yukendev commented on packages/app/src/components/PageHistory.jsx
> +const PageHistory = () => {
いや、jsxだったから大丈夫だわ。
別タスクでtsx化しても勉強になりそう。

2022-06-07 05:05 UTC, yukendev commented on packages/app/src/components/PageHistory/PageRevisionTable.jsx
>    renderRow(revision, previousRevision, latestRevision, oldestRevision, hasDiff, isContiguousNodiff) {
revision, previousRevision, latestRevision, oldestRevisionを引数に取ってるの、もっといい方法がありそう？

2022-06-07 05:07 UTC, yukendev commented on packages/app/src/components/PageHistory/PageRevisionTable.jsx
>  import PropTypes from 'prop-types';
別タスクでFC化＆TS化してもいいかも

2022-06-07 05:08 UTC, yukendev commented on packages/app/src/components/RevisionComparer/RevisionComparer.jsx
> +import React, { useState, useCallback, useEffect } from 'react';
useCallbackは使ってないなら消す

2022-06-07 05:20 UTC, yukendev commented on packages/app/src/components/RevisionComparer/RevisionComparer.jsx
この部分は廣原君のタスクだから消してよさそう

2022-06-07 07:18 UTC, yuki-takei requested changes

2022-06-07 07:18 UTC, yuki-takei commented on packages/app/src/components/RevisionComparer/RevisionComparer.jsx
> +  const { data: currentPagePath = '' } = useCurrentPagePath();
currentPagePath に初期値を入れず、null の場合はレンダリングの設定を変えるなりで対応してください。

2022-06-07 07:18 UTC, yuki-takei commented on packages/app/src/components/PageHistory/PageRevisionTable.jsx
> +  changeTargetRevision: PropTypes.func.isRequired,
イベントハンドリングに使う porps の名前をガイドライン通りに。
https://tips.weseek.co.jp/60ae84d41091010049bed55d

2022-06-07 12:11 UTC, yuki-takei commented
RevisionComparerContainer って不要になったなら消していいんじゃないかな。

2022-06-13 09:12 UTC, yuki-takei requested changes

2022-06-13 09:12 UTC, yuki-takei commented on packages/app/src/components/RevisionComparer/RevisionComparer.jsx
> +    if (pathName == null) return null;
- ここで null チェックするのは違うな
    - CopyToClipboard, DropdownItemContents に null 値を渡しても大丈夫だろうという、子供に異常値チェックを丸投げしている実装になっている
    - RevisionComparer 自体がその処理を考えないといけない
- 引数の型を明示してほしい

2022-06-14 09:56 UTC, yuki-takei requested changes

2022-06-14 09:56 UTC, yuki-takei commented on packages/app/src/components/RevisionComparer/RevisionComparer.jsx
> +    if (pathName == null) return null;
generateURL のFB対応を行ってください。

2022-06-15 03:27 UTC, merged