imprv: Limit display of notification paths
weseek/growi pull request #5991
Opened 2022-06-07 06:38 UTC by jam411

https://redmine.weseek.co.jp/issues/96905
https://redmine.weseek.co.jp/issues/96907

・修正で上記の二つのタスクが終了します。
・通知ドロップダウンと通知一覧にて、通知パスが長い場合の制限と省略文字を設けました。

2022-06-07 07:14 UTC, kaoritokashiki requested changes

2022-06-07 07:14 UTC, kaoritokashiki commented on packages/app/src/styles/molecules/copy-dropdown.scss
> +}
このfileに追加はおかしいような気がしています。
copy dropdown は関係ないですよね??

2022-06-07 08:55 UTC, jam411 commented on packages/app/src/styles/molecules/copy-dropdown.scss
> +}
_navbar.scssに作成し直しました。

2022-06-08 08:06 UTC, kaoritokashiki approved these changes

2022-06-08 08:08 UTC, merged