imprv: 97299 convert 12 files
weseek/growi pull request #6016
Opened 2022-06-09 06:21 UTC by yukendev

https://redmine.weseek.co.jp/issues/97299

以下のファイルを置き換え、複雑でないファイルはFC化、TS化もしました
CustomizeCssSetting.jsx
CustomizeFunctionOption.jsx
CustomizeFunctionSetting.jsx
CustomizeHeaderSetting.jsx
CustomizeHighlightSetting.jsx
CustomizeLayoutSetting.jsx
CustomizeScriptSetting.jsx
CustomizeThemeOptions.jsx
CustomizeThemeSetting.jsx
CustomizeLayoutSetting.jsx
PagingSizeUncontrolledDropdown.jsx 
ElasticsearchManagement.jsx

2022-06-09 12:59 UTC, yuki-takei requested changes

2022-06-09 12:59 UTC, yuki-takei commented on packages/app/src/components/Admin/Customize/CustomizeCssSetting.tsx
> +  const onClickSubmit = async() => {
useCallback 使って

2022-06-09 12:59 UTC, yuki-takei commented on packages/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
> +  const onClickSubmit = async() => {
useCallback 使って

2022-06-09 12:59 UTC, yuki-takei commented on packages/app/src/components/Admin/Customize/CustomizeHeaderSetting.tsx
> +  const onClickSubmit = async() => {
useCallback 使って

2022-06-09 12:59 UTC, yuki-takei commented on packages/app/src/components/Admin/Customize/CustomizeHighlightSetting.tsx
> +  const renderHljsDemo = () => {
同ファイルの別コンポーネントに

2022-06-10 04:54 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeCssSetting.tsx
> +  const onClickSubmit = async() => {
修正済み

2022-06-10 04:55 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
> +  const onClickSubmit = async() => {
修正済み

2022-06-10 04:56 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeHeaderSetting.tsx
> +  const onClickSubmit = async() => {
修正済み

2022-06-10 05:02 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeHighlightSetting.tsx
> +  const renderHljsDemo = () => {
修正済み

2022-06-10 05:10 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeHighlightSetting.tsx
> +  });
修正済み

2022-06-10 05:11 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeThemeOptions.jsx
> +  }];
修正済み

2022-06-10 06:37 UTC, yuki-takei requested changes

2022-06-10 06:37 UTC, yuki-takei commented on packages/app/src/components/Admin/Customize/CustomizeHighlightSetting.tsx
> +const renderHljsDemo = (adminCustomizeContainer: AdminCustomizeContainer): JSX.Element => {
- 引数は `isHighlightJsStyleBorderEnabled` に限るべきだね
- React.memo 使って

2022-06-10 07:03 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeHighlightSetting.tsx
> +const renderHljsDemo = (adminCustomizeContainer: AdminCustomizeContainer): JSX.Element => {
修正済み

2022-06-10 07:08 UTC, merged