feat: Create TTL index for Activity collection at server startup
weseek/growi pull request #6017
Opened 2022-06-09 06:39 UTC by miya

## Task
[#96136](https://redmine.weseek.co.jp/issues/96136) [GROWI] [AuditLog] Activity ドキュメントの保持期間を設定できる
└ [#97185](https://redmine.weseek.co.jp/issues/97185) [backend] TTL index の expires（秒数）を入れる環境変数を用意・参照し、activity ドキュメントに有効期限をつける

2022-06-09 10:13 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    const activityExpirationSeconds = configManager != null ? configManager.getConfig('crowi', 'app:activityExpirationSeconds') : 7776000;
configManager から `app:activityExpirationSeconds` の値を取得

2022-06-09 10:13 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    }
`createdAt_1` にすでに TTL index が付与されていた場合は drop index

2022-06-09 10:13 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    }
TTL index を作成

2022-06-09 10:13 UTC, miya commented on packages/app/src/server/service/config-loader.ts
> +  },
Activity ドキュメントの有効期限
デフォルトは 7776000（90日）

2022-06-09 10:13 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    this.createTtlIndex();
ActivityService 初期化時に TTL index を作成

2022-06-09 13:17 UTC, yuki-takei requested changes

2022-06-09 13:17 UTC, yuki-takei commented on packages/app/src/server/service/activity.ts
> +    }
「すでに TTL index が付与されていた場合は」じゃなく、createdAt_1 が存在していたら drop してない？

- 存在していなかったら createIndex するのは OK
- TTL index が設定されていたら skip してほしい(作り直しじゃなく)
- TTL index が設定されていなかったら、dropIndex / createIndex するのはOK

2022-06-09 13:17 UTC, yuki-takei commented on packages/app/src/server/service/activity.ts
> +  };
TTL インデックスの設定がうまくいかなかったら、サーバーは正常起動せずに落ちるようにしてほしい。
もしくは正常起動するけど AuditLog は無効化されるように。

後続ストーリーでも可。

2022-06-09 17:56 UTC, miya commented on packages/app/src/server/service/activity.ts
> +      const shoudDropAndCreateIndex = ttlIndex != null && ttlIndex.expireAfterSeconds !== activityExpirationSeconds;
TTL index が存在 && tlIndex.expireAfterSeconds が環境変数と異なっただった場合 true

2022-06-09 17:59 UTC, miya commented on packages/app/src/server/service/activity.ts
> +  };
エラーが出たら停止するようにしました。
AuditLog の有効化の有無は後続ストーリーにて着手します。

2022-06-09 17:59 UTC, miya commented on packages/app/src/server/service/config-loader.ts
> +    default: 2592000,
デフォルトは1ヶ月

2022-06-09 18:09 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    }
- 存在していなかったら createIndex
- 存在しているが expireAfterSeconds が環境変数の値と異なっていたら dropIndex して createIndex
という感じに修正しました。

2022-06-10 06:29 UTC, yuki-takei requested changes

2022-06-10 06:29 UTC, yuki-takei commented on packages/app/src/server/service/activity.ts
> +      const ttlIndex = indexes.find(i => i.name === 'createdAt_1');
変数名直して

- isCreatedAtExists: boolean を作る
- shoudCreateIndex: boolean も作る
    - shouldDrop || !isCreatedAtExists

2022-06-10 06:29 UTC, yuki-takei commented on packages/app/src/server/service/activity.ts
> +        await collection.dropIndex('createdAt_1');
const に入れて
'createdAt_1'

2022-06-10 08:09 UTC, merged