move page test to service
weseek/growi pull request #6026
Opened 2022-06-10 04:34 UTC by yukendev

- ForceCreateBySystemのテストを追加
- PageService.createのテストをモデル層からサービス層に移動
- isGrantNormalizedが走るかどうかのテストを追加

2022-06-10 05:32 UTC, yukendev commented on packages/app/test/integration/service/v5.non-public-page.test.ts
> +
既存のテスト移動＋isGrantNormalizedを追加

2022-06-10 05:33 UTC, yukendev commented on packages/app/test/integration/service/v5.public-page.test.ts
> +  describe('create', () => {
既存のテスト移動＋isGrantNormalizedを追加

2022-06-10 05:33 UTC, yukendev commented on packages/app/test/integration/service/v5.public-page.test.ts
> +  describe('create by system', () => {
既存のcreateのテストを丸パクリ＋isGrantNormalized追加

2022-06-13 07:31 UTC, hakumizuki commented on packages/app/test/integration/service/v5.non-public-page.test.ts
> +        // isGrantNormalized is called when GRANT RESTRICTED
is not

2022-06-13 07:33 UTC, hakumizuki requested changes
コメントしたとこだけ

2022-06-13 07:36 UTC, hakumizuki approved these changes

2022-06-13 07:42 UTC, merged