feat: Testcode for rename operation interruption
weseek/growi pull request #6032
Opened 2022-06-10 07:44 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/97508

2022-06-10 08:04 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.public-page.test.ts
> +    test('should add 1 descendantCount to parent page in MainOperation', async() => {
MainOperation で新しい親ページの子孫数が +1 されること

2022-06-10 08:04 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.public-page.test.ts
> +    test('should subtract 1 descendantCount from parent page in SubOperation', async() => {
SubOperation で新しい親ページの子孫数が -1 されること

※これより上のテストで MainOperation で +1 されることは証明されている

2022-06-10 08:04 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.public-page.test.ts
> +      expect(page0.descendantCount).toBe(2); // originally 0, +1 in Main, -1 in Sub, +2 for descendants.
Mainで+1 される
Sub で -1 される（Mainで+1された分のマイナス）
Sub で 子孫数分 + される

2022-06-10 08:04 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.public-page.test.ts
> +      expect(page0.descendantCount).toBe(1); // originally 0, +1 in Main.
Mainで+1 される

2022-06-13 09:37 UTC, hakumizuki requested changes

2022-06-13 09:37 UTC, hakumizuki commented on packages/app/test/integration/service/v5.public-page.test.ts
> +      const _path0 = '/v5_pageForRename24';
_ ありなしで何が違うのかのコメントつけておくといいと思います

2022-06-13 09:37 UTC, hakumizuki commented on packages/app/test/integration/service/v5.public-page.test.ts
> +      expect(page0.descendantCount).toBe(1); // originally 0, +1 in Main.
コメントに関して、main operation だったり Main だったり統一されてないのはあんま良くないので表現統一しましょう

2022-06-13 09:37 UTC, hakumizuki commented on packages/app/test/integration/service/v5.public-page.test.ts
> +    const renameWithOnlyMainOperation = async(page, newPagePath, user, options) => {
これ用意せずに renameMainOperation のみのテストにしたほうが良いのでは？必要最低限の unit test に近い形で

2022-06-13 09:37 UTC, hakumizuki commented on packages/app/test/integration/service/v5.public-page.test.ts
> +    test('should subtract 1 descendantCount from parent page in SubOperation', async() => {
SubOperation だけをテストするコードを追加しないと SubOperation によって -1 されたとは言えないですね。(言えるかもしれないが、このテストだけでは言えない)

このテストは renamePage の統合テストとして残していいと思います。

2022-06-13 12:19 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.public-page.test.ts
> +      expect(page0.descendantCount).toBe(2); // originally 0, +1 in Main, -1 in Sub, +2 for descendants.
ここの expect の箇所だけは、このままの方がメリット多いので妥協してほしいです。

- 全て統一して 始めから `main` だけだと、文脈ないのでなんのことかよくわからない
- `renameMainOperation` と素直に全部書くと、`reameSubOperation` と並んだ時コメント長すぎて読みにくい

- 途中から main にしている場合、
  - コードを読んでいる人は文脈的に何を指しているかほぼほぼ理解できるはず。
  - 短いので読みやすい

2022-06-13 12:58 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.public-page.test.ts
> +    test('should subtract 1 descendantCount from a new parent page in renameSubOperation', async() => {
新しく追加したテスト

新しい親から子孫数が -1 されること

2022-06-13 12:59 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.public-page.test.ts
> +  let pageOpId1;
PageOperationドキュメントに必要なので定義

2022-06-13 13:00 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.public-page.test.ts
> +      },
renameSubOperation で子孫数が -1 されるテスト用のデータ

2022-06-13 13:01 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.public-page.test.ts
> +      expect(page0.descendantCount).toBe(1); // originally 0, +1 in Main.
https://github.com/weseek/growi/pull/6032/files#r895651626

2022-06-14 07:18 UTC, Yohei-Shiina commented on packages/app/test/integration/service/v5.public-page.test.ts
> +    const renameWithOnlyMainOperation = async(page, newPagePath, user, options) => {
renameMainOperation のみの関数に変更してます

2022-06-14 07:25 UTC, merged