feat: The users get notified when the descendant pages are renamed
weseek/growi pull request #6044
Opened 2022-06-13 09:17 UTC by Shunm634-source

子孫ページのみをサブスクライブしているユーザーに対して、親ページがリネームされたときに通知を飛ばすようにする。
以下ストーリー参照
https://redmine.weseek.co.jp/issues/84441

2022-06-14 12:56 UTC, yukendev commented on packages/app/src/server/models/subscription.ts
> +};
このメソッドの中で、サブスクライブしてるユーザーを取得して、かつアクションしたユーザーを取り除くのは複数の処理をやらせすぎな気がする。ここでは単にtargetsに結びついているユーザーを取得するだけにして、呼び出し側で、フィルターをかける処理をした方がすっきりすると思う。

2022-06-14 12:58 UTC, yukendev commented on packages/app/src/server/routes/apiv3/pages.js
消し忘れ？

2022-06-14 13:11 UTC, yukendev commented on packages/app/src/server/service/page.ts
>      const Page = mongoose.model('Page') as unknown as PageModel;
返り値の型を消す必要なかったのでは？

2022-06-14 13:13 UTC, yukendev commented on packages/app/src/server/service/page.ts
ここでpagesを返す意味はある？

2022-06-14 13:34 UTC, yukendev commented on packages/app/src/server/service/page.ts
>      }
コメント消し忘れ？

2022-06-15 02:50 UTC, yukendev commented on packages/app/src/server/service/page.ts
>      // revert
なし

2022-06-16 06:40 UTC, Shunm634-source commented on packages/app/src/server/models/subscription.ts
> +    .filter(item => (item.toString() !== actionUser.toString()));
子孫ページをサブスクライブしているユーザをとってくる実装とそれらからアクションユーザーを排除する実装をそれぞれ分離しました。

2022-06-16 06:41 UTC, Shunm634-source commented on packages/app/src/server/models/subscription.ts
> +};
アクションユーザを取り除く部分をcreateAndSendNotifications()に移動させました。

2022-06-16 06:41 UTC, Shunm634-source commented on packages/app/src/server/service/page.ts
削除済み

2022-06-16 06:41 UTC, Shunm634-source commented on packages/app/src/server/service/page.ts
> +    this.pageEvent.on('rename', async(page, descendantPages, user) => {
修正済み

2022-06-16 06:42 UTC, Shunm634-source commented on packages/app/src/server/service/page.ts
>      }
削除済み

2022-06-17 07:40 UTC, hakumizuki requested changes

2022-06-17 07:40 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +  private async createAndSendNotifications(page, descendantPages, user, action) {
引数に型をつけよう。page とかは `PageDocument` が使える。まだ型が用意されてない場合は any で妥協して OK。

利用想定として descendantPages には null が入る場合があるよね。引数の位置、デフォルト値などがこれでいいか考えてみよう

2022-06-20 02:31 UTC, Shunm634-source commented on packages/app/src/server/models/subscription.ts
> +subscriptionSchema.statics.getSubscriptions = async function(targets) {
削除済み

2022-06-20 02:32 UTC, Shunm634-source commented on packages/app/src/server/models/activity.ts
> +    Subscription.getUnsubscription((target as Types.ObjectId)),
削除済み

2022-06-20 02:36 UTC, Shunm634-source commented on packages/app/src/server/service/page.ts
> +  private async createAndSendNotifications(page, descendantPages, user, action) {
（anyで妥協しているのはuserとaction)残り２つは指定済み。

2022-06-20 06:19 UTC, hakumizuki commented on packages/app/src/server/models/subscription.ts
> +subscriptionSchema.statics.getSubscription = async function(target: Types.ObjectId | undefined) {
これ undefined じゃなくて Document じゃないかな？

2022-06-20 06:19 UTC, hakumizuki commented on packages/app/src/server/models/subscription.ts
> +subscriptionSchema.statics.getUnsubscription = async function(target: Types.ObjectId | undefined) {
ここも

2022-06-20 06:19 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +  private async createAndSendNotifications(page, descendantPages, user, action) {
引数の位置変えるべきじゃないかなあ

結構なパターンで `descendantPages` は null になっているので、最後の引数にしてデフォルト値を null にするとかするといいと思うよ。それか、`options: { descendantPages?: PageDocument[] }` とかにするのもありかも

2022-06-21 07:28 UTC, hakumizuki requested changes

2022-06-21 07:28 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +  private async createAndSendNotifications(page: PageDocument, user: any, action: any, descendantPages: PageDocument[] | null = null) {
オプショナル引数にして `| null` を消すと綺麗になりそうです

2022-06-21 08:05 UTC, merged

2022-06-22 05:53 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    if (descendantPages !== undefined && descendantPages.length > 0) {
ここガイドライン違反してるね

`!= null` で統一してくれ