support: Omit Tag Container
weseek/growi pull request #6049
Opened 2022-06-14 01:48 UTC by kaoritokashiki

2022-06-15 04:55 UTC, kaoritokashiki commented on packages/app/src/client/services/EditorContainer.js
> +      tags: [],
これはわざとnull にしているのでしょうか? そうであれば元に戻します。

2022-06-15 07:30 UTC, kaoritokashiki commented on packages/app/src/client/services/TagContainer.js
> -    }
## TODO
ここの部分の反映はこのPRではしていません。
[83341](https://redmine.weseek.co.jp/issues/83341) 過去の PR のコードからサルベージできるものがあるかを確認し、不要になったら delete branch する

2022-06-16 08:20 UTC, yuki-takei commented
## Q 1
これはデグレ扱い(本来そうあってほしい仕様とは違う)

### そのエラーが起こる原因の予想
飽くまでも予想なので確かめて欲しいけど、

View からタグを編集した場合、DB データ的には revision が進む。
しかしクライアントの PageContainer で持ってる revision がその最新のものに更新されていないため、古い revisionId を添えてページ更新をしようとしてしまい、結果 `Posted param "revisionId" is outdated.` が出る。

2022-06-16 08:22 UTC, yuki-takei commented
## Q2
> 2. タグを追加できないようにする

これは、 `/trash` は特別にタグを追加できないようにする、で合ってる？
この認識が合ってるならこの方針でよい。

2022-06-16 10:00 UTC, kaoritokashiki commented
## Q 1
期待する挙動になっていないこと。了解です。原因追求 & 修正します

## Q2
> これは、 /trash だけは特別にタグを追加できないようにする、で合ってる？
そうです。そのように進めます。
これはもともとあったバグなのと、このPRが既に差分多めなので別タスクで対応しようかと思います。

2022-06-16 10:34 UTC, yuki-takei requested changes

2022-06-16 10:34 UTC, yuki-takei commented on packages/app/src/stores/editor.tsx
> +};
型は string[] の方がいいかも。
meet でヒアリングした結果、この hook の作り方および使い方がちょっとおかしいのでリファクタしてください。

- 名前とキーを変えて、「PageEditor と PageEditorByHackMD のための一時編集中の tags 置き場」としてこの hook (as a global state) を定義してください
    - 仮に `usePageTagsForEditors` とします

ただ、この global state の値の更新は少し工夫しないといけない。

シーケンスとしては初回ページロード → usePageTagsForEditors にそのコピーを保持 の流れになるが、今のように hook の引数を fallbackData に入れるやり方はいろいろ不都合がある(もう体験してくれてると思うので割愛)。

解決策としては、useEditorSettings.update を参考に usePageTagsForEditors にカスタムメソッドを一つ追加する。

```
sync(): void => {
  mutate(useSWRxTagsInfo(pageId) の値);
}
```

これを、

- 初回ページロード直後
- apiPost で保存が成功した直後

に呼ぶようにする。

2022-06-16 10:34 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  }, [isViewMode, mutateTagsOnEditMode, pageId, revisionId, mutateSWRTagsInfo]);
tagsUpdatedHandler ちょっと読みにくかったので、view 用と editor 用と handler を 2つ作って、isViewMode に応じてどちらを GrowiSubNavigation に渡すか変えてください。

2022-06-17 04:20 UTC, kaoritokashiki commented on packages/app/src/interfaces/tag.ts
> +}
`interfaces/pageTagsInfo.ts`　のfileを削除し、`interface/tag.ts`に移動させました。

2022-06-17 06:39 UTC, kaoritokashiki commented
Q1, Q2, どちらも既存のバグですので別タスクにて修正します。

## Q1
- [98146](https://redmine.weseek.co.jp/issues/98146) [fix][bug]Viewモードでタグを追加しリロードせずにEditモードに遷移、タグの編集 & ページの更新 をすると Posted param "revisionId" is outdated.のエラーが表示されてしまう

## Q2
- [98145](https://redmine.weseek.co.jp/issues/98145) /trash ページ直下では、tagLabelsを表示させないようにする

2022-06-17 06:48 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiSubNavigation.tsx
> +          { showTagLabel && !isCompactMode && currentPath !== '/trash' && (
`/trash`ページ直下の場合、`TagLabels`コンポーネントを表示しないようにしました。

2022-06-17 06:53 UTC, kaoritokashiki commented on packages/app/src/stores/editor.tsx
> +};
usePageTagsForEditors に sync メソッドを追加しました。

2022-06-17 10:29 UTC, yuki-takei requested changes

2022-06-17 10:29 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const { data: tagsForEditors, sync: syncPageTagsForEditors } = usePageTagsForEditors();
usePageTagsForEditors は引数に pageId を取るようにし、内部で `useSWRxTagsInfo(pageId)` を呼ぶ。
そうすると sync には引数がいらなくなるはず。

2022-06-17 10:29 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiSubNavigation.tsx
> +  const { data: currentPath } = useCurrentPagePath();
このコンポーネントは GrowiContextualSubNavigation とは違うので、props.page を使って判断しないといけない。

2022-06-17 10:29 UTC, yuki-takei commented on packages/app/src/components/Page.jsx
> +  const { data: pageTags, sync: syncPageTagsForEditors } = usePageTagsForEditors();
syncPageTagsForEditors 使ってないね

2022-06-17 10:29 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> +import { useSWRxTagsInfo } from '~/stores/page';
useSWRxTagsInfo も使ってないね

不要な import ないかどうか全ファイルチェックして。

2022-06-18 14:23 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const { data: tagsForEditors, sync: syncPageTagsForEditors } = usePageTagsForEditors();
sync の使い道は2つ

1.  Editorの初回レンダリング時に、useSWRxTagsInfoのtagsInfoData.tagsを反映させる
2. Editor画面でtagを編集した際に、global変数である`tags`を反映させる

1は上記のやり方で `sync` の引数には何も渡さなくて良いが、
2に関しては、newTagsを引数に渡す必要があります。

2022-06-18 15:00 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiSubNavigation.tsx
> +          { showTagLabel && !isCompactMode && path !== '/trash' && (
props から渡ってくる page.path を参照し、/trashかどうかを判別するようにしました。

2022-06-18 15:02 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiSubNavigation.tsx
> +  tagsUpdatedHandler?: (newTags: string[]) => Promise<void> | void,
`tagsUpdatedHandlerForViewMode` は、`/tags.update` をするので、`Promise<void>`、
`tagsUpdatedHandlerForEditMode` は、apiを叩かないので、`void` を返します。

2022-06-18 15:04 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  }, [tagsInfoData?.tags]);
tagsInfoDataの値が更新された時に、`syncPageTagsForEditors()` を実行します。

2022-06-18 15:13 UTC, kaoritokashiki commented on packages/app/src/stores/editor.tsx
> +      mutate(newTagsOnEdit || tagsInfoData?.tags || [], false);
- syncの引数に何も指定されていない場合は、DBの値(tagsInfoData?.tags)が反映される
- edit画面で編集したタグが渡された場合はそれを反映させる
ようにしています。

2022-06-18 15:23 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor.tsx
> +import { useSWRxTagsInfo } from '~/stores/page';
すみません、不要なものは削除いたしました。

2022-06-18 15:24 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiSubNavigation.tsx
> +  const { data: currentPath } = useCurrentPagePath();
ありがとうございます。props.page.pathを参照するようにしました。

2022-06-19 14:11 UTC, yuki-takei requested changes

2022-06-19 14:11 UTC, yuki-takei commented on packages/app/src/stores/editor.tsx
> +      mutate(newTagsOnEdit || tagsInfoData?.tags || [], false);
「edit画面で編集したタグが渡された場合はそれを反映させる」用途では単に利用側から直接 mutate を呼べばいい。

2022-06-19 14:11 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const { data: tagsForEditors, sync: syncPageTagsForEditors } = usePageTagsForEditors();
2つめの用途では単に mutate を呼べばいい。

2022-06-19 16:59 UTC, kaoritokashiki commented
理解いたしました。

2022-06-19 17:33 UTC, kaoritokashiki commented
## VRTについて
Guest modeでのcompact navibarが消えたように見えるが、実際に確認したところ、スクロール時にも正常に表示されていたのでマージします。
<img width="1787" alt="Screen Shot 2022-06-20 at 2 31 49" src="https://user-images.githubusercontent.com/59536731/174493351-7a2519b7-4228-4830-999a-744c610de684.png">

2022-06-19 17:37 UTC, kaoritokashiki commented on packages/app/src/stores/editor.tsx
> +      mutate(newTagsOnEdit || tagsInfoData?.tags || [], false);
確かに分けた方がいいですね。
ありがとうございます。修正しました。

2022-06-19 17:38 UTC, merged