feat: Create markdown it plugin
weseek/growi pull request #6054
Opened 2022-06-14 10:58 UTC by jam411

・attachment用のプラグイン(attachment-plugin.jsx)を作成しました.
・syntax は, fence(~~~で囲まれる) を使用しました.
・fence のinfo要素が"attachment"なら, 専用のルールが付加されるようにしました.
・urlやユーザ情報, アップロード日時などのrenderに渡したい情報がMarkdown側のfence内に記載されていきます.
・その他コードはまだ荒いです.

![image](https://user-images.githubusercontent.com/68407388/173560935-c29c8152-21bc-4b50-ab9a-8b53d4ca366e.png)

2022-06-14 11:13 UTC, yuki-takei requested changes

2022-06-14 11:13 UTC, yuki-takei commented on packages/app/src/client/util/markdown-it/attachment-plugin.jsx
> +import * as ReactDOMServer from 'react-dom/server';
これってありなのか…？(クライアントサイドだしなしだと思う)

2022-06-14 11:13 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> +        insertText = `~~~attachment\nfilename:${fileName}\nurl:${attachment.filePathProxied}\n~~~`;
fileName にあたるものは、attachment document 内に入ってると思う。
PageAttachmentPresentation が自律的にデータ取得しないといけないのでは。

2022-06-27 04:16 UTC, jam411 commented on packages/app/src/client/util/markdown-it/attachment-plugin.jsx
> +import * as ReactDOMServer from 'react-dom/server';
修正済み

2022-06-27 05:21 UTC, jam411 commented on packages/app/src/components/PageEditor.tsx
> +        insertText = `~~~attachment\nfilename:${fileName}\nurl:${attachment.filePathProxied}\n~~~`;
await apiGet()のような非同期処理 （またはReactライフサイクルの再描画処理）が期待通りできませんでした.

markdown-itのparse解析の段階で, GrowiRenderer.js を経由して, attachment-plugin.ts で カスタムルールが規定された時にデータを自律的に取得したかったのですが, 

- apiGetを同期的に処理する（あり得るのか）.
- 非同期処理が結果が帰ったタイミングでのmarkdown-itの再描画処理の実装.

ができませんでした．

参考として, 自律的にデータ取得することを目指した実装の PageRichAttachmentPresentation.tsx (旧:PageAttachmentPresentation)  を用意しました.

結論としては, この提出のように, 自律的に実装せず PageEditor の段階で情報をmarkdown側にファイル名などの情報記載してしまって, それを読み込むような処理で対応していくなら実装を進められそうです.

2022-06-27 08:01 UTC, jam411 commented
棚上げのためクローズ
https://redmine.weseek.co.jp/issues/97242

2022-06-27 08:01 UTC, closed without merging