feat: 96846 implement backend
weseek/growi pull request #6055
Opened 2022-06-14 11:35 UTC by yukendev

https://redmine.weseek.co.jp/issues/96846

- カスタマイズ画面でゲストや新規ユーザー（サイドバーの設定をしていないユーザー）がGROWIを開いたときに表示されるサイドバーのモードを設定可能にした。
- カスタマイズ画面でDock Modeの時にデフォルトでサイドバーが開いた状態か、閉じた状態かを設定できるようにした。

2022-06-14 13:56 UTC, yuki-takei requested changes

2022-06-14 13:56 UTC, yuki-takei commented on packages/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
> +  }, [retrieveIsSidebarDrawerMode, retrieveIsSidebarClosedAtDockMode]);
SWR 化してください。

2022-06-14 13:56 UTC, yuki-takei commented on packages/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
> +  }, [t, isSidebarClosedAtDockMode]);
これらも SWR hook に閉じ込めると綺麗。useEditorSettings が提供する update メソッドを参考に。

2022-06-14 13:56 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/customize-setting.js
> +  );
これら冗長なので、GET /sidebar と PUT /sidebar で一緒に処理できるようにしてください。

2022-06-15 03:03 UTC, yukendev commented on packages/app/src/server/routes/apiv3/customize-setting.js
> +  );
修正済み

2022-06-15 03:03 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
> +  }, [t, isSidebarClosedAtDockMode]);
修正済み

2022-06-15 03:03 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
> +  }, [retrieveIsSidebarDrawerMode, retrieveIsSidebarClosedAtDockMode]);
修正済み

2022-06-16 10:48 UTC, yuki-takei requested changes

2022-06-16 10:48 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +    update: async(updateData) => {
この引数なしで更新できない？305 行目の mutate も不要だと思う。

2022-06-16 10:48 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +export const useSidebarConfig = (): SWRResponse<ISidebarConfig, Error> & SidebarConfigOption => {
サーバーから値取ってくる custom hook なので、`useSWRxSidebarConfig` にしよう。

2022-06-16 11:14 UTC, yukendev commented on packages/app/src/stores/ui.tsx
> +export const useSidebarConfig = (): SWRResponse<ISidebarConfig, Error> & SidebarConfigOption => {
修正済み

2022-06-16 11:16 UTC, yukendev commented on packages/app/src/stores/ui.tsx
> +    update: async(updateData) => {
修正済み

2022-06-16 11:29 UTC, merged