Support: SWRize apiGet /tag.search
weseek/growi pull request #6062
Opened 2022-06-16 06:22 UTC by kaoritokashiki

2022-06-16 07:21 UTC, hakumizuki requested changes

2022-06-16 07:21 UTC, hakumizuki commented on packages/app/src/components/Page/TagsInput.tsx
> +    setSearchQuery(query);
try-catch いらないですね

loading は今あんま機能してなさそうなのでやるとしたら SWR レスポンスに依存した実装にしてください

2022-06-16 09:49 UTC, kaoritokashiki commented on packages/app/src/components/Page/TagsInput.tsx
> +  const isLoading = error == null && tagsSearch === undefined;
`isLoading` をSWR レスポンスに依存した実装に改修しました。

2022-06-16 09:49 UTC, kaoritokashiki commented on packages/app/src/components/Page/TagsInput.tsx
> +    setSearchQuery(query);
undefinedの時はempty array がセットされるようにしました。

2022-06-16 10:01 UTC, merged

2022-06-29 09:48 UTC, kaoritokashiki commented on packages/app/src/components/Page/TagsInput.tsx
> +    tagsSearchData.unshift(searchQuery);
☠️ unshift の引数に query ではなく`searchQuery` が入ってしまっている。