feat: Do not create an Activity if it is an action that does not belong to the Action Group
weseek/growi pull request #6063
Opened 2022-06-16 09:08 UTC by miya

## Task
[#93968](https://redmine.weseek.co.jp/issues/93968) [GROWI] [AuditLog] 収集する Activity を action グループごとに選択できる
└ [#97979](https://redmine.weseek.co.jp/issues/97979) /interfaces/activity に 3種類のグループを作成する
└ [#97981](https://redmine.weseek.co.jp/issues/97981) action グループを選択する環境変数を作成、 activity を更新する際に参照できる

2022-06-18 17:39 UTC, miya commented on packages/app/src/server/service/config-loader.ts
> +  },
SMALL, MEDIUM, LARGE を選択できるようにしました

2022-06-18 17:39 UTC, miya commented on packages/app/src/interfaces/activity.ts
> +} as const;
ログイン・ログアウト・ページ作成・ページ削除

2022-06-18 17:39 UTC, miya commented on packages/app/src/interfaces/activity.ts
> +} as const;
SmallActionGroup + 一般ユーザーによる操作全部 - ページ閲覧

2022-06-18 17:39 UTC, miya commented on packages/app/src/interfaces/activity.ts
> +} as const;
MediumActionGroup + 管理ユーザーによる操作全部 + ページ閲覧

2022-06-18 17:39 UTC, miya commented on packages/app/src/server/service/activity.ts
> +  }
action を update するかどうかの確認
引数に入る action が設定されている action group に含まれているもの || 通知に必要な action かどうかで判断しています

2022-06-18 17:39 UTC, miya commented on packages/app/src/server/models/activity.ts
> +// Check if you should update using ActivityService.shoudUpdateActivity
initActivityEventListeners を介さないで利用する場合は、ActivityService.shoudUpdateActivity を使って更新しても良いか確認してね、というコメントをつけた。ActivityModel が crowi を持っていないので（ActivityService が使えない）のでコメントに留めました。

2022-06-21 03:29 UTC, yuki-takei requested changes

2022-06-21 03:29 UTC, yuki-takei commented on packages/app/src/interfaces/activity.ts
> +export const AllLargeAction = Object.values(LargeActionGroup);
AllSomething は、最後複数計で s を付けたい

AllSmallAction -> AllSmallGroupActions

2022-06-21 07:54 UTC, miya commented on packages/app/src/server/service/activity.ts
> +  }
個別に アクションを 追加 / 削除 機能の実装は別ストーリーでやろうと思っています。
https://redmine.weseek.co.jp/issues/97982
https://redmine.weseek.co.jp/issues/97986

2022-06-21 08:12 UTC, miya commented on packages/app/src/server/models/activity.ts
> +// Check if you should update using ActivityService.shoudUpdateActivity
修正しました

2022-06-21 08:37 UTC, miya commented on packages/app/src/interfaces/activity.ts
> +export const AllLargeAction = Object.values(LargeActionGroup);
修正しました。

2022-06-21 08:43 UTC, miya commented on packages/app/src/interfaces/activity.ts
> +} as const;
PAGE_VIEW を抜いて、現時点までに作成した管理者ユーザーの action を追加しました

2022-06-22 06:07 UTC, yuki-takei requested changes

2022-06-22 06:07 UTC, yuki-takei commented on packages/app/src/server/service/activity.ts
> +    const auditLogActionGroupSize = configManager != null ? configManager.getConfig('crowi', 'app:auditLogActionGroupSize') : ActionGroupSize.Small;
configManager が null のケースなんてあるのか？

2022-06-22 06:07 UTC, yuki-takei commented on packages/app/src/server/service/activity.ts
> +  }
- 後続ストーリーでというのはわかったけど、こういうケースではアウトラインだけわかるような(インターフェースを意識した)コーディングをしといてほしかった
- as ReadonlyArray ってここで書かないといけないもの？(export 側では書けない？)

2022-06-22 08:50 UTC, miya commented on packages/app/src/server/service/activity.ts
> +  }
- as ReadonlyArray は不要になったので消しました

2022-06-22 08:52 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    const auditLogActionGroupSize = configManager != null ? configManager.getConfig('crowi', 'app:auditLogActionGroupSize') : ActionGroupSize.Small;
`setupConfigManager` が ActivityServiceより先に呼ばれるので null にはならなそうでしたので修正しました。

<img width="327" alt="ScreenShot 2022-06-22 15 59 48" src="https://user-images.githubusercontent.com/34241526/174986872-112888aa-7ee1-4482-8e83-872533c827aa.png">

2022-06-22 09:08 UTC, merged