imprv: 97999 refactor comment editor fc and ts
weseek/growi pull request #6071
Opened 2022-06-17 08:35 UTC by yukendev

https://redmine.weseek.co.jp/issues/97999

- CommentEditorをFC/TS化

2022-06-17 10:56 UTC, yuki-takei requested changes

2022-06-17 10:56 UTC, yuki-takei commented on packages/app/src/interfaces/global.ts
> +import InterceptorManager from '~/services/interceptor-manager';
これは実装を含んでいるので import してはいけない。
型安全にしたいなら、interface IInterceptorManager を作る。

2022-06-17 10:56 UTC, yuki-takei commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  commentBody: string,
commentBody は optional なはず。
他の props も全て required なのかどうかもう一度精査して。

2022-06-17 10:56 UTC, yuki-takei commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +import InterceptorManager from '~/services/interceptor-manager';
InterceptorManager の実態はインポートすべきではない。

2022-06-17 10:56 UTC, yuki-takei commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +    editorRef.current.setGfmMode(value);
isMarkdown を false にできる機能は廃止しましょう

2022-06-17 10:56 UTC, yuki-takei commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  };
このメソッド冗長かな

2022-06-17 10:56 UTC, yuki-takei commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  }, [mutateIsSlackEnabled]);
このメソッド冗長かな

2022-06-17 10:56 UTC, yuki-takei commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  };
useCallback 使ってください。
他のイベントハンドラも使ってなさそうなものあるので再チェックを。

2022-06-17 10:56 UTC, yuki-takei commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  };
useMemo を使うか、もしくは CommentEditor の外に出す

2022-06-20 04:23 UTC, yukendev commented on packages/app/src/interfaces/global.ts
> +import InterceptorManager from '~/services/interceptor-manager';
修正済み

2022-06-20 04:25 UTC, yukendev commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +import InterceptorManager from '~/services/interceptor-manager';
修正済み

2022-06-20 06:22 UTC, yukendev commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  commentBody: string,
修正済み

2022-06-20 06:44 UTC, yukendev commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +    editorRef.current.setGfmMode(value);
https://redmine.weseek.co.jp/issues/98296
少し変更が大きそうだったので後続タスクを作ってこちらで着手します。

2022-06-20 06:44 UTC, yukendev commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  };
修正済み

2022-06-20 06:48 UTC, yukendev commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  }, [mutateIsSlackEnabled]);
mutateIsSlackEnabledを直接渡しても第二引数にfalseを入れるのが複雑になるかなと思ったのでこのままにします。

2022-06-20 07:00 UTC, yukendev commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  };
修正済み

2022-06-20 07:04 UTC, yukendev commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  };
修正済み

2022-06-20 09:07 UTC, yuki-takei requested changes

2022-06-20 09:07 UTC, yuki-takei commented on packages/app/src/interfaces/global.ts
> +export type CustomWindow = Window & typeof globalThis & { xss: Xss } & { interceptorManager: IInterceptorManager };
globalEmitter と GraphViewer を追加してほしい。

2022-06-20 09:07 UTC, yuki-takei commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  }, [mutateIsSlackEnabled]);
`isSlackEnabled => mutateIsSlackEnabled(isSlackEnabled, false)`
って書けばいいと思う

2022-06-20 11:25 UTC, yukendev commented on packages/app/src/interfaces/global.ts
> +export type CustomWindow = Window & typeof globalThis & { xss: Xss } & { interceptorManager: IInterceptorManager };
修正済み

2022-06-21 00:04 UTC, yuki-takei requested changes

2022-06-21 00:04 UTC, yuki-takei commented on packages/app/src/components/Drawio.tsx
> +  const GraphViewer: IGraphViewer = (window as CustomWindow).GraphViewer;
ここで定義するなら useMemo 使った方がいいかも。
別の選択肢としては、editButtonClickHandler か renderDrawio の中で取得するようにする。

2022-06-21 04:44 UTC, merged