Fix: show page history comparation modal
weseek/growi pull request #6072
Opened 2022-06-17 11:19 UTC by hirokei-camel

タスク：https://redmine.weseek.co.jp/issues/97260
統合ブランチをmasterへmergeをお願いします！

2022-06-17 12:27 UTC, yuki-takei requested changes

2022-06-17 12:27 UTC, yuki-takei commented on packages/app/src/client/services/ShowPageAccessories.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
この eslint-disable-next-line 消せない？

2022-06-17 12:27 UTC, yuki-takei commented on packages/app/src/client/services/ShowPageAccessories.tsx
> +      if (/([a-z0-9]){24}...([a-z0-9]){24}/.test(pageIdParams)) {
`/([a-z0-9]){24}...([a-z0-9]){24}/` は、コンポーネント外で予め定義しておいて。 new RegExp を使って。

2022-06-17 12:27 UTC, yuki-takei commented on packages/app/src/client/services/ShowPageAccessories.tsx
> +        openPageAccessories(PageAccessoriesModalContents.PageHistory);
open はするだろうけど、リビジョンの指定はどこでやっているの？

2022-06-17 12:31 UTC, yuki-takei requested changes

2022-06-20 07:06 UTC, hirokei-camel commented on packages/app/src/client/services/ShowPageAccessories.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
コメントがないと「React Hook useEffect has a missing dependency:」という警告文が表示されてしまうため、コメントアウトは消せません。
警告通りに第２引数にopenPageAccessoriesを入れるとuseEffectの無限ループが起こってしまいます。

2022-06-20 23:53 UTC, yuki-takei commented on packages/app/src/client/services/ShowPageAccessories.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
react-hooks/exhaustive-deps を disable にするのはやはりおかしい。解決策を探して。

2022-06-21 00:01 UTC, yuki-takei requested changes

2022-06-21 00:01 UTC, yuki-takei commented on packages/app/src/client/services/ShowPageAccessoriesModal.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
この eslint-disable-next-line は消す。(warning が出ないように正しい deps をセットする)

根本解決を模索して。なぜ無限ループになるのか、どうしたら抑制できるのかを理解しなければならない。

2022-06-22 09:03 UTC, yuki-takei requested changes

2022-06-22 09:03 UTC, yuki-takei commented on packages/app/src/client/services/ShowPageAccessoriesModal.tsx
> +  }, [openPageAccessories, status, isOpenDone]);
惜しいなあ。
`pageIdParams` が null だったとしても(つまり compare パラメータがなかったとしても)、このコンポーネントは「モーダルを開く必要はない」という判断をして役目を終えるわけだよね。`setIsOpenDone` には useEffect が走りきったあとで true を入れるべきだね。(そしてその場合相応しい名前に変えてほしいね)

2022-06-24 08:59 UTC, hirokei-camel commented on packages/app/src/client/app.jsx
> +  }
椎名さんに確認を取りました。
コンフリクトが起きた箇所では、何かしら書かれているページとそうでないページを分岐しているコードで、今回私が取り組んでいたタスクには影響がありませんでした！
動作も問題ないです。
よろしくお願いします

2022-06-26 05:22 UTC, merged