imprv/add shouldEmit argument and excute socket.emit only in addAllPages
weseek/growi pull request #6077
Opened 2022-06-20 11:02 UTC by hirokei-camel

タスク：https://redmine.weseek.co.jp/issues/97708
レビューお願いします！

2022-06-23 02:41 UTC, hakumizuki commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +  async updateOrInsertPages(queryFactory, option: any = {}, shouldEmit = false) {
shouldEmit って既にある isEmittingProgressEvent と同じ意味じゃないかな？っていうのを初めに俺が気づいてあげられればよかったんだけど、、

 あと option 引数の型をつけよう

2022-06-28 10:05 UTC, hakumizuki requested changes

2022-06-28 10:05 UTC, hakumizuki commented on packages/app/src/server/interfaces/search.ts
> +  shouldEmitAvailable?: boolean
あと、サーバー再度のコードの interface, type の置き場所なんだけど
以下のルールでいけそう

1. コントローラーで使用されるならば、`/server/interfaces` 以下にそのコントローラーを表すような意味のファイル名でファイルを用意して型を記述
2. サービス層で使用されるならば、`/server/service/interfaces` 以下にそのサービスを表すような意味のファイル名でファイルを用意して型を記述
3. モデル層のみで使用されるならば、以下略

2022-06-29 02:21 UTC, hirokei-camel commented on packages/app/src/server/interfaces/search.ts
> +  shouldEmitAvailable?: boolean
shouldEmitProgressの名前更新（shouldEmitAvailable → shoulEmitProgress）は完了しました！

2022-07-01 08:01 UTC, hakumizuki requested changes

2022-07-05 09:31 UTC, merged