feat: getAvailableActions implementation considering adding and excluding actions
weseek/growi pull request #6109
Opened 2022-06-22 10:21 UTC by miya

## Tasks

[#97982](https://redmine.weseek.co.jp/issues/97982) [GROWI] [AuditLog] 環境変数 AUDIT_LOG_ACTIONS_GROUP で指定されたグループに所属していない action を個別に追加できる
└ [#97983](https://redmine.weseek.co.jp/issues/97983) 実装

[#97986](https://redmine.weseek.co.jp/issues/97986) [GROWI] [AuditLog] 環境変数 AUDIT_LOG_ACTIONS_GROUP で指定されたグループに所属している action を個別に取り除くことができる
└ [#97987](https://redmine.weseek.co.jp/issues/97987) 実装

2022-06-22 16:47 UTC, miya commented on packages/app/src/server/service/activity.ts
> +};
環境変数に入力されたカンマ区切りの action を配列に直すためのメソッド

2022-06-22 16:47 UTC, miya commented on packages/app/src/server/service/activity.ts
> +  const actions = actionsString.split(',').map(value => value.trim());
array にする

2022-06-22 16:47 UTC, miya commented on packages/app/src/server/service/activity.ts
> +
環境変数に入力されたカンマ区切りの文字列を配列に直すメソッド

2022-06-22 16:47 UTC, miya commented on packages/app/src/server/service/activity.ts
> +  const actions = actionsString.split(',').map(value => value.trim());
array にする

2022-06-22 16:47 UTC, miya commented on packages/app/src/server/service/activity.ts
> +  return actions.filter(action => (AllSupportedAction as string[]).includes(action)) as SupportedActionType[];
`AllSupportedAction` に含まれない action を排除して `SupportedActionType[]` にアサーション

AllSupportedAction はより良い名前に変更する（後続）

2022-06-22 16:47 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    availableActions.push(...additionalActions);
additionalActions を追加

2022-06-22 16:47 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    const filteredAvailableActions = availableActions.filter(action => !excludeActions.includes(action));
excludeActions を排除

2022-06-22 16:47 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    filteredAvailableActions.push(...AllSupportedActionToNotified);
必須アクションを追加

AllSupportedActionToNotified はより良い名前に変更する（後続）

2022-06-22 16:47 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    return Array.from(new Set(filteredAvailableActions));
重複排除して return

2022-06-23 11:48 UTC, yuki-takei requested changes

2022-06-23 11:48 UTC, yuki-takei commented on packages/app/src/server/service/activity.ts
> +    return Array.from(new Set(filteredAvailableActions));
最初から全て Set で操作して最後に Array に直したほうが楽だろうね。つまり parseActionString の返り値が Set の方がよさそう。

2022-06-24 03:19 UTC, miya commented on packages/app/src/server/service/activity.ts
> +    return Array.from(new Set(filteredAvailableActions));
最初から array ではなく set で持つようにしました。
以降は 追加 / 削除 をする場合は配列を forEach して add / delete するようにしました。

2022-06-24 04:03 UTC, merged