imprv: SWRize apiGet /personal-setting
weseek/growi pull request #6116
Opened 2022-06-23 15:53 UTC by kaoritokashiki

## Task
[Omit Unstated] [SWR化] PersonalContainer
┗[98159](https://redmine.weseek.co.jp/issues/98159) apiv3Get /personal-setting/ をSWR化

## Description
### 対象ファイル
- BasicInfoSettings
    - 初回リロード時のdataの反映
    - iinputなどの値の変更の反映
    - (SlackMemberId: )
- PasswordSettings
- ApiSettings
　 - FC / TS化
    -  `AppContainer`,` PersonalContainer` への依存がなくなりました。
    - submit時に新しいtokenの反映しました
    
    
 ## Note
 以下は後続タスクで対応します。
 - BasicInfoSettings
     - 「更新」の処理:  https://redmine.weseek.co.jp/issues/98160
     - [[bug] [BasicInfoSettings] Slack Member ID 、１文字入力するとfocusが外れてしまう](https://redmine.weseek.co.jp/issues/98717) 👉🏻 既存のバグです
 
    
    
 ### ScreenRecording
- BasicInfoSettings

https://user-images.githubusercontent.com/59536731/175361545-acd9fcde-6790-43a8-9bd4-fc2183b1c467.mov

- PasswordSettings

https://user-images.githubusercontent.com/59536731/175361590-292cd325-09cd-418a-8621-06dc8ad59c81.mov

- ApiSettings の FC / TS化

https://user-images.githubusercontent.com/59536731/175361558-a7504735-a8b7-46fc-881d-288676e027c2.mov

2022-06-23 17:13 UTC, kaoritokashiki commented on packages/app/src/components/Me/BasicInfoSettings.jsx
>        await personalContainer.updateBasicInfo();
本PRでは、`updateBasicInfo` が正常に動きません。
後続で対応します。

2022-06-23 17:15 UTC, kaoritokashiki commented on packages/app/src/interfaces/user.ts
> +  apiToken?: string;
`IUser` に `apiToken` の `property `が存在しなかったので追加したのですがよろしかったでしょうか?

2022-06-23 17:17 UTC, kaoritokashiki commented on packages/app/src/components/Me/BasicInfoSettings.jsx
> +  }, [usePersonalSettingsInfoResult.personalSettingsDataFromDB]);
DBに保存されている値を `usePersonalSettingsInfo`から取得できるようにしています。

2022-06-23 17:24 UTC, kaoritokashiki commented on packages/app/src/components/Me/BasicInfoSettings.jsx
> +    const { registrationWhiteList } = appContainer.getConfig();
### registrationWhiteList について
`personalContainer` のstate からは削除し、appContainerからそのまま取得するようにしました

2022-06-23 17:25 UTC, kaoritokashiki commented on packages/app/src/client/services/PersonalContainer.js
> -      registrationWhiteList: this.appContainer.getConfig().registrationWhiteList,
BasicInfoSettings.jsxで、appContainerから取得するようにしたので、こちらからは削除しました。

2022-06-24 05:16 UTC, hakumizuki requested changes

2022-06-24 05:16 UTC, hakumizuki commented on packages/app/src/interfaces/user.ts
> +  apiToken?: string;
いいと思います

2022-06-24 05:16 UTC, hakumizuki commented on packages/app/src/stores/personal-settings.tsx
> +  const swrResult = useStaticSWR<IUser, Error>('personalSettingsInfo', undefined);
swig 経由で値渡したりしてないので、`useStaticSWR` を使う必要なさそうです。シンプルに `useSWRxPersonalSettingsInfo` だけ使って実装したらいいのではないでしょうか

`sync` 関数もただただ `useSWRxPersonalSettingsInfo` の mutate を引数なしで呼ぶだけでいいと思います

2022-06-24 05:16 UTC, hakumizuki commented on packages/app/src/components/Me/PasswordSettings.jsx
> +  return <PasswordSettings t={t} onSubmit={mutatePersonalSetting} syncPersonalSettingsInfo={syncPersonalSettingsInfo} {...props} />;
mutate をそのまま渡すのは怖いですね。event が第一引数に入ってしまいます

2022-06-26 04:59 UTC, kaoritokashiki commented on packages/app/src/components/Me/BasicInfoSettings.jsx
> -
TS/FC 化しました。

2022-06-26 05:23 UTC, kaoritokashiki commented on packages/app/src/stores/personal-settings.tsx
> +  const swrResult = useStaticSWR<IUser, Error>('personalSettingsInfo', undefined);
`useSWRxPersonalSettingsInfo` のみでの実装に変更しました。

2022-06-26 09:49 UTC, yuki-takei requested changes

2022-06-26 09:49 UTC, yuki-takei commented on packages/app/src/components/Me/ApiSettings.tsx
> +      mutatePersonalSettings(result.data.userData);
意図があるなら mutate してもいいだろうけど、revalidate (引数なしの mutate)が適切かと。

2022-06-26 09:49 UTC, yuki-takei commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +  }, [personalSettingsInfo]);
この useEffect 内の処理意味が分からない

2022-06-26 09:49 UTC, yuki-takei commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +  }, [personalSettingsInfo]);
sync の名残だということは理解。ただ SWR 1つで運用するなら不要なので消す。

- 別解1. BasicInfoSettings にユーザーの指定値ストア用 state を用意するならここでコピーする
- 別解2. 上記は元々の実装の useStaticSWR にしてもよい(共通化の必要がないのでしなくてもよい)

2022-06-26 09:49 UTC, yuki-takei commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +      await personalContainer.updateBasicInfo();
ここで revalidate する必要がある

2022-06-26 11:22 UTC, kaoritokashiki commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +      mutate();
mutate 追加いたしました。

2022-06-26 11:23 UTC, kaoritokashiki commented on packages/app/src/stores/personal-settings.tsx
> +  const swrResult = useStaticSWR<IUser, Error>('personalSettingsInfo', undefined);
`usePersonalSettings` こちらのコードは元に戻しました。
https://github.com/weseek/growi/pull/6116#discussion_r906786538

2022-06-26 11:24 UTC, kaoritokashiki commented on packages/app/src/components/Me/ApiSettings.tsx
> +      mutateDatabaseData();
apiPutした後に、`useSWRxPersonalSettings` のmutateを実行しています。

2022-06-26 11:25 UTC, kaoritokashiki commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +      await personalContainer.updateBasicInfo();
対応しました。

2022-06-26 15:34 UTC, yuki-takei requested changes

2022-06-26 15:34 UTC, yuki-takei commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +      mutate();
以下のシナリオでうまく revalidate されるかを試してほしい

1. Robo 3T 等で、email など BasicInfoSettings で取り扱う値を書き換えておく
2. BasicInfoSettings の submitHandler を呼ぶ

「1.」で書き換えた値が UI に反映されていればOK、
反映されていなければ sync にまだ課題がある。

2022-06-27 05:17 UTC, kaoritokashiki commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +  }, [personalSettingsInfo]);
別解2 にしました。

2022-06-27 05:21 UTC, kaoritokashiki commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +      mutate();
`useSWRxPersonalSettings` のuseSWR option に `revalidateOnFocus: false` をセットして上記を試したところ、「submitHandler」が実行されたタイミングでは、反映されないですね。
`usePersonalSettings` ではなく`useSWRxPersonalSettings` のmutate() を実行する必要がありそうなので修正します。

2022-06-27 05:41 UTC, kaoritokashiki commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +      mutateDatabaseData();
apiPutした後に、useSWRxPersonalSettings(apiGet) のmutateを実行しています。

2022-06-27 07:46 UTC, yuki-takei requested changes

2022-06-27 07:46 UTC, yuki-takei commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +      mutateDatabaseData();
useEffect に任せてるけど明示的に sync すべき。
もしかすると useEffect で sync 呼んでるのいらないかも…

2022-06-27 09:37 UTC, kaoritokashiki commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +  }, [personalSettingsDataFromDB]);
sync に置き換えました。

> もしかすると useEffect で sync 呼んでるのいらないかも…
useEffect をなくすと、初回リロード時にdataが反映されず、inputの中身が空のままになってしまうので、そのままにしています。

2022-06-27 11:24 UTC, yuki-takei requested changes

2022-06-27 11:24 UTC, yuki-takei commented on packages/app/src/stores/personal-settings.tsx
> +    personalSettingsDataFromDB,
personalSettingsDataFromDB はリターンしない

2022-06-27 11:24 UTC, yuki-takei commented on packages/app/src/stores/personal-settings.tsx
> +  const swrResult = useStaticSWR<IUser, Error>('personalSettingsInfo', undefined);
初期状態の挙動を改善する

- personalSettingsDataFromDB が null ならキーを null にセット
- `fallbackData` に personalSettingsDataFromDB  をセット

2022-06-27 11:24 UTC, yuki-takei commented on packages/app/src/stores/personal-settings.tsx
> +    update: () => {
async method にする

2022-06-27 11:24 UTC, yuki-takei commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +      mutateDatabaseData();
await update() してから sync() を呼ぶ

2022-06-27 11:24 UTC, yuki-takei commented on packages/app/src/components/Me/BasicInfoSettings.tsx
> +  }, [personalSettingsDataFromDB]);
この useEffect やはりあまりよくない。eslint-disable-next-line react-hooks/exhaustive-deps も書きたくないし。
usePersonalSettings 側の改善をやって、消せないかどうか試して。

2022-06-27 13:04 UTC, kaoritokashiki commented
`useEffect` useStaticSWR のキーにnull を追加したことで、いらなくなりました。

2022-06-27 14:22 UTC, kaoritokashiki commented on packages/app/src/stores/personal-settings.tsx
> +  };
sync のロジックを更新

2022-06-27 14:28 UTC, merged