reflect tmp tag data
weseek/growi pull request #6124
Opened 2022-06-24 08:45 UTC by kaoritokashiki

2022-07-04 08:59 UTC, yuki-takei requested changes

2022-07-04 08:59 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +  const key = pageId == null ? 'tmpPage' : `/pages.getPageTag?pageId=${pageId}`;
Next.js 化を見越して `[endpoint, pageId, shareLinkId, pagePath]` にしましょう。
以下を区別しないといけない。

- ページが存在する
    - pageId ごとに結果が違う
    - share link かどうかで結果が違う
- ページが存在しない
    - pagePath ごとに結果が違う

2022-07-04 08:59 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +  const { data: templateTagData } = useTemplateTagData();
これも SWR 化したいな。

2022-07-06 09:32 UTC, kaoritokashiki commented on packages/app/src/stores/page.tsx
> +  const { data: templateTagData } = useTemplateTagData();
すみません、理解できていないのですが
`useSWRxTemplateTags` のような形式にしたいということでしょうか ?

2022-07-06 09:34 UTC, kaoritokashiki commented on packages/app/src/stores/page.tsx
> +  const key = [endpoint, pageId, shareLinkId, pagePath];
key を`[endpoint, pageId, shareLinkId, pagePath]` に変更しました。
また、pagePath は pageId と同様に引数から取得するようにしています。

2022-07-06 19:12 UTC, yuki-takei requested changes

2022-07-06 19:12 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +  const { data: templateTagData } = useTemplateTagData();
わかりにくくてごめん。

## 現状
`data-template-tags` 経由で context に入れるようになってる。

コード的には `routes/page.js` の _notFound のこの部分

```
      // retrieve templates
      if (req.user != null) {
        const template = await Page.findTemplate(path);
        if (template.templateBody) {
          const body = replacePlaceholdersOfTemplate(template.templateBody, req);
          const tags = template.templateTags;
          renderVars.template = body;
          renderVars.templateTags = tags;
        }
      }
```

## Next.js 版理想
Not Found 時のみ、getServerSideProps で取得して SSR するように変えたい。

## master 版の落とし所
なので、master 版の落とし所としては少なくともこの SWR が面倒を見ないほうがいいんじゃないかなと。

2022-07-07 07:37 UTC, kaoritokashiki commented on packages/app/src/stores/page.tsx
> +  const { data: templateTagData } = useTemplateTagData();
こちらでよろしいか確認お願いします
console.log のコードは削除済みです
https://github.com/weseek/growi/pull/6124/commits/ce6296e515b116d8fd8f307acbe4ec57e2b321fc

2022-07-07 07:40 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +      tags={tagsForEditors || []}
editモードでタグを編集した後に Viewモードに切り替えたときにeditモードのtag がそのまま表示されるようにするために、`isViewMode` で切り替えるのはやめました。

2022-07-07 08:21 UTC, yuki-takei requested changes

2022-07-07 08:21 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +      tags={tagsForEditors || []}
うーん…どこかに穴がありそう。

例えば、View から直接タグを編集・保存した時とか、あるいは Editor でタグを編集して未保存で View に戻ったときとかってこれで大丈夫なの？

2022-07-07 08:22 UTC, yuki-takei requested changes

2022-07-07 08:22 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    if (pageId != null && shareLinkId == null) {
これまだ直ってない

2022-07-07 10:33 UTC, kaoritokashiki commented
##  Editor でタグを編集して未保存で View に戻ったとき
https://user-images.githubusercontent.com/59536731/177753636-780f8f9e-6348-47cb-8cb8-483debae53c5.mov

## ページ遷移した時(View Mode)
https://user-images.githubusercontent.com/59536731/177753643-0180cdcf-0f95-47b0-bd61-74d2b67b303c.mov

2022-07-07 10:54 UTC, kaoritokashiki commented on packages/app/src/stores/page.tsx
> +    }
shareLink の場合、 tag がつけられていたとしても、表示されない仕様になっています。

<img width="1142" alt="Screen Shot 2022-07-07 at 19 53 17" src="https://user-images.githubusercontent.com/59536731/177757320-d9a76330-f675-42f5-9026-a65aa78d9603.png">

2022-07-07 23:31 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +      tags={tagsForEditors || []}
すみません、仕様を勘違いしていました。戻しました。

2022-07-08 12:49 UTC, merged