Imprv/confirm adding and removing beforeunload event lister timing
weseek/growi pull request #6154
Opened 2022-06-28 04:54 UTC by kaoritokashiki

2022-06-28 05:03 UTC, kaoritokashiki commented on packages/app/src/components/BasicLayout.tsx
> +      <a href="https://www.google.com/">https://www.google.com/</a>
テスト用にリンクを追加しただけです。マージはできません

2022-06-28 05:55 UTC, kaoritokashiki commented on packages/app/src/client/util/editor.ts
> +};
`showAlertDialog` util 化しました。

2022-06-28 11:52 UTC, yuki-takei requested changes

2022-06-28 11:52 UTC, yuki-takei commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +export default UnsavedAlertDialog;
`ReferenceError: localStorage is not defined` については、sync-to-storage を universal にするのがベストな解。

2022-06-30 04:22 UTC, kaoritokashiki commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +export default UnsavedAlertDialog;
ふむふむ、理解しました。説明ありがとうございます。

2022-06-30 10:44 UTC, kaoritokashiki commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +      window.alert(alertMsg);
window.alert を使う場所がここだけだったので、stores/editor で宣言していたshowAlertDialog は削除しました。

2022-06-30 10:45 UTC, kaoritokashiki commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +  }, [isEnabledUnsavedWarning]);
window.alertを使わずとも  e.returnValue がセットされればアラートが表示されるという事実を知らずに苦戦していました。

2022-07-05 06:04 UTC, kaoritokashiki commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +  }, []);
第二引数は空にしています。

2022-07-05 06:04 UTC, kaoritokashiki commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +  }, []);
第二引数は空にしています。

2022-07-05 06:24 UTC, yuki-takei requested changes

2022-07-05 06:24 UTC, yuki-takei commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +  }, []);
eslint-disable-next-line react-hooks/exhaustive-deps はやめる

2022-07-05 06:27 UTC, yuki-takei requested changes

2022-07-05 06:27 UTC, yuki-takei commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +      window.alert('Changes you made may not be saved.');
l10n しましょう

2022-07-05 09:24 UTC, kaoritokashiki commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +      window.alert(t('page_edit.changes_not_saved'));
i18n 対応しました。

2022-07-05 09:39 UTC, kaoritokashiki commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +  }, []);
修正いたしました。

2022-07-05 09:40 UTC, kaoritokashiki commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +      window.alert('Changes you made may not be saved.');
i18n対応しました。

2022-07-05 11:37 UTC, yuki-takei requested changes

2022-07-05 11:37 UTC, yuki-takei commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +import { useTranslation } from 'react-i18next';
next-i18next から import してください

2022-07-05 11:46 UTC, kaoritokashiki commented on packages/app/src/pages/UnsavedAlertDialog.tsx
> +import { useTranslation } from 'react-i18next';
修正しました。

2022-07-05 11:50 UTC, merged