feat: Implement OldRevisionAlert
weseek/growi pull request #6172
Opened 2022-06-29 13:43 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/98982

2022-06-29 18:09 UTC, yuki-takei requested changes

2022-06-29 18:09 UTC, yuki-takei commented on packages/app/src/components/PageAlert/OldRevisionAlert.tsx
> +      <a href="{ encodeURI(page.path) }"><i className="icon-fw icon-arrow-right-circle"></i>{ t('Show latest') }</a>
- encodeURI に渡している page.path はどこから手に入れたのだ？
- currentPageId へのリンクにすべき
- next/link にすべき

2022-06-29 18:09 UTC, yuki-takei commented on packages/app/src/interfaces/page.ts
> +  isLatestRevision?: boolean,
PageInfo に入れる必要はないのでは？

2022-06-29 18:09 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  if(revisionId == null || isSpecifiedRevisionExist ) {
条件おかしい。

2022-06-30 03:43 UTC, Yohei-Shiina commented on packages/app/src/interfaces/page.ts
> +  isLatestRevision?: boolean,
消し忘れてました

2022-06-30 03:44 UTC, Yohei-Shiina commented on packages/app/src/pages/[[...path]].page.tsx
> +  if(revisionId == null || isSpecifiedRevisionExist ) {
すいません、テスト的に消した `!` を戻し忘れてました

2022-06-30 04:20 UTC, Yohei-Shiina commented on packages/app/src/components/PageAlert/OldRevisionAlert.tsx
> +  if (page == null || isLatestRevision == null || isLatestRevision) {
page が漏れてたので追加しました

2022-06-30 04:21 UTC, Yohei-Shiina commented on packages/app/src/components/PageAlert/OldRevisionAlert.tsx
> +      <Link href={encodeURI(page._id)}>
ページの pathlinkではなく permalink になるように変更

2022-07-01 04:17 UTC, Yohei-Shiina commented on packages/app/src/components/PageAlert/OldRevisionAlert.tsx
> +      <Link href={`/${page._id}`}>
permalink になるように変更

2022-07-01 06:48 UTC, merged