support: Login pages rendering with next.js
weseek/growi pull request #6186
Opened 2022-07-01 07:40 UTC by Shunm634-source

Installerページ同様、Loginページをnext化に伴いレンダリングできるようにする。
なお、LoginForm.jsxファイルに渡されるべきプロップスについては、数が多く、分からない部分が多いため、一旦レンダリングに必要なプロップスのみ渡しています。
追加で必要なプロップスについては、FB後に引き続き本タスク内か新しくタスクを切って取り組む模様。
また、デザインに関しても、動作確認した際に不完全であること（タイトルがない等）は認知済みだが、ここに関してもレンダリングするというタスクから外れている気がするので（単純にこのタスクに時間をかけすぎているというのもあるが）差し当たりFBに委ねている。

以下タスクリンク参照
https://redmine.weseek.co.jp/issues/99046

2022-07-25 08:54 UTC, yuki-takei requested changes

2022-07-25 08:54 UTC, yuki-takei commented on packages/app/src/components/UnstatedUtils.tsx
> +    </Provider>
このファイルは書き換えてはいけない。

2022-07-25 08:54 UTC, yuki-takei commented on packages/app/src/pages/login.page.tsx
> +}
細かいんだけどこれら inject 系 function はサーバーサイドだと思うので、記述箇所をこのファイルの下の方に移動させて。

2022-07-25 08:54 UTC, yuki-takei commented on packages/app/src/pages/login.page.tsx
> +  useCsrfToken(props.csrfToken);
このあたりのいくつかは _app.page.tsx でやっているので不要

2022-07-25 08:54 UTC, yuki-takei commented on packages/app/src/pages/login.page.tsx
> +  useCurrentPagePath(props.currentPathname);
useCurrentPathname の間違いでは？

2022-07-28 08:34 UTC, Shunm634-source commented on packages/app/src/components/UnstatedUtils.tsx
> +    </Provider>
修正済み。

2022-07-28 08:34 UTC, Shunm634-source commented on packages/app/src/pages/login.page.tsx
> +}
修正済み

2022-07-28 08:34 UTC, Shunm634-source commented on packages/app/src/pages/login.page.tsx
> +  useCsrfToken(props.csrfToken);
削除済み。

2022-07-28 08:35 UTC, Shunm634-source commented on packages/app/src/pages/login.page.tsx
> +  useCurrentPagePath(props.currentPathname);
修正済み。

2022-07-29 06:53 UTC, yuki-takei requested changes

2022-07-29 06:53 UTC, yuki-takei commented on packages/app/src/components/UnstatedUtils.tsx
> +import { Provider, Subscribe } from 'unstated';
Provider も消して

2022-07-29 07:25 UTC, merged