feat: Feat/descendant notifications
weseek/growi pull request #6192
Opened 2022-07-04 10:01 UTC by Shunm634-source

以下ストーリー参照：
https://redmine.weseek.co.jp/issues/84441

2022-07-06 18:50 UTC, yuki-takei requested changes

2022-07-06 18:50 UTC, yuki-takei commented on packages/app/src/server/models/subscription.ts
> +  target: Types.ObjectId | Document
この指定ちょっと変かなあ。

この interface も `src/interfaces` あたりに持っていって、他の type に寄せて定義してくれる？
そうすると mongoose 由来の型を含まないようになり、ObjectId も単に string になるはず。

2022-07-11 10:51 UTC, Shunm634-source commented
revertのとこだけfindListWithDescendantsを呼んでもなぜか子孫ページが取れません。。（おそらくトラッシュページ配下にあるページは別の方法で取る必要がある？）
差し当たりこの問題が解決するまでconsole.log等は残してあるので、明日、また対面で相談いたします。
ここ以外は一応動作確認済みです。

2022-07-12 06:19 UTC, Shunm634-source commented on packages/app/src/server/routes/page.js
> +      descendantPages = pages.pages;
revertの処理が終わった後に呼んだことで解決済み。

2022-07-12 06:45 UTC, Shunm634-source commented on packages/app/src/server/models/subscription.ts
> +  target: Types.ObjectId | Document
ISubscription Interfaceをsrc/interfacesに持っていき、targetとuserをそれぞれRef<IPage>、Ref<IUser>に変更しました。

2022-07-12 10:34 UTC, miya commented on packages/app/src/server/service/in-app-notification.ts
> +      let notificationTargetUsers = await activity?.getNotificationTargetUsers();
ここは let にしたくないなぁ...
descendantsUsers を let で空の配列を定義して、それを this.upsertByActivity に入れた方がキレイそう

2022-07-12 10:36 UTC, miya commented on packages/app/src/server/service/page.ts
> +import PageEvent from '../events/page';
結局、service/page.ts の差分って必要になったんでしたっけ？

2022-07-12 10:48 UTC, miya commented on packages/app/src/server/routes/page.js
> +      const bPages = await Page.findListWithDescendants(page.path, req.user);
この変数は使われないみたい

2022-07-12 10:52 UTC, miya commented on packages/app/src/server/models/activity.ts
> +  target: Ref<IPage>
口頭で `Ref<IPage>` でいいかなぁって言っちゃった気がする？けど IPage に限定したくない感はある... もう一回口頭で話そう

2022-07-13 06:23 UTC, Shunm634-source commented on packages/app/src/server/service/page.ts
> +import PageEvent from '../events/page';
削除済み。

2022-07-13 06:23 UTC, Shunm634-source commented on packages/app/src/server/routes/page.js
> +      const bPages = await Page.findListWithDescendants(page.path, req.user);
削除済み。

2022-07-13 17:01 UTC, yuki-takei requested changes

2022-07-13 17:01 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/pages.js
> +      descendantPages.pop();
この処理コストが高すぎる。何件取ってくることになるんだ。

2022-07-13 17:01 UTC, yuki-takei commented on packages/app/src/server/routes/page.js
> +      descendantPages.pop();
ここもコストが高すぎる。

2022-07-13 17:01 UTC, yuki-takei commented on packages/app/src/server/routes/page.js
> +      descendantPages.pop();
コストが高すぎる。

2022-07-15 07:57 UTC, Shunm634-source commented on packages/app/src/server/routes/apiv3/pages.js
> +      descendantPages.pop();
/service/page.tsにてactivityEventを生成することによってコストを抑える。

2022-07-15 07:58 UTC, Shunm634-source commented on packages/app/src/server/routes/page.js
> +      descendantPages.pop();
同上

2022-07-15 07:58 UTC, Shunm634-source commented on packages/app/src/server/routes/page.js
> +      descendantPages.pop();
同上。

2022-08-01 07:05 UTC, miya commented on packages/app/src/server/models/activity.ts
> +    ref: 'Page',
Page に限定したくない（口頭で話した）

2022-08-01 07:05 UTC, miya commented on packages/app/src/server/routes/apiv3/pages.js
> +    const nOptions = {
変数名が分かりにくいので良い感じの名前をつける

2022-08-01 07:05 UTC, miya commented on packages/app/src/server/routes/apiv3/pages.js
> +    };
- activity document の生成処理は service/page.ts で行いたいので、add-activity middleware を外す
- nOptions は activity document の中身のデータなので、activityId は含めない（add-activity middleware がなくなるので、不要になると思うけど）

2022-08-01 07:07 UTC, Shunm634-source commented on packages/app/src/server/models/activity.ts
> +    ref: 'Page',
修正済み。

2022-08-01 07:08 UTC, Shunm634-source commented on packages/app/src/server/routes/apiv3/pages.js
> +    const nOptions = {
activityParametersに変更済み。

2022-08-01 08:19 UTC, Shunm634-source commented on packages/app/src/server/routes/apiv3/pages.js
> +    };
add-activity削除済み。
activityIdも削除済み。

2022-08-01 09:04 UTC, Shunm634-source commented on packages/app/src/server/models/activity.ts
> +  target: Ref<IPage>
activityのターゲットをTypes.ObjectIdに戻し（元の仕様）、subscriptionメソッドとの整合性は無理やり as unknown asで合わせました。

2022-08-30 09:14 UTC, merged