feat: implement sidebar nav skeleton
weseek/growi pull request #6193
Opened 2022-07-04 10:14 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/99370

2022-07-04 10:39 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar.tsx
> +  const SidebarNav = dynamic(() => import('./Sidebar/SidebarNav').then(mod => mod.SidebarNav), { ssr: false });
SidebarNav を CSR

2022-07-04 10:39 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar.tsx
> +import { SidebarNavSkeleton } from './Sidebar/SidebarNav';
スケルトンを SSR

2022-07-04 11:02 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar.tsx
> +  return SidebarNavElem();
ブラウザコンソールの以下エラー対処のため、 useEffect で表示コンポーネントを切り替えている
>Warning: Did not expect server HTML to contain a <div> in <div>.

ReactDom.hydrate 時に、SSRとCSRの結果が違うことで出ているエラーらしい

以下記事等を参考
https://nishinatoshiharu.com/next-hydration-warning-resolution/
┗  `レンダリング結果が異なる場合に警告されるメッセージの例`

https://en.reactjs.org/docs/react-dom.html#hydrate

2022-07-04 11:24 UTC, yuki-takei requested changes

2022-07-04 11:24 UTC, yuki-takei commented on packages/app/src/components/Sidebar.tsx
> +  const [isClient, setIsClient] = useState(false);
これをローカルステートで管理する必要はない

2022-07-04 11:24 UTC, yuki-takei commented on packages/app/src/components/Sidebar.tsx
> +  return SidebarNavElem();
別の手段で解決を。isServer(isClient)で出し分ける手段を使うかどうかも再検討。

2022-07-05 07:31 UTC, yuki-takei requested changes

2022-07-05 07:31 UTC, yuki-takei commented on packages/app/src/components/Sidebar.tsx
> +  const isLoading = isLoadingIsDrawerMode || isLoadingCurrentContents || isLoadingIsCollapsed;
原因は isLoading が SWR (クライアントでしか値を返さない) に依存してるからだね。

2022-07-05 10:28 UTC, Yohei-Shiina commented on packages/app/src/components/Sidebar.tsx
> +const GlobalNavigation = () => {
ここはアンコメントのみ

2022-07-05 10:30 UTC, Yohei-Shiina commented on packages/app/src/pages/[[...path]].page.tsx
> +  props.userUISettings = JSON.parse(JSON.stringify(userUISettings));
`JSON.parse(JSON.stringify())` は以下のエラー対応

> Error: Error serializing `.userUISettings` returned from `getServerSideProps` in "/[[...path]]".
Reason: `object` ("[object Object]") cannot be serialized as JSON. Please only return JSON serializable data types.

2022-07-05 11:20 UTC, yuki-takei requested changes

2022-07-05 11:20 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  isSidebarClosedAtDockMode: boolean,
ISidebarConfig の形で入れてください

2022-07-06 05:12 UTC, merged