Imprv/99374 next growi contextual sub nav
weseek/growi pull request #6199
Opened 2022-07-04 14:45 UTC by yukendev

2022-07-04 15:13 UTC, yukendev commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +      mutateCurrentPage();
前までは、appContainerを使ってrevisionIdを管理していましたが、useSWRxCurrentPage()で一括で情報を取得するようになったので、更新のためにmutateSWRTagsInfo();を呼んでいます。

2022-07-04 18:48 UTC, yuki-takei requested changes

2022-07-04 18:48 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> -      mutatePageTagsForEditors(newTags);
この辺の mutation は必要なのでは？

2022-07-05 03:38 UTC, yukendev commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> -      mutatePageTagsForEditors(newTags);
確かに。pageIdにしか依存してないので、mutateCurrentPage();をしただけでは更新されず、個別でmutateする必要がありました。ミスです、追加します

2022-07-07 03:41 UTC, merged