imprv: update subscribe button icon on Navbar
weseek/growi pull request #6213
Opened 2022-07-06 04:42 UTC by jam411

target ticket:https://redmine.weseek.co.jp/issues/99672

2022-07-06 05:03 UTC, jam411 commented on packages/app/src/styles/atoms/_buttons.scss
> +  width: 44px;
`fa-bell-o` と `fa-bell-slash-o` のwidthのずれがあったので, 多めに44pxとって調整

2022-07-06 05:16 UTC, kaoritokashiki requested changes

2022-07-06 05:16 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +        <div className="btn-group" role="group" aria-label="Subscribe buttons">
class に `btn-group` をセットした理由ってありますか??
`btn-group` は二つ以上のボタンをセットで表示したい時に使うイメージですが、このコードをみた感じだと`SubscribeButton` しか中にないので不要そうと思いました。
何か特別な理由があるのであれば教えてください。
https://getbootstrap.jp/docs/4.5/components/button-group/#basic-example

2022-07-06 05:16 UTC, kaoritokashiki commented on packages/app/src/components/SubscribeButton.tsx
> +  const iconClass = isSubscribing === false ? 'fa fa-bell-slash-o' : 'fa fa-bell-o';
このicon class, 43行目でしか使われていないので i タグにそのまま記述して良さそうです!
あともう少し短くかけそうです。

2022-07-06 05:16 UTC, kaoritokashiki commented on packages/app/src/styles/atoms/_buttons.scss
> +  box-shadow: none !important;
bootstrapのクラスで shadow を表示しないようにできるか試してもらえますか? 
https://getbootstrap.jp/docs/4.1/utilities/shadows/

2022-07-06 05:57 UTC, jam411 commented on packages/app/src/styles/atoms/_buttons.scss
> +  box-shadow: none !important;
できたので, pushしてみました. ご確認ください.

2022-07-06 05:57 UTC, jam411 commented on packages/app/src/components/SubscribeButton.tsx
> +  const iconClass = isSubscribing === false ? 'fa fa-bell-slash-o' : 'fa fa-bell-o';
修正ずみ.
BookmarkButton.tsx を参考に書き直しました.

2022-07-06 05:58 UTC, jam411 commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +        <div className="btn-group" role="group" aria-label="Subscribe buttons">
理由は合わせたいだけだったので他と合わせて不要にします.
階層を合わせたいので <div></div> だけ記載します.

2022-07-06 06:16 UTC, kaoritokashiki commented on packages/app/src/styles/atoms/_buttons.scss
> +  box-shadow: none !important;
他のボタンもついでに修正お願いします。🙏

2022-07-07 05:17 UTC, shukmos commented
![image](https://user-images.githubusercontent.com/20252919/177696854-027eefbe-994f-4163-bc3c-17cce3bf7767.png)
こちらのサブナビバーの方のBellアイコンのみ`fa-bell-o`ではなく[こちら](https://fontawesome.com/v4/icon/bell)の`fa-bell`を使ってください。
他のハートとブックマークのON状態がoutlineではないアイコンなので統一したいです。

2022-07-07 05:35 UTC, jam411 commented
`fa-bell`の対応   

・default
![image](https://user-images.githubusercontent.com/68407388/177698236-4ca31064-0e57-45c0-a17e-04e5ca26b863.png)
・ダークモード
![image](https://user-images.githubusercontent.com/68407388/177698274-c3bafe4a-cc10-4cfb-8940-d44157cf5612.png)

2022-07-07 05:37 UTC, jam411 commented on packages/app/src/styles/atoms/_buttons.scss
> +  box-shadow: none !important;
修正しました.

2022-07-07 06:05 UTC, kaoritokashiki requested changes

2022-07-07 06:13 UTC, jam411 commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +        <div>
修正しました.

2022-07-07 06:44 UTC, merged