feat Integrate implement page alert component
weseek/growi pull request #6218
Opened 2022-07-06 09:16 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/99063

2022-07-06 10:03 UTC, Yohei-Shiina commented on packages/app/src/pages/[[...path]].page.tsx
> +  }
Todoで残していた、URLクエリで指定された revisionId を_id にもつ Revisionドキュメント の存在チェックを実装(361行目)

2022-07-06 19:27 UTC, yuki-takei requested changes

2022-07-06 19:27 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  useXss(new Xss());
master では base.jsx でglobal variable として作成している。hooks に置き換えるなら全て置き換えたい。
利用している箇所は CustomWindow で検索。

2022-07-06 19:27 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  }
- 別メソッドに切り出してください
- この実装によって不要になる古いサーバーサイドコードを削除してください

2022-07-06 19:28 UTC, yuki-takei commented
追加された alert 系コンポーネントのコード分、古いコードを削除して欲しい。

2022-07-06 20:01 UTC, yuki-takei requested changes

2022-07-06 20:03 UTC, yuki-takei requested changes

2022-07-07 04:41 UTC, Yohei-Shiina commented on packages/app/src/interfaces/page.ts
> +export type IPageHasId = IPage & HasObjectId & {latestRevision?: Ref<IRevision>};
対応済み

2022-07-07 05:44 UTC, Yohei-Shiina commented on packages/app/src/pages/[[...path]].page.tsx
> +  }
Pageモデルにlatestかどうか確認する機構があったのでそれに置き換えました

2022-07-07 05:45 UTC, Yohei-Shiina commented on packages/app/src/pages/[[...path]].page.tsx
> +  }
Pageモデルにlatestかどうか確認する機構があったのでそれに置き換えました

2022-07-07 06:17 UTC, Yohei-Shiina commented on packages/app/src/components/PageAlert/TrashPageAlert.tsx
> +  const { data: updatedAt } = useCurrentUpdatedAt();
ここは pagedata から取得するようにしました。
GrowiContextualSubNavigation で useCurrentUpdatedAt が使われているので context からは削除しませんでした

2022-07-07 06:24 UTC, Yohei-Shiina commented on packages/app/src/pages/[[...path]].page.tsx
> +  useXss(new Xss());
対応しました

2022-07-07 06:42 UTC, Yohei-Shiina commented on packages/app/src/components/PageAlert/FixPageGrantAlert.tsx
> +};
対応ずみ

2022-07-07 08:12 UTC, yuki-takei commented on packages/app/src/components/PageAlert/TrashPageAlert.tsx
> +  const { data: updatedAt } = useCurrentUpdatedAt();
GrowiContextualSubNavigation の該当部分も合わせてリファクタすべき。

2022-07-08 04:24 UTC, merged