imprv: next GrowiSubNavigation
weseek/growi pull request #6220
Opened 2022-07-07 04:02 UTC by yukendev

https://redmine.weseek.co.jp/issues/99348

GrowiContextualSubNavigationが完全に使えるようになりました

2022-07-08 11:56 UTC, yuki-takei requested changes

2022-07-08 11:56 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +    };
このファイルのリファクタって必須なの？デグレが怖いなと思ってコメントしてるんだけど。

2022-07-08 11:56 UTC, yuki-takei commented on packages/app/src/components/Navbar/PageEditorModeManager.jsx
> +        className={`btn-group grw-page-editor-mode-manager ${styles['grw-subnav']}`}
ここおかしいね

2022-07-11 02:47 UTC, yukendev commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +    };
displayNameのlintエラーが出ていたのでリファクタしました

2022-07-11 02:49 UTC, yukendev commented on packages/app/src/components/Navbar/PageEditorModeManager.jsx
> +        className={`btn-group grw-page-editor-mode-manager ${styles['grw-subnav']}`}
修正済み

2022-07-11 07:50 UTC, merged