[WIP] support: Refactor growi renderer using hooks
weseek/growi pull request #6223
Opened 2022-07-07 06:05 UTC by hakumizuki

Redmine: 

GrowiRenderer 周りの hooks 化

2022-07-07 07:11 UTC, hakumizuki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  useRendererSettings({
useRendererSettings の初期化

2022-07-07 07:13 UTC, hakumizuki commented on packages/app/src/client/util/GrowiRenderer.ts
> +  init() {
initMarkdownItConfigurers を解体して init に改名

2022-07-07 07:15 UTC, hakumizuki commented on packages/app/src/stores/renderer.tsx
> +import { Key, SWRResponse } from 'swr';
ケース別 renderers

2022-07-07 07:25 UTC, hakumizuki commented on packages/app/src/client/util/GrowiRenderer.ts
> +};
個別で設定が必要なものは分ける

2022-07-07 07:39 UTC, yuki-takei requested changes

2022-07-07 07:39 UTC, yuki-takei commented on packages/app/src/client/util/GrowiRenderer.ts
> +  appContainer: any
できれば appContainer に依存しないようにしたい。(が、工数がかかるなら諦める)

2022-07-07 07:39 UTC, yuki-takei commented on packages/app/src/client/util/GrowiRenderer.ts
> +};
factory は Next.js 化でサーバーサイドからも使うことになる。
必ずしも master でユニバーサルになっている必要はないが、最低限ページのリネームや移動で差分が出ないように `src/client` からは外に出したほうがいい。

2022-07-08 04:38 UTC, hakumizuki commented on packages/app/src/client/util/GrowiRenderer.ts
> +  appContainer: any
依存外しました

2022-07-08 04:39 UTC, hakumizuki commented on packages/app/src/client/plugin.js
> +  installAll(appContainer) {
originRenderer は廃止しました

2022-07-08 04:39 UTC, hakumizuki commented on packages/app/src/client/services/AppContainer.js
> -    this.rendererInstances = {};
これも不要になったので削除

2022-07-08 04:39 UTC, hakumizuki commented on packages/app/src/client/services/AppContainer.js
> -    this.originRenderer = new GrowiRenderer(this);
`originRenderer` は `window.growiRenderer` に統合

2022-07-08 04:40 UTC, hakumizuki commented on packages/app/src/client/services/AppContainer.js
> +    window.growiRenderer = new GrowiRenderer(this.getConfig());
ここで `window.growiRenderer` に注入

2022-07-08 04:41 UTC, hakumizuki commented on packages/app/src/client/services/AppContainer.js
> -  getRenderer(mode) {
用途別に解体した

2022-07-08 04:41 UTC, hakumizuki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  });
Renderer に必要なものをピックアップして `RendererSettings` として StaticSWR化

2022-07-08 04:42 UTC, hakumizuki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  useGrowiRendererConfig({
Renderer に必要な Config をピックアップして `RendererConfig` として StaticsSWR 化

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  // Do not access this property from other than reveal.js plugins.
reveal.js 用に `previewRenderer` を `window` に注入

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/client/util/reveal/plugins/growi-renderer.js
>  (function(root, factory) {
appContainer を排除

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/interfaces/global.ts
> +                         & { previewRenderer: GrowiRenderer }; // TODO: Remove this code when reveal.js is omitted. see: https://github.com/weseek/growi/pull/6223
`CustomWindow` 型に追加

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/services/renderer/PreProcessor/XssFilter.ts
> +import Xss from '~/services/xss';
TS化して `appContainer` を排除

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/services/renderer/markdown-it/blockdiag.js
> +  constructor(growiConfig) {
`appContainer` の代わりに `growiConfig` をとるように変更

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/services/renderer/markdown-it/link-by-relative-path.ts
> +  constructor(pagePath: string) {
`appContainer` の代わりに `pagePath` をとるように変更

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/services/renderer/markdown-it/mathjax.js
> +  constructor(growiConfig) {
appContainer の代わりに growiConfig をとるように変更

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/services/renderer/markdown-it/plantuml.js
> +  constructor(growiConfig) {
appContainer の代わりに growiConfig をとるように変更

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/services/renderer/markdown-it/task-lists.js
> -  }
そもそも使われてないので削除

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/services/xss/xssOption.ts
> +export type XssOptionConfig = {
ただただ TS 化

2022-07-08 04:55 UTC, hakumizuki commented on packages/plugin-pukiwiki-like-linker/src/client-entry.js
> +  window.growiRenderer.preProcessors.unshift(new PukiwikiLikeLinker());
`window.growiRenderer` を使う

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/client/services/AppContainer.js
> -    this.rendererInstances = {};
不要になったので削除

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/client/services/AppContainer.js
> -    this.originRenderer = new GrowiRenderer(this);
`originRenderer` は `window.growiRenderer` に統合

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/client/services/AppContainer.js
> +    window.growiRenderer = new GrowiRenderer(this.getConfig());
ここで `window.growiRenderer` に注入

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/client/services/AppContainer.js
> -  getRenderer(mode) {
用途別に解体した

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  });
Renderer に必要なものをピックアップして `RendererSettings` として StaticSWR 化

2022-07-08 04:55 UTC, hakumizuki commented on packages/app/src/client/services/ContextExtractor.tsx
> +  });
Renderer に必要な Config をピックアップして `RendererConfig` として StaticsSWR 化

型は `packages/app/src/interfaces/services/renderer.ts` に定義した

2022-07-08 11:45 UTC, yuki-takei requested changes

2022-07-08 11:45 UTC, yuki-takei commented on packages/app/src/stores/renderer.tsx
> +};
useViewRenderer, usePreviewRenderer, ... の用途別 hooks も結構コード重複があって、
その上 generateViewRenderer, generatePreviewRenderer, ... という factory method もバラバラっていうのはもう少し整理してほしいな。

2022-07-08 11:54 UTC, hakumizuki commented on packages/app/src/stores/renderer.tsx
> +};
メモ: generateHoge を外から渡す形にする

2022-07-09 03:20 UTC, hakumizuki commented on packages/app/src/stores/renderer.tsx
> +};
`_useRendererBase` に処理を共通化しました

現在は基本的に `generateViewRenderer` を渡し、必要があればカスタムされた別の `RendererGenerator` を渡す形にしました

2022-07-09 03:23 UTC, hakumizuki commented on packages/app/src/services/renderer/growi-renderer.ts
> +}
generateHogeRenderer を `RendererGenerator` interface に 統一

2022-07-09 03:24 UTC, hakumizuki commented on packages/app/src/stores/renderer.tsx
> +const _useRendererBase = (key: Key, generator: RendererGenerator): SWRResponse<GrowiRenderer, any> => {
[FB対応]
共通化した hook

2022-07-11 07:26 UTC, yuki-takei commented
reveal の emoji のデグレ修正待ち

2022-07-11 07:49 UTC, hakumizuki commented
https://github.com/weseek/growi/pull/6223/commits/b708c45fecefdb7a8b521cd16230c940261c178d で修正しました

2022-07-11 08:31 UTC, merged