Imprv/100056 show app settings
weseek/growi pull request #6236
Opened 2022-07-11 11:50 UTC by kaoritokashiki

2022-07-11 11:55 UTC, kaoritokashiki commented on packages/app/src/components/Admin/App/AppSetting.jsx
> +import { i18n } from '~/next-i18next.config';
`'~/client/util/i18n` の代わりに '~/next-i18next.config' を使用

2022-07-12 09:13 UTC, yuki-takei requested changes

2022-07-12 09:13 UTC, yuki-takei commented on packages/app/public/static/locales/ja_JP/translation.json
> +    "zh_CN": "中国語"
ここちょっと工夫する必要がある。

ある英語圏の人が日本語設定のPCを使って GROWI をセットアップしようとしたとする(まあシチュエーションはなんでもいいが)。
ブラウザーの言語設定から自動で日本語が選択されて、言語選択ドロップダウンを開いた時に、英語圏の人は「English」を探す。「英語」は読めないはず。

なので、このラベルはネイティブが識別可能な一意の文字列にしたほうがよい。全 translation に書くものでもないので support/apply-nextjs ではこういうのを用意してたりする。
https://github.com/weseek/growi/blob/support/apply-nextjs/public/static/locales/en_US/translation.json#L3

ただこれをどうやって読むんだったか、方法はわすれた。。

2022-07-13 08:31 UTC, kaoritokashiki commented on packages/app/public/static/locales/ja_JP/translation.json
> +    "zh_CN": "中国語"
`i18n-next` の`getFixedT`と `loadLanguages` を使用して実現させました。

2022-07-13 08:35 UTC, merged