show ExportArchiveDataPage
weseek/growi pull request #6239
Opened 2022-07-12 02:34 UTC by kaoritokashiki

2022-07-12 02:41 UTC, kaoritokashiki commented on packages/app/src/components/Admin/ExportArchiveDataPage.jsx
> -const ExportArchiveDataPageWrapper = withUnstatedContainers(ExportArchiveDataPageWrapperFC, [AppContainer, AdminSocketIoContainer]);
- `AppContainer` 👉🏻 使われていなかったので削除
- AdminSocketIoContainer 👉🏻 代わりに useDefaultSocket を使用しました。

2022-07-12 02:43 UTC, kaoritokashiki commented on packages/app/src/components/Admin/ExportArchiveDataPage.jsx
> +    if (socket != null) {
socket の null checkをしています。

2022-07-12 09:19 UTC, yuki-takei requested changes

2022-07-12 09:19 UTC, yuki-takei commented on packages/app/src/components/Admin/ExportArchiveDataPage.jsx
> -const ExportArchiveDataPageWrapper = withUnstatedContainers(ExportArchiveDataPageWrapperFC, [AppContainer, AdminSocketIoContainer]);
この用途では useAdminSocket にするんじゃないかな。

2022-07-13 10:33 UTC, kaoritokashiki commented on packages/app/src/components/Admin/ExportArchiveDataPage.jsx
> -const ExportArchiveDataPageWrapper = withUnstatedContainers(ExportArchiveDataPageWrapperFC, [AppContainer, AdminSocketIoContainer]);
`useAdminSocket ` に置き換えました。

2022-07-13 10:56 UTC, merged