support: delete appcontainer for page comments
weseek/growi pull request #6260
Opened 2022-07-14 03:26 UTC by jam411

タスク: https://redmine.weseek.co.jp/issues/100027

PageCommentのNext化へ向けて, 関連するコンポーネントのContainerを削除, SWR化.

2022-07-14 05:09 UTC, kaoritokashiki requested changes

2022-07-14 05:14 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +          <PageComment pageId={useCurrentPageId()} isReadOnly={false} titleAlign="left" />
反映もれでした. 修正済み.

2022-07-14 08:56 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.jsx
> +  revisionCreatedAt: PropTypes.object,
ありがとうございます. 一旦, instanceOf()にしました.

2022-07-15 06:34 UTC, kaoritokashiki commented on packages/app/src/components/PageComment/Comment.jsx
> +  revisionCreatedAt: PropTypes.object,
instanceOf は `revisionCreatedAt ` だけのことを言っていました

2022-07-15 06:35 UTC, kaoritokashiki commented on packages/app/src/components/PageComment/Comment.jsx
> +  interceptorManager: PropTypes.instanceOf(interceptorManager).isRequired,
instanceOf は revisionCreatedAt だけのことを言っていました

2022-07-15 06:35 UTC, kaoritokashiki requested changes

2022-07-15 06:35 UTC, kaoritokashiki commented on packages/app/src/components/PageComment/Comment.jsx
> +  interceptorManager: PropTypes.instanceOf(interceptorManager).isRequired,
instanceOf は revisionCreatedAt だけのことを言っていました

2022-07-15 06:44 UTC, kaoritokashiki commented on packages/app/src/components/PageComment/Comment.jsx
> +  interceptorManager: PropTypes.instanceOf(interceptorManager).isRequired,
引数に入れている値がおかしいので修正を 🙏 
意味わからなかったら聞いてください

2022-07-15 08:47 UTC, merged