feat: gw7836 truncate long path when recent changes is in S size
weseek/growi pull request #6263
Opened 2022-07-14 06:18 UTC by mudana-grune

https://youtrack.weseek.co.jp/issue/GW-7836
- Add text-truncate class to page path in SmallPageItem
- Override .flex-grow-1 and .truncate-text in _recent-changes.scss

# Test
## Size L
![default](https://user-images.githubusercontent.com/92426728/178913506-18b5d981-1056-40a6-a2c7-ad5be129108b.png)

## Size S
![truncated](https://user-images.githubusercontent.com/92426728/178913532-37074539-29cd-489e-bc16-8351060f1b29.png)

2022-07-22 08:58 UTC, yuki-takei requested changes

2022-07-22 08:58 UTC, yuki-takei commented on packages/app/src/styles/_recent-changes.scss
> +    }
truncate-text のためというコメントを付けて

2022-07-25 09:00 UTC, miya reviewed
add comment

2022-07-25 09:57 UTC, miya commented on packages/app/src/styles/_recent-changes.scss
> +    }
コメントつけました

2022-09-06 07:29 UTC, merged