Imprv/10035 show user group management and slack integration
weseek/growi pull request #6272
Opened 2022-07-14 17:12 UTC by kaoritokashiki

2022-07-14 17:29 UTC, kaoritokashiki commented on packages/app/src/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
> +  }, [appTitle]);
`appContainer` からではなく、`useAppTitle`から取得するように変更しました。

2022-07-14 17:37 UTC, kaoritokashiki commented on packages/app/src/components/SuspenseUtils.jsx
> +};
`withLoadingSppiner`でエラーが出て画面が描画されないのを修正しました。

2022-07-14 19:26 UTC, yuki-takei requested changes

2022-07-21 06:24 UTC, kaoritokashiki commented on packages/app/src/components/Admin/LegacySlackIntegration/LegacySlackIntegration.jsx
> -const LegacySlackIntegrationWithUnstatedContainer = withUnstatedContainers(withLoadingSppiner(LegacySlackIntegration), [AdminSlackIntegrationLegacyContainer]);
`withLoadingSppiner` は削除

2022-07-21 06:25 UTC, kaoritokashiki commented on packages/app/src/components/Admin/SlackIntegration/SlackIntegration.jsx
> -const SlackIntegrationWrapper = withUnstatedContainers(SlackIntegration, [AppContainer]);
`AppContainer` は使われていなかったので削除

2022-07-21 06:26 UTC, kaoritokashiki commented on packages/app/src/components/SuspenseUtils.jsx
> +};
`withLoadingSppiner` は以下のタスクで一括削除いたします。
https://redmine.weseek.co.jp/issues/100060

2022-07-21 06:34 UTC, kaoritokashiki commented on packages/app/src/components/Admin/LegacySlackIntegration/LegacySlackIntegration.jsx
> +    // TODO: Omit AdminSlackIntegrationLegacyContainer by https://redmine.weseek.co.jp/issues/100947
後続で Omit AdminSlackIntegrationLegacyContainer します

2022-07-21 06:48 UTC, kaoritokashiki commented on packages/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
> +        {options}
これコメントアウトの方が良かったかな

2022-07-21 09:35 UTC, merged