Imprv/show toc
weseek/growi pull request #6277
Opened 2022-07-15 07:16 UTC by yukendev

https://redmine.weseek.co.jp/issues/100207
<img width="319" alt="toc" src="https://user-images.githubusercontent.com/65263895/179184651-666346a5-1b9e-4dde-8a2d-025f23bea2ac.PNG">

- tocをNext化されたページで表示できるようにした
- スタイルを当てるのと、tocをタップしたときの挙動の実装は後続タスクでやります(https://redmine.weseek.co.jp/issues/100635)

2022-07-15 08:20 UTC, yukendev commented on packages/app/src/components/TableOfContents.tsx
> +        </ReactMarkdown>
空のマークダウンをReactMarkdownに渡し、optionの中のプラグインでtoc部分を挿入することでtocを表示しています。説明が難しいのでわからない部分があれば、口頭で説明します。

2022-07-15 08:21 UTC, yukendev commented on packages/app/src/services/renderer/renderer.tsx
> +  (config: RendererConfig, customizer?: RendererOptionsCustomizer): RendererOptions
rendererのオプションを外部の値でカスタマイズする必要があったので、引数にcustomizerを追加しました。

2022-07-15 08:25 UTC, yukendev commented
ciでエラーが出ていますが、tscのエラーなので無視しています

2022-07-15 08:46 UTC, yuki-takei requested changes

2022-07-15 08:46 UTC, yuki-takei commented on packages/app/src/stores/renderer.tsx
> +  return _useOptionsBase(key, generateTocOptions, customizer);
generateTocOptions の wrapper メソッドを作れば customizer いらない。

2022-07-15 09:23 UTC, yuki-takei requested changes

2022-07-15 09:23 UTC, yuki-takei commented on packages/app/src/stores/renderer.tsx
> +import toc, { HtmlElementNode } from 'rehype-toc';
rehype 関連パッケージを取り扱うのは services/renderer/renderer にすべきかな。

2022-07-19 03:11 UTC, yukendev commented
いろいろRevertとかしてますが、間違ってsupport/apply-nextjs2をマージしてしまったのを取り消したりしているだけで、実際何もしていません。修正点は
- customizeを別ファイルに移動
- lint errorの修正
です

2022-07-19 05:16 UTC, yuki-takei requested changes

2022-07-19 05:16 UTC, yuki-takei commented on packages/app/src/services/renderer/renderer.tsx
> +};
generateViewOptions と customizeViewOptions を別で用意する意味ある？ないのであれば統合してほしい。

2022-07-19 05:16 UTC, yuki-takei commented on packages/app/src/services/renderer/renderer.tsx
> +};
generateTocOptions と customizeTocOptions も同様。

2022-07-19 06:13 UTC, yukendev commented on packages/app/src/services/renderer/renderer.tsx
> +};
修正済み

2022-07-19 06:14 UTC, yukendev commented on packages/app/src/services/renderer/renderer.tsx
> +};
修正済み

2022-07-19 06:31 UTC, merged