Support/apply nextjs to page comments
weseek/growi pull request #6279
Opened 2022-07-15 09:02 UTC by jam411

Target Task: https://redmine.weseek.co.jp/issues/100253

## 概要
PageCommment (Footer周り)のNext化のため, 一旦レンダリングできるまで．
- containerの削除
- renderer インポートと conflict解消

## After
![image](https://user-images.githubusercontent.com/68407388/179190718-7be25553-7d14-4d0f-a45d-9063c54c50fd.png)

2022-07-15 09:05 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.jsx
> +        // isMathJaxEnabled={isMathJaxEnabled}
config に env.MATHJAX が定義されていなかったため一旦コメントアウトしています.

2022-07-15 09:06 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.jsx
> +    // context.parsedHTML = await rendererOptions.postProcess(context.parsedHTML, context);
rendererOptions.preProcess(), rendererOptions.process(), rendererOptions.postProcess() はエラーがでるため一旦コメントアウト.

2022-07-15 09:06 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.jsx
> +  // interceptorManager: PropTypes.instanceOf(InterceptorManager),
一旦コメントアウト.

2022-07-15 09:21 UTC, yuki-takei requested changes

2022-07-15 09:21 UTC, yuki-takei commented on packages/app/src/components/PageComment.tsx
> +import { Nullable } from '^/../core/src/interfaces/common';
`@growi/core` からインポートしてください。

2022-07-15 09:21 UTC, yuki-takei commented on packages/app/src/components/PageComment/Comment.jsx
> +    // const isMathJaxEnabled = !!config.env.MATHJAX;
env.MATHJAX は廃止するので消してよいです。

2022-07-15 09:21 UTC, yuki-takei commented on packages/app/src/components/PageComment/Comment.jsx
> +    // context.parsedHTML = await rendererOptions.postProcess(context.parsedHTML, context);
ReactMarkdown 使ってください。

2022-07-21 07:10 UTC, kaoritokashiki commented on packages/app/src/components/PageComment/CommentEditor.tsx
>    const isSlackConfigured = config.isSlackConfigured;
認識間違ってたらすみませんが、
`useRendererConfig` から `upload.file` `upload.image` `isSlackConfigured`取得できるんですかね...?? 👀

2022-07-26 01:25 UTC, jam411 commented on packages/app/src/components/PageComment.tsx
> +import { Nullable } from '^/../core/src/interfaces/common';
修正済み

2022-07-26 05:58 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.jsx
> +  // interceptorManager: PropTypes.instanceOf(InterceptorManager),
FC, tsx化で対応.

2022-07-26 05:58 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.jsx
> +    // const isMathJaxEnabled = !!config.env.MATHJAX;
対応済み

2022-07-26 05:59 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.jsx
> +    // context.parsedHTML = await rendererOptions.postProcess(context.parsedHTML, context);
修正済み.

2022-07-26 06:50 UTC, jam411 commented
![image](https://user-images.githubusercontent.com/68407388/180941715-f8d3b684-b2d4-42c2-bfa8-b480489f30b3.png)

- Comment.tsx の ReactMarkdown 使用で絵文字表示まで

2022-07-27 11:29 UTC, yuki-takei requested changes

2022-07-27 11:29 UTC, yuki-takei commented on packages/app/src/components/PageComment/ReplayComments.jsx
> +    const isAllReplyShown = config.isAllReplyShown || false;
これは RendererConfig には入れないと思う。(remark/rehype の設定と関係ないので)

2022-07-27 11:29 UTC, yuki-takei commented on packages/app/src/services/renderer/renderer.tsx
> +    if (config.isEnabledLinebreaks) {
isEnabledLinebreaksInComments の方を使う

2022-07-28 05:09 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  // const isSlackConfigured = config.isSlackConfigured;
こちらのタスクで取り組みます. https://redmine.weseek.co.jp/issues/101393

2022-07-28 05:11 UTC, jam411 commented on packages/app/src/components/PageComment/ReplayComments.jsx
> +    const isAllReplyShown = config.isAllReplyShown || false;
承知しました. 取り組む場合はこちらのPR配下のタスクで取り組もうと思います. https://github.com/weseek/growi/pull/6356

2022-07-28 05:11 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.tsx
> +      interceptorManager.process('postRenderCommentHtml', comment.comment);
修正しました.

2022-07-28 06:50 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.tsx
> +  const { data: revisionCreatedAt } = useRevisionCreatedAt();
修正しました.
useCurrentUser から取得する currentUser は Comment で自律的に取得するままにしています.

2022-07-28 06:55 UTC, jam411 commented on packages/app/src/services/renderer/renderer.tsx
> +    if (config.isEnabledLinebreaks) {
修正しました.

2022-07-28 06:59 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.tsx
> +  }
エラーのため一旦記載, ReplayComments.jsx を改修後に削除.

2022-07-28 07:54 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.tsx
> +    else if (Date.parse(comment.createdAt.toString()) > Date.parse(currentRevisionCreatedAt.toString())) {
現状の取得している値に合わせて修正

2022-07-29 06:35 UTC, yuki-takei requested changes

2022-07-29 06:35 UTC, yuki-takei commented on packages/app/src/components/PageComment/Comment.tsx
> +    else if (Date.parse(comment.createdAt.toString()) > Date.parse(currentRevisionCreatedAt.toString())) {
toString して parse するの無駄な気がするが…
そうしなきゃいけない理由がある？

2022-08-01 03:54 UTC, jam411 commented on packages/app/src/components/PageComment.tsx
>    const { data: rendererOptions } = useCommentPreviewOptions();
rendererOptions は props で渡さずに, CommentPreview で完結させたほうが良いと考えたので後続タスクでリファクタリングします.

2022-08-01 03:56 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.tsx
> +    else if (comment.createdAt.getTime() > currentRevisionCreatedAt.getTime()) {
getTime に変更.
出力は同じこと確認.

2022-08-01 06:45 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +// import Editor from '../PageEditor/Editor';
CIエラーのためコメントアウトしました.
参考PR https://github.com/weseek/growi/pull/6374 がマージ後に以下のタスクで再確認します.
修正タスク:https://redmine.weseek.co.jp/issues/101808

2022-08-01 08:06 UTC, yuki-takei approved these changes

2022-08-01 08:06 UTC, yuki-takei commented on packages/app/src/components/PageComment.tsx
>    const { data: rendererOptions } = useCommentPreviewOptions();
いや、props で渡した方がいいのでそのリファクタは不要です。

2022-08-01 08:06 UTC, merged