imprv: 100335 implement skelton growi contextual sub nav
weseek/growi pull request #6295
Opened 2022-07-19 11:08 UTC by yukendev

https://redmine.weseek.co.jp/issues/100200
![スケルトン](https://user-images.githubusercontent.com/65263895/179736023-05d38e67-bddf-4dc5-a29e-cf82b38845a6.gif)

- GrowiContextualSubNavigationのコンポーネントのSSR時にスケルトンを表示
- PagePathNavに関しては、パスが長いと2行になり、高さが動的に変化するのでスケルトンを実装するとカクついてしまうため、SSRするようにしました

2022-07-19 11:30 UTC, yukendev commented on packages/app/src/server/routes/apiv3/users.js
> +  router.delete('/:id/remove', loginRequiredStrictly, adminRequired, addActivity, async(req, res) => {
このPRとは全く関係ない箇所ですが、lintエラーを修正しました

2022-07-20 09:34 UTC, yukendev commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  // dynamic import for show skelton
スケルトンの幅と高さは実際の大きさを参考に値を決めました

2022-07-20 09:35 UTC, yukendev commented on packages/app/src/components/Skelton.tsx
> +}
スケルトンは、幅と高さを指定したい場合と、クラスでスタイルを当てたい場合があるかなと考えたのでプロパティはオプショナルにしています

2022-07-20 12:21 UTC, yuki-takei requested changes

2022-07-20 12:21 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  // dynamic import for show skelton
height は css に任せられるはず。

2022-07-20 12:21 UTC, yuki-takei commented on packages/app/src/components/Skelton.module.scss
> +}
light/dark を考えると一律 $gray-200 にはできないはず。
apply-colors or apply-colors-dark で指定したい。

2022-07-20 12:21 UTC, yuki-takei commented on packages/app/src/components/Skelton.tsx
> +}
rounded-pill を適用する boolean があったら便利そうだね

2022-07-21 03:04 UTC, yukendev commented on packages/app/src/components/Skelton.tsx
> +}
修正済み

2022-07-21 03:48 UTC, yukendev commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  // dynamic import for show skelton
修正済み

2022-07-21 04:40 UTC, yukendev commented on packages/app/src/components/Skelton.module.scss
> +}
修正済み

2022-07-21 04:42 UTC, yukendev commented on packages/app/src/components/BookmarkButtons.tsx
>          type="button"
LikeButtonなどのボタンで、モジュール化されたスタイルしか当たっておらず、SubNav配下のスタイルが当たっていないことに気が付いたので、globalなクラス名を追加しました。

2022-07-21 07:01 UTC, merged