feat: gw7841 implement delete from bookmark sidebar
weseek/growi pull request #6320
Opened 2022-07-21 09:24 UTC by mudana-grune

4. implement "delete"
https://youtrack.weseek.co.jp/issue/GW-7841

### Result
![delete](https://user-images.githubusercontent.com/92426728/180179318-fd13ed45-0435-4a73-8411-b5ec1853e352.gif)

2022-07-22 05:02 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/Bookmarks.tsx
> +                  <BookmarksItem key={data.page._id} page={data.page} swr={swr} />
swrをそのままpropsで渡すってありなんだろうか...?

2022-07-22 05:51 UTC, yuki-takei commented on packages/app/src/components/Sidebar/Bookmarks.tsx
> +                  <BookmarksItem key={data.page._id} page={data.page} swr={swr} />
はい、その方がよいです

2022-08-05 00:12 UTC, kaoritokashiki requested changes

2022-08-05 00:12 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/Bookmarks.tsx
> +                onDeleted={onBookmarkItemDeleted}
The method name is not appropriate and please fix the method name like I said before. 
if you have questions, let me know.

2022-08-08 03:35 UTC, kaoritokashiki requested changes

2022-08-08 03:35 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/Bookmarks.tsx
> +  const deleteBookmarkItem = (pageToDelete: IPageToDeleteWithMeta) => {
`deleteMenuItemClickHandler` should be okay.

2022-08-08 03:35 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/Bookmarks.tsx
> +    onDeleted(pageToDelete);
```suggestion
    onClickDeleteMenuItem(pageToDelete);
```

2022-08-08 03:45 UTC, kaoritokashiki requested changes

2022-08-08 03:45 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/Bookmarks.tsx
> +    openDeleteModal([pageToDelete], { onDeleted: onDeletedHandler });
```suggestion
    openDeleteModal([pageToDelete], { onDeleted: pageDeletedHandler });
```

Some people might confuse removing bookmarks and page deletion so I consider that we should be declare page deletion expressly.

2022-08-08 12:39 UTC, merged