Feat Render modal containing page list and timeline
weseek/growi pull request #6335
Opened 2022-07-22 10:20 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/101104

2022-07-26 08:26 UTC, yuki-takei commented
- コンフリクトしてるので解消して自分でマージしてください
- スタイルはここでやっといた方がいいと思うなあ(この修正やってる人が一緒にやるのが早い)

2022-07-26 08:29 UTC, yuki-takei requested changes

2022-07-26 08:29 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +};
dynamic import は DescendantsPageListModal の中に入れたい。(カプセル化＆可読性向上)
ついでに言うと open/close のロジックまでその中に入れたい。(レンダリングパフォーマンス向上)
ついでに言うと他のモーダルも全てこの形にしたい。

2022-07-28 07:29 UTC, Yohei-Shiina commented on packages/app/src/pages/[[...path]].page.tsx
> +};
Memo
>モーダル外枠は通常通りレンダー
中身はOpenの時だけコンテンツをレンダー
それ以外は <></>

2022-08-02 05:16 UTC, Yohei-Shiina commented on packages/app/src/pages/[[...path]].page.tsx
> +        <DescendantsPageListModal />
カプセル化・可読性向上のためここでは dynamic import しないように変更

2022-08-02 05:17 UTC, Yohei-Shiina commented on packages/app/src/components/DescendantsPageListModal.tsx
> +        },
モーダルが開いていない時は `<></>` を retrun して レンダリングパフォーマンス向上

2022-08-02 06:14 UTC, Yohei-Shiina commented on packages/app/src/styles/style-next.scss
> +@import 'mixins';
モーダルの拡張表示の mixin を import

2022-08-02 06:14 UTC, Yohei-Shiina commented on packages/app/src/styles/style-next.scss
> +@import 'modal';
モーダルの拡張表示の mixin の使用

2022-08-02 10:41 UTC, yuki-takei requested changes

2022-08-02 10:41 UTC, yuki-takei commented on packages/app/src/styles/style-next.scss
> +@import 'page-accessories-modal';
この3つは可能な限り css module 化する。後続タスクでもOK。

2022-08-02 10:41 UTC, yuki-takei commented on packages/app/src/styles/style-next.scss
> +@import 'mixins';
_modal.scss に `@mixin expand-modal-fullscreen` を移植してください。

2022-08-02 10:41 UTC, yuki-takei commented on packages/app/src/styles/style-next.scss
> +@import 'modal';
modal はこのまま global style として取り扱う方向で OK。
逆に既に .grw-presentation-modal の方で @use してしまっているので、そちらでは @include しないように修正を。つまり、expand が必要なモーダルには全て `.grw-modal-expanded` というクラスを当てる。

2022-08-04 05:37 UTC, merged