support: FC/TSize PageAttachment
weseek/growi pull request #6336
Opened 2022-07-22 10:45 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/100965

PageAttachment を FC/TS 化しつつリファクタしました

2022-07-22 10:54 UTC, hakumizuki commented on packages/app/src/components/PageAttachment.tsx
> +const checkIfFileInUse = (markdown: string, attachment) => {
下の処理をコンポーネントの外に出しました

2022-07-22 10:56 UTC, hakumizuki commented on packages/app/src/components/PageAttachment.tsx
> +  const [pageNumber, setPageNumber] = useState(1);
もともと activePage だったのをリネーム

2022-07-22 10:57 UTC, hakumizuki commented on packages/app/src/components/PageAttachment.tsx
> +const useInUseAttachments = (attachments) => {
inUse 周りのロジックはここに切り出しました

2022-07-22 10:58 UTC, hakumizuki commented on packages/app/src/pages/[[...path]].page.tsx
> +  useCurrentMarkdown(props.markdown);
新たに追加

2022-07-22 10:58 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/attachment.js
> +      query('pageNumber').optional().isInt().withMessage('pageNumber must be a number'),
リネーム

2022-07-22 10:58 UTC, hakumizuki commented on packages/app/src/stores/attachment.tsx
> +  const fetcher = useCallback(async(endpoint) => {
fetcher もメモ化

2022-07-22 10:58 UTC, hakumizuki commented on packages/app/src/stores/attachment.tsx
> +  return withUtils<Util, IDataAttachmentList, Error>(swrResponse, { remove });
withUtils で remove を追加

2022-07-22 11:01 UTC, hakumizuki commented on packages/app/src/stores/attachment.tsx
> +export const useSWRxAttachments = (pageId?: Nullable<string>, pageNumber?: number): SWRResponseWithUtils<Util, IDataAttachmentList, Error> => {
`/attachments/list` 用 SWR
プラスで remove 用ユーティリティも入れた

2022-07-23 18:37 UTC, yuki-takei requested changes

2022-07-23 18:37 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  props.markdown = pageWithMeta.revision.body;
pageWithMeta は構造を保ったまま props に入るので、わざわざ props.markdown を用意する必要はない。

2022-07-23 18:37 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  useCurrentMarkdown(props.markdown);
「今表示中のページの markdown を保持する SWR」という用途であれば既に useSWRxCurrentPage がある。
もし「編集中の markdown」を保持したいなら名前を変えた方がいい。current という単語は「今表示中のページの～～」というコンテキストで使われることが多いので。

2022-07-25 02:18 UTC, hakumizuki commented on packages/app/src/pages/[[...path]].page.tsx
> +  props.markdown = pageWithMeta.revision.body;
この行は削除しました

2022-07-25 02:29 UTC, hakumizuki commented on packages/app/src/pages/[[...path]].page.tsx
> +  useCurrentMarkdown(props.markdown);
useEditingMarkdown に変更しました

2022-07-25 02:29 UTC, merged