feat: Display number of actions that can be saved
weseek/growi pull request #6353
Opened 2022-07-26 09:29 UTC by miya

## Task
[#101373](https://redmine.weseek.co.jp/issues/101373) [AuditLog] 現在収集できるアクションの種類が全体のうち何個なのかを設定画面に表示できる
└ [#101396](https://redmine.weseek.co.jp/issues/101396) 実装

2022-07-26 11:39 UTC, yuki-takei requested changes

2022-07-26 11:39 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLog/AuditLogSettings.tsx
> +        dangerouslySetInnerHTML={{ __html: actionCounter }}
- dangerouslySetInnerHTML を使わなくても再現できるはず
- h4 の中に badge とかで `14 / 156` だけ表示するだけでよさそう
    - 横に「?」アイコンでも置いて docs に飛ばすようにすればわけはわかるので

2022-07-29 02:16 UTC, miya commented on packages/app/src/components/Admin/AuditLog/AuditLogSettings.tsx
> +        dangerouslySetInnerHTML={{ __html: actionCounter }}
修正しました。
PR の説明欄のスクリーンショットに新しくなったものを貼り付けています。

2022-07-29 06:36 UTC, yuki-takei requested changes

2022-07-29 06:36 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLog/AuditLogSettings.tsx
> +          href="https://docs.growi.org/en/admin-guide/admin-cookbook/audit-log-setup.html#log-types"
ja/en だけでも出し分けて

2022-07-29 07:13 UTC, miya commented on packages/app/src/components/Admin/AuditLog/AuditLogSettings.tsx
> +          href="https://docs.growi.org/en/admin-guide/admin-cookbook/audit-log-setup.html#log-types"
修正しました。

2022-07-29 07:32 UTC, merged