Imprv/101284 show each tab contents on authentication mechanism settings
weseek/growi pull request #6354
Opened 2022-07-26 11:36 UTC by kaoritokashiki

2022-07-26 13:04 UTC, kaoritokashiki commented on packages/app/src/stores/context.tsx
> +
`useIsMailerSetup` を定義

2022-07-26 13:05 UTC, kaoritokashiki commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +  injectServerConfigurations(context, props)
`isMailerSetup` をクライアント側で使用するために `injectServerConfigurations` を定義して使うようにしました。

2022-07-26 13:06 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
> +      isMailerSetup
`appContainer.config` からではなく、swr のpops から取得するように変更しました。

2022-07-26 13:13 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Security/GitHubSecuritySettingContents.jsx
> +              value={gitHubCallBackUrl}
元は `appSiteUrl ` を参照しているが、callBackUrl を表示するのが正しいので修正しました。

2022-07-26 13:46 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
> +    const samlCallbackUrl = urljoin(pathUtils.removeTrailingSlash(siteUrl), '/passport/saml/callback');
<img width="771" alt="Screen Shot 2022-07-26 at 22 46 08" src="https://user-images.githubusercontent.com/59536731/181021588-4ccfdf18-6bc0-467e-9074-cfa0bf7df139.png">

2022-07-27 10:18 UTC, yuki-takei requested changes

2022-07-27 10:18 UTC, yuki-takei commented on packages/app/src/components/Admin/Security/BasicSecuritySetting.jsx
> +  }, [adminBasicSecurityContainer]);
try-catch まで含んだ useCallback を用意した方がいいだろうね。現在のコードだと、fetchBasicSecuritySettingsData の成否と catch が関係なくなってしまう。

2022-07-27 10:18 UTC, yuki-takei commented on packages/app/src/components/Admin/Security/GitHubSecuritySettingContents.jsx
> +            {!siteUrl && (
null チェックはガイドライン通りに

2022-07-28 06:12 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Security/BasicSecuritySetting.jsx
> +  }, [adminBasicSecurityContainer]);
修正いたしました。

2022-07-28 06:20 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Security/GitHubSecuritySettingContents.jsx
> +            {!siteUrl && (
修正いたしました。

2022-07-28 13:37 UTC, yuki-takei requested changes

2022-07-28 13:37 UTC, yuki-takei commented on packages/app/src/components/Admin/Security/TwitterSecuritySettingContents.jsx
> +            {siteUrl != null && (
これだけだと siteUrl が空文字列だった場合に alert が出ないのでは？

2022-07-29 03:51 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Security/TwitterSecuritySettingContents.jsx
> +            {siteUrl != null && (
すみませんコメントし忘れていたのですが、
アプリ設定でサイトURLを設定するときに空文字列を入れて更新ボタンを押すとエラーが出力されて更新できないのでそもそもsiteUrlに空文字列が入ることががないと判断し条件分岐に追加しませんでした。

2022-07-29 05:58 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Security/GitHubSecuritySettingContents.jsx
> +            {(siteUrl == null || siteUrl === '') && (
siteUrl が空文字列だった場合も対応

2022-07-29 05:59 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Security/TwitterSecuritySettingContents.jsx
> +            {siteUrl != null && (
やはりsiteUrlが空文字列の場合もアラートを表示するようにしました。

2022-07-29 07:12 UTC, merged