support: Create ReplayComments.tsx
weseek/growi pull request #6356
Opened 2022-07-27 01:49 UTC by jam411

対象チケット: https://redmine.weseek.co.jp/issues/101391

- ReplayComments の ts/FC 化.

2022-07-27 01:54 UTC, jam411 commented on packages/app/src/components/PageComment/ReplayComments.tsx
> +import { Comment } from './Comment';
以下のPRマージ後にeslintエラー解消される見込みです.
https://github.com/weseek/growi/pull/6279

2022-07-28 04:56 UTC, jam411 commented on packages/app/src/components/PageComment/ReplayComments.tsx
> +  }
isAllReplyShown は remark/rehype の設定と関係ないので RendererConfig には入れない見込み

2022-07-28 05:27 UTC, kaoritokashiki requested changes

2022-07-28 05:27 UTC, kaoritokashiki commented on packages/app/src/components/PageComment/ReplayComments.tsx
> +      <React.Fragment>
個人的に Fragment は省略記法を使ったほうがスッキリしてて好きです。

2022-07-28 05:27 UTC, kaoritokashiki commented on packages/app/src/components/PageComment/ReplayComments.tsx
> +  replyList: ICommentHasIdList,
元のコード、replyList optional になっているが、required で良さそうですね。
(つまり、このままでいいと思います。)

2022-07-28 09:02 UTC, merged