Imprv/101020 refactor sub nav skelton design
weseek/growi pull request #6360
Opened 2022-07-28 05:15 UTC by yukendev

https://redmine.weseek.co.jp/issues/101020

修正前
<img width="911" alt="スケルトン_修正前" src="https://user-images.githubusercontent.com/65263895/181425977-55546689-67c4-431a-b686-694df1c38689.PNG">

修正後
<img width="923" alt="スケルトン_修正版" src="https://user-images.githubusercontent.com/65263895/181424968-d84ee5f7-6ce8-40ca-b7f9-0d83f4862f2d.PNG">

mosさんのデザイン(https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/9eb054d4-99e1-4bbb-8e2d-3f98f04be5b1/)を参考にGrowiContextualSubNavigationのスケルトンのデザインを修正

2022-07-28 05:22 UTC, yukendev commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  );
`btn-like`などのクラスには高さのスタイルが当たっていたんですが、SubNavButtonsのクラスには高さが当たっていなかったので、SubNavButtonsのスケルトンクラスに`btn-like`を指定するのはよくないかと思い、直接高さ40を指定しました。

2022-07-28 05:24 UTC, yukendev commented on packages/app/src/components/Skelton.tsx
>    roundedPill?: boolean,
以前までは、表示されるコンポーネントをそのままスケルトンの高さにしていましたが、デザインの修正で、表示されるコンポーネントよりもスケルトンの高さを小さくしたい場合が出てきたので、新たに引数を追加しています。

2022-07-29 04:00 UTC, yuki-takei requested changes

2022-07-29 04:00 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  );
「btn-like の高さ」は scss で変わる。ということは、何らかの理由でそれを変えた時に、このスケルトンの高さも**一緒に変えやすい**のが理想。場所を工夫して。少なくとも scss 側にしたい。

btn-like を模したクラスを用意するというアイデアもあるし、SubNavButtons 向けの[高さ指定 placeholder](https://sass-lang.com/documentation/style-rules/placeholder-selectors)を作って、それをスケルトンと btn-like から @use するという手もある。

2022-07-29 04:00 UTC, yuki-takei commented on packages/app/src/components/Skelton.tsx
>    roundedPill?: boolean,
元に戻す

2022-08-01 04:26 UTC, yukendev commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  );
- SubNavButtonsのスタイル定義の中にスケルトンのスタイルを定義
- SubNavButtonsの高さをplaceholderで共通化
で対応しました

2022-08-01 04:26 UTC, yukendev commented on packages/app/src/components/Skelton.tsx
>    roundedPill?: boolean,
修正済み

2022-08-01 04:29 UTC, yukendev commented
ぴったりmosさんのデザイン通りにはなっていませんが、本来のコンポーネントよりもスケルトンが小さくなる部分に関しては、additionalClassにpy-1などを入れることで対応しています。

2022-08-01 07:57 UTC, yuki-takei requested changes

2022-08-01 07:57 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  );
GrowiContextualSubNavigation でスケルトンとの切り替えやっちゃうと、検索結果画面でロード中にスケルトン表示するシチュエーションに対応できないのでは。

2022-08-01 10:25 UTC, yukendev commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  );
スケルトンのスタイルを完全にcssに依存するようにしました

2022-08-01 11:15 UTC, merged