support: Update cc to fc sharelink
weseek/growi pull request #6362
Opened 2022-07-28 09:43 UTC by hirokei-camel

タスク：https://redmine.weseek.co.jp/issues/100966
TS化とSWR化はタスクを切って着手するつもりです！
レビューお願いします！

2022-07-28 10:20 UTC, hakumizuki requested changes

2022-07-28 10:20 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.jsx
> +  return <ShareLink {...props} />;
このラッパーいらないね

2022-07-28 10:20 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLinkList.tsx
> +            key={shareLink}
unique だったらこのままで OK だけど、map のコールバックの第二引数を使うと確実に unique にできる

2022-07-28 10:32 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLink.jsx
> +  return <ShareLink {...props} />;
クラスコンポーネントであるが故に記述していた箇所を忘れていました。。。
FCのラッパー削除完了しました！

2022-07-28 10:45 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLinkList.tsx
> +            key={shareLink}
keyにインデックスを追加する手段は、アンチパターンになっているようです！
下記のサイトに例が載っていました！
https://zenn.dev/luvmini511/articles/f7b22d93e9c182

なので、固有の値である_idに絞ってkeyを指定しました！

2022-07-29 05:34 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLinkList.tsx
> +            key={shareLink}
いい調査力だ！感動したぜ！

2022-07-29 05:38 UTC, hakumizuki requested changes

2022-07-29 05:38 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.jsx
> +  const retrieveShareLinks = useCallback(async() => {
`pageId` を引数にして `retrieveShareLinks` をFC の外に出そう

他の hooks の依存配列の変更も忘れずにね

2022-07-29 06:20 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLink.jsx
> +  const retrieveShareLinks = useCallback(async() => {
データフェッチとstateの更新があったので、swr化にて修正をすることになりました！

2022-07-29 07:19 UTC, merged