Imprv/101293 empty not found page
weseek/growi pull request #6363
Opened 2022-07-28 11:25 UTC by yukendev

https://redmine.weseek.co.jp/issues/101293

`isEmpty: true`のページにおけるNotFoundComponentを表示

2022-07-29 06:46 UTC, yukendev commented on packages/app/src/components/PageAlert/PageAlerts.tsx
> +        { !isEmpty && <FixPageGrantAlert /> }
<FixPageGrantAlert />の内部の権限確認のAPIでエラーが出て、swrによる再試行が何回も走ってしまうので、空ページの場合は<FixPageGrantAlert />をレンダリングしない実装にしました

2022-07-29 06:48 UTC, yukendev commented on packages/app/src/components/PageAlert/TrashPageAlert.tsx
> +  const lastUpdateUserName = pageData?.lastUpdateUser?.name;
空ページの場合にlastUpdateUserが存在せず、エラーになるのでオプショナルチェインで回避しています

2022-07-29 06:49 UTC, yukendev commented on packages/app/src/server/routes/apiv3/page.js
>      let pages;
空ページでuseSWRxCurrentPage()を呼んだ時に、fetcherでエラーが発生し、再試行が何回も走ってしまうので、空ページを許容するパラメーターを追加しました

2022-07-29 06:50 UTC, yukendev commented on packages/app/src/server/routes/apiv3/page.js
> +      // Empty page should not be related to grant API
空ページは権限関係のAPIに一切関与しないことの説明を追加しただけです

2022-07-29 06:51 UTC, yukendev commented on packages/app/src/server/service/page.ts
> +      page = await Page.findByPathAndViewer(path, user, null, true, includeEmpty);
includeEmptyの引数が正しく渡せていなかったので修正しました。四番目の引数のuseFindOneはデフォルトでtrueだったので、ここでもtrueを入れています

2022-07-29 06:52 UTC, yukendev commented on packages/app/src/stores/page.tsx
> +    (endpoint, pageId, shareLinkId) => apiv3Get<{ page: IPagePopulatedToShowRevision }>(
空ページの場合を考慮しています

2022-07-29 06:53 UTC, yukendev commented on packages/app/src/stores/ui.tsx
>    const { data: currentPageId } = useCurrentPageId();
Next化前まではpageId != nullだけで空ページじゃないことを判断できていましたが、Next化に伴って空ページもpageIdを持つようになったので、isEmptyフラグを追加しました

2022-07-29 06:54 UTC, yukendev commented on packages/app/src/stores/ui.tsx
> +  const key = `isAbleToShowPageManagement ${currentPageId}`;
ページ遷移したときに、前のページの値が返されえることを考慮して、keyにpageIdを含むようにしています

2022-07-29 07:46 UTC, yukendev commented on packages/app/src/pages/[[...path]].page.tsx
>    useEffect(() => {
パス名が日本語などだった場合window.location.pathnameがデコードされておらずとprops.currentPathnameが、一致せず無限ループが発生していたので、デコードを挟むことで日本語などのパスのリダイレクトに対応しました

2022-07-29 08:41 UTC, yuki-takei requested changes

2022-07-29 08:41 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/page.js
>      let pages;
未調査だけど、この変更はシステム全体への影響が大きそう。

クライアント側で例外処理すればいいだけでは？

2022-07-29 08:41 UTC, yuki-takei commented on packages/app/src/stores/context.tsx
> +};
IPageInfo から取得出来る情報のはず

2022-07-29 10:00 UTC, yukendev commented on packages/app/src/stores/context.tsx
> +};
isNotFoundでisEmptyの場合も考慮するような実装にして、useIsEmptyを削除しました

2022-08-02 08:05 UTC, yukendev commented on packages/app/src/components/Page/DisplaySwitcher.tsx
> +            { !isNotFound && (
空ページの場合もisNotFoundに含めました

2022-08-02 08:08 UTC, yukendev commented on packages/app/src/server/routes/apiv3/response.js
> +        return { message: e, status };
useSWRxPageでエラーハンドリングをする際に、ステータスコードが必要だったのでエラーの内容にステータスコードを追加しました

2022-08-02 08:10 UTC, yukendev commented on packages/app/src/stores/page.tsx
> +    },
notFoundのエラーが返ってきたときは、再検証をしないようにしました

2022-08-02 11:00 UTC, yuki-takei requested changes

2022-08-02 11:00 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    },
些細な違いだが、この SWR では status 403/404 の時は「エラーですらない」ように取り扱っていいように思う。
fetcher で Promise.catch 使えば null を返せるのでは？50x 系で飲み込まないように注意。

2022-08-02 11:00 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +  const key = `isAbleToShowPageManagement ${currentPageId}`;
- array にしてください
- notfound 状態のページが作成された場合に revalidate しなければいけないはずなので、キーに isNotFound も追加した方がいいんじゃないかな
- というか、isTrashPage, isSharedUser も入れるべきかどうかも検討して

2022-08-02 11:00 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +  const isPageExist = (pageId != null) && !isNotFound;
includesUndefined のチェックに isNotFound も含む必要がある。

2022-08-02 11:00 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +  const key = `isAbleToShowTagLabel ${currentPageId}`;
useIsAbleToShowPageManagement と同様の考慮を

2022-08-02 11:00 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +  const isPageExist = (currentPageId != null) && !isNotFound;
useIsAbleToShowPageManagement と同様の考慮を

2022-08-03 02:22 UTC, yukendev commented on packages/app/src/stores/ui.tsx
> +  const isPageExist = (pageId != null) && !isNotFound;
修正済み

2022-08-03 03:02 UTC, merged