support: Apply nextjs to CommentEditor
weseek/growi pull request #6365
Opened 2022-07-29 03:25 UTC by jam411

## 対象タスク
https://redmine.weseek.co.jp/issues/101393

## 概要
- PageComment配下のNext化ストーリのタスクです

**yukendevに特にみてほしいところ**
- CommentEditor.tsx

**kaoritokashikiに特にみてほしいところ**
- editorConfig 周り
- 以前コメントいただいたPR: https://github.com/weseek/growi/pull/6279

2022-07-29 03:43 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditor.tsx
> -    currentCommentId, commentBody, commentCreator, onCancelButtonClicked, onCommentButtonClicked,
commentCreator は putComment コンテナに渡されていました (参考https://github.com/weseek/growi/commit/f245aa89c010150adde5c7d17d83c2663af0068e)
ここでは使用されなくなったので commentCreator を削除しています

2022-07-29 03:44 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  }, [currentPagePath, markdown, rendererOptions]);
CommentPreviewコンポーネントでRevisionRendererにpropsを渡すので, 合わせて調整しました

2022-07-29 04:24 UTC, yukendev commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  }, [currentPagePath, markdown, rendererOptions]);
特に理由がなければ、propsでoptionを渡すのではなくてCommentPreviewの中でrendererOptionsをswrで取得した方が良いような気がします

2022-07-29 06:18 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditor.tsx
> +  }, [currentPagePath, markdown, rendererOptions]);
useCommentPreviewOptions() で取得する rendererOptions は PageCommentコンポーネントから子へpropsを渡すのではなく, CommentPreview で完結させるような方針で以下のPRも併せて全体を修正します
https://github.com/weseek/growi/pull/6279/files

2022-07-29 07:16 UTC, kaoritokashiki requested changes

2022-07-29 07:16 UTC, kaoritokashiki commented on packages/app/src/pages/[[...path]].page.tsx
> +  useEditorConfig(props.editorConfig);
`useEditorConfig(props.editorConfig);`
2回記述されていますね。どちらか片方削除お願いします。

2022-07-29 07:16 UTC, kaoritokashiki commented on packages/app/src/interfaces/editor-settings.ts
> +    file: any,
any はやめたい....です!

2022-07-29 08:45 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +  useEditorConfig(props.editorConfig);
修正ずみ

2022-07-29 08:58 UTC, jam411 commented on packages/app/src/interfaces/editor-settings.ts
> +    file: any,
booleanに修正しました

2022-08-01 07:19 UTC, kaoritokashiki approved these changes

2022-08-01 07:22 UTC, kaoritokashiki commented on packages/app/src/interfaces/editor-settings.ts
> +    file: any,
この変数名、bool って感じじゃないので後続でもいいから変えたいですよね....。というぼやきです。

2022-08-01 07:25 UTC, merged