Imprv/101156 delete unused code related to theme preview and custom bar editor
weseek/growi pull request #6366
Opened 2022-07-29 04:24 UTC by kaoritokashiki

## Task
[GROWI][Next.js][Admin][Customize] 各種設定の更新ができる
┗[101156](https://redmine.weseek.co.jp/issues/101156) テーマのプレビュー機能、CustomHogeEditorの削除に伴い不要になったコードを削除 & themeが更新されないbug 修正

## Description
- package "jquery-ui` の削除
- adminCustomizeContainer での theme 関連のstate method を削除
- AdminLayout にて Provider でinject adminContainers

## ScreenRecording (latest)

https://user-images.githubusercontent.com/59536731/182072980-7e2ce721-616b-4e86-a250-74d0f7de322c.mov

## Note
CustomizeContainer 以外の UnstatedContainers の インスタンスの有効化は　https://redmine.weseek.co.jp/issues/101816 のタスクで行います。

2022-07-29 05:02 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Customize/CustomizeThemeOptions.jsx
> +    mutateGrowiTheme(themeName, false);
## 元の書き方(preview されない)
`mutate()` を実行せず `adminCustomizeContainer.switchThemeType`

## 新しい書き方 (previewされる)
この書き方だと更新したいテーマを2回押さないと`adminCustomizeContainer`のstate `currentTheme`が変更されないという現象が起きています。

そもそも`switchThemeType` は使わないほうがいいとかあったりしますでしょうか?


https://github.com/weseek/growi/pull/6343/files#r932864816

2022-07-29 05:15 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Customize/CustomizeThemeOptions.jsx
> +
`switchThemeType`は不要するつもりでいましたが、テーマの更新のために必要であったことがわかったので復活させました。ただ、そこで問題が生じたので相談したいです↓。

## 元の書き方(テーマ選択時にpreview されない)
`mutate()` を実行せず `adminCustomizeContainer.switchThemeType()` のみを行う
┗更新ボタンを押したときに正常にテーマが更新できていることを確認できる

## 新しい書き方 (テーマ選択時にpreviewされる)

この書き方だと更新したいテーマを2回押さないと`adminCustomizeContainer`のstate `currentTheme`が変更されないため、previewは切り替わるが更新ボタンを押してもテーマが変更されないという現象が起きています。

そもそも`switchThemeType` は使わないほうがいいとかあったりしますでしょうか?

## Memo
-  [前回のPR](https://github.com/weseek/growi/pull/6343/files#r932864816)

## ScreenRecording
### 1回目
blackboard を1回クリック -> 更新 -> リロード -> default テーマに設定されている
### 2回目
blackboard を2回クリック(blackboald の文字が太くなっており `isSelected` 状態になっていることを確認) -> リロード- > blackboardテーマに設定されている
 
https://user-images.githubusercontent.com/59536731/181687081-98a187bf-8c91-41d0-80ea-d970543342b6.mov

mutateの知識不足...?

2022-07-29 06:51 UTC, yuki-takei requested changes

2022-07-29 06:51 UTC, yuki-takei commented on packages/app/src/components/Admin/Customize/CustomizeThemeOptions.jsx
> +
> mutateの知識不足...?

のような気がしますね。
`mutateGrowiTheme(themeName, false);` はなぜ revalidate しないの？

2022-07-31 22:07 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Customize/CustomizeThemeSetting.tsx
> +    </div>
- React.Fragment: 不要だったので削除
- CustomizeThemeOptions に props `onSelected` と `currentTheme` を追加しました。

2022-08-01 03:48 UTC, kaoritokashiki commented on packages/app/src/server/views/admin/customize.html
> -{% endblock %}
Customize で　コードミラーを使わずtextarea を使うようになったので削除しました。

2022-08-01 07:46 UTC, kaoritokashiki commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +  ];
インスタンスの有効化は　https://redmine.weseek.co.jp/issues/101816 のタスクで行います。

2022-08-01 08:01 UTC, merged