support: Rendering PageContentFooter
weseek/growi pull request #6367
Opened 2022-07-29 05:42 UTC by jam411

対象タスク: https://redmine.weseek.co.jp/issues/100393

## 概要

- PageContentFooter のレンダリング
- Skelton 表示
- hooks の作成

![wideview](https://user-images.githubusercontent.com/68407388/181688519-1108f170-5762-4a3f-9a3e-60a6730c8fca.gif)

2022-07-29 05:48 UTC, jam411 commented on packages/app/src/components/PageContentFooter.tsx
> +  const AuthorInfo = dynamic(() => import('./Navbar/AuthorInfo'), { ssr: false, loading: () => <p><Skelton width={300} height={20} /></p> });
dynamicインポートとSkelton表示
段落表示にするため<p>タグでくくっています

2022-07-29 06:27 UTC, kaoritokashiki requested changes

2022-07-29 06:27 UTC, kaoritokashiki commented on packages/app/src/components/PageContentFooter.tsx
> +  const { data: revisionAuthor } = useRevisionAuthor();
これらの情報、page が既に持ってるようなので swr を新規に定義しなくても良さそうです。
GrowiContextualSubNavigationを参考にするといいと思います

2022-07-29 06:27 UTC, kaoritokashiki commented on packages/app/src/components/PageContentFooter.tsx
> +  const AuthorInfo = dynamic(() => import('./Navbar/AuthorInfo'), { ssr: false, loading: () => <p><Skelton width={300} height={20} /></p> });
pタグで囲うのではなく additionalClass で対応できたりしないですかね??

2022-07-29 07:35 UTC, jam411 commented on packages/app/src/components/PageContentFooter.tsx
> +  const { data: revisionAuthor } = useRevisionAuthor();
useSWRxCurrentPage() で page をとるように修正しました. 現状はPageContentFooterが[[...path]].page.tsx の次のコンポーネントになるので自律的に取得するようにしています.

2022-07-29 07:35 UTC, jam411 commented on packages/app/src/components/PageContentFooter.tsx
> +  const AuthorInfo = dynamic(() => import('./Navbar/AuthorInfo'), { ssr: false, loading: () => <p><Skelton width={300} height={20} /></p> });
`mb-3`に修正しました. (AuthorInfo と同じ高さでmerginとれたため)

2022-07-29 07:42 UTC, jam411 commented
## FB修正後
![wideview](https://user-images.githubusercontent.com/68407388/181709726-da39a632-71ba-4878-8c5c-5d313e92650d.gif)

2022-08-01 06:48 UTC, kaoritokashiki requested changes

2022-08-01 06:48 UTC, kaoritokashiki commented on packages/app/src/stores/context.tsx
> +export const useIsAllReplyShown = (initialData?: boolean): SWRResponse<boolean, any> => {
```suggestion
export const useIsAllReplyShown = (initialData?: boolean): SWRResponse<boolean, Error> => {
```
で良さそうです。

2022-08-01 06:52 UTC, jam411 commented on packages/app/src/stores/context.tsx
> +export const useIsAllReplyShown = (initialData?: boolean): SWRResponse<boolean, any> => {
修正しました

2022-08-01 06:56 UTC, merged