support: Created NoLoginLayout file and eliminate login from import
weseek/growi pull request #6373
Opened 2022-07-29 10:37 UTC by Shunm634-source

2022-08-04 11:40 UTC, yuki-takei requested changes

2022-08-04 11:40 UTC, yuki-takei commented on packages/app/src/components/Layout/NoLoginLayout.tsx
> +import styles from './Installer.module.scss';
NoLoginLayout.module.scss を作って。共用のスタイルはそこへ。
Installer.module.scss (InstallerForm.modulescss でもいいけど)はインストーラー専用のスタイルのみ、Login.module.scss はログイン画面専用のスタイルのみを入れる。

2022-08-04 11:42 UTC, yuki-takei requested changes

2022-08-04 11:42 UTC, yuki-takei commented on packages/app/src/components/Layout/Installer.module.scss
> +        }
ここより上の行までは共用のはず

2022-08-04 11:42 UTC, yuki-takei commented on packages/app/src/components/Layout/Installer.module.scss
> +        }
ここはログイン画面のみだよねきっと。
共用してるんだとしたらクラス名が悪い。

2022-08-04 11:42 UTC, yuki-takei commented on packages/app/src/components/Layout/Installer.module.scss
> +        }
以下の行も同様の観点で仕分けを。

2022-08-05 06:26 UTC, Shunm634-source commented on packages/app/src/components/Layout/NoLoginLayout.tsx
> +import styles from './Installer.module.scss';
Installerページ固有のスタイルはないと判断したので、NoLogin.module.scssとLogin.module.scssに分けて実装しました。
LoginとInstaller両方とも動作確認済み。

2022-08-05 06:27 UTC, Shunm634-source commented on packages/app/src/components/Layout/Installer.module.scss
> +        }
上記の通り仕分け済み。

2022-08-05 11:57 UTC, yuki-takei requested changes

2022-08-05 11:57 UTC, yuki-takei commented on packages/app/src/styles/theme/_apply-colors-dark.scss
> +  .noLogin-dialog {
このファイルはOK

2022-08-05 11:57 UTC, yuki-takei commented on packages/app/src/styles/theme/_apply-colors-light.scss
> +  .noLogin-dialog {
このファイルはOK

2022-08-05 11:57 UTC, yuki-takei commented on packages/app/src/components/Theme/ThemeWood.module.scss
> +    .noLogin-dialog {
このファイルとテーマ関係の scss ファイルはこれでOK

2022-08-05 11:57 UTC, yuki-takei commented on packages/app/src/components/Layout/Installer.module.scss
> +.nologin :global {
このクラス名は名前が悪い。`.installer` にして。
あとこの scss はどこから使われているの？

2022-08-05 11:57 UTC, yuki-takei commented on packages/app/src/components/Layout/Installer.module.scss
> +  .login-header {
名前が悪い

2022-08-05 11:57 UTC, yuki-takei commented on packages/app/src/components/Layout/Login.module.scss
> +.invited,
invited はまた別の scss では？

2022-08-05 11:57 UTC, yuki-takei commented on packages/app/src/components/Layout/Login.module.scss
> +}
Installer.module.scss にも重複のクラスがある。

2022-08-09 07:36 UTC, Shunm634-source commented on packages/app/src/components/Layout/Installer.module.scss
> +.nologin :global {
Installer.page.moduke自体削除ずみ。

2022-08-09 07:36 UTC, Shunm634-source commented on packages/app/src/components/Layout/Installer.module.scss
> +  .login-header {
同上

2022-08-09 07:36 UTC, Shunm634-source commented on packages/app/src/components/Layout/Login.module.scss
> +.invited,
Invited.module.scssを新たに作成してそちらに移行。

2022-08-09 07:36 UTC, Shunm634-source commented on packages/app/src/components/Layout/Login.module.scss
> +}
Installer.module.scss自体を削除ずみ

2022-08-10 04:28 UTC, jam411 commented
- [ ] CIエラーが出ているので、最新の support/apply-nextjs-2 を取り込むなどして解消してください.

- [ ] 現状で分かっている範囲でいいので、このPRでスコープ外とした、ストーリ完了するまでに必要な後続タスクを切ってください. (CSS適用,_login.scssの削除など?).
ただ、このPRのスコープは_login.scssのモジュール化と分割だと思うから_login.scssの削除と各tsx/jsxファイルのでSCSSモジュールインポートまではやったほうがいいかな
このPRでやらずに後続タスクでやったほうがいい理由があったりスコープが大きくなりすぎそうなら ~~は後続タスクで取り組みますの記載をする(参考: https://github.com/weseek/growi-docs/pull/311)

- [ ] できればだけどスタイルが変わるような実装はBefore/Afterで提示してくれるとなおわかりやすいです.(参考:https://github.com/weseek/growi/pull/6446)

2022-08-12 07:15 UTC, jam411 requested changes

2022-08-12 07:15 UTC, jam411 commented on packages/app/src/components/Layout/Invited.module.scss
> +.nologin.error {
これは installer や login でもあり得るから NoLoginLayout.module.scss でいい気がします.　

2022-08-12 09:08 UTC, Shunm634-source commented on packages/app/src/components/Layout/NoLoginLayout.module.scss
> +  // }
移動済み。

2022-08-18 06:14 UTC, Shunm634-source commented on packages/app/src/components/Layout/Invited.module.scss
> +.nologin.error {
移動済み。

2022-08-18 06:15 UTC, Shunm634-source commented on packages/app/src/components/Layout/Login.module.scss
> +  }
移動済み。

2022-08-18 06:17 UTC, Shunm634-source commented on packages/app/src/pages/installer.page.tsx
> -                      <div className="logo"></div>
NoLoginLayout.tsxファイルにてすでに修正済み。

2022-08-18 10:24 UTC, merged