support: Rendering CommentEditorLazyRenderer
weseek/growi pull request #6381
Opened 2022-08-01 04:15 UTC by jam411

対象タスク: https://redmine.weseek.co.jp/issues/101432

- CommentEditorLazyRenderer.tsx のレンダリング

2022-08-01 07:48 UTC, jam411 commented on packages/app/src/interfaces/editor-settings.ts
> +    isFileUploaded: boolean,
参考PR: https://github.com/weseek/growi/pull/6365/files/1ea2b91b48079e02170a0f709d9daa9f8e0a0e93#diff-505a2d3d5baf95cf230b686911957ac6aba297322203f8046f8b093f8fdb533e

2022-08-01 07:52 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditorLazyRenderer.tsx
> +  const { data: pageId } = useCurrentPageId();
自律的に取得するようにしています。

2022-08-02 06:04 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +          <PageComment isReadOnly={false} titleAlign="left" />
memo化のため今の設計ではpageIdはpropsで渡す必要がありました。次のタスクで取り組みます。

2022-08-02 06:05 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +          <CommentEditorLazyRenderer />
こちらのコンポーネントは PageComment 配下で呼び出す必要がありました。こちらも次のタスクで取り組みます。

2022-08-03 04:22 UTC, jam411 commented on packages/app/src/components/PageComment/ReplayComments.tsx
>  export const ReplayComments = (props: ReplaycommentsProps): JSX.Element => {
そもそもこのファイル名は ReplyComments が良いので後続タスクで修正します。

2022-08-03 04:25 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditorLazyRenderer.tsx
> +  const { data: pageId } = useCurrentPageId();
こちら自律的に取得するとページ遷移時に更新されないのですが、現状通りpropsで渡すと問題なく更新されるので、後続タスクでpageIdはpropsで渡すようにします。
親コンポーネントになるPageComment.tsxも同様に。

2022-08-03 06:03 UTC, kaoritokashiki requested changes

2022-08-03 06:41 UTC, jam411 commented on packages/app/src/interfaces/editor-settings.ts
> +    isFileUploaded: boolean,
useUploadableImage と useUploadableFile を使うように修正しました

2022-08-03 06:48 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditorLazyRenderer.tsx
> +  const { data: pageId } = useCurrentPageId();
修正済み

2022-08-03 06:48 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +          <PageComment isReadOnly={false} titleAlign="left" />
修正済み

2022-08-03 06:48 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +          <CommentEditorLazyRenderer />
修正済み

2022-08-03 06:48 UTC, jam411 commented on packages/app/src/components/PageComment/ReplayComments.tsx
>  export const ReplayComments = (props: ReplaycommentsProps): JSX.Element => {
修正済み

2022-08-03 08:00 UTC, yuki-takei requested changes

2022-08-03 09:52 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> -  };
editorConfigを定義しなおしました。

2022-08-03 09:52 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +  useIsUploadableImage(props.editorConfig.upload.isUploadableImage);
初期化

2022-08-03 10:00 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.tsx
> +  const deleteBtnClickedHandler = () => {
引数は必要なし。修正

2022-08-03 10:21 UTC, merged