support: Update fc exportarchivedatepage
weseek/growi pull request #6390
Opened 2022-08-02 04:50 UTC by hirokei-camel

タスク：https://redmine.weseek.co.jp/issues/100083
7月Users Meetupの準備のためのタスクです。レビューお願いします！

2022-08-02 08:12 UTC, hakumizuki requested changes

2022-08-02 08:12 UTC, hakumizuki commented on packages/app/src/components/Admin/ExportArchiveDataPage.jsx
> +  }, [setupWebsocketEventHandler, cleanupWebsocketEventHandler]);
`setupWebsocketEventHandler` と `cleanupWebsocketEventHandler` は `socket` を引数で取るようにして、ここを socket に依存させた方がいいかなあ

そうすると、Handler の責務も小さくできるし、Handler 自体をコンポーネントの外に出せるし、メモ化のコストも低くなる

2022-08-02 08:12 UTC, hakumizuki commented on packages/app/src/components/Admin/ExportArchiveDataPage.jsx
> +        onClose={() => closeExportModal()}
これってなんで wrap してるの？

2022-08-03 07:51 UTC, closed without merging

2022-08-08 08:15 UTC, hakumizuki commented on packages/app/src/components/Admin/ExportArchiveDataPage.jsx
> +  }, [setupWebsocketEventHandler, cleanupWebsocketEventHandler]);
>handlerを関数コンポーネントの外に持っていくのは、SWR化にて取り組みます！

外に出すのは今でもできるから今やろう

2022-08-09 01:55 UTC, hirokei-camel commented on packages/app/src/components/Admin/ExportArchiveDataPage.jsx
> +  }, [setupWebsocketEventHandler, cleanupWebsocketEventHandler]);
あ、そうでしたか。。。
了解しました、修正します！