support: Update sharelink use swr
weseek/growi pull request #6400
Opened 2022-08-03 08:52 UTC by hirokei-camel

タスク：https://redmine.weseek.co.jp/issues/101565
ブランチ関係でトラブってしまったので、新しく作成しました
前PR：https://github.com/weseek/growi/pull/6385

2022-08-18 03:35 UTC, hakumizuki requested changes

2022-08-18 03:35 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +  const { data, isValidating, mutate } = useSWR('/share-links/', (endpoint => fetchShareLinks(endpoint, currentPageId)));
SWR hooks は /stores/ に書こう

isValidating を使ってる理由はなんですか？

2022-08-18 03:35 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +  const res = await apiv3Get(endpoint, { relatedPage: pageId });
型が動いてなさそう。あと、pageId をキーに入れないとページ遷移した後に結果が変わらないからバグりそうだね

2022-08-18 03:35 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +        <button className="btn btn-danger ml-auto " type="button" onClick={() => deleteAllLinksButtonHandler(currentPageId)}>{t('delete_all')}</button>
ここで関数作られちゃったら useCallback した意味なくなっちゃうのでこれは元の実装でよいです

2022-08-25 06:34 UTC, hakumizuki requested changes

2022-08-25 06:34 UTC, hakumizuki commented on packages/app/src/stores/sharelink.tsx
> +import useSWR, { SWRResponse } from 'swr';
このファイル名は share-link.tsx にしよう

2022-08-25 06:34 UTC, hakumizuki commented on packages/app/src/stores/sharelink.tsx
> +  return useSWR('/share-links/', (endpoint => fetchShareLinks(endpoint, currentPageId)));
key に currentPageId 含めないとだね。前に Slack で言ってたのこのことだったわ。コメントつける位置間違えただけだった

2022-08-25 06:34 UTC, hakumizuki commented on packages/app/src/stores/sharelink.tsx
> +const fetchShareLinks = async(endpoint, pageId): Promise<IResShareLinkList['shareLinksResult']> => {
これちゃんと型動いてたら返り値の型は推論されるから省略してもいいかも

2022-08-25 06:34 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +          shareLinks={!data ? [] : data}
null check 使ってください

2022-08-25 06:34 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +  const { data: pageId } = useCurrentPageId();
名前 currentPageId のままでいいと思うよ

2022-08-25 06:34 UTC, hakumizuki commented on packages/app/src/stores/sharelink.tsx
> +  return useSWR('/share-links/', (endpoint => fetchShareLinks(endpoint, currentPageId)));
あとこれ currentPageId は外に出そう。pageId を受け取ってそれに応じて fetch したりしなかったりする方が汎用的だし、名前にあってる

2022-08-25 09:56 UTC, hirokei-camel commented on packages/app/src/stores/sharelink.tsx
> +import useSWR, { SWRResponse } from 'swr';
了解です！完了しました！

2022-08-25 10:21 UTC, hirokei-camel commented on packages/app/src/stores/sharelink.tsx
> +  return useSWR('/share-links/', (endpoint => fetchShareLinks(endpoint, currentPageId)));
なるほど！
引数にcurrentPageIdを含めれば同じ処理が省略できますね！

修正完了しました！

2022-08-26 01:40 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +  const { data: pageId } = useCurrentPageId();
了解です、統一した方が良かったですね。
修正完了しました！

2022-08-26 02:01 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +          shareLinks={!data ? [] : data}
統一するの忘れていました。。。
修正完了しました！

2022-08-26 02:07 UTC, hirokei-camel commented on packages/app/src/stores/sharelink.tsx
> +const fetchShareLinks = async(endpoint, pageId): Promise<IResShareLinkList['shareLinksResult']> => {
apiv3Getを実行している段階で型指定をしているので、fetchShareLinksの返り値まで型指定をする必要が無いってことですね！
最終的にPromise<any[]>と推論されているのですが、Promise<IResShareLinkList['shareLinksResult']> と推論されるべきなのではないでしょうか？

2022-08-26 02:51 UTC, hirokei-camel commented on packages/app/src/stores/sharelink.tsx
> +const fetchShareLinks = async(endpoint, pageId): Promise<IResShareLinkList['shareLinksResult']> => {
理解しました💦
定義した型の中のany[]が推論されるという意味ですね！

2022-08-26 08:06 UTC, hakumizuki requested changes

2022-08-26 08:06 UTC, hakumizuki commented on packages/app/src/stores/share-link.tsx
> +  return useSWR(['/share-links/', currentPageId], ((endpoint) => {
key の部分を `currentPageId == null ? null : ['/share-links/', currentPageId]` にしたほうがいいね

で、

```typescript:example.ts
if (currentPageId == null) {
      return [];
    }
```

は不要

2022-08-26 08:06 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +  const { data, mutate } = useSWRxSharelink(currentPageId);
data => currentShareLinks にしよう

2022-08-26 09:46 UTC, hirokei-camel commented on packages/app/src/stores/share-link.tsx
> +  return useSWR(['/share-links/', currentPageId], ((endpoint) => {
了解です！
完了しました！

2022-08-26 09:47 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +  const { data, mutate } = useSWRxSharelink(currentPageId);
修正完了しました！

2022-08-26 09:51 UTC, merged