imprv: show external-accounts page
weseek/growi pull request #6401
Opened 2022-08-03 09:12 UTC by kaoritokashiki

2022-08-03 09:58 UTC, kaoritokashiki commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +  }
`admin/users/external-accounts` にページ遷移したとき、
router.query.path には ['users', 'external-accounts'] が入ります。

2022-08-03 10:05 UTC, kaoritokashiki commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +    name = path[1] || path[0];
現状、path (配列)に３つ以上の値が入ることはないので、これで正常に動きますが、もしかしたら他にもっといい方法があるかもしれません。

2022-08-03 10:15 UTC, yuki-takei requested changes

2022-08-03 10:15 UTC, yuki-takei commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +    name = path[1] || path[0];
path を分解するのではなくて、adminPagesMap のキーを path 通りにしたらだめかな？

2022-08-04 06:26 UTC, kaoritokashiki commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +  };
jsのreduceを使って実現しました

https://github.com/weseek/growi/pull/6401#discussion_r936490094

2022-08-05 11:35 UTC, merged