support: isLoading PageComment
weseek/growi pull request #6415
Opened 2022-08-04 06:05 UTC by jam411

タスク：

2022-08-04 06:10 UTC, jam411 commented on packages/app/src/components/PageComment.tsx
> +    }
hideIfEmpty が true な時は comments?.length によって comment が表示されない場合があるので空を返しています

2022-08-04 06:33 UTC, jam411 commented on packages/app/src/components/PageComment.tsx
> +  if (commentsFromOldest == null || commentsExceptReply == null || rendererOptions == null || currentPagePath == null || currentPage == null) {
リストとevery()メソッドを使おうと思いましたが、props undefined で lintエラーがでるのでそのまま記載しています。

2022-08-04 11:37 UTC, yuki-takei commented
loading spinner よりは、スケルトン(1,2件のコメントを表す矩形)がいいと思う

2022-08-08 03:38 UTC, jam411 commented
- 矩形表示に変更しました。
## gif

![PageComment_Skelton](https://user-images.githubusercontent.com/68407388/183333532-c143143c-c643-4626-885a-7c69fe04bbae.gif)

## png

![image](https://user-images.githubusercontent.com/68407388/183333507-dd08ab5e-762e-498c-b42c-27ca801b27be.png)

![image](https://user-images.githubusercontent.com/68407388/183333445-0877e110-84cd-4c35-ab82-aebbe19741a4.png)

2022-08-08 03:54 UTC, jam411 commented
## CommentEditorLazyRenderer のスケルトンのみ
## gif
![PageComment_Skelton](https://user-images.githubusercontent.com/68407388/183335661-5824a685-9e69-4410-b12b-15c3d640baab.gif)

2022-08-09 14:38 UTC, yuki-takei commented
個数は気にしなくてよい。

https://user-images.githubusercontent.com/68407388/183334555-da2db9f3-9f13-4cd8-830a-fa9e6714540e.png

この見た目(のできればもうちょっと洗練されたやつ)にしてほしい。

2022-08-09 14:42 UTC, yuki-takei requested changes

2022-08-09 14:42 UTC, yuki-takei commented on packages/app/src/components/PageComment.module.scss
> +}
このマジックナンバーだらけの指定は NG

2022-08-18 01:56 UTC, jam411 commented
・Skeltonのデザインを修正しました.
・リファクタリングする必要があるのでマージはまだできません

![PageComment_Skelton_C_1](https://user-images.githubusercontent.com/68407388/185275011-79d2e6c7-7c5d-4225-a401-17be4238c709.gif)

2022-08-18 02:22 UTC, jam411 commented on packages/app/src/components/PageComment.module.scss
> +}
時間がかかりそうなので以下タスクで取り組みます
https://redmine.weseek.co.jp/issues/102651

2022-08-18 13:31 UTC, kaoritokashiki approved these changes

2022-08-18 13:32 UTC, merged