support: Scss module import for PageComments
weseek/growi pull request #6416
Opened 2022-08-04 06:58 UTC by jam411

タスク：[100552](https://redmine.weseek.co.jp/issues/100552)

- PageComment.tsx から Editor までの SCSS module 適用

2022-08-05 05:59 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditor.module.scss
> +    // }
_comment_growi.scss から、どこにも使用されてないクラス

2022-08-05 05:59 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditor.module.scss
> +    // }
_comment_growi.scss から、どこにも使用されてないクラス

2022-08-05 06:02 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.module.scss
> +}
_comment_growi.scss から、どこにも使用されてないクラス
.page-commentは共通のクラスがあり `pointer-events: none;` のみ移動 (.page-comment は .growi クラス配下でなく .page-comments クラス配下の場合がないと考えたから)

2022-08-05 06:04 UTC, jam411 commented on packages/app/src/styles/_comment.scss
>  }
Modal 用のクラスだけ 他と共有のため
[102028](https://redmine.weseek.co.jp/issues/102028)で取り組みます

2022-08-05 06:22 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.module.scss
> +      }
CommentControl.tsx でインポートすると `Missing whitespace before :global`.
上位クラスを作る場合、上位タグが Comment.tsx 内のタグになるため.
現状はCommentControlはCommentからしか使用されておらず, CommentControl.tsx にコメント記載.

2022-08-05 06:25 UTC, jam411 commented on packages/app/src/styles/_comment.scss
>    }
.page-commentは _comment.scss と _comment_growi.scss にあり pointer-events: none; のみ移動 (.page-comment は .growi クラス配下でなく .page-comments クラス配下かその逆の場合がないと考えたから)

2022-08-05 11:39 UTC, yuki-takei requested changes

2022-08-05 11:39 UTC, yuki-takei commented on packages/app/src/components/PageComment/Comment.module.scss
> +    // ユーザー名
日本語NGです

2022-08-08 00:40 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.module.scss
> +    // ユーザー名
修正しました。

2022-08-08 00:48 UTC, merged