Imprv/101883 show user management detail page
weseek/growi pull request #6418
Opened 2022-08-04 07:11 UTC by kaoritokashiki

2022-08-05 11:47 UTC, yuki-takei requested changes

2022-08-05 11:47 UTC, yuki-takei commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +import UserGroupTable from '../UserGroup/UserGroupTable';
SSR 時点で表示する必要のないものは dynamic import にしていいんじゃないかな。

2022-08-05 11:47 UTC, yuki-takei commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +  }
あんまり綺麗じゃないなあ。
`pagePathKeys[1]` が valid ObjectId であるという保証がない。

正規表現にするとか、bson-objectid の isValid を使うとかを検討してください。

2022-08-05 11:47 UTC, yuki-takei commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  }, [userGroup]);
SWR と local state の二重管理する必要ある？

2022-08-05 11:49 UTC, yuki-takei requested changes

2022-08-05 11:49 UTC, yuki-takei commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  const { userGroupId: currentUserGroupId } = props;
props から ID を得るのはいいと思うんだけど、コード中で `currentUserGroup._id` を参照している箇所もある。統一して。

2022-08-08 05:29 UTC, kaoritokashiki commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  const { userGroupId: currentUserGroupId } = props;
すみません、`currentUserGroupId` に統一しました。

2022-08-08 05:29 UTC, kaoritokashiki commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  }, [userGroup]);
なかったので、削除しました。

2022-08-08 19:26 UTC, kaoritokashiki commented
余計な差分が入ってしまったので https://github.com/weseek/growi/pull/6441 を新規作成

2022-08-08 19:26 UTC, closed without merging