support: Update js to ts
weseek/growi pull request #6434
Opened 2022-08-08 03:12 UTC by hirokei-camel

タスク：https://redmine.weseek.co.jp/issues/101564

2022-08-08 04:16 UTC, hirokei-camel commented
すみませんReviewer追加してませんでした。。。

2022-08-08 04:18 UTC, hakumizuki requested changes

2022-08-08 04:18 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +type ShareLinkItemType = {
この型は結局 `shareLinksResult` の型だと思うんだけど、その場合は src/interface/share-link.ts に `IResShareLinkList` 的な名前でレスポンスの型を作っておくとバックエンドフロントエンドで共通の型が使えて良いです。

ただし今はまだ ShareLink ドキュメントの汎用的な型がないので、ShareLink ドキュメントの型は `any` で妥協しておいて良いです。any で妥協する場合は `// TODO: TypeScriptize ShareLink model` の様なコメントを書いておいてください。

型をつける姿勢はとてもいいと思います。

2022-08-08 04:18 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
>    const { pageId } = pageContainer.state;
この2行は useCurrentPageId で置き換えられると思うのでそうしましょう。で、PageContainer を排除しましょう。

2022-08-08 08:32 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLink.tsx
>    const { pageId } = pageContainer.state;
useCurrentPageIdへの置き換えは、SWR化タスクにて取り組むようにしても良いですか？
ソースコードに自分用のコメントアウトを残してはいけないと考えたので、このことに関しては注釈を追記しませんでした！

2022-08-08 09:02 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +type ShareLinkItemType = {
なるほど、interfaces下に新しく型定義をするのが正解だったのですね！
とりあえずあたらしくファイルを生成し、型定義はanyに省略しました！

2022-08-08 10:13 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
>    const { pageId } = pageContainer.state;
コードに TODO コメント残していいよ。タスクへのリンクとかあるといいと思う。あと英語でね

2022-08-08 10:20 UTC, hakumizuki requested changes

2022-08-08 10:20 UTC, hakumizuki commented on packages/app/src/interfaces/share-link.ts
> +export type IResShareLinkList = any[];
こうかな。で、apiGet のジェネリクスに渡してちゃんと型が動く様にしよう

```typescript
export type IResShareLinkList = {
    shareLinksResult: any[],
};
```

2022-08-08 10:20 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
>      try {
res の型が any とかになっていたら IRes を作った意味が薄れてしまうよ

2022-08-08 10:20 UTC, hakumizuki commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +const ShareLink: FC<Props> = (props: Props): JSX.Element => {
FC っていう型定義不要かな。貼ったリンク読んでみて

https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/

2022-08-09 01:00 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLink.tsx
>    const { pageId } = pageContainer.state;
了解です！
WSR化にて取り組む旨を追記します！

2022-08-09 01:01 UTC, hirokei-camel commented on packages/app/src/interfaces/share-link.ts
> +export type IResShareLinkList = any[];
あ、なるほど。
shareLinkResultは必要でしたね💦
ありがとうございます！

2022-08-09 01:03 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLink.tsx
>      try {
確かに、妥協するとは言っても必要な要素はありましたね！
shareLinkResultの型をanyにするよう修正します！

2022-08-09 01:09 UTC, hirokei-camel commented on packages/app/src/components/ShareLink/ShareLink.tsx
> +const ShareLink: FC<Props> = (props: Props): JSX.Element => {
propsの型指定は引数の中だけで書くべきだったのですね！
了解です！

2022-08-09 04:50 UTC, merged