Imprv: make PageEditorByHackmd.jsx fc
weseek/growi pull request #6436
Opened 2022-08-08 07:40 UTC by Kami-jo

[98189](https://redmine.weseek.co.jp/issues/98189) Editor周りのFC/TS化
┗ [98451](https://redmine.weseek.co.jp/issues/98451) PageEditorByHackmd.jsxのFC化

2022-08-08 09:50 UTC, yukendev requested changes
useCallback付ける意識はとてもいい。おそらく何個か付け忘れてるので、基本全部つけるように

2022-08-08 09:50 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.jsx
>     */
useCallbackを使おう

2022-08-08 09:50 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.jsx
> -                    disabled={this.state.isInitializing}
ここら辺のアロー関数はreturnを省略できそう

2022-08-08 09:50 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.jsx
>  export default PageEditorByHackmdWrapper;
default export は積極的にnamed exportにしていきたい（TS化のタスクでも大丈夫）

2022-08-08 09:50 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.jsx
> +  const penpalErrorOccuredHandler = (error) => {
useCallbackを使おう

2022-08-08 09:50 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.jsx
> +  const renderPreInitContent = () => {
useCallbackを使おう

2022-08-08 09:57 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.jsx
>  export default PageEditorByHackmdWrapper;
いや、やっぱcontainerはがさない限りwrapperがあってやりづらそうだから、containerはがすタスクで俺がやります

2022-08-08 13:02 UTC, yuki-takei requested changes

2022-08-08 13:02 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.jsx
> +  }, [pageContainer]);
deps に pageContainer 全体を入れるのは避ける

2022-08-08 13:02 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.jsx
> +  }, [pageContainer.state]);
deps に pageContainer.state 全体を入れるのは避ける

2022-08-08 13:02 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.jsx
> +  }, [editorContainer, editorMode, grant, grantGroupId, grantGroupName, isSlackEnabled, pageContainer, pageTags, slackChannels]);
ここの deps も大きなオブジェクトをそのまま入れないようにする

2022-08-08 13:02 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.jsx
> +  }, [pageContainer, t]);
ここの deps も大きなオブジェクトをそのまま入れないようにする
`t` はOK

2022-08-08 13:02 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.jsx
> +                    onClick={() => { resumeToEdit() }}
ここ closure をわざわざ作る必要なさそう。
以降も同じような箇所があるので変更して。

2022-08-22 12:17 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.jsx
> +  }, [appContainer, isInitialized, t]);
修正済み

2022-08-22 12:18 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.jsx
> +                    onClick={() => { resumeToEdit() }}
修正済み

2022-08-22 12:21 UTC, yukendev commented
useCallbackなどの依存関係にappContainerなどの大きいオブジェクトが入っているのは修正していませんが、すぐにcontainerが排除されて消されるので今回はスルーでお願いします

2022-08-23 01:13 UTC, merged