Imprv/101883 show user management detail page new
weseek/growi pull request #6441
Opened 2022-08-08 16:52 UTC by kaoritokashiki

2022-08-08 19:08 UTC, kaoritokashiki commented on packages/app/src/components/Layout/AdminLayout.tsx
> +              {title != null ? children : <AdminNotFoundPage />}
title が null の場合は　`AdminNotFoundPage` を表示するようにしました
<img width="931" alt="Screen Shot 2022-08-09 at 4 07 41" src="https://user-images.githubusercontent.com/59536731/183494982-9cd71b3f-ee39-402e-9661-58a80f4bacb3.png">

2022-08-08 19:11 UTC, kaoritokashiki commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  }, [currentUserGroup, currentUserGroupId, router]);
- UserGroupId がinvalid の場合
もしくは
- currentUserGroup が null (not undefind)
の場合は、`/admin/user-groups` にリダイレクトするようにしました。

2022-08-08 19:13 UTC, kaoritokashiki commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +  }
`pagePathKeys[index]` より、分割代入で名前をつけた方がわかりやすいかなと思い、変更しました。

2022-08-08 19:24 UTC, kaoritokashiki commented on packages/app/src/server/routes/admin.js
> +  // };
過去の遺産をコメントアウト

2022-08-08 19:24 UTC, kaoritokashiki commented on packages/app/src/server/views/admin/not_found.html
> +<!-- Use AdminNotFoundPage component instead -->
過去の遺産をコメントアウト

2022-08-09 14:26 UTC, yuki-takei requested changes

2022-08-09 14:26 UTC, yuki-takei commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +  }
前と同じ事を書くけど、secondPath が valid ObjectId であるという保証がない。

`import { isValidObjectId } from '~/utils/objectid-utils';`
を使ってください。

2022-08-09 14:26 UTC, yuki-takei commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +    },
path から userGroupId を抽出する処理はこのブロック内でやるべき。

2022-08-09 14:26 UTC, yuki-takei commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  }, [currentUserGroup, currentUserGroupId, router]);
- currentUserGroupId の null check と ObjectId validation は [[...path]].page.tsx でも行い、かつここでもやってよい
    - ただし `import { isValidObjectId } from '~/utils/objectid-utils';` を使う
- currentUserGroup は SWR loading 中は null が入ってくる可能性があるのでリダイレクトしてはいけない

2022-08-18 06:35 UTC, kaoritokashiki commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +  // TODO: refactoring adminPagesMap => https://redmine.weseek.co.jp/issues/102694
adminPagesMap のリファクタ用のタスクを作成

2022-08-18 10:53 UTC, yuki-takei requested changes

2022-08-18 10:53 UTC, yuki-takei commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +import { isValidObjectId } from '../../../../core/src/utils/objectid-utils';
`from '@growi/core'` にしてください

2022-08-18 10:53 UTC, yuki-takei commented on packages/app/src/components/Layout/AdminLayout.tsx
> +                {title != null ? children : <AdminNotFoundPage />}
title の有無で判断するのは違う気がするなあ

2022-08-18 14:52 UTC, kaoritokashiki commented on packages/app/src/components/Layout/AdminLayout.tsx
> +                {title != null ? children : <AdminNotFoundPage />}
タイトルというより、chidren (targetPage.component) で判断する方が良さそうなので、そのように修正しました。

2022-08-18 15:02 UTC, kaoritokashiki commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +import { isValidObjectId } from '../../../../core/src/utils/objectid-utils';
そのように修正しました。

2022-08-18 15:06 UTC, merged