Fix/102159 admin user group detail is null
weseek/growi pull request #6443
Opened 2022-08-09 04:16 UTC by kaoritokashiki

2022-08-09 04:32 UTC, kaoritokashiki commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +const UserGroupUserTable = dynamic(() => import('./UserGroupUserTable'), { ssr: false });
`unstatedContainer` 付きのコンポーネントは 以下のようにwrap されるので、default export されたものをdynamic import しています。

```
const UserGroupUserModalWrapper = withUnstatedContainers(UserGroupUserModalWrapperFC, [AdminUserGroupDetailContainer]);
``

2022-08-09 04:39 UTC, kaoritokashiki commented on packages/app/src/client/services/AdminUserGroupDetailContainer.js
> +      // userGroup: JSON.parse(rootElem.getAttribute('data-user-group')),
rootElem が null で早期リターンされていたので、`AdminUserGroupDetailContainer`　を使用している部分でundefined となっていました。

## 相談

<img width="764" alt="Screen Shot 2022-08-09 at 13 24 44" src="https://user-images.githubusercontent.com/59536731/183565483-ee4c611d-448c-472e-8a2d-98567e489061.png">

2022-08-09 14:32 UTC, yuki-takei commented on packages/app/src/client/services/AdminUserGroupDetailContainer.js
> +      // userGroup: JSON.parse(rootElem.getAttribute('data-user-group')),
> 今はコメントアウトして表示させただけなので、UserGroupDetailContainer 関連のやり方相談したいです。

rootElem の存在チェックは、「UserGroupDetailPage 以外を表示している時」にこの container を初期化しないようにする処置なので、本来的には UserGroupDetailPage  を表示する時にのみインスタンス化すべき。

なので、`admin/[[...path]].page.tsx` で全 container をインスタンス化するようにした措置が裏目に出たかもしれない。

2022-08-09 14:32 UTC, yuki-takei commented on packages/app/src/client/services/AdminUserGroupDetailContainer.js
> +      // userGroup: JSON.parse(rootElem.getAttribute('data-user-group')),
1 or 2 は早く終わる方で構わない

2022-08-18 06:40 UTC, kaoritokashiki commented on packages/core/src/interfaces/user.ts
> +  lastLoginAt: Date,
`createdAt` `lastLoginAt` をプロパティに追加

2022-08-18 06:41 UTC, kaoritokashiki commented on packages/core/src/interfaces/user.ts
> +} & HasObjectId;
`UserGroupRelation` の`relatedUser` のみ populate されている用の型を作成

2022-08-18 06:48 UTC, kaoritokashiki commented on packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +  const xss = useMemo(() => new Xss(), []);
## Before
constructor で state `xss` に　` Xss のインスタンスを生成 & 代入していたのを、
useMemoで所持

2022-08-18 07:09 UTC, kaoritokashiki commented on packages/app/_obsolete/src/client/admin.jsx
> +// import AdminUserGroupDetailContainer from '~/client/services/AdminUserGroupDetailContainer';
Omit AdminUserGroupDetailContainer しました。

2022-08-18 10:33 UTC, yuki-takei requested changes

2022-08-18 10:33 UTC, yuki-takei commented on packages/core/src/interfaces/user.ts
> +  lastLoginAt: Date,
作ってすぐのユーザーのデータは lastLoginAt を持っていないので optional だと思う。

2022-08-18 10:33 UTC, yuki-takei commented on packages/core/src/interfaces/user.ts
> +} & HasObjectId;
packages/app/src/interfaces/user-group-response.ts に定義すればいいんじゃないかな。

2022-08-18 16:22 UTC, kaoritokashiki commented on packages/core/src/interfaces/user.ts
> +  lastLoginAt: Date,
そうですね、修正しました。ありがとうございます。

2022-08-18 16:23 UTC, kaoritokashiki commented on packages/core/src/interfaces/user.ts
> +} & HasObjectId;
そのように修正いたしました!

2022-08-18 16:40 UTC, merged