impv: Activity paging UI
weseek/growi pull request #6444
Opened 2022-08-09 04:26 UTC by miya

## Task
[#100577](https://redmine.weseek.co.jp/issues/100577) [AuditLog] ページング UI の改善
└ [#102177](https://redmine.weseek.co.jp/issues/102177) 改善

2022-08-12 11:59 UTC, yuki-takei requested changes

2022-08-12 11:59 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +  }, [totalPagingPages]);
ワンライナーで書ける
https://stackoverflow.com/a/5842770

2022-08-12 11:59 UTC, yuki-takei commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +              />
Enter キー押下に対応してほしい

2022-08-19 02:34 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +  }, [totalPagingPages]);
ワンライナーで書き直しました

2022-08-19 02:34 UTC, miya commented on packages/app/src/components/Admin/AuditLogManagement.tsx
> +              />
対応しました。

2022-08-19 03:53 UTC, merged