feat: Apply background image and navbar image for themes
weseek/growi pull request #6447
Opened 2022-08-09 13:45 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/101211

2022-08-09 13:53 UTC, Yohei-Shiina commented on packages/app/src/components/Theme/utils/ThemeImageProvider.tsx
> +      return getWoodBackgroundImageSrc(colorScheme);
ここの7テーマは背景に画像が使われている

2022-08-09 13:54 UTC, Yohei-Shiina commented on packages/app/src/components/Layout/AdminLayout.tsx
> +      <header className="py-0 position-relative">
これがないと 背景画像がかぶってヘッダー部分が表示されなくなるので必要

2022-08-09 14:27 UTC, Yohei-Shiina commented on packages/app/src/pages/[[...path]].page.tsx
> +        <header className="py-0 position-relative">
これがないと 背景画像がかぶってヘッダー部分が表示されなくなるので必要

2022-08-09 14:29 UTC, Yohei-Shiina commented on packages/app/src/components/Theme/utils/ThemeImageProvider.tsx
> +import { getBackgroundImageSrc as getWoodBackgroundImageSrc } from '../ThemeWood';
設定されているテーマと light/dark mode に応じて、各テーマから適切な背景画像のURLを取得できるようにしている

2022-08-09 14:30 UTC, Yohei-Shiina commented on packages/app/src/components/Layout/RawLayout.tsx
> +    setBackgroundImageSrc(imgSrc);
背景画像のURLを取得して state にセット

2022-08-09 14:33 UTC, Yohei-Shiina commented on packages/app/src/components/Layout/RawLayout.tsx
> +          </div>}
背景画像がある時のみ表示するようにしている

共通のプロパティは`<Image />`にいれて、テーマごとの異なるものは各テーマのscss内に定義
https://nextjs.org/docs/api-reference/next/image#layout
https://nextjs.org/docs/api-reference/next/image#quality

2022-08-10 07:46 UTC, yuki-takei requested changes

2022-08-10 07:46 UTC, yuki-takei commented on packages/app/src/components/Theme/utils/ThemeImageProvider.tsx
> +      return getWoodBackgroundImageSrc(colorScheme);
ThemeProvider.tsx で switch 文を書いているので、あらたに増やしたくはない。このファイルはなくせるはず。

2022-08-10 07:47 UTC, merged