fix: Show toc correctly
weseek/growi pull request #6451
Opened 2022-08-10 12:11 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/102294

TOC が表示されるように修正しました

2022-08-10 12:14 UTC, hakumizuki commented on packages/app/src/stores/context.tsx
> +  const { data: currentPagePath } = useCurrentPagePath();
key を `currentPagePath` に依存させて `useCurrentPageTocNode` 単体で Current の意味を持つように修正

2022-08-10 12:14 UTC, hakumizuki commented on packages/app/src/components/Page.tsx
> +class PageSubstance extends React.Component<PageSubstanceProps> {
TS 化

2022-08-10 12:18 UTC, hakumizuki commented on packages/app/src/stores/renderer.tsx
> -  return _useOptionsBase(key, config => generateTocOptions(config, tocNode));
`_useOptionsBase` を使わない形に変更

2022-08-10 12:19 UTC, hakumizuki commented on packages/app/src/services/renderer/renderer.ts
> +        tocRef.current = toc;
ref.current で toc を更新

2022-08-12 06:31 UTC, yuki-takei requested changes

2022-08-12 06:31 UTC, yuki-takei commented on packages/app/src/services/renderer/renderer.ts
> +        tocRef.current = toc;
services で react から import したくないなあ。少し工夫したい。

2022-08-12 10:51 UTC, hakumizuki commented on packages/app/src/services/renderer/renderer.ts
> +        tocRef.current = toc;
リファクタしました

2022-08-12 12:19 UTC, merged