imprv: 101262 next private legacy page
weseek/growi pull request #6460
Opened 2022-08-18 06:56 UTC by yukendev

https://redmine.weseek.co.jp/issues/102682

- PrivateLegacyページを表示する

スタイルを当てるのは別タスクでやります（https://redmine.weseek.co.jp/issues/102700）

2022-08-19 03:07 UTC, yukendev commented on packages/app/src/server/routes/index.js
useとrouterを使ったgetだとうまく動作しなかったので純粋なgetに変えました
slackのスレッド（https://wsgrowi.slack.com/archives/C03LCBW00H3/p1660814463372779）

2022-08-19 16:05 UTC, yuki-takei requested changes

2022-08-19 16:05 UTC, yuki-takei commented on packages/app/src/server/routes/index.js
書き換えは問題ない。
途中で挟まってる injectUserUISettings 不要なんじゃない？

2022-08-22 02:12 UTC, yukendev commented on packages/app/src/server/routes/index.js
修正済み

2022-08-22 02:40 UTC, merged