Imprv/102140 create new pages
weseek/growi pull request #6472
Opened 2022-08-23 01:39 UTC by kaoritokashiki

2022-08-24 17:55 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
> +const OptionsSelector = dynamic(() => import('~/components/PageEditor/OptionsSelector').then(mod => mod.OptionsSelector), { ssr: false });
named export x dynamic import に変更

2022-08-24 17:56 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
> +          <SavePageControls />
SaveAndReload を PageEditor で行うようにしたので、`SavePageControls` からはpropsを渡す必要がなくなりました

2022-08-24 18:04 UTC, kaoritokashiki commented on packages/app/src/components/SavePageControls.tsx
> +    (window as CustomWindow).globalEmitter.emit('saveAndReload', { overwriteScopesOfDescendants: true });
スコープを上書き保存する際には、`{ overwriteScopesOfDescendants: true }` を渡すようにしました。

2022-08-24 18:05 UTC, kaoritokashiki commented on packages/app/src/components/SavePageControls.tsx
> +      (window as CustomWindow).globalEmitter.emit('saveAndReload');
通常のページ保存 / 編集 時 に globalEmitter.emit しています

2022-08-24 18:07 UTC, kaoritokashiki commented on packages/app/src/components/SavePageControls.tsx
> +  const grant = grantData?.grant || 1;
ページ新規作成時は grantData がないので `grantData?.grant` は 1 (公開) が入るようにしました。

2022-08-24 18:24 UTC, kaoritokashiki commented on packages/app/src/client/services/PageContainer.js
> -    const socketIoContainer = this.appContainer.getContainer('SocketIoContainer');
```
 const socketIoContainer = this.appContainer.getContainer('SocketIoContainer');
```
どこにも使われていなかったので削除してます。

2022-08-24 18:24 UTC, kaoritokashiki commented on packages/app/src/client/services/PageContainer.js
> -    const socketIoContainer = this.appContainer.getContainer('SocketIoContainer');
```
const socketIoContainer = this.appContainer.getContainer('SocketIoContainer');
```
どこにも使われていなかったのでTS化されたファイルには反映させていません。

2022-08-24 18:25 UTC, kaoritokashiki commented on packages/app/src/client/services/page-operation.ts
> +  // }
HackMD での実装が残っているので、コメントアウトしたままにしています。

2022-08-24 18:54 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor.tsx
> +    await saveAndReload(optionsToSave, { pageId, path: currentPagePath || currentPathname, revisionId: currentPage?.revision?._id }, markdown);
ページ新規作成時には　currentPagePathが undefined となってしまうので、`|| currentPathname` を指定しています

2022-08-24 22:17 UTC, yuki-takei requested changes

2022-08-24 22:17 UTC, yuki-takei commented on packages/app/src/components/SavePageControls.tsx
> +  const grant = grantData?.grant || 1;
後続タスクで GRANT_PUBLIC 等の consts を `@growi/core` にしてそれを参照するようにしてください。

2022-08-24 22:17 UTC, yuki-takei commented on packages/app/src/components/SavePageControls.tsx
> +  };
useCallback 使ってください。その他の arrow function も同様に。

2022-08-25 05:51 UTC, kaoritokashiki commented on packages/app/src/components/SavePageControls.tsx
> +  const grant = grantData?.grant || 1;
畏まりました。以下のタスクで着手します。
https://redmine.weseek.co.jp/issues/103282

2022-08-25 06:03 UTC, merged