feat: Refactor ThemeImageProvider
weseek/growi pull request #6475
Opened 2022-08-23 12:22 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/102529

2022-08-25 05:35 UTC, Yohei-Shiina commented on packages/app/src/components/Theme/ThemeDefault.module.scss
> +    $primary: #122c55;
`.theme` と `[data-color-scheme=`] の階層を変更しただけ
他ファイルも同様

2022-08-25 05:36 UTC, Yohei-Shiina commented on packages/app/src/components/Theme/ThemeAntarctic.tsx
> +  );
colorScheme が渡されていれば背景画像の要素を挿入
なければ children のみを返す

背景画像を表示する他themeのファイルも同様

2022-08-25 05:38 UTC, Yohei-Shiina commented on packages/app/src/components/Theme/utils/ThemeInjector.tsx
> +  return React.cloneElement(<div>{children}</div>, { className });
children の一番親が Fragment だと className が挿入されないので div で囲んでいる
```
<>
  <Image />
  {children}
</>
```

2022-08-25 05:43 UTC, Yohei-Shiina commented on packages/app/src/components/Theme/utils/ThemeProvider.tsx
> +      return <ThemeWood colorScheme={colorScheme}>{children}</ThemeWood>;
背景画像を表示するものに colorScheme を渡している

2022-08-29 12:27 UTC, yuki-takei requested changes

2022-08-29 12:27 UTC, yuki-takei commented on packages/app/src/components/Theme/utils/ThemeInjector.tsx
> +  return React.cloneElement(<div>{children}</div>, { className });
この方法だと clone してるとは言えない。第三引数を上手く使うと挿入できる。

2022-08-29 12:29 UTC, merged