support: Import scss module for Editor components
weseek/growi pull request #6480
Opened 2022-08-25 01:42 UTC by jam411

タスク: [101975](https://redmine.weseek.co.jp/issues/101975)

## 概要

- Editor.tsx配下のSCSSモジュール化とそのインポートをした
- 対象既存SCSSファイル
    `_on-edit.scss`
    `_editor-overlay.scss`
    `_editor-navbar.scss`
    `_editor-attachment.scss`

## BEFORE

## AFTER

2022-08-25 04:16 UTC, jam411 commented on packages/app/src/components/PageEditor/GridEditModal.jsx
> +      <Modal isOpen={this.state.show} toggle={this.cancel} size="xl" className={`${styles['grw-grid-edit-modal']}`}>
Editorは以下の GridEditModal はまだ有効化されていないので動作確認できない. 
SCSSモジュール分割とインポートまで.

2022-08-25 04:17 UTC, jam411 commented on packages/app/src/styles/_mixins.scss
> +}
mixinは_mixins.scssにまとめる

2022-08-25 04:21 UTC, jam411 commented on packages/app/src/styles/_on-edit.scss
>  }
@kaoritokashiki
こちらのpage-editor-preview-body配下のwikiクラスがRevisioinBodyを通らないから当たっていないようなのでご確認お願いいたします。
このあたりのコミット？https://github.com/weseek/growi/commit/a981c4659525adfa800235601e44302a270370ee#

2022-08-25 04:24 UTC, jam411 commented on packages/app/src/components/PageEditor/CodeMirrorEditor.module.scss
> +  }
このPRは `_editor-overlay.scss`にあった .overlay.overlay-gfm-cheatsheet 以外はすべてEditor.tsxでモジュールインポート.

2022-08-25 04:28 UTC, jam411 commented on packages/app/src/styles/_on-edit.scss
on-editはui.tsxや依存関係が複数ありそうだったのでglobalインポートのままにしています。
スタイルが適用されていることは確認できました。

2022-08-25 14:29 UTC, kaoritokashiki commented on packages/app/src/styles/_on-edit.scss
>  }
すみません、理解できていないのですが、
ReactMarkdown の child である`context` の部分が削除されたことによって  元々あったはずのクラスが削除され、スタイルが適用されなくなったということでしょうか??

```
const context = useMemo(() => { ~~~~
```

2022-08-25 14:42 UTC, jam411 commented on packages/app/src/styles/_on-edit.scss
>  }
はい、
Preview.tsxの`<ReactMarkdown {...rendererOptions} >{html}</ReactMarkdown>`でwiki クラスがなくなっているのかなと思いました。

2022-08-25 15:21 UTC, kaoritokashiki commented on packages/app/src/styles/_on-edit.scss
>  }
ありがとうございます、理解しました。

Preview.tsx の`<RevisionBody>` が なくなったことにより、RevisionBody内で指定されていた wiki クラスがDOMから消えてしまっていると。

https://github.com/weseek/growi/blob/e0526d270a2cca1b050e7c16b3e27ba59c04c8fc/packages/app/src/components/Page/RevisionBody.jsx#L65


RevisionBody は ReactMarkdown に置き換えられたので、ReactMarkdownで同じことを実現する必要があると思います。
`className={`wiki ${additionalClassName}`}`

ReactMarkdown は props に `className` を渡すことができるようなので追加できますね。
=> https://github.com/remarkjs/react-markdown


`id="wiki"` はなくなっても良さそうだが、vrt use-tools の↓気になる

```
    cy.get('#wiki').should('not.be.empty');
```

2022-08-25 15:32 UTC, kaoritokashiki commented on packages/app/src/styles/_on-edit.scss
>  }
.wikiに書き換えで問題なさそうですね

2022-08-25 15:34 UTC, kaoritokashiki commented on packages/app/src/styles/_on-edit.scss
>  }
これ　ReactMarkdown 使っているところで additionalClass 渡しているところは 追加しないといけないですね。
後続でもOKです。

2022-08-25 15:36 UTC, kaoritokashiki commented on packages/app/src/styles/_on-edit.scss
>  }
って言っても comment がつくかつかないかですね

2022-08-25 23:32 UTC, jam411 commented on packages/app/src/styles/_on-edit.scss
>  }
このタスクで修正しました。

2022-08-26 14:41 UTC, yuki-takei requested changes

2022-08-26 14:41 UTC, yuki-takei commented on packages/app/src/styles/style-app.scss
> -@import 'editor-navbar';
これは現 master 版の記録として残しておいてください。リリース時にファイルごと消す。

2022-08-30 02:37 UTC, jam411 commented on packages/app/src/styles/style-app.scss
> -@import 'editor-navbar';
残すよう修正しました

2022-08-30 03:00 UTC, jam411 commented on packages/app/src/styles/_on-edit.scss
>  }
`ReactMarkdown`でgrep
TableOfContents.tsx は`.wiki`があってはいけないのでそのままです。

2022-08-30 06:50 UTC, kaoritokashiki commented
なんでこれずっとpendingになっているんだ
<img width="630" alt="Screen Shot 2022-08-30 at 15 50 07" src="https://user-images.githubusercontent.com/59536731/187369241-dff9da29-3e1f-48ab-b5ac-db83caa33bf0.png">

2022-08-30 07:08 UTC, merged