Imprv/102320 omit container from page editor by hackmd
weseek/growi pull request #6482
Opened 2022-08-25 04:40 UTC by yukendev

https://redmine.weseek.co.jp/issues/102320

- PageEditorByHackmd.tsxからAppContainer、PageContainerを削除

2022-08-25 09:28 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
> +  const saveAndReloadHandler = useCallback(async(opts?: {overwriteScopesOfDescendants: boolean}) => {
渡嘉敷さんのPageEditorのPR(https://github.com/weseek/growi/pull/6472)を参考にして更新ボタンを押したときの挙動を実装しました。

2022-08-25 09:28 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
> +    globalEmitter.on('saveAndReload', saveAndReloadHandler);
更新ボタンを押したとき用のイベントを登録

2022-09-14 03:35 UTC, yukendev commented
https://wsgrowi.slack.com/archives/C03LCBW00H3/p1661422482578679
こちらのスレッドで話したコメントアウトの部分に関しては変更を加えていません。
動作確認の時は、コメントアウトを消してHackmdを開き、動作確認を行いました。

2022-09-14 07:51 UTC, yuki-takei requested changes

2022-09-14 07:51 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.tsx
> +  }, [setMarkdownWithDebounce]);
この辺のメカニズムは PageEditor をリスペクトしない方がいいと思う。
つまり、編集中の markdown string はここでは管理しない。

2022-09-15 05:50 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
> +  }, [setMarkdownWithDebounce]);
PageEditorByHackmd内のstateでmarkdownを管理していた部分を削除しました。保存ボタンを押したときに必要な本文はEditorのRefのgetValueメソッドで取得しています。

2022-09-15 11:36 UTC, yuki-takei requested changes

2022-09-15 11:36 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.tsx
> +    }
ここは黙殺せず例外を投げて処理するところまで実装する(後続タスクでも良い)

2022-09-15 11:36 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.tsx
> +    mutateEditorMode(EditorMode.View);
try-catch が必要

2022-09-15 11:36 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.tsx
> +  const { data: revisionIdHackmdSynced, mutate: updateRevisionIdHackmdSynced } = useRevisionIdHackmdSynced();
mutate を別の変数に入れる際は `mutateHoge` に統一したいな

2022-09-15 11:36 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.tsx
> +  const [remoteRevisionId, setRemoteRevisionId] = useState(revision?._id); // initialize
remoteRevisionId も global state として管理しないと、ConflictDiffModal で使えないんじゃないかな。
PageEditor では一旦コメントアウトしてるので後続タスクでも良い。

2022-09-16 01:26 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
> +  const { data: revisionIdHackmdSynced, mutate: updateRevisionIdHackmdSynced } = useRevisionIdHackmdSynced();
修正済み

2022-09-16 11:42 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
> +    }
https://redmine.weseek.co.jp/issues/105164
この後続タスクで実装します

2022-09-16 11:43 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
> +  const [remoteRevisionId, setRemoteRevisionId] = useState(revision?._id); // initialize
https://redmine.weseek.co.jp/issues/100206
この後続タスクで実装します

2022-09-16 11:45 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
> +    mutateEditorMode(EditorMode.View);
https://redmine.weseek.co.jp/issues/105164
こちらの修正も上の例外処理とかぶる部分がありそうなので同じく後続タスクで対応します

2022-09-16 11:52 UTC, merged