support: Apply Nextjs to BookmarkList
weseek/growi pull request #6483
Opened 2022-08-25 05:53 UTC by jam411

タスク: [103107](https://redmine.weseek.co.jp/issues/103107)

## 概要

- BookmarkListのTS/FC, next化, SCSS import, i18n有効化

2022-08-26 01:56 UTC, jam411 commented on packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
> +const SavePageControls = dynamic(() => import('../SavePageControls').then(mod => mod.SavePageControls), { ssr: false });
`No such file or directory (os error 2)` の修正

2022-08-26 01:58 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +          { !isUsersHomePage(props.currentPathname) && (
条件分岐がうまくいかなかったため。
https://redmine.weseek.co.jp/issues/103188 で調査

2022-08-26 15:33 UTC, kaoritokashiki requested changes

2022-08-26 15:33 UTC, kaoritokashiki commented on packages/app/src/components/PageList/PageListItemS.tsx
> +  page: any,
型つけれそうですね

2022-08-26 15:33 UTC, kaoritokashiki commented on packages/app/src/components/PageList/BookmarkList.tsx
> +  const [pages, setPages] = useState<any>([]);
これも型つけられないです?

2022-08-26 15:33 UTC, kaoritokashiki commented on packages/app/src/pages/[[...path]].page.tsx
> +          { !isUsersHomePage(props.currentPathname) && (
あ~~~ なるほど、`props.currentPathname` だと url に記載されているid が入ってきちゃいますね。
なので、元々使われていた `pageWithMeta?.data.path`を使う必要がありますね。
pageWithMeta が存在する　かつ isUsersHomePage がtrue の場合に表示する
で確認してみて欲しいです。🙏

(※ ページ新規作成時にもエラーがでないか確認お願いします。)

2022-08-26 15:34 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
> +const SavePageControls = dynamic(() => import('../SavePageControls').then(mod => mod.SavePageControls), { ssr: false });
ありがとうございます!

2022-08-29 01:49 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +          { !isUsersHomePage(props.currentPathname) && (
[103188](https://redmine.weseek.co.jp/issues/103188) こちらのtsx作成タスクで対応します。

2022-08-29 02:48 UTC, jam411 commented on packages/app/src/components/PageList/PageListItemS.tsx
> +  page: any,
IPageHasId としました

2022-08-29 02:48 UTC, jam411 commented on packages/app/src/components/PageList/BookmarkList.tsx
> +  const [pages, setPages] = useState<any>([]);
type BookmarkListPages を作成しました。

2022-08-29 02:57 UTC, jam411 commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +import { IResTagsUpdateApiv1 } from '~/interfaces/tag';
lint エラー修正

2022-08-29 12:35 UTC, kaoritokashiki commented on packages/app/src/pages/[[...path]].page.tsx
> +          { !isUsersHomePage(props.currentPathname) && (
この条件分岐の修正はこのPRでやって欲しいですね

2022-08-29 14:57 UTC, kaoritokashiki commented on packages/app/src/components/PageList/BookmarkList.tsx
> +}
これは interfaces/bookmark-info の方に追加でお願いします 🙏 

- 名前は`BookmarkListPage`(単数系)が正しそうなのと

あとは、
- page は `Populated<IPage>` を使う
- user は `Ref<IUser>` を使う

が良さそうと思ったけど一応確認したい。  @yuki-takei 


@yuki-takei 
ちょっと、`__v` の処遇はわかっていないんですけど、そのまま型に追加するでいいんでしょうか??

2022-08-29 15:44 UTC, yuki-takei commented on packages/app/src/components/PageList/BookmarkList.tsx
> +}
__v は type には含めなくてよい。プログラム中から参照しなきゃいけないケースもないと思うし。

2022-08-30 02:07 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +          { !isUsersHomePage(props.currentPathname) && (
修正しました。

2022-08-30 02:08 UTC, jam411 commented on packages/app/src/components/PageList/BookmarkList.tsx
> +}
__v を型に含めないように修正しました。

2022-08-30 05:39 UTC, kaoritokashiki commented
https://github.com/weseek/growi/pull/6483#discussion_r957449567
ここの部分で反映されてない部分あるので確認お願いします。

2022-08-30 06:01 UTC, kaoritokashiki requested changes

2022-08-30 06:01 UTC, kaoritokashiki commented on packages/app/src/pages/[[...path]].page.tsx
> +                    <BookmarkList userId={pageWithMeta.data.creator._id} />
渡嘉敷調べによると pageWithMeta に `?` は必要 
& 
BookmarkList のprops `userId` は required なので `pageWithMeta?.data.creator._id` をそのまま渡してはいけないと思います。

確認お願いします 🙏 意見あればください

2022-08-30 06:02 UTC, kaoritokashiki approved these changes

2022-08-30 06:02 UTC, kaoritokashiki commented on packages/app/src/pages/[[...path]].page.tsx
> +          { (pageWithMeta != null && isUsersHomePage(pageWithMeta.data.path)) && (
これは 🆗

2022-08-31 02:17 UTC, jam411 commented on packages/app/src/components/PageList/BookmarkList.tsx
> +}
@kaoritokashiki 
userはRef<IUser>に修正しました。ありがとうございます。

pageの型は他と統一の意味も兼ねて IPageHasId でもよいですか？ "<PageListMeta page=" でgrepなど
（参考）以下は BookmarkListPage 型が受け取るデータ.
![image](https://user-images.githubusercontent.com/68407388/187577451-fed141a0-6a0b-4662-8148-8525c36d21c8.png)

2022-08-31 02:22 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +                    <BookmarkList userId={pageWithMeta.data.creator._id} />
@kaoritokashiki 
`?` 修正しました.

pageWithMetaがnullの場合の処理を加えました。リファクタは以下のタスクで行います。
https://redmine.weseek.co.jp/issues/103188

2022-09-01 08:05 UTC, jam411 commented
Commentのリプライやaタグリンクが聞かなくなっていますが以下のタスクで取り組みます。
https://redmine.weseek.co.jp/issues/103189

2022-09-01 16:09 UTC, kaoritokashiki commented on packages/app/src/components/PageList/BookmarkList.tsx
> +}
memo
Populated<>　なんて型はない。私の頭がおかしくなっていた

2022-09-01 16:28 UTC, kaoritokashiki requested changes

2022-09-01 16:28 UTC, kaoritokashiki commented on packages/app/src/components/PageList/BookmarkList.tsx
> +  const [pages, setPages] = useState<BookmarkListPage[]>([]);
細かいですが、型に List とつけると Item の集合体であるかのような印象を受けて頭が混乱するので

型宣言する際に配列として扱う方がわかりやすいかなと思いました。

2022-09-01 16:28 UTC, kaoritokashiki commented on packages/app/src/interfaces/bookmark-info.ts
> +}
```suggestion
type BookmarkedPage = {
  _id: string,
  page: IPageHasId,
  user: Ref<IUser>,
  createdAt: Date,
}

export type MyBookmarkList = BookmarkedPage[]
```

みたいなイメージで...

2022-09-02 00:49 UTC, jam411 commented on packages/app/src/interfaces/bookmark-info.ts
> +}
ありがとうございます。同意です。勉強になります。

FB修正しました。

2022-09-02 05:44 UTC, kaoritokashiki approved these changes

2022-09-02 05:45 UTC, merged