: Apply Nextjs to RecentCreated
weseek/growi pull request #6491
Opened 2022-08-26 04:19 UTC by jam411

タスク：[103109](https://redmine.weseek.co.jp/issues/103109)

## 概要

## After

2022-08-29 09:22 UTC, jam411 commented on packages/app/src/components/UsersHomePageFooter.module.scss
> +}
こちらのインポートはこのタスクでやります。[103188](https://redmine.weseek.co.jp/issues/103188)

2022-08-29 15:59 UTC, kaoritokashiki requested changes

2022-08-29 15:59 UTC, kaoritokashiki commented on packages/app/src/pages/[[...path]].page.tsx
> +                    <RecentCreated userId={pageWithMeta?.data.creator._id} />
pageWithMeta についている `?` いらなそうです。

2022-08-29 16:05 UTC, kaoritokashiki requested changes

2022-08-29 16:05 UTC, kaoritokashiki commented on packages/app/src/pages/[[...path]].page.tsx
> +                    <RecentCreated userId={pageWithMeta?.data.creator._id} />
あと、TODOコメントも必要なければ削除お願いします 🙏

2022-08-30 01:48 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +                    <RecentCreated userId={pageWithMeta?.data.creator._id} />
`?`の削除
TODOコメント削除

2022-08-30 02:04 UTC, merged