support: global notification next admin
weseek/growi pull request #6492
Opened 2022-08-26 06:26 UTC by Shunm634-source

2022-08-31 17:48 UTC, kaoritokashiki requested changes

2022-08-31 17:48 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
>        globalNotification = JSON.parse(document.getElementById('admin-global-notification-setting').getAttribute('data-global-notification'));
## 前提
`/admin/global-notification/xxxx` にページアクセスする時には以下の2パターンがあることがわかりました。

https://github.com/weseek/growi/blob/c4c08e914243d07c498742d2816603e91aaf479c/packages/app/src/server/routes/index.js#L124-L125

### パターン1 `/admin/global-notification/new`

これは、「Add 」ボタンを押した時のパスで global-notification の 新規作成のために使われる
👉🏻 `globalNotification.detail`が実行される

### パターン2: `'/admin/global-notification/:id'`
これは、パターン1で作成したglobal-notificationの「編集」ボタンを押した時のパスで、id には該当する global-notificationのidが入る
👉🏻   `globalNotification.detail` が実行される

<img width="1276" alt="Screen Shot 2022-09-01 at 2 43 19" src="https://user-images.githubusercontent.com/59536731/187744583-5f70b0f7-8542-4ff3-9a56-37bcec061e6f.png">


※ポイント: どちらも `globalNotification.detail` の処理が実行されます


## `globalNotification.detail` での処理

https://github.com/weseek/growi/blob/c4c08e914243d07c498742d2816603e91aaf479c/packages/app/src/server/routes/admin.js#L196-L210

Add ボタンを押して、 ManageGlobalNotification をレンダリングするときは、globalNotification のデータはundefinedですね。(それはそうだ。新規作成するんだもの...!)


## 結論
本タスクのゴールは、global-notification の新規作成なので、 globalNotification の値を取ってくる処理はコメントアウトのままで良いです。(後続タスクを追加し、TODOコメントとしてコード上に記載してください)

globalNotification の値が入ってなくても`/new`ページは表示できると思います。

2022-09-01 06:11 UTC, Shunm634-source commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +      },
不要でしたので削除ずみ。

2022-09-01 06:12 UTC, Shunm634-source commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +      },
external_notificationにすることで修正済み。

2022-09-01 06:34 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +    // const { isMailerSetup } = appContainer.config;
修正済み。

2022-09-01 06:45 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/GlobalNotification.jsx
> +  const { t, adminNotificationContainer } = props;
修正済み。

2022-09-01 06:48 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/GlobalNotification.jsx
> +      toastSuccess(t('toaster.update_successed', { target: t('External_Notification') }));
external_notification.external_notificationに戻すことで解決済み。

2022-09-01 06:50 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/GlobalNotification.jsx
> +        <div className="col-sm-5 offset-sm-4">
申し訳ありません。見落としてました！
修正済みです。

2022-09-01 06:53 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/GlobalNotification.jsx
>  };
- 上記の通り、tをGlobalNotification内部で取得済み
- 同様にuseTranslationの引数に'admin'を追加

2022-09-01 07:19 UTC, Shunm634-source commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +import ManageGlobalNotification from '~/components/Admin/Notification/ManageGlobalNotification';
修正済み。

2022-09-01 07:44 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +export default class ManageGlobalNotification extends React.Component {
今FC化取り組んでいますが、時間も押してきているので、先にその他の部分をレビューしていただき、終わり次第再度レビューお願いしたいと思います。

2022-09-01 09:00 UTC, kaoritokashiki requested changes

2022-09-01 09:00 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +  const { isMailerSetup } = props;
props からではなく、`useIsMailerSetup` (swr) から取得。

2022-09-01 09:06 UTC, kaoritokashiki requested changes

2022-09-01 09:06 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/GlobalNotification.jsx
> +// export default GlobalNotificationWrapper;
> adminNotificationContainer

を使用するにはこのコードが必要。

2022-09-01 09:11 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/GlobalNotification.jsx
> +// export default GlobalNotificationWrapper;
上記のように修正済み。

2022-09-01 09:19 UTC, kaoritokashiki requested changes

2022-09-01 09:19 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> -          disabled={this.state.retrieveError != null}
これ元のコードが間違ってそうですね

this.state. に `retrieveError`はないので。

正しくは

```
adminNotificationContainer.state.retrieveError
```
そうです。

2022-09-01 09:25 UTC, kaoritokashiki requested changes

2022-09-01 09:25 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +  // }
FC化に伴い不要になったコードは削除お願いします 🙏

2022-09-01 09:25 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +      setTriggerEvents({ triggerEvents });
これは と class の setState と functional componentの の setXXXの 違いですね

`setState`は複数の変数の値を書き換えられるのでオブジェクトになります。

他のsetHoge も修正お願いします。

```suggestion
      setTriggerEvents({ triggerEvents });
```

2022-09-01 09:26 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> -          disabled={this.state.retrieveError != null}
上記の通り修正済み。
その際新たにadminNotificationContainerをpropsに追加しました。

2022-09-01 09:27 UTC, kaoritokashiki requested changes

2022-09-01 09:27 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +      slacChannelToSend,
typo　しております..!

2022-09-01 09:30 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +      slacChannelToSend,
見落としていました！
修正済み。

2022-09-01 09:35 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +  // }
他のファイルも含め削除済み。

2022-09-01 09:35 UTC, kaoritokashiki requested changes

2022-09-01 09:35 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/GlobalNotification.jsx
> +        <div className="btn btn-outline-secondary pull-right">
`className="btn btn-outline-secondary pull-right"`

このclass, btn タグの方につけるべきですね。
bootstrap 公式 ↓
https://getbootstrap.jp/docs/4.5/components/buttons/#button-tags

2022-09-01 09:35 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +      setTriggerEvents({ triggerEvents });
上記のように修正済み。

2022-09-01 09:39 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/GlobalNotification.jsx
> +        <div className="btn btn-outline-secondary pull-right">
上の<div>タブを削除し、className=...のところをそのまま<buttotn>タグに持ってきました。

2022-09-01 09:47 UTC, kaoritokashiki requested changes

2022-09-01 09:47 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +// import { withUnstatedContainers } from '../../UnstatedUtils';
削除お願いします。

2022-09-01 09:47 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +// import AppContainer from '~/client/services/AppContainer';
削除お願いします。

2022-09-01 09:47 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +      // toastError(err);
これ、コメント外しても大丈夫そうじゃないですか??

2022-09-01 09:47 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +  }, []);
warning 出てるので
Quick fix で update dependencies してください

<img width="717" alt="Screen Shot 2022-09-01 at 18 44 12" src="https://user-images.githubusercontent.com/59536731/187884596-274b17f0-149f-412b-8f8c-78021da360a5.png">

2022-09-01 09:47 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +  const [triggerEvents, setTriggerEvents] = useState(new Set());
元のコードのように

```suggestion
  const [triggerEvents, setTriggerEvents] = useState(new Set(globalNotification.triggerEvents));
```

としてください。

また、↓の感じで書いておいていただけると。
```
let globalNotification;

//TODO: xxxxxxx タスクURL ~
// globalNotification = JSON.parse(document.getElementById('admin-global-notification-setting').getAttribute('data-global-notification'));
 ```

2022-09-01 09:49 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +      // toastError(err);
上記の通り修正済み。

2022-09-01 09:49 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +// import AppContainer from '~/client/services/AppContainer';
削除済み。

2022-09-01 09:50 UTC, kaoritokashiki requested changes

2022-09-01 09:50 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/GlobalNotification.jsx
> +    <><h2 className="border-bottom my-4">{t('notification_settings.valid_page')}</h2>
インデントがっ
`<h2 class ~~` は改行した方がいいですね

2022-09-01 09:50 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +  }, []);
上記の通り修正済み。

2022-09-01 09:53 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/GlobalNotification.jsx
> +    <><h2 className="border-bottom my-4">{t('notification_settings.valid_page')}</h2>
上記の通り修正済み。

2022-09-01 09:54 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +  const [triggerEvents, setTriggerEvents] = useState(new Set());
上記の通り修正済み。
globalNotificationだけinitialize the valueしなければならないので、const globalNotification = null;にしてあります。

2022-09-01 09:56 UTC, kaoritokashiki requested changes

2022-09-01 09:56 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +  // TODO: globalNotificationを取得する タスクURL https://redmine.weseek.co.jp/issues/103901
ごめんなさい、英語でお願いします

2022-09-01 09:57 UTC, Shunm634-source commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +  // TODO: globalNotificationを取得する タスクURL https://redmine.weseek.co.jp/issues/103901
英語に直して修正済み。

2022-09-01 10:14 UTC, merged