feat: Rendering maintenance mode
weseek/growi pull request #6499
Opened 2022-08-29 09:25 UTC by miya

## Task
[#101095](https://redmine.weseek.co.jp/issues/101095) [GROWI][Next.js][Admin][Customize以外] 残存の不具合を修正し、全てのページで正常に表示 & 更新ができる 
└ [#103073](https://redmine.weseek.co.jp/issues/103073) メンテナンスモードをレンダリングできる

2022-08-30 03:08 UTC, miya commented on packages/app/src/components/MaintenanceMode.tsx
> +};
- `maintenance-mode.html` を React 化
- `/components/MaintenanceModeContent.tsx` を統合

2022-08-30 03:08 UTC, miya commented on packages/app/src/components/Admin/App/AppSettingsPageContents.tsx
> +        isMaintenanceMode && (
swr の値を利用

2022-08-30 03:08 UTC, miya commented on packages/app/src/components/Admin/App/MaintenanceMode.tsx
> -export default withUnstatedContainers(MaintenanceMode, [AdminAppContainer]);
- omit unstated 
- named export

2022-08-30 03:08 UTC, miya commented on packages/app/src/components/Admin/App/MaintenanceMode.tsx
> -  const [isMaintenanceMode, setMaintenanceMode] = useState<boolean | undefined>(adminAppContainer.state.isMaintenanceMode);
- ステート管理を useState から SWR で isMaintenanceMode の状態管理を行うように変更

2022-08-30 03:08 UTC, miya commented on packages/app/src/components/Admin/App/MaintenanceMode.tsx
> +  }, []);
adminAppContainer で行っていた処理をここでやる

2022-08-30 03:08 UTC, miya commented on packages/app/src/server/middlewares/unavailable-when-maintenance-mode.ts
> +// };
getServerSideProos に isMaintenaceMode の値を入れて、レンダリングする前にその値を参照し、components/MaintenaceMode.tsx の出し分けをするようにしたのでコメントアウトしています。このやり方で良いのか自信がないですが...

2022-08-30 04:37 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +  const title = useCustomTitle(props, 'GROWI');
下記のエラーが出ていたので修正
> React Hook "useCustomTitle" is called conditionally. React Hooks must be called in the exact same order in every component render  react-hooks/rules-of-hooks

2022-08-30 07:28 UTC, yuki-takei requested changes

2022-08-30 07:28 UTC, yuki-takei commented on packages/app/src/components/Admin/App/MaintenanceMode.tsx
> +  }, []);
useIsMaintenanceMode に組み込んでください

2022-08-30 07:28 UTC, yuki-takei commented on packages/app/src/server/middlewares/unavailable-when-maintenance-mode.ts
> +// };
元のやり方(express の middleware で制御)がベター。
`res.render('maintenance-mode');` の Next.js page 版を用意しないといけない。

2022-08-31 08:40 UTC, miya commented on packages/app/src/server/middlewares/unavailable-when-maintenance-mode.ts
> +  nextApp.render(req, res, '/maintenance');
`pages/maintenance.page` をレンダリングする

2022-08-31 08:40 UTC, miya commented on packages/app/src/components/Navbar/GrowiNavbar.tsx
> +        }
next/link を有効にするとメンテナンスモード時に通常ページに遷移してしまうので、有効時は a タグを使う

2022-08-31 08:56 UTC, miya commented on packages/app/src/server/middlewares/unavailable-when-maintenance-mode.ts
> +// };
修正しました。

2022-08-31 08:56 UTC, miya commented on packages/app/src/components/Admin/App/MaintenanceMode.tsx
> +  }, []);
`/stores/maintenaceMode.tsx` を新しく作成し、そこに組み込んだものを作りました。

2022-08-31 16:29 UTC, miya commented on packages/app/src/pages/maintenance.page.tsx
> +  }
`/maintenance` が検索バーに直入力され、`isMaintenanceMode` が true ではなかった場合 `/` にリダイレクトさせる

2022-08-31 16:29 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +  }
`isMaintenanceMode` が true 時に GrowiNavbar のロゴをクリックすると、通常ページがレンダリングされてしまうため以上の処理を追加しました。master は問題ありませんでしたが、next/link によるページ遷移だとこの問題が発生してしまうようです。

2022-09-01 01:47 UTC, yuki-takei requested changes

2022-09-01 01:47 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  }
- `crowi.appService.isMaintenanceMode()` の取得は getServerSideCommonProps に移動
- このリダイレクトさせる処理も common.ts 内に移動させ、共通化する
- `[[...path]].page.tsx` 以外にリダイレクトが必要と思われるページでも呼び出す
    - どのページで必要になるのかは routes/index.js をよく読むこと

2022-09-01 05:24 UTC, miya commented on packages/app/src/pages/utils/commons.ts
> +  }
メンテナンスモードではない時に `/maintenance` にリクエストがあった時に、`/` にリダイレクトさせる

2022-09-01 05:24 UTC, miya commented on packages/app/src/pages/utils/commons.ts
> +  }
メンテナンスモード時で currentPathname が  `/admin/*` と  `/maintenance` ではない時ときに `/maintenance` にリダイレクトさせる

2022-09-01 05:24 UTC, miya commented on packages/app/src/pages/utils/commons.ts
> +  isMaintenanceMode: boolean,
common props に移動

2022-09-01 05:40 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +  }
result に redirect が含まれていた場合リダイレクトさせる

2022-09-01 05:40 UTC, miya commented on packages/app/src/pages/maintenance.page.tsx
> +  }
result に redirect が含まれていた場合リダイレクトさせる

2022-09-01 15:39 UTC, yuki-takei requested changes

2022-09-01 15:39 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  }
type safe なコードではないので NG。
CommonProps の中に全部入れ込んでしまえばいいのでは？

2022-09-02 02:24 UTC, miya commented on packages/app/src/pages/utils/commons.ts
> +    redirectDestination,
- リダイレクト先を commonProp 移動

2022-09-02 02:24 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +  }
common props にリダイレクト先が存在する場合は、リダイレクトする

2022-09-02 02:24 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +  }
以下のコミットで修正しました。　
https://github.com/weseek/growi/pull/6499/commits/7cc673bfac487fbf24622d38b39cb1c4b9ed4d37

2022-09-02 02:39 UTC, merged