imprv: Create UsersHomePageFooter.tsx
weseek/growi pull request #6501
Opened 2022-08-29 09:58 UTC by jam411

タスク：[103188](https://redmine.weseek.co.jp/issues/103188)

- UsersHomePageFooter.tsxの作成
- userページフッター全体のCSS調整

2022-08-31 18:22 UTC, kaoritokashiki requested changes

2022-08-31 18:22 UTC, kaoritokashiki commented on packages/app/src/pages/[[...path]].page.tsx
> +import { UsersHomePageFooter } from '~/components/UsersHomePageFooter';
dynamic import でお願いします。って言おうと思ったけどスケルトン表示しなきゃいけないやつのような気がしてきた....。:eyes:

2022-08-31 18:22 UTC, kaoritokashiki commented on packages/app/src/components/UsersHomePageFooter.tsx
> +          Bookmarks
お手数ですが、ついでに i18n対応までお願いしたいです 🙏

2022-08-31 18:24 UTC, kaoritokashiki commented on packages/app/src/components/UsersHomePageFooter.tsx
> +          Bookmarks
うー、styleここで指定してるの気になる....

2022-09-01 01:53 UTC, yuki-takei requested changes

2022-09-01 01:53 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +import { UsersHomePageFooter } from '~/components/UsersHomePageFooter';
- スケルトン表示は後続でOK
- 現時点では最低限 dynamic import (ssr: false) にしてください。

2022-09-01 02:43 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +import { UsersHomePageFooter } from '~/components/UsersHomePageFooter';
CSRに変更しました。
スケルトン表示のタスクを作成しました [103788](https://redmine.weseek.co.jp/issues/103788)

2022-09-01 03:19 UTC, jam411 commented on packages/app/src/components/UsersHomePageFooter.tsx
> +          Bookmarks
i18n 化しました。
以下のエラーがサーバで出ますが、最新のapply-nextjs-2で解消見込み
```
03:11:38.723Z ERROR growi:routes:apiv3:personal-setting: Cannot read properties of undefined (reading 'changeLanguage')
  TypeError: Cannot read properties of undefined (reading 'changeLanguage')
      at /workspace/growi/packages/app/src/server/routes/apiv3/personal-setting.js:245:16
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

2022-09-01 06:32 UTC, kaoritokashiki requested changes

2022-09-01 06:32 UTC, kaoritokashiki commented on packages/app/public/static/locales/en_US/translation.json
> +    "recently_created": "Recently Created"
どこにも使われていない残骸みたいなのがありました のでこちらは削除お願いします。

https://github.com/weseek/growi/blob/571399e6153485b2e4d421fadae2d32c1157b812/packages/app/public/static/locales/en_US/translation.json#L168

2022-09-01 06:46 UTC, merged