feat: Rendering all in app notifications
weseek/growi pull request #6520
Opened 2022-09-01 14:58 UTC by miya

## Task
[#103466](https://redmine.weseek.co.jp/issues/103466) [Next.js] /me/all-in-app-notifications をレンダリングできる
└ [#103609](https://redmine.weseek.co.jp/issues/103609) /me/all-in-app-notifications をレンダリングできる

2022-09-02 03:41 UTC, miya commented on packages/app/src/pages/me/[[...path]].page.tsx
> +  const targetPage = getTargetPageToRender(mePagesMap, pagePathKeys);
- /admin ページのレンダリング方法を踏襲
- drafts ページは動いていないので別ストーリーで着手します

2022-09-02 03:41 UTC, miya commented on packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
> +  const limit = showPageLimitationXL != null ? showPageLimitationXL : 20;
appContainer で取得していたものを swr で取得するように変更

2022-09-02 10:20 UTC, yuki-takei requested changes

2022-09-02 10:20 UTC, yuki-takei commented on packages/app/src/pages/me/[[...path]].page.tsx
> +  };
これ再レンダリング多くならないか心配ですね

2022-09-02 10:20 UTC, yuki-takei commented on packages/app/src/pages/me/[[...path]].page.tsx
> +  const targetPage = getTargetPageToRender(mePagesMap, pagePathKeys);
ここも useMemo とか使えそう

2022-09-05 02:09 UTC, miya commented on packages/app/src/pages/me/[[...path]].page.tsx
> +  };
修正しました

2022-09-05 02:26 UTC, merged