imprv: PageList page footer conditional
weseek/growi pull request #6524
Opened 2022-09-02 07:30 UTC by jam411

タスク：
[103189](https://redmine.weseek.co.jp/issues/103189)
[103603](https://redmine.weseek.co.jp/issues/103603)

## 概要

- ページごとのfooter表示の調整
- hydration エラーの解消
- タスク2つ分のPRになります

### トップページにcommentを表示させない
![image](https://user-images.githubusercontent.com/68407388/188081022-c2f36b22-cff3-4b1b-8923-73caff07052b.png)

### ページリストが表示されるページにfooterを表示させない
![image](https://user-images.githubusercontent.com/68407388/188081130-d1402914-057c-492b-bc91-1f03db012b66.png)

### Not found ページにfooterを表示させない (ローディングのままで停止する挙動は別タスク)
![image](https://user-images.githubusercontent.com/68407388/188081277-c18d1b0e-aadc-4eaf-bd7e-256eaecc2a85.png)

### その他, identicalpathpageではfooterを表示させない, trashページは未レンダリングのため確認はできていない

2022-09-02 07:36 UTC, jam411 commented on packages/app/src/components/Navbar/GrowiSubNavigation.tsx
> +  }, [Controls]);
Hydrationエラー解消のため

2022-09-02 07:37 UTC, jam411 commented on packages/app/src/components/PagePathNav.tsx
> +const PagePathHierarchicalLink = dynamic(() => import('./PagePathHierarchicalLink'), { ssr: false });
hydrationエラー解消のためCSRに変更しています。

2022-09-02 10:27 UTC, yuki-takei requested changes

2022-09-02 10:27 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiSubNavigation.tsx
> +});
子のための skelton のスタイルを親が付けるのなんか嫌なので…

`<Skelton additionalClass={`${TagLabelsStyles['grw-tag-labels-skelton']} py-1`} />` を `../Page/TagLabels` の方に含んで named export するようにできないかな？つまり skelton は static import して、本物は dynamic import する。

2022-09-05 03:47 UTC, jam411 commented on packages/app/src/components/Navbar/GrowiSubNavigation.tsx
> +});
TagLabelsSkelton として, `../Page/TagLabels` に含めました。

2022-09-05 03:47 UTC, jam411 commented on packages/app/src/components/Page/TagLabels.tsx
> +        />
`<span className="grw-tag-label badge badge-secondary">―</span>`
こちらをスケルトンで代替しました。

2022-09-05 16:58 UTC, merged

2022-09-05 16:58 UTC, yuki-takei approved these changes

2022-09-05 16:58 UTC, yuki-takei commented on packages/app/src/components/PagePathNav.tsx
> +const PagePathHierarchicalLink = dynamic(() => import('./PagePathHierarchicalLink'), { ssr: false });
ページパスはそのページのタイトル表示に等しいので、CSR を待つのは UX が悪くなる。
後続ストーリーを作ってください。(もちろん hydration エラーがでないように実装することをゴールとして明記する)