feat: Create invitedForm
weseek/growi pull request #6539
Opened 2022-09-07 04:05 UTC by jam411

ストーリ：[103934](https://redmine.weseek.co.jp/issues/103934)
　|- タスク：[104040](https://redmine.weseek.co.jp/issues/104040)
　
## 
- invited.htmlの代替
- /login/invited なので, /login 配下エンドポイント用の /login/[[..path]].page.tsx を作成
- 通常フロー処理のみ確認済み。CSS修正, 例外処理、動作確認は別タスクで取り組みます。

## After
<img width="460" alt="invited_page" src="https://user-images.githubusercontent.com/68407388/188784230-ae254c38-2032-4bfe-9376-8f1ca50803b1.png">

2022-09-08 15:52 UTC, yuki-takei requested changes

2022-09-08 15:52 UTC, yuki-takei commented on packages/app/src/pages/login/[[...path]].page.tsx
> +  };
不定の URL 全てのリクエストを処理するケースはないので、login と invited でページは分けるべき。
コードの重複が多くなって共通化した方が良さそうな箇所は、Layout や utils でどうにかする。

2022-09-12 03:55 UTC, jam411 commented on packages/app/src/pages/login/[[...path]].page.tsx
> +  };
修正しました。

2022-09-12 03:55 UTC, jam411 commented on packages/app/src/server/routes/index.js
> +  app.post('/invited/activateInvited' , applicationInstalled, loginFormValidator.inviteRules(), loginFormValidator.inviteValidation, csrfProtection, login.invited);
path の変更

2022-09-12 07:07 UTC, merged