Imprv/104022 show drawio modal on editor navbar
weseek/growi pull request #6546
Opened 2022-09-07 13:18 UTC by kaoritokashiki

2022-09-30 12:44 UTC, kaoritokashiki commented on packages/app/src/components/PageEditor/DrawioModal.tsx
> +    url.searchParams.append('lang', getDiagramsNetLangCode(personalSettingsInfo?.lang || 'en'));
言語を personalSettingsInfo から取得するように変更
`getDiagramsNetLangCode(personalSettingsInfo?.lang`

2022-09-30 12:48 UTC, kaoritokashiki commented on packages/app/src/pages/[[...path]].page.tsx
> +  };
DrawioModal.tsx で `DRAWIO_URI` を取得するために、GrowiHydratedEnv を有効化

2022-09-30 12:48 UTC, kaoritokashiki commented on packages/app/src/stores/modal.tsx
> +        // }
saveの処理 は後続で行います。

2022-10-01 00:33 UTC, kaoritokashiki commented on packages/app/src/components/Page.tsx
> +            /> */}
view mode でのdrawioModal の編集は後続で行います。

2022-10-03 05:44 UTC, yuki-takei requested changes

2022-10-03 05:44 UTC, yuki-takei commented on packages/app/src/interfaces/services/renderer.ts
> +}
この type は廃止。(消してよい)

`[[...path]].page.tsx` 内の `props.hackmdUri` を参考にして。

2022-10-03 05:44 UTC, yuki-takei commented on packages/app/src/stores/modal.tsx
> +    const fontFamily = "Lato, -apple-system, BlinkMacSystemFont, 'Hiragino Kaku Gothic ProN', Meiryo, sans-serif";
この2行がここにはいってくるのはやめたい。

2022-10-03 05:44 UTC, yuki-takei commented on packages/app/src/stores/modal.tsx
> +      }), '*');
config 内の値も責務的には view で指定する内容なので、stores に入れたくない。別のファイルに切り出して。

2022-10-04 04:50 UTC, kaoritokashiki commented on packages/app/src/stores/modal.tsx
> +      }), '*');
[drawio-config.ts](https://github.com/weseek/growi/pull/6546/files#diff-dc77f49f6c800b2c5bbb736ff2b7cdfceb0910194a8110ef939c44b4b29780da) を参照するようにしました。

2022-10-04 04:52 UTC, kaoritokashiki commented on packages/app/src/interfaces/services/renderer.ts
> +}
そのように修正しました

2022-10-04 04:52 UTC, kaoritokashiki commented on packages/app/src/stores/modal.tsx
> +    const fontFamily = "Lato, -apple-system, BlinkMacSystemFont, 'Hiragino Kaku Gothic ProN', Meiryo, sans-serif";
[/src/utils/drawio-config.ts](https://github.com/weseek/growi/pull/6546/files#diff-dc77f49f6c800b2c5bbb736ff2b7cdfceb0910194a8110ef939c44b4b29780da) で定義するように変更

2022-10-04 05:46 UTC, yuki-takei requested changes

2022-10-04 05:46 UTC, yuki-takei commented on packages/app/src/stores/modal.tsx
> +    receiveFromDrawio,
receiveFromDrawio の処理は view 側に移せないかな。addEventListener/removeEventListener も useEffect を使えばいける気がする。

2022-10-04 05:46 UTC, yuki-takei commented on packages/app/src/utils/drawio-config.ts
> +};
これも view 側に移せそう

2022-10-04 06:06 UTC, merged

2022-10-04 06:08 UTC, kaoritokashiki commented on packages/app/src/stores/modal.tsx
> +    receiveFromDrawio,
後続で対応します。
┗https://redmine.weseek.co.jp/issues/106109　

2022-10-04 06:08 UTC, kaoritokashiki commented on packages/app/src/utils/drawio-config.ts
> +};
後続で対応します。
┗https://redmine.weseek.co.jp/issues/106109　