feat: Update PageComment for Searchesult content page
weseek/growi pull request #6548
Opened 2022-09-08 02:26 UTC by jam411

2022-09-08 04:22 UTC, jam411 commented on packages/app/src/components/PageComment.tsx
> +  if (commentsFromOldest == null || commentsExceptReply == null || rendererOptions == null) {
1. SearchResultContent から PageCommnet が呼び出された場合, `currentPagePath` と `currentPage` がundefinedのまま更新されず, スケルトンが返っていたので, v5系同様に, ここで `currentPage`, `currentPagePath` を呼び出さないことにしました。

2022-09-08 04:27 UTC, jam411 commented on packages/app/src/components/Page/RevisionRenderer.tsx
> +    rendererOptions, markdown, highlightKeywords, additionalClassName,
2. PageCommnet で呼び出されていた `currentPage` のPageComment配下のコンポーネントでの用途は RevisionRenderer に渡すためだけでした. しかし、RevisionRendererでは pagePath を使用していないので、RevisionRendererから pagePath propsを削除しました。したがって, RevisionRenderer コンポーネントを使用しているファイルでpagePage propsを渡さないように修正しました。

2022-09-08 04:30 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.tsx
> +  const { data: currentPage } = useSWRxCurrentPage();
3. Commnet.tsxで自律的に currentPageを取得している. v5系での `this.props.pageContainer.state` の代替

2022-09-08 15:49 UTC, yuki-takei requested changes

2022-09-08 15:49 UTC, yuki-takei commented on packages/app/src/components/PageComment/Comment.tsx
> +  const { data: currentPage } = useSWRxCurrentPage();
ここは見直したいなあ。このコンポーネントは props で ICommentHasId を受け取っているし、受け身で何を表示するかが決まるコンポーネントだと思う。(そういう意味では currentUser も本当は props の方が望ましいが)

2022-09-08 15:49 UTC, yuki-takei commented on packages/app/src/components/PageContentFooter.tsx
> +}
これはいい改修だが、[[...path]].page.tsx など使う側がごちゃごちゃし過ぎてしまうので、IPage を受け取るコンポーネントにしていいと思う。

2022-09-12 05:57 UTC, jam411 commented on packages/app/src/components/PageContentFooter.tsx
> +}
IPage を受け取るように修正しました

2022-09-12 07:08 UTC, jam411 commented on packages/app/src/components/PageComment/Comment.tsx
> +  const { data: currentPage } = useSWRxCurrentPage();
currentUser と currentPage は親から受け取るように修正しました。

2022-09-12 07:40 UTC, yuki-takei requested changes

2022-09-12 07:40 UTC, yuki-takei commented on packages/app/src/components/PageComment.tsx
> +  if (typeof (revision) !== 'string') {
revision って Ref<IRevisionHasId> だよね？
isPopulated または getIdForRef を使って。

2022-09-12 08:09 UTC, jam411 commented on packages/app/src/components/PageComment.tsx
> +  if (typeof (revision) !== 'string') {
修正しました

2022-09-12 08:15 UTC, merged