fix: Rendering UserInfo
weseek/growi pull request #6551
Opened 2022-09-08 09:33 UTC by jam411

タスク:[104320](https://redmine.weseek.co.jp/issues/104320)

2022-09-09 03:53 UTC, kaoritokashiki requested changes

2022-09-09 03:53 UTC, kaoritokashiki commented on packages/app/src/components/User/UserInfo.tsx
> +    <div className={`${styles['grw-users-info']} d-flex align-items-center d-edit-none mb-5 pb-3 border-bottom`}>
className に `grw-users-info` も入れないと行けないかと思います

2022-09-09 03:53 UTC, kaoritokashiki commented on packages/app/src/pages/[[...path]].page.tsx
> +  usePageUser(pageWithMeta?.data.creator);
userを新規作成した時もそのユーザーの情報(username やemailなど)が正確に入っているか確認お願いしたいです。

また、`usePageUser` の SWRResponse の型の修正までお願いします!

2022-09-09 04:27 UTC, jam411 commented on packages/app/src/components/User/UserInfo.tsx
> +    <div className={`${styles['grw-users-info']} d-flex align-items-center d-edit-none mb-5 pb-3 border-bottom`}>
themeやcolor等で使われていないから必要ないと思いました。

2022-09-09 04:40 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +  usePageUser(pageWithMeta?.data.creator);
・POST /register した時もUserpageにユーザ情報 (username, name, email) が正しく表示されました
![image](https://user-images.githubusercontent.com/68407388/189272541-f4569d7c-ca0e-4ae5-ada7-92499e082de7.png)

・SWRResponse の型修正しました

2022-09-09 09:31 UTC, jam411 commented on packages/core/src/utils/page-path-utils.ts
> +  if (path.match(/^\/user\/.*?$/)) {
/user ページにもUserInfo が表示されていたので修正.
/user ページは PageTree表記、影響はない.

- TableOfContents.tsxは /userページで使用しない
- ui.tsx /userページに影響しない

2022-09-09 09:35 UTC, jam411 commented on packages/app/src/components/User/UserInfo.tsx
> +      { (pageUser.name === '') ? (
@hakumizuki 
page.creator を pageUser として渡している.
もし, page.creator が削除されている場合は pageUser.name === '' となる.
pageUser.name === '' のユーザは設定から作れない.
ほかのuserIDなどは delete_hoge のように値が入る

2022-09-14 10:19 UTC, yuki-takei requested changes

2022-09-14 10:19 UTC, yuki-takei commented on packages/app/src/components/User/UserInfo.tsx
> +    <div className={`${styles['grw-users-info']} d-flex align-items-center d-edit-none mb-5 pb-3 border-bottom`}>
GROWI では `hoge ${styles['hoge']}` はセットで入れるというのをガイドラインにしたほうがよさそう。

2022-09-15 02:14 UTC, merged

2022-09-15 02:14 UTC, jam411 commented on packages/app/src/components/User/UserInfo.tsx
> +    <div className={`${styles['grw-users-info']} d-flex align-items-center d-edit-none mb-5 pb-3 border-bottom`}>
修正しました。

2022-09-15 02:17 UTC, jam411 commented
PR [#6580](https://github.com/weseek/growi/pull/6580) のマージ後修正をこのPRで行った