[wip] fix:  Rendering trash page
weseek/growi pull request #6552
Opened 2022-09-08 09:37 UTC by miya

## Task
[#99801](https://redmine.weseek.co.jp/issues/99801) [Next.js] ゴミ箱ページ（/trash）をnext.jsでレンダリングできる
└ [#104363](https://redmine.weseek.co.jp/issues/104363) /trash ページがレンダリングできなくなっている問題の修正
└ 104364 empty trash modal を表示・機能させる
└ [#103651](https://redmine.weseek.co.jp/issues/103651) 元に戻すモーダルを表示・機能させる

2022-09-09 03:53 UTC, miya commented on packages/app/src/components/EmptyTrashButton.tsx
> +  }
`deletablePages.length === 0` の時にボタンを押しても何もおこないという挙動が微妙だと思ったので、表示しないように変更しました。

2022-09-09 03:53 UTC, miya commented on packages/app/src/components/Navbar/GrowiNavbar.tsx
> +const AppearanceModeDropdown = dynamic(() => import('./AppearanceModeDropdown').then(mod => mod.AppearanceModeDropdown), { ssr: false });
FC の外に出しました

2022-09-09 03:53 UTC, miya commented on packages/app/src/components/Navbar/GrowiNavbar.tsx
> +const PersonalDropdown = dynamic(() => import('./PersonalDropdown'), { ssr: false });
hydration error が出ていたので CSR

2022-09-09 03:53 UTC, miya commented on packages/app/src/components/PagePathNav.tsx
> +const CopyDropdown = dynamic(() => import('./Page/CopyDropdown'), { ssr: false });
FC の外に出しました

2022-09-09 03:53 UTC, miya commented on packages/app/src/components/PagePathNav.tsx
> +    latterLink = <PagePathHierarchicalLink linkedPagePath={linkedPagePath} isInTrash={isTrashPage} />;
next/link を利用した遷移の時に、PagePathHierarchicalLink で表示しているアイコン（home なのか trash なのか）が切り替わらなかったので追加

2022-09-09 03:53 UTC, miya commented on packages/app/src/stores/context.tsx
> +
引数で true or false を入れるのが微妙だと思ったので、currentPagePath を見てゴミ箱ページなのかを判断するようにしました。

2022-09-09 03:53 UTC, miya commented on packages/app/src/pages/trash.page.tsx
> -  useIsTrashPage(true);
引数不要になったので消し

2022-09-09 03:53 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> -  useIsTrashPage(_isTrashPage(pagePath));
引数不要になったので消し

2022-09-09 03:53 UTC, miya commented on packages/app/src/pages/trash.page.tsx
> +const PutbackPageModal = dynamic(() => import('~/components/PutbackPageModal'), { ssr: false });
FC 外に出す &  EmptyTrashModal と PutbackPageModal をレンダリングできるようにしました

2022-09-09 03:53 UTC, miya commented on packages/app/src/pages/trash.page.tsx
> +        <div id="grw-fav-sticky-trigger" className="sticky-top"></div>
BacicLayout.tsx で呼んでいる Fab が機能していなかったため追加

2022-09-09 07:20 UTC, yuki-takei requested changes

2022-09-09 07:20 UTC, yuki-takei commented on packages/app/src/client/services/ContextExtractor.tsx
> -  useIsTrashPage(isTrashPage);
これは残してOK (ContextExtractor どこからも使ってないはずなので)

2022-09-09 07:20 UTC, yuki-takei commented on packages/app/src/components/EmptyTrashButton.tsx
> +  }
表示したまま disabled にしてください

2022-09-09 07:20 UTC, yuki-takei commented on packages/app/src/components/PagePathNav.tsx
> +    latterLink = <PagePathHierarchicalLink linkedPagePath={linkedPagePath} isInTrash={isTrashPage} />;
責務的に PagePathHierarchicalLink が判断すべき (そういうコードになっているはず)

うまく動いてないのは PagePathHierarchicalLink 側のバグ

2022-09-09 07:20 UTC, yuki-takei commented on packages/app/src/stores/context.tsx
> +    ['isTrashPage', result],
currentPagePath == null の時はキーも null にする

2022-09-09 09:26 UTC, miya commented on packages/app/src/components/EmptyTrashButton.tsx
> +  }
修正しました。￥

2022-09-09 09:26 UTC, miya commented on packages/app/src/components/PagePathNav.tsx
> +    latterLink = <PagePathHierarchicalLink linkedPagePath={linkedPagePath} isInTrash={isTrashPage} />;
`PagePathHierarchicalLink` 側で参照するように修正しました

2022-09-09 09:28 UTC, miya commented on packages/app/src/client/services/ContextExtractor.tsx
> -  useIsTrashPage(isTrashPage);
lint でエラーが出るようになってしまいますが、戻しました

2022-09-09 10:00 UTC, yuki-takei requested changes

2022-09-09 10:00 UTC, yuki-takei commented on packages/app/src/components/PagePathNav.tsx
> +    latterLink = <PagePathHierarchicalLink linkedPagePath={linkedPagePath} isInTrash={isTrashPage} />;
いや、ごめん、整理する

## 現状
- PagePathNav は GrowiSubNavigation で使われており、これは検索結果画面とかでも使われる
    - そのため、current page の状態を表す `useIsTrashPage` は使ってはいけない
    - useIsNotFound も たぶん NG

## ToBe
- PagePathNav は、current page の状態に依存させない
    - 必要なパラメータは props で渡ってきた情報から作る(pagePath がゴミ箱の中なのかどうか含め)
- PagePathHierarchicalLink も同様に、current page の状態に依存させない
    - ただし、「責務的に PagePathHierarchicalLink が判断すべき (そういうコードになっているはず)」は一部誤りで、もし page path にあたる情報を props で渡していたのであれば、正しかった
    - でも実際にはそうではないので、`isInTrash={isTrashPage}` は指定する必要がある

2022-09-12 04:23 UTC, miya commented on packages/app/src/components/PagePathNav.tsx
> +  const isInTrash = isTrashPage(pagePath);
ページのパスから /trash 配下にあるかどうかを判断するように修正しました

2022-09-12 07:01 UTC, yuki-takei requested changes

2022-09-12 07:01 UTC, yuki-takei commented on packages/app/src/stores/context.tsx
> +};
なんか両方不要な気がしてきた。
useCurrentPagePath が取得出来る場所なら、ユーティリティを直接使えばいいんじゃないかと。

2022-09-12 07:29 UTC, merged