fix: render /register with nextjs
weseek/growi pull request #6560
Opened 2022-09-12 04:58 UTC by Yohei-Shiina

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/35527421/189576756-796be11b-f04a-409b-99f7-fcc36458c144.png">

2022-09-12 05:36 UTC, Yohei-Shiina commented on packages/app/next.config.js
> +    },
/register に来た場合も login.page に流す

2022-09-12 05:38 UTC, Yohei-Shiina commented on packages/app/src/components/Layout/NoLoginLayout.tsx
> +  const errors = errorString?.split(',');
`errors?='aaa,bbb'` を配列に変更して格納している

2022-09-12 05:39 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> +
`sendEmailToAllAdmins` が定義される前に使われているという warnigが出ていたのでコードを上に移動しただけ

2022-09-12 05:40 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> +          return res.redirect(`/register?errors=${errors}`);
error の配列をクエリにいれて return

クエリは `?key='AAA, BBB, CCC'` という形になる

2022-09-12 05:41 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> -
上に移動しただけ

2022-09-12 07:14 UTC, yuki-takei requested changes

2022-09-12 07:14 UTC, yuki-takei commented on packages/app/next.config.js
> +    },
- rewrites を使ってまで再現したい挙動なのかをもう一度考える
- `/register` へのアクセス自体、起こらないように改修すればいいという案もあるかも(つまり XHR にする)

2022-09-12 07:14 UTC, yuki-takei commented on packages/app/src/components/Layout/NoLoginLayout.tsx
> +  const errors = errorString?.split(',');
- エラーの解析は layout を司るコンポーネントの責務ではない
- Next.js way にできないか？

2022-09-14 13:54 UTC, Yohei-Shiina commented on packages/app/src/server/routes/apiv3/index.js
> +) => {
`packages/app/src/server/routes/index.js` から渡している

2022-09-14 13:55 UTC, Yohei-Shiina commented on packages/app/src/server/routes/apiv3/index.js
> +    require('./register')(crowi));
もともと POST /registerに設定されていた middleware と同様。
最後だけ新規に作成した apiv3/register を渡している

2022-09-14 13:59 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> -    }
/register に GET することはなくなったのでここは消し

2022-09-14 14:02 UTC, Yohei-Shiina commented on packages/app/src/server/routes/apiv3/register.ts
> +import express from 'express';
- `packages/app/src/server/routes/login.js` から `router.post('/',...` で使うのに必要なものだけコードを移動
- `res.redirect `していたものは `res.apiv3` / `res.apiv3Err` に変更
- リダイレクト先で表示されていた req.flash の エラーメッセージは遷移元のフォームに表示するようにした

2022-09-14 14:07 UTC, Yohei-Shiina commented on packages/app/src/server/routes/apiv3/register.ts
> +    }
middleware の
`registerFormValidator.registerRules(),` でvalidationエラーを検知し
`registerFormValidator.registerValidation,` で `req.form.errors` にエラーが入ってくる
その際 `req.form.isValid` が false になるので、falseの時はそのエラーをクライアントに返す

2022-09-14 14:12 UTC, Yohei-Shiina commented on packages/app/src/pages/login.page.tsx
> +      />
ここはセキュリティ設定等をみて正しい値を取得して props に渡す必要があるが、
現状は仮の値を入れているようなのでこのタスクのスコープでも一旦触れていない
後続ストーリーは作成済み

2022-09-14 14:16 UTC, Yohei-Shiina commented on packages/app/next.config.js
> +    },
XHRにしました

2022-09-14 14:16 UTC, Yohei-Shiina commented on packages/app/src/components/Layout/NoLoginLayout.tsx
> +  const errors = errorString?.split(',');
ここは消えました

2022-09-14 14:36 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +}
一部 optionalになっている箇所等は、LoginForm を呼び出している側の props を修正するときに一緒に修正される

2022-09-14 14:43 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +  };
新規登録フォームが送信された場合の処理
- /register にPOST リクエストし、成功したらサーバーから返されたパスにリダイレクト
- 失敗した場合はエラーを state にセット

2022-09-14 14:44 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +  };
やってること
- `isRegistering` の変更（カードの裏表変更）
- カードを flip したらエラーをリセット

2022-09-14 14:45 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +        }
エラー表示箇所

2022-09-14 14:46 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +        <form role="form" onSubmit={e => handleRegisterFormSubmit(e, registerAction) } id="register-form">
イベントに加えてり稀有スト成功時の遷移先を渡している

2022-09-14 14:48 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +  return (
基本的に構成は変えていない
`this.` で呼ばれていたコードの箇所のみ

2022-09-14 15:05 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +import React, {
- FC/TS化した
  - FC化のため function 関連の差分が出ているが基本的にFC対応以外の変更は加えていない
- /register へのリクエストをXHR化
- POST /register 成功時は router.push でページ遷移

2022-09-14 15:05 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +  const renderExternalAuthInput = (auth) => {
FC対応のみ

2022-09-14 15:06 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +  const renderExternalAuthLoginForm = () => {
FC対応のみ

2022-09-14 15:07 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +  const renderRegisterForm = () => {
FC対応のみ

2022-09-14 15:12 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +                  onChange={(e) => { setUsername(e.target.value) }}
- setState 呼び出し
- name key の変更
- 改行

2022-09-14 15:12 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +                <input type="text"
- setState 呼び出し
- name key の変更
- 改行

2022-09-14 15:12 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +            <input type="email"
- setState 呼び出し
- name key の変更
- 改行

2022-09-14 15:12 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +                <input type="password"
- setState 呼び出し
- name key の変更
- 改行

2022-09-15 04:59 UTC, Yohei-Shiina commented
close し、こちらで対応：#6584

2022-09-15 04:59 UTC, closed without merging