imprv: Update PageContentFooter for present updated data
weseek/growi pull request #6566
Opened 2022-09-12 11:05 UTC by jam411

task: [104310](https://redmine.weseek.co.jp/issues/104310)

- EditページのUpdate後にViewに自動遷移しても PageContentFooter の `Last revision posted at` が更新されない の修正

2022-09-12 11:43 UTC, yuki-takei requested changes

2022-09-12 11:43 UTC, yuki-takei commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +        <PageContentFooter />
このケースでは検索結果のリストから選択されたページの情報を出したいわけだから、自律的に useSWRxCurrentPage で取ってきたらだめじゃない？

2022-09-13 01:54 UTC, jam411 commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +        <PageContentFooter />
その通りでした.. 修正しました。

2022-09-13 01:56 UTC, jam411 commented on packages/app/src/components/PageContentFooter.tsx
> +};
Wrapper関数を用意して用途別に呼び出すようにしました。

2022-09-13 10:53 UTC, yuki-takei requested changes

2022-09-13 10:53 UTC, yuki-takei commented on packages/app/src/components/PageContentFooter.tsx
> +export const PageContentFooterWrapper = (): JSX.Element => {
Current っていう文字を含む名前にして。wrapper ではわかりにくい。

2022-09-14 01:04 UTC, jam411 commented on packages/app/src/components/PageContentFooter.tsx
> +export const PageContentFooterWrapper = (): JSX.Element => {
修正しました

2022-09-14 01:16 UTC, merged