Fix/rendering button on user page
weseek/growi pull request #6580
Opened 2022-09-14 07:57 UTC by jam411

タスク: [104427](https://redmine.weseek.co.jp/issues/104427)

2022-09-14 08:21 UTC, jam411 commented on packages/app/src/stores/context.tsx
> -      return (!isNotCreatable && !isTrashPage && !isGuestUser);
1. useIsNotCreatableは !isCreatable() 等によって判断されていた。
これはv5でのuseIsNotCreatable(props.isNotCreatable)とは違う。(v5はswigでページ単位で判断)
useIsEditable で isNotCreatableが呼び出され, v5系での isNotCreatableだけど, isEditable ができていなかった。

2022-09-14 08:36 UTC, jam411 commented on packages/app/src/stores/ui.tsx
> +    () => !!isEditable && !isSharedUser,
`!!isEditable` はエラー回避のため

2022-09-14 08:39 UTC, jam411 commented on packages/app/src/components/Navbar/GrowiSubNavigation.tsx
> +      { !isNotFound && (
flickering解消のため

2022-09-14 10:21 UTC, merged

2022-09-14 10:22 UTC, yuki-takei requested changes

2022-09-14 10:22 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  IsNotCreatablePage: boolean,
頭は小文字に

2022-09-15 02:09 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +  IsNotCreatablePage: boolean,
以下のPRで修正しました。
https://github.com/weseek/growi/pull/6551