[wip] feat: Render shared page
weseek/growi pull request #6581
Opened 2022-09-14 09:26 UTC by miya

## Task
[#104578](https://redmine.weseek.co.jp/issues/104578) [Next.js] 作成された Share link にアクセスできる
└ [#104583](https://redmine.weseek.co.jp/issues/104583) 共有済みページをレンダリングできる

2022-09-15 10:29 UTC, yuki-takei requested changes

2022-09-15 10:29 UTC, yuki-takei commented on packages/app/src/components/Layout/BasicLayout.tsx
> +      }
下の方の modal もいらないと思うので、別途 layout ファイルを作成すべき

2022-09-15 10:29 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const { data: currentPage, mutate: mutateCurrentPage } = useSWRxCurrentPage(shareLinkId ?? '');
どんな問題を解決しようとして入れた修正かはわからないが、このような使い方は気持ち悪いので元には戻して。
問題があるなら別の手段で解決。

2022-09-15 10:29 UTC, yuki-takei commented on packages/app/src/pages/share/[[...path]].page.tsx
> +  userUISettings?: IUserUISettings,
userUISettings 不要なのでは？

2022-09-15 10:29 UTC, yuki-takei commented on packages/app/src/pages/share/[[...path]].page.tsx
> +              <DisplaySwitcher />
editor 必要ないと思うので、DisplaySwitcher じゃなくていいと思う

2022-09-22 04:38 UTC, miya commented on packages/app/src/components/Layout/BasicLayout.tsx
> +      }
`ShareLinkLayout.tsx` を作成しました。

2022-09-22 04:39 UTC, miya commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const { data: currentPage, mutate: mutateCurrentPage } = useSWRxCurrentPage(shareLinkId ?? '');
これは不要でしたので元に戻しました。

2022-09-22 05:00 UTC, miya commented on packages/app/src/pages/share/[[...path]].page.tsx
> +  userUISettings?: IUserUISettings,
これも不要でしたので元に戻しました。

2022-09-22 05:01 UTC, miya commented on packages/app/src/pages/share/[[...path]].page.tsx
> +              <DisplaySwitcher />
master では shared page でもページの作成ができるため残しています。

2022-09-22 05:03 UTC, miya commented on packages/app/src/components/ShareLink/ShareLinkForm.tsx
> +      return parse(`${formattedDate}T${formattedTime}`, "yyyy-MM-dd'T'HH:mm", new Date());
Invalid Date になっていたので修正しました。

2022-09-22 05:03 UTC, miya commented on packages/app/src/components/ShareLink/ShareLinkForm.tsx
> +      return addDays(new Date(), numberOfDays);
dateFns の addDays を使ってシンプルにしました

2022-09-22 14:36 UTC, yuki-takei requested changes

2022-09-22 14:36 UTC, yuki-takei commented on packages/app/src/components/ShareLink/ShareLinkForm.tsx
> +      return parse(`${formattedDate}T${formattedTime}`, "yyyy-MM-dd'T'HH:mm", new Date());
なんでこんな format して parse するっていう無駄なことをやってるんだ？
input が Date で output も Date なんだから string 型を取り扱う理由がない。

2022-09-22 14:36 UTC, yuki-takei commented on packages/app/src/pages/share/[[...path]].page.tsx
> +                <DisplaySwitcher />
Editor は要らないので、DisplaySwitcher である必要がない。

2022-09-22 14:36 UTC, yuki-takei commented on packages/app/src/server/routes/index.js
> +  app.get('/share/:linkId', next.delegateToNext);
`actions.showSharedPage` でやってる activity の記録とかが抜け落ちちゃうんじゃないかな。
そこだけ別の middleware (shared page 専用でもよい) を作って対応する必要がある。後続タスクで実装して。

2022-09-22 14:36 UTC, yuki-takei commented on packages/app/src/components/Page.tsx
> +  const { data: currentPage } = useSWRxCurrentPage(shareLinkId ?? '');
空文字列を渡すのは NG

2022-09-22 14:37 UTC, yuki-takei requested changes

2022-09-22 14:37 UTC, yuki-takei commented on packages/app/src/pages/share/[[...path]].page.tsx
> +export default SharedPage;
presentation は一旦不要

2022-09-26 04:40 UTC, miya commented on packages/app/src/components/ShareLink/ShareLinkForm.tsx
> +      return parse(`${formattedDate}T${formattedTime}`, "yyyy-MM-dd'T'HH:mm", new Date());
date-fns の set を使った処理に変更しました

comit: https://github.com/weseek/growi/pull/6581/commits/93e2c82cb487e2e2bc04dd71ad60f30038b2ade7

2022-09-27 04:11 UTC, merged