feat: Use XHR for POST /register
weseek/growi pull request #6584
Opened 2022-09-15 04:57 UTC by Yohei-Shiina

以下４つまとめたPR
https://redmine.weseek.co.jp/issues/104523
https://redmine.weseek.co.jp/issues/104532
https://redmine.weseek.co.jp/issues/104537
https://redmine.weseek.co.jp/issues/104744

# 変更点
- 新規登録のリクエストを XHRリクエストに変更
- サーバーサイドでの req.t を廃止
- リダイレクト先に表示する req.flash を廃止
- エラーメッセージはそのページのフォーム内で表示するように変更
- LoginForm を TS/FC化
- middlewareで発生するエラーも新規登録フォームでエラーとして表示
- サーバー側ではなくクライアントでリダイレクトするように変更

<img width="470" alt="image (28)" src="https://user-images.githubusercontent.com/35527421/189826350-fa4c6e42-686d-4c8d-91e3-48a8610d9449.png">

2022-09-15 05:02 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +import React, {
FC/TS化した
- FC化のため function 関連の差分が出ているが基本的にFC対応以外の変更は加えていない
- /register へのリクエストをXHR化
- POST /register 成功時は router.push でページ遷移

2022-09-15 10:06 UTC, yuki-takei requested changes

2022-09-21 13:14 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> +  async function sendEmailToAllAdmins(userData) {
場所を変えただけ

2022-09-21 13:17 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> -        userData.updateLastLoginAt(new Date(), (err, userData) => {
使われていなかったので削除

2022-09-21 13:19 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> +      return res.apiv3({ redirectTo });
redirect せずに redirect 先をクライアントに返すように変更

2022-09-21 13:19 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> -    if (req.method === 'POST' && req.form.isValid) {
POSTしかこないので条件から外した

2022-09-21 13:20 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> +    if (!req.form.isValid) {
フォームに問題がある時の処理

2022-09-21 13:20 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> +    const registerForm = req.form.registerForm || {};
ここから正常系

2022-09-21 13:29 UTC, Yohei-Shiina commented on packages/app/src/server/routes/index.js
> +const csrfProtection = csrf({ ignoreMethods: ['GET', 'HEAD', 'OPTIONS', 'POST'], cookie: false });
対応済み

2022-09-21 13:45 UTC, yuki-takei requested changes

2022-09-21 13:45 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +    window.location.href = `/passport/${auth}`;
この warning って、挙動に影響あるかな？
もし影響がないなら出たままでいいので router.push を使った実装にしてほしい。

同じ問題を別のシチュエーションで確認していて、解決策はオレもまだ見つけていない。

2022-09-21 13:45 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +  const handleLoginWithExternalAuth = (e) => {
基本的に全ての closure 定義時に useCallback を使ってください

2022-09-21 13:45 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +      const res = await apiv3Post(requestPath, { registerForm, _csrf: csrfToken });
XHR にした場合、csrfToken は不要になる

2022-09-21 13:45 UTC, yuki-takei commented on packages/app/src/pages/login.page.tsx
> +const LoginForm = dynamic<LoginFormProps>(() => import('~/components/LoginForm').then(mod => mod.LoginForm), { ssr: false });
SSR したい
`#register` へのアクセス時は useEffect で flip される挙動でよい。

2022-09-21 13:45 UTC, yuki-takei commented on packages/app/src/server/routes/index.js
> +  const [apiV3Router, apiV3AdminRouter, apiV3AuthRouter] = require('./apiv3')(crowi, middlewaresForAuth);
`routes/apiv3/index` 側で import/require すればいいのでは？

2022-09-21 13:45 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +      return res.apiv3({ redirectTo });
apiv3 method を利用する実装は将来的にはいいとして、endpoint を `/_api/v3/login` などにしたい。
後続タスク化して誰かに振ってください。(自分でやってもOK)

2022-09-21 13:45 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +          return res.apiv3Err(errors, 400);
UserUpperLimitException の場合は 405 かなあ

2022-09-22 03:22 UTC, Yohei-Shiina commented on packages/app/src/server/routes/index.js
> +  const [apiV3Router, apiV3AdminRouter, apiV3AuthRouter] = require('./apiv3')(crowi, middlewaresForAuth);
対応済み

2022-09-22 03:22 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +    window.location.href = `/passport/${auth}`;
対応済み

2022-09-22 03:22 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +      const res = await apiv3Post(requestPath, { registerForm, _csrf: csrfToken });
対応済み

2022-09-22 05:09 UTC, Yohei-Shiina commented on packages/app/src/pages/login.page.tsx
> +const LoginForm = dynamic<LoginFormProps>(() => import('~/components/LoginForm').then(mod => mod.LoginForm), { ssr: false });
勘違いをしていなければ現状そうなっているのでこのままにします。
> #register へのアクセス時は useEffect で flip される挙動でよい

2022-09-22 05:10 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> +          return res.apiv3Err(errors, 400);
対応済み

2022-09-22 05:11 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +  const handleLoginWithExternalAuth = (e) => {
対応済み

2022-09-22 05:11 UTC, merged