feat: Use XHR for POST /login with apiv3
weseek/growi pull request #6585
Opened 2022-09-15 05:54 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/104411

2022-09-22 11:49 UTC, yuki-takei requested changes

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/index.js
> +    addActivity, loginPassport.loginWithLocal, loginPassport.loginWithLdap);
- forgot-password の `.use(forgotPassword.handleErrosMiddleware))` を参考に loginFailure が最後のエラーハンドリングをするように改修してください

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err('message.strategy_has_not_been_set_up.LdapStrategy', 405);
ここは OK

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err(err);
- 引数に err を入れて next を使う
    - err が null なら正常系のまま最終的には loginFailure に渡る
    - err が null じゃなければ異常系になるが、最終的にはやはり loginFailure に渡る

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err(req.form.errors, 400);
引数付きの異常系として next を使う (最終的に loginFailure に渡る)

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err('message.ldap_user_not_valid', 400);
引数付きの異常系として next を使う (最終的に loginFailure に渡る)

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err('message.external_account_not_exist', 404);
引数なしの正常系として next を使う (最終的には loginFailure に渡る)

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      if (err) { debug(err.message); return res.apiv3Err(err) }
引数付きの異常系として next を使う (最終的に loginFailure に渡る)

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err('message.strategy_has_not_been_set_up.LocalStrategy', 405);
ここは OK

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err(req.form.errors, 400);
引数付きの異常系として next を使う (最終的に loginFailure に渡る)

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +        return res.apiv3Err('message.database_error', 500);
引数付きの異常系として next を使う (最終的に loginFailure に渡る)

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +        return res.apiv3Err('message.user_not_found', 401);
引数なしの正常系として next を使う (最終的には loginFailure に渡る)

2022-09-22 11:49 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +        if (err) { debug(err.message); return res.apiv3Err(err) }
引数付きの異常系として next を使う (最終的に loginFailure に渡る)

2022-09-26 03:40 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +        return res.apiv3Err('message.database_error', 500);
対応済み

2022-09-26 03:40 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +        return res.apiv3Err('message.user_not_found', 401);
対応済み

2022-09-26 03:40 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +        if (err) { debug(err.message); return res.apiv3Err(err) }
対応済み

2022-09-26 03:40 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err(req.form.errors, 400);
対応済み

2022-09-26 03:41 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +      if (err) { debug(err.message); return res.apiv3Err(err) }
対応済み

2022-09-26 03:45 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err('message.ldap_user_not_valid', 400);
対応済み

2022-09-26 03:45 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err(err);
対応済み

2022-09-26 03:46 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err(req.form.errors, 400);
対応済み

2022-09-26 03:46 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err('message.strategy_has_not_been_set_up.LdapStrategy', 405);
対応済み

2022-09-27 04:28 UTC, yuki-takei requested changes

2022-09-27 04:28 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      }
異常系の処理として logger 出力だけでは不十分。

1. getOrCreateUser では throw Error
2. getOrCreateUser を呼んだ側では `next(err)` を呼ぶ

の流れにしてください。でないと req.flush の代わりの処理を実装したことにならない。

2022-09-27 04:28 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/index.js
> +    addActivity, loginPassport.loginWithLocal, loginPassport.loginWithLdap, loginPassport.cannotLoginErrorHadnler, loginPassport.loginFailure);
> forgot-password の .use(forgotPassword.handleErrosMiddleware)) を参考に loginFailure が最後のエラーハンドリングをするように改修してください

と書いたんだけど見た？

この書き方では next(err) した時に `loginPassport.loginFailure` に処理が渡らないと思うよ。

2022-09-27 04:47 UTC, Yohei-Shiina commented on packages/app/src/server/routes/apiv3/index.js
> +    addActivity, loginPassport.loginWithLocal, loginPassport.loginWithLdap, loginPassport.cannotLoginErrorHadnler, loginPassport.loginFailure);
実験済み・口頭解決
next(Error('HOGE')) した場合、通常の middleware を飛ばして、errorHandlingMiddleware まで飛ぶ

2022-09-27 06:08 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +      }
対応済み

2022-09-27 10:17 UTC, Yohei-Shiina commented
`logger.error('provider-DuplicatedUsernameException', providerId);` の箇所は、5系 master 同様に丁寧なメッセージで表示するようにする
上記は後続タスクで対応：https://redmine.weseek.co.jp/issues/105658

2022-09-27 10:17 UTC, merged