fix: UserPage delete deleted user info
weseek/growi pull request #6625
Opened 2022-09-21 06:32 UTC by jam411

タスク:
https://redmine.weseek.co.jp/issues/104827

2022-09-21 12:13 UTC, jam411 commented on packages/app/src/components/ContentLinkButtons.module.scss
>      height: 14px;
_toc.scss 内のクラスはtoc関連でmodule化されたものは削除されており、grep確認し残りはこのmodule化のみでしたので削除しました。

2022-09-21 12:13 UTC, jam411 commented on packages/app/src/components/ContentLinkButtons.tsx
> +  }, []);
条件によって再レンダリングされなかったのでこちらの構成にしました。

2022-09-21 12:14 UTC, jam411 commented on packages/app/src/components/ContentLinkButtons.tsx
> +  if (pageUser == null || pageUser.name === '') {
ユーザが削除されていた場合の処理を追加しました。
後続タスク:https://redmine.weseek.co.jp/issues/105325

2022-09-22 03:35 UTC, jam411 commented on packages/app/src/components/Page/DisplaySwitcher.tsx
> +        { isUserPage && <UserInfo /> }
ContentLinkButtons のように UserInfo で `usePageUser` を呼び出すように修正しました。

2022-09-22 03:55 UTC, jam411 commented on packages/app/src/components/Navbar/GrowiSubNavigation.tsx
> +      {/* Right side. */}
自分が記載していたコメント削除しました。

2022-09-22 04:01 UTC, jam411 commented on packages/app/src/components/Page/DisplaySwitcher.tsx
> +              { isUserPage && <ContentLinkButtons /> }
ContentLinkButtonsはuserページ以外で表示しないため

2022-09-22 11:03 UTC, yuki-takei requested changes

2022-09-22 11:03 UTC, yuki-takei commented on packages/app/src/components/Page/DisplaySwitcher.tsx
> +        { isUserPage && <UserInfo /> }
useIsUserPage の使い方間違ってると思う。これは `/user/dummyuser/memo1` でも true になる。
`/user/dummyuser` というページかどうかを判定するには、pagePathUtils の `isUsersHomePage` を使う必要がある。

そしてついでに自分がエンバグした箇所を発見した。DisplaySwitcher で誤って `isUsersTopPage` を使ってしまった。ここも `isUsersHomePage` を使う必要がある。

整理しよう。。

## ToBe

- UserInfo コンポーネントが props.pageUser を見て自律的に表示・非表示を切り替えるように改修するのは OK
    - props.pageUser は undefined 許容していいと思う
    - pageUser が削除済みかどうかも自律的に判定してよい
- 今表示しているパスが `/user/dummyuser` なのかどうかは UserInfo 呼び出し側で判定する必要があり(ここは現在の仕様でただしい)、それは useIsUserPage ではなく`isUsersTopPage` でもなく `isUsersHomePage` を使う必要がある

2022-09-26 01:04 UTC, jam411 commented on packages/app/src/components/Page/DisplaySwitcher.tsx
> +        { isUserPage && <UserInfo /> }
isUsersHomePageを使うように修正しました

2022-09-26 01:05 UTC, jam411 commented on packages/app/src/components/ContentLinkButtons.tsx
> +import styles from '~/components/ContentLinkButtons.module.scss';
修正しました。今後統一します。

2022-09-26 01:30 UTC, jam411 commented on packages/app/src/components/User/UserInfo.tsx
> +  if (pageUser == null || pageUser.name === '') {
`pageUser.status === 4` に修正

2022-09-27 04:01 UTC, merged