imprv: Use xhr installer modify request
weseek/growi pull request #6651
Opened 2022-09-26 07:13 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/105252

Installer を apiv3 化して周辺を XHR 化しました

2022-09-26 07:14 UTC, hakumizuki commented on packages/app/src/server/routes/index.js
> +    app.use('/_api/v3/installer', applicationNotInstalled, apiv3Installer);
apiv3 の router の中に入れることも考えましたが、`isInstalled` を複数の場所で管理する方が微妙かなあと思ったのでこういう形で登録しました

2022-09-26 07:15 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/installer.ts
> +  router.post('/', registerRules(), apiV3FormValidator, addActivity, async(req: FormRequest, res: ApiV3Response) => {
apiv3 化

2022-09-26 07:16 UTC, hakumizuki commented on packages/app/src/components/InstallerForm.tsx
> +    };
state で管理することも考えましたが、なるだけ既存のコードを残す方向で実装しようと思ったので、`e.target.elements` から value を抽出するようにしました

2022-09-26 07:16 UTC, hakumizuki commented on packages/app/src/components/InstallerForm.tsx
> +      window.location.href = '/';
トップページに遷移

2022-09-26 07:17 UTC, hakumizuki commented on packages/app/src/server/service/installer.ts
> +  async install(firstAdminUserToSave: Pick<IUser, 'name' | 'username' | 'email' | 'password'>, globalLang: Lang, options?: AutoInstallOptions): Promise<IUser> {
型を改善

2022-09-27 04:58 UTC, yuki-takei requested changes

2022-09-27 04:58 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/installer.ts
> +      }
旧コードでの
```
      if (err) {
        req.flash('successMessage', req.t('message.complete_to_install1'));
        req.session.redirectTo = '/';
        return res.redirect('/login');
      }
```
相当の処理を、サーバー側・クライアント側どちらでも構わないので実装してください。

2022-09-27 04:58 UTC, yuki-takei commented on packages/app/src/server/routes/index.js
> +    app.use('/_api/v3/installer', applicationNotInstalled, apiv3Installer);
`apiv3/installer.ts` に入れるのが綺麗だと思うよ。`isInstalled` は require したときに引数で渡せばいい。

2022-09-27 05:11 UTC, hakumizuki commented on packages/app/src/server/routes/index.js
> +    app.use('/_api/v3/installer', applicationNotInstalled, apiv3Installer);
なるほど。それいい感じなのでそうしました。

2022-09-27 05:20 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/installer.ts
> +      }
クライアントサイドで toastErr 表示した後にちょっと待って /login に遷移する実装にしました

2022-09-27 05:59 UTC, merged