support: add error handling to PageEditorByHackmd
weseek/growi pull request #6673
Opened 2022-09-28 07:00 UTC by yukendev

https://redmine.weseek.co.jp/issues/105164

PageEditorByHackmd内でエラーハンドリングできていなかった部分を追加

2022-09-28 07:04 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
> +  const { data: pageData, mutate: mutatePageData } = useSWRxCurrentPage();
mutate関数の名前をmutateHogeに統一できていなかったので修正しました

2022-09-28 07:05 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
> +      ) { throw new Error('Some materials to save are invalid') }
上の修正と同じように、保存に必要な要素がない場合はエラーを返すようにしました

2022-09-28 07:28 UTC, yuki-takei requested changes

2022-09-28 07:28 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.tsx
> +      ) { throw new Error('Some materials to save are invalid') }
`currentPagePath || currentPathname` を一次変数に入れておいて、それを null チェックすべきかと。

2022-09-28 07:28 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.tsx
> +      mutatePageData();
この mutate でサーバーから値を取得すると、厳密には203行目以降の res 内のデータで mutate するデータと不整合が起きる可能性があるんじゃないかな。

2022-09-29 12:50 UTC, yuki-takei requested changes

2022-09-29 12:50 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.tsx
> +      mutateHasDraftOnHackmd(pageData.hasDraftOnHackmd);
おかしい気がする。
`revision` や `pageData` には、saveOrUpdate 後のデータは入ってこないのでは？このコードで2回連続で onSaveWithShortcut できる？revisionHackmdSynced が最新のものに差し替わらないので、2回目の更新で失敗するんじゃないかと思っている。

2022-10-03 11:03 UTC, merged