feat: convert form to xhr
weseek/growi pull request #6678
Opened 2022-09-29 02:56 UTC by jam411

タスク: 
[104769](https://redmine.weseek.co.jp/issues/104769)
[105724](https://redmine.weseek.co.jp/issues/105724)

2022-09-29 03:01 UTC, jam411 commented on packages/app/src/server/middlewares/invited-form-validator.ts
> +};
ファイル分割

2022-09-29 03:02 UTC, jam411 commented on packages/app/src/server/routes/index.js
> +  // app.post('/login'                   , applicationInstalled, loginFormValidator.loginRules(), loginFormValidator.loginValidation, csrfProtection,  addActivity, loginPassport.loginWithLocal, login
apiv3に移行のためコメントアウト

2022-09-29 03:03 UTC, jam411 commented on packages/app/src/server/routes/login-passport.js
> +
loginForm の router.push() では routes/index.js の loginRequired が期待通り機能しないので resで `/invited` を返すように修正
リファクタリングは後続タスク

2022-09-29 03:04 UTC, jam411 commented on packages/app/src/server/routes/login.js
> +    }
コメントアウトされていたため有効化

2022-09-29 03:04 UTC, jam411 commented on packages/app/src/server/routes/login.js
> -  };
使用していないため削除

2022-09-29 03:04 UTC, jam411 commented on packages/app/src/components/InvitedForm.tsx
> +      // TODO: show errors
例外処理は後続タスク https://redmine.weseek.co.jp/issues/104290

2022-09-30 02:26 UTC, Yohei-Shiina commented on packages/app/src/server/middlewares/invited-form-validator.ts
> +      .withMessage('message.Username has invalid characters')
`message.` の箇所は translation file に存在していますか？していればOKです

2022-09-30 02:26 UTC, Yohei-Shiina commented on packages/app/src/server/routes/index.js
> +  // app.post('/login'                   , applicationInstalled, loginFormValidator.loginRules(), loginFormValidator.loginValidation, csrfProtection,  addActivity, loginPassport.loginWithLocal, login
別タスクで対応するのでこれはアンコメントしてもらってOKです！

2022-09-30 02:26 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +    }
下のコードとうまくまとめれば `return res.apiv3({ redirectTo:` を2回書かなくて済みそうですね
```
const { redirectTo } = req.session;
// remove session.redirectTo
delete req.session.redirectTo;
```

2022-09-30 02:26 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login.js
> +      return res.safeRedirect(redirectTo);
これはこのまま `safeRedirect` でも問題ないですか？

2022-09-30 02:46 UTC, jam411 commented on packages/app/src/server/routes/login.js
> +      return res.safeRedirect(redirectTo);
`user.status === User.STATUS_ACTIVE` なので `/invited` 観点では大丈夫です。

2022-09-30 02:48 UTC, jam411 commented on packages/app/src/server/middlewares/invited-form-validator.ts
> +      .withMessage('message.Username has invalid characters')
存在していますが、動作確認は後続タスクでも対応します。https://redmine.weseek.co.jp/issues/104290

2022-09-30 03:26 UTC, jam411 commented on packages/app/src/server/routes/login-passport.js
> +    }
`/invited`用の処理が独立するように一旦まとめずおいておきます

2022-09-30 08:46 UTC, yuki-takei requested changes

2022-09-30 08:46 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/index.js
> +    applicationInstalled, invitedFormValidator.invitedRules(), invitedFormValidator.invitedValidation, login.invited);
login, register, invited に共通することなんだけど、上の方にある api や logout と同様、router.use を使ってカプセル化してほしい。post とか 1 method の単位でここに書いて行くのは粒度が小さくなりすぎるし、`invitedFormValidator` もここで import しなくて済むようになる。

リファクタは後続タスクでも構わない。

2022-09-30 08:46 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +    }
この処理、ログイン成功の response を受け取ったクライアント側で `/invited` に遷移することを判断していいと思うな。改修はこの PR のスコープでやってほしい。

2022-10-01 08:18 UTC, jam411 commented on packages/app/config/rate-limiter.ts
> +  '/invited': {
エンドポイント名の修正.　他と統一と動詞を使用しない

2022-10-01 08:19 UTC, jam411 commented on packages/app/src/server/routes/apiv3/invited.ts
> +};
例外処理は後続タスク https://redmine.weseek.co.jp/issues/104290

2022-10-01 08:20 UTC, jam411 commented on packages/app/src/server/routes/login.js
> -  };
routes/apiv3/invited.ts へ移動

2022-10-01 08:21 UTC, jam411 commented on packages/app/src/server/routes/login-passport.js
> +    }
まとめるように修正

2022-10-01 08:21 UTC, jam411 commented on packages/app/src/server/routes/apiv3/index.js
> +    applicationInstalled, invitedFormValidator.invitedRules(), invitedFormValidator.invitedValidation, login.invited);
カプセル化もこのPRで改修しました。

2022-10-03 05:49 UTC, yuki-takei requested changes

2022-10-03 05:49 UTC, yuki-takei commented on packages/app/config/rate-limiter.ts
> +  '/invited': {
これって `defaultConfigWithRegExp` の方に入れなくて大丈夫？

2022-10-03 06:49 UTC, jam411 commented on packages/app/config/rate-limiter.ts
> +  '/invited': {
defaultConfigWithRegExp は正規表現用なので問題ないと判断します。

2022-10-03 06:50 UTC, merged