imprv: Return login error msg properly
weseek/growi pull request #6680
Opened 2022-09-29 06:12 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/105658

2022-09-29 07:20 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err(new ErrorV3('message.sign_in_failure'));
master 同様、ここでは `sign_in_failure` のみ表示

`message.strategy_has_not_been_set_up.LdapStrategy'` の表示は、 `/admin/security` で接続テストをした時に表示される実装になっていた

2022-09-29 07:22 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +      return next(new ErrorV3('message.external_account_not_exist'));
Error は new 不要だが ErrorV3 は new 必要だったので追加

2022-09-29 07:44 UTC, yuki-takei requested changes

2022-09-29 07:44 UTC, yuki-takei commented on packages/app/src/interfaces/errors/v3-error.ts
> +export type IErrorV3 = ErrorV3
interfaces 下のソースが models 下のソースに依存するのはやめたい。ただ models/vo ならいいじゃん、というのもわからなくはない。type だけ interfaces 下のソース内に移植するとか上手いこと整理できたらいいんだけど。

2022-09-29 07:44 UTC, yuki-takei commented on packages/app/src/server/models/vo/error-apiv3.js
> +    this.i18nArg = i18nArg;
この改修は複雑になりすぎる。
Error 内容を保持するオブジェクトが i18n について何かしらの責務を持つ(かのような変数を持つ)のはおかしい。

2022-09-29 07:44 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err(new ErrorV3('message.sign_in_failure'));
これ正常系の next でいいんじゃないか？

2022-09-29 07:52 UTC, Yohei-Shiina commented on packages/app/src/server/models/vo/error-apiv3.js
> +    this.i18nArg = i18nArg;
限定的な名前ではなく、汎用的ななめのプロパティに変更する

2022-09-29 07:53 UTC, Yohei-Shiina commented on packages/app/src/server/routes/login-passport.js
> +      return res.apiv3Err(new ErrorV3('message.sign_in_failure'));
たしかに。対応します

2022-09-29 07:54 UTC, Yohei-Shiina commented on packages/app/src/interfaces/errors/v3-error.ts
> +export type IErrorV3 = ErrorV3
口頭FB: v3 としては全体共通なので、core に移動してもいいかもしれない

core/src 配下などなど

2022-10-02 02:57 UTC, Yohei-Shiina commented on packages/app/src/interfaces/errors/v3-error.ts
> +export type IErrorV3 = ErrorV3
/core/src/models/vo 配下に移動

2022-10-02 02:57 UTC, Yohei-Shiina commented on packages/app/src/server/models/vo/error-apiv3.js
> +    this.i18nArg = i18nArg;
argsに変更

2022-10-03 11:17 UTC, yuki-takei requested changes

2022-10-03 11:17 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +        errorsWithDangerouslySetInnerHTML.push(e);
事前に IErrorV3 を引数に、JSX.Element を返すメソッドを用意しておき、
ここではそのメソッドを呼んで `<small dangerouslySetInnerHTML={{ __html: t(err.message, err.args) }} key={index}></small>` 相当を取得する

2022-10-03 11:17 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +        errorsWithoutDanderouslySetInnerHTML.push(e);
ここで
```
            <li key={index}>
              {t(err.message, err.args)}<br/>
            </li>
```
相当を取得する

2022-10-03 11:17 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +        {renderLoginErrors(errorsWithoutDanderouslySetInnerHTML, false)}
ここで取得した JSX.Element 群を表示する

2022-10-03 11:17 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +      if (e.code === LoginErrorCode.PROVIDER_DUPLICATED_USERNAME_EXCEPTION) {
この判定部分はいいとして、セットしてるのはどこ？

2022-10-04 03:15 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +      if (e.code === LoginErrorCode.PROVIDER_DUPLICATED_USERNAME_EXCEPTION) {
修正しました

2022-10-04 05:38 UTC, yuki-takei requested changes

2022-10-04 05:38 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +  };
useCallback 使って

2022-10-04 06:54 UTC, Yohei-Shiina commented on packages/app/src/components/LoginForm.tsx
> +  };
対応済み

2022-10-04 06:55 UTC, merged