imprv: Emoji picker performance master
weseek/growi pull request #6689
Opened 2022-09-30 06:20 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/104273

EmojiPicker のパフォーマンスチューン

2022-09-30 06:46 UTC, hakumizuki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> -  checkWhetherEmojiPickerShouldBeShown() {
廃止

2022-09-30 06:47 UTC, hakumizuki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
>    }
`:` のあとに `shouldLoadEmojiPicker` を満たす文字が入力された場合にのみ `loadEmojiPicker` を呼ぶことで EmojiPicker を表示

2022-09-30 06:48 UTC, hakumizuki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +          onKeyPress={this.keyPressHandler}
KeyPress にすることで表示可能な文字が入力された時のみ handler を呼び出す

2022-09-30 06:49 UTC, hakumizuki commented on packages/app/src/components/PageEditor/EmojiPickerHelper.ts
> +const EMOJI_PATTERN = ':';
Picker で選択した時、コロンを置き換える

e.g. : => :o:

2022-09-30 06:50 UTC, hakumizuki commented on packages/app/src/components/PageEditor/EmojiPickerHelper.ts
>  export default class EmojiPickerHelper {
インデント修正がほとんど

2022-09-30 08:57 UTC, yuki-takei requested changes

2022-09-30 08:57 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    this.loadEmojiPicker(char);
`:` 判定と shouldLoadEmojiPicker を呼ぶ条件に無駄が多い

2022-09-30 12:16 UTC, yuki-takei requested changes

2022-09-30 12:16 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    this.loadEmojiPicker(char);
このメソッドの中身はまるっと emoji 関連のメソッドに切り出して、そのメソッドを keyPressHandler から呼ぶ用にして。

2022-09-30 12:19 UTC, yuki-takei requested changes

2022-09-30 12:19 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    this.loadEmojiPicker(char);
throttle 使う検討を

2022-09-30 12:19 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    this.loadEmojiPicker(char);
isEmojiPickerMode をオフにする条件として、カーソル移動(マウスクリック)をケアした方がいいかもしれない

2022-10-03 04:04 UTC, hakumizuki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    this.loadEmojiPicker(char);
WIP

`onCursorActivity ` でカーソル移動時に mode off するようにしました。

2022-10-03 06:35 UTC, hakumizuki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    this.loadEmojiPicker(char);
throttle は検討しましたが時間がかかりそうだったので後続ストーリーにしました。(https://redmine.weseek.co.jp/issues/106038)

mode off のタイミングとして
、矢印キー押下、バックスペース押下、画面をクリックの３つを追加しました。

2022-10-03 06:37 UTC, hakumizuki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    document.removeEventListener('click', this.windowClickHandler);
onClick が動かなかったのでこうしました。

2022-10-03 06:38 UTC, hakumizuki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +  }
ここで矢印キーやバックスペースで mode off するようにしています

2022-10-03 08:12 UTC, hakumizuki commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    }
`:` を連打した時に mode off にならないように対応しました

2022-10-03 16:42 UTC, yuki-takei approved these changes

2022-10-03 16:42 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +      startPosWithEmojiPickerModeTurnedOn: null,
isEmojiPickerMode が ture になった時のカーソル位置を記憶する state を用意

2022-10-03 16:42 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    this.keyPressHandlerForEmojiPickerThrottled = debounce(50, throttle(200, this.keyPressHandlerForEmojiPicker));
throttle されたイベントが 50ms 遅れで実行されるように設定
(keypress イベントが起こったあと、エディタへの入力が済んでいる状態で emojiPickerHelper.shouldModeTurnOn を評価させるため)

2022-10-03 16:42 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +    this.keyDownHandlerForEmojiPickerThrottled = throttle(400, this.keyDownHandlerForEmojiPicker);
keydown にも throttle を適用する

2022-10-03 16:42 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +        onClick={() => this.showEmojiPicker()}
showEmojiPicker に統一

2022-10-03 16:42 UTC, yuki-takei commented on packages/app/src/components/PageEditor/EmojiPicker.tsx
> +  }, [onClose, onSelected]);
onSelected に統一

2022-10-03 16:42 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +              onSelected={emoji => this.emojiPickerHelper.addEmoji(emoji, this.state.startPosWithEmojiPickerModeTurnedOn)}
startPosWithEmojiPickerModeTurnedOn が null なのか Position インスタンスがあるのかに応じて replace 範囲が変わる

2022-10-03 17:19 UTC, merged