feat: Show page control dropdown in empty page
weseek/growi pull request #6697
Opened 2022-10-03 05:25 UTC by miya

## Task
[#103753](https://redmine.weseek.co.jp/issues/103753) [Next.js] empty page 時に三点ボタンが表示されない
└ [#104409](https://redmine.weseek.co.jp/issues/104409) 修正

2022-10-03 10:59 UTC, yuki-takei requested changes

2022-10-03 10:59 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +                    showPageControlDropdown={isAbleToShowPageManagement || currentPage?.isEmpty}
改修の必要がある場合は useIsAbleToShowPageManagement 側を変えて

2022-10-03 10:59 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/page.js
> +        page = await Page.findByIdAndViewer(pageId, user, null, true);
空ページ時は not found でよい

2022-10-04 04:42 UTC, miya commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +                    showPageControlDropdown={isAbleToShowPageManagement || currentPage?.isEmpty}
FB 通りに修正しました

2022-10-04 04:43 UTC, miya commented on packages/app/src/server/routes/apiv3/page.js
> +        page = await Page.findByIdAndViewer(pageId, user, null, true);
API 側は変更しないようにしました

2022-10-04 05:01 UTC, miya commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +              <div className="h-50">
master と同じ見た目に修正

2022-10-04 05:01 UTC, miya commented on packages/app/src/stores/ui.tsx
> +    () => (isPageExist && !isTrashPage && !isSharedUser) || (isEmptyPage != null && isEmptyPage),
ページ遷移時に空ページかどうかを取得して、ここで参照する

2022-10-04 05:26 UTC, yuki-takei requested changes

2022-10-04 05:26 UTC, yuki-takei commented on packages/app/src/stores/context.tsx
> +};
isNotFound と同じデータしか入らないのならこれは不要

2022-10-04 05:35 UTC, closed without merging