feat: Create activity when shared page is viewed
weseek/growi pull request #6699
Opened 2022-10-03 09:02 UTC by miya

## Task
[#104578](https://redmine.weseek.co.jp/issues/104578) [Next.js] 共有済みページをレンダリングできる
└ [#105499](https://redmine.weseek.co.jp/issues/105499) 共有済みのページを閲覧した時に activity を保存する

2022-10-03 11:19 UTC, yuki-takei requested changes

2022-10-03 11:19 UTC, yuki-takei commented on packages/app/src/pages/share/[[...path]].page.tsx
> +  const action = props.isExpired ? SupportedAction.ACTION_SHARE_LINK_EXPIRED_PAGE_VIEW : props.shareLink == null ? SupportedAction.ACTION_SHARE_LINK_NOT_FOUND : SupportedAction.ACTION_SHARE_LINK_PAGE
読めない。no-nested-ternary を disable すると可読性が落ちる

2022-10-03 11:19 UTC, yuki-takei commented on packages/app/src/pages/utils/commons.ts
> +  const req: CrowiRequest = context.req as CrowiRequest;
ユーティリティに as のコードは入れたくない

2022-10-04 03:51 UTC, miya commented on packages/app/src/pages/share/[[...path]].page.tsx
> +}
ひとまずログの生成処理はここに定義しました

2022-10-04 03:51 UTC, miya commented on packages/app/src/pages/share/[[...path]].page.tsx
> +  await addActivity(context, action);
簡潔にしました

2022-10-04 03:52 UTC, miya commented on packages/app/src/pages/utils/commons.ts
> +  const req: CrowiRequest = context.req as CrowiRequest;
pages/share/[[...path]].tsx に書きました

2022-10-04 03:52 UTC, miya commented on packages/app/src/pages/share/[[...path]].page.tsx
> +  const action = props.isExpired ? SupportedAction.ACTION_SHARE_LINK_EXPIRED_PAGE_VIEW : props.shareLink == null ? SupportedAction.ACTION_SHARE_LINK_NOT_FOUND : SupportedAction.ACTION_SHARE_LINK_PAGE
読めるように修正しました

2022-10-04 05:32 UTC, yuki-takei requested changes

2022-10-04 05:32 UTC, yuki-takei commented on packages/app/src/pages/share/[[...path]].page.tsx
> +  await addActivity(context, action);
この PR でも後続タスクでもいいのでリファクタして。

- このロジックは切り出す新たにメソッドを定義して切り出す(getServerSideProps が長くならないように)
- try-catch の例外処理が全く書かれていないので追加する

2022-10-04 06:30 UTC, miya commented on packages/app/src/pages/share/[[...path]].page.tsx
> +  await addActivity(context, action);
- action 取得するロジックをメソッドとして切り出しました
- エラー時に logger.error を吐くようにしました

2022-10-04 06:47 UTC, merged