imprv: Add style for code element
weseek/growi pull request #6704
Opened 2022-10-04 05:19 UTC by Yohei-Shiina

2022-10-04 05:50 UTC, yuki-takei requested changes

2022-10-04 05:50 UTC, yuki-takei commented on packages/app/src/styles/atoms/_code.scss
> +}
CodeBlock.module.scss の `.code-inline` をこのファイルに移植し、それを `:not(pre) > code` に適用してください。
CodeBlock.module.scss 側も同様にこのファイルの .code-inline を引っ張ってくるように。

2022-10-04 05:50 UTC, yuki-takei commented on packages/app/src/styles/theme/_apply-colors.scss
> +}
apply-colors 内も `.code-inline` と共通化してください。

2022-10-11 05:38 UTC, Yohei-Shiina commented on packages/app/src/styles/theme/_apply-colors.scss
> +}
>.code-inline と共通化
これがよくわかりませんでした。

ここは配色だけが責務だと思うので、`/atoms/_mixin.scss` に色付けの処理を切り出して、引数を渡して処理するように変更しました

2022-10-11 05:39 UTC, Yohei-Shiina commented on packages/app/src/styles/atoms/_code.scss
> +}
`/atoms/_mixin.scss` に mixin として `.code-inline` のスタイルを切り出しで、
`styles/_code.scss` と `CodeBlock.module.scss` から使うよ修正しました

2022-10-11 05:40 UTC, Yohei-Shiina commented on packages/app/src/styles/atoms/_mixins.scss
> +}
色以外のスタイル

2022-10-11 05:40 UTC, Yohei-Shiina commented on packages/app/src/styles/atoms/_mixins.scss
> +}
色のスタイル

2022-10-11 06:34 UTC, yuki-takei requested changes

2022-10-11 06:34 UTC, yuki-takei commented on packages/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
> +@use '~/styles/atoms/mixins' as c;
`as c` なくてよいかと

2022-10-11 06:34 UTC, yuki-takei commented on packages/app/src/styles/atoms/_code.scss
> +@use '~/styles/atoms/mixins' as c;
`as c` なくてよいかと

2022-10-11 06:34 UTC, yuki-takei commented on packages/app/src/styles/atoms/_code.scss
> +}
mixin もここに含んでいいと思う。`atoms/_mixins.scss` になんでもかんでも入れるより、code 関連をこのファイルにまとめたい。

2022-10-11 09:49 UTC, Yohei-Shiina commented on packages/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
> +@use '~/styles/atoms/mixins' as c;
対応済み

2022-10-11 09:49 UTC, Yohei-Shiina commented on packages/app/src/styles/atoms/_code.scss
> +@use '~/styles/atoms/mixins' as c;
対応済み

2022-10-11 10:26 UTC, merged