feat: Enable styles for PageAccessoriesModal diffs
weseek/growi pull request #6723
Opened 2022-10-11 07:23 UTC by jam411

タスク:

2022-10-11 10:05 UTC, jam411 commented on packages/app/src/styles/style-next.scss
> +@import '~diff2html/bundles/css/diff2html.min.css';
diff2html.min.css のインポート

2022-10-12 01:45 UTC, jam411 commented on packages/app/src/components/PageHistory.tsx
> +  const { data: revisionsData } = useSWRxPageRevisions(activePage, 10, currentPageId);
currentPageId が Nullableのため useSWRxPageRevisions hooksの型と引数の順序変更

2022-10-12 01:50 UTC, jam411 commented on packages/app/src/components/PageHistory/RevisionDiff.tsx
> +      currentRevision.pageId, // currentRevision.path is DEPRECATED
ここで pageId を使用するので `IRevisionHasPageId`

2022-10-12 01:53 UTC, jam411 commented on packages/app/src/stores/page.tsx
> +    pageId: string | null | undefined,
`page.tsx` にある他の hooks 同様に pageId の型を nullable に変更

2022-10-12 09:21 UTC, yuki-takei requested changes

2022-10-14 06:52 UTC, jam411 commented on packages/core/src/interfaces/revision.ts
> +  revisions: IRevisionHasPageId[], // revisions in one pagination
`IRevisionHasPageId`に修正しました

2022-10-14 06:57 UTC, jam411 commented on packages/app/src/components/PageHistory.tsx
> +        targetRevision={targetRevision as IRevisionHasPageId}
`PageHistory.tsx`でしか使用されない swr hooks だったので revision.ts 側を修正
[revision.ts](https://github.com/weseek/growi/pull/6723/files#diff-b0cc8eb9fa547c7b1e4201621a4a1f07922dfa8a65b1807e131c5fd51ba51d6f)

2022-10-14 06:59 UTC, jam411 commented on packages/app/src/components/PageHistory/RevisionDiff.tsx
> +import 'diff2html/bundles/css/diff2html.min.css';
scssでインポートがうまくいかなかったので、tsx側で css インポート

2022-10-14 09:15 UTC, merged