feat: 106322 create hackmd directory in packages
weseek/growi pull request #6732
Opened 2022-10-12 09:32 UTC by yukendev

https://redmine.weseek.co.jp/issues/106322

2022-10-12 09:57 UTC, yukendev commented on packages/hackmd/src/hackmd-agent.js
> +/**
このファイルの内容は`packages/app/src/client/hackmd-agent.js`の内容を全てコピーしただけです

2022-10-12 09:58 UTC, yukendev commented on packages/hackmd/src/hackmd-styles.js
> +/**
このファイルの内容は`packages/app/src/client/hackmd-styles.js`の内容を全てコピーしただけです

2022-10-12 11:23 UTC, yukendev commented on packages/hackmd/src/styles.scss
> +.navbar-header {
webpackでバンドル化したこのファイルをhackmd側に渡しているだけだったので、appの中にある必要がないと判断しここに移動しました

2022-10-13 04:01 UTC, yuki-takei requested changes

2022-10-13 04:19 UTC, yukendev commented on packages/hackmd/package.json
> +    "throttle-debounce": "^3.0.1"
修正済み

2022-10-13 04:21 UTC, merged