fix: Admin customize code highlight cannot be changed
weseek/growi pull request #6733
Opened 2022-10-12 10:19 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/106061

<img width="484" alt="image" src="https://user-images.githubusercontent.com/35527421/195317417-bd5a4180-57bc-40a8-8151-2db6959b5fa7.png">

<img width="477" alt="image" src="https://user-images.githubusercontent.com/35527421/195317497-e924f952-3275-426e-8a0a-05e7e919a299.png">

2022-10-12 10:22 UTC, Yohei-Shiina commented on packages/app/src/styles/_wiki.scss
> +.wiki {
styleが当たっていなかったので、ついでに有効化

2022-10-12 10:23 UTC, Yohei-Shiina commented on packages/app/src/services/cdn-resources-service.js
> +  #generateAttributesForStyleTag(manifest) {
ココでしか使われないはずなので private として実装
中身は `generateStyleTag` メソッド から丸ごと移植した

2022-10-12 10:23 UTC, Yohei-Shiina commented on packages/app/src/services/cdn-resources-service.js
> +const urljoin = require('url-join');
自動整形なので無視OK

2022-10-12 10:27 UTC, Yohei-Shiina commented on packages/app/src/pages/admin/[[...path]].page.tsx
> +      component: <CustomizeSettingContents attrsForCdnHighlightJsStyleLinkeTag={props.attrsForCdnHighlightJsStyleLinkeTag}/>,
特に使いまわしを想定していないので swr でキャッシュせずにバケツリレーにしている
(swrの方が良いだろうか…)

2022-10-12 10:43 UTC, Yohei-Shiina commented on packages/app/src/services/cdn-resources-service.js
> +    return this.#generateAttributesForStyleTag(manifest);
next化前は `this.generateStyleTag` でhtml の文字列(`"<link rel="stylesheet" href={url} ... />"`)を返して swig に入れていたが、文字列は返さず、 link タグに必要なデータのみ返すようにした

2022-10-12 10:47 UTC, Yohei-Shiina commented on packages/app/src/components/Admin/Customize/CustomizeHighlightSetting.tsx
> +        <link rel="stylesheet" href={url} {...attrs} />
ココの代替：https://github.com/weseek/growi/blob/dev/5.1.x/packages/app/src/server/views/admin/customize.html#L20-L22

2022-10-13 04:21 UTC, yuki-takei requested changes

2022-10-13 04:21 UTC, yuki-takei commented on packages/app/src/styles/_wiki.scss
> +.wiki {
hljs 適用方法が変わったのでこれは不要
`react-syntax-highlighter` を使っているコードを検索

2022-10-17 03:36 UTC, Yohei-Shiina commented
Close this and new pr will take care of this fix

2022-10-17 03:36 UTC, closed without merging