fix: Normalize Customize HTML Header
weseek/growi pull request #6734
Opened 2022-10-12 10:59 UTC by miya

## Task
[#103178](https://redmine.weseek.co.jp/issues/103178) [Next.js][Admin][Customize][コードハイライト以外] 各種設定の更新ができる
└ [#106124](https://redmine.weseek.co.jp/issues/106124) カスタムHTMLヘッダー

2022-10-12 11:07 UTC, miya commented on packages/app/src/pages/_document.page.tsx
> +          { JSON.parse(customizeHeaderDocument.value) }
- 登録されたカスタムヘッダーが正常に適用されていなかったため修正
- crowi 等をとってこれなかたったので、`feat/new-plugin` を参考に mongoose を使って直に config を取得している

2022-10-13 04:37 UTC, yuki-takei requested changes

2022-10-13 04:37 UTC, yuki-takei commented on packages/app/src/pages/_document.page.tsx
> +    const customizeHeaderDocument = await ConfigModel.findOne({ key: 'customize:header' }) as unknown as Config;
null チェックが必要では？

2022-10-13 05:23 UTC, miya commented on packages/app/src/pages/_document.page.tsx
> +    const customizeHeaderDocument = await ConfigModel.findOne({ key: 'customize:header' }) as unknown as Config;
すみません null チェックを追加しました

2022-12-19 02:47 UTC, closed without merging