support: 106321 refactor hackmd routing
weseek/growi pull request #6738
Opened 2022-10-13 04:23 UTC by yukendev

https://redmine.weseek.co.jp/issues/106321

2022-10-13 09:33 UTC, yukendev commented on packages/hackmd/src/index.js
> +// export to app as string
`/packages/hackmd`で必要なファイルを文字列にして、moduleとしてexportするようにしました

2022-10-13 11:36 UTC, yukendev commented on packages/app/package.json
> +    "resources:hackmd": "yarn lerna run build --scope=@growi/hackmd",
`predev`, `predev: ci`の時に`packages/hackmd`のビルドが走るようにしました

2022-10-13 13:04 UTC, yuki-takei requested changes

2022-10-13 13:04 UTC, yuki-takei commented on packages/hackmd/src/hackmd-agent.js
> +const allowedOrigin = '<%= origin %>'; // will be replaced by swig
コメントも変えてください

2022-10-14 01:19 UTC, yukendev commented on packages/hackmd/src/hackmd-agent.js
> +const allowedOrigin = '<%= origin %>'; // will be replaced by swig
修正済み

2022-10-14 01:20 UTC, merged