imprv: Show OptionsSelector
weseek/growi pull request #6741
Opened 2022-10-13 14:05 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/106264

OptionsSelector  が表示されるように修正

# 後続タスク
- `fallbackData` が `undefined` でも動くようなコードにする
  - SWR 周りの抜本改修待ち

2022-10-13 14:06 UTC, hakumizuki commented on packages/app/src/stores/editor.tsx
> +  return withUtils<EditorSettingsOperation, IEditorSettings, Error>(swrResult, {
withUtils を使用

2022-10-13 14:06 UTC, hakumizuki commented on packages/app/src/stores/ui.tsx
> +  useEffect(() => {
DOMContentLoaded イベントは SSR だと発火を検知できないので、useEffect に書き換え

2022-10-14 10:53 UTC, jam411 commented
歯車部分（`grw-editor-configuration-dropdown` class）以外の動作確認をし設定も引き継がれており問題なかった。
歯車部分は後続タスク[106623](https://redmine.weseek.co.jp/issues/106623)。
一点だけ、keymap で打鍵ごとにLoading Keymapされる 事象があった。 タスク:[106654](https://redmine.weseek.co.jp/issues/106654)
![keymap_log](https://user-images.githubusercontent.com/68407388/195826924-82d57638-eb5d-4182-989a-daf7ec253952.gif)

2022-10-17 08:45 UTC, yuki-takei requested changes

2022-10-17 08:45 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +      const mql = addBreakpointListener(Breakpoint.MD, mdOrAvobeHandler);
今気付いたけど、新旧どちらのコードでもこれの cleanup 必要なんじゃないかな

2022-10-18 05:52 UTC, hakumizuki commented on packages/app/src/stores/ui.tsx
> +      const mql = addBreakpointListener(Breakpoint.MD, mdOrAvobeHandler);
cleanup を実装しました

2022-10-18 06:08 UTC, merged