feat: gw7833 create bookmarkfolder model and api
weseek/growi pull request #6778
Opened 2022-10-19 11:11 UTC by mudana-grune

https://youtrack.weseek.co.jp/issue/GW-7833

2022-10-20 10:16 UTC, kaoritokashiki commented on packages/app/src/server/models/bookmark-folder.ts
> +  return bookmarkFolder;
https://mongoosejs.com/docs/tutorials/findoneandupdate.html
> You should set the new option to true to return the document after update was applied. 👏🏻

new オプション知らなかった。

2022-10-20 10:25 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/bookmark-folder.ts
> +      return res.apiv3();
これは `res.apiv3();` だけを返すのはありなのだろうか

2022-10-20 10:30 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/bookmark-folder.ts
> +      return res.apiv3();
`res.apiv3();` だけを返すのはベストな方法なのだろうか??

ただ、他にも同じようにしているところがある
![Screen Shot 2022-10-20 at 19 25 56](https://user-images.githubusercontent.com/59536731/196924487-3b4b084a-d6a4-43ec-bfb9-52dd09bb6802.png)

2022-10-20 10:32 UTC, kaoritokashiki commented
@mudana-grune  
Please fix lint errors

2022-10-20 10:47 UTC, yuki-takei requested changes

2022-10-20 10:47 UTC, yuki-takei commented on packages/app/src/server/models/bookmark-folder.ts
> +  const parentFolder = await this.findById(parent);
This method should throw an error when the specified ID of the parent is invalid. Please create a custom error class that extends `ExtensibleCustomError`

2022-10-20 10:47 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/bookmark-folder.ts
> +      return res.apiv3Err(err, 500);
上でコメントした createByParameters が invalid parent exception を投げる場合に対応すべき。
それ以外のエラーの場合は結局原因不明なのでこのコードでいいと思う。

2022-10-20 10:47 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/bookmark-folder.ts
> +      return res.apiv3();
delete の正常終了時はまあこれでもいいけど、欲を言えば何件削除されたとかっていう結果がわかるといいなあ。(コストが高ければ見送りで良い)

2022-10-25 04:05 UTC, kaoritokashiki requested changes

2022-10-25 04:05 UTC, kaoritokashiki commented on packages/app/src/server/models/bookmark-folder.ts
> +  }
I think you are misunderstanding about Yuki San's FB.

`parent` variable passed from client side might be invalid value like `111` `aaa` not mongoose object id.
That's why we need to check the value is valid and it's exactly exist.

2022-10-25 04:05 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/bookmark-folder.ts
> +      return res.apiv3Err(err, 500);
理解いたしました!

2022-10-25 04:05 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/bookmark-folder.ts
> +      return res.apiv3();
Could you return the number of deleted bookmarks?
(If it take time, you don't need to handle this.)

2022-10-31 07:41 UTC, kaoritokashiki requested changes

2022-10-31 07:41 UTC, kaoritokashiki commented on packages/app/src/server/models/bookmark-folder.ts
> +    }
parentFolder should be nullable.
If you have any questions, please ask me.

2022-10-31 07:41 UTC, kaoritokashiki commented on packages/app/src/server/models/bookmark-folder.ts
> +export class InvalidParentBookmarkFolder extends ExtensibleCustomError {}
Please declare on `server/models/errors.ts` and add `Error` to the suffix.

2022-11-01 07:55 UTC, kaoritokashiki commented on packages/app/src/server/models/bookmark-folder.ts
> +import { ErrorInvalidParentBookmarkFolder } from './errors';
sorry, it should be `InvalidParentBookmarkFolderError`

2022-11-01 07:55 UTC, kaoritokashiki commented on packages/app/src/server/models/bookmark-folder.ts
> +    }
we can create a new folder even if the parentFolder is null. 

so when parentFolder is null, I think the error should not be thrown.

 (parentFolder != null && !isParentFolderIdValid)
i think the err should be thrown in the above case

2022-11-01 07:58 UTC, kaoritokashiki commented on packages/app/src/server/models/bookmark-folder.ts
> +    }
if you have any problems, please share.

2022-11-01 18:09 UTC, kaoritokashiki requested changes

2022-11-01 18:28 UTC, kaoritokashiki requested changes

2022-11-15 06:38 UTC, kaoritokashiki approved these changes

2022-11-15 06:38 UTC, merged