feat: check storage limit before g2g
weseek/growi pull request #6779
Opened 2022-10-19 13:26 UTC by mizozobu

- [x] 移行先のストレージ容量が添付ファイルの合計容量を上回っていた場合、転送が開始できないとして処理を終了し、エラーをクライアントに表示する

https://redmine.weseek.co.jp/issues/106571

2022-10-19 13:29 UTC, mizozobu commented on packages/app/src/components/Admin/G2GDataTransfer.tsx
> -      await customAxios.post('/_api/v3/g2g-transfer/transfer', {
`apiv3Post`使ってなかった理由あります？

2022-10-19 13:29 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> +    const userUpperLimit = configManager.getConfig('crowi', 'security:userUpperLimit');
userの上限ではなく現在のuser数の方いいのでは？と思いました。

2022-10-20 08:00 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +    const userUpperLimit = configManager.getConfig('crowi', 'security:userUpperLimit');
オレもそう思った。

2022-10-20 08:00 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +        reason: `Growi versions mismatch. From: ${version}, To: ${toGROWIInfo.version}.`,
これ、UI に出すこと考えたら i18n の message key とかにしたほうがいいんじゃない？

2022-10-20 08:24 UTC, hakumizuki commented on packages/app/src/components/Admin/G2GDataTransfer.tsx
> -      await customAxios.post('/_api/v3/g2g-transfer/transfer', {
ないです。`apiv3Post` の方が良いです

2022-10-20 08:39 UTC, hakumizuki commented on packages/app/src/server/service/g2g-transfer.ts
> +    const userUpperLimit = configManager.getConfig('crowi', 'security:userUpperLimit');
自分もそう思います。

2022-10-20 08:45 UTC, hakumizuki commented on packages/app/src/server/service/g2g-transfer.ts
> +        reason: `Growi versions mismatch. From: ${version}, To: ${toGROWIInfo.version}.`,
できればそれがいいですが、GROWI であんまそういうことやってるとこまだないので面倒だったら TODO で OK です

2022-10-20 14:46 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> +    : configManager.getConfig('crowi', 'app:fileUploadTotalLimit');
そうしました

2022-10-20 14:46 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> +        reason: `Growi versions mismatch. From: ${version}, To: ${toGROWIInfo.version}.`,
TODOコメつけときました

2022-10-20 14:47 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> +    const userUpperLimit = configManager.getConfig('crowi', 'security:userUpperLimit');
active user数に変えました

2022-10-20 20:14 UTC, skomma commented on packages/app/src/server/service/config-manager.ts
> +      // Use app:fileUploadTotalLimit if gridfs:totalLimit is null (default for gridfs:totalLimitd is null)
```suggestion
      // Use app:fileUploadTotalLimit if gridfs:totalLimit is null (default for gridfs:totalLimit is null)
```

2022-10-20 20:14 UTC, skomma commented on packages/app/src/server/service/config-manager.ts
> +      // Use app:fileUploadTotalLimit if gridfs:totalLimit is null (default for gridfs:totalLimitd is null)
なんでこんなことしてるかわからなくなりそうだから、ここと同じコードを使ってるってコメントしておいた方がいいなぁ。

https://github.com/weseek/growi/blob/f4fc5ed1fa2c145bcbf518b8f96ce54f5445a517/packages/app/src/server/service/file-uploader/gridfs.js#L89 (Commit ID 適当なので、なんか適切なものに変えてほしい)

2022-10-24 07:04 UTC, hakumizuki requested changes

2022-10-24 07:04 UTC, hakumizuki commented on packages/app/src/server/service/g2g-transfer.ts
> +        reason: `Total file size exceeds file upload limit of new Growi. Requires ${totalFileSize.toLocaleString()} bytes, but got ${toGROWIInfo.fileUploadTotalLimit!.toLocaleString()} bytes.`,
`toGROWIInfo.fileUploadTotalLimit` が `null` のとき throw されそうなので、そのケアお願いします。

2022-10-24 10:05 UTC, merged