fix: Modal styles and Enable Lato font
weseek/growi pull request #6794
Opened 2022-10-20 15:00 UTC by jam411

タスク:https://redmine.weseek.co.jp/issues/107009

- Modal のスタイル修正
- 過程で, Lato font が効いてなかったことがわかったので適用してみました

## Before
![image](https://user-images.githubusercontent.com/68407388/196983297-ada21f1a-1db6-4c43-a58a-7b5bfc369048.png)

## After
![image](https://user-images.githubusercontent.com/68407388/196981524-82e9413d-26e8-44bf-84ec-d943dce60cbc.png)

- ただ、fontの影響範囲が大きいのでほかのスタイル崩れが発生する場合あり（こっちを修正したい）
![image](https://user-images.githubusercontent.com/68407388/196984665-9f4e8224-462c-4bd8-b940-5f4f9f9399c1.png)

2022-10-20 15:05 UTC, jam411 commented on packages/app/src/styles/_layout.scss
> +  // font-size: 1em;
v5でも同じ内容のプロパティでしたが、このセレクタのfont-sizeは .grw-modal-head を使っている要素で有効化されていなかったため。デグレ予防にコメントアウトにした。

2022-10-21 02:20 UTC, jam411 commented on packages/app/src/pages/_document.page.tsx
> +/* eslint-disable @next/next/google-font-display */
公式
https://nextjs.org/docs/messages/google-font-display

2022-10-21 06:01 UTC, yuki-takei requested changes

2022-10-21 06:01 UTC, yuki-takei commented on packages/app/src/pages/_document.page.tsx
> +          />
CDN 使わない方針にするので別ストーリーにする

2022-10-21 06:01 UTC, yuki-takei commented on packages/app/src/styles/_layout.scss
> +  // font-size: 1em;
使わないなら消してください
残す意味があるならコード内コメントを追加して

2022-10-23 03:35 UTC, jam411 commented on packages/app/src/pages/_document.page.tsx
> +          />
別コミットで Lato セルフホスト済み

2022-10-23 03:35 UTC, jam411 commented on packages/app/src/styles/_layout.scss
> +  // font-size: 1em;
削除しました

2022-10-23 03:54 UTC, merged