feat: isolate hackmd from app
weseek/growi pull request #6796
Opened 2022-10-21 05:37 UTC by yukendev

https://redmine.weseek.co.jp/issues/106758

2022-10-21 05:38 UTC, yukendev commented on packages/app/package.json
> +    "ejs": "^3.1.8",
hackmdから取得したstringのjsファイルにoriginなどの文字を埋め込む必要があったので、appのpackage.jsonにejsを追加しました。

2022-10-21 06:20 UTC, yukendev commented on packages/hackmd/src/index.js
> +
esmの形式だとうまくいかなかったため、cjsの形式で書いています

2022-10-21 17:57 UTC, yuki-takei requested changes

2022-10-21 17:57 UTC, yuki-takei commented on packages/hackmd/package.json
> +    "build": "vite build && cp ./src/index.js ./dist"
他のパッケージを参考に、`npx -y shx cp` を使ってください

2022-10-24 04:39 UTC, yukendev commented on packages/hackmd/package.json
> +    "build": "vite build && cp ./src/index.js ./dist"
修正済み

2022-10-24 05:13 UTC, merged