fix: Unable to update empty pages
weseek/growi pull request #6808
Opened 2022-10-23 14:27 UTC by miya

## Task
[#106890](https://redmine.weseek.co.jp/issues/106890) [Nextjs] 空ページの更新ができない
└ [#107222](https://redmine.weseek.co.jp/issues/107222) 修正

2022-10-23 14:34 UTC, miya commented on packages/app/src/server/routes/page.js
> +    let page = await Page.findByIdAndViewer(pageId, req.user, null, true);
empty page も引っかかるように

2022-10-23 14:34 UTC, miya commented on packages/app/src/server/routes/page.js
> +      return res.json(ApiResponse.error('pageId and paegBody are required.'));
`revisionId` が null なのは許容する

2022-10-23 14:34 UTC, miya commented on packages/app/src/server/routes/page.js
> +    }
empty page だった場合新しく revision を作成する

2022-10-23 14:34 UTC, miya commented on packages/app/src/server/routes/page.js
> +    }
empty page だった場合、false を入れる

2022-10-23 14:34 UTC, miya commented on packages/app/src/client/services/page-operation.ts
> +    if (!isEmpty && revisionId == null) {
- not empty かつ revison が無い場合はエラーを throw する
- empty page、通常ページは updatePage できる

2022-10-24 14:56 UTC, yuki-takei requested changes

2022-10-25 05:13 UTC, miya commented on packages/app/src/client/services/page-operation.ts
> +  const isEmpty = pageId != null && isNotFound;
この boolean は消しました

2022-10-25 05:16 UTC, miya commented on packages/app/src/client/services/page-operation.ts
> +  if (pageId == null || (pageId != null && revisionId == null)) {
page document は存在するが、revisionId が存在しないページを empty page とし、createPage に投げるようにしました。

2022-10-27 03:09 UTC, hakumizuki commented on packages/app/src/client/services/page-operation.ts
> +  if (pageId == null || (pageId != null && revisionId == null)) {
これユーティリティに切り出しましょう。`isNoRevisionPage` とかですかね。実装は以下のような感じがいいと思ってます。これちょっと改良必要ですが

```typescript
interface PageWithRevisionId {
    pageId: string,
    revisionId: string,
}

const isPageWithRevisionId = (val: any): val is PageWithRevisionId => {
    return typeof val.revisionId === 'string' && typeof val.pageId === 'string';
};

```

2022-10-27 04:36 UTC, merged