imprv: Refactoring admin pages map
weseek/growi pull request #6818
Opened 2022-10-24 05:31 UTC by kaoritokashiki

2022-10-24 18:07 UTC, kaoritokashiki commented on packages/app/src/utils/admin-page-util.ts
> +};
retrieveServerSideProps を　util 化

2022-10-24 18:08 UTC, kaoritokashiki commented on packages/app/src/pages/admin/app.page.tsx
> +};
これは後ほど interface file配下に移していろんなところで使えるようにします

2022-10-24 18:09 UTC, kaoritokashiki commented on packages/app/src/pages/admin/app.page.tsx
> +  return <AdminPage title={t('commons:headers.app_settings')} component={<AppSettingsPageContents />} {...props}/>;
AdminPage component に title, 表示したいcomponent props を渡す

2022-10-24 18:10 UTC, kaoritokashiki commented on packages/app/src/components/Layout/AdminLayout.tsx
> +                <AdminNavigation />
AdminNavigation  の中で pathを取得していたので、selectedNavOptは不要でした

2022-10-24 18:24 UTC, yuki-takei requested changes

2022-10-24 18:24 UTC, yuki-takei commented on packages/app/src/utils/admin-page-util.ts
> +}
この中身は各ページ毎に必要最低限のものにすればいいんじゃないかな

2022-10-24 18:24 UTC, yuki-takei commented on packages/app/src/pages/admin/app.page.tsx
> +  return <AdminPage title={t('commons:headers.app_settings')} component={<AppSettingsPageContents />} {...props}/>;
AdminPage でやってることはこのページでやればいいと思う。つまり AdminPage は不要じゃないかな。

2022-10-25 05:02 UTC, kaoritokashiki commented on packages/app/src/utils/admin-page-util.ts
> +}
畏まりました。そのように修正します。

2022-10-26 17:20 UTC, kaoritokashiki commented on packages/app/src/utils/admin-page-util.ts
> +export const retrieveServerSideProps = async(context: GetServerSidePropsContext, injectServerConfigurations?:(context: GetServerSidePropsContext, props) => Promise<void> ) => {
第二引数に、optionで injectServerConfigurations を取れるようにしました。

2022-10-26 17:38 UTC, kaoritokashiki commented on packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> -const GeneratingTokensAndRegisteringProxyServiceProcess = withUnstatedContainers((props) => {
どこにも Container が使われていなかったので削除しました。

2022-10-27 04:56 UTC, kaoritokashiki commented on packages/app/src/pages/admin/app.page.tsx
> +const AdminAppPage: NextPage<CommonProps> = (props) => {
特にinjectする必要がないものは、 CommonProps のみを受け取ります。
CommonProps は　retrieveServerSideProps　の中でinject されます。

2022-10-27 04:57 UTC, kaoritokashiki commented on packages/app/src/pages/admin/audit-log.page.tsx
> +};
CommonProps 以外に各ページで必要なPropsを定義するように改修しています。
(audit-log はaudit-log に必要なものだけをPropsで受け取る)

2022-10-27 04:58 UTC, kaoritokashiki commented on packages/app/src/pages/admin/audit-log.page.tsx
> +};
audit-log page だけに必要な 値を Server side からClient側にprops で渡しています。

2022-10-27 05:02 UTC, kaoritokashiki commented on packages/app/src/pages/admin/customize.page.tsx
> +  }
unstated Container を使用しているページは。 Provider の injectに挿入しています。
Q. `injectableContainers` 現在配列で格納していますが、一つだけにした方が良いかも?ですね。
恐らく将来的にContainerが複数必要になることもなさそうですし

2022-10-27 05:02 UTC, kaoritokashiki commented on packages/app/src/utils/admin-page-util.ts
> +    context: GetServerSidePropsContext, injectServerConfigurations?:(context: GetServerSidePropsContext, props) => Promise<void>,
`injectServerConfigurations` を第２引数で受け取るようにしました。

2022-10-27 06:01 UTC, merged