modify pagelist mutate method
weseek/growi pull request #6820
Opened 2022-10-24 06:52 UTC by yukendev

2022-10-24 06:57 UTC, yukendev commented on packages/app/src/components/EmptyTrashButton.tsx
> +  const { data: pagingResult, mutate } = useSWRxDescendantsPageListForCurrrentPath(1, limit);
`TrashPageList`で管理している`DescendantsPageListForCurrentPath`とswrのkeyをそろえることで、空にした後にページがリロードされるようにしました。

2022-10-25 06:16 UTC, hakumizuki commented on packages/app/src/components/EmptyTrashButton.tsx
> +  emptyTrashClickHandler: () => void,
他のコンポーネントの慣習に併せて `onEmptyTrashButtonClick` にしよう

2022-10-25 06:27 UTC, hakumizuki requested changes
もうちょい綺麗にできる

2022-10-25 06:27 UTC, hakumizuki commented on packages/app/src/components/EmptyTrashButton.tsx
>          onClick={() => emptyTrashClickHandler()}
直渡しでもいいとは思うんだけど、以下の２点から俺はコンポーネントのローカル関数にしちゃう派です。

1. `useCallback` でメモ化できる

2. 他の処理を書きたくなった時に関数にまとめられる

2022-10-25 06:27 UTC, hakumizuki commented on packages/app/src/components/TrashPageList.tsx
> +  const convertToIDataWithMeta = (page) => {
メモ化せい

2022-10-25 06:27 UTC, hakumizuki commented on packages/app/src/components/TrashPageList.tsx
> +  const { injectTo } = useSWRxPageInfoForList(pageIds, null, true, true);
ここら辺はカスタムフックにしがいがありそう。SOLID の S を意識してみてくれ

2022-10-25 08:20 UTC, yukendev commented on packages/app/src/components/EmptyTrashButton.tsx
> +  emptyTrashClickHandler: () => void,
修正済み

2022-10-25 08:23 UTC, yukendev commented on packages/app/src/components/EmptyTrashButton.tsx
>          onClick={() => emptyTrashClickHandler()}
修正済み

2022-10-25 08:24 UTC, yukendev commented on packages/app/src/components/TrashPageList.tsx
> +  const convertToIDataWithMeta = (page) => {
修正済み

2022-10-25 08:24 UTC, yukendev commented on packages/app/src/components/TrashPageList.tsx
> +  const { injectTo } = useSWRxPageInfoForList(pageIds, null, true, true);
修正済み

2022-10-25 08:39 UTC, yukendev commented on packages/app/src/components/TrashPageList.tsx
> +type EmptyTrashButtonOptions = {
ゴミ箱を空にするボタンに関するロジックをまとめています

2022-10-26 10:49 UTC, hakumizuki requested changes

2022-10-26 10:49 UTC, hakumizuki commented on packages/app/src/components/TrashPageList.tsx
> +  const convertToIDataWithMeta = useCallback((page) => {
これ hook の外出して

2022-10-27 05:13 UTC, merged