fix: refactor empty trash operation
weseek/growi pull request #6835
Opened 2022-10-26 07:46 UTC by yukendev

https://redmine.weseek.co.jp/issues/107353

2022-10-26 08:40 UTC, yukendev commented on packages/app/src/server/service/page.ts
> +    if (originPage != null && isRecursively === true) {
同じパスのページがすでにあってエラーを返すのは`isRecursively = true`の時のみで十分なので`isRecursively = false`の時はスルーします

2022-10-26 08:41 UTC, yukendev commented on packages/app/src/server/service/page.ts
> +    else {
elseの条件の中は、既存の実装をコピペしてます

2022-10-26 08:43 UTC, yukendev commented on packages/app/src/server/service/page.ts
> +    if (originPage != null) {
パスがかぶっているページがあるときは、ゴミ箱のページの情報をアップデートした後に、同じパスの空ページと位置を入れ替える処理をしています

2022-10-26 09:00 UTC, yukendev commented on packages/app/src/server/service/page.ts
> +    if ((originPage != null && !originPage.isEmpty) || isRecursively === true) {
- `isRecursively === true`の場合、同じパスがあったら問答無用でエラーを投げる
- 同じパスがあるが`empty`の場合、下の処理でページの入れ替えを行うためエラーは投げずに次の処理へ進む
- 同じパスがあり、`empty`ではない場合、ページの入れ替えは行えないため、エラーを投げる

2022-10-26 09:14 UTC, yukendev commented on packages/app/src/server/service/page.ts
> +    if (originPage != null && (!originPage.isEmpty || isRecursively === true)) {
- isRecursively === trueの場合、同じパスがあったら問答無用でエラーを投げる
- 同じパスがあるがemptyの場合、下の処理でページの入れ替えを行うためエラーは投げずに次の処理へ進む
- 同じパスがあり、emptyではない場合、ページの入れ替えは行えないため、エラーを投げる

2022-10-26 10:15 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    if (originPage != null && (!originPage.isEmpty || isRecursively === true)) {
`isRecursively === true` => `isRecursively` に

2022-10-26 10:19 UTC, hakumizuki requested changes

2022-10-26 10:19 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    if (originPage != null && (!originPage.isEmpty || isRecursively === true)) {
`isRecursively === true` => `isRecursively` に

2022-10-26 10:19 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    if (originPage != null) {
意味不

2022-10-26 10:19 UTC, hakumizuki commented on packages/app/src/server/service/page.ts
> +    else {
リファクタよろ

2022-10-28 02:04 UTC, yukendev commented on packages/app/src/components/PutbackPageModal.jsx
> +
エラーがあるとき、モーダルを閉じても再度表示するときエラーが出たままという不具合があったので修正しました

2022-10-28 06:43 UTC, merged