feat: 106971 106972 Update PageAccessories modal for next routing
weseek/growi pull request #6836
Opened 2022-10-26 09:18 UTC by jam411

タスク: [106971](https://redmine.weseek.co.jp/issues/106971)

2022-10-26 09:25 UTC, jam411 commented on packages/app/src/stores/attachment.tsx
> +  useEditingMarkdown(currentPage?.revision.body);
In Use タブが更新されないのは、`useEditingMarkdown` で呼び出した `data: markdown` が Next routing では更新されないからでした。
ここで `useEditingMarkdown`を更新する

2022-10-26 11:03 UTC, jam411 commented on packages/app/src/components/PageEditor.tsx
> +      mutateEditingMarkdown(markdownToSave.current);
この mutate きかない

2022-10-26 13:06 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +
`useEditingMarkdown()` を使わないようにする

2022-10-26 13:08 UTC, jam411 commented on packages/app/src/components/PageAttachment.tsx
> +  const markdown = currentPage?.revision.body;
currentPage の revision.body を使う

2022-10-26 13:08 UTC, jam411 commented on packages/app/src/components/PageEditor.tsx
> +  const initialValue = currentPage?.revision.body ?? '';
`currentPage?.revision.body` を使う

2022-10-26 13:09 UTC, jam411 commented on packages/ui/src/components/Attachment/Attachment.tsx
> +};
デバックの過程で, TS/FC化

2022-10-26 13:16 UTC, jam411 commented on packages/app/src/components/PageEditor.tsx
> +      mutateEditingMarkdown(markdownToSave.current);
mutate で cacheに値は入っていたが、[[...path]].page.tsx で 古い`pageWithMeta`の値で上書きされていたことが原因.
このバグの回避策としては、useEditingMarkdown() の代わりに c

2022-10-27 06:05 UTC, yuki-takei requested changes

2022-10-27 06:05 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> +  const initialValue = currentPage?.revision.body ?? '';
ここは変えちゃだめだと思う。(別の箇所で不具合が出そう)

どういう理由で変えたい？
明確な理由がなければ元に戻して。

2022-10-27 06:47 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +
PageEditorで使用する

2022-10-27 06:49 UTC, jam411 commented on packages/app/src/components/PageEditor.tsx
> +  const initialValue = currentPage?.revision.body ?? '';
`currentPage?.revision.body`を使わなくてはいけない理由はなかったです。元に戻します。

2022-10-27 07:11 UTC, merged