feat: gw7895 create new folder from sidebar bookamarks
weseek/growi pull request #6843
Opened 2022-10-27 10:26 UTC by mudana-grune

https://youtrack.weseek.co.jp/issue/GW-7895
## Results
![image](https://user-images.githubusercontent.com/92426728/198260492-b88c7a63-f446-43dd-a429-2cfb3738b276.png)

![image](https://user-images.githubusercontent.com/92426728/198260579-8e4e6208-96b9-41de-94e1-f1b70741f826.png)

2022-11-25 03:46 UTC, kaoritokashiki requested changes

2022-11-25 03:46 UTC, kaoritokashiki commented on packages/app/src/components/Sidebar/Bookmarks/BookmarkFolderItem.tsx
> +  const childCount = useCallback((): number => {
please rename the method like getXXXX

2022-11-25 10:27 UTC, mudana-grune commented on packages/app/src/components/Sidebar/Bookmarks/BookmarkFolderTree.module.scss
> +    // To realize a hierarchical structure, set multiplied padding-left to each foldertree-item
This styling based on page tree

2022-11-28 06:47 UTC, kaoritokashiki approved these changes

2022-11-28 06:48 UTC, merged