imprv: Show UserGroupDetail and GlobalNotificationDetail pages
weseek/growi pull request #6844
Opened 2022-10-27 10:39 UTC by kaoritokashiki

2022-10-27 11:03 UTC, kaoritokashiki commented on packages/app/src/server/views/admin/global-notification-detail.html
> +<!-- {% extends '../layout/admin.html' %}
swig file の後片付けを https://redmine.weseek.co.jp/issues/107707 で一気にやろうかと思っているのですが、
削除しないでほしいなど要望あれば教えてください。

![Screen Shot 2022-10-27 at 20 02 42](https://user-images.githubusercontent.com/59536731/198267873-3ce43fd7-dda3-496c-8189-af33c6641a1e.png)

2022-10-27 11:11 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +    }
以下のように処理を書くと、
```
 setEmailToSend(globalNotification.toEmail);
setSlackChannelToSend(globalNotification.slackChannels);
```

emailToSend, slackChannelToSend の両方に同じ値が入ってしまうので、notifyType の条件分岐をしました。

2022-10-27 11:40 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +    }
DBに存在しない場合は、 `/admin/notification`にリダイレクトされるようにしています。

2022-10-27 11:40 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
> +  const [notifyType, setNotifyType] = useState('mail');
`notifyToType` がよくわからなかったので、notifyType に変更

2022-10-27 11:47 UTC, kaoritokashiki commented on packages/app/src/server/routes/apiv3/notification-setting.js
> +  });
[src/server/routes/admin.js](https://github.com/weseek/growi/pull/6844/files#diff-297db49a5109c1d2df8bba4d01d4f75af10e1570c0afba08fee385437c31874a) を apiv3 の方に移動

2022-10-27 12:01 UTC, yuki-takei requested changes

2022-10-27 12:01 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/notification-setting.js
> +  });
express-validator で validation を書いてください

2022-10-27 12:01 UTC, yuki-takei commented on packages/app/src/server/views/admin/global-notification-detail.html
> +<!-- {% extends '../layout/admin.html' %}
消してしまってよいです

2022-11-01 05:20 UTC, kaoritokashiki commented on packages/app/src/server/views/admin/global-notification-detail.html
> +<!-- {% extends '../layout/admin.html' %}
承知しました！

2022-11-01 06:03 UTC, kaoritokashiki commented on packages/app/src/pages/admin/global-notification/[globalNotificationId].page.tsx
> +  const { globalNotificationId } = router.query;
既存の、globalnotification のvalidationを使用しました

2022-11-01 06:45 UTC, merged