feat: 106973 Enable View this version on PageAccessoriesModal History tab
weseek/growi pull request #6856
Opened 2022-10-30 14:49 UTC by jam411

タスク：https://redmine.weseek.co.jp/issues/106973

2022-11-01 12:10 UTC, yuki-takei requested changes

2022-11-01 12:10 UTC, yuki-takei commented on packages/app/src/components/Page.tsx
> +  const { data: markdown } = useEditingMarkdown();
これは PageEditor で編集対象の markdown string を入れるものであって、用途が違う

2022-11-04 01:15 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +  useStaticPageData(pageWithMeta?.data); // store page data statically for History function on PageAccessoryModal
`pageWithMeta.data.revision` には期待する revision のデータが入っているので, pageWithMeta.data を受け取る `statiSWR` を用意しました。

2022-11-04 01:19 UTC, jam411 commented on packages/app/src/components/Page.tsx
> +  const { data: markdown } = useEditingMarkdown();
`useEditingMarkdwon()` は使わないように修正

2022-11-04 01:28 UTC, jam411 commented
GrowiContextualSubNavigation と PageContentFooter　の `AuthorInfo` は最新 revision の状態のままにする。
v5では、user情報は revision に合わせて表示が変わるが, updateAt は最新 revision の情報だった。

2022-11-07 07:38 UTC, yuki-takei commented on packages/app/src/components/Page.tsx
> +      isLatestRevision={isLatestRevision}
context.tsx にこれを入れるのはおかしい。current page の内容に絞るべきなので。

代案としては、useSWRxPage のリビジョン指定版を作ったりとかそういうのが必要なんじゃないかな。
それから useSWRxCurrentPage の仕様を、latest revision 限定にするのか specified revision に対応するのか、というのもサーバー側・クライアント側で統一してほしい。

2022-11-14 03:45 UTC, jam411 commented on packages/app/src/components/Navbar/PageEditorModeManager.jsx
> -      data-testId={`${targetMode}-button`}
`data-testid` に修正

2022-11-14 03:48 UTC, jam411 commented
- Hitory 機能の revisionId はリクエストパラメータで渡される
- getServerSideProps 内の以下の処理で pageWithMeta を更新して返している
- これをそのまま使いたい

https://github.com/weseek/growi/blob/f0541a4df0b6760351abcad586451a77d72b861b/packages/app/src/pages/%5B%5B...path%5D%5D.page.tsx#L411-L416

2022-11-14 04:09 UTC, jam411 commented on packages/app/src/components/Page.tsx
> +      isLatestRevision={isLatestRevision}
現状の構成を [コメント](https://github.com/weseek/growi/pull/6856#issuecomment-1313056127) に記載しました。
認識ずれていたら教えてほしいのですが、自分の理解では、
指定の revision はリクエストパラメータで渡されるので getServerSideProps で revisionId を取得する swr hooks の作成と、revisionId が渡されたら specified revision の page データを取得できるような useSWRxPage のリビジョン指定版を作成して、それらhooksに対応するコンポーネントを作成することもできると考えましたが、isLatestRevisionをもう使っているのでこのPRで要件が達成できるのと変更が少なくて済むと思いました。
useSWRxPage のリビジョン指定版を作成するなどする場合は、リクエストパラメータで渡される構成そのものを改修することもできると思いますが、工数がかかりそうです。

2022-11-14 18:19 UTC, yuki-takei commented on packages/app/src/components/Page.tsx
> +      isLatestRevision={isLatestRevision}
目的は合っていそうだが、実装を見た感じ少し違和感がある
ペアプロで見てるところでFBして解決したい

- useRequestRevision に違和感
- useSWRxCurrentPage を改修する
    - 現在の pageId or pagePath と revisionId に符合するものを取得するように
    - 必要であれば useCurrentRevisionId 等を用意する

2022-11-15 09:13 UTC, jam411 commented on packages/app/src/components/PageComment/CommentEditor.tsx
> -  const { data: revisionId } = useRevisionId();
useRevisionId はここでのみ使われおり、ContextExtractor.tsx の名残でした。
親コンポーネントでrevisionがわたっていたので、そちらをpropsで渡すように修正しました。

2022-11-15 09:13 UTC, jam411 commented on packages/app/src/components/PageHistory/Revision.tsx
> +              <a className="ml-xl-3" onClick={onClose}>
遷移後にモーダルが閉じないので close を渡しました。

2022-11-15 12:41 UTC, yuki-takei requested changes

2022-11-15 12:41 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  useCurrentRevisionId(props.currentRevisionId);
この行は useSWRxCurrentPage よりも手前で呼ぶ。でないと useSWRxCurrentPage を useCurrentRevisionId に依存させられない。

2022-11-15 12:41 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    shareLinkId?: string, revisionId?: string, initialData?: IPagePopulatedToShowRevision|null,
useSWRxCurrentPage は useCurrentRevisionId に依存させて。

2022-11-15 13:54 UTC, jam411 commented on packages/app/src/components/PageHistory/RevisionDiff.tsx
> +              </Link>
こちらも Link 使用に修正と onClose を渡しました。

2022-11-15 13:54 UTC, jam411 commented on packages/app/src/pages/[[...path]].page.tsx
> +    props.currentRevisionId = props.isLatestRevision && page.latestRevision != null ? page.latestRevision.toString() : revisionId;
@yuki-takei 
useCurrentRevisionId() 依存にするにしたがって、isLatestRevision の場合は`page.latestRevision.toString()`を代入しました。

2022-11-15 13:56 UTC, jam411 commented on packages/app/src/stores/page.tsx
> +  const swrResult = useSWRxPage(currentPageId, shareLinkId, currentRevisionId, initialData);
@yuki-takei
useCurrentRevisionId()に依存させる

2022-11-15 15:04 UTC, merged