support: 107721 refactor page status alert ts fc
weseek/growi pull request #6857
Opened 2022-10-31 05:07 UTC by yukendev

2022-10-31 05:30 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
>    const { mutate: mutateIsEnabledUnsavedWarning } = useIsEnabledUnsavedWarning();
PageStatusAlertでIsHackmdDraftUpdatingInRealtimeを参照している箇所があったので、グローバルなstateをあたらしく作成し、置き換えました

2022-10-31 05:31 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +import React, { useCallback } from 'react';
いったんTS/FC化しただけです。細かい部分は後続タスクで対応します

2022-10-31 05:32 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +    // });
後続タスクで対応
https://redmine.weseek.co.jp/issues/107700

2022-10-31 05:32 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +    // if (pageEditor != null) {
後続タスクで対応
https://redmine.weseek.co.jp/issues/107701

2022-10-31 05:51 UTC, hakumizuki commented on packages/app/src/components/PageStatusAlert.tsx
> +  const getContentsForUpdatedAlert = () => {
メモ化してください

2022-10-31 05:54 UTC, hakumizuki requested changes

2022-10-31 05:54 UTC, hakumizuki commented on packages/app/src/components/PageStatusAlert.tsx
> +  const getContentsForDraftExistsAlert = (isRealtime) => {
メモ化してください

2022-10-31 05:54 UTC, hakumizuki commented on packages/app/src/components/PageStatusAlert.tsx
> +  const getContentsForUpdatedAlert = () => {
メモ化してください

2022-10-31 05:54 UTC, hakumizuki commented on packages/app/src/components/PageStatusAlert.tsx
> +  const [additionalClasses, label, btn] = getContentsFunc();
関数にまとめてメモ化してください

2022-10-31 07:29 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +  const getContentsForDraftExistsAlert = (isRealtime) => {
修正済み

2022-10-31 07:29 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +  const getContentsForUpdatedAlert = () => {
修正済み

2022-10-31 07:39 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +  const [additionalClasses, label, btn] = getContentsFunc();
修正済み

2022-10-31 07:57 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +  const getFC = useCallback(() => {
関数にまとめてメモ化しました

2022-10-31 07:58 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +    <div className={`card grw-page-status-alert text-white fixed-bottom animated fadeInUp faster ${additionalClasses.join(' ')}`}>
メソッドの返り値の型が`(JSX.Element | string)[]`だと`additionalClasses.join`この部分でlintエラーが出たため、各メソッドの返り値を決めました

2022-10-31 08:50 UTC, hakumizuki requested changes

2022-10-31 08:50 UTC, hakumizuki commented on packages/app/src/components/PageStatusAlert.tsx
> +type AlertComponent = {
`Component = React.Component` にとらえられそうなので名前変えてください

2022-10-31 08:50 UTC, hakumizuki commented on packages/app/src/components/PageStatusAlert.tsx
> +  const getFC = useCallback(() => {
名前が汎用的すぎるので改善してください。あと useMemo の方が呼び出す必要なくなるからいいぞ

2022-11-01 04:52 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +  const getFC = useCallback(() => {
修正済み

2022-11-01 04:56 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +type AlertComponent = {
修正済み

2022-11-01 06:00 UTC, hakumizuki requested changes

2022-11-01 06:27 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +  if (alertComponent === null) { return <></> }
修正済み

2022-11-01 06:27 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +  const getAlertComponent = useMemo(() => {
修正済み

2022-11-01 06:28 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
> +type AlertComponentType = {
修正済み

2022-11-01 07:33 UTC, hakumizuki requested changes

2022-11-01 07:33 UTC, hakumizuki commented on packages/app/src/components/PageStatusAlert.tsx
> +  if (alertComponent == null) { return <></> }
use `alertComponentContents` ONLY

2022-11-01 07:44 UTC, merged