feat: skip dupe attachment transfer
weseek/growi pull request #6881
Opened 2022-11-02 14:28 UTC by mizozobu

- [x] 添付ファイルの移行が途中で失敗してもリトライすることで正常に終了できる

https://redmine.weseek.co.jp/issues/106417

2022-11-07 05:48 UTC, skomma requested changes

2022-11-07 05:48 UTC, skomma commented on packages/app/src/server/service/export.js
> +    const nativeCursor = collection.find();
https://github.com/weseek/growi/blob/master/packages/app/src/server/models/attachment.js#L29-L46

これ全部は不要じゃない？
転送されているかどうかを知るために必要な最低限の情報に絞ったほうがよくない？
使わない情報を DB -> 引っ越し先 GROWI -> 引っ越し元 GROWI と転送することになるし。

2022-11-07 05:48 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
>      if (shouldEmit) socket.emit('admin:onStartTransferAttachments', {});
このタスクでやらなくてもいいけど、`transferAttachments` に揃えて、ここから上の部分も別メソッドに出したいなぁ。

2022-11-07 15:37 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
>      if (shouldEmit) socket.emit('admin:onStartTransferAttachments', {});
後でまとめて
https://redmine.weseek.co.jp/issues/106502

2022-11-07 15:46 UTC, mizozobu commented on packages/app/src/server/service/export.js
> +    const nativeCursor = collection.find();
`_id`だけにしました

2022-11-08 16:44 UTC, skomma approved these changes
確認付き approve

2022-11-09 06:18 UTC, merged