スケルトン実装(pagetree)
weseek/growi pull request #6885
Opened 2022-11-04 06:37 UTC by kym-n

2022-11-04 06:39 UTC, kym-n commented
https://redmine.weseek.co.jp/issues/101114

![localhost_3000_ (1)](https://user-images.githubusercontent.com/42678532/199907819-ba7886a4-c5af-442b-9809-a161b153ba04.png)

2022-11-07 06:13 UTC, hakumizuki requested changes

2022-11-07 06:13 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree.tsx
>          </div>
タスクの範囲外ではあったと思うんだけど、この3行が下でも使いまわされてるから PageTreeHeader てきな名前のコンポーネントとして別ファイルで切り出して欲しい。

で、ItemsTreeSkelton じゃなくて PageTreeSkelton として、PageTreeHeader を含んだコンポーネントとしてスケルトンにして欲しい。

PageTree コンポーネントは CSR になると思われるので(SSR しないということ)、最終的に SideBarContents.tsx の

```typescript
import PageTree from './PageTree';
```

が

```typescript
const PageTree = dynamic(() => import('./PageTree'), { ssr: false, loading: () => <PageTreeSkelton /> });
```

みたいになります

2022-11-09 05:46 UTC, kym-n commented on packages/app/src/components/Sidebar/PageTree.tsx
>          </div>
`SidebarContents`の親要素の`components/Sidebar.tsx`で既に
```
const SidebarContents = dynamic(() => import('./Sidebar/SidebarContents').then(mod => mod.SidebarContents), { ssr: false });
```
となっていますが、ここに`loading: () => <SidebarSkelton />`を追加する形での対応でも大丈夫でしょうか？

2022-11-09 07:16 UTC, kym-n commented on packages/app/src/components/Sidebar/PageTree.tsx
>          </div>
`PageTreeHeader`ですが、`SidebarHeader`としてPageTree以外の3種とも共通のコンポーネントを実装しようと思います。

2022-11-09 07:44 UTC, kym-n commented
PageTreeの読み込みはこのような感じになりました。
[screen-recording (1).webm](https://user-images.githubusercontent.com/42678532/200768713-ce509c57-be1e-4e39-822f-80584ba0db6f.webm)

2022-11-09 09:02 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree.tsx
>          </div>
https://redmine.weseek.co.jp/issues/108534 をこの PR 内でやる

2022-11-09 10:11 UTC, yuki-takei requested changes

2022-11-16 02:44 UTC, kym-n commented
## 改修内容
- 読込始め、及びアイテムが表示される直前にスケルトンが消える所の改善
- ファイル構成・コンポーネントの整理

### 前者に関して
PageTreeコンポーネントの読み込まれるまでの過程に該当部位に表示されるコンポーネントは以下の4つ
- `StickyStretchableScroller`(SidebarContentsの親コンポーネント)の`loading` ([`components/Sidebar.tsx`](https://github.com/weseek/growi/pull/6885/files#diff-1fb36e94b9efba8d3f40b774ffcc28be70ddaeb1c02a99980e0345f9affd0eb2), 60-61行目)
- `SidebarContents`の`loading` ([`components/Sidebar.tsx`](https://github.com/weseek/growi/pull/6885/files#diff-1fb36e94b9efba8d3f40b774ffcc28be70ddaeb1c02a99980e0345f9affd0eb2), 62-63行目)

2022-11-16 04:22 UTC, hakumizuki requested changes
あと口頭で言ってた無駄な dynamic import の解消もお願いします

2022-11-16 04:22 UTC, hakumizuki commented on packages/app/src/components/Sidebar/SidebarHeader.tsx
> +      { props.children }
これら全てを外から渡せるようにしよう。で、それぞれの 「PageTree」「RecentChanges」「Tags」「CustomSidebar」用の SidebarHeader コンポーネントを作ろう。

https://zenn.dev/koki_tech/articles/361bb8f2278764
これ読んでください

2022-11-16 04:22 UTC, hakumizuki commented on packages/app/src/components/Sidebar/Skelton/PageTreeSkelton.tsx
> +const PageTreeSkelton = (): JSX.Element => {
名前を `PageTreeBodySkelton` or `ItemsTreeSkelton` にしよう

2022-11-24 05:20 UTC, kym-n commented
対応しました。
`SidebarHeader`を廃し代わりにリロードボタンのみをコンポーネントとして共通化しました。
dynamic import の重複解消については、試みたところ挙動に支障が出たので保留にしています。

2022-11-24 05:43 UTC, hakumizuki requested changes

2022-11-24 05:43 UTC, hakumizuki commented on packages/app/src/components/Sidebar/SidebarHeaderReloadButton.tsx
> +};
`onClick` に型をつけて欲しいです

2022-11-24 05:43 UTC, hakumizuki commented on packages/app/src/components/Sidebar/RecentChanges.tsx
> +  const { data, error, mutate } = swr;
これ 2行使う意味もないので L136 にまとめよう

2022-11-24 05:43 UTC, hakumizuki commented on packages/app/src/components/Sidebar/RecentChanges.tsx
> +        <SidebarHeaderReloadButton onClick={mutate}/>
`mutate` を直で渡すのは微妙だから元の書き方が良いです

2022-11-24 05:43 UTC, hakumizuki commented on packages/app/src/components/Sidebar/CustomSidebar.tsx
> +        <a><i className="icon-magic-wand"></i> Create <strong>/Sidebar</strong> page</a>
これ a tag で囲む必要ある？

2022-11-24 05:43 UTC, hakumizuki commented on packages/app/src/components/Sidebar/CustomSidebar.tsx
> +        <SidebarHeaderReloadButton onClick={mutate} />
`mutate` を直で渡すのは微妙だから元の書き方が良いです

2022-11-24 05:44 UTC, hakumizuki commented
コンポーネントの切り方は OK

2022-11-24 06:06 UTC, kym-n commented on packages/app/src/components/Sidebar/CustomSidebar.tsx
> +        <a><i className="icon-magic-wand"></i> Create <strong>/Sidebar</strong> page</a>
Nextjsの仕様的にこれが正しい書き方のようです。

2022-11-24 06:13 UTC, kym-n commented on packages/app/src/components/Sidebar/RecentChanges.tsx
> +  const { data, error, mutate } = swr;
確認したところ、`swr`自体もreturn内の`InfiniteScroll`のpropsとして使われているようです。

2022-11-24 06:40 UTC, kym-n commented
`onClick()`について対応しました。

2022-11-24 07:27 UTC, yuki-takei requested changes

2022-11-24 07:27 UTC, yuki-takei commented on packages/app/src/components/Sidebar.module.scss
> +    }
細かいけど [/開発ガイドライン/スタイルガイド](https://growi.weseek.co.jp/5c9a6760ea960e0050b2935e) のアンチパターンなので改善して

2022-11-24 07:50 UTC, hakumizuki requested changes

2022-11-24 07:50 UTC, hakumizuki commented on packages/app/src/components/Sidebar.module.scss
> +    }
これまだ足りないんじゃないかな

>マークアップ側の柔軟性を殺してしまう
>クラスを眺めて、マークアップ構造を想像できてしまったら黄信号

h3 ではなく、h3 に class をつけてその class にスタイルをあてよう

2022-11-24 08:14 UTC, kym-n commented
修正しました。（結果的に以前と同じ書き方に戻りました）

2022-11-24 09:05 UTC, merged