fix: Do not allow users to log in when user registration is restricted
weseek/growi pull request #6886
Opened 2022-11-04 08:56 UTC by miya

## Task
[#108280](https://redmine.weseek.co.jp/issues/108280) [Next.js] registrationMode が Restricted 時、ユーザーを作成後ログインできてしまう
└ [#108283](https://redmine.weseek.co.jp/issues/108283) 修正

2022-11-07 06:34 UTC, miya commented on packages/app/src/components/CompleteUserRegistration.tsx
> +};
- 登録制限時の登録完了画面をコンポーネント化（dev/5.1 系とデザインはほぼ同じ）
- CompleteUserRegistrationForm と LoginForm で利用

<img width="560" alt="ScreenShot 2022-11-07 15 17 15" src="https://user-images.githubusercontent.com/34241526/200238918-d3feb540-61fa-427a-bfea-44eb5e2a1604.png">

2022-11-07 06:34 UTC, miya commented on packages/app/src/interfaces/registration-mode.ts
> +export type RegistrationMode = typeof RegistrationMode[keyof typeof RegistrationMode];
ユニオン型を作成

2022-11-07 06:34 UTC, miya commented on packages/app/src/server/routes/login.js
> +    activityEvent.emit('update', res.locals.activity._id, parameters);
登録成功ハンドラーの処理が開始した段階で activity を作成

2022-11-07 06:34 UTC, miya commented on packages/app/src/server/routes/login.js
> +    }
ユーザー登録制限時は req.login に渡さず、/login#register にリダイレクト

2022-11-07 06:34 UTC, miya commented on packages/app/src/server/routes/login.js
> +  };
上のコメントまで変更なし

2022-11-07 06:34 UTC, miya commented on packages/app/src/components/CompleteUserRegistrationForm.tsx
> +  const [isSuccessToRagistration, setIsSuccessToRagistration] = useState(false);
ユーザー登録作成成功時の state<boolean>

2022-11-07 06:34 UTC, miya commented on packages/app/src/components/CompleteUserRegistrationForm.tsx
> +      }
ユーザー登録制限時でない時は /login に遷移させる

2022-11-07 06:34 UTC, miya commented on packages/app/src/components/LoginForm.tsx
> +    setIsSuccessToRagistration(false);
- ユーザー登録成功時の boolean（269 行目のコードと共通化）

2022-11-07 06:34 UTC, miya commented on packages/app/src/components/LoginForm.tsx
> +  }
ユーザー登録制限時 && メール認証無効時は CompleteUserRegistration をレンダリング（dev/5.1 系以前と同じ）

2022-11-07 12:09 UTC, yuki-takei requested changes

2022-11-07 12:09 UTC, yuki-takei commented on packages/app/src/components/CompleteUserRegistrationForm.tsx
> +      }
基本的に toastr とページ遷移を同時にやるべきじゃないと思っていて(今までの実装からして良くなかったんだけど)
どういう挙動がベストか検討して修正してほしいな

2022-11-07 12:09 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +    }
admin からの承認を待つわけだよね？ `/login#register` にリダイレクトしたら混乱しないかな。

2022-11-08 09:32 UTC, miya commented on packages/app/src/server/routes/login.js
> +    }
/login にリダイレクトするように修正しました

2022-11-08 09:34 UTC, miya commented on packages/app/src/components/CompleteUserRegistrationForm.tsx
> +      }
`toastSuccess` は辞めて、ユーザー作成後、ログイン処理を行い `/` に遷移するように修正しました。

2022-11-09 02:54 UTC, yuki-takei requested changes

2022-11-09 02:54 UTC, yuki-takei commented on packages/app/src/components/CompleteUserRegistrationForm.tsx
> +      }
registrationMode を見る必要ないと思う。res.data.redirectTo 次第でいいよね。

2022-11-09 02:54 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +      if (registrationMode === RegistrationMode.RESTRICTED) {
ここもなぜ registrationMode  を見ないといけない？

2022-11-09 02:54 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +    }
「admin からの承認を待ってね」ってことがユーザーに伝わるような UI/UX になってる？
なってるならOK

2022-11-09 09:38 UTC, yuki-takei requested changes

2022-11-09 09:38 UTC, yuki-takei commented on packages/app/src/components/CompleteUserRegistrationForm.tsx
> +      }
redirectTo をサーバーサイドで指定せず、指定がなければリダイレクトしなければいいだけの話

2022-11-10 00:56 UTC, miya commented on packages/app/src/components/CompleteUserRegistration.tsx
> +          <a href='/login'>
遷移元が /login だった場合 next/link を利用したリンクでは遷移しなかったため、a タグを利用

2022-11-10 01:04 UTC, merged