support: refactor page wide view
weseek/growi pull request #6895
Opened 2022-11-08 05:56 UTC by yukendev

https://redmine.weseek.co.jp/issues/108202

2022-11-09 10:29 UTC, yukendev commented on packages/app/src/stores/context.tsx
> +export const useIsContainerFluid = (initialData?: boolean): SWRResponse<boolean, Error> => {
dbのwide viewの設定値をSubNavButtonsで参照する必要があったので、新しいcontextを作成しました

2022-11-09 10:29 UTC, yukendev commented on packages/app/src/server/service/page.ts
>      const seenUsers = page.seenUsers.slice(0, 15) as Ref<IUserHasId>[];
pageInfoからexpandContentWidthの情報を削除しました

2022-11-09 10:48 UTC, yuki-takei requested changes

2022-11-09 10:48 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  const { mutate: mutateCrrentPage } = useSWRxCurrentPage();
SubNavButtonsSubstance は current page に依存してはならない

2022-11-10 05:16 UTC, yukendev commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  const { mutate: mutateCrrentPage } = useSWRxCurrentPage();
onClickSwitchContentWidthを外から渡すようにすることで依存しないようにしました

2022-11-10 05:17 UTC, yukendev commented on packages/app/src/components/SearchPage/SearchResultContent.tsx
> +  const [isExpandContentWidth, setIsExpandContentWidth] = useState(page.expandContentWidth);
SerachResult画面では、wide viewを切り替えても、見た目がすぐに変更される必要がなく、無駄にuseSWRxPageのmutateを呼ぶ必要がないと思ったので、通常のstateで代用しています

2022-11-10 08:49 UTC, yuki-takei requested changes

2022-11-10 08:49 UTC, yuki-takei commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  const { data: isContainerFluid } = useIsContainerFluid();
atomic design の粒度で考えた時に、コンポーネントサイズが小さくなればなるほど global state への依存をなくしてほしい。
`expandContentWidth ?? isContainerFluid` みたいな判定は SubNavButtons か欲を言えばもっと上位のコンポーネントでやればよくて、SubNavButtonsSubstance や WideViewMenuItem は完全に props に従う受け身であるべき。

2022-11-11 07:46 UTC, yukendev commented on packages/app/src/components/Navbar/SubNavButtons.tsx
> +  const { data: isContainerFluid } = useIsContainerFluid();
修正済み

2022-11-11 08:54 UTC, merged