fix: login ui is shown on navigation bar even if users are logged in
weseek/growi pull request #6900
Opened 2022-11-08 12:41 UTC by kaoritokashiki

2022-11-08 13:20 UTC, kaoritokashiki commented on packages/app/src/pages/utils/commons.ts
> +  }
getServerSideCommonProps の中で取得するようにしたのですがよろしかったでしょうか ??

2022-11-10 08:35 UTC, yuki-takei requested changes

2022-11-10 08:35 UTC, yuki-takei commented on packages/app/src/pages/utils/commons.ts
> +  }
`share/[[...path]].page.tsx` も修正した方がいいんじゃないかな。
で、share link page とか他の箇所でも currentUser なしの場合もあるだろうから型定義を optional にしておくべきだと思う。

2022-11-11 10:57 UTC, kaoritokashiki commented on packages/app/src/pages/utils/commons.ts
> +  }
オプショナルにしておくべきというのは、もともとのやり方　の方がよかったということでしょうか?
(`getServerSideCommonProps` で currentUser に代入せずに
各ページ `xxx.page.tsx` の getServerSideCommonProps の後に、 props.currentUser　をにuser のdataを代入すべきということでしょうか...??)

2022-11-15 06:05 UTC, merged