feat: show detailed progress
weseek/growi pull request #6901
Opened 2022-11-08 16:14 UTC by mizozobu

- [x] socket.io でクライアントに進行状況を emit し、クライアントはそれを随時表示できる

https://redmine.weseek.co.jp/issues/106419

https://user-images.githubusercontent.com/27652080/200617599-90b36c2b-79ba-443a-b440-1a718a3b8f02.mov

2022-11-08 16:20 UTC, mizozobu commented on packages/app/src/components/Admin/G2GDataTransfer.tsx
> +}
これclientとserverで共通にしたいです。どこに置けばいいですか？

2022-11-08 16:20 UTC, mizozobu commented on packages/app/src/components/Admin/G2GDataTransferStatusIcon.tsx
> +}
置き場所が決まり次第、共通化される予定

2022-11-08 16:20 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> +
置き場所が決まり次第、共通化される予定

2022-11-08 16:20 UTC, mizozobu commented on packages/app/src/components/Admin/G2GDataTransfer.tsx
> +  : never;
[utility-types](https://github.com/piotrwitek/utility-types/blob/df2502ef504c4ba8bd9de81a45baef112b7921d0/src/mapped-types.ts#L589-L597)から拝借しました

2022-11-08 16:55 UTC, skomma requested changes
i18n translation だけ

2022-11-08 16:55 UTC, skomma commented on packages/app/public/static/locales/en_US/admin.json
> +    "transfer_success": "G2G transfer successfully completed",
```suggestion
    "transfer_success": "Completed GROWI to GROWI transfer successfully",
```
UI に `GROWI to GROWI transfer` と表示しているのと、`successfully` は最後に来るイメージ。

2022-11-08 16:55 UTC, skomma commented on packages/app/src/components/Admin/G2GDataTransfer.tsx
> +}
@hakumizuki 回答ヨロ

2022-11-09 06:21 UTC, hakumizuki commented on packages/app/src/components/Admin/G2GDataTransfer.tsx
> +}
@mizozobu `/src/interfaces` においてください。ファイル名は `g2g-transfer.ts` とかで大丈夫です

2022-11-09 13:42 UTC, merged