fix: 107915 GlobalNotification toolchip update
weseek/growi pull request #6905
Opened 2022-11-09 07:33 UTC by jam411

Description in Story: [107915](https://redmine.weseek.co.jp/issues/107915)
task: [108333](https://redmine.weseek.co.jp/issues/108333)

- ToolChip 修正
- TS/FC化
- type 修正

## Screen Shot
![image](https://user-images.githubusercontent.com/68407388/200766731-1c48238b-a4d2-4c3b-a9e5-26f119ecb04a.png)

2022-11-09 07:52 UTC, jam411 commented on packages/app/src/client/interfaces/global-notification.ts
> +  Email: 'mail',
自分も email のほうがいいと思いましたが、改修箇所が多いのと, DBのモデルも変更必要になりそうだったので、こちらを修正にしました。

2022-11-09 07:52 UTC, jam411 commented on packages/app/src/client/interfaces/global-notification.ts
> +  provider: any
provider は一旦 any にしています。

2022-11-09 07:52 UTC, jam411 commented on packages/app/src/components/Admin/Notification/NotificationTypeIcon.jsx
> -  }
この意味が分からなかったので provider は any のまま

2022-11-09 14:05 UTC, kaoritokashiki requested changes

2022-11-09 14:05 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/GlobalNotificationTypeIcon.tsx
> +  const elemId = `notification-${__t}-${_id}`;
実際に入ってくる値を確認していませんが、
10, 11 行目をみた感じ、
User trigger notificationの場合 `__t` は undefined になりそう?ですね👀 
確認お願いします 🙏 

```
  // supports 2 types:
  //   User trigger notification -> has 'provider: slack'
  //   Global notification -> has '__t: slack|mail'

```

2022-11-10 00:54 UTC, jam411 commented on packages/app/src/components/Admin/Notification/GlobalNotificationTypeIcon.tsx
> +  const elemId = `notification-${__t}-${_id}`;
Globalのみで使用されると勘違いしていました。。。
NotificationTypeIcon と一般的にして、null の場合の処理を追加しました。

2022-11-10 02:05 UTC, kaoritokashiki requested changes

2022-11-10 03:28 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Notification/NotificationTypeIcon.jsx
> -  }
気づいたかもですが一応

User trigger notification の場合、providerプロパティには　'slack' しかはいってこない(はず)ので、

let type = 'slack'
で定義したやつがそのまま変わらずtypeになるということを示しているんだと思います。

2022-11-10 04:53 UTC, kaoritokashiki commented
https://github.com/weseek/growi/pull/6905#discussion_r1018618086 
comment 追加しました。

2022-11-10 04:53 UTC, merged