support: refactor customize layout in admin
weseek/growi pull request #6919
Opened 2022-11-11 10:35 UTC by yukendev

https://redmine.weseek.co.jp/issues/108654

## やったこと
- 管理者画面 => カスタマイズ のレイアウトの項目で初期値がうまく設定されていなかった不具合を修正
- ワイドビューを切り替えるスイッチの挙動を修正

2022-11-11 12:11 UTC, hakumizuki requested changes

2022-11-11 12:11 UTC, hakumizuki commented on packages/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
> +};
この実装だと一瞬正しくない値で設定されているように見えるのでそこを改善してください

2022-11-11 13:01 UTC, hakumizuki requested changes

2022-11-11 13:01 UTC, hakumizuki commented on packages/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
> +  if (isContainerFluid == null) { return <></> }
ローディングにするか選択されてないやつにするかで改善お願いします

2022-11-14 02:37 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
> +};
修正済み

2022-11-14 02:38 UTC, yukendev commented on packages/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
> +  if (isContainerFluid == null) { return <></> }
修正済み

2022-11-14 03:50 UTC, merged