feat: Enable HandsonTableModal
weseek/growi pull request #6921
Opened 2022-11-13 02:22 UTC by jam411

Task: [108321](https://redmine.weseek.co.jp/issues/108321)

- [ ] scss module 化
- [ ] 開閉処理の hooks 化
- [ ] インスタンスを一か所から生成する
- [ ] save できる

2022-11-13 15:51 UTC, jam411 commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +        }}
CodeMirrorEditor のパラメータを HandsonTableModal へ渡す

2022-11-13 15:51 UTC, jam411 commented on packages/app/public/static/locales/en_US/commons.json
> +  },
ボタン表記などいくつか共通化できる
一旦は commons.json にモーダル毎に記載する

2022-11-13 15:51 UTC, jam411 commented on packages/app/src/components/PageEditor/MarkdownTableDataImportForm.tsx
> +};
MarkdownTableDataImportForm.tsx の ts/fc 化と i18n 化

2022-11-13 15:51 UTC, jam411 commented on packages/app/src/stores/modal.tsx
>    };
save メソッド追加

2022-11-13 15:51 UTC, jam411 commented on packages/app/src/components/PageEditor/HandsontableModal.tsx
> +  }, [isOpened]);
isOpen したときに CodeMirrorEditor の table を参照できる。
リセットできるように `setMarkdownTableOnInit(initTableInstance);`

2022-11-14 04:41 UTC, jam411 commented on packages/app/src/components/PageEditor/HandsontableModal.tsx
> +  const table = handsontableModalData?.table;
参照のため hooks から table を取得

2022-11-14 04:42 UTC, jam411 commented on packages/app/src/components/PageEditor/HandsontableModal.tsx
> +  const [markdownTableOnInit, setMarkdownTableOnInit] = useState<MarkdownTable>(defaultMarkdownTable);
```
const [markdownTable, setMarkdownTable] = useState<MarkdownTable>(() => defaultMarkdownTable());
const [markdownTableOnInit, setMarkdownTableOnInit] = useState<MarkdownTable>(() => defaultMarkdownTable());
```
下に修正

```
const [markdownTable, setMarkdownTable] = useState<MarkdownTable>(defaultMarkdownTable);
const [markdownTableOnInit, setMarkdownTableOnInit] = useState<MarkdownTable>(defaultMarkdownTable);
```

2022-11-14 04:44 UTC, jam411 commented on packages/app/src/components/PageEditor/HandsontableModal.tsx
> +    debounce(100, expandHotTableHeight);
debounce 関数かせずそのまま使用

2022-11-14 04:45 UTC, jam411 commented on packages/app/src/components/PageEditor/HandsontableModal.tsx
> +};
コメント箇所以外レビュー済み。
その他i18n化しました。

2022-11-14 18:26 UTC, yuki-takei requested changes

2022-11-14 18:26 UTC, yuki-takei commented on packages/app/src/components/Page.tsx
> +  // handsontableModal: any;
この辺のコメントアウトしたコードは不要なら消してよい

2022-11-14 18:26 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +// import { HandsontableModal } from './HandsontableModal';
この辺のコメントアウトしたコードは不要なら消してよい

2022-11-15 11:32 UTC, jam411 commented on packages/app/src/components/Page.tsx
> +  // handsontableModal: any;
削除しました。

2022-11-15 11:32 UTC, jam411 commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +// import { HandsontableModal } from './HandsontableModal';
削除しました。

2022-11-15 11:36 UTC, jam411 commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +        }}
CodeMirrorEditor のパラメータを HandsonTableModal へ渡す

2022-11-15 12:42 UTC, merged