feat: Enable pasteHandler and scrollCursorIntoViewHandler on CodeMirrorEditor
weseek/growi pull request #6926
Opened 2022-11-14 06:32 UTC by jam411

task: [107525](https://redmine.weseek.co.jp/issues/107525)
scrollCursorIntoViewHandler の有効化もこのPRに含む

- [ ] Editor に clipboard から attachment の貼り付けができる (pasteHandler有効化)
- [ ] Editor の任意の行をクリックすると、View 画面がその行を表す場所までスクロールする (scrollCursorIntoViewHandler有効化)

2022-11-14 18:33 UTC, yuki-takei requested changes

2022-11-14 18:33 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +          scrollCursorIntoViewHandler={this.scrollCursorIntoViewHandler}
1067行目付近消してほしい

2022-11-14 18:33 UTC, yuki-takei commented on packages/app/src/components/UncontrolledCodeMirror.tsx
> +  scrollCursorIntoViewHandler?: (editor: any, event: Event) => void;
これらも onHoge の形にしてほしいな

2022-11-15 01:22 UTC, jam411 commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> +          scrollCursorIntoViewHandler={this.scrollCursorIntoViewHandler}
コメント削除しました。

2022-11-15 01:23 UTC, jam411 commented on packages/app/src/components/UncontrolledCodeMirror.tsx
> +  scrollCursorIntoViewHandler?: (editor: any, event: Event) => void;
すでに onPasteFiles と onScrollCursorIntoView が定義されていたのでおきかえました。

2022-11-15 01:36 UTC, merged