fix: Unsend Email notification styles
weseek/growi pull request #6928
Opened 2022-11-15 02:43 UTC by jam411

Task:[108931](https://redmine.weseek.co.jp/issues/108931)

- [ ] module.scss 化, `UserMenu.tsx` TS/FC化
![image](https://user-images.githubusercontent.com/68407388/201813210-cafd6d51-e0a1-490a-8fdd-f2140544904d.png)

- [] pager が no share link のとき隠れるようにする

2022-11-15 05:04 UTC, jam411 commented
table よりドロップダウンのほうが大きいとボタンに被って表示される。 v5でも確認.
<img width="213" alt="image (9)" src="https://user-images.githubusercontent.com/68407388/201830768-250a2538-0706-4fdc-a6ba-d96aa476f951.png">

2022-11-16 03:48 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Users/UserMenu.tsx
> +  };
useCallback 使ってください

2022-11-16 03:58 UTC, kaoritokashiki requested changes

2022-11-16 03:58 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Users/UserMenu.tsx
> +  };
useCallback 使うようにお願いします🙏
(他のメソッドも)

2022-11-16 04:03 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Users/UserMenu.tsx
> +const UserMenuWrapper: React.ForwardRefExoticComponent<Pick<any, string | number | symbol> & React.RefAttributes<any>> = withUnstatedContainers(UserMenu, [AdminUsersContainer]);
この部分は、このままでいいのかわからないので武井さんチェックお願いします。

2022-11-16 04:05 UTC, kaoritokashiki requested changes

2022-11-16 04:05 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Users/UserMenu.tsx
> +          {user.status === 5 && (
user.status 用の interface 作りたいですね

2022-11-16 12:35 UTC, yuki-takei commented on packages/app/src/components/Admin/Users/UserMenu.tsx
> +const UserMenuWrapper: React.ForwardRefExoticComponent<Pick<any, string | number | symbol> & React.RefAttributes<any>> = withUnstatedContainers(UserMenu, [AdminUsersContainer]);
この部分はこれでいいです。
「これでいい」というのは望ましいコードかという意味ではなく、withUnstatedContainers 使う時にそこまでタイプがんばらなくていいという意味。

2022-11-17 05:53 UTC, kaoritokashiki commented on packages/core/src/interfaces/user.ts
> +export type IUserStatus = typeof UserStatus[keyof typeof UserStatus]
感覚でしかない(言語化できない)んですけど、`REGISTERED` のように コンスタントケースの方がいいような気がします。
`user.js`みたいな感じで

https://github.com/weseek/growi/blob/f4840b120d6e94d225c558ec691bd5a2a1871191/packages/app/src/server/models/user.js#L22-L26

2022-11-17 05:58 UTC, kaoritokashiki requested changes

2022-11-17 05:58 UTC, kaoritokashiki commented on packages/app/src/components/Admin/Users/UserMenu.tsx
> +          {user.status === 5 && (
数字を定義したtypeに置き換えお願いします...!

2022-11-17 06:21 UTC, jam411 commented on packages/core/src/interfaces/user.ts
> +export type IUserStatus = typeof UserStatus[keyof typeof UserStatus]
イメージできました。ありがとうございます。修正してみました。

2022-11-17 06:26 UTC, kaoritokashiki approved these changes

2022-11-17 08:38 UTC, merged