fix: 10740 Show GROWI Search bar on admin pages
weseek/growi pull request #6944
Opened 2022-11-16 06:14 UTC by kaoritokashiki

2022-11-16 09:07 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GlobalSearch.tsx
> +  }, [isSearchScopeChildrenAsDefault]);
useEffect で　isSearchScopeChildrenAsDefault　の値が更新されたらsetScopeChildrenするように修正しました。

2022-11-16 09:08 UTC, kaoritokashiki commented on packages/app/src/pages/utils/commons.ts
> +  isSearchScopeChildrenAsDefault?: boolean,
CommonProps に追加しました

2022-11-16 12:50 UTC, yuki-takei requested changes

2022-11-16 12:50 UTC, yuki-takei commented on packages/app/src/stores/context.tsx
> +export const useIsSearchPage = (initialData?: Nullable<boolean>) : SWRResponse<Nullable<boolean>, Error> => {
これはあってもよい

2022-11-16 12:50 UTC, yuki-takei commented on packages/app/src/components/Navbar/GlobalSearch.tsx
> -  const [isScopeChildren, setScopeChildren] = useState<boolean|undefined>(isSearchScopeChildrenAsDefault);
- useIsSearchScopeChildrenAsDefault に fallbackData を指定したい
- 初期値は `isSearchScopeChildrenAsDefault ?? false` でいいんじゃない？
    - 上記の fallbackData 設定で undefined が返されることはなくなると思うけど

2022-11-16 12:50 UTC, yuki-takei commented on packages/app/src/components/Navbar/GlobalSearch.tsx
> +  }, [isSearchScopeChildrenAsDefault]);
これはあっていいけど、`isSearchScopeChildrenAsDefault !== undefined` の判定はいらないかな。

2022-11-16 12:50 UTC, yuki-takei commented on packages/app/src/components/Navbar/GlobalSearch.tsx
> +  if (isLoadingIsSearchScopeChildrenAsDefault) {
ここ慎重になりたいな…

loading 中は `<></>` を返したいというところまではいいんだけど、その判定が `isScopeChildren == null || isSearchServiceReachable == null` から `isSearchScopeChildrenAsDefault === undefined` に変わってしまっているんだよね。SearchForm をレンダリングできるかどうかは isScopeChildren, isSearchServiceReachable が初期化済みかどうかも関わるんじゃないかなあ。

2022-11-18 03:15 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GlobalSearch.tsx
> +  }, [isSearchScopeChildrenAsDefault]);
> isSearchScopeChildrenAsDefault !== undefined の判定はいらないかな。
なんでだろうと思っていましたが、確かにいらないですね。ありがとうございます。 :memo:
load後に値を取得した後に、undefined に変わるということもないでしょうし。

2022-11-18 03:17 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GlobalSearch.tsx
> +  if (isLoadingIsSearchScopeChildrenAsDefault) {
理解しました。

2022-11-18 03:33 UTC, kaoritokashiki commented on packages/app/src/pages/utils/commons.ts
> -import { SupportedActionType } from '~/interfaces/activity';
どこからも使われていなかったので削除しました。

2022-11-18 03:41 UTC, kaoritokashiki commented on packages/app/src/stores/context.tsx
> +  return useContextSWR<boolean, Error>('isSearchScopeChildrenAsDefault', initialData, { fallbackData: false });
fallbackData に `false`　を指定

2022-11-18 03:53 UTC, kaoritokashiki commented on packages/app/src/components/Navbar/GlobalSearch.tsx
> -  const [isScopeChildren, setScopeChildren] = useState<boolean|undefined>(isSearchScopeChildrenAsDefault);
ありがとうございます。そのように修正しました。

2022-11-18 08:58 UTC, merged