fix: AttachTitleHeader
weseek/growi pull request #6961
Opened 2022-11-18 11:09 UTC by miya

## Task
[#107867](https://redmine.weseek.co.jp/issues/107867) [Next.js] [Admin] カスタマイズ設定の 新規ページ作成時の h1 セクション自動挿入 が機能していない
└ [#109244](https://redmine.weseek.co.jp/issues/109244) 修正

2022-11-18 11:15 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +    initialEditingMarkdown += `${attachTitleHeader(props.currentPathname)}\n`;
isEnabledAttachTitleHeader が true の時は `# {currentPathName}` を予め挿入

2022-11-21 18:10 UTC, yuki-takei requested changes

2022-11-21 18:10 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +    initialEditingMarkdown += `${attachTitleHeader(props.currentPathname)}\n`;
[[...path]].page.tsx がこのロジックを持つのはあまり好ましくない(肥大化にも繋がるし)

useEditingMarkdown 側の初期化ロジックでこのような処理をしてほしい。引数増やしたりするのも良いと思う。

2022-11-22 02:13 UTC, miya commented on packages/app/src/stores/context.tsx
> -
不要な import の削除、pathUtils の追加

2022-11-22 02:13 UTC, miya commented on packages/app/src/stores/context.tsx
> +};
- Computed な SWR に修正
- ページが存在している場合は `initialData ?? ''` を返す
- 上記以外の場合は、ページのパスの h1 や テンプレートボディなど設定されていればそれを返す

2022-11-22 02:13 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +    initialEditingMarkdown += `${attachTitleHeader(props.currentPathname)}\n`;
> useEditingMarkdown 側の初期化ロジックでこのような処理をしてほしい

そのように修正しました

2022-11-22 07:49 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +  props.isNotFound = !(page != null && !page.isEmpty);
簡略化

2022-11-22 07:49 UTC, miya commented on packages/app/src/stores/context.tsx
> +  return useContextSWR('revisionBody', initialData);
旧 useEditingMarkdown に入れていた値が入る

2022-11-22 08:14 UTC, miya commented on packages/app/src/stores/context.tsx
> +};
- Computed な SWR に変更
- ページが存在している場合は `revisionBody ?? ''` を返す
- 上記以外の場合は、ページのパスの h1 や テンプレートボディなど設定されていればそれを返す

2022-11-22 08:14 UTC, miya commented on packages/app/src/stores/context.tsx
> +  return useContextSWR('revisionBody', initialData);
旧 useEditingMarkdown に入れていた値が入る

2022-11-22 08:14 UTC, miya commented on packages/app/src/stores/context.tsx
> -// import { CustomWindow } from '~/interfaces/global';
（1-9 行目まで）不要な import の削除、pathUtils の追加

2022-11-22 08:14 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +  props.isNotFound = !(page != null && !page.isEmpty);
簡略化

2022-11-24 06:35 UTC, yuki-takei requested changes

2022-11-24 06:35 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +  props.isNotFound = !(page != null && !page.isEmpty);
元の方がいいな

2022-11-24 06:35 UTC, yuki-takei commented on packages/app/src/stores/context.tsx
> +};
- 引数がゼロになったのでめちゃ複雑になってしまっている
- useContextSWR を使わないのであればもはや context.tsx 内に存在してはいけない
    - が、どこかに移せという話ではなく、引き続き useContextSWR を使って欲しいと思っている

2022-11-25 08:11 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +  props.isNotFound = !(page != null && !page.isEmpty);
これは戻しました

2022-11-25 08:42 UTC, miya commented on packages/app/src/stores/context.tsx
> +};
- useContextSWR は値を入れるだけが良いということを聞いた
- useContextSWR を利用し引数を増やす場合、その内部でロジックを組み上げることになる
以上からの理由からロジックに必要な値は全て ContextSWR化、ロジックは使う側 `PageEditor.tsx` で作成するようにしました。

2022-11-25 12:23 UTC, merged