feat: Create error handler for external account
weseek/growi pull request #6975
Opened 2022-11-21 10:20 UTC by miya

## Task
[#108543](https://redmine.weseek.co.jp/issues/108543) req.t, req.flash を代替する
└ [#108543](https://redmine.weseek.co.jp/issues/108543) Extenal Account 用の login error handler を作成する

2022-11-24 09:22 UTC, miya commented on packages/app/src/server/routes/login-passport.js
> +  };
エラーオブジェクトを含めて、login.page.tsx をレンダリングできるように修正

2022-11-24 09:24 UTC, miya commented on packages/app/src/server/routes/index.js
> +  app.get('/passport/github'                      , loginPassport.loginWithGitHub, loginPassport.loginFailureForExternalAccount);
こちら問題なければ won't fix でお願いします

2022-11-24 09:25 UTC, miya commented on packages/app/src/pages/login.page.tsx
> +  }
初期エラーオブジェクトを取得

2022-11-24 09:26 UTC, miya commented on packages/app/src/components/LoginForm.tsx
> +  const [loginErrors, setLoginErrors] = useState<IErrorV3[]>(props.loginError != null ? [props.loginError] : []);
レンダリング時に `nextApp.render` によってエラーオブジェクトが渡ってきた場合は state に入れる

2022-11-28 01:52 UTC, miya commented on packages/app/src/pages/login.page.tsx
> +    props.loginError = { ...loginError };
- エラーオブジェクトの取得
- nextApp.render で  ErrorV3 オブジェクトを返却する際に  `[ErrorV3: msg] { code: '', args: undefined }` という形になってしまうので通常のオブジェクトの形にするために `{ ...loginError }` とやっている

2022-11-28 06:32 UTC, yuki-takei requested changes

2022-11-28 06:32 UTC, yuki-takei commented on packages/app/src/server/routes/login-passport.js
> +      const error = new ErrorV3('message.strategy_has_not_been_set_up', undefined, undefined, { strategy: 'GoogleStrategy' });
- API ではないので ErrorV3 をあまり使いたくない
- ExternalAccount でのログイン専用のエラーオブジェクトを extensible-custom-error で作ってはどうか

2022-11-28 06:32 UTC, yuki-takei commented on packages/app/src/server/routes/index.js
> +  app.get('/passport/github'                      , loginPassport.loginWithGitHub, loginPassport.loginFailureForExternalAccount);
'/passport/google' はそのままでいいの？

2022-11-28 06:32 UTC, yuki-takei commented on packages/app/src/pages/login.page.tsx
> +    props.loginError = { ...loginError };
- type guard を作って

2022-11-28 06:32 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +  const [loginErrors, setLoginErrors] = useState<IErrorV3[]>(props.loginError != null ? [props.loginError] : []);
props 時点で配列の方がいいのでは？

2022-11-30 16:02 UTC, miya commented on packages/app/src/server/routes/index.js
> +  app.get('/passport/github'                      , loginPassport.loginWithGitHub, loginPassport.loginFailureForExternalAccount);
見落としていました、修正しました

2022-11-30 17:53 UTC, miya commented on packages/app/src/pages/login.page.tsx
> +      props.loginError = { ...loginError as IExternalAccountLoginError };
type guard を入れた アサーションは必要

2022-11-30 17:53 UTC, miya commented on packages/app/src/pages/login.page.tsx
> +    props.loginError = { ...loginError };
type guard つくりました

2022-11-30 17:53 UTC, miya commented on packages/app/src/server/routes/login-passport.js
> +      const error = new ErrorV3('message.strategy_has_not_been_set_up', undefined, undefined, { strategy: 'GoogleStrategy' });
`ExternalAccountLoginError` を作りました

2022-11-30 18:01 UTC, miya commented on packages/app/src/components/LoginForm.tsx
> +  const [loginErrors, setLoginErrors] = useState<IErrorV3[]>(props.loginError != null ? [props.loginError] : []);
これは LoginForm.tsx に渡す pros.loginError が配列の状態で渡した方が良いということでしょうか？
nextApp.render は単一のエラーオブジェクトを返すようになっているのでこのままでも良いと思ったのですが..

2022-12-01 04:49 UTC, yuki-takei requested changes

2022-12-01 04:49 UTC, yuki-takei commented on packages/app/src/components/LoginForm.tsx
> +  const [loginErrors, setLoginErrors] = useState<IErrorV3[] | IExternalAccountLoginError[]>(props.loginError != null ? [props.loginError] : []);
これは今回の PR で意味が分かった。

## エラーの種類を整理する
express.response.apiv3Err はエラーを配列で投げる仕様なので、保持する場合は `IErrorV3[]` である必要がある。
一方 IExternalAccountLoginError は単一しか投げられない仕様なのであれば、必ずしも配列にする必要はない、が、`loginErrors` 変数の使い勝手を考えた時には配列でも構わない。

なので、型は `(IErrorV3 | IExternalAccountLoginError)[]` にするか、`IErrorV3[] | IExternalAccountLoginError` か。
(前者を選ぶなら現状の表現でも同じ)

## props / state を整理する
上記は単一の loginErrors という state を使う前提だが、そもそも v3 のエラーと external account login のエラーを同一 state で取り扱うのが使いやすいのか？というのはあると思う。
最低限、props の名前は変えてほしい。ここには IExternalAccountLoginError しか入ってこないはずなので。
state を分けるかどうかは任せる。

2022-12-01 08:49 UTC, miya commented on packages/app/src/components/LoginForm.tsx
> +  const [loginErrors, setLoginErrors] = useState<IErrorV3[] | IExternalAccountLoginError[]>(props.loginError != null ? [props.loginError] : []);
- IExternalAccountLoginError は配列のままにして、使う時には型を `(IErrorV3 | IExternalAccountLoginError)[]` に変更
- 名前を `props.externalAccountLoginError` に変更、state 管理をやめました

2022-12-01 08:51 UTC, merged