Support/108172 for updated alert
weseek/growi pull request #6977
Opened 2022-11-22 06:02 UTC by yukendev

2022-11-24 07:06 UTC, yukendev commented on packages/app/src/components/PageEditor.tsx
編集中のマークダウンをswrを使って保持する実装も考えましたが、おそらくこの部分でしか使われないので、PageEditorでもページの更新を監視して、更新されたタイミングでコンフリクトがあるかどうかのbool値をPageStatusAlertで参照するようにしました

2022-11-24 07:59 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.module.scss
> +@use '~/styles/variables' as var;
既存のスタイルをモジュールに切り出しただけです

2022-11-24 08:00 UTC, yukendev commented on packages/app/src/styles/_page.scss
>  }
モジュールに切り出した分のスタイルは削除しました

2022-11-24 08:01 UTC, yukendev commented on packages/app/src/stores/remote-latest-page.ts
> +
もともと`stores/hackmd.ts`にあった`useRemoteRevisionId`を移動させ、`useRemoteRevisionBody`、`useRemoteRevisionLastUpdatUser`を追加しました。

2022-11-24 08:03 UTC, yukendev commented on packages/app/src/stores/context.tsx
`useEditingMarkdown`は`getServerSideProps`で取得した`pageWithMeta`のbodyで初期化され、`PageEditor`のstateの初期値として入れるだけの用途として使用されており、`currentPage`のbodyで代用することができたので不要と判断し、削除しました

2022-11-24 08:04 UTC, yukendev commented on packages/app/src/components/PageStatusAlert.tsx
ページの更新の通知を受け取り、DBの最新の値をglobal stateとして保持しています。

2022-11-24 08:09 UTC, yukendev commented on packages/app/src/components/PageEditor.tsx
> -  const initialValue = editingMarkdown ?? '';
`editingMarkdown`は`currentPage?.revision?.body`で代用できたので削除しました

2022-11-24 08:33 UTC, yukendev commented on packages/app/src/components/Page/DisplaySwitcher.tsx
前のPRではページ更新の通知のlistenをPageStatusAlertに書いていましたが、PageViewに移動しました

2022-11-25 11:45 UTC, yuki-takei requested changes

2022-11-25 11:45 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> -  const initialValue = editingMarkdown ?? '';
これ useSWRxCurrentPage の revalidate (再 fetch) が走ったら、今編集中の markdown 吹っ飛ぶと思うんだけど

1. タブAで任意のページを編集し、保存しないで放置
2. タブBで同じページを表示し、編集、保存
3. タブAに戻る

で、タブA の useSWR による revalidateOnFocus が走って PageEditor(の CodeMirror) で編集中だったテキストが `currentPage?.revision?.body` で置き換わってしまう

2022-11-28 04:07 UTC, yukendev commented on packages/app/src/components/PageEditor.tsx
> -  const initialValue = editingMarkdown ?? '';
https://redmine.weseek.co.jp/issues/109716
後続タスクで実装しようとしていましたが、このPRに新しく含めました。
useSWRxPageをImmutableにすることで、revalidateしないようにしています

2022-11-28 06:38 UTC, yuki-takei requested changes

2022-11-28 06:38 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> -  const initialValue = editingMarkdown ?? '';
元に戻した方が安全だと思う。
開発者の誰かがどこかのコンポーネントで useSWRxPage か useSWRxCurrentPage を mutate したら同様の事象が起こる。それって予期しない挙動なんじゃないかな。

2022-11-28 11:32 UTC, yukendev commented on packages/app/src/components/PageEditor.tsx
> -  const initialValue = editingMarkdown ?? '';
考慮できてなかったのでもとに戻しました

2022-11-29 05:23 UTC, merged