feat: Use rehype sanitize plugin only when xss prevention is enabled
weseek/growi pull request #6985
Opened 2022-11-23 05:53 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/109549

- `isEnabledXssPrevention` が true の時だけ `rehype-plugin` を使う
- `isEnabledXssPrevention` が true の時だけ `verifySanitizePlugin` を実行

2022-11-24 07:20 UTC, yuki-takei requested changes

2022-11-24 07:20 UTC, yuki-takei commented on packages/app/src/services/renderer/renderer.tsx
> +  }
sanitize plugin を差し込む順番重要なのでこれでは NG

2022-11-24 08:01 UTC, Yohei-Shiina commented on packages/app/src/services/renderer/renderer.tsx
> +  }
対応済み

2022-11-24 08:05 UTC, yuki-takei requested changes

2022-11-24 08:05 UTC, yuki-takei commented on packages/app/src/services/renderer/renderer.tsx
> +  }
あんまりかっこよくないね。。

```
  rehypePlugins.push(
    slug,
    [lsxGrowiPlugin.rehypePlugin, { pagePath }],
    () => {
      // sanitize plugin を返したり返さなかったりする arrow function
    }(),
    katex,
    ...
  );
```
みたいにできないかね

2022-11-25 10:43 UTC, yuki-takei requested changes

2022-11-25 10:43 UTC, yuki-takei commented on packages/app/src/services/renderer/renderer.tsx
> +    ? [sanitize, deepmerge(commonSanitizeOption, lsxGrowiPlugin.sanitizeOption)]
こっちは `addLineNumberAttribute.sanitizeOption` がない

2022-11-25 10:43 UTC, yuki-takei commented on packages/app/src/services/renderer/renderer.tsx
> +    ? [sanitize, deepmerge(commonSanitizeOption, lsxGrowiPlugin.sanitizeOption)]
lsx いらない

2022-12-15 08:31 UTC, merged