feat: Add default markdown config values
weseek/growi pull request #6989
Opened 2022-11-24 06:03 UTC by Yohei-Shiina

https://redmine.weseek.co.jp/issues/109642

データベースへのデフォルトの用意まで。
使う側の改修は別タスクで対応

2022-11-24 07:32 UTC, yuki-takei requested changes

2022-11-24 07:32 UTC, yuki-takei commented on packages/app/src/server/models/config.ts
> +  'markdown:sanitize:option': 1,
enum 化して

2022-11-24 07:32 UTC, yuki-takei commented on packages/app/src/server/models/config.ts
> +  'markdown:sanitize:attrWhiteList': [],
remark-sanitize のデータモデルに相応しい名前・型にして

2022-11-24 11:32 UTC, Yohei-Shiina commented on packages/app/src/interfaces/rehype.ts
> +export type RehypeSanitizeOption = typeof RehypeSanitizeOption[keyof typeof RehypeSanitizeOption];
以下参考にした
https://typescriptbook.jp/reference/values-types-variables/enum/enum-problems-and-alternatives-to-enums#%E5%88%97%E6%8C%99%E5%9E%8B%E3%81%AE%E4%BB%A3%E6%9B%BF%E6%A1%882-%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%83%AA%E3%83%86%E3%83%A9%E3%83%AB

2022-11-25 10:02 UTC, Yohei-Shiina commented on packages/app/src/server/models/config.ts
> +  'markdown:rehypeSanitize:attributes': {},
> schema.js 踏襲で、tagNames は string[] で、attributes は { [key: string]: string[] | (string|boolean)[][] } っぽい型になる

2022-11-25 10:47 UTC, yuki-takei requested changes

2022-11-25 10:47 UTC, yuki-takei commented on packages/app/src/interfaces/rehype.ts
> +  CUSTOM: 2,
値は数字ではなく文字列の方がいいな

2022-11-29 06:55 UTC, merged