Imprv: gw7849 imprv bookmarks like sidebar
weseek/growi pull request #7011
Opened 2022-11-29 10:50 UTC by mudana-grune

https://youtrack.weseek.co.jp/issue/GW-7849
Test Result: 

https://user-images.githubusercontent.com/92426728/204509600-3cdfe851-6194-4bb0-87e4-e53de2ab326c.mp4

2022-11-30 06:59 UTC, kaoritokashiki commented on packages/app/src/components/Bookmarks/BookmarkItem.tsx
> +      }
Could you use the same component for each Bookmark contents? (`Sidebar` and `/me`).
If you think it's impossible, please tell me why.

especially, bookmarks tree is not difference between sidebar and /me

2022-12-05 04:13 UTC, kaoritokashiki commented on packages/app/src/components/Bookmarks/BookmarkFolderItem.tsx
> +  const getChildCount = useCallback((): number => {
@yuki-takei 
これって useCallback でもいけるが、 中身の処理的にuseMemoを使った方がいいのでしょうか。

```suggestion
  const childCount = useMemo((): number => {
```

2022-12-05 11:20 UTC, yuki-takei commented on packages/app/src/components/Bookmarks/BookmarkFolderItem.tsx
> +  const getChildCount = useCallback((): number => {
CountBadge にはメソッドの参照渡しではなく結果を渡しているだけなので、パフォーマンス的にはどちらも同程度かと。
可読性の面で useMemo でいいとは思う。

2022-12-05 11:24 UTC, kaoritokashiki requested changes

2022-12-05 11:24 UTC, kaoritokashiki commented on packages/app/src/components/Bookmarks/BookmarkFolderItem.tsx
> +  const getChildCount = useCallback((): number => {
@mudana-grune 

Please use useMemo 🙏 

```suggestion
  const childCount = useMemo((): number => {
```

2022-12-06 05:00 UTC, kaoritokashiki requested changes

2022-12-06 06:48 UTC, merged