support: resolve conflicts and fix lint errors
weseek/growi pull request #7013
Opened 2022-11-29 15:56 UTC by mizozobu

- [x] masterを取り込んでconflict解消
- [x] lint error修正

2022-11-29 16:09 UTC, mizozobu commented on packages/app/src/pages/admin/data-transfer.page.tsx
> +export default DataTransferPage;
`packages/app/src/pages/admin/[[...path]].page.tsx`がmasterで削除されてそれぞれのページに分かれていたので、g2g用のページを作成

2022-11-29 16:09 UTC, mizozobu commented on packages/app/src/server/service/config-manager.ts
>     * @returns file upload total limit in bytes
lint error修正

2022-11-29 16:09 UTC, mizozobu commented on packages/app/src/server/routes/apiv3/import.js
> +import { SupportedAction } from '~/interfaces/activity';
lint error修正

2022-11-29 16:09 UTC, mizozobu commented on packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> +const GeneratingTokensAndRegisteringProxyServiceProcess = (props) => {
masterでは`CustomCopyToClipBoard`がこのファイルにあったのでこの辺がコンフリクト

2022-11-29 16:09 UTC, mizozobu commented on packages/app/src/components/Admin/Common/AdminNavigation.jsx
> +        <MenuLink menu="search"       isListGroupItems isActive={isActiveMenu('/search')} />
`/data-transfer`が増えたのとwhitespaceの数が変わったのでこのへんもコンフリクト

2022-11-29 16:09 UTC, mizozobu commented on packages/app/src/components/Admin/Common/AdminNavigation.jsx
> +      /* eslint-enable no-multi-spaces, max-len */
`/data-transfer`が増えたのとwhitespaceの数が変わったのでこのへんもコンフリクト

2022-11-30 01:36 UTC, skomma requested changes

2022-11-30 01:36 UTC, skomma commented on packages/app/src/components/Admin/Common/AdminNavigation.jsx
> +      /* eslint-enable no-multi-spaces, max-len */
`data-transfer` だけ `mr-1` がついてないけど、いいの？

2022-11-30 13:41 UTC, merged