fix: Login users able to access invited page
weseek/growi pull request #7036
Opened 2022-12-05 10:51 UTC by kaoritokashiki

## Task
[Next.js] ログイン中に /invited にアクセスできてしまう
┗[110374](https://redmine.weseek.co.jp/issues/110374) 修正

## Description
-　[再現条件・ 症状 ・期待する動作](https://redmine.weseek.co.jp/issues/110144)　を確認

- `/invited` が 211行目より上にあるので存在しないページ(通常のページ)を表示させることはできないと判断しました。
- やったこととしては `/` にリダイレクトされるようにしました。
https://github.com/weseek/growi/blob/6c8bfa512878afdb3ae6002b2e4453b825760913/packages/app/src/server/routes/index.js#L82

## Before

https://user-images.githubusercontent.com/59536731/205624190-19738785-004f-45ce-909e-f1c7a85f32d8.mov

## After
invited user 以外は `/` にリダイレクトされるようにしました。

https://user-images.githubusercontent.com/59536731/205623691-bce93242-3653-45aa-bc4b-39249d15084b.mov

2022-12-05 10:52 UTC, kaoritokashiki commented on packages/app/src/server/routes/login.js
> +      const { redirectTo } = req.session;
ちなみに、このredirectTo には undefined がきます。

2022-12-05 12:37 UTC, yuki-takei requested changes

2022-12-05 12:37 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +      const { redirectTo } = req.session;
全然覚えてない、と思ったらオレじゃなかった
https://github.com/weseek/growi/pull/6186

2022-12-05 12:37 UTC, yuki-takei commented on packages/app/src/server/routes/login.js
> +      const { redirectTo } = req.session;
ただ元々 `/invited` にはついてなかったわけで、付けてしまって問題ないかどうかは定かではない…

少し考えて見たけどたぶん付けちゃだめなんだと思う。
メールに来た URL にアクセスして新しいユーザーを作る機能は、その時のブラウザセッション(ログインしているかどうか)は関係なく使えないといけないはず。

2022-12-07 08:09 UTC, kaoritokashiki commented on packages/app/src/pages/invited.page.tsx
> +    }
https://zenn.dev/uttk/scraps/acc7e67b0cd900 の記事を参考にしました。

2022-12-07 15:49 UTC, merged