Imprv: refactor tk
weseek/growi pull request #7048
Opened 2022-12-07 13:26 UTC by mizozobu

- [x] installされていなかった`form-data`を追加
- [x] transfer key周りのrefactor

2022-12-07 13:31 UTC, mizozobu commented on packages/app/src/server/models/transfer-key.ts
> -import loggerFactory from '../../utils/logger';
使ってないので削除

2022-12-07 13:31 UTC, mizozobu commented on packages/app/src/server/models/transfer-key.ts
> -const logger = loggerFactory('growi:models:transfer-key');
使ってないので削除

2022-12-07 13:31 UTC, mizozobu commented on packages/app/src/server/routes/apiv3/g2g-transfer.ts
> -import { SupportedAction } from '~/interfaces/activity';
使ってないので削除

2022-12-07 13:31 UTC, mizozobu commented on packages/app/src/utils/vo/transfer-key.ts
> +  static generateKeyString(key: string, appUrl: string): string {
URL objectが必要というわけではないのでURLをstringで渡す

2022-12-08 08:06 UTC, hakumizuki requested changes

2022-12-08 08:06 UTC, hakumizuki commented on packages/app/src/utils/vo/transfer-key.ts
> +  static generateKeyString(key: string, appUrl: string): string {
`appUrl` は `appSiteUrl` に統一した方が良さそうです

2022-12-08 09:07 UTC, skomma requested changes

2022-12-09 08:59 UTC, merged