support: 110607 show conflict diff modal
weseek/growi pull request #7053
Opened 2022-12-08 09:25 UTC by yukendev

https://redmine.weseek.co.jp/issues/110607

2022-12-08 09:29 UTC, yukendev commented on packages/app/src/components/Page/DisplaySwitcher.tsx
DBが更新されたタイミングで
- revisionId
- revisionBody
- lastUpdatedUser
- lastUpdatedAt
をswrで保持しています

2022-12-08 09:38 UTC, yukendev commented on packages/app/src/components/PageEditor/ConflictDiffModal.tsx
swrの情報を使用するため、undefinedのチェックを行う必要があったので、ConflictDiffModalコンポーネントの中でチェックを行い、ConflictDiffModalCoreコンポーネントには確実にundefinedじゃない値を渡すようにしました。その関係で、request, origin, latestオブジェクトの定義をConflictDiffModalCoreからConflictDiffModalに移動させています

2022-12-08 09:40 UTC, yukendev commented on packages/app/src/stores/modal.tsx
>  };
`PageStatusAlert`コンポーネントから`PageEditor`内のモーダルを開く必要があるので、swrでモーダルの開閉を管理しています。

2022-12-08 13:26 UTC, yuki-takei requested changes

2022-12-09 05:49 UTC, yukendev commented on packages/app/src/stores/modal.tsx
> +  };
修正髄m

2022-12-09 07:40 UTC, merged