fix: HackMD load styles
weseek/growi pull request #7062
Opened 2022-12-09 09:38 UTC by hakumizuki

Redmine: https://redmine.weseek.co.jp/issues/110840, https://redmine.weseek.co.jp/issues/110730

HackMD にスタイルが当たっていないのを修正しました

2022-12-09 09:41 UTC, hakumizuki commented on packages/app/src/server/routes/hackmd.js
> +    const stylesCSSLineBreaksRemoved = hackmdFiles.stylesCSS.replace(/(\r\n|\n|\r)/gm, ''); // https://stackoverflow.com/questions/10805125/how-to-remove-all-line-breaks-from-a-string
`ejs.render` によって以下のような文法的に壊れた文字列を含むコードが生成されていたので改行を取り除くことで回避

```javascript
const str = "string
";
```

2022-12-09 09:41 UTC, hakumizuki commented on packages/hackmd/src/hackmd-styles.js
> -  element.type = 'text/css';
不要なので削除

2022-12-10 06:44 UTC, yuki-takei requested changes

2022-12-10 06:44 UTC, yuki-takei commented on packages/app/src/server/routes/hackmd.js
> +    const stylesCSSLineBreaksRemoved = hackmdFiles.stylesCSS.replace(/(\r\n|\n|\r)/gm, ''); // https://stackoverflow.com/questions/10805125/how-to-remove-all-line-breaks-from-a-string
この処理って `@growi/hackmd` よりこっちでやるべき？検討して。

2022-12-12 03:25 UTC, merged