feat: Refactor install plugin feature without using execSync
weseek/growi pull request #7067
Opened 2022-12-11 12:47 UTC by jam411

task: https://redmine.weseek.co.jp/issues/110850

2022-12-12 04:28 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +          .get(url)
@yuki-takei 
SSRF対策のため、ユーザの入力が直接リクエストに入らないようにしないといけません。
相談したいです。

現状では `ghOrganizationName` と `ghReposNmae` が安全であることを確認すればいいので、
マーケットプレイスから情報を取得して Organization と reposName のホワイトリストのようなものを作って制御する?

2022-12-12 05:29 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +        }).then((res) => {
@yuki-takei
SSRF対策のため、ユーザの入力が直接リクエストに入らないようにしないといけません。
相談したいです。

現状では ghOrganizationName と ghReposNmae が安全であることを確認すればいいので、
マーケットプレイスから情報を取得して Organization と reposName のホワイトリストのようなものを作って制御する?

2022-12-12 06:58 UTC, yuki-takei requested changes

2022-12-12 06:58 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +        }).then((res) => {
いや、それだと野良プラグインを使えなくなってしまう。

user-provided value を validate すればいいと思う

2022-12-13 05:07 UTC, jam411 commented
yarn.lock ファイルの差分が発生し、build に失敗するので https://github.com/weseek/growi/pull/7082 に引き継ぎます。

2022-12-13 05:07 UTC, closed without merging