feat: Display plugin cards dynamically
weseek/growi pull request #7068
Opened 2022-12-11 12:58 UTC by jam411

task: https://redmine.weseek.co.jp/issues/110869

2022-12-17 20:52 UTC, yuki-takei requested changes

2022-12-17 20:52 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/plugins.ts
> +  router.get('/', async(req: any, res: any) => {
admin での利用に限っている他の route を参考に、middleware を設定してください。
他のエンドポイントも同様に。

## API 設計

- GET / は全てのプラグインを取得するように
    - enabled なものに限るかどうかはクライアント側でフィルタすればいいと思うが、もし必要であれば GET param で指定して既に実装済みの GrowiPlugin.findEnabledPlugins を使う
- GET /:id で単一プラグイン取得
    - enabled かどうかはクライアントで判断すればよい

2022-12-17 20:52 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +  async getPluginIsEnabled(targetPluginId: string): Promise<boolean> {
server/models/growi-plugin.ts に移動

2022-12-17 20:52 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +  async switchPluginIsEnabled(targetPluginId: string): Promise<boolean> {
server/models/growi-plugin.ts に移動

2022-12-17 20:52 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +    };
validation は route の責務

2022-12-17 20:52 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +    };
validation は route の責務

2022-12-17 20:52 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +  async pluginDeleted(targetPluginId: string): Promise<void> {
- これはサービスにあってもよい
- 命名を見直して
    - [/開発ガイドライン/命名規則](https://growi.weseek.co.jp/58f096e08f554b0018dcf923)
- ディレクトリの削除に成功したら DB document の削除を行うように修正

2022-12-17 20:52 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +  async getPlugins(): Promise<any> {
- このメソッドに限らないが、any の利用を避ける
- manifest の取得って必要だろうか？
    - 現状、必要な情報はインストール時に GrowiPlugin document に保存するようにしているので、なんらかの用途で必要ならその情報を拡張する方で検討したい

2022-12-17 20:52 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/plugins.ts
> +  router.post('/deleted', async(req: any, res: ApiV3Response) => {
DELETE /:id にして

2022-12-17 20:52 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/plugins.ts
> +  router.post('/get-isenabled', async(req: any, res: ApiV3Response) => {
このエンドポイントは不要

2022-12-17 20:52 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/plugins.ts
> +  router.post('/switch-isenabled', async(req: any, res: ApiV3Response) => {
PUT / にして

2022-12-20 03:34 UTC, jam411 commented on packages/app/src/server/routes/apiv3/plugins.ts
> +  router.get('/', async(req: any, res: any) => {
修正しました。

2022-12-20 03:35 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +  async pluginDeleted(targetPluginId: string): Promise<void> {
修正しました。

2022-12-20 03:35 UTC, jam411 commented on packages/app/src/server/routes/apiv3/plugins.ts
> +  router.post('/deleted', async(req: any, res: ApiV3Response) => {
修正しました。

2022-12-20 03:35 UTC, jam411 commented on packages/app/src/server/routes/apiv3/plugins.ts
> +  router.post('/switch-isenabled', async(req: any, res: ApiV3Response) => {
修正しました。

2022-12-20 03:38 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +  async switchPluginIsEnabled(targetPluginId: string): Promise<boolean> {
@yuki-takei 
イメージできず、そのままとしています。
巻き取りお願いします。

2022-12-20 03:39 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +  async getPluginIsEnabled(targetPluginId: string): Promise<boolean> {
@yuki-takei 
イメージできず、そのままとしています。
巻き取りお願いします。

2022-12-20 09:33 UTC, yuki-takei requested changes

2022-12-20 09:33 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +  }
- model に移す
- stringify, parse のコンボは any の利用と同じなので NG
- 返り値が boolean??
-

2022-12-20 09:33 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +      await growiPlugins.update({ isEnabled: !growiPlugins.isEnabled });
findOneAndUpdate() 使って

2022-12-20 09:33 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +    return growiPlugins.isEnabled;
これは変更後の値が返って来るのか？

2022-12-20 09:33 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/plugins.ts
> +    }
pluginService がないのはユーザーのせいではないので 4xx ではない

2022-12-20 13:29 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +  }
修正しました。

2022-12-20 13:29 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +      await growiPlugins.update({ isEnabled: !growiPlugins.isEnabled });
growi-plugin.ts に移動

2022-12-20 13:29 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +    return growiPlugins.isEnabled;
growi-plugin.ts に移動

2022-12-20 13:29 UTC, jam411 commented on packages/app/src/server/routes/apiv3/plugins.ts
> +    }
throw new Error に修正しました。

2022-12-20 13:30 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +  async getPluginIsEnabled(targetPluginId: string): Promise<boolean> {
server/models/growi-plugin.ts に移動しました。

2022-12-20 13:33 UTC, jam411 commented on packages/app/src/server/models/growi-plugin.ts
> +  deactivateStatus(id: Types.ObjectId): Promise<GrowiPlugin | null>
null able なのが気になります。

2022-12-20 14:44 UTC, yuki-takei requested changes

2022-12-20 14:44 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/plugins.ts
> +    }
- REST API ユーザーに対して親切な応答を
    - `pluginId` に相当する GrowiPlugin は存在するのか？
    - そのためには GrowiPluginModel 側ももう少しよく考える必要がある

2022-12-20 14:44 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +  }
このメソッドいるかな…

2022-12-26 07:14 UTC, yuki-takei requested changes

2022-12-26 07:14 UTC, yuki-takei commented on packages/app/src/server/models/growi-plugin.ts
> +};
このメソッドは不要 (素の find となんら変わらないので)

2022-12-26 09:17 UTC, merged