imprv: mv logics
weseek/growi pull request #7077
Opened 2022-12-12 15:28 UTC by mizozobu

- [x] TransferKeyの有効確認ロジックをG2GTransferReceiverServiceに持たせる
- [x] 書き込み権限確認のロジックをuploaderに持たせる
- [x] `fileUploadType`が`none`のときのエラー回避

2022-12-12 15:40 UTC, mizozobu commented on packages/app/src/server/service/file-uploader/uploader.js
> +  }
仮ファイルをアップロードするだけなので全storage共通

2022-12-12 15:40 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> -};
`uploader.getIsWritable`に移動

2022-12-12 15:40 UTC, mizozobu commented on packages/app/src/server/routes/apiv3/g2g-transfer.ts
> -      return res.apiv3Err(new ErrorV3('Transfer key has expired or not found.', 'transfer_key_expired_or_not_found'), 404);
`g2gTransferReceiverService.validateTransferKey`に移動。エラーは403だけにしました。

2022-12-12 15:40 UTC, mizozobu commented on packages/app/src/server/service/file-uploader/aws.ts
> +  lib.saveFile = async function({ filePath, contentType, data }) {
attachementではないファイルアップロード用の`saveFile`を各storageに作りました。

2022-12-12 15:40 UTC, mizozobu commented on packages/app/src/server/service/file-uploader/aws.ts
> -  lib.isValidUploadSettings = () => {
prototype継承をしているところなので、arrow functionとthisを気をつけるところなのに書き方が統一されてなかったので、arrow functionを使わない + thisを使わないように書き換えました。

|  | arrow function | function |
| :--: | :--: | :--: |
| `this` | ⚠️ | ✅ |
| `lib` | ✅ | ✅ |

2022-12-12 15:40 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> -};
分ける意味がないと思うので、`answerGROWIInfo`の中に移動しました

2022-12-12 15:49 UTC, mizozobu commented on packages/app/src/server/service/file-uploader/uploader.js
> +  }
実はまだこれ使ってないんですけど、書き込み権限がなかったらどうすべきですか

- g2g全体を中止
- ファイルの移行はしないでg2gする

2022-12-12 15:50 UTC, mizozobu commented on packages/app/src/server/service/file-uploader/none.js
> +    return [];
`none`のときにエラーにならないようにしました。詳細はコード内のコメントに。

2022-12-13 05:34 UTC, hakumizuki approved these changes

2022-12-13 05:34 UTC, hakumizuki commented on packages/app/src/server/service/file-uploader/uploader.js
> +  }
g2g全体を中止 がいいと思っています

2022-12-14 04:59 UTC, skomma requested changes

2022-12-14 04:59 UTC, skomma commented on packages/app/src/server/service/file-uploader/gcs.js
> +      && lib.configManager.getConfig('crowi', 'gcs:bucket') != null;
なんか configManager への辿り方が 3 種類くらいあるけど、これは統一しなくてもいいものなの？

* 単純に `configManager`
* `crowi.configManager`
* `lib.configManager`

2022-12-14 04:59 UTC, skomma commented on packages/app/src/server/service/file-uploader/uploader.js
> +  async getIsWritable() {
```suggestion
  async isWritable() {
```
じゃダメなの？
`getIsUploadble` とか `getIsReadble` とか気持ち悪い…

2022-12-14 13:02 UTC, mizozobu commented on packages/app/src/server/service/file-uploader/gcs.js
> +      && lib.configManager.getConfig('crowi', 'gcs:bucket') != null;
`configManager`に統一しました

2022-12-14 13:02 UTC, mizozobu commented on packages/app/src/server/service/file-uploader/uploader.js
> +  }
これは次のPRでやります

2022-12-14 18:48 UTC, skomma approved these changes

2022-12-14 18:48 UTC, merged