fix: Redirect to under /trash path
weseek/growi pull request #7087
Opened 2022-12-13 12:12 UTC by kaoritokashiki

2022-12-13 12:19 UTC, kaoritokashiki commented on packages/app/src/components/PageAlert/TrashPageAlert.tsx
> +      unlink();
unlink を実行したときの内部処理
https://github.com/weseek/growi/blob/e41b9650b02a486c7d4c267137777095413a58a0/packages/app/src/stores/page-redirect.tsx#L22

2022-12-13 12:36 UTC, yuki-takei requested changes

2022-12-13 12:36 UTC, yuki-takei commented on packages/app/src/components/PageAlert/TrashPageAlert.tsx
> +      unlink();
PageRedirectedAlert を参考にエラーハンドリングを追加してください

2022-12-15 10:47 UTC, kaoritokashiki commented on packages/app/src/components/PageAlert/TrashPageAlert.tsx
> +      unlink();
エラーハンドリングを 追加しました!

2022-12-15 11:33 UTC, merged