fix: disable sidebar button for guest
weseek/growi pull request #7089
Opened 2022-12-13 13:35 UTC by yukendev

2022-12-13 13:58 UTC, hakumizuki requested changes

2022-12-13 13:58 UTC, hakumizuki commented on packages/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  const { data: isGuest } = useIsGuestUser();
ここでやらないでください

2022-12-13 13:58 UTC, hakumizuki commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  const { data: isGuest } = useIsGuestUser();
ここでやらないでください

2022-12-14 07:33 UTC, yukendev commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
> +  const { data: isGuest } = useIsGuestUser();
ライブラリを導入することで修正

2022-12-14 07:34 UTC, yukendev commented on packages/app/src/components/Sidebar/PageTree/Item.tsx
>          )}
今まで`<i id='option-button-in-page-tree' className="icon-options fa fa-rotate-90 p-1"></i>`のみを`<NotAvailableForGuest>`で囲んでいましたが、ボタンが押せてしまったので全体を囲むようにしました

2022-12-14 07:37 UTC, yukendev commented on packages/app/package.json
>      "react-datepicker": "^4.7.0",
簡単にコンポーネント全体を`disabled`にすることができる`react-disable`をインストールしました

2022-12-14 10:23 UTC, merged