fix: Create new page using the page save shortcut leaves editor blank
weseek/growi pull request #7092
Opened 2022-12-14 17:55 UTC by miya

## Task
[#111057](https://redmine.weseek.co.jp/issues/111057) [Next化] ショートカットを使ってページの新規作成を行うとエディターが空白になる
└ [#111058](https://redmine.weseek.co.jp/issues/111058) 修正

2022-12-15 12:35 UTC, miya commented on packages/app/src/components/PageEditor.tsx
> +    if (!isNotFound || currentPage != null) {
isNotFound は context なので not found page からエディターを開き、ショートカットキーでページを新規作成する場合、ページ作成後に mutate される currentPage も見る必要がある

2022-12-16 05:59 UTC, yuki-takei requested changes

2022-12-16 05:59 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> +    if (!isNotFound || currentPage != null) {
うーん…なるほど

isNotFound を context から外して useStaticSWR 化すると他のところで問題でるかなあ？

## 確認

`stores/ui.tsx` で依存している custom swr がいくつかあるので、それらが正常動作するかどうかチェック
正常動作するなら useStaticSWR にしてよい

## useStaticSWR でも正常動作する場合

`[[...path]].page.tsx` で
```
  // sync grant data
  useEffect(() => {
    mutateSelectedGrant(grantData?.grantData.currentPageGrant);
  }, [grantData?.grantData.currentPageGrant, mutateSelectedGrant]);
```
と同様、useSWRxCurrentPage の結果如何でデータが変わったら mutate する

2022-12-16 05:59 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> +  }, [isNotFound, currentPage, isEnabledAttachTitleHeader, currentPathname, templateBodyData, editingMarkdown]);
currentPage は大きなオブジェクトなので deps に入れたくない

2022-12-16 05:59 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> +  }, [currentPage, mutateEditingMarkdown]);
この useEffect は別の問題を引き起こす

2022-12-16 07:27 UTC, closed without merging