imprv: Apply getLayout to page
weseek/growi pull request #7097
Opened 2022-12-15 06:51 UTC by hakumizuki

# Redmine
- https://redmine.weseek.co.jp/issues/111337
- https://redmine.weseek.co.jp/issues/111048

# やったこと
- getLayout を `[[...path]].page.tsx` に適用
- react の list 関係の warning を解消

2022-12-15 06:52 UTC, hakumizuki commented on packages/app/src/components/Navbar/AppearanceModeDropdown.tsx
> +        )}
warning 解消。`[]` だと List 扱いになるぽい

2022-12-15 06:52 UTC, hakumizuki commented on packages/app/src/pages/[[...path]].page.tsx
> +      <HandsontableModal />
この部分を layout とした

2022-12-15 07:30 UTC, hakumizuki commented on packages/app/src/pages/admin/plugins.page.tsx
> +        </Head>
未修正だったので修正

2022-12-20 03:00 UTC, hakumizuki commented on packages/app/src/stores/ui.tsx
> +      // }
一旦無効化

2022-12-20 03:02 UTC, hakumizuki commented on packages/app/src/client/services/layout.ts
> +  // }
一旦無効化。修正ストーリーは起票済み

2022-12-20 03:03 UTC, hakumizuki commented on packages/app/src/styles/_layout.scss
> +.dynamic-layout-root.growi-layout-fluid .grw-container-convertible {
getLayout 外の layout-root として `dynamic-layout-root` を追加した

2022-12-20 09:25 UTC, yuki-takei requested changes

2022-12-20 09:25 UTC, yuki-takei commented on packages/app/src/stores/ui.tsx
> +      // }
コメントにストーリーURL追加して

2022-12-20 12:57 UTC, merged