fix: 111380 unlink for trash pagelist
weseek/growi pull request #7107
Opened 2022-12-16 10:12 UTC by kaoritokashiki

2022-12-16 10:38 UTC, kaoritokashiki commented on packages/app/src/stores/page-redirect.tsx
> +  unlink(path?: string): Promise<void>
引数にpathを入れた場合、そのパスをunlinkできるように改修しました。

2022-12-17 22:13 UTC, yuki-takei requested changes

2022-12-17 22:13 UTC, yuki-takei commented on packages/app/src/stores/page-redirect.tsx
> +  unlink(path?: string): Promise<void>
ちょっと追加のリファクタを

- unlink の処理を、client/services/page-operation に移植
    - 引数は `path: string`
- useRedirectFrom.unlink は page-operetion から import した unlink メソッドのラッパーにする
    - 従来通り引数無しで使えて良くて、useCurrentPagePath の内容を入れる
    - currentPagePath が null なら throw error
    - これを使うのは PageRedirectedAlert のみ
- PageListItemL および TrashPageAlert からは page-operetion から import した unlink をそのまま使う

2022-12-17 22:13 UTC, yuki-takei commented on packages/app/src/components/PageList/PageListItemL.tsx
> +        await unlink(`/trash${path}`);
この `/trash` を頭に付ける処理がなぜ必要なのかがわかっていない。
ゴミ箱内のページは `/trash/page` になっているのではないか？ test/integration/service でも `expect(resultPage.path).toBe('/trash/parentForDelete1');` という expect をしている。

2022-12-19 10:17 UTC, kaoritokashiki commented on packages/app/src/stores/page-redirect.tsx
> +  unlink(path?: string): Promise<void>
なるほど、ありがとうございます。そのように修正いたしました。

2022-12-19 10:38 UTC, kaoritokashiki commented on packages/app/src/components/PageList/PageListItemL.tsx
> +        await unlink(`/trash${path}`);
みている場所が違っていまして、ページの削除ではなく、「元に戻す」の時のパスです。
なので、`deletePage`ではなく`pageService.revertDeletedPage` を実行したときに帰ってくるパスが、PutbackPageModal の onPutBackedの引数に入ります。そのパスは `/trash/fuga` ではなく `/fuga` が入ります。

https://github.com/weseek/growi/blob/9701591cc4f8635cb8c176c1e7bc7e89b68659f1/packages/app/src/server/routes/page.js#L1369

https://github.com/weseek/growi/blob/16b428759a52ab5a98159696728f5ff5ad142787/packages/app/src/components/PutbackPageModal.jsx#L49

2022-12-19 10:39 UTC, kaoritokashiki commented on packages/app/src/components/PageList/PageListItemL.tsx
> +        await unlink(pageData.path);
putBackedHandler　から渡ってくる引数(path) ではなく、`pageData.path` だと /trash/fuga
が入ってくるので、そちらを利用するようにしました。

2022-12-19 10:53 UTC, yuki-takei commented on packages/app/src/stores/page-redirect.tsx
> +  unlink(path?: string): Promise<void>
TrashPageAlert も書き換えて

2022-12-19 11:01 UTC, kaoritokashiki commented on packages/app/src/stores/page-redirect.tsx
> +  unlink(path?: string): Promise<void>
あれ、すみません、
TrashPageAlert は　useRedirectFrom.unlink　を使うではダメなのでしょうか??

2022-12-19 11:30 UTC, kaoritokashiki commented on packages/app/src/stores/page-redirect.tsx
> -    },
useRedirectFrom  の util `unlink()` を廃止しました。

2022-12-19 11:59 UTC, merged