imprv: mv logics
weseek/growi pull request #7109
Opened 2022-12-17 07:36 UTC by mizozobu

- [x] storageのwrite権限が無いときにG2Gを中止する
- [x] 引数`shouldEmit`が全体的に不要だったので削除
- [x] contollerからserviceにロジック移動
- [x] typing改善とJSDoc記載

2022-12-17 07:41 UTC, mizozobu commented on packages/app/src/components/Admin/G2GDataTransfer.tsx
> -      apiv3Get<{status: { zipFileStats: any[], isExporting: boolean, progressList: any[] }}>('/export/status', {}),
使ってないので削除しました

2022-12-17 07:41 UTC, mizozobu commented on packages/app/src/server/routes/apiv3/g2g-transfer.ts
> -      });
`g2gTransferReceiverService.getImportSettingMap`に移動

2022-12-17 07:41 UTC, mizozobu commented on packages/app/src/server/routes/apiv3/g2g-transfer.ts
> -      await crowi?.appService?.setupAfterInstall();
`g2gTransferReceiverService.importCollections`に移動

2022-12-17 07:41 UTC, mizozobu commented on packages/app/src/server/routes/apiv3/overwrite-params/pages.js
> -
modelがロードされる前に実行されてエラーになるため、必要なときに実行するようにしました

2022-12-17 07:41 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> -   */
JSDocは基本的にinterfaceに記載してます

2022-12-17 07:41 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> +   * @param {Readable} fileStream Attachment data(loaded from storage)
privateはinterfaceに定義できないのでclassにJSDoc記載しました

2022-12-17 07:42 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> -  public async startTransfer(tk: TransferKey, user: any, toGROWIInfo: IDataGROWIInfo, collections: string[], optionsMap: any, shouldEmit = true): Promise<void> {
`toGROWIInfo`は使ってないので削除しました

2022-12-23 01:25 UTC, hakumizuki approved these changes

2022-12-23 01:43 UTC, skomma requested changes
命名だけ。

2022-12-23 01:43 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +  public getAxiosConfig(tk: TransferKey, config: AxiosRequestConfig = {}): AxiosRequestConfig {
`get` に違和感があるなぁ。元々すべてが決まっていた値ではないものから作り出すので、`generate` と命名していた。
あと、`config` という引数も、`baseConfig` の方がより適切？

2022-12-23 01:43 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +const uploadConfigKeys = [
```suggestion
const UPLOAD_CONFIG_KEYS = [
```
file 内の global な const 定義の変数名なら大文字/snake_case の方がよいと思う。

2022-12-24 03:52 UTC, skomma requested changes

2022-12-24 03:52 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +  public generateAxiosBaseConfig(tk: TransferKey, config: AxiosRequestConfig = {}): AxiosRequestConfig {
```suggestion
  public generateAxiosConfig(tk: TransferKey, baseConfig: AxiosRequestConfig = {}): AxiosRequestConfig {
```
意図としてはこっちだった…
ここで作り出したものが base になるというより、base を入れて axios.get なり post なりするときのパラメータを作り出す、という使い方をしているので。

2022-12-25 04:34 UTC, skomma approved these changes

2022-12-25 04:34 UTC, merged