fix: unsaved alert in hackmd editor
weseek/growi pull request #7117
Opened 2022-12-19 12:54 UTC by yukendev

https://redmine.weseek.co.jp/issues/111482

2022-12-19 12:57 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
> +
初期状態では常にアラートは出ない状態

2022-12-19 12:57 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
ショートカットキーで保存した場合はアラートが出ないようにする

2022-12-19 12:58 UTC, yukendev commented on packages/app/src/components/PageEditorByHackmd.tsx
文章が変更されたタイミングで、アラートが出るようにする

2022-12-20 08:28 UTC, yuki-takei requested changes

2022-12-20 08:28 UTC, yuki-takei commented on packages/app/src/components/PageEditorByHackmd.tsx
> +
これ入れちゃうと、PageEditor 開いて編集して true になってから HackMD 開いたら false になっちゃわないかな
(逆もまた然りかもしれないが)

2022-12-20 11:42 UTC, merged