feat: Plugin reinstall features
weseek/growi pull request #7122
Opened 2022-12-20 07:08 UTC by jam411

- [ ] インストール済みの plugin を再インストールできる
task: 
https://redmine.weseek.co.jp/issues/111178
https://redmine.weseek.co.jp/issues/110882

- [ ] fs にリポジトリがない場合自動で再インストールできる
task:
https://redmine.weseek.co.jp/issues/111558

2022-12-20 12:09 UTC, yuki-takei requested changes

2022-12-20 12:09 UTC, yuki-takei commented on packages/app/src/pages/_document.page.tsx
> +    await (pluginService as IPluginService).reintallNotExistPluginRepositories();
これだとリクエスト毎に試行されてしまう。
サーバー起動時に一度やればいいだけ。PluginService セットアップ時とか。

2022-12-20 12:09 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +          await this.install(growiPlugin.origin);
install 失敗したら消すだけになってしまう。
GrowiPlugin は弄らずにダウンロードさせるだけにしてください。

2022-12-22 14:19 UTC, jam411 commented on packages/app/src/server/crowi/index.js
> +  await this.pluginService.downloadNotExistPluginRepositories();
pluginService の setup 時に実行。
このときにネットワークに接続できていないとインストールに失敗する。

2022-12-22 14:20 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +        throw new Error('Filed to rename path.');
ユーザまで投げるのは簡単な文字列。
loggerにはエラーログを残す。

2022-12-22 14:20 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +      throw err;
次のインスタンスへエラーを渡す。

2022-12-22 14:25 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +          await this.downloadPluginRepository(ghOrganizationName, ghReposName, ghBranch);
冗長だが、正規の install のものをそのまま拝借、todo タスクのときにリファクタしたいです。

2022-12-22 14:28 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +      await this.deleteOldPluginDocument(installedPath);
install 時に、リポジトリをダウンロードした後、同じ installedPath の document がすでにあるかをチェックしてあればここで削除する。

2022-12-22 22:17 UTC, yuki-takei requested changes

2022-12-22 22:17 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/plugins.ts
> +      }
pluginService が null であることは有り得ないので現状のコードでもあまり問題はないが、
本来的には route が throw error することは避ける。なぜなら UnhandledException に落ちるしか道がないから。
ここは 500 エラーをユーザーに知らせるのが望ましい。

2022-12-22 22:17 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +    if (growiPlugin) await GrowiPlugin.findOneAndDelete({ installedPath: path });
- また、findOne してから findOneAndDelete する必要はなく、findAndDelete を 1回呼ぶだけでよい
- savePluginMetaData を見ると分かるが、複数の GrowiPlugin document が insert される
    - つまり、installedPath が一致するものを全て消す必要があるので deleteMany を使う

2022-12-23 11:20 UTC, merged