Feat/110268 111686 get questionnaire order periodically
weseek/growi pull request #7153
Opened 2022-12-24 07:53 UTC by arafubeatbox

2022-12-24 08:23 UTC, arafubeatbox commented on packages/app/package.json
> +    "node-cron": "^3.0.2",
node 内の cron job 実行のために追加しました。
[LICENSE](https://github.com/node-cron/node-cron/blob/master/LICENSE.md) 的に使って大丈夫だと思っています。

[THIRD-PARTY-NOTICES](https://github.com/weseek/growi/blob/master/THIRD-PARTY-NOTICES.md) はほぼ武井さんしかいじっていなかったので一旦いじりませんでした。

2023-01-05 04:35 UTC, hakumizuki requested changes

2023-01-05 04:35 UTC, hakumizuki commented on packages/app/src/server/service/config-loader.ts
> +    key: 'app:growiQuestionnaireUri',
`GROWI_QUESTIONNAIRE_SERVER_ORIGIN` の方が直接的でいいかなと思います

2023-01-05 04:35 UTC, hakumizuki commented on packages/app/src/server/service/questionnaire-cron.ts
> +  }
今回の場合は環境変数でしか設定値を変更しないので大丈夫なのですが、コンストラクタで設定値を初期化してしまうと、設定値を UI 上で変更可能にした場合などに対応できなくなってしまうので、使う時に取得するのがいいかと思います

2023-01-05 04:35 UTC, hakumizuki commented on packages/app/src/server/service/questionnaire-cron.ts
> +        const response = await axios.get(`${this.growiQuestionnaireUri}/questionnaire-order/index`);
`axios-retry` を使うと簡単にリトライできるので、もし余裕あれば変更お願いします。既に GROWI で使われてます

https://www.npmjs.com/package/axios-retry

2023-01-06 01:02 UTC, arafubeatbox commented on packages/app/src/server/service/questionnaire-cron.ts
> +        const response = await axios.get(`${this.growiQuestionnaireUri}/questionnaire-order/index`);
https://github.com/softonic/axios-retry/issues/159
custom axios instance を使おうとするとエラーが起こるみたいで、growi で現在使われている場所と同じく、default の axios を使うようにしました。
https://github.com/weseek/growi/blob/003565bbf75d8afdf4c3d1ed4aba53baf0c2098c/packages/app/src/server/service/passport.ts#L685

2023-01-06 04:14 UTC, merged