feat: Update error handling to clean up data
weseek/growi pull request #7161
Opened 2022-12-26 07:26 UTC by jam411

task: https://redmine.weseek.co.jp/issues/111177

- [ ] zip のダウンロード、展開失敗、または DB へのデータ保存失敗時にデータをクリーンアップする

2022-12-26 10:27 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +      await this.cleanUp(installedPath, ghBranch);
同じ Github URL のプラグインがインストールされていた場合は、インストール時の例外処理で cleanUp() してしまうとインストール済みの repository と documents も削除されてしまう。
仕方ないこととしてインストール処理のはじめと例外時に cleanUp() を行うようにする。

2022-12-26 10:29 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
>    }
一括して掃除する関数

2022-12-26 11:19 UTC, yuki-takei requested changes

2022-12-26 11:19 UTC, yuki-takei commented on packages/app/src/server/service/plugin.ts
> +      await this.cleanUp(installedPath, ghBranch);
ごめん、やっぱりゴールを変更しここまでやってください

1. まずダウンロード(rename の手前まで)
2. detectPlugins
    - 今ファイルが存在する tmpPath と、本来のインストール先である installedPath は区別して処理する
3. detect 成功したら 旧ファイルは消して tmpPath から installedPath へ rename、  
    失敗したらダウンロード済みファイルを消す

2022-12-27 02:26 UTC, jam411 commented on packages/app/src/server/service/plugin.ts
> +      })
このサービスではurlバリデーションしているので false positive にします。
ssrf guard が必要なことをコメントを残しました。

2022-12-27 07:42 UTC, merged