imprv: error handling
weseek/growi pull request #7169
Opened 2022-12-26 15:33 UTC by mizozobu

- [x] Admin画面のconsole error修正
- [x] Transfer Key発行エラー時にtoast表示
- [x] G2G移行開始時にレスポンスを返すようにリファクタ
- [x] ファイル移行エラー時にtoast表示

2022-12-26 15:41 UTC, mizozobu commented on packages/app/src/client/services/g2g-transfer.ts
> -    });
`throttle`と`useMemo`の理由がよくわからなかったので書き換えました

2022-12-26 15:41 UTC, mizozobu commented on packages/app/src/components/Admin/G2GDataTransfer.tsx
> +    }
Transfer Key発行エラー時にtoast表示

2022-12-26 15:41 UTC, mizozobu commented on packages/app/src/components/Admin/G2GDataTransferExportForm.tsx
> +            return null;
`Fragment`でも`key`がないとunique keyつけろエラーが出てました

2022-12-26 15:41 UTC, mizozobu commented on packages/app/src/components/Admin/G2GDataTransferExportForm.tsx
> +                isImporting={false}
prop type error修正

2022-12-26 15:41 UTC, mizozobu commented on packages/app/src/components/Admin/G2GDataTransferExportForm.tsx
> -  const WarnForGroups = ({ errors, key }): JSX.Element => {
`key`はpropsとして指定すると`undefined`なってしまいます。

2022-12-26 15:41 UTC, mizozobu commented on packages/app/src/server/routes/apiv3/g2g-transfer.ts
> +      g2gTransferPusherService.startTransfer(tk, req.user, collections, optionsMap);
長時間responseが返ってこない事がありそうだったのでawait外しました

2022-12-26 15:41 UTC, mizozobu commented on packages/app/src/server/routes/apiv3/g2g-transfer.ts
> -      return res.apiv3Err(new ErrorV3(err.message, err.code), 500);
エラーはwebsocketで返すので不要

2022-12-26 15:41 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> +            key: `Error occured when uploading Attachment(ID=${attachment.id})`,
転送失敗1ファイルごとにtoastが出ます。

serverのエラーをtranslationにparamsを渡す方法が確立されていないので一旦これで

2023-01-05 19:54 UTC, skomma requested changes

2023-01-05 19:54 UTC, skomma commented on packages/app/src/components/Admin/G2GDataTransferExportForm.tsx
> +            return <li key={error}>{error}</li>;
これ `error` ってエラー文言が入った文字列が入ってくる想定？
なんか公式を見る限り、index を含めたもっと単純なものを設定したほうがあまり何も考えずに uniqueness も保証されるし、よさそうな感じがしたので。

https://ja.reactjs.org/docs/lists-and-keys.html

あと、そうすると `eslint-disable-next-line` 不要にならん？

2023-01-05 19:54 UTC, skomma commented on packages/app/src/server/routes/apiv3/g2g-transfer.ts
> +      g2gTransferPusherService.startTransfer(tk, req.user, collections, optionsMap);
非同期でやるなら try/catch 不要じゃない？
await しないなら絶対に catch の中に入らないと思うが。

2023-01-06 13:03 UTC, mizozobu commented on packages/app/src/server/routes/apiv3/g2g-transfer.ts
> +      g2gTransferPusherService.startTransfer(tk, req.user, collections, optionsMap);
たしかにそうなのでtry catch消しました

2023-01-06 13:03 UTC, mizozobu commented on packages/app/src/components/Admin/G2GDataTransferExportForm.tsx
> +            return <li key={error}>{error}</li>;
要素が増減しないのでindexにしました。`eslint-disable-next-line`なくてもOKみたいです。

2023-01-07 01:49 UTC, skomma approved these changes

2023-01-07 01:50 UTC, merged