Feat/110280 112131 112133 questionnaire order save
weseek/growi pull request #7211
Opened 2023-01-04 14:37 UTC by arafubeatbox

2023-01-06 11:35 UTC, arafubeatbox commented on packages/app/src/server/service/questionnaire-cron.ts
> +        await saveOrders(questionnaireOrders);
最初に全てのアンケートを消し、growi-questionnaire にある、終了していないアンケートを保存するので、
- 過去に保存されたが、growi-questionnaire 上で更新されたアンケート -> 更新される
- 過去に保存されたが、growi-questionnaire 上で削除されたアンケート -> 削除される
ようになっています。

QuestionnaireOrder から他の collection の document を参照することは無い（と思っている）ので、最初に全削除でも問題なく更新されると思ってます。

2023-01-06 11:39 UTC, arafubeatbox commented on packages/app/src/server/service/questionnaire-cron.ts
>    }
stop しないと jest が終了しないので追加しました。
test を記述していなかったとしても test 外でも stop できるようにはしておいたほうが良いのかと思っています。

2023-01-06 11:39 UTC, arafubeatbox commented on packages/app/src/server/service/questionnaire-cron.ts
> +    this.cronJob.stop();
stop しないと jest が終了しないので追加しました。
test を記述していなかったとしても test 外でも stop できるようにはしておいたほうが良いのかと思っています。

2023-01-12 04:41 UTC, hakumizuki commented on packages/app/src/interfaces/questionnaire/condition.ts
> +  versionRegExps: string[] // GROWI versions to show questionnaire in
`determine which GROWI types to show questionnaires to`

2023-01-12 04:48 UTC, hakumizuki commented on packages/app/src/interfaces/questionnaire/growi-info.ts
> +  appSiteUrl: string // it may be hashed
[内部仕様](https://dev.growi.org/6385911e1632aa30f4dae6a4#mdcont-%E8%A1%A8%E7%A4%BA%E3%81%97%E3%81%9F%E3%81%84%E3%82%A2%E3%83%B3%E3%82%B1%E3%83%BC%E3%83%88%E6%83%85%E5%A0%B1%E3%81%AE%E4%BF%9D%E6%8C%81) 通りの、以下の型でお願いします

```ts
type GrowiInfo = {
  ...
  appSiteUrl?: string
  appSiteUrlHashed: string
  ...
}
```

2023-01-12 05:10 UTC, hakumizuki requested changes

2023-01-12 05:10 UTC, hakumizuki commented on packages/app/src/server/service/questionnaire-cron.ts
> +        await saveOrders(questionnaireOrders);
> 他の collection の document から QuestionnaireOrder を参照する

このときに、同一の QuestionaireOrder かどうかを決めるためのユニークなキーが必要そうです。アンケートセンター側で id を確定させて、それを GROWI 側で識別するのに使うのがいいかと思います。
Slack で議論されていたのを見ると、MongoID でも良さそうですね。

2023-01-12 05:10 UTC, hakumizuki commented on packages/app/test/integration/service/questionnaire-cron.test.ts
> +import QuestionnaireOrder from '../../../src/server/models/questionnaire/questionnaire-order';
忘れていたんですが、GROWI のテストコード中の文字列も全て英語でお願いします

2023-01-16 02:26 UTC, merged