imprv: Do not use api for fetching pages when using shared pages
weseek/growi pull request #7213
Opened 2023-01-05 08:46 UTC by miya

## Task
[#112499](https://redmine.weseek.co.jp/issues/112499) [Next.js] SharedPage で /_page/v3/page を叩かないようにする
└ [#112501](https://redmine.weseek.co.jp/issues/112501) 改善

2023-01-05 08:58 UTC, miya commented on packages/app/src/stores/page.tsx
> +    isSharedPage ? null : (endpoint, pageId, shareLinkId, revisionId) => apiv3Get<{ page: IPagePopulatedToShowRevision }>(endpoint, { pageId, shareLinkId, revisionId })
sharedPage 時は fetcher を null にすることで、api 通信をせずに initialData を参照するようにしました

2023-01-05 12:03 UTC, yuki-takei requested changes

2023-01-05 12:03 UTC, yuki-takei commented on packages/app/src/pages/share/[[...path]].page.tsx
> +      props.page = page.toObject();
toObject するのではなく、`pages/[[...path]].page.tsx` の `superjson.registerCustom<IPageToShowRevisionWithMeta, IPageToShowRevisionWithMetaSerialized>` を共通化する

2023-01-05 12:03 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    isSharedPage ? null : (endpoint, pageId, shareLinkId, revisionId) => apiv3Get<{ page: IPagePopulatedToShowRevision }>(endpoint, { pageId, shareLinkId, revisionId })
useSWRxCurrentPage 側で対処できない？

2023-01-05 12:03 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const { data: currentPage, mutate: mutateCurrentPage } = useSWRxCurrentPage();
ここの引数消す必要ある？(デグレして別の症状出そう)

2023-01-06 13:26 UTC, miya commented on packages/app/src/pages/share/[[...path]].page.tsx
> +
shared page 用の type と  serializer を新規に作成しました

2023-01-06 13:26 UTC, miya commented on packages/app/src/stores/page.tsx
> +export const useSWRxCurrentPage = (initialData?: IPagePopulatedToShowRevision|null): SWRResponse<IPagePopulatedToShowRevision|null, Error> => {
`shareLinkId` 引数を廃止しました

2023-01-06 13:26 UTC, miya commented on packages/app/src/stores/page.tsx
> +  const shouldFetch = pageId != null && !isSharedPage;
shared page に居る場合は fetch しない

2023-01-06 13:26 UTC, miya commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  currentPage?: IPagePopulatedToShowRevision,
page のデータは props から取ってくるようにしました

2023-01-06 13:26 UTC, miya commented on packages/app/src/components/Page.tsx
> +  currentPage?: IPagePopulatedToShowRevision,
page のデータは props で取ってくるようにしました

2023-01-06 13:27 UTC, miya commented on packages/app/src/pages/share/[[...path]].page.tsx
> +      props.page = page.toObject();
ここで toObject をせずに superjson を使ってシリアライズするようにしました

2023-01-06 14:41 UTC, yuki-takei requested changes

2023-01-06 14:41 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +  const shouldFetch = pageId != null && !isSharedPage;
useSWRxPage は元に戻す(shareLinkId 月でリクエストを送れるという仕様は残す)

2023-01-06 20:51 UTC, yuki-takei approved these changes

2023-01-06 20:51 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +  );
useShareLinkId 復活、設定時は config 値を渡して fetcher を上書きする

2023-01-06 20:51 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    config,
config に fetcher を入れていれば上書きできるが、そもそも自動 fetch を無効にしたいわけなので、SWR@v2 にアップグレードしたら useSWRMutation を使うのがよさそう

2023-01-06 21:14 UTC, merged