imprv: Do not use API to get tag on shared page
weseek/growi pull request #7214
Opened 2023-01-05 10:40 UTC by miya

## Task
[#112601](https://redmine.weseek.co.jp/issues/112601) [Next.js] SharedPage で /pages.getPageTag を叩かないようにする
└ [#112601](https://redmine.weseek.co.jp/issues/112601) [Next.js] SharedPage で /pages.getPageTag を叩かないようにする

2023-01-10 06:55 UTC, yuki-takei requested changes

2023-01-10 06:55 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +  const isSharedPage = _isSharedPage(pathname ?? '');
useShareLinkId で判定するロジックに統一した方がよくない？

2023-01-10 06:55 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    !isSharedPage && pageId != null && termNumber != null ? ['/page/info', pageId, fixedShareLinkId, termNumber] : null,
まず `routes/apiv3/page.js` の `/info` の仕様を確認して、それに合わせて。送ってるパラメータとかぐちゃぐちゃ。。

このエンドポイントは share link に対応してる気がするんだけど。(route 側に certifySharedPage がある)
リクエストしない方がいいならそのように改修する、でいいと思うんだけど、その場合上で書いたようにパラメータを整頓して整合性とって。

2023-01-11 01:40 UTC, miya commented on packages/app/src/stores/page.tsx
> +  const isSharedPage = _isSharedPage(pathname ?? '');
useShareLinkId で判断するようにしました

2023-01-11 01:40 UTC, miya commented on packages/app/src/stores/page.tsx
> +    !isSharedPage && pageId != null && termNumber != null ? ['/page/info', pageId, fixedShareLinkId, termNumber] : null,
`/_api/v3/page/info` は Basic Auth のホワイトリストに入れることにしたので修正はしない方向で行きます

2023-01-11 08:05 UTC, yuki-takei approved these changes

2023-01-11 08:06 UTC, merged