fix: 112734 delete page modal label
weseek/growi pull request #7224
Opened 2023-01-10 06:01 UTC by yukendev

2023-01-10 06:59 UTC, yuki-takei requested changes

2023-01-10 06:59 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +};
Next Page に特化したコンポーネントは、ページ側に作ればいいんじゃないかな

2023-01-10 07:38 UTC, yukendev commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +};
修正済み

2023-01-10 07:52 UTC, yuki-takei requested changes

2023-01-10 07:52 UTC, yuki-takei commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +export const GrowiContextualSubNavigationSubstance = (props: GrowiContextualSubNavigationSubstanceProps): JSX.Element => {
これはファイル名と合わせて(つまり元に戻して)

2023-01-10 09:45 UTC, yukendev commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +export const GrowiContextualSubNavigationSubstance = (props: GrowiContextualSubNavigationSubstanceProps): JSX.Element => {
修正済み

2023-01-12 06:02 UTC, yukendev commented on packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
>    return (
SubNavigationSwitcherが有効化された関係で、`grw-contextual-sub-nav`で複数のコンポーネントが参照されてしまい、cypressのエラーが出ていたのでGrowiSubNavigationのラッパーで`test-id`を管理するようにしました

2023-01-12 06:03 UTC, yukendev commented on packages/app/src/pages/[[...path]].page.tsx
> +  return (
この部分で`test-id`を設定しています

2023-01-12 06:03 UTC, yukendev commented on packages/app/src/pages/share/[[...path]].page.tsx
> +  return (
この部分で`test-id`を設定しています

2023-01-13 10:26 UTC, merged