feat: fileuploadtype none
weseek/growi pull request #7247
Opened 2023-01-12 16:56 UTC by mizozobu

https://redmine.weseek.co.jp/issues/113021

移行先のストレージタイプが none の時に内部仕様通りの挙動になる

2023-01-12 17:00 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
>          // TODO: i18n for reason
移行先の`fileUploadType`を使うのにwrite権限がないときは中止

2023-01-13 09:26 UTC, skomma approved these changes
すっげー細かい変数名の修正だけ。
変数名修正だけ別タスクでもいいです。

2023-01-13 09:26 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +    if (shouldUseFileUploadTypeOfNewGrowi && !toGROWIInfo.attachmentInfo.writable) {
`toGROWI` `NewGrowi` で表記が揺れてるのが気になった。
`destGROWI` とかにすれば統一できる？

そうなると、`fromGROWI` も `srcGROWI` にしたくなってくる…

2023-01-14 22:12 UTC, skomma requested changes
ちゃんと見たら表現の問題でもっと出てきちゃった。

2023-01-14 22:12 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +        reason: 'File upload is disabled in dest GROWI.',
```suggestion
        reason: 'The file upload setting is disabled in the destination GROWI.',
```

2023-01-14 22:12 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +        reason: `The number of active users (${activeUserCount} users) exceeds the limit of dest GROWI (to up ${destGROWIInfo.userUpperLimit} users).`,
```suggestion
        reason: `The number of active users (${activeUserCount} users) exceeds the limit of the destination GROWI (up to ${destGROWIInfo.userUpperLimit} users).`,
```

2023-01-14 22:12 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +        reason: `Total file size exceeds file upload limit of dest GROWI. Requires ${totalFileSize.toLocaleString()} bytes, but got ${(destGROWIInfo.fileUploadTotalLimit ?? Infinity).toLocaleString()
```suggestion
        reason: `The total file size of attachments exceeds the file upload limit of the destination GROWI. Requires ${totalFileSize.toLocaleString()} bytes, but got ${destGROWIInfo.fileUploadTotalLimit.toLocaleString()} bytes.`,
```
この if 分に入るときに、Inifinity のケースなくね？

2023-01-14 22:12 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +    if ((destGROWIInfo.fileUploadTotalLimit ?? Infinity) < totalFileSize) {
これ別タスク対応でいいと思うんだけど、既に引っ越し先 GROWI にファイルがアップロードされている場合、それらの使用量を考慮したほうがいいかも？

2023-01-14 22:12 UTC, skomma commented on packages/app/src/server/service/import.js
> +      throw new Error('the version of this GROWI and the GROWI that exported the data are not met');
これも他と同じ表現に。

2023-01-14 22:12 UTC, skomma commented on packages/app/public/static/locales/zh_CN/admin.json
> +        "versions_not_met": "This GROWI and the uploaded data versions are not met",
あと、これ key が en_US とあってないよね？

2023-01-14 22:12 UTC, skomma commented on packages/app/src/server/routes/apiv3/import.js
>        return res.apiv3Err(new ErrorV3(msg, varidationErr), 500);
```suggestion
      const validationErr = 'versions-are-not-met';
      return res.apiv3Err(new ErrorV3(msg, varldationErr), 500);
```
`validationErr` の key って i18n の key ではないのか？
kebab-case と snake_case が混じってる。

2023-01-14 22:12 UTC, skomma commented on packages/app/src/server/routes/apiv3/import.js
> +      const msg = 'the version of this GROWI and the GROWI that exported the data are not met';
これも他と同じ表現に。

2023-01-15 12:44 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> +        reason: `Total file size exceeds file upload limit of dest GROWI. Requires ${totalFileSize.toLocaleString()} bytes, but got ${(destGROWIInfo.fileUploadTotalLimit ?? Infinity).toLocaleString()
defaultが`null`, `Infinity`なので`null`になることがあります。
https://github.com/weseek/growi/blob/f61b9e77e9c9374a2c30b89c780b047005892bd7/packages/app/src/server/service/config-loader.ts#L256-L261
https://github.com/weseek/growi/blob/f61b9e77e9c9374a2c30b89c780b047005892bd7/packages/app/src/server/service/config-loader.ts#L310-L318

型にも`null`が入っています。
https://github.com/weseek/growi/blob/f61b9e77e9c9374a2c30b89c780b047005892bd7/packages/app/src/server/service/g2g-transfer.ts#L59-L60

APIを経由すると`Infinity`が`null`に変わってしまうので`Infinity`に戻しています。
```ts
JSON.stringify(Infinity)
// 'null'
```

2023-01-15 12:44 UTC, mizozobu commented on packages/app/public/static/locales/zh_CN/admin.json
> +        "versions_not_met": "This GROWI and the uploaded data versions are not met",
合わせておきました

2023-01-15 12:50 UTC, mizozobu commented on packages/app/src/server/routes/apiv3/import.js
>        return res.apiv3Err(new ErrorV3(msg, varidationErr), 500);
これはフロント側でエラーコードで処理を変えたりするためのエラーコード的なやつだと思います。

2023-01-15 13:27 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> +    if ((destGROWIInfo.fileUploadTotalLimit ?? Infinity) < totalFileSize) {
チケット作りました
https://redmine.weseek.co.jp/issues/113223

2023-01-16 02:09 UTC, skomma commented on packages/app/src/server/service/g2g-transfer.ts
> +        reason: `Total file size exceeds file upload limit of dest GROWI. Requires ${totalFileSize.toLocaleString()} bytes, but got ${(destGROWIInfo.fileUploadTotalLimit ?? Infinity).toLocaleString()
うーん、if 文で以下のように書いているので、

```
if ((destGROWIInfo.fileUploadTotalLimit ?? Infinity) < totalFileSize) {
```

`fileUploadTotalLimit == null` のときは Infinity になって、この if 文の中には入らないような気がするんだが…？
メッセージに `but got Infinity bytes` って出るのおかしいよね？

```
reason: `The total file size of attachments exceeds the file upload limit of the destination GROWI. Requires ${totalFileSize.toLocaleString()} bytes, but got ${(destGROWIInfo.fileUploadTotalLimit ?? Infinity).toLocaleString()} bytes.`,
```

2023-01-16 12:04 UTC, mizozobu commented on packages/app/src/server/service/g2g-transfer.ts
> +        reason: `Total file size exceeds file upload limit of dest GROWI. Requires ${totalFileSize.toLocaleString()} bytes, but got ${(destGROWIInfo.fileUploadTotalLimit ?? Infinity).toLocaleString()
完全理解。`as number`しておきました。

2023-01-16 21:25 UTC, skomma approved these changes

2023-01-16 21:26 UTC, merged