Feat/110272 112702 show questionnaire UI
weseek/growi pull request #7251
Opened 2023-01-15 13:24 UTC by arafubeatbox

2023-01-17 07:28 UTC, hakumizuki commented
# デザインに関する意見
- 管理者用のアンケート設定へのリンクはアイコンがあるといいかなと思いました。モーダルが全体的に文字が多く、何か目印があった方が見やすいかなと思ったためです。
- 感謝モーダルは、新井さんも以前提案してくださったようにトースターが良さそうです。簡単にアンケートを終了してユーザーが他の操作をなるはやでできるようにした方が UX が良さそうだと思ったためです。

2023-01-17 14:19 UTC, arafubeatbox commented
対応しました。
![Jan-17-2023 23-18-45](https://user-images.githubusercontent.com/32846231/212922564-e54bf42e-3270-48b8-89e3-46e9d9aabfea.gif)

2023-01-18 05:18 UTC, hakumizuki requested changes

2023-01-18 05:18 UTC, hakumizuki commented on packages/app/src/stores/modal.tsx
> +  [key: string]: boolean,
2個以上のモーダルが同時に開くことはありえないと思うので、もし ID で管理する場合は、

```typescript
type QuestionnaireModalStatuses = {
  openQuestionnaireId: string | null
}
```

とかがいいかなと思います

2023-01-18 14:14 UTC, arafubeatbox commented on packages/app/src/stores/modal.tsx
> +  [key: string]: boolean,
確かにです！

2023-01-18 14:18 UTC, arafubeatbox commented on packages/app/src/components/PopUps.tsx
> +  const { data: questionnaireOrders } = useSWRxQuestionnaireOrders();
今後別の PopUp を表示したい場合に、全てここにまとめたら良いかな、と思って汎用的な名前にしたんですが、width とか場所とか色々変わってきそうなので、提案いただいた通りに QuestionnaireModalManager にまとめようかなと思います。

2023-01-18 14:31 UTC, merged