feat: Use configured xss custom whitelist
weseek/growi pull request #7252
Opened 2023-01-17 06:45 UTC by miya

## Task
[#107872](https://redmine.weseek.co.jp/issues/107872) [Next.js] XSS (Cross Site Scripting) 対策設定 が機能していない
└ [#109648](https://redmine.weseek.co.jp/issues/109648) 設定されたカスタムホワイトリストを使用できる

2023-01-19 09:24 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +    xssOption: configManager.getConfig('markdown', 'markdown:rehypeSanitize:option'),
Recommended or Custom が入るようにした

2023-01-19 09:24 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
> +    tagWhiteList: crowi.configManager.getConfig('markdown', 'markdown:rehypeSanitize:tagNames'),
カスタムホワイトリスト (tags, attributes) が入るようにした

2023-01-19 09:24 UTC, miya commented on packages/app/src/pages/[[...path]].page.tsx
>    props.sidebarConfig = {
pages/ 配下の差分は全て上記と同じ

2023-01-19 09:24 UTC, miya commented on packages/app/src/services/renderer/renderer.tsx
> +  }
config.xssOptions が RehypeSanitizeOption.CUSTOM だった場合、commonSanitizeOption.tagNames と commonSanitizeOption.attributes を上書きするようにしました。

commonSanitizeOption.attributes に関しては既存の設定を deepmerge したもので上書きするようになっています。

## 既存の設定
```javascript
attributes: {
  '*': ['class', 'className', 'style'],
},
```

2023-01-19 09:24 UTC, miya commented on packages/app/src/services/xss/xssOption.ts
> +  attrWhiteList: attrWhiteList,
type の修正

2023-01-19 09:24 UTC, miya commented on packages/app/src/services/xss/xssOption.ts
> +  xssOption: RehypeSanitizeOption,
新規追加

2023-01-20 10:08 UTC, yuki-takei requested changes

2023-01-21 06:46 UTC, miya commented on packages/app/src/services/renderer/renderer.tsx
> +  }
このコミットで共通化しました
https://github.com/weseek/growi/pull/7252/commits/b1d9221c8d06733763ec2f9484303d15e3f1cb7c

2023-01-21 09:13 UTC, merged