fix: Cannot login unless local strategy is enabled
weseek/growi pull request #7259
Opened 2023-01-18 04:18 UTC by miya

## Task
[#112939](https://redmine.weseek.co.jp/issues/112939) [要調査] LdapStrategy の挙動確認と修正
└ [#113387](https://redmine.weseek.co.jp/issues/113387) 修正

2023-01-18 04:39 UTC, miya commented on packages/app/src/server/routes/login-passport.js
> +      return next();
### バグの原因
LocalStrategy が有効になっていない時に早期に res.apiv3Err をしていたことで、loginPassport.loginWithLdap が呼ばれないことがバグの原因でした。IsEnableLoginWithLocalOrLdapMiddleware を挟むことでいずれかの認証方法が有効になっていることが保証されるので next() のみに修正しました。

2023-01-18 04:39 UTC, miya commented on packages/app/src/server/middlewares/is-enable-login-with-local-or-ldap.ts
> +};
LocalStrategy と LdapStrategy は同一のエンドポイント (POST: /login) を使っているため、どちらかのセットアップが有効になっているか確認するための express middleware を作成しました。

2023-01-18 06:47 UTC, miya commented on packages/app/src/server/routes/apiv3/index.js
> +    addActivity, isEnableLoginWithLocalOrLdapMiddleware, loginPassport.loginWithLocal, loginPassport.loginWithLdap, loginPassport.cannotLoginErrorHadnler, loginPassport.loginFailure);
こちら問題なければ Won't fix でお願いします

2023-01-19 12:01 UTC, yuki-takei requested changes

2023-01-19 12:01 UTC, yuki-takei commented on packages/app/src/server/middlewares/is-enable-login-with-local-or-ldap.ts
> +};
- login-passport.js に移す

2023-01-19 12:33 UTC, miya commented on packages/app/src/server/middlewares/is-enable-login-with-local-or-ldap.ts
> +};
移動させました

2023-01-19 12:36 UTC, miya commented on packages/app/src/server/routes/apiv3/index.js
> +    addActivity, loginPassport.isEnableLoginWithLocalOrLdap, loginPassport.loginWithLocal, loginPassport.loginWithLdap,
こちら問題なければ Won't fix でお願いします

2023-01-19 13:05 UTC, merged