support: add migration file
weseek/growi pull request #7266
Opened 2023-01-19 08:47 UTC by yukendev

2023-01-23 10:34 UTC, yuki-takei requested changes

2023-01-23 10:34 UTC, yuki-takei commented on packages/app/migration.sh
> +}
こういうことではないなあ


## 理想
```
replaceLatestRevisions(replacer: Replacer[]) {

   // replacer の数だけ body.replace する

}
```

## 利点
- グループ別に差し替えたい、スキップしたいがあるはず
    - グループ1: drawio, plantuml 等
    - グループ2: GROWI 独自 syntax の linker
    - 将来的に、ユーザーが入れられると一番強い

2023-01-23 10:36 UTC, yuki-takei requested changes

2023-01-23 10:36 UTC, yuki-takei commented on packages/app/migration.sh
> +  const drawioReplaced = body.replace(oldDrawioRegExp, '```drawio\n$1\n```');
細かいけど drawio の前にスペース一つ入れよう

2023-01-23 10:36 UTC, yuki-takei commented on packages/app/migration.sh
> +// 各ページの最新のrevisionを取得(最新revisionしか記法のマイグレーションをしない)
最終的には日本語禁止

2023-01-23 10:36 UTC, yuki-takei commented on packages/app/migration.sh
> +});
パフォーマンス的に NG。ページが10万とかあったらどうするのだ。

2023-01-25 07:35 UTC, yukendev commented on packages/app/migration.sh
> +  const drawioReplaced = body.replace(oldDrawioRegExp, '```drawio\n$1\n```');
修正済み

2023-01-25 07:37 UTC, yukendev commented on packages/app/migration.sh
> +// 各ページの最新のrevisionを取得(最新revisionしか記法のマイグレーションをしない)
修正済み

2023-01-25 08:04 UTC, yukendev commented on packages/app/migration.sh
> +}
修正済み

2023-01-25 11:24 UTC, yukendev commented on packages/app/migration.sh
> +});
100ページごと、最新のrevisionを置き換える形にしました

2023-01-25 18:42 UTC, merged