imprv: Override process for commonSanitizeOptions
weseek/growi pull request #7271
Opened 2023-01-23 04:07 UTC by miya

2023-01-25 02:40 UTC, miya commented on packages/app/src/services/renderer/renderer.tsx
> +  const commonSanitizeOption = generateCommonSanitizeOptions();
使う側で commonSanitizeOption を生成できるようにして、変数の影響範囲を使う側のメソッド内に閉じれるようにしました。

2023-01-25 11:59 UTC, yuki-takei requested changes

2023-01-25 11:59 UTC, yuki-takei commented on packages/app/src/services/renderer/renderer.tsx
> +  const commonSanitizeOption = generateCommonSanitizeOptions();
- generateViewOptions はページ遷移の都度呼ばれるし、遷移しなくても SWR の refetch で何度も呼ばれる可能性がある
- generateCommonOptions は pagePath が変わる頻度で実行しないとしょうがないが、generateCommonSanitizeOptions は都度実行する必要がない
- 結果的に generateCommonSanitizeOptions と injectCustomSanitizeOptions 両方で呼ばれる deepmerge の回数分、処理が無駄である

2023-01-26 04:57 UTC, miya commented on packages/app/src/services/renderer/renderer.tsx
> +  const commonSanitizeOption = generateCommonSanitizeOptions();
generateCommonSanitizeOptions  の実行結果を useSWRImmutable で持って generateCommonSanitizeOptions 自体の実行回数を 1回にしました

2023-01-26 05:00 UTC, miya commented on packages/app/src/stores/renderer.tsx
>  };
commonSanitizeOption が必要なメソッドに引数で渡す

2023-01-26 09:56 UTC, closed without merging