feat: 110277 113224 anwer or decline questionnaire
weseek/growi pull request #7277
Opened 2023-01-23 15:08 UTC by arafubeatbox

## review task
https://redmine.weseek.co.jp/issues/113741

## UI/UX (回答時の UX は前の PR で確認ずみ)
- スキップした時の tooltip
![skipped](https://user-images.githubusercontent.com/32846231/214080583-30c1b9e1-9422-4f2f-a397-96aac3bbac53.gif)
- 回答失敗
![failed](https://user-images.githubusercontent.com/32846231/214081008-cd8cf316-fd72-422f-91b0-f6db88945072.gif)

2023-01-23 15:18 UTC, arafubeatbox commented on packages/app/src/pages/[[...path]].page.tsx
> +    || configManager.getConfig('crowi', 'app:growiQuestionnaireServerOrigin');
dev 環境だと、

- server 側:  docker container 内部なので growi-questionnaire の url として localhost:3003 が使えず host.docker.internal:3003 を使う必要あり
- client 側: ブラウザからリクエストしているので host.docker.internal:3003 を認識せず localhost:3003 を使う必要あり

というもどかしい状況なのですが、自分の中では env.development で growiQuestionnaireServerOriginClientSide を定義し、それが存在する場合は client でそれを使う、という手法で落ち着いてしまいました。。

何かもっといい方法の提案がありましたらお願いします。

2023-01-23 15:18 UTC, arafubeatbox commented on packages/app/src/components/Questionnaire/QuestionnaireModal.tsx
> +  // TODO: モック化されている箇所を実装
https://redmine.weseek.co.jp/issues/113742 で実装予定です。

2023-01-25 05:14 UTC, hakumizuki requested changes

2023-01-25 05:14 UTC, hakumizuki commented on packages/app/src/interfaces/questionnaire/answer.ts
> +  question: Types.ObjectId | string
client side で使う時に mongoose があるとファイルサイズ増えちゃうので、/app/src/interface 配下では、mongoose をインポートしたくないです。以下のようにして、使う時に ObjectIdLike を渡してあげてください

```typescript
export interface IAnswer<ID = string> {
  question: ID
  value: string
}
```

2023-01-25 05:14 UTC, hakumizuki commented on packages/app/src/pages/[[...path]].page.tsx
> +    || configManager.getConfig('crowi', 'app:growiQuestionnaireServerOrigin');
プライベートなネットワーク空間とかだったらこういうことは dev 環境じゃなくてもあり得ると思うので、全然これで OK だと思います！

もし origin 同じにしたかったら ngrok 使うとかですかね

2023-01-25 05:14 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/questionnaire.ts
> +const router = express.Router();
Router を直でインポートしてください。ファイルサイズがちょっとちっちゃくなるはずです

2023-01-25 05:14 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/questionnaire.ts
> +  router.get('/questionnaire-orders', async(req: Request, res: ApiV3Response) => {
`/orders` の方が直感的で読みやすいかもですね。任せます

2023-01-25 05:14 UTC, hakumizuki commented on packages/app/src/server/routes/apiv3/questionnaire.ts
> +  });
認証用のミドルウェアを噛ませないと user 取れないです。loginRequired とかです。ただ guest user に見せるアンケートもあるのでそこもよしなにお願いします

2023-01-26 12:04 UTC, arafubeatbox commented on packages/app/src/components/Questionnaire/QuestionnaireModal.tsx
> +  }, [currentUser]);
ゲストユーザーを許可するとのことだったので、ゲストの場合は

1. type に 'guest' を追加し、UserInfo の type 以外は空にする
2. QuestionnaireAnswer の userInfo を optional にする

のどちらかだと思うのですが、どちらも growi-questionnaire 含めて型改修が必要です。
個人的には 1. が良いと思うのですが、それで改修しちゃって良いでしょうか？

2023-01-26 12:09 UTC, arafubeatbox commented on packages/app/src/components/Questionnaire/QuestionnaireModal.tsx
> +  const currentUserHasId = currentUser as IUserHasId;
対応しました。

server 側で、req.user で user 情報を取得できるので、今回の PR では IUserHasId 不要でしたが、結局 userIdHash 生成時に必要だと思うので、そのままにしておきます。
認識間違っていたら指摘してください。

2023-01-26 12:21 UTC, hakumizuki commented on packages/app/src/components/Questionnaire/QuestionnaireModal.tsx
> +  }, [currentUser]);
1 の型強め版の

```typescript
type IUserInfo = {
  userIdHash: string // userId hash generated by using appSiteUrl as salt
  type: UserType の 'guest' 以外
  userCreatedAt: Date // createdAt of user that answered the questionnaire
} & {
  type: 'guest'
}
```

も検討お願いします！
判断は任せます

2023-01-26 14:46 UTC, arafubeatbox commented
@hakumizuki どんでん返しでごめんなさいなのですが、server 側で growi-questionnaire に POST したほうが、必要な情報取得が server 側で全て完結するため、そっちでの実装に変更しました。

2023-01-26 17:26 UTC, arafubeatbox commented on packages/app/src/server/service/questionnaire-info.ts
> +      deploymentType: undefined, // TODO: set actual value
すみません、現在取得できないものの他に、wikiType と activeExternalAccountTypes の取得内容がわかりませんでした🙇‍♂️

2023-01-26 17:47 UTC, arafubeatbox commented on packages/app/src/server/service/questionnaire-info.ts
> +      attachmentType,
.env.development にある 'mongo' は GrowiAttachmentType の中にないため、それを変えないとエラーが起こるため開発時注意してください。

2023-01-26 17:47 UTC, arafubeatbox commented on packages/app/src/server/service/questionnaire-info.ts
> +    const attachmentType = this.crowi.configManager.getConfig('crowi', 'app:fileUploadType');
.env.development にある 'mongo' は GrowiAttachmentType の中になく、値を変えないとエラーが起こるため開発時注意してください。

2023-01-27 02:15 UTC, merged