feat: GROWI Questionnaire
weseek/growi pull request #7316
Opened 2023-01-30 10:27 UTC by hakumizuki

task: https://redmine.weseek.co.jp/issues/120949

2023-05-01 08:09 UTC, yuki-takei requested changes

2023-05-01 08:09 UTC, yuki-takei commented on apps/app/src/styles/theme/apply-colors.scss
> +}
features の下に定義して `@use` で入れられないかな

この辺参考に
https://lunalunadesign.net/2022/09/2895/

ちょっとやってみて時間がかかるようだったら諦めていい。

2023-05-01 08:09 UTC, yuki-takei commented on apps/app/src/stores/modal.tsx
> +};
これも features 下に移したい

2023-05-01 08:09 UTC, yuki-takei commented on apps/app/src/server/service/config-loader.ts
> +  },
すべて `QUESTIONNAIRE_` から始めてほしい

2023-05-01 08:09 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/personal-setting.js
> +  });
features の中に admin 用の routes ファイル作ってそこに移して `router.use` で読み込めないか

かえって複雑になりそうだったら見送ってよい

2023-05-01 08:09 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/app-settings.js
> +  });
features の中に routes ファイル作ってそこに移して router.use で読み込めないか

かえって複雑になりそうだったら見送ってよい

2023-05-08 05:50 UTC, jam411 commented on apps/app/src/components/Navbar/PersonalDropdown.jsx
> +import ProactiveQuestionnaireModal from '../../features/questionnaire/client/components/ProactiveQuestionnaireModal';
{ ssr: false } で修正しました。

2023-05-08 06:26 UTC, jam411 commented on apps/app/src/pages/[[...path]].page.tsx
> +import QuestionnaireModalManager from '~/features/questionnaire/client/components/QuestionnaireModalManager';
`{ ssr: false }` で修正しました。

2023-05-08 06:32 UTC, jam411 commented on apps/app/src/utils/sleep.ts
questioinnaire-cron.ts でのみ使用していたのでこのコンポーネント内で定義しました。

2023-05-08 08:07 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +};
移動しました。

2023-05-08 08:08 UTC, jam411 commented on apps/app/src/styles/theme/apply-colors.scss
> +}
別タスク: https://redmine.weseek.co.jp/issues/121722

2023-05-08 08:09 UTC, jam411 commented on apps/app/src/server/routes/apiv3/personal-setting.js
> +  });
別タスク: https://redmine.weseek.co.jp/issues/121723

2023-05-08 08:10 UTC, jam411 commented on apps/app/src/server/routes/apiv3/app-settings.js
> +  });
別タスク: https://redmine.weseek.co.jp/issues/121724

2023-05-08 09:02 UTC, merged