support: Migrate Notation for v5 to v6
weseek/growi pull request #7326
Opened 2023-01-31 11:16 UTC by yukendev

https://redmine.weseek.co.jp/issues/112440

2023-01-31 11:26 UTC, yukendev commented on bin/data-migrations/v6/migration.js
> +
```
docker run --network growi_devcontainer_default --rm -e MONGO_URI=mongodb://growi_devcontainer_mongo_1/growi -e MIGRATION_TYPE=v6 -e SLEEP_TIME=5 growi-migration
```

このようにしてdockerワンライナーを走らせるイメージです。
MIGRATION_TYPEは
- drawio
- plantuml
- tsv
- csv
- pagelint
- v6(上の記法全て)

の中からユーザーに入力してもらいます

2023-01-31 11:51 UTC, yuki-takei requested changes

2023-01-31 11:51 UTC, yuki-takei commented on bin/data-migrations/v6/migration.js
> +  case 'pagelink':
これの名前もうちょっと考えたいなあ

bracketlink とか、、他のでもいいけど

2023-01-31 11:51 UTC, yuki-takei commented on bin/data-migrations/v6/migration.js
> +    if (operations.length > 99) {
BATCH_SIZE も変数化

2023-01-31 11:51 UTC, yuki-takei commented on bin/data-migrations/v6/migration.js
> +var sleepTime = process.env.SLEEP_TIME ?? 5; // default 5 milliseconds
- SLEEP_TIME -> BATCH_INTERBAL に変更
- 単位を sec ではなく msec に
- 5秒は長いからデフォルト値は3秒にしよう

つまりデフォルト設定は `BATCH_INTERBAL=3000`

2023-01-31 11:51 UTC, yuki-takei commented on bin/data-migrations/v6/migration.js
> +  case 'drawio':
`v6-drawio`, `v6-plantuml`, ... にする

2023-01-31 11:51 UTC, yuki-takei commented on bin/data-migrations/v6/migration.js
> +}
require できるようなので、ここから上の部分は分割する

2023-01-31 11:53 UTC, yuki-takei commented on bin/data-migrations/v6/Dockerfile
> +COPY migration.js /opt/bin/
copy ではなく bind mount を使いたい
https://qiita.com/flu_bit/items/21b3d204d1581d100682#%E3%83%90%E3%82%A4%E3%83%B3%E3%83%89%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E3%82%92%E4%BD%BF%E3%81%86%E6%96%B9%E6%B3%95

2023-02-01 10:01 UTC, yukendev commented on bin/data-migrations/v6/migration.js
> +  case 'pagelink':
修正済み

2023-02-01 10:06 UTC, yukendev commented on bin/data-migrations/v6/migration.js
> +    if (operations.length > 99) {
修正済み

2023-02-01 10:07 UTC, yukendev commented on bin/data-migrations/v6/migration.js
> +var sleepTime = process.env.SLEEP_TIME ?? 5; // default 5 milliseconds
もともと単位はmilisecでデフォルトで5milisecのつもりでした。
修正済み

2023-02-01 10:09 UTC, yukendev commented on bin/data-migrations/v6/migration.js
> +  case 'drawio':
修正済み

2023-02-01 12:36 UTC, yukendev commented on bin/data-migrations/v6/Dockerfile
> +COPY migration.js /opt/bin/
```
docker run --rm \
--network growi_devcontainer_default \
-e MONGO_URI=mongodb://growi_devcontainer_mongo_1/growi \
-e MIGRATION_TYPE=v6 \
-v "$(pwd)"/src:/opt/bin \
growi-migration
```
バインドマウントを使用してファイルを参照するようにしました

2023-02-01 23:10 UTC, yuki-takei requested changes

2023-02-01 23:10 UTC, yuki-takei commented on bin/data-migrations/v6/Dockerfile
> +CMD /bin/mongosh ${MONGO_URI} migration.js
このイメージ中途半端なので必ず必要かというと微妙だなあ

カスタムイメージなしで docker run しようとするとどうなるかやってみてほしい

2023-02-01 23:10 UTC, yuki-takei commented on bin/data-migrations/v6/src/processor.js
> +// ===========================================
main process っていうコメントは変だね

2023-02-01 23:10 UTC, yuki-takei commented on bin/data-migrations/v6/src/processor.js
> +module.exports = oldFormatProcessors;
- メソッドを export しよう
    - migrationType を引数に取って、processors を返す
    - undefined や v6-* 以外の値が来たときは空の配列を返すような挙動でよい
- その代わり migration.js の方で有効な processor が一つもないというメッセージを出す

2023-02-02 05:30 UTC, yukendev commented on bin/data-migrations/v6/src/processor.js
> +// ===========================================
修正済み

2023-02-02 05:42 UTC, yukendev commented on bin/data-migrations/v6/src/processor.js
> +module.exports = oldFormatProcessors;
修正済み

2023-02-03 08:28 UTC, yukendev commented on bin/data-migrations/v6/Dockerfile
> +CMD /bin/mongosh ${MONGO_URI} migration.js
```
docker run --rm\
 --network growi_devcontainer_default\
 -w /opt/bin\
 -e MIGRATION_TYPE=v6\
 -v "$(pwd)"/src:/opt/bin mongo:6.0\
 /bin/mongosh mongodb://growi_devcontainer_mongo_1/growi migration.js
```

このようにカスタムイメージなしでも正常に動作しました

2023-02-03 08:57 UTC, merged