imprv: Disable lsx in shared page
weseek/growi pull request #7333
Opened 2023-02-01 09:20 UTC by miya

## Task
[#112947](https://redmine.weseek.co.jp/issues/112947) [v6] share link ページ で lsx を表示しないようにする
└ [#112948](https://redmine.weseek.co.jp/issues/112948) 改善

2023-02-01 09:23 UTC, miya commented on packages/remark-lsx/src/components/Lsx.tsx
> +  }
- share link ページだった場合は lsx を機能させないようにしました
- 以下の画像のように、shared page で lsx を利用したページを閲覧した場合は `lsx is not available on the share link page` という文言を表示するようにしました

<img width="302" alt="ScreenShot 2023-02-01 16 01 07" src="https://user-images.githubusercontent.com/34241526/216002314-3fd4d214-599d-4aed-81d1-24b19ecdc83f.png">

2023-02-01 09:23 UTC, miya commented on packages/remark-lsx/src/stores/lsx.tsx
> +    shouldFetch: boolean, pagePath: string, options?: Record<string, string | undefined>, isImmutable?: boolean,
shouldFetch: boolean という引数を新たに追加し、false だった場合は API リクエストさせないようにしました

2023-02-01 09:55 UTC, yuki-takei requested changes

2023-02-01 09:55 UTC, yuki-takei commented on packages/remark-lsx/src/components/Lsx.tsx
> +  }
text-warning と fa-exclamation-triangle だと異常状態っぽいので、
text-muted と何かもうちょっと穏やかなアイコンにしよう。

2023-02-01 09:55 UTC, yuki-takei commented on packages/remark-lsx/src/components/Lsx.tsx
> +  const isSharedPage = pagePathUtils.isSharedPage(pathname);
このコンポーネントは現時点では SSR していないとはいえ、window が入るとユニバーサルでなくなってしまう。

isSharedPage を判断する場所と、「lsx is not available on the share link page」を表示させるコードの実装場所の両方を再考しよう。

2023-02-02 04:10 UTC, miya commented on packages/app/src/services/renderer/renderer.tsx
> +    components.lsx = config.isLsxDisabled ? LsxDisable : Lsx;
app 側で出し分けるようにしました

2023-02-02 04:10 UTC, miya commented on packages/remark-lsx/src/components/Lsx.tsx
> +LsxDisable.displayName = 'LsxDisable';
新しいコンポーネントとして切り出しました

2023-02-02 04:11 UTC, miya commented on packages/remark-lsx/src/components/Lsx.tsx
> +  }
修正しました
<img width="209" alt="ScreenShot 2023-02-02 13 04 16" src="https://user-images.githubusercontent.com/34241526/216229683-30310c38-0eed-484e-95d1-6e93073c31e3.png">

2023-02-02 04:12 UTC, miya commented on packages/remark-lsx/src/components/Lsx.tsx
> +  const isSharedPage = pagePathUtils.isSharedPage(pathname);
isSharedPage かどうかの判断は app 側で行うように、「lsx is not available on the share link page」は新しいコンポーネントとして切り出して表示できるようにしました

2023-02-02 09:00 UTC, yuki-takei requested changes

2023-02-02 09:00 UTC, yuki-takei commented on packages/app/src/interfaces/services/renderer.ts
> +  isLsxDisabled?: boolean, // for shared page
せっかく remark-lsx という別パッケージにしてるのに、lsx にまつわる固有設定(のように見える変数)が本体にしみ出してくるのはよくない。変数名を `isSharedPage` に変えよう。

2023-02-02 09:00 UTC, yuki-takei commented on packages/app/src/services/renderer/renderer.tsx
> +    components.lsx = config.isLsxDisabled ? LsxDisable : Lsx;
コンポーネントを差し替えるのではなく、lsxGrowiPlugin.rehypePlugin へのオプションとして isSharedPage を渡そう。そして Lsx コンポーネント側で出し分ける。LsxDisabled の実装は OK。

2023-02-02 10:51 UTC, miya commented on packages/app/src/services/renderer/renderer.tsx
> +    components.lsx = config.isLsxDisabled ? LsxDisable : Lsx;
修正しました。
加えて、Basic 認証のことを考えて shared page の時は `/_api/lsx` にリクエストしないようにしました。

2023-02-02 23:16 UTC, yuki-takei requested changes

2023-02-02 23:16 UTC, yuki-takei commented on packages/remark-lsx/src/stores/lsx.tsx
> +    shouldFetch: boolean, pagePath: string, options?: Record<string, string | undefined>, isImmutable?: boolean,
この修正はいらない。

今までの Lsx 本体は LsxSubstance と改名する
新しい Lsx が isSharedPage を見て LsxSubstance と LsxDisabled を出し分ければそもそも useSWRxLsxResponse は宣言しなくて済む

2023-02-03 02:33 UTC, miya commented on packages/remark-lsx/src/stores/lsx.tsx
> +    shouldFetch: boolean, pagePath: string, options?: Record<string, string | undefined>, isImmutable?: boolean,
LsxSubstance を wrap する新しい Lsx を作成しました

2023-02-03 07:24 UTC, merged