feat: Detect i18n locale from browser accept languages
weseek/growi pull request #7341
Opened 2023-02-01 23:19 UTC by jam411

## 対象タスク
- [Next.js][v5との差異] ゲストユーザの表示言語がブラウザの設定言語に依存できる
task: https://redmine.weseek.co.jp/issues/114468

## 概要
[Next js のロケール検出](https://nextjs.org/docs/advanced-features/i18n-routing#automatic-locale-detection) もあったがルーティングの関係かすんなり使えなかったのと getNextI18NextConfig が用意されていたのでそこで accept-language から locale detect するようにしました。

2023-02-05 11:46 UTC, jam411 commented on packages/app/src/pages/utils/commons.ts
> +  if (browserLang?.includes('zh')) detectLocale = Lang.zh_CN;
- `fr-CH,ja;q=0.8,en-US;q=0.2` の場合は ja を表示できるように修正
- ` zh-TW ; q = 0.8 , en-US;q=0.9,en;q=0.90, ja,zh-CN,zh` のような場合も対処できるように修正

2023-02-09 11:50 UTC, yuki-takei requested changes

2023-02-09 11:50 UTC, yuki-takei commented on packages/app/src/pages/utils/commons.ts
> +  };
このメソッド自体を getNextI18NextConfig のメソッドの外に出す

2023-02-09 11:50 UTC, yuki-takei commented on packages/app/src/pages/utils/commons.ts
> +    return Lang.en_US;
for ブロックからここまでの「lang をインプットに Lang を得る」部分は key-value で対応する map としてこのメソッドの外に出す

2023-02-09 11:50 UTC, yuki-takei commented on packages/app/src/pages/utils/commons.ts
> +  const detectLocale = detectLocaleFromBrowserAcceptLanguage();
detectLocaleFromBrowserAcceptLanguage() を実行するのは、この後の三項演算子の `user == null` が確定してから

2023-02-13 05:45 UTC, merged