fix: Too many re-renders. React limits the number of renders to preve…
weseek/growi pull request #7343
Opened 2023-02-03 01:46 UTC by miya

## Task
[#114627](https://redmine.weseek.co.jp/issues/114627) [v6] 検索結果ページで閲覧権限が無いページをクリックすると 500 エラーが出る
└ [#114630](https://redmine.weseek.co.jp/issues/114630) 修正

2023-02-03 01:49 UTC, miya commented on packages/app/src/components/Page/RevisionLoader.tsx
> -  }
ここで `Too many re-renders. React limits the number of renders to prevent an infinite loop.` が出ていて 500 エラーになっていたので、useEffect に処理を閉じ込めた

2023-02-03 08:48 UTC, yuki-takei requested changes

2023-02-03 08:48 UTC, yuki-takei commented on packages/app/src/components/Page/RevisionLoader.tsx
> +  }, [errors, t]);
これは SWR 化しよう。useSWRMutation を使って、今 loadData が呼ばれるタイミングで trigger メソッドを叩く。

2023-02-04 14:06 UTC, miya commented on packages/app/src/components/Page/RevisionLoader.tsx
> +  }, [errors, t]);
修正しました

2023-02-05 16:48 UTC, yuki-takei requested changes

2023-02-05 16:48 UTC, yuki-takei commented on packages/app/src/components/Page/RevisionLoader.tsx
> +      const pageRevision = await mutatePageRevision();
useSWRxCurrentPage を参考に、読み出し用の useSWRxPageRevision を作ろう。
その方が SWR が提供する isLoading とかも使えるので、isLoading, isLoaded のステートが不要になって綺麗になる。

2023-02-05 16:48 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +
## リファクタ1
useSWRMutation は他の useSWRMutation とはキャッシュを共有しない(公式参照)。その仕様のおかげで現在のコードはたまたま上手く動いているが、用途的に revisionId ごとにキャッシュを分けたいのでキーには revisionId を含めたほうがいい。

## リファクタ2
その上で、任意の revisionId ごとにキャッシュを共用する useSWRxPageRevision (useSWR のラッパー)を作ることになるが、ハマりポイントがある。

useSWRxPageRevision 側で `['/revisions', revisionId, pageId]` のような配列をキーとし、また同様の配列を useSWRMUTxPageRevision でも作ってキーにした時に、違うオブジェクトなので同一のキーとみなしてくれない。
([公式参照](https://swr.vercel.app/ja/docs/arguments#%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E5%8F%97%E3%81%91%E6%B8%A1%E3%81%97))

同一キーとみなされないと、useSWRMUTxPageRevision の trigger を呼んでも useSWRxPageRevision の data は相変わらず undefined という挙動になってしまう。公式には「自動でシリアライズされる」とあるので shallow compare で同一視してくれてもよさそうなものだが、ここの詳細な挙動はまだ掴めていない。

なので、あまりかっこよくはないがワークアラウンドとして `/revisions/${revisionId}` という文字列をキーにするのはアリだと思う。これなら同一文字列のキーなのでキャッシュが共用される。

2023-02-05 16:48 UTC, yuki-takei commented on packages/app/src/components/Page/RevisionLoader.tsx
> +      }
useSWRxPageRevision を作れば setMarkdown は不要になる。

2023-02-09 04:43 UTC, miya commented on packages/app/src/components/Page/RevisionLoader.tsx
> +      }
swr から data も error も取ってこれるので setMarkdown を使わずに実装することはできそうですが、state を使った方が綺麗にかけると思ったので、setMarkdown だけは残しました

2023-02-09 11:55 UTC, yuki-takei requested changes

2023-02-09 11:55 UTC, yuki-takei commented on packages/app/src/stores/page.tsx
> +    return res.data.revision;
useSWRxPageRevision のキャッシュを考慮する実装って必要？

2023-02-11 23:07 UTC, miya commented on packages/app/src/stores/page.tsx
> +
props.lazy が無くなって任意のタイミングでリクエストする必要が無くなったので、useSWRImmutable から useSWRMutation に変更しました

2023-02-12 22:23 UTC, merged