fix: 114374 114406 disable to show password to admin when reset password
weseek/growi pull request #7356
Opened 2023-02-06 07:13 UTC by jam411

task: https://redmine.weseek.co.jp/issues/114406

2023-02-06 08:30 UTC, miya commented on packages/app/src/server/routes/apiv3/users.js
> +      return res.apiv3({ user });
user に password が含まれているのでシリアライズしてください

2023-02-06 08:30 UTC, miya commented on packages/app/src/components/Admin/Users/PasswordResetModal.jsx
> -        </p>
文言の修正をお願いします

<img width="440" alt="ScreenShot 2023-02-06 17 28 50" src="https://user-images.githubusercontent.com/34241526/216922127-89f4ef00-7d43-4055-9cf0-af2a0fd2cee6.png">

2023-02-13 07:50 UTC, jam411 commented on packages/app/src/server/routes/apiv3/users.js
> +      return res.apiv3({});
使われないと思ったので何も返さないようにしました。
時間があるとき申し訳ないですが動作確認お願いします

2023-02-13 07:51 UTC, jam411 commented on packages/app/src/components/Admin/Users/PasswordResetModal.jsx
> -        </p>
せっかくなので文言を修正してモーダルは一旦そのままにしています。

2023-02-15 06:04 UTC, yuki-takei requested changes

2023-02-15 06:04 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/users.js
> +      });
メール送信前後で try-catch を分けて

2023-02-15 23:34 UTC, jam411 commented on packages/app/src/server/routes/apiv3/users.js
> +      });
users.js `'/:id/recent'` を参考に修正しました.

2023-02-16 10:19 UTC, merged