Imprv/114143 114888 complete questionnaire i18n
weseek/growi pull request #7376
Opened 2023-02-10 13:55 UTC by arafubeatbox

2023-02-12 01:58 UTC, arafubeatbox commented on packages/app/src/components/Questionnaire/ProactiveQuestionnaireModal.tsx
> +              </div>
position、occupation の順番で表示されていて、日本語のラベルは 職種、役職 の順番だったので修正。
（position: 職種、occupation: 役職 という訳になっていたが、そもそもそれが間違っていて、position: 役職、occupation: 職種 が正しい)

2023-02-16 00:12 UTC, arafubeatbox commented on packages/app/public/static/locales/ja_JP/commons.json
> +
能動的アンケートは PersonalDropdown から呼び出されており、そこは `tranlslation` ns が有効でないページ（管理者設定画面など）からも表示できてしまうため、`commons` に移動しました。

2023-02-16 00:12 UTC, arafubeatbox commented on packages/app/public/static/locales/en_US/commons.json
> +  },
能動的アンケートは PersonalDropdown から呼び出されており、そこは `tranlslation` ns が有効でないページ（管理者設定画面など）からも表示できてしまうため、`commons` に移動しました。

2023-02-16 00:16 UTC, arafubeatbox commented on packages/app/public/static/locales/zh_CN/commons.json
> +    "close": "Close",
中国語の Close は translation.js で Close だったのでそのまま持ってきました。

2023-02-17 00:45 UTC, jam411 approved these changes

2023-02-17 00:47 UTC, jam411 requested changes
能動的アンケート 回答モーダルの送信ボタンが、
`回答する` `Answer` になってるけど、それを `送信`, `Submit` に変更してください。zh はよしなに
Google Form 参照
![image](https://user-images.githubusercontent.com/68407388/219520947-7a2914c4-42d3-4241-b9ae-82b6e74c71df.png)

2023-02-17 04:24 UTC, merged