[WIP] feat: Compare all page revisions on History tab
weseek/growi pull request #7414
Opened 2023-02-21 02:13 UTC by jam411

YouTrack: https://youtrack.weseek.co.jp/issue/GW-7918
- infinite scroll によってすべての revision を比較できるようになった
- ページリンクが動作するようになった. revision を指定し History tab が開いた状態で表示される.

2023-02-22 04:32 UTC, jam411 commented on packages/app/src/stores/page.tsx
> +      revalidateAll: false,
PageRevisionTable.tsx のみで使用している swr

2023-02-22 04:39 UTC, jam411 commented
- 大きな変更点は PageHistory.tsx 配下でのみの責務を負っている
 - `revisions/list` エンドポイント
 - useSWRxInfinitePageRevisions
 - PageHistory.tsx, PageRevisionTable.tsx, PageAccessoriesModal.tsx
- その他は format 修正と interface のみ

2023-02-24 09:10 UTC, yuki-takei requested changes

2023-02-24 09:10 UTC, yuki-takei commented on packages/app/src/components/PageHistory.tsx
> +      {currentPageId && currentPagePath && (
`!= null` をちゃんと書く

2023-02-24 09:10 UTC, yuki-takei commented on packages/app/src/components/PageAccessoriesModal.tsx
> +  };
この辺のメソッドは PageHistory に移す

2023-02-24 09:10 UTC, yuki-takei commented on packages/app/src/components/PageAccessoriesModal.tsx
> +      const [sourceRevisionId, targetRevisionId] = queryParams.split('...');
RegExp のグループで抽出できるはず

2023-02-28 01:13 UTC, merged