feat: Refactor template modal with hooks
weseek/growi pull request #7423
Opened 2023-02-22 07:24 UTC by yukendev

https://redmine.weseek.co.jp/issues/116350

# やったこと
- `CodeMirrorEditor`の中でレンダリングされていた、`TemplateModal`を`swr`を使用しグローバルなモーダルにした。
- `[[...path]].page.tsx`でレンダリングするようにした

2023-02-22 10:16 UTC, yuki-takei requested changes

2023-02-22 10:16 UTC, yuki-takei commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
>  import { TemplateModal } from '../TemplateModal';
import 行不要になるのでは？

2023-02-22 10:16 UTC, yuki-takei commented on packages/app/src/pages/[[...path]].page.tsx
> +import { TemplateModal } from '~/components/TemplateModal';
dynamic import して

2023-02-24 04:51 UTC, yukendev commented on packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
>  import { TemplateModal } from '../TemplateModal';
削除済み

2023-02-24 04:51 UTC, yukendev commented on packages/app/src/pages/[[...path]].page.tsx
> +import { TemplateModal } from '~/components/TemplateModal';
修正済み

2023-02-24 04:52 UTC, merged