fix: Error when trying to create a new page with attachments
weseek/growi pull request #7424
Opened 2023-02-22 08:33 UTC by miya

## Task
[#115878](https://redmine.weseek.co.jp/issues/115878) [v6] ページ新規作成時に画像を添付して保存しようとすると保存に失敗する
└ [#115996](https://redmine.weseek.co.jp/issues/115996) 修正

2023-02-24 04:28 UTC, yuki-takei requested changes

2023-02-24 04:28 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> +        { pageId: currentPage?._id, path: currentPagePath || currentPathname, revisionId: currentRevisionId },
いろいろ認識齟齬と誤解がある。

## 齟齬 1
まず #7473 のコメントの意図を宮沢くんが読み違えている。この時指摘したのは、useContextSWR をつかっているものの初期化(＝NextPage で引数に値を入れて呼び出す処理)のタイミングを変えないでと言っただけ。(この考え方は今後も有効)

## 齟齬 2
だがオレの方にも誤解があった。
今ソースを見たところ、useCurrentPageId は context.tsx 内にありながら useStaticSWR を使っていた。ということは、useEffect を使って mutate できる (useContextSWR はできない)。
これはオレが今まで勘違いをしたせいだが、context.tsx にあるのがよくないので page.tsx あたりに移動させるべき。

## 今後の方向性
これらを踏まえて、
useCurrentPageId が useStaticSWR を使っているなら context と違って mutate 可能なので、useEffect を使って書き換えて良い。ただ、今宮沢くんが考えているベストなコードをまだ見ていないので、それをレビューしてOKと言うかどうかは現時点ではわからない。

2023-02-28 02:23 UTC, miya commented on packages/app/src/stores/page.tsx
> +
- useCurrentPageId を /stores/page に移動
- useIsLatestRevision, useIsNotFound を /stores/page に移動, useStaticSWR 化

2023-03-02 06:18 UTC, yuki-takei requested changes

2023-03-02 06:18 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> +        await mutateCurrentPage();
useUpdateStateAfterSave に集積させてほしい。

2023-03-06 03:59 UTC, merged