imprv: Page body to markdown when uploading attachments
weseek/growi pull request #7432
Opened 2023-02-27 02:10 UTC by miya

## Task
[#116583](https://redmine.weseek.co.jp/issues/116583) [v6] 添付ファイルをアップロードしてページを新規作成する場合に保存されるページの page body を添付ファイルアップロード時点に入力していた markdown にする
└ [#116585](https://redmine.weseek.co.jp/issues/116585) 改善

2023-02-27 07:21 UTC, miya commented on packages/app/src/server/routes/attachment.js
> +      page = await crowi.pageService.create(pagePath, pageBody ?? '', req.user, { grant });
添付ファイルアップロード時点の markdown を保存できるようにした

2023-02-27 07:21 UTC, miya commented on packages/app/src/components/PageEditor.tsx
> +      }
- ファイルをアップロードしてページを作成する場合、作成された pageId に router.push するようにした

## 添付ファイルをアップロードしてページを作成する際の挙動の before / after 
### before 
page.body が一律で  `# {page.path}` という markdown で保存される

### after
ファイルをアップロードする前の markdown が pageBody に保存される

2023-03-02 06:09 UTC, yuki-takei requested changes

2023-03-02 06:09 UTC, yuki-takei commented on packages/app/src/components/PageEditor.tsx
> +      }
`if (pageId == null && markdownToSave.current != null) {` にした方がサーバー側の仕様と合う。

2023-03-02 06:18 UTC, miya commented on packages/app/src/components/PageEditor.tsx
> +      }
修正済み

2023-03-02 06:18 UTC, miya commented on packages/app/src/components/PageEditor.tsx
> +      }
修正済み

2023-03-02 06:19 UTC, merged