imprv: User home page deleteable if needed
weseek/growi pull request #7437
Opened 2023-02-28 10:16 UTC by jam411

task: https://redmine.weseek.co.jp/issues/114660

## 概要
- isUserPageDeletionEnabled: boolean によってユーザを削除したときに /user/{username} とその配下のページを削除できるようにした。
- isUserPageDeletionEnabled は管理画面のセキュリティ設定で操作できる。

## やったこと
- isUserPageDeletionEnabled のデフォルト値を false にした。
- サーバサイドでも isUserPageDeletionEnabled の config を扱えるようにした。
- ユーザ削除時のエンドポイントである remove にすでに removeByPath というメソッドが存在していた。しかし、動作していなかった。修正し。isUserPAgeDeletionEnabled の値に従ってエンドポイントで removeByPath を使えるようにした。
- removeByPath をリファクタリングし DB から子孫ページまで削除できるようにした。

2023-02-28 10:20 UTC, jam411 commented on packages/app/src/server/models/config.ts
> +  'security:isUserPageDeletionEnabled': false,
デフォルト値

2023-02-28 10:20 UTC, jam411 commented on packages/app/src/server/models/obsolete-page.js
>    };
正規表現で子孫ページも削除できるようにした。
もともとDBから削除していたからそのままだけど完全削除になる。

2023-03-01 01:26 UTC, miya commented on packages/app/src/client/services/AdminGeneralSecurityContainer.js
> +      isUserPageDeletionEnabled: this.state.isUserPageDeletionEnabled,
get してきた security:isUserPageDeletionEnabled を state に入れなくても大丈夫ですか？

2023-03-01 01:48 UTC, jam411 commented on packages/app/src/client/services/AdminGeneralSecurityContainer.js
> +      isUserPageDeletionEnabled: this.state.isUserPageDeletionEnabled,
https://github.com/weseek/growi/blob/f54f7188188d0f1dc4d04c8acacc3e67bd41b428/packages/app/src/client/services/AdminGeneralSecurityContainer.js#L65-L88

以前のPRでここまでやっていました。

2023-03-02 06:41 UTC, yuki-takei requested changes

2023-03-02 06:41 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/users.js
> +      if (isUserPageDeletionEnabled) await Page.removeByPath(userHomePagePath);
- removeByPath は models/obsolete-page.js から廃止し、models/page.ts に removeUserPages として再実装してください
- `const userHomePagePath = `/user/${userData.username}`;` 相当もそのメソッド内でやる
- isUserPageDeletionEnabled のチェックは現状通り route 側で OK

2023-03-05 09:39 UTC, jam411 commented on packages/app/src/server/routes/apiv3/users.js
> +      const userHomePagePath = `/user/${userData.username}`;
Page.removeByPaht() に userHomePagePath を渡すタイミングは `await userData.statusDelete();` の後になるので, userData.username を渡してしまうと path 名が `/user/deleted_at_*` になってしまします。なので、userData を remove する前にあらかじめ userHomePagePath としてコピーするようにしています。

2023-03-05 09:39 UTC, jam411 commented on packages/app/src/server/models/page.ts
> +
`server/models/page.ts` に移動しました.

2023-03-05 09:55 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/users.js
> +      const userHomePagePath = `/user/${userData.username}`;
removeByPath っていう汎用的なメソッドにする必要はなくないかな。`/user/${username}` の削除にしか使われてないんだからさ。

```
schema.statics.removeUserHome = async function(username: string) {
        const userHomePagePath = `/user/${username}`;
```
にしたらいいと思う。

2023-03-05 10:04 UTC, jam411 commented on packages/app/src/server/routes/apiv3/users.js
> +      const userHomePagePath = `/user/${userData.username}`;
removeUserHome は username を受け取って中で userHomePagePath を作るようにしました。

statusDelete にできてから 最後に HomePage を削除したほうがいいと思うので
`const username = userData.username;` のようにコピーしてから
`if (isUserPageDeletionEnabled) await Page.removeUserHome(username);` で渡しています

2023-03-05 11:13 UTC, merged