Imprv/114334 116948 add days since creation to user condition
weseek/growi pull request #7451
Opened 2023-03-03 06:32 UTC by arafubeatbox

## review task
https://redmine.weseek.co.jp/issues/116951

2023-03-03 06:33 UTC, arafubeatbox commented on packages/app/test/integration/service/questionnaire.test.ts
> +        },
ユーザに表示されないはずのアンケート

2023-03-05 07:14 UTC, jam411 requested changes

2023-03-05 07:14 UTC, jam411 commented on packages/app/src/server/util/questionnaire/condition.ts
> +    })();
変数名変更と早期リターンを利用して以下のようにしましょうか.

```
const isValidLeftThreshold = (() => {
    if (moreThanOrEqualTo == null) {
        return true;
    }

    const leftThreshold = new Date(createdAt.getTime() + 60 * 1000 * 60 * 24 * moreThanOrEqualTo);
    return leftThreshold <= currentDate;
})();
```

2023-03-05 07:14 UTC, jam411 commented on packages/app/src/server/util/questionnaire/condition.ts
> +    })();
こちらも修正お願いします.

2023-03-05 08:40 UTC, merged