Feat/114424 116536 track guest user questionnaire answer status with local storage
weseek/growi pull request #7453
Opened 2023-03-05 07:54 UTC by arafubeatbox

2023-03-05 08:16 UTC, arafubeatbox commented on packages/app/src/client/services/guest-questionnaire-answer-status.ts
> +const daysUntilExpiration = 30;
一旦一ヶ月にしてみました。

2023-03-06 03:36 UTC, jam411 requested changes

2023-03-06 03:36 UTC, jam411 commented on packages/app/src/client/services/guest-questionnaire-answer-status.ts
> +const daysUntilExpiration = 30;
了解です.
`DAYS_UNTIL_EXPIRATION`　のように upper case とアンダースコアに修正お願いします

2023-03-06 03:36 UTC, jam411 commented on packages/app/src/client/services/guest-questionnaire-answer-status.ts
> +};
この辺も早期リターンで書けそうなところは修正お願いします.

2023-03-06 03:36 UTC, jam411 commented on packages/app/src/components/Questionnaire/QuestionnaireModal.tsx
> +      if (!currentUser) {
こちらも比較演算子使うように修正お願いします.
以下同じ観点でお願いします.

2023-03-08 02:37 UTC, jam411 commented on packages/app/src/client/services/guest-questionnaire-answer-status.ts
> +};
if else 使わずに こんな感じでどうでしょうか

```
  if (storage != null) {
    storage[questionnaireOrderId] = guestQuestionnaireAnswerStatus;
    localStorage.setItem(storageKey, JSON.stringify(storage));
    return;
  }
  
  const initialStorage: GuestQuestionnaireAnswerStatusStorage = { [questionnaireOrderId]: guestQuestionnaireAnswerStatus };
  localStorage.setItem(storageKey, JSON.stringify(initialStorage));
```

2023-03-08 02:37 UTC, jam411 commented on packages/app/src/components/Questionnaire/QuestionnaireModalManager.tsx
> +    if (currentUser || !guestQuestionnaireAnswerStorage) {
ここも `currentUser != null || guestQuestionnaireAnswerStorage == null` でお願いします

2023-03-08 09:56 UTC, jam411 approved these changes

2023-03-08 09:56 UTC, merged