fix: Page paths in search results are not displayed correctly
weseek/growi pull request #7463
Opened 2023-03-08 11:10 UTC by miya

## Task
[#116390](https://redmine.weseek.co.jp/issues/116390) [GROWI] 検索結果のページパス一部が `/` と表示される
└ [#117351](https://redmine.weseek.co.jp/issues/117351) 修正

2023-03-08 11:21 UTC, miya commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +          fragment_size: 150,
検索結果の path の長さが fragment_size 以下だった場合省略されて返却されてしまうので値を増やしました

2023-03-10 08:52 UTC, yuki-takei requested changes

2023-03-10 08:52 UTC, yuki-takei commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +          fragment_size: 150,
クエリごとに可変にしましょう

2023-03-10 08:53 UTC, yuki-takei commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +          fragment_size: 150,
プログラム側で MAX 250 とか決めといて、それを越えたら highlight ごとなしにしてもいいかも。

2023-03-10 11:28 UTC, miya commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +          fragment_size: 150,
ページパスに上限がない以上、fragment_size を可変にするのはパフォーマンス的に良くない気がしたので上限を設けそれを超えたらハイライトしないように修正しました。

2023-03-10 12:23 UTC, yuki-takei requested changes

2023-03-10 12:23 UTC, yuki-takei commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +          fragment_size: DEFAULT_HIGHLIGHT_FRAGMENT_SIZE,
250 固定でもパフォーマンス悪くなると思うので可変にしてほしい。
parsedKeywords.match とか parsedKeywords.phrase に入ってる文字列の最長の長さになるんだと思う。

2023-03-15 13:09 UTC, miya commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +          number_of_fragments: 0,
- フラグメントは返さない
- pagePath フィールド全体をハイライト対象とする

2023-03-16 01:41 UTC, miya commented on packages/app/src/server/service/search-delegator/elasticsearch.ts
> +          fragment_size: DEFAULT_HIGHLIGHT_FRAGMENT_SIZE,
B 案で修正することに決定しました

2023-03-16 07:15 UTC, merged