fix: CodeBlock string is be `[object Object]` if searched
weseek/growi pull request #7484
Opened 2023-03-15 11:37 UTC by jam411

task: [117414](https://redmine.weseek.co.jp/issues/117414)

## 原因
- renderer.tsx で code タグを CodeBlock コンポーネントで置き換えている
- CodeBlock.tsx では children (ReactNode) を string にキャストしてから PrismAsyncLight コンポーネントで挟むことで codeblock 表示している
- 一方検索ワードに引っかかった文字列は highlight される仕様
- つまり対象のcodeが CodeBlock.tsx の children として渡ってくる時には `<span>` タグや `<em>` タグが付与されている
- HTML タグが付与されている children を string にキャストすると [Object Object]  と表示されていた

## 修正案 (TBD)

## Screenshot (TBD)

2023-03-15 22:21 UTC, jam411 commented on packages/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
> +            <code className={`language-${lang}`}>
"language-" クラスを渡してこうなるのを防ぐ
![image](https://user-images.githubusercontent.com/68407388/225455591-d7fe5b2d-0ac5-49e2-a529-2d1577f99785.png)

2023-03-15 22:21 UTC, jam411 commented on packages/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
> +}
参照:
![image](https://user-images.githubusercontent.com/68407388/225456521-cf099424-8f2a-43ba-9025-b7e2628e4d1c.png)

2023-03-16 07:12 UTC, yuki-takei requested changes

2023-03-16 07:12 UTC, yuki-takei commented on packages/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
> +}
これらの css を書きたくない。
`style={oneDark}` で解決できるのでは？

2023-03-16 07:12 UTC, yuki-takei commented on packages/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
> +            <code className={`language-${lang}`}>
`typeof children[0]` で exception 出そうなので null check とかをもう少ししっかりやる

2023-03-20 12:25 UTC, jam411 commented on packages/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
> +        </div>
このように直接指定するしか思い浮かばなかったです。
oneDark の構造は one-dark.js より以下
```
var _default = {
  "code[class*=\"language-\"]": {
    "background": "hsl(220, 13%, 18%)",
    "color": "hsl(220, 14%, 71%)",
    "textShadow": "0 1px rgba(0, 0, 0, 0.3)",
    "fontFamily": "\"Fira Code\", \"Fira Mono\", Menlo, Consolas, \"DejaVu Sans Mono\", monospace",
    "direction": "ltr",
    "textAlign": "left",
    "whiteSpace": "pre",
    "wordSpacing": "normal",
    "wordBreak": "normal",
    "lineHeight": "1.5",
    "MozTabSize": "2",
    "OTabSize": "2",
    "tabSize": "2",
    "WebkitHyphens": "none",
    "MozHyphens": "none",
    "msHyphens": "none",
    "hyphens": "none"
  },
  "pre[class*=\"language-\"]": {
    "background": "hsl(220, 13%, 18%)",
    "color": "hsl(220, 14%, 71%)",
    "textShadow": "0 1px rgba(0, 0, 0, 0.3)",
    "fontFamily": "\"Fira Code\", \"Fira Mono\", Menlo, Consolas, \"DejaVu Sans Mono\", monospace",
    "direction": "ltr",
    "textAlign": "left",
    "whiteSpace": "pre",
    "wordSpacing": "normal",
    "wordBreak": "normal",
    "lineHeight": "1.5",
    "MozTabSize": "2",
    "OTabSize": "2",
    "tabSize": "2",
    "WebkitHyphens": "none",
    "MozHyphens": "none",
    "msHyphens": "none",
    "hyphens": "none",
    "padding": "1em",
    "margin": "0.5em 0",
    "overflow": "auto",
    "borderRadius": "0.3em"
  },
  "code[class*=\"language-\"]::-moz-selection": {
    "background": "hsl(220, 13%, 28%)",
    "color": "inherit",
    "textShadow": "none"
  },
  ...
}
```

2023-03-20 12:25 UTC, jam411 commented on packages/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
> +  }, [children]);
長さを見るようにしました。null はわたってこないので見ていません。

2023-03-23 13:59 UTC, merged