fix: Templates are not applied when pages are created from PageTree
weseek/growi pull request #7553
Opened 2023-04-08 14:40 UTC by miya

## Task
[#119757](https://redmine.weseek.co.jp/issues/119757) [GROWI] テンプレートページが適用される階層にページツリーからページを作成した時にテンプレートが適用されない
└ [#119758](https://redmine.weseek.co.jp/issues/119758) 修正 & VRT 追加

2023-04-08 14:59 UTC, miya commented on packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
> +  });
- 同一階層テンプレートページをエディターモードでアクセスする VRT コードをアンコメント & リファクタ
- 加えて `Template for children` という revision.body でテンプレートページ (/Sandbox/__template) を作成するようにした

2023-04-08 14:59 UTC, miya commented on packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
> +  });
- 下位層テンプレートページをエディターモードでアクセスする VRT コードをアンコメント & リファクタ

2023-04-08 14:59 UTC, miya commented on packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
> +  });
- /Sandbox/__template が存在する階層に PageTree から新規にページ (/Sandbox/template-test-page) を作成してテンプレートが適用されるか確認するための VRT を作成

2023-04-08 14:59 UTC, miya commented on packages/app/src/server/routes/apiv3/pages.js
> +    }
- PageTree からページを新規作成する際にテンプレートページを考慮できるようにした
- ページに h1 header を付ける処理もまとめてサーバーサイドに移動

2023-04-10 05:26 UTC, yuki-takei requested changes

2023-04-10 05:26 UTC, yuki-takei commented on packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
> +  });
- _template のみが存在する場合
- __template のみが存在する場合
- 両方存在する場合

の3通りのテストがないといけないんだけど、そのようなテストには見えない

2023-04-10 05:30 UTC, yuki-takei requested changes

2023-04-10 05:30 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/pages.js
> +      body, grant, grantUserGroupId, overwriteScopesOfDescendants, isSlackEnabled, slackChannels, pageTags, createFromPageTree,
createFromPageTree というキー名がよくない

2023-04-10 05:30 UTC, yuki-takei commented on packages/app/src/server/routes/apiv3/pages.js
> +    let bodyCreatedFromPageTree = '';
変数名に FromPageTree という文字列が入るのはよくない

2023-04-10 07:10 UTC, miya commented on packages/app/src/server/routes/apiv3/pages.js
> +    let bodyCreatedFromPageTree = '';
修正済み

2023-04-10 07:10 UTC, miya commented on packages/app/src/server/routes/apiv3/pages.js
> +      body, grant, grantUserGroupId, overwriteScopesOfDescendants, isSlackEnabled, slackChannels, pageTags, createFromPageTree,
req.body が undefined だった場合に header と template の注入をするように修正

2023-04-10 07:11 UTC, miya commented on packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
> +  });
後続タスクで対応します

2023-04-10 07:43 UTC, yuki-takei approved these changes

2023-04-10 09:06 UTC, merged