fix: gw 7946 sticky event uncaught type error
weseek/growi pull request #7566
Opened 2023-04-12 10:08 UTC by mudana-grune

## Issue 
https://youtrack.weseek.co.jp/issue/GW-7946
- sticky-event Uncaught TypeError on open editor mode
- sticky-event Uncaught TypeError on some page transition

## Fix
- Create custom useSticky hook to observe sticky elements in use-sticky-utils
- Get isSticky status with useSticky hook
- Remove implementation of useSticky hook form react-use-sticky
- Remove isSticky state from Fab componnet
- Remove sticky-events and react-use-sticky library

2023-04-13 02:30 UTC, jam411 approved these changes

2023-04-13 02:30 UTC, jam411 commented on packages/app/src/components/Fab.tsx
>     */
@mudana-grune 
Please move this comment to right place or update or delete.

2023-04-13 02:30 UTC, jam411 commented on packages/app/src/components/Fab.tsx
> -    logger.debug('StickyEvents.CHANGE detected');
logger はいらないかな

2023-04-13 02:30 UTC, jam411 commented on packages/app/src/components/Fab.tsx
> +    }
```
The button will showing at first load, then disappear. So I set isStickyApplied to true if isSticky is true at the first time.
If isStickyApplied is false, the effect will not run, button not appear at first load
```

https://wsgrowi.slack.com/archives/C029KNKD1RS/p1681352128540049?thread_ts=1681174479.582449&cid=C029KNKD1RS

2023-04-14 04:27 UTC, yuki-takei requested changes

2023-04-14 04:27 UTC, yuki-takei commented on packages/app/src/stores/use-sticky.ts
src/client/side-effects に入れてください

2023-04-14 05:18 UTC, jam411 approved these changes

2023-04-14 05:38 UTC, merged