imprv: Add sanitize for registration white list
weseek/growi pull request #7567
Opened 2023-04-13 01:09 UTC by jam411

task: [116155](https://redmine.weseek.co.jp/issues/116155)

## Screenshot
- ホワイトリストは string[] 型で保持する
- 空文字は含めない
![image](https://user-images.githubusercontent.com/68407388/231619392-f96c5757-a13f-4719-a370-e91221e30afd.png)

### エラーの場合
![image](https://user-images.githubusercontent.com/68407388/231618832-b7da3d48-e45a-46af-ae92-9e507661c0a0.png)

2023-04-13 01:16 UTC, jam411 commented on packages/app/src/client/services/AdminLocalSecurityContainer.js
> +  }
相談なのですが, この修正方針でよいとなったとして，メソッド用に unit テスト書いてみたいと思っています。 
この場合, 例えばテストのためだけにメソッドをクラスの外に切り出すのはありでしょうか.

2023-04-14 04:23 UTC, yuki-takei requested changes

2023-04-14 04:23 UTC, yuki-takei commented on packages/app/src/client/services/AdminLocalSecurityContainer.js
> +  }
- この制約の根拠資料もコメントに載せといて
- core package のユーティリティにしたい

2023-04-14 04:23 UTC, yuki-takei commented on packages/app/src/client/services/AdminLocalSecurityContainer.js
> +          throw new Error('The input to the white list contains an invalid character. Please enter it in a format such as @growi.org.');
画面上で localize されたメッセージを出すべきだと思うが、この throw error でいいのかどうか…

クライアント側は isValidEmailDomain によるチェックだけで十分ではないかね？
サーバー側で sanitize して保存すべきだと思う。

2023-04-14 04:23 UTC, yuki-takei commented on packages/app/src/client/services/AdminLocalSecurityContainer.js
> +  }
ありだが、可読性優先
(別にクラスのメンバーメソッドでもテストはできると思うので)

2023-04-24 06:48 UTC, jam411 commented on packages/app/src/client/services/AdminLocalSecurityContainer.js
> +  }
[根拠資料](https://www.nic.ad.jp/ja/dom/system.html)をコメントに載せて、core package に追加しました。

2023-04-24 06:51 UTC, jam411 commented on packages/app/src/client/services/AdminLocalSecurityContainer.js
> +  }
今回は packages/core/test/util/email-domain-utils.test.js を作成しました。

2023-04-24 06:55 UTC, jam411 commented on packages/app/src/client/services/AdminLocalSecurityContainer.js
> +          throw new Error('The input to the white list contains an invalid character. Please enter it in a format such as @growi.org.');
/client/services/AdminLocalSecurityContainer.js では isValidEmailDomain() でのチェックのみにして、
/server/routes/apiv3/security-settings.js でサニタイズするようにしました。

2023-04-24 07:06 UTC, jam411 commented on packages/app/src/client/services/AdminLocalSecurityContainer.js
> +          throw new Error('The input to the white list contains an invalid character. Please enter it in a format such as @growi.org.');
> 画面上で localize されたメッセージを出すべきだと思うが、この throw error でいいのかどうか…
これに関しては後続タスクを作成しました。https://redmine.weseek.co.jp/issues/120936

2023-04-24 08:37 UTC, yuki-takei requested changes

2023-04-24 08:37 UTC, yuki-takei commented on apps/app/src/client/services/AdminLocalSecurityContainer.js
> +        }
- logger.warn でコンソールログにも出力
    - どんな line かわかるように
- エラーメッセージの localization

2023-04-25 02:14 UTC, jam411 commented on apps/app/src/client/services/AdminLocalSecurityContainer.js
> +        }
コンソールログに出力
![image](https://user-images.githubusercontent.com/68407388/234157139-cffe7bab-f8f7-4493-944f-c40fc544ce7b.png)

エラーメッセージの localization. 英語はそのまま表示されるので admin.json に追加は不要.
![image](https://user-images.githubusercontent.com/68407388/234157104-337d7dd0-7215-4504-843e-d0b342759738.png)

2023-04-25 02:14 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-setting.js
> +        });
そのまま保存するように修正しました。

2023-04-26 07:34 UTC, yuki-takei requested changes

2023-08-03 02:21 UTC, jam411 commented
https://github.com/weseek/growi/pull/7945 引っ越しのためクローズ

2023-08-03 02:21 UTC, closed without merging