imprv: Can use registration approval request without mail settings
weseek/growi pull request #7581
Opened 2023-04-18 05:29 UTC by jam411

task:https://redmine.weseek.co.jp/issues/120045

# Screenshot
## 01
### Before
![image](https://user-images.githubusercontent.com/68407388/232679503-07217226-2966-4a6d-9065-671e57e8ef8b.png)
### After
![image](https://user-images.githubusercontent.com/68407388/232679473-b0e88ccc-6d4e-4154-984b-8f7f80d7cd9e.png)

## 02
### Before
### After

2023-04-19 04:18 UTC, jam411 commented on apps/app/src/server/routes/login.js
> +      }
- 新規登録ユーザが作られていたら通知を送る.
- もしメールがセットアップされていれば admin ユーザ宛にメールも送信する.

2023-04-19 10:26 UTC, jam411 commented on apps/app/src/components/InAppNotification/InAppNotificationElm.tsx
> +        {notification.targetModel === 'User' && (
`notification.targetModel === 'Page'` こちらも 
`notification.targetModel === SupportedTargetModel.MODEL_PAGE ` に修正しました

2023-04-19 10:26 UTC, jam411 commented on apps/app/src/stores/in-app-notification.ts
> +            case 'User':
下のように修正しました。
```
switch (doc.targetModel) {
  case SupportedTargetModel.MODEL_PAGE:
    doc.parsedSnapshot = pageSerializers.parseSnapshot(doc.snapshot);
    break;
  case SupportedTargetModel.MODEL_USER:
    doc.parsedSnapshot = userSerializers.parseSnapshot(doc.snapshot);
    break;
  default:
    throw new Error(`No serializer found for targetModel: ${doc.targetModel}`);
}
```

2023-04-19 16:18 UTC, yuki-takei requested changes

2023-04-19 16:18 UTC, yuki-takei commented on apps/app/src/components/InAppNotification/PageNotification/UserModelNotification.tsx
このコンポーネント、PageModelNotification と重複が多すぎて冗長。
120632 のスコープに共通化も入れてください。

## 共通化する際のヒント
- PageModelNotification と UserModelNotification で共通でレンダリングする部分は HoC にすればよさそう
- InAppNotificationElm もあわせてリファクタすべき
    - page に閉じるべきものは PageModelNotification に移す

2023-04-19 16:18 UTC, yuki-takei commented on apps/app/src/server/service/in-app-notification.ts
> +    this.activityEvent.on('updated', async(activity: ActivityDocument, target: any, users?: Ref<IUser>[]) => {
変数名を descendantsSubscribedUsers から users にするメリットある？

2023-04-19 16:18 UTC, yuki-takei commented on apps/app/src/server/service/in-app-notification.ts
> +    }
この場合分け嫌なので 120632 のスコープにリファクタを入れてください

2023-04-19 16:18 UTC, yuki-takei commented on apps/app/src/stores/in-app-notification.ts
> +          }
この場合分け嫌なので 120632 のスコープにリファクタを入れてください

2023-04-20 00:03 UTC, jam411 commented on apps/app/src/server/service/in-app-notification.ts
> +    this.activityEvent.on('updated', async(activity: ActivityDocument, target: any, users?: Ref<IUser>[]) => {
sendNotificationToAllAdmins() で adminUsers を渡すようにしたので汎用的な users にしました。

2023-04-20 00:17 UTC, jam411 commented on apps/app/src/server/service/in-app-notification.ts
> +    }
スコープに入れました

2023-04-20 00:17 UTC, jam411 commented on apps/app/src/stores/in-app-notification.ts
> +          }
スコープに入れました

2023-04-20 00:17 UTC, jam411 commented on apps/app/src/components/InAppNotification/PageNotification/UserModelNotification.tsx
スコープに入れました

2023-04-20 08:52 UTC, merged