feat: Update bookmarks tree move to root features
weseek/growi pull request #7586
Opened 2023-04-20 08:41 UTC by jam411

task: https://redmine.weseek.co.jp/issues/119721

### Outline
- DnD の「ルートに配置する」をコメントアウト
- 三連ボタンから「ルートに配置する」を選択できるように修正

### Screenshot
![image](https://user-images.githubusercontent.com/68407388/233310455-4dfd5b94-6d1f-453f-bda1-a379ef89c0c6.png)

![image](https://user-images.githubusercontent.com/68407388/233310348-7b220c1f-1d71-46db-8207-bbcb603de696.png)

2023-04-20 08:42 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkFolderItemControl.tsx
> +        style={{ zIndex: 1055 }} /* make it larger than $zindex-modal of bootstrap */
page tree に合わせる

2023-04-20 08:42 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
> +  // };
復活するかもしれないのでコメントアウトしておく

2023-04-20 08:47 UTC, jam411 commented on apps/app/src/components/UsersHomePageFooter.module.scss
> +@use '@growi/ui/src/styles/molecules/page_list';
conflict 解消

2023-04-20 10:21 UTC, yuki-takei requested changes

2023-04-20 10:21 UTC, yuki-takei commented on apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
> +  const { mutate: mutateBookmarkData } = useSWRxBookmarkFolderAndChild();
改めて見ると swr hooks への依存が多すぎるな。
`useSWRxSomething;` 系くらいは親からの props で入れたい。(後続タスクで可)

2023-04-20 10:21 UTC, yuki-takei commented on apps/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx
> +  const { mutate: mutateBookmarkData } = useSWRxBookmarkFolderAndChild();
BookmarkFolderItem.tsx の FB に同じ。
`useSWRxSomething` 系で取れるデータ、トリガーしたいイベントハンドラくらいは親の props から渡したい。

2023-04-20 10:21 UTC, yuki-takei commented on apps/app/src/components/Common/Dropdown/PageItemControl.tsx
> +  const { data: userBookmarks, mutate: mutateUserBookmarks } = useSWRxCurrentUserBookmarks();
これもここには置きたくないね
そもそも、`additionalMenuItemOnTopRenderer` を使うべき。

2023-04-20 10:21 UTC, yuki-takei commented on apps/app/src/components/DescendantsPageListModal.tsx
> +          return <DescendantsPageList path={status.path} forceHideMenuItems={[MenuItemType.BOOKMARKS_TREE_MOVE_TO_ROOT]}/>;
そっちではなく `additionalMenuItemOnTopRenderer` で必要な場合に足す。

2023-04-20 10:21 UTC, yuki-takei commented on apps/app/src/components/UsersHomePageFooter.tsx
> +  const { mutate: mutateChildBookmarkData } = useSWRxBookmarkFolderAndChild();
このコンポーネントから bookmark folder 作れなくていい気がする。
それか、BookmarkFolderTree に委譲したい。

2023-04-27 09:02 UTC, jam411 commented on apps/app/src/components/DescendantsPageListModal.tsx
> +          return <DescendantsPageList path={status.path} forceHideMenuItems={[MenuItemType.BOOKMARKS_TREE_MOVE_TO_ROOT]}/>;
additionalMenuItemOnTopRenderer を使うように修正しました。

2023-04-27 09:05 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
> +  const { mutate: mutateBookmarkData } = useSWRxBookmarkFolderAndChild();
この PR で props で渡すように修正しました。

2023-04-27 09:05 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx
> +  const { mutate: mutateBookmarkData } = useSWRxBookmarkFolderAndChild();
この PR で props で渡すように修正しました。

2023-04-27 09:06 UTC, jam411 commented on apps/app/src/components/UsersHomePageFooter.tsx
> +  const { mutate: mutateChildBookmarkData } = useSWRxBookmarkFolderAndChild();
後続タスクで着手します
https://redmine.weseek.co.jp/issues/121191

2023-04-27 09:07 UTC, jam411 commented
BookmarkFolderMenu 周りは https://redmine.weseek.co.jp/issues/119728 でリファクタリングします。

2023-04-27 10:00 UTC, yuki-takei requested changes

2023-04-27 10:03 UTC, jam411 commented on apps/app/src/components/Sidebar/PageTree/Item.tsx
> +import { MenuItemType, PageItemControl } from '../../Common/Dropdown/PageItemControl';
消し忘れだったので削除しました。

2023-04-28 02:20 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx
> +import type { KeyedMutator } from 'swr';
`import type { KeyedMutator } from 'swr';` はインポートしないようにしました。

BookmarkFolderTree.tsx, BookmarkFolderItem.tsx, BookmarkItem.tsx は bookmark に関連する mutate 関数をまとめて bookmarkFolderTreeMutation として渡すようにしてしまいました。
余分に呼ぶ可能性もありますが許容範囲かと考えました。

```
  const bookmarkFolderTreeMutation = useCallback(() => {
    mutateUserBookmarks();
    mutateBookmarkInfo();
    mutateBookmarkFolders();
  }, [mutateBookmarkFolders, mutateBookmarkInfo, mutateUserBookmarks]);
```

useEffect で  mutateBookmarkFolders(); を呼び出していた箇所を削除することができました。

2023-04-28 02:22 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkItem.tsx
> -  }, [mutateBookamrkData]);
bookmarkFolderTreeMutation() することで不要

2023-04-28 02:22 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx
> +}) => {
修正しました。

2023-04-28 07:04 UTC, yuki-takei requested changes

2023-04-28 07:04 UTC, yuki-takei commented on apps/app/src/components/Bookmarks/BookmarkFolderItemControl.tsx
> +  isMoveToRoot,
`onClickMoveToRoot` がセットされているかどうかで代用できるのでは？
代用できないのだとしたら変数名を `canMoveToRoot` に変更する

2023-04-28 11:55 UTC, merged