fix: Reverted descendant pages do not appear in search results
weseek/growi pull request #7587
Opened 2023-04-20 08:47 UTC by miya

## Task
[#120476](https://redmine.weseek.co.jp/issues/120476) ゴミ箱に出し入れした際の全文検索のバグを修正する
└ [#120723](https://redmine.weseek.co.jp/issues/120723) 修正 (問題2)

2023-04-20 10:46 UTC, yuki-takei requested changes

2023-04-20 10:46 UTC, yuki-takei commented on apps/app/src/server/service/page.ts
> +    this.pageEvent.emit('create', updatedPage, user);
これはおかしい

revert event 発火時の処理を見直すべきなのでは？

2023-04-20 10:46 UTC, yuki-takei commented on apps/app/src/server/service/page.ts
> +          this.pageEvent.emit('syncDescendantsUpdate', updatedPage, user);
try の中に入れたいな

2023-04-21 01:41 UTC, miya commented on apps/app/src/server/service/page.ts
> +          this.pageEvent.emit('syncDescendantsUpdate', updatedPage, user);
修正済み

2023-04-21 01:41 UTC, miya commented on apps/app/src/server/service/page.ts
> +    this.pageEvent.emit('create', updatedPage, user);
revert event の中で es に対して必要な処理を行うように修正しました

2023-04-21 03:05 UTC, miya commented
r

2023-04-21 11:29 UTC, merged