feat: Maximum folder hierarchy of 2 levels
weseek/growi pull request #7594
Opened 2023-04-21 09:43 UTC by jam411

task: https://redmine.weseek.co.jp/issues/119724

2023-04-21 11:49 UTC, yuki-takei requested changes

2023-04-21 11:49 UTC, yuki-takei commented on apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
> +      // Maximum folder hierarchy of 2 levels
このコメントだと why? がよくわからないなあ

2023-04-21 11:49 UTC, yuki-takei commented on apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
> +            {/* Maximum folder hierarchy of 2 levels */}
これは理解

2023-04-21 11:49 UTC, yuki-takei commented on apps/app/src/server/models/bookmark-folder.ts
> +        const parentFolder = await this.model('BookmarkFolder').findById(parent);
validate 内で DB fetch が発生するのはあまりよくないかもなあ。
こういう処理をするなら route の middleware でガードすべきかな。

2023-04-26 04:25 UTC, yuki-takei requested changes

2023-04-26 04:25 UTC, yuki-takei commented on apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
> +      // Maximum folder hierarchy of 2 levels
- コメント間違ってるので直してください
- 詳しく書いてください(children が 0 じゃないということは...みたいなことも)

2023-04-26 04:25 UTC, yuki-takei commented on apps/app/src/server/models/bookmark-folder.ts
> +  // Check source folder has no chidren or dest folder has no parent
コメントの見直しを

2023-04-27 01:56 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
> +      // Maximum folder hierarchy of 2 levels
修正しました。

2023-04-27 01:56 UTC, jam411 commented on apps/app/src/server/models/bookmark-folder.ts
> +  // Check source folder has no chidren or dest folder has no parent
修正しました。

2023-04-27 01:56 UTC, merged