Feat/112904 120355 enable attachment refs
weseek/growi pull request #7597
Opened 2023-04-22 03:15 UTC by arafubeatbox

2023-04-23 16:09 UTC, arafubeatbox commented on packages/remark-attachment-refs/src/client/components/ExtractedAttachments.tsx
> +// TODO: implement image carousel modal without using react-images
react-images が今は開発されておらず、今の環境だと動かなくなってしまいました。
react-images の README では
https://www.npmjs.com/package/react-responsive-carousel
がお勧めされていましたが、react-images と異なり modal ではないので少し追加実装が必要そうなのと、これもメンテナンスされていないので、自前実装の方が確実かもしれません。

そもそも carousel が必要かどうかの検討も必要かもですが、carousel の実装は、別ストーリーに切り出した方が良いと思っています。

2023-04-24 03:37 UTC, jam411 approved these changes

2023-04-24 15:16 UTC, yuki-takei requested changes

2023-04-24 15:16 UTC, yuki-takei commented on packages/remark-attachment-refs/src/client/components/ExtractedAttachments.tsx
> +// TODO: implement image carousel modal without using react-images
この PR からはスコープは外して別ストーリーでよいです。

イメージを小さく表示すると carousel ほしいなあって思うはず…

2023-04-24 15:16 UTC, yuki-takei commented on packages/remark-attachment-refs/src/client/services/renderer/refs.ts
> +import { visit } from 'unist-util-visit';
この辺のパッケージも vite の externals に入れるべきかな

2023-04-24 15:16 UTC, yuki-takei commented on turbo.json
> +      "dependsOn": ["^dev"]
dependsOn は最低限に

2023-04-25 15:03 UTC, arafubeatbox commented on packages/remark-attachment-refs/src/client/components/ExtractedAttachments.tsx
> +// TODO: implement image carousel modal without using react-images
了解です。
https://redmine.weseek.co.jp/issues/121095
ストーリー作成し、README の carousel の説明部分をコメントアウトしました。

2023-04-26 09:38 UTC, yuki-takei approved these changes

2023-04-26 09:38 UTC, merged