imprv: show alert when comment not posted
weseek/growi pull request #7603
Opened 2023-04-24 12:37 UTC by arafubeatbox

## review task
https://redmine.weseek.co.jp/issues/121003

## 動作イメージ
コメント編集中も同様
![Apr-24-2023 21-29-43](https://user-images.githubusercontent.com/32846231/233996712-59dcdf87-e1cf-4cd5-aa5f-18e9e963152c.gif)

2023-04-25 01:39 UTC, jam411 requested changes

2023-04-25 01:39 UTC, jam411 commented on apps/app/src/components/PageComment/CommentEditor.tsx
> +  }, [mutateIsEnabledUnsavedWarning]);
- post しても引き続き browser warning がでます。ご確認お願いします。
comment post 後に渡る値を見てみると newValue は <empty string> ですが, isClean は false でわたってくるようです。

- Reply と Add Comment の CommentEditor が同時に呼ばれる場合があるのでどちらかに not posted な値があるときは browser warning を出すようにしてください。（両方に入力してから片方 post したら warning されない気がする。）

2023-04-25 14:16 UTC, arafubeatbox commented on apps/app/src/components/PageComment/CommentEditor.tsx
> +  }, [mutateIsEnabledUnsavedWarning]);
対応しました。

2023-04-27 00:40 UTC, jam411 requested changes

2023-04-27 00:40 UTC, jam411 commented on apps/app/src/components/PageComment/CommentEditor.tsx
> +  }, [initializeSlackEnabled, mutateIsEnabledUnsavedWarning, decrementEditingCommentsNum]);
cancelButtonClickedHandler() でも initializeEditor() 呼ぶようにしてください。
（なぜこれまで呼ばれてなかったんだろう。呼んでもいいはず。デグレがないか確認していただけるとありがたいです。）

2023-04-28 06:58 UTC, yuki-takei requested changes

2023-04-28 06:58 UTC, yuki-takei commented on apps/app/src/stores/comment.tsx
> +    increment: () => swrResponse.mutate(swrResponse.data ? swrResponse.data + 1 : 1),
細かいけど、

コーディングガイド的には三項演算子の条件に使うなら `!= null` と明示したい。
完結に書くなら `(swrResponse.data ?? 0) + 1` でよさそう。

2023-04-28 06:58 UTC, yuki-takei commented on apps/app/src/stores/comment.tsx
> +      return swrResponse.mutate(0);
こちらも完結に、
```
const newValue = (swrResponse.data ?? 0) - 1);
mutate(Math.max(0, newValue))`;
```

2023-04-28 11:25 UTC, merged