feat: Create useIsReadOnlyUser hooks
weseek/growi pull request #7612
Opened 2023-04-30 05:44 UTC by jam411

task: 
- useIsReadOnly hooks を作成できる
https://redmine.weseek.co.jp/issues/121329

後続タスク:
- NotAvailableForGuest コンポーネントを一般化し、isUserReadOnlyの場合でも使用できる
- useIsGuestUser を参考に必要な個所に isReadOnlyUser 条件を追加する

2023-04-30 05:49 UTC, jam411 commented on apps/app/src/stores/context.tsx
> +  const isReadOnlyUser = !isGuestUser && !!currentUser?.readOnly;
```
const isReadOnlyUser = !(currentUser?._id == null) && !!currentUser?.readOnly;
```

のようにすると useIsGuestUser(); は呼び出さなくてもよいが可読性と hooks から取得するほうがデータが一貫すると考えたのでこのようにしてみました。

2023-04-30 05:49 UTC, jam411 commented on apps/app/src/stores/context.tsx
> +
useIsReadOnlyUser は useIsGuestUser と統合することも考えましたがnavbar 右上の Login ボタン or Home ボタン表示など guest user と rom user で切り分けたい場合があるので、新しく useIsReadOnlyUser フックを作成することにしました。

2023-05-01 09:36 UTC, yuki-takei requested changes

2023-05-01 09:36 UTC, yuki-takei commented on apps/app/src/stores/context.tsx
> +    isLoading ? null : ['isReadOnlyUser', isReadOnlyUser],
キーに `currentUser?._id` は入れないといけない

2023-05-08 06:18 UTC, merged