feat: Add activityEvent for ReadOnly user access actions
weseek/growi pull request #7615
Opened 2023-04-30 06:26 UTC by jam411

task: https://redmine.weseek.co.jp/issues/121247

## Screenshot
![image](https://user-images.githubusercontent.com/68407388/235338677-ff7f460c-d52c-483a-9b6a-2da552ab9742.png)

![image](https://user-images.githubusercontent.com/68407388/235338848-9646a01d-5007-4152-b344-0bfbb26057ad.png)

2023-05-01 09:41 UTC, yuki-takei requested changes

2023-05-01 09:41 UTC, yuki-takei commented on apps/app/public/static/locales/en_US/admin.json
> +    "ADMIN_USERS_REMOVE_READ_ONLY": "Remove read only access",
今更って感じは否めないが、give/remove って変な感じがする。。
再考をお願いしたい。API エンドポイントもそうなってると思うので、最終的には変えたい。後続タスクでOK。

2023-05-01 09:41 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/admin.json
> +    "ADMIN_USERS_REMOVE_READ_ONLY": "閲覧ユーザーから外す",
「閲覧ユーザー」ではない表現にしたい
https://www.google.com/search?q=read+only+user+%E9%96%B2%E8%A6%A7%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC

2023-05-08 10:30 UTC, jam411 commented on apps/app/public/static/locales/en_US/admin.json
> +    "ADMIN_USERS_REMOVE_READ_ONLY": "Remove read only access",
後続タスク: https://redmine.weseek.co.jp/issues/121730

2023-05-08 10:30 UTC, jam411 commented on apps/app/public/static/locales/ja_JP/admin.json
> +    "ADMIN_USERS_REMOVE_READ_ONLY": "閲覧ユーザーから外す",
英語「Read Only」日本語「閲覧のみ」にしてフラグとしました。
https://wsgrowi.slack.com/archives/C0111HG81GB/p1683537245035329

2023-05-08 11:00 UTC, merged