feat: Elasticsearchv8 module
weseek/growi pull request #7623
Opened 2023-05-02 12:02 UTC by miya

## Task
[#120343](https://redmine.weseek.co.jp/issues/120343) [GROWI]  ElasticSearch v8 アップグレード
└ [#120705](https://redmine.weseek.co.jp/issues/120705) es8 用のモジュール実装

2023-05-09 12:32 UTC, yuki-takei requested changes

2023-05-09 12:32 UTC, yuki-takei commented on apps/app/src/server/service/search-delegator/elasticsearch.ts
> +    this.elasticsearch = this.isElasticsearchV7 ? elasticsearch7 : elasticsearch8;
isElasticsearchV7 による三項演算子がこのファイル内に増えすぎているのを改善したい。
元々の利用回数を許容できる最低値として、同数かそれ以下に減らしたい(elasticsearch-client のように差異を吸収するモジュールを用意してカプセル化するなどして)

2023-05-10 08:42 UTC, miya commented on apps/app/src/server/service/search-delegator/elasticsearch.ts
> +    this.elasticsearch = this.isElasticsearchV7 ? elasticsearch7 : elasticsearch8;
レスポンス結果の差異を elasticsearch-client 側で吸収する用に修正しました

2023-05-10 08:48 UTC, yuki-takei approved these changes

2023-05-10 08:57 UTC, merged