feat: Add isReadOnlyUser condition to client side
weseek/growi pull request #7631
Opened 2023-05-09 07:09 UTC by jam411

task:https://redmine.weseek.co.jp/issues/121330

## 概要
- user に readOnly フラグがある場合のクライアントサイドでの制限

## 実装方針
1. useIsGuestUser を呼び出している箇所を確認し、必要であれば useIsReadOnlyUser フックから UI 表示を制限する
2. trash ページの「Empty The Trash」だけ useIsGuestUser による制限でなかったが、 useIsReadOnlyUser を追加
3. NotAvailableForGuest コンポーネントによる制限箇所がある。これは一旦実装したが、後続タスクで実装します。 https://redmine.weseek.co.jp/issues/121331

## Screenshot
### nav, growi nav （Bookmark などに登録できる. 三連ボタンは押せない）
![image](https://user-images.githubusercontent.com/68407388/237011438-102df1b8-412f-4dba-a89c-028fb89114a4.png)
### fab
![image](https://user-images.githubusercontent.com/68407388/237018907-cd496861-3bd2-4911-a2be-a2b00b20b337.png)
### Tag
![image](https://user-images.githubusercontent.com/68407388/237011676-04323ba7-1783-49ec-abc2-e2293e243256.png)
### PageTree
![image](https://user-images.githubusercontent.com/68407388/237011716-e3185729-2523-480d-90f0-c6c4439f8215.png)
### Trash
![image](https://user-images.githubusercontent.com/68407388/237017991-0fec8310-c650-4a3c-9da2-c27dd7335273.png)
### Search
![image](https://user-images.githubusercontent.com/68407388/237011933-05ae3eaf-4ce3-4397-bfef-5404d0274cf5.png)
Bookmark などに登録できる
![image](https://user-images.githubusercontent.com/68407388/237012956-482d58a2-27fb-43ae-8c01-4d1e953cd48f.png)
### Comment
![image](https://user-images.githubusercontent.com/68407388/237018348-180a7bc5-1714-4675-8357-970ec03fae98.png)

2023-05-09 12:33 UTC, yuki-takei requested changes

2023-05-11 04:07 UTC, jam411 commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        disabled={!!isGuestUser || !!isReadOnlyUser || !!isSharedUser}
これらが操作できるように修正しました。
![image](https://github.com/weseek/growi/assets/68407388/8ce93ec6-02fa-435b-97fc-2bd8687491e6)

![image](https://github.com/weseek/growi/assets/68407388/279da465-245e-4009-a9a3-1a7b562981c8)

![image](https://github.com/weseek/growi/assets/68407388/4f15db13-ffac-4c64-8a17-06fa329eb5a1)

2023-05-11 04:07 UTC, jam411 commented on apps/app/src/components/DescendantsPageList.tsx
> +        isEnableActions={!(isGuestUser || isReadOnlyUser)}
このPRに含めました

2023-05-12 02:44 UTC, yuki-takei approved these changes

2023-05-12 02:44 UTC, yuki-takei commented on apps/app/src/components/Common/Dropdown/PageItemControl.tsx
> +        { !forceHideMenuItems?.includes(MenuItemType.RENAME) && isEnableActions && !isReadOnlyUser && pageInfo.isMovable && (
現行の `isReadOnlyUser` を props で入れてくるのがいいか、
`isReadOnlyUser` の値によって親が `forceHideMenuItems` を変えるのがいいのか、
どっちが綺麗か一旦検討してみてほしい

まあ ROM かどうかで使える機能が変わるのであって親によって show/hide を変えるというわけではないから今のままでもいいのかもしれない

2023-05-12 09:46 UTC, merged