imprv: Change from EnvVarsTable.jsx to EnvVarsTable.tsx
weseek/growi pull request #7634
Opened 2023-05-10 04:27 UTC by reiji-h

# Task
- https://redmine.weseek.co.jp/issues/121646
# 概要
`apps/app/src/components/Admin/AdminHome/EnvVarsTable.jsx` をTS/FC 化

2023-05-10 08:16 UTC, jam411 requested changes
- propTypes を廃止してください。
- GROWI は named export で統一する方針なので named export にしてください。

2023-05-10 08:16 UTC, jam411 commented on apps/app/src/components/Admin/AdminHome/EnvVarsTable.tsx
> +  const envVarRows: JSX.Element[] = [];
`const envVarRows: React.ReactNode[] = [];` でよさそうです。

2023-05-11 06:22 UTC, reiji-h commented on apps/app/src/components/Admin/AdminHome/EnvVarsTable.tsx
> +  const envVarRows: JSX.Element[] = [];
今回 `envVarRows` に push する要素内の `key`, `value` はともに `string` で `JSX.Element` 以外の要素になることがないと考えるので `JSX.Element` のままでいこうと思います。

2023-05-11 08:25 UTC, jam411 approved these changes

2023-05-12 02:50 UTC, yuki-takei requested changes

2023-05-12 02:50 UTC, yuki-takei commented on apps/app/src/components/Admin/AdminHome/EnvVarsTable.tsx
> +  envVars: object,
`Record<string, object>` とか少なくともキーが string とわかるタイプがいいかなあ

2023-05-18 03:15 UTC, merged