feat: Apply read-only-validator.ts
weseek/growi pull request #7639
Opened 2023-05-11 09:26 UTC by jam411

task: https://redmine.weseek.co.jp/issues/121339

## Screenshot
### console warning
![image](https://github.com/weseek/growi/assets/68407388/9283d6ab-80ff-417a-84d4-aadab5564ce3)
### toastr
![image](https://github.com/weseek/growi/assets/68407388/ddeebecf-449b-4755-85d6-d890db310308)

2023-05-11 09:41 UTC, jam411 commented on apps/app/src/server/routes/apiv3/slack-integration-settings.js
> +  router.delete('/slack-app-integrations/:id', loginRequiredStrictly, adminRequired, validator.deleteIntegration, apiV3FormValidator, addActivity,
slack-integration-settings.js の中でこのルートだけ loginRequiredStrictly, adminRequired がなかったので追加しました。
ご確認お願いします。

参考：
- [エンドポイントが作成されたらしき RR](https://github.com/weseek/growi/pull/3734/files) 
- [:id 追加の改修がされたらしき PR](https://github.com/weseek/growi/commit/b306107052d795a8fd71a852fca2cff08aa15799#diff-93dcef02cfa7853e903d1cd472d2f01c054418d0c3cfe768719ea3eb57da1f96R413)

2023-05-11 09:41 UTC, jam411 commented on apps/app/src/server/middlewares/read-only-validator.ts
> +  }
readOnly フラグが true ならば apiv3Err() でエラーを返すようにしました。

2023-05-12 04:26 UTC, yuki-takei commented
apiv1 全般カバーが必要だと思う

2023-05-12 04:27 UTC, yuki-takei requested changes

2023-05-12 04:27 UTC, yuki-takei commented on apps/app/src/server/middlewares/read-only-validator.ts
> +  }
名前を excludeReadOnlyUser に変えてください

2023-05-12 04:27 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/pages.js
> +  router.post('/resume-rename', accessTokenParser, loginRequiredStrictly, readOnlyValidator, validator.resumeRenamePage, apiV3FormValidator,
resume はできてもいいね

2023-05-12 11:58 UTC, yuki-takei requested changes

2023-05-12 11:58 UTC, yuki-takei commented on apps/app/src/server/middlewares/exclude-read-only-user.ts
> +  if (user.readOnly) {
user が null の場合を一応カバーしておきたい。カバーしていない場合、暗黙的に loginRequiredStrictly の後に実行される必要があるという制約ができてしまうので。

user が null の場合は、logger.warn でその旨を出した上で通過させてよい。

2023-05-13 13:19 UTC, merged