imprv: Admin user can use `reset-password` without email settings
weseek/growi pull request #7650
Opened 2023-05-15 03:22 UTC by jam411

task: https://redmine.weseek.co.jp/issues/121726

- メール設定に依存せずに管理者がユーザーのパスワードをリセットできる

## やってこと
- #7356 の変更を Revert する
- メール設定されていれば送信ボタンを表示する

## 関連PR
- v6 #7356
- v5 #7382

2023-05-15 13:05 UTC, yuki-takei requested changes

2023-05-15 13:05 UTC, yuki-takei commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +        </p>
欲を言えば collapse で隠したい

2023-05-16 02:15 UTC, jam411 commented on apps/app/resource/locales/en_US/admin/userResetPassword.txt
修正しました

2023-05-16 02:20 UTC, jam411 commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +        </p>
後続ストーリーに記載しました。

2023-05-16 03:12 UTC, merged