imprv: infinite scroll pagetimeline
weseek/growi pull request #7679
Opened 2023-05-22 06:31 UTC by reiji-h

- 概要
  - ページリスト > タイムライン を無限スクロール可能に。
- Task
  - https://redmine.weseek.co.jp/issues/115299

2023-05-23 04:50 UTC, jam411 requested changes

2023-05-23 04:50 UTC, jam411 commented on apps/app/src/components/PageTimeline.tsx
>          {/* eslint-disable-next-line react/no-danger */}
このコメントは不要だと思うので削除しておいてください。
次いでに、次の行の `no_page_list` が property key 名としてふさわしくないと思うので `no_pages_under_this_page` とかにしておいてください。

2023-05-23 04:50 UTC, jam411 commented on apps/app/src/components/PageTimeline.tsx
> +
`apps/app/src/stores/page-timeline.tsx` に移動してください。

2023-05-23 04:50 UTC, jam411 commented on apps/app/src/components/PageTimeline.tsx
> +          .map(page => (
`data.map(apiResult => apiResult.pages).flat().map(page => (`

この部分は flatMap が使えそうです。
`data.flatMap(apiResult => apiResult.pages).map(page => (`

ref: https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

2023-05-24 02:07 UTC, reiji-h commented on apps/app/src/components/PageTimeline.tsx
> +          .map(page => (
flatMap を使います！

2023-05-24 02:27 UTC, jam411 commented on apps/app/src/components/PageTimeline.tsx
> +        <p>{t('custom_navigation.no_pages_under_this_page')}</p>
translation.json も修正する必要があります。
そして、translation.json はほかコンポーネントで共通で使われるので、no_page_list で grep して、該当箇所を修正する必要があります。

2023-05-24 06:39 UTC, jam411 approved these changes

2023-05-24 12:40 UTC, merged