feat: Clean up client design
weseek/growi pull request #7687
Opened 2023-05-23 06:42 UTC by jam411

- commit [update attachment client](https://github.com/weseek/growi/commit/6155e94e60f0d8b1d7fa93f2b09289b1935a8c95)
  - task: 
    - https://redmine.weseek.co.jp/issues/121391
    - https://redmine.weseek.co.jp/issues/121390

- commit [add serialize user securely](https://github.com/weseek/growi/commit/0eeb91a30737f7be10dd8c547797fcc098660f6d)
  - task: 
    - https://redmine.weseek.co.jp/issues/122323
    - https://redmine.weseek.co.jp/issues/121389

## Screenshot
![image](https://github.com/weseek/growi/assets/68407388/82afa4ae-0917-4ee0-95a3-95f89cee1348)

2023-05-23 07:44 UTC, yuki-takei requested changes

2023-05-23 07:44 UTC, yuki-takei commented on apps/app/src/services/renderer/remark-plugins/attachment.ts
> +    attachmentId:  pathName[2],
ここは一応 split ではなく path などのライブラリを使おう

2023-05-23 07:44 UTC, yuki-takei commented on apps/app/src/components/ReactMarkdownComponents/Attachment.tsx
> +                {new Date(createdAt).toLocaleString(getLocaleStringLocale(i18n.language))}
わざわざ const LocaleStringLang を作りたくないのでこの機能は消そう

2023-05-23 07:44 UTC, yuki-takei commented on apps/app/src/components/ReactMarkdownComponents/Attachment.tsx
> +    <div className={`${styles.attachment} d-inline-block`}>
inline block にすべきかどうかから検討かなあ
Notion とか参考にするといいと思うけど

2023-06-21 09:55 UTC, jam411 commented on apps/app/src/services/renderer/remark-plugins/attachment.ts
> +    attachmentId:  pathName[2],
path.basename を使うようにしました。

2023-06-21 09:58 UTC, jam411 commented on apps/app/src/components/ReactMarkdownComponents/Attachment.tsx
> +    <div className={`${styles.attachment} d-inline-block`}>
d-inline-block にするとカード伸縮を表現できなくてできれば inline block にしたいです。
反対に「d-inline-block あり」と同じようなカード表現ができれば、d-inline-block を使う理由はないです。

## d-inline-block あり
![image](https://github.com/weseek/growi/assets/68407388/017cc876-37e0-46fc-a1a9-9558de88694b)
## d-inline-block なし
![image](https://github.com/weseek/growi/assets/68407388/6cb49f7d-a631-4a5e-bbd6-f73764356a23)

2023-06-21 12:27 UTC, merged