fix : gw7957 fix put back page on bookmark sidebar
weseek/growi pull request #7698
Opened 2023-05-25 10:26 UTC by mudana-grune

### Issue
https://youtrack.weseek.co.jp/issue/GW-7957
Put back not openend from bookmark 

### Fix 
- Add PutBackModal to BasicLayout
- Implement mutation of bookmark folder, user's bookmark, bookmark info and page info after delete or put back a page

### Test

https://github.com/weseek/growi/assets/92426728/a0c5192c-4190-4981-b68b-27b68a6f729d

2023-06-19 02:30 UTC, jam411 requested changes
We want to avoid changing other components for bookmarks as much as possible.
I'm sorry, but could you please write the code in a direction where put back is not shown from the bookmark sidebar dropdown?

2023-06-19 02:30 UTC, jam411 commented on apps/app/src/components/PageList/PageListItemL.tsx
> +        mutateBookmarkFolders();
Are these mutate function required?
I don't want to use them.

2023-06-19 02:30 UTC, jam411 commented on apps/app/src/components/SearchPage/SearchResultList.tsx
> +    mutateBookmarkFolders();
Are these functions necessary?

2023-07-13 04:23 UTC, jam411 commented on apps/app/src/components/Layout/BasicLayout.tsx
> +        <PutbackPageModal />
Bookmarks Sidebar で PutbackPageModal を呼び出すようになったので BasicLayout で呼び出すようにしました。

2023-07-13 04:23 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkItem.tsx
> +  }, [bookmarkedPage, openPutBackPageModal, bookmarkFolderTreeMutation, router, mutateCurrentPage, t]);
Bookmarks 用の putBackClickHandler

2023-07-13 04:23 UTC, jam411 commented on apps/app/src/components/Navbar/SubNavButtons.tsx
> +  ];
SubNavButtons では Put back page の項目を表示しないように修正しました。
- /trash 配下のページはそもそも SubNavButtons は表示されません。
- 検索時に表示される SearchResultContent の SubNavButtons には表示されるが handler メソッドが渡っておらず機能していませんでした。
![image](https://github.com/weseek/growi/assets/68407388/a7626a6e-0350-44f2-9db2-b89811d83181)
- ただし、SearchResultList の PageListItemL.tsx から put back page はできます。

2023-07-13 04:27 UTC, jam411 reviewed
残りは Mudana さんのフォーマット修正だけの見込み

2023-07-13 04:27 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
> +              <React.Fragment key={`bookmark-folders-${folder._id}`}>
key の修正

2023-07-13 04:27 UTC, jam411 commented on apps/app/src/pages/[[...path]].page.tsx
PutbackPageModal は BasicLayout で呼び出すようにしたため削除

2023-07-13 04:27 UTC, jam411 commented on apps/app/src/pages/_search.page.tsx
PutbackPageModal は BasicLayout で呼び出すようにしたため削除

2023-07-13 04:27 UTC, jam411 commented on apps/app/src/pages/trash.page.tsx
PutbackPageModal は BasicLayout で呼び出すようにしたため削除

2023-07-13 05:24 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
> +      }
このあたりの mutate 処理は put back page している箇所すべてで整合性をとる必要がありそうだったので別ストーリーに切り出しました。
https://redmine.weseek.co.jp/issues/126732

2023-07-13 11:31 UTC, yuki-takei approved these changes

2023-07-13 11:31 UTC, yuki-takei commented on apps/app/src/components/Bookmarks/BookmarkItem.tsx
> +        mutateCurrentPage();
- router.push しながら mutateCurrentPage を呼ぶのは違和感

2023-07-13 11:31 UTC, merged