imprv:  Can ues normal browser transition in searching page
weseek/growi pull request #7755
Opened 2023-05-29 09:17 UTC by reiji-h

# Task
- https://redmine.weseek.co.jp/issues/88266
# 概要
検索結果におけるブラウザバック、ブラウザフォワードを正常に動作するように改善

2023-06-01 11:11 UTC, yuki-takei requested changes

2023-06-05 05:19 UTC, reiji-h commented on apps/app/src/components/SearchPage.tsx
> +    router.push(`${newUrl.pathname}${newUrl.search}`);
やり直す形で修正しました。

2023-06-05 06:38 UTC, jam411 commented on apps/app/src/components/SearchPage.tsx
> +  const [changeState, setChangeState] = useState<changeStyle>(null);
初期値が null な必要がありますか？
なければ 
- type は関数の外に出す

かそのまま

- `const [changeState, setChangeState] = useState<'search' | 'browser'>('search');` とか

2023-06-05 06:38 UTC, jam411 commented on apps/app/src/components/SearchPage.tsx
> +  }, [keyword, setChangeState]);
useEffect の依存配列に eslint warning が出ていると思うから修正してください。
原則 eslint にしたがって書きたいです。

2023-06-05 06:38 UTC, jam411 commented on apps/app/src/components/SearchPage.tsx
> +  }, [keyword, setChangeState]);
switch 文使わなくても書けそうです。

```
useEffect(() => {
    const newUrl = new URL('/_search', 'http://example.com');
    newUrl.searchParams.append('q', keyword);

    if (changeState === 'search') {
      router.push(`${newUrl.pathname}${newUrl.search}`, '', { shallow: true });
    }

    setChangeState('search');
  }, [keyword, setChangeState]);
```

2023-06-05 06:38 UTC, jam411 commented on apps/app/src/components/SearchPage.tsx
> +  }, [setChangeState, setKeyword]);
こちらも useEffect の依存配列に eslint warning が出ていると思うから修正してください。
原則 eslint にしたがって書きたいです。

2023-06-05 06:38 UTC, jam411 commented on apps/app/src/components/SearchPage.tsx
> +      }
`if (newKeyword == null)` で始めてください。
理由は newKeyword の型が string | null だからなのと GROWI は null をはじくときは　`==` で明記するようにしています。(`!newKeyword` とはしない)

2023-06-06 04:54 UTC, jam411 commented on apps/app/src/components/SearchPage.tsx
クエリパラメータに合わせて再検索が行われて SearchResultList は更新されているけど左ペインの PageView の挙動があやしいですね。
- フリッカリングする（何度かレンダリングされているよう）
- 一度 view に表示されるとブラウザバックしてもそのまま表示される
  - ページが引っかからないキーワードで検索する。
  - 引っかかるキーワードで検索する
  - ブラウザバックする

2023-06-06 13:15 UTC, reiji-h commented on apps/app/src/components/SearchPage.tsx
- フリッカリングについては今回から起こってる問題ですね…。
- PageView に一番最初に表示されたものが残る現象については今回の変更に直接的な影響がないので別タスクに切り分けるのが良いかなと思っています。

2023-06-06 13:19 UTC, reiji-h commented on apps/app/src/components/SearchPage.tsx
## 現状
https://github.com/weseek/growi/assets/132258880/a2c59ad1-c423-49a8-b9ec-c37ebc13fd89

2023-06-06 23:17 UTC, yuki-takei requested changes

2023-06-06 23:17 UTC, yuki-takei commented on apps/app/src/components/SearchPage.tsx
- 今回の変更以前から起きている問題についてはこのストーリーで取り扱う必要はない
- 今回の変更で flicker が起きてしまっているのであれば、それはこのストーリーで取り扱うべきで、かつそれが解消されるまでは master にマージすべきでない
    - PR を master に向けるのであれば後続タスク化はあまり意味がないね(結局この PR に修正を反映させないといけないので)
    - feature ブランチを切って PR を分けるならそれはそれで構わない

2023-06-06 23:17 UTC, yuki-takei commented on apps/app/src/components/SearchPage.tsx
> +  const routerRef = useRef(router);
なぜ useRef しているのかはコード内にコメントを追加しておいて

2023-06-12 04:18 UTC, reiji-h commented on apps/app/src/components/SearchPage.tsx
主に SearcPageBase.tsx で起こっていた問題で、次の点を修正することでフリッカリングを無くしました。
- dynamic import をコンポーネント外へ出す
- SearchResultContent は検索結果(pages)があった時のみ返す

また view が一度固定されるとブラウザバッグしても表示され続ける問題(以前からあった問題)も修正しました。
- selectedPageWithMeta を pages に依存して更新するように

2023-06-12 05:57 UTC, reiji-h commented on apps/app/src/components/SearchPage.tsx
## 現状
https://github.com/weseek/growi/assets/132258880/14f6a62a-6b7f-49cc-9448-cb89cfa1d145

2023-06-12 06:49 UTC, merged