feat: GW-7958 update authentication settings
weseek/growi pull request #7761
Opened 2023-05-30 10:41 UTC by mudana-grune

### Issue
https://youtrack.weseek.co.jp/issue/GW-7958
- Can disable authentication method without admin access so no admin can login

### Fix
- Get a user with admin access from an external account
- Leave at least one authentication method that has admin access
- Checks all authentication methods that have admin access when disabling an authentication method. If there is still an authentication method with admin access, then the authentication method can be disabled. If not, then there must be 1 auth method with admin access so it can't be disabled

2023-06-02 01:54 UTC, jam411 requested changes
Please fix CI errors.

2023-06-05 03:17 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-setting.js
> +    }
Please refactor like that
```
async function checkExternalStrategyHasAdmin(providerType) {
  const externalAccounts = await ExternalAccount.find({ providerType }).populate('user').exec();
  return externalAccounts.some(externalAccount => externalAccount.user && externalAccount.user.admin);
}
```

2023-06-05 03:17 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-setting.js
> +    await Promise.all(externalAuthPromises);
How about separate functions like.
```
  const allActiveAuthMethodsWithAdmin = await getAllActiveAuthMethodsWithAdmin();

  if (!isEnabled && allActiveAuthMethodsWithAdmin.length === 0) {
    return res.apiv3Err(new ErrorV3('Must have admin enabled authentication method'), 405);
  }

  async function getAllActiveAuthMethodsWithAdmin() {
    const activeAuthMethodsWithAdmin = [];

    await checkAndAddActiveAuthMethodWithAdmin('local', 'crowi', 'security:passport-local:isEnabled', checkLocalStrategyHasAdmin);
    
    const externalAuthTypes = Object.values(GrowiExternalAuthProviderType);
    await Promise.all(externalAuthTypes.map(async strategy => {
      const configKey = `security:passport-${strategy}:isEnabled`;
      await checkAndAddActiveAuthMethodWithAdmin(strategy, 'crowi', configKey, checkExternalStrategyHasAdmin);
    }));

    return activeAuthMethodsWithAdmin;
  }

  async function checkAndAddActiveAuthMethodWithAdmin(strategy, configNamespace, configKey, checkHasAdminFunction) {
    const isEnabled = configManager.getConfig(configNamespace, configKey);
    const hasAdmin = await checkHasAdminFunction(strategy);
    if (isEnabled && hasAdmin && setupStrategies.includes(strategy)) {
      allActiveAuthMethodsWithAdmin.push(strategy);
    }
  }
```

2023-06-19 04:11 UTC, jam411 commented
1. have an administrative user with ID/Pass
2. enable GitHub authentication
3. Login as a GitHub user and make this user an administrator 
4. Remove admin rights for the admin user in ID/Pass
5. Make sure you can disable ID/Pass authentication
6. Re-enable and update ID/Pass authentication
7. Disable GitHub Authentication 

# Symptoms
Github authentication can be disable even though they are the only github administrative user.

2023-06-22 07:12 UTC, jam411 requested changes
Still Github authentication can be disable. Please recheck.

2023-06-23 04:06 UTC, jam411 requested changes

2023-06-23 04:06 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-setting.js
> +    }
getAllActiveAuthMethodsWithAdmin() は !isEnabled の時だけ実行するようにしたい

2023-06-23 04:06 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-setting.js
> +    }
strategy × user の処理が走るので、

- disable される strategy 以外だけを見る。
- それ以外の strategy でログインしている admin ユーザーがあったタイミングで処理を切り上げるようにする。

2023-06-29 10:44 UTC, jam411 commented
Github 認証でログインするとエラーがでるのでそれが解消してから

2023-07-13 06:05 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-setting.js
> +    }
この部分のレビューお願いします。
残りは configManager を crowi 依存から外した差分です。

2023-07-13 06:10 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-setting.js
> +    }
認証機構設定を無効化する毎に 「user 数」 × 「有効になっている auth method の数」だけ実行されます。

2023-07-13 11:44 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/security-setting.js
> +
上の 2 つの check* メソッドは TS 化したい

- rename security-setting.js -> security-settings/index.js
- check* メソッドは新たな TS にして security-settings/index.js からインポートして使う

2023-07-13 11:47 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/security-setting.js
> +        const hasAdmin = await checkAuthStrategyHasAdmin(strategy);
わざわざ個別の strategies ごとに判定しなくても、「local の判定」と「external 系まるっと判定」の2回のクエリでいいと思う

2023-07-13 11:48 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/security-setting.js
> +          { $match: { externalAccounts: [] } },
local の判定方法これじゃない気がする。
externalAccounts のいくつかをセットアップ済みのユーザー(ログイン手段を複数持っているユーザー)の中で local strategy でログイン可能なユーザーはいると思う。

じゃあ代替はなんだといわれるとちょっと自信がないけど…password フィールドに値があるかどうか？(要調査)

2023-07-13 11:51 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/security-setting.js
> +        .exec();
`ExternalAccount.find({ providerType: strategy })` は確実にユーザー数よりも多いので、ExternalAccount.find してそれぞれ populate するのは効率が悪い。

## 代替案

523行目の FB で書いたような 「external 系まるっと判定」 を前提とすると、

local と同じように `User.aggregate` で externalAccounts に setupStrategies のどれかを含むようなユーザーを抽出して数を数える、でいいと思う。

2023-07-14 03:26 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-setting.js
> +
修正しました。

2023-07-14 07:22 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-setting.js
> +          { $match: { externalAccounts: [] } },
`username` or `email` フィールドと `password` フィールドがあれば ID/Pass 認証でき、`username`, `email` は`required: true` であり User モデルには必ず入ってくるため `password` フィールドに値があるかどうかで aggregate するようにしました。

2023-07-14 07:22 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-setting.js
> +        .exec();
「external 系まるっと判定」で修正しました。

2023-07-14 08:16 UTC, jam411 commented on packages/core/src/interfaces/external-account.ts
> +}
- check* 系メソッドを TS 化する過程で `apps/app/src/interfaces/external-account.ts` に、`apps/app/src/features/questionnaire/interfaces/growi-info.ts` の GrowiExternalAuthProviderType を持ってきて、`packages/core/src/interfaces/external-account/ts` に移動し `@growi/core` からインポートできるようにして `providerType: string` としているところに適用しました。
- 主な理由は `packages/core/src/interfaces/user.ts` が providerType プロパティを持っていたので `IExternalAuthProviderType` を適用したかったのと、features/questionnaire にもまたがっていたからなどですが、core パッケージ化していいか相談させてください。
- なお、基本的に `providerType` で grep して TS 化されているところに `IExternalAuthProviderType` を適応しました。`/workspace/growi/apps/app/src/server/models/update-post.ts` には、認証とは別で `slack` が入ってくる provider プロパティがありますがこれは別ものだと判断しています。

2023-07-14 10:54 UTC, yuki-takei requested changes

2023-07-14 10:54 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/security-settings/checkSetupStrategiesHasAdmin.ts
> +  const User = crowi.model('User');
mongoose.model() で置き換えれば crowi に依存しなくてすむ

2023-07-14 10:54 UTC, yuki-takei commented on packages/core/src/interfaces/external-account.ts
> +}
問題ないです

2023-07-15 06:39 UTC, jam411 commented on apps/app/src/server/routes/apiv3/security-settings/checkSetupStrategiesHasAdmin.ts
> +  const User = crowi.model('User');
`const User = mongoose.model('User') as any;`
を使うようにしました。

2023-07-15 07:56 UTC, merged

2023-07-15 07:59 UTC, jam411 commented on packages/core/src/interfaces/external-account.ts
`apps/app/src/interfaces/external-account.ts` をこちらに移動

2023-07-15 08:12 UTC, jam411 commented on packages/core/src/interfaces/external-account.ts
`apps/app/src/interfaces/external-account.ts` からこちらに移動