imprv: Delete completely user pages
weseek/growi pull request #7766
Opened 2023-06-01 04:57 UTC by jam411

task: https://redmine.weseek.co.jp/issues/117014

- page を削除するには pages コレクションを削除するだけでは不十分だったので、pages.js の `router.post('/delete'` ルートを参考にしてメソッドを追加した。

2023-06-02 02:08 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +      // see: https://redmine.weseek.co.jp/issues/123556
疑問点:
- isAnyoneWithTheLink の扱い
- router.post('/delete', を参考にしているが page.js の api.remove をつかわなくてもいいか

2023-06-02 10:33 UTC, yuki-takei requested changes

2023-06-02 10:33 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/users.js
> +        );
フィルタリングは必要ない

2023-06-02 10:35 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/users.js
> +        );
deleteUserHomeByUserDeletion というメソッドをサービス層に追加しよう

2023-06-02 11:50 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +        );
修正しました。

2023-06-02 12:01 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +        );
いろいろ考えた結果 deleteUserHomePageAndSubPages に行きつきました。

2023-06-02 12:26 UTC, yuki-takei requested changes

2023-06-02 12:26 UTC, yuki-takei commented on apps/app/src/server/models/obsolete-page.js
> +  pageSchema.statics.getUserHomePagePath = function(user) {
廃止しよう

2023-06-02 12:26 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/users.js
> +    const isUsersHomePageDeletionEnabled = crowi.configManager.getConfig('crowi', 'security:isUsersHomePageDeletionEnabled');
configManager は crowi から取らなくて良くなったのでモジュールから直接 import してください

2023-06-02 12:26 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/users.js
> +        );
- このブロックの中身はまるっと PageService 行き
- 移植したメソッドは non blocking で呼ぶ(つまり await を付けない)

2023-06-02 12:34 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +    const isUsersHomePageDeletionEnabled = crowi.configManager.getConfig('crowi', 'security:isUsersHomePageDeletionEnabled');
修正しました。

2023-06-03 13:06 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +        );
修正しました。

2023-06-03 13:12 UTC, jam411 commented on apps/app/src/server/events/user.js
- deleteCompletelyUserHomePageAndSubpages を使うようにしました。
- class を使うようにリファクタリングしました。

2023-06-04 03:25 UTC, yuki-takei requested changes

2023-06-04 03:25 UTC, yuki-takei commented on apps/app/src/server/events/user.js
> +    const userHomePagePath = `/user/${user.username}`;
`const userHomePagePath = `/user/${user.username}`;` のユーティリティ化を後続タスクで

2023-06-04 03:25 UTC, yuki-takei commented on apps/app/src/server/events/user.js
> +    let page = await Page.findByPath(userHomePagePath, user);
元からあるコードだが、第二引数 `includeEmpty` のはずだからおかしいような…要精査

2023-06-04 03:26 UTC, yuki-takei commented
後続タスクに integration test を追加したい

2023-06-09 05:04 UTC, jam411 commented on apps/app/src/server/events/user.js
> +    const userHomePagePath = `/user/${user.username}`;
https://redmine.weseek.co.jp/issues/124324
こちらで着手します。

2023-06-09 05:11 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +    const isUsersHomePageDeletionEnabled = configManager.getConfig('crowi', 'security:isUsersHomePageDeletionEnabled');
このエンドポイントはユーザーを削除するエンドポイントで、
もし `isUsersHomePageDeletionEnabled` が disabled ならばユーザー削除処理してほしいので、
早期 return せずにいます。

2023-06-09 05:28 UTC, jam411 commented on apps/app/src/server/service/page.ts
> +  async deleteCompletelyUserHomePageAndSubpages(user, userHomePagePath, options = {}): Promise<void> {
> 第一引数の user は消す 

こちら時間かけたいので後続タスクで取り組みます。
https://redmine.weseek.co.jp/issues/124326

2023-06-09 06:16 UTC, jam411 commented on apps/app/src/server/service/page.ts
> +  async deleteCompletelyUserHomePageAndSubpages(user, userHomePagePath, options = {}): Promise<void> {
> 引数に型付けを
> options は結局使われないので不要では？
> メソッド名を deleteCompletelyUserHomeBySystem にして、jsdoc で呼び出し元を限定するようにメッセージを書く

こちら修正しました。
JSDoc で呼び出し元の限定をする方法はなさそうなので、@description に記載するようにしました。

2023-06-09 06:17 UTC, jam411 commented on apps/app/src/server/events/user.js
> +    let page = await Page.findByPath(userHomePagePath, user);
こちらもこの後続タスクで着手します。
https://redmine.weseek.co.jp/issues/124326

2023-06-09 07:22 UTC, jam411 commented on apps/app/src/server/events/user.ts
> +    super();
import Crowi from '../crowi' とすると相互参照になるため any 型にしてます。

2023-06-09 07:27 UTC, jam411 commented
> 

こちらで対応します。　https://redmine.weseek.co.jp/issues/123652

2023-06-09 07:28 UTC, jam411 commented on apps/app/src/server/events/user.js
対応しました。

2023-06-09 13:11 UTC, yuki-takei requested changes

2023-06-10 00:47 UTC, jam411 commented on apps/app/src/server/events/user.ts
> +      await this.crowi.pageService?.deleteCompletelyUserHomeBySystem(user, userHomePagePath);
修正しました

2023-06-10 00:54 UTC, merged