Imprv: Send new password email
weseek/growi pull request #7767
Opened 2023-06-01 07:22 UTC by soumaeda

https://redmine.weseek.co.jp/issues/123395
パスワードリセット後、メール設定がされていればメールが送信できるようにしました。
Sendボタン横に宛先を表示しましたが、メールアドレスが長い場合を想定し、usernameとemailを上下に分けました。

<img width="497" alt="スクリーンショット 2023-06-01 16 16 08" src="https://github.com/weseek/growi/assets/112812878/22f76e12-237e-4256-8f43-c134868b600b">
<img width="498" alt="スクリーンショット 2023-06-01 16 16 48" src="https://github.com/weseek/growi/assets/112812878/d819e2c2-77e4-4319-a582-9e5aaa9cb13a">

2023-06-02 01:48 UTC, jam411 requested changes

2023-06-02 01:48 UTC, jam411 commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +        </div>
ここのデザインは武井さんに同意をとってください

2023-06-02 01:48 UTC, jam411 commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
>      );
共通化できるところは共通化してみてください.
Close ボタン箇所など

2023-06-02 01:48 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +    const newPassword = await User.resetPasswordByRandomString(id);
ここでもう一度 newPassword 発行するとまずそう。

2023-06-02 01:48 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +    const user = await User.findById(id);
try-catch 文にいれて、user が見つからなかった時のハンドリングをしてください。

2023-06-02 09:37 UTC, jam411 commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +      this.setState({ isCreateUserButtonPushed: false });
これ必要ないですか？コメントに返してほしいです。

2023-06-02 09:47 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +    const user = await User.findById(id);
参考 passport.js
```
const user = await User.findById(id);
if (user == null) {
　　throw new Error('user not found');
}
```

2023-06-02 09:49 UTC, jam411 reviewed
- コメントに対して回答が欲しいです
- https://github.com/weseek/growi/pull/7767#discussion_r1214162071 こちら追記しました

よろしくお願いします。

2023-06-05 01:11 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +      this.setState({ isCreateUserButtonPushed: false });
UserInviteModal.jsxを参考にした際に、メール送信後、ボタンの状態を元に戻す処理が実装されていましたが、ここでは不要だと判断したのでしたが、その一部が残ったままでした。

2023-06-05 01:12 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +    const newPassword = await User.resetPasswordByRandomString(id);
発行されたパスワードをクライアントから取得するように修正しました

2023-06-05 01:52 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
>      );
renderButtons()としてまとめてみました。

2023-06-05 01:54 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +    const user = await User.findById(id);
idによって取得したユーザーが見つからない場合のエラーハンドリングを追加しました

2023-06-05 03:57 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +      // eslint-disable-next-line no-await-in-loop
これいらないと思います。

2023-06-05 03:57 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +    const failedToSendEmailList = [];
リストでなくてもいいのでは思ったのと、
userResetPassword 用であることを明記したい。
それか sendEmailByUserList と共通化したい気もしますが。。
invitation とも絡んでくるので一旦そのまま

2023-06-05 03:57 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +  });
JSDoc を書いてください。

2023-06-05 05:24 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +    const failedToSendEmailList = [];
failedToSendNewPasswordEmailに名称変更しました

2023-06-05 06:31 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +          </button>
こちらもコンフリクト解消箇所です

2023-06-05 08:27 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +  });
/reset-passwordのJSDocを参考に記述しました

2023-06-05 08:57 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +    const failedToSendEmailList = [];
すみません。日本語おかしかった。

2023-06-05 10:50 UTC, jam411 requested changes

2023-06-05 10:50 UTC, jam411 commented on apps/app/public/static/locales/en_US/admin.json
> +      "mail_setting_link":"<i class='icon-settings mr-2'></i><a href='/admin/app'>Email settings</a>"
こちら "invite_modal" と全く内容が同じなので統合したいです。
`"mail_setting_link":"<i class='icon-settings mr-2'></i><a href='/admin/app'>Email settings</a>"` を一般化して 
invite_modal の方を削除して呼び出している箇所も修正してください。

2023-06-05 10:50 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +  };
- `reazon` を `reason` に修正してください

2023-06-05 10:50 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +      return res.apiv3({ user, failedToSendEmail: sendEmail.failedToSendNewPasswordEmail[0] });
ここも list を返さないよになったので合わせて修正してください

2023-06-05 10:50 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +
細かいですがここの空白を削除しておいてください

2023-06-06 01:27 UTC, soumaeda commented on apps/app/public/static/locales/en_US/admin.json
> +      "mail_setting_link":"<i class='icon-settings mr-2'></i><a href='/admin/app'>Email settings</a>"
mailer_setup_requiredを利用していたので、reset_password_modalのmail_setting_linkを削除しました。

2023-06-06 01:29 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +  };
188行目も修正いたしました

2023-06-06 02:02 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +  };
failedToSendNewPasswordEmailをcatch内で定義し、返すようにしました。

2023-06-06 03:41 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +      return res.apiv3({ user, failedToSendEmail: sendEmail.failedToSendNewPasswordEmail[0] });
あらかじめ、failedToSendNewPasswordEmailにnullを代入し、例外が発生した際に情報が追加され、nullではなくなる良いに変更しました。

2023-06-06 22:49 UTC, yuki-takei requested changes

2023-06-06 22:49 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/users.js
> +  };
sendEmailByUser のインターフェースの作法が悪い。
ファイルが ts 化されていないのがそもそも問題ではあるんだけれども…。

- return type は Promise<void> でいいはず
- try-catch はここではしなくていいはず
    - fail した際の送り先メアドは呼び出し元(router)でわかるし、reason も err.message をそのまま使えばいいので
    - 蛇足: 今回のタスクでは不要だが、もし fail した場合に追加の情報を入れたい場合は、extensible-custom-error で独自のエラーを作り、その中に値を入れて再 throw するという手法がよい

2023-06-06 22:49 UTC, yuki-takei commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +        </div>
後続タスク化して dev-uiux で相談

2023-06-06 22:49 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/users.js
> +    }
sendEmailByUser で例外が発生した場合は res.apiv3Err する

2023-06-06 22:49 UTC, yuki-takei commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +    }
- router の方に書いた FB 対応をしたら正常終了した場合の if-else は必要なくなるはず
- 正常終了した場合は toastr 表示するまではしなくていいと思う
    - ボタンが押せなくなって(消えても良い)正常終了した旨がわかるようになれば
    - これも後続タスク化して、dev-uiux で相談

2023-06-09 01:46 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +  };
try-catchを削除しました。

2023-06-09 01:47 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +    }
apiv3Errにerr.messageを渡すようにしました

2023-06-09 04:06 UTC, jam411 requested changes

2023-06-09 04:06 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +   */
こちら直しておいて下さい。

2023-06-09 04:06 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +      return res.apiv3({ user });
user を返す必要はありますか？
なければ返さなくてもいいと思います。

2023-06-09 04:51 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +   */
不要な箇所を削除しました。

2023-06-09 05:32 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/users.js
> +      return res.apiv3({ user });
現状は必要ないので、返さないようにしました

2023-06-09 06:28 UTC, jam411 approved these changes

2023-06-09 10:19 UTC, merged