update email alert
weseek/growi pull request #7771
Opened 2023-06-02 07:16 UTC by WNomunomu

既に登録されているメールアドレスに変更しようとした場合に、原因を含めたエラーメッセージが表示されるようにしました。

2023-06-06 09:11 UTC, miya commented on apps/app/src/server/routes/apiv3/personal-setting.js
> +      // return res.apiv3Err('update-personal-settings-failed');
不要な差分は消そう

2023-06-06 09:11 UTC, miya commented on apps/app/src/components/Me/BasicInfoSettings.tsx
> +      }
良くなってきている。

あんまり err.message で条件分岐したくないので err.code に 'email_is_already_in_use' みたいなのを API 側で返却するようにしたい。

参考になりそうなコードを垂れ流しのスレッドに貼ったので確認してください。

2023-06-08 12:39 UTC, WNomunomu commented
task: https://redmine.weseek.co.jp/issues/121423
### 概要
・既に登録されているメールアドレスに変更しようとした場合に、原因を含めたエラーメッセージが表示されるようにしました。

### 詳細
・入力されたユーザーのメールアドレスがuniqueであるかどうかの判定を、API側で判定できるようにした。

2023-06-08 13:14 UTC, miya commented on apps/app/src/server/models/user.js
> +  };
if (userData) {...  はあまり良く無い。null check をしよう。
https://tips.weseek.co.jp/5fb74e7aa1ba4200489a4bd1

それともっとシンプルにできそう。

``` javascript
if (userData != null && this._id !== userData._id) {
    return false;
}

return true
```

2023-06-08 13:14 UTC, miya commented on apps/app/src/server/routes/apiv3/personal-setting.js
> +      if (err.message === 'email-is-not-unique') {
message ではないんじゃない？ フロントでは error.code で受け取りたい。

2023-06-08 13:14 UTC, miya commented on apps/app/src/server/routes/apiv3/personal-setting.js
> +        logger.error('email-is-unique');
ユニークなメールだったら logger.error では無いよね？

2023-06-08 13:14 UTC, miya commented on apps/app/src/server/routes/apiv3/personal-setting.js
> +        throw new Error('email-is-not-unique');
!isUniqueEmail だったら return res.apiv3Err( しちゃって良さそう

2023-06-09 05:53 UTC, miya commented on apps/app/src/components/Me/BasicInfoSettings.tsx
> +      }
err.message ではなく err.code で受け取れるように修正してください

2023-06-15 11:14 UTC, miya commented on apps/app/src/stores/personal-settings.tsx
> +      throw new ErrorV3('Failed to update personal data', 'failed-to-update-personal-data');
ここで条件分岐しなくても良さそう。erros をそのまま throw new して useSWRxPersonalSettings を使う側で条件分岐すれば綺麗になりそう。

2023-06-15 11:14 UTC, miya commented on apps/app/src/server/routes/apiv3/personal-setting.js
> +      return res.apiv3Err(new ErrorV3(err.message, 'update-personal-settings-failed'));
`update-personal-settings-failed` という err.code って必要 ？(どっかで使ってる？)

2023-06-19 08:22 UTC, yuki-takei requested changes

2023-06-19 08:22 UTC, yuki-takei commented on apps/app/src/server/models/user.js
> +    const userData = await User.findOne({ email: this.email });
User モデルを引っ張ってくる必要はないので、username 等を絡めたクエリに対する count を取得してその数で true/false を判定してください

2023-06-20 10:39 UTC, merged