feat: Saving the 'latestRevisionBodyLength' in the page document when saving a revision
weseek/growi pull request #7772
Opened 2023-06-02 11:16 UTC by miya

## Task
[#119759](https://redmine.weseek.co.jp/issues/119759) [GROWI] ページの revision.body を見て SSR をするか否かを決定できる
└ [#119760](https://redmine.weseek.co.jp/issues/119760) 実装

2023-06-02 18:28 UTC, yuki-takei requested changes

2023-06-02 18:28 UTC, yuki-takei commented on apps/app/src/server/models/obsolete-page.js
> +    }
この判断は next page 側でやるべき。SSR は Next の仕事なので、モデルは should SSR 云々を知るよしもない。
それから next page に移植する際は、skipSSR みたいな名前にしたい。(default で false、特定の条件下で true)

2023-06-02 18:28 UTC, yuki-takei commented on apps/app/src/pages/[[...path]].page.tsx
> +  const { trigger: mutateCurrentPage } = useSWRMUTxCurrentPage();
この辺の仕組みあまり変えたくないな。
revision body がない状態で pageWithMeta?.data を入れるとおかしなことになる？

2023-06-02 18:28 UTC, yuki-takei commented on apps/app/src/pages/[[...path]].page.tsx
> +  }, [currentPageId, mutateCurrentPage, mutateEditingMarkdown, props.isNotFound, props.shouldSSR]);
`props.shouldSSR` が true なら早期リターンしよう

2023-06-05 03:13 UTC, miya commented on apps/app/src/pages/[[...path]].page.tsx
> +  }, [currentPageId, mutateCurrentPage, mutateEditingMarkdown, props.isNotFound, props.shouldSSR]);
修正しました

2023-06-05 03:13 UTC, miya commented on apps/app/src/server/models/obsolete-page.js
> +    }
修正しました

2023-06-05 03:14 UTC, miya commented on apps/app/src/pages/[[...path]].page.tsx
> +  const { trigger: mutateCurrentPage } = useSWRMUTxCurrentPage();
そうですね... revisionBody が表示されなくなります。

2023-06-06 23:06 UTC, yuki-takei requested changes

2023-06-08 10:09 UTC, miya commented on apps/app/src/pages/[[...path]].page.tsx
> +    if (isClient() && currentPageId != null && !props.isNotFound && props.skipSSR) {
isClient は消しました

2023-06-08 10:33 UTC, miya commented on apps/app/src/pages/[[...path]].page.tsx
> +  const { trigger: mutateCurrentPage } = useSWRMUTxCurrentPage();
口頭で解決しました

2023-06-08 10:33 UTC, miya commented on apps/app/src/server/service/config-loader.ts
> +  },
50000 文字以上の文字列を持つデータを貼り付けると、開発環境でも dev wiki 等でもブラウザが停止してしまうためひとまず 30000 にしました

2023-06-08 10:33 UTC, miya commented on apps/app/src/pages/utils/commons.ts
> +};
共通化しました

2023-06-08 10:33 UTC, miya commented on apps/app/src/stores/page.tsx
> +  const shouldMutate = initialData?._id !== cache.get(key)?.data?._id && initialData !== undefined;
useSWRxCurrentPage 自身のキャッシュの page._id と initialData の _id を比較し、異なる場合に mutation を行う

2023-06-09 10:12 UTC, yuki-takei requested changes

2023-06-09 10:12 UTC, yuki-takei commented on apps/app/src/pages/[[...path]].page.tsx
> +    };
mutatePageData の宣言は props.skipSSR の判定の後でいいね。

2023-06-09 10:12 UTC, yuki-takei commented on apps/app/src/pages/[[...path]].page.tsx
> +    if (currentPageId != null && !props.isNotFound && props.skipSSR) {
`!props.skipSSR` で早期リターンするならこの判定式は冗長だね。

2023-06-09 10:12 UTC, yuki-takei commented on apps/app/src/pages/utils/commons.ts
> +  const ssrMaxRevisionBodyLength = req.crowi.configManager.getConfig('crowi', 'app:ssrMaxRevisionBodyLength');
configManager は crowi から取得する必要がある？
完全にサーバーサイドのコードなら import すべきだけど、next page から呼び出すので import が害にならないか心配している。

2023-06-13 07:00 UTC, merged