imprv: After reset password footer modal design
weseek/growi pull request #7790
Opened 2023-06-09 04:40 UTC by soumaeda

2023-06-12 14:24 UTC, jam411 commented
PRのスコープを理解するのが大変だったので、スコープを意識して説明やコメント、タスクを作るようにしてくれると嬉しいです。次回は特にコミットメッセージを意識できるともっとわかりやすくなると思います。

2023-06-13 01:19 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
>        temporaryPassword: [],
こちらのPRでは残しておくようにしました

2023-06-13 01:23 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> -  }
こちらのPRでは残しておくようにしました

2023-06-13 01:31 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
>        </>
if文を削除し、return内で真偽の判定を行うようにしました

2023-06-13 02:12 UTC, jam411 requested changes

2023-06-13 02:12 UTC, jam411 commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +          {(!isMailerSetup) ? (
`{!isMailerSetup ? (` でいけませんか？

2023-06-13 02:12 UTC, jam411 commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +      <>
フラグメント不要なら消しておいてください。

2023-06-13 02:21 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +          {(!isMailerSetup) ? (
いけました。

2023-06-13 02:21 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +      <>
不要なので、削除しました

2023-06-14 07:18 UTC, yuki-takei requested changes

2023-06-14 07:18 UTC, yuki-takei commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +        )}
要素を出し分ける必要はなく、attribute を変えればよい

2023-06-14 07:18 UTC, yuki-takei commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +      this.setState({ isEmailSent: true });
異常系の考慮がされていない

2023-06-14 07:18 UTC, yuki-takei commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +      isEmailSent: false,
一度メール送信が正常に終わって、モーダルを再度開いた時の state も考慮されてる？

2023-06-14 07:20 UTC, yuki-takei commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +        )}
送ってる最中の spinner とか、その間の disabled はどう制御してるの？

2023-06-21 01:17 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +        )}
ボタン押下後、disabledにし、スピナーを表示した後にメール送信処理が実行されるようにしました

2023-06-21 01:26 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +      isEmailSent: false,
モーダルを再度開く場合は、再度パスワードリセットが必要で、`isEmailSent`はfalseになります。
なので、モーダルを閉じて再度開かない限りはtrueのままになります。

2023-06-23 08:40 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +      this.setState({ isEmailSent: true });
catchした場合はisEmailSentをfalseにすることで対応しました

2023-06-23 08:48 UTC, soumaeda commented
ボタンを押下後、ボタンがdisabledになり、スピナーが表示されるように追加修正しました。
UIUXについても相談済みです。
https://wsgrowi.slack.com/archives/C0111HG81GB/p1687232422036569?thread_ts=1686278525.533409&cid=C0111HG81GB


https://wsgrowi.slack.com/files/U055544K335/F05DMN2ETL1/_____________2023-06-20_12.38.43.mov

2023-06-23 09:23 UTC, jam411 requested changes

2023-06-23 09:23 UTC, jam411 commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
> +    }
useState で初期化されるとはいえこのほうが安全ですね。

2023-06-23 09:23 UTC, jam411 commented on apps/app/public/static/locales/ja_JP/admin.json
> +  "Done": "完了",
commons.json にあるものを転用して、なければ commons.json に置くようにしてそこから使うようにしてほしいです。

2023-06-23 09:23 UTC, jam411 commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
>          </button>
- `onClick={isEmailSent ? undefined : this.onClickSendNewPasswordButton}` は disabled で制御しているので条件分岐させる必要はない気がします。確認お願いします。

- 三項演算子が使えそうです。
### before
```
{isEmailSending && <i className='fa fa-spinner fa-pulse mx-2' />}
{!isEmailSending && (isEmailSent ? t('Done') : t('Send'))}
```
### after
```
{isEmailSending ? <i className='fa fa-spinner fa-pulse mx-2'/> : (isEmailSent ? t('Done') : t('Send'))
```
`(isEmailSent ? t('Done') : t('Send'))` は括弧なしでも期待通り動かないか試してほしいです。

2023-06-26 02:04 UTC, soumaeda commented on apps/app/src/components/Admin/Users/PasswordResetModal.jsx
>          </button>
lintエラーが発生してしまい、ネストされた 3 項式は推奨されていないようでした
https://eslint.org/docs/latest/rules/no-nested-ternary

2023-06-26 02:05 UTC, soumaeda commented on apps/app/public/static/locales/ja_JP/admin.json
> +  "Done": "完了",
commons.jsonに追加しました

2023-06-26 02:55 UTC, jam411 approved these changes

2023-06-28 08:59 UTC, merged