imprv: Can be deleted even on the grant pages
weseek/growi pull request #7811
Opened 2023-06-15 02:13 UTC by jam411

task: https://redmine.weseek.co.jp/issues/124592

2023-06-19 09:00 UTC, jam411 commented on apps/app/src/server/service/page.ts
>          user,
ここの user 引数が required なので引数から user オブジェクトを渡すようにしています。

2023-06-20 06:56 UTC, yuki-takei requested changes

2023-06-20 06:56 UTC, yuki-takei commented on apps/app/src/server/service/page.ts
>          user,
user をオプショナルにしよう

2023-06-20 06:56 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/users.js
> +        crowi.pageService.deleteCompletelyUserHomeBySystem(req.user, userHomepagePath);
引数に user は入れない

2023-06-20 07:43 UTC, jam411 commented on apps/app/src/server/routes/apiv3/users.js
> +        crowi.pageService.deleteCompletelyUserHomeBySystem(req.user, userHomepagePath);
修正しました。

2023-06-20 07:43 UTC, jam411 commented on apps/app/src/server/service/page.ts
>          user,
修正しました。

2023-06-20 07:44 UTC, jam411 commented on apps/app/src/server/events/user.ts
> +    if (page != null && page.creator != null && page.creator.toString() !== user._id.toString()) {
page を undefined の場合もはじくようにしました。

2023-06-20 07:44 UTC, jam411 commented on apps/app/src/server/models/page-operation.ts
> +  user: { type: userSchemaForResuming },
optional にしました。

2023-06-20 09:11 UTC, jam411 commented on apps/app/src/server/models/page-operation.ts
> +  user: { type: userSchemaForResuming },
required に再修正

2023-06-20 12:26 UTC, merged