Feat/120030 124384 exec ldap group sync
weseek/growi pull request #7816
Opened 2023-06-18 11:49 UTC by arafubeatbox

2023-06-18 11:53 UTC, arafubeatbox commented on apps/app/src/server/routes/login-passport.js
> -
external user group 関連のコードでも使えるように external-account.js に分離

2023-06-21 06:07 UTC, jam411 requested changes

2023-06-22 08:41 UTC, arafubeatbox commented on apps/app/src/components/Admin/UserGroup/ExternalUserGroup/LdapGroupSyncSettingsForm.tsx
>      }
直しました。
ちなみに、api の validation にはほぼほぼ exists のチェックだけで、form には required をつけているため、api に到達する前に html で弾かれると思っていましたが、どういう場合に 400 が起こりますか？

2023-06-22 08:41 UTC, arafubeatbox commented on apps/app/src/components/Admin/UserGroup/ExternalUserGroup/LdapGroupSyncSettingsForm.tsx
>      }
あ、下に書いてありましたねm(_ _)m

2023-06-22 15:02 UTC, arafubeatbox commented on apps/app/src/components/Admin/UserGroup/ExternalUserGroup/LdapGroupSyncSettingsForm.tsx
>      }
ありがとうございます、対応しました。

2023-06-27 04:15 UTC, jam411 commented on apps/app/src/server/routes/apiv3/external-user-group.ts
> +      const ldapUserGroupSyncService = new LdapUserGroupSyncService(crowi, req.user.name, req.body.password);
これもインスタンス生成ここでしないように実装できないか一度考えてみてほしいです。

2023-06-27 04:15 UTC, jam411 commented on apps/app/src/interfaces/external-user-group.ts
> +  ldapGroupMembershipAttributeType: 'DN' | 'UID'
`'DN' | 'UID'` も interface として切り出してください。

2023-06-27 15:38 UTC, arafubeatbox commented on apps/app/src/server/routes/apiv3/external-user-group.ts
> +      const ldapUserGroupSyncService = new LdapUserGroupSyncService(crowi, req.user.name, req.body.password);
ユーザごとに異なる username と password を`apps/app/src/server/crowi/index.js` での初期化時に渡すのは無理で、となると初期化後の ldapUserGroupSyncService に対してここで `setupBindUserInfo(req.user.name, req.body.password)` みたいなメソッドを別途実行することになりますが、これを `ldapUserGroupSyncService.syncExternalUserGroups()` 実行の前に実行を強制することが必要となります。

しかし、`syncExternalUserGroups` は LdapUserGroupSyncService の親 class である ExternalUserGroupSyncService のメソッドであるため、この強制を行うためには ExternalUserGroupSyncService に LdapUserGroupSyncService のロジックが食い込むという歪な形になると思っています。

結果として、LdapUserGroupSyncService の constructor で username password を渡す（つまり api 内でインスタンス生成する）のが一番綺麗かな、と思ってしまったのですが、どうでしょうか？

https://github.com/weseek/growi/pull/7816#discussion_r1243882504
にも書いたように、crowi に singleton としてインスタンスを所属させるメリットをあまり理解できていない節があるので、もし何か見落としていたら教えていただきたいですm(_ _)m

2023-06-28 02:49 UTC, jam411 commented on apps/app/src/server/routes/login-passport.js
> +  const externalAccountService = new ExternalAccountService(crowi);
ご意見いただけてすごく助かります 🙏

GROWI としては service は crowi でアクセスする方針になっています。
個人的には crowi に所属させることよりもシングルトン的になるのがメリットだと思っていて、
config-manager のように vitest の導入にあたって crowi 依存から外す流れがあります。参照: https://github.com/weseek/growi/pull/7752 （まだ依存性を残していますが）
@yuki-takei つっこみあればお願いします。

より良い設計にするために聞きたいのですが、
反対に externalAccountService を必要な場所で初期化したほうがメリットは多そうですか？
それともシングルトン的にすることの恩恵がすくないならそうしなくてもいいのでは？といったところでしょうか。

2023-06-28 02:59 UTC, jam411 commented on apps/app/src/server/routes/login-passport.js
> +  const externalAccountService = new ExternalAccountService(crowi);
GROWI としては service は crowi でアクセスする方針になっています。
個人的には crowi に所属させることよりもシングルトン的になるのがメリットだと思っていて、
確かに config-manager のように vitest の導入にあたって crowi 依存から外す流れがあります。参照: https://github.com/weseek/growi/pull/7752 （まだ依存性を残していますが）
@yuki-takei つっこみあればお願いします。

より良い設計にするために聞きたいのですが、
反対に externalAccountService を必要な場所で初期化したほうがメリットは多そうですか？
それともシングルトン的にすることの恩恵がすくないならそうしなくてもいいのでは？といったところでしょうか。

2023-06-28 03:06 UTC, jam411 commented on apps/app/src/server/routes/apiv3/external-user-group.ts
> +      const ldapUserGroupSyncService = new LdapUserGroupSyncService(crowi, req.user.name, req.body.password);
ありがとうございます。いいと思います。

2023-06-28 07:03 UTC, yuki-takei commented
features/external-user-group 下にまとめてほしい

2023-06-28 07:27 UTC, yuki-takei requested changes

2023-06-28 07:27 UTC, yuki-takei commented on apps/app/src/server/service/external-account.js
> +  }
- 今後のことも考えて、新規サービスクラスは可能な限り crowi インスタンスへの依存を外してほしい
- TS にしてほしい
    - 既存メソッドの移植なので any が多くなるのはやむなし

2023-06-28 07:27 UTC, yuki-takei commented on apps/app/src/server/service/external-account.js
> +    const ExternalAccount = this.crowi.model('ExternalAccount');
- `crowi.model(...)` は、`mongoose.model(...)` に置き換える
    - 利用タイミングがモデルの初期化タイミングより遅ければ問題は起こらないはずなので、ここで `mongoose.model` すれば大丈夫なはず

2023-06-28 07:27 UTC, yuki-takei commented on apps/app/src/server/service/external-account.js
> +    const isSameEmailTreatedAsIdenticalUser = this.crowi.passportService.isSameEmailTreatedAsIdenticalUser(providerId);
- 理想的には PassportService からも crowi 依存を外し、configManager のようにモジュールから直接インポートしたい
    - 現状の PassportService のコードを見る限り configManager 利用が多いので、これは簡単にリファクタできる
    - 残るは appService と s2sMessagingService だが、これは剥がすのは難しそう…
- 妥協案として、このサービスが依存する passportService インスタンスを constructor で入れるという手はどうか
    - 根本解決ではないが、DI が限定的になるのでまだましになる

2023-06-28 07:27 UTC, yuki-takei commented on apps/app/src/server/service/external-group/external-user-group-sync-service.ts
> +  }
- 今後のことも考えて、新規サービスクラスは可能な限り crowi インスタンスへの依存を外してほしい

2023-06-28 07:27 UTC, yuki-takei commented on apps/app/src/server/service/external-group/external-user-group-sync-service.ts
> +        return this.crowi.externalAccountService.getOrCreateUser(userInfo, this.authProviderType);
ここを configManager と同じく、直接インポートしたインスタンスを使いたいので、以下のようなギミックにしてはどうか。

1. external-account.js 側では、以下を named export する
    - `function instanciate(passportService: PassportService): void`
        - `crowi/index.js` はこれを使ってインスタンスを作るが、ただし crowi は参照を持たない
    - `externalAccount`
        - instanciate で作られたインスタンスはモジュール内で保持し、`externalAccount` で取得できるようにする
        - このサービスではこれをインポートして使う
        - instanciate 呼び出し前の場合は undefined の可能性もあるが致し方ない

2023-06-28 07:27 UTC, yuki-takei commented on apps/app/src/server/service/external-group/ldap-user-group-sync-service.ts
> +  }
今後のことも考えて、新規サービスクラスは可能な限り crowi インスタンスへの依存を外してほしい

2023-06-28 07:28 UTC, yuki-takei commented on apps/app/src/server/routes/login-passport.js
> +  const externalAccountService = new ExternalAccountService(crowi);
サービス層の在り方として、シングルトンにはしたい。が、crowi インスタンスで一元管理からは脱却したい。

そのための工夫(案)をコメントしたので、一旦検討してほしい。工数が大きかったり影響範囲が広くなりすぎて破綻するようなら無理はしなくていい。

2023-06-28 07:31 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/external-user-group.ts
> +      const ldapUserGroupSyncService = new LdapUserGroupSyncService(crowi, req.user.name, req.body.password);
`LdapUserGroupSyncService` はここでしか使わないならインスタンス化してもいい気はする。Ts.ED で言うところの instance scoped service みたいな扱いだと思えば。
https://tsed.io/docs/injection-scopes.html#instance-scope

2023-06-28 07:40 UTC, yuki-takei requested changes

2023-06-28 07:40 UTC, yuki-takei commented on apps/app/src/server/models/external-user-group-relation.ts
> +export default getOrCreateModel<ExternalUserGroupRelationDocument, ExternalUserGroupRelationModel>('ExternalUserGroupRelation', schema);
vitest + mongodb-memory-server でテストを書きたい

- vitest.config.integ.ts により、`*.integ.ts` は上記を使うようにセットアップされている
- 既にあるテストは acl.integ.ts だけだが少しは参考にはなるかと
    - ただここ数日で tsconfig の "vitest/globals" が効かなくなってるのが書きにくいかも…
    - ![image](https://github.com/weseek/growi/assets/1638767/efdaa2dd-268c-4325-9008-bb242f983de3)

2023-06-28 07:40 UTC, yuki-takei commented on apps/app/src/server/models/external-user-group.ts
> +export default getOrCreateModel<ExternalUserGroupDocument, ExternalUserGroupModel>('ExternalUserGroup', schema);
vitest + mongodb-memory-server でテストを書きたい

2023-06-29 13:32 UTC, arafubeatbox commented on apps/app/src/server/service/external-account.js
> +    const ExternalAccount = this.crowi.model('ExternalAccount');
https://github.com/weseek/growi/blob/5069948b62a2fb228979a1cea9a198616f862d6e/apps/app/src/server/models/page.ts#L311
独自に定義した static method があるので、それを使う際の TS エラーを避けるために一旦上記のように any で定義する形になりますかね。

2023-06-29 13:33 UTC, arafubeatbox commented on apps/app/src/server/service/external-account.js
> +    const isSameEmailTreatedAsIdenticalUser = this.crowi.passportService.isSameEmailTreatedAsIdenticalUser(providerId);
方針提示ありがとうございます。妥協案で実装したので、passport service の configManager のリファクタは行っていません（master とのコンフリクトを避けるという意味でも）

2023-06-29 23:17 UTC, arafubeatbox commented on apps/app/src/server/service/external-group/external-user-group-sync-service.ts
> +        return this.crowi.externalAccountService.getOrCreateUser(userInfo, this.authProviderType);
```
// eslint-disable-next-line import/no-mutable-exports
export let externalAccountService: ExternalAccountService | undefined; // singleton instance
export function instanciate(passportService: PassportService): void {
  externalAccountService = new ExternalAccountService(passportService);
}
```

という風に書きました。let にすると mutable export になり eslint の no-mutable-exports エラーが出てしまうため、切っています。
crowi.externalAccountService にも instanciate されたインスタンスを代入するようにしました。

2023-06-29 23:22 UTC, arafubeatbox commented on apps/app/src/server/models/external-user-group-relation.ts
> +export default getOrCreateModel<ExternalUserGroupRelationDocument, ExternalUserGroupRelationModel>('ExternalUserGroupRelation', schema);
https://redmine.weseek.co.jp/issues/124934 で行おうと思います。

2023-06-29 23:22 UTC, arafubeatbox commented on apps/app/src/server/models/external-user-group.ts
> +export default getOrCreateModel<ExternalUserGroupDocument, ExternalUserGroupModel>('ExternalUserGroup', schema);
https://redmine.weseek.co.jp/issues/124934 で行おうと思います。

2023-06-29 23:34 UTC, arafubeatbox commented on apps/app/src/server/service/external-group/external-user-group-sync-service.ts
> +        return this.crowi.externalAccountService.getOrCreateUser(userInfo, this.authProviderType);
余談）
ts.ed 化すると、DI が有効になって、crowi を使った singleton の表現と instanciate が不要になるんですかね。

2023-06-29 23:38 UTC, arafubeatbox commented on apps/app/src/server/service/external-group/external-user-group-sync-service.ts
> +        return this.crowi.externalAccountService.getOrCreateUser(userInfo, this.authProviderType);
これって、武井さんの
> crowi インスタンスで一元管理からは脱却したい。

のコメントを参照する限り、crowi.externalAccountService も無くした方が良い感じですかね？
脱却の方法として instanciate が今後主流になるかはわからないですが。

2023-06-29 23:41 UTC, arafubeatbox commented on apps/app/src/server/routes/login-passport.js
> +  const externalAccountService = new ExternalAccountService(crowi);
> 反対に externalAccountService を必要な場所で初期化したほうがメリットは多そうですか？
> それともシングルトン的にすることの恩恵がすくないならそうしなくてもいいのでは？といったところでしょうか。

メリットが薄いまま、crowi という object 自体が肥大化するのに抵抗がある、という程度でした。

> サービス層の在り方として、シングルトンにはしたい。が、crowi インスタンスで一元管理からは脱却したい。

武井さんのこちらのコメントで納得しましたm(_ _)m

2023-06-30 00:20 UTC, arafubeatbox commented
> features/external-user-group 下にまとめてほしい

client 側に関しては https://github.com/weseek/growi/pull/7833 との conflict が結構ありそうなので、7833 上で対応します。

2023-07-03 12:00 UTC, yuki-takei commented on apps/app/src/server/service/external-group/external-user-group-sync-service.ts
> +        return this.crowi.externalAccountService.getOrCreateUser(userInfo, this.authProviderType);
> ts.ed 化すると、DI が有効になって、crowi を使った singleton の表現と instanciate が不要になるんですかね。

そう。さらに依存関係にあるサービスインスタンスの初期化順とかもフレームワークがやってくれるようになる。


> これって、武井さんの
> 
>     crowi インスタンスで一元管理からは脱却したい。
> 
> のコメントを参照する限り、crowi.externalAccountService も無くした方が良い感じですかね？

できるなら。


> 脱却の方法として instanciate が今後主流になるかはわからないですが。

Ts.ED 化前の状態としては、以下の中間状態を目指す、でよいと思っている。

1. class の export (これは一旦 named export でも default export でもどちらでもいい)
2. module 内でインスタンス化してそれを export するなり、今回のように factory method を用意してそれを export するなり
3. 利用側は crowi object を介さず、「2.」で用意されたものをインポート

将来的に DI できるフレームワークを採用した暁には、2 のコードを消し、3の利用部分を DI 対応コードに置き換える
https://github.com/weseek/growi/blob/master/apps/slackbot-proxy/src/controllers/slack.ts#L76-L101

2023-07-03 12:05 UTC, yuki-takei requested changes

2023-07-03 12:05 UTC, yuki-takei commented on apps/app/src/stores/external-user-group.ts
このファイルも features 下でいいかな。

2023-07-04 03:24 UTC, arafubeatbox commented on apps/app/src/server/service/external-group/external-user-group-sync-service.ts
> +        return this.crowi.externalAccountService.getOrCreateUser(userInfo, this.authProviderType);
了解です。今後も中間状態をなるべく作るようにしますm(_ _)m

2023-07-04 03:36 UTC, merged