imprv: presentation style preview
weseek/growi pull request #7817
Opened 2023-06-19 02:29 UTC by reiji-h

# Task
https://redmine.weseek.co.jp/issues/115674

# 変更点まとめ
- frontmatter に presentation: true があった際 preview にスライドで描画されるように変更
- 変更された後 frontmatter を消す処理はこの PR にはない。
- preview のスライドのスタイルについては改善の余地あり

2023-06-27 03:13 UTC, jam411 commented on apps/app/src/components/Page/PageView.tsx
> +        <RevisionRenderer rendererOptions={rendererOptions} markdown={markdown} isSlidesOverviewEnabled={true}/>
true するだけなら `isSlidesOverviewEnabled` と宣言するだけでできます。

```
<RevisionRenderer rendererOptions={rendererOptions} markdown={markdown} isSlidesOverviewEnabled />
```

2023-06-27 03:13 UTC, jam411 commented on apps/app/src/components/Page/PageView.tsx
> +        <RevisionRenderer rendererOptions={rendererOptions} markdown={markdown} isSlidesOverviewEnabled={true}/>
PR の説明には` preview にスライドで描画される`
とありましたが View にしか表示されませんでした。
Preview に表示するには Preview.tsx の RevisioinRenderer に渡す必要がある?

2023-06-28 04:44 UTC, jam411 commented on packages/presentation/src/components/Slides.tsx
> +  }
今後実装する箇所には TODO コメントとタスク URL を書いておいてください.

例：
```
TODO: Marp でレンダリングできる
https://redmine.weseek.co.jp/issues/115673
```

2023-06-28 04:44 UTC, jam411 commented on packages/presentation/src/components/Slides.tsx
> +`);
このあたりにテーマが追加されるなら

2023-06-28 05:12 UTC, jam411 commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +  }, [markdown, setSlideStyle]);
こんな感じにできないか確認してほしいです。

```
useEffect(() => {
  const processMarkdown = (tree) => {
    setSlideStyle(null);

    visit(tree, 'yaml', (node) => {
      if (node.value == null) {
        const lines = node.value.split('\n');

        lines.forEach((line) => {
          const [key, value] = line.split(':').map(part => part.trim());

          if (key === 'presentation') {
            setSlideStyle(value === 'marp' || value === 'true' ? value : null);
          }
          else if (key === 'marp' && value === 'true') {
            setSlideStyle('marp');
          }
        });
      }
    });
  };

  unified()
    .use(remarkParse)
    .use(remarkStringify)
    .use(remarkFrontmatter, ['yaml'])
    .use(processMarkdown)
    .process(markdown);
}, [markdown, setSlideStyle]);
```

2023-06-28 10:32 UTC, jam411 requested changes

2023-06-28 10:32 UTC, jam411 commented on packages/presentation/src/components/Slides.tsx
> +`);
伝え忘れていました。コメントは英語でお願いします。

2023-06-28 10:32 UTC, jam411 commented on packages/presentation/src/components/Slides.tsx
> +  }
申し訳ない。こちらも

> 伝え忘れていました。コメントは英語でお願いします

2023-06-28 10:32 UTC, jam411 commented on packages/presentation/src/interfaces/index.ts
> +export type presentationSlideStyle = 'true' | 'marp' | null;
style としては `true` か `marp` なはずなので、ここで null を明示しなくてもいいと思います。
props のように useState 側で nullable にするように統一してほしいです。

2023-06-28 10:32 UTC, jam411 commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +  const [slideStyle, setSlideStyle] = useState<presentationSlideStyle>(null);
`useState<presentationSlideStyle | null>();` こうしてみましょう

2023-06-28 10:32 UTC, jam411 commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +  }, [markdown, setSlideStyle]);
条件式を追加して isSlidesOverviewEnabled が true のときだけ useEffect 内の処理を実行するようにしたいと思ったんですが、通常 `/workspace/growi/apps/app/src/client/services/renderer/renderer.tsx` では unified 処理を毎回実行しているのか。
でも、Preview と View だけ実行したいから条件分岐させるのでいいか。
よさそうであれば修正してほしいです。

2023-06-28 10:32 UTC, jam411 commented on packages/presentation/src/interfaces/index.ts
> +export type presentationSlideStyle = 'true' | 'marp' | null;
`'true' | 'marp'` を定数として使うのはどうでしょうか？
参考にしてみてください, `/workspace/growi/apps/app/src/features/questionnaire/interfaces/growi-info.ts`

2023-06-29 09:48 UTC, jam411 commented on packages/presentation/src/components/Slides.tsx
> +
細かいけどこうゆう改行も気を付けるようにしたほうがいと思う。

2023-06-29 09:48 UTC, jam411 commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +                setSlideStyle('marp');
set するところだけ SLIDE_STYLE を使っては？

2023-06-29 09:48 UTC, jam411 commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +                setSlideStyle(value === 'marp' || value === 'true' ? value : null);
口頭で話した内容:
```
---
presentaion: ture
---

---
presentaion: marp
---

---
marp: ture
---
```

とする理由と、
`presentation: marp` で `theme:` や `size:` などがわたってきた場合の処理がいけそうか確認しておいてください。

2023-06-29 09:48 UTC, jam411 commented on packages/presentation/src/interfaces/index.ts
> +export const SLIDE_STYLE = { true: 'true', marp: 'marp' } as const;
true だとわかりにくいので、できれば style の名前を決めておきたいです。
```
presentation: true
presentation: marp
marp: ture
```
があって、 presentation: marp と marp: true が同じなら, slide style は `growi_presentaion | marp` とかになるんですかね?
口頭で話した内容をもとに武井さんと話して、できるのであればいい感じの命名を考えてみてください。

2023-07-03 04:25 UTC, reiji-h commented
# 変更の概要
以下の方法でスライド表示をするようにする
- frontmatter に次の文言が含まれているときに 挙動を変更する
  - slide: true の時 スライド表示。
  - marp: true の時 slide: true でも marp のスライド表示。

なお、この PR では次のことは**行っていない**
- marp でのスライド表示
- スライドの見た目を整えること

2023-07-03 04:50 UTC, jam411 approved these changes

2023-07-03 12:34 UTC, yuki-takei requested changes

2023-07-03 12:34 UTC, yuki-takei commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +  }, [markdown, setHasSlideFlag, setHasMarpFlag, isSlidesOverviewEnabled]);
- この useEffect 内の remark plugin は別モジュールとして外に出す
- この remark plugin を使うかどうかは `src/client/services/renderer/renderer.tsx` の責務で、 `generateViewOptions` と `generatePreviewOptions` にのみ登録されていればいいはず(たぶん)

2023-07-03 12:34 UTC, yuki-takei commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +  }
- また、`<Slides />` のレンダリングも、ここで条件分岐させるのではなく ReactMarkdown にやらせるべきなので、同様に `src/client/services/renderer/renderer.tsx` の `// add components` コメント付近を確認
    - rehype plugin で slides element を作る
    - ryoji-s がやっていた attachment element -> RichAttachment component レンダリングが参考になるはず

2023-07-12 04:48 UTC, reiji-h commented
# 変更の概要
- remark-plugin 等の追加により RevisionRenderer へのコードの変更なしに スライドの見た目のプレビューを可能にする
- slide.ts ... remark plugin。mdast の tree node と children node の間に新しい Node を追加
- SlideViewer.tsx ... 追加された Node に対しコンポーネントによる置き換えを行う。(直接 Root の置き換えが不可能なため)
# 別 PR で行うこと
- スライドの見た目を整える
- marp 実装
- remark-growi-directive の対応

2023-07-12 07:11 UTC, jam411 requested changes

2023-07-12 07:11 UTC, jam411 commented on apps/app/package.json
> +>>>>>>> imprv/115672-presentation-preview
conflict 解消したときのものがのこちゃってます

2023-07-12 07:11 UTC, jam411 commented on apps/app/src/components/ReactMarkdownComponents/SlideViewer.tsx
> +      }}>{children}</Slides>
細かいですが　attribute をそろえてほしいです。:pray:
```
<Slides 
  hasMarpFlag={marp === 'marp'}
  options={{ rendererOptions: rendererOptions as ReactMarkdownOptions }}
>
  {children}
</Slides>
```

2023-07-18 03:36 UTC, jam411 reviewed
`Dependency cycle via ~ eslint[import/no-cycle](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-cycle.md)`
エラーを解決するタスクを作っておいてください。

2023-07-18 03:36 UTC, jam411 commented on apps/app/src/services/renderer/remark-plugins/slides.ts
> +      marp: marp ? 'marp' : '',
boolean でいいんじゃないですかね？
今後拡張する予定があるならこれでもいいと思います。

2023-07-24 11:44 UTC, yuki-takei requested changes

2023-07-24 11:44 UTC, yuki-takei commented on apps/app/src/services/renderer/remark-plugins/slides.ts
このファイルは packages/presentation 配下に移してほしい

2023-07-27 21:43 UTC, yuki-takei requested changes

2023-07-27 21:43 UTC, yuki-takei commented on packages/presentation/package.json
> +    "mdast-util-to-markdown": "1.3.0"
- mdast-util-* は devDependencies に移してください
- バージョン指定を全て `^*.*.*` という形式にしてください
    - それでは問題がある場合は相談して

なお、FB の thread は自分で resolved にせず unresolved のままにしておいてください(解決したとみなしたらレビュアーが resolve する)

2023-07-27 21:43 UTC, yuki-takei commented on packages/presentation/src/components/Slides.tsx
> +      </div>
ここの変更必要？変な辻褄の合わせ方をしていないだろうか…

2023-07-31 08:50 UTC, merged