fix: SSL connection error to Elasticsearch8 using self certificate
weseek/growi pull request #7818
Opened 2023-06-19 03:48 UTC by miya

## Task
[#124348](https://redmine.weseek.co.jp/issues/124348) [elasticsearch] Issue 対応
└ [#124349](https://redmine.weseek.co.jp/issues/124349) 修正

2023-06-19 11:47 UTC, yuki-takei requested changes

2023-06-19 11:47 UTC, yuki-takei commented on apps/app/src/server/service/search-delegator/elasticsearch.ts
> +      : { tls: { rejectUnauthorized: elasticsearchRejectUnauthorized } };
差異は elasticsearch-client.ts で吸収

2023-06-20 04:35 UTC, miya commented on apps/app/src/server/service/search-delegator/elasticsearch.ts
> +      : { tls: { rejectUnauthorized: elasticsearchRejectUnauthorized } };
修正しました

2023-06-20 04:44 UTC, miya commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +    });
- elasticsearch-client の中で初期化するようにしました
- `elasticserch === elasticsearch7` の比較方法が良くない場合は ElasticsearchDelegator から isElasticsearchV7 を引数で渡すようにしようと思います

2023-06-20 07:11 UTC, yuki-takei requested changes

2023-06-20 07:11 UTC, yuki-takei commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +    });
あんまりよくないね。

というか、第一引数に来ている elasticsearch インスタンスすらカプセル化したいのはある。

そして第二引数のオプションも独自にタイプを定義し直す他ないのでは？ES7Client のオプションと ES8Client のオプションに互換性がないわけなので。

2023-07-03 05:00 UTC, miya commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +    });
- elasticsearch インスタンスを elasticsearch-client の中で初期化するように修正しました
- 第二引数の option も ES7ClientOptions | ES7ClientOptions といったように型付けしました

2023-07-03 05:15 UTC, miya commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +      this.client = new ES8Client(esOptions as ES8ClientOptions);
第一引数から ES7 判定できる boolean を受け取り elasticsearch-client.ts 内で初期化できるようにした

2023-07-03 05:15 UTC, miya commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +};
- ElasticSearch7 の option かどうかチェックする Type guard (冗長かもしれませんが..)
- どちらにせよ ElasticsearchClient の第二引数が `ES7ClientOptions | ES8ClientOptions` となっている為、ES7Client or ES8Client 初期化時に Type guard や Type assertion をする必要がありそうです

2023-07-03 12:51 UTC, yuki-takei requested changes

2023-07-03 12:51 UTC, yuki-takei commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +  constructor(isES7: boolean, options: ES7ClientOptions | ES8ClientOptions, rejectUnauthorized: boolean) {
- constructor は 2 種を overload で実装する
    - `(options: ES7ClientOptions, rejectUnauthorized = false)`
    - `(options: ES8ClientOptions, rejectUnauthorized = false)`
- type guard が活きると思う

2023-07-03 12:51 UTC, yuki-takei commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +      this.client = new ES8Client(esOptions as ES8ClientOptions);
constructor を改修して type guard を通せば、`as` は消せるはず

2023-07-04 01:09 UTC, miya commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +  constructor(isES7: boolean, options: ES8ClientOptions, rejectUnauthorized: boolean)
- es7, es8 の constructor の overload を追加

2023-07-04 01:09 UTC, miya commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +      this.client = new ES8Client(esOptions);
- overload を追加しても、`ES7ClientOption | ES8ClientOption` という型のままだった
- esOption 変数に型付けをすることで as を消せた
- overload は elasticsearch-client を使う側としてはあっても良さそうだったので残しています

2023-07-04 01:09 UTC, miya commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +  constructor(isES7: boolean, options: ES7ClientOptions | ES8ClientOptions, rejectUnauthorized: boolean) {
修正しました

2023-07-04 14:21 UTC, yuki-takei requested changes

2023-07-04 14:21 UTC, yuki-takei commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +  constructor(...params: ElasticsearchClientParams) {
結局オーバーロードはなくした。
代わりに Union 型にした ElasticsearchClientParams を受け取り、`isES7` を評価することで options がどちらかに定まるという方式にした。

2023-07-04 14:21 UTC, yuki-takei commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +  constructor(...params: ElasticsearchClientParams) {
```
// Type guard for ES7ClientOptions
const isES7Options = (options: any): options is ES7ClientOptions => {
  return options.ssl != null;
};
```

これがなんで良くないかというと、`options.ssl` に値が入ってなければ false が返るので。つまり仮に `options: any` が空オブジェクトであれば、`isES7` が true だろうが false だろうが true が返る。

2023-07-04 14:21 UTC, yuki-takei commented on apps/app/src/server/service/search-delegator/elasticsearch-client.ts
> +      : new ES8Client({ ...options, tls: { rejectUnauthorized } });
元の object spread syntax
`new ES7Client({ ...options, ...{ ssl: { rejectUnauthorized } } })`
は、後者のオブジェクト作成部分で型チェックが働かないのでよくない。

2023-07-04 14:22 UTC, yuki-takei approved these changes

2023-07-11 04:32 UTC, merged