Imprv: Show spinner after create
weseek/growi pull request #7821
Opened 2023-06-19 09:30 UTC by soumaeda

https://redmine.weseek.co.jp/issues/124844

2023-06-20 04:45 UTC, jam411 commented
@soumaeda
2023-06-20.13.29.06.mov で `接続しました！` って表示されるのはどんなロジックなんだろう。
個人的にはあってもいいとは思うけれど、ローディング表示できるようになったので消せるなら消したいですね。
検討してみてほしいです。

2023-06-20 04:46 UTC, jam411 commented
@soumaeda 
2023-06-20.13.23.54.mov が途中で切れているようです。

2023-06-20 06:12 UTC, soumaeda commented
後から見返すと、2023-06-20.13.23.54.mov ではページ遷移されるところまで写っていなかったので、2023-06-20.15.02.35.movに変更しました

2023-06-21 01:53 UTC, soumaeda commented
ログインフォームやインストーラーフォームでは、「ログインに成功しました！」などのメーセージは表示されないため、invitedフォームの「接続に成功しました！」は不要と考え、表示しないようにしました。

https://github.com/weseek/growi/assets/112812878/8c97fa06-5d71-470f-9fe1-56afe555ac27

2023-06-21 02:03 UTC, jam411 requested changes

2023-06-21 07:24 UTC, soumaeda commented on apps/app/src/components/InstallerForm.tsx
> +      setSubmittingDisabled(false);
`if (isSubmittingDisabled) {
      return;
    }`と`if (e.target.elements == null) {
      return;
    }`は不要と判断し、削除しました

2023-06-21 07:43 UTC, jam411 commented on apps/app/src/components/InstallerForm.tsx
> +      setSubmittingDisabled(false);
input タグに required attr があるので `if (e.target.elements == null) { return; }` もいらないと理解しました。

2023-06-21 08:16 UTC, jam411 approved these changes
React className 内で条件分岐する箇所をみると [classnames](https://www.npmjs.com/package/classnames) (or clsx) 使ってみたいなという気持ちになったりします。実際いいのか悪いのかわかってない。

2023-06-21 12:19 UTC, merged