Feat/123277 125405 external user group index UI
weseek/growi pull request #7833
Opened 2023-06-25 14:34 UTC by arafubeatbox

2023-06-27 05:44 UTC, jam411 commented on apps/app/src/stores/external-user-group.ts
> +export const useSWRxAncestorExternalUserGroups = (groupId: string | undefined): SWRResponse<IExternalUserGroupHasId[], Error> => {
細かいですが `groupId?: string` でいいかもです。

2023-06-27 05:44 UTC, jam411 commented on apps/app/src/components/Admin/UserGroup/ExternalUserGroup/ExternalUserGroupManagement.tsx
> +      setDeleteModalShown(false);
`hideDeleteModal()` が使えそうです。

2023-06-27 05:44 UTC, jam411 commented on apps/app/src/components/Admin/UserGroup/ExternalUserGroup/ExternalUserGroupManagement.tsx
> +      isExternalGroup={true}
true を渡すだけならプロップス名 `isExternalGroup` のみ渡すだけでよさそうです。

2023-06-27 05:44 UTC, jam411 commented on apps/app/src/server/models/external-user-group-relation.ts
> +  }
型チェック必要ですかね？
型チェックはできればTSの責務にしたいです。

2023-06-27 05:44 UTC, jam411 commented on apps/app/src/server/models/external-user-group-relation.ts
> +  }
なるほど既存コードがそうなっているのか

2023-06-27 05:44 UTC, jam411 commented on apps/app/src/server/models/external-user-group.ts
> +  }
これもできればやりたくないですね。Array 以外が入ってくる可能性があるのか

2023-06-27 05:44 UTC, jam411 commented on apps/app/src/server/models/user-group.ts
>    }
既存コード, parentIds の型が array じゃない場合があるのか

2023-06-27 05:44 UTC, jam411 commented on apps/app/src/server/routes/apiv3/external-user-group.ts
> +      return res.apiv3({ userGroupRelations });
`serializeUserGroupRelationSecurely` は不要でしょうか？

2023-06-27 05:44 UTC, jam411 commented on apps/app/src/server/routes/apiv3/external-user-group.ts
serialize が必要な個所がないか確認してほしいです。

2023-07-01 08:44 UTC, arafubeatbox commented on apps/app/src/server/routes/apiv3/external-user-group.ts
> +      return res.apiv3({ userGroupRelations });
必要そうですね。user-group.js の方にも追加しました。

2023-07-01 08:56 UTC, arafubeatbox commented on apps/app/src/server/models/user-group.ts
>    }
呼び出されているのが API のみで、API では array かどうかを express-validator でチェックしているので、不要そうです🙏

2023-07-01 09:01 UTC, arafubeatbox commented on apps/app/src/server/models/external-user-group-relation.ts
> +  }
Array の型に限定して良さそうだったので、TS として新設した external-user-group-relation.ts ではそうしました。

2023-07-01 09:07 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/models/external-user-group.ts
> +schema.statics.findGroupsWithDescendantsRecursively = UserGroup.findGroupsWithDescendantsRecursively;
相談なのですが、mongoose の UserGroup の model の static メソッドを丸ごとコピーすることで正常に動くようなのですが、これは許容でしょうか？

mongoose 的には schema の継承はされていないのですが、interface は IUserGroup を継承しているので、基本的に UserGroup でできることは ExternalUserGroup でできるという認識です。

2023-07-01 09:09 UTC, arafubeatbox commented
各ファイルを features/external-user-group 配下に移動しました。

2023-07-03 04:13 UTC, jam411 commented on apps/app/src/features/external-user-group/server/models/external-user-group.ts
> +schema.statics.findGroupsWithDescendantsRecursively = UserGroup.findGroupsWithDescendantsRecursively;
こうしても ExternalUserGroup コレクションへの操作になるんですね。

@yuki-takei ご確認お願いします。

2023-07-04 15:01 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/client/components/ExternalUserGroup/ExternalUserGroupManagement.tsx
> +export const ExternalGroupManagement: FC = () => {
features/external-user-group に移動 + UserGroupPage と同様のロジックを追加

2023-07-04 15:01 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/client/components/ExternalUserGroupDetail.tsx
> +const ExternalUserGroupDetailPage = (props: Props): JSX.Element => {
UserGroupDetailPage と同様のロジック

2023-07-04 15:02 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/client/components/ExternalUserGroupDetail.tsx
> +  // const { data: userGroupPages } = useSWRxUserGroupPages(currentExternalUserGroupId, 10, 0);
ページ権限管理は後続タスクで実装

2023-07-05 11:41 UTC, yuki-takei requested changes

2023-07-05 11:41 UTC, yuki-takei commented on apps/app/src/interfaces/user-group-response.ts
> +export type ChildUserGroupListResult<TUSERGROUP = IUserGroupHasId> = {
この辺の総称型は `extends` を使って入れられるものを限定してほしい

2023-07-05 11:41 UTC, yuki-takei commented on apps/app/src/features/external-user-group/client/components/ExternalUserGroupDetail.tsx
> +const ExternalUserGroupDetailPage = (props: Props): JSX.Element => {
このファイルって UserGroupDetailPage との共通化難しい？

2023-07-05 11:41 UTC, yuki-takei commented on apps/app/src/components/Admin/UserGroup/UserGroupForm.tsx
> +              />}
ラベルと input の出し分けではなく disabled attribute で

2023-07-05 11:41 UTC, yuki-takei commented on apps/app/src/components/Admin/UserGroup/UserGroupForm.tsx
> +          {isExternalGroup ? <div className="col-md-4 my-auto">{parentUserGroup?.name}</div>
こちらも同様

2023-07-09 05:13 UTC, arafubeatbox commented on apps/app/src/server/service/user-group.ts
> +  async removeCompletelyByRootGroupId(deleteRootGroupId, action, transferToUserGroupId, user, isExternalGroup = false) {
大変参考になりますm(_ _)m

2023-07-09 05:21 UTC, arafubeatbox commented on apps/app/src/server/service/user-group.ts
> +  async removeCompletelyByRootGroupId(deleteRootGroupId, action, transferToUserGroupId, user, isExternalGroup = false) {
対応の過程で models/user-group-relation を TS 化しました。

2023-07-09 07:13 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/client/components/ExternalUserGroupDetail.tsx
> +const ExternalUserGroupDetailPage = (props: Props): JSX.Element => {
if 文地獄になるかと思って共通化してなかったのですが、共通化してみたら案外まとまりました。

変更の commit は以下になります。
https://github.com/weseek/growi/pull/7833/commits/cb7d7303711138ae48c0054d5e10f258a3ee4110

2023-07-09 07:25 UTC, arafubeatbox commented on apps/app/src/server/crowi/index.js
> +  });
crowi.models を確認すると、以下のように、Model として格納されていないものがありました。

```
{
  Page: Model { Page },
  PageTagRelation: Model { PageTagRelation },
  User: Model { User },
  ExternalAccount: Model { ExternalAccount },
  Revision: Model { Revision },
  Tag: { _id: new ObjectId("64aa3a573d1876afbeb5f7b2") },
  Bookmark: Model { Bookmark },
  Comment: Model { Comment },
  Attachment: Model { Attachment },
  GlobalNotificationSetting: Model { GlobalNotificationSetting },
  GlobalNotificationMailSetting: Model { mail },
  GlobalNotificationSlackSetting: Model { slack },
  ShareLink: Model { ShareLink },
  SlackAppIntegration: Model { SlackAppIntegration },
  Activity: { _id: new ObjectId("64aa3a573d1876afbeb5f7b3") },
  UserGroup: { description: '', _id: new ObjectId("64aa3a573d1876afbeb5f7b4") },
  PageRedirect: { _id: new ObjectId("64aa3a573d1876afbeb5f7b6") }
}
```

それらは、crowi に依存しない（コンストラクタに crowi を渡す必要がないもので、setupModels で誤って初期化されていたため、修正しました。

2023-07-10 12:51 UTC, yuki-takei requested changes

2023-07-10 12:51 UTC, yuki-takei commented on apps/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +      }
SWR の返り値にユーティリティとして含めたい。
withUtils, SWRResponseWithUtils というオリジナルのコードがあるので growi リポジトリ内で検索して。

2023-07-10 12:51 UTC, yuki-takei commented on apps/app/src/stores/user-group.tsx
> +export const useSWRxUserGroup = (groupId: string | undefined, isExternalGroup = false): SWRResponse<IUserGroupHasId, Error> => {
UserGroup と ExternalUserGroup は routes もファイルを分けているので、SWR hooks も分けていいと思う。

- 別モジュールである以上は将来的にオプション含め統一されたまま維持されるかどうかわからない
- 現時点でもそのままだと withUtils で apiv3Post する場合も API endpoint を決める if 文ができでしまうが、SWR を分ければそれがなくなってすっきりするのではないか

2023-07-10 12:51 UTC, yuki-takei commented on apps/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
> +      }
因みに SWR に withUtils で含めると違和感のある POST 操作(GET するデータと特に関連のない POST 操作)は、独立したメソッドや hooks として `src/client/services/page-operation.ts` などにまとめている。

2023-07-11 01:31 UTC, arafubeatbox commented on apps/app/src/stores/user-group.tsx
> +export const useSWRxUserGroup = (groupId: string | undefined, isExternalGroup = false): SWRResponse<IUserGroupHasId, Error> => {
https://github.com/weseek/growi/pull/7833/commits/cb7d7303711138ae48c0054d5e10f258a3ee4110 の stores/external-user-group への変更をやめるということだと認識していますが、

例えば useSWRxUserGroup と useSWRxExternalUserGroup の UserGroupDetailPage での呼び出しの場合分けはどのようにするイメージでしたか？

単純に
```typescript
const { data: currentUserGroup } = 
    isExternalGroup ? useSWRxExternalUserGroup(currentUserGroupId) : useSWRxUserGroup(currentUserGroupId, isExternalGroup);
```

のように場合分けすると、
```
React Hook "useSWRxUserGroup" is called conditionally. React Hooks must be called in the exact same order in every component render.
```

と出てしまいまして。

2023-07-11 01:36 UTC, arafubeatbox commented on apps/app/src/stores/user-group.tsx
> +export const useSWRxUserGroup = (groupId: string | undefined, isExternalGroup = false): SWRResponse<IUserGroupHasId, Error> => {
src/client/services に

```typescript
export const useUserGroup = (currentUserGroupId: string, isExternalGroup: boolean): IUserGroupHasId | undefined => {
  const { data: currentUserGroup } = useSWRxUserGroup(currentUserGroupId);
  const { data: currentExternalUserGroup } = useSWRxExternalUserGroup(currentUserGroupId);

  return isExternalGroup ? currentExternalUserGroup : currentUserGroup;
};
```

みたいなメソッドを作るイメージでしょうか。

2023-07-11 01:40 UTC, arafubeatbox commented on apps/app/src/stores/user-group.tsx
> +export const useSWRxUserGroup = (groupId: string | undefined, isExternalGroup = false): SWRResponse<IUserGroupHasId, Error> => {
別に services に分ける必要もないのか。

2023-07-11 13:20 UTC, merged