imprv: Adjust margin between title
weseek/growi pull request #7839
Opened 2023-06-28 09:47 UTC by soumaeda

2023-06-28 10:52 UTC, jam411 requested changes

2023-06-28 10:52 UTC, jam411 commented on apps/app/src/components/PageList/PageListItemS.tsx
> +      <div className="mx-2" style={{ lineHeight: 1.2 }}>
`style={{ lineHeight: 1.2 }}`
できるだけハードコードはやめたいです。まず bootstrap などで代用できないか考えてみてほしいです。

2023-07-03 01:37 UTC, soumaeda commented on apps/app/src/components/PageList/PageListItemS.tsx
> +      <div className="mx-2" style={{ lineHeight: 1.2 }}>
bootstrapで代用できなかったので、scssに記述し、適用するようにしました

2023-07-03 01:43 UTC, soumaeda commented
ページタイトルが3行以上の長さになってしまう場合は、3行目で三点リーダーを表示させるようにしました
https://wsgrowi.slack.com/archives/C0111HG81GB/p1688094176531109?thread_ts=1687845584.207329&cid=C0111HG81GB

<img width="308" alt="スクリーンショット 2023-07-03 10 34 41" src="https://github.com/weseek/growi/assets/112812878/5ed90e33-801a-4a50-a5a5-6be4e82db55e">

2023-07-03 02:21 UTC, jam411 commented on apps/app/src/components/PageList/PageListItemS.tsx
> +      </div>
@soumaeda 
PageListItemS.tsx は bookmarks 以外でも使っているコンポーネントだと思うので使っている箇所を確認して影響がないか確認してほしいです.

2023-07-03 09:35 UTC, soumaeda commented on apps/app/src/components/PageList/PageListItemS.tsx
> +      </div>
確認したところ、他のページへの影響もありましたが、そちらは次タスクhttps://redmine.weseek.co.jp/issues/125692でのスコープにしました。

2023-07-04 01:55 UTC, jam411 requested changes
PageListItemS.tsx を修正せずに、ほかの PageListItemS.tsx を使っているコンポーネントを参照するなどして BookmarkItem.tsx 側を修正することで表現できないか考えてみてほしいです。

2023-07-04 04:41 UTC, soumaeda commented
条件分岐により、PageListItemSコンポーネントをBookmarkItem.tsxでのみscssを適用させた状態で利用できるようにしました

<img width="309" alt="スクリーンショット 2023-07-03 18 13 48" src="https://github.com/weseek/growi/assets/112812878/cecc497d-c9d9-4712-b2c6-970769eecc96">

2023-07-04 05:05 UTC, jam411 requested changes

2023-07-04 05:05 UTC, jam411 commented on apps/app/src/components/PageList/PageListItemS.tsx
> +  let pagePathElement = <PagePathLabel path={path} additionalClassNames={additionalClassNames}/>;
isBookmarkItem が true の時に pagePathElement を書き換えるからこの処理はいらないと思いました。
（なぜ mx-0, mx-2 にしたのかわかってないです）

2023-07-04 06:37 UTC, jam411 commented on packages/ui/src/styles/molecules/_page_list.scss
> +  }
bookmarks 用だとわかるように, `bookmarks-path-element` としてください。
呼び出し側も修正忘れずにお願いします。

2023-07-05 10:13 UTC, yuki-takei requested changes

2023-07-05 10:13 UTC, yuki-takei commented on apps/app/src/components/PageList/PageListItemS.tsx
> +  isBookmarkItem?: boolean,
bookmark に特化した名前の props が入るのは NG

2023-07-05 10:13 UTC, yuki-takei commented on packages/ui/src/styles/molecules/_page_list.scss
> +  .bookmarks-path-element {
bookmark に特化した名前のクラス名は NG

2023-07-05 10:13 UTC, yuki-takei commented on packages/ui/src/styles/molecules/_page_list.scss
> +    -webkit-box-orient: vertical;
vendor prefix 不要

2023-07-05 10:13 UTC, yuki-takei commented on packages/ui/src/styles/molecules/_page_list.scss
> +    display: -webkit-box;
d-flex を利用すべきでは？

2023-07-10 12:14 UTC, yuki-takei requested changes

2023-07-10 12:14 UTC, yuki-takei commented on apps/app/src/components/PageList/PageListItemS.tsx
> +  }
noLink が考慮されていない

2023-07-12 02:23 UTC, jam411 requested changes

2023-07-12 02:23 UTC, jam411 commented on apps/app/src/components/PageList/PageListItemS.tsx
> +            <a className="text-break" href={page.path}>{pagePathElement}</a>
isNarrowView かつ noLink の場合はあるはずだからここが変わる感じになるんじゃないですかね？
精査お願いします。

2023-07-13 01:27 UTC, soumaeda commented
pagePathElementを何度も上書きして、isNarrowViewがtrueの場合の表示を実装していましたが、isNarrowViewはreturn内で分岐させることで、pagePathElementを上書きしないようにしました

2023-07-14 02:57 UTC, soumaeda commented
PageListItemsは汎用的なコンポーネントであるので、様々な条件で利用されることを考慮し、修正しました。
isNarrowViewがtrueかつnoLinkがtrueの場合、text-breakが適用されていない状態だったので、条件分岐でclassNameを付与するようにしました。
また、pageList.module.scssをimportしてstyleを適用させていたのですが、pageListItemSに対してのstyle適用を明確にするために、PageListItemS.module.scssを新たに作成しました。

2023-07-14 09:25 UTC, jam411 requested changes

2023-07-14 09:25 UTC, jam411 commented on apps/app/src/components/PageList/PageListItemS.module.scss
> +.pagetitle {
`page-title` ではなく？

2023-07-14 09:25 UTC, jam411 commented on apps/app/src/components/PageList/PageListItemS.tsx
> +import styles from './PageListItemS.module.scss';
これだけで styles 読み込めてるんでしょうか？
他ファイルで module scss 呼んでることろを参考に見てみてください。

2023-07-18 02:48 UTC, jam411 requested changes

2023-07-18 02:48 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkItem.tsx
> +        className="grw-bookmark-item-list list-group-item list-group-item-action border-0 py-0 my-2 mr-auto d-flex align-items-center"
実際動かしてみると `my-2` でホバーしたときの影より隙間があいて不自然だと思ったので `my-2` なしでもいいと思います。デザイナーに確認してください。
item 間をあけるにしてもページツリーのように影も含めてあけてほしいです。
![image](https://github.com/weseek/growi/assets/68407388/eff7b002-bf5e-479b-8bfd-9b0a12992036)



## `my-2` あり
![image](https://github.com/weseek/growi/assets/68407388/9c79998b-25d1-46ca-9400-2218ac57f584)


## `my-2` なし
![image](https://github.com/weseek/growi/assets/68407388/6613d1dd-b694-401b-8b20-85980c170ab3)

2023-07-18 05:22 UTC, jam411 approved these changes

2023-07-18 05:22 UTC, merged