imprv: Replace isAdmin with usersAdminHooks
weseek/growi pull request #7840
Opened 2023-06-28 11:14 UTC by WNomunomu

task: https://redmine.weseek.co.jp/issues/125689
### 概要
・useState, useEffectを使うことなく、hooksを用いてisAdminを判定できるようにしました。

2023-06-28 11:51 UTC, jam411 requested changes
`const isAdmin = currentUser?.admin;` などで grep して useIsAdmin で代用できるところがないか確認してほしいです。

2023-06-28 11:51 UTC, jam411 commented on apps/app/src/stores/context.tsx
> +  const isAdminUser = currentUser?.admin !== undefined ? currentUser.admin : false;
`const isAdminUser = currentUser != null ? currentUser.admin : false;` 

でお願いします。

2023-06-29 03:13 UTC, jam411 requested changes

2023-06-29 03:13 UTC, jam411 commented on apps/app/src/components/PrivateLegacyPages.tsx
> +  const isAdmin = useIsAdmin();
SWRResponse が渡ってしまってます。

2023-06-29 10:29 UTC, jam411 approved these changes

2023-07-03 12:15 UTC, yuki-takei requested changes

2023-07-03 12:15 UTC, yuki-takei commented on apps/app/src/stores/context.tsx
> +    { fallbackData: isAdminUser },
これは `keepPreviousData: true` 設定してもよさそう

2023-07-21 20:17 UTC, yuki-takei approved these changes

2023-07-21 20:17 UTC, merged