imprv: Don't show icon and count in two steps
weseek/growi pull request #7845
Opened 2023-07-03 08:28 UTC by soumaeda

2023-07-18 06:29 UTC, jam411 commented on apps/app/src/components/Bookmarks/BookmarkFolderTree.module.scss
> +      height: 50px;
こちらはすでにマージした差分のはず

2023-07-18 07:15 UTC, jam411 requested changes

2023-07-18 07:17 UTC, soumaeda commented on apps/app/src/components/PageList/PageListItemS.tsx
> +        <div className={`d-flex ${styles['page-list-items']}`}>
align-items-centerでUserPictureとPageListMetaを中央揃えにしました

2023-07-18 07:51 UTC, soumaeda commented on apps/app/src/components/PageList/PageListItemS.module.scss
> +      margin-right: 0.3rem;
こちらですが、PageListMeta.tsxの<span className="page-list-meta">に対してのstyleになるので、bootstrapを使わずにstyle指定する方法を選びました

2023-07-21 03:41 UTC, soumaeda commented
ページタイトルの文字数が多い場合でも、足跡とコメントが二段に分かれずに横一列で表示されるようにしました。

足跡とコメントの間隔(margin)については以下のタスクで改善します
https://redmine.weseek.co.jp/issues/127217

<img width="315" alt="スクリーンショット 2023-07-21 12 36 28" src="https://github.com/weseek/growi/assets/112812878/07601030-02e5-4693-818c-1fdd95601b40">

2023-07-21 05:35 UTC, jam411 commented on apps/app/src/components/PageList/PageListItemS.tsx
flex: 1 だけで
以下ように使えませんかね？
`d-flex align-items-center` なしでもかけそう。

```
    <>
      <UserPicture user={page.lastUpdateUser} noLink={noLink} />
      {isNarrowView ? (
        <Clamp lines={2}>
          <div className={`mx-2 text-break ${styles['page-title']} ${noLink ? 'text-break' : ''}`}>
            {pagePathElement}
          </div>
        </Clamp>
      ) : (
        { pagePathElement }
      )}
      <span className="ml-2">
        <PageListMeta page={page} shouldSpaceOutIcon={isNarrowView} />
      </span>
    </>
```

2023-07-21 06:27 UTC, soumaeda commented on apps/app/src/components/PageList/PageListItemS.tsx
この記述で対応できました。

ただ、isNarrowViewがfalseの場合、エラー（Objects are not valid as a React child）が出てしまっていたので、{ pagePathElement }をspanタグで囲みました

2023-07-21 07:13 UTC, merged