[WIP] imprv: Responsive Template Modal
weseek/growi pull request #7847
Opened 2023-07-04 08:09 UTC by jam411

## task
https://redmine.weseek.co.jp/issues/125850
https://redmine.weseek.co.jp/issues/125848

## Screenshot
### モーダルを開いてすぐ
![image](https://github.com/weseek/growi/assets/68407388/cae302df-345d-44ac-b610-1e03ad05dae2)
### Template を選択
![image](https://github.com/weseek/growi/assets/68407388/a63b1dd0-45da-458f-b483-87f1409f1663)
### Template の locale 選択
![image](https://github.com/weseek/growi/assets/68407388/8e53a1ec-0890-455d-8e3b-867df8225b7e)
![image](https://github.com/weseek/growi/assets/68407388/4f6b98fb-9599-45c6-9fb7-a1f7398c5055)
### Template 変更しても選択した locale が引き継がれる
![image](https://github.com/weseek/growi/assets/68407388/2df1d12a-ec1d-4d47-9e91-a3ddb4a49f4b)
### 存在しない locale の場合はなにも表示されない (例として `/minutes/zh_CN` ファイルを削除している)
![image](https://github.com/weseek/growi/assets/68407388/af58f6e7-1a3e-48f3-9ebb-038b5143774f)

## responsive
<img src="https://github.com/weseek/growi/assets/68407388/702c3e0d-f021-4b2c-85e5-77daf7ceeb4d" width="50%" />

<img src="https://github.com/weseek/growi/assets/68407388/8a95694f-b306-4b33-920b-e1f6ef23e960" width="50%" />

<img src="https://github.com/weseek/growi/assets/68407388/9596ae4a-b907-4e42-aaaa-e98c6c12717d" width="50%" />

2023-07-05 12:27 UTC, yuki-takei requested changes

2023-07-05 12:27 UTC, yuki-takei commented on apps/app/src/components/TemplateModal/TemplateModal.tsx
> +    }
この return だめでは？

2023-07-05 12:27 UTC, yuki-takei commented on apps/app/src/components/TemplateModal/TemplateModal.tsx
> +  const [selectedTemplate, setSelectedTemplate] = useState<TemplateStatus>();
state を増やす必要はない。(selectedTemplateSummary と selectedTemplateLocale さえあれば導出できるので)

2023-07-06 02:27 UTC, jam411 commented on apps/app/src/components/TemplateModal/TemplateModal.tsx
> +  const [selectedTemplate, setSelectedTemplate] = useState<TemplateStatus>();
getLocalizedTemplate と getTemplateLocales で導出するようにしました。

2023-07-06 02:31 UTC, jam411 commented on apps/app/src/components/TemplateModal/TemplateModal.tsx
> +    }
テンプレート選択は `usersDefaultLang` にかかわらずできるようにしました。

2023-07-06 03:39 UTC, jam411 commented on apps/app/src/features/templates/server/routes/apiv3/index.ts
メソッドが名前変更と移動していたので修正しました

2023-07-06 03:39 UTC, jam411 commented on packages/preset-templates/test/index.test.ts
こちらも修正

2023-07-06 04:47 UTC, yuki-takei requested changes

2023-07-06 04:47 UTC, yuki-takei commented on apps/app/src/components/TemplateModal/TemplateModal.tsx
> +  templateLocales?: Set<string>,
```
  templateSummary: TemplateSummary,
  selectedLocale?: string,
  onClick?: () => void,
  isSelected?: boolean,
  usersDefaultLang?: Lang,
```
にする

2023-07-06 04:47 UTC, yuki-takei commented on packages/pluginkit/src/v4/utils/template.ts
> +export const getLocalizedTemplate = (templateSummary: TemplateSummary | undefined, locale?: string, usersDefaultLang?: Lang): TemplateStatus | undefined => {
魔改造されている。戻して。

2023-07-06 04:47 UTC, yuki-takei commented on packages/pluginkit/src/v4/utils/template.ts
> +  const selectedLocale = usersDefaultLang ?? locale;
この ulitity method の身になって考えると、「selected」というコンテキストは意味が分からない。

```
const selectedLocale = usersDefaultLang ?? locale;
```
この処理相当はメソッドを呼ぶ側でやればよい。

2023-07-06 04:47 UTC, yuki-takei commented on packages/pluginkit/src/v4/utils/template.ts
> +  return selectedLocale != null && selectedLocale in templateSummary
`return locale != null && locale in templateSummary`

2023-07-06 04:47 UTC, yuki-takei commented on packages/pluginkit/src/v4/utils/template.ts
> +export const getTemplateLocales = (templateSummary: TemplateSummary | undefined): Set<string> | undefined => {
メソッド名を `extractSupportedLocales` に変更して

2023-07-06 05:23 UTC, jam411 commented on packages/pluginkit/src/v4/utils/template.ts
> +export const getTemplateLocales = (templateSummary: TemplateSummary | undefined): Set<string> | undefined => {
修正しました

2023-07-06 06:03 UTC, jam411 commented on packages/pluginkit/src/v4/utils/template.ts
> +export const getLocalizedTemplate = (templateSummary: TemplateSummary | undefined, locale?: string, usersDefaultLang?: Lang): TemplateStatus | undefined => {
戻しました

2023-07-06 06:03 UTC, jam411 commented on packages/pluginkit/src/v4/utils/template.ts
> +  const selectedLocale = usersDefaultLang ?? locale;
メソッドを呼ぶ側で条件分岐するようにしました。

2023-07-06 06:04 UTC, jam411 commented on apps/app/src/components/TemplateModal/TemplateModal.tsx
> +  templateLocales?: Set<string>,
TemplateItem コンポーネントの Props を修正し、それに合わせて `localizedTemplate` と `tempalteLocales` の取得を TemplateItem コンポーネント内で行うようにしました。

2023-07-06 07:21 UTC, yuki-takei requested changes

2023-07-06 07:21 UTC, yuki-takei commented on apps/app/src/components/TemplateModal/TemplateModal.tsx
> +      : undefined,
不要なロジックがある
というか全部不要説ある(getLocalizedTemplate は undefined な値にも対応しているので)

2023-07-06 07:21 UTC, yuki-takei commented on apps/app/src/components/TemplateModal/TemplateModal.tsx
> +      : undefined,
不要なロジックがある
というか全部不要説ある(getLocalizedTemplate は undefined な値にも対応しているので)

2023-07-06 07:33 UTC, jam411 commented on apps/app/src/components/TemplateModal/TemplateModal.tsx
> +      : undefined,
const localizedTemplate = getLocalizedTemplate(templateSummary, usersDefaultLang);

これでよかったので修正

2023-07-06 07:36 UTC, merged