support: Cypress test for TemplateModal
weseek/growi pull request #7864
Opened 2023-07-11 06:36 UTC by jam411

### task
- https://redmine.weseek.co.jp/issues/126557

2023-07-11 09:12 UTC, yuki-takei requested changes

2023-07-11 09:12 UTC, yuki-takei commented on apps/app/test/cypress/e2e/23-editor/23-editor--template-modal.cy.ts
> +    cy.visit('/Sandbox/child');
これ他のテストで作られる予定のページじゃないかね？あまり材料として好ましくない

2023-07-11 09:12 UTC, yuki-takei commented on apps/app/test/cypress/e2e/23-editor/23-editor--template-modal.cy.ts
> +    cy.collapseSidebar(true, true);
opened のスクリーンショット撮る前に collapse した方がいいのでは？

2023-07-12 02:58 UTC, jam411 commented on apps/app/test/cypress/e2e/23-editor/23-editor--template-modal.cy.ts
> +    cy.visit('/Sandbox/child');
修正しました

2023-07-12 02:58 UTC, jam411 commented on apps/app/test/cypress/e2e/23-editor/23-editor--template-modal.cy.ts
> +    cy.collapseSidebar(true, true);
修正しました

2023-07-12 04:32 UTC, merged