imprv: Show modal when you delete plugin
weseek/growi pull request #7875
Opened 2023-07-12 08:59 UTC by soumaeda

2023-07-20 01:40 UTC, jam411 requested changes

2023-07-20 01:40 UTC, jam411 commented on apps/app/public/static/locales/en_US/admin.json
> +    "delete": "Delete",
commons.json の `"Delete": "Delete"` で代用できるならそちらを使うようにしてください。

2023-07-20 01:40 UTC, jam411 commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginCard.tsx
`/workspace/growi/apps/app/src/stores/modal.tsx` を使うようにしてください。

2023-07-20 01:40 UTC, jam411 commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal.tsx
modal のデザイン確認についてですが、スレッドを見る限りで方向性の話はしているようだけど、最終こうなりましたっていう確認はしているのでしょうか？
例えば CommentDeleteModal を参考にしたと推測したんですが、CommentDeleteModal と違って `icon icon-fire` が無かったりするんですが。。

2023-08-06 13:28 UTC, soumaeda commented on apps/app/public/static/locales/en_US/admin.json
> +    "delete": "Delete",
commons.jsonのDeleteで代用し、PluginCard内でもcommon.jsonのDeleteを使うようにしました

2023-08-07 03:09 UTC, soumaeda commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginCard.tsx
modal.tsxから情報を取得するようにしました

2023-08-07 03:09 UTC, soumaeda commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal.tsx
fumiya-sさんに相談し、icon-fireを入れました

2023-08-07 03:16 UTC, soumaeda commented
### 修正点
PluginCardコンポーネント内でPluginDeleteModalコンポーネントの呼び出しを行っていましたが、modal.tsx内のカスタムフック（usePluginDeleteModal）でPluginDeleteModalの状態管理ができるようにしました。

2023-08-07 05:44 UTC, jam411 requested changes

2023-08-07 05:44 UTC, jam411 commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal.tsx
> +  };
他のコードを参考に書いてくれたと思いますが、行数が少ないのと特殊なことしてないから *Content 変数に入れずにそのまま React JSX を書いてほしい。
見るときに上下するので読みにくいって考えている。

2023-08-07 05:44 UTC, jam411 commented on apps/app/src/components/Layout/AdminLayout.tsx
> +  '../../features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal'
import 分はなるべく行数を短くしたいのでこんな感じにしておいてください。

```
const PluginDeleteModal = dynamic(() => import('~/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal')
  .then(mod => mod.PluginDeleteModal), { ssr: false });
```

2023-08-07 05:44 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +}
これ使ってないのでは？

2023-08-07 05:44 UTC, jam411 commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginCard.tsx
> +  mutate: () => void,
`mutate` はなんで残しているんですかね？

2023-08-07 05:44 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +
意図的ならOKだけど、この改行とか気を付けてほしい。

2023-08-07 05:44 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +    });
`mutate(initialStatus)` ではできませんか？

2023-08-07 05:55 UTC, soumaeda commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal.tsx
> +  };
直接return内に記述しました

2023-08-07 06:00 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +}
削除し忘れていました。
使っていないため、削除しました

2023-08-07 09:31 UTC, soumaeda commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginCard.tsx
> +  mutate: () => void,
usePluginDeleteModalからPluginDeleteModalに渡るため、不要と判断し、削除しました

2023-08-07 09:38 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +    });
initialStatusと同じ値が入るので、initialStatusを利用するようにしました

2023-08-07 23:42 UTC, jam411 requested changes

2023-08-07 23:42 UTC, jam411 commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginsExtensionPageContents.tsx
> +                    });
- `openPluginDeleteModal(plugin)` で渡せませんか？
- もともと僕が変数に入れてから渡していたのがわるかったんだけど `PluginCard` にpluginId とか pluginName も直接渡したほうがシンプルにかけそうなので修正お願いしたいです。 

```
      {data.plugins.map((plugin) => (
        <PluginCard
          key={plugin._id}
          id={plugin._id}
          name={plugin.meta.name}
          url={plugin.origin.url}
          isEnalbed={plugin.isEnabled}
          desc={plugin.meta.desc}
          mutate={() => openPluginDeleteModal(plugin)} // できたら
        />
      ))}
```

2023-08-07 23:42 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +}
とても細かいですが id プロパティは上にあるイメージです。
以下にしたい。
```
type PluginDeleteModalStatus = {
  isOpen: boolean,
  id: string,
  name: string,
  url: string,
}
```

2023-08-07 23:42 UTC, jam411 commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal.tsx
> +  const id = pluginDeleteModal?.id;
ここも 
```
  const id = pluginDeleteModal?.id;
  const name = pluginDeleteModal?.name;
  const url = pluginDeleteModal?.url;
```

2023-08-07 23:42 UTC, jam411 commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal.tsx
> +  const { data: pluginDeleteModal, close: closePluginDeleteModal } = usePluginDeleteModal();
変数名を `const { data: pluginDeleteModalData` にしたい

2023-08-08 01:46 UTC, soumaeda commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginsExtensionPageContents.tsx
> +                    });
直接渡すことができたので、修正しました。

また、PluginCard内のDeleteボタンを押した時にトリガーされる関数名ですが、onDeleteの方が良いのではないかと思いましたので、`mutate={() => openPluginDeleteModal(plugin)}`ではなく、`onDelete={() => openPluginDeleteModal(plugin)}`にしました。

2023-08-08 01:48 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +}
`const open = useCallback((plugin: IGrowiPluginHasId) => {
    mutate({
      isOpen: true,
      id: plugin._id,
      name: plugin.meta.name,
      url: plugin.origin.url,
    });
  }, [mutate]);`

こちらもidを上に記述しました

2023-08-08 03:04 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +}
戻り値の型が void でいいのか確認お願いします 🙏

2023-08-08 04:48 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +}
voidの場合戻り値がなく、呼び出し元の処理の完了を待たずに、open、closeメソッドを実行する。
`type PluginDeleteModalUtils = {
  open(plugin: IGrowiPluginHasId): Promise<PluginDeleteModalStatus | undefined>,
  close(): Promise<PluginDeleteModalStatus | undefined>,
}`
このように修正することで、PluginDeleteModal内の処理(await apiv3Delete(reqUrl);)が完了するまで待つことができるようになりました。

2023-08-08 07:42 UTC, soumaeda commented
`async(plugin: IGrowiPluginHasId): Promise<PluginDeleteModalStatus | undefined>`

型推論で足りるところをわざわざ型アサーションおり、不要のため削除しました。

async関数内でswrResponse.Dataをreturnしていましたが、グローバルステートの更新には不要なので削除し、型エイリアスではPromise<void>と定義しました。

2023-08-10 02:50 UTC, jam411 approved these changes

2023-08-18 19:55 UTC, yuki-takei requested changes

2023-08-18 19:55 UTC, yuki-takei commented on apps/app/src/components/Layout/AdminLayout.tsx
> +        <PluginDeleteModal />
ここには入れず、PluginsExtensionPageContents.tsx に入れてください

2023-08-18 19:55 UTC, yuki-takei commented on apps/app/src/stores/modal.tsx
> +};
これも features/growi-plugin/client の中にあった方がいいね

2023-08-18 19:55 UTC, yuki-takei commented on apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal.tsx
> +  }, [id, closePluginDeleteModal, t, mutate]);
更にコード品質を上げるために、いくつか後続ストーリーを作ってください。

- apiv3Delete をカスタムフック化する
    - `client/services/page-operation.ts` が参考になる
- toast 表示および Modal の close を PluginsExtensionPageContents にやらせる
    - 責務の観点から

2023-08-21 07:33 UTC, soumaeda commented
後続ストーリー

- https://redmine.weseek.co.jp/issues/128875
- https://redmine.weseek.co.jp/issues/128908

2023-08-21 07:49 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +};
/growi-plugin/client/stores/admin-plugins.tsxに記述しました

2023-08-22 00:41 UTC, merged