Feat/120030 126901 set batch size for promise all
weseek/growi pull request #7884
Opened 2023-07-17 02:01 UTC by arafubeatbox

2023-07-17 02:15 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +const MAX_USERS_TO_PROCESS = 100;
一度に処理するグループ木の数とグループ内のユーザの数を指定して Promise.all を実行（51, 74行目)

木の中のグループは for await で一個ずつ処理（46行目）
理由:
- 処理する子グループの数を MAX_CHILD_TO_PROCESS で指定しても、仮に各グループに紐づく子グループ数が MAX 程度であれば処理する Promise 数が MAX_CHILD_TO_PROCESS 分だけ指数的に増える可能性がある

2023-07-17 02:24 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +const USERS_BATCH_SIZE = 100;
一度に処理するグループ木の数とグループ内のユーザの数を指定して Promise.all を実行（51, 74行目)

木の中のグループは for await で一個ずつ処理（46行目）
理由:

処理する子グループの数を CHILD_BATCH_SIZE で指定しても、仮に各グループに紐づく子グループ数がバッチサイズ程度であれば処理する Promise 数が CHILD_BATCH_SIZE 分だけ指数的に増える可能性がある

2023-07-17 02:24 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +const USERS_BATCH_SIZE = 100;
空間計算量は、一番階層が深いグループ木の深さを d として

```
O(TREES_BATCH_SIZE * d * USERS_BATCH_SIZE)
```

2023-07-17 02:25 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +const USERS_BATCH_SIZE = 100;
バッチサイズは適当に選んだもので、最適値の検証を行ったわけではありません。

2023-07-20 05:36 UTC, jam411 commented on apps/app/src/utils/promise.ts
> +    const end = start + limit > items.length ? items.length : start + limit;
こうもかけそうです。良ければ
`const end = Math.min(start + limit, items.length);`

2023-07-20 05:37 UTC, jam411 commented on apps/app/src/utils/promise.ts
> +    const end = start + limit > items.length ? items.length : start + limit;
こうもかけそうです。良ければ
`const end = Math.min(start + limit, items.length);`

2023-07-20 05:37 UTC, jam411 commented on apps/app/src/utils/promise.ts
> +    ];
push() を使うのはどうでしょうか？
`results.push(...slicedResults);`

2023-07-20 12:57 UTC, arafubeatbox commented on apps/app/src/utils/promise.ts
> +    ];
concat の方が直接的かと思うので、concat を使います。

2023-07-26 06:51 UTC, yuki-takei requested changes

2023-07-26 06:51 UTC, yuki-takei commented on apps/app/src/utils/promise.ts
ここまで汎用的なユーティリティとして用意すると例外処理が気になってくるんだよねえ。
Promise.allSettled をチェックしてほしい。batch の1つが失敗したら全部失敗でいいなら今回の実装でいいが、そうではないケースもありそう。

(今修正しろという話ではない)

2023-07-26 06:51 UTC, yuki-takei commented on apps/app/src/utils/promise.spec.ts
> +    });
このテストでは limit に応じてちゃんとスライスされてるかどうかのテストにはならないと思う。
fn は map の callback なので `(item, index, array)` を引数に取れる。第三引数の array が batch1/2/3 と等しいかどうかを expect でチェックしよう。

2023-07-26 06:51 UTC, yuki-takei commented on apps/app/src/features/external-user-group/server/service/ldap-user-group-sync.ts
> +      const userInfos = (await batchProcessPromiseAll(userIds, USERS_BATCH_SIZE, (id) => {
ここ 100 promises 分 getUserInfo が走るのはコスト高いと思う

2023-07-26 06:51 UTC, yuki-takei commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +    await batchProcessPromiseAll(node.userInfos, USERS_BATCH_SIZE, async(userInfo) => {
ここ 100 promises 分 findGroupsWithAncestorsRecursively やら ExternalUserGroupRelation.find やらが走るのはコスト高いと思う。

2023-07-26 06:51 UTC, yuki-takei commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +const USERS_BATCH_SIZE = 100;
ケースバイケースだろうがたぶん 100 は多い。利用箇所にコメントする。

2023-07-30 08:05 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +const USERS_BATCH_SIZE = 100;
少なくします。

どこかで大規模グループツリー取り込みの動作検証はしなきゃなと思っていたので、後続ストーリーで行おうかと思います。
全てローカルになってしまうので実際のケースとは異なりますが、
グループ数: 100
各グループのユーザ数: 100
くらいで試そうかなと思ってます。

2023-07-30 08:06 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +const USERS_BATCH_SIZE = 100;
そこでまた数値いじる必要がありそうだったら行います。

2023-07-30 08:07 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/ldap-user-group-sync.ts
> +      const userInfos = (await batchProcessPromiseAll(userIds, USERS_BATCH_SIZE, (id) => {
https://github.com/weseek/growi/pull/7884/files#r1278527808 参照

2023-07-30 08:07 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +    await batchProcessPromiseAll(node.userInfos, USERS_BATCH_SIZE, async(userInfo) => {
https://github.com/weseek/growi/pull/7884/files#r1278527808 参照

2023-07-30 08:17 UTC, arafubeatbox commented on apps/app/src/utils/promise.ts
後続ストーリーで対応しますm(_ _)m

2023-07-30 08:24 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/models/external-user-group-relation.integ.ts
> +          _id: groupId2, name: 'test group 2', externalId: 'testExternalId2', provider: 'testProvider',
何故今まで落ちていなかったのか謎ですが、unique validation に引っかかっていたので修正しました
（unique の指定は2ヶ月前に実施

2023-08-01 17:54 UTC, merged