Fix/126404 manager authority modifying
weseek/growi pull request #7908
Opened 2023-07-24 08:17 UTC by WNomunomu

2023-07-26 06:45 UTC, WNomunomu commented on apps/app/src/server/routes/login-passport.js
> +    return res.apiv3({ redirectTo, isAdmin });
ログインしたユーザーがadminかどうかを示すデータがres.dataに入るようにしました。

2023-07-26 06:47 UTC, WNomunomu commented on apps/app/src/components/LoginForm.tsx
> +      }
adminではないユーザーが /admin にリダイレクトしようとした時に、 / にリダイレクトされるようにしました。

2023-07-26 08:34 UTC, yuki-takei commented on apps/app/src/server/routes/login-passport.js
> +    return res.apiv3({ redirectTo, isAdmin });
login-passport への変更は不要

2023-07-26 08:37 UTC, yuki-takei commented on apps/app/src/components/LoginForm.tsx
> +      }
ここで処理を分けるのではなく、`admin/*.page.tsx` の getServerSideProps に判定処理を入れるべき

2023-08-07 06:00 UTC, yuki-takei requested changes

2023-08-07 06:00 UTC, yuki-takei commented on apps/app/src/utils/admin-page-util.ts
> +  props.isAccessDeniedForNonAdminUser = props.currentUser != null && !props.currentUser.admin;
currentUser が null でもここは denied にならないとでは？

2023-08-07 09:32 UTC, miya commented on apps/app/src/utils/admin-page-util.ts
> +  props.isAccessDeniedForNonAdminUser = props.currentUser != null && !props.currentUser.admin;
currentUser が null の時は true が入るように修正しました

2023-08-07 09:32 UTC, miya commented on apps/app/src/pages/admin/index.page.tsx
> +  const { data: isAdmin } = useIsAdmin();
不要でしたので削除しました

2023-08-07 10:27 UTC, merged