imprv: Improve default behavior of skipSSR
weseek/growi pull request #7927
Opened 2023-07-28 08:46 UTC by jam411

- task: https://redmine.weseek.co.jp/issues/126576

2023-07-28 09:33 UTC, yuki-takei requested changes

2023-07-28 09:33 UTC, yuki-takei commented on apps/app/src/pages/utils/commons.ts
> +}
ここのロジック含め model 側に閉じ込めてよい。
つまり、利用側は単なる `get latestRevisionBodyLength()` として利用できるようにする。(obsolete-page.js の `pageSchema.methods.seen` と似たような処理)

2023-07-28 09:33 UTC, yuki-takei commented on apps/app/src/server/models/page.ts
> +      },
document を丸ごと持ってくるのをやめよう

2023-07-29 10:37 UTC, jam411 commented on apps/app/src/server/models/page.ts
> +  }
revision が無い page ドキュメント用は null を返すようにしました。

2023-07-29 10:37 UTC, jam411 commented on apps/app/src/server/models/page.ts
> +    const calculatedLatestRevisionBodyLength = await calculateAndUpdateLatestRevisionBodyLength(this);
計算し、ドキュメントが update されることがわかるように `calculateAndUpdateLatestRevisionBodyLength` という命名にしてみました

2023-07-29 10:37 UTC, jam411 commented on apps/app/src/server/models/page.ts
> +  }
revision モデルの型が any になるので一応 latestRevisionData.body の型もチェックするようにしています。

2023-07-29 10:37 UTC, jam411 commented on apps/app/src/server/models/page.ts
> +  await page.save();
model('Page') を呼び出さなくていいように、そのままドキュメントを save() するようにしました。

2023-07-29 10:37 UTC, jam411 commented on apps/app/src/pages/utils/commons.ts
>    }
null の場合は SSR する

2023-07-29 10:37 UTC, jam411 commented on apps/app/src/server/models/page.ts
> +      },
シンプルに書けると思ったので aggregate を使わないで書いてみました。

2023-07-29 10:39 UTC, jam411 commented on apps/app/src/pages/utils/commons.ts
> +}
page.latestRevisionBodyLength() とすると latestRevisionBodyLength をフィールド名として使っているため型エラーとなったので page.ensureLatestRevisionBodyLength(); として利用できるようにしました。

2023-07-29 10:46 UTC, jam411 commented on apps/app/src/server/models/page.ts
> +  }
revision モデルの型が any になるので一応 latestRevisionData.body の型もチェックするようにしています。
throw せずに logger と null を返すようにしています。

2023-07-29 11:01 UTC, yuki-takei commented on apps/app/src/pages/utils/commons.ts
> +}
メソッド名は ensure ではなく get で始めてください

2023-07-29 11:07 UTC, yuki-takei requested changes

2023-07-29 11:07 UTC, yuki-takei commented on apps/app/src/server/models/page.ts
> +  const latestRevisionData = await mongoose.model('Revision').findById(page.revision, { body: 1 });
これは populate で書けない？

2023-07-29 11:07 UTC, yuki-takei commented on apps/app/src/server/models/page.ts
> +  }
`this.revision` に対する操作なのでもっと type safe に書けるんじゃないかと思ってる

2023-07-29 11:08 UTC, yuki-takei requested changes

2023-07-29 11:08 UTC, yuki-takei commented on apps/app/src/server/models/page.ts
> +schema.methods.ensureLatestRevisionBodyLength = async function(this: PageDocument): Promise<number | null> {
メソッド名は ensure ではなく get で始めてください

2023-07-30 12:05 UTC, jam411 commented on apps/app/src/pages/utils/commons.ts
> +}
修正しました。

2023-07-30 12:06 UTC, jam411 commented on apps/app/src/server/models/page.ts
> +  }
Ref<IRevision> が populate されるので string かどうかを判断することで型ガードするようにしました。

2023-07-30 12:07 UTC, jam411 commented on apps/app/src/server/models/page.ts
> +  const latestRevisionData = await mongoose.model('Revision').findById(page.revision, { body: 1 });
model 層で populate は NG だと思っていました。populate するように変更してみました。

2023-07-30 14:06 UTC, yuki-takei requested changes

2023-07-30 14:06 UTC, yuki-takei commented on apps/app/src/server/models/page.ts
> +schema.methods.getLatestRevisionBodyLength = async function(this: PageDocument): Promise<number | null | undefined> {
undefined が返ることってある？

2023-07-30 14:06 UTC, yuki-takei commented on apps/app/src/server/models/page.ts
> +  }
条件の 2 つのケースは処理を分けたい。
revision が null なら null (または undefined) を返すのは良さそうだが、isLatestRevision() が false の場合にこのメソッドが呼ばれるというのは想定外の使われ方なのではないか？もしそうなら throw Error の方がいい。

2023-07-30 14:06 UTC, yuki-takei commented on apps/app/src/pages/utils/commons.ts
> +    return false;
ここ return true では？
過去の revision 閲覧時は多少 UX 落ちても良くて、それより重いかもしれないデータを SSR しない方が安全だよね。

2023-07-30 15:07 UTC, jam411 commented on apps/app/src/pages/utils/commons.ts
> +    return false;
そうか、過去の revision を見る場合もありました。
`return true` で SSR しないようにします。

2023-07-30 15:33 UTC, jam411 commented on apps/app/src/server/models/page.ts
> +schema.methods.getLatestRevisionBodyLength = async function(this: PageDocument): Promise<number | null | undefined> {
- `this.latestRevisionBodyLength` がもともと number | undefined 型なので undefined も許容しないと最後の `return this.latestRevisionBodyLength;` で型エラーになるためこうしました。 
確かに値が入っているか null かどうかなことは getLatestRevisionBodyLength すれば分かるので undefined が返りえるのが気持ち悪い感じもします。
ただ考えてみると、実際 latestRevisionBodyLength フィールドに null を格納するわけではないのでむしろ undefined を返すほうが正しいんでしょうかね？

- calculateAndUpdateLatestRevisionBodyLength が結果を返すようにすれば解決しそうですが、calculateAndUpdate の接頭語のメソッドに結果を返す責務も持たせていいのかわからなかったのでこうしていました。

2023-07-31 05:53 UTC, merged