Fix page service and page grant service
weseek/growi pull request #7928
Opened 2023-07-30 05:11 UTC by arafubeatbox

2023-08-01 07:53 UTC, jam411 commented on apps/app/src/server/service/page-grant.ts
> +      const isUserExistInGroup = await isUserExistInUserGroup || isUserExistInExternalUserGroup;
await なしでもいいと思います。
`const isUserExistInGroup = isUserExistInUserGroup || isUserExistInExternalUserGroup;`

2023-08-01 14:17 UTC, arafubeatbox commented on apps/app/src/server/service/page-grant.ts
> +  }[],
これ迷いましたが、現段階で Ref が有用なケースも見つかってないので、GrantedGroup の方を一旦 ObjectIdLike に変えてみようと思います。

2023-08-01 14:25 UTC, arafubeatbox commented on apps/app/src/server/service/page-grant.ts
> +        applicableGroupIds = [...applicableUserGroups, ...applicableExternalUserGroups].map(g => g._id) || null;
この行まで到達している場合、必ず applicableGroupIds は配列となるので、null とっても良さそうでした。
配列が格納された applicableGroupIds は、processValidation で別の配列との部分集合があるかの比較に使われます。

2023-08-02 02:05 UTC, jam411 approved these changes

2023-08-02 02:09 UTC, jam411 commented on apps/app/src/server/service/page-grant.ts
> +      applicableUserIds = Array.from(new Set([...userGroupRelations, ...externalUserGroupRelations].map(r => r.relatedUser))) as ObjectIdLike[];
`as ObjectIdLike[]` を外しても同じ `ObjectIdLike[] | undefined` で型推論されるようなので気になりました。
不要であればないほうがいいと思う派です。

2023-08-03 12:24 UTC, yuki-takei requested changes

2023-08-03 14:55 UTC, arafubeatbox commented on apps/app/src/server/util/compare-objectId.ts
> +};
intersection (共通要素がある) が条件だと今までの仕様から外れそうだったので、includes (部分集合である) に変えました。

2023-08-03 14:56 UTC, arafubeatbox commented on packages/core/src/interfaces/page.ts
> +  item: Ref<any>,
IExternalGroup を core に入れるのは憚れるので、一旦様子見で、IUserGroup のみにしました。

2023-08-07 14:41 UTC, merged