Imprv/115673 115675 enable from adminsetting
weseek/growi pull request #7939
Opened 2023-08-01 08:03 UTC by reiji-h

# 概要
Marp を管理者画面から有効化するオプションを追加する
# Task
- https://redmine.weseek.co.jp/issues/115673
  - https://redmine.weseek.co.jp/issues/115675
- 管理者画面で無効化していると、Frontmatter で marp: true を指定しても使えない

2023-08-02 02:41 UTC, jam411 requested changes
- `/workspace/growi/apps/app/src/server/models/config.ts` で isEnabledMarp の初期値を設定してほしいです。

- 管理画面の配置とデザインを dev-uiux で yuki さん fumiya-s さん shintaro-o　さんにメンションしてこんな感じでやろうと思っていること垂れ流しておいてほしいです。ツッコミがあれば教えてくれると思う。武井さんは review のタイミングでもいいかもしれないが。

2023-08-02 02:41 UTC, jam411 commented on apps/app/src/pages/me/[[...path]].page.tsx
`/me` ではいらないんじゃないかな？
でも `props.rendererConfig` があるので入れておいたほうがよさそうか。

2023-08-02 02:41 UTC, jam411 commented on apps/app/src/pages/_search.page.tsx
`useIsEnabledMarp` を使用しないで大丈夫でしょうか？

2023-08-02 02:41 UTC, jam411 commented on apps/app/src/client/services/AdminCustomizeContainer.js
> +        isEnabledMarp: this.state.isEnabledMarp,
`customizedParams.isEnabledMarp` にしてください。

2023-08-02 02:41 UTC, jam411 commented on apps/app/src/pages/[[...path]].page.tsx
> +  props.isEnabledMarp = configManager.getConfig('crowi', 'customize:isEnabledMarp');
不具合がなければ `useIsEnalbedMarp(props.rendererConfig.isEnalbedMarp)` とすればいいんでないかな？
`configManager.getConfig('crowi', 'customize:isEnabledMarp');` 二回呼び出す必要はなくなる。

2023-08-04 01:45 UTC, reiji-h commented on apps/app/src/client/services/AdminCustomizeContainer.js
> +        isEnabledMarp: this.state.isEnabledMarp,
修正しました。

2023-08-04 02:07 UTC, reiji-h commented on apps/app/src/pages/[[...path]].page.tsx
> +  props.isEnabledMarp = configManager.getConfig('crowi', 'customize:isEnabledMarp');
出来なさそうだったので今回はそのままでいきます。

2023-08-04 02:24 UTC, reiji-h commented on apps/app/src/pages/_search.page.tsx
検索結果のプレビューに使われる renderer には remarkPlugin を入れていないので、rendererConfig の内容にかかわらずプレビューにスライド表示はされないと考えています。そのため `useIsEnabledMarp` も必要ないと判断しました。

2023-08-04 02:25 UTC, reiji-h commented on apps/app/src/pages/me/[[...path]].page.tsx
lint error が起きていたので解決のため入れました。

2023-08-04 06:09 UTC, jam411 commented on apps/app/src/pages/[[...path]].page.tsx
> +  props.isEnabledMarp = configManager.getConfig('crowi', 'customize:isEnabledMarp');
props.rendererConfig.isEnalbedMarp だけにgetConfigから取得した値を格納し、フックスに渡す時も props.rendererConfig.isEnalbedMarp を渡せばどうですか？　と言う意味でした。
これでもできませんでしたかね？
つまり props.isEnabledMarp を用意しないでもいいのでは？ ってことでした。

2023-08-04 06:33 UTC, jam411 approved these changes
- `/trash` ページと検索ではレンダリングしないで了解です
- レンダリングする next pages は動作確認で網羅できるようにしておきたいです。忘れずに動作確認タスクに加えておいてください

2023-08-04 07:30 UTC, reiji-h commented on apps/app/src/pages/[[...path]].page.tsx
> +  props.isEnabledMarp = configManager.getConfig('crowi', 'customize:isEnabledMarp');
確認しました。`props.isEnabledmarp`の用意は必要なかったのでそのように修正します。

2023-08-04 10:07 UTC, yuki-takei requested changes

2023-08-04 10:07 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/admin.json
> +      "enable_marp_desc": "OFFの場合、Marp は使用できません。",
> プレゼンテーション表示に Marp を利用できるようになります。

に変更して。

更に、XSS に対して脆弱になり得るということを追記してください。

2023-08-04 10:07 UTC, yuki-takei commented on apps/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
> +          </div>
Functions の中ごちゃごちゃしてきたから、「プレゼンテーション」っていうサブセクションがほしいな
後続ストーリーにして meiri-k にアサインしてください。

2023-08-07 01:52 UTC, reiji-h commented on apps/app/public/static/locales/ja_JP/admin.json
> +      "enable_marp_desc": "OFFの場合、Marp は使用できません。",
次のように変更しました。

<img width="559" alt="image" src="https://github.com/weseek/growi/assets/132258880/6835ec1c-cc25-4461-9d72-bdd6602a4ca2">

2023-08-07 03:46 UTC, merged