imprv: Normal slide preview look like a Marp
weseek/growi pull request #7952
Opened 2023-08-04 03:45 UTC by reiji-h

# 概要
GROWI のスライドもプレビューに表示できるようにする。その際に Marp のプレビュー表示と外枠やサイズなどに差がないようにする
# Task
- https://redmine.weseek.co.jp/issues/115672
  - https://redmine.weseek.co.jp/issues/125680
# Screenshot
## Marp のスライドプレビュー
<img width="952" alt="スクリーンショット 2023-08-04 124234" src="https://github.com/weseek/growi/assets/132258880/cb27d2d2-8eea-4dc5-a738-e2ab20c005f5">

## GROWI スライドのプレビュー
<img width="952" alt="スクリーンショット 2023-08-04 124325" src="https://github.com/weseek/growi/assets/132258880/2b68b91a-fa56-4c19-8639-e0d72b9656c2">

2023-08-22 01:12 UTC, jam411 commented on packages/presentation/src/components/RichSlideSection.tsx
> +        <foreignObject width="1280" height="720">
1280 720 と `data-marpit-svg=""` はどうやってきまったのでしょうか？

2023-08-22 09:42 UTC, reiji-h commented on packages/presentation/src/components/RichSlideSection.tsx
> +        <foreignObject width="1280" height="720">
Marp が render したときに出力される HTML のクラス名等をそのまま持ってきてこの形になっています。

2023-08-23 02:12 UTC, jam411 approved these changes

2023-08-23 05:23 UTC, yuki-takei requested changes

2023-08-23 05:23 UTC, yuki-takei commented on packages/presentation/src/components/GrowiSlides.tsx
> +  }
元の実装も悪かったのかもしれないけど、これだと remarkPlugins, components が null だと何も追加されなくなってしまうね。null だったとしても入れ物を新設して追加する必要がある。

2023-08-23 05:23 UTC, yuki-takei commented on packages/presentation/src/components/Slides.tsx
> +});
このコンポーネントがここまで詳細に Marp インスタンスを作るのはちょっと気持ち悪い。

marpit, presentationMarpit 両方を新規モジュール(ファイル)に逃がして export し、GrowiSlides と MarpSlides 双方から参照する形にしてはどうか？(もし穴があったら相談してほしい)

2023-08-23 07:02 UTC, reiji-h commented on packages/presentation/src/components/Slides.tsx
> +});
growi-marpit.ts に slideMarpit と presentationMarpit という形に分けて入れました。また Slides.tsx からの参照は完全になくしたほう良いと思ったので、MARP_CONTAINER_CLASS_NAME 周りも移動しました。

2023-08-23 08:28 UTC, reiji-h commented on packages/presentation/src/components/GrowiSlides.tsx
> +  }
入れ物を新設するのではなく、undefined だった時何も返さない形で実装しました。これにより Flickering はなくなり、完全な rendererOptions のみでレンダリングできるようになります。

2023-08-23 13:43 UTC, merged