imprv: Create  Japanese  ejs files
weseek/growi pull request #7957
Opened 2023-08-07 04:51 UTC by meiri-k

### 概要
- `/growi/apps/app/resource/locales/ja_JP` 配下にある ejs ファイルを日本語にする
### Task
- https://redmine.weseek.co.jp/issues/125083
          - https://redmine.weseek.co.jp/issues/128021

2023-08-07 23:52 UTC, jam411 requested changes
- `/workspace/growi/apps/app/resource/locales/ja_JP/notifications` 配下の ejs ファイルも同じように日本語にしてほしいです。
- ejs ファイルについて url が小文字大文字でばらばらだったり、`さん` つけしたりしてなかったりemail の呼び方が email アドレス, Email とかばらばらなので ejs ファイル全体を見て日本語のメール文としていい感じに統一してほしいです。

2023-08-07 23:52 UTC, jam411 commented on foo.txt
foo.txt は必要なければ消してほしいです。

2023-08-07 23:52 UTC, jam411 commented on apps/app/resource/locales/ja_JP/admin/userWaitingActivation.ejs
> + <%- appTitle %> に登録されているユーザー。
最初の行に半角スペースがありますが意図的でしょうかね？
スペースはいらないかなと思いました。

2023-08-07 23:52 UTC, jam411 commented on apps/app/resource/locales/ja_JP/admin/userResetPassword.ejs
>  New Password: <%- password %>
`New Password` を `新しいパスワード` のように日本語にしたいです。追加修正お願いします。

2023-08-08 05:15 UTC, meiri-k commented
### 概要
- 「/growi/apps/app/resource/locales/ja_JP 配下にある ejs ファイルを日本語にする」のFB対応
### FB内容

1. foo.txtファイルの削除
2. 半角スペースの削除
3. 「new password」の日本語変換

2023-08-08 05:23 UTC, jam411 commented on apps/app/resource/locales/ja_JP/admin/userInvitation.ejs
> +あなたは、我々のwikiに招待されましたので、次のアカウントでログインできます。:
このあたりの日本語は武井さんに確認してもらう

2023-08-08 05:25 UTC, meiri-k commented on apps/app/resource/locales/ja_JP/admin/userInvitation.ejs
> +あなたは、我々のwikiに招待されましたので、次のアカウントでログインできます。:
> あなたは
っていうのいらないですかね

2023-08-09 09:31 UTC, yuki-takei commented on apps/app/resource/locales/ja_JP/admin/userInvitation.ejs
> +あなたは、我々のwikiに招待されましたので、次のアカウントでログインできます。:
> GROWI に招待されました！次のアカウント情報でログインしてください:

とかでいいかな。

2023-08-21 10:33 UTC, merged