feat:  Support Marp
weseek/growi pull request #7958
Opened 2023-08-07 05:05 UTC by reiji-h

# 概要
Marp を利用可能にする
# Task
- https://redmine.weseek.co.jp/issues/115673
  - https://redmine.weseek.co.jp/issues/115675
- ページの frontmatter を次のようにすると Marp が有効になる
```
---
marp: true
---
```
# Screenshot
![image](https://github.com/weseek/growi/assets/132258880/a35328fb-3f10-4c53-a943-0abb12144a02)

2023-08-07 14:39 UTC, yuki-takei requested changes

2023-08-07 14:39 UTC, yuki-takei commented on packages/presentation/src/components/Slides.tsx
> +    new Element('div', { class: 'shadow rounded', style: 'margin: 20px' }),
スタイリングは CSS でやる

2023-08-10 03:19 UTC, reiji-h commented on packages/presentation/src/components/Slides.tsx
> +    new Element('div', { class: 'shadow rounded', style: 'margin: 20px' }),
ピクセル単位までのこだわりがなかったため Bootstrap を用いて margin を表現するよう変更しましたが、この解決方法はアリでしょうか？

```
new Element('div', { class: 'shadow rounded m-2' }),
```


![image](https://github.com/weseek/growi/assets/132258880/22cbbcba-2087-404c-8fbe-5ac3b5d18819)

2023-08-10 03:22 UTC, reiji-h commented on packages/presentation/src/components/Slides.tsx
> +      </>
- Slides.tsx のうち Marp を MarpSlides.tsx にし GROWI のスライドを GrowiSlides.tsx に分割しました。
- Slides.tsx の MARP_CONTAINER_CLASS_NAME については https://redmine.weseek.co.jp/issues/125680
 で無くす予定です。

2023-08-13 16:23 UTC, merged