Fix api to use granted user groups
weseek/growi pull request #7967
Opened 2023-08-08 15:21 UTC by arafubeatbox

2023-08-18 14:31 UTC, jam411 commented on apps/app/src/components/PageAlert/PageGrantAlert.tsx
> +              typeof pageData.grantedGroups[0].item !== 'string' && pageData.grantedGroups[0].item.name
`isPopulated()` 使えないでしょうか？

2023-08-18 14:31 UTC, jam411 commented on apps/app/src/components/PageEditorByHackmd.tsx
> +      return { item: group.id, type: group.type as GroupType };
> page.ts の IPageGrantData インターフェースの type の型を GroupType に変えられないでしょうか？

2023-08-18 14:31 UTC, jam411 commented on apps/app/src/components/SavePageControls/GrantSelector.tsx
> +    type: string,
`type: GroupType` として絞れませんかね？

2023-08-18 14:31 UTC, jam411 commented on apps/app/src/interfaces/page.ts
> +    type: string,
あ、ここですね。

2023-08-18 14:31 UTC, jam411 commented on apps/app/src/pages/[[...path]].page.tsx
> +    }),
GrantedGroup インターフェース使ったらいいんじゃないかと思ったけど、GrantedGroup には id プロパティがないな。
page-grant.ts をみてると ComparableTarget などで `grantedGroupIds?: GrantedGroup[]` としているから完全に用途が違うのか。

2023-08-18 14:31 UTC, jam411 commented on apps/app/src/server/routes/apiv3/page.js
> +      body('grantedGroups').optional().isArray().withMessage('grantedGroups must be an array'),
grantedGroups 配列の中身はバリデーションすると too much ですかね。簡単にできそうならやってもいいのかな。

2023-08-20 13:18 UTC, arafubeatbox commented on apps/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
> +    const grantUserGroupIds = currentPage.grantedGroups?.map((g) => {
上の方で if (currentPage == null のチェックを行っていたので不要でしたm(_ _)m

2023-08-20 13:34 UTC, arafubeatbox commented on apps/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
> +    const grantUserGroupIds = currentPage.grantedGroups?.map((g) => {
Page model の grantedGroups にデフォルト値がなくて、正確には document の grantedGroups が空値があり得たので、デフォルト値を空配列に変更し、.? を削除しました。。

2023-08-20 13:53 UTC, arafubeatbox commented on apps/app/src/components/SavePageControls/GrantSelector.tsx
> +      onUpdateGrant({ grant: 5, grantedGroups: [{ id: grantGroup._id, name: grantGroup.name, type: 'UserGroup' }] });
中途半端ですみませんが、こちらは一時的な処置で https://github.com/weseek/growi/pull/7999 で修正されるため、修正不要としたいです。

2023-08-21 17:38 UTC, arafubeatbox commented on apps/app/src/server/routes/apiv3/page.js
> +      body('grantedGroups').optional().isArray().withMessage('grantedGroups must be an array'),
追加してみました。

2023-08-22 00:02 UTC, jam411 approved these changes

2023-08-23 12:36 UTC, arafubeatbox commented on apps/app/src/server/service/search-delegator/elasticsearch.ts
> +              { terms: { granted_groups: userGroupIds } },
index を作り直し、security:list-policy:hideRestrictedByGroup が true の時所属していないグループが ES の検索結果に表示されないことを確認しました。

2023-08-23 14:04 UTC, yuki-takei requested changes

2023-08-23 14:05 UTC, merged