imprv: Add installed date to questionnaire answer
weseek/growi pull request #7971
Opened 2023-08-09 07:29 UTC by TatsuyaIse

### task
- https://redmine.weseek.co.jp/issues/127459

2023-08-21 06:49 UTC, TatsuyaIse commented on apps/app/test/integration/service/questionnaire-cron.test.ts
> +    });
テストに最古のユーザーが存在する必要があるため追加しています。

2023-08-21 08:34 UTC, yuki-takei requested changes

2023-08-21 08:34 UTC, yuki-takei commented on apps/app/src/features/questionnaire/server/service/questionnaire.ts
> +    const installedAtByOldestUser = users[0].createdAt;
- findOne を使い、かつ null チェックをする(1ユーザーもいないということは有り得ないだろうけれど)

2023-08-21 08:34 UTC, yuki-takei commented on apps/app/src/features/questionnaire/server/service/questionnaire.ts
> +    const appInstalledConfig = await mongoose.model('Config').findOne({ key: 'app:installed' });
mongoose.model ではなく `import Config from '~/server/models/config';` を使ってください

2023-08-28 07:01 UTC, TatsuyaIse commented on apps/app/src/features/questionnaire/server/service/questionnaire.ts
> +    const installedAtByOldestUser = users[0].createdAt;
対応しました。

2023-08-28 08:07 UTC, merged