feat: PDF preview before expand using react-pdf
weseek/growi pull request #7995
Opened 2023-08-17 07:00 UTC by jam411

## Task
- https://redmine.weseek.co.jp/issues/125416

## Outline
- PDF 表示のために [react-pdf](https://www.npmjs.com/package/react-pdf) を使うことにしました.
   - https://npmtrends.com/@phuocng/react-pdf-viewer-vs-@react-pdf/renderer-vs-react-file-viewer-vs-react-pdf
   - https://blog.bitsrc.io/top-react-pdf-libraries-in-2021-d0cfbeccdbf8
- react-pdf 表示のためにライブラリのインポートなどいくつか setup が必要でした. next.config.js を触っています.
   - https://github.com/wojtekmaj/react-pdf#readme
   - https://zenn.dev/kin/articles/658b06a3233e60#react-pdf%E5%88%9D%E6%9C%9F%E8%A8%AD%E5%AE%9A
- その他 
   - TODO タスクの記載 (Expand 後の表示もいけそうでした)
   - デザイン修正
   - リファクタリング

## Screenshot
### reactstrap
![image](https://github.com/weseek/growi/assets/68407388/64fb7681-ff4f-42ba-a245-e43c898d2904)
### マウスオーバー時
![image](https://github.com/weseek/growi/assets/68407388/21214e94-2e1b-41ed-82cd-ffec8c6fb285)

### デザイン後続タスク
- RichAttachment カードのデザインで attachment と pdf attachment したときの共通部分と思われる個所が XD だと変わっているため、fumiya さんに確認予定
- マウスオーバーのしたときの expand の図形を相談予定
- pdf 用の icon を fumiya さんに相談予定

2023-08-18 19:43 UTC, yuki-takei requested changes

2023-08-18 19:43 UTC, yuki-takei commented on apps/app/next.config.js
> +        });
こちらの worker も vite によるファイルコピー＆ import 文なしでいけるのではないか？
(https://github.com/wojtekmaj/react-pdf/issues/136#issuecomment-940584082 を見る限りだが)

ただ、いずれにせよ後続タスクでこの辺のプロセスやら何が何故必要なのかの解説を dev wiki の内部仕様にメモしておきたい

2023-08-18 19:43 UTC, yuki-takei commented on apps/app/next.config.js
> +        );
webpack 設定が魔境になってしまうので、このフォントのコピーに関しては turbo + vite での制御に変えたい。
(apps/app の styles-prebuilt スクリプトを参照)

2023-08-18 19:43 UTC, yuki-takei commented on apps/app/package.json
> +    "react-pdf": "^7.3.3",
devDependencies に移したい。
現状で SSR されているならされないようにする。

2023-08-18 19:43 UTC, yuki-takei commented on apps/app/src/components/ReactMarkdownComponents/RichAttachment.tsx
> +pdfjs.GlobalWorkerOptions.workerSrc = workerPath;
この初期化コードをここに書くのは違う気がするなあ。

## 着眼点整理
- 着眼点A: 実行タイミングの制御ができているか
- 着眼点B-1: サーバーサイドでの実行回数
    - サーバーサイドでは実行はさせたくない
    - react-pdf の README にも書いてあるな
        > Using Pages Router, make sure to [disable SSR](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr) when importing the component you're using this code in.
- 着眼点B-2: クライアントサイドでの実行回数
    - ~~クライアントでは初回1回キリの実行が望ましい~~
    - いや、「1回キリ」にはそこまでこだわらないが、やみくもに再代入されるコードが走るのは気持ち悪い

## 現状
- A
    - Next により複雑にトランスパイルされるような状況でこのコードでは仮に現時点で開発環境での正常動作を確認できていても不安が残る
- B-1
    - このコンポーネントが SSR されないようになっていれば問題ないと言える(その辺はレビューではチェックしていない)
- B-2
    - 今のコードでもおそらく実行は1回だけに留まるのだろうが、module cache が頼りというのはあまり筋が良くない(と個人的には思う)

## 改修案
- custom hook 化し、useEffect (特に useIsomorphicLayoutEffect) で実行する
    - 中のロジックで再代入コードがやたら走らないようにする

### 着眼点について
改修案採用で以下のようになる(はず)

- A
    - useEffect を書くことにより react の世界で解決できる
- B-1
    - useEffect を書くことにより、このコンポーネントが SSR されるかどうかに関係なく解決
    - むしろサーバーサイドでは初期化コードが走らないことにより必ず正常動作しなくなるので、このコンポーネントの利用側の制約として SSR しないことが必須になって望ましい
- B-2
    - プログラマブルな制御になるので望ましい(個人の好みかもしれないが)

2023-09-20 04:04 UTC, jam411 commented on apps/app/src/components/ReactMarkdownComponents/RichAttachment.module.scss
> +    max-height: 150px;
仮置きでした。
TODO コメントを記載しておき、後続タスクで確認します。
https://redmine.weseek.co.jp/issues/128793

2023-09-20 04:04 UTC, jam411 commented on apps/app/package.json
> +    "react-pdf": "^7.3.3",
devDependencies に移動しました。

2024-09-03 12:04 UTC, closed without merging