enable selecting external user group for page grant
weseek/growi pull request #7999
Opened 2023-08-17 12:51 UTC by arafubeatbox

2023-08-28 07:28 UTC, jam411 commented on apps/app/src/components/SavePageControls/GrantSelector.tsx
> +  const groupListItemClickHandler = useCallback((grantGroup: GrantedGroup) => {
この修正と直接関係ないのですが (しかも `type GrantedGroup` で宣言してるんですが), どこかのタイミングで `GrantedGroup` に `I` をつけて `IGrantedGroup` としておきましょうか

2023-08-28 07:28 UTC, jam411 commented on apps/app/src/server/routes/me.js
せっかくなので apiv3 化できないでしょうか？
できればお願いしたいです。

2023-08-29 14:13 UTC, arafubeatbox commented on apps/app/src/components/SavePageControls/GrantSelector.tsx
> +  const groupListItemClickHandler = useCallback((grantGroup: GrantedGroup) => {
https://redmine.weseek.co.jp/issues/129539
で実施します。

2023-08-30 12:01 UTC, arafubeatbox commented on apps/app/src/stores/user-group.tsx
>  }
UserGroupListResult が使いまわせそうでした。

2023-08-30 12:01 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/client/stores/external-user-group.ts
> +}
UserGroupListResult が使いまわせそうでした。

2023-08-30 12:36 UTC, yuki-takei requested changes

2023-08-30 12:36 UTC, yuki-takei commented on apps/app/src/client/services/user-group.ts
> +};
GrantSelector でしか使わないデータ構造なのであれば、コンポーネントの近くに置きたい。例えば以下のような structure で

- components/SavePageControls
    - GrantSelector
        - index.ts ( <-- `export * from './GrantSelector';` )
        - GrantSelector.tsx
        - use-my-user-groups.ts

他コンポーネントから共用するなら src/stores に置く。

2023-08-30 13:33 UTC, arafubeatbox commented on apps/app/src/client/services/user-group.ts
> +};
現状 GrantSelector でしか使う用途が無さそうなので、GrantSelector 配下に移動しました。

また、このファイル内の他のメソッドについては UserGroupDetailPage でしか使われておらず、そもそも client/services 配下にあるのは違和感があるため、UserGroupDetailPage と同じ階層に use-user-group-resource.ts という名前で移動しました。

2023-08-31 12:33 UTC, merged