fix: Pages can be created under a non-existent user page (During attachment upload)
weseek/growi pull request #8001
Opened 2023-08-21 00:35 UTC by miya

## Task
[#125056](https://redmine.weseek.co.jp/issues/125056) [User homapage] `/user/{存在しないusername}/{任意のページ}` でページが作成できてしまう
└ [#128784](https://redmine.weseek.co.jp/issues/128784) attachment をアップロードしてページを作成する時の対応

2023-08-21 08:30 UTC, yuki-takei requested changes

2023-08-21 08:30 UTC, yuki-takei commented on apps/app/src/server/routes/attachment.js
> +      if (isUserPage(pagePath)) {
page-path-utils の isCreatablePage を利用した方がいいのでは？
なにか不都合がある？

2023-08-23 02:47 UTC, miya commented on apps/app/src/server/routes/attachment.js
> +      if (isUserPage(pagePath)) {
isCreatablePage も考慮するように修正しました

2023-08-23 02:50 UTC, miya commented on apps/app/src/server/routes/apiv3/pages.js
> +    }
API 経由で `POST: _api/v3/pages/` にリクエストすると、not creatable なパスを持つページを作成できてしまっていたのでこちらも isCreatablePage を考慮するようにしました。(rename と duplicate は既に対応済み)

2023-08-23 05:25 UTC, merged