Support/128848 fix forms breaking changes
weseek/growi pull request #8006
Opened 2023-08-22 05:28 UTC by soumaeda

2023-08-23 02:49 UTC, jam411 requested changes
やったことに書いてあるものと差分に違いがある。
張り付けてある公式ドキュメントに記載されている事柄（やるべきこと）とやったことに差分がある。
まずは自分がやったことを正確に伝えてほしいです。

2023-08-24 04:15 UTC, jam411 commented on apps/app/src/components/Admin/App/AppSetting.jsx
> +          <div className="form-check form-check-info">
`custom-checkbox` って削除していいんでしょうか？

2023-08-24 05:57 UTC, jam411 commented on apps/app/src/components/Admin/App/AppSetting.jsx
> +                <div key={locale} className="form-check custom-radio form-check-inline">
`.custom-radio` は不要そうなので確認して不要なら削除してください

2023-08-24 05:57 UTC, jam411 commented on apps/app/src/components/Admin/ExportArchiveData/SelectCollectionsModal.tsx
> +    const checkboxColor = color ? `form-check-${color}` : 'form-check-info';
color は form-check-* に統一

2023-08-24 05:57 UTC, jam411 commented on apps/app/src/components/Admin/Users/UserInviteModal.jsx
> +        <div className="col text-left form-check form-check-info text-left" onChange={this.handleCheckBox}>
ついでに余分な text-left クラスを消しておいてください

2023-08-24 05:57 UTC, jam411 commented on apps/app/src/components/LoginForm.tsx
> +              <div>
これなんで削除したんでしょうか？

2023-08-24 06:37 UTC, soumaeda commented on apps/app/src/components/LoginForm.tsx
> +              <div>
これは次タスクのスコープでした。
`.input-group-append` も廃止されたので、削除することになっていますが、スコープ外なので元に戻します

2023-08-24 06:40 UTC, soumaeda commented on apps/app/src/components/Admin/App/AppSetting.jsx
> +          <div className="form-check form-check-info">
v5.3.xの公式ドキュメント[https://getbootstrap.jp/docs/5.3/migration/#%e3%83%95%e3%82%a9%e3%83%bc%e3%83%a0](url)で確認しました。

2023-08-24 07:07 UTC, soumaeda commented on apps/app/src/components/Admin/App/AppSetting.jsx
> +                <div key={locale} className="form-check custom-radio form-check-inline">
`.custom-control.custom-radio` が `.form-check` に変更されているので、`.custom-radio` は削除しました。

2023-08-24 07:26 UTC, merged