Fix/128041 129379 large ldap group tree sync error
weseek/growi pull request #8026
Opened 2023-08-27 23:20 UTC by arafubeatbox

2023-08-29 07:19 UTC, yuki-takei requested changes

2023-08-29 07:19 UTC, yuki-takei commented on apps/app/src/server/service/ldap.ts
> +    return new Promise<void>((resolve, reject) => {
async/await で書き直してほしい

2023-08-29 07:19 UTC, yuki-takei commented on apps/app/src/server/service/ldap.ts
> +    return new Promise((resolve, reject) => {
async/await で書き直してほしい

2023-08-31 11:00 UTC, arafubeatbox commented on apps/app/src/server/service/ldap.ts
> +    return new Promise<void>((resolve, reject) => {
bind 実行時のエラーを event を listen し、コールバックに渡すという実装になっています。
https://github.com/ldapjs/node-ldapjs/blob/bec2ff8e7399155ebdcbf86eec2077a792b8510b/lib/client/client.js#L298

このエラーの内容次第で reject resolve するには、async/await だと記述できなさそうです。
もし FB 内容を読み違えてたらすみません。

2023-08-31 11:01 UTC, arafubeatbox commented on apps/app/src/server/service/ldap.ts
> +        reject(err);
bind していない際のエラーをサービス側で catch できていなかったため、ちゃんと connection エラーが生じた際に reject するように変更しました。

2023-08-31 12:35 UTC, merged