support: Add grid utilities
weseek/growi pull request #8033
Opened 2023-08-29 01:44 UTC by soumaeda

## やったこと
・.form-inline を使用していた箇所は横並びではなくなっているので、親要素に .row 、子要素に .col-auto を追加して、横並びで表示されるようにした。

・sass に .form-inline と .form-group が記述されたままだったので、削除した。

## タスク
https://redmine.weseek.co.jp/issues/129246

## わからない点
AuditLogManagement.tsx で親要素に .row 、子要素に .col-auto を追加し、横並び表示をしようとしたところ「ユーザー名」のフォームのみ横並びにできない。
※ 添付画像参照

<img width="1080" alt="スクリーンショット 2023-08-25 14 43 30" src="https://github.com/weseek/growi/assets/112812878/77d23dde-2878-4b79-82d6-c6ffdad992b8">

2023-08-29 03:45 UTC, jam411 commented on apps/app/src/components/Admin/AuditLog/SelectActionDropdown.tsx
> +    <div className="btn-group me-2 admin-audit-log col-12">
もう一つ上の階層で col-12 で囲えないですか？

2023-08-29 03:45 UTC, jam411 commented on apps/app/src/components/Admin/AuditLogManagement.tsx
> +            <button type="button" className="btn btn-link col-12" onClick={clearButtonPushedHandler}>
ここの col-12 って必要でしょうかね？

2023-08-29 03:48 UTC, jam411 commented on apps/app/src/styles/_override-rbt.scss
これは react-bootstrap-typeahead のスタイルだから今は残しておきたいです。

2023-08-29 03:48 UTC, jam411 commented on apps/app/src/styles/_editor.scss
> -      }
なぜこれは削除したのでしょうか？
scss を少なくして bs に任せるのは賛成なんですが

2023-08-29 04:22 UTC, soumaeda commented on apps/app/src/components/Admin/AuditLogManagement.tsx
> +            <button type="button" className="btn btn-link col-12" onClick={clearButtonPushedHandler}>
"クリア"は col-12 も必要なかったですね。

2023-08-29 04:42 UTC, soumaeda commented on apps/app/src/styles/_override-rbt.scss
元に戻しました

2023-08-29 04:52 UTC, soumaeda commented on apps/app/src/styles/_editor.scss
> -      }
元々使用している箇所がないのと、.table-responsive で横スクロールができるため、不要と判断し削除しました

2023-08-29 05:09 UTC, soumaeda commented on apps/app/src/components/Admin/AuditLog/SelectActionDropdown.tsx
> +    <div className="btn-group me-2 admin-audit-log col-12">
上の階層で .col-12 で囲むと、レスポンシブデザインではアクションボタンのみ左に寄ってしまっているので、.text-center でレスポンシブ時は中央寄せにしました

<img width="981" alt="スクリーンショット 2023-08-29 14 05 08" src="https://github.com/weseek/growi/assets/112812878/1ea209d4-42cb-4e09-99e3-8c26405fa5bb">

<img width="987" alt="スクリーンショット 2023-08-29 14 05 39" src="https://github.com/weseek/growi/assets/112812878/13e9340b-ee22-411e-950c-c79614f7f818">

2023-08-30 03:06 UTC, soumaeda commented
新たにdivタグで囲まず、既存のdivタグに .col-12 を入れることで、element では同一階層で .col-12 があり、ブラウザ上でも問題なく表示されました。

<img width="193" alt="スクリーンショット 2023-08-30 12 04 06" src="https://github.com/weseek/growi/assets/112812878/71bf74ef-a7cb-46d2-8ff4-4fe94fd5e71d">

2023-08-30 12:15 UTC, yuki-takei requested changes

2023-08-30 12:15 UTC, yuki-takei commented on apps/app/src/components/Admin/AuditLog/DateRangePicker.tsx
> +    <div className="col-12 btn-group me-2">
- col 単体での利用は不可
- このコンポーネントをどう並べるかは、親が決めることである

2023-08-30 12:15 UTC, yuki-takei commented on apps/app/src/components/Admin/AuditLog/SelectActionDropdown.tsx
> +    <div className="col-12 btn-group me-2 admin-audit-log">
- col 単体での利用は不可
- このコンポーネントをどう並べるかは、親が決めることである

2023-08-30 12:15 UTC, yuki-takei commented on apps/app/src/styles/_editor.scss
> -      }
ちょっとずれてる。
タグの横スクロールは別途 https://redmine.weseek.co.jp/issues/129277 で実装する必要があるが、その際 `.table-responsive` を使えるわけではない(そもそもテーブルではないので)

2023-08-31 02:36 UTC, soumaeda commented
AuditLogManagement の .row 内でコンポーネントを col で囲むようした。

DateRangePicker で .btn-group が指定されていたが、こちらを削除することで、レスポンシブ時に DateRangePicker が SearchUsernameTypeahead 同様に横いっぱいに表示された。
.btn-group は複数ボタンを囲むためにあるが、DateRangePicker では複数ボタンはないため、不要と判断し、削除した。

2023-08-31 06:28 UTC, merged