feat Create mock for workflow api
weseek/growi pull request #8038
Opened 2023-08-30 02:41 UTC by miya

## Task
[#129415](https://redmine.weseek.co.jp/issues/129415) [approval-workflow] API 設計とモデル実装を行い workflow を作成することができる
└ [#129510](https://redmine.weseek.co.jp/issues/129510) API 設計

2023-09-06 00:25 UTC, miya commented on apps/app/src/server/routes/apiv3/workflow.ts
現状必要な API の新設とそのパラメーターと戻り値の設計を行いました。
引数と戻り値は swagger-jsdoc を使って描きました。コード内の Description と Memo は実装時に参考にするためのメモで最終的には削除します。

2023-09-06 05:33 UTC, yuki-takei requested changes

2023-09-06 05:33 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/workflow.ts
> +  router.post('/create', accessTokenParser, loginRequired, validator.createWorkflow, apiV3FormValidator, async(req: RequestWithUser, res: ApiV3Response) => {
post method が作成を意味するので、endpoint に create という文字列は入れなくてもいいかな

2023-09-06 05:33 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/workflow.ts
> +      body('approverGroups').isArray().withMessage('approverGroups is required'),
ここ考えどころだな

- name, comment は空でも許容していいかも
- approverGroups は必須なのか、一旦空でも作成可能なのかは UI による
    - XD レベルで固められているのか？

2023-09-06 05:33 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/workflow.ts
> +    });
- PUT /:workflowId にしたい
    - 口頭で FB するので聞きに来て

2023-09-06 05:33 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/workflow.ts
> +    });
- PUT /:workflowId/status にするか…？
    - 用途による
    - 口頭で FB したいので聞きに来て

2023-09-07 07:37 UTC, miya commented on apps/app/src/server/routes/apiv3/workflow.ts
> +  router.post('/create', accessTokenParser, loginRequired, validator.createWorkflow, apiV3FormValidator, async(req: RequestWithUser, res: ApiV3Response) => {
修正しました

2023-09-07 07:39 UTC, miya commented on apps/app/src/server/routes/apiv3/workflow.ts
> +      body('approverGroups').isArray().withMessage('approverGroups is required'),
- name, comment は optional にしました (fumiya-s, hiromu-t と合意済み)
- approverGroups は XD レベルで固められてはいないので一旦このままになっています (optional にするのであれば後から optional にするでも良いと思いました)

2023-09-07 22:59 UTC, yuki-takei approved these changes

2023-09-07 22:59 UTC, merged