imprv: Indent with tab
weseek/growi pull request #8039
Opened 2023-08-30 03:26 UTC by reiji-h

# 概要
- Tab でインデントを増やし、Shift + Tab でインデントを減らす
- インデントの個数を変えることができる

# Task
- https://redmine.weseek.co.jp/issues/126529
  - https://redmine.weseek.co.jp/issues/129067

2023-08-31 06:54 UTC, jam411 reviewed
- 管理画面からインデント数を変更しても 2 で固定化されている（動作確認してもそうだった）
![image](https://github.com/weseek/growi/assets/68407388/3905b424-f3e7-4d9a-be2e-4f4033644f1d)
- ~~This is test sentence
ってエディタに文字列があったとして test ぐらいにカーソルもってきて tab 押すと先頭が改行されるんですが期待通りでしたか？~~(v6 でもそうだったからこれはよさそう）
- 管理画面からのインデント無効化はまだできないと理解したんですが後続タスク作っておいてください。武井さんと話せてるなら大丈夫です。

2023-09-13 03:50 UTC, jam411 requested changes
ショートカットキーによるインデント幅が 2 に固定されている.
windows なら `ctrl + ]` など

2023-09-13 05:40 UTC, jam411 approved these changes

2023-09-13 06:36 UTC, yuki-takei requested changes

2023-09-13 06:36 UTC, yuki-takei commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +      },
コード内コメントを書いてください(英語)

- react-codemirror のプリセットの設定を排除する必要があることと、その理由

2023-09-13 07:54 UTC, reiji-h commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +      },
コメントを記述しました。マージします。

2023-09-13 07:54 UTC, merged