support: Revoke well classes
weseek/growi pull request #8041
Opened 2023-08-30 09:39 UTC by soumaeda

## やったこと
- bootstrap4 以降から廃止された(.card に置き換わった) .well を削除した。
- .well はカスタムスタイルとして利用されていたが、bg-light で同じ見た目を作れた
- bs には box-shadow: inset; の代替がないため、sass の .card.shadow-inset を利用して、card 内側に shadow がスタイルされるようにした。

- CopyDropdown と RevisionComparer では .well (カスタムクラス) でfont-size を指定していたので、.well から .card-font にclass名を変更しました。

## タスク
https://redmine.weseek.co.jp/issues/129279

## 参考
https://getbootstrap.com/docs/5.2/components/card/#about

## 変更後の card

<img width="502" alt="スクリーンショット 2023-08-30 18 48 09" src="https://github.com/weseek/growi/assets/112812878/87c550d7-2705-4fc7-b51f-35bcf848cfd0">

<img width="1089" alt="スクリーンショット 2023-08-30 18 49 47" src="https://github.com/weseek/growi/assets/112812878/d38ae105-5985-49d5-8b20-bdf35a6931ff">

2023-08-31 04:22 UTC, jam411 requested changes

2023-08-31 04:22 UTC, jam411 commented on apps/app/resource/locales/en_US/sandbox-bootstrap4.md
`sandbox-bootstrap4.md` はクリーンインストール時に使用されるサンプルファイルなので変更せずそのままにしておいてください。

2023-08-31 04:22 UTC, jam411 commented on apps/app/resource/locales/ja_JP/sandbox-bootstrap4.md
同上

2023-08-31 04:22 UTC, jam411 commented on apps/app/resource/locales/zh_CN/sandbox-bootstrap4.md
同上

2023-08-31 04:22 UTC, jam411 commented on apps/app/src/styles/theme/apply-colors.scss
> -  border-color: var(--light);
これらを消すと theme が有効化されたときに当たらなくなる気がします。

2023-08-31 04:22 UTC, jam411 commented on apps/app/src/components/RevisionComparer/RevisionComparer.module.scss
>          word-break: break-all;
`.card-font` を作らずに `.card` ってすると上書きされてしまうんでしたっけ？事足りるなら `.well` も `.card` に統合されたので `.card` に追加スタイルをあてたい.
`.card` にまとめる場合は module.scss の範囲内で他クラスに影響がないかだけ確認お願いします。

2023-08-31 04:22 UTC, jam411 commented on apps/app/src/components/Page/CopyDropdown.module.scss
> +    .card-font {
こちらも同様に確認してみてください。

2023-08-31 05:32 UTC, soumaeda commented on apps/app/src/components/RevisionComparer/RevisionComparer.module.scss
>          word-break: break-all;
他の箇所にも影響がなかったので、.card に置き換えました。

2023-08-31 05:32 UTC, soumaeda commented on apps/app/src/components/Page/CopyDropdown.module.scss
> +    .card-font {
こちらも影響がなかったので、.card に置き換えました

2023-08-31 06:02 UTC, soumaeda commented
- sassで .well としていた箇所は .custom-card に変更した。

- 現状、border-color: var(--light); は有効でないため、.card (旧 .card.well )は画像のような見た目になっている。

<img width="504" alt="スクリーンショット 2023-08-29 12 48 44" src="https://github.com/weseek/growi/assets/112812878/929c3e42-abd9-415d-a24a-4478ef0c19b0">

2023-08-31 07:04 UTC, jam411 requested changes
- _apply-colors-dar.scss にも well が残っているからコメントしておいてください。

2023-08-31 07:04 UTC, jam411 commented on packages/core/scss/bootstrap/_override.scss
>  // // Well (substitute Well of bootstrap3)
このコメント（コード上の）が Well についてのコメントのままだから、この[コメントアウトを外すタスク](https://redmine.weseek.co.jp/issues/128307)実施時に、混乱するかもしれないので well クラスを custom-card に置き換えたことを https://redmine.weseek.co.jp/issues/128307 のタスク番号と一緒に追加コメントしておいてください。

2023-08-31 08:14 UTC, jam411 commented on apps/app/src/styles/theme/_apply-colors-dark.scss
> +  // // TODO: Use .custom-card instead of Well
クラスであることがわかるように `Well` ではなく `.well` にしておいてください

2023-08-31 08:25 UTC, jam411 commented on packages/core/scss/bootstrap/_override.scss
> +// // https://redmine.weseek.co.jp/issues/128307
ごめんこれやっぱりなしで大丈夫です。
`Well (substitute Well of bootstrap3)`
でわかると思うので

2023-08-31 08:35 UTC, soumaeda commented
コメントアウトされている sass 中の .well については、コメントアウトを外す際に .well も書き換えるようにするので、その旨のコメントを残しました。

2023-08-31 08:43 UTC, jam411 commented on packages/core/scss/bootstrap/_override.scss
> +// .card.well {
.well のままにするなら .custom-card に置き換わったことのコメントが必要だと思う

2023-09-01 02:03 UTC, soumaeda commented on packages/core/scss/bootstrap/_override.scss
> +// .card.well {
.well を .custom に置き換える旨のコメントを追加しました

2023-09-01 03:45 UTC, jam411 approved these changes

2023-09-01 06:11 UTC, yuki-takei requested changes

2023-09-01 06:11 UTC, yuki-takei commented on apps/app/src/styles/theme/_apply-colors-dark.scss
> +  // https://redmine.weseek.co.jp/issues/128307
dark mode 時の実装しないとじゃない？

2023-09-06 05:25 UTC, merged