imprv: Correspond prohibited characters
weseek/growi pull request #8043
Opened 2023-08-31 03:37 UTC by soumaeda

## 概要
OSで禁止されている文字を含んでいる、あるいはOSで制限されている文字数を超えたファイル名でエクスポートする場合は、禁則文字の置換や文字数の省略をして対応する。

2023-09-06 07:58 UTC, jam411 requested changes

2023-09-06 07:58 UTC, jam411 commented on apps/app/src/server/routes/apiv3/page.js
> +      .replace(/\.$/, '_');
`.md` に反応して、禁止文字でなくてもファイル名末尾が `_` に置き換えられるようです。
![image](https://github.com/weseek/growi/assets/68407388/0249642d-640f-4303-9307-c617f7d93715)

2023-09-11 03:52 UTC, soumaeda commented
```
長いベージ名（81文字以上）をエクスポートすると、ファイル名が80文字以内になる（81文字以降は省略）が、原因がわからない。

OS でファイル名を255文字以下に制限されているが、80文字のファイル名を使うケースはあまりなく、81文字以上のファイル名をつけたい場合は、ユーザーがファイル名を変更するだけなので、md 形式でエクスポートする場合のファイル名は、このまま80文字以下の制限がかかっているままで良いかと思います。

```
不明点で述べた内容についてですが、実際には半角の場合は244文字、全角の場合は80文字に省略されたファイル名でエクスポートされます。

## 調べた内容
- サーバーデバッグでエクスポートするファイル名に文字数制限をかける記述はありませんでした。
- UTF-8 でエンコーディングする場合、半角が1バイト、全角が3バイトとされるため、長いページ名の場合は全角の場合と半角の場合でファイル名の文字数が変わってしまうのではないかと考えています。

2023-09-12 02:52 UTC, jam411 approved these changes

2023-09-12 02:52 UTC, merged