imprv: Ignore GROWI's CSS in Marp slides.
weseek/growi pull request #8056
Opened 2023-09-04 08:22 UTC by reiji-h

# 概要
- GROWI 固有の CSS がスライドの描画にも反映され、Marp 本来の見た目にならない問題を解決
- その他リファクタなど
# Task
- https://redmine.weseek.co.jp/issues/129384
  - https://redmine.weseek.co.jp/issues/129401
  - https://redmine.weseek.co.jp/issues/129931
# 補足
- CSS 適用のため追加、修正
   - `src/components/Presentation/Slides.tsx`
   - `src/components/ReactMarkdownComponents/SlideViewer.tsx`
- リファクタ
   - `growi-marpit.ts`

2023-09-05 05:39 UTC, jam411 commented on packages/presentation/src/components/Slides.module.scss
> +}
このCSSセレクタは適用できているんでしたっけ？
該当箇所がわからず調べられなかった。

2023-09-05 05:39 UTC, jam411 commented on packages/presentation/src/services/growi-marpit.ts
>    ],
空配列を入れておく必要はありますかね？

2023-09-06 02:57 UTC, reiji-h commented on packages/presentation/src/components/Slides.module.scss
> +}
現状だと適用されていなかったので、適用されるように修正しました。

2023-09-06 02:57 UTC, reiji-h commented on packages/presentation/src/services/growi-marpit.ts
>    ],
必要はなかったので削除する形で修正しました。

2023-09-06 07:16 UTC, jam411 approved these changes

2023-09-06 08:07 UTC, yuki-takei requested changes

2023-09-06 08:07 UTC, yuki-takei commented on packages/presentation/src/components/Slides.module.scss
> +}
reset が目的というコメントをコード内に追加してください

2023-09-06 09:47 UTC, reiji-h commented on packages/presentation/src/components/Slides.module.scss
> +}
Marp を正常にレンダリングするためにリセットする旨をコメントに書きました。

2023-09-06 09:49 UTC, merged