feat: Modal for displaying a list of workflows
weseek/growi pull request #8060
Opened 2023-09-06 03:28 UTC by miya

## Task
[#129420](https://redmine.weseek.co.jp/issues/129420) [approval-workflow] ワークフローを作成できる
└ [#130001](https://redmine.weseek.co.jp/issues/130001) [client] ワークフロー作成ボタンとワークフロー作成画面の実装
└ [#130000](https://redmine.weseek.co.jp/issues/130000) [client] ワークフロー一覧を表示するモーダルの実装

2023-09-06 10:09 UTC, miya commented on apps/app/src/components/Navbar/SubNavButtons.tsx
> +      );
XD 通りに WideViewMenuItem の下にコミュニケーション機能関連の dropdown item が表示されるようにした

2023-09-06 10:09 UTC, miya commented on apps/app/src/stores/modal.tsx
> +};
modal 関連の SWR

2023-09-06 10:09 UTC, miya commented on apps/app/src/components/Workflow/WorkflowListPage.tsx
> +};
- ワークフロー一覧画面用のコンポーネント

## XD
<img width="611" alt="ScreenShot 2023-09-06 19 02 12" src="https://github.com/weseek/growi/assets/34241526/a4e3fce1-5879-4d10-88af-705209913d18">

2023-09-06 10:09 UTC, miya commented on apps/app/src/components/Workflow/CreateWorkflowPage.tsx
> +};
- 新規作成画面
- XD には「戻る」ボタンは存在しないが、ページごとに「戻る」ボタンを設置することになったので適当な場所に置いている (fumiya-s と合意している)

## XD 
<img width="612" alt="ScreenShot 2023-09-06 19 04 55" src="https://github.com/weseek/growi/assets/34241526/5c97790b-f8ce-4a90-a213-4ce21c67f7bb">

2023-09-06 10:09 UTC, miya commented on apps/app/src/components/Workflow/WorkflowModal.tsx
> +export default WorkflowModal;
- ページ内の三点ボタンの中にある workflow の dropdown item を押下したときに表示されるモーダル
- 一覧画面や新規作成画面など、モーダル内でページ遷移するように実装する
- ワークフロー一覧画面が初期画面

2023-09-07 22:57 UTC, yuki-takei requested changes

2023-09-07 22:57 UTC, yuki-takei commented on apps/app/src/components/Navbar/SubNavButtons.tsx
> +          <WideViewMenuItem {...props} onClickMenuItem={switchContentWidthClickHandler} expandContentWidth={expandContentWidth} />
props を union にするなら `{...props}` のように横着するのはよくない

2023-09-07 22:57 UTC, yuki-takei commented on apps/app/src/components/Navbar/SubNavButtons.tsx
> +
- SubNavButtons 肥大化してきてるので、CommunicationMenuItems や WideViewMenuItem は別モジュール(ファイル)にわけよう
- SubNavButtons ディレクトリをつくり、その中に全部入れる
- SubNavButtons/index.ts で export するものは限定する

2023-09-08 01:36 UTC, miya commented on apps/app/src/components/Navbar/SubNavButtons.tsx
> +
以下のコンポーネントと対応する scss ファイルを SubNavButtons ディレクトリ配下に移動させました
- LikeButtons,
- SeenUserInfo,
- SubscribeButton
- BookmarkButtons
- WideViewMenuItem
- CommunicationMenuItems


こちらは何を限定すれば良いかが不明でした..
> SubNavButtons/index.ts で export するものは限定する

2023-09-08 01:36 UTC, miya commented on apps/app/src/components/SubNavButtons/LikeButtons.tsx
> -export default LikeButtons;
named export に変更

2023-09-08 01:37 UTC, miya commented on apps/app/src/components/Navbar/SubNavButtons.tsx
> +          <WideViewMenuItem {...props} onClickMenuItem={switchContentWidthClickHandler} expandContentWidth={expandContentWidth} />
修正しました

2023-09-08 04:27 UTC, yuki-takei requested changes

2023-09-08 04:27 UTC, yuki-takei commented on apps/app/src/components/SubNavButtons/index.ts
外から使う必要があるものだけに絞ってください

2023-09-11 01:36 UTC, merged