Imprv/128163 export md with page name
weseek/growi pull request #8061
Opened 2023-09-06 03:33 UTC by soumaeda

2023-09-13 04:07 UTC, jam411 commented on apps/app/src/server/routes/apiv3/page.js
> +      .replace(/\.$/, '_');
`/` ページは `md` というファイル名でエクスポートされます。
どうしたらいいかな。思いつかない。。
いい案がなければ fumiya-s さん武井さんに相談してみてほしいです。

2023-09-13 07:15 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/page.js
> +      .replace(/\.$/, '_');
/ページについては、_top.md としてエクスポートされるようにしました

以下、相談時のslackのリンクです
https://wsgrowi.slack.com/archives/C0111HG81GB/p1694581737092079

2023-09-14 00:27 UTC, jam411 requested changes

2023-09-14 00:27 UTC, jam411 commented on apps/app/src/server/routes/apiv3/page.js
> +    }
- この処理は何をやっているかコメントを書いておいてほしいです。 
  - ~ を ~ に書き換える. 
  - 参照元 など

2023-09-14 11:20 UTC, yuki-takei requested changes

2023-09-14 11:20 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page.js
> +    if (!fileName) {
if ブロックの判定をガイドライン通りに

2023-09-14 11:20 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page.js
> +  const path = require('path');
ファイルの冒頭で import してください (require ではなく)

2023-09-14 11:20 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page.js
> +      .replace(/\.$/, '_');
これ使った方がいいような気がする
https://www.npmjs.com/package/sanitize-filename

ソースコードまで確認して、ベターだと判断できればこちらに差し替えてください

2023-09-20 05:36 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/page.js
> +      .replace(/\.$/, '_');
windowsOSの予約語も置換できるため、こちらを利用することにしました

2023-09-22 02:22 UTC, soumaeda commented on apps/app/src/server/routes/apiv3/page.js
> +    if (!fileName) {
ガイドラインに従って、ifブロックの判定を `fileName == null` で行おうとしましたが、fileNameが空のとき、nullとして扱われないため、 `if (fileName === '')`で対応しました

2023-09-25 12:39 UTC, merged