feat: Implement endpoints to create workflow
weseek/growi pull request #8065
Opened 2023-09-08 02:41 UTC by miya

## Task
[#129420](https://redmine.weseek.co.jp/issues/129420) [approval-workflow] ワークフロー作成画面を実装しワークフローデータを作成できる
└ [#129998](https://redmine.weseek.co.jp/issues/129998) [server] ワークフローを作成するためのエンドポイントの実装

2023-09-11 15:46 UTC, yuki-takei requested changes

2023-09-11 15:46 UTC, yuki-takei commented on apps/app/src/server/models/workflow.ts
features/ の下に全部のファイルを集めてほしい

2023-09-11 15:46 UTC, yuki-takei commented on apps/app/src/server/service/workflow.ts
> +    this.crowi = crowi;
なるべく crowi オブジェクトに依存させずに済ませたい。
AclService を参考に singleton instance を export するようにしてほしい。

2023-09-11 15:46 UTC, yuki-takei commented on apps/app/test/integration/models/workflow.test.ts
今後インテグレーションテストは Jest ではなく Vite + mongodb-memory-server で書いて行きたい。
モデルのテストは features/growi-plugin/server/models/growi-plugin.integ.ts を参考にして。
インテグレーションテストに関する設定ファイルは以下。

- vitest.config.integ.ts
- test-with-vite/*

2023-09-11 15:46 UTC, yuki-takei commented on apps/app/src/server/service/workflow.ts
> +  async createWorkflow(creatorId: string, pageId: string, name: string, comment: string, approverGroups: IWorkflowApproverGroup[]): Promise<IWorkflow> {
引数は IWorkflow instance そのものを取った方がシンプルかなあ。
そのオブジェクトの status は INPROGRESS 以外でもいいよね。下書き状態のものは作れていいわけだし。

2023-09-11 15:46 UTC, yuki-takei commented on apps/app/src/server/crowi/index.js
> +    this.setupWorkflowService(),
できればこのセットアップ不要にしたい。

2023-09-11 15:46 UTC, yuki-takei commented on apps/app/src/server/service/workflow.ts
> +  validateApproverGroups(isNew: boolean, creatorId: string, approverGroups: IWorkflowApproverGroup[]): void {
どちらかといえばこのメソッドには単体テストを用意したい

2023-09-11 15:46 UTC, yuki-takei commented on apps/app/test/integration/service/workflow.test.ts
> +    });
このテストケースはインテグレーションテストとして残して良い

2023-09-11 15:46 UTC, yuki-takei commented on apps/app/test/integration/service/workflow.test.ts
> +    });
ここから下は単体テストにする

2023-09-12 01:08 UTC, miya commented on apps/app/src/server/crowi/index.js
> +    this.setupWorkflowService(),
singleton instance を export  したことによって不要になったため削除しました

2023-09-12 06:59 UTC, miya commented on apps/app/src/server/service/workflow.ts
> +  validateApproverGroups(isNew: boolean, creatorId: string, approverGroups: IWorkflowApproverGroup[]): void {
用意しました

2023-09-12 06:59 UTC, miya commented on apps/app/test/integration/service/workflow.test.ts
> +    });
対応しました。

2023-09-12 07:00 UTC, miya commented on apps/app/test/integration/service/workflow.test.ts
> +    });
対応しました。

2023-09-12 07:04 UTC, miya commented on apps/app/src/server/models/workflow.ts
>  features/ の下に全部のファイルを集めてほしい

ワークフロー機能関連のソースコード (server, client 含め) をfeatures/ 配下に全部移動するという理解です。(参考: features/growi-plugin )
こちらに関しては、今現在出しているワークフロー機能の PR がマージされた後に行いたいと思います (コンフリクトしそうなので)

2023-09-13 07:09 UTC, yuki-takei requested changes

2023-09-13 07:09 UTC, yuki-takei commented on apps/app/src/server/models/workflow.integ.ts
- 単体テストにする場合は workflow.spec.ts にする
- MongoDB へのデータ保存はできないので、hasInprogressWorkflowInTargetPage に渡す引数は適当なインスタンスを作るか、もしくは mock オブジェクトを作る

2023-09-13 16:54 UTC, miya commented on apps/app/src/interfaces/workflow.ts
> +  pageId: ObjectIdLike,
テストしやすい型に変更

例)
https://github.com/weseek/growi/blob/63f951297d6b3fc6a43a8f5293436a8c98af030c/apps/app/src/server/service/workflow.integ.ts#L16

2023-09-13 16:54 UTC, miya commented on apps/app/src/server/models/workflow.ts
> +WorkflowSchema.statics.hasInprogressWorkflowInTargetPage = async function(pageId: ObjectIdLike) {
こちらもテストしやすい型に変更

2023-09-14 07:18 UTC, yuki-takei requested changes

2023-09-14 07:18 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/workflow.ts
> +    const xssProcessedComment = crowi.xss.process(comment);
今更だけど crowi.xss (src/server/service/xss.js) は使う必要ない気がする。なぜなら API routes で利用するとコンフィグ値とかで無効化されてしまうので。(他の API routes からの利用も同様)

src/services/xss を直接インポートして使えばいい。

2023-09-14 09:03 UTC, merged