feat: Implement endpoint to retrieve the workflow list
weseek/growi pull request #8066
Opened 2023-09-11 02:16 UTC by miya

## Task
[#129958](https://redmine.weseek.co.jp/issues/129958) [approval-workflow] ページ内に存在するワークフロー一覧を表示できる
└ [#130272](https://redmine.weseek.co.jp/issues/130272) [server] workflow 一覧を返却する API の実装

2023-09-11 05:45 UTC, miya commented on apps/app/src/server/models/workflow.ts
> +WorkflowSchema.plugin(mongoosePaginate);
- クライアントではワークフロー一覧を無限スクロールさせる予定なので `mongoose-paginate-v2` を利用してページングできるようにしている

2023-09-11 15:52 UTC, yuki-takei requested changes

2023-09-12 00:13 UTC, miya commented on apps/app/src/server/routes/apiv3/workflow.ts
> +      const User = crowi.model('User');
修正しました

2023-09-12 00:13 UTC, miya commented on apps/app/src/server/routes/apiv3/workflow.ts
> +    const limit = req.query.limit || await crowi.configManager?.getConfig('crowi', 'customize:showPageLimitationS') || 10;
修正しました

2023-09-13 07:05 UTC, merged