support: Use new accordion
weseek/growi pull request #8071
Opened 2023-09-11 23:42 UTC by soumaeda

2023-09-13 04:14 UTC, jam411 commented on apps/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
こちら `①` -> `1` になぜ変更したのでしょうか？
CustomBotWithoutProxySettingsAccordion.jsx のほうは `①` のままなので気になりました。

2023-09-13 04:22 UTC, jam411 reviewed
collapse したあとのこの影はデフォルトでつくようですね。。

![image](https://github.com/weseek/growi/assets/68407388/9d252a0e-14f7-40e7-8b5e-8407ebcbc458)

2023-09-13 04:29 UTC, jam411 commented on apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> +    <div className="accordion border-0 overflow-hidden">
`.border-0` と `.overflow-hidden` は必要でしょうか？

2023-09-13 04:29 UTC, jam411 commented on apps/app/src/components/Admin/Common/Accordion.jsx
> +    <div className="accordion-item mb-0">
`mb-0` も必要でしょうか？

2023-09-13 04:29 UTC, jam411 commented on apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
> +                        <div className="accordion-item p-1">
`p-1` も必要ければ削除しておいてください

2023-09-14 02:11 UTC, soumaeda commented
あああ

2023-09-14 03:02 UTC, soumaeda commented
> こちら ① -> 1 になぜ変更したのでしょうか？CustomBotWithoutProxySettingsAccordion.jsx のほうは ① のままなので気になりました。
> officialBotIntegrationProcedure も ① のまま
こちらについては、fumiya-s さんに相談させていただいた際に、全角ではなく、半角数字にしたいとのことだったので変更しました。
officialBotIntegrationProcedure についても変更を加えました。

以下が話した内容のリンクです。
https://wsgrowi.slack.com/archives/C05HK5SA8CC/p1694503807399349?thread_ts=1694499309.003259&cid=C05HK5SA8CC

2023-09-14 03:04 UTC, soumaeda commented
SamlSecuritySettingContents.jsx 内の .p-1 ですが、fumiya-s さんに相談し、デザイン的(特にcollapse した場合)にp-1 を残しておいた方が良かったので、こちらは削除せずに残すことにしました

2023-09-14 03:11 UTC, jam411 requested changes
>     こちら ① -> 1 になぜ変更したのでしょうか？CustomBotWithoutProxySettingsAccordion.jsx のほうは ① のままなので気になりました。
>     officialBotIntegrationProcedure も ① のまま
>     こちらについては、fumiya-s さんに相談させていただいた際に、全角ではなく、半角数字にしたいとのことだったので変更しました。
>     officialBotIntegrationProcedure についても変更を加えました。
> 
> 以下が話した内容のリンクです。
> https://wsgrowi.slack.com/archives/C05HK5SA8CC/p1694503807399349?thread_ts=1694499309.003259&cid=C05HK5SA8CC

こちら変更理由が、「①②③…が全角の機種依存なのでこれを機に半角数字にできたらと思いました」だとよみとったんですが、だとするとほかの全角の機種依存も変更したほうがいいのでは？

2023-09-14 07:43 UTC, soumaeda commented
## 修正点
①②③...と、全角の機種依存を使用している箇所については、半角数字を使うようにしました。

2023-09-19 02:47 UTC, jam411 approved these changes

2023-09-21 12:24 UTC, yuki-takei requested changes

2023-09-21 12:24 UTC, yuki-takei commented on apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
> +                        <div className="accordion-item p-1">
元のコードが悪いんだけど、477行目の「accordionExample」という id は不適切なので変えておいてください

2023-09-22 02:58 UTC, merged