Feat/123280 130394 keycloak group sync exec
weseek/growi pull request #8072
Opened 2023-09-12 01:12 UTC by arafubeatbox

2023-09-12 01:16 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/interfaces/external-user-group.ts
> +  keycloakGroupSyncClientRealm: string
Admin API を叩くために使用する client について

client 名は情報として不要でした。
client が所属する realm は、master realm に限定されないため、指定できるようにしました。

2023-09-12 01:18 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/interfaces/external-user-group.ts
> +  keycloakGroupSyncClientRealm: string
補足)
'master realm にある client' ではなく、'manage-users が与えられている client' がユーザ/グループに関する Admin API を叩けるという仕様でした。
https://keycloak.discourse.group/t/using-keycloak-admin-apis-without-using-master-realm-user-details/13001

2023-09-12 01:26 UTC, arafubeatbox commented on apps/app/package.json
> +    "@s3pweb/keycloak-admin-client-cjs": "^22.0.1",
keycloak Admin API に OAuth 認証し、叩くためのライブラリです。
これは公式ライブラリ https://www.npmjs.com/package/@keycloak/keycloak-admin-client の fork になります。

apps/app 内は commonJS にコンパイルされるため、公式の方は https://github.com/keycloak/keycloak-nodejs-admin-client/issues/523 の issue が原因で、使用できません。

このまま fork 元を使うか、API 叩く部分を自作するかは迷い中ですが、後続タスクで自作する、に傾いています。

2023-09-14 01:04 UTC, jam411 approved these changes
動作確認必要であればまた依頼してください。

2023-09-16 10:58 UTC, yuki-takei requested changes

2023-09-16 10:58 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/admin.json
> +      "group_sync_client_realm": "Admin API を叩くための Client がある Realm",
「叩く」って表現は慣用的すぎるね

2023-09-16 10:58 UTC, yuki-takei commented on apps/app/package.json
> +    "@s3pweb/keycloak-admin-client-cjs": "^22.0.1",
next.config.js の getTranspilePackages に列挙したらいけないかな。
当該パッケージが依存してるもののなかに esm only のものがあったらそれも含め全部載せないといけないからそこそこ大変だけど。

2023-09-16 11:05 UTC, yuki-takei requested changes

2023-09-16 11:05 UTC, yuki-takei commented on apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group.ts
> +    if (authProviderType == null) return res.apiv3Err('external_user_group.keycloak.auth_not_set', 500);
error object に i18n のキーをそのまま載せるだけというのはちょっと不親切。

```
res.apiv3Err(new ErrorV3(message, code), 500);
```

のようにして、クライアントでは code から 18n message を解決するようにしてください。

2023-09-17 05:59 UTC, merged