feat: Workflow list page
weseek/growi pull request #8077
Opened 2023-09-14 04:58 UTC by miya

## Task
[#129958](https://redmine.weseek.co.jp/issues/129958) [approval-workflow] ページ内に存在するワークフロー一覧を表示できる
└ [#130302](https://redmine.weseek.co.jp/issues/130302) [client] workflow 一覧を表示を表示する画面の実装
└ [#130304](https://redmine.weseek.co.jp/issues/130304) [client] GET: /workflow/list/:pageId をリクエストするための fetcher とその SWR の実装

2023-09-16 11:20 UTC, yuki-takei requested changes

2023-09-16 11:20 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/CreateWorkflowPage.tsx
> +  mutateWorkflows: () => void;
イベントハンドラの命名規則に忠実に

- onPersisted or onCreated などのメソッド名にする
- optional にする

2023-09-16 11:20 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/CreateWorkflowPage.tsx
> +      mutateWorkflows();
今リファクタする必要はないが、createWorkflow メソッドを swr custom hook と連携させれば作成後の mutate 処理はそちらで完結できる。
swr custom hook の中で create メソッドを定義して withUtils とかで一緒に export してもいいし、最近追加された useSWRMutation は用途的に今回のケースにマッチする。

2023-09-16 11:20 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/stores/workflow.ts
> +};
useSWRImmutable はオプションを工夫しないとモーダルを再度開いた時に revalidate が走らない

2023-09-19 09:48 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/CreateWorkflowPage.tsx
> +  mutateWorkflows: () => void;
`onCreated` に修正しました

2023-09-19 09:49 UTC, miya commented on apps/app/src/features/approval-workflow/client/stores/workflow.ts
> +};
useSWR に変更しました (特にオプションはいじっていないです)

2023-09-19 09:55 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/WorkflowModal.tsx
> +  const { data: workflowPaginateResult, mutate: mutateWorkflows } = useSWRxWorkflowList(workflowModalData?.pageId, 1, 0);
- 初期実装時は「1ページに1ワークフロー」という制約になったので、limit: 1 , offset: 0 を渡しています
- 上記制約の実装は https://redmine.weseek.co.jp/issues/130893 で行います

2023-09-21 10:52 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/CreateWorkflowPage.tsx
> +      mutateWorkflows();
TODO コメントをつけました

2023-09-21 12:33 UTC, yuki-takei requested changes

2023-09-21 12:33 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/stores/workflow.ts
> +  const key = pageId != null ? `/workflow/list/${pageId}` : null;
limit, offset もキーに含めないと意図しないキャッシュが返る

2023-09-21 12:33 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/stores/workflow.ts
> +    endpoint => apiv3Get<{paginateResult: IWorkflowPaginateResult}>(endpoint, { limit, offset }).then(result => result.data.paginateResult),
apiv3Get に渡す limit, offset は fetcher の引数(に入ってくるキー構成要素)から取るべき

2023-09-21 15:04 UTC, miya commented on apps/app/src/features/approval-workflow/client/stores/workflow.ts
> +  const key = pageId != null ? `/workflow/list/${pageId}` : null;
修正しました

2023-09-21 15:04 UTC, miya commented on apps/app/src/features/approval-workflow/client/stores/workflow.ts
> +    endpoint => apiv3Get<{paginateResult: IWorkflowPaginateResult}>(endpoint, { limit, offset }).then(result => result.data.paginateResult),
修正しました

2023-09-21 15:15 UTC, merged