Imprv/129542 129840 show sync status on external group sync
weseek/growi pull request #8089
Opened 2023-09-18 02:32 UTC by arafubeatbox

2023-09-18 02:39 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +abstract class ExternalUserGroupSyncService<SyncParamsType = any> {
isExecutingSync というステータスをグローバルにアクセス可能にするために、結局同期サービスを singleton 化することにしました。

LdapUserGroupSyncService では同期実行時に bind のための username, password の受け渡しが必要で、元々は constructor で渡していたのですが、singleton 化によりできなくなりました。
そのため、継承するメソッド syncExternalUserGroups, generateExternalUserGroupTrees に params という引数を指定できるようにしました。
params の型が、SyncParamsType という generics になります。

2023-09-18 02:39 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +  isExecutingSync = false;
同期実行が複数走ると、多くのリソースが同時アクセス対象となる可能性があると共に、重い処理が複数走る可能性があるため、isExecutingSync が true の時は実行できない仕様にしました。

2023-09-18 02:40 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +  isExecutingSync = false;
例えば keycloak 同期が走っている時は、ldap も keycloak 同期も実行できません。
また、他のユーザが実行中の時も実行できません。

2023-09-18 03:16 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/keycloak-user-group-sync.ts
> -  constructor(authProviderType: string) {
authProviderType は同期実行時に判別されるため、service が singleton 化されることによって、コンストラクタでを渡せなくなります。

2023-09-18 03:19 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/keycloak-user-group-sync.ts
> -  constructor(authProviderType: string) {
authProviderType は親クラスの ExternalUserGroupSyncService のプロパティですが、
ExternalUserGroupSyncService での authProviderType のコンストラクタでの初期化もやめています。

2023-09-18 03:23 UTC, arafubeatbox commented on apps/app/src/server/service/ldap.ts
> +  initClient(userBindUsername?: string, userBindPassword?: string): void {
constructor で ldap serverUrl を精査して、不適切だったらエラーが生じる仕様でしたが、ldap service を使用する service が singleton 化されたので、growi 起動時に ldap serverUrl が設定されていなければエラーが出るようになってしまいました。

そのため、constructor での初期化はやめ、メソッドを用意しました。

2023-09-21 05:52 UTC, jam411 commented on apps/app/src/features/external-user-group/client/components/ExternalUserGroup/SyncExecution.tsx
> +  }, [socket, mutateExternalUserGroups, t, provider]);
コンポーネントがアンマウントされたときのクリーンアップは不要でしょうか？

例えば、
```
useEffect(() => {
  if (socket == null) return;

  const eventName = SocketEventName.externalUserGroup[provider];
  
  const handleGroupSyncProgress = (data) => {
    setSyncStatus(SyncStatus.syncExecuting);
    setProgress({
      total: data.totalCount,
      current: data.count,
    });
  };

  const handleGroupSyncCompleted = () => {
    setSyncStatus(SyncStatus.syncCompleted);
    mutateExternalUserGroups();
    toastSuccess(t('external_user_group.sync_succeeded'));
  };

  const handleGroupSyncFailed = () => {
    setSyncStatus(SyncStatus.syncFailed);
    mutateExternalUserGroups();
    toastError(t('external_user_group.sync_failed'));
  };

  socket.off(eventName.GroupSyncProgress);
  socket.off(eventName.GroupSyncCompleted);
  socket.off(eventName.GroupSyncFailed);

  socket.on(eventName.GroupSyncProgress, handleGroupSyncProgress);
  socket.on(eventName.GroupSyncCompleted, handleGroupSyncCompleted);
  socket.on(eventName.GroupSyncFailed, handleGroupSyncFailed);

  return () => {
    socket.off(eventName.GroupSyncProgress, handleGroupSyncProgress);
    socket.off(eventName.GroupSyncCompleted, handleGroupSyncCompleted);
    socket.off(eventName.GroupSyncFailed, handleGroupSyncFailed);
  };
}, [socket, mutateExternalUserGroups, t, provider]);
```

それとも実行前に socket.off しているのでそれで充分なのか。

2023-09-22 01:47 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/client/components/ExternalUserGroup/SyncExecution.tsx
> +  }, [socket, mutateExternalUserGroups, t, provider]);
グループページから他のページに移動した後でも、同期完了/失敗通知が流れてくる方が良いかなと思いましたが、
例えば
1. admin A がグループページで同期を実行
2. admin B がグループページに移動
3. admin B が別ページに移動し、A の実行した同期が完了されたことが通知される
というのは B にとって違和感がありそうなので、クリーンアップで良い気がしました。

2023-09-22 02:01 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/client/components/ExternalUserGroup/SyncExecution.tsx
> +  }, [socket, mutateExternalUserGroups, t, provider]);
補足) A と B の event を独立させるということもあまりしたくなくて、同期実行が共有されているプロセス（一度に A と B 両方が実行できない）である以上、B がグループページにいる時は同期進捗を表示して欲しいんですよね。

2023-09-22 02:14 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/client/components/ExternalUserGroup/SyncExecution.tsx
> +  }, [socket, mutateExternalUserGroups, t, provider]);
ただの共有)
一応 [Room](https://socket.io/docs/v4/rooms/#joining-and-leaving) を使えば event ごとに個人に通知するのか broadcast するのか切り替えできそうですが、個人に room の id を設定できるように SocketIo service の実装を改修をするなどが必要そうですね。

2023-09-22 02:47 UTC, jam411 approved these changes

2023-09-23 17:18 UTC, yuki-takei requested changes

2023-09-23 17:18 UTC, yuki-takei commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +  isExecutingSync = false;
S2sMessageHandlable で検索して、ある app server で同期実行が走った際に並列で動いている別の app server の isExecutingSync の T/F を切り替える処理を入れてほしい

2023-09-23 17:18 UTC, yuki-takei commented on apps/app/src/features/external-user-group/server/service/keycloak-user-group-sync.ts
> +}
パッと見あまり歓迎できない仕組み。。
(代案をすぐ出せるわけではないが)

2023-09-24 04:48 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +  isExecutingSync = false;
対応しました。

2023-09-24 04:51 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/keycloak-user-group-sync.ts
> +  }
シングルトン化を行ったことにより、constructor 以外で実行する必要がある初期化処理が、同期実行メソッド内に隠蔽されていることが問題に見えたので、
SyncParamsType を取り除いて、init メソッドで、明示的に初期化処理を定義してみました。

2023-09-24 04:51 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/ldap-user-group-sync.ts
> +  }
シングルトン化を行ったことにより、constructor 以外で実行する必要がある初期化処理が、同期実行メソッド内に隠蔽されていることが問題に見えたので、
SyncParamsType を取り除いて、init メソッドで、明示的に初期化処理を定義してみました。

2023-09-24 04:52 UTC, arafubeatbox commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +  isExecutingSync = false;
ちなみに、こちらの実装の動作確認はどのように行っていますか？

2023-09-24 14:23 UTC, yuki-takei commented on apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
> +  isExecutingSync = false;
まず nchan サーバーを立てる

[/Tips/開発用のnchanサーバーセットアップ](https://dev.growi.org/5f16c6d5ec75070048deecdb)

開発中の app をそれに繋げて、まずは当該 app からメッセージが発信されることをテスト。
次に別の app からのメッセージをハンドリングできるかをテストするために、上記セットアップページにある「ホストから手動で Publish する」でシミュレートする。

2023-09-24 14:27 UTC, merged