feat: Unit test implementation of serialize workflow securely
weseek/growi pull request #8101
Opened 2023-09-22 03:00 UTC by miya

## Task
[#130307](https://redmine.weseek.co.jp/issues/130307) [approval-workflow] ワークフロー一覧画面からワークフロー詳細画面に遷移できる
└ [#131160](https://redmine.weseek.co.jp/issues/131160) [server] serializeWorkflowSecurely の単体テスト実装

2023-09-22 14:39 UTC, miya commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.spec.ts
> +      expect(mocks.serializeUserSecurelyMock).toHaveBeenCalled();
- serializeWorkflowSecurely が内部で依存している serializeUserSecurely を mock 化
- serializeWorkflowSecurely が呼ばれた時に serializeUserSecurely  が正常に呼ばれるかテストしている

2023-09-23 17:40 UTC, yuki-takei requested changes

2023-09-23 17:40 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.spec.ts
> +      const workflow = mock<IWorkflowHasId>({ approverGroups: [] });
serializeWorkflowSecurely の第二引数を入れないなら、approverGroups 内の user も serialize されることをテストしないといけないので、空配列にするのは望ましくない。

2023-09-23 17:40 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.spec.ts
> +      expect(mocks.serializeUserSecurelyMock).toHaveBeenCalled();
厳密なテストを書くなら、creator と approvers 内の user 全てが serializeUserSecurelyMock からの返り値で置き換わることを expect しないといけない。
このモジュールのテストとしてはあまり推奨はしないが、最小限の怠惰なテストで済ませるにしてもメソッドが呼ばれる回数くらいはチェックしないと。

2023-09-27 07:24 UTC, miya commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.spec.ts
> +      const workflow = mock<IWorkflowHasId>({ approverGroups: [] });
第二引数を false にするテストと第二引数を true にするテストを作成し、それぞれダミーのデータを入れ serialize できるように修正しました

2023-09-27 12:26 UTC, yuki-takei requested changes

2023-09-28 03:21 UTC, miya commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.spec.ts
> +    vi.spyOn(mongoose, 'model').mockReturnValue(DummyUser);
修正しました

2023-09-29 09:28 UTC, yuki-takei requested changes

2023-09-29 09:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.spec.ts
> +} from '../../../interfaces/workflow';
タイプは type-only import にしてください

2023-09-29 09:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.spec.ts
> +import { serializeWorkflowSecurely } from './workflow-seroalizer';
ファイル名の typo を直して欲しい
`workflow-seroalizer`

2023-09-29 09:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.spec.ts
> +      expect(serializedWorkflow.approverGroups[0].approvers[0].user.apiToken).toBeUndefined();
serializeUserSecurelyMock の呼び出し回数を expect でチェックしてほしい

2023-09-29 09:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.spec.ts
> +      });
呼び出しに対していつもその動きをするはずなので、mockImplementationOnce ではなく mockImplementation でいいと思う

2023-09-29 09:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.spec.ts
> +      } as IWorkflowHasId;
- approverGroups は複数にして、全て処理されることを確認する
- approvers も同様に

2023-09-29 12:36 UTC, merged