imprv: Support to attach some files  in editor
weseek/growi pull request #8103
Opened 2023-09-22 05:51 UTC by reiji-h

2023-09-27 04:01 UTC, jam411 requested changes
一応こちらでもコメントで、オーバレイ実装するかどうかから uiux で確認して必要であればタスク切っておきますか。

2023-09-27 05:23 UTC, reiji-h commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +        // const { pageId, path } = pageContainer.state;
削除しました。

2023-09-27 05:24 UTC, reiji-h commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +        // modify to "![fileName](url)" syntax
インデントを合わせました。

2023-09-27 05:25 UTC, reiji-h commented on apps/app/src/components/PageEditor/PageEditor.tsx
>     * @param {any} file
削除しました。

2023-09-27 06:11 UTC, reiji-h commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +  const uploadHandler = useCallback((args: File | File[]) => {
`File` になる場合を考えましたが、特になかったので `File[]` にするように修正しました。

2023-09-27 06:26 UTC, reiji-h commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-text.ts
> +  }, [view]);
すぐ出てきませんが、これが近いです。
https://codemirror.net/examples/change/

2023-09-27 07:24 UTC, jam411 requested changes

2023-09-27 07:24 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-text.ts
> +};
- replaceSelection() を使うと範囲指定したうえで attachment を attach したときに上書きされたりしないですかね？
- text を insert する場面はほかのタスクでもあるし useInsertText は他 editor 機能でも使うだろうことを意識して useInsertText を作る必要があると思う.
- useInsertText というメソッド名で replaceSelection() を使っていいか検討してほしい. refs として送ってくれたドキュメントを見ると changes の insert で代替できるかもしれない.

2023-09-27 08:48 UTC, reiji-h commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-text.ts
> +};
replaceSelection は replaceText という別の形で作成し、insertText として changes を使って代替しました。これにより、選択していようと現在存在するカーソルの位置にファイルの文字列が来るようになりました。

2023-09-27 09:10 UTC, jam411 commented on packages/editor/src/components/playground/Playground.tsx
> +      const insertText = `[${file.name}](/attachment/aaaabbbbccccdddd)\n`;
消し忘れだろうか？

2023-09-27 09:10 UTC, jam411 commented on packages/editor/src/components/playground/Playground.tsx
> +            indentSize={4}
これは必要？

2023-09-27 09:10 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/replace-text.ts
replaceText は今回使わないし, 今後はどこかで使うのかな?
確定してなければ僕は消してしまうかな.
せっかくなのであってもいいとは思いますが...
お任せします

2023-09-27 09:47 UTC, reiji-h commented on packages/editor/src/components/playground/Playground.tsx
> +      const insertText = `[${file.name}](/attachment/aaaabbbbccccdddd)\n`;
playground でも upload の機能が使えることを示すためにあってもいいのかなと思い残しました。

2023-09-27 09:47 UTC, reiji-h commented on packages/editor/src/components/playground/Playground.tsx
> +            indentSize={4}
playground でも upload の機能が使えることを示すためにあってもいいのかなと思い残しました。

2023-09-27 09:47 UTC, reiji-h commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/replace-text.ts
後続のタスクですぐ使うので残しておきます。

2023-09-27 12:32 UTC, yuki-takei requested changes

2023-09-27 12:32 UTC, yuki-takei commented on packages/editor/src/components/playground/Playground.tsx
> +      const insertText = `[${file.name}](/attachment/aaaabbbbccccdddd)\n`;
チームメイトにデバッグコードだと思われるということは、コード内になんのためのコードか書いておくべきということだ

2023-09-27 12:32 UTC, yuki-takei commented on packages/editor/src/services/dropzone-editor/use-dropzone-editor.ts
> +export const useDropzoneEditor = (props: DropzoneEditor): DropzoneState => {
命名がいまいち。このモジュール内に editor 要素はないよね？
useDropzoneForCodeMirrorEditor ってことかな？(この名前にせよということではないが)

2023-09-28 15:01 UTC, reiji-h commented on packages/editor/src/components/playground/Playground.tsx
> +      const insertText = `[${file.name}](/attachment/aaaabbbbccccdddd)\n`;
ファイルアップロードのデモで、ダミーのファイル名を使用することをコメントしました。

2023-09-28 15:14 UTC, reiji-h commented on packages/editor/src/services/dropzone-editor/use-dropzone-editor.ts
> +export const useDropzoneEditor = (props: DropzoneEditor): DropzoneState => {
useFileDropzoneという名前にしました。そのほかだと
- useDropFile
- useDropzoneForEditor
などがあるのかなと思っています。

2023-09-29 10:11 UTC, yuki-takei requested changes

2023-09-29 10:11 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
> +  fileOpen: () => void,
onFoo で統一。つまり onFileOpen などが望ましい。

2023-10-04 09:38 UTC, reiji-h commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
> +  fileOpen: () => void,
onFileOpen で統一しました。

2023-10-04 11:21 UTC, merged