imprv: Prepare dummy HighlightStyle
weseek/growi pull request #8111
Opened 2023-09-25 05:58 UTC by soumaeda

# 概要
codemirror6にバージョンアップしたことで、エディタ画面で #(接頭辞) をつけてもフォントサイズが変わらなくなった。

# やったこと
https://0xsuk.github.io/posts/2022-03-25-build-your-own-markdown-editor-with-react.js-and-codemirror-6/
こちらを参考に、HighlightStyleを用意し、tagsを使ってheaderにスタイルを適用できるようにするための準備をしました。

# Task
https://redmine.weseek.co.jp/issues/130149

# 後続Task
https://redmine.weseek.co.jp/issues/131167
https://redmine.weseek.co.jp/issues/131239

2023-09-25 06:22 UTC, jam411 requested changes
後続タスクで使うから lint エラーをそのままにしていると思うけど、基本的は CI が落ちている状態でレビュー依頼するのは望ましくないです。
やはりタスクの粒度が小さすぎたことが原因だと思うから、`syntaxHighlighting` を適用するところまでで PR 出してください。

2023-09-25 06:22 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
> +    }
このようにすれば scss で fontSize 指定しなくてもいけませんか？
```
const markdownHighlighting = HighlightStyle.define([
  { tag: tags.heading1, fontSize: "1.6em", fontWeight: "bold" },
  {
    tag: tags.heading2,
    fontSize: "1.4em",
    fontWeight: "bold",
  },
  {
    tag: tags.heading3,
    fontSize: "1.2em",
    fontWeight: "bold",
  },
]);
```

理想は scss をなくすことだと思うので、CodeMirror 6 で賄えるなら scss を使うよりもいいと思います。

2023-09-25 07:05 UTC, soumaeda commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
> +    }
HighlightStyleを定義するときに、style指定するようにしました。

fontSizeについては、Growi v6のエレメントを見て、同じ大きさに設定しました。

2023-09-25 07:09 UTC, soumaeda commented
このPRで syntaxHighlighting を適用するところまで行うことにしました。

https://redmine.weseek.co.jp/issues/131167
こちらの後続タスクにて、エディタで#をつけると要素に期待したクラスが当てられるようにします。

2023-09-25 09:06 UTC, jam411 requested changes

2023-09-25 09:06 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +  syntaxHighlighting(markdownHighlighting),
平木さんからのタレコミで
```
Extension 周りに限った話ですが、Extension は優先度を変えない限り先に追加したものが適用されます。なので Codemirror6 か react-codemirror が先に syntax 周りの Extension を定義している場合 syntaxHighlighting は適用されないかもしれません。
```
とのこと、検証してみてほしいです。

2023-09-28 06:58 UTC, soumaeda commented
## 修正点
・Playground.tsx で動かすとカスタムsyntaxHighlightingが適用されていて、本体(PageEditor.tsx)ではデフォルトのままだったが、packages/editor/package.json の devDependencies に @codemirror/language を入れると本体でもカスタムsyntaxHighlightingが適用された。

・defaultHighlightStyleの優先度を低く設定した。(カスタムsyntaxHighlightingはheaderレベルに応じてフォントサイズを変えるので、header以外についてはdefaultHighlightStyleが適用される。)

2023-09-28 07:05 UTC, jam411 commented on packages/editor/package.json
> +    "@codemirror/language": "^6.0.0",
devDependencies に追加する処理がなぜ必要なのか, これをすることで何がどう変わるのか言えるようにしてほしい.
`@codemirror/commands` は追加せずともなぜ使えているのか.
指定した version が `^6.0.0` な理由も.

2023-09-28 07:05 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +]);
Screenshot を張ってほしいです。
細かいデザインがこれでいいかは後続タスクで確認する認識でいます。

2023-09-28 07:48 UTC, soumaeda commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +]);
Screenshot貼りました。
後続タスクにてデザイン相談をします。

2023-09-29 01:35 UTC, soumaeda commented on packages/editor/package.json
> +    "@codemirror/language": "^6.0.0",
開発に @codemirror/language が必要にも関わらず、devDependencies に @codemirror/language を含めていなかったため、カスタムしたsyntaxHighlighting が動作していなかったので、devDependencies に@codemirror/languageを追加しました。
バージョンについては、最新の6.9.1 にしました。

2023-09-29 04:22 UTC, jam411 commented on packages/editor/package.json
> +    "@codemirror/language": "^6.0.0",
`@codemirror/language` は `~/packages/editor/package.json` の devDependencies に加える前から node_modules 配下にあって、参照もできていたはず（VSCode 上で lint エラーがなかったはず)。
なぜ、当該ライブラリを devDependencies に加えないと「カスタムしたsyntaxHighlighting が動作していなかった」んだろう。

2023-10-03 00:05 UTC, soumaeda commented on packages/editor/package.json
> +    "@codemirror/language": "^6.0.0",
@codemirror/languageがすでにnode_module配下にあるため、プロジェクトの依存関係として機能している可能性がありますが、devDependenciesに追加されていないため開発環境で動かなかったのではないかと思います。

## 参考
https://mo-gu-mo-gu.com/about-dependencies-devdependencies/

2023-10-03 00:44 UTC, jam411 approved these changes

2023-10-04 10:12 UTC, yuki-takei requested changes

2023-10-04 10:12 UTC, yuki-takei commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +]);
スタイル指定ではなくクラスを付与すべき

2023-10-05 01:53 UTC, soumaeda commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +]);
classを付与し、CodeMirrorEditor.module.scssでスタイル指定することで、headerレベルに応じてfont-sizeが変わるようにしました

2023-10-05 02:50 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +]);
fontWeight: 'bold' は不要？

2023-10-05 03:21 UTC, jam411 commented
次回から PR の説明欄を最新状態に保つ

2023-10-05 03:21 UTC, merged