feat: Allow transition to workflow detail page
weseek/growi pull request #8112
Opened 2023-09-25 09:37 UTC by miya

## Task
[#130307](https://redmine.weseek.co.jp/issues/130307) [approval-workflow] ワークフロー一覧画面からワークフロー詳細画面に遷移できる
└ [#130922](https://redmine.weseek.co.jp/issues/130922) [client] 一覧画面から詳細画面への動線を作成し、クリックした時に詳細画面に遷移できるようにする

2023-09-25 13:57 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/WorkflowModal.tsx
> +  }, [mutateWorkflows]);
ワークフロー作成後の処理

2023-09-25 13:57 UTC, miya commented on apps/app/src/features/approval-workflow/client/services/workflow.ts
> +    return createWorkflow;
作成直後に `POST: /workflow` のレスポンス結果を取得する必要があるので戻り値を返却するようにした

2023-09-27 11:54 UTC, yuki-takei requested changes

2023-09-27 11:54 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowCreationPage.tsx
> +export const WorkflowCreationPage = (props: Props): JSX.Element => {
Page という接尾辞は Next の pages でよく使われるものなので変えたい。
以前のPRでも違和感を一応は感じていたのをスルーしたのだが、今回改めて感じたので。

2023-09-27 11:54 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/services/workflow.ts
> +    return createWorkflow;
createdWorkflow という state を持つあたり、この hook の設計がいまいちな感じする。

return される createWorkflow というメソッドが API response の戻り値を返すのは別にいいのだが、そのメソッドを提供する factory である useCreateWorkflow が、単一の IWorkflowHasId を保持するのは違和感。

2023-09-27 11:58 UTC, yuki-takei commented
モーダル内の遷移に違和感があるのでブラッシュアップしてもらいたい。

- empty 状態の list で「作成する」導線となるボタン(またはリンク)は必須だが、現状の UI があまりよくない気がする
    - modal footer にボタンがあると detail の UI と酷似しているので
    - modal body にもうちょっと違う表現で置けないか？デザイナーに相談する案件かもしれない
- create で作成後、detail ではなく list に遷移してはどうか？

2023-09-29 08:40 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowCreationPage.tsx
> +export const WorkflowCreationPage = (props: Props): JSX.Element => {
~ModalContent という接尾辞に修正しました。

2023-09-29 08:49 UTC, miya commented on apps/app/src/features/approval-workflow/client/services/workflow.ts
> +    return createWorkflow;
あまり state で管理するメリットを感じなかったため、SWR のカスタムフックにしました

2023-09-29 09:20 UTC, miya commented
> モーダル内の遷移に違和感があるのでブラッシュアップしてもらいたい。
> 
> * create で作成後、detail に遷移するのは違和感
>   
>   * list に遷移してはどうか？
> * empty 状態の list で「作成する」導線となるボタン(またはリンク)は必須だが、現状の UI があまりよくない気がする
>   
>   * modal footer にボタンがあると detail の UI と酷似しているので
>   * modal body にもうちょっと違う表現で置けないか？デザイナーに相談する案件かもしれない
>   * こちらは後続ストーリーでも構わない

2023-09-29 09:28 UTC, miya commented
> モーダル内の遷移に違和感があるのでブラッシュアップしてもらいたい。
> 
> * create で作成後、detail に遷移するのは違和感
>   
>   * list に遷移してはどうか？

確かにワークフロー作成直後に作成者が詳細を見るというケース (作成直後は承認者が見ることが多そう) は少なそうなので一旦 list に遷移するように修正しました。

> * empty 状態の list で「作成する」導線となるボタン(またはリンク)は必須だが、現状の UI があまりよくない気がする
>   
>   * modal footer にボタンがあると detail の UI と酷似しているので
>   * modal body にもうちょっと違う表現で置けないか？デザイナーに相談する案件かもしれない
>   * こちらは後続ストーリーでも構わない

こちらと、create 後の遷移先も後続タスクで fumiya-s, hiromu-t と相談して進めようと思います

2023-10-03 10:18 UTC, merged