feat: implement endpoints for approving workflows
weseek/growi pull request #8115
Opened 2023-09-26 01:19 UTC by miya

## Task
[#130335](https://redmine.weseek.co.jp/issues/130335) [approval-workflow] ワークフロー詳細画面から承認者のステータスを更新することができる
└  [#131344](https://redmine.weseek.co.jp/issues/131344) [server] PUT: /:workflowId/status (承認時) のロジック実装

2023-09-27 12:22 UTC, yuki-takei requested changes

2023-09-27 12:22 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/workflow.ts
> +};
コードをよく見てインテグレーションテストが本当に必要かどうかを考えよう。
findApprover は単体テストでいいのではないか？

2023-09-27 12:22 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/workflow.ts
> +WorkflowSchema.methods.isFinalApprover = function(approverId: string): boolean {
isFinalApprover も再検討を。こちらもざっと見た感じ単体テストでよさそうだが、本当にインテグレーションテストが必要なら書いてもよい。

2023-09-27 12:22 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/routes/apiv3/workflow.ts
> +        return res.apiv3({});
なにかしら処理の結果は返したい

2023-09-27 12:22 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +  async approve(workflowId: ObjectIdLike, operatorId: string): Promise<void> {
せっかく Workflow, WorkflowGroup, WorkflowApprover とモデルが別れているのにその利を活かせていない。インターフェースに対する実装になっていない。

mongoose との兼ね合いで WorkflowApprover と WorkflowGroup を IApprovable として取り扱うのを断念したと思うが、その影響がここで出ている。もう一度その辺をよく考えてこのサービスメソッドの詳細設計をして。

WorkflowApprover を approve すると、その親である WorkflowGroup のステータスが決まる(本来なら IApprovable の入れ子として無限に親を遡ってそういった処理が行われるのだが)。
その結果、root にあたる Workflow のステータスが決まる。

2023-09-28 09:28 UTC, miya commented on apps/app/src/features/approval-workflow/server/models/workflow.ts
> +WorkflowSchema.methods.isFinalApprover = function(approverId: string): boolean {
isFinalApprover メソッド自体不要だったので消しました

2023-09-28 09:29 UTC, miya commented on apps/app/src/features/approval-workflow/server/routes/apiv3/workflow.ts
> +        return res.apiv3({});
処理結果の document を返却するように修正しました

2023-09-28 09:51 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +  async approve(workflowId: ObjectIdLike, operatorId: string): Promise<void> {
root にあたる Workflow model に isApproved というインスタンスメソッドを持たせ、最後の ApproverGroup の appeoverGroup.isApproved が true になった時に Workflow のステータスが "APPROVE" になるように修正しました。

operator が最後の承認者かどうかは判断する必要はなかったので isFinalApprver() は消しました。

2023-09-29 09:49 UTC, yuki-takei requested changes

2023-09-29 09:49 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/workflow.ts
> +};
> インスタンスメソッドなので、インスタンス化 (new Workflow()) して DB にデータが保存される必要があると思い

これって正しい？普通に `new Workflow()` して呼べばいいだけだと思っていたが。

別解としては、findApprover を個別 function にして export してそれをテストする方法や、あるいは findApprover をいっそのことモジュール化して export しそれをテストするという手もある。その場合は新規に workflow ディレクトリを作ってその中に閉じ込める。

2023-09-29 09:49 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +  }
このメソッドは、例外処理を除いたロジックは以下程度しか書かないようにする。

```
let updatedApproverGroup;

// IApprovable 実装である ApproverGroup に処理を任せる
for (const approverGroup in approverGroups) {
  if (approverGroup.hasApprover(operatorId) {
    approverGroup.approve(operatorId);  // この先、ApproverGroup 内部では当然子供の IApprovable に処理が委譲される
    updatedApproverGroup = approverGroup;
    break;
  }
}

// Workflow のステータスを更新
workflow.updateStatus(updatedApproverGroup);
```

単体テストでは ApproverGroup や Workflow のモックを用意し、それらのメソッドが呼ばれるかどうかをテストする。

今書いている統合テストはあってもよい。

2023-11-16 01:30 UTC, closed without merging