feat: 126520 emoji features 1
weseek/growi pull request #8125
Opened 2023-09-29 08:35 UTC by WNomunomu

2023-10-18 07:48 UTC, miya commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +  codeMirrorEditor: UseCodeMirrorEditor | undefined
`codeMirrorEditor? : seCodeMirrorEditor` という書き方の方がシンプルそう

2023-10-18 07:48 UTC, miya commented on apps/app/package.json
> +    "emoji-mart": "npm:panta82-emoji-mart@^3.0.1",
devDependencies に既に入っているんだけどひつようなのかな？

2023-10-19 07:38 UTC, yuki-takei requested changes

2023-10-19 07:38 UTC, yuki-takei commented on apps/app/src/components/PageComment/CommentEditor.tsx
> +import { useResolvedTheme } from '@growi/editor/src/stores/use-resolved-theme';
src から読むのは NG (production で動かない)

2023-10-19 07:38 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +import type { UseCodeMirrorEditor } from 'src';
src からの import は NG

2023-10-19 07:38 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +  codeMirrorEditor?: UseCodeMirrorEditor
あまり UseCodeMirrorEditor インスタンスをリレーしたくない。

## 改修案
EmojiButton 側で useCodeMirrorEditorIsolated を使って引っ張ってきてほしい。その引数に必要な swr key にあたるものを props で渡すようにできないかな。

PlaygroundController.tsx を参考に。

無理がありそうだったら相談してほしい。

2023-10-19 07:38 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +        <Modal isOpen={isOpen} toggle={toggle} backdropClassName="emoji-picker-modal" fade={false}>
open していない場合は Picker をレンダリングしないようにしたい。
fade させないのであれば Modal すらレンダリングしなくていいかも。

2023-10-19 07:38 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +  };
カーソル移動の度にこの closure が更新されるような気がしているので、もしそうであれば抑制したい。

もしくは契機を抑制できない場合、つまりカーソル移動の度に再生成するのをしょうがないと妥協するのであれば、中身を工夫して計算を少なくしたい。isOpen が false の場合は計算する必要もないはずなので。

また、useMemo でメモ化する選択肢もありそう。

2023-10-19 07:38 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +  const selectEmoji = (emoji: { colons: string }): void => {
useCallback を使う

2023-10-19 07:38 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +            onSelect={(emoji: any) => selectEmoji(emoji)}
新たに closure を作るのではなく、selectEmoji をそのまま入れればよくないかな

2023-10-19 07:38 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +  const translation = getEmojiTranslation();
再レンダリングコストが無駄なのでメモ化するか、もしくは EmojiButton の外で作っておく

因みにサブパッケージなので `import { useTranslation } from 'react-i18next';` が使えないということなのだろうか？
そうであればアーキテクチャ的に問題があるなあ。後続ストーリーを作っておいてほしい。

2023-10-19 07:38 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
> +import type { UseCodeMirrorEditor } from 'src';
src からの import は NG

2023-10-19 07:38 UTC, yuki-takei commented on apps/app/src/components/PageComment/CommentEditor.tsx
> +  const { mutate: mutateResolvedTheme } = useResolvedTheme();
本体側からするとやっぱりこの行が一瞬なんだ？ってなるので、hook の名前を変えて useResolvedThemeForEditors にしよう。

最終的にはこの行は

`const { mutate: mutateResolvedThemeForEditors } = useResolvedThemeForEditors();`

のようにする。

2023-10-26 11:38 UTC, yuki-takei requested changes

2023-10-26 11:38 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +              onSelect={(emoji: any) => selectEmoji(emoji)}
https://github.com/weseek/growi/pull/8125#discussion_r1365042800 が直ってないね

2023-10-26 11:38 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +  };
これは未対応？

2023-10-26 11:38 UTC, yuki-takei commented on packages/editor/src/@types/declaration.d.ts
> +declare module 'emoji-mart';
これ必要なのか？原因が分からないなら相談して。

2023-10-26 11:38 UTC, yuki-takei commented on packages/editor/src/stores/use-resolved-theme.ts
> +  };
useCallback を使って欲しい

それからこれってそもそも正常動作するのか？global mutate を使っているのに `'resolvedTheme'` がキーに指定されていないようだが。

2023-10-31 10:01 UTC, yuki-takei requested changes

2023-10-31 10:01 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
> +    }
このメソッドでも `!isOpen` を見て早期リターンする

2023-11-01 07:33 UTC, merged