feat: Implement endpoints for updating approver groups
weseek/growi pull request #8132
Opened 2023-10-02 05:50 UTC by miya

## Task
[#131556](https://redmine.weseek.co.jp/issues/131556) [approval-workflow] ワークフロー編集画面からワークフローを編集できる
└ [#131561](https://redmine.weseek.co.jp/issues/131561) [server] PUT: /:workflowId のロジックを作成

2023-10-02 12:38 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +    };
- 一番末端に存在している承認済みの approverGroup より後を編集可能な approverGroups として抽出
- クライアントサイドから送られてきたデータ

2023-10-03 11:01 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +  validateApproverGroups(isNew: boolean, creatorId: string, approverGroups: IWorkflowApproverGroupReq[]): void {
- creatorId を ObjectIdLike から string に変更
- `new ObjectId("64e4116aaa753ef87f07374d")` や `64e4116aaa753ef87f07374d` が混在してしまうため

2023-10-03 11:22 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +        }
a

2023-10-03 11:30 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +        }
削除しようとしている approverGroup に承認済みの approver がいないかのチェックをする必要がありました。修正します。

2023-10-05 13:54 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +  }
- approverGroup を新規作成するメソッド
- Workflow.approvers の配列の index を指定し作成

2023-10-05 13:54 UTC, miya commented on apps/app/src/features/approval-workflow/interfaces/workflow.ts
> +}
既存の approverGroup をアップデートする際にクライアントから渡されるデータ型

2023-10-05 13:54 UTC, miya commented on apps/app/src/features/approval-workflow/interfaces/workflow.ts
> +}
新規に approverGroup を作成する際にクライアントから渡されるデータ型

2023-10-06 07:50 UTC, yuki-takei requested changes

2023-10-06 08:45 UTC, miya commented on apps/app/src/features/approval-workflow/server/models/workflow.ts
> +  for (let i = 0; i < apprverGroupsLength; i++) {
ありがとうございます。修正しました。

2023-10-16 07:05 UTC, merged