feat: 126521 emoji features 2
weseek/growi pull request #8137
Opened 2023-10-03 06:51 UTC by WNomunomu

2023-10-30 10:53 UTC, miya commented on packages/editor/src/services/codemirror-editor/use-emoji-autocompletion/use-emoji-autocompletion.ts
> +});
これをそのまま export すれば良さそう？

2023-10-31 09:54 UTC, yuki-takei requested changes

2023-10-31 09:54 UTC, yuki-takei commented on packages/editor/src/stores/emojiAutocompletionSettings.ts
stores は swr を利用した global variables を入れる場所にしたいので、これは他の場所に移してください。

実態は codemirror の extension だと思うので、services/extensions ディレクトリを作ってもいいかもしれない

2023-10-31 09:54 UTC, yuki-takei commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +          emojiAutocompletionSettings,
defaultExtensions に含んでいいんじゃないかな

2023-10-31 09:54 UTC, yuki-takei commented on packages/editor/src/stores/emojiAutocompletionSettings.ts
> +    validFor: /^:\w{2,}$/,
この正規表現はモジュール変数に入れておく(上でも使っているので)

また、2文字以上入力した時に働くという挙動の説明をコード内コメントとして入れておいてください

2023-11-01 08:18 UTC, merged