support: Apply colors and fix layout in login page
weseek/growi pull request #8145
Opened 2023-10-06 07:35 UTC by soumaeda

# 概要
v7 ログイン画面がapply-colorsの廃止に伴い装飾されていない状態なので、代替のmodule.scssでライトモードとダークモード時の配色をする。また、一部のLayoutが崩れているので修正

# やったこと
### 背景色の適用
  - v6 では`apply-colors-light.scss`、`apply-colors-dark.scss`でライトモードとダークモードのログイン画面の背景色を設定していたが、それらが廃止されたため、`NoLoginLayout.module.scss`内で`apply-colors-light.scss`、`apply-colors-dark.scss`で行っていたライトモードとダークモードのログイン画面背景色を設定した。
 
###  レイアウトの修正
  - bootstrap5 では `.col` にposition: relative; が適用されなくなってしまい、growi.orgのリンクがログインフォーム外の下の方に表示されてしまっていたので、`.position-relative`を追加して修正した。
 
  - `input-group`のレイアウトが崩れていたが、bootstrap5へのバージョンアップでinput-group内に`<div className="input-group-prepend">`が不要になってにも関わらず、divタグだけが残っていたままだったので、余計なdivタグを削除することでレイアウト崩れを修正した。`

  - bootstrap5 では expand するとき、data-target ではなく data-bs-target としなければならず、data-targetとしていた箇所をdata-bs-target に修正しました。

# Task
https://redmine.weseek.co.jp/issues/131644
https://redmine.weseek.co.jp/issues/132193

# デザイン確認Slack
https://wsgrowi.slack.com/archives/C05HK5SA8CC/p1696914825500399

# Screen Shot
<img width="364" alt="スクリーンショット 2023-10-10 14 47 59" src="https://github.com/weseek/growi/assets/112812878/d5d24756-5baa-4d79-be74-45baf882b690">
<img width="361" alt="スクリーンショット 2023-10-10 14 48 19" src="https://github.com/weseek/growi/assets/112812878/2c09306f-3143-4247-8b56-8ada0bb7d270">
<img width="1268" alt="スクリーンショット 2023-10-10 14 12 25" src="https://github.com/weseek/growi/assets/112812878/400000be-505c-47b7-b564-198cebb04f26">
<img width="365" alt="スクリーンショット 2023-10-10 16 12 22" src="https://github.com/weseek/growi/assets/112812878/21fce742-78e5-4be6-972b-b6ae47a1680d">

2023-10-10 07:19 UTC, jam411 commented on apps/app/src/components/Layout/NoLoginLayout.module.scss
> +}
これはどこかから取得してきました？

2023-10-10 07:19 UTC, jam411 commented on apps/app/src/components/LoginForm.module.scss
> +    margin-top: -1.75rem;
これは対象のクラスを使っている JSX に bootstrap のクラスを充てることで置き換えられないかな

2023-10-10 07:24 UTC, soumaeda commented on apps/app/src/components/Layout/NoLoginLayout.module.scss
> +}
こちらはobsoleteの`apply-colors-light.scss`と`apply-colors-light.scss`から取得しました。
PRの「やったこと」にも追記しました。

2023-10-10 09:45 UTC, soumaeda commented on apps/app/src/components/LoginForm.module.scss
> +    margin-top: -1.75rem;
そもそもbootstrap5 への移行によって .col に position: relative; が適用されなくなってしまったので、代替として .nologin-dialog にposition: relative; を適用するようにしました

2023-10-16 03:55 UTC, jam411 commented on apps/app/src/components/Layout/NoLoginLayout.module.scss
> +    flex-direction: row;
default で `row` ですが、なぜ必要なんでしょうか？
`.nologin-header` で `flex-direction: column` しているため？

2023-10-16 03:55 UTC, jam411 commented on apps/app/src/components/LoginForm.tsx
> +            data-bs-target="#external-auth"
`data-target` になっている個所 grep して PR 出してほしい。

2023-10-16 04:21 UTC, soumaeda commented on apps/app/src/components/Layout/NoLoginLayout.module.scss
> +    flex-direction: row;
.page-wrapper の主軸が縦方向になっており、align-item: center; としても横方向(x軸)の中間に配置されるだけになっていたので、主軸を横方向にするために`flex-direction: row;`を追加しました。

2023-10-16 05:00 UTC, soumaeda commented on apps/app/src/components/LoginForm.tsx
> +            data-bs-target="#external-auth"
`HandsontableModal.tsx`と`GrowiNavbarButtom.tsx`に1箇所づつ data-target になっている箇所があったので、そちらも data-bs-target に修正しました

2023-10-16 05:33 UTC, jam411 approved these changes

2023-10-16 05:33 UTC, jam411 commented on apps/app/src/components/LoginForm.tsx
> +            data-bs-target="#external-auth"
この PR で実施したということで理解しました

2023-10-16 06:00 UTC, soumaeda commented
# 追加修正
flex-direction はbootstrapで指定できるので、.page-wrapperと.nologin-headerにそれぞれ .flex-rowと.flex-columnを追加しました。

2023-10-16 08:21 UTC, yuki-takei requested changes

2023-10-16 08:21 UTC, yuki-takei commented on apps/app/src/components/Layout/NoLoginLayout.module.scss
> +      }
fill で色を付けているところを見つけたら一旦全て color の指定に変えてください。(一旦色つかなくても構わないので)

v7 では svg icon は全て font icon に変える予定なので、color で色が付くようになるはず。

以降も同じ。

2023-10-19 01:56 UTC, soumaeda commented on apps/app/src/components/Layout/NoLoginLayout.module.scss
> +      }
svg iconは fill で色をつけていたが、color で色指定をするようにしました。
現状は svg のため、色がついていない状態です。

2023-10-19 02:26 UTC, merged