imprv: Limit the file types in editor.
weseek/growi pull request #8146
Opened 2023-10-06 09:42 UTC by reiji-h

# 概要
- エディタからアップロード可能なファイルに制限を設ける
- オーバーレイは未実装
- 制限は GROWI 起動時の環境変数で次の三つから指定可能。
   - すべてのファイルをアップロードできる
   - 画像だけアップロードできる
   - アップロードできない
# Task
- https://redmine.weseek.co.jp/issues/131762
  -  https://redmine.weseek.co.jp/issues/131770
# 実装
追加点は
- ファイル制限の方法の追加
- ファイル制限があった時に、D&D の挙動を変える
- ファイル制限があった時に、ツールバーの + からの Attachment ボタンの表示/非表示

今回、ファイル制限のために `packages/editor/consts` に `AcceptedUploadFileType` を追加。`CodeMirrorEditorMain` がそれを受け取り、dropzone の許容するファイルタイプと Attachment ボタンに反映する。react-dropzone のファイルの制限は次を参照。
- https://react-dropzone.js.org/#section-accepting-specific-file-types

2023-10-18 07:07 UTC, jam411 requested changes
コメントエディタにもファイルをアタッチできるので、`CodeMirrorEditorComment.tsx` で呼び出している `CodeMirrorEditor` コンポーネントにも `acceptedFileType` を渡したい.
そして props の型をオプショナルにしなくてもよくなると思う。

2023-10-18 07:15 UTC, jam411 commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
> +  const noDrag = acceptedFileType == null;
定数を使えばいいと思う。
`const noDrag = acceptedFileType === AcceptedUploadFileType.NULL`

undefined の場合も考慮していたらすまん

2023-10-18 07:15 UTC, jam411 commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
> +  accept[(acceptedFileType ?? '')] = [];
- オプショナルにする必要がなければこのあたりもシンプルになる想定

2023-10-20 07:40 UTC, reiji-h commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +  }, [isUploadableFile, isUploadableImage]);
確かに今のままだと、画像のみアップロード可能にするためにファイルのアップロードを禁止にする変な状況になっていますね…。理想の挙動をするように変更しました。

2023-10-20 07:44 UTC, reiji-h commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
> +  accept[(acceptedFileType ?? '')] = [];
オプショナルではない変数が`CodeMirrorEditor` にはなかったので、一貫するため今回はオプショナルとして書きました。

2023-10-20 07:46 UTC, reiji-h commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
> +  const noDrag = acceptedFileType == null;
オプショナルなので `undefined` と `AcceptedFileType::NONE` を考慮しています。

2023-10-20 07:49 UTC, reiji-h commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
> +  const noDrag = acceptedFileType == null;
noDrag だとまだ Dropzone を使えてしまうような書き方なので、 disabled を使うように変更しました。

2023-10-20 08:44 UTC, jam411 reviewed
開発環境で動きますかね？以下のエラーがでます。
```
Error: [vite]: Rollup failed to resolve import "src/consts" from "/workspace/growi/packages/editor/src/services/file-dropzone/use-file-dropzone.ts".
@growi/editor:dev: This is most likely unintended because it can break your application at runtime.
@growi/editor:dev: If you do want to externalize this module explicitly add it to
@growi/editor:dev: `build.rollupOptions.external`
```

2023-10-20 08:44 UTC, jam411 commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
> +  const disabled = acceptedFileType == acceptedFileType.NONE;
lint エラー修正してください

2023-10-20 08:44 UTC, jam411 commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
> +  accept[(acceptedFileType)] = [];
これできないか？
```
const accept: Accept = {
  acceptedFileType: []
};
```

2023-10-20 08:54 UTC, reiji-h commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
> +  accept[(acceptedFileType)] = [];
出来たのでそのように変更しました。
エラーについては import に使用するパスがおかしかったので修正しました。

2023-10-20 09:08 UTC, jam411 approved these changes

2023-10-20 11:32 UTC, yuki-takei approved these changes

2023-10-20 11:32 UTC, yuki-takei commented on packages/editor/src/consts/accepted-upload-file-type.ts
> +} as const;
細かいんだけど、今 app 側でこの const をインポートしている。ということは中身の `*` っていう文字列を、app 側も取り扱っていることになるよね(見えていないだけで)。

しかし dropzone がその形式の文字列を必要としているだけで、accept を設定する直前で手に入れば app 側は不要。つまり packages/editor に閉じたまま取り扱える文字列。

その点が少し気持ち悪いなあと思っているが…どうしてお直さないといけないようなものでもないかなあとか…

2023-10-20 11:32 UTC, merged