feat: Create PageCreateButton component outline
weseek/growi pull request #8157
Opened 2023-10-16 07:29 UTC by jam411

## task
https://redmine.weseek.co.jp/issues/132493

## 概要
- 新規作成のコンポーネントのアウトラインを作成しました。
- TODO コメントしている個所を後続タスクで取り組みます。

## Screenshot
![image](https://github.com/weseek/growi/assets/68407388/fe07bfd9-8582-4570-98f3-3c8d5aa63125)

2023-10-16 07:31 UTC, jam411 commented on apps/app/src/components/TreeItem/NewPageCreateButton.tsx
> -
`console.log` にログが大量にでてたので
おそらく消し忘れと判断し削除しています。

2023-10-18 08:03 UTC, yuki-takei requested changes

2023-10-18 08:03 UTC, yuki-takei commented on apps/app/src/components/Sidebar/PageCreateButton.tsx
> +            className="btn btn-secondary position-absolute"
position-absolute が付くのは共通見解 :+1:

2023-10-18 08:03 UTC, yuki-takei commented on apps/app/src/components/Sidebar/PageCreateButton.tsx
> +      </div>
細かい変更提案だけど、[マザーシップ](https://xd.adobe.com/view/9d2867cd-8f84-4995-9d94-ee27ce04c62d-c87b/screen/30378b36-59ec-4155-88d1-bd22a55f3bbc/) の挙動を見ると、bs5の [スプリットボタン](https://getbootstrap.jp/docs/5.3/components/dropdowns/#%e3%82%b9%e3%83%97%e3%83%aa%e3%83%83%e3%83%88%e3%83%9c%e3%82%bf%e3%83%b3) をそのまま採用できるんじゃないかな

2023-10-19 05:52 UTC, merged