feat: Add create button for not found page
weseek/growi pull request #8165
Opened 2023-10-19 13:54 UTC by jam411

## task
https://redmine.weseek.co.jp/issues/133119
https://redmine.weseek.co.jp/issues/133120

2023-10-19 14:02 UTC, jam411 commented on apps/app/src/stores/context.tsx
> +};
ページを作成処理できるかどうか、と、編集処理できるかどうか、を分けました。
not found page は厳密にはページを作成してから（not found でないページにしてから）はじめて編集できるためです。

2023-10-20 11:47 UTC, yuki-takei requested changes

2023-10-20 11:47 UTC, yuki-takei commented on apps/app/src/stores/context.tsx
> +
context.tsx 内は useContextSWR で管理する next page 表示時から変わることがない変数の集合にしたいので、ここに useStaticSWR のものを移すのは不適当。

2023-10-20 11:47 UTC, yuki-takei commented on apps/app/src/stores/context.tsx
> +};
useIsNotFound を context.tsx には入れられないので、それに依存するこの hook もここにあるのは不適当ということになる。

2023-10-20 11:47 UTC, yuki-takei commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        )}
ロジックはいいと思うけれど、View|Edit ボタンと違うデザインのものを入れたいかどうかはデザイナーに決めてもらって。

2023-10-23 05:36 UTC, jam411 commented on apps/app/src/stores/context.tsx
> +
理解しました。ありがとうございます。

2023-10-23 05:37 UTC, jam411 commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +        )}
後続タスクを作成しました。
https://redmine.weseek.co.jp/issues/133274

2023-10-23 05:37 UTC, jam411 commented
#8172

2023-10-23 05:37 UTC, closed without merging