imprv: Able to edit tags in editor
weseek/growi pull request #8167
Opened 2023-10-20 01:35 UTC by soumaeda

# やったこと

- PageSideContents.tsx を参考に、PageTags を PageControls.tsx で使うようにした。
 
- 条件分岐により編集画面の場合のみ PageControls に PageTags を表示させるようにした。

- 編集画面では、追加された Tag は表示させず、タグの編集のみ行えるようにするのでタグ編集モーダルを出すボタンのみ配置。

# タスク
https://redmine.weseek.co.jp/issues/132486

# 仕様・デザイン相談Slack
https://wsgrowi.slack.com/archives/C05HK5SA8CC/p1697697877523389
https://wsgrowi.slack.com/archives/C05LB9T4KR9/p1697692493178809?thread_ts=1697682798.970699&cid=C05LB9T4KR9

2023-10-20 05:29 UTC, jam411 requested changes
シンプルに以下の要件を満たすボタンを用意すればいいのではないか？
- クリックすると tag モーダルが表示される
- 編集モード時だけ表示される

2023-10-25 01:20 UTC, jam411 commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const { open: openTagEditModal } = useTagEditModal();
GROWI では末端のコンポーネント内で SWR を呼び出すことは推奨されていなくて、上位のコンポーネントで hooks を呼び出して props で渡す設計になっているのでそれに合わせてほしいです。

2023-10-25 01:20 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  }, [tags]);
これと `const [tags, setTags] = useState<string[]>([]);` いるのかな。tags は tagEditModalData から取得できないかな

2023-10-25 04:05 UTC, soumaeda commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  }, [tags]);
tagsを更新する場合には initTags に追加した tags を入れる必要があるため、useStateは利用します。

2023-10-25 04:08 UTC, soumaeda commented
# 修正点

- TagsEditModal の状態を swr で管理することで、TagsEditModal の呼び出しを一つにすることができました。

- swr の呼び出しを上位コンポーネントで行い、props で子コンポーネントに渡すようにしました。

2023-10-25 06:18 UTC, jam411 requested changes

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +
- Modal のコメントをつけておいてほしいです。
- 改行は一行でお願いします。

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +
- 改行は一行でお願いします。

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +import useSWR, { SWRResponse, mutate } from 'swr';
このインポート差分は意図したもの？

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +import { IPageTagsInfo } from '~/interfaces/tag';
こちらも

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +  const open = async(tags, pageId, revisionId) => {
引数に型をつける必要がある

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +import { tags } from '~/services/xss/recommended-whitelist';
これは使っている？

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/components/PageTags/TagsInput.tsx
> +  onTagsUpdated: (tags?: string[] | undefined) => void;
オプショナルにするのではなくて、親コンポーネントで undefined の場合をハンドリングしてほしい

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +    closeTagEditModal();
`finally` 使いましょうか

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +    closeTagEditModal();
でもエラーの場合はモーダルクローズする必要はない気がする

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/components/PageControls/PageControls.tsx
> +
この辺の改行丁寧に

2023-10-25 06:18 UTC, jam411 commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +              openTagEditModal={() => openTagEditModal(tagsInfoData?.tags, pageId, revisionId)}
以下のようにハンドラーを作ってそれを渡すようにしましょうか

> onClickDuplicateMenuItem={duplicateItemClickedHandler}
> onClickRenameMenuItem={renameItemClickedHandler}
> onClickDeleteMenuItem={deleteItemClickedHandler}
> onClickSwitchContentWidth={switchContentWidthHandler}

2023-10-25 06:28 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +
TagEditModalコメント入れました

2023-10-25 06:30 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +import { tags } from '~/services/xss/recommended-whitelist';
使っていませんでした。
削除しました。

2023-10-25 06:31 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +import { IPageTagsInfo } from '~/interfaces/tag';
IPageTagsInfoもmodal.tsxでは利用していないため削除しました

2023-10-25 06:32 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +import useSWR, { SWRResponse, mutate } from 'swr';
こちらは意図していませんでした。useSWR と mutate のみ削除しました

2023-10-25 06:42 UTC, soumaeda commented on apps/app/src/components/PageControls/PageControls.tsx
> +
上下1行ずつの改行に修正しました。

2023-10-25 07:49 UTC, soumaeda commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +    closeTagEditModal();
closeTagEditModal()は正常終了した場合に呼び出すようにし、erroeの場合はモーダルクローズしないようにしました。

2023-10-25 08:22 UTC, soumaeda commented on apps/app/src/components/PageTags/TagsInput.tsx
> +  onTagsUpdated: (tags?: string[] | undefined) => void;
tagsにinitTagsを渡していましたが、initTags ?? [] として、undefinedの場合は空の配列を送るようにしました

2023-10-27 07:23 UTC, soumaeda commented
# 修正点
useStateでinitTagsをtagsの初期値にして、そこにnewTagsが追加されていく実装だったが、別のページに移動した時点ではtagsには前のページのtagsが初期値として入ってしまうため、useEffectを利用することにしました。

2023-10-30 02:14 UTC, jam411 requested changes

2023-10-30 02:14 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  }, [closeTagEditModal, pageId, revisionId, updateStateAfterSave]);
handleSubmit は引数とって渡すのではなく, `tags` を直接渡せばいいんじゃないかな？

2023-10-30 02:14 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  const handleSubmit = useCallback(async(newTags?: string[]) => {
- この辺りの改行をきれいにしてほしいです。

- なぜ useEffect が必要なのかコメントしておいてください

- useMemo を使って型を string[] に固定したいです。検証してみてほしいです。
```
  const initTags = useMemo(() => {
    return tagEditModalData?.tags ?? [];
  }, [tagEditModalData?.tags]);
```
TagsInput の tags props の型と defaultSelected に渡すときの `?? []` が不要になると思う
const [tsgs, setTags] の初期値は `[]` でよいです。 場所は useTranslation の後にしてみてください。

2023-10-30 10:31 UTC, soumaeda commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  }, [closeTagEditModal, pageId, revisionId, updateStateAfterSave]);
newTagsを使わずに、tagsを直接渡すようにしました

2023-10-30 13:58 UTC, soumaeda commented on apps/app/src/components/PageSideContents/PageSideContents.tsx
> +            openTagEditModal={() => openTagEditModal(tagsInfoData?.tags, pageId, revisionId)}
命名をonClickEditTagsButtonとして、それをprops(onClickEditTagsButton)に渡すようにしました。
エディタ(GrowiContextualSubNavigation → PageControlls)についても同様にonClickEditTagsButtonとして渡すように修正しました。

2023-10-31 02:05 UTC, soumaeda commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  const handleSubmit = useCallback(async(newTags?: string[]) => {
useMemoを使ってinitTagsを定義し、TagsInput の tagsの型定義をなくし、defaultSelectedにはptagsだけが渡るようにしました。

2023-10-31 03:00 UTC, soumaeda commented
# 修正点
GrowiContextualSubNavigation.tsx内で onClickEditTagsButton を定義し、propsでonClick まで渡すようにしていましたが、PageControls 内でonClickEditTagsButtonをpropsとして受け取るようにすると、SearchResultContent.tsx でもonClickEditTagsButtonを定義しないといけなくなってしまいます。
なので、PageControls でonClickEditTagsButtonを定義するようにしました。

2023-10-31 03:48 UTC, jam411 requested changes

2023-10-31 03:48 UTC, jam411 commented on apps/app/src/components/PageControls/PageControls.tsx
> +      {revisionId != null && !isViewMode && (
`revisionId != null` が気になるけど他の `SubscribeButton` や `LikeButtons` もそうなっている

2023-10-31 03:48 UTC, jam411 commented on apps/app/src/components/PageTags/TagsInput.tsx
> +  tags,
これ lint エラーになりそうだけどならないのか。
string[] にしておいてほしい。今 any 型になっている

2023-10-31 03:48 UTC, jam411 commented on apps/app/src/components/SearchPage/SearchResultContent.tsx
> +          // onClickEditTagsButton={onClickEditTagsButton}
不要なら、もともとなかったコードなので、コメントアウトじゃなくて削除してください。

2023-10-31 05:08 UTC, jam411 requested changes

2023-10-31 05:08 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  const [tags, setTags] = useState<string[] | undefined>();
`const [tags, setTags] = useState<string[]>([]);`
こうしてください

2023-10-31 09:39 UTC, yuki-takei requested changes

2023-10-31 09:39 UTC, yuki-takei commented on apps/app/src/components/PageControls/PageControls.tsx
> +  isReadOnlyUser?: boolean,
この2つは props で外部から持ってくるんじゃなくて、このコンポーネント内で hook で取得していいよ

2023-10-31 09:39 UTC, yuki-takei commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +    <Modal isOpen={isOpen} toggle={closeTagEditModal} id="edit-tag-modal" autoFocus={false}>
- isOpen が false なら、モーダルのレンダリングはおろか、これより上の行にある hundleSubmit 作ったり useUpdateStateAfterSave 呼んだりといった処理すらいらない
- このモジュール内でコンポーネントを分けて(TagEditModal と TagEditModalSubstance など)、useTagEditModal の結果 isOpen 状態でなければなにもしないにしてほしい

2023-10-31 09:39 UTC, yuki-takei commented on apps/app/src/stores/modal.tsx
> +  };
open, close は useCallback を使う

2023-11-01 02:34 UTC, soumaeda commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +    <Modal isOpen={isOpen} toggle={closeTagEditModal} id="edit-tag-modal" autoFocus={false}>
TagEditModalSubstance でモーダルの処理を行い、TagEditModal で isOpen が false 出ない場合にTagEditModalSubstanceを呼び出すようにしました。

2023-11-01 02:35 UTC, jam411 requested changes

2023-11-01 02:35 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +export const TagEditModalSubstance: React.FC = () => {
export いらないと思う

2023-11-01 02:35 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +};
ここで useTagEditModal() から close も取得してしまって props で data と close を渡してください。

2023-11-01 02:37 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +  };
@soumaeda 
これ対応できてない！！

2023-11-01 03:15 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +  };
open と close で useCallbackを使うようにしました。

2023-11-01 04:00 UTC, jam411 requested changes

2023-11-01 08:13 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +    mutate({ isOpen: false });
initialStatusを入れました

2023-11-01 08:28 UTC, soumaeda commented
hooks で型を固定し、onClickEditTagsButton関数内で pageId、revisionId 、tagsInfoData が null or undefined 場合に早期リターンするようにしました

2023-11-01 08:43 UTC, jam411 requested changes

2023-11-01 08:43 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  tagEditModalData?: TagEditModalStatus,
これって undefined で渡りえるのかな？

2023-11-01 08:43 UTC, jam411 commented on apps/app/src/components/PageSideContents/PageSideContents.tsx
> +            isTagLabelsDisabled={isTagLabelsDisabled ?? false}
isTagLabelsDisabled もオプショナルじゃないと思う

2023-11-01 09:06 UTC, soumaeda commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  tagEditModalData?: TagEditModalStatus,
undefinedが渡った時はモーダルが開く前に早期リターンするので、渡り得ないと思います

2023-11-01 11:07 UTC, jam411 requested changes

2023-11-01 11:07 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  if (tagEditModalData == null || !tagEditModalData.isOpen) {
- `!tagEditModalData?.isOpen` のみでカバーできるはず。

2023-11-01 11:07 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +    return;
return するのは JSX.Element にしてほしい。
よって、 `<></>` にしてください。

2023-11-01 11:07 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +  const close = useCallback(() => {
こちらの修正ありがとう。

2023-11-01 11:07 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +  const open = useCallback(async(tags: string[], pageId: string, revisionId: string) => {
async とつけるなら、戻り値の型が Promise<> になるはず。`type TagEditModalUtils` で定義している型と整合性をとるようにしてほしい。

2023-11-01 11:07 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +  }, [initialStatus, mutate]);
async とつけるなら、戻り値の型が Promise<> になるはず。`type TagEditModalUtils` で定義している型と整合性をとるようにしてほしい。

2023-11-01 12:43 UTC, soumaeda commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +  }, [tagEditModalData.tags]);
useMemoは使わずに、`const initTags = tagEditModalData.tags;`で定義しました

2023-11-01 12:48 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +  const open = useCallback(async(tags: string[], pageId: string, revisionId: string) => {
型推論でPromise<void>になっていたので、修正しました

2023-11-01 12:48 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +  }, [initialStatus, mutate]);
型推論でPromiseになっていたので、修正しました

2023-11-02 05:04 UTC, jam411 approved these changes

2023-11-02 05:33 UTC, merged