feat: Create New Page button handler
weseek/growi pull request #8173
Opened 2023-10-23 11:33 UTC by jam411

task: https://redmine.weseek.co.jp/issues/132680

2023-10-23 11:46 UTC, jam411 commented on apps/app/src/components/Sidebar/PageCreateButton.tsx
> +  }, [currentPage, isLoading, router]);
response が帰ってくるまでのローディング表示等やっていません。

2023-10-25 06:18 UTC, yuki-takei requested changes

2023-10-25 06:18 UTC, yuki-takei commented on apps/app/src/components/Sidebar/PageCreateButton.tsx
> +    }
API 呼び出し部分は別モジュールに分離したい

`client/services/page-operation.ts` あたりにまとめてるものはある(同じファイルでもいいし新設でもよい)

2023-10-25 06:18 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/pages.js
> +  }
`router.get('/exist-paths'` の実装があるので、共通化しないと混乱しそう。
includeEmpty = true が不要なのであれば、generateUniquePath から直接 findByPath を呼び出すでいい気がする。

2023-10-25 06:18 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/pages.js
> +        const defaultTitle = '/Untitled';
i18n 対応したい (後続タスクでよい)

2023-10-26 07:33 UTC, jam411 commented on apps/app/src/components/Sidebar/PageCreateButton.tsx
> +    }
`client/services/page-operation.ts` の createPage() を使いました。

2023-10-26 07:48 UTC, merged