feat: Create page when click edit button if page is not found
weseek/growi pull request #8174
Opened 2023-10-24 07:59 UTC by jam411

task: https://redmine.weseek.co.jp/issues/133362

2023-10-25 07:57 UTC, yuki-takei requested changes

2023-10-25 07:57 UTC, yuki-takei commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +    onPageEditorModeButtonClicked(viewType);
`onPageEditorModeButtonClicked?.(viewType)` と書ける

2023-10-26 02:30 UTC, jam411 commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +          pageTags: [],
オプショナルな変数でありデフォルト値でよさそうだったので、`path` `grant` `grantUserGroupId` 以外は渡さないようにしました。

2023-10-26 02:31 UTC, jam411 commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +
`/Navbar/hooks.tsx` に `useOnPageEditorModeButtonClicked()` を作成しました。

2023-10-26 11:05 UTC, yuki-takei requested changes

2023-10-26 11:05 UTC, yuki-takei commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +            onPageEditorModeButtonClicked={onPageEditorModeButtonClicked}
これ外(GrowiContextualSubNavigation) から入れなくても、という気はするな。
hooks.tsx は `Navbar/PageEditorModeManager/hooks.tsx` に閉じ込めて、PageEditorModeManager 内で import すればいいんじゃないかな。

2023-10-27 04:58 UTC, merged