imprv: Add Marp preset template ja
weseek/growi pull request #8179
Opened 2023-10-25 07:32 UTC by AikaHiyama

2023-10-26 10:55 UTC, yuki-takei requested changes

2023-10-26 10:55 UTC, yuki-takei commented on packages/preset-templates/dist/marp-example/ja_JP/template.md
> +- :vs: [Marp for VS Code][marp-vscode]: 編集中のデッキをライブプレビューする
ここ5行かなり機械翻訳味が強いので、別の翻訳機を使うなり ChatGPT を使うなりして「特徴」セクションとして自然かつ訴求力ある(こんなに魅力的なものなんだよというのがわかる)表現にしてください。

2023-10-26 10:55 UTC, yuki-takei commented on packages/preset-templates/dist/marp-example/zh_CN/template.md
中国語は機械翻訳そのままで構わないのでとりあえず修正してください。
とはいえ、日本語の方の template.md へのフィードバックを参考に、英語のままの方がよさそうなところはそのままにしてください。

2023-10-30 08:45 UTC, AikaHiyama commented
レビューメッセージを残すため、[75abc63](https://github.com/weseek/growi/pull/8179/commits/75abc63ce034ad5cb009499a45cc9fe4ebcc44a7)で追加した不要な差分を削除するコミットを追加しました。

いただいたFBについては、この後修正いたします。

2023-11-15 11:16 UTC, merged