Separation of client and server side interfaces
weseek/growi pull request #8183
Opened 2023-10-25 16:12 UTC by miya

## Task
[#132928](https://redmine.weseek.co.jp/issues/132928) [approval-workflow] mongoose インスタンス用の type と DB から取得してきた純粋なデータの type を使い分けることができる
┗ [#133434](https://redmine.weseek.co.jp/issues/133434) 改善

2023-10-30 10:27 UTC, yuki-takei requested changes

2023-10-30 10:27 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow.spec.ts
> +  WorkflowApprovalType, WorkflowStatus, WorkflowApproverStatus,
import type

2023-10-30 10:27 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +import Workflow, { WorkflowDocument } from '../models/workflow';
IWorkflowDocument にできない？

2023-10-30 10:27 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow.spec.ts
> +import { WorkflowDocument } from '../models/workflow';
IWorkflowDocument にできない？

2023-10-30 10:27 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +import { WorkflowDocument, WorkflowApproverGroupDocument } from '../models/workflow';
IWorkflowDocument, IWorkflowApproverDocument にできない？

2023-10-31 06:22 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +import { WorkflowDocument, WorkflowApproverGroupDocument } from '../models/workflow';
WorkflowDocument.getLatestApprovedApproverGroupIndex() や WorkflowApproverGroupDocument.findApprover() 等のインスタンスメソッドも `WorkflowDocument` や `WorkflowApproverGroupDocument` が必要なので部分的に修正しました。

2023-10-31 10:52 UTC, yuki-takei requested changes

2023-10-31 10:52 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-serializer.spec.ts
> +      const serializedWorkflow = serializeWorkflowSecurely(workflow) as any;
- まずやりたいことは返り値を any にするのではなく、引数を any にすることだった (`workflow as any`)

2023-10-31 10:52 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-serializer.spec.ts
> +      const serializedWorkflow = serializeWorkflowSecurely(workflow) as any;
`import { mock } from 'vitest-mock-extended';` 使えないか？

2023-10-31 10:52 UTC, yuki-takei requested changes

2023-10-31 10:52 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/serializers/workflow-serializer.spec.ts
> +      const serializedWorkflow = serializeWorkflowSecurely(workflow) as any;
現状のテストは「通信しない結合テスト」になっている。

`omitInsecureAttributes` は別途単体テストを書きましょう。

2023-10-31 10:54 UTC, yuki-takei requested changes

2023-10-31 10:54 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/routes/apiv3/workflow.ts
> +      const paginateResult = await (Workflow as any).paginate(
この as any はなんだ？

2023-10-31 10:54 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +      targetWorkflow.approverGroups.splice(data.groupIndex, 0, newApproverGroup as any);
as any 多すぎ

2023-11-07 11:19 UTC, yuki-takei requested changes

2023-11-07 11:19 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +      targetWorkflow.approverGroups.splice(data.groupIndex, 0, newApproverGroup as any);
それは any をつかっていい理由にはならないな。

IWorkflowApproverGroupDocument を使う全てのケースで isApproved が optional になってよいのであれば、`isApproved?: boolean` とすべき。 

そうでないのであれば、たとえば `Omit<IWorkflowApproverGroupDocument, 'isApproved'> & { isApproved?: boolean }` のように一部 property を取り除いて新たな型を作り、利用シーンにあわせて限定的に使う方法もある。とにかく少しでも type safe にする意識を持って欲しい。any は全て放棄するのと同じなので。

2023-11-07 11:19 UTC, yuki-takei commented on packages/core/src/interfaces/user.ts
> +};
@groi/core で提供している isPopulated を使えない？

2023-11-08 08:37 UTC, miya commented on packages/core/src/interfaces/user.ts
> +};
`isPopulated` が使えたのでこちらに置き換えました

2023-11-08 09:33 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +      targetWorkflow.approverGroups.splice(data.groupIndex, 0, newApproverGroup as any);
isApproved の問題もそうですが、 targetWorkflow.approverGroups.splice の第3引数には `WorkflowApproverGroupDocument` つまりインスタンス化された mongoose のオブジェクトを受け付けるようになっていました。なので targetWorkflow.approverGroups.splice のインターフェースを omit して、第3引数に `IWorkflowApproverGroupReq` を受け付けるように書き換えました。

2023-11-09 13:14 UTC, merged