feat:  Implement api for incremental search of user
weseek/growi pull request #8184
Opened 2023-10-26 01:20 UTC by miya

## Task
[#130338](https://redmine.weseek.co.jp/issues/130338) [approval-workflow] XD 通りにワークフロー作成画面を実装しワークフローの作成ができる
┗ [#133229](https://redmine.weseek.co.jp/issues/133229) [server] user をインクリメントサーチするための API の実装

2023-10-26 10:01 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowCreationModalContent.tsx
> +  const isCreatableWorkflow = allEditingApproverIds.length > 0;
承認者が 0 人の場合作成ボタンを押せないように

2023-10-26 10:01 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/ApproverGroupCards.tsx
> -  const excludedSearchUserId = [creatorId, ...editingApprovers];
これは WorkflowCreationModalContent.tsx から props で渡すように修正

2023-10-26 11:22 UTC, yuki-takei requested changes

2023-10-26 11:22 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/users.js
> +  });
既に `router.get('/', accessTokenParser, loginRequired, validator.statusList, apiV3FormValidator, async(req, res) => {` が存在するので新設したくはない。

全く用途が違うなら相談がほしい。

2023-10-26 11:28 UTC, yuki-takei requested changes

2023-10-26 11:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/SearchUserTypeahead.tsx
> +  }, []);
ここの処理足りないんじゃないかなあ？
添付の動画の 0:12 付近で、typeahead の input にフォーカスしただけで user-b, user-d がサジェストされているのが気になる。

![image](https://github.com/weseek/growi/assets/1638767/573f13ef-e3ec-4f80-b507-697b4029479f)

2023-10-26 11:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/services/workflow.ts
> +  const allEditingApproverIds = getAllApproverIds(editingApproverGroups);
useMemo した方がいいかな。

2023-10-27 09:53 UTC, miya commented on apps/app/src/features/approval-workflow/client/services/workflow.ts
> +  const allEditingApproverIds = getAllApproverIds(editingApproverGroups);
修正しました

2023-10-29 03:08 UTC, miya commented on apps/app/src/server/routes/apiv3/users.js
> +  });
`/users` で excludedUserIds を受け取れるように改修してこれを利用するようにしました

2023-10-29 03:45 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/SearchUserTypeahead.tsx
> +  }, []);
修正しました

2023-10-30 05:14 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/ApproverGroupCards.tsx
> +    }
選択されている userIds が1以下の時は強制的に WorkflowApprovalType が AND に変更される

2023-10-30 05:14 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/ApproverGroupCards.tsx
> +            </Dropdown>
approvalType を変更するための dropdown 関連コンポーネントを reactstrap に変更

2023-10-30 05:14 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/ApproverGroupCards.tsx
> +                )}
approvalType が変更不能な場合は理由を tooltip で表示させる

2023-10-30 10:23 UTC, merged