feat: Make button work to insert markdown text
weseek/growi pull request #8185
Opened 2023-10-27 02:28 UTC by soumaeda

# やったこと
https://codemirror.net/docs/ref/#state.EditorState
ドキュメントを参考に、EditorState の replaceselection、dispatch を使って、渡された引数(* 、~)をエディタ画面に挿入できるようにした。

replaceselection で選択されている範囲を、渡される引数で置き換える仕様を作成し、dispatch により作成された transactionの仕様を取得し、エディタに表示させるようにしました。

# タスク
https://redmine.weseek.co.jp/issues/133069
https://redmine.weseek.co.jp/issues/133072
https://redmine.weseek.co.jp/issues/133083

2023-10-27 08:09 UTC, jam411 requested changes

2023-10-27 08:09 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
> +  }, [view]);
`/workspace/growi/packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-text.ts` のように hooks 化できないかな
検討してみてほしい

2023-10-31 05:51 UTC, soumaeda commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
> +  }, [view]);
insert-markdown-text.ts を作り、hooks化しました。

use-codemirror-editor.ts で作成したhook( useInsertMarkdownText )を取り込み、return で返すことで、
`codeMirrorEditor?.insertMarkdownText(prefix, suffix);`
のように使うことができるようになりました。

2023-10-31 06:35 UTC, jam411 requested changes

2023-10-31 06:35 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
> +  editorKey: string,
editorKey の型を `string | GlobalCodeMirrorEditorKey` としておいてください

2023-10-31 06:35 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
> +  editorKey: string,
editorKey の型を string | GlobalCodeMirrorEditorKey としておいてください

2023-10-31 06:35 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-markdown-text.ts
> +    let curPosAfterReplacing = {};
何で初期値で `{}` を与えてから `as number` 型アサーションしているんだろう？

2023-10-31 06:35 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-markdown-text.ts
> +};
このようにしてはどうでしょうか？
- null ガードは明示的にする
- 早期リターンする

```
export const useInsertMarkdownText = (view?: EditorView): InsertMarkdownText => {
  return useCallback((prefix, suffix) => {
    const selection = view?.state.sliceDoc(
      view?.state.selection.main.from,
      view?.state.selection.main.to,
    );

    const cursorPos = view?.state.selection.main.head;
    const insertText = view?.state.replaceSelection(prefix + selection + suffix);

    if (insertText == null || cursorPos == null) {
      return;
    }

    view?.dispatch(insertText);
    view?.dispatch({ selection: { anchor: cursorPos + prefix.length } });
    view?.focus();
  }, [view]);
};
```

2023-10-31 07:48 UTC, soumaeda commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-markdown-text.ts
> +    let curPosAfterReplacing = {};
typeエラーが出ていたので型定義してました

2023-10-31 07:52 UTC, soumaeda commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-markdown-text.ts
> +};
早期リターンすることでコードが綺麗になりました。

2023-11-02 00:45 UTC, yuki-takei requested changes

2023-11-02 00:45 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
> +import { GlobalCodeMirrorEditorKey, AcceptedUploadFileType } from 'src/consts';
import type にしてください

2023-11-02 00:46 UTC, yuki-takei requested changes

2023-11-02 00:46 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
> +import { GlobalCodeMirrorEditorKey } from '../../../consts';
こちらも同様に、enum として使うわけではなく type としてしか参照しないのであれば import type にしてください

2023-11-02 03:38 UTC, soumaeda commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
> +import { GlobalCodeMirrorEditorKey, AcceptedUploadFileType } from 'src/consts';
import type とすることで型インポートを明示的にしました

2023-11-02 06:09 UTC, jam411 approved these changes

2023-11-02 06:09 UTC, merged