imprv:  Enable file uploading overlay
weseek/growi pull request #8191
Opened 2023-10-30 02:58 UTC by reiji-h

# 概要
- ファイルを D&D したときのオーバーレイを実装。

# Task
- https://redmine.weseek.co.jp/issues/131554
  - https://redmine.weseek.co.jp/issues/131771

2023-10-30 04:13 UTC, jam411 requested changes
PR と直接関係ないですが、前回間違った FB をしていたので修正してください
`/workspace/growi/apps/app/src/components/PageEditor/PageEditor.tsx`

```
const acceptedFileType = useMemo(() => {
  if (!isUploadableImage) {
    return AcceptedUploadFileType.NONE;
  }
  if (isUploadableFile) {
    return AcceptedUploadFileType.ALL;
  }
  return AcceptedUploadFileType.IMAGE;
}, [isUploadableFile, isUploadableImage]);
```

isUploadableImage のほうが強かった.

2023-11-02 03:21 UTC, reiji-h commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
> +$secondary: $gray-600 !default;
取得できたのでそのように変更しました。

2023-11-02 03:36 UTC, jam411 requested changes

2023-11-02 03:36 UTC, jam411 commented on apps/app/src/components/PageEditor/PageEditor.tsx
>        return AcceptedUploadFileType.IMAGE;
isUploadableImage が一番強くこれが falsy なら添付できなくしたいので、`AcceptedUploadFileType.NONE` を返してください。

2023-11-02 03:40 UTC, jam411 requested changes

2023-11-02 03:40 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
> +.codemirror-editor :global {
この辺りの移植元の scss を削除してください

2023-11-02 04:55 UTC, reiji-h commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
> +.codemirror-editor :global {
`Editor.module.scss` と `_mixin.scss` の該当箇所をコメントアウトする形で削除しました。

2023-11-02 04:55 UTC, reiji-h commented on apps/app/src/components/PageEditor/PageEditor.tsx
>        return AcceptedUploadFileType.IMAGE;
修正しました。

2023-11-06 16:18 UTC, yuki-takei requested changes

2023-11-06 16:18 UTC, yuki-takei commented on apps/app/src/components/PageEditor/PageEditor.tsx
このファイルの修正内容自体はいいんだけど、そもそも変数名(hook 名)がわるいと思うんだよね。

`[[...path]].page.tsx` の以下の部分

```
  props.editorConfig = {
    upload: {
      isUploadableFile: crowi.fileUploadService.getFileUploadEnabled(),
      isUploadableImage: crowi.fileUploadService.getIsUploadable(),
    },
  };
```

の isUploadableImage という変数名を修正し、併せて useIsUploadableImage も改名してほしい。

2023-11-06 16:18 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
> +.codemirror-editor :global {
完全に移植できたのなら _mixin.scss のコードごと消し去ってください。
まだスタイルが完璧でなく、後続タスクで _mixin.scss のコメントアウトされたコードを参照する必要があるのであれば、その旨をコード中にコメントで記載してください。(後続タスクの URL と一緒に)

2023-11-06 16:18 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
> +  } = useFileDropzone({ onUpload, acceptedFileType });
renderOverlay の中身もこの hook が提供するようにしてください

2023-11-06 16:18 UTC, yuki-takei commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
use-file-dropzone はモジュールディレクトリにして、export を書く index.ts を作る
そのディレクトリ内に renderOverlay をコンポーネント化したものも入れてください。

2023-11-06 16:18 UTC, yuki-takei commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
> +  }, [isUploading, dzState.isDragAccept, dzState.isDragReject, acceptedFileType]);
fileUploadState の実態は css クラス名である。
css クラス名の決定はビュー側の責務なので、AcceptedUploadFileType からクラス名を解決する機構はビュー側に移す。

2023-11-08 07:53 UTC, reiji-h commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
FileDropzoneOverlay.tsx として新たに作成しました。

2023-11-08 07:57 UTC, reiji-h commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
> +  } = useFileDropzone({ onUpload, acceptedFileType });
コンポーネント化し別のファイルに作成しました。

2023-11-08 09:21 UTC, reiji-h commented on packages/editor/src/services/file-dropzone/use-file-dropzone.ts
> +  }, [isUploading, dzState.isDragAccept, dzState.isDragReject, acceptedFileType]);
fileUploadState は `CodeMirrorEditor.tsx` で作成するようにしました。

2023-11-10 05:32 UTC, reiji-h commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
> +.codemirror-editor :global {
参照する必要がなかったので該当箇所を削除しました。

2023-11-10 05:47 UTC, reiji-h commented on apps/app/src/components/PageEditor/PageEditor.tsx
`isUploadableImage` を `isUploadEnabled`
`isUploadableFile` を `isUploadAllFileAllowed` に変更しました。

2023-11-13 09:11 UTC, merged