feat: 133821 create announcement model
weseek/growi pull request #8196
Opened 2023-10-30 13:50 UTC by WNomunomu

2023-11-08 02:26 UTC, miya commented on packages/editor/src/services/index.ts
> +export * from './extensions';
emoji 関連の差分は意図されたもの？？

2023-11-08 02:26 UTC, miya commented on apps/app/src/server/models/announcement.ts
> +  },
見落としていたら申し訳ないんだけど name ってなんだっけ？？(xd とか外部仕様みてもわからなかった)

2023-11-08 02:26 UTC, miya commented on apps/app/src/server/models/announcement.ts
> +  comment: string
interface 側も optional を考慮しなくちゃじゃない？

2023-11-09 13:35 UTC, yuki-takei requested changes

2023-11-09 13:35 UTC, yuki-takei commented on apps/app/src/server/models/announcement.ts
> +}
enum ではなく union を使ってください
https://weseek.co.jp/tech/1609/

また、これはクライアントでも使うと思うのでサーバーサイドのソースからは分離する。

2023-11-09 13:35 UTC, yuki-takei commented on apps/app/src/server/models/announcement.ts
> +  },
emoji は optional でもいいと思う

2023-11-09 13:35 UTC, yuki-takei commented on apps/app/src/server/models/announcement.ts
> +  },
default: false を入れておこう

2023-11-16 10:54 UTC, yuki-takei requested changes

2023-11-16 10:54 UTC, yuki-takei commented on apps/app/src/features/announcement/announcement.ts
> +}
`features/comment/server/models/comment.ts` を参考に、IAnnounce を作成して extends に含めてください

ディレクトリ構成や[バレル](https://typescript-jp.gitbook.io/deep-dive/main-1/barrel)もそちらを参考に。

2023-11-24 07:48 UTC, merged