feat: Create today's and template page
weseek/growi pull request #8202
Opened 2023-10-31 05:58 UTC by jam411

https://redmine.weseek.co.jp/issues/133891
https://redmine.weseek.co.jp/issues/133890
https://redmine.weseek.co.jp/issues/132682

2023-10-31 08:32 UTC, jam411 commented on apps/app/src/server/routes/apiv3/pages.js
> +    }
このエンドポイントではすでにページが存在する場合に 40x を返すので、`shouldReturnIfPathExists` が true のときは `{}` と 200 を返すようにしました。

2023-10-31 10:14 UTC, yuki-takei requested changes

2023-10-31 10:14 UTC, yuki-takei commented on apps/app/public/static/locales/en_US/commons.json
> +
移植元の translation.json の行を削除してほしい

2023-10-31 10:14 UTC, yuki-takei commented on apps/app/src/components/Sidebar/PageCreateButton.tsx
> +  const onClickCreateTodaysButtonHandler = useCallback(async() => {
dropdown menu はこのモジュール内で最低限別コンポーネントにわけてください
(PageCreateButton ディレクトリを作って、private な別モジュールにしてもよい)

2023-10-31 10:14 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/pages.js
> +    }
作成できないページパスに対する POST 処理に対して API が 40x の結果を返すのは正しい。その場合の挙動はクライアント側で制御すべきでは？

2023-11-06 02:51 UTC, jam411 commented on apps/app/public/static/locales/en_US/commons.json
> +
消せそうなものは削除しました。
PageCreateModal.jsx ファイル自体はそのままにしています。

2023-11-06 02:51 UTC, jam411 commented on apps/app/src/components/Sidebar/PageCreateButton.tsx
> +  const onClickCreateTodaysButtonHandler = useCallback(async() => {
`apps/app/src/components/Sidebar/PageCreateButton/PageCreateButtonDropdownMenu.tsx` に分割しました。

2023-11-06 07:13 UTC, jam411 commented on apps/app/src/server/routes/apiv3/pages.js
> +    }
迷ったのですが、`/pages.exist` を使ってページがあるかどうかの判断をするようにしました。
```
export const exist = async(pagePaths: string): Promise<PageExistResponse> => {
  const request: PageExistRequest = { pagePaths };
  const res = await apiGet('/pages.exist', request);
  return res as PageExistResponse;
};
```

2023-11-06 16:24 UTC, yuki-takei approved these changes

2023-11-06 16:24 UTC, yuki-takei commented on apps/app/src/client/services/page-operation.ts
> +  return res as PageExistResponse;
`apiGet<T>` が使えるはずなので as は消してください。

2023-11-06 16:24 UTC, merged