feat: Can be edited from the edit screen
weseek/growi pull request #8212
Opened 2023-11-06 02:07 UTC by miya

## Task
[#132622](https://redmine.weseek.co.jp/issues/132622) [approval-workflow] XD 通りにワークフロー編集画面を実装しワークフローを編集できる
┗ [#134117](https://redmine.weseek.co.jp/issues/134117) [client] 更新に必要なデータを作成して、API リクエストできる

2023-11-06 16:32 UTC, yuki-takei requested changes

2023-11-06 16:32 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/EditableApproverGroupCards.tsx
> +              <button type="button" className="btn-close" aria-label="Close" onClick={() => { removeApproverGroupCardHandler() }}></button>
引数いらなくなったのであれば、無名 closure 作る必要ないのでは？

2023-11-06 16:32 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowEditModalContent.tsx
> +};
…という説明を加えておいてください

2023-11-06 16:33 UTC, yuki-takei requested changes

2023-11-06 16:33 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +        (approverGroup.approvers as any).push({ user: userIdToAdd });
as any を消す後続タスクが欲しい

2023-11-07 01:55 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +        (approverGroup.approvers as any).push({ user: userIdToAdd });
こちらのタスクで対応中です
https://github.com/weseek/growi/pull/8183

2023-11-07 01:55 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/EditableApproverGroupCards.tsx
> +              <button type="button" className="btn-close" aria-label="Close" onClick={() => { removeApproverGroupCardHandler() }}></button>
不要でしたの修正しました

2023-11-07 01:55 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowEditModalContent.tsx
> +};
コメントを加えたのと、より具体的なメソッド名、引数名に修正しました

2023-11-07 02:00 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +        (approverGroup.approvers as any).push({ user: userIdToAdd });
こちらのタスクで対応中です
https://github.com/weseek/growi/pull/8183

2023-11-07 11:21 UTC, merged