feat: You can add header with button
weseek/growi pull request #8214
Opened 2023-11-06 08:22 UTC by soumaeda

# 概要
エディタtoolbarのヘッダーボタンを機能させた・

# やったこと
- [Codemirror 公式](https://codemirror.net/docs/ref/#:~:text=Anything%20else.-,Text,-The%20Text%20type)を参考に、カーソルが当たっている行を lineAt で取得し、'#' がなければ'#'とスペースが挿入されてスペースの後ろにカーソルが当たるようにした。
- 挿入した後、続けてボタンを押すとカーソルより1前の箇所に'#'のみが挿入され、見出しのレベルを作れるようにした。

# Task
https://redmine.weseek.co.jp/issues/133085

2023-11-07 02:21 UTC, jam411 requested changes

2023-11-07 02:21 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-header.ts
`prefix` を渡せる拡張性を持たせるなら、useInsertHeader 内部で `#` と書いている部分も引数から取得するべきだし、その拡張性を持たせる必要がないなら、prefix をとらなくてもいいと思う。

2023-11-07 04:34 UTC, soumaeda commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-header.ts
# ではなく引数(prefix) をif判定の対象にしました。

2023-11-07 05:05 UTC, jam411 requested changes

2023-11-07 05:05 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-header.ts
> +
10 行目の改行を無くしておいてください。

2023-11-07 05:05 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-header.ts
> +    const selection = view?.state.sliceDoc(
早期リターンしているので、`?` はいらないと思います。

2023-11-07 05:05 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-header.ts
> +    }
insertPos の下は改行にして、let insertText と if 分の間の改行を無くしてください。

2023-11-07 11:09 UTC, yuki-takei requested changes

2023-11-07 11:09 UTC, yuki-takei commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +  const insertHeader = useInsertHeader(view);
insertHeader というメソッドはやや汎用的と言い難い。
use-codemirror-editor を介さず、TextFormatTools と useInsertHeader の間だけで完結しないだろうか？

2023-11-08 06:07 UTC, soumaeda commented
# 修正点
- codeMirrorEditor の view のデータをTextFormatToolsの中で取得し、`insertHeader`に渡すようにしました。
- onClickAddHeaderToSelection 関数に渡した引数を受け取るのではなく、insert-header.ts内で直接'#'をprefixに代入しました(汎用性がないため)

2023-11-08 07:14 UTC, merged