imprv: Able to add prefix with toolbar buttons
weseek/growi pull request #8219
Opened 2023-11-08 03:00 UTC by soumaeda

# 概要
エディタToolbar内のボタン(リスト、数字リスト、引用、チェックボックス)を機能させた。

# やったこと
- 取得したカーソル位置(view.state.selection.main.head) に引数(prefix) と 空白が挿入されるようにした。
- insertTextが挿入された後、カーソルがprefix と空白の後ろに位置するように調整。

# Task
https://redmine.weseek.co.jp/issues/134164

# ScreenShot

https://github.com/weseek/growi/assets/112812878/bb09cb71-1d17-46c9-979e-e7f22bb9266b

2023-11-08 07:23 UTC, jam411 requested changes

2023-11-08 07:23 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
> +  return useCallback((prefix) => {
以下を他と合わせてやってください。
- view の早期リターン
- prefix の型

2023-11-08 07:23 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
> +          insert: insertText + selection,
selection が plus ってどうなるんだろう。

2023-11-09 02:18 UTC, soumaeda commented
# 修正点
- isContinuous というフラグを用意し、headerのみtrueにすることで、すでに行頭に'#'が挿入されている場合はボタンを押すと連続して'#'が挿入されるようにし、headerレベルを変えられるようになったため、insert-header.ts は不要のため削除しました。
- テキストを選択した状態でinsertすると、選択が解除されてしまっていたので、insert後もテキストを選択している状態になるように、selection に head を追加しました。(参考: [CodeMirror Selection](https://codemirror.net/docs/guide/#:~:text=set%20compose%20method.)-,Selection,-Alongside%20the%20document))

2023-11-09 05:58 UTC, jam411 requested changes
複数行をドラックした時の挙動を確認してほしい。
おそらく修正が必要です。

2023-11-09 05:58 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
> +export type InsertPrefix = (prefix: string, flag: boolean) => void;
- 第二引数をオプショナルにしてください。
- 第二引数の名前を `noSpace` とかにしてください（header でも prefix がなければスペースはつくのでよくないな。。`noSpaceIfPrefixExists` とか具体的にするかそもそももっといい名前あるかも）

2023-11-09 05:58 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
> +        to: line.from,
`to` はいらないと思う。

2023-11-09 05:58 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
> +      selection: { anchor: line.from + line.text.length + insertText.length },
`line.to + insertText.length` だけでいけないか？

2023-11-09 05:58 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
> +          <button type="button" className="btn btn-toolbar-button" onClick={() => onClickInsertPrefix('-', false)}>
第二引数いらないときは undefined を渡すようにしましょうか

2023-11-09 05:58 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
> +  return useCallback((prefix: string, isContinuous: boolean) => {
第二引数の初期値は false でいいと思います。

2023-11-09 06:53 UTC, soumaeda commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
> +      selection: { anchor: line.from + line.text.length + insertText.length },
いけました。

2023-11-09 07:06 UTC, soumaeda commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
> +export type InsertPrefix = (prefix: string, flag: boolean) => void;
noSpaceIfPrefixExists と命名しました。

2023-11-09 07:51 UTC, soumaeda commented
# 修正点
複数行選択してinsertした場合、選択している状態でのカーソルが位置している行の先頭にinsertされてしまっていたので、
カーソルの取得位置を`view.state.selection.main.head`から`view.state.selection.main.from`に変更することで、複数行選択し状態でinsertするときは常に上の行の行頭にinsertされるようになった。

2023-11-09 07:55 UTC, jam411 requested changes

2023-11-09 07:55 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
> +          <button type="button" className="btn btn-toolbar-button" onClick={() => onClickInsertPrefix('-', undefined)}>
第二引数をからにすればいいよ
`onClick={() => onClickInsertPrefix('-')}`

2023-11-14 02:34 UTC, soumaeda commented
# 修正点
- v6 の /Pageeditor/CodeMirroreditor.tsx 内のcreateAddPrefixToEachLinesHandlerを参考に、for文を使って、複数行を選択した状態でボタンを押すと各行の行頭にprefix が挿入されるようにしました。

- 最初に`const endPos = view.state.selection.main.to;`としているので、dispatch文のselectionでも利用しようとしたのですが、prefixの挿入後に再度`view.state.doc.lineAt(view.state.selection.main.to)`としないと、挿入後の`view.state`を取得できない様子でした。そのため、dispatchでinsertTextを挿入後、`const getEndLine = view.state.doc.lineAt(view.state.selection.main.to)`として、getEndLine をselectionで使うようにしました。

- selection の anchor ですが、getEndLine.to とすると、複数行選択した場合の一番下の行が空白の場合、なぜかinsertTextの前(行頭)にカーソルが位置してしまうので、あえて行頭にカーソルを位置させ(getEndLine.from)、行中のtextの長さだけ後ろにカーソルを移動させるようにしました。

2023-11-14 03:11 UTC, jam411 reviewed
@soumaeda 
こちらの経緯を武井さん伝えて、そもそもこの方針でいいのかから相談・修正お願いします。

### 経緯
insert-header と insert-prefix を共通化した。
しかし、header だけその他の Numbered list や Unordered list と仕様が違う個所が2つあった。
1. 範囲選択したときに header は選択した範囲の一番上だけに `#` が挿入されること
1. すでに `#` が存在していたら `##` と space なしにインクリメントされていくこと

2023-11-14 03:11 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
> +    const getEndLine = view.state.doc.lineAt(view.state.selection.main.to);
変数名を get つけずに `endLine` にしてください。

2023-11-15 03:14 UTC, jam411 approved these changes

2023-11-15 03:14 UTC, jam411 commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
こんな感じでいかがでしょうか？
もし修正する場合はコメントは英語に直してください。
insertTextLength がなんか微妙な気はする

```
export const useInsertPrefix = (view?: EditorView): InsertPrefix => {
  return useCallback((prefix: string, noSpaceIfPrefixExists = false) => {
    if (view == null) {
      return;
    }

    // select した範囲の line number を取得する
    const { from, to } = view.state.selection.main;
    const startLine = view.state.doc.lineAt(from);
    const endLine = view.state.doc.lineAt(to);

    // line ごとに prefix を挿入する
    const lines = [];
    let insertTextLength = 0;
    for (let i = startLine.number; i <= endLine.number; i++) {
      const line = view.state.doc.line(i);
      const insertText = noSpaceIfPrefixExists && line.text.startsWith(prefix)
        ? prefix
        : `${prefix} `;
      insertTextLength += insertText.length;
      lines.push({ from: line.from, insert: insertText });
    }
    view.dispatch({ changes: lines });

    // カーソルを select した line のうち一番最後に移動させる
    view.dispatch({ selection: { anchor: endLine.to + insertTextLength } });
    view.focus();
  }, [view]);
};
```

2023-11-15 04:53 UTC, soumaeda commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
`view.state.selection.main` と `view.state.doc.lineAt()` を多用せずに済むため、上記の変更を取り入れました。

2023-11-16 09:40 UTC, merged