support: 134087 refactor conditional branch about doc.parsed snapshot
weseek/growi pull request #8227
Opened 2023-11-10 05:24 UTC by WNomunomu

2023-11-13 07:43 UTC, miya commented on apps/app/src/server/routes/apiv3/in-app-notification.ts
> +    const serializedDocs: Array<IInAppNotification<IUser | IPage>> = paginationResult.docs.map((doc) => {
`IInAppNotification<IUser | IPage>` がかなりいろんな箇所で使われているので /interfaces/in-app-notification.ts の中に定義しちゃっても良さそう？

2023-11-13 07:43 UTC, miya commented on apps/app/src/stores/in-app-notification.ts
> -              break;
これは無くなっていいの？

2023-11-13 08:32 UTC, WNomunomu commented on apps/app/src/server/routes/apiv3/in-app-notification.ts
> +    const serializedDocs: Array<IInAppNotification<IUser | IPage>> = paginationResult.docs.map((doc) => {
IInAppNotification.targetの型が、場合によってIUserやIPage、IUser | IPageと異なるので、in-app-notification.tsの中で定義せず、このような書き方にしています。

2023-11-13 08:32 UTC, WNomunomu commented on apps/app/src/stores/in-app-notification.ts
> -              break;
武井さんとリファクタについて話し合ったところ、stores/in-app-notificationからはparsedSnapshotに関する処理は消去して、pageModelNotificationで必要な時に処理を行うことになりました。

2023-11-13 10:42 UTC, miya commented on apps/app/src/components/InAppNotification/PageNotification/PageModelNotification.tsx
> +  };
useCallback か useMemo 使ったほうがよさそう

2023-11-16 10:47 UTC, yuki-takei requested changes

2023-11-16 10:47 UTC, yuki-takei commented on apps/app/src/interfaces/in-app-notification.ts
> +export interface IInAppNotification<T> {
`IInAppNotification<T = unknown>` としてください。
そうすれば `IInAppNotification<IUser | IPage>` の大部分は `IInAppNotification` と書いて問題なくなるはず。

type guard は

```
  const isPageNotification = (notification: IInAppNotification): notification is IInAppNotification<IPage> => {
    ...
  };
```

のようになります。

2023-11-16 10:48 UTC, yuki-takei requested changes

2023-11-16 10:48 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/in-app-notification.ts
> +    const serializedDocs: Array<IInAppNotification<IUser | IPage>> = paginationResult.docs.map((doc) => {
https://github.com/weseek/growi/pull/8227/files#r1395509506 参照

2023-11-17 08:43 UTC, merged