imprv: Workflow interface improvements
weseek/growi pull request #8236
Opened 2023-11-14 00:48 UTC by miya

## Task
[#134710](https://redmine.weseek.co.jp/issues/134710) [approva-wokflow] interfaces/workflow.ts の改善
┗ [#134711](https://redmine.weseek.co.jp/issues/134711) 改善

2023-11-14 01:30 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +  validateApproverGroups(isNew: boolean, creatorId: string, approverGroups: any): void {
- 引数 `approverGroups`  を any にして実装内部で type guard 処理を加えた
- 現状 WorkflowService.createWorkflow() と WorkflowService.updateWorkflow() から呼び出されており、それぞれクライアンドサイドから渡される Array<CreateWorkflowApproverGroupData\> 型 とサーバーサイドから渡される mongoose インスタンスの WorkflowApproverGroupDocumentWithoutArraySplice があり、これらの union 型を作ると複雑になってしまうため引数を any とした

2023-11-14 01:30 UTC, miya commented on apps/app/src/features/approval-workflow/interfaces/workflow.ts
>  }
IWorkflow ~ はクライアンドサイドでのみ利用しているので削除して IWorkflow ~ HasObjectId に統一

2023-11-15 11:27 UTC, yuki-takei requested changes

2023-11-15 11:27 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +  validateApproverGroups(isNew: boolean, creatorId: string, approverGroups: any): void {
type guard の関数の引数以外で any は禁止です。(例えこのメソッドの最初に type guard を使っていたとしても)

共通のユニバーサルな type を作るのではだめなの？ 今のコードだと ValidateApproverGroupArg がそれにあたると思うんだけど。

2023-11-16 02:12 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +}>, 'splice'>
https://github.com/weseek/growi/blob/imprv/134711-workflow-interface-improvements/apps/app/src/features/approval-workflow/server/models/workflow.ts#L108 で Array.prototype.splice() を omit しているためここでも omit しました。ValidateApproverGroupArg はこのサービスメソッド内でのみ利用するので多少の複雑さは許容範囲だと判断しました。

2023-11-16 02:12 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow-approver-group.ts
> +  validateApproverGroups(isNew: boolean, creatorId: string, approverGroups: any): void {
修正しました。

2023-11-16 05:54 UTC, miya commented on apps/app/src/features/approval-workflow/server/models/workflow.ts
> -
クライアントサイドでも使えるように共通化してあるのでこのインスタンスメソッドは削除
https://github.com/weseek/growi/blob/imprv/134711-workflow-interface-improvements/apps/app/src/features/approval-workflow/utils/workflow.ts#L4-L15

2023-11-16 10:07 UTC, yuki-takei approved these changes

2023-11-17 01:12 UTC, merged