feat: Implement endpoints for approving workflows
weseek/growi pull request #8237
Opened 2023-11-15 01:36 UTC by miya

## Task
[#130335](https://redmine.weseek.co.jp/issues/130335) [approval-workflow] API から進行中のワークフローを「承認」できる
┗ [#131344](https://redmine.weseek.co.jp/issues/131344) [server] PUT: /:workflowId/status (承認時) のロジック実装

2023-11-15 10:53 UTC, miya commented on apps/app/src/features/approval-workflow/server/models/workflow.ts
> +  }
- 最後の group が approved だった場合に workflow が approved になる

2023-11-15 10:53 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +        updatedWorkflow = await targetWorkflow.save();
- 親ドキュメントを save() することで approver.status が更新した内容が保存される
- save() することで updatedWorkflow.isApproved には approverGroup.approve() が実行されたことが考慮された boolean が入る (updatedWorkflow.updateStatus() の中で利用する)
  - save() しないと virtual (isApproved) が再実行されない

2023-11-15 10:55 UTC, miya reviewed
すみません、時間が経ってしまったので 別 PR にしました。以下の実装提案コードを考慮したものになります。
https://github.com/weseek/growi/pull/8115#discussion_r1341148259

テストは別タスクで書く予定です。

2023-11-15 11:44 UTC, yuki-takei requested changes

2023-11-15 11:44 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +        updatedWorkflow = await targetWorkflow.save();
この for-of って、approve 対象の要素1つを見つけるためであって、複数要素の approve() を呼ぶためではないということでよい？それであれば、findApprover は for-of の中にあっていいけれど、approve() は for-of の外に出てから呼んでほしい。

2023-11-15 11:47 UTC, yuki-takei requested changes

2023-11-15 11:47 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/workflow.ts
> +  }
save しないと isApproved の T/F が変わらないのが不便なのなら、これは virtual は向いていないのかもしれない(単なる getter でいいような)

2023-11-15 11:47 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/server/models/workflow.ts
> +  }
また、status の更新は schema.pre でどうにかならないか？
https://mongoosejs.com/docs/api/schema.html#Schema.prototype.pre()

2023-11-16 01:29 UTC, miya commented on apps/app/src/features/approval-workflow/server/models/workflow.ts
> +  }
schema.pre('validate') が使えたのでこちらを利用することにしました。これは save() が呼ばれる前に呼ばれる middleware ですが、save() 前でもこの middleware 内では isApproved の T/F が変化していたので virtual なのはそのままにしています。

2023-11-16 01:29 UTC, miya commented on apps/app/src/features/approval-workflow/server/services/workflow.ts
> +        updatedWorkflow = await targetWorkflow.save();
> この for-of って、approve 対象の要素1つを見つけるためであって、複数要素の approve() を呼ぶためではないということでよい？

そうです。break が使えたのでこちらを利用しました (あまり let を増やしたくなかったので)

2023-11-16 10:04 UTC, merged