feat: Update CreateTemplateModal
weseek/growi pull request #8242
Opened 2023-11-20 04:03 UTC by jam411

https://redmine.weseek.co.jp/issues/135249
https://redmine.weseek.co.jp/issues/135248

2023-11-20 09:41 UTC, jam411 commented on apps/app/src/components/CreateTemplateModal.jsx
方針よさそうであれば tsx 化しようと思います。
https://redmine.weseek.co.jp/issues/135294

2023-11-21 04:53 UTC, yuki-takei requested changes

2023-11-21 04:53 UTC, yuki-takei commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  }, [currentPage, router]);
テンプレート固有のこのコンポーネントからは抜きたい
(delete 周りで固有のロジックが入ってしまっているのは承知しているが、新たに増やしたくない)

updateContentWidth などのように、カスタム hook に逃がすのがいいと思う

2023-11-21 04:53 UTC, yuki-takei commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  }, [currentPage, router]);
そしてコードの重複が気になる

2023-11-21 04:53 UTC, yuki-takei commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const [isCreating, setIsCreating] = useState<boolean>(false);
isCreating はカスタムhookから提供する。

CreateTemplateModal も、そのカスタムhookから isCreating や onClickTemplateForChildrenButtonHandler 処理を受け取っていいと思う

2023-11-21 04:53 UTC, yuki-takei commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const [isCreating, setIsCreating] = useState<boolean>(false);
また、急に isCreating という state が追加されるとなぜ必要だと思ったのかがわからない。
意図がわかるタスクを作るか、コード内コメントを書くか、PR の説明に書くか、レビュー依頼時に説明するか、なんかやってほしい。

2023-11-21 05:20 UTC, jam411 commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const [isCreating, setIsCreating] = useState<boolean>(false);
`await createPage(path, '', params);` レスポンスが帰ってくるまで、button をクリックできないようにと思っていました。
PageCreateButton.tsx でもそうやっていたので特にコメント書かずにコード書きました。

2023-11-21 08:18 UTC, yuki-takei commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const [isCreating, setIsCreating] = useState<boolean>(false);
PageCreateButton.tsx の中に isCreating があったら他の人が見ても意味わかると思うよ。
GrowiContextualSubNavigation.tsx の中に isCreating って書かれてても何を作ってる最中のステートなのかわからないと思う。

2023-11-22 09:22 UTC, jam411 commented on apps/app/src/components/CreateTemplateModal.jsx
リファクタリングの過程で、すぐできそうだったのと実装に必要だったのでこの PR でやってしまいました。

2023-11-22 09:24 UTC, jam411 commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  }, [currentPage, router]);
hooks.tsx に移動して共通化しました。
hooks.tsx に置くべきではないのと
`/workspace/growi/apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx` このコードにも適用できそうだったので、後続タスクで改善します。

https://redmine.weseek.co.jp/issues/135443

2023-11-22 09:24 UTC, jam411 commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +  const [isCreating, setIsCreating] = useState<boolean>(false);
修正しました。

2023-11-22 09:34 UTC, jam411 commented on apps/app/src/components/Navbar/hooks.tsx
useOnTemplateButtonClicked をここに置くのはおかしいと思うので後続タスクで改善します。
https://redmine.weseek.co.jp/issues/133892

2023-11-24 01:44 UTC, yuki-takei requested changes

2023-11-24 01:44 UTC, yuki-takei commented on apps/app/src/components/CreateTemplateModal.tsx
> +  const [isPageCreating, setIsPageCreating] = useState(false);
このステートは useOnTemplateButtonClicked に含む

2023-11-24 19:38 UTC, merged