feat: Able to open edit table modal in editor
weseek/growi pull request #8246
Opened 2023-11-21 06:04 UTC by soumaeda

# 概要
エディタ画面のツールバーからEdit Tableモーダルを開き、テーブルの挿入や編集をできるようにする

# Task
https://redmine.weseek.co.jp/issues/134360

2023-11-21 09:38 UTC, jam411 reviewed
- タスクの分割をしたほうがよさそう。
  - modal の開閉
  - MarkdownTableUtil.js の Codemirror v6 化
  - MarkdownTableUtil の ts 化
  - etc.

2023-11-21 13:54 UTC, jam411 commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
この差分もスコープ外なので revert してください。
差分を戻すときは commit を重ねるのでなくて revert できるのがベストだと思っています。
なので commit も revert しやすいというかまとまりで commit できたらベター

2023-11-21 13:55 UTC, jam411 reviewed
最新の `dev/7.0.x` を取り込むと CI の test がパスするはずなので、CI pass してから修正してから再度レビュー依頼お願いします。

2023-11-22 02:56 UTC, jam411 reviewed
- CodeMirrorEditorComment には openTableModal を渡さなくてもいい?
スコープ外なら理解

- openTableModal という props 名を修正したい。どんなものを渡しているのかわかるようにしたい。ハンドラーなのか、`onClickTableBtn` という動作によるものなのか

2023-11-22 02:56 UTC, jam411 commented on apps/app/src/stores/modal.tsx
> +    table?: MarkdownTable,
これを optional にする必要はないんじゃないかな

2023-11-22 03:00 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/TableButton.tsx
> +    }
ここでガードするのがいいのかな

2023-11-22 05:09 UTC, soumaeda commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/TableButton.tsx
> +    }
CodeMirrorEditorComment に `openTableModal `を渡さない想定だったため TableButton内でガードしていましたが、CodeMirrorEditorComment でもHandsontableModalを使う想定で、CodeMirrorEditorComment にも　`openTableModal ` を渡すようにするので、PageEdit.tsx内でガードするようにしました。

2023-11-22 05:12 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +    table?: MarkdownTable,
markdownTable を 渡すときにnullガードしているため不要でした。

2023-11-22 05:32 UTC, soumaeda commented
#修正点
v6では props名を`onClickTableBtn`としていたので、v7でも同様のprops名にしました。

2023-11-22 06:08 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/TableButton.tsx
> +  };
openTableModalHandler で wrap する必要がなくなる
直接 onClickTableBtn を渡せばいいと思います。

2023-11-22 06:08 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditorMain.tsx
> +  onClickTableBtn: () => void,
ここでオプショナルにしましょう。

2023-11-22 06:08 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditorComment.tsx
> +  onClickTableBtn: () => void,
同じくここでオプショナル

2023-11-22 07:04 UTC, jam411 commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +    }
markdownTable をここでガードしないといけない理由はなんだろう
モーダル側の型も変えたいですね。。

2023-11-22 07:11 UTC, soumaeda commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +    }
useHandsontableModalフックのtableにundefinedが渡らないようにするためにガードしています。

2023-11-22 07:55 UTC, jam411 commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +    }
口頭で話して markdownTable はオプショナルでなかった。

2023-11-24 03:05 UTC, soumaeda commented on packages/editor/src/components/CodeMirrorEditorMain.tsx
> +  onClickTableBtn: () => void,
CodeMirrorEditorMain.tsxではundefinedを許容し、CodeMirrorEdtitor.tsx内でnullガードするようにしました。

2023-11-24 03:58 UTC, jam411 requested changes

2023-11-24 03:58 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
> +  }
onClickTableBtn が optional になっているのは CodeMirrorEditor がば onClickTableBtn なしでも使えるということだから、ここで `<></>` を返すとすべての JSX に影響が及んでいるのでよくなかった。

2023-11-24 03:58 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
> +      <TableButton onClickTableBtn={onClickTableBtn} />
ここで `onClickTableBtn == null` だったら `<TableButton` を表示させないようにしてください。

2023-11-24 03:58 UTC, jam411 commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +    }
Editor の markdownTable "でない"ところにマウスカーソルが当たっている状態だと、markdownTable のeditor から get できなくて、ボタンを押せなくなると思ったんですが大丈夫ですかね？

2023-11-24 03:58 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
> +  }
https://github.com/weseek/growi/pull/8246#discussion_r1403915204
ここで型ガードお願いします。

2023-11-24 04:42 UTC, soumaeda commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +    }
markdownTableがundefinedで渡ってくるとボタンが押せなくなるので、こちらではnullガードしないようにしました。
HandsontableModal に tableがnullで渡ってくる想定でいるので、useHandsontableModal の table をoptionalにしました。

2023-11-24 04:50 UTC, jam411 approved these changes

2023-11-24 05:39 UTC, yuki-takei requested changes

2023-11-24 05:39 UTC, yuki-takei commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +  }, [codeMirrorEditor]);
この処理を PageEditor が面倒見るのは違うかなあ。CodeMirrorEditorMain も CodeMirrorEditorComment もやることは変わらないはずなので、CodeMirrorEditor がクッションにならないといけない。

まずこの PR でやるべき最低限が、上で書いた mtu との橋渡しの責務の見直し。

2023-11-24 05:39 UTC, yuki-takei commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +  }, [codeMirrorEditor]);
上記に加えて、以下を可能な範囲で後続タスクとしてやってほしい

- MarkdownTableUtil の整理
    - TypeScrpt 化
    - 責務の整理(view から handsontable を開くときのユーティリティと、codemirror から handsontable を開く時のユーティリティに分ける)

2023-11-24 05:39 UTC, yuki-takei commented on apps/app/src/stores/modal.tsx
> +    table: MarkdownTable | null,
以下を可能な範囲で後続タスクとしてやってほしい

- 引数から table と editor を除く
    - onSave を駆使すればなくせるはず

2023-11-24 05:39 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
> +      { onClickTableBtn && <TableButton onClickTableBtn={onClickTableBtn} /> }
ボタン自体は常に表示すべきだと思う

2023-11-27 04:04 UTC, soumaeda commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +  }, [codeMirrorEditor]);
口頭で話したように、packages/editor配下にモーダルopen用のフックを作成し、`HandsontableModal`が二つのフックを参照するようにしました。

2023-11-27 04:16 UTC, soumaeda commented
# 修正点
新たに作成したuse-handsontableフックを経由してエディタの状態をモーダルに渡し、mtu.getMarkdownTable(editor) でエディタ上のマークダウンテーブルを取得するようにしました。

2023-11-27 04:20 UTC, soumaeda commented on apps/app/src/stores/modal.tsx
> +    table: MarkdownTable | null,
> - 引数から table と editor を除く
>    - onSave を駆使すればなくせるはず

上記のイメージがついていないので、タスクに取り掛かる際に再度ご相談させていただきたいです。

2023-11-28 02:02 UTC, soumaeda commented
# 修正点
packages/editor配下のフック(useHandsontableModalForEditor)をモーダルが参照し、editorデータを受け取るようにしました。
これにより、モーダルの開閉までは可能な状態になりました。

タスクのリンクもストーリーリンクになっていたので、変更しておきました。

2023-11-28 09:21 UTC, merged