Support/133781 refactor where to get users to be notified
weseek/growi pull request #8248
Opened 2023-11-21 13:15 UTC by WNomunomu

2023-11-27 01:45 UTC, miya commented on apps/app/src/server/service/preNotify.ts
> +  generatePreNotify = (activity: ActivityDocument, getAditionalTargetUsers?: GetAditionalTargetUsers): PreNotify => {
`getAditionalTargetUsers` って関数で渡さなければいけないのかな？

2023-11-29 06:18 UTC, WNomunomu commented on apps/app/src/server/service/preNotify.ts
> +  generatePreNotify = (activity: ActivityDocument, getAditionalTargetUsers?: GetAditionalTargetUsers): PreNotify => {
targetUsersを配列で渡すことも考えたのですが、そうするとcomment.jsのように追加の通知対象のユーザーを取得する際にactivityが必要になる場合に対応できなくなります。
そのため、getAdditionalTargetUsersというコールバック関数を用いることにしました。

2023-11-29 09:15 UTC, yuki-takei requested changes

2023-11-29 09:15 UTC, yuki-takei commented on apps/app/src/server/models/activity.ts
> +  const activity = await this.findOneAndUpdate({ _id: activityId }, parameters, { new: true }) as unknown as ActivityDocument;
as 以下いらないんじゃないかな

2023-11-29 09:15 UTC, yuki-takei commented on apps/app/src/server/service/preNotify.ts
ファイル名は kebab-case にしてください

2023-11-29 09:15 UTC, yuki-takei commented on apps/app/src/server/service/preNotify.ts
> +class PreNotifyService {
`class PreNotifyService implements IPreNotifyService` みたいにしないと、フィールドメソッドとして定義している generatePreNotify が本当に GeneratePreNotify タイプなのかどうかが vscode or tsc によって保証されないんじゃないかな。

2023-11-29 09:15 UTC, yuki-takei commented on apps/app/src/server/service/in-app-notification/in-app-notification-utils.ts
> +      snapshot = pageSerializers.stringifySnapshot(target as IPage);
as を使わない type safe な generateSnapshot の書き方を検討してください

2023-11-29 09:15 UTC, yuki-takei commented on apps/app/src/server/service/activity.ts
> +        activityId: string, parameters, target: IPage, generatePreNotify: GeneratePreNotify, getAdditionalTargetUsers?: GetAdditionalTargetUsers,
generatePreNotify は optional では？

2023-12-01 08:44 UTC, yuki-takei requested changes

2023-12-01 08:44 UTC, yuki-takei commented on apps/app/src/server/models/activity.ts
> +  const activity = await this.findOneAndUpdate({ _id: activityId }, parameters, { new: true }) as ActivityDocument;
`as ActivityDocument` 不要だと思っている。
もし Query 型が返るようであれば `.exec()` 呼び出しが必要。

2023-12-07 07:10 UTC, merged