feat: Correspond with migration for codemirror6
weseek/growi pull request #8249
Opened 2023-11-22 02:26 UTC by soumaeda

# 概要
MarkdownTableUtil で codemirror6へのマイグレーション対応をしました

# やったこと
codemirrorのマイグレーションガイドを参考にMarkdownTableUtilを修正することで、MarkdownTableUtil内の関数が利用できるようになったので、HandsontableModal が機能するようになった。
https://codemirror.net/docs/migration/

# Task
https://redmine.weseek.co.jp/issues/135395

2023-11-24 09:10 UTC, jam411 requested changes

2023-11-27 03:41 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +      return this.curPos;
機能していませんでした。
this.curPosに引数のeditorを渡すことで機能するようになりました。

2023-11-27 05:57 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +
現在のカーソル位置を取得しています

2023-11-27 05:57 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +    const firstLine = doc.line(1);
エディタの一番上の行を取得しています
(v5はは0から始まるが、v6では1から始まる)

2023-11-27 05:57 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +      if (!this.linePartOfTableRE.test(strLine.text)) {
カーソル位置の一行上を取得し、その行にテーブルがあるかを見て、無くなるまで一行ずつ上がります

2023-11-27 05:57 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +    return botLine.from;
テーブルの一番上の行頭を取得します

2023-11-27 05:57 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
>          break;
カーソル行を取得し、テーブルが無くなるまで一行ずつ下がります。

2023-11-27 05:57 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +    return eotLine.to;
テーブルの一番したの行末を取得します

2023-11-27 05:57 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +    return editor.state.sliceDoc(this.getBot(editor), this.curPos(editor));
テーブル先頭からカーソルまでの文字を取得

2023-11-27 05:57 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
>    }
カーソルからテーブル末までの文字を取得

2023-11-27 05:57 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +    const strFromBotToEot = editor.state.sliceDoc(this.getBot(editor), this.getEot(editor));
getBotからgetEotまでの範囲の文字列を取得

2023-11-27 05:57 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +    const lineText = editor.state.doc.lineAt(this.curPos(editor)).text;
カーソル行の文字列を取得

2023-11-28 02:23 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +    const lineText = editor.state.doc.lineAt(this.curPos(editor)).text;
こちらはマイグレーションガイドに従うと`doc.line`になっていたのですが、実際は
`Cannot read properties of undefined (reading 'length')`と出てしまっていました。

ここではカーソルの位置している行の文字列を取得する必要があったので、`lineAt(this.curPos(editor)).text`とすれば行の文字列を取得し、正規表現のテストができると判断したため、マイグレーションガイドと異なる記述になっています。

2023-11-28 02:50 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +    return (this.curPos(editor) === editor.state.doc.line(this.curPos(editor).line + 1).length);
こちらは確認不足で誤っていました。
.ch(縦の位置)はcodemirror6で使うことはなく、さらにこちらではカーソル位置の行末を返すべきなので、
`this.curPos(editor) === editor.state.doc.lineAt(this.curPos(editor)).to`と修正しました。

2023-11-28 03:22 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> -    editor.getDoc().setCursor(curPos.line + 1, 2);
こちらはカーソルが位置している行の一行下にカーソルをセットするような記述だと思うのですが、実際にv6エディタを見るとテーブルinsert後にカーソルが位置していませんでした。

変更した記述ではカーソル行末に位置させるようにしましたが、それも中途半端だと思うので、テーブルの一番したの行末にカーソルを位置させるように修正してみました。

2023-11-28 03:47 UTC, soumaeda commented
# 相談したいこと
テーブル挿入後のカーソル位置についてですが、v6エディタでは挿入後にカーソルが表示されていなく、ただ記述を見た様子だとカーソルの一行したに位置させるようでした。

現時点では挿入されたテーブルの一番したの行末に位置させるようにしていますが、こちらの仕様を固めたいと思っています。

例えばテーブルの一番下の行の次の行とかに表示されるとすると、すでに行が存在していれば問題ないのですが、存在していない場合は新たに行を作るようにしなければなりません。

2023-11-28 05:00 UTC, jam411 requested changes

2023-11-28 06:41 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +    const botLine = doc.line(line + 1);
firstLineと比較している理由がわからなかったのですが、念の為比較するように修正しました。

2023-11-28 07:03 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownTableUtil.js
> +    const eotLine = doc.line(line - 1);
lastLineと比較している理由がわからなかったのですが、念の為比較するように修正しました。

2023-11-28 09:31 UTC, soumaeda commented
# 修正点
- 行番号を直接定数に入れるよう修正しました

2023-11-28 09:54 UTC, jam411 approved these changes
~Num の部分だけ修正お願いします。

2023-11-28 11:47 UTC, merged