feat: Custom instant search client interface
weseek/growi pull request #8259
Opened 2023-11-24 07:36 UTC by miya

## Task
[#134807](https://redmine.weseek.co.jp/issues/134807) [v7][search] GET: /_api/search のレスポンスフォーマットを InstantSearch に渡すフォーマットに変換できる
┗ 135516 CustomClient の interface 実装

2023-11-27 07:24 UTC, miya commented on apps/app/package.json
> +    "@algolia/client-search": "^4.20.0",
interface が使いたかったので install しました

2023-11-27 07:24 UTC, miya commented on apps/app/src/client/services/instant-search/search-client.ts
> +const search = async <T = Record<string, any>>(requests: readonly MultipleQueriesQuery[]): Promise<{ results: Array<SearchResponse<T>> }> => {
[https://github.com/meilisearch/meilisearch-js-plugins/blob/main/packages/instant-meilisearch/src/client/instant-meilisearch-client.ts を](https://github.com/meilisearch/meilisearch-js-plugins/blob/main/packages/instant-meilisearch/src/client/instant-meilisearch-client.ts#L86) を参考に InstatntSearch に渡すためのインターフェースを実装しました。ロジック実装は後続タスクで行います。

2023-11-27 07:24 UTC, miya commented on apps/app/src/client/services/instant-search/search-client.ts
> +    const response = await apiGet('/search', { q: request.params?.query }) as IFormattedSearchResult;
試しに GET: /_api/search を叩いてみています

2023-11-27 07:24 UTC, miya commented on apps/app/src/client/services/instant-search/search-client.ts
> +  const dummyResponse = { results: [] } as any;
ロジックが未実装なので any を返却しています

2023-11-27 09:57 UTC, yuki-takei requested changes

2023-11-27 09:57 UTC, yuki-takei commented on apps/app/package.json
> +    "@algolia/client-search": "^4.20.0",
devDependencies に移してください

2023-11-28 01:04 UTC, miya commented on apps/app/package.json
> +    "@algolia/client-search": "^4.20.0",
移動させました

2023-11-28 01:10 UTC, merged