imprv: Refactor deleteCompletelyUserHomeBySystem
weseek/growi pull request #8262
Opened 2023-11-24 11:38 UTC by jam411

https://redmine.weseek.co.jp/issues/134631

2023-11-24 19:44 UTC, yuki-takei requested changes

2023-11-24 19:44 UTC, yuki-takei commented on apps/app/src/server/service/page.ts
> +    const parentId = isPopulated(userHomepage.parent) ? userHomepage.parent._id : userHomepage.parent;
`getIdForRef` を使える

2023-11-24 19:44 UTC, yuki-takei commented on apps/app/src/server/events/user.ts
> +    const Page = mongoose.model('Page') as unknown as PageModel;
`model<IPage>('Page')` ではだめなの？
Model の型を入れたいなら `model<IPage, PageModel>('Page');`

2023-11-27 05:31 UTC, jam411 commented on apps/app/src/server/service/page.ts
> +    const parentId = isPopulated(userHomepage.parent) ? userHomepage.parent._id : userHomepage.parent;
ありがとうございます。

2023-11-27 06:35 UTC, jam411 commented on apps/app/src/server/events/user.ts
> +    const Page = mongoose.model('Page') as unknown as PageModel;
修正しました。

2023-11-27 07:05 UTC, merged