feat: 132740 135569 imlement component
weseek/growi pull request #8265
Opened 2023-11-25 08:09 UTC by yukendev

# やったこと
- `/me`の`その他の設定`タブのアンケート設定コンポーネントをファイル分割
- 新たにUI設定のコンポーネントを作り`その他の設定`タブに設置
  - ワイドビュー設定用のスイッチを作成

<img width="1449" alt="スクリーンショット 2023-11-25 17 09 47" src="https://github.com/weseek/growi/assets/65263895/f854a2dc-9bff-4a2c-b1a5-17ef95b3272b">

# 備考
- 設定を保存する部分はまだ実装していないので、次のPRで実装します

2023-11-25 08:10 UTC, yukendev commented on apps/app/src/components/Me/QuestionnaireSettings.tsx
そのまま`OtherSettings`コンポーネントから持ってきました

2023-11-28 19:35 UTC, yuki-takei requested changes

2023-11-28 19:35 UTC, yuki-takei commented on apps/app/src/components/Me/UISettings.tsx
> +import SidebarDrawerIcon from '../Icons/SidebarDrawerIcon';
Me の中でしか使わなくなったと思うのでアイコンのファイルも移動させてください

2023-11-28 19:35 UTC, yuki-takei commented on apps/app/src/components/Me/UISettings.module.scss
> +    }
svg ブロック内の color って有効なの？

font icon を使う前提なら svg ブロックは不要になるだろうし、svg のまま使うなら fill とかになると思う

2023-11-29 07:12 UTC, yukendev commented on apps/app/src/components/Me/UISettings.tsx
> +import SidebarDrawerIcon from '../Icons/SidebarDrawerIcon';
移動させました

2023-11-29 07:13 UTC, yukendev commented on apps/app/src/components/Me/UISettings.module.scss
> +    }
svgファイルのスタイルを削除して、colorで色をつけるようにしました

2023-11-29 07:23 UTC, merged