Feat/78027 135782 bulk export UI mock
weseek/growi pull request #8277
Opened 2023-11-28 15:33 UTC by arafubeatbox

# イメージ
![image](https://github.com/weseek/growi/assets/32846231/1256ce6d-d7d6-49f5-b503-13b6d3477d67)
![image](https://github.com/weseek/growi/assets/32846231/051eb41a-e5c9-41a0-8f08-cf7b6d176e2a)
![image](https://github.com/weseek/growi/assets/32846231/6308445b-b99a-47eb-9afd-eb60379e34f8)

2023-11-29 08:00 UTC, jam411 approved these changes

2023-11-29 10:57 UTC, arafubeatbox commented
[デザイン FB](https://wsgrowi.slack.com/archives/C061Q2GPARE/p1701247092644559?thread_ts=1701216578.566079&cid=C061Q2GPARE)  を受けてのモーダルイメージ
![image](https://github.com/weseek/growi/assets/32846231/aaa232de-b70a-4bc0-8321-969d7f09a915)

2023-11-30 07:04 UTC, yuki-takei requested changes

2023-11-30 07:04 UTC, yuki-takei commented on apps/app/src/stores/modal.tsx
> +};
modal.tsx 肥大化してきているので、これも features/page-bulk-export 内に入れてください

2023-11-30 08:00 UTC, merged