imprv: Upload handler use apiv3 post
weseek/growi pull request #8279
Opened 2023-11-29 06:05 UTC by reiji-h

# 概要
`PageEditor.tsx` の uploadHandler 内で添付ファイルの作成に apiv3 を使用するように変更

# Task
- https://redmine.weseek.co.jp/issues/131756
  - https://redmine.weseek.co.jp/issues/131772

## コメントの削除について
- `editorRef.current.insertText(insertText); `
  - `codeMirrorEditor?.insertText(insertText);` に変更したため削除
- `editorRef.current.terminateUploadingState();`
  - react-dropzone に状態の管理を任せて不要になったため削除

2023-11-29 07:35 UTC, jam411 requested changes

2023-11-29 07:35 UTC, jam411 commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +        const { data: resLimit }: any = await apiv3Get('/attachment/limit', { fileSize: file.size });
`: any` 消しちゃっていいと思います

2023-11-29 07:35 UTC, jam411 commented on apps/app/src/server/routes/apiv3/attachment.js
> +  });
query のバリデーションを作って middleware として適用してください。

2023-11-29 07:35 UTC, jam411 commented on apps/app/src/server/routes/apiv3/attachment.js
> +    }
同じくバリデーションを作ってください。そうすればこのあたりの処理もいらなくなる？

2023-11-29 07:38 UTC, jam411 requested changes

2023-11-29 07:38 UTC, jam411 commented on apps/app/src/server/routes/apiv3/attachment.js
> +    return res.apiv3(await fileUploadService.checkLimit(fileSize));
try-catch でエラーハンドリングが必要ではないか？

2023-11-30 05:37 UTC, reiji-h commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +        const { data: resLimit }: any = await apiv3Get('/attachment/limit', { fileSize: file.size });
消しました。

2023-11-30 05:48 UTC, reiji-h commented on apps/app/src/server/routes/apiv3/attachment.js
> +    return res.apiv3(await fileUploadService.checkLimit(fileSize));
`checkLimit` の箇所に try-catch を置きました。

2023-12-01 09:06 UTC, reiji-h commented on apps/app/src/server/routes/apiv3/attachment.js
> +    }
`req` 直下のバリデーションが無理そうだったので `req.file` は残しました。
また、`pagePath` はあったとしても使わず、`pageId == null, pagePath == なにか`という状況ではファイルのアップロードができないことからそもそも `pagePath` を入れるのをやめました。

2023-12-04 03:24 UTC, jam411 commented on apps/app/src/server/routes/apiv3/attachment.js
> +  router.post('/add', uploads.single('file'), accessTokenParser, loginRequired, validator.retrieveAddAttachment, apiV3FormValidator, addActivity,
ミドルウェアについて、元コードを見ると以下が気になりました。確認して修正 or 修正不要な旨コメントお願いします。
- loginRequired ではなく loginRequiredStrictly にしないといけないのでは？
- excludeReadOnlyUser が必要
- autoReap は不要か？

ref: `apiV1Router.post('/attachments.add' , uploads.single('file'), autoReap, accessTokenParser, loginRequiredStrictly , excludeReadOnlyUser, addActivity , attachmentApi.add);`

2023-12-05 05:07 UTC, reiji-h commented on apps/app/src/server/routes/apiv3/attachment.js
> +  router.post('/add', uploads.single('file'), accessTokenParser, loginRequired, validator.retrieveAddAttachment, apiV3FormValidator, addActivity,
全て apiV1Router とそろえるために必要だったので加えました。

2023-12-05 05:08 UTC, reiji-h commented on apps/app/src/server/routes/apiv3/attachment.js
> +  router.get('/limit', accessTokenParser, loginRequired, validator.retrieveFileLimit, apiV3FormValidator, async(req, res) => {
ありがとうございます。

2023-12-05 06:38 UTC, jam411 commented on apps/app/src/server/routes/apiv3/attachment.js
> +    const fileSize = Number(req.query.fileSize);
Number() で囲っているけれど、validator.isNumeric() で検証しているので不要だと思う。

`/attachment/limit` を使っている個所は一か所しかなく number 型が入ってくる

accessToken を使ったときに対応しているのか？
ただ、その場合でも isNumeric() により検証できるようになるはず。

2023-12-05 06:38 UTC, jam411 commented on apps/app/src/components/PageEditor/PageEditor.tsx
>          }
直接 PR に関係ないですが、この処理は必要でしょうか？

2023-12-06 06:09 UTC, reiji-h commented on apps/app/src/server/routes/apiv3/attachment.js
> +    const fileSize = Number(req.query.fileSize);
確かに試したところ不要でしたので外します。

2023-12-07 06:27 UTC, jam411 approved these changes

2023-12-07 06:27 UTC, jam411 commented on apps/app/src/server/routes/apiv3/attachment.js
> +    const fileSize = Number(req.query.fileSize);
クエリパラメータはテキストで渡るので number 型へのキャストが必要

2023-12-08 06:15 UTC, yuki-takei requested changes

2023-12-08 06:15 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/attachment.js
> +  router.post('/add', uploads.single('file'), autoReap, accessTokenParser, loginRequiredStrictly, excludeReadOnlyUser,
`router.post('/',` でいいと思います

2023-12-08 07:24 UTC, merged