feat: Open drawio modal in editor
weseek/growi pull request #8281
Opened 2023-11-29 07:44 UTC by soumaeda

# 概要
エディタ画面でDrawioモーダルを開くことができるようにしました。

# やったこと
- useDrawioModalForEditorというフックを作成し、DiagramButtonとDrawioModalから参照できるようにした

# Task
https://redmine.weseek.co.jp/issues/135366

# 後続タスク
(マイグレーション対応)
https://redmine.weseek.co.jp/issues/135426
(TS化)
https://redmine.weseek.co.jp/issues/135842
(図をエディタに入れる)
https://redmine.weseek.co.jp/issues/135845

2023-11-29 08:24 UTC, jam411 requested changes

2023-11-29 08:24 UTC, jam411 commented on apps/app/src/components/PageEditor/DrawioModal.tsx
> +  const { data: drawioModalDataInEditor } = useDrawioModalForEditor();
drawioModal の開閉は２種類必要なんですか？

2023-11-29 08:35 UTC, soumaeda commented on apps/app/src/components/PageEditor/DrawioModal.tsx
> +  const { data: drawioModalDataInEditor } = useDrawioModalForEditor();
本体側のフックとeditor配下のフックをそれぞれ参照するために追加しました。

2023-12-04 04:04 UTC, jam411 commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
> +  const openDrawioModalHandler = useCallback(() => {
handler 名が、また挙動を表すものになってる。
「DiagramButton をクリックすると」を表す名前にして。

2023-12-04 04:08 UTC, jam411 commented on packages/editor/src/stores/use-drawio.ts
onSave 変数があるので、このスコープで保存までできるようになっているのかわからないが、後続タスクで修正が入る認識: https://redmine.weseek.co.jp/issues/135845

2023-12-04 11:16 UTC, merged