Imprv/133905 replace icons material symbols outlined
weseek/growi pull request #8282
Opened 2023-11-29 08:04 UTC by meiri-k

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/ConfirmModal.tsx
<img width="359" alt="スクリーンショット 2023-12-21 15 08 14" src="https://github.com/weseek/growi/assets/34241526/f22c512f-e8dc-437e-86d0-2ce823ec7070">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/FileUploadSetting.tsx
<img width="710" alt="スクリーンショット 2023-12-21 15 34 58" src="https://github.com/weseek/growi/assets/34241526/58764b52-e086-4660-9267-0eafcad4e40e">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/MailSetting.tsx
<img width="280" alt="スクリーンショット 2023-12-21 15 39 13" src="https://github.com/weseek/growi/assets/34241526/61162648-099f-4965-b90b-a9171428cc21">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/MaintenanceMode.tsx
<img width="383" alt="スクリーンショット 2023-12-21 15 40 13" src="https://github.com/weseek/growi/assets/34241526/f550b899-a06d-4ca1-a5ee-7069579ef2b2">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/QuestionnaireSettings.tsx
<img width="293" alt="スクリーンショット 2023-12-21 15 41 23" src="https://github.com/weseek/growi/assets/34241526/ba12b90b-fb72-4756-8028-8211c84b575c">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/SiteUrlSetting.tsx
<img width="384" alt="スクリーンショット 2023-12-21 15 42 59" src="https://github.com/weseek/growi/assets/34241526/9760ef4e-9c82-4ade-b8f7-586daace08d8">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/QuestionnaireSettings.tsx
外部リンクアイコンが存在しなかったので適当なアイコンを借り置きしています。

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/V5PageMigration.tsx
<img width="345" alt="スクリーンショット 2023-12-21 15 49 00" src="https://github.com/weseek/growi/assets/34241526/eea6552a-1401-4368-82f8-a7ccd52ea691">

2023-12-21 06:57 UTC, miya commented on apps/app/_obsolete/src/components/Navbar/GrowiNavbar.tsx
>        </span>
apps/app/_obsolete/ 配下なのでおそらく不要な差分

2023-12-21 06:57 UTC, miya commented on apps/app/_obsolete/src/components/PageEditor/CodeMirrorEditor.jsx
>    }
apps/app/_obsolete/ 配下なのでおそらく不要な差分

2023-12-21 06:57 UTC, miya commented on apps/app/_obsolete/src/components/PageEditor/ConflictDiffModal.tsx
>                </div>
apps/app/_obsolete/ 配下なのでおそらく不要な差分

2023-12-21 06:57 UTC, miya commented on apps/app/_obsolete/src/components/PageEditorByHackmd.tsx
>                {errorReason}
apps/app/_obsolete/ 配下なのでおそらく不要な差分

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/ConfirmModal.tsx
>                </span>
<img width="359" alt="292108454-f22c512f-e8dc-437e-86d0-2ce823ec7070" src="https://github.com/weseek/growi/assets/34241526/4d45354b-9334-4899-bf56-16eab1bbaf6a">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/FileUploadSetting.tsx
>            </p>
<img width="710" alt="292113466-58764b52-e086-4660-9267-0eafcad4e40e" src="https://github.com/weseek/growi/assets/34241526/35442b0d-998c-4adf-b277-809da362ab57">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/MailSetting.tsx
>          <label className="col-md-3 col-form-label text-end">{t('admin:app_setting.from_e-mail_address')}</label>
<img width="280" alt="292114422-61162648-099f-4965-b90b-a9171428cc21" src="https://github.com/weseek/growi/assets/34241526/9b240aea-4b7e-4245-bfc6-9b8a210e3586">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/MaintenanceMode.tsx
>        </p>
<img width="383" alt="292114845-f550b899-a06d-4ca1-a5ee-7069579ef2b2" src="https://github.com/weseek/growi/assets/34241526/f3d098e3-10a8-4618-a068-f91900e566a7">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/QuestionnaireSettings.tsx
>            {t('app_setting.other_info_will_be_sent')}<br />
<img width="293" alt="292115054-ba12b90b-fb72-4756-8028-8211c84b575c" src="https://github.com/weseek/growi/assets/34241526/9e2badd4-2c18-4ec1-bdbc-cb3a63c78880">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/SiteUrlSetting.tsx
>          <div className="row">
<img width="384" alt="292115329-9760ef4e-9c82-4ade-b8f7-586daace08d8" src="https://github.com/weseek/growi/assets/34241526/2b2b79ba-09aa-40fc-bacb-ec7effa2d843">

2023-12-21 06:57 UTC, miya commented on apps/app/src/components/Admin/App/V5PageMigration.tsx
>        </p>
<img width="345" alt="292116520-eea6552a-1401-4368-82f8-a7ccd52ea691" src="https://github.com/weseek/growi/assets/34241526/3524cf0e-d30c-4990-8272-d54f22234821">

2023-12-21 07:06 UTC, miya commented on apps/app/src/components/Admin/App/QuestionnaireSettings.tsx
>            {t('app_setting.other_info_will_be_sent')}<br />
外部リンクアイコンが存在しなかったので適当なアイコンを借り置きしています。
存在しないアイコンに関してはふみやさんに依頼をしています。後から探せるように TODO コメントを貼っています。

2024-01-09 00:49 UTC, miya commented on apps/app/src/components/CompleteUserRegistrationForm.tsx
>                </div>
<img width="356" alt="スクリーンショット 2024-01-09 9 04 05" src="https://github.com/weseek/growi/assets/34241526/1310d936-c724-48dc-8aee-6e804eeede6d">

2024-01-09 00:49 UTC, miya commented on apps/app/src/components/CompleteUserRegistration.tsx
>        </div>
<img width="373" alt="スクリーンショット 2024-01-09 9 19 25" src="https://github.com/weseek/growi/assets/34241526/25bd52cd-0956-4cce-9798-93f95d7b4564">

2024-01-09 00:49 UTC, miya commented on apps/app/src/components/Bookmarks/BookmarkFolderItemControl.tsx
>        </DropdownMenu>
<img width="151" alt="スクリーンショット 2024-01-09 9 42 29" src="https://github.com/weseek/growi/assets/34241526/0f2643b6-65f5-4ccc-833a-57fce86332f9">

2024-01-09 00:49 UTC, miya commented on apps/app/src/components/Common/PagePathHierarchicalLink/PagePathHierarchicalLink.tsx
>              // eslint-disable-next-line react/no-danger
まだスタイルが洗練されていない
<img width="267" alt="スクリーンショット 2024-01-09 9 48 24" src="https://github.com/weseek/growi/assets/34241526/219d2f5e-7771-40a7-8345-14fa83e9e1ba">

2024-01-09 00:49 UTC, miya commented on apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
>              </div>
<img width="176" alt="スクリーンショット 2024-01-09 9 49 05" src="https://github.com/weseek/growi/assets/34241526/4cf4ed6d-998b-4572-9024-0cbf4bbc1891">

2024-01-09 05:56 UTC, yuki-takei requested changes

2024-01-09 05:56 UTC, yuki-takei commented on apps/app/src/components/Admin/App/ConfirmModal.tsx
> +        <div className="d-flex align-items-center">
この箇所に限らないんだけど、d-flex で囲うという解でいいのかを検討したい。

d-flex を付ける以前は、中の dom は `display: inline-block` だったはずだが、d-flex を付けることで `display: block` になると思う。できれば中身を inline 要素にしたまま縦方向の整列をしたい。
(検討の結果、d-flex にするのがベストという着地も有り得る)

2024-01-10 08:28 UTC, miya commented on apps/app/src/styles/_fonts.scss
> +  vertical-align: middle;
fontawsome から material icon に置き換えた人のコメントを参考にしました。
> I was using font Awesome and to get the exact same Vertical Align with Material Font, I setup this CSS and it aligns perfectly
> ```css
> .material-icons {
>   vertical-align: middle;
>   padding-bottom: 3px 
> }
> ```

https://stackoverflow.com/questions/43360526/align-material-icon-vertically

2024-01-11 12:00 UTC, merged