feat: 132740 135570 save UI settings
weseek/growi pull request #8288
Opened 2023-11-30 04:32 UTC by yukendev

https://redmine.weseek.co.jp/issues/135570

# やったこと
- 編集時のサイドバーモードの設定を削除
- 設定のスイッチを切り替えたタイミングでswrに状態を保存、サイドバーの見た目を変更するようにした
- 更新ボタンを押したタイミングでDBに保存するようにした
- 画面がlg以下の場合はUI設定のコンポーネントを表示しないようにしました

# 備考
- 更新ボタンを押したタイミングでDBの`useruisettinsprefer`の`CollapsedModeByUser`が更新されていることを確認しました

2023-11-30 04:34 UTC, yukendev commented on apps/app/public/static/locales/en_US/translation.json
>        "description": "You can set whether the sidebar is always open or not."
編集時のサイドバーモードの設定は必要なかったので翻訳ファイルから削除しました

2023-11-30 04:36 UTC, yukendev commented on apps/app/src/components/Me/UISettings.tsx
> +
スイッチでモードを変更した時は、swrのmutateのみを呼んで、swrで状態を保持、見た目を変更するだけです。更新ボタンを押したタイミングでDBに保存しています。

2023-11-30 04:36 UTC, yukendev commented on apps/app/src/components/Me/UISettings.tsx
編集時のサイドバーモードの設定は必要なかったのでコンポーネントを削除しました。

2023-11-30 04:41 UTC, yukendev commented on apps/app/src/components/Me/UISettings.tsx
>      <>
`sidebarMode != null && !isDrawerMode()`の条件で画面の大きさがlg以下の場合はUI設定のコンポーネントを表示しないようにしました。本当はサイドバーモードの設定のみが表示されないのが理想ですが、現在UI設定にサイドバーの設定しかないため、UI設定ごと消すようにしています。

2023-11-30 07:24 UTC, yuki-takei requested changes

2023-11-30 07:24 UTC, yuki-takei commented on apps/app/src/components/Me/UISettings.tsx
> +      scheduleToPut({ preferCollapsedModeByUser: isCollapsedMode() });
- 現状の scheduleToPut は debounce が効いてしまう
- sync function なので保存失敗しても catch に入らない

上記理由から、try-catch に対応した、即座に保存するメソッドを実装すべきかと

2023-11-30 07:24 UTC, yuki-takei commented on apps/app/src/components/Me/UISettings.tsx
>      <>
表示隠す必要はないと思うなあ

どちらかというと、この設定は lg サイズ以上のときのみ効果があるんだよという説明がありさえすればいい。

2023-12-01 03:31 UTC, yukendev commented on apps/app/src/components/Me/UISettings.tsx
>      <>
修正済み

2023-12-01 03:37 UTC, yukendev commented on apps/app/src/components/Me/UISettings.tsx
> +      scheduleToPut({ preferCollapsedModeByUser: isCollapsedMode() });
`apiv3Put`を直接呼んで保存するようにしました

2023-12-01 08:03 UTC, yuki-takei requested changes

2023-12-01 08:03 UTC, yuki-takei commented on apps/app/src/components/Me/UISettings.tsx
> +      await apiv3Put<IUserUISettings>('/user-ui-settings', { settings: { preferCollapsedModeByUser: isCollapsedMode() } });
apiv3Put を呼ぶコードはサービス層に寄せてほしい

2023-12-05 02:43 UTC, yukendev commented on apps/app/src/components/Me/UISettings.tsx
> +      await apiv3Put<IUserUISettings>('/user-ui-settings', { settings: { preferCollapsedModeByUser: isCollapsedMode() } });
debounceなしで保存するメソッドをサービス層に作成して、そのメソッドをここで呼ぶようにしました

2023-12-05 03:12 UTC, merged