feat: incremental search results
weseek/growi pull request #8292
Opened 2023-12-01 01:51 UTC by miya

## Task
[#134384](https://redmine.weseek.co.jp/issues/134384) [v7][search] 全文検索用モーダルでインクリメンタルサーチ結果を表示し、それを選択することで検索結果画面へ遷移できる
┗ [#135930](https://redmine.weseek.co.jp/issues/135930) インクリメンタルサーチ結果を表示する見た目の実装

2023-12-01 07:36 UTC, miya commented on apps/app/src/features/search/client/components/SearchModal.tsx
> +  const { data: searchResult } = useSWRxSearch(searchKeyword, null, { limit: 10 });
debounce 処理は後続タスクで行います

2023-12-01 07:36 UTC, miya commented on apps/app/src/features/search/client/components/SearchResults.tsx
> +                <span className="ms-3">{pageWithMeta.data.seenUsers.length}</span>
足跡アイコンの設置は後続タスクで行います

2023-12-01 08:55 UTC, yuki-takei requested changes

2023-12-04 00:50 UTC, miya commented on apps/app/src/features/search/client/components/SearchResults.tsx
useSWRxSearch を SearchResultMenuIrtem の中で呼ぶよ雨に修正しました

2023-12-04 23:30 UTC, merged