imprv: Correspond with codemirror migration
weseek/growi pull request #8295
Opened 2023-12-01 09:30 UTC by soumaeda

# 概要
MarkdownDrawioUtil.js で codemirror6へのマイグレーション対応をした。

# やったこと
https://codemirror.net/docs/migration/
codemirrorのマイグレーションガイドに従って、MarkdownDrawioUtil.jsを修正しました。

# task
https://redmine.weseek.co.jp/issues/135426

# 後続タスク
(MarkdownDrawioUtil の TS化・関数コンポーネント化)
https://redmine.weseek.co.jp/issues/135842

2023-12-06 06:14 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +      const bodLineNum = this.doc(editor).lineAt(bod).number + 1;
行番号を取得

2023-12-06 06:14 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +      const bodLine = this.doc(editor).line(bodLineNum).from;
行の先頭を取得

2023-12-06 06:14 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +      const eodLine = this.doc(editor).line(eodLineNum).to;
行末を取得

2023-12-06 06:14 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +      return editor.state.sliceDoc(bodLine, eodLine);
bodLineからeodLineまでの範囲のtextを返す

2023-12-06 06:54 UTC, jam411 requested changes

2023-12-06 06:54 UTC, jam411 commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +      const line = this.doc(editor).line(i + 1).text;
`firstLine()`, `lastLine()`, `getLineText()` みたいな感じでメソッド化してください。

2023-12-06 07:32 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +      const line = this.doc(editor).line(i + 1).text;
メソッド化しました

2023-12-06 08:05 UTC, jam411 requested changes
curPos(editor) はすべて lineAt で処理しているので共通化できないですか？

2023-12-06 08:05 UTC, jam411 commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +  // get list line number
list なのか？

2023-12-06 08:05 UTC, jam411 commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +  // get line information
information でなく line でいいと思う

2023-12-06 08:05 UTC, jam411 commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +  firstLine() {
`firstLineNum()`　でお願いします。

2023-12-06 08:05 UTC, jam411 commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +  lastLine(editor) {
`lastLineNum()`

2023-12-06 08:08 UTC, jam411 requested changes

2023-12-06 08:08 UTC, jam411 commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +    for (firstLine, lastLine; firstLine <= lastLine; firstLine++) {
`firstLine, lastLine;` この初期化必要？

2023-12-07 02:17 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +  // get list line number
last でした

2023-12-07 07:03 UTC, jam411 commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +      endPos = this.getCursorLine(editor).to;
既存コードがまったく同じものを返しているように見えるが to from にしても大丈夫かな？
```
beginPos = { line: curPos.line, ch: curPos.ch };
endPos = { line: curPos.line, ch: curPos.ch };
```

2023-12-07 07:09 UTC, jam411 requested changes

2023-12-07 07:29 UTC, jam411 commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +      endPos = this.getCursorLine(editor).to;
else なら cursor pos を返せばいい。
select しているときの挙動を確認する必要がある

2023-12-07 07:34 UTC, jam411 requested changes

2023-12-07 07:38 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +      endPos = this.getCursorLine(editor).to;
エディタの空白行にカーソルが当たっている時はそのカーソル位置にdrawioを入れるので、既存コードのように、beginPosとendPosの双方にカーソルポジションを入れるようにしました

2023-12-07 07:41 UTC, soumaeda commented on apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
> +    const eodLine = Math.min(line, this.lastLineNum(editor));
this.firstLineNum()も const firstLineNum に代入しました。

2023-12-08 05:48 UTC, merged