feat: Uniform behavior when creating pages from create new page button
weseek/growi pull request #8297
Opened 2023-12-04 07:50 UTC by jam411

https://redmine.weseek.co.jp/issues/135811

2023-12-08 06:00 UTC, yuki-takei commented
- `/trash` `/me` `/tags` 遷移時の useSWRxCurrentPage キャッシュ対策はしておきたい
    - 遷移時に flush するなど

2023-12-08 06:01 UTC, yuki-takei commented
>/{path}/{additional_path} が作成できないパス（path が Not Found Page や Not Creatable Page なども）であるか、もしくは path を受け取れないときは、ルートページ配下へ /{additional_path} を作成もしくへ編集画面へ遷移する

これは不正確では？
`/{path}` が not found か not creatable かどうかは、`/{path}/{additional_path}` を作成可能かとは関係がない。

2023-12-08 06:08 UTC, yuki-takei requested changes

2023-12-08 06:08 UTC, yuki-takei commented on apps/app/src/components/Sidebar/PageCreateButton/hooks.tsx
> +      router.push(`${response.page.path}#edit`);
これは id のままが望ましい。path にしなければいけないなんらかの事情は、createPage からの response の方を変える方がベターではないか？を疑う。

ピンとこなければ具体的な「なんらかの事情」の事例とともに相談してください。

2023-12-08 06:08 UTC, yuki-takei commented on apps/app/src/client/services/use-on-template-button-clicked.ts
> +    isLoading?: boolean,
currentPagePath と順番逆がいいね

2023-12-15 11:18 UTC, jam411 commented on apps/app/src/components/Sidebar/PageCreateButton/hooks.tsx
> +      router.push(`${response.page.path}#edit`);
`router.push(`/${response.page.id}#edit`);` として `/` を加えれば対応できたので id 使用に戻しました。

2023-12-15 11:22 UTC, jam411 commented on apps/app/src/pages/utils/commons.ts
> +  mutate(undefined, { revalidate: false });
useInitSidebarConfig でキャッシュをクリアするようにしました。
- useCurrentPagePath の中で読んでいる useSWRxCurrentPage のキャッシュを消す必要がありました。
- mutate を使っているのは https://swr.vercel.app/docs/advanced/cache#modify-the-cache-data を参照

2023-12-15 14:21 UTC, yuki-takei requested changes

2023-12-15 14:21 UTC, yuki-takei commented on apps/app/src/pages/utils/commons.ts
> +  mutate(undefined, { revalidate: false });
ここに書くとこの hook を使っているコンポーネントが re-rendering される度に mutate が走るので、ここでやるのは違う

2024-01-04 11:13 UTC, merged