feat: Able to edit drawio in modal
weseek/growi pull request #8304
Opened 2023-12-06 06:25 UTC by soumaeda

# 概要
DrawioModal でエディタ上の drawio を取得し、編集できるようにしました。

# やったこと
- DiagramButton からエディタの状態を`useDrawioModalForEditor`フック経由で DrawioModal に渡し、DrawioModal 内でエディタ上でカーソルがdrawio中に位置指定れば、`getMarkdownDrawioMxfile`でdrawioを取得し、DrawioModalに表示させるようにした。
- エディタ上で DrawioModal のsaveボタンを押すと、`replaceFocusedDrawioWithEditor`により、DrawioModalで編集したdrawioがエディタに挿入されるようにした。

# Task
https://redmine.weseek.co.jp/issues/135845
https://redmine.weseek.co.jp/issues/136228

# 後続タスク
 (MarkdownDrawioUtil.js のTS化)
https://redmine.weseek.co.jp/issues/135842
(editorKeyがnullの場合の処理)
https://redmine.weseek.co.jp/issues/136640

# 後続ストーリー
(drawioの折りたたみ)
https://redmine.weseek.co.jp/issues/136473

2023-12-08 02:20 UTC, jam411 approved these changes

2023-12-08 05:56 UTC, yuki-takei requested changes

2023-12-08 05:56 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
> +    openDrawioModal(editor);
store に渡すものって、editor instance である必要ってある？editorKey でもいいんじゃないかと思うんだけど。

2023-12-08 05:56 UTC, yuki-takei commented on apps/app/src/components/PageEditor/DrawioModal.tsx
> +  const editor = drawioModalDataInEditor?.editor;
editor が null の場合は、モーダルが開いても利用不能にするなどの措置が必要そう

2023-12-12 02:56 UTC, soumaeda commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
> +    openDrawioModal(editor);
editorKeyを`useDrawioModalForEditor`に渡し、DrawioModal でエディターインスタンスを取得するようにしました。

2023-12-12 03:08 UTC, soumaeda commented on apps/app/src/components/PageEditor/DrawioModal.tsx
> +  const editor = drawioModalDataInEditor?.editor;
こちら後続タスクで取りかかります。

修正により`editorKey`が`useDrawioModalForEditor`経由でDrawioModalに渡ってくるので、`editorKey`がnullの場合は

> モーダルが開いても利用不能にするなどの措置
をするようにします。

https://redmine.weseek.co.jp/issues/136640

2023-12-12 12:46 UTC, merged