imprv: Change drawio util file to TS and function component
weseek/growi pull request #8305
Opened 2023-12-06 06:54 UTC by soumaeda

# 概要
MarkdownDrawioUtil.js の TS化、関数コンポーネント化

# Task
https://redmine.weseek.co.jp/issues/135842

# 後続タスク
https://redmine.weseek.co.jp/issues/135845
https://redmine.weseek.co.jp/issues/136228

2023-12-12 04:53 UTC, jam411 requested changes

2023-12-12 04:53 UTC, jam411 commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-editor.ts
> +export const getMarkdownDrawioMxfile = (editor: EditorView): string | undefined | null => {
`getMarkdownDrawioMxfile` あたり、`markdown-drawio-util-for-editor.ts` にある関数の呼び出し元のパスは修正ずみでしょうか？

2023-12-12 04:54 UTC, jam411 requested changes

2023-12-12 04:54 UTC, jam411 commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-editor.ts
> +const firstLineNum = 1;
これは定数として
```
const lineBeginPartOfDrawioRE = /^```(\s.*)drawio$/;
const lineEndPartOfDrawioRE = /^```$/;
```
の下に移動してまとめておいてください

2023-12-12 06:50 UTC, soumaeda commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-editor.ts
> +export const getMarkdownDrawioMxfile = (editor: EditorView): string | undefined | null => {
今のところは`drawio-modal-launcher-for-view.ts`で replaceDrawioInMarkdown をインポートしているだけでした。
現時点ではそれ以外の呼び出し元のパスの修正が必要な箇所はありませんでした

2023-12-13 04:11 UTC, soumaeda commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-editor.ts
> +export const getMarkdownDrawioMxfile = (editor: EditorView): string | undefined | null => {
https://github.com/weseek/growi/pull/8304がマージされたので、DrawioModal内で`markdown-drawio-util-for-editor.ts`の getMarkdownDrawioMxfile と replaceFocusedDrawioWithEditor が使われるようになったため、呼び出し元のパスの修正をしました。

2023-12-13 04:15 UTC, soumaeda commented
# 修正点
- DrawioModal内でmarkdown-drawio-util-for-editor.tsの getMarkdownDrawioMxfile と replaceFocusedDrawioWithEditor が使われるようになったため、呼び出し元のパスの修正。
- getMarkdownDrawioMxfie関数からnullが返ってくる場合があるため、`DrawioCommunicationHelper.ts`のonReceiveMessageでもdtawioMxfileにnullを許容するように変更しました。

2023-12-13 04:45 UTC, jam411 requested changes

2023-12-13 04:45 UTC, jam411 commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-view.ts
> +   */
コメントの改行を
```
/**
 *
 */
```
にしてください
/** にカーソルを合わせて Enter キーでインデントできるはず。

- 同様に他も修正しておいてください。

2023-12-13 04:45 UTC, jam411 commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-editor.ts
> +  let endPos;
number 型にした場合、getBod, getEod で null が入ってくる場合を考慮できてないです。

isInDrawioBlock() で担保されているから、例外処理（やりすぎか？）とも思いましたが、

isInDrawioBlock 内でも getBod, getEod やっていて無駄な気がするので、isInDrawioBlock を廃止して処理をまとめていいと思いましたがどうですか？
例：
```
  const bod = getBod(editor);
  const eod = getEod(editor);

  if (bod === null || eod === null || JSON.stringify(bod) === JSON.stringify(eod)) {
    return null;
  }
```

2023-12-13 04:45 UTC, jam411 commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-editor.ts
> +};
現在使用してないと思うからコメントアウトとコメントしておいてください。
```
TODO: This function is obsolete with `~/_obsolete/src/components/PageEditor/CodeMirrorEditor.jsx`
```

2023-12-13 04:45 UTC, jam411 commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-editor.ts
> +};
このあたり、タイプと変数名から役割がわかるのでコメントを削除しておいてください。

2023-12-13 05:09 UTC, soumaeda commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-editor.ts
> +};
後続ストーリーで findAllDrawioSection を利用可能にしたいので、
`TODO: https://redmine.weseek.co.jp/issues/136473` とコメントしました。

2023-12-13 05:49 UTC, soumaeda commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-editor.ts
> +  let endPos;
```
const bod = getBod(editor);
const eod = getEod(editor);
```
を繰り返していて、無駄があるなと思ったので、isInDrawioBlockを廃止し、`getMarkdownDrawioMxfile`と`eplaceFocusedDrawioWithEditor`内で`JSON.stringify(bod) === JSON.stringify(eod)`の場合に例外処理をするようにしました。

2023-12-13 07:04 UTC, yuki-takei requested changes

2023-12-13 07:04 UTC, yuki-takei commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-view.ts
このモジュールは PageEditor とは無関係なので別の場所へ移す

2023-12-14 02:59 UTC, soumaeda commented on apps/app/src/components/PageEditor/markdown-drawio-util-for-view.ts
components/Page配下に移動しました。

2023-12-14 03:04 UTC, merged