feat: 133860 design coding of creation screen
weseek/growi pull request #8307
Opened 2023-12-07 07:14 UTC by WNomunomu

2023-12-20 09:10 UTC, miya requested changes

2023-12-20 09:10 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowCreationModalContent.tsx
> +                  </div>
スコープが広がって悪いんだけどこれは編集画面でも使うので外部コンポーネントにして共通化して欲しい

2023-12-20 09:10 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowCreationModalContent.module.scss
> +  // background: linear-gradient(to right, blue 45%, blue 55%);
このコメントは何？

2023-12-20 09:10 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/EditableApproverGroupCards.tsx
> +const EditableApproverGroupCard = (props: Props & { groupIndex: number, isLastApproverGroup: boolean }): JSX.Element => {
ごめんこれってなんで必要なんだっけ？
実装が変わる場合はコメントつけてくれると助かります。

2023-12-21 06:33 UTC, WNomunomu commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/EditableApproverGroupCards.tsx
> +const EditableApproverGroupCard = (props: Props & { groupIndex: number, isLastApproverGroup: boolean }): JSX.Element => {
ワークフロー作成画面内の最後のApproverGroupCardの下のボタンだけスタイルが全く違うので、最後のApproverGroupであるかどうかを判定する必要がありました。

2023-12-21 07:14 UTC, miya requested changes

2023-12-21 07:14 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowForm.tsx
> +  editingWorkflowName: string | undefined
`editingWorkflowName?` って書いた方がシンプル

2023-12-21 07:14 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowForm.tsx
> +  editingWorkflowDescription: string | undefined
`editingWorkflowDescription?` って書いた方がシンプル

2023-12-21 07:14 UTC, miya commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/EditableApproverGroupCards.tsx
> +            </span>
これも考慮してくれて助かります。
まだ D&D でフローを移動できる実装になっていないのでその機能を実装するためのストーリーを作成して TODO コメントしておいてください。おそらく初期リリース時にはこの機能は付けないので多分コメントアウトすると思う。(今はあってもいい)

2023-12-21 08:28 UTC, yuki-takei requested changes

2023-12-21 08:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowCreationModalContent.module.scss
> +}
これなに用のスタイル？

2023-12-21 08:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/EditableApproverGroupCards.tsx
> +        <div className="rounded bg-light-subtle mt-5">
light/dark 対応を考えると `light` 色は適切ではない

2023-12-21 08:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/EditableApproverGroupCards.tsx
> +                      <span className="material-symbols-outlined text-light bg-secondary rounded-circle">add</span>
light/dark 対応を考えると `light` 色は適切ではない

2023-12-21 08:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/EditableApproverGroupCards.tsx
> +                    color="light"
light/dark 対応を考えると `light` 色は適切ではない

2023-12-21 08:28 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/EditableApproverGroupCards.tsx
> +                      <span className="material-symbols-outlined text-light bg-secondary rounded-circle">add</span>
light/dark 対応を考えると `light` 色は適切ではない

2023-12-22 12:32 UTC, yuki-takei requested changes

2023-12-22 12:32 UTC, yuki-takei commented on apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowCreationModalContent.module.scss
> +}
理解した。ちょっとトリッキーだね。

- 普通の灰色の棒を用意して、`position-absolute` して中央揃えした方がいい気がする。

- 色は bootstrap の scss 変数か css 変数(どちらでもよい)を参照するようにして。(後続ストーリーでもよい)

2023-12-25 10:10 UTC, merged