add types
weseek/growi pull request #8311
Opened 2023-12-09 06:32 UTC by arafubeatbox

2023-12-09 06:37 UTC, arafubeatbox commented on apps/app/src/server/service/page-grant.ts
> +      operator, updateGrant?: PageGrant, grantGroupIds?: IGrantedGroup[],
型を PageGrantCanBeOnTree に絞った上に、validation もメソッド内に行っていたというどっちつかずの状態だったので、validation だけに変更。メソッド仕様元では validation を実施していなかった。

2023-12-09 06:38 UTC, arafubeatbox commented on apps/app/src/server/service/page.ts
> +  pageGrantService: PageGrantService;
pageGrantService 内のメソッドの型チェックを利用したかった。

2023-12-09 06:39 UTC, arafubeatbox commented on apps/app/src/server/service/page-grant.ts
> +  grant?: number,
誤っていた型の修正

2023-12-09 09:17 UTC, arafubeatbox commented on apps/app/src/server/routes/page.js
> -    }
これによって自動的に https://redmine.weseek.co.jp/issues/136140 の「ページの内容の更新」が有効になります
元々仕様を満たしていたため、136140 で実施する内容はありません。却下にしておきます。

2023-12-15 13:28 UTC, yuki-takei requested changes

2023-12-15 13:28 UTC, yuki-takei commented on apps/app/src/server/service/page.ts
> +  pageGrantService: PageGrantService;
クラスそのものをインポートするのではなく、インターフェースを作成してください。もちろん `class PageGrantService implements IPageGrantService` とする。
宣言するメソッドはとりあえずこのサービスから参照しているものだけでいいと思う。

2023-12-18 04:22 UTC, merged