feat: Implementation of the behavior for the search menu (using downshift)
weseek/growi pull request #8325
Opened 2023-12-14 07:04 UTC by miya

2023-12-15 06:50 UTC, miya commented on apps/app/src/features/search/client/components/SearchForm.tsx
> +  }, [highlightedIndex, onEnterKeyDownHandler, searchKeyword]);
input にフォーカスを当てているときにキーボード操作を行なった時に呼ばれれるハンドラ (若干気持ち悪いがここはライブラリでカバーできなかった)

2023-12-15 06:50 UTC, miya commented on apps/app/src/features/search/client/components/SearchModal.tsx
> +          onSelect={(selectedItem: DownshiftItem) => { selectSearchMenuItemHandler(selectedItem.url) }}
MenuItem がハイライトされている状態でエンターキーを押下するかクリックすることで呼ばれる

https://github.com/downshift-js/downshift?tab=readme-ov-file#onselect

2023-12-15 09:38 UTC, miya commented on apps/app/src/features/search/client/components/SearchModal.tsx
> +              <ul {...getMenuProps({ onMouseLeave: () => { setHighlightedIndex(-1) } })} className="list-unstyled">
バグではありませんがメニューアイテムをホバーしてハイライトさせた後にカーソルをメニュー外に離すと、ホバーしたアイテムがハイライトされたままになってしまう問題がありました。

GitHub の検索フォームの UX を踏襲しているのでカーソルがメニューを離れたらハイライトを解除するというのが期待される動作だと言う認識です。

Issue とそれに対する解法があったので参考にしました。
https://github.com/downshift-js/downshift/issues/582

## Before
https://github.com/weseek/growi/assets/34241526/394a6377-c19d-40d4-ad93-4f4cd2f2e9b7

## After
https://github.com/weseek/growi/assets/34241526/f769a1d3-a1b7-4d47-a9bb-f4276c18e18f

2023-12-15 13:43 UTC, yuki-takei requested changes

2023-12-15 13:43 UTC, yuki-takei commented on apps/app/package.json
> +    "downshift": "^8.2.3",
devDependencies に移してください

2023-12-15 13:43 UTC, yuki-takei commented on apps/app/src/features/search/client/components/SearchForm.tsx
> +        onClick={clickCloseModalButtonHandler}
ボタン自体このコンポーネントから抜いていいと思うな

2023-12-15 13:43 UTC, yuki-takei commented on apps/app/src/features/search/client/components/SearchForm.tsx
> +  }, [highlightedIndex, onEnterKeyDownHandler, searchKeyword]);
Enter キーが押下されたことだけを検知できればいいのであれば、form でラップして onSubmit を利用することはできなかった？

2023-12-15 13:43 UTC, yuki-takei commented on apps/app/src/features/search/client/components/SearchForm.tsx
> +    && highlightedIndex == null
highlightedIndex が null という条件はこのコンポーネントの関心事には入らないいのでは？

2023-12-15 13:43 UTC, yuki-takei commented on apps/app/src/features/search/client/components/SearchMenuItem.tsx
> +  highlightedIndex: number | null
`highlightedIndex === index` という条件は `isActive: boolean` で入れたい

2023-12-16 03:39 UTC, miya commented on apps/app/src/features/search/client/components/SearchForm.tsx
> +        onClick={clickCloseModalButtonHandler}
確かに SearchForm の責務では無いので外しました

2023-12-16 03:40 UTC, miya commented on apps/app/src/features/search/client/components/SearchForm.tsx
> +  }, [highlightedIndex, onEnterKeyDownHandler, searchKeyword]);
ありがとうございます。form を使うことによって気持ち悪い部分が解消されました。

2023-12-16 03:40 UTC, miya commented on apps/app/package.json
> +    "downshift": "^8.2.3",
修正済み

2023-12-16 03:41 UTC, miya commented on apps/app/src/features/search/client/components/SearchForm.tsx
> +    && highlightedIndex == null
不要でしたので外しました

2023-12-18 03:38 UTC, miya commented on apps/app/src/features/search/client/components/SearchMenuItem.tsx
> +  highlightedIndex: number | null
`highlightedIndex === index` と言う条件は親コンポーネント側で計算して `isActive` を props で受け取れるようにしました。`index`  props は必須なので引き続き入れています。

2023-12-20 08:29 UTC, yuki-takei requested changes

2023-12-20 08:29 UTC, yuki-takei commented on apps/app/src/features/search/client/components/SearchMenuItem.tsx
> +      className: 'text-muted d-flex p-1',
これはスタイル指定ではなくクラス化し、light/dark mode 対応すべき。
後続タスクで構わない。

2023-12-20 08:47 UTC, merged