imprv: Unable to push Diagram Button when receive  editorKey as null
weseek/growi pull request #8330
Opened 2023-12-15 02:43 UTC by soumaeda

# 概要
edlitorKeyがnullの場合、DiagramButtonを利用不可にし、コンポーネントのレンダリングを極力抑制することにしました。

# やったこと
- DiagramButtonのonClickDiagramButtonハンドラー内で、editorKeyに対してnullガードしました。

# 仕様相談Slack
https://wsgrowi.slack.com/archives/C05LB9T4KR9/p1702524369757009

# Task
https://redmine.weseek.co.jp/issues/136640

2023-12-15 13:54 UTC, yuki-takei requested changes

2023-12-15 13:54 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
> +    }
Props の宣言の仕方的に editorKey が null になることは有り得ないのでは？

2023-12-18 02:47 UTC, soumaeda commented on packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
> +    }
editorKeyはprops経由でstringで渡ってきて、フック内でもstringで渡るので、editorKeyがnullで渡る可能性があるとしたらDrawioModal内なので、エディタ画面でedlitorKey が null の場合は、closeDrawioModalInEditorを発火させ、モーダルが開かないようにしました。

2023-12-19 05:20 UTC, yuki-takei requested changes

2023-12-19 05:20 UTC, yuki-takei commented on apps/app/src/components/PageEditor/DrawioModal.tsx
> +  if ((isOpened || isOpendInEditor) && editorKey == null && drawioModalData?.onSave == null) {
この条件はおかしい。
View から開く場合の条件は `drawioModalData?.isOpened` が true だけでよい。

だがそもそもこの修正方針自体微妙な感じがするので、キリの良いところで聞きに来てください。

2023-12-19 06:36 UTC, soumaeda commented
editorがnullの場合、`isOpendInEditor`がtrueにならないよう
`const isOpendInEditor = (editor != null && drawioModalDataInEditor?.isOpened) ?? false;`
としようと考えましたが、DiagramButtonを押した時にisOpenedもtrueになってしまうので、editorがnullの場合でも一度はisOpendInEditorがtrueになるが、その後`closeDrawioModalInEdior`するようにしました

2023-12-19 07:51 UTC, yuki-takei commented on apps/app/src/components/PageEditor/DrawioModal.tsx
> +  }
以下のようにしてください。

```
const isOpendInEditor = (drawioModalDataInEditor?.isOpened ?? false) && (editor != null)
```

2023-12-21 03:48 UTC, soumaeda commented
# 修正点
- editorがnullの場合には、isOpenedInEditorがfalseになるようにしました。
- useDrawioModalForEditor内のuseSWRStaticでkeyを`drawioModalStatus`としていたため、useDrawioModalとデータを共有していました。そのため、`drawioModalStatusForEditor`と一意のkeyにすることで独自のキャッシュを持つことができるようになりました。
- useDrawioModalForEditorからDrawioModalにonSaveを送ることはないので、削除しまいした。

2023-12-21 08:17 UTC, merged