add config for isAllGroupMembershipRequiredForPageCompleteDeletion
weseek/growi pull request #8352
Opened 2023-12-25 15:19 UTC by arafubeatbox

2023-12-28 08:58 UTC, arafubeatbox commented on apps/app/public/static/locales/en_US/admin.json
> +    "is_all_group_membership_required_for_page_complete_deletion_explanation": "Effective when page access settings is set to \"Only specific groups\".",
hogehoge_explain を hogehoge_explanation に統一

2024-01-04 10:15 UTC, yuki-takei requested changes

2024-01-04 10:15 UTC, yuki-takei commented on apps/app/src/server/service/page.ts
> +  async canDeleteCompletely(page: PageDocument, operator: any | null, isRecursively: boolean): Promise<boolean> {
このメソッドはかなり呼び出し回数が多いので async にしたくない。
(/routes/apiv3/page-listing.ts に付けたコメントを参照)


# #8224 の改修経緯と対応

当該 PR は「すでに削除されたユーザーのユーザーホームを削除する」機能を搭載することが目的だったが、その際にページ削除処理前、与えられたページパスと操作対象ユーザーの組みに対して以下を検査する必要があった。

- 与えられたページパスが `/user` 配下にあるかどうか
- 上記が true の時、持ち主のユーザーは存在するか(既に削除されたユーザーでないかどうか
    - この時、DBアクセスが必要になる

初期は今回の修正と同様に canDeleteCompletely を非同期化するようなコードだったが、上で説明したパフォーマンスへの懸念から canDeleteCompletely の修正は同期的に処理できる最小限のもの(configManager から取得した値のチェックなど)とした。

代わりに削除 API から直接かつ限定的な目的で利用する `filterPagesByCanDelete` を実装し、そちらに非同期通信が必要な処理を集めた。

同様の観点からリファクタをお願いしたい。

2024-01-04 10:15 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page-listing.ts
> +        const canDeleteCompletely = await pageService.canDeleteCompletely(page, req.user, false); // use normal delete config
この API は GROWI システムの中でも呼び出し頻度の高い API だが、ここは更に for 文のイテレーション内なので、パフォーマンス上の理由からここを await にはしたくない。
`service/page.ts` に書いたコメントを参照してほしい。

2024-01-14 08:16 UTC, arafubeatbox commented on apps/app/src/server/service/page.ts
> +  async canDeleteCompletely(page: PageDocument, operator: any | null, isRecursively: boolean): Promise<boolean> {
userRelatedGroups を canDeleteCompletely にパラメータとして渡すようにし、それを元に userRelatedGrantedGroups を計算するようにしました。
これにより、canDeleteCompletely は async でなくなります。

今回のロジックは各ページ依存なので、canDeleteCompletely から完全に分離しても結局 /page-listing/info での for 文イテレーション内での実行は必要となるため、async await で取得する必要がある情報だけを抽出しました。

2024-01-15 09:33 UTC, yuki-takei requested changes

2024-01-15 09:33 UTC, yuki-takei commented on apps/app/src/server/service/page/index.ts
> +      const canDelete = await canDeleteFunction(p, user, isRecursively, userRelatedGroups);
ここには await は不要ではないか？

2024-01-15 09:33 UTC, yuki-takei commented on apps/app/src/server/service/page/index.ts
> +    }
現状細かいロジック canDeleteLogic と compareDeleteConfig に閉じ込められているので、上記処理もそちら(または別のメソッド)に任せられないか？(可読性の観点から)

2024-01-15 12:31 UTC, arafubeatbox commented on apps/app/src/server/service/page/index.ts
> +    }
canDeleteCompletely から canDeleteCompletelyAsMultiGroupGrantedPage というメソッドに分離しました。

2024-01-15 12:36 UTC, merged