imprv: Insert number list only 1 in editor when enter line
weseek/growi pull request #8355
Opened 2023-12-27 07:35 UTC by soumaeda

# 概要
カーソルが位置している行頭に番号付きリストが存在している時にenterすると、改行した行頭にも`1.`が挿入される。

# やったこと
- マークダウンリストが行頭にあり、その行にカーソルを当てている状態でenterを押すと `newlineAndIndentContinueMarkdownList`を発火させる。
- `getStrFromBol`で行頭からカーソルまでの文字列を取得し、正規表現(indentAndMarkRE)に当てはまる場合は `insertText`でindentAndMark(getStrFromBolで取得したマークダウンアイテムのうち一番先頭にあったもの)を改行した行に挿入する

# Task
https://redmine.weseek.co.jp/issues/137432

2024-01-16 10:34 UTC, miya requested changes

2024-01-16 10:34 UTC, miya commented on packages/editor/src/services/list-util/markdown-list-util.ts
> +const indentAndMarkRE = /^(\s*)(>[> ]*|[*+-] \[[x ]\]\s|[*+-]\s|(\d+)([.)]))(\s*)/;
https://regex101.com を使ってコメントを追加してください (正規表現を書く時は必ず)。VSCode で全文検索してみると例が出ると思います。

2024-01-24 07:23 UTC, miya commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
> +      codeMirrorEditor?.view?.dom.removeEventListener('keydown', handleEnterKey);
`editor` 変数はあえて利用していない？

2024-01-30 10:52 UTC, yuki-takei requested changes

2024-01-30 10:52 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
> +        const strFromBol = getCurrentLine(editor);
変数名が beginning of line なのに current line を取得しているのが違和感がある
正常に動くのか？

2024-01-30 10:52 UTC, yuki-takei commented on packages/editor/src/services/list-util/markdown-list-util.ts
> +const insertText = (editor: EditorView, text: string) => {
insertText って他の箇所でも実装してなかったっけ？

2024-01-30 10:52 UTC, yuki-takei commented on packages/editor/src/services/list-util/markdown-list-util.ts
> +  const aboveLine = editor.state.doc.lineAt(curPos).number - 1;
カーソルが先頭行にあった場合に正常に動くのか？

2024-02-02 13:00 UTC, yuki-takei requested changes

2024-02-02 13:00 UTC, yuki-takei commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +  { key: 'Enter', run: insertNewlineContinueMarkup },
これもコード内コメントに残す

2024-02-02 13:36 UTC, merged