Feat/136288 136767 icon package
weseek/growi pull request #8356
Opened 2023-12-27 08:07 UTC by yukendev

WIP

2023-12-29 09:26 UTC, yukendev commented on apps/app/src/components/Me/UISettings.module.scss
>  .grw-sidebar-mode-icon {
アイコンの位置を調整

2023-12-29 09:26 UTC, yukendev commented on apps/app/src/components/Me/UISettings.tsx
> +            <div className="form-check form-switch ms-1">
アイコンの位置を調整

2023-12-29 09:27 UTC, yukendev commented on apps/app/src/server/service/mail.ts
> +      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
おそらく、`svgtofont`を追加したタイミングで`ejs`の型定義ファイルが追加され、`ts`のエラーが出るようになっていたので、いったん無視しています

2024-01-04 09:51 UTC, yuki-takei requested changes

2024-01-04 09:51 UTC, yuki-takei commented on packages/apps-font-icons/turbo.json
> +    "build": {}
```
"outputs": ["dist/**"],
"inputs": ["svg/**"],
"outputMode": "new-only"
```
あたりでどうだろう

2024-01-04 09:51 UTC, yuki-takei commented on packages/apps-font-icons/package.json
> +    "svgtofont": "^4.1.1"
devDependencies に移してください

2024-01-04 09:51 UTC, yuki-takei commented on packages/apps-font-icons/package.json
> +  "name": "@growi/apps-font-icons",
ディレクトリは `packages/custom-icons`
パッケージ名は `@growi/custom-icons`
にしましょう。

2024-01-04 09:51 UTC, yuki-takei commented on packages/apps-font-icons/.svgtofontrc
> +  "fontName": "growi-custom-icon",
`growi-custom-icons` にしましょう

2024-01-04 09:51 UTC, yuki-takei commented on apps/app/turbo.json
> +      "dependsOn": ["^dev", "dev:migrate", "dev:styles-prebuilt", "@growi/apps-font-icons#build"],
`@growi/apps-font-icons` 側で dev という名前のスクリプトを用意すればここに書き足す必要がなくなる

2024-01-05 06:43 UTC, yukendev commented on packages/apps-font-icons/turbo.json
> +    "build": {}
修正済み

2024-01-05 06:44 UTC, yukendev commented on packages/apps-font-icons/package.json
> +    "svgtofont": "^4.1.1"
修正済み

2024-01-05 06:49 UTC, yukendev commented on packages/apps-font-icons/package.json
> +  "name": "@growi/apps-font-icons",
修正済み

2024-01-05 06:53 UTC, yukendev commented on packages/apps-font-icons/.svgtofontrc
> +  "fontName": "growi-custom-icon",
修正済み

2024-01-05 07:05 UTC, yukendev commented on apps/app/turbo.json
> +      "dependsOn": ["^dev", "dev:migrate", "dev:styles-prebuilt", "@growi/apps-font-icons#build"],
修正済み

2024-01-05 10:42 UTC, yuki-takei commented on apps/app/turbo.json
> +      "dependsOn": ["^dev", "dev:migrate", "dev:styles-prebuilt", "@growi/apps-font-icons#build"],
直ってない

2024-01-09 12:01 UTC, merged