feat: Scroll sync
weseek/growi pull request #8361
Opened 2024-01-04 06:56 UTC by reiji-h

# 概要
- 編集画面における Editor と Preview のスクロール同期の実装

# Task
- https://redmine.weseek.co.jp/issues/126519
  - https://redmine.weseek.co.jp/issues/136101

2024-01-12 12:47 UTC, yuki-takei requested changes

2024-01-12 12:47 UTC, yuki-takei commented on apps/app/src/components/PageEditor/ScrollSyncHelper.ts
参考にした実装の permalink をコード内コメントに書いておいてほしい

2024-01-12 12:47 UTC, yuki-takei commented on packages/editor/src/services/extensions/setDataLine.ts
> +// Ref: https://www.npmjs.com/package/@uiw/codemirror-extensions-classname
permalink にしてください

2024-01-16 07:53 UTC, reiji-h commented on packages/editor/src/services/extensions/setDataLine.ts
> +// Ref: https://www.npmjs.com/package/@uiw/codemirror-extensions-classname
変更しました。

2024-01-17 12:28 UTC, yuki-takei requested changes

2024-01-18 08:11 UTC, reiji-h commented on packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
> +  setDataLine,
迷いましたが、`packages/editor` に残し、`CodeMirrorEditorMain.tsx` のほうに置くことにしました。

2024-01-19 16:46 UTC, merged