support: New Future
weseek/growi pull request #8367
Opened 2024-01-09 06:48 UTC by satof3

# Task
https://redmine.weseek.co.jp/issues/137469

# XD
- https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/6a7eb52c-77a1-43da-bb4e-50fc813189b1/
- https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/58fcb127-a1a9-4f5e-af21-5fce4c84fe5a/

# 内容
- Future テーマの実装

2024-01-10 08:38 UTC, yuki-takei requested changes

2024-01-10 08:38 UTC, yuki-takei commented on packages/preset-themes/src/styles/future.scss
> +$min-contrast-ratio: 2;
これは NG とする。

1. primary or highlight の値を変えられないかを検討する
2. どうしても変えたくない場合は、この行を消した上でどのようになってほしいのかをタスクに書いて武井に委譲する

2024-01-10 08:38 UTC, yuki-takei commented on packages/preset-themes/src/styles/future.scss
> +:root[data-bs-theme='dark'] {
dark 限定のテーマは light も受け付けるようにしないといけない。

2024-01-11 11:23 UTC, satof3 commented on packages/preset-themes/src/styles/future.scss
> +$min-contrast-ratio: 2;
`$min-contrast-ratio: 2;`を削除し、primaryを`#4FBFC2`から`#15A3A7`にすることで解決しました

2024-01-11 11:24 UTC, satof3 commented on packages/preset-themes/src/styles/future.scss
> +:root[data-bs-theme='dark'] {
教えていただいた`:root[data-bs-theme]{`の記述でエラーがでないことを確認しました

2024-01-12 12:20 UTC, merged