feat: Notification count badge
weseek/growi pull request #8372
Opened 2024-01-11 02:50 UTC by miya

## Task
[#137966](https://redmine.weseek.co.jp/issues/137966) [v7] サイドバーに通知を表示できる
┗ [#137967](https://redmine.weseek.co.jp/issues/137967) サイドバーアイコンに通知数を表示させる

2024-01-11 11:08 UTC, yuki-takei requested changes

2024-01-11 11:08 UTC, yuki-takei commented on apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.module.scss
> +  }
公式に則るのであれば
https://getbootstrap.com/docs/5.2/components/badge/#positioned

class を書くか css で書くかはまかせる

2024-01-11 11:08 UTC, yuki-takei commented on apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.tsx
> +      }
もっと汎用的に実装してほしい

- PrimaryItems では、props から badge を受け取ってレンダリングするだけにする
- Notification 用の PrimaryItems を独立したコンポーネントとして実装し、NotificationIconWithCountBadge 相当を badge props に入れる

2024-01-12 07:38 UTC, miya commented on apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.tsx
> +      }
PrimaryItems の badgeContents props (バッジの中身) を受け取るようにし badgeContents があれば badge をレンダリングできるようにしました

2024-01-16 06:21 UTC, miya commented on apps/app/src/components/Sidebar/InAppNotification/InAppNotificationSubstance.tsx
> +            onClickNotificationElm={mutateInAppNotificationData}
`isUnopendNotificationsVisible: true` の時に通知をクリックしても未読状態が変わらなかったので通知をクリックしたときに mutateInAppNotificationData() をするように改修しました。

2024-01-16 07:40 UTC, yuki-takei requested changes

2024-01-16 07:40 UTC, yuki-takei commented on apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.tsx
> +export const PrimaryItemsForNotification = memo((props: Props) => {
- 別モジュールに移す
- Props は PrimaryItemProps ベースにする
    - 不要な物は省く
    - sidebarMode は not null なものが入ってくるのを前提に実装する

2024-01-16 07:40 UTC, yuki-takei commented on apps/app/src/components/Sidebar/SidebarNav/SidebarNav.tsx
> +        <PrimaryItemsForNotification onItemHover={onPrimaryItemHover} />
PrimaryItems 内でインポートして並べるべきでは？

2024-01-16 10:10 UTC, miya commented on apps/app/src/components/Sidebar/SidebarNav/SidebarNav.tsx
> +        <PrimaryItemsForNotification onItemHover={onPrimaryItemHover} />
components/Sidebar/InAppNotification/PrimaryItemForNotification.tsx を import して並べました

2024-01-16 10:11 UTC, miya commented on apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.tsx
> +export const PrimaryItemsForNotification = memo((props: Props) => {
- Sidebar/InAppNotification/PrimaryItemForNotification.tsx にモジュールを切り出したました
- Props は PrimaryItemProps を import して不要なものを omit して使うようにしました
- https://github.com/weseek/growi/blob/feat/137967-notification-count-badge/apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.tsx#L26-L28 で not null なものが入っている場合はレンダリングしないように考慮されています

2024-01-23 12:37 UTC, yuki-takei requested changes

2024-01-23 12:37 UTC, yuki-takei commented on apps/app/src/components/Sidebar/InAppNotification/InAppNotificationSubstance.tsx
> +    isUnopendNotificationsVisible ? InAppNotificationStatuses.STATUS_UNOPENED : undefined,
- flicker が気になるのでコンフィグに `keepPreviousData: true,` を入れたい
- `revalidateOnFocus: true` は必要なのか？

2024-01-23 12:37 UTC, yuki-takei commented on apps/app/src/components/Sidebar/InAppNotification/InAppNotificationSubstance.tsx
> +            onClickNotificationElm={mutateInAppNotificationData}
クリックしたら発火という条件ではなく、
`await apiv3Post('/in-app-notification/open',` の処理が終わったら発火という条件のイベントだよね。
名が体を表すように変更して。

2024-01-23 13:56 UTC, miya commented on apps/app/src/components/Sidebar/InAppNotification/InAppNotificationSubstance.tsx
> +            onClickNotificationElm={mutateInAppNotificationData}
修正しました

2024-01-23 14:14 UTC, merged