imprv: Use unzip stream instead of unzipper
weseek/growi pull request #8378
Opened 2024-01-13 10:41 UTC by ryu-sato

やったこと

* unzipper の代わりに unzip-stream を使った
* unzipper をアンインストールした
* apps/app/src/server/service/growi-bridge.js を ts 化し、型エラーを解消
* apps/app/src/server/service/{growi-bridge.ts, import.js} に unzip-stream の型情報を参照した

確認したこと

* データアーカイブは正常に実行できた
* データインポートはアップロードした zip が展開できることは確認できた

注意点

* g2gtransfer は動作確認環境をどのように作ればよいのか分からず試せてません

2024-01-13 10:48 UTC, ryu-sato commented on apps/app/src/server/service/growi-bridge.ts
> +        entryStreams.push(streamToPromise(entry.pipe(metaStream)));
unzipStreamPipe に渡す関数を async にしつつ、この行で `await streamToPromise(entry.pipe(metaStream))` としても L137 の `await streamToPromise(unzipStreamPipe);` で待機されなかったので Promise.all で待機するようにしてます。

2024-01-15 08:57 UTC, yuki-takei requested changes

2024-01-15 08:57 UTC, yuki-takei commented on apps/app/src/server/service/growi-bridge.ts
> +import unzipStream, { Entry } from 'unzip-stream';
type のみのインポートのときは `import type` を使ってください

2024-01-15 08:57 UTC, yuki-takei commented on apps/app/src/server/service/growi-bridge.ts
> +        entryStreams.push(streamToPromise(entry.pipe(metaStream)));
ここで追加したコードはこれ相当？
https://github.com/ZJONSSON/node-unzipper/blob/master/lib/BufferStream.js

entry に対する汎用的な操作だと思うので、別モジュール(ファイル)に分割したい。

2024-01-20 11:16 UTC, ryu-sato commented on apps/app/src/server/service/growi-bridge.ts
> +        entryStreams.push(streamToPromise(entry.pipe(metaStream)));
> ここで追加したコードはこれ相当？
> https://github.com/ZJONSSON/node-unzipper/blob/master/lib/BufferStream.js

そうです。

モジュール化します。

2024-01-22 18:38 UTC, merged