Feat/136139 137890 page duplicate for multiple group grant
weseek/growi pull request #8381
Opened 2024-01-14 15:17 UTC by arafubeatbox

2024-01-17 15:32 UTC, arafubeatbox commented on apps/app/src/server/service/page/index.ts
> +      grantUserGroupIds: grantedGroupIds,
2 の validation 実行で使用した情報ではなく、page から取得したデータを渡しており、恐らくバグ？だったので修正しました。

2024-01-17 15:41 UTC, arafubeatbox commented on apps/app/src/server/service/page/index.ts
> -  async getUserRelatedGrantedGroups(page: PageDocument, user): Promise<IGrantedGroup[]> {
pageGrant service に移動

2024-01-19 16:39 UTC, yuki-takei requested changes

2024-01-20 05:43 UTC, arafubeatbox commented on apps/app/public/static/locales/ja_JP/translation.json
> +      "Only duplicate user related resources": "ユーザに関連のあるリソースのみを複製する"
後続タスクを作成しました。
https://redmine.weseek.co.jp/issues/138858

2024-01-20 05:44 UTC, merged