typescriptize export service related files
weseek/growi pull request #8390
Opened 2024-01-19 09:43 UTC by arafubeatbox

2024-01-19 10:15 UTC, arafubeatbox commented on apps/app/src/server/models/vo/collection-progress.js
> -    this.totalCount = totalCount;
使用箇所で totalCount は全て 0 で初期化されていました。

2024-01-19 17:24 UTC, yuki-takei requested changes

2024-01-19 17:24 UTC, yuki-takei commented on apps/app/src/server/service/export.ts
> +export default ExportService;
singleton instance を named export し、
ファクトリーメソッド(引数に crowi instance を受け取る)を default export するようにはできないか？

2024-01-19 17:24 UTC, yuki-takei commented on apps/app/src/server/service/growi-bridge.ts
> +    const Model = Object.values(this.crowi.models).find((m: any) => {
今気付いたけど、リファクタを進める中で crowi.models に登録されるモデルが減らすと、[apps/app/src/server/service/import.js](https://github.com/weseek/growi/blob/05374c3da8564510694cfdb5fa0136d0e231e68f/apps/app/src/server/service/import.js#L464) がうまく動かなかったりする？？

(このタスクのスコープ外)

2024-01-20 10:19 UTC, arafubeatbox commented on apps/app/src/server/service/export.ts
> +export default ExportService;
eslint error が出るのであまり良くないですが、以前自分が external-account service でやったように、let のまま singleton を export する方針で実装しました。

2024-01-20 10:30 UTC, arafubeatbox commented on apps/app/src/server/service/growi-bridge.ts
> +    const Model = Object.values(this.crowi.models).find((m: any) => {
ですね。この行を [getModelSafely](https://github.com/weseek/growi/blob/773c8b9f3312f16207f52f8bc6bbb259353a1c26/apps/app/src/server/util/mongoose-utils.ts#L21) とかに置き換える方針とかで良ければバックログに積んでおきます。

2024-01-20 10:46 UTC, arafubeatbox commented on apps/app/src/server/service/growi-bridge.ts
> +    const Model = Object.values(this.crowi.models).find((m: any) => {
https://redmine.weseek.co.jp/issues/138863
起票してみました。

2024-01-20 11:03 UTC, merged