fix: Non-admin user cannot rename pages
weseek/growi pull request #8391
Opened 2024-01-19 10:25 UTC by jam411

This reverts commit 39efb0bf10e6f6155099cf78d2838f3eefa0b877.

## task
https://redmine.weseek.co.jp/issues/138838

2024-01-19 11:33 UTC, jam411 commented on apps/app/src/server/service/page.ts
> +    const isMovable = isGuestUser ? false : isMovablePage(page.path);
user homepage を削除可能設定にして user homepage が削除可能な条件になっても rename/move はできないので isMovablePage を使ってもよさそうでした。

2024-01-19 11:33 UTC, jam411 commented on apps/app/src/components/Common/Dropdown/PageItemControl.tsx
> +        { !forceHideMenuItems?.includes(MenuItemType.DELETE) && isEnableActions && !isReadOnlyUser && pageInfo.isDeletable && (
v6.2.3 までは pageInfo.isMovable がつかわれていたので pageInfo.isDeletable を使うように修正しました。

2024-01-19 17:38 UTC, yuki-takei requested changes

2024-01-19 17:38 UTC, yuki-takei commented on apps/app/src/server/service/page.ts
> +      isDeletable: isMovable,
`isUsersHomepage(path)` の結果が true になる場合は `isMovable = isDeletable = false` になると思うんだけど、それでいいんだっけ？(`/user/foo` って削除できるのか？)

2024-01-22 05:37 UTC, jam411 commented on apps/app/src/server/service/page.ts
> +      isDeletable: isMovable,
pageInfo の isDeletable を参照する箇所は

- PageDeleteModal.tsx
- PageItemControl.tsx

ですが、
findPageAndMetaDataByViewer から meta data を取得するときに isDeletable, isAbleToDeleteCompletely を上書きしていました。
https://github.com/weseek/growi/blob/773c8b9f3312f16207f52f8bc6bbb259353a1c26/apps/app/src/server/service/page/index.ts#L371-L372

削除可否はバックエンド側で制御しています。
- `/pages.remove`
https://github.com/weseek/growi/blob/773c8b9f3312f16207f52f8bc6bbb259353a1c26/apps/app/src/server/routes/page.js#L779-L785
https://github.com/weseek/growi/blob/773c8b9f3312f16207f52f8bc6bbb259353a1c26/apps/app/src/server/routes/page.js#L805-L811

- `/pages/delete`
https://github.com/weseek/growi/blob/773c8b9f3312f16207f52f8bc6bbb259353a1c26/apps/app/src/server/routes/apiv3/pages.js#L918-L925

2024-01-22 19:03 UTC, merged