support: React Testing Library
weseek/growi pull request #8393
Opened 2024-01-20 08:36 UTC by miya

2024-01-22 18:54 UTC, yuki-takei requested changes

2024-01-22 18:54 UTC, yuki-takei commented on apps/app/vitest.config.components.ts
> +      '**/*.test.{tsx,jsx}',
この suffix は悩ましい。現状は、

- test/integration 配下の `*.test.ts`
    - jest による統合テスト
- `*.spec.ts`
    - vitest による単体テスト
- `*.integ.ts`
    - vitest による統合テスト

なので、jest とは別にしたい

2024-01-22 18:54 UTC, yuki-takei commented on apps/app/src/components/Common/Dropdown/PageItemControl.test.tsx
> +    const openPageMoveRenameModalButton = screen.getByTestId('open-page-move-rename-modal-btn');
不思議なんだけど、getByTestId ってなんで使えるんだ？

2024-01-23 02:48 UTC, miya commented on apps/app/vitest.config.components.ts
> +      '**/*.test.{tsx,jsx}',
*.spec.tsx にしようと思います。

2024-01-23 02:48 UTC, miya commented on apps/app/src/components/Common/Dropdown/PageItemControl.test.tsx
> +    const openPageMoveRenameModalButton = screen.getByTestId('open-page-move-rename-modal-btn');
こちらを参考にしました
https://testing-library.com/docs/queries/bytestid/

2024-01-27 09:17 UTC, merged