fix: 139350 fix paste operation in editor
weseek/growi pull request #8412
Opened 2024-01-26 09:29 UTC by WNomunomu

## タスク
https://redmine.weseek.co.jp/issues/139353

## 概要
v7で実装されたペースト操作が正しく動作しない問題を解決しました。

## 実装内容
ペーストする直前に発火するadjustPasteData()内でのペースト対象のテキストを調整する操作を修正しました。

2024-01-30 10:44 UTC, yuki-takei requested changes

2024-01-30 10:44 UTC, yuki-takei commented on packages/editor/src/services/list-util/markdown-list-util.ts
> -  else {
この else ブロックが不要な理由があれば書いて
理由が特にないなら実装を変えない方がよい

2024-02-02 04:02 UTC, WNomunomu commented on packages/editor/src/services/list-util/markdown-list-util.ts
> +  else if (strFromBol.match(indentAndMarkRE)) {
ペーストを行ったときのカーソルより前に、マークダウンのprefixが存在した場合の処理です。
ペースト対象のテキストの前にマークダウンのprefixを挿入します。

2024-02-02 04:02 UTC, WNomunomu commented on packages/editor/src/services/list-util/markdown-list-util.ts
>    return adjusted;
マークダウンが関係しない通常のペーストの場合は、処理を加えることなく、そのままペーストします。

2024-02-02 04:04 UTC, WNomunomu commented on packages/editor/src/services/list-util/markdown-list-util.ts
> +export const getLineToCursor = (editor: EditorView, lineNumBeforeCursor = 0): string => {
好きな行の行頭からカーソルまでのテキストを取得できる関数を用意しました。
こちらは同時並行している https://github.com/weseek/growi/pull/8355 でも使用します。

2024-02-02 10:59 UTC, merged