fix: Current page item in page tree is not active
weseek/growi pull request #8428
Opened 2024-01-31 14:20 UTC by miya

## Task
[#139754](https://redmine.weseek.co.jp/issues/139754) [v7] PageTree で自分がいるページが active にならない
┗ [#139755](https://redmine.weseek.co.jp/issues/139755) 修正

2024-02-07 07:03 UTC, yuki-takei requested changes

2024-02-07 07:03 UTC, yuki-takei commented on apps/app/src/components/TreeItem/SimpleItem.tsx
> +        className={`list-group-item list-group-item-action border-0 py-0 pr-3 d-flex align-items-center text-muted ${page.isTarget ? 'active' : ''}`}
active 時は list-group-item-action を外すのではないか？

https://getbootstrap.jp/docs/5.3/components/list-group/#%e3%82%a2%e3%82%af%e3%83%86%e3%82%a3%e3%83%96%e3%81%aa%e3%82%a2%e3%82%a4%e3%83%86%e3%83%a0

で、active 時の list-group-item の見た目に関してはいろいろ選択肢がある。

- SidebarContents.module.scss で指定
- グローバルに指定
    - core/scss/bootstrap/theming/_list-group.scss があるが、なんでわざわざこれを書いたんだったかちょっと覚えてない…
- または上記の両方？SimpleItem はサイドバーの内外少なくとも2箇所で使われているので

2024-02-07 07:03 UTC, yuki-takei commented on apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.module.scss
> +    }
あまりよくない。
SimpleItem のフィードバック参照

2024-02-08 13:14 UTC, miya commented on apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.tsx
> +  const mainClassName = `pagetree-item ${styles['pagetree-item']} ${isOver ? 'grw-pagetree-is-over' : ''} ${shouldHide ? 'd-none' : ''}`;
不要でしたので削除しました

2024-02-19 13:33 UTC, WNomunomu commented on apps/app/src/styles/molecules/_list-group-item.scss
グローバルにスタイルを適用するために、こちらのファイルにスタイルを記述しました。

2024-02-26 09:33 UTC, merged