feat: Support Vim/Emacs/VS Code keybind
weseek/growi pull request #8432
Opened 2024-02-01 09:07 UTC by reiji-h

# 概要
一般的なテキストエディタのキーバインドを、GROWI のテキストエディタで使えるように機能追加。

# Task
- https://redmine.weseek.co.jp/issues/126524
  - https://redmine.weseek.co.jp/issues/139355
  - https://redmine.weseek.co.jp/issues/139354

2024-02-07 03:27 UTC, yuki-takei requested changes

2024-02-07 03:27 UTC, yuki-takei commented on packages/editor/src/services/keymaps/index.ts
カプセル化の切り口がちょっとよくない
keymaps/index.ts は barrel file として残しつつ、1 editor - 1 module に対応するようにしてください

2024-02-07 03:27 UTC, yuki-takei commented on packages/editor/src/services/keymaps/index.ts
> +export const getKeymap = (keymapName: string, onSave?: () => void): Extension => {
`keymapName: string` は union を使った enum 的なものを作る
https://weseek.co.jp/tech/1609/

2024-02-09 06:24 UTC, reiji-h commented on packages/editor/src/services/keymaps/index.ts
> +export const getKeymap = (keymapName: string, onSave?: () => void): Extension => {
union を使う形で修正しました。

2024-02-09 06:24 UTC, reiji-h commented on packages/editor/src/services/keymaps/index.ts
vim を切り離し、対応するように修正しました。

2024-02-09 13:52 UTC, merged