imprv: 140068 improve page title header
weseek/growi pull request #8439
Opened 2024-02-03 04:19 UTC by WNomunomu

2024-02-03 07:24 UTC, WNomunomu commented on apps/app/src/components/PageHeader/PageHeader.tsx
> +  const [editingPagePath, setEditingPagePath] = useState(currentPagePath ?? '');
これまで、PageTitleHeaderとPagePathHeaderがそれぞれ独立してstateを持っていましたが、2つのコンポーネントの同期のためにstateを共通化しました。このstateは編集中のpagePathを保持します。

2024-02-05 10:07 UTC, miya commented on apps/app/src/components/PageHeader/PagePathHeader.tsx
https://github.com/weseek/growi/pull/8439/files#diff-4c682efb0abb6926f6303a3dbbe0f0e077e8715ad5165cdca3e84f47253c593fR53 の props. currentPage が nullable ではないので null チェック不要では？他にもありそうなので確認お願いします。

2024-02-05 10:07 UTC, miya commented on apps/app/src/components/PageHeader/PageHeader.tsx
> +}
命名方法がおかしい
https://tips.weseek.co.jp/60ae84d41091010049bed55d

2024-02-06 02:52 UTC, WNomunomu commented on apps/app/src/components/PageHeader/TextInputForPageTitleAndPath.tsx
> +}
私も悩みましたが、下記の理由から、この場所でeditedPagePathStateを宣言しました。
- 親でこのtypeを宣言してしまうと、子コンポーネントが親コンポーネントに依存してしまう
- このtypeは子コンポーネントが受け取るオブジェクトを制限するためのものであり、子コンポーネント側で定義するのが適切だと考えた
この指針が適切なのかどうかご教示いただければ幸いです。

2024-02-06 06:54 UTC, yuki-takei requested changes

2024-02-06 06:54 UTC, yuki-takei commented on apps/app/src/components/PageHeader/TextInputForPageTitleAndPath.tsx
> +}
そもそも他コンポーネントの state の getter, setter を外から入れるという実装をやめよう

type の宣言は、必要であれば別のファイルでやる
また、PascalCase にする

2024-02-08 07:25 UTC, yuki-takei requested changes

2024-02-08 07:25 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PagePathHeader.tsx
> +  };
この辺全部 useCallback を使って欲しい
意図する挙動にならないときは引数の deps を疑ってみて

2024-02-08 08:20 UTC, merged