fix: User settings rayout (User information)
weseek/growi pull request #8458
Opened 2024-02-08 12:01 UTC by satof3

# タスク
https://redmine.weseek.co.jp/issues/140194

# XD
https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/140b8455-0884-4043-99b1-5592aed34891/

# 概要
- /me 共通部分
  - タイトルのレイアウト調整
  - containerでのレスポンシブの調整
  - navtab のアイコン置き換え
- ユーザー情報
 - レイアウトの調整、レスポンシブ調整

2024-02-13 09:47 UTC, yuki-takei requested changes

2024-02-13 09:47 UTC, yuki-takei commented on apps/app/src/pages/me/[[...path]].page.tsx
> +            <h3 className="title mt-5">{ targetPage.title }</h3>
アクセシビリティ的に h1 のままにすべきでは？
文字サイズを変えたければ `fs-*` を使うのだと思う

2024-02-13 09:47 UTC, yuki-takei commented on apps/app/src/components/Me/UserSettings.tsx
> +        <h4 className="border-bottom mt-4 mb-5 pb-1">{t('Set Profile Image')}</h4>
こちらもアクセシビリティの観点をチェック
上の要素に mb を付けるよりは、後に続く要素に mt を付けたい

2024-02-13 09:47 UTC, yuki-takei commented on apps/app/src/components/Me/PersonalSettings.jsx
CustomNav.module.scss を整理すべきかな
アプリ全体で調整しないとなので

`svg { ... }` とかも不要になると思う

2024-02-13 09:47 UTC, yuki-takei commented on apps/app/src/components/Me/BasicInfoSettings.tsx
XD が見えないので判断のしようがないが、mb-x って必要なのか？

2024-02-14 09:04 UTC, satof3 commented on apps/app/src/pages/me/[[...path]].page.tsx
> +            <h3 className="title mt-5">{ targetPage.title }</h3>
h1に戻し`fs-3`にしました

2024-02-14 09:06 UTC, satof3 commented on apps/app/src/components/Me/UserSettings.tsx
> +        <h4 className="border-bottom mt-4 mb-5 pb-1">{t('Set Profile Image')}</h4>
h2に戻し`fs-4`にしました
またmb部分は全体的にmtに治しました

2024-02-14 09:06 UTC, satof3 commented on apps/app/src/components/Me/PersonalSettings.jsx
CustomNav.module.scss で調整しました

2024-02-14 09:07 UTC, satof3 commented on apps/app/src/components/Me/BasicInfoSettings.tsx
上記のようにmtで調整し直した結果今回新規でのmbは必要ないと判りました

2024-02-14 15:24 UTC, merged