feat: implement to add table when doing a line break in table markdown
weseek/growi pull request #8461
Opened 2024-02-09 10:04 UTC by WNomunomu

2024-02-15 11:58 UTC, WNomunomu commented on packages/core/src/models/markdown-table.js
> +import csvToMarkdown from 'csv-to-markdown-table';
こちらのmarkdown-table.jsのファイルはapps/appにあったものをpackages/editor配下にコピーしたものです。

2024-02-16 10:39 UTC, miya commented on packages/core/src/models/markdown-table.js
> +import csvToMarkdown from 'csv-to-markdown-table';
packages/core より packages/src/services な気がする

2024-02-16 10:39 UTC, miya commented on packages/core/src/models/markdown-table.js
> +import csvToMarkdown from 'csv-to-markdown-table';
あとわざわざやり直さなくても良いけど、コピーするなら VSCode 上でコピーしたい階層に D&D すればコピー元の commit 履歴を引き継げる (git lens とかでどういう意図でこういうコードを書いたのかなどが追いやすくなる)

2024-02-19 13:43 UTC, yuki-takei requested changes

2024-02-19 13:43 UTC, yuki-takei commented on packages/editor/src/services/table-util/index.d.ts
これ .d.ts ではなく .ts では？

2024-02-19 13:43 UTC, yuki-takei commented on packages/editor/src/services/table-util/markdown-table.js
> +import stringWidth from 'string-width';
この辺のパッケージは packages/editor/package.json に追加しないと production build で動かないんじゃないかな？

2024-02-26 09:10 UTC, yuki-takei requested changes

2024-02-26 09:10 UTC, yuki-takei commented on packages/editor/package.json
> +    "string-width": "7.1.0"
手で足した場合、アルファベット順に並べてください
(yarn add とかで足すと自動でやってくれる)

2024-02-27 04:16 UTC, merged