feat: Enable saving as a wip page
weseek/growi pull request #8472
Opened 2024-02-14 03:33 UTC by miya

## Task
[#136286](https://redmine.weseek.co.jp/issues/136286) [WIP page] ページをWIPページとして保存できる
┗  [#140128](https://redmine.weseek.co.jp/issues/140128) page ドキュメントに WIP フラグを追加

[#136298](https://redmine.weseek.co.jp/issues/136298) [WIP page] 特定のページ作成時にデフォルトで WIP ページとして保存できる
┗ [#140662](https://redmine.weseek.co.jp/issues/140662) 実装

2024-02-14 11:02 UTC, miya commented on apps/app/src/server/models/page.ts
> +  wipExpiredAt: { type: Date },
mongo TTL によって自動削除するために見る Date Object

2024-02-14 11:53 UTC, miya commented on apps/app/src/server/models/page.ts
> +};
View 画面「WIP を解除」ボタンを押下した時に呼ぶ

<img width="866" alt="スクリーンショット 2024-02-14 20 16 15" src="https://github.com/weseek/growi/assets/34241526/dbd483c1-973f-4999-a9d2-4bf2e56ce6cb">

2024-02-14 11:53 UTC, miya commented on apps/app/src/server/models/page.ts
> +};
ページの新規作成導線からページを作成した時、作成済みのページを Editor 画面で開き右下のボタンを押下した時に呼ばれる

<img width="854" alt="スクリーンショット 2024-02-14 20 17 50" src="https://github.com/weseek/growi/assets/34241526/56418a31-b674-482c-b078-5e8c8216fa7c">

2024-02-14 11:53 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +    }
ページが更新された場合は自動削除の対象外とする。wip フラグはそのまま。

2024-02-14 15:51 UTC, yuki-takei requested changes

2024-02-14 15:51 UTC, yuki-takei commented on packages/core/src/utils/should-create-wip-page.ts
> +};
細かいんだけど core に入れるまでは必要ない気がするなあ
apps/app 内でいいと思う

それか、むしろ不要(use-create-page-and-transit.tsx への FB コメント参照)

2024-02-14 15:51 UTC, yuki-takei commented on packages/core/src/interfaces/page.ts
> +  wipExpiredAt?: Date
ttl index の仕様を鑑みると、expired at っていう名前は違うんじゃないかなー
まあ今後の自動削除のタスクをやるときに直してもらえればいいんだけど

2024-02-14 15:51 UTC, yuki-takei commented on apps/app/src/server/service/page/index.ts
> +    }
if の判定いらないんじゃないかな

2024-02-14 15:51 UTC, yuki-takei commented on apps/app/src/server/models/page.ts
> +};
unpublish という名前はすでに published なものを取り下げる印象なので、isNewPage フラグはなんとなく違和感

もう一つメソッド作ったらどうかね？makeWip みたいな

2024-02-14 15:51 UTC, yuki-takei commented on apps/app/src/server/models/page.ts
> +};
wip も undefined でいいかも

2024-02-14 15:51 UTC, yuki-takei commented on apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
> +      const response = await createPage({ ...params, wip: shouldCreateWipPage(params.path) });
shouldCreateWipPage の判定ここでやりたくはないな

SidebarNotFound から作成ボタンクリックしたときの挙動を、useCreatePageAndTransit を使って再実装すればいいと思う
そうすれば params に直接 `wip: false` を設定できる
`shouldCheckPageExists` はなしでよい

2024-02-15 02:23 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +    }
if 判定外しました

2024-02-15 02:23 UTC, miya commented on packages/core/src/utils/should-create-wip-page.ts
> +};
apps/app に移動させました。shoudCreateWipPage のロジックは少なくとも2つのコンポーネントで利用するので残しています。

2024-02-15 02:23 UTC, miya commented on apps/app/src/server/models/page.ts
> +};
対応しました

2024-02-15 02:23 UTC, miya commented on apps/app/src/server/models/page.ts
> +};
makeWip を実装しました

2024-02-15 02:23 UTC, miya commented on apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
> +      const response = await createPage({ ...params, wip: shouldCreateWipPage(params.path) });
use-create-page-and-transit.tsx を利用する側から wip パラメーターを入れるように修正しました

2024-02-15 02:39 UTC, miya commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +        { path, wip: shouldCreateWipPage(path) },
NotFound ページからのページ作成ではテンプレートページや Sidebar ページも作成できてしまうので shouldCreateWipPage() で wip をつけるか否かを判断しています。(そこまで厳密にする必要がなければ削除しようと思います..)

2024-02-15 12:05 UTC, yuki-takei requested changes

2024-02-15 12:05 UTC, yuki-takei commented on apps/app/src/server/models/page.ts
> +};
makeWip の方で `this.wipExpiredAt = new Date();` をセットする (pageService.create で呼ばれるのがこれ)

2024-02-15 13:38 UTC, merged