imprv:  Fix broken layout of search result page
weseek/growi pull request #8473
Opened 2024-02-14 06:55 UTC by reiji-h

# 概要
- 検索結果ページにおいて、検索した単語を表示しないように
- 検索結果ページにおけるレイアウト崩れの修正、XDに寄せる

# Task
- https://redmine.weseek.co.jp/issues/139438
  - https://redmine.weseek.co.jp/issues/140577
- https://redmine.weseek.co.jp/issues/139433
  - https://redmine.weseek.co.jp/issues/140576
# 後続予定
- 検索結果の infinite scroll
- 検索欄にフォーカスした際に、useSearchModal を使用したモーダル検索を開けるようにする。

2024-02-14 07:49 UTC, satof3 commented on apps/app/src/components/SearchPage/SearchControl.tsx
> +              <div className="px-2 py-1 me-3">
ここのマージンはpx-2同士で16px空いているので`me-3`は不要です

2024-02-14 08:52 UTC, reiji-h commented on apps/app/src/components/SearchPage/SearchControl.tsx
> +              <div className="px-2 py-1 me-3">
削除しました

2024-02-16 07:24 UTC, yuki-takei requested changes

2024-02-16 07:24 UTC, yuki-takei commented on apps/app/src/components/SearchPage/SearchControl.tsx
> +        </div>
この dropdown は廃止、
削除のための checkbox + button は外に出して右端に置く

2024-02-16 07:24 UTC, yuki-takei commented on apps/app/src/components/SearchPage/SortControl.module.scss
> +  width: 180px;
i18n 考えるとラベル長変わるから width 固定しちゃだめだと思う
min-width だとどうだろう？

2024-02-16 07:24 UTC, yuki-takei commented on apps/app/src/components/SearchPage/SortControl.tsx
> +        </button>
スクリーンショットを見る限り水平方向のセンタリングがちょっと完全じゃない気がする

2024-02-16 07:24 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/translation.json
> +    "hit_number_unit" : "件",
恒久的に不要になった label は消してください
result_meta とか

2024-02-20 08:34 UTC, reiji-h commented on apps/app/src/components/SearchPage/SearchControl.tsx
> +        </div>
右端に置くように修正しました。

2024-02-20 08:41 UTC, reiji-h commented on apps/app/src/components/SearchPage/SortControl.module.scss
> +  width: 180px;
min-width で期待通りに動いたので、そのように変更しました。

2024-02-20 08:42 UTC, reiji-h commented on apps/app/src/components/SearchPage/SortControl.tsx
> +        </button>
修正しスクリーンショットの差し替えを行いました。

2024-02-20 08:50 UTC, reiji-h commented on apps/app/public/static/locales/ja_JP/translation.json
> +    "hit_number_unit" : "件",
今回のタスク内で不要になったラベル`result_meta` は `PrivateLegacyPages.tsx` で使用されているため、locales ファイル群からは消す必要はないと判断しました。

2024-02-22 10:39 UTC, yuki-takei requested changes

2024-02-22 10:39 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/translation.json
> +    "hit_number_unit" : "件",
そうだとすると、PrivateLegacyPages も検索結果に倣う形で修正した方がいい
そして最終的にそちらも XD 通りになったら translation.json からも削除する
(後続ストーリーを作る)

2024-02-22 10:40 UTC, merged