fix: Sidebar renders above the lightbox layer
weseek/growi pull request #8478
Opened 2024-02-15 09:31 UTC by miya

## Task
[#139734](https://redmine.weseek.co.jp/issues/139734) [v7][design] 画像プレビューがサイドバーに隠れてしまう問題の修正
┗ [#140638](https://redmine.weseek.co.jp/issues/140638) 修正

2024-02-15 09:59 UTC, miya commented on apps/app/src/components/Layout/BasicLayout.tsx
> +        <LightBox />
## バグの原因
SIdebar より LightBox を呼び出している {children} の方が z-index 値が低いことが原因でした。
https://github.com/weseek/growi/pull/8478/files#diff-0816e0e7899ad5dc781fc549c0ee13cb984df5e30fb96acbe6d1a8c2780ee683L40-L49

## 解決策
FsLightbox をレンダーするコンポーネントを新規に作成し、モーダルなどと同じ階層に配置しました。そのため 表示/非表示 をコントロールする部分と LightBox をレンダーする箇所が分離したので、表示/非表示 を判断する値を SWR を使ってグローバルステート化しました。

2024-02-15 09:59 UTC, miya commented on apps/app/src/components/LightBox.tsx
> +      toggler={data.toggler}
toggler は isVisible flag ではなく渡す値が変化することで 表示/非表示 する
https://github.com/banthagroup/fslightbox-react/issues/232#issuecomment-1513272937

2024-02-15 10:01 UTC, miya commented on apps/app/src/stores/light-box.ts
> +      toggler: !swrResponse.data?.toggler ?? false,
コメントの理由から toggler は lightBoxController が実行されるたびに true/false が変動するだけ
https://github.com/weseek/growi/pull/8478/files#r1490715892

2024-02-16 09:03 UTC, yuki-takei requested changes
これ StaffCredit みたいに Modal として実装できないかな
global state できればない方がいいよね

2024-04-03 14:11 UTC, closed without merging