feat: Add editing user list on page header
weseek/growi pull request #8486
Opened 2024-02-15 14:40 UTC by jam411

## Description
task: https://redmine.weseek.co.jp/issues/140637
XD: https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/38175ff0-3e3c-4f1e-8d02-783448d316e0/specs/

## Screenshot
### isRoot なページ
![userlist](https://github.com/weseek/growi/assets/68407388/0f5092e7-aad8-4305-9f1c-1c4fc87e38d0)

### isRoot ではないページ
![userpicture2](https://github.com/weseek/growi/assets/68407388/94fe4f18-9032-4cd3-94cd-514d35974e4d)

2024-02-16 12:46 UTC, jam411 commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +  const [userList, setUserList] = useState<IUserHasId[]>([]);
use-collaborative-editor-mode まで setUserList を渡す.

2024-02-16 12:46 UTC, jam411 commented on packages/editor/src/stores/use-collaborative-editor-mode.ts
> +    });
任意のユーザーが added, removed の時にリストにそれぞれ対象の ydoc clientId が入るので、そのタイミングで states から同時編集中の全ユーザー情報を取得して onUserList に渡しています。

2024-02-16 12:46 UTC, jam411 commented on packages/editor/src/stores/use-collaborative-editor-mode.ts
> +    socketIOProvider.awareness.setLocalStateField('user', userLocalState);
UserPicture 表示や EditingUserPicture の表示のために、自分の user: IUserHasId を丸ごと socketIOProvider.awareness に渡してしまっています。

2024-02-16 12:46 UTC, jam411 commented on apps/app/src/components/PageHeader/PageHeader.tsx
> +  const dPagePath = new DevidedPagePath(currentPage.path, true);
PagePathHeader, PageTitleHeader でも呼び出しているのでここで呼び出してprops で渡すべきか迷っています。

2024-02-19 13:27 UTC, yuki-takei requested changes

2024-02-19 13:27 UTC, yuki-takei commented on apps/app/src/components/PageHeader/EditingUserList.tsx
> +import popoverStyles from '../PageControls/user-list-popover.module.scss';
この参照方法は NG

2024-02-19 13:27 UTC, yuki-takei commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +  const [userList, setUserList] = useState<IUserHasId[]>([]);
PageEditor で state を持っておく必要あるかな？

use-collaborative-editor-mode 側で state 管理して、返り値で渡してほしい気がする
→ EditingUserList または一段上の PageHeader で hooks から得ればいいのでは？

2024-02-19 13:27 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PageHeader.tsx
> +  const dPagePath = new DevidedPagePath(currentPage.path, true);
これはまあどちらでも

2024-02-27 15:39 UTC, jam411 commented on apps/app/src/components/PageHeader/EditingUserList.tsx
> +import popoverStyles from '../PageControls/user-list-popover.module.scss';
user-list-popover.module.scss をグローバルにしました。

2024-02-28 02:51 UTC, jam411 commented on packages/core/src/swr/use-editing-users.ts
> +  };
react を core にインポートすることになるので useCallback は使っていません。

2024-02-28 13:48 UTC, yuki-takei requested changes

2024-02-28 13:48 UTC, yuki-takei commented on packages/core/src/swr/use-editing-users.ts
> +  };
この hook は core ではなく apps/app 内に置いておきたい

core の責務の範囲は明文化されているわけではないので線引きが難しいのだが…
基本的に app の状態を保存する swr は apps/app の中に置く

useGlobalSocket は大変特殊なケースと言ってよい

2024-02-28 13:48 UTC, yuki-takei commented on apps/app/src/styles/molecules/user-list-popover.scss
> +.user-list-popover {
グローバルなスタイルを増やしたくないので、`_wiki-custom-sidebar.scss` や `_button-styles.scss` を参考に placeholder として実装して、使う側からは `@use` で参照する形にしてほしい

2024-02-28 13:48 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PageHeader.tsx
> +  const { data: EditingUsers } = useEditingUsers();
変数は camelCase にする

2024-02-28 13:48 UTC, yuki-takei commented on apps/app/src/pages/[[...path]].page.tsx
> +        <nav className="sticky-top z-1">
今回足している `z-2` や `z-1` が必要である理由がちょっとわからない
position-absolute を使っているわけでもないよね？ sticky-top のせい？

2024-03-01 09:47 UTC, jam411 commented on apps/app/src/pages/[[...path]].page.tsx
> +        <nav className="sticky-top z-1">
こんな感じで User icon が GrowiContextualSubNavigation に隠れてしまうんですよね
![Screenshot 2024-03-01 183506](https://github.com/weseek/growi/assets/68407388/7e3c3e34-7bab-47e4-8635-c70f59c032b9)

![Screenshot 2024-03-01 183605](https://github.com/weseek/growi/assets/68407388/7117861d-905e-45fb-861b-f71f550f528e)

2024-03-01 09:48 UTC, jam411 commented on apps/app/src/pages/[[...path]].page.tsx
> +        <nav className="sticky-top z-1">
ここ変えたくはないので EditingUserList コンポーネント側に margin を持たせて調整しました。

2024-03-01 10:50 UTC, jam411 commented on apps/app/src/styles/molecules/user-list-popover.scss
> +.user-list-popover {
修正しました

2024-03-01 10:50 UTC, jam411 commented on packages/editor/src/stores/use-collaborative-editor-mode.ts
> +        onEditorsUpdated(userList);
初回エディタ画面に接続時に update が走らず自分のアイコンが表示されなかったので、sync したタイミングで editors updated するようにしています。

2024-03-01 10:56 UTC, jam411 commented on apps/app/src/components/PageControls/LikeButtons.tsx
> +        <PopoverBody className={`user-list-popover ${popoverStyles['user-list-popover']}`}>
スタイル適用したほうがよさそうだったので合わせてこちらも修正しました。
![Screenshot 2024-03-01 195408](https://github.com/weseek/growi/assets/68407388/b069ce65-d7c1-4b2e-a88a-508f65b85dd2)

スタイル適用されている箇所はこうなっている
![image](https://github.com/weseek/growi/assets/68407388/fe6747ba-2588-4c5d-8d6a-95c72d47489b)

2024-03-01 11:30 UTC, merged