feat: Automatic deletion of wip pages using TTL index
weseek/growi pull request #8496
Opened 2024-02-19 03:09 UTC by miya

## Task
[#136303](https://redmine.weseek.co.jp/issues/136303) [WIP page] WIP ページを自動削除できる
┗ [#140684](https://redmine.weseek.co.jp/issues/140684) 実装

2024-02-20 07:23 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +    await Page.updateMany({ _id: { $in: nonEmptyAncestorIds } }, { $unset: { ttlTimestamp: true } });
Page.unpublish() 時に ttlTimestamp に undefined を入れている (フィールドそのものが消えるようにしている) のでそれに倣って null を挿入するのではなく unset を使うようにしています。
https://github.com/weseek/growi/blob/0e401fc12ec350f73bc916c4ecd75a64983e76e1/apps/app/src/server/models/page.ts#L1063

2024-02-20 13:06 UTC, yuki-takei requested changes

2024-02-20 13:06 UTC, yuki-takei commented on apps/app/src/server/service/page/index.ts
> +  }
ancestorPaths を得るところまではよくて、そこから ancestorPageIds を得るのは Page.aggregate を使ってほしい(projection で id だけを取ってくる)

既存コードを参考にしてくれたと思うが、aggregation を使った方がパフォーマンスがよい

2024-02-20 15:31 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +  }
Page.aggregate を使う実装にしました

2024-02-20 15:31 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +      page.makeWip(disableTtl);
修正しました

2024-02-20 15:31 UTC, miya commented on apps/app/src/server/service/config-loader.ts
> +  PAGE_EXPIRATION_SECONDS: {
修正しました

2024-02-22 10:32 UTC, yuki-takei requested changes

2024-02-22 10:32 UTC, yuki-takei commented on apps/app/src/server/service/page/index.ts
> +      page.makeWip(disableTtl);
先回りが足りなかった
更に `limit: 1` 付けて count しようか

https://stackoverflow.com/a/53004942

2024-02-22 11:08 UTC, merged