feat: Switch wip page visibility (PageTree, RecentChanges)
weseek/growi pull request #8499
Opened 2024-02-19 13:16 UTC by miya

## Tasks
[#136300](https://redmine.weseek.co.jp/issues/136300) [WIP page] Page Tree で WIP ページの表示/非表示を切り替えできる
┗ [#140685](https://redmine.weseek.co.jp/issues/140685) 実装

[#136302](https://redmine.weseek.co.jp/issues/136302) [WIP page] Recent Changes で WIP ページの表示/非表示を切り替えできる
┗ [#140686](https://redmine.weseek.co.jp/issues/140686) 実装

## XD
### PageTree
https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/872f72a7-fab8-47a3-99e1-3edb4e03284b

### RecentChanges
無し

## ScreenRecord
### PageTree
https://github.com/weseek/growi/assets/34241526/2b79888b-9ebc-4698-9136-54a039ede2e9

### RecentChanges
https://github.com/weseek/growi/assets/34241526/3d3fa01e-b191-47c7-8e3b-2589da115b8e

2024-02-19 13:18 UTC, miya commented on apps/app/src/components/TreeItem/SimpleItem.tsx
> +  }
`isWipPageShwon: false` の時は WIP Page を含む WIP Page 配下は非表示になる

2024-02-21 08:41 UTC, miya commented on apps/app/src/server/routes/apiv3/pages/index.js
> +    const includeWipPage = JSON.parse(req.query.includeWipPage ?? true); // String to boolean, Requires validation by express-validator before conversion
- req.query.includeWipPage はクエリパラメーターから取得することから string で渡ってくるので boolean に変換させている
- express-validator によるバリデーションを追加したので 'true' | 'false' | undefined のみが渡ってくる

2024-02-26 11:36 UTC, yuki-takei requested changes

2024-02-26 11:36 UTC, yuki-takei commented on apps/app/src/components/Sidebar/SidebarContents.module.scss
> +    font-size: 0.5rem;
`--bs-badge-font-size` の上書きの方がよさそう

2024-02-26 11:36 UTC, yuki-takei commented on apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
> +      </UncontrolledButtonDropdown>
中途半端なスコープ外の差分が入ってないかな

2024-02-26 11:36 UTC, yuki-takei commented on apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx
> +      </UncontrolledButtonDropdown>
中途半端なスコープ外の差分が入ってないかな

2024-02-26 12:43 UTC, miya commented on apps/app/src/components/Sidebar/SidebarContents.module.scss
> +    font-size: 0.5rem;
修正しました

2024-02-26 13:41 UTC, merged