Feat/139718 141055 sidebar account modal design
weseek/growi pull request #8501
Opened 2024-02-20 06:57 UTC by yukendev

ストーリー: https://redmine.weseek.co.jp/issues/139718
タスク: https://redmine.weseek.co.jp/issues/141055

# やったこと
- `PersonalDropdown`のフォントサイズ、余白を調整
- アイコンを一部変更

変更前
<img width="316" alt="スクリーンショット 2024-02-20 15 57 14" src="https://github.com/weseek/growi/assets/65263895/cd639291-10ab-47b3-805b-d9659e928532">

変更後
<img width="293" alt="スクリーンショット 2024-02-20 15 55 42" src="https://github.com/weseek/growi/assets/65263895/a109020c-e79e-4340-bfba-0bcd13a15ee7">

2024-02-20 13:17 UTC, yuki-takei requested changes

2024-02-20 13:17 UTC, yuki-takei commented on apps/app/src/components/Sidebar/SidebarNav/PersonalDropdown.module.scss
> +}
- 色は light/dark 対応が必要
    - dark の色変数はなににすべきかは fumiya-s からインプットをもらって
- `ToggleCollapseButton.module.scss` などを参考に
    - color や font-size に対して値を指定するのはやむを得ない(bs5 が対応していないような)場合を除き極力避け、css var を上書きする

2024-03-03 09:58 UTC, yukendev commented on apps/app/src/components/Sidebar/SidebarNav/PersonalDropdown.module.scss
> +}
修正済み

2024-03-04 19:25 UTC, yuki-takei requested changes

2024-03-04 19:25 UTC, yuki-takei commented on apps/app/src/components/Sidebar/SidebarNav/PersonalDropdown.module.scss
> +}
最初の FB と同じことを書きますが、フォントサイズと padding について、以下の順で css を減らせないか検討してください

1. `.small` や `fs-1` `pb-0` 等の bootstrap のユーティリティクラスを利用できるならそちらに差し替える
2. `--bs-dropdown-font-size` や `--bs-dropdown-item-padding-y` の css var の上書きで済むならそちらに書き換える
3. 上記 1,2 では対応できない指定はそのままで OK

開発者ツールで見てる感じ、2 でいけるような気がしている
3になるのであれば slack でいいので理由を教えて

2024-03-05 10:41 UTC, yuki-takei approved these changes

2024-03-06 04:58 UTC, merged