imprv: Collect settings on the EditorConfig button.
weseek/growi pull request #8504
Opened 2024-02-20 08:17 UTC by reiji-h

# 概要
- Edit 時のフッターに存在した設定を EditorConfig にまとめる

# Task
- https://redmine.weseek.co.jp/issues/140199
  - https://redmine.weseek.co.jp/issues/140914
# XD
https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/edcf4f77-019a-4e96-b064-73521e9db550/

# ScreenShot
<img width="215" alt="image" src="https://github.com/weseek/growi/assets/132258880/7f178793-0674-41e9-b153-73e48eadd7b4">

<img width="132" alt="image" src="https://github.com/weseek/growi/assets/132258880/1d282389-b5fd-4db1-a7cc-c293de10c1fc">

<img width="182" alt="image" src="https://github.com/weseek/growi/assets/132258880/55ff82a3-514c-4833-8625-f4e063d312de">

<img width="137" alt="image" src="https://github.com/weseek/growi/assets/132258880/5c5ca17e-0453-41d2-9ef7-99498a3171e6">

<img width="202" alt="image" src="https://github.com/weseek/growi/assets/132258880/210fad56-8a72-4fdf-aae7-d396eaa03c8f">

2024-02-20 08:51 UTC, satof3 commented on apps/app/src/components/PageEditor/OptionsSelector.tsx
> +            <label className="ms-1 me-1">Editor Config</label>
ここは`ms-3`で良さそうです

2024-02-20 11:26 UTC, reiji-h commented on apps/app/src/components/PageEditor/OptionsSelector.tsx
> +            <label className="ms-1 me-1">Editor Config</label>
修正しました

2024-02-20 11:26 UTC, reiji-h commented on apps/app/src/components/PageEditor/OptionsSelector.tsx
> +    <div className="mx-2 mt-1">
修正しました

2024-02-20 13:33 UTC, yuki-takei requested changes

2024-02-20 13:33 UTC, yuki-takei commented on apps/app/src/interfaces/editor-settings.ts
> +export type EditorTheme = typeof EditorTheme[keyof typeof EditorTheme];
packages/editor/src/services/editor-theme/index.ts と二重管理になっているのはなぜ？回避してほしい

2024-02-20 13:33 UTC, yuki-takei commented on apps/app/src/components/PageEditor/OptionsSelector.tsx
> +            : <label className="ms-1 me-1">Editor Config</label>
ここのラベルの i18n を検討してください
後続タスクでも OK

2024-02-21 08:34 UTC, reiji-h commented on apps/app/src/interfaces/editor-settings.ts
> +export type EditorTheme = typeof EditorTheme[keyof typeof EditorTheme];
`@growi/editor` から `EditorTheme` と、同じような管理をしていた `KeyMapMode` を持ってくる形に修正しました。

2024-02-22 10:44 UTC, merged