fix: 140329 141060 fix display of page title in page tree
weseek/growi pull request #8505
Opened 2024-02-20 08:27 UTC by WNomunomu

## タスク
## 概要
このセクションでは、このPRの目的と概要を簡潔に説明してください。
## 変更点
このセクションでは、具体的な変更点や修正箇所を箇条書きでリストアップしてください。
- 変更点1
- 変更点2
- 変更点3
## 後続ストーリー
このセクションでは、このPRのストーリーの後続ストーリーを書いてください
## セルフチェック
- [ ] コンフリクト解消したか
- [ ] 余計なコードは残っていないか
- [ ] 適切にメモ化したか
- [ ] 責務の問題はクリアしているか
- [ ] CIは通っているか
- [ ] PRの内容は適切にかけているか

2024-02-20 08:58 UTC, miya reviewed
v6 と同じにはなっていないので確認お願いします
https://github.com/weseek/growi/assets/34241526/beb2f18b-81a4-43b7-8aef-c607d39412e8

2024-02-26 09:29 UTC, miya commented on apps/app/src/components/ItemsTree/ItemsTree.module.scss
> +        width: $grw-pagetree-item-container-width;
他で使いまわさないのであれば変数で持たなくても良いと思いました

2024-02-27 12:53 UTC, yuki-takei requested changes

2024-02-28 14:48 UTC, WNomunomu commented on apps/app/src/components/TreeItem/SimpleItem.tsx
> +      style={{ minWidth: 0 }}
widthを指定するのではなく、minWidthを指定することでPageTitleがはみ出ないようにしました。

2024-02-28 14:48 UTC, WNomunomu commented on apps/app/src/components/TreeItem/SimpleItem.tsx
> +              className={`grw-pagetree-triangle-btn btn p-0 ${isOpen ? 'grw-pagetree-open' : ''}`}
widthを指定するのではなく、無駄なpaddingを無くすことで、buttonがdiv要素からはみ出てスタイルが崩れるのを防ぎました。

2024-02-29 18:58 UTC, merged