Fix/141309 141311 multi group grant page becomes public when one of groups deleted
weseek/growi pull request #8518
Opened 2024-02-24 10:29 UTC by arafubeatbox

2024-02-24 10:32 UTC, arafubeatbox commented on apps/app/test/integration/service/user-groups.test.ts
> -  test('Updated values should be reflected. (name, description, parent)', async() => {
ここら辺の既存部分への変更は、メソッド単位でテストを describe で囲んだだけです。

2024-02-24 10:32 UTC, arafubeatbox commented on apps/app/test/integration/service/user-groups.test.ts
> +  describe('removeCompletelyByRootGroupId', () => {
ここから下が新規テストになります。

2024-02-24 10:38 UTC, arafubeatbox commented on apps/app/test/integration/models/v5.page.test.js
> +          expect(normalizeGrantedGroups(page.grantedGroups).length).toBe(3);
過去テスト補強:
expect.arrayContaining は array の中身に要素群がいるかを確認するだけで、完全一致かどうかは確認していなかったため、length の assertion を追加。

2024-02-27 14:31 UTC, yuki-takei requested changes

2024-02-27 14:31 UTC, yuki-takei commented on apps/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
> +          <div className="d-flex mb-0 me-3          ">
なんかおかしなスペースがある

2024-02-27 14:31 UTC, yuki-takei commented on apps/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
> +        {actionName === 'public' && (
ついでに public, delete, transfer を const (enum 的な) に変えてください

2024-02-27 14:31 UTC, yuki-takei commented on apps/app/src/server/service/page/index.ts
> +      case 'public': {
const (enum) を参照して挙動を変える

2024-02-27 14:31 UTC, yuki-takei commented on apps/app/src/server/service/page/index.ts
> +        await Page.bulkWrite(queries);
Page.publicizePages の引数を拡張して groupsToDeleteIds を渡して、その中で updateOne クエリを変える方がよさそうだなあ
そうすると名前も publicize じゃない方がいいのかもしれない

2024-02-27 15:32 UTC, arafubeatbox commented on apps/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
> +          <div className="d-flex mb-0 me-3          ">
修正しました。

2024-02-27 15:33 UTC, arafubeatbox commented on apps/app/src/server/service/page/index.ts
> +        await Page.bulkWrite(queries);
removeGroupsToDeleteFromPages として実装し直しました。

2024-02-27 15:33 UTC, arafubeatbox commented on apps/app/src/server/service/page/index.ts
> +      case 'public': {
PageActionOnGroupDelete を定義しました。

2024-02-27 15:33 UTC, arafubeatbox commented on apps/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
> +        {actionName === 'public' && (
PageActionOnGroupDelete を定義しました。

2024-02-28 09:12 UTC, yuki-takei requested changes

2024-02-28 09:12 UTC, yuki-takei commented on apps/app/src/server/models/page.ts
> +};
queries を先に concat すれば bulkWrite は1回で済むんじゃないかな

2024-02-28 09:34 UTC, merged