feat: When updating a page from the Editor, the latest revision is not required
weseek/growi pull request #8522
Opened 2024-02-26 06:08 UTC by miya

## Task
[#126533](https://redmine.weseek.co.jp/issues/126533) [v7][New Editor][collab] コンフリクト状態を解消できる
┗ [#141319](https://redmine.weseek.co.jp/issues/141319) Editor からページを保存する際に最新 revision を必要としないようにする

2024-02-27 14:00 UTC, yuki-takei requested changes

2024-02-29 19:35 UTC, yuki-takei requested changes

2024-02-29 19:35 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/update-page.ts
> +  };
なるほど
関係ないけど、カスタムじゃなくても `isIn` でいいね

https://express-validator.github.io/docs/api/validation-chain#isin

2024-03-02 14:15 UTC, miya commented on apps/app/src/server/routes/apiv3/page/update-page.ts
> +  };
`isIn` いいですね.. こちらを使うように修正しました。

2024-03-02 14:17 UTC, miya commented on apps/app/src/server/models/obsolete-page.js
> +    }
revision document にページ保存時の origin を保存できるようにして修正しました。

2024-03-02 14:44 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +    const isBodyPresent = body != null;
最新の revisionId が不要になるケースが存在するので `previousBody != null` の条件は廃止しました。

2024-03-02 14:44 UTC, miya commented on apps/app/src/server/routes/apiv3/page/update-page.ts
> +    body('revisionId').optional().exists().not()
最新の revisionId が不要になるケースが存在するので optinal にしました。

2024-03-02 14:44 UTC, miya commented on apps/app/src/server/routes/apiv3/page/update-page.ts
ページ更新時に作成された revision に origin を保存できるようにしました。

2024-03-02 14:44 UTC, miya commented on apps/app/src/server/routes/apiv3/page/create-page.ts
ページ作成時に作成された revision に origin を保存できるようにしました。

2024-03-02 14:44 UTC, miya commented on apps/app/src/client/services/create-page/use-create-template-page.ts
createAndTransit の第一引数の object に origin を入れられるようにし、全て `View` を入れるようにしました。

2024-03-04 19:16 UTC, yuki-takei requested changes

2024-03-04 19:16 UTC, yuki-takei commented on apps/app/src/components/PageCreateModal.tsx
> +        optionalParentPath: '/',
optionalParentPath 入れるべきではないかもなあ
パスを指定してページをつくる挙動を期待しているわけだから、失敗したらそのまま(モーダルも消えないし transit もしない)が適切だと思う

2024-03-05 02:30 UTC, merged