imprv: All editor config option is available
weseek/growi pull request #8529
Opened 2024-02-27 06:47 UTC by reiji-h

# 概要
- EditorConfig 内の「アクティブ行をハイライト」「表の自動整形」を使用可能にする。
- EditorConfig の i18n 化

# Task
- https://redmine.weseek.co.jp/issues/140199
  - https://redmine.weseek.co.jp/issues/141158

- https://redmine.weseek.co.jp/issues/140549
  - https://redmine.weseek.co.jp/issues/140562

2024-02-27 10:58 UTC, miya commented on packages/editor/src/components/CodeMirrorEditorMain.tsx
>        onSave={onSave}
`onSave` も `...codeMirrorEditorProps` に含まれるから消しちゃって良さそう？

2024-02-27 11:44 UTC, reiji-h commented on packages/editor/src/components/CodeMirrorEditorMain.tsx
>        onSave={onSave}
最初 codeMirrorEditorProps を定義する際、onSave は別で定義してしています。よって codeMrrorEditorProps には含まれていないため、コードの変更はしない方向で行きます。
ただ、codeMirrorEditorProps という名前では問題っぽいので otherProps にまとめようと思います。

2024-02-27 14:18 UTC, yuki-takei requested changes

2024-02-27 14:18 UTC, yuki-takei commented on apps/app/src/components/PageEditor/OptionsSelector.tsx
> +    <Selector header={t('page_edit.theme', 'Theme')} onClickBefore={onClickBefore} items={listItems} />
第二引数の default value はなしでお願いします(他の箇所でも使ってはいないので)

2024-02-27 14:18 UTC, yuki-takei commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +            autoFormatMarkdownTable={editorSettings?.autoFormatMarkdownTable}
ここまで props 多くなると editorSettings オブジェクトをそのまま渡してしまいたくなるね

2024-02-27 14:18 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
> +  }, [codeMirrorEditor, onPressEnter]);
この辺の挙動を制御するものを CodeMirrorEditor に置くか use-codemirror-editor に置くか迷うんだけれど、、
少なくとも backspace と enter の処理が別々に分かれているのはちょっと気持ち悪い

hooks 側に置く方が読みやすくないかなあとは思うんだけど、そうすると useCodeMirrorEditor の引数に GROWI の機能由来のものが入ってきてしまうか…

悩ましい

2024-03-04 03:09 UTC, reiji-h commented on apps/app/src/components/PageEditor/OptionsSelector.tsx
> +    <Selector header={t('page_edit.theme', 'Theme')} onClickBefore={onClickBefore} items={listItems} />
削除しました。

2024-03-04 03:13 UTC, reiji-h commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +            autoFormatMarkdownTable={editorSettings?.autoFormatMarkdownTable}
edutirSettings を @growi/editor に任せる形で修正しました。

2024-03-04 03:32 UTC, reiji-h commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
> +  }, [codeMirrorEditor, onPressEnter]);
一旦 `use-codemirror-editor` にあった `defaultExtensions`  と `editor-settings` 周りの `Extension` を外のファイルに隔離する形で書いてみました。ですがこれは単にファイルを分けて見やすくなった程度で、backspace と enter の処理が別々に書かれていて気持ち悪い点は特に変わってはいないです。

2024-03-04 19:48 UTC, yuki-takei approved these changes

2024-03-05 10:58 UTC, merged