imprv: 136128 hide title of untitled page
weseek/growi pull request #8536
Opened 2024-02-28 13:49 UTC by WNomunomu

## タスク
https://redmine.weseek.co.jp/issues/140146
## 概要
- PageCreateButtonからuntitledページを新規作成し、editorに自動で遷移したときにPageTitleHeaderのinputモードに「ページを入力してください」と表示するようにしました。
 ## 変更点
- PageCreateButtonから新規作成されたuntitledページなのかを判定する定数、isNewlyCreatedPageを追加しました。
- 上記のisNewlyCreatedPageを取得するために、新しく正規表現を作成しました。
- currentPage.idが変更されたときに発火するuseEffectを作成しました。
## スクリーンショット
<img width="220" alt="image" src="https://github.com/weseek/growi/assets/83588003/cad69e4d-eaf0-435f-a8d2-bd5177c47f0e">

## セルフチェック
- [ ] コンフリクト解消したか
- [ ] 余計なコードは残っていないか
- [ ] 適切にメモ化したか
- [ ] 責務の問題はクリアしているか
- [ ] CIは通っているか
- [ ] PRの内容は適切にかけているか

2024-02-29 03:21 UTC, miya commented on apps/app/src/components/PageHeader/PageTitleHeader.tsx
> PageCreateButtonからuntitledページを新規作成し、editorに自動で遷移したときにPageTitleHeaderのinputモードに「ページを入力してください」と表示するようにしました。

これってどこに実装してある？ input の placeholder のこと？

2024-02-29 03:21 UTC, miya commented on apps/app/src/components/PageHeader/PageTitleHeader.tsx
> +  const untitledPageRegex = /^Untitled-\d+$/;
新規作成時の path が  Untitled ~ のままだとは限らないので path で判断するのはあまりよくないと思う

https://github.com/weseek/growi/blob/cc0e4c707357d9bb9571b5d395c6a9f8ab9bccda/apps/app/src/server/routes/apiv3/page/create-page.ts#L45-L46

2024-02-29 03:21 UTC, miya commented on apps/app/src/components/PageHeader/PageTitleHeader.tsx
> +  const isNewlyCreatedPage = (currentPage.wip && currentPage.latestRevision == null && untitledPageRegex.test(editedPageTitle)) ?? false;
一度も更新していないページという意味では `currentPage.ttlTimestamp != null` が使えるけどどうだろう？

2024-02-29 04:46 UTC, WNomunomu commented on apps/app/src/components/PageHeader/PageTitleHeader.tsx
inputのplaceholderのことです。
inputのvalueが空白の状態で表示されるという意味です。
分かりにくかったため、PRの表現を修正します。

2024-03-22 09:19 UTC, yuki-takei requested changes

2024-03-22 09:19 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PageTitleHeader.tsx
> +  const isNewlyCreatedPage = (currentPage.wip && currentPage.latestRevision == null && untitledPageRegex.test(editedPageTitle)) ?? false;
これは一旦このまま行く

2024-03-22 09:19 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PageTitleHeader.tsx
> +  const untitledPageRegex = /^Untitled-\d+$/;
これは後続タスクがあるのでこの PR では一旦このままでOK

2024-03-22 09:19 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PageTitleHeader.tsx
> +  }, [currentPage._id, isNewlyCreatedPage]);
インプットを表示するところまではよくて、オートフォーカスもしてる？

2024-03-22 09:19 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/create-page.ts
> +  // console.log(test);
デバッグ用のコードは消してください

2024-03-22 09:19 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/create-page.ts
> +      console.log(basePathname);
デバッグ用のコードは消してください

2024-03-25 06:55 UTC, reiji-h commented on apps/app/src/components/PageHeader/PageTitleHeader.tsx
> +  }, [currentPage._id, isNewlyCreatedPage]);
おそらく該当コードがオートフォーカスもしていそうです。

2024-04-04 08:04 UTC, merged