Feat: Replace Fontawesome icons with Material Symbols
weseek/growi pull request #8537
Opened 2024-02-29 04:14 UTC by satof3

# Task
https://redmine.weseek.co.jp/issues/137282

# 概要
- FontAwesome のアイコン(`fa-hoge`) を Material Symbols Outlined に置き換え

# やっていないところ
- `fa-spinner`
  - https://redmine.weseek.co.jp/issues/140441
- `fa-pulse`
  - https://redmine.weseek.co.jp/issues/141426
- `fa-rotate-90`
  - https://redmine.weseek.co.jp/issues/141620
- `fa-external-link` (オリジナルアイコンに差し替え)
  - https://redmine.weseek.co.jp/issues/141197
- `sandbox-diagram.md`内の`fa-book`(対応検討中)

2024-02-29 19:02 UTC, yuki-takei requested changes

2024-02-29 19:02 UTC, yuki-takei commented on apps/app/src/components/Admin/App/AppSettingsPageContents.tsx
> +              <span className="material-symbols-outlined ms-1" aria-hidden="true">expand_more</span>
- fa-fw をただ消すだけではなく、なんらかのルールで対応をしてください
- 現時点でよい案を思いつかない場合は、一律 `me-1` を入れてください

2024-02-29 19:04 UTC, yuki-takei commented on apps/app/src/components/Admin/App/AppSettingsPageContents.tsx
> +              <span className="material-symbols-outlined ms-1" aria-hidden="true">expand_more</span>
こうコメントしたものの、例えば [CustomizeNoscriptSetting.tsx](https://github.com/weseek/growi/pull/8537/files#diff-1df9d042c6fc415b0641510a2908b50816f379cbd2f47ad2c8868cbe414baac2) などを見ると `me-1` が入っている…
ということは、目視でのチェックが終わっているということ？

もしそうであればこのままマージできる
目視していないが fa-fw を消した箇所があるなら一律 `me-1` を入れたい

2024-03-01 11:39 UTC, satof3 commented on apps/app/src/components/Admin/App/AppSettingsPageContents.tsx
> +              <span className="material-symbols-outlined ms-1" aria-hidden="true">expand_more</span>
改めて見直して2点視認できていない箇所があったので修正しました。
現時点で`me-1`をつけていない部分は視認した上で余白が適切だったのでつけていません。

2024-03-01 12:24 UTC, merged