imprv: truncate page path when editing
weseek/growi pull request #8538
Opened 2024-02-29 05:12 UTC by WNomunomu

2024-03-22 07:04 UTC, WNomunomu commented on apps/app/src/components/PageHeader/PagePathHeader.tsx
> +  useEffect(() => {
このuseEffect内部で、page pathの方がcontainerよりも長い場合を示すisIconHidden stateを決定しています。
このisIconHiddenがtrueの場合にはホームアイコンを非表示にし、左向きにtruncateします。

2024-03-24 13:47 UTC, yuki-takei requested changes

2024-03-24 13:47 UTC, yuki-takei commented on apps/app/public/static/locales/zh_CN/translation.json
> +	"Create under": "Create page under below:",
余計な差分まで出てる気がする

2024-03-24 13:47 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PagePathHeader.tsx
> +  useEffect(() => {
getElementById で要素を取ってきてあれこれするのは結構凝った処理になるので、どうしても必要な場合を除いてやりたくない。
いまのストーリーのゴールを満たすのに必須であればやるしかないのだが、そうでもないのなら React の流儀から外れない処理だけをやってクローズしたい。

2024-03-25 05:30 UTC, reiji-h commented on apps/app/public/static/locales/zh_CN/translation.json
> +	"Create under": "Create page under below:",
space か tab かの影響でした。余計な差分は消しました。

2024-03-25 13:34 UTC, merged