fix: Unable to create pages from page create modal
weseek/growi pull request #8541
Opened 2024-03-01 03:08 UTC by miya

## Task
[#141354](https://redmine.weseek.co.jp/issues/141354) [v7][要仕様検討] PageCreateModal (新規作成モーダル) からページの新規作成ができない
┗ [#141664](https://redmine.weseek.co.jp/issues/141664) 修正

2024-03-01 08:53 UTC, miya commented on apps/app/src/client/services/use-toastr-on-error.tsx
https://github.com/weseek/growi/pull/8541/files#diff-55b0771d50bf096e8c9989e94a61cb579fcd2c898cced6d6e7cf4efc7ec52e9bL15-L28 を独立したファイルにして共通化しました。コピー元との差分はありません。

2024-03-01 11:20 UTC, yuki-takei requested changes

2024-03-01 11:20 UTC, yuki-takei commented on apps/app/public/static/locales/en_US/translation.json
> +  "Create today's": "Create today's memo",
これ commons.json にあったよね？

2024-03-02 10:15 UTC, miya commented on apps/app/public/static/locales/en_US/translation.json
> +  "Create today's": "Create today's memo",
commons.json にありましたのでそちらを使うように修正しました 🙏

2024-03-02 10:35 UTC, merged