imprv: 133910 141426 replace spinner pulse
weseek/growi pull request #8543
Opened 2024-03-01 08:32 UTC by TatsuyaIse

### task
- https://redmine.weseek.co.jp/issues/141426

2024-03-08 12:50 UTC, yuki-takei requested changes

2024-03-08 12:50 UTC, yuki-takei commented on apps/app/src/components/LoadingSpinnerPulse.jsx
LoadingSpinner を作ったのであればこのコンポーネントいらないと思う

2024-03-08 12:50 UTC, yuki-takei commented on apps/app/src/components/LoadingSpinnerPulse.jsx
> +  // If you want to use a large spinner icon, call this component with a larger font size (e.g. <span className="fs-3"><LoadingSpinnerPulse /></span>)
`<LoadingSpinnerPulse className="fs-3" />` で実現できるようにしてください

2024-03-13 06:41 UTC, TatsuyaIse commented
Pulse ではない `LoadingSpinner` に置き換えました  
以下 `Admin` の `QuestionnaireSetting` の画面キャプチャ (固定画像) です  
![image](https://github.com/weseek/growi/assets/8895367/668d8724-79b4-427f-a12d-fb85d7d9bbd6)

2024-03-13 08:10 UTC, yuki-takei approved these changes

2024-03-13 08:48 UTC, merged