imprv: Update tag edit modal design
weseek/growi pull request #8546
Opened 2024-03-02 17:48 UTC by jam411

## Description
task: https://redmine.weseek.co.jp/issues/141065
task: https://redmine.weseek.co.jp/issues/139809

## Screenshot
### light
![image](https://github.com/weseek/growi/assets/68407388/dc0cff2e-5d2b-486e-9a06-f7cbb02fd1c0)

![image](https://github.com/weseek/growi/assets/68407388/69df1a3a-d6bd-4845-b420-c97e539c6d8f)

### dark
![Screenshot 2024-03-03 024556](https://github.com/weseek/growi/assets/68407388/ef26d96b-74e7-4d17-be6d-b1f1fc6443c4)

![image](https://github.com/weseek/growi/assets/68407388/90052eef-ef06-49f7-88c4-f0d9f2e0ee69)

2024-03-02 17:49 UTC, jam411 commented on apps/app/src/styles/_override-rbt.scss
現状はコメントアウトするだけにしています。

2024-03-02 17:50 UTC, jam411 commented on apps/app/src/components/PageTags/RenderTagLabels.tsx
bootstrap のクラスを使うようにリファクタしました。

2024-03-04 19:35 UTC, yuki-takei requested changes

2024-03-04 19:35 UTC, yuki-takei commented on apps/app/src/components/PageTags/TagEditModal.module.scss
> +    box-shadow: 0 0 0 0.05rem #007bff40;
この色、ハードコードは NG では？
info 等の色に相当する css var にするか、またはテーマ毎の `--grw-primary-xxx` 等の css var を参照するようにするのか

2024-03-04 19:35 UTC, yuki-takei commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +    <Modal isOpen={isOpen} toggle={closeTagEditModal} id="edit-tag-modal" autoFocus={false} className={`tag-edit-modal ${styles['tag-edit-modal']}`}>
scoped ではない `tag-edit-modal` は消してください

2024-03-04 19:37 UTC, yuki-takei requested changes

2024-03-04 19:37 UTC, yuki-takei commented on apps/app/src/components/PageTags/TagEditModal.module.scss
> +    box-shadow: 0 0 0 0.05rem #007bff40;
また、細かいところだけれどカラー指定のブロックは別の `.tag-edit-modal :global { ... }` に分けてください 
他のコンポーネントに倣って `// == Color` みたいなのを付けておいてくれると後々探しやすい

2024-03-06 15:38 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.module.scss
> +    box-shadow: 0 0 0 0.05rem #007bff40;
`--grw-primary-400` を使うように修正しました。

2024-03-06 15:39 UTC, jam411 commented on apps/app/src/components/PageTags/TagEditModal.tsx
> +    <Modal isOpen={isOpen} toggle={closeTagEditModal} id="edit-tag-modal" autoFocus={false} className={`tag-edit-modal ${styles['tag-edit-modal']}`}>
ここで使っていた scss module を TagsInput.tsx に移動できそうだったので移動させました。

2024-03-06 20:30 UTC, merged