Imprv/133910 141620 replace fa rotate
weseek/growi pull request #8565
Opened 2024-03-11 05:16 UTC by TatsuyaIse

### task
- https://redmine.weseek.co.jp/issues/141620

### image capture
![image](https://github.com/weseek/growi/assets/8895367/208cdd89-10df-4901-99c5-7fd97763af94)

2024-03-12 21:26 UTC, yuki-takei requested changes

2024-03-12 21:26 UTC, yuki-takei commented on apps/app/src/styles/style-app.scss
> +}
- vendor prefix は常に不要
- 90 だけではなく https://fastbootstrap.com/docs/rotate/ を参考に一通り実装して
- apps/app ではなく packages/core に実装して
    - いずれ packages/ui とかでも使いそうなので
- style-app の冒頭で import して
    - flex-expand の取り扱いと同じ

2024-03-13 08:12 UTC, TatsuyaIse commented on packages/core/scss/_rotate.scss
> +$rotate-degrees: [0, 1, 2, 3, 6, 12, 45, 90, 180];
https://fastbootstrap.com/docs/rotate/ を参考に回転の角度を定義してみました。

2024-03-13 08:13 UTC, TatsuyaIse commented on packages/core/scss/_rotate.scss
> +  .-rotate-#{$degree} {
逆回転のスタイルも fastbootstrap を参考に定義

2024-03-13 08:25 UTC, merged