imprv: Disable groups not assignable to page due to parent grant
weseek/growi pull request #8570
Opened 2024-03-11 15:05 UTC by arafubeatbox

## task
https://redmine.weseek.co.jp/issues/142310

## やったこと
ページへのグループ紐付けの選択肢として表示されるもののうち、親の group grant の影響で紐づけられないものを disabled にする

## 方針
~~ページに紐づけるグループとして取得していた myUserGroups に canGrantPage というプロパティを追加~~
https://github.com/weseek/growi/pull/8591
https://github.com/weseek/growi/pull/8592
で実装した API のレスポンスに cannotGrant の情報を付与

## イメージ
disabled な選択肢は下に表示される
ユーザが属するものに関しては notGranted > isGranted > cannotGrant の順で表示
その下にユーザが属さないもの (全て granted) を表示
![image](https://github.com/weseek/growi/assets/32846231/d8ccdbce-707f-4e00-af2a-b09c248991af)

## 備考
テストは最後に書きます

2024-03-11 15:10 UTC, arafubeatbox commented on apps/app/src/server/service/page-grant.ts
> +      grant: PageGrant | undefined, grantedUserIds: ObjectIdLike[] | undefined, grantedGroupIds: IGrantedGroup[] | undefined,
元々 includeApplicable が false の時は返却するデータも単純で、async の要素がなかったためそのような場合は明示的にこのメソッドを使わないように変更。

背景)
getCanGrantPageForUserGroups の userGroups のループで async のこのメソッドを使用したくなかったため。

2024-03-12 21:09 UTC, yuki-takei requested changes

2024-03-12 21:09 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/me.ts
> +  router.get('/user-groups', accessTokenParser, loginRequiredStrictly, validator.getUserGroups, apiV3FormValidator,
`/me/user-groups` というエンドポイントでこの改修内容にあたる情報を返すことに違和感を覚えてきた。
後続タスクの

[タスク #142311](https://redmine.weseek.co.jp/issues/142311): 自身が所属していない、grant されているグループを disabled で選択肢に表示する

実装後の世界を考えてみても、`/me/user-groups` はもはや不要で、代わりに `/page/:pageId/user-groups` のようなエンドポイントで本 PR の内容と 142311 で提供する予定のデータ両方を返す方が理に適っている気がする。

実際にデータを作るサービスは PageGrantService のままでいいと思う。

2024-04-07 05:00 UTC, arafubeatbox commented on apps/app/src/server/routes/apiv3/me.ts
> +  router.get('/user-groups', accessTokenParser, loginRequiredStrictly, validator.getUserGroups, apiV3FormValidator,
> 代わりに /page/:pageId/user-groups のようなエンドポイントで本 PR の内容と 142311 で提供する予定のデータ両方を返す方が理に適っている気がする。

https://github.com/weseek/growi/pull/8591
https://github.com/weseek/growi/pull/8592
で /page/is-grant-normalized に実装しました。
また、この PR で /page/is-grant-normalized を /page/grant-data に変更しました。

2024-04-09 09:04 UTC, merged