feat: Resolve conflict from editor
weseek/growi pull request #8571
Opened 2024-03-12 04:51 UTC by miya

## Task
[#126533](https://redmine.weseek.co.jp/issues/126533) [v7][New Editor][collab] コンフリクト状態が起こりにくい新方式でページを更新できる
┗ [#142112](https://redmine.weseek.co.jp/issues/142112) Editor からコンフリクトを解消できる (latestRevision.origin が undefined の時)

2024-03-12 10:20 UTC, miya commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +    storeConflictHandler(conflictHandler);
新設した usePageStatusAlert に conflictHandler をキャッシュさせておく (微妙だと思っています...)
やりたいことは PageStatusAlert のコンフリクト解消ボタンを押下した時に conflictHandler() を発火させたいと思いこの実装になりました。

2024-03-12 10:20 UTC, miya commented on apps/app/src/components/PageStatusAlert.tsx
> +  }
usePageStatusAlert に入れた conflictHander の有無で Editor 時の Alert の出し分けをする

2024-03-12 10:20 UTC, miya commented on apps/app/src/components/PageStatusAlert.tsx
> +  }, [onClickResolveConflict, t]);
<img width="484" alt="スクリーンショット 2024-03-12 19 14 26" src="https://github.com/weseek/growi/assets/34241526/7ec5fd69-cd99-4167-8a9b-618837920e72">

2024-03-12 10:20 UTC, miya commented on apps/app/src/components/PageStatusAlert.tsx
> +  }, [refreshPage, remoteRevisionLastUpdateUser, t]);
<img width="491" alt="スクリーンショット 2024-03-12 19 14 17" src="https://github.com/weseek/growi/assets/34241526/140249bb-1b86-40cd-b445-5948c8216155">

2024-03-12 21:32 UTC, yuki-takei requested changes

2024-03-12 21:32 UTC, yuki-takei commented on apps/app/src/client/services/update-page/conflict.ts
> +export const usePageStatusAlert = (): SWRResponse<PageStatusAlertStatus, Error> & PageStatusAlertUtils => {
PageStatusAlert のための SWR hook は stores に作るべき

2024-03-13 02:09 UTC, miya commented on apps/app/src/client/services/update-page/conflict.ts
> +export const usePageStatusAlert = (): SWRResponse<PageStatusAlertStatus, Error> & PageStatusAlertUtils => {
修正しました

2024-03-13 13:09 UTC, miya commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +    openPageStatusAlert({ onResolveConflict: conflictHandler });
`PUT: /_api/v3/page` を行った結果コンフリクトがわかったタイミングで PageStatusAlert を表示させる。
コンフリクト解消後は Editor に編集結果を反映させつつ `PUT: /_api/v3/page` を行う。

2024-03-15 10:39 UTC, yuki-takei requested changes

2024-03-15 10:39 UTC, yuki-takei commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +    openPageStatusAlert({ onResolveConflict: conflictHandler });
コンフリクト解消関係の処理を別モジュールに切り出して hook で提供してください

- saveAndReturnToViewHandler と saveWithShortcut の宣言まではこのファイルでよくて、その中の save に渡す onConflictHandler 相当を hook から取得する感じ
- その hook には、Save function 型やその他必要なものを全て渡せばたぶん実現できる
- updateRemotePageDataHandler 

```
const { onConflict } = useConflictResolver({
  save: Save,
  onResolved: () => void,  // codeMirrorEditor?.initDoc(newMarkdown); などの処理
  ... // その他必要なもの
});
```

2024-03-15 10:39 UTC, yuki-takei commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +  }, [closePageStatusAlert, currentRevisionId, editorMode, onConflictHandlerEffect, openPageStatusAlert, socket]);
この useEffect はこのファイルに置いたままで OK

2024-03-15 10:39 UTC, yuki-takei commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +  }, [closePageStatusAlert, closeConflictDiffModal, codeMirrorEditor, openConflictDiffModal]);
このメソッドは後述の hook module が提供するように改修

2024-03-15 10:39 UTC, yuki-takei commented on apps/app/src/client/services/side-effects/page-updated.ts
> +      // Open PageStatusAlert
この処理は PageView でやるんだと思う

2024-03-15 14:26 UTC, miya commented on apps/app/src/client/services/side-effects/page-updated.ts
> +      // Open PageStatusAlert
Editor をレンダーしていない時に socket 通信ができないためそのままにしています。

2024-03-15 22:36 UTC, miya commented on apps/app/src/components/PageStatusAlert.tsx
> +    <div className={`${styles['grw-page-status-alert']} card text-white fixed-bottom animated fadeInUp faster bg-warning text-dark`}>
修正しました

2024-03-15 22:36 UTC, miya commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +    openPageStatusAlert({ onResolveConflict: conflictHandler });
hook を新設しました

2024-03-19 05:29 UTC, yuki-takei requested changes

2024-03-19 05:29 UTC, yuki-takei commented on apps/app/src/client/services/update-page/conflict.tsx
> +export const useGenerateResolveConflictHandler: GenerateResolveConflicthandler = () => {
外部への export はしなくていいのでは？

2024-03-19 05:29 UTC, yuki-takei commented on apps/app/src/client/services/update-page/conflict.tsx
細かいところだけど、このファイル PageEditor ディレクトリ下に移すべきかもなあ

2024-03-19 05:56 UTC, miya commented on apps/app/src/client/services/update-page/conflict.tsx
> +export const useGenerateResolveConflictHandler: GenerateResolveConflicthandler = () => {
確かに外部で利用しないものでしたので修正しました

2024-03-19 05:56 UTC, miya commented on apps/app/src/client/services/update-page/conflict.tsx
hooks 周りを切り出して修正しました

2024-03-19 06:24 UTC, merged