fix: Cannot view past revisionbody in editor
weseek/growi pull request #8582
Opened 2024-03-18 12:49 UTC by miya

## Task
[#140132](https://redmine.weseek.co.jp/issues/140132) [v7][collab] History から過去の revision を選択してエディター画面を開くと最新の revision が表示されてしまう
┗ [#140188](https://redmine.weseek.co.jp/issues/140188) 修正

2024-03-19 10:52 UTC, miya commented on apps/app/src/components/PageEditor/PageEditorReadOnly.tsx
> +});
- ReadOnly な PageEditor 
- 必要最小限のロジックを持つ

 scrollEditorHandler など必要なロジックは PageEditor.tsx から借りてきたもので内容は変わらないので共通化した方が良いでしょうか？

2024-03-19 12:54 UTC, yuki-takei requested changes

2024-03-19 12:54 UTC, yuki-takei commented on apps/app/src/components/PageEditor/PageEditorReadOnly.tsx
> +});
そうだね、hook にできたらいいかもね

2024-03-19 12:54 UTC, yuki-takei commented on packages/editor/src/components/CodeMirrorEditorReadOnly.tsx
> +  const { data: codeMirrorEditor } = useCodeMirrorEditorIsolated(GlobalCodeMirrorEditorKey.MAIN);
GlobalCodeMirrorEditorKey を同じにするとトラブルが起きたりしないかな？
CodeMirrorEditorReadOnly を利用してから最新リビジョンに遷移してエディタが使えるかどうか(またはその逆の順で不具合が起きないか)などをチェックしてほしい

2024-03-19 12:54 UTC, yuki-takei commented on apps/app/src/pages/[[...path]].page.tsx
> +  props.isOldRevisionPage = revisionId != null;
useIsLatestRevision と役割かぶってないかな
また、query に入っている ID が latest revision と同じ ID の場合どうなるか

2024-03-19 12:54 UTC, yuki-takei commented on apps/app/src/components/PageAlert/OldRevisionAlert.tsx
> +  const { data: isOldRevisionPage } = useIsOldRevisionPage();
useIsLatestRevision を使えないのはなぜ？

2024-03-20 12:24 UTC, miya commented on packages/editor/src/components/CodeMirrorEditorReadOnly.tsx
> +  const { data: codeMirrorEditor } = useCodeMirrorEditorIsolated(GlobalCodeMirrorEditorKey.MAIN);
特に不具合はなかったですが、念の為 readOnly 用の key を作成しました

2024-03-20 12:25 UTC, miya commented on apps/app/src/pages/[[...path]].page.tsx
> +  props.isOldRevisionPage = revisionId != null;
被っていますね.. useIsLatestRevision を使う実装に戻しました

2024-03-20 12:25 UTC, miya commented on apps/app/src/components/PageEditor/PageEditorReadOnly.tsx
> +});
hook を作成して共通化しました

2024-03-20 12:26 UTC, miya commented on apps/app/src/components/PageAlert/OldRevisionAlert.tsx
> +  const { data: isOldRevisionPage } = useIsOldRevisionPage();
useIsLatestRevision が使えましたので修正しました

2024-03-20 12:36 UTC, miya commented on packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
> +      ) }
readOnly 時は不要なので隠せられるように

2024-03-20 12:36 UTC, miya commented on apps/app/src/stores/page.tsx
> +    }
古い revision から最新 revision に戻る際に mutate されなかったので条件を追加しました

2024-03-21 00:59 UTC, miya commented on apps/app/src/components/PageAlert/OldRevisionAlert.tsx
> +    mutateCurrentPage();
「最新のページボタンを表示」ボタンをクリックしても今まで表示されていた古い revision が表示されたままでしたので最新の revision に遷移した後に `mutateCurrentPage()` をすることでこの問題を修正しました。

2024-03-21 11:40 UTC, merged