fix: Styling error in the Slack Integration
weseek/growi pull request #8584
Opened 2024-03-19 04:13 UTC by reiji-h

# 概要

`/admin/slack-integration` の画面崩れの修正

# Task
- https://redmine.weseek.co.jp/issues/141938
   - https://redmine.weseek.co.jp/issues/142712

2024-03-21 06:47 UTC, satof3 commented on apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxyConnectionStatus.tsx
> +        <h5 className="card-title fw-bold mt-3 ms-4 text-center">Slack</h5>
`text-center`が入ったので`ms-3`が不要です

2024-03-21 06:47 UTC, satof3 commented on apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxyConnectionStatus.tsx
> +        <h5 className="card-title fw-bold mt-3 ms-4 text-center">GROWI App</h5>
こちらも`ms-4`が不要です

2024-03-21 07:53 UTC, reiji-h commented on apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxyConnectionStatus.tsx
> +        <h5 className="card-title fw-bold mt-3 ms-4 text-center">Slack</h5>
削除しました

2024-03-21 07:53 UTC, reiji-h commented on apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxyConnectionStatus.tsx
> +        <h5 className="card-title fw-bold mt-3 ms-4 text-center">GROWI App</h5>
削除しました

2024-03-21 12:13 UTC, yuki-takei requested changes

2024-03-21 12:13 UTC, yuki-takei commented on apps/app/src/components/Layout/Admin.module.scss
> +        color: $gray-200;
light/dark 対応できてる？

2024-03-21 12:13 UTC, yuki-takei commented on apps/app/src/components/Layout/Admin.module.scss
> +        z-index: 1;
なるべく bs5 のユーティリティクラスにする

2024-03-21 12:14 UTC, merged

2024-03-21 12:15 UTC, yuki-takei commented
間違えてマージしてしまったので #8597 で revert した

2024-03-22 03:35 UTC, reiji-h commented on apps/app/src/components/Layout/Admin.module.scss
> +        z-index: 1;
bs5 を使うように修正しました。

2024-03-22 04:14 UTC, reiji-h commented on apps/app/src/components/Layout/Admin.module.scss
> +        color: $gray-200;
Primary の中に表示される文字色であり、Primary の色が light/dark で変わらないので、対応できていないほどではないと思います。

2024-03-22 05:32 UTC, reiji-h commented on apps/app/src/components/Layout/Admin.module.scss
> +        color: $gray-200;
@satof3 と確認して、現状は Primary の中に入っているため問題ないという認識になりました。