feat: Reflect update results from view in ydoc
weseek/growi pull request #8594
Opened 2024-03-21 06:32 UTC by miya

## Task
[#126533](https://redmine.weseek.co.jp/issues/126533) [v7][New Editor][collab] コンフリクト状態が起こりにくい新方式でページを更新できる
┗ [#142109](https://redmine.weseek.co.jp/issues/142109) View からページを更新した時に ydoc を更新させる

2024-03-21 12:49 UTC, miya commented on apps/app/src/server/service/yjs-connection-manager.ts
> +    // It's necessary to confirm that the user is not editing the target page in the Editor
ydoc の更新前に Editor で編集している人がいないことを確認する必要がある

2024-03-21 12:49 UTC, miya commented on apps/app/src/server/service/yjs-connection-manager.ts
> +    currentYdoc.getText('codemirror').insert(0, newMarkdown);
- 最新の ydoc からその文字列分削除して最新の revisionBody を insert している
- 最適解かどうかわかっていない状態 (yjs community に質問を投げている)
- 参考
  - https://docs.yjs.dev/api/shared-types/y.text

2024-03-22 08:55 UTC, yuki-takei requested changes

2024-03-22 08:55 UTC, yuki-takei commented on apps/app/src/server/service/socket-io.js
> +          await this.yjsConnectionManager.handleYDocUpdate(pageId, newMarkdown);
これは update API (`update-page.ts`) の postAction の中でやる

そのためには yjsConnectionManager をシステムグローバルに取得可能な singleton instance にする必要がある
SocketIoService の中では YjsConnectionManager をインスタンス化することはなくなる

2024-03-22 08:55 UTC, yuki-takei commented on apps/app/src/server/service/socket-io.js
> +  setupYjsUpdateEvent() {
この setup はなくなる

2024-03-22 08:55 UTC, yuki-takei commented on apps/app/src/server/service/yjs-connection-manager.ts
> +    currentYdoc.getText('codemirror').delete(0, currentMarkdownLength);
delete の第二引数って `-1` とか入らないのかな？

2024-03-23 08:55 UTC, miya commented on apps/app/src/server/service/socket-io.js
> +          await this.yjsConnectionManager.handleYDocUpdate(pageId, newMarkdown);
修正しました

2024-03-23 08:55 UTC, miya commented on apps/app/src/server/service/socket-io.js
> +  setupYjsUpdateEvent() {
修正しました

2024-03-23 08:57 UTC, miya commented on apps/app/src/server/service/yjs-connection-manager.ts
> +};
初期化時に引数が必要なためこのような実装になりました

2024-03-24 14:05 UTC, yuki-takei requested changes

2024-03-24 14:05 UTC, yuki-takei commented on apps/app/src/server/service/yjs-connection-manager.ts
> +};
1. `instanciateYjsConnectionManager(io)` を新設し、`crowi/index.js` から呼ぶ
2. 使う側は引数なしの `getYjsConnectionManager()` を呼ぶ

2024-03-24 14:05 UTC, yuki-takei commented on apps/app/src/server/service/socket-io.js
> +    this.yjsConnectionManager = getYjsConnectionManager(this.io);
このサービスはインスタンス化の責務を持たないようにする

2024-03-25 04:20 UTC, miya commented on apps/app/src/server/service/yjs-connection-manager.ts
> +};
FB 対応しました

2024-03-25 09:05 UTC, yuki-takei requested changes

2024-03-25 10:11 UTC, merged