feat: Apply locale to defualt page title
weseek/growi pull request #8600
Opened 2024-03-21 17:04 UTC by jam411

## Description
task: https://redmine.weseek.co.jp/issues/143040

## Screenshot

2024-03-22 07:46 UTC, jam411 commented on apps/app/src/utils/locale-utils.ts
client/util/locale-utils.ts から移動しました

2024-03-22 08:08 UTC, yuki-takei requested changes

2024-03-22 08:08 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/create-page.ts
> +  };
これは各言語の json から採らないといけない
つまり、i18next の `t` インスタンスを利用する必要がある

import で使えるならそれが理想
無理なら `req.t` から取得しかないが、負債として残る
https://redmine.weseek.co.jp/issues/125884

2024-04-26 02:10 UTC, jam411 commented on apps/app/src/server/routes/apiv3/page/create-page.ts
> +  const basePathname = t?.('create_page.untitled') || 'Untitled';
i18next, react-i18next, next-i18next を試しましたが
[next-i18next を適用できた](https://github.com/i18next/next-i18next/issues/1698#issuecomment-1046732836)ので commons.ts でやっている locale 特定をここにおいています。
https://github.com/weseek/growi/blob/bcca30bf781fb3658f6c3ab06ca05c7216cddf2e/apps/app/src/pages/utils/commons.ts#L126-L128

ただし外部から API をたたいた場合などで、 Client がレンダリングされていない状態だと t 関数が null になります。なので falsy な場合はハードコーディングで `basePathname="Untitled"` になるようにしました。

ブラウザからアクセスするタイミングでサーバーログにこれが出るあたりで t 関数を使えるかどうかが変わり、おそらく `getServerSideProps` で実行される `serverSideTranslations` が関係しているのではないかなと思っています。
![image](https://github.com/weseek/growi/assets/68407388/19bc8f00-c8da-461e-82cb-dd5461236b64)

2024-04-26 02:10 UTC, jam411 commented on apps/app/src/utils/locale-utils.ts
server side でも呼び出すために丸ごと utils 配下に移動しました。

2024-04-26 02:32 UTC, jam411 commented on apps/app/src/utils/locale-utils.ts
「新規ユーザーのデフォルト設定言語」のみ見るので revet しました。
https://redmine.weseek.co.jp/issues/141574

2024-04-26 02:39 UTC, jam411 commented on apps/app/src/server/routes/apiv3/page/create-page.ts
> +  const basePathname = t?.('create_page.untitled') || 'Untitled';
- i18next, react-i18next, next-i18next を試しましたが next-i18next を適用できたので使っています。
ref: https://github.com/i18next/next-i18next/issues/1698#issuecomment-1046732836

- locale はストーリーの仕様より globalLang のみを参照しています。
https://redmine.weseek.co.jp/issues/141574
https://wsgrowi.slack.com/archives/C05LB9T4KR9/p1714098148433849

- 外部から API をたたいた場合などで、 Client がレンダリングされていない状態だと t 関数が null になります。なので falsy な場合はハードコーディングで `basePathname="Untitled"` になるようにしました。t 関数が使えるかどうかは、ブラウザからアクセスしてサーバーログに添付写真が出るあたりで変わりそうでした。おそらく `getServerSideProps` で実行される `serverSideTranslations` が関係しているのではないかなと思っています。
![image](https://github.com/weseek/growi/assets/68407388/19bc8f00-c8da-461e-82cb-dd5461236b64)

- `serverSideTranslation` を仕込んで使えないかいくつか試しましたが、複雑になりそうだったこともあり適用していません。 ref: https://github.com/i18next/next-i18next/issues/1698#issuecomment-1046754181

2024-05-01 23:37 UTC, yuki-takei commented
## 修正サマリ
サーバーサイドの `create-page.ts` でもローカライズされるように修正

## 手段
- サーバーサイド用の i18next instance を作成するモジュールを追加
- コンフィグファイルを分割
    - i18next の InitOptions 型オブジェクトを export するコンフィグファイルを作成
    - 新モジュールと next-i18next 用コンフィグファイル両方から参照できるように

2024-05-01 23:39 UTC, merged