feat: Update App Title presentation
weseek/growi pull request #8601
Opened 2024-03-21 18:12 UTC by jam411

## Description
task: https://redmine.weseek.co.jp/issues/143042

## XD

2024-03-21 18:22 UTC, jam411 commented on apps/app/src/components/Sidebar/AppTitle/AppTitle.tsx
> +        <div id="grw-site-name" className="grw-site-name text-truncate">
truncate がデグレしているので修正する

2024-03-24 17:06 UTC, jam411 commented on apps/app/src/components/Admin/App/AppSetting.jsx
defaultValue だと以下の再現条件で onChange の event が発火されていなかったので value を使うように修正しました。

## 再現条件
- `/admin/app` のサイト名とコンフィデンシャルの input に `a` など一文字だけ入れて保存する
- ブラウザリロードして input に先ほど入力した文字列が表示されていることを確認する
- back space で文字列を消す
- 更新を押す

## 症状
- 変更が反映されない

2024-03-25 09:03 UTC, yuki-takei requested changes

2024-03-25 09:03 UTC, yuki-takei commented on apps/app/src/components/Sidebar/AppTitle/AppTitle.tsx
> +          </span>
Link のままでいいと思う

2024-03-25 09:03 UTC, yuki-takei commented on apps/app/src/components/Sidebar/AppTitle/AppTitle.module.scss
> +    }
appTitle は Link のままでいいので、このスタイル適用は不要だと思う

2024-03-25 16:21 UTC, jam411 commented on apps/app/src/components/Sidebar/AppTitle/AppTitle.tsx
> +          </span>
修正しました

2024-03-25 16:21 UTC, jam411 commented on apps/app/src/components/Sidebar/AppTitle/AppTitle.module.scss
> +    }
修正しました

2024-03-26 07:48 UTC, merged