wip Improved white space
weseek/growi pull request #8615
Opened 2024-03-26 06:38 UTC by kazutoweseek

サイドバー_pagetree の switch 下部の不要なスペースを削除。wipの余白を修正しました。

2024-03-28 15:06 UTC, yuki-takei requested changes

2024-03-28 15:06 UTC, yuki-takei commented on apps/app/src/features/search/client/components/SearchModal.tsx
> -                <div className="border-top mt-2 mb-2" />
これ別のタスク向けの変更では？

2024-03-28 15:06 UTC, yuki-takei commented on apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx
> +              <label className="form-label form-check-label text-muted mb-0" htmlFor="wipPageVisibility">
こちらは OK

2024-03-29 07:23 UTC, kazutoweseek commented on apps/app/src/features/search/client/components/SearchModal.tsx
> -                <div className="border-top mt-2 mb-2" />
間違えてコミットとプッシュしてしまいました。

2024-04-01 07:31 UTC, merged