support: New Comment style
weseek/growi pull request #8631
Opened 2024-03-29 07:33 UTC by satof3

# Task
https://redmine.weseek.co.jp/issues/142908

# 概要
- コメントデザインの改良
  - 新規コメント、コメントエディタにアイコンを追加
  - コメントUI全般の背景をグラスニューモーフィズムへ
- Button や TabPane などの ReactStrap を Bootstrap化

# XD
- https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/e8c35039-ed3f-46f5-8684-7b07b5be2a71/
- https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/17103fbd-7c15-4e79-9625-65bca8ee4d49/

# ScreenShot

2024-04-02 07:54 UTC, yuki-takei requested changes

2024-04-02 07:54 UTC, yuki-takei commented on apps/app/public/static/locales/en_US/translation.json
> +  "comment": "Commment",
```
  "color_mode_settings": {
    "light": "ライト",
    "dark": "ダーク",
    "system": "システム",
    "settings": "カラーモードの設定",
    "description": "ライトモードかダークモード、もしくはシステム合わせた表示をするか選択します。<br>対応したテーマのみ切り替えることができます。"
  },
```
のようにグループを作ってその中に入れてください

2024-04-02 07:54 UTC, yuki-takei commented on apps/app/src/components/PageComment.module.scss
> +    }
実際に使うコンポーネントの module scss に移す

2024-04-02 07:54 UTC, yuki-takei commented on apps/app/src/components/PageComment.module.scss
> +    }
実際に使うコンポーネントの module scss に移す

2024-04-02 07:54 UTC, yuki-takei commented on apps/app/src/components/PageComment/Comment.tsx
> +                  className="page-comment-revision comment-timestamp"
page-comment-revision と comment-timestamp は整頓を

2024-04-02 11:07 UTC, satof3 commented on apps/app/public/static/locales/en_US/translation.json
> +  "comment": "Commment",
既存の`"Page_comment"`というグループに入れました

2024-04-02 11:12 UTC, satof3 commented on apps/app/src/components/PageComment.module.scss
> +    }
`_comment-inheritance.scss`に移しました

2024-04-02 11:15 UTC, satof3 commented on apps/app/src/components/PageComment.module.scss
> +    }
下記コメントの`.page-comment-revision`にスタイルのみ移し、`.comment-timestamp`はクラスごと消しました

2024-04-02 11:15 UTC, satof3 commented on apps/app/src/components/PageComment/Comment.tsx
> +                  className="page-comment-revision comment-timestamp"
問題なかったので`.page-comment-revision`にまとめました

2024-04-03 08:47 UTC, yuki-takei requested changes

2024-04-03 08:47 UTC, yuki-takei commented on apps/app/src/components/PageComment/CommentEditor.tsx
> +              <p className="ms-2 mb-0">Add a comment</p>
localize してください
もしくはそのような後続タスクを作る

2024-04-03 08:47 UTC, yuki-takei commented on apps/app/src/components/PageComment/CommentEditor.tsx
> +            <div id="comment_editor" className="tab-pane active">
素の bs5 で実装するなら、id は変えないといけない
(CommentEditor コンポーネントは同一画面に多数出現するため)

2024-04-04 05:38 UTC, satof3 commented on apps/app/src/components/PageComment/CommentEditor.tsx
> +              <p className="ms-2 mb-0">Add a comment</p>
整理しながら進めたいので後続タスクにしました
https://redmine.weseek.co.jp/issues/143958

2024-04-04 13:46 UTC, merged