fix: Initialize grant correctly after when page transition
weseek/growi pull request #8633
Opened 2024-03-29 08:49 UTC by yukendev

ストーリー: https://redmine.weseek.co.jp/issues/140819

タスク: https://redmine.weseek.co.jp/issues/143352

やったこと

ページ編集の保存時に、`useSWRxIsGrantNormalized`のmutateを行うようにした

2024-03-29 08:56 UTC, yukendev commented on apps/app/src/client/services/page-operation.ts
> -  IApiv3PageCreateParams, IApiv3PageCreateResponse, IApiv3PageUpdateParams, IApiv3PageUpdateResponse,
使われていない型のimportを削除しました

2024-03-29 08:56 UTC, yukendev commented on apps/app/src/client/services/page-operation.ts
> +    await mutateGrant();
ページ保存時にgrantデータがmutateされておらず、ページ移動しても初期化時に入れたgrantデータが保持されたままだったことが不具合の原因だったので、ページ保存時にgrantデータをmutateするようにしました

2024-03-29 12:40 UTC, yuki-takei requested changes

2024-03-29 12:40 UTC, yuki-takei commented on apps/app/src/client/services/page-operation.ts
> +    await mutateGrant();
useSWRxApplicableGrant も同様の理屈で mutate する必要があるんじゃないかな

2024-04-14 05:12 UTC, yukendev commented on apps/app/src/client/services/page-operation.ts
> +    await mutateGrant();
その必要がありそうだったので追加しました。

2024-04-15 14:36 UTC, merged