[WIP] refs #143808: OpenTelemetry で GROWI から Trace を吐き出せる
weseek/growi pull request #8667
Opened 2024-04-03 07:10 UTC by skomma

現段階でまだ動いていない。

Next.js 公式ドキュメント通りやってるつもりだが、読み込まれていたら出てくるはずのログが出てこない…

https://nextjs.org/docs/app/building-your-application/optimizing/open-telemetry#using-vercelotel

2024-04-08 05:23 UTC, skomma commented on .devcontainer/docker-compose.yml
> +    - opentelemetry-collector-dev-setup_default
あまり整理されたやり方にはなっていないが、手元で動作確認できるように、docker-compose.yml に追加した。

2024-04-08 05:23 UTC, skomma commented on apps/app/src/server/crowi/index.js
> +  // await newSdk.start();
ちょっと試したのでコメントで残してある。

2024-04-08 05:23 UTC, skomma commented on apps/app/src/server/crowi/index.js
> +        exporter: new OTLPMetricExporter({ url: 'http://otel-collector:4317' }),
一旦宛先固定で書いている。

2024-04-08 08:00 UTC, skomma commented
/retest

2024-04-09 09:01 UTC, yuki-takei requested changes

2024-04-09 09:01 UTC, yuki-takei commented on .devcontainer/docker-compose.yml
> +    - opentelemetry-collector-dev-setup_default
この設定が恒久的なものなら、説明がたりない (開発スタートアップにも説明が必要になってくるかも)
後続タスクを作っておいて。

恒久的なものでないのなら、やはり消すための後続タスクを作って。

2024-04-10 08:06 UTC, skomma commented on .devcontainer/docker-compose.yml
> +    - opentelemetry-collector-dev-setup_default
後続ストーリーを用意して、ソース内にコメントを追記した。

2024-04-10 08:06 UTC, skomma commented on apps/app/src/server/crowi/index.js
> +  // await newSdk.start();
分離した。

2024-04-10 11:10 UTC, yuki-takei requested changes

2024-04-10 11:10 UTC, yuki-takei commented on apps/app/src/server/crowi/index.js
> +  const otel = new OpenTelemetry('next-app', 'growi-app-XXX', this.version);
ここの instanceId を決定する後続ストーリーを作って TODO コメントを入れてください

2024-04-11 02:32 UTC, skomma commented on apps/app/src/server/crowi/index.js
> +  const otel = new OpenTelemetry('next-app', 'growi-app-XXX', this.version);
ストーリーを作成してコメントに書いた

2024-04-11 07:24 UTC, merged