feat: Mark to check for the presence of drafts
weseek/growi pull request #8681
Opened 2024-04-04 09:38 UTC by miya

## Task
[#132775](https://redmine.weseek.co.jp/issues/132775) [v7][New Editor][collab] Editor で編集中またはドラフトが存在することを subnav から確認できる
┗ [#141357](https://redmine.weseek.co.jp/issues/141357) デザイン実装#8680 

## Screenshot
<img width="262" alt="スクリーンショット 2024-04-04 18 32 54" src="https://github.com/weseek/growi/assets/34241526/c79d0720-9145-4f82-a254-74bb3c6fae63">

2024-04-04 09:46 UTC, miya commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +            { hasYjsDraft && <span className="position-absolute top-0 start-100 translate-middle p-1 bg-primary border border-light rounded-circle" />}
公式のサンプルコードを参考
https://getbootstrap.jp/docs/5.3/components/badge/#%e4%bd%8d%e7%bd%ae

2024-04-04 10:45 UTC, yuki-takei requested changes

2024-04-04 10:45 UTC, yuki-takei commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +            { hasYjsDraft && <span className="position-absolute top-0 start-100 translate-middle p-1 bg-primary border border-light rounded-circle" />}
border-light だけ、このままでいいのかどうか再考してほしい
light/dark mode 対応したほうがいいのか、外すだけで問題ないのか

2024-04-04 10:47 UTC, yuki-takei commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +  const hasYjsDraft = false;
名前これでいいのかな…
ストーリーに

> View を見ているのかエディタを開いているのかという情報を含む

という条件を考慮するようには書いてあるので、後続タスクで変数名で何が相応しいのかは改めて考えてほしい

2024-04-09 05:31 UTC, miya commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +            { hasYjsDraft && <span className="position-absolute top-0 start-100 translate-middle p-1 bg-primary border border-light rounded-circle" />}
border-light を外しました (ふみやさんと合意済み)

2024-04-11 06:02 UTC, merged