fix: lsx icon and localization
weseek/growi pull request #8691
Opened 2024-04-05 07:40 UTC by satof3

# Task
- https://redmine.weseek.co.jp/issues/143853

# 概要
- lsxページのアイコンのズレを修正
- Load more ボタンをlocalize
  - https://redmine.weseek.co.jp/issues/140566

# Screenshot
<img width="509" alt="image" src="https://github.com/weseek/growi/assets/113958844/719fac94-0380-4c1f-aa86-88c54e733c77">

2024-04-09 09:07 UTC, yuki-takei requested changes

2024-04-09 09:07 UTC, yuki-takei commented on apps/app/public/static/locales/en_US/translation.json
localize はタスクのスコープ外なので取り除いてください

2024-04-09 09:07 UTC, yuki-takei commented on packages/remark-lsx/src/client/components/LsxPageList/LsxListView.module.scss
> +    --grw-wiki-link-hover-color-rgb: $body-color;
これだと hover で色が変わらないのでは？

2024-04-10 08:14 UTC, satof3 commented on apps/app/public/static/locales/en_US/translation.json
削除しました

2024-04-11 07:33 UTC, merged