support: Comment localization
weseek/growi pull request #8694
Opened 2024-04-05 12:10 UTC by satof3

# Task
‐ https://redmine.weseek.co.jp/issues/143958

## 翻訳のタスク
- [Add a comment](https://redmine.weseek.co.jp/issues/140554)
- [slack notification](https://redmine.weseek.co.jp/issues/140556)
- [削除モーダル](https://redmine.weseek.co.jp/issues/140568)
- [Reply](https://redmine.weseek.co.jp/issues/140567)

# 概要
- コメントボタンの翻訳
- コメントエディタの翻訳
- コメントリプライボタンの翻訳
- コメント削除モーダルの翻訳

# Screenshot
- <img width="542" alt="image" src="https://github.com/weseek/growi/assets/113958844/5d9b03f2-927a-4e48-bff0-20f7720bed26">
- ![image](https://github.com/weseek/growi/assets/113958844/bf1bdcc0-5519-484a-a441-f4a81d4f3b82)
- ![image](https://github.com/weseek/growi/assets/113958844/7b1d809c-11df-4aba-94b8-916947db9e23)

2024-04-09 08:48 UTC, yuki-takei requested changes

2024-04-09 08:48 UTC, yuki-takei commented on apps/app/public/static/locales/en_US/translation.json
> +  "write": "Write",
これも page_comment 内に入れるべき

2024-04-09 08:48 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/translation.json
> +  "write": "内容",
内容、は変じゃないかなあ

2024-04-10 06:08 UTC, satof3 commented on apps/app/public/static/locales/ja_JP/translation.json
> +  "write": "内容",
田中さんと相談し「入力」に変更しました

2024-04-10 10:58 UTC, merged