tags-en-ja
weseek/growi pull request #8698
Opened 2024-04-08 05:05 UTC by kazutoweseek

2024-04-12 06:23 UTC, kazutoweseek commented
![スクリーンショット 2024-04-12 152025](https://github.com/weseek/growi/assets/164848419/b0d077fe-607f-465a-9db7-3e4b172c29dd)
![スクリーンショット 2024-04-12 152249](https://github.com/weseek/growi/assets/164848419/98713015-6fa4-42bb-b5fe-5f550435c46d)

2024-04-17 03:17 UTC, miya commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const { t } = useTranslation('');
引数は不要だと思う

2024-04-17 03:17 UTC, miya commented on apps/app/src/components/PageControls/PageControls.tsx
> +        <div className="mb-0">{t('Tags')}</div>
div タグいらないんじゃないかな

2024-04-17 03:24 UTC, miya requested changes
PR 名を改善してください。

## 参考 (同一ストーリーの PR)
https://github.com/weseek/growi/pull/8716

2024-04-19 05:25 UTC, kazutoweseek commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const { t } = useTranslation('');
引数がないとエラーが出てしまいました。

2024-04-19 07:11 UTC, kazutoweseek commented on apps/app/src/components/PageControls/PageControls.tsx
> +        <div className="mb-0">{t('Tags')}</div>
divタグがないとCIが回りませんでした。

2024-04-19 07:24 UTC, kazutoweseek commented on apps/app/src/components/PageControls/PageControls.tsx
> +        <div className="mb-0">{t('Tags')}</div>
divタグないとCIが回りませんでした

2024-04-22 06:47 UTC, miya commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const { t } = useTranslation('');
エラー内容をコメントしてください

2024-04-22 06:47 UTC, miya commented on apps/app/src/components/PageControls/PageControls.tsx
> +        <div className="mb-0">{t('Tags')}</div>
エラー内容をコメントしてください

2024-04-22 06:59 UTC, miya requested changes

2024-04-22 06:59 UTC, miya commented on apps/app/src/components/PageControls/PageControls.tsx
> -        Tags
多言語対応した tag はどこに表示されるのか

2024-04-22 07:26 UTC, kazutoweseek commented on apps/app/src/components/PageControls/PageControls.tsx
> +        <div className="mb-0">{t('Tags')}</div>
divがなくてもできました

2024-04-22 07:26 UTC, kazutoweseek commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const { t } = useTranslation('');
引数がなくても出来ました。

2024-04-26 05:09 UTC, closed without merging