imprv: FootstrampIcon-delete-material symbolsIcon-put
weseek/growi pull request #8699
Opened 2024-04-08 06:06 UTC by kazutoweseek

TASK
https://redmine.weseek.co.jp/issues/143625
┗https://redmine.weseek.co.jp/issues/143952

2024-04-08 06:31 UTC, miya commented on packages/ui/src/components/PagePath/PageListMeta.tsx
> -import { FootstampIcon } from '../FootstampIcon';
不要なファイルを削除してください

2024-04-08 08:25 UTC, miya requested changes

2024-04-08 08:25 UTC, miya commented on CHANGELOG.md
この差分は不要なので元に戻してください

2024-04-08 08:25 UTC, miya commented on packages/ui/scss/molecules/_page_list.scss
> -      }
/workspace/growi/apps/app/src/components/Sidebar/RecentChanges.module.scss の中にあるる class も消そう

2024-04-19 07:27 UTC, kazutoweseek commented on CHANGELOG.md
僕の画面では消えているように見えます

2024-04-19 07:33 UTC, kazutoweseek commented on packages/ui/scss/molecules/_page_list.scss
> -      }
私の画面VSCODEでは消えているように見えます。

2024-04-19 08:15 UTC, miya requested changes

2024-04-19 08:15 UTC, miya commented on CHANGELOG.md
差分を消してください

2024-04-25 08:59 UTC, merged