Imprv: search results form improvements
weseek/growi pull request #8705
Opened 2024-04-10 01:42 UTC by maeshinshin

## Task
[#140673](https://redmine.weseek.co.jp/issues/140673): [v7] 検索結果ページから再度検索する際でも SearchModal を開くことができる
┗ [#143662](https://redmine.weseek.co.jp/issues/143662) 実装

## Demo
![Uploading Demo.gif…]()

2024-04-10 03:34 UTC, miya requested changes

2024-04-10 03:34 UTC, miya commented on apps/app/src/features/search/client/stores/search.ts
> +      }
undefined 許容にしたことによってシンプルになりそう

2024-04-10 03:34 UTC, miya commented on apps/app/src/features/search/client/stores/search.ts
> +  const initialStatus = { searchKeyword: '', isOpened: false };
undefined 許容にしたらこの値は不要になる

2024-04-10 03:34 UTC, miya commented on apps/app/src/features/search/client/stores/search.ts
> +  searchKeyword: string,
undefined 許容で良さそう
```suggestion
  searchKeyword?: string,
```

2024-04-10 03:34 UTC, miya commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +export default ForwardedSearchTypeahead;
ForwardedSearchTypeahead という名前は react-bootstrap-typeahed を利用したコンポーネントをラップしていた時の名前なので修正しよう

2024-04-10 03:34 UTC, miya commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +};
TypeaheadProps という props は不要そう

2024-04-10 03:34 UTC, miya commented on apps/app/src/features/search/client/components/SearchModal.tsx
> +    if (!searchModalData?.isOpened || typeof searchModalData?.searchKeyword === 'undefined') {
null チェックに変更する
https://tips.weseek.co.jp/5fb74e7aa1ba4200489a4bd1#%E5%88%A4%E5%AE%9A%E5%BC%8F
```suggestion
    if (searchModalData?.searchKeyword != null)
```

2024-04-10 03:52 UTC, miya commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +export default ForwardedSearchTypeahead;
もはや forwardRef もいらないかも

2024-04-10 04:28 UTC, maeshinshin commented on apps/app/src/features/search/client/stores/search.ts
> +  searchKeyword: string,
修正しました。

2024-04-10 04:33 UTC, maeshinshin commented on apps/app/src/features/search/client/stores/search.ts
> +  const initialStatus = { searchKeyword: '', isOpened: false };
修正しました。

2024-04-10 04:33 UTC, maeshinshin commented on apps/app/src/features/search/client/stores/search.ts
> +      }
修正しました。

2024-04-10 04:42 UTC, maeshinshin commented on apps/app/src/features/search/client/components/SearchModal.tsx
> +    if (!searchModalData?.isOpened || typeof searchModalData?.searchKeyword === 'undefined') {
修正しました。

2024-04-10 04:57 UTC, maeshinshin commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +export default ForwardedSearchTypeahead;
修正しました。

2024-04-10 05:07 UTC, maeshinshin commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +};
修正しました。

2024-04-10 06:06 UTC, miya requested changes

2024-04-10 06:12 UTC, miya commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +const SearchModalTriggerinput: ForwardRefRenderFunction<IFocusable, Props> = (props: Props) => {
ForwardRefRenderFunction もいらないね。以下のような形になりそうだね。
```typescript
SearchModalTriggerinput: React.FC<Props> = (props: Props) => { 
```

2024-04-10 06:13 UTC, miya commented on apps/app/src/features/search/client/stores/search.ts
> +    close: () => swrResponse.mutate({ isOpened: false, searchKeyword: '' }),
close した時に searchKeyword を undefined にしよう

2024-04-10 06:27 UTC, maeshinshin commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +export default SearchModalTriggerinput;
修正しました。

2024-04-10 06:38 UTC, maeshinshin commented on apps/app/src/features/search/client/stores/search.ts
> +    close: () => swrResponse.mutate({ isOpened: false, searchKeyword: '' }),
修正しました。

2024-04-10 06:47 UTC, maeshinshin commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +const SearchModalTriggerinput: ForwardRefRenderFunction<IFocusable, Props> = (props: Props) => {
修正しました。

2024-04-10 06:47 UTC, maeshinshin commented on apps/app/src/features/search/client/stores/search.ts
> +    close: () => swrResponse.mutate({ isOpened: false, searchKeyword: '' }),
修正しました。

2024-04-10 11:07 UTC, yuki-takei requested changes

2024-04-10 11:07 UTC, yuki-takei commented on apps/app/src/features/search/client/stores/search.ts
> +    },
以前のコードがあまりよくなかったんだけど、open に指定するメソッドは useCallback を使って作成してください。close もついでにそのように。

2024-04-11 00:33 UTC, miya requested changes

2024-04-11 00:33 UTC, miya commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +        data-testid="open-search-modal-button"
これは消してください

2024-04-11 00:56 UTC, miya requested changes

2024-04-11 00:56 UTC, miya commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +        data-testid="open-search-modal-button"
これは不要なので消してください

2024-04-12 07:28 UTC, maeshinshin commented on apps/app/src/features/search/client/stores/search.ts
> +    },
修正いたしました。

2024-04-12 07:31 UTC, maeshinshin commented on apps/app/src/components/SearchPage/SearchModalTriggerInput.tsx
> +        data-testid="open-search-modal-button"
修正いたしました。

2024-04-12 08:06 UTC, merged