imprv: Truncate page path title in view
weseek/growi pull request #8707
Opened 2024-04-10 09:54 UTC by reiji-h

# Summary
- View におけるページタイトルが Sticky になったときに正常に省略されるようにする。
- 正常にとは、Sidebar の開閉、ドラッグ時にその広さに対応した長さにできるようにすることである。

# Task 
- https://redmine.weseek.co.jp/issues/143964
  - https://redmine.weseek.co.jp/issues/144048

# Draft
- サイドバーのドラッグには対応できたが、開閉には対応できていないため
- サイドバーの開閉をしたときに、useRef で管理している親コンポーネントの座標が正常に更新されない。
  - 開いたときにはサイドバーを閉じたときにあるべき座標が、閉じたときにはサイドバーを開いたときにあるべき座標が取得されてしまう。

2024-04-10 11:23 UTC, yuki-takei requested changes

2024-04-10 11:23 UTC, yuki-takei commented on apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
> +    setNavMaxWidth(pageControlsX - pagePathNavRef.current.getBoundingClientRect().x - 10);
sidebarMode が変わってからサイドバーの開閉アニメーションがあるので、それが終わった時に getBoundingClientRect しないといけないだろうね。

選択肢としては、

1. setTimeout を使ってアニメーションが終わったであろうタイミングを見計らって getBoundingClientRect を呼ぶ
1. MutationObserver でレンダリング完了後のタイミングを検知する

とか？

2024-04-10 11:23 UTC, yuki-takei commented on apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
> +    setNavMaxWidth(pageControlsX - pagePathNavRef.current.getBoundingClientRect().x - 10);
pagePathNavRef に対しても useRect を使う、では検知できないの？

2024-04-12 03:18 UTC, reiji-h commented on apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
> +    setNavMaxWidth(pageControlsX - pagePathNavRef.current.getBoundingClientRect().x - 10);
useRect では検知できませんでした。サイドバーの width 変更も検知できなかったので、今回は useRect は使わない方針です。

2024-04-12 04:26 UTC, reiji-h commented on apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
> +    setNavMaxWidth(pageControlsX - pagePathNavRef.current.getBoundingClientRect().x - 10);
setTimeout を使用して実装しました。

2024-04-12 11:20 UTC, merged