feat: Implementation to retrieve the existence of drafts in Yjs
weseek/growi pull request #8708
Opened 2024-04-11 05:37 UTC by miya

## Task
[#132775](https://redmine.weseek.co.jp/issues/132775) [v7][New Editor][collab] Editor で編集中またはドラフトが存在することを subnav から確認できる
┗ [#144055](https://redmine.weseek.co.jp/issues/144055) ドラフトが存在するかどうかを確認するためのロジック実装

2024-04-12 11:26 UTC, yuki-takei requested changes

2024-04-12 11:26 UTC, yuki-takei commented on apps/app/src/pages/[[...path]].page.tsx
> +  useHasYjsDraft(props.hasYjsDraft);
next page のレンダリング時に1度だけ初期化される設計では不足ではないか？
`Ctrl + S` での保存時とかに mutate されるはずでは？また、当該ページを閲覧中の他のユーザーも保存されたことを検知したら mutate しなければいけないのではないか？

next page のレンダリング時の初期化がタイミングとしてさほど重要ではないのなら、websocket 経由で値の変更をトリガーしたほうがいいのかもしれない。その検討をしてほしい。

2024-04-19 19:45 UTC, yuki-takei requested changes

2024-04-19 19:45 UTC, yuki-takei commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +  }, [mutateHasYjsDraft, socket]);
このコンポーネントはモード切替を行うボタンでしかないので、これらの責務を持つのは不適切

2024-04-19 19:45 UTC, yuki-takei commented on apps/app/src/server/service/yjs-connection-manager.ts
> +      .emit(SocketEventName.YjsUpdated, true);
この操作をここに書くのは違和感がある。socket-io.js 側でやる。

2024-04-22 10:23 UTC, miya commented on apps/app/src/server/service/socket-io.js
> +  }
複数の room に入れるような実装になっていたため、退出できるようにした

2024-04-22 10:23 UTC, miya commented on apps/app/src/server/service/yjs-connection-manager.ts
> +      .emit(SocketEventName.YjsUpdated, true);
修正しました

2024-04-22 10:23 UTC, miya commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +  }, [mutateHasYjsDraft, socket]);
`useYjsDraftEffect` を新設して DisplaySwitcher で呼び出す形式に修正しました。

2024-04-22 10:50 UTC, yuki-takei requested changes

2024-04-22 10:50 UTC, yuki-takei commented on apps/app/src/server/service/socket-io.js
> +          .emit(SocketEventName.YjsUpdated, true);
boolean ではなく `{ hasYjsDraft: true }` のような型を作ってそのオブジェクトを渡すようにしてください

2024-04-22 10:50 UTC, yuki-takei commented on apps/app/src/client/services/side-effects/yjs-draft.ts
> +  const { mutate: mutateHasYjsDraft } = useHasYjsDraft();
useHasYjsDraft を改修したい。
- 改名
    - currentPageId を自律的に読み取るなら `useCurrentPageYjsDraft` のような名前がいいと思う。
- `{ hasYjsDraft: true }` のようなメタデータ型を作ってそのオブジェクトを管理する

2024-04-22 12:00 UTC, miya commented on apps/app/src/server/service/socket-io.js
> +          .emit(SocketEventName.YjsUpdated, true);
修正しました

2024-04-22 12:00 UTC, miya commented on apps/app/src/client/services/side-effects/yjs-draft.ts
> +  const { mutate: mutateHasYjsDraft } = useHasYjsDraft();
修正しました

2024-04-23 11:24 UTC, merged