refs #144410: can specify otel config from config manager
weseek/growi pull request #8714
Opened 2024-04-12 03:19 UTC by skomma

* OpenTelemetry データの出力先を ConfigManager 経由で取得するように実装した
* コメントを英語に直した

2024-04-12 03:32 UTC, skomma commented on apps/app/src/server/crowi/opentelemetry.ts
> +    process.env.OTEL_SDK_ENABLED = this.crowi.configManager?.getConfig('crowi', 'instrumentation:enabled');
OpenTelemetry ライブラリ内で環境変数によって、無効化する機能がついている。
そのため、ConfigManager の基本方針(DB > env の優先度) に沿うと、`DB: true, env: false` のケースに意図しない動きになるため、このメソッドで `sdk.start()` を呼ぶ前に環境変数に書き込んでいる。

2024-04-12 11:13 UTC, yuki-takei requested changes

2024-04-12 11:13 UTC, yuki-takei commented on apps/app/src/server/crowi/opentelemetry.ts
> +        [SEMRESATTRS_SERVICE_INSTANCE_ID]: this.crowi.configManager?.getConfig('crowi', 'instrumentation:instanceId'),
configManager は crowi インスタンスから取得せず、export されている singleton instance をインポートしてください
タイミングの問題があるのであれば dynamic import する

2024-04-12 11:13 UTC, yuki-takei commented on apps/app/src/server/crowi/opentelemetry.ts
> +    process.env.OTEL_SDK_ENABLED = this.crowi.configManager?.getConfig('crowi', 'instrumentation:enabled');
上書きしたというメッセージを logger.info or logger.warn に吐いた方がいいな

2024-04-12 11:13 UTC, yuki-takei commented on apps/app/src/server/service/config-loader.ts
> +  },
GROWI で扱う環境変数の設計を再考したほうがいいと思う。

OpenTelemetry ライブラリ内で参照されるものをそのまま configManager で管理するのはやめたほうがいいんじゃないかな。

2024-04-15 07:00 UTC, skomma commented on apps/app/src/server/crowi/opentelemetry.ts
> +        [SEMRESATTRS_SERVICE_INSTANCE_ID]: this.crowi.configManager?.getConfig('crowi', 'instrumentation:instanceId'),
なおした

2024-04-15 07:01 UTC, skomma commented on apps/app/src/server/service/config-loader.ts
> +  },
[/資料/開発ガイドライン/ADR - Architecture Decision Record/OpenTelemetry 出力#decision-決定](https://dev.growi.org/6617428fce72715b879e9bda#decision-決定)

に書いた通り、現時点でわかっている有効化/無効化以外の値については、GROWI では余計な処理を実施しないようにした。

2024-04-15 07:02 UTC, skomma commented on apps/app/src/server/crowi/opentelemetry.ts
> +    process.env.OTEL_SDK_ENABLED = this.crowi.configManager?.getConfig('crowi', 'instrumentation:enabled');
なおした。
あと、`OTEL_SDK_ENABLED` ではなく `OTEL_SDK_DISABLED` だったので、それも修正した。

https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#general-sdk-configuration

2024-04-15 07:05 UTC, skomma commented on apps/app/src/server/crowi/opentelemetry.ts
> +      traceExporter: new OTLPTraceExporter(),
宛先は、SDK の環境変数から取得する形にした。

https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_endpoint

2024-04-15 07:05 UTC, skomma commented on apps/app/src/server/crowi/opentelemetry.ts
> +        exporter: new OTLPMetricExporter(),
宛先は、SDK の環境変数から取得する形にした。

https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_endpoint

2024-04-15 07:05 UTC, skomma commented on apps/app/src/server/crowi/opentelemetry.ts
> -      sampler: new TraceIdRatioBasedSampler(0.5),
sampler も環境変数から設定する形にした。

https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_traces_sampler

2024-04-16 20:26 UTC, merged