feat: implementions of announcement creation function
weseek/growi pull request #8715
Opened 2024-04-12 08:06 UTC by WNomunomu

2024-07-19 10:24 UTC, miya requested changes

2024-07-19 10:24 UTC, miya commented on apps/app/src/server/routes/apiv3/announcement.ts
> +    const activity = await crowi.activityService.createActivity(parametersForActivity);
add-activity middleware (/apps/app/src/server/middlewares/add-activity.ts) は使えないのかな？

2024-07-19 10:24 UTC, miya commented on apps/app/src/client/util/announcement-utils.ts
> +};
features/announcement ディレクトリに移した方が良さそう

2024-07-19 10:24 UTC, miya commented on apps/app/src/server/service/announcement.ts
> +module.exports = AnnouncementService;
features/announcement ディレクトリに移した方が良さそう

2024-08-06 05:05 UTC, WNomunomu commented on apps/app/src/server/routes/apiv3/announcement.ts
> +    const activity = await crowi.activityService.createActivity(parametersForActivity);
今回は使用するパラメータが多く、add-activity middlewareは使えなさそうです。

2024-08-06 05:05 UTC, WNomunomu commented on apps/app/src/server/routes/apiv3/announcement.ts
> +    const page = await Page.findById(params.pageId);
req.paramsではpageIdが正しく取得できなかったため、この形にしています。

2024-08-26 01:30 UTC, miya requested changes

2024-08-26 01:30 UTC, miya commented on apps/app/src/server/routes/apiv3/announcement.ts
> +    const page = await Page.findById(params.pageId);
クライアントのリクエスト方法がパスパラメーターで取得できるかたちになっていないのでは？
https://github.com/weseek/growi/pull/8715/files#diff-16e65c79c9018f437410fdf1211d572707905ec324e3b3129c795555aa364a5cR13

2024-08-26 01:30 UTC, miya commented on apps/app/src/server/routes/apiv3/announcement.ts
> +};
これも features ディレクトリで良さそう

2024-08-26 01:30 UTC, miya commented on apps/app/src/interfaces/announcement.ts
> +}
これも featues ディレクトリで良さそう

2024-09-09 06:57 UTC, WNomunomu commented on apps/app/src/interfaces/announcement.ts
> +}
こちらも移動しました。

2024-09-09 06:57 UTC, WNomunomu commented on apps/app/src/server/routes/apiv3/announcement.ts
> +    const page = await Page.findById(params.pageId);
/:id を用いることで、pageIdをパスパラメータで取得できるようにしました。

2024-09-10 07:08 UTC, miya commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    ],
- sender とか pageId など ObjectId でとるものは isMongoId() をつけよう
- バリデーションに失敗した時にクライアントにエラーメッセージを返却するために .withMessage() をつけよう

2024-09-10 07:08 UTC, miya commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    const { id: pageId } = req.params;
ごめん、そもそも req.body で pageId をとっているのであればそれを使うでよさそう

2024-09-12 08:05 UTC, WNomunomu commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    const { id: pageId } = req.params;
req.bodyを採用しました。

2024-09-12 08:06 UTC, WNomunomu commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    ],
validatorに設定を追加させていただきました。

2024-09-23 22:56 UTC, miya approved these changes

2024-09-24 11:24 UTC, yuki-takei requested changes

2024-09-24 11:24 UTC, yuki-takei commented on apps/app/src/features/announcement/client/utils/announcement-utils.ts
> +    toastError(err);
toastr の表示は view の責務
このユーティリティは DAO/サービス層に分類されるので不適切

2024-09-24 11:24 UTC, yuki-takei commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +  router.post('/doAnnouncement', loginRequiredStrictly, validators.doAnnouncement, async(req: CrowiRequest) => {
URL は kebab-case で

2024-09-24 11:24 UTC, yuki-takei commented on apps/app/src/features/announcement/server/service/announcement.ts
> +module.exports = AnnouncementService;
ExternalAccountService を参考に、singleton instance をこのモジュールで export するようにしてください

2024-09-24 11:24 UTC, yuki-takei commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    crowi.announcementService.doAnnounce(activity, page, params);
- announcementService は crowi 経由で取得するのではなくここで直接動的 import する
- try-catch してください
    - エラーの場合はログ出力して 500 status

2024-09-24 11:24 UTC, yuki-takei commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    const page = await Page.findById(pageId);
- req.user がアクセスできるページでないといけないので、取得はそれを考慮しているメソッドを使ってください
- ページが見つからなかった場合は 4xx 系エラーを返す

2024-09-24 11:24 UTC, yuki-takei commented on apps/app/src/features/announcement/server/models/announcement.ts
> +  const announcement = await this.create(parameters) as IAnnouncement;
as を使わず記述してください

2024-09-24 11:24 UTC, yuki-takei commented on apps/app/src/features/announcement/server/service/announcement.ts
> +  ): Promise<void> => {
private を付けよう

2024-09-24 11:24 UTC, yuki-takei commented on apps/app/src/features/announcement/server/service/announcement.ts
> +    await Announcement.bulkWrite(operation);
bulkWrite しないといけない理由ある？

2024-09-24 11:24 UTC, yuki-takei commented on apps/app/src/server/routes/login.js
> +      notificationTargetUsers.push(...adminUsers);
これは現存する何かしらのバグの修正？

2024-09-29 14:31 UTC, WNomunomu commented on apps/app/src/features/announcement/server/service/announcement.ts
> +  ): Promise<void> => {
private method にしました。

2024-09-29 14:40 UTC, WNomunomu commented on apps/app/src/features/announcement/server/service/announcement.ts
> +module.exports = AnnouncementService;
singleton instanceをexportするようにしました。

2024-09-29 14:41 UTC, WNomunomu commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +  router.post('/doAnnouncement', loginRequiredStrictly, validators.doAnnouncement, async(req: CrowiRequest) => {
こちら kebab-case にしました。

2024-09-29 14:50 UTC, WNomunomu commented on apps/app/src/features/announcement/server/models/announcement.ts
> +  const announcement = await this.create(parameters) as IAnnouncement;
as を消去し、修正しました。

2024-11-16 07:17 UTC, WNomunomu commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    crowi.announcementService.doAnnounce(activity, page, params);
直接動的 import する形に変更しました。
また、エラーの場合はログ出力、500 status を出すように変更しました。

2024-11-22 02:05 UTC, WNomunomu commented on apps/app/src/features/announcement/server/service/announcement.ts
> +    await Announcement.bulkWrite(operation);
今回は operation が1つだけなので、Model.bulkwrite ではなく Model.create に変更しました。

2024-11-22 02:06 UTC, WNomunomu commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    const page = await Page.findById(pageId);
findByIdAndViewer メソッドを使用しました。
ページの閲覧が制限されている場合（403）、ページが存在しない場合（404）でも同じように page が null になるので、これらは分けずに、400 エラーを返すようにしました。

2024-11-22 02:07 UTC, WNomunomu commented on apps/app/src/features/announcement/client/utils/announcement-utils.ts
> +    toastError(err);
utils 内で try-catch をやめて、apiv3Post のみにしました。
toastr を表示する場合は、この createAnnouncement 関数を呼び出す側の責務にしようと思います。

2024-11-22 04:32 UTC, WNomunomu commented on apps/app/src/server/routes/login.js
> +      notificationTargetUsers.push(...adminUsers);
はい。こちら現存するバグの修正です。
今回アナウンス機能の実装をしている中で、新規ユーザー作成リクエストを行ったときにadmin への通知が行われないことに気づき、修正しました。

2024-11-22 12:45 UTC, yuki-takei requested changes

2024-11-22 12:45 UTC, yuki-takei commented on apps/app/src/features/announcement/client/utils/announcement-utils.ts
> +import { toastError } from '../../../../client/util/toastr';
不要な import 文は削除してください

2024-11-22 12:45 UTC, yuki-takei commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +import { announcementService } from '../../server/service/announcement';
router の実装の中で動的に import してください。

`await import('...')`

2024-11-22 12:45 UTC, yuki-takei commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    }
> ページの閲覧が制限されている場合（403）、ページが存在しない場合（404）でも同じように page が null になるので、これらは分けずに、400 エラーを返すようにしました。

それではだめです。

page が見つからなかったら、更に DB に実態が存在するかをチェックして 400 not found か 403 forbidden なのかを場合分けしてください。

2024-11-22 12:45 UTC, yuki-takei commented on apps/app/src/features/announcement/server/models/announcement.ts
> +    type: String,
これはなぜ String にしたの？

2024-11-22 12:45 UTC, yuki-takei commented on apps/app/src/server/routes/login.js
> +      notificationTargetUsers.push(...adminUsers);
https://github.com/weseek/growi/pull/9434

こちらの PR で同様の修正をしたので取り込んでください

2024-11-23 07:04 UTC, WNomunomu commented on apps/app/src/features/announcement/client/utils/announcement-utils.ts
> +import { toastError } from '../../../../client/util/toastr';
こちら削除しました。

2024-11-23 07:04 UTC, WNomunomu commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +import { announcementService } from '../../server/service/announcement';
動的 import に変更しました。

2024-11-23 07:05 UTC, WNomunomu commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    }
`const isAnnouncedPageExist = !!(await Page.findById(pageId));`
を用いた条件分岐を追加しました。

2024-11-23 07:25 UTC, WNomunomu commented on apps/app/src/features/announcement/server/models/announcement.ts
> +    type: String,
PageModel.findByIdAndViewer の引数の pageId が ObjectIdLike 型を指定されていたので、Ref<IPage> から string に変えました。
しかし、その必要がないと分かったのでこの変更は revert しました。

2024-11-25 09:09 UTC, yuki-takei requested changes

2024-11-25 09:09 UTC, yuki-takei commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +        return res.apiv3Err(new ErrorV3(`Page('${pageId}') is not forbidden`), 403);
not forbidden はおかしい

2024-11-25 09:09 UTC, yuki-takei commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    }
Page モデルをインスタンス化するコストは無駄なので、
`await Page.count({ _id: pageId }) > 0` のようにしてください

2024-11-25 09:09 UTC, yuki-takei commented on apps/app/src/features/announcement/server/models/announcement.ts
> +};
このメソッド使われていないので消そう

2024-11-25 12:24 UTC, WNomunomu commented on apps/app/src/features/announcement/routes/apiv3/announcement.ts
> +    }
モデルをインスタンス化せずに、isAnnouncedPageExist を得られるようにしました。

2024-11-25 12:24 UTC, WNomunomu commented on apps/app/src/features/announcement/server/models/announcement.ts
> +};
消去しました。

2024-11-26 07:52 UTC, yuki-takei approved these changes

2024-11-26 08:05 UTC, merged