fix: Drawio not available with GROWI slides
weseek/growi pull request #8725
Opened 2024-04-16 06:06 UTC by reiji-h

# Summary
`slide: true` を使用した際に drawio が図として表示されない問題の修正

# Task
- https://redmine.weseek.co.jp/issues/144087
  - https://redmine.weseek.co.jp/issues/144091

# Issue
https://github.com/weseek/growi/issues/8662

2024-04-17 09:31 UTC, yuki-takei requested changes

2024-04-17 09:31 UTC, yuki-takei commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +import { hasEnabledSlideTypes } from '@growi/presentation/src/services';
この参照の仕方は production build で動かなくなる

2024-04-17 09:31 UTC, yuki-takei commented on packages/presentation/src/services/has-enabled-slide-types.ts
判定部分は自作するメリットがなさそうなので戻す

2024-04-17 09:31 UTC, yuki-takei commented on apps/app/src/components/Page/RevisionRenderer.tsx
RevisionRenderer は Comment や CustomSidebar からも使われているので、このコンポーネントに SlideViewer との切り替え機能を持たせるのは不適切

2024-04-23 06:53 UTC, reiji-h commented on packages/presentation/src/services/has-enabled-slide-types.ts
こちら戻しました

2024-04-23 06:55 UTC, reiji-h commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +import { hasEnabledSlideTypes } from '@growi/presentation/src/services';
`@growi/presentation` の参照の方式だと、SSR 周りの関係の影響か動作できなかったので、一旦 apps/app 側に marp か growi-slide か判定するための関数を持ってきました。(RevisionRenderer で切り替えする場合の話であり、後で変更の可能性あり)

2024-04-23 11:38 UTC, yuki-takei commented on apps/app/src/components/Page/RevisionRenderer.tsx
2がよいです

2024-04-23 11:41 UTC, yuki-takei commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +import { hasEnabledSlideTypes } from '@growi/presentation/src/services';
monorepo のメリットが失われるのでこれはなんにせよ元に戻す必要がある
packages/presentation 内はサーバーサイドからは利用しないファイルしか存在しないはずなので、サーバーサイドから import している箇所があるんだとすればそちらの問題

2024-04-30 08:54 UTC, reiji-h commented on apps/app/src/components/Page/RevisionRenderer.tsx
2 で実装しました。
もともとスライドが使用可能だった rendererOptions は useViewOpitons と usePreviewOptions であり、前者は PageView.tsx と ShareLinkPageView.tsx が使用、後者は最終的に Preview.tsx のみにおいて使用されていました。よってこれら３つのファイルで切り替えをするようにしました。
ですが、PageView.tsx と ShareLinkPageView.tsx についてはこれらから直接 @growi/presentation を使用するとサーバーサイドからの import になるのかエラーが起こるので、dynamic import するコンポーネントを噛ます形にしています。

2024-04-30 08:57 UTC, reiji-h commented on apps/app/src/components/Page/RevisionRenderer.tsx
> +import { hasEnabledSlideTypes } from '@growi/presentation/src/services';
@growi/presentation 内に戻しました。
[こちら](https://github.com/weseek/growi/pull/8725#discussion_r1584391755)でも発言しましたが、同じ問題は起きるので、dynamic import で対処しています。

2024-04-30 10:38 UTC, yuki-takei requested changes

2024-04-30 10:38 UTC, yuki-takei commented on apps/app/src/components/Page/PageView.tsx
> +const ViewRenderer = dynamic(() => import('./ViewRenderer').then(mod => mod.ViewRenderer), { ssr: false });
ここで dynamic import してしまうと本文が SSR されなくなるので NG

2024-04-30 10:38 UTC, yuki-takei commented on apps/app/src/components/ReactMarkdownComponents/SlideViewer.tsx
ReactMarkdownComponents ディレクトリからは外に出す方がいいと思う

2024-04-30 10:38 UTC, yuki-takei commented on apps/app/src/components/ShareLinkPageView.tsx
> +const ViewRenderer = dynamic(() => import('./Page/ViewRenderer').then(mod => mod.ViewRenderer), { ssr: false });
ここで dynamic import してしまうと本文が SSR されなくなるので NG

2024-05-07 05:09 UTC, reiji-h commented on apps/app/src/components/ReactMarkdownComponents/SlideViewer.tsx
一つ上の階層に配置しました。

2024-05-07 05:26 UTC, reiji-h commented on apps/app/src/components/Page/PageView.tsx
> +const ViewRenderer = dynamic(() => import('./ViewRenderer').then(mod => mod.ViewRenderer), { ssr: false });
確かに RevisionRenderer は SSR したかったので、SlideRenderer という dynamic import するコンポーネントを新たに作成し、それの children として RevisionRenderer を渡すようにしました。SlideRenderer 内ではスライドにするかどうかの判定を行いスライドにするなら SlideViewer を使用し、そうでなければ children (この場合 RevisionRenderer )を返すようにしています。

参考：https://qiita.com/kay-adamof/items/e3767e17e5be0b41faa8#2---server-component-%E3%82%92%E7%9B%B4%E6%8E%A5%E3%83%8D%E3%82%B9%E3%83%88%E3%81%97%E3%81%AA%E3%81%84

2024-05-07 05:27 UTC, reiji-h commented on apps/app/src/components/ShareLinkPageView.tsx
> +const ViewRenderer = dynamic(() => import('./Page/ViewRenderer').then(mod => mod.ViewRenderer), { ssr: false });
確かに RevisionRenderer は SSR したかったので、SlideRenderer という dynamic import するコンポーネントを新たに作成し、それの children として RevisionRenderer を渡すようにしました。SlideRenderer 内ではスライドにするかどうかの判定を行いスライドにするなら SlideViewer を使用し、そうでなければ children (この場合 RevisionRenderer )を返すようにしています。

参考：https://qiita.com/kay-adamof/items/e3767e17e5be0b41faa8#2---server-component-%E3%82%92%E7%9B%B4%E6%8E%A5%E3%83%8D%E3%82%B9%E3%83%88%E3%81%97%E3%81%AA%E3%81%84

2024-05-07 18:23 UTC, yuki-takei requested changes

2024-05-07 18:23 UTC, yuki-takei commented on apps/app/src/components/Page/PageView.tsx
> +          </SlideRenderer>
これでは SSR されないのでだめです
ブラウザのネットワークタブで、レスポンス中に RevisionRenderer でレンダリングされるべき HTML が入っているかどうかを確認してください。

2024-05-07 18:23 UTC, yuki-takei commented on apps/app/src/components/ShareLinkPageView.tsx
> +        </SlideRenderer>
こちらも PageView.tsx と同様 SSR されないので NG

2024-05-13 09:16 UTC, merged