imprv: Truncate page path title in editor
weseek/growi pull request #8726
Opened 2024-04-16 08:48 UTC by reiji-h

# Summary
- Editor におけるページタイトル及びページパスが長かったとき正常に Truncate されるようにする。
  - 正常とは、window サイズによらず 上記2つのコンポーネントがそれ以外のコンポーネントに被らない状態である。
- ページタイトルが Truncate 不要な長さのときには、input も相応の幅を取るように修正。

# Task
- https://redmine.weseek.co.jp/issues/143963
  - https://redmine.weseek.co.jp/issues/144050

2024-04-17 09:43 UTC, yuki-takei requested changes

2024-04-17 09:43 UTC, yuki-takei commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +              d-flex align-items-center justify-content-end px-2 px-sm-3 px-md-4 ps-0 ps-sm-0 ps-md-0 py-1 gap-2 gap-md-4 d-print-none
spacing 関連のクラスがぐちゃぐちゃになっている
例えば px-2 と ps-0 は排他だろう

2024-04-17 09:43 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PageHeader.tsx
> +    return pageControlsX - pageHeaderRef.current.getBoundingClientRect().x - 10;
300, 10 といったマジックナンバーはなるべく避ける
どうしても書く必要があるならコード内コメントも一緒に

2024-04-17 09:43 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PagePathHeader.module.scss
> +  }
ストーリーのスコープ外ではないか

2024-04-17 09:43 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PageTitleHeader.module.scss
> +  }
ストーリーのスコープ外ではないか

2024-04-17 09:43 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PageTitleHeader.tsx
> +      <div className="page-title-header-input me-1 d-inline-block overflow-x-scroll">
page-title-header-input というクラスは不要ではないか

2024-04-17 09:44 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PagePathHeader.tsx
> +        // id="grw-page-path-header-container"
対応されていない

2024-04-23 04:08 UTC, reiji-h reviewed
test

2024-04-23 11:35 UTC, yuki-takei requested changes

2024-04-23 11:35 UTC, yuki-takei commented on apps/app/src/components/PageHeader/PagePathHeader.module.scss
> +  }
- その情報は重要なのでコードコメントに残してください
- `-webkit-scrollbar` は不要なのでは？
    - https://caniuse.com/mdn-css_properties_scrollbar-width によれば最新ブラウザは対応している
    - Next.js による PostCSS もある
        - https://nextjs.org/docs/pages/building-your-application/configuring/post-css

2024-04-30 06:09 UTC, reiji-h commented on apps/app/src/components/PageHeader/PagePathHeader.module.scss
> +  }
コメントを残し、 webkit を削除しました。

2024-04-30 06:33 UTC, merged