Feat/144301 144437 select unrelated group inheritance on normal child page create
weseek/growi pull request #8728
Opened 2024-04-16 15:52 UTC by arafubeatbox

2024-04-16 15:56 UTC, arafubeatbox commented on apps/app/src/interfaces/page-grant.ts
> +export type IResCurrentGrantData = {
今のストーリーとは直接関係ないが、https://redmine.weseek.co.jp/issues/140571 で API を /page/is-grant-normalized から /page/grant-data で変えたことにより、type の名前をそれに合わせて変更

2024-04-16 16:12 UTC, arafubeatbox commented on apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
> +    }
若干複雑な実装なのですが、isNonUserRelatedGroupsGranted が true の場合は GrantedGroupsInheritanceSelectModal を表示し、GrantedGroupsInheritanceSelectModal の中でグループ継承のオプションを選択後、ここの処理に再度リクエストを送るように実装しました。

再度リクエストを送るときは onlyInheritUserRelatedGrantedGroups が存在しているので、この下の通常の処理が走ります。

2024-04-16 16:15 UTC, arafubeatbox commented on apps/app/src/client/services/create-page/use-create-template-page.ts
> +        path: normalizePath(`${currentPagePath}/${label}`), parentPath: currentPagePath, wip: false, origin: Origin.View,
use-create-page-and-transit で isNonUserRelatedGroupsGranted を取得するために、parentPath を明示的に指定しました。これが指定されても createPage の処理内容に変化はない認識です。

2024-04-16 16:16 UTC, arafubeatbox commented on apps/app/src/components/Sidebar/PageCreateButton/hooks/use-create-todays-memo.tsx
> +      },
use-create-page-and-transit で isNonUserRelatedGroupsGranted を取得するために、parentPath を明示的に指定しました。これが指定されても createPage の処理内容に変化はない認識です。

2024-04-16 16:21 UTC, arafubeatbox commented on apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
> +    }
同じ内容のリクエスト (+ 継承するかしないかの情報) で再度リクエストするために、modal を開くときに params と opts を渡しています。

2024-04-16 16:29 UTC, arafubeatbox commented on apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
> +    }
数箇所に記載されているページ作成ロジックの箇所それぞれで別々にモーダルを管理する処理を記述したくなかったため、ここで実装しています。
その結果、このような実装になりました。

2024-04-16 22:00 UTC, yuki-takei requested changes

2024-04-16 22:00 UTC, yuki-takei commented on apps/app/src/stores/modal.tsx
> +    close: () => swrResponse.mutate({ isOpened: false }),
open, close 共に useCallback を使って作成してください

2024-04-16 22:00 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/index.ts
> +    }
page が findByPathAndViewer で見つからず null だった場合ってカバーされてる？
その場合は明示的に 400 を返したい。その他の予測不可能な要因で catch に落ちることもあるのでその場合は 500 でもよい。

2024-04-16 22:00 UTC, yuki-takei commented on apps/app/src/client/services/page-operation.ts
> +export const nonUserRelatedGroupsGranted = async(path: string): Promise<NonUserRelatedGroupsGrantedResponse> => {
closure の名前は動詞で始まるように

2024-04-16 22:00 UTC, yuki-takei commented on apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
> +    }
あまり良い実装とは思えない。

- 少なくともページの存在チェックより後に持ってくる必要があるんじゃないかな
    - ページが存在していない場合に限り nonUserRelatedGroupsGranted を呼んでモーダルを開く・開かないという場合分けをする
- `isNonUserRelatedGroupsGranted` が false の場合は親子関係的に即ページ作成で問題ないケースなので、finally で onTerminated を呼んではいけないんじゃない？

2024-04-16 22:00 UTC, yuki-takei commented on apps/app/src/components/GrantedGroupsInheritanceSelectModal.tsx
> +          </div>
キャンセルが必要な気がする

2024-04-16 22:00 UTC, yuki-takei commented on apps/app/src/components/GrantedGroupsInheritanceSelectModal.tsx
> +      </ModalHeader>
ヘッダーには bg-primary を付けないように

[XD 参照](https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/7718c9a0-ec13-4962-a697-9db777a195df/)

![image](https://github.com/weseek/growi/assets/1638767/5d91c51f-ea68-4f09-9361-66f93dedf208)

2024-04-18 11:34 UTC, arafubeatbox commented on apps/app/src/components/GrantedGroupsInheritanceSelectModal.tsx
> +          </div>
コメント削除モーダルなどを参考にしました。
![image](https://github.com/weseek/growi/assets/32846231/72f8090f-5933-4e80-9dec-1f4bc5ed60d3)

2024-04-19 09:44 UTC, arafubeatbox commented on apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
> +    }
上記対応しました。
また、再度 createAndTransit にリクエストするのではなく、createAndTransit のメインの処理を callback 関数として GrantedGroupsInheritanceSelectModal に渡し、「ページ作成」ボタンが押されたら呼ばれるようにしました。

2024-04-19 09:49 UTC, arafubeatbox commented on apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
> +          throw err;
「今日のメモ」作成は「メモ」という親ページが存在しなくても作成できるようにしなければいけないので、親ページが page_unreachable_or_empty となっていても、エラーを無効にするようにしました。

unreachable の場合、今まで通り後続の createAndTransit でエラーが出るイメージです。

2024-04-19 20:23 UTC, yuki-takei requested changes

2024-04-19 20:23 UTC, yuki-takei commented on apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
> +        onAborted?.();
onAborted にはモーダルを閉じる処理などが入ってくる想定なので、catch 時は呼ばない方がいい
(名前がよくないのかもしれないが)

2024-04-19 20:23 UTC, yuki-takei commented on apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
> +        onAborted?.();
onAborted にはモーダルを閉じる処理などが入ってくる想定なので、catch 時は呼ばない方がいい
(名前がよくないのかもしれないが)

2024-04-25 10:54 UTC, yuki-takei requested changes

2024-04-25 10:54 UTC, yuki-takei commented on apps/app/src/server/service/page-grant.ts
> +      return !userRelatedGroupIds.includes(group.item);
細かい書き方の話だけど、`getIdForRef` で ID を取得してから `return !userRelatedGroupIds.includes` を使って if block を消そう

2024-04-25 11:01 UTC, yuki-takei commented
加えて、PageEditorModeManager から createAndTransit を呼ぶ際にも parentPath は必要なのではないだろうか？
ブラウザから適当に URL を打ち込んで not found ページへ遷移して Edit ボタンを押下したときに、親ページの grant を見て GrantedGroupsInheritanceSelectModal を表示させる必要がある。

2024-04-26 07:51 UTC, arafubeatbox commented
> 加えて、PageEditorModeManager から createAndTransit を呼ぶ際にも parentPath は必要なのではないだろうか？
API を新規作成し、存在する nearestAncestor を取得し、それを parentPath に設定するようにしました。
https://github.com/weseek/growi/pull/8728/commits/d8b0b8ac5dcdcb93d860861eb7fc9d27831d17d5

メモページの作成において、parentPath をこの API を使って判断するようにリファクタリングしました。
https://github.com/weseek/growi/pull/8728/commits/e5822fcea61a136290cd2fef9fc2987551dd2465

2024-04-26 07:52 UTC, arafubeatbox commented on apps/app/src/server/service/page-grant.ts
> +      return !userRelatedGroupIds.includes(group.item);
getUserRelatedGrantedGroupsSyncronously の方も修正しました。

2024-04-30 08:55 UTC, yuki-takei requested changes

2024-04-30 08:55 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/index.ts
> +      console.log('ここ', path);
console.log は消してください

2024-04-30 08:55 UTC, yuki-takei commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +        },
クライアントからは non empty だろうが non empty ではなかろうが parentPath を指定できてよい
`nonEmptyClosestAncestor?.path` にあたるものを取得して挙動を変えるのはサーバーサイドの責務

`routes/apiv3/page/create-page.ts` の `determinePath` で決定する

そのように改修すると、`/page/non-empty-closest-ancestor` は消えるのではないか？

2024-05-02 04:29 UTC, arafubeatbox commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +        },
ご提案ありがとうございます。
parentPath が empty で問題となっていたのは、create-page ではなく、`/page/non-user-related-groups-granted` で
す。
そちらで、指定されたページが存在しない場合は、nonEmptyClosestAncestor を取得するように変更しました。

https://github.com/weseek/growi/pull/8728/commits/4cacb600e5bef4054d801edb4ee2f6ba0e7b8c61

2024-05-02 11:11 UTC, yuki-takei requested changes

2024-05-02 11:11 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/index.ts
> +          return res.apiv3Err(new ErrorV3('Page and ancestor does not exist.', 'page_does_not_exist'), 400);
`findNonEmptyClosestAncestor` を呼んだら必ず page ドキュメントは手に入るはずなので、仮にこのブロックに入るとしたら 400 ではなく 5xx 系な気がするね

2024-05-02 12:59 UTC, arafubeatbox commented
PageEditorModeManager で parentPath を path string から作成する時、parentPath が '/' にならなければならない場合、'' となってしまっていたバグを修正しました。
https://github.com/weseek/growi/pull/8728/commits/6d99810e4e011d22aae2b1408f2c081bd6365ca7

2024-05-07 17:55 UTC, merged

2024-05-07 18:00 UTC, yuki-takei commented on apps/app/src/components/Navbar/PageEditorModeManager.tsx
> +      parentPath = parentPath === '' ? '/' : parentPath;
`import { normalizePath } from '@growi/core/dist/utils/path-utils';`
とかその周辺のユーティリティメソッドを使ったらもうちょっとすっきり書けないかな