fix: EditingUserList shows user icons that are not currently writing
weseek/growi pull request #8752
Opened 2024-04-23 10:00 UTC by miya

## Task
[#141939](https://redmine.weseek.co.jp/issues/141939) [v7] View 画面を開いている時にそのユーザーが Editor 画面の執筆中アイコンに表示されてしまう
┗ [#144321](https://redmine.weseek.co.jp/issues/144321) 修正

2024-04-24 06:16 UTC, miya reviewed
## 症状と原因
Yjs のドラフトや awareness は Editor を開くことによって作成されるという前提がある。

PageEditor は LazyRenderer によって Editor mode になった時に遅延ロードされる。一度でも Editor mode になった場合、View mode に変更しても PageEditor は Dom に残り続ける。
https://github.com/weseek/growi/blob/dd696bd8c66527373ab3ce4dadcb53fad6f62f80/apps/app/src/components/Page/DisplaySwitcher.tsx#L36-L41

そのため以下のようなケースで /page-b に View mode で遷移した時に、ドラフトが作成されたり awareness が作成されてしまったりする。

1. /page-a に遷移 (View mode)
2. Editor mode に変更
3. View mode に変更
4. /page-b に遷移 (View mode)

## 解決策
useCollaborativeEditorMode の中で Editor mode を考慮するようにして、View mode の時は yjs の socket に接続しないようにした。これにより他ページへの遷移に加え、View mode に切り替えた時に  awareness を destroy するように改修した。

2024-04-25 09:09 UTC, yuki-takei requested changes

2024-04-25 09:09 UTC, yuki-takei commented on packages/editor/src/stores/use-collaborative-editor-mode.ts
軽くリファクタをお願いします

- isEditorMode は isEnabled: boolean にする
- useEffect の第一引数に直にメソッド実装を書く
    - 現状の実装だと、cleanupYDoc 等はたぶん rerendering 時に再定義されてしまうので(deps の働きで実行はされないと思うけど)

2024-04-25 09:43 UTC, miya commented on packages/editor/src/stores/use-collaborative-editor-mode.ts
リファクタしました

2024-04-25 09:46 UTC, miya commented on packages/editor/src/stores/use-collaborative-editor-mode.ts
修正しました。

2024-04-25 09:53 UTC, merged