fix: An error occurred during user activation via email
weseek/growi pull request #8767
Opened 2024-04-26 11:02 UTC by maeshinshin

## Task
[#144137](https://redmine.weseek.co.jp/issues/144137): ユーザー登録時のメール認証」を有効時に「Activation」画面で「作成」ボタンを押下しても反応しない件の修正
┗ [#144368](https://redmine.weseek.co.jp/issues/144368) 実装

## Demo

![Demo](

https://github.com/weseek/growi/assets/106868314/c0fe0eb5-c789-471a-96bf-537f457e5838

)

2024-04-30 02:52 UTC, miya requested changes

2024-04-30 02:52 UTC, miya commented on apps/app/src/pages/user-activation.page.tsx
> +  const req: CrowiReq & CrowiRequest = context.req as CrowiReq & CrowiRequest;
`crowi` という型は既に `CrowiRequest` の中にあるので、`CrowiReq` よりも `ReqWithUserRegistrationOrder` を import して使った方が良さそうだね。

Type Assertion していれば型推論してくれそうだから Type annotation はなくても良さそう。

2024-04-30 03:29 UTC, maeshinshin commented on apps/app/src/pages/user-activation.page.tsx
> +  const req: CrowiReq & CrowiRequest = context.req as CrowiReq & CrowiRequest;
修正しました。

2024-04-30 03:59 UTC, miya requested changes

2024-04-30 03:59 UTC, miya commented on apps/app/src/server/routes/user-activation.ts
> +export type CrowiReq = ReqWithUserRegistrationOrder & {
不要になった export は消そう

2024-04-30 04:12 UTC, miya requested changes

2024-04-30 04:12 UTC, miya commented on apps/app/src/pages/user-activation.page.tsx
> +    const userRegistrationOrder = req.userRegistrationOrder as unknown as IUserRegistrationOrder;
`as unknown as IUserRegistrationOrder` も不要になると思う

2024-05-01 07:36 UTC, maeshinshin commented on apps/app/src/server/routes/user-activation.ts
> +export type CrowiReq = ReqWithUserRegistrationOrder & {
修正しました。

2024-05-01 07:36 UTC, maeshinshin commented on apps/app/src/pages/user-activation.page.tsx
> +    const userRegistrationOrder = req.userRegistrationOrder as unknown as IUserRegistrationOrder;
修正しました。

2024-05-01 09:38 UTC, miya approved these changes

2024-05-01 20:55 UTC, yuki-takei commented
fix #8510

2024-05-01 20:55 UTC, merged