Feat/78037 144924 download bulk export from in app notification be
weseek/growi pull request #8770
Opened 2024-04-27 10:38 UTC by arafubeatbox

2024-04-27 10:46 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/interfaces/page-bulk-export.ts
> -  expireAt: Date, // the date at which downloading of result expires
扱いやすくするために、PageBulkExportResult を消し、PageBulkExportJob から attachment に直接アクセスできるようにしました。

それぞれの expireAt については、
- 元々 PageBulkExportJob.expireAt だった情報: PageBulkExportJob.createdAt + (jobExpireTimeLength 的なもの)
- 元々 PageBulkExportResult.expireAt だった情報: PageBulkExportResult.completedAt + (downloadExpireTimeLength 的なもの)
にしようかなと思っています。

2024-04-29 14:24 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/routes/apiv3/page-bulk-export.ts
> +      await pageBulkExportService?.bulkExportWithBasePagePath(path, req.user, activityParameters);
multipart upload 開始前のエラーを catch するために await

2024-04-29 14:27 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> +      throw err;
handleExportError は multipart upload 開始後のエラーハンドリングに限定し、開始前のエラーはメソッド呼び出し元で処理してもらう。

2024-04-29 14:48 UTC, arafubeatbox commented on apps/app/src/interfaces/activity.ts
> +const ACTION_PAGE_BULK_EXPORT_FAILED = 'PAGE_BULK_EXPORT_FAILED';
export の "Result" を Activity として処理するのは少し違和感がありますが、Activity を通じて InAppNotification を出す仕組みのようだったので、一旦ここに追加してみました。

2024-04-29 15:20 UTC, arafubeatbox commented on apps/app/src/server/models/attachment.ts
> +) {
fileStream はメソッド内で使用されていなかったので取り除きました。

2024-04-29 15:43 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> +  async bulkExportWithBasePagePath(basePagePath: string, currentUser, activityParameters: ActivityParameters): Promise<void> {
主な改修内容:
- export の成功/失敗を通知するコードを追加
    - 実行の流れ:
        1. export 開始後に PageBulkExportJob を作成
        1. PageBulkExportJob に subscribe
        1. 実行が成功・失敗したら Activity を作成
        1. Activity 作成に伴って activityEvent によって InAppNotification が作成される
- PageBulkExportJob に紐づける Attachment を作成

2024-04-30 10:14 UTC, yuki-takei requested changes

2024-04-30 10:14 UTC, yuki-takei commented on apps/app/src/server/service/pre-notify.ts
> +        : subscribedUsers.filter(item => (item.toString() !== actionUser._id.toString()));
特定の種類の SupportedTargetModel に特化した処理がこのファイルに記述されるのは避けなければならない。
notificationTargetUsers への追加は、引数で渡す `getAdditionalTargetUsers?: GetAdditionalTargetUsers` で行う。

2024-05-02 02:56 UTC, arafubeatbox commented on apps/app/src/server/service/pre-notify.ts
> +        : subscribedUsers.filter(item => (item.toString() !== actionUser._id.toString()));
対応しました。
https://github.com/weseek/growi/pull/8770/commits/c3bd7179236b1c79c5ffa1b523ef5a147285a5d9

2024-05-02 10:26 UTC, merged