fix: Do not insert initial value when input is empty in editor
weseek/growi pull request #8773
Opened 2024-04-30 07:30 UTC by miya

## Task
[#126535](https://redmine.weseek.co.jp/issues/126535) [v7][New Editor][autosave] 明示的なページの保存でオートセーブリビジョンが自動で削除される
┗ [#130798](https://redmine.weseek.co.jp/issues/130798) 空文字にしたときに initialValue が入らないようにする

2024-05-21 06:53 UTC, miya commented on apps/app/src/components/PageEditor/PageEditor.tsx
> +  const [markdownToPreview, setMarkdownToPreview] = useState<string>(codeMirrorEditor?.getDoc() ?? '');
- markdownToPreview の初期値にエディターで入力中の文字列を入れるようにした
- ドラフトが空文字列の時に CodeMirrorEditorMain に渡す onChange がトリガーされたかったためこのような改修を行なった

2024-05-21 11:16 UTC, yuki-takei requested changes

2024-05-21 11:16 UTC, yuki-takei commented on apps/app/src/server/service/yjs-connection-manager.ts
> +    if (persistedCodeMirrorText === '' && currentCodeMirrorText === '' && initialValue != null) {
getYdoc() や getText で得られるインスタンスにはそれなりに多くの情報が入っているように見える。
toString() した結果だけをもって判定しようとするから融通が利かないのでは？

2024-05-23 02:51 UTC, miya commented on apps/app/src/server/service/yjs-connection-manager.ts
> +    if (clientsSize === 0) {
Ydoc の初期化後に何らかの操作を行うことにより store.clients.size が増えていく

## 参考
https://speakerdeck.com/kentomoriwaki/wakatutaqi-ninareru-crdt-woshi-tutagong-tong-bian-ji?slide=22

2024-05-23 02:52 UTC, miya commented on apps/app/src/server/service/yjs-connection-manager.ts
> +    if (persistedCodeMirrorText === '' && currentCodeMirrorText === '' && initialValue != null) {
こちらで解決しました
https://github.com/weseek/growi/pull/8773#discussion_r1610897279

2024-05-24 02:13 UTC, merged