Imprv: behavior of dropdown toggle in 'Recent Changes' sidebar
weseek/growi pull request #8782
Opened 2024-05-01 12:23 UTC by maeshinshin

## Task
[#141636](https://redmine.weseek.co.jp/issues/141636): サイドバー「最新の変更」の三点リーダー内ドロップダウンのトグル押下後の挙動の修正
┗ [#145347](https://redmine.weseek.co.jp/issues/145347) 実装

## Demo
![demo](https://github.com/weseek/growi/assets/106868314/855994c3-9cb4-4c02-95bb-179c8f4de71d)

2024-05-02 11:00 UTC, yuki-takei requested changes

2024-05-02 11:00 UTC, yuki-takei commented on apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
> +      <UncontrolledButtonDropdown className="me-1" isOpen={dropdownOpen} toggle={handleDropdownToggle}>
isOpen を制御するのなら Uncontrolled ではないコンポーネントを使うべきなのでは？)

2024-05-08 08:18 UTC, miya commented on apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
> +        <Button
これはあえて reactstrap 由来のコンポーネントを使っている？

2024-05-08 08:54 UTC, maeshinshin commented on apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
> +        <Button
修正しました。

2024-05-08 08:56 UTC, maeshinshin commented on apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
> +  }, []);
以下をもとに、reactstrap ではなく、react bootstrap を利用した実装に変更しました。
https://getbootstrap.jp/docs/5.3/components/dropdowns/#%e8%87%aa%e5%8b%95%e3%81%a7%e9%96%89%e3%81%98%e3%82%8b

2024-05-08 08:56 UTC, maeshinshin commented on apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
> +      <UncontrolledButtonDropdown className="me-1" isOpen={dropdownOpen} toggle={handleDropdownToggle}>
変更しました。

2024-05-08 12:02 UTC, merged