feat: Make the PageEditorMode manager circle active when the editor is open
weseek/growi pull request #8793
Opened 2024-05-05 13:35 UTC by miya

2024-05-05 14:06 UTC, miya commented on apps/app/src/client/services/side-effects/yjs.ts
> +};
ここは変更ありません。
yjs-draft.ts というファイル名から yjs.ts というファイル名に変更したため差分が出ています。

2024-05-05 14:06 UTC, miya commented on apps/app/src/client/services/side-effects/yjs.ts
> +};
yjs の Awareness の状態をリアルタイムに受け取るための hook

2024-05-05 14:06 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +  }
yjs の Awareness のサイズ (Editor を開いているユーザー数) を返却するメソッド

2024-05-05 14:06 UTC, miya commented on apps/app/src/server/service/yjs-connection-manager.ts
> +  public getCurrentYdoc(pageId: string): Document | undefined {
返却される型が間違っていたため修正

2024-05-07 03:40 UTC, yuki-takei requested changes

2024-05-07 03:40 UTC, yuki-takei commented on apps/app/src/pages/[[...path]].page.tsx
> +  useCurrentPageYjsAwarenessStateSize(props.yjsAwarenessStateSize);
useCurrentPageYjsDraft で取り扱うデータを object にしたのに、useCurrentPageYjsAwarenessStateSize が新設されてしまったな
socket.io の中を流れるデータの型をきちんと定義して取り扱いたいので統合してほしい

2024-05-07 03:40 UTC, yuki-takei commented on apps/app/src/pages/[[...path]].page.tsx
> +    props.yjsAwarenessStateSize = crowi.pageService.getYjsAwarenessStateSize(page._id);
こちらも統合

2024-05-07 03:40 UTC, yuki-takei commented on apps/app/src/server/service/yjs-connection-manager.ts
> +  public ysocketio: YSocketIO;
https://redmine.weseek.co.jp/issues/139870 でリファクタされそうだが一応

- private のままにする
- 必要があれば getter を定義する

2024-05-07 06:50 UTC, miya commented on apps/app/src/pages/[[...path]].page.tsx
> +  useCurrentPageYjsAwarenessStateSize(props.yjsAwarenessStateSize);
統合しました

2024-05-07 06:50 UTC, miya commented on apps/app/src/pages/[[...path]].page.tsx
> +    props.yjsAwarenessStateSize = crowi.pageService.getYjsAwarenessStateSize(page._id);
統合しました

2024-05-07 06:58 UTC, miya commented on apps/app/src/server/service/yjs-connection-manager.ts
> +  public ysocketio: YSocketIO;
private のままにして getter を定義しました

2024-05-07 10:37 UTC, miya commented on apps/app/src/server/service/socket-io.js
> +      });
setupYjsConnection() が呼ばれた時に一回だけ listen するように変更
commit: https://github.com/weseek/growi/pull/8793/commits/a593e37ccbc0868325530c17924bbe1eacbdd447

2024-05-07 18:55 UTC, merged