feat: Make the PageEditorModeManager circle bg-secondary when there is a difference between the revision body and the draft
weseek/growi pull request #8794
Opened 2024-05-07 12:24 UTC by miya

## Task
[#132775](https://redmine.weseek.co.jp/issues/132775) [v7][New Editor][collab] Editor で編集中またはドラフトが存在することを subnav から確認できる
┗ [#145652](https://redmine.weseek.co.jp/issues/145652) Editor を開いているユーザーがおらず、revision.Body と yjs ドラフトに差分がある時に PageEditorModeManager 右上の circle の色を bg-muted にする

2024-05-07 13:18 UTC, miya commented on apps/app/src/server/service/socket-io.js
> +        }
- 対象ページを Editor を最後に閉じた時にトリガーされる
- 最新 revisionBody とドラフトを比較する
- PageService に移した方が良いかもしれないです

2024-05-07 13:18 UTC, miya commented on apps/app/src/client/services/side-effects/yjs.ts
>  };
一つの hook に統合

2024-05-07 13:18 UTC, miya commented on apps/app/src/stores/yjs.ts
>    updateHasDraft(hasYjsDraft: boolean): void
これは不要そうなので削除予定です。

2024-05-07 18:48 UTC, yuki-takei requested changes

2024-05-07 18:48 UTC, yuki-takei commented on apps/app/src/server/service/socket-io.js
> +        }
> PageService に移した方が良いかもしれないです

同意
PageService 側への実装は `currentYdoc?.getText('codemirror').toString();` を渡して T/F (hasRevisionBodyDiff 相当)を返すようなメソッドでいいと思う。

2024-05-07 22:50 UTC, miya commented on apps/app/src/server/service/socket-io.js
> +        }
pageService.hasRevisionBodyDiff() を実装しました

2024-05-07 23:49 UTC, miya commented on apps/app/src/stores/yjs.ts
> +    { populateCache: true, revalidate: false },
skip

2024-05-08 02:32 UTC, miya commented on apps/app/src/stores/yjs.ts
>    updateHasDraft(hasYjsDraft: boolean): void
ドラフトの有無の情報を取得するロジックは不要なので関連コードは全て削除済み

2024-05-08 02:32 UTC, miya commented on apps/app/src/pages/[[...path]].page.tsx
> +    }
対応済み
https://github.com/weseek/growi/pull/8794#discussion_r1593222159

2024-05-08 11:56 UTC, yuki-takei requested changes

2024-05-08 11:56 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/get-yjs-data.ts
> +        const page = await Page.findOne({ _id: pageId });
viwer を考慮しないといけない
また、Revision body が必要な状況なので Page ドキュメントを取得する必要は必ずしもない

apps/app/src/server/routes/apiv3/revisions.js の `/:id` を参考に

2024-05-08 11:56 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/get-yjs-data.ts
> +        const populatedPage = await page.populateDataToShowRevision();
populate は最低限が望ましい

2024-05-08 11:56 UTC, yuki-takei commented on apps/app/src/server/service/page/index.ts
> +    return revisionBody != null && revisionBody !== comparisonTarget;
このデータ取得・populate・文字列の比較の実装箇所がバラバラ

API route の apiv3/page/get-yjs-data.ts でどこまでやるのか、
このサービスメソッドの getYjsData / hasRevisionBodyDiff でどこまでやるのかを整理して

2024-05-08 13:24 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +    return revisionBody != null && revisionBody !== comparisonTarget;
以下のように統合できる箇所は統合しました。
getYjsData: 受けとった pageid から CurrentPageYjsData 相当のデータを取得する (SSR時・CSR時に利用 )
hasRevisionBodyDiff: 引数で受け取った pageid から最新の revisionBody を取得して、第二引数の文字列と比較する

2024-05-08 13:24 UTC, miya commented on apps/app/src/server/routes/apiv3/page/get-yjs-data.ts
> +        const page = await Page.findOne({ _id: pageId });
Page ドキュメントを取得しない方法で修正しました。

2024-05-08 13:25 UTC, miya commented on apps/app/src/server/routes/apiv3/page/get-yjs-data.ts
> +        const populatedPage = await page.populateDataToShowRevision();
Revisoon ドキュメントを直接取得する方法で修正したので populate はしなようにしました。

2024-05-08 13:34 UTC, yuki-takei commented on apps/app/src/server/service/page/index.ts
> +    const Revision = mongoose.model('Revision');
少しでも type safe にするなら
`const Revision = mongoose.model<IRevisionHasId>('Revision');`
かな。`update-page.ts` でこのようなコードを書いている。

2024-05-08 13:34 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/get-yjs-data.ts
> +        const page = await Page.findOne({ _id: pageId });
revisions.js にあるようなこの処理は必要では？

```
    // check whether accessible
    if (!isSharedPage && !(await Page.isAccessiblePageByViewer(pageId, req.user))) {
      return res.apiv3Err(new ErrorV3('Current user is not accessible to this page.', 'forbidden-page'), 403);
    }
```

サービス層ではチェックを入れないのだから、route でアクセス権を見ないといけない

2024-05-08 14:16 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +    const Revision = mongoose.model('Revision');
修正しました

2024-05-08 14:17 UTC, miya commented on apps/app/src/server/routes/apiv3/page/get-yjs-data.ts
> +        const page = await Page.findOne({ _id: pageId });
page へのアクセスアクセス権を見るように修正しました

2024-05-08 14:34 UTC, merged