imprv: display selected tree item in page select modal as active
weseek/growi pull request #8802
Opened 2024-05-13 08:04 UTC by WNomunomu

2024-05-14 05:46 UTC, miya commented on apps/app/src/components/PageSelectModal/PageSelectModal.tsx
> +  const onClickDone = useCallback(async() => {
この差分必要？

2024-05-17 12:29 UTC, yuki-takei requested changes

2024-05-17 12:29 UTC, yuki-takei commented on apps/app/src/components/TreeItem/TreeItemLayout.tsx
> +const markTarget = (page: IPageForItem, children: ItemNode[], targetPathOrId?: Nullable<string>): void => {
この改修は readable なコードから遠ざかる

- 「選択中のアイテム」を示すのが targetPathOrId
- 「選択中のアイテムかどうかをテストする対象」が page または children

だが、後者は呼び出し側を工夫すれば `children: ItemNode[]` でことたりるはず。ただし名前は children は相応しくないかもしれないので修正しても良い。
または、`テスト対象: ItemNode | ItemNode[]` という型の方が扱いやすいのであればそう変えてもよい

2024-05-17 12:29 UTC, yuki-takei commented on apps/app/src/components/PageSelectModal/PageSelectModal.tsx
> +  const targetPath = clickedParentPagePath || '/';
cuttent page path がモーダルを開いたときの初期値にならないといけないのでは？

2024-05-27 14:22 UTC, yuki-takei requested changes

2024-05-27 14:22 UTC, yuki-takei commented on apps/app/src/components/PageSelectModal/PageSelectModal.tsx
> +  const targetPath = clickedParentPagePath || currentPage.path;
`const targetPath = targetPathOrId || '/';`
でいいんじゃないかな

2024-05-27 14:22 UTC, yuki-takei commented on apps/app/src/components/PageSelectModal/PageSelectModal.tsx
> +  }
このブロックは消す

2024-05-27 14:22 UTC, yuki-takei commented on apps/app/src/components/TreeItem/TreeItemLayout.tsx
> +const markTarget = (itemNode: ItemNode | ItemNode[], targetPathOrId?: Nullable<string>): void => {
この行は元の方が readable なので戻してください
型も呼び出し側で工夫すれば `ItemNode[]` だけでいいはず

2024-05-27 14:26 UTC, yuki-takei commented on apps/app/src/components/TreeItem/TreeItemLayout.tsx
> +  }, [itemNode, page.path, targetPathOrId]);
この処理はなぜ必要？ 既存コードの markTarget 呼び出し部分だけでは不足している理由を教えてほしい。

2024-05-30 10:13 UTC, yuki-takei requested changes

2024-05-30 10:13 UTC, yuki-takei commented on apps/app/src/components/PageSelectModal/PageSelectModal.tsx
> +  }
この対応が済んでいない

2024-05-30 23:17 UTC, merged