imprv: autofocus on PageTitleHeader when edigin untitled page
weseek/growi pull request #8813
Opened 2024-05-16 06:52 UTC by WNomunomu

2024-05-22 05:11 UTC, miya reviewed
手元で動作確認した結果
- 初回レンダリング時且つ Untitled-{number} のページにのみオートフォーカスが当たっている
- Default language for new users が英語の時以外はそもそも機能していないみたいだけどこれはスコープ外なのか

2024-05-28 01:15 UTC, miya requested changes
以下の状況の時にオートフォーカスされてない
1. Untitled なページを作成
2. editor mode に切り替える (この時点ではオートフォーカスされている)
3. view mode に切り替える
4. editor mode に切り替える’

2024-05-28 01:15 UTC, miya commented on apps/app/src/components/PageHeader/untitled-page-utils.ts
> +      // https://regex101.com/r/Wg2Hh6/1
日本語、中国語も追加してください

2024-05-28 13:15 UTC, WNomunomu commented on apps/app/src/components/PageHeader/untitled-page-utils.ts
> +      // https://regex101.com/r/Wg2Hh6/1
こちら、AllLangという配列を用いて、全言語追加してあります。

2024-05-28 13:15 UTC, WNomunomu commented on apps/app/src/components/PageHeader/PageTitleHeader.tsx
> +  }, [currentPage._id, currentPagePath, isNewlyCreatedPage, editorMode]);
依存配列にeditorModeを加えることで、editorに切り替えた時にもautoFocusするようにしました。

2024-05-30 08:04 UTC, yuki-takei requested changes

2024-05-30 08:04 UTC, yuki-takei commented on apps/app/src/components/PageHeader/untitled-page-utils.ts
> +  return isNewlyCreatedPage;
hook の名前と返す boolean の性格は揃えてください

2024-05-30 08:04 UTC, yuki-takei commented on apps/app/src/pages/[[...path]].page.tsx
> +  const nextI18NextConfig = await getNextI18NextConfig(serverSideTranslations, context, namespacesRequired, true);
この最後の引数 true にしたくないなあ…どうするか

2024-06-03 22:06 UTC, merged