imprv: Fix flow from subnav
weseek/growi pull request #8822
Opened 2024-05-20 08:21 UTC by TatsuyaIse

2024-05-21 01:07 UTC, miya commented on apps/app/src/pages/utils/commons.ts
/pages/[[...path]].page.tsx と /pages/share/[[...path]].page.tsx で利用する程度でしたら、commons ではなくそれらの Next Page に直接取得処理を書くで良いかもしれないです。

props.currentUser など大半の Next Page で利用する値の取得を commons に書くイメージです。

2024-05-21 09:04 UTC, TatsuyaIse commented on apps/app/src/pages/utils/commons.ts
common から取り除き、それぞれのページコンポーネントで個別にサーバサイドから取得する実装を加えました。

2024-05-24 02:51 UTC, yuki-takei requested changes

2024-05-24 02:51 UTC, yuki-takei commented on apps/app/src/pages/share/[[...path]].page.tsx
> +  isRegistrationEnabled: boolean,
`isLocalAccountRegistrationEnabled` に変更する

2024-05-24 02:51 UTC, yuki-takei commented on apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
> +                )}
ストーリーの期待される動作通りではないが、それがベストではない気もする。
再考してほしい。

## グレーアウト案
ストーリーの説明ではグレーアウトさせるのが期待される動作となっている
disabled にするのであれば tooltip も一緒に実装すべき

## ボタンを表示しない案
OIDC や SAML で初回ログインすれば新規作成できる場合、「ログイン」ボタンをクリックする気になるだろうか？

## 表示はするが href をログイン画面にする案
ボタンは表示しつつ、href を `/login` にする？

## ログインボタンのラベルを「新規作成 or ログイン」にする案
ただし local account が有効だろうが無効だろうが、OIDC / SAML でも新規アカウント作成できる点はかわらない
その条件で変えてしまっていいだろうか？

2024-07-01 08:11 UTC, closed without merging