feat: Design coding of search result page
weseek/growi pull request #8828
Opened 2024-05-21 09:42 UTC by miya

## Task
[#141570](https://redmine.weseek.co.jp/issues/141570) [v7][design] 検索結果一覧の表示を XD 通りにコーディングする
┗ [#146155](https://redmine.weseek.co.jp/issues/146155) 実装

## XD
https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/7894221d-1d59-4026-b0c4-671fa79692c2/

## Demo
wip

2024-05-24 02:28 UTC, yuki-takei requested changes

2024-05-24 02:28 UTC, yuki-takei commented on apps/app/src/components/PageControls/PageControls.tsx
> +          {revisionId != null && !isSearchPage && (
subscribe はできてもいいんじゃないかな

2024-05-24 02:28 UTC, yuki-takei commented on apps/app/src/components/SearchPage.tsx
> +          </div>
こういう UI 一般的じゃないしわからないと思う
UI 設計まで差し戻したい

2024-05-24 02:28 UTC, yuki-takei commented on apps/app/src/components/SearchPage.module.scss
> +  }
- .danger-style の適用対象が広すぎる
- ボタンのカスタマイズは css variable を利用して

2024-05-24 02:28 UTC, yuki-takei commented on apps/app/src/components/SearchPage.tsx
> +    <div className={`${styles['search-page']}`}>
wrap する div を用意するのではなく、
SearchPageBase に `className?: string` props を用意し、そちらの root element に追加するようにしてください

2024-05-28 09:34 UTC, miya commented on apps/app/src/components/PageControls/PageControls.tsx
> +          {revisionId != null && !isSearchPage && (
Subscribe ボタンは戻しました

2024-05-28 12:27 UTC, miya commented on apps/app/src/components/SearchPage.tsx
> +    <div className={`${styles['search-page']}`}>
修正しました

2024-05-28 12:27 UTC, miya commented on apps/app/src/components/SearchPage.module.scss
> +  }
しゅうせいしました

2024-05-28 21:40 UTC, yuki-takei requested changes

2024-05-28 21:40 UTC, yuki-takei commented on apps/app/src/components/SearchPage.module.scss
> +  }
`--bs-danger-rgb` などを使って欲しかった
今回は btn-muted mixin があるのでそちらを流用することにした

2024-05-28 21:40 UTC, yuki-takei commented on apps/app/src/components/SearchPage/OperateAllControl.tsx
> +    inputId,
htmlFor を使えるように id を入れられるようにした

2024-05-28 21:46 UTC, yuki-takei commented on apps/app/src/components/SearchPage/SearchControl.tsx
> +  toggleControl: React.ReactNode,
名が体を表すように、気付いた時に修正をしよう

2024-05-28 21:46 UTC, yuki-takei commented on apps/app/src/components/SearchPage.tsx
> +                  htmlFor="cb-select-all"
ラベルをクリックして選択状態を変更できるかどうかで UX が変わってくる
そのための htmlFor

2024-05-28 21:46 UTC, yuki-takei commented on apps/app/src/components/SearchPage.tsx
> +              disabled={selectedCount === 0}
このボタンの disabled 条件は hitsCount ではなく選択アイテムがあるかどうか

2024-05-28 21:46 UTC, yuki-takei commented on apps/app/src/components/SearchPage.tsx
> +                  className="form-check-label ms-2"
bootstrap のクラスをきちんと使うことで、disabled 状態になったときにラベルの色やポインタースタイルも変えることができる
https://getbootstrap.jp/docs/5.3/forms/overview/

2024-05-28 22:24 UTC, yuki-takei commented on apps/app/src/components/SearchPage/SearchControl.tsx
> +  extraControls: React.ReactNode,
名が体を表すように、気付いた時に修正をしよう

2024-05-28 22:24 UTC, merged