imprv: Behavior of dropdown toggle in groundglassbar
weseek/growi pull request #8832
Opened 2024-05-22 07:23 UTC by maeshinshin

[#145795](https://redmine.weseek.co.jp/issues/145795): [v7] 上部の GroundGlassBar 内の三点リーダー内ドロップダウンのトグル押下後の挙動の修正
┗ [#145917](https://redmine.weseek.co.jp/issues/145917): 実装

- 切り替え後、dropdown が閉じないままになる
- input (switch) クリックで切り替えができる
- label クリックでも切り替えができる

2024-05-22 08:00 UTC, miya requested changes

2024-05-22 08:00 UTC, miya commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const switchContentWidthClickHandler = useCallback(async(e:any) => {
型をつけよう

2024-05-24 07:26 UTC, maeshinshin commented on apps/app/src/components/PageControls/PageControls.tsx
> +  onClickMenuItem: (e:any) => void,
修正しました。

2024-05-24 07:26 UTC, maeshinshin commented on apps/app/src/components/PageControls/PageControls.tsx
> +          onChange={onClickMenuItem}
onChange 削除しました。

2024-05-24 07:35 UTC, maeshinshin commented on apps/app/src/components/PageControls/PageControls.tsx
> +  onClickMenuItem: (e:any) => void,
React.MouseEvent<HTMLInputElement> の型アノテーションをつけました。

2024-05-24 07:36 UTC, maeshinshin commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const switchContentWidthClickHandler = useCallback(async(e:any) => {
React.MouseEvent<HTMLInputElement> の型アノテーションをつけました。

2024-05-24 07:43 UTC, miya requested changes

2024-05-24 07:43 UTC, miya commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const switchContentWidthClickHandler = useCallback(async(e: React.MouseEvent<HTMLInputElement>) => {
スコープ外だけど、このメソッドは非同期処理ではなさそうなので async func である必要はなさそう

2024-05-24 08:07 UTC, maeshinshin commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const switchContentWidthClickHandler = useCallback(async(e: React.MouseEvent<HTMLInputElement>) => {
async 外しました。

2024-05-24 09:13 UTC, yuki-takei requested changes

2024-05-24 09:13 UTC, yuki-takei commented on apps/app/src/components/PageControls/PageControls.tsx
> +    e.preventDefault();
細かいところだけれど、e.preventDefault() するのは WideViewMenuItem の方の onClick でやってください

2024-05-27 07:29 UTC, miya requested changes

2024-05-27 07:29 UTC, miya commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const wrapedonClickMenuItem = useCallback((e: React.MouseEvent<HTMLInputElement>) => {
`menuItemClickedHandler` というメソッド名にしてください

2024-05-27 07:55 UTC, maeshinshin commented on apps/app/src/components/PageControls/PageControls.tsx
> +  const wrapedonClickMenuItem = useCallback((e: React.MouseEvent<HTMLInputElement>) => {
修正しました。

2024-05-27 08:43 UTC, merged