imprv: Styling icon on the side of header
weseek/growi pull request #8833
Opened 2024-05-22 07:43 UTC by reiji-h

# Summary
- Header 横の Edit アイコンを固定サイズ二変更
- Header 横のリンクを # に変更し、左側に配置

# Task
- https://redmine.weseek.co.jp/issues/145477
  - https://redmine.weseek.co.jp/issues/146791
- https://redmine.weseek.co.jp/issues/145476
  - https://redmine.weseek.co.jp/issues/146792

2024-06-04 07:52 UTC, yuki-takei requested changes

2024-06-04 07:52 UTC, yuki-takei commented on apps/app/src/components/ReactMarkdownComponents/Header.tsx
> +      <NextLink href={`#${id}`} className="d-none d-md-inline revision-head-link">
- scss 側で　`hX > span` のような指定にしたくないので、 DOM 構造は一旦元に戻し、`#` リンクは CustomTag の外に出してください
    - 文字サイズの設定は `h{props.level}` クラスを付ければよい

2024-06-04 07:52 UTC, yuki-takei commented on apps/app/src/components/Common/PageViewLayout.module.scss
> +  }
この指定は bs5 のグリッドシステムを壊しかねない
やるなら `--bs-gutter-x` を利用した計算式を踏襲して上書きする


![image](https://github.com/weseek/growi/assets/1638767/adfe40f7-f81c-470e-89cd-656c89871ffc)

2024-06-04 07:52 UTC, yuki-takei commented on apps/app/src/styles/organisms/_wiki.scss
> +}
PageViewLayout.module.scss での調整との相殺になるようなコードをここに追加すると読みにくくなる
この調整自体なしにはできないのか検討しよう

2024-06-10 02:12 UTC, reiji-h commented on apps/app/src/components/ReactMarkdownComponents/Header.tsx
> +      <NextLink href={`#${id}`} className="d-none d-md-inline revision-head-link">
外に出し、scss 側の指定は .h1 .h2 などのクラスを使用するように変更しました。

2024-06-10 02:24 UTC, reiji-h commented on apps/app/src/styles/organisms/_wiki.scss
> +}
md 以上の時 margin-left を追加するようにし、このコードは削除しました。

2024-06-10 02:25 UTC, reiji-h commented on apps/app/src/components/Common/PageViewLayout.module.scss
> +  }
PageViewLayout.module.scss ではなく、PagePathNav.module.scss と _wiki.scss に記入しました。

2024-06-10 09:00 UTC, merged