fix: Match width of video tag to img tag
weseek/growi pull request #8836
Opened 2024-05-23 05:17 UTC by TatsuyaIse

### task
- https://redmine.weseek.co.jp/issues/144159

### before

### after

2024-05-23 05:19 UTC, TatsuyaIse commented on apps/app/src/styles/organisms/_wiki.scss
> +  img,video {
img タグと同様にページ内で表示された video にも max-width: 100% のスタイルが適用されるようにセレクタを追加  
XSS 抑制のデフォルトは video タグは許容されていないが、カスタムホワイトリストで追加した際に崩れてしまうので追加している。

2024-05-24 02:37 UTC, yuki-takei requested changes

2024-05-24 02:37 UTC, yuki-takei commented on apps/app/src/styles/organisms/_wiki.scss
> +  img,video {
おすすめ設定でデフォルトで video タグを許容するコードもこの PR に追加してください

108 行目のコメントは不要になる

2024-05-29 07:55 UTC, TatsuyaIse commented on apps/app/src/components/Admin/MarkdownSetting/WhitelistInput.jsx
> +    this.tags = [...sanitizeDefaultSchema.tagNames, 'video'];
rehype-sanitize が管轄している tagNames に、個別で `video` を追加するためこうしています。

2024-06-11 20:37 UTC, merged

2024-06-18 05:15 UTC, yuki-takei commented on apps/app/src/server/service/xss.js
> -    const xssOpiton = this.configManager.getConfig('markdown', 'markdown:xss:option');
古いコンフィグ値を利用していたコード

2024-06-18 05:15 UTC, yuki-takei commented on apps/app/src/server/service/xss.js
> -          return this.configManager.getConfig('markdown', 'markdown:xss:tagWhitelist');
古いコンフィグ値を利用していたコード

2024-06-18 05:15 UTC, yuki-takei commented on apps/app/src/server/service/xss.js
> -          return this.configManager.getConfig('markdown', 'markdown:xss:attrWhitelist');
古いコンフィグ値を利用していたコード