imprv: Edit icon add
weseek/growi pull request #8855
Opened 2024-05-29 07:46 UTC by kazutoweseek

TASK
https://redmine.weseek.co.jp/issues/140677
┗https://redmine.weseek.co.jp/issues/145630
![スクリーンショット 2024-05-29 164506](https://github.com/weseek/growi/assets/164848419/94fa0274-c43b-4911-8cba-f704efd413df)

2024-06-12 06:05 UTC, miya requested changes

2024-06-12 06:05 UTC, miya commented on apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +                          key={index}
`group._id` に変えたら // eslint-disable-next-line react/no-array-index-key が不要になると思う

2024-06-13 18:38 UTC, yuki-takei requested changes

2024-06-13 18:38 UTC, yuki-takei commented on apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +                        </button>
## DOM 構造について
DOM 構造的に Link の中に button があるのは違和感。

親コンテナの中に Link と button を子供として並列に入れて、
親コンテナに対する hover で button の表示・非表示をコントロールしたらいいと思う。
PageCreateButton あたりが参考になるはず。

## ステート管理について
index を保持するのはあまりスマートではないので、ここは切り出して別コンポーネントにしよう。
このファイル内に定義してしまって構わない。

2024-06-24 07:14 UTC, miya commented on apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
> +                        </button>
これが考慮されていないと思う。
以下を別コンポーネントに切り出して index を props で渡す、という実装になるんじゃないかな。

```jsx
    <button
      className="btn btn-link btn-edit-groups text-secondary py-0"
      type="button"
      key={group._id}
    >
      <span className="material-symbols-outlined pe-2 pt-2">group</span>
      <span className="text-decoration-underline">{group.name}</span>
      <span className={`material-symbols-outlined px-2 py-0 ${hovereditem === item ? '' : 'opacity-0'}`}>edit</span>
    </button>
```

2024-07-24 10:20 UTC, merged