support: Replace tests with playwright (21-basic-features-for-guest/21-basic-features-for-guest--access-to-page)
weseek/growi pull request #8885
Opened 2024-06-11 10:16 UTC by miya

## Task
[#148045](https://redmine.weseek.co.jp/issues/148045) E2E test を Cypress からPlaywright にリプレイスする
┗ [#148123](https://redmine.weseek.co.jp/issues/148123) 21-basic-features-for-guest/21-basic-features-for-guest--access-to-page

2024-06-17 13:45 UTC, yuki-takei requested changes

2024-06-17 13:45 UTC, yuki-takei commented on apps/app/playwright.config.ts
> +}));
こうまとめるなら他のもまとめてほしい

2024-06-17 13:49 UTC, yuki-takei commented on .github/workflows/reusable-app-prod.yml
> +        cat config/ci/.env.local.for-set-wiki-mode-to-public >> .env.production.local
他のテスト(browser別、shard別)でも言えることだけれど、別の DB にしてテスト環境をそれぞれで独立させた方がいいかもね

2024-06-18 05:23 UTC, miya commented on apps/app/playwright.config.ts
> +}));
installer 以外をまとめました

2024-06-18 06:40 UTC, miya commented on .github/workflows/reusable-app-prod.yml
> +        cat config/ci/.env.local.for-set-wiki-mode-to-public >> .env.production.local
Guest mode 時は `MONGO_URI: mongodb://mongodb:27017/growi-playwright-guest-mode` を割り当てるように改修しました

2024-06-18 07:48 UTC, merged