fix: Minimum number of characters in password cannot be changed
weseek/growi pull request #8896
Opened 2024-06-13 09:26 UTC by miya

## Task
[#147824](https://redmine.weseek.co.jp/issues/147824) [v7][v6][issue] 環境変数 MIN_PASSWORD_LENGTH が考慮されない
┗ [#148259](https://redmine.weseek.co.jp/issues/148259) 修正

2024-06-13 12:00 UTC, miya commented on apps/app/src/server/middlewares/register-form-validator.ts
> +      .withMessage(new ErrorV3('message.Password minimum character should be more than n characters', undefined, undefined, { number: fixedMinPasswordLength }))
ErrorV3 を利用し任意のオブジェクトを返却する

2024-06-13 12:00 UTC, miya commented on apps/app/src/server/middlewares/login-form-validator.ts
> -      .isLength({ min: 6 })
login と register で数値が変わるのは不自然なので統一

2024-06-13 12:03 UTC, miya commented on apps/app/src/server/middlewares/login-form-validator.ts
> +      .withMessage(new ErrorV3('message.Password minimum character should be more than n characters', undefined, undefined, { number: fixedMinPasswordLength }))
ErrorV3 を利用し任意のオブジェクトを返却する

2024-06-13 12:03 UTC, miya commented on apps/app/src/components/LoginForm/LoginForm.tsx
> +                  {tWithOpt(err.message, err.args)}<br />
err.args を受け取れるように改修

2024-06-13 18:42 UTC, yuki-takei requested changes

2024-06-13 18:42 UTC, yuki-takei commented on apps/app/src/server/middlewares/login-form-validator.ts
> +import { DEFAULT_PASSOWRD_MINIMUM_NUMBER } from '~/consts/user';
configManager から取得するべきかと

2024-06-13 18:42 UTC, yuki-takei commented on apps/app/src/consts/user.ts
> +export const DEFAULT_PASSOWRD_MINIMUM_NUMBER = 8;
config-loader でデフォルト値は入れているのに const を作る必要があるのはなぜ？

2024-06-14 01:06 UTC, miya commented on apps/app/src/consts/user.ts
> +export const DEFAULT_PASSOWRD_MINIMUM_NUMBER = 8;
registerRules(), loginRules() で引数で入れる minPasswordLength がオプショナルだから、という理由でしたがそもそもオプショナルにする必要は無いので元に戻しました。

2024-06-14 01:06 UTC, miya commented on apps/app/src/server/middlewares/login-form-validator.ts
> +import { DEFAULT_PASSOWRD_MINIMUM_NUMBER } from '~/consts/user';
修正しました

2024-06-14 08:01 UTC, yuki-takei requested changes

2024-06-17 13:36 UTC, merged

2024-06-17 13:54 UTC, yuki-takei commented on apps/app/src/pages/installer.page.tsx
> +  const { configManager } = crowi;
直接インポートしてください