imprv: lang attribute in Html element to correctly reflect locale
weseek/growi pull request #8940
Opened 2024-07-03 09:26 UTC by maeshinshin

task: https://redmine.weseek.co.jp/issues/149169

2024-07-03 10:02 UTC, miya requested changes

2024-07-03 10:15 UTC, maeshinshin commented on apps/app/src/pages/_document.page.tsx
> +  locale: string;
import している type は、GROWI 内部のものであり、rfc 5646 で決められている、lnag attribute の形式に合わないため、以降の行で、map を定義し変換しています。
https://www.ietf.org/rfc/bcp/bcp47.txt

2024-07-03 10:16 UTC, maeshinshin commented on apps/app/src/pages/_document.page.tsx
> +    };
修正しました。

2024-07-03 12:05 UTC, yuki-takei requested changes

2024-07-03 12:05 UTC, yuki-takei commented on apps/app/src/pages/_document.page.tsx
> +
commons.ts の getNextI18NextConfig 内のコードを共通化し、ここでのマッピング時にも使えるようにしてください。

2024-07-05 07:28 UTC, maeshinshin commented on apps/app/src/pages/_document.page.tsx
> +
共通化し、置き換えました。
common.ts 内のコードも共通化したものを使用するように変更しました。

2024-07-05 13:06 UTC, merged