imprv: lang attribute in Html element
weseek/growi pull request #8960
Opened 2024-07-12 12:09 UTC by maeshinshin

task: https://redmine.weseek.co.jp/issues/149981

2024-07-16 03:03 UTC, miya requested changes

2024-07-16 03:03 UTC, miya commented on apps/app/src/pages/_app.page.tsx
> +    const handle = () => {
具体的な変数名にした方が良さそう

2024-07-19 12:16 UTC, maeshinshin commented on apps/app/src/pages/utils/commons.ts
> +export const getLocaleAtServerSide = (req: CrowiRequest): 'ja-jp' | 'en-us' | 'zh-cn' | 'fr-fr' => {
追加しました。

2024-07-19 12:24 UTC, maeshinshin commented on apps/app/src/pages/utils/commons.ts
> +  } as const;
getLocateAtServerSide の外に置くように変更しました。

2024-07-19 12:43 UTC, maeshinshin commented on apps/app/src/pages/_app.page.tsx
> +    const handle = () => {
updateLangAttribute にしました

2024-08-02 14:00 UTC, merged