Feat/78040 135788 resume suspended bulk export job
weseek/growi pull request #8963
Opened 2024-07-15 14:46 UTC by arafubeatbox

2024-07-15 14:53 UTC, arafubeatbox commented on apps/app/src/server/service/file-uploader/gcs/multipart-uploader.ts
> +    this.file = bucket.file(urljoin(namespace || '', uploadKey));
アップロード先の namespace の指定が抜けており、ファイル取得時のパスと齟齬があったため修正。

2024-07-15 14:58 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/interfaces/page-bulk-export.ts
> +  md: 'md',
pdf の PR で行っていた修正ですが、リリース前に修正しちゃいたかったので修正します。
format と extension の変換 ("markdown" -> "md") が冗長に感じたので、両方兼ね備えた値にします。

2024-07-15 15:14 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> +  private async executePageBulkExportJob(
bulkExportWithBasePagePath -> executePageBulkExportJob に変わっています。
変更点:
- pageBulkExportJob の実行のステップ (status) を追加
    - initializing -> exporting -> uploading
- pageBulkExportJob を再開する場合、status によって処理の開始ポイントが異なるため、その場合分けを追加
- initializing (createPageSnapshots) の処理を新たに追加
    - exporting 以降の処理は今までもあり、ほぼほぼ変更無いが、個別のメソッドに切り分けるリファクタリングをしている

2024-07-16 09:21 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> +  async executePageBulkExportJob(pageBulkExportJob: PageBulkExportJobDocument & HasObjectId): Promise<void> {
bulkExportWithBasePagePath -> executePageBulkExportJob に変わっています。
変更点:
- pageBulkExportJob の実行のステップ (status) を追加
    - initializing -> exporting -> uploading
- pageBulkExportJob を再開する場合、status によって処理の開始ポイントが異なるため、その場合分けを追加
- initializing (createPageSnapshots) の処理を新たに追加
    - exporting 以降の処理は今までもあり、ほぼほぼ変更無いが、個別のメソッドに切り分けるリファクタリングをしている

2024-07-16 09:34 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> -      ...activityParameters,
ここをどうするか迷ったのですが、再開する時は `apps/app/src/crowi/index.js` から実行されるため、activityParameters (ip と endpoint) を渡すことができません。

最初のクライアントからの bulk export 実行のリクエスト時に、ip と endpoint をどこかに保存しておいて、createActivity 時に渡すべきでしょうか？

正直 ip と endpoint の用途があまりわかっていませんが、ログ的な役割だと思っています。
裏で走っている非同期プロセス上でアプリが activity を行い、クライアントが直接実行したわけではない、という風に捉えれば、ip と endpoint は入れなくても良いのかなと思ったりしています (今はそのように実装しています)。

2024-07-16 09:52 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/interfaces/page-bulk-export.ts
> +  md: 'md',
リリース前に行いたいのは、これが DB に保存される値だからです。
(PageBulkExporJob.format)

2024-08-07 14:54 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> +    }
エクスポートリクエストが重複する場合はエラーを投げる。

2024-08-07 14:55 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> +      user: currentUser, page: basePage, format, status: PageBulkExportJobStatus.initializing,
エクスポートの実行を追うための PageBulkExportJob を作成

2024-08-07 15:03 UTC, arafubeatbox commented on apps/app/src/server/crowi/index.js
> +};
起動時に進行中の PageBulkExportJob を再開

2024-08-07 15:05 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> +  private async exportPagesToFS(pageBulkExportJob: PageBulkExportJobDocument): Promise<void> {
元々 bulkExportWithBasePagePath にあった処理

2024-08-07 15:06 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> +  private async compressAndUpload(user, pageBulkExportJob: PageBulkExportJobDocument): Promise<void> {
元々 bulkExportWithBasePagePath にあった処理

2024-08-08 12:17 UTC, yuki-takei requested changes

2024-08-08 12:17 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> +  async executePageBulkExportJob(pageBulkExportJob: PageBulkExportJobDocument & HasObjectId): Promise<void> {
本筋には関係ないフィードバックだけれど、`PageBulkExportJobDocument & HasObjectId` は、mongoose 由来の `HydratedDocument` を使うといいよ

2024-08-08 12:17 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> -      ...activityParameters,
action のタイプを、ユーザーが export をトリガーしたときとシステムが再開をトリガーしたときで分けちゃえばいいんじゃないかな。ユーザーがトリガーした時はやはり ip 欲しいので。

逆にシステムによるトリガーはログとしての activity はそんなに重要ではない
InAppNotification の方に影響がないならば記録しなくてもいい

2024-08-08 12:17 UTC, yuki-takei commented on apps/app/src/server/crowi/index.js
> +};
ペンディング中の job 数は予測ができない。
多すぎる場合に Promise.all ではリソースを食い潰すので、擬似的にでもキューイングのようなことをしたい。

2024-08-10 03:16 UTC, arafubeatbox commented on apps/app/src/server/crowi/index.js
> +};
こちら
https://redmine.weseek.co.jp/issues/143599
で対応しようと思います。
TODO コメント残しておきました。

2024-08-10 03:31 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> -      ...activityParameters,
activityParameters を optional にし、API 経由で直接実行された時だけ渡すようにしましたm(_ _)m

2024-08-10 03:31 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
> -      ...activityParameters,
> 逆にシステムによるトリガーはログとしての activity はそんなに重要ではない
> InAppNotification の方に影響がないならば記録しなくてもいい

InAppNotification に影響はないため、システムからのトリガーでは渡さなくて問題ありません。

2024-08-13 07:54 UTC, merged