support: Chage text size in sidebar
weseek/growi pull request #8965
Opened 2024-07-16 10:16 UTC by satof3

# Task
https://redmine.weseek.co.jp/issues/150088

# Summary
- サイドバーのページを表す部分のテキストサイズを`16px`から`14px`に変更
- それに伴い`arrow_right`を調整

<img width="555" alt="image" src="https://github.com/user-attachments/assets/28c84a25-37bb-414a-9c8d-c90049a0188d">

2024-07-18 11:25 UTC, yuki-takei requested changes

2024-07-18 11:25 UTC, yuki-takei commented on apps/app/src/client/components/Sidebar/SidebarContents.module.scss
> +}
このクラスあまり作りたくない

- bs5 の css var では調整できないのか？
- どうしても font-size を指定する必要があるなら、個別のコンポーネントに対する module css で

2024-07-19 12:56 UTC, satof3 commented on apps/app/src/client/components/Sidebar/SidebarContents.module.scss
> +}
bs5ではテキストサイズの調整ができなかったため、個別コンポーネントに`font-size`を追加しました

2024-07-19 13:23 UTC, yuki-takei requested changes

2024-07-19 13:23 UTC, yuki-takei commented on apps/app/src/client/components/TreeItem/SimpleItemContent.module.scss
SimpleItemContent は TreeItemLayout を通じて数カ所で使っているはず
Sidebar と PageSelectModal のそれぞれで font-size を設定してください

2024-07-22 07:59 UTC, satof3 commented on apps/app/src/client/components/TreeItem/SimpleItemContent.module.scss
Sidebar のみテキストサイズを変えたいので `Sidebar/PageTreeLitem/PageTreeLitem.module.scss` に記述しました

2024-07-23 10:58 UTC, merged