support: Migration script for revision document (for #8954)
weseek/growi pull request #8973
Opened 2024-07-18 09:26 UTC by miya

## Task
[#150649](https://redmine.weseek.co.jp/issues/150649) revision.pageId の値を ObjectId から String に変換するためのマイグレーションスクリプトの実装
┗ [#150650](https://redmine.weseek.co.jp/issues/150650) マイグレーションスクリプトの実装

2024-07-18 11:44 UTC, yuki-takei requested changes

2024-07-18 11:44 UTC, yuki-takei commented on apps/app/src/server/service/normalize-data/convert-revision-page-id-to-string.ts
> +  const targetDocuments = await Revision.find({ $expr: { $not: { $eq: [{ $type: '$pageId' }, 'string'] } } });
この実装は v7.0.12 を使った期間が長いと(つまり Revision 数が多いと)メモリが枯渇してしまう

https://mongoosejs.com/docs/api/model.html#Model.updateMany()
を使ってください

2024-07-18 11:44 UTC, yuki-takei commented on apps/app/src/server/service/normalize-data/convert-revision-page-id-to-string.ts
起動時に必ずこのメソッドがあるので pageId の type を変えてはいけないというコード内コメントを Revision model の方に追加してください

2024-07-18 11:51 UTC, yuki-takei commented on apps/app/src/server/service/normalize-data/convert-revision-page-id-to-string.ts
> +  const targetDocuments = await Revision.find({ $expr: { $not: { $eq: [{ $type: '$pageId' }, 'string'] } } });
explain でフルスキャンにならないことを確認できると尚良い

2024-07-18 14:18 UTC, miya commented on apps/app/src/server/service/normalize-data/convert-revision-page-id-to-string.ts
> +  const targetDocuments = await Revision.find({ $expr: { $not: { $eq: [{ $type: '$pageId' }, 'string'] } } });
- updateMany を使った実装に改修しました
- explain() の結果をログに出力するように改修しました

2024-07-18 14:18 UTC, miya commented on apps/app/src/server/service/normalize-data/convert-revision-page-id-to-string.ts
コメントを追加しました

2024-07-19 07:44 UTC, miya commented on apps/app/src/server/service/normalize-data/convert-revision-page-id-to-string.ts
> +  const targetDocuments = await Revision.find({ $expr: { $not: { $eq: [{ $type: '$pageId' }, 'string'] } } });
explain の結果

```bash
@growi/app:dev: 07:39:34.177Z  INFO growi:service:NormalizeData:convert-revision-page-id-to-string:  (explainVersion=1, ok=1)
@growi/app:dev:   queryPlanner: {
@growi/app:dev:     "namespace": "growi.revisions",
@growi/app:dev:     "indexFilterSet": false,
@growi/app:dev:     "parsedQuery": {
@growi/app:dev:       "pageId": {
@growi/app:dev:         "$type": [
@growi/app:dev:           7
@growi/app:dev:         ]
@growi/app:dev:       }
@growi/app:dev:     },
@growi/app:dev:     "queryHash": "C2307198",
@growi/app:dev:     "planCacheKey": "918277E6",
@growi/app:dev:     "maxIndexedOrSolutionsReached": false,
@growi/app:dev:     "maxIndexedAndSolutionsReached": false,
@growi/app:dev:     "maxScansToExplodeReached": false,
@growi/app:dev:     "winningPlan": {
@growi/app:dev:       "stage": "UPDATE",
@growi/app:dev:       "inputStage": {
@growi/app:dev:         "stage": "FETCH",
@growi/app:dev:         "inputStage": {
@growi/app:dev:           "stage": "IXSCAN",
@growi/app:dev:           "keyPattern": {
@growi/app:dev:             "pageId": 1
@growi/app:dev:           },
@growi/app:dev:           "indexName": "pageId_1",
@growi/app:dev:           "isMultiKey": false,
@growi/app:dev:           "multiKeyPaths": {
@growi/app:dev:             "pageId": []
@growi/app:dev:           },
@growi/app:dev:           "isUnique": false,
@growi/app:dev:           "isSparse": false,
@growi/app:dev:           "isPartial": false,
@growi/app:dev:           "indexVersion": 2,
@growi/app:dev:           "direction": "forward",
@growi/app:dev:           "indexBounds": {
@growi/app:dev:             "pageId": [
@growi/app:dev:               "[ObjectId('000000000000000000000000'), ObjectId('ffffffffffffffffffffffff')]"
@growi/app:dev:             ]
@growi/app:dev:           }
@growi/app:dev:         }
@growi/app:dev:       }
@growi/app:dev:     },
@growi/app:dev:     "rejectedPlans": []
@growi/app:dev:   }
@growi/app:dev:   --
@growi/app:dev:   command: {
@growi/app:dev:     "update": "revisions",
@growi/app:dev:     "updates": [
@growi/app:dev:       {
@growi/app:dev:         "q": {
@growi/app:dev:           "pageId": {
@growi/app:dev:             "$type": "objectId"
@growi/app:dev:           }
@growi/app:dev:         },
@growi/app:dev:         "u": [
@growi/app:dev:           {
@growi/app:dev:             "$set": {
@growi/app:dev:               "pageId": {
@growi/app:dev:                 "$toString": "$pageId"
@growi/app:dev:               }
@growi/app:dev:             }
@growi/app:dev:           },
@growi/app:dev:           {
@growi/app:dev:             "$set": {
@growi/app:dev:               "null": "2024-07-19T07:39:34.175Z"
@growi/app:dev:             }
@growi/app:dev:           }
@growi/app:dev:         ],
@growi/app:dev:         "multi": true
@growi/app:dev:       }
@growi/app:dev:     ],
@growi/app:dev:     "ordered": true,
@growi/app:dev:     "$db": "growi"
@growi/app:dev:   }
@growi/app:dev:   --
@growi/app:dev:   serverInfo: {
@growi/app:dev:     "host": "acbcdd6bcab8",
@growi/app:dev:     "port": 27017,
@growi/app:dev:     "version": "6.0.12",
@growi/app:dev:     "gitVersion": "21e6e8e11a45dfbdb7ca6cf95fa8c5f859e2b118"
@growi/app:dev:   }
@growi/app:dev:   --
@growi/app:dev:   serverParameters: {
@growi/app:dev:     "internalQueryFacetBufferSizeBytes": 104857600,
@growi/app:dev:     "internalQueryFacetMaxOutputDocSizeBytes": 104857600,
@growi/app:dev:     "internalLookupStageIntermediateDocumentMaxSizeBytes": 104857600,
@growi/app:dev:     "internalDocumentSourceGroupMaxMemoryBytes": 104857600,
@growi/app:dev:     "internalQueryMaxBlockingSortMemoryUsageBytes": 104857600,
@growi/app:dev:     "internalQueryProhibitBlockingMergeOnMongoS": 0,
@growi/app:dev:     "internalQueryMaxAddToSetBytes": 104857600,
@growi/app:dev:     "internalDocumentSourceSetWindowFieldsMaxMemoryBytes": 104857600
@growi/app:dev:   }
@growi/app:de
```

2024-07-19 08:34 UTC, merged