Feat/78039 135789 delete unnecessary page bulk export jobs
weseek/growi pull request #8974
Opened 2024-07-19 06:37 UTC by arafubeatbox

2024-08-20 19:43 UTC, yuki-takei requested changes

2024-08-20 19:43 UTC, yuki-takei commented on apps/app/src/server/crowi/index.js
> +  pageBulkExportJobCronService.startCron(pageBulkExportJobCronSchedule);
コンフィグ値の読み込みと設定は各サービスでやりたいな
cronwi/index.js がその注入に関わった方がいい道理もないと思うので

2024-08-20 19:43 UTC, yuki-takei commented on apps/app/src/features/questionnaire/server/service/questionnaire-cron.integ.ts
jest から vitest 利用への移行はとてもありがたい :+1:

2024-08-20 20:07 UTC, yuki-takei requested changes

2024-08-21 00:20 UTC, arafubeatbox commented on apps/app/src/server/service/config-loader.ts
> +    default: '0 * * * *',
`0 * * * *` は毎時間の意味でした。ただ、cleanup の負荷を考えると10分に1回が良さそうに思ったので、繁栄しますm(_ _)m

2024-08-21 12:52 UTC, arafubeatbox commented on apps/app/src/server/crowi/index.js
> +  pageBulkExportJobCronService.startCron(pageBulkExportJobCronSchedule);
対応しました。
https://github.com/weseek/growi/pull/8974/commits/c24165c2433d8c0043d820e5d002e5a4bdb89c37

2024-08-21 12:53 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron.ts
> +    }
対応しました。
https://github.com/weseek/growi/pull/8974/commits/2674ad24d89d3187b4f8e2bc6ddc6355013beffe

2024-08-22 15:18 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron.ts
> +    }
補足)
export 中は PageBulkExportPageSnapshot が export 対象のページ数分 DB 上にあり、export が中断されると cleanUp 時にこれらが pageBulkExportService.cleanUpExportJobResources の実行により一括削除されます。

最初これの削除が並列で実行されるのは良く無いかなと思っていましたが、
- cronjob が 10 分おきに実行され、定期的に cleanUp されること
- https://github.com/weseek/growi/pull/9031 によって並列で実行される export job が制限されること (9031 では上限を 5 に設定しています)

を考えると、武井さんのいうように cronjob 側で Promise 数を制御する必要はないかなと思いました。

また、もし PageBulkExportPageSnapshot の一括削除の負荷の最大値を下げたい場合は、
https://github.com/weseek/growi/blob/812f0b8dd31baaa5132b50aa3b2e438a9cde7a95/apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts#L155
での deleteMany の実行を分割する方が得策かなと思いました。

2024-08-26 06:23 UTC, merged