support: Sidebar header text size
weseek/growi pull request #8986
Opened 2024-07-23 05:53 UTC by satof3

# Task
https://redmine.weseek.co.jp/issues/150156

# Summary
- サイドバー中のヘッダーの文字サイズを小さくし、フォントウェイトを上げた
- 文字の大きさのためにh4にしていたタグをh1に変更し、Bsのクラスでテキストサイズを指定している
- サイドバータグにおいてはヘッダーの位置を他のものと揃え統一させた
- 上記変更に伴い、reload ボタンのフォントサイズも調整

<img width="305" alt="image" src="https://github.com/user-attachments/assets/e770a9aa-d5b9-4e2e-ace4-c43283504080">
<img width="304" alt="image" src="https://github.com/user-attachments/assets/b8e57eea-6b50-4d96-884d-10674a84d445">

# Note
- [Figma](https://www.figma.com/proto/ZiEcjZ8sYt6YvowboA5Um6/GROWI-v7?page-id=450%3A88&node-id=1236-3119&viewport=-814%2C1109%2C0.23&t=C2u74xmPP1PTMx4V-1&scaling=min-zoom&content-scaling=fixed)
- サイドバーのページタイトルのテキストサイズは #8965 で変更しておりそれがマージされると見え方が変わる
  - ヘッダー16px ページタイトル14px(元:16px)となる

2024-07-23 11:04 UTC, yuki-takei requested changes

2024-07-23 11:04 UTC, yuki-takei commented on apps/app/src/client/components/Sidebar/Bookmarks.tsx
h1 は多用しない方がよいです
https://mieru-ca.com/blog/h1tag/

フォントサイズを `fs-*` で指定するのであれば、タグは hX じゃなくてもいい説ある

2024-07-24 10:09 UTC, satof3 commented on apps/app/src/client/components/Sidebar/Bookmarks.tsx
https://github.com/weseek/growi/blob/master/apps/app/src/client/components/Sidebar/SidebarContents.module.scss#L4
で文字の色が付けられているのでhX は維持し、見出しではあることから`h2`としました

2024-07-24 16:48 UTC, yuki-takei commented on apps/app/src/client/components/Sidebar/Bookmarks.tsx
h3 以下にしてください
https://chatgpt.com/share/a13b7171-329c-40a7-8f72-6d75d00a50dc

2024-07-25 05:55 UTC, satof3 commented on apps/app/src/client/components/Sidebar/Bookmarks.tsx
GPT-4o に引っ掛けでh3タグも文章に含めて質問してみましたがh3タグ以下で良いみたいです
<img width="935" alt="image" src="https://github.com/user-attachments/assets/b7312a31-62f1-42c9-adc5-8d99de2b0f08">
h3タグに置き換えました

2024-07-25 06:16 UTC, merged