imprv: Update dependencies due to unified package upgrade
weseek/growi pull request #8995
Opened 2024-07-26 07:39 UTC by reiji-h

# Summary
- unified のパッケージアップグレードに伴うエラーの解消

# Task
- https://redmine.weseek.co.jp/issues/148445
  - https://redmine.weseek.co.jp/issues/150079

2024-08-06 01:25 UTC, miya commented on packages/presentation/src/client/services/renderer/extract-sections.ts
> +function wrapWithSection(parentNode: Parent, startElem: Node, endElem: Node | undefined | null, isDarkMode?: boolean): void {
`endElem?: Node | null` で書けそう？

2024-08-06 01:25 UTC, miya commented on packages/remark-drawio/src/services/renderer/remark-drawio.ts
> +function isDrawioBlock(lang: string | undefined | null): lang is Lang {
`lang?: string | null` で書けそう？

2024-08-06 02:47 UTC, reiji-h commented on packages/presentation/src/client/services/renderer/extract-sections.ts
> +function wrapWithSection(parentNode: Parent, startElem: Node, endElem: Node | undefined | null, isDarkMode?: boolean): void {
書き換えました。

2024-08-06 02:47 UTC, reiji-h commented on packages/remark-drawio/src/services/renderer/remark-drawio.ts
> +function isDrawioBlock(lang: string | undefined | null): lang is Lang {
書き換えました。

2024-08-06 11:14 UTC, yuki-takei requested changes
- import 文の as 利用は OK
- memolized component の `as typeof` 利用も OK
- 処理ステートメント中の as (たとえば `(node as Code)` など) は、こんなに多用しないといけないのはなんか釈然としない
    - type guard とかないのか？
    - ないなら作ってはどうか？as Parent や as Code のケースが多そうなのである程度共通化もできそう

2024-08-13 09:37 UTC, yuki-takei requested changes

2024-08-13 09:37 UTC, yuki-takei commented on apps/app/src/services/renderer/remark-plugins/attachment.ts
> +}
## やりたいこと
- rewriteNode で link 要素の Node を全く別物(オリジナルの attachment 要素)に差し替えたい

## 今やっていること
Link 型の魔改造

## ToBe
Attachment 要素として相応しい typescript を書く

2024-08-13 09:47 UTC, yuki-takei requested changes

2024-08-13 09:47 UTC, yuki-takei commented on apps/app/src/services/renderer/remark-plugins/codeblock.ts
> +        addClassToProperties(element.properties, 'inline');
sanitize の設定を見直すことで class には入れなくても property として扱えると思う

getCommonSanitizeOption を呼んで rehypeSanitizePlugin を作っているところで code 用の設定も入れ込む

2024-08-23 03:45 UTC, reiji-h commented on packages/remark-drawio/src/services/renderer/remark-drawio.ts
> +}
及ぼすようなので他の方法を模索します。

2024-08-23 03:58 UTC, reiji-h commented on apps/app/src/services/renderer/remark-plugins/codeblock.ts
> +        addClassToProperties(element.properties, 'inline');
Sanitize を設定し、property から inline を判断するようにしました。

2024-08-23 07:04 UTC, reiji-h commented on apps/app/src/services/renderer/remark-plugins/attachment.ts
> +}
Link の children[0] の型の PhrasingContent は、今までのコードで想定されている Text の他にも Break や Strong などの型が[ありえます](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8b46b339d7432e545c92cdfee8a461bc3bd6037c/types/mdast/index.d.ts#L286)。そのうち RichAttachment のタイトルとして使用できるのは(以前のコードと同様に) Text や inlineCode などの要素に value を持っている型のみだと判断し、そのように修正しました。

2024-08-26 06:34 UTC, merged