Feat/78039 151411 cancel streams on export job abort
weseek/growi pull request #8997
Opened 2024-07-28 12:37 UTC by arafubeatbox

## task
https://redmine.weseek.co.jp/issues/151411

2024-08-16 06:14 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts
> -}
apps/app/src/features/page-bulk-export/server/service/page-bulk-export/errors.ts に移動

2024-08-26 08:20 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts
> +    this.pageBulkExportJobStreamManager?.destroyJobStream(pageBulkExportJob._id);
job を cleanUp する際、実行中の stream があればそれを停止させる (実行中の stream が無くてもエラーにはならない

2024-08-26 08:27 UTC, yuki-takei requested changes

2024-08-26 08:27 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/page-bulk-export-job-stream-manager.ts
> +    this.jobStreams[jobId.toString()] = stream;
add 時に既に同 ID の stream が存在していたら destroy すべきではないかな

2024-08-26 08:27 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts
> +    this.pageBulkExportJobStreamManager?.destroyJobStream(pageBulkExportJob._id);
`pageBulkExportJobStreamManager?` の `?` 不要では？

2024-08-26 09:34 UTC, merged