enable restarting bulk export
weseek/growi pull request #9020
Opened 2024-08-07 14:35 UTC by arafubeatbox

## task
https://redmine.weseek.co.jp/issues/151978

## screenshot
![image](https://github.com/user-attachments/assets/acdb863d-0ebb-4361-b853-061051affdca)

2024-08-07 14:37 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/client/components/PageBulkExportSelectModal.tsx
> +              {/* <button className="btn btn-primary ms-2" type="button" onClick={() => startBulkExport(PageBulkExportFormat.pdf)}>PDF</button> */}
pdf 形式は一旦リリースを見送るため、コメントアウト

2024-08-26 11:38 UTC, yuki-takei requested changes

2024-08-26 11:38 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/client/components/PageBulkExportSelectModal.tsx
> +        setIsRestartModalOpened(true);
重複している job の情報の一部をエラーに追加し、それをモーダルに追加表示させよう。
そうすることでユーザーが中断すべきかどうかを判断しやすくなると思う。

(以下一例)
- 作成日時
- トリガーしたユーザー
- その他表示した方がいい情報があれば

2024-08-26 11:52 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/client/components/PageBulkExportSelectModal.tsx
> +        setIsRestartModalOpened(true);
後続タスクで実装しますm(_ _)m
https://redmine.weseek.co.jp/issues/153064

2024-08-26 11:53 UTC, merged