imprv: translation modification
weseek/growi pull request #9035
Opened 2024-08-20 06:12 UTC by maeshinshin

task: https://redmine.weseek.co.jp/issues/152730

2024-08-20 20:41 UTC, yuki-takei requested changes

2024-08-20 20:41 UTC, yuki-takei commented on apps/app/src/pages/utils/commons.ts
> +
これを作るなら getLocaleAtServerSide も getLangAtServerSide を利用するように変更してください

2024-08-21 10:33 UTC, miya requested changes

2024-08-21 10:33 UTC, miya commented on packages/core/src/interfaces/locale.ts
> +export type Locale = 'ja-JP' | 'en-US' | 'zh-CN' | 'fr-FR';
AllLocale という配列から Locale 相当の型が作れそう

2024-08-21 10:33 UTC, miya commented on apps/app/src/pages/utils/commons.ts
> +  [Lang.fr_FR]: 'fr-FR' as Locale,
このアサーションいらなそう？

2024-08-21 10:33 UTC, miya commented on apps/app/src/pages/_app.page.tsx
> +  const userLocale = getLocaleAtServerSide(appContext.ctx.req as unknown as CrowiRequest) as Locale;
アサーション (as Locale) 不要そう

2024-08-21 10:50 UTC, miya approved these changes

2024-08-22 00:44 UTC, merged