fix: Input text becomes empty when opening the ReadOnlyEditor
weseek/growi pull request #9059
Opened 2024-09-02 06:17 UTC by miya

## Task
- [#153286](https://redmine.weseek.co.jp/issues/153286) 過去の revision を Editor mode で開いた時に Editor が空白になってしまう
  - [#153287](https://redmine.weseek.co.jp/issues/153287) 修正

2024-09-02 06:40 UTC, miya commented on packages/editor/src/client/components/CodeMirrorEditorReadOnly.tsx
> +    EditorView.editable.of(false),
(スコープ外) ReadOnlyEditor ではカーソルは不要なのでカーソル消すための Extension を追加
参考: https://discuss.codemirror.net/t/hide-cursors-and-prevent-selection-in-readonly/4815

2024-09-02 06:40 UTC, miya commented on packages/editor/src/client/components/CodeMirrorEditorReadOnly.tsx
> +      cmProps={{}}
## バグの原因
useCodeMirrorEditorIsolated は CodeMirrorEditor.tsx で初期化される。
https://github.com/weseek/growi/blob/52dcf96d1d020c4d354659851d7a9937bd11f1d8/packages/editor/src/client/components-internal/CodeMirrorEditor/CodeMirrorEditor.tsx#L70

useCodeMirrorEditorIsolated の第3引数に undefined が入ることで shouldUpdate フラグが false になり初期化されていなかった。
https://github.com/weseek/growi/blob/52dcf96d1d020c4d354659851d7a9937bd11f1d8/packages/editor/src/client/stores/codemirror-editor.ts#L36-L45

そのため initDoc() や appendExtensions() などのメソッドが有効になっていなかった。

2024-09-02 06:40 UTC, miya commented on packages/editor/src/client/components/CodeMirrorEditorReadOnly.tsx
> +      cmProps={{}} // Do not pass undefined when initializing useCodeMirrorEditorIsolated
## バグの原因
useCodeMirrorEditorIsolated は CodeMirrorEditor.tsx で初期化される。
https://github.com/weseek/growi/blob/52dcf96d1d020c4d354659851d7a9937bd11f1d8/packages/editor/src/client/components-internal/CodeMirrorEditor/CodeMirrorEditor.tsx#L70

useCodeMirrorEditorIsolated の第3引数に undefined が入ることで shouldUpdate フラグが false になり初期化されていなかった。
https://github.com/weseek/growi/blob/52dcf96d1d020c4d354659851d7a9937bd11f1d8/packages/editor/src/client/stores/codemirror-editor.ts#L36-L45

そのため initDoc() や appendExtensions() などのメソッドが有効になっていなかったことが今回のバグの原因。

2024-09-02 06:40 UTC, miya commented on packages/editor/src/client/components/CodeMirrorEditorReadOnly.tsx
> +      cmProps={{}} // Do not pass undefined when initializing useCodeMirrorEditorIsolated
shouldUpdate のロジックの中で `props` を見ないという実装方法もあると思います。

2024-09-02 12:04 UTC, yuki-takei requested changes

2024-09-02 12:04 UTC, yuki-takei commented on packages/editor/src/client/components/CodeMirrorEditorReadOnly.tsx
> +      cmProps={{}} // Do not pass undefined when initializing useCodeMirrorEditorIsolated
> shouldUpdate のロジックの中で props を見ないという実装方法もあると思います。

こっちの方がいいね

2024-09-03 01:11 UTC, miya commented on packages/editor/src/client/components/CodeMirrorEditorReadOnly.tsx
> +      cmProps={{}} // Do not pass undefined when initializing useCodeMirrorEditorIsolated
修正しました
commit: https://github.com/weseek/growi/pull/9059/commits/59bbac27606cd31d31406e21e3a22ee20ccbb323

2024-09-03 01:29 UTC, merged