fix: Updated content is not reflected on the View screen even after refreshing the page
weseek/growi pull request #9086
Opened 2024-09-10 03:55 UTC by miya

## Task
- [#153759](https://redmine.weseek.co.jp/issues/153759) ページを更新しても View 画面に更新内容が反映されない
  - [#153770](https://redmine.weseek.co.jp/issues/153770) 修正

2024-09-10 09:10 UTC, miya commented on apps/app/src/stores/page.tsx
> -    if (cachedData.revision?._id != null && initialData.revision?._id != null && cachedData.revision._id !== initialData.revision._id) {
ページ更新時にもここが実行され、最後に getServerSideProps が実行された時 (対象ページに遷移時) の initialData が入ってしまうことで、ページ更新時に古い revisionBody が View に表示されてしまっていた。

2024-09-10 10:49 UTC, yuki-takei requested changes

2024-09-10 10:49 UTC, yuki-takei commented on apps/app/src/stores/page.tsx
>    // Problem 1: https://github.com/weseek/growi/pull/7772/files#diff-4c1708c4f959974166c15435c6b35950ba01bbf35e7e4b8e99efeb125a8000a7
Problem にこの問題へのリンクも追加した方がよさそう

2024-09-11 02:25 UTC, miya commented on apps/app/src/stores/page.tsx
>    // Problem 1: https://github.com/weseek/growi/pull/7772/files#diff-4c1708c4f959974166c15435c6b35950ba01bbf35e7e4b8e99efeb125a8000a7
追加しました

2024-09-11 02:26 UTC, miya reviewed
@mergify queue

2024-09-11 02:33 UTC, miya reviewed
@mergify queue

2024-09-11 02:34 UTC, miya commented on apps/app/src/stores/page.tsx
>    // Problem 1: https://github.com/weseek/growi/pull/7772/files#diff-4c1708c4f959974166c15435c6b35950ba01bbf35e7e4b8e99efeb125a8000a7
@mergify queue

2024-09-11 04:06 UTC, yuki-takei commented
@mergify queue

2024-09-11 04:10 UTC, merged