fix: the issue that grant of pages can be changed via api even if restricted
weseek/growi pull request #9087
Opened 2024-09-10 05:10 UTC by WNomunomu

## タスク
https://redmine.weseek.co.jp/issues/134084  
https://redmine.weseek.co.jp/issues/134085
## 概要

 
## 変更点

## セルフチェック
- [x] コンフリクト解消したか
- [x] 余計なコードは残っていないか
- [x] 適切にメモ化したか
- [x] 責務の問題はクリアしているか
- [x] CIは通っているか
- [x] PRの内容は適切にかけているか

2024-09-10 06:33 UTC, miya requested changes

2024-09-10 08:34 UTC, miya requested changes

2024-09-10 08:34 UTC, miya commented on apps/app/src/server/routes/apiv3/page/update-page.ts
> +      if (grant && grant !== currentPage.grant && isGrantImmutable) {
grant は null チェックをする

2024-09-12 09:07 UTC, yuki-takei commented
@mergify queue

2024-09-12 09:13 UTC, merged