fix: Shared page is not displayed
weseek/growi pull request #9089
Opened 2024-09-10 10:37 UTC by miya

## Task
- [#153811](https://redmine.weseek.co.jp/issues/153811) [issue] グループのみ閲覧可能なページの共有リンクのコンテンツが表示されない
  - [#153815](https://redmine.weseek.co.jp/issues/153815) 修正

2024-09-10 11:02 UTC, miya commented on apps/app/src/server/routes/apiv3/page/index.ts
> +    }
この API に shared page を返却する処理が書かれていなかったため getServerSideProps ででやっている相当の処理を追加しました。

## 参考
https://github.com/weseek/growi/blob/8fc33a0e9a0dfa1bf8b917ba04f69e3422e24491/apps/app/src/pages/share/%5B%5B...path%5D%5D.page.tsx#L235-L241

2024-09-10 11:18 UTC, yuki-takei requested changes

2024-09-10 11:18 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/index.ts
>      }
validation が足りない

- (pageId or path) と shareLinkId を同時に指定できてはいけない
    - shareLinkId が存在する時は pageId or path は指定されていてはいけない(400 を返す)
- isSharedPage が true なら、shareLinkId は not null でなければならない
    - さもなくば `ShareLink.findOne()` によって取れてはいけないデータが取れてしまう
    - middleware で保証されているのであれば、res.apiv3Err を返す必要はなく、単に 500 (throw new Error)でよい

2024-09-10 11:18 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/index.ts
> +    }
revision の populate はこの下の try-catch block に任せる

2024-09-11 07:26 UTC, miya commented on apps/app/src/server/routes/apiv3/page/index.ts
>      }
> (pageId or path) と shareLinkId を同時に指定できてはいけない

certify-shared-page middleware では有効な shareLinkId かどうかを判断するために shareLinkId と pageId を取得する必要があるので validation の条件を以下のように修正しました

```javascript
const isValid = (shareLinkId != null && pageId != null && path == null) || (shareLinkId == null && (pageId != null || path != null));
```

https://github.com/weseek/growi/blob/e7a94cb9902c556852144935d5a80a9631dd0b2f/apps/app/src/server/middlewares/certify-shared-page.js#L9-L13

> isSharedPage が true なら、shareLinkId は not null でなければならない

こちらは修正しました。

2024-09-12 09:10 UTC, yuki-takei requested changes

2024-09-12 09:10 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/page/index.ts
> +        const shareLink = await ShareLink.findOne({ _id: shareLinkId }).populate('relatedPage');
`.populate('relatedPage')` いらないんじゃない？

2024-09-12 09:24 UTC, miya commented on apps/app/src/server/routes/apiv3/page/index.ts
> +        const shareLink = await ShareLink.findOne({ _id: shareLinkId }).populate('relatedPage');
不要でしたので削除しました

2024-09-12 09:47 UTC, miya commented
@mergify queue

2024-09-12 11:27 UTC, yuki-takei commented
@mergify requeue

2024-09-12 11:29 UTC, yuki-takei commented
@mergify queue

2024-09-12 11:34 UTC, merged