imprv: Update Recent Changes when a page is created, updated, or deleted
weseek/growi pull request #9092
Opened 2024-09-11 04:44 UTC by nHigashiWeseek

2024-09-11 08:25 UTC, miya reviewed
## このストーリーのゴール

1. 適当なページを作成
1. サイドバーから RecentChange を開きページ 1 で作成したページが表示されるようにする
1. ページに対するアクション (更新とか削除)
1. 1 で作成されたページが削除された場合は RecentChanges から対象ページが消えるようにする

なので基本的にサーバーサイドのコードの差分は出ない想定です。
ページのアクションが起きたタイミングで useSWRINFxRecentlyUpdated を mutate するようなイメージです。

https://github.com/weseek/growi/blob/e7a94cb9902c556852144935d5a80a9631dd0b2f/apps/app/src/stores/page-listing.tsx#L36-L56

2024-09-12 07:29 UTC, miya requested changes

2024-09-12 07:29 UTC, miya commented on apps/app/src/client/components/PageDeleteModal.tsx
> +  const { mutate: mutateRecentlyUpdated } = useSWRINFxRecentlyUpdated(20, true);
RecentChanges を更新†する責務をこのコンポーネント群に持たせるのは少し違うかなと感じます。

一例ですが usePageDeleteModal() には open というメソッドを持っていて onDeleted というページ削除時に実行される処理を渡すことができるオプションがあります。そこに recent changes を mutate するメソッドを渡すようにしたいです。
https://github.com/weseek/growi/blob/e25be0382777e0100735252fb4d8d63288b4026c/apps/app/src/client/components/PageList/PageListItemL.tsx#L155

`mutatePageTree` (ページツリーの更新) で全文検索してヒットしたところに一緒に書くイメージです。

2024-09-16 09:28 UTC, yuki-takei requested changes

2024-09-16 09:28 UTC, yuki-takei commented on apps/app/src/client/components/DescendantsPageList.tsx
> +  const { mutate: mutateRecentlyUpdated } = useSWRINFxRecentlyUpdated(20, true);
これは更新の仕組みとしてあまりよくない。

## SWR の revalidate について
今回変更を加えている箇所全てに言えることだが、useSWRINFxRecentlyUpdated に渡す引数の値は useSWRInfinite のキーに使われてしまっているので、更新トリガーを引くこのコンポーネントでも「更新対象で入力している引数と同じ値」を正確に入れる必要が生じてしまっている。つまり RecentChangesSubstance で入れている `limit: 20, includeWipPage: true` をそのまま入れなければいけないということだが、本来 DescendantsPageList をはじめ更新トリガーを引く側のコンポーネント群はそれを知る由もない。これは更新の仕組みとして破綻している。

## やりたいこと
`limit: 20, includeWipPage: true` という値など気にせず useSWRINFxRecentlyUpdated を revalidate したい

## 改修案
`page-listing.tsx` で export している `mutatePageList` や `mutatePageTree` のように、キーの一部に一致する SWR を全て mutate するようなユーティリティメソッドを新たに追加実装した方がよさそう

2024-09-25 09:44 UTC, miya commented on apps/app/src/stores/page-listing.tsx
> +      mutations.push(mutate(key));
mutate する

2024-09-25 09:45 UTC, miya commented on apps/app/src/stores/page-listing.tsx
> +      mutations.push(mutate(key));
mutate の戻り値を配列に入れるのはなぜでしょうか？

2024-09-25 10:09 UTC, nHigashiWeseek commented on apps/app/src/stores/page-listing.tsx
> +      mutations.push(mutate(key));
不要なので消しました

2024-09-29 16:45 UTC, yuki-takei requested changes

2024-09-29 16:45 UTC, yuki-takei commented on apps/app/src/stores/page-listing.tsx
> +export const mutateRecentlyUpdated = async(): Promise<undefined> => {
公式に則ったやり方で revalidate してください
https://swr.vercel.app/docs/pagination#global-mutate-with-useswrinfinite

2024-10-01 22:48 UTC, yuki-takei requested changes

2024-10-01 22:48 UTC, yuki-takei commented on apps/app/src/stores/page-listing.tsx
> +export const mutateRecentlyUpdated = async(): Promise<undefined> => {
やり方が違う

まず cache.keys() を for で走査するのをやめる (公式にそんなやり方書いてないよね？)

```
mutate(unstable_serialize(getKey))
```

この形になるはず。getKey が何者なのかはドキュメントを読んでください。
そして useSWRINFxRecentlyUpdated では getKey にあたるものは何なのかということを考え、共通化し、それを用いて mutateRecentlyUpdated を実装してください。

2024-10-03 09:37 UTC, yuki-takei requested changes

2024-10-03 09:37 UTC, yuki-takei commented on apps/app/src/stores/page-listing.tsx
> +    limit: number,
limit がキーのシリアライズの足枷になるので、キー配列の要素からは外しましょう。
RecentChangesSubstance.tsx の PER_PAGE は useSWRINFxRecentlyUpdated  内に移す。
つまりほぼハードコードで、この hook 利用時は常にページサイズ20とする。

2024-10-03 09:37 UTC, yuki-takei commented on apps/app/src/stores/page-listing.tsx
> +  ));
global mutate は OK :+1:

2024-10-04 07:54 UTC, yuki-takei approved these changes

2024-10-04 08:07 UTC, merged