fix: Ensure text-only paste for mixed content from various sources
weseek/growi pull request #9096
Opened 2024-09-11 07:35 UTC by reiji-h

# Summary
- 画像とテキストが混在している場合、テキストのみを貼り付けるように変更

# Task
- https://redmine.weseek.co.jp/issues/153810
  - https://redmine.weseek.co.jp/issues/153820

# issue
#9016

2024-09-23 22:24 UTC, miya commented on packages/editor/src/consts/paste-mode.ts
> +export const DEFAULT_PASTE_MODE = 'both';
PasteMode.both の方が良さそう

2024-09-23 22:24 UTC, miya commented on apps/app/src/client/components/PageEditor/OptionsSelector.tsx
> +                data={t(`page_edit.paste.${editorSettings.pasteMode ?? 'both'}`) ?? ''}
?? PasteMode.both を使った方が良さそう

2024-09-23 22:24 UTC, miya commented on packages/editor/src/client/stores/use-editor-settings.ts
> +      if (editorSetings?.pasteMode !== 'text' && onUpload != null && event.clipboardData.types.includes('Files')) {
PasteMode を使おう

2024-09-23 22:24 UTC, miya commented on packages/editor/src/client/stores/use-editor-settings.ts
> +      if (editorSetings?.pasteMode !== 'file' && event.clipboardData.types.includes('text/plain')) {
PasteMode を使おう

2024-09-23 22:24 UTC, miya approved these changes

2024-09-27 05:23 UTC, reiji-h commented on packages/editor/src/consts/paste-mode.ts
> +export const DEFAULT_PASTE_MODE = 'both';
修正しました

2024-09-27 05:27 UTC, reiji-h commented on apps/app/src/client/components/PageEditor/OptionsSelector.tsx
> +                data={t(`page_edit.paste.${editorSettings.pasteMode ?? 'both'}`) ?? ''}
修正しました

2024-09-27 05:31 UTC, reiji-h commented on packages/editor/src/client/stores/use-editor-settings.ts
> +      if (editorSetings?.pasteMode !== 'text' && onUpload != null && event.clipboardData.types.includes('Files')) {
修正しました。

2024-09-27 05:31 UTC, reiji-h commented on packages/editor/src/client/stores/use-editor-settings.ts
> +      if (editorSetings?.pasteMode !== 'file' && event.clipboardData.types.includes('text/plain')) {
修正しました。

2024-09-29 18:38 UTC, yuki-takei commented
スクリーンショットをください

2024-09-29 18:44 UTC, yuki-takei requested changes

2024-09-29 18:44 UTC, yuki-takei commented on packages/editor/src/client/stores/use-editor-settings.ts
> +  }, [codeMirrorEditor, editorSetings?.pasteMode, onUpload]);
この処理は view の責務なので stores に入れないでください

2024-09-30 05:43 UTC, reiji-h commented on packages/editor/src/client/stores/use-editor-settings.ts
> +  }, [codeMirrorEditor, editorSetings?.pasteMode, onUpload]);
CodeMirrorEditor に戻しました。変数名がおかしかったのでそこは直しました。(`useEditorSetings` -> `useEditorSettings`)

2024-10-02 14:25 UTC, yuki-takei approved these changes

2024-10-03 08:43 UTC, yuki-takei commented
@mergify requeue

2024-10-03 08:48 UTC, yuki-takei commented
@mergify queue

2024-10-03 09:04 UTC, yuki-takei commented
@mergify queue

2024-10-03 09:05 UTC, yuki-takei commented
@mergify requeue

2024-10-03 09:20 UTC, merged