Corrected wording on admin page (/admin/data-transfer)
weseek/growi pull request #9098
Opened 2024-09-11 08:38 UTC by shironegi39

2024-09-12 05:44 UTC, shironegi39 commented on apps/app/public/static/locales/ja_JP/commons.json
> +    "transfer_to_growi_cloud": "※ 詳しくは <a href='https://{{growiDataTransferHelpPage}}/ja/admin-guide/management-cookbook/g2g-transfer.html'>こちら</a>"
`https://{{growiDataTransferHelpPage}}/ja/admin-guide/management-cookbook/g2g-transfer.html`
として、後続ストーリーで en ページができた際に、日本語以外の path の ja 部分を変更すると en に変更すると英語ページに遷移できる想定です

2024-09-12 06:29 UTC, miya requested changes

2024-09-12 06:29 UTC, miya commented on apps/app/src/client/components/Admin/G2GDataTransfer.tsx
> +
このロジックは GROWI 全体で使えそうなロジックなので、useGrowiCloudUri と useGrowiAppIdForGrowiCloud を見て growi.cloud/help か docs.growi.org を返却してくれるカスタム Hook を作ったほうがいいかもしれません。

### 参考
https://github.com/weseek/growi/blob/e25be0382777e0100735252fb4d8d63288b4026c/apps/app/src/stores-universal/context.tsx#L211-L288

2024-09-12 06:29 UTC, miya commented on apps/app/public/static/locales/ja_JP/commons.json
> +    "transfer_to_growi_cloud": "※ 詳しくは <a href='https://{{growiDataTransferHelpPage}}/ja/admin-guide/management-cookbook/g2g-transfer.html'>こちら</a>"
- `growiDataTransferHelpPage` という変数名には少し違和感があります
- growi.cloud/help or  docs.growi.org が来るのであればドメイン名なのでそのニュアンスに修正お願いします

2024-09-12 06:48 UTC, shironegi39 commented on apps/app/public/static/locales/ja_JP/commons.json
> +    "transfer_to_growi_cloud": "※ 詳しくは <a href='https://{{growiDataTransferHelpPage}}/ja/admin-guide/management-cookbook/g2g-transfer.html'>こちら</a>"
`growiHelpUrl`
に変更しました

2024-09-12 08:14 UTC, shironegi39 commented on apps/app/src/stores-universal/context.tsx
> +  return useSWRImmutable(
GROWI_CLOUD_URI, GROWI_APP_ID_FOR_GROWI_CLOUD
は変わることはないと思い Immutable にしています

2024-09-12 08:38 UTC, shironegi39 commented on apps/app/src/client/components/Admin/G2GDataTransfer.tsx
> +
作成しました

2024-09-12 10:01 UTC, miya commented on apps/app/public/static/locales/ja_JP/commons.json
> +    "transfer_to_growi_cloud": "※ 詳しくは <a href='https://{{growiDataTransferHelpPage}}/ja/admin-guide/management-cookbook/g2g-transfer.html'>こちら</a>"
すみません、growi.cloud/help もあるのでドメインではなかったですね.. `documentationUrl` などはどうでしょうか？

2024-09-12 10:04 UTC, miya approved these changes

2024-09-12 10:04 UTC, miya commented on apps/app/src/stores-universal/context.tsx
> +    [growiCloudUri, growiAppIdForGrowiCloud],
これより上に `const key = "growiDocumentationUrl"` のような key を作って useSWRImmutable の配列に入れるようにしてください

2024-09-12 10:10 UTC, merged

2024-09-13 01:13 UTC, shironegi39 commented on apps/app/src/stores-universal/context.tsx
> +export const useGrowiHelpDomain = (): SWRResponse<'growi.cloud/help' | 'docs.growi.org', Error> => {
`useGrowiDocumentationUrl `
に変更しました

2024-09-13 01:28 UTC, shironegi39 commented on apps/app/src/stores-universal/context.tsx
> +    [growiCloudUri, growiAppIdForGrowiCloud],
他の Hook を見ると
`['growiDocumentationUrl', growiCloudUri, growiAppIdForGrowiCloud]`
でも行けそうなので、こちらの変更しました