fix: the issue users can browse the content of revision in history of particular page when broken revision document exists
weseek/growi pull request #9099
Opened 2024-09-11 09:03 UTC by WNomunomu

## タスク
- [#151652](https://redmine.weseek.co.jp/issues/151652) 壊れた revision document が存在する場合、特定のページの History で壊れた revision の内容を閲覧することができてしまう
  -  [#153892](https://redmine.weseek.co.jp/issues/153892) 修正
## 概要
- 

## 変更点
- 

## セルフチェック
- [x] コンフリクト解消したか
- [x] 余計なコードは残っていないか
- [x] 適切にメモ化したか
- [x] 責務の問題はクリアしているか
- [x] CIは通っているか
- [x] PRの内容は適切にかけているか

2024-09-23 23:34 UTC, miya approved these changes

2024-09-24 08:23 UTC, yuki-takei requested changes

2024-09-24 08:23 UTC, yuki-takei commented on apps/app/src/client/components/PageHistory/PageRevisionTable.tsx
> +const REVISION_BROKEN_BEFORE = new Date('2023-06-07T23:45:20.348+0000');
この日時は DB から取得しないといけない

2024-09-24 08:24 UTC, yuki-takei commented
ストーリーに
> History ではそれ以前に作成された revision を取得しないようにする
とあるように、データを絞るのはバックエンドでやらないといけないです

2024-09-24 08:32 UTC, yuki-takei commented
@mergify dequeue

2024-10-03 07:06 UTC, miya requested changes

2024-10-03 07:06 UTC, miya commented on apps/app/src/server/routes/apiv3/revisions.js
> +      const revisions = paginateResult.docs.filter(isNotBrokenRevision);
これって有効なコード？

isNotBrokenRevision() の戻り値って boolean だよね。Array.prototype.filter() の第一引数には callbackFn が入るはずだけど。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2024-10-03 07:13 UTC, miya requested changes

2024-10-03 07:13 UTC, miya commented on apps/app/src/server/routes/apiv3/revisions.js
> +      const migration = await migrationCollection.findOne({ MIGRATION_FILE_NAME });
これで対象の document ってとってこれるのかな？ ファイルネームが書いてある migration document のフィールド値って fileName だけど

2024-10-03 09:30 UTC, WNomunomu commented on apps/app/src/server/routes/apiv3/revisions.js
> +      const migration = await migrationCollection.findOne({ MIGRATION_FILE_NAME });
こちら修正しました。

2024-10-03 09:35 UTC, WNomunomu commented on apps/app/src/server/routes/apiv3/revisions.js
> +      const revisions = paginateResult.docs.filter(isNotBrokenRevision);
有効なコードです。

Array.prototype.filter()の第一引数には「引数として配列の要素を取り、booleanを返すcallbackFn」が入ります。
isNotBrokenRevision はこの条件を満たします。

![Uploading image.png…]()

2024-10-03 10:00 UTC, miya approved these changes

2024-10-03 10:00 UTC, miya commented on apps/app/src/server/routes/apiv3/revisions.js
> +      const revisions = paginateResult.docs.filter(isNotBrokenRevision);
これは勘違いでした。ごめんなさい。

2024-10-03 11:56 UTC, miya approved these changes

2024-10-03 11:56 UTC, miya commented on apps/app/src/server/routes/apiv3/revisions.js
> +        createdAt: { $gt: appliedAt },
なぜこういうクエリにしないといけないか、という情報が無いのでストーリーの URL をソースコードにコメントしておいた方がいいかも。

2024-10-04 01:47 UTC, WNomunomu commented on apps/app/src/server/routes/apiv3/revisions.js
> +        createdAt: { $gt: appliedAt },
良い変数名が思いつかなかったので、ストーリーのURLをコメントとして追記させていただきました。

2024-10-04 07:52 UTC, yuki-takei requested changes

2024-10-04 07:52 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/revisions.js
> +const MIGRATION_FILE_NAME = '20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js';
将来的にこのファイルは js から ts に変わる可能性があるので、`.js` は削り、migrationCollection から find する時には前方一致で検索するようにしてください

2024-10-04 07:52 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/revisions.js
> +      const appliedAt = migration.appliedAt;
appliedAt の日付はサーバーを起動してから一度取得したらもう変化しないはず。

この API が叩かれた時に毎回このクエリを発行する必要はないので、オンメモリで保持するような実装に変えてください。

2024-10-07 12:44 UTC, WNomunomu commented on apps/app/src/server/routes/apiv3/revisions.js
> +const MIGRATION_FILE_NAME = '20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js';
正規表現を用いて、前方一致で検索するようにしました。

2024-10-07 14:13 UTC, yuki-takei approved these changes

2024-10-07 14:26 UTC, merged