Revert "Revert "Merge pull request #9098 from weseek/imprv/144244-153…
weseek/growi pull request #9106
Opened 2024-09-12 10:19 UTC by miya

…642-corrected-wording-on-management-screeen""

This reverts commit 5511beb789e5152090f5563bcacee3366acea281.

2024-09-19 08:56 UTC, yuki-takei requested changes

2024-09-19 08:56 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/commons.json
> +    "transfer_to_growi_cloud": "※ 詳しくは <a href='https://{{documentationUrl}}/ja/admin-guide/management-cookbook/g2g-transfer.html'>こちら</a>"
「こちら」という文字列にリンクを当てるのはアクセシビリティ的によくないので改善してください
(今回の改修箇所は管理画面なのでそこまで重要なところではないが、一般的な改修水準として)

https://weba11y.jp/know-how/guidelines/descriptive-link-text/

2024-09-19 08:56 UTC, yuki-takei commented on apps/app/src/client/components/Admin/G2GDataTransfer.tsx
> +        <p className="mb-0" dangerouslySetInnerHTML={{ __html: t('commons:g2g_data_transfer.transfer_to_growi_cloud', { documentationUrl }) }} />
documentationUrl が undefined の場合に対応したコードにしてください

2024-09-19 08:56 UTC, yuki-takei commented on apps/app/src/stores-universal/context.tsx
このモジュールは OK

2024-09-19 10:41 UTC, shironegi39 commented on apps/app/public/static/locales/ja_JP/commons.json
> +    "transfer_to_growi_cloud": "※ 詳しくは <a href='https://{{documentationUrl}}/ja/admin-guide/management-cookbook/g2g-transfer.html'>こちら</a>"
`詳しくは <a href=''> GROWI お引越し機能</a>をご確認ください。`
に修正しました

2024-09-20 04:56 UTC, shironegi39 commented on apps/app/src/client/components/Admin/G2GDataTransfer.tsx
> +        <p className="mb-0" dangerouslySetInnerHTML={{ __html: t('commons:g2g_data_transfer.transfer_to_growi_cloud', { documentationUrl }) }} />
`docs.growi.org` 側にたおすようにしました

2024-09-23 15:40 UTC, merged