ref: 114434 CustomNavTab の改修とテスト
weseek/growi pull request #9123
Opened 2024-09-13 04:26 UTC by moekumasaka

2024-09-19 09:11 UTC, yuki-takei requested changes

2024-09-19 09:11 UTC, yuki-takei commented on apps/app/src/client/components/CustomNavigation/CustomNav.module.scss
> +  width: 100%;
- `width: 100%` はユーティリティクラスでどうにかなるはず
- オリジナルのクラスを宣言する必要があるのであれば一般的なクラス名を避けてください

2024-09-24 01:18 UTC, moekumasaka commented on apps/app/src/client/components/CustomNavigation/CustomNav.module.scss
> +  width: 100%;
w-100 を追加するように修正しました。

2024-09-24 08:42 UTC, yuki-takei approved these changes

2024-09-24 08:43 UTC, yuki-takei commented
merge 待ち

2024-09-24 08:54 UTC, merged