fix: Notification count badge
weseek/growi pull request #9124
Opened 2024-09-13 06:57 UTC by shironegi39

2024-09-19 05:56 UTC, shironegi39 commented on apps/app/src/server/service/in-app-notification.ts
> -  };
`STATUS_UNREAD` を廃止に伴い削除

※ 現状の db にある Notification の instance の status は `STATUS_UNREAD` となっていると思います
migration を作成しないとなった際は、この async method を使用し、従来通りの機能を損なわないようにするようになるかと思います(migration script の作成については確認中...)

2024-09-25 05:09 UTC, miya approved these changes

2024-09-25 11:52 UTC, yuki-takei requested changes

2024-09-25 11:52 UTC, yuki-takei commented on apps/app/src/migrations/20240924181317-changed-status-in-inappnotifications-from-unread-to-unopened.js
> +      { status: { $eq: 'UNREAD' } },
細かいけど値は `InAppNotificationStatuses.STATUS_UNREAD` を入れましょう
下の 'UNOPENED' も同じ

2024-09-26 07:14 UTC, shironegi39 commented on apps/app/src/migrations/20240924181317-changed-status-in-inappnotifications-from-unread-to-unopened.js
> +      { status: { $eq: 'UNREAD' } },
string のままでよいとのことなのでそのまま

2024-09-26 07:44 UTC, miya commented
@mergify queue

2024-09-27 06:08 UTC, shironegi39 commented
@mergify queue

2024-09-29 18:32 UTC, merged