fix: Make it impossible to overwrite grants on descendant pages when 'anyone with the link' is selected.
weseek/growi pull request #9125
Opened 2024-09-13 07:12 UTC by WNomunomu

## タスク
- [#153813](https://redmine.weseek.co.jp/issues/153813) [issue] 「更新と同時に全ての配下ページのスコープを上書き」で更新すると、配下の記事にアクセスできなくなる場合がある。
  -  [#153818](https://redmine.weseek.co.jp/issues/153818) 修正
## 概要
- 「リンクを知っている人のみ」の grant が設定されているページや、「リンクを知っている人のみ」を指定して更新する場合に、「更新と同時に全ての配下ページのスコープを上書き」をできなくなるようにしました。

## 変更点
- サーバーサイドでは、shouldBeOnTree が true（i.e. 「リンクを知っている人のみ」ではないページ） でなければ「更新と同時に全ての配下ページのスコープを上書き」が実行されないようにしました。
- フロントエンドでは、「リンクを知っている人のみ」が指定されている場合に「更新と同時に全ての配下ページのスコープを上書き」ボタンが disable になるようにしました。

## セルフチェック
- [x] コンフリクト解消したか
- [x] 余計なコードは残っていないか
- [x] 適切にメモ化したか
- [x] 責務の問題はクリアしているか
- [x] CIは通っているか
- [x] PRの内容は適切にかけているか

2024-10-03 07:25 UTC, miya requested changes

2024-10-03 07:25 UTC, miya commented on apps/app/src/client/components/SavePageControls.tsx
> +                </Disable>
NotAvailable .tsx が用意されているのでこちらを使った方が良さそう (grw-not-available という prefix が class 名に付与されるのでテストしやすそう)

2024-10-03 07:26 UTC, miya approved these changes

2024-10-03 10:01 UTC, WNomunomu commented on apps/app/src/client/components/SavePageControls.tsx
> +                </Disable>
Disable コンポーネントを NotAvailable コンポーネントに置き換えました。

2024-10-07 09:24 UTC, yuki-takei requested changes

2024-10-07 09:24 UTC, yuki-takei commented on apps/app/src/client/components/SavePageControls.tsx
> +import { Disable } from 'react-disable';
これ使ってないのではないか

2024-10-07 12:19 UTC, yuki-takei approved these changes

2024-10-07 12:31 UTC, yuki-takei commented
@mergify requeue

2024-10-07 12:48 UTC, merged