feat: Uunsaved warning in single editor mode
weseek/growi pull request #9126
Opened 2024-09-13 07:44 UTC by miya

## Task
- [#142089](https://redmine.weseek.co.jp/issues/142089) [v7] 文字数の多いページ（Draw.ioなど）の Edit 画面開くと Markdown の内容が表示されない件の修正
  -  [#153653](https://redmine.weseek.co.jp/issues/153653) SingleEditorMode で執筆中に内容を保存せずに離脱しようとした時にアラートを表示させる

2024-09-17 08:42 UTC, yuki-takei requested changes

2024-09-17 08:42 UTC, yuki-takei commented on apps/app/src/client/components/PageEditor/PageEditor.tsx
> +    if (!isYjsEnabled && currentPage != null && currentPage.revision?.body != null && value !== currentPage.revision.body) {
本文のボリュームが大きい場合に `value !== currentPage.revision.body` のコストが高くなるので省いていいと思う

2024-11-25 09:18 UTC, yuki-takei requested changes

2024-11-25 09:18 UTC, yuki-takei commented on apps/app/src/client/components/PageEditor/PageEditor.tsx
> +  }, [isYjsEnabled, mutateUnsavedWarning]);
この useEffect はおかしいんじゃない？
ユーザーの入力とは無関係に isYjsEnabled 値の変更トリガーで mutate される。そのような挙動でいいのか？

2024-11-26 14:38 UTC, miya commented on apps/app/src/client/components/PageEditor/PageEditor.tsx
> +  useUnsavedWarningUtils({ shouldWarnBeforeUnloadOrRouteChaange: unloadOrRouteChaangeHandler });
currentPageRevisionBody !== editingMarkdow の計算コスト削減のため、routeChangeStart イベント or beforeunload イベント時に一回だけ実行できるようにした

2024-11-26 14:38 UTC, miya commented on apps/app/src/client/components/UnsavedAlertDialog.tsx
> +    const shouldWarnBeforeUnloadOrRouteChaange = unsavedWarningUtils?.shouldWarnBeforeUnloadOrRouteChaange();
routeChangeStart イベント or beforeunload イベント発火時にオプショナルで警告を出すか否かをチェックするためのメソッドを実行できるようにした。

2024-11-26 14:38 UTC, miya commented on apps/app/src/client/components/PageEditor/PageEditor.tsx
> +  useUnsavedWarningUtils({ shouldWarnBeforeUnloadOrRouteChaange: unloadOrRouteChaangeHandler });
https://github.com/weseek/growi/pull/9126#discussion_r1762661941 の FB に対応したもの

2024-11-27 07:55 UTC, yuki-takei requested changes

2024-11-27 07:55 UTC, yuki-takei commented on apps/app/src/stores/editor.tsx
> +  shouldWarnBeforeUnloadOrRouteChaange: () => boolean
typo

2024-11-27 07:55 UTC, yuki-takei commented on apps/app/src/client/components/PageEditor/PageEditor.tsx
> +  useUnsavedWarningUtils({ shouldWarnBeforeUnloadOrRouteChaange: unloadOrRouteChaangeHandler });
CommentEditor の方もこの方式に統一した方がいい気がする

2024-11-27 07:57 UTC, yuki-takei commented on apps/app/src/stores/editor.tsx
> +  return useSWRStatic<UnsavedWarningUtils, Error>('unsavedWarningUtils', status);
CommentEditor の方もこれを使えるように、複数登録・解除できるようになっているとよいね

2024-11-28 03:17 UTC, miya commented on apps/app/src/stores/editor.tsx
> +  }, [swrResponse]);
未保存のものがあるかどうかをチェックするためのメソッドを map に登録するメソッド

2024-11-28 03:17 UTC, miya commented on apps/app/src/stores/editor.tsx
> +  }, [swrResponse.data]);
登録された detector を実行し一つでも true が返却されれば未保存のものがあるとし true を返却する

2024-11-28 03:17 UTC, miya commented on apps/app/src/stores/editor.tsx
> +  shouldWarnBeforeUnloadOrRouteChaange: () => boolean
修正しました

2024-11-28 03:18 UTC, miya commented on apps/app/src/stores/editor.tsx
> +  return useSWRStatic<UnsavedWarningUtils, Error>('unsavedWarningUtils', status);
Editor, CommentEditor 問わず key: string ごとに複数のメソッドを登録できるようにしました

2024-11-28 09:02 UTC, yuki-takei requested changes

2024-11-28 09:02 UTC, yuki-takei commented on apps/app/src/stores/editor.tsx
> +  }, [swrResponse]);
mutate の引数は MutatorCallback 型にしたい

2024-11-28 09:02 UTC, yuki-takei commented on apps/app/src/client/components/PageEditor/PageEditor.tsx
> +  const unloadOrRouteChaangeHandler = useCallback(() => {
typo

2024-11-28 09:17 UTC, miya commented on apps/app/src/client/components/PageEditor/PageEditor.tsx
> +  const unloadOrRouteChaangeHandler = useCallback(() => {
修正しました

2024-11-29 00:20 UTC, miya commented on apps/app/src/stores/editor.tsx
> +  }, [swrResponse]);
修正しました

2024-11-29 00:28 UTC, merged