imprv: Add GitHub Markdown Alerts
weseek/growi pull request #9127
Opened 2024-09-13 07:48 UTC by reiji-h

# Summary
- GitHub の Markdown 記法の Alert を追加
参考：https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/

# Task
- https://redmine.weseek.co.jp/issues/153035
  - https://redmine.weseek.co.jp/issues/153036

# ScreenShot
![スクリーンショット 2024-09-10 174017](https://github.com/user-attachments/assets/4062189a-0450-44de-b419-2a355e91bea6)

2024-09-23 22:51 UTC, miya approved these changes

2024-09-27 06:19 UTC, reiji-h commented on apps/app/package.json
> +    "remark-github-admonitions-to-directives": "^2.0.0",
devDependencies に移せそうだったので移しました

2024-09-27 08:53 UTC, reiji-h commented on apps/app/src/features/callout/components/CalloutViewer.tsx
> +          <div className="callout-hint" dangerouslySetInnerHTML={{ __html: githubCallout[name].hint ?? '' }}>
SVG 使うときは必要かと思っていましたが、使わずに実装できました

2024-09-30 06:05 UTC, reiji-h commented on apps/app/src/features/callout/components/CalloutViewer.module.scss
色の扱いをもっと単純にしました。

後続タスクはこちらの作成しました。
https://redmine.weseek.co.jp/issues/154673

2024-10-01 22:39 UTC, yuki-takei requested changes

2024-10-01 22:39 UTC, yuki-takei commented on apps/app/package.json
> +    "remark-github-admonitions-to-directives": "^2.0.0",
移ってないですね

2024-10-01 22:39 UTC, yuki-takei commented on apps/app/src/features/callout/services/consts.tsx
アイコンは svg ではなく material symbols にしてください

タイプとタイトル・アイコンの関連付けは View の責務なので、services ディレクトリに置かないでください

2024-10-03 03:55 UTC, reiji-h commented on apps/app/package.json
> +    "remark-github-admonitions-to-directives": "^2.0.0",
確認不足でした。移しました。

2024-10-03 03:56 UTC, reiji-h commented on apps/app/src/features/callout/services/consts.tsx
service 内の consts には Type 定義のみ
CalloutViewer で Type からタイトル、アイコンに変換するようにしました。

2024-10-03 08:34 UTC, yuki-takei approved these changes

2024-10-03 08:43 UTC, yuki-takei commented
@mergify requeue

2024-10-03 09:01 UTC, merged