feat: Implement api for regenerating vector store
weseek/growi pull request #9133
Opened 2024-09-17 08:58 UTC by miya

## Task
- [#153746](https://redmine.weseek.co.jp/issues/153746) [RAG] 管理画面の OpenAI 設定画面から vector store の再構築ができる
  -  [#153986](https://redmine.weseek.co.jp/issues/153986) vector store 再構築のための API を作成

2024-09-18 08:08 UTC, miya commented on apps/app/src/server/middlewares/certify-ai-service.ts
> +};
AI 機能が利用可能かどうかを判断するための express middleware

2024-09-19 05:36 UTC, miya commented on apps/app/src/server/routes/apiv3/openai/rebuild-vector-store.ts
> +};
- vector store を再作成するためのエンドポイント
- 中身は https://github.com/weseek/growi/pull/9138 で実装しています

2024-09-19 09:24 UTC, yuki-takei requested changes

2024-09-19 09:24 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/admin.json
> +    "rebuild_vector_store_failed": "Vector Store のリビルドに失敗しました"
クリック時に表示するメッセージは成功可否ではなく「リビルドを受け付けた」という内容ではないか？

2024-09-19 09:24 UTC, yuki-takei commented on apps/app/src/server/middlewares/certify-ai-service.ts
> +    return res.apiv3Err(message, 400);
403 かなあ
400 だとパラメータ次第でリクエスト通りそうな印象

2024-09-19 09:24 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/openai/index.ts
> +  router.put('/rebuild-vector-store', rebuildVectorStoreHandlersFactory(crowi));
post でよい

2024-09-19 16:39 UTC, miya commented on apps/app/public/static/locales/ja_JP/admin.json
> +    "rebuild_vector_store_failed": "Vector Store のリビルドに失敗しました"
修正しました

2024-09-19 16:39 UTC, miya commented on apps/app/src/server/middlewares/certify-ai-service.ts
> +    return res.apiv3Err(message, 400);
修正しました

2024-09-19 16:45 UTC, merged