feat: Implement OpenAI client delegator
weseek/growi pull request #9138
Opened 2024-09-18 09:50 UTC by miya

## Task
- [#153746](https://redmine.weseek.co.jp/issues/153746) [RAG] 管理画面の OpenAI 設定画面から vector store の再構築ができる
  -  [#153989](https://redmine.weseek.co.jp/issues/153989) OpenAIService に既存の vector store を削除するロジックを実装

2024-09-19 05:18 UTC, miya commented on apps/app/src/server/routes/apiv3/ai-integration/rebuild-vector-store.ts
> +        }
既存の VectorStoreFile を全て取得して削除

2024-09-19 05:18 UTC, miya commented on apps/app/src/server/routes/apiv3/ai-integration/rebuild-vector-store.ts
> +        // TODO: https://redmine.weseek.co.jp/issues/153988
公開ページの VectorStoreFIle を作成

2024-09-19 05:18 UTC, miya commented on apps/app/src/server/service/openai-client-delegator.ts
> +    }
- AI_SERVICE_TYPE が openai だった場合に必要な環境変数を取得、無ければ throw Error する
- クライアントの初期化もこのブロックで行う

2024-09-19 06:39 UTC, miya commented on apps/app/src/server/service/openai/openai-client-delegator.ts
> +    }
- AI_SERVICE_TYPE が openai だった場合に必要な環境変数を取得、必要な環境変数が無ければ throw Error する
- クライアントの初期化もこのブロックで行う

2024-09-19 06:39 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +    }
- 既存の VectorStoreFile を全て取得して削除

2024-09-19 06:39 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +    // TODO: https://redmine.weseek.co.jp/issues/153988
公開ページの VectorStoreFIle を作成

2024-09-19 06:39 UTC, miya commented on apps/app/src/server/service/openai/openai-client-delegator.ts
> +}
OpenAI、Azure OpenAI の差異を吸収するための delegator

2024-09-19 06:39 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +};
openai-client-delegator.ts を利用するためのサービスメソッド

2024-09-19 10:22 UTC, yuki-takei requested changes

2024-09-19 10:22 UTC, yuki-takei commented on apps/app/src/server/service/openai/openai.ts
> +};
このメソッド export 必須じゃないと思う
コンストラクタか getOpenaiService の中に押し込められるのでは？

2024-09-19 10:31 UTC, yuki-takei requested changes

2024-09-19 10:31 UTC, yuki-takei commented on apps/app/src/server/crowi/index.js
> +  initializeOpenaiService();
ここには個別のサービスの初期化メソッド呼び出しを書きたくない。(soket-io が絡むやつはやむを得ず書いているのはあるが)

対策は後述↓
https://github.com/weseek/growi/pull/9138#discussion_r1766575461

2024-09-19 10:31 UTC, yuki-takei commented on apps/app/src/server/service/openai/openai.ts
> +    }
ページングに対応しないといけない(リストAPIの結果はデフォルト20件のはず)

2024-09-19 17:02 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +};
修正しました
commit: https://github.com/weseek/growi/pull/9138/commits/5f3b4eb068bfdcf265fca1cd946b33d02c8786b5

2024-09-19 17:02 UTC, miya commented on apps/app/src/server/crowi/index.js
> +  initializeOpenaiService();
修正しました
https://github.com/weseek/growi/pull/9138#discussion_r1767255324

2024-09-24 07:43 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +  }
GROWI の公開ページの revisionBody で Vector Store を作成するためのロジック

### 参考
https://github.com/weseek/growi/blob/f7682110a5c312a5e907d41d24021e1b1cc123c9/apps/app/src/server/service/openai/file-upload.ts#L13-L31

2024-09-24 09:46 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +    }
VectorStoreFile の削除は別ストーリーで実装します
ストーリー: https://redmine.weseek.co.jp/issues/154364

2024-09-24 09:55 UTC, miya commented on apps/app/src/server/service/openai/openai-client-delegator.ts
> +}
> Azure 用のサービスの雛形も書いてみてほしい

Azure 利用時も考慮して実装してみました

2024-09-24 11:05 UTC, yuki-takei requested changes

2024-09-24 11:05 UTC, yuki-takei commented on apps/app/src/server/service/openai/openai-client-delegator.ts
> +  private client: OpenAI | AzureOpenAI;
ここは union ではなく型推論が効くようなタイプにしないといけない

2024-09-25 03:19 UTC, miya commented on apps/app/src/server/service/openai/openai-client-delegator.ts
> +  private client: OpenAI | AzureOpenAI;
修正しました
commit: https://github.com/weseek/growi/pull/9138/commits/9a1fbf8083f345756604799ee70a4f18b3fcc8ae

2024-09-25 14:45 UTC, yuki-takei requested changes

2024-09-25 14:45 UTC, yuki-takei commented on apps/app/src/interfaces/ai.ts
OpenAI と互換性のあるサービス2種の切り替えに利用する const ということで改名
(OpenAI と全く互換性がないサービスだとサービス層のコードはほぼまるっと変えることになるはずなので)

2024-09-25 14:45 UTC, yuki-takei commented on apps/app/src/server/service/openai/client-delegator/get-client.ts
> +};
この getClient の何がうれしいかというと、以下のようなコードを書いたときに(つまり引数が明らかな場合に)返り値が OpenaiClientDelegator に推論される

```
const client = getClient({ openaiServiceType: 'openai' });
```

2024-09-25 14:45 UTC, yuki-takei commented on apps/app/src/server/service/openai/openai.ts
> +    return getClient({ openaiServiceType });
ここでは any が入るので残念ながら IOpenaiClientDelegator として返すしかない

2024-09-29 17:02 UTC, yuki-takei approved these changes

2024-09-29 17:03 UTC, merged