fix: Mermaid diagrams fail to render in search results with 'syntax error in text'"
weseek/growi pull request #9145
Opened 2024-09-20 05:24 UTC by reiji-h

# Summary
- 検索結果ページのみで、mermaid が syntax error in text として表示されてしまう問題の修正
- 原因は検索結果ページの検索文字ハイライターによるハイライトタグの挿入
- 上記原因を回避するために、 remark の data.hProperties 経由で mermaid の文字列を送ることで回避した

# Task
- https://redmine.weseek.co.jp/issues/122548
  - https://redmine.weseek.co.jp/issues/153821

2024-09-23 22:42 UTC, miya approved these changes

2024-09-29 18:36 UTC, yuki-takei requested changes

2024-09-29 18:36 UTC, yuki-takei commented on apps/app/src/features/mermaid/services/mermaid.ts
> +  },
なぜ attributes として value が必要になるのか説明してください

2024-09-30 05:15 UTC, reiji-h commented on apps/app/src/features/mermaid/services/mermaid.ts
> +  },
今回のエラーの原因は、検索結果ページの検索文字のハイライトタグが、mermaid ブロックの中に入ったとき、mermaid の文法エラーを引き起こすものでした。よって mermaid ブロックの中身を文字列として value に入れて MermaidViewer に送っています。

children のみでは出来ない理由は、特定の単語がハイライトされると MermaidViewer は children を文字列ではなく React.Element として受け取るためです。React.Element から文字列を復元することは出来なくはないですが、その方法だと、おそらく復元と mermaid の描画するタイミングが合わず出来なかったため、出来ないと判断しました。

![image](https://github.com/user-attachments/assets/9b5e67d2-568f-4627-b49f-0b1ffb473647)

2024-10-10 06:15 UTC, yuki-takei requested changes

2024-10-10 06:15 UTC, yuki-takei commented on apps/app/src/features/mermaid/services/mermaid.ts
> +  },
であれば、もうちょっとやりようがあると思う。このままでは children と value の役割が冗長だし、MermaildViewer で中途半端に使っていたり使っていなかったりするので意図がわからない。

# 案1
MermaidViewerProps の型を変えるというのはやったのだろうか？
ここで children を string に限定すれば ReactMarkdown がよしなにやってくれるのであれば、children に一本化できる。

とはいえこの案は望み薄。

# 案2
案1 でうまくいかない場合は hast 時点まで遡る。
`rewriteNode` 処理 で children を text node にできないのだろうか？

https://github.com/syntax-tree/hast?tab=readme-ov-file#text

これでうまくいけば children に一本化できる。

# 案3
案1, 2両方共うまくいかない場合、hast では text node でも ReactMarkdown のおせっかいにより React.Element 化されるという診断になるか？
それであれば attribute を使う方が string 型になることが保証されるので、children を使わず attribute に一本化すればいいと思う。

2024-10-17 06:27 UTC, reiji-h commented on apps/app/src/features/mermaid/services/mermaid.ts
> +  },
結果として**案3**の採用となりました。

# 案1
string に制限しても React.Element が流れてきたので断念。

# 案2
mdast の Code は value: string しか持てず、任意の型の children を持たないので、node を paragraph にし children に text node を入れる形で実験してみましたが、結果は変わリませんでした。
![image](https://github.com/user-attachments/assets/28f9673b-8eb4-49c4-ad49-02150d5febc5)

そもそも keyword-highlighter は rehype-plugin であり、node のタイプが text のときにキーワードを <em> で挟む処理でした。これを避けるためには mermaid の中身の node のタイプが text ではなく element な必要がありますが、element 化しつつ中身をテキストとして扱える型や方法がなかったので案2 も断念。

2024-10-17 12:33 UTC, yuki-takei approved these changes

2024-10-17 13:02 UTC, merged