feat: Rebuild vector store when updating page
weseek/growi pull request #9172
Opened 2024-09-25 07:54 UTC by miya

## Task
- [#153747](https://redmine.weseek.co.jp/issues/153747) [RAG] ページの更新・削除・公開範囲変更・複製時に vector store の削除・再作成を行い、Assistant が利用するナレッジの入れ替えができる
  - [#154030](https://redmine.weseek.co.jp/issues/154030) ページ更新時に VectorStoreFile の再作成ができる

2024-09-27 09:45 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> -  }
意味がないコードでしたので削除しました

2024-09-27 09:45 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +        const revision = page?.revision as IRevisionHasId;
- 上記の filter によって populate された revision だということが保証されているので IRevisionHasId に assertion 
-  Typescript v5.5 から型推論できるようになるようです
    - 参考: https://zenn.dev/ubie_dev/articles/ts-infer-type-predicates

2024-09-27 09:45 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +};
`AI_EABLED = true` が設定されている時に初期化したインスタンスを export するような実装に改修しました

2024-09-27 09:45 UTC, miya commented on apps/app/src/server/routes/apiv3/page/update-page.ts
> +    }
ページ更新時 (閲覧権限変更時も含む) に VectorStore の再構築を行う

2024-09-27 09:45 UTC, miya commented on apps/app/src/server/routes/apiv3/page/create-page.ts
> +      logger.error('Rebuild vector store failed', err);
ページ作成時に VectorStore の再構築を行う

2024-09-27 09:45 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +      openaiService?.createVectorStoreFile([duplicatedTarget]);
ページ複製時に VectorStore の作成を行う

2024-09-27 09:45 UTC, miya commented on apps/app/src/server/service/page/index.ts
> +    openaiService?.createVectorStoreFile(duplicatedPagesWithPopulatedToShowRevison);
子ページ複製時に VectorStore の作成を行う

2024-09-29 16:28 UTC, yuki-takei requested changes

2024-09-29 16:28 UTC, yuki-takei commented on apps/app/src/server/service/openai/openai.ts
> +        const revision = page?.revision as IRevisionHasId;
5.5 に上げるときにこういうコードにすべきで、それまでは as は使わないでください

2024-09-29 16:28 UTC, yuki-takei commented on apps/app/src/server/service/openai/openai.ts
> +    const allPublicPages = await page.find({ grant: PageGrant.GRANT_PUBLIC }).populate('revision') as PageDocument[];
ES のサービスでやっているように stream にしてページング処理しないとメモリを食い潰す

2024-09-29 16:28 UTC, yuki-takei commented on apps/app/src/server/service/openai/openai.ts
> +      .filter(page => page.grant === PageGrant.GRANT_PUBLIC && page.revision != null && isPopulated(page.revision) && page.revision.body.length > 0)
`page.revision` が populate されている前提でしかこのメソッドが正常に機能しないのはよくない
サービス利用側がそれを気にしないといけないので

2024-09-30 08:44 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +    const allPublicPages = await page.find({ grant: PageGrant.GRANT_PUBLIC }).populate('revision') as PageDocument[];
修正しました
commit: https://github.com/weseek/growi/pull/9172/commits/16fb5cfce0b2fa8245bb851fbce927813b7e3277

2024-09-30 08:45 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +      .filter(page => page.grant === PageGrant.GRANT_PUBLIC && page.revision != null && isPopulated(page.revision) && page.revision.body.length > 0)
populate されていない document があれば populate するように改修しました
commit: https://github.com/weseek/growi/pull/9172/commits/83e2f2fe4b046cf32340814ef5d1566b321567a3

2024-09-30 08:46 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +        const revision = page?.revision as IRevisionHasId;
as を使わない実装に修正しました

2024-10-01 23:18 UTC, yuki-takei commented on apps/app/src/server/service/openai/openai.ts
> +    });
## 後続のリファクタタスク

- `createVectorStoreFileStream` は、updateOrInsertPages での `writeStream` 相当となる
    - Transform ではなく Writable で書けないか試す
    - toFile 呼び出しと client.uploadAndPoll 呼び出しの2つの操作を 1 つの promise とし、それらの promise をarray にまとめたもの(つまり PageDocument[] の数と要素数は一致するはず)を Promise.allSettled で処理し、エラーはログに出す
    - rate limit が気になるが一旦 Promise.allSettled でよいという判断

2024-10-01 23:18 UTC, yuki-takei commented on apps/app/src/server/service/openai/openai.ts
> +    });
## 後続のリファクタタスク

- getFileList() の結果を走査するのはコストが高すぎるので、ページ毎にどの file id と紐付いているのか保管しておかないといけないかもしれない

2024-10-01 23:18 UTC, yuki-takei approved these changes

2024-10-01 23:22 UTC, merged

2024-10-02 02:33 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +    });
## 後続ストーリー
https://redmine.weseek.co.jp/issues/154820

2024-10-02 02:33 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +  async rebuildVectorStoreAll() {
## 後続ストーリー
https://redmine.weseek.co.jp/issues/154821

2024-10-02 02:33 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +    });
##  後続ストーリー
https://redmine.weseek.co.jp/issues/154822

2024-10-02 02:33 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +  rebuildVectorStore(page: PageDocument): Promise<void>;
現時点では外部から呼ぶメソッドのみしかないのでそのままにしています。そうでないものが実装された段階で private にします。