fix/154291-reject requests with invalid format
weseek/growi pull request #9179
Opened 2024-09-27 08:37 UTC by abichan99911111

2024-09-27 08:45 UTC, abichan99911111 commented on apps/app/src/server/routes/apiv3/forgot-password.js
> +    const validEmailRegexp = new RegExp(/^[\w+\-.]+@[a-z\d\-.]+\.[a-z]+$/, 'i');
rexexp は rails tutorial から引っ張ってきました

2024-10-01 06:33 UTC, miya commented on apps/app/src/server/routes/apiv3/forgot-password.js
> +    const validEmailRegexp = new RegExp(/^[\w+\-.]+@[a-z\d\-.]+\.[a-z]+$/, 'i');
FilterXSS は使えないかな？自前実装しなくて済みそう

2024-10-01 08:22 UTC, miya requested changes

2024-10-03 08:50 UTC, reiji-h commented on apps/app/src/server/routes/apiv3/forgot-password.js
> +    const validEmailRegexp = new RegExp(/^[\w+\-.]+@[a-z\d\-.]+\.[a-z]+$/, 'i');
そもそも email かどうかをちゃんと判定すればよかったので、validator を使いました

2024-10-03 09:01 UTC, reiji-h commented on apps/app/src/server/routes/apiv3/forgot-password.js
> +    const validEmailRegexp = new RegExp(/^[\w+\-.]+@[a-z\d\-.]+\.[a-z]+$/, 'i');
また、forgot-password で入力される新しいパスワードの方にも validator を適用しました。

2024-10-03 09:14 UTC, miya approved these changes

2024-10-03 09:19 UTC, reiji-h commented on apps/app/src/server/routes/apiv3/forgot-password.js
> +      }
修正しました。

2024-10-03 12:18 UTC, merged