feat: Make AI chat unavailable to guest users
weseek/growi pull request #9186
Opened 2024-10-02 05:49 UTC by miya

## Task
- [#153750](https://redmine.weseek.co.jp/issues/153750) [RAG][AI chat] ゲストユーザーでは AI chat 機能を使えないようにする
  - [#154432](https://redmine.weseek.co.jp/issues/154432) 実装

2024-10-02 05:53 UTC, miya reviewed
API 周りは既に Express middleware (certifyAiService, loginRequiredStrictly) によって制限されています

2024-10-03 09:09 UTC, yuki-takei requested changes

2024-10-03 09:09 UTC, yuki-takei commented on apps/app/src/client/components/PageControls/RagSearchButton.tsx
> +  }
isAiEnabled が false の時はこれでOK
ゲスト時は NotAvailableForGuest で囲うんじゃないかな

2024-10-03 09:28 UTC, miya commented on apps/app/src/client/components/PageControls/RagSearchButton.tsx
> +  }
修正しました

2024-10-03 09:41 UTC, merged