feat: Generate vector store inside GROWI
weseek/growi pull request #9217
Opened 2024-10-08 10:01 UTC by miya

## Task
- [#155197](https://redmine.weseek.co.jp/issues/155197) [RAG] VectorStore を GROWI 本体で作成できる
  - [#155201](https://redmine.weseek.co.jp/issues/155201) 実装

2024-10-08 10:04 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +    configManager.updateConfigsInTheSameNamespace('crowi', { [configKey]: newVectorStoreId });
DB or 環境変数に値が存在しない場合は新規に VectorStore を作成し、id を DB に保存する

2024-10-08 10:04 UTC, miya commented on apps/app/src/server/service/openai/client-delegator/interfaces.ts
> -  uploadAndPoll(files: Uploadable[]): Promise<OpenAI.Beta.VectorStores.FileBatches.VectorStoreFileBatch>;
不要なメソッドの削除

2024-10-10 06:53 UTC, yuki-takei requested changes

2024-10-10 06:53 UTC, yuki-takei commented on apps/app/src/server/service/openai/openai.ts
> +    configManager.updateConfigsInTheSameNamespace('crowi', { [configKey]: newVectorStoreId });
OpenaiVectorStore model を作成してください

2024-10-10 15:00 UTC, yuki-takei requested changes

2024-10-11 01:36 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +  public async getOrCreateVectorStoreIdForPublicScope(): Promise<string> {
修正しました
commit: https://github.com/weseek/growi/pull/9217/commits/5a0085d5e0bc9d91d3e5bcca325bf09d18a3dc2e

2024-10-11 01:36 UTC, miya commented on apps/app/src/server/service/openai/openai.ts
> +      return vectorStore.vectorStoreId;
修正しました
commit: https://github.com/weseek/growi/pull/9217/commits/5a0085d5e0bc9d91d3e5bcca325bf09d18a3dc2e

2024-10-12 09:49 UTC, merged