feat: Split markdown into specified tokens
weseek/growi pull request #9251
Opened 2024-10-16 07:24 UTC by nHigashiWeseek

2024-10-16 12:28 UTC, yuki-takei requested changes

2024-10-16 12:28 UTC, yuki-takei commented on packages/markdown-splitter/src/services/markdown-token-splitter.ts
> +import { encodingForModel } from 'js-tiktoken'; // eslint-disable-line camelcase
`eslint-disable-line camelcase` は不要では？

2024-10-16 12:28 UTC, yuki-takei commented on packages/markdown-splitter/src/services/markdown-token-splitter.ts
> +      const overlap = Math.ceil(averageCharsPerChunk * 0.05);
overlap はいらなさそう (前後の内容が入らなくても構わないので)

2024-10-16 12:28 UTC, yuki-takei commented on packages/markdown-splitter/test/index.spec.ts
> +    }
これだと、

```
### Header 1.1.1
```

と

```
${longParagraph}
```

がそれぞれ maxTokens を超えないことは保証されるけれど、

```
### Header 1.1.1
${longParagraph}
```

が超えないかどうかは保証されないのではないか？

2024-10-18 08:26 UTC, nHigashiWeseek commented on packages/markdown-splitter/src/services/markdown-token-splitter.ts
> +import { encodingForModel } from 'js-tiktoken'; // eslint-disable-line camelcase
対応しました。

2024-10-18 12:33 UTC, merged