imprv: Error handling for when a thread cannot be created
weseek/growi pull request #9252
Opened 2024-10-16 08:12 UTC by miya

## Task
- [#155005](https://redmine.weseek.co.jp/issues/155005) [RAG] 使われなくなった Thread が自動で削除される
  -  [#155304](https://redmine.weseek.co.jp/issues/155304) thread が作成できなかった場合のエラーハンドリングの改善

2024-10-16 13:01 UTC, yuki-takei requested changes

2024-10-16 13:01 UTC, yuki-takei commented on apps/app/src/features/openai/chat/components/AiChatModal/AiChatModal.tsx
createThread でもエラーハンドリングをする

2024-10-17 00:42 UTC, miya commented on apps/app/src/features/openai/chat/components/AiChatModal/AiChatModal.tsx
追加しました

2024-10-17 00:42 UTC, miya commented on apps/app/src/features/openai/server/routes/message.ts
`routes/thread`  では thread を取得 or 作成したものをクライアントに返却する、ということをやっていているため、これに失敗した場合は 「スレッドの作成または取得に失敗しました」というトースターを表示させるようにしましました。そのためサーバーサイドには手を入れていません。

2024-10-17 13:21 UTC, yuki-takei approved these changes

2024-10-17 13:42 UTC, yuki-takei commented
@mergify requeue

2024-10-17 14:14 UTC, merged