feat: Implement OpenAI thread model
weseek/growi pull request #9254
Opened 2024-10-17 01:25 UTC by miya

## Task
- [#155005](https://redmine.weseek.co.jp/issues/155005) [RAG] 使われなくなった Thread が自動で削除される
  -  [#155690](https://redmine.weseek.co.jp/issues/155690) thread model の実装

2024-10-17 10:21 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +    const thread = await this.client.retrieveThread(threadRelation.threadId);
thread-relation document が存在していれば OpenAI 側の thread 実態をチェック

2024-10-17 10:21 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +    await threadRelation.updateThreadExpiration();
- OpenAI 側に thread の実態が存在していれば thread の有効期限を延長
- 過去に作成した thread にメッセージを新規に追加する場合は延長するべきと考えた
　- thread を参照しただけでは延長は不要か..？

2024-10-17 10:26 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +    const threadRelation = await ThreadRelationModel.findOne({ threadId });
以下の commit で対策済み
https://github.com/weseek/growi/pull/9254/commits/691329156bac3bfc5e5d5a7d779e04c1dfede306

2024-10-17 13:37 UTC, yuki-takei commented on apps/app/src/features/openai/server/services/openai.ts
> +    }
vector store と同じ手順で作成してください

1. ThreadRelation を作成
2. `client.createThread`
    - try-catch で失敗したら ThreadRelation を削除、catch した err を更に throw
 
(たしかこの順だったと思うけど、逆なら逆で揃える)

2024-10-17 13:38 UTC, yuki-takei commented on apps/app/src/features/openai/server/services/openai.ts
> +    }
指定された ID の ThreadRelation が存在しなければ throw error なんじゃないかな

2024-10-17 13:40 UTC, yuki-takei commented on apps/app/src/features/openai/server/services/openai.ts
> +      const vectorStore = await this.getOrCreateVectorStoreForPublicScope();
vector store は外から渡すべきだと思う
(将来 public scope でないものにも対応できるように)

2024-10-18 01:56 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +    }
修正しました

2024-10-18 01:57 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +      const vectorStore = await this.getOrCreateVectorStoreForPublicScope();
修正しました

2024-10-18 02:02 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +    }
修正しました

https://github.com/weseek/growi/pull/9254/commits/1d672f2e9c2f0fc71d6543bd982789d566a79599

2024-10-18 02:07 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +    }
VectorStore、VectorStoreFile 共に以下のような順番になっています

1. OpenAI 側の Create の API を叩く
2. 1 に成功したらそれに対応するデータを保存する
3. (VectorStoreFile だけ) 1 に失敗した場合は 2 を実行せずにアップロードしたファイルを削除

### VectorStore の作成
https://github.com/weseek/growi/blob/6d3919d9a366adaf3997b3a7d2a2e1ebcfc49065/apps/app/src/features/openai/server/services/openai.ts#L88-L92

### VectorStoreFile の作成
https://github.com/weseek/growi/blob/6d3919d9a366adaf3997b3a7d2a2e1ebcfc49065/apps/app/src/features/openai/server/services/openai.ts#L142-L159

2024-10-18 12:39 UTC, yuki-takei requested changes

2024-10-21 09:09 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +      }
this.deleteVectorStoreFile (アップロードされた file の削除とそれに紐つく document の削除) を使う実装に変更

2024-10-21 09:09 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +      }
vector-store document は存在するが VectorStore の実体が存在しない場合は vector-store document の削除

2024-10-21 09:41 UTC, yuki-takei commented on apps/app/src/features/openai/server/services/openai.ts
> +      await VectorStoreFileRelationModel.upsertVectorStoreFileRelations(vectorStoreFileRelations);
1 file (実態)のアップロード
2 vector stor file relations の作成(model)
3 vector store への紐付け(実態)

この順で実行することにした。これにより3に失敗した場合、catch ブロックで1の削除を試行するが、rate limit に引っかかってしまったとしても2のデータを残せるようになった。これは、1のデータを削除するのに有用である。

仮に 3 を 2 より先に実行すると、vector store file 実態の作成失敗した場合に catch ブロックで1の
削除を試行するが、ここで rate limit に引っかかってしまうと 2 のデータも 3のデータも存在しない状態で 1 のデータだけが残るので、その後削除のしようがなくなってしまう。

2024-10-21 09:41 UTC, merged