add pdf-converter app
weseek/growi pull request #9279
Opened 2024-10-20 08:08 UTC by arafubeatbox

## task
https://redmine.weseek.co.jp/issues/153347

2024-10-20 09:43 UTC, arafubeatbox commented
github がバグって差分が正しく反映されていなかったので、PR の open/close を繰り返していましたm(_ _)m

2024-10-20 10:01 UTC, arafubeatbox commented on apps/pdf-converter/.gitignore
> +/specs/**/*.json
specs に openapi spec を出力する設定にしていますが、
https://github.com/tsedio/tsed-cli/tree/master/packages/cli-generate-swagger
に yaml だけ出力するオプションがありませんでした (コードも確認しました

2024-10-20 10:02 UTC, arafubeatbox commented on apps/pdf-converter/package.json
> +    "build": "yarn gen:client-code && tsc -p tsconfig.build.json"
build 時に gen:client-code でクライアントコードも自動生成しています。

2024-10-20 10:14 UTC, arafubeatbox commented on apps/pdf-converter/.eslintrc.js
> +    '@typescript-eslint/consistent-type-imports': 'off',
ts.ed で DI している場所で `@typescript-eslint/consistent-type-imports` がオンになっていると、DI 対象の import が type のみの import に強要されますが、その結果 DI された対象が何であっても実体のない [Function: anonymous] となってしまいます。
例えば DI された hoge に対して hogeMethod を実行すると `TypeError: hoge.hogeMethod is not a function`
となってしまいます。

多分 ts.ed の DI では、DI 対象の実装本体を import する必要があるっぽいです。

2024-10-23 19:24 UTC, yuki-takei requested changes

2024-10-23 19:24 UTC, yuki-takei commented on apps/pdf-converter/docker/Dockerfile
> +ENTRYPOINT ["/usr/bin/tini", "-e", "143", "--"]
tini は不要
https://tips.weseek.co.jp/6151b1832b337100519281e7

terminus と連携して解決するのが望ましい
https://tsed.io/tutorials/terminus.html

後続ストーリーで対応をお願いしたい

2024-10-23 19:24 UTC, yuki-takei commented on apps/pdf-converter/package.json
この app は `type: module` にできないだろうか？
Ts.ED が未対応というケースもあるだろうが調査をしてほしい(後続ストーリーでOK)

2024-10-23 19:24 UTC, yuki-takei commented on apps/pdf-converter/specs/v3/docs/swagger.yaml
このファイルは .gitignore したらだめなの？

2024-10-23 19:24 UTC, yuki-takei commented on apps/pdf-converter/package.json
> +    "lint": "yarn eslint **/*.{js,ts}",
tsconfig を細かくチェックはしていないのだけれど、build での tsc は typecheck はせずにスピードを出すのが望ましい。
代わりに lint で typecheck のための tsc を走らせる。
後続ストーリーでよい。

2024-10-24 02:52 UTC, arafubeatbox commented on apps/pdf-converter/specs/v3/docs/swagger.yaml
apps/pdf-converter/src/client-library の生成元の schema がわかると良いかなと思いましたが、確かにあまり気にすることは無さそうですね。むしろ schema が手動修正 -> commit されるリスクの方が大きそうです。
ignore しますm(_ _)m

2024-10-24 03:03 UTC, arafubeatbox commented on apps/pdf-converter/package.json
https://redmine.weseek.co.jp/issues/156177 ストーリー作成しました

2024-10-24 03:42 UTC, arafubeatbox commented on apps/pdf-converter/package.json
> +    "lint": "yarn eslint **/*.{js,ts}",
https://redmine.weseek.co.jp/issues/156178 ストーリー作成しました。

2024-10-24 03:47 UTC, arafubeatbox commented on apps/pdf-converter/docker/Dockerfile
> +ENTRYPOINT ["/usr/bin/tini", "-e", "143", "--"]
ストーリー作成しました。 https://redmine.weseek.co.jp/issues/156179

2024-10-24 07:27 UTC, yuki-takei approved these changes

2024-10-24 07:27 UTC, merged