Feat/135772 155547 pdf converter tsed devcontainer
weseek/growi pull request #9280
Opened 2024-10-20 08:09 UTC by arafubeatbox

## task
https://redmine.weseek.co.jp/issues/155547

2024-10-25 09:22 UTC, yuki-takei requested changes

2024-10-25 09:22 UTC, yuki-takei commented on .devcontainer/app/devcontainer.json
pnpm 化に乗じて devcontainer 関連ファイルもかなり変えたので、新しい方式に則ってください

2024-10-25 09:22 UTC, yuki-takei commented on .devcontainer/docker-compose.yml
> +      - node_modules_pdf_converter:/workspace/growi/apps/pdf-converter/node_modules
node_modules_pdf_converter volume も不要になると思う
(ただの symlink 置き場なので volume 管理しなくてよい)

2024-10-25 09:22 UTC, yuki-takei commented on turbo.json
> +    },
リポジトリ内の別のパッケージのビルドに依存するとかがなければ、トップレベルの turbo.json には書かなくてもいい気はする

- 単に `apps/pdf-converter` に移動してから pnpm 叩くでもよい
- トップレベルのディレクトリから実行したいならトップの package.json に追加する( `slackbot-proxy:*` script がそのような設計)
- pdf-converter 内の複数スクリプトを叩かせたいなら `pdf-converter/turbo.json` を用意する

2024-11-06 13:33 UTC, arafubeatbox commented on turbo.json
> +    },
> 単に apps/pdf-converter に移動してから pnpm 叩くでもよい

これにしようと思います。apps/pdf-converter でのコマンドも単純な dev にしました。

2024-11-09 12:33 UTC, arafubeatbox commented on .devcontainer/compose.yml
> +    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-20
docker-compose によって devcontainer が二つ立ち上がりますが、二つ目に立ち上がった devcontainer  ではどうしても features が有効になりませんでした。仕様なのかバグなのかは分かりませんが、ドキュメントを漁っても原因がわからなかったため一旦 base image を node が入ったものにして、[issue 起票](https://github.com/devcontainers/features/issues/1175) しました。

2024-11-10 06:04 UTC, arafubeatbox commented on .devcontainer/app/devcontainer.json
> +      }
自分の環境だと zsh でターミナルが起動されてしまい、postCreateCommand で bashrc に書き込んだ設定が読み込まれませんでした。

2024-11-11 13:37 UTC, merged