enable pdf bulk export
weseek/growi pull request #9283
Opened 2024-10-20 09:26 UTC by arafubeatbox

## task
https://redmine.weseek.co.jp/issues/153348

2024-11-13 14:09 UTC, arafubeatbox commented on apps/pdf-converter/package.json
> +    "dev:pdf-converter": "nodemon --watch \"src/**/*.ts\" --ignore \"node_modules/**/*\" --exec ts-node -r \"dotenv-flow/config\" src/index.ts",
右往左往してすみません、pdf-converter はアプリであると同時に (クライアントライブラリを app に読み込むために) app の dependency でもあるため、アプリ起動 script を dev にしてしまうと、app の lint, test, launch-dev:ci で ^dev によって実行対象になってしまいました。
https://github.com/weseek/growi/blob/44321d16106889fef74260e2b2a812bb76baf897/apps/app/turbo.json#L59

"persistent": true にしても
```
Error:   × "@growi/pdf-converter#dev" is a persistent task, "@growi/app#lint" cannot depend on it
```
となるため、script 名を変えるしか無さそうです。そのため dev:pdf-converter に戻そうと思います。

2024-11-21 15:41 UTC, yuki-takei requested changes

2024-11-21 15:41 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts
> +  }
`remark().use(html)` で得られるインスタンスは保持して使い回した方がいいんじゃないかな
どこまで差が出るかはわからないけど

2024-11-21 15:41 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts
> +  }
このメソッドはレビューしきれてないので引き続き

2024-11-21 15:41 UTC, yuki-takei commented on apps/app/turbo.json
slackbot-proxy を起動しなくても app が使えるように、
pdf-converter もまた app の起動に必須ではないので、dependsOn からは外してほしい。

開発時に開発者がやらないといけないことはマニュアルに書いて周知する。

2024-11-22 12:09 UTC, arafubeatbox commented on apps/app/turbo.json
こちら pdf-converter の起動ではなく、クライアントコード生成のための build になります。
pdf-converter の起動は無関係であり、これを取り除くと `Error: Cannot find module '@growi/pdf-converter/dist/client-library'` が `apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts` で生じてしまいます。

それはそれとして、pdf-converter の開発ドキュメントは書こうと思います。
ストーリー作成しました。
https://redmine.weseek.co.jp/issues/157930

2024-11-22 12:10 UTC, yuki-takei requested changes

2024-11-22 12:10 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts
> +      const interval = setInterval(async() => {
setInterval より node-cron を使うべきではないか？

また、サーバーが再起動した時に job を参照して再開してほしい。

参考:
- thread-deletion-cron.ts
- vector-store-file-deletion-cron.ts

2024-11-22 12:59 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts
> +  }
対応しました。
インスタンス変数にして全ての job で共通にするのは並列で処理が走ったときバグる可能性があるように思えたので、ジョブごとに stream 開始前に定義して引数として渡す形にしました。

引数の型ですが、remark().use(html) の返り値の type が unified のものですが、
```
unified.Processor<remark.RemarkOptions>
```
remark が依存している unified と growi が package.json で指定している unified のバージョンが異なるっぽくて、同様の type を付与するとエラーが生じてしまいます。
そのため引数に type は付与していません。
(バージョンを対応させようとすると、esm only の remark 系のパッケージが必要となり、エラーが生じてしまいます)

2024-11-25 09:27 UTC, yuki-takei requested changes

2024-11-25 09:27 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts
> +  }
- 使われるバージョンが一致するように別タスクで処理した方がいいように思う
- サーバーサイドでの ESM only package のインポートは、`dynamic-import` で対応できる
    - `import { dynamicImport } from '@cspell/dynamic-import';` でソース内検索

2024-11-25 09:29 UTC, yuki-takei commented on apps/app/turbo.json
> クライアントコード生成のための build になります

なるほど。理解した。
apps/* 間の依存はない方がいいかなとも思ったけど、どうなんだろう。
`@growi/slack` みたいに分けてすっきりするなら分けていいけど、分けるメリットを感じないならそのままでOK

2024-12-14 05:51 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts
> +  }
https://redmine.weseek.co.jp/issues/159172
タスク作りました。

2024-12-14 07:21 UTC, arafubeatbox commented on apps/pdf-converter/src/service/pdf-convert.ts
> -    if (this.puppeteerCluster == null) await this.initPuppeteerCluster();
initPuppeteerCluster の実行が完了しないまま registerOrUpdateJob が再度呼ばれてしまうと puppeteer cluster が複数立ち上がってしまうため、onInit で初期化するように変更。

2024-12-14 07:24 UTC, arafubeatbox commented on apps/pdf-converter/package.json
> +    "gen:client-code": "SWAGGER_GENERATION=true tsed run generate-swagger --output ./specs && orval",
apps/pdf-converter/src/service/pdf-convert.ts で $onInit で puppeteer を初期化するように変更した結果、tsed run generate-swagger で puppetter のエラー (Error: Unable to launch browser, error message: Could not find Chrome (ver. 130.0.6723.69)) が生じるようになったが、swagger schema 生成に puppeteer は必要ないため、SWAGGER_GENERATION=true の時立ち上げないように設定。

2024-12-14 07:37 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export/index.ts
> +      const interval = setInterval(async() => {
https://redmine.weseek.co.jp/issues/158220 で service を cron 化し、pdf 化の処理については request-pdf-converter 内に記載し、cron 内で呼び出すように実装しました。

2024-12-14 07:41 UTC, arafubeatbox commented on apps/app/turbo.json
別パッケージ化するべきかの検討も含めて
https://redmine.weseek.co.jp/issues/159173
でしたいと思います。しない場合は理由をご連絡します。

2024-12-14 08:01 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
> +      }
以下の流れを想定

1.  L166 の非同期実行されている createPageSnapshotsAsync が完了し、status が exporting になる
2. cron 実行の度、requestPdfConverter が実行されるようになる
    - pdf 変換が完了するまで statusOnPreviousCronExec が同じになるため、L154 より前に実行する必要がある
3. L169 の exportPagesToFsAsync が非同期で実行される
4. 非同期で実行されている exportPagesToFsAsync が完了し、HTML でのエクスポートが完了する
5. pdf converter での pdf 変換処理が完了する
6. requestPdfConverter で pdf 変換処理を検知し、status が uploading になる

2024-12-16 12:14 UTC, yuki-takei approved these changes

2024-12-16 12:14 UTC, yuki-takei commented on apps/pdf-converter/package.json
> +    "gen:client-code": "SWAGGER_GENERATION=true tsed run generate-swagger --output ./specs && orval",
この先この仕様をしらないプログラマがどのサービスの onInit に何を仕込むかわからないから、generate-swagger するためだけのエントリーポイントを作るのがよさそうかなと (後続ストーリーでよい)

2024-12-16 12:14 UTC, merged