feat: Delete obsolete VectorStoreFile when rebuilding VectorStore
weseek/growi pull request #9326
Opened 2024-10-28 10:06 UTC by miya

# Task
- [#156483](https://redmine.weseek.co.jp/issues/156483) [RAG] rebuild 時に既存の VectorStoreFile を削除できる
  -  [#156485](https://redmine.weseek.co.jp/issues/156485) 実装

2024-10-28 15:54 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +    ).limit(limit);
削除された VectorStore に紐ついていた vector-store-file-relation document の取得

2024-10-28 15:54 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +        await oepnaiApiErrorHandler(err, { notFoundError: async() => { deletedFileIds.push(fileId) } });
- VectorStoreFile 削除時に対象 VectorStoreFile が存在しなかった場合に vector-store-file-relation docment に　fileId が残り続けるのは良くないので削除する

2024-10-29 09:11 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +      await oepnaiApiErrorHandler(err, { notFoundError: vectorStoreDocument.markAsDeleted });
OpenAI 側で NotFoundError が出た場合は関連 document の isDeleted フラグを true にする

2024-10-29 12:08 UTC, yuki-takei requested changes

2024-10-29 12:08 UTC, yuki-takei commented on apps/app/src/features/openai/server/services/openai.ts
> +  }
$lookup はコストが高いと思う。

vectorstorefilerelations に対して aggregation し、同一 vector store でグルーピングして数をカウントした方が低コスト。

2024-10-29 12:08 UTC, yuki-takei commented on apps/app/src/server/service/config-loader.ts
> +  },
`OPENAI_` prefix を付けてください

2024-10-30 04:47 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +      await oepnaiApiErrorHandler(err, { notFoundError: vectorStoreDocument.markAsDeleted });
修正しました

2024-10-30 04:48 UTC, miya commented on apps/app/src/features/openai/server/models/vector-store-file-relation.ts
> -    unique: true,
修正しました

2024-10-30 04:48 UTC, miya commented on apps/app/src/server/service/config-loader.ts
> +  },
修正しました

2024-10-30 04:54 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +  }
vectorstorefilerelations 対して aggegation し同一 vectorStoreRelationId でグルーピング後に vectorstorefilerelations が存在する documnt の ObjectId の配列を返却するようにしました。

2024-10-31 08:01 UTC, yuki-takei approved these changes

2024-10-31 08:12 UTC, merged