fix:  Deleted pages appear in the page tree
weseek/growi pull request #9337
Opened 2024-10-31 07:06 UTC by reiji-h

# Task
- https://redmine.weseek.co.jp/issues/126846

2024-11-01 09:24 UTC, miya approved these changes

2024-11-08 11:00 UTC, yuki-takei commented
useSWRxPageAncestorsChildren の自動 revalidation を許すと、API を叩く回数が増えるのを心配している。

https://swr.vercel.app/ja/docs/revalidation#disable-automatic-revalidations

関係ないトリガーはもう少し抑制できないだろうか。

2024-11-08 11:01 UTC, yuki-takei requested changes

2024-11-08 11:01 UTC, yuki-takei commented on apps/app/src/stores/page-listing.tsx
> +  return useSWR(
useSWRxPageAncestorsChildren の自動 revalidation を許すと、API を叩く回数が増えるのを心配している。

https://swr.vercel.app/ja/docs/revalidation#disable-automatic-revalidations

関係ないトリガーはもう少し抑制できないだろうか。

2024-11-08 11:01 UTC, yuki-takei commented on apps/app/src/client/components/TreeItem/TreeItemLayout.tsx
> +      console.log('This is new data!!!!: ', newChildren);
console.log は消してください

2024-11-21 05:58 UTC, reiji-h commented on apps/app/src/client/components/TreeItem/TreeItemLayout.tsx
> +      console.log('This is new data!!!!: ', newChildren);
消し忘れていました。削除しました。

2024-11-21 06:16 UTC, reiji-h commented on apps/app/src/stores/page-listing.tsx
> +  return useSWR(
`useSWRxPageAncestorsChildren` の useSWR を Immutable に戻しました。

`TreeItemLayout.tsx` の受け取る PageTree の情報は、上位から受け取る `useSWRxPageAncestorsChildren` の childrenA と 41 行目の `useSWRxPageChildren` の childrenB の2つがありました。/trash に遷移した際、childrenA は削除したものが残っており、childrenB はちゃんと消えていました。常に childrenB の情報のほうが正しかったので、childrenA を受け取るのを辞める形で変更しました。

2024-11-22 12:47 UTC, yuki-takei approved these changes

2024-11-22 13:00 UTC, merged