feat: Retrieve the source (Page) of the knowledge assistant's response results
weseek/growi pull request #9362
Opened 2024-11-06 07:20 UTC by miya

## Task
- [#156805](https://redmine.weseek.co.jp/issues/156805) [RAG] ナレッジアシスタント上で出典元を表示できる
  - [#156884](https://redmine.weseek.co.jp/issues/156884) クライアント側で出典元 (pageId) を取得できる

2024-11-06 14:43 UTC, miya commented on apps/app/src/features/openai/server/services/annotation-replacer.ts
annoation の置換方法は公式を参考にしました
https://platform.openai.com/docs/assistants/tools/file-search#step-5-create-a-run-and-check-the-output

2024-11-06 14:43 UTC, miya commented on apps/app/src/features/openai/chat/components/AiChatModal/MessageCard.tsx
> +};
リンクをクリックした時にページ遷移できるようにした next/link のラップコンポーネント

2024-11-06 14:43 UTC, miya commented on apps/app/src/features/openai/server/services/annotation-replacer.ts
> +          const { t } = await getTranslation(lang);
user の言語によって翻訳できるようにした

2024-11-07 07:50 UTC, yuki-takei requested changes

2024-11-07 07:50 UTC, yuki-takei commented on apps/app/src/features/openai/chat/components/AiChatModal/MessageCard.tsx
> +};
`ReactMarkdwnComponents/NextLink` はそのまま使えなかったの？

2024-11-07 07:50 UTC, yuki-takei commented on apps/app/src/features/openai/server/services/annotation-replacer.ts
> +export const annotationReplacer = async(delta: MessageDelta, lang: Lang): Promise<void> => {
- メソッドの名前は動詞から始めたい
- `lang` は undefined でも動くようにしてください

2024-11-07 07:50 UTC, yuki-takei commented on apps/app/src/features/openai/server/services/annotation-replacer.ts
> +export const annotationReplacer = async(delta: MessageDelta, lang: Lang): Promise<void> => {
少し処理コストの心配をしている。以下2点で問題があるなら後続タスクでやってほしい。

1. annotationReplacer が、一度の質問＆応答で何回呼ばれるのかを知りたい
1. それから `for await (const annotation of annotations) {` が回るのは annotation の数だけなのか
    - N+1 問題なのでできれば 1 クエリで取得したいが、annotation の数はそう多くないので許容してもいいかもしれない

2024-11-07 07:50 UTC, yuki-takei commented on apps/app/src/features/openai/server/services/annotation-replacer.ts
> +          );
appSiteUrl なしでリンク作れるよね？

2024-11-07 08:51 UTC, miya commented on apps/app/src/features/openai/server/services/annotation-replacer.ts
> +export const annotationReplacer = async(delta: MessageDelta, lang: Lang): Promise<void> => {
> 1. annotationReplacer が、一度の質問＆応答で何回呼ばれるのかを知りたい

クライアントに文字を送信させる度に呼ばれます。以下の if ブロックで annotation がなければ、以降の処理は呼ばれないようになっています (DB アクセスなどしない)。

[https://github.com/weseek/growi/blob/797cf152ad0aec36f2218c063f8fc1937256c2db/apps[…]/app/src/features/openai/server/services/annotation-replacer.ts](https://github.com/weseek/growi/blob/797cf152ad0aec36f2218c063f8fc1937256c2db/apps/app/src/features/openai/server/services/annotation-replacer.ts#L15)

2024-11-07 09:28 UTC, miya commented on apps/app/src/features/openai/chat/components/AiChatModal/MessageCard.tsx
> +};
ReactMarkdwnComponents/NextLink を利用するように修正しました。onClick を渡した状態のコンポーネントを react-markdown に渡す方法が思いつかなかったためラップしたものを渡すようにしています。

2024-11-07 10:20 UTC, miya commented on apps/app/src/features/openai/server/routes/message.ts
> +        }
replaceAnnotationWithPageLink() を利用する側でも annotation の有無をチェックするようにした

commit: https://github.com/weseek/growi/pull/9362/commits/6e3b9f28fa526b7c7f5ebd163efb65174477cdd8

2024-11-07 10:21 UTC, miya commented on apps/app/src/features/openai/server/services/annotation-replacer.ts
> +export const annotationReplacer = async(delta: MessageDelta, lang: Lang): Promise<void> => {
> - メソッドの名前は動詞から始めたい
> - lang は undefined でも動くようにしてください

こちらは修正しました

2024-11-07 11:36 UTC, yuki-takei requested changes

2024-11-07 11:36 UTC, yuki-takei commented on apps/app/src/components/ReactMarkdownComponents/NextLink.tsx
> +  onClickNextLink?: () => void,
この props の作成必要？ LinkProps に onClick あると思う

2024-11-07 11:36 UTC, yuki-takei commented on apps/app/src/features/openai/server/services/replace-annotation-with-page-link.ts
> +type PopulatedVectorStoreFileRelation = Omit<VectorStoreFileRelation, 'pageId'> & { pageId: IPageHasId }
- この型は不要
- `.populate<{ foo: T }>('foo');` を使う

2024-11-08 08:12 UTC, miya commented on apps/app/src/features/openai/chat/components/AiChatModal/MessageCard.tsx
> +};
NextLink.tsx は next/link を使った要素の他に通常の a タグを使った要素も存在することからそれぞれの要素に対して別の onClick を渡せるようにしたつもりでした。それは少し冗長な気もするので onClick で統一するように改修しました。

NextLink.tsx
```typescript 

if (isExternalLink(href, siteUrl)) {
  return (
    <a id={id} href={href} className={className} target="_blank" onClick={onClick} rel="noopener noreferrer" {...dataAttributes}>
      {children}&nbsp;<span className="growi-custom-icons">external_link</span>
    </a>
  );
}

// when href is an anchor link or not-creatable path
if (isAnchorLink(href) || !isCreatablePage(href)) {
  return (
    <a id={id} href={href} className={className} onClick={onClick} {...dataAttributes}>{children}</a>
  );
}

return (
  <Link {...rest} href={href} prefetch={false} legacyBehavior>
    <a href={href} className={className} {...dataAttributes} onClick={onClick}>{children}</a>
  </Link>
);

```

2024-11-08 08:13 UTC, miya commented on apps/app/src/components/ReactMarkdownComponents/NextLink.tsx
> +  onClickNextLink?: () => void,
NextLink.tsx は next/link を使った要素の他に通常の a タグを使った要素も存在することからそれぞれの要素に対して別の onClick を渡せるようにしたつもりでした。それは少し冗長な気もするので onClick で統一するように改修しました。

NextLink.tsx
```typescript 

if (isExternalLink(href, siteUrl)) {
  return (
    <a id={id} href={href} className={className} target="_blank" onClick={onClick} rel="noopener noreferrer" {...dataAttributes}>
      {children}&nbsp;<span className="growi-custom-icons">external_link</span>
    </a>
  );
}

// when href is an anchor link or not-creatable path
if (isAnchorLink(href) || !isCreatablePage(href)) {
  return (
    <a id={id} href={href} className={className} onClick={onClick} {...dataAttributes}>{children}</a>
  );
}

return (
  <Link {...rest} href={href} prefetch={false} legacyBehavior>
    <a href={href} className={className} {...dataAttributes} onClick={onClick}>{children}</a>
  </Link>
);

```

2024-11-08 08:13 UTC, miya commented on apps/app/src/features/openai/server/services/replace-annotation-with-page-link.ts
> +type PopulatedVectorStoreFileRelation = Omit<VectorStoreFileRelation, 'pageId'> & { pageId: IPageHasId }
修正しました

2024-11-08 08:13 UTC, miya commented on apps/app/src/features/openai/server/services/replace-annotation-with-page-link.ts
> +          .populate('pageId', 'path') as PopulatedVectorStoreFileRelation;
- 修正しました
- フィールド名を変更したことに対応するマイグレーションスクリプトも追加しました

2024-11-08 09:30 UTC, yuki-takei approved these changes

2024-11-08 09:42 UTC, merged