support: ChristmasTheme with light/dark mode
weseek/growi pull request #9374
Opened 2024-11-08 03:00 UTC by satof3

# Task

https://redmine.weseek.co.jp/issues/156547

# Summary

* v7 で実装していなかったクリスマステーマの復活
* ライト/ダークモードの両方に対応

# Screenshot
![Chirstmas-light - 配色 2024 11](https://github.com/user-attachments/assets/edc0f22b-a09e-4faf-b9a2-ab5b9c776288)
![スクリーンショット 2024-11-01 16 38 27 1](https://github.com/user-attachments/assets/d4d50f6e-774e-49f5-b898-068eaa2cab9f)
<img width="1089" alt="image" src="https://github.com/user-attachments/assets/3913cab1-783f-410b-ba3b-31db30244031">

2024-11-08 06:51 UTC, yuki-takei requested changes

2024-11-08 06:51 UTC, yuki-takei commented on packages/preset-themes/src/styles/christmas.scss
> +$gray-900: #362824;
indent 揃えてください

2024-11-08 06:51 UTC, yuki-takei commented on packages/preset-themes/src/styles/christmas.scss
> +    --bs-border-color: var(--grw-primary-200);
header 下以外の部分で問題がないかチェックしてください(テーブルとか)

2024-11-11 04:46 UTC, satof3 commented on packages/preset-themes/src/styles/christmas.scss
> +$gray-900: #362824;
揃えました

2024-11-11 04:48 UTC, satof3 commented on packages/preset-themes/src/styles/christmas.scss
> +    --bs-border-color: var(--grw-primary-200);
テーブルの線の主張が強すぎる印象だったので header のみborder に適用しようと思います
![image](https://github.com/user-attachments/assets/db7ae385-f582-4600-9da2-f2692dee64e4)
![image](https://github.com/user-attachments/assets/753691a6-b9bd-4fd0-b509-5340b28aed3d)

2024-11-11 14:10 UTC, yuki-takei commented
@mergify queue

2024-11-11 14:10 UTC, yuki-takei approved these changes

2024-11-11 14:35 UTC, merged