imprv: design of scrollbar in sidebar
weseek/growi pull request #9430
Opened 2024-11-22 06:41 UTC by reiji-h

# Summary
- Sidebar のスクロールバーをブラウザ標準からカスタマイズしたものに変更

# Task
- https://redmine.weseek.co.jp/issues/139655
  - https://redmine.weseek.co.jp/issues/154366

# Screenshot 

https://github.com/user-attachments/assets/5fdb32e6-1da5-40fb-b503-0c5eb56f9f2a

2024-11-28 09:07 UTC, yuki-takei requested changes

2024-11-28 09:07 UTC, yuki-takei commented on apps/app/src/client/components/Sidebar/Sidebar.module.scss
> +    }
light/dark で値を変える必要がないのであれば一箇所にまとめてください。
付近にこの記述のみを書いた新規ブロックを作ればいいと思う。

2024-11-28 09:35 UTC, reiji-h commented on apps/app/src/client/components/Sidebar/Sidebar.module.scss
> +    }
light/dark のすぐ上に新規ブロックを作成し移動しました。
また、サイドバーの全モードでの自動スクロール、Dock Mode での自動開閉に問題ないことを確認しました。

2024-11-29 09:00 UTC, yuki-takei approved these changes

2024-11-29 09:15 UTC, merged