fix: Wider-clipboard-area
weseek/growi pull request #9450
Opened 2024-11-28 04:15 UTC by Ryosei-Fukushima

https://redmine.weseek.co.jp/issues/157769
ページのタイトルにカーソルを合わせた時、カーソルが少しでもずれるとクリップボードが出てこなくなってしまっていた。

修正点
PagePathNavTitle.module.scssでmin-widthを加えることで反応範囲を広げました。

2024-12-16 11:28 UTC, yuki-takei requested changes

2024-12-16 11:28 UTC, yuki-takei commented on apps/app/src/components/Common/PagePathNav/PagePathNavLayout.tsx
> +  };
この解決策は大仰すぎるし複雑です。別の解決策を提示してください。

2024-12-18 05:13 UTC, Ryosei-Fukushima commented on apps/app/src/components/Common/PagePathNav/PagePathNavLayout.tsx
> +  };
この部分を削除し、わかりやすく簡素にしました。
ボタン分のヒットエリアを広げました。

2024-12-18 09:54 UTC, yuki-takei approved these changes

2024-12-18 10:08 UTC, merged