Imprv/158220 158223 add page bulk export job cron
weseek/growi pull request #9461
Opened 2024-12-01 03:56 UTC by arafubeatbox

2024-12-01 08:46 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
> +  }
PageBulkExportService からの抽出

2024-12-01 08:47 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
> +  }
PageBulkExportService からの抽出

2024-12-01 08:47 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
> +  async handlePipelineError(err: Error | null, pageBulkExportJob: PageBulkExportJobDocument) {
PageBulkExportService からの抽出

2024-12-01 08:47 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
> +  async notifyExportResultAndCleanUp(
PageBulkExportService からの抽出

2024-12-01 08:48 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
> +  async cleanUpExportJobResources(pageBulkExportJob: PageBulkExportJobDocument, restarted = false) {
PageBulkExportService からの抽出

2024-12-01 08:48 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
> +  private async notifyExportResult(
PageBulkExportService からの抽出

2024-12-01 08:49 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/steps/compress-and-upload-async.ts
> +
このファイル内の関数は全て PageBulkExportService からの抽出

2024-12-01 08:49 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/steps/create-page-snapshots-async.ts
> +
このファイル内の関数は全て PageBulkExportService からの抽出

2024-12-01 08:49 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/steps/export-pages-to-fs-async.ts
> +
このファイル内の関数は全て PageBulkExportService からの抽出

2024-12-01 12:48 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
> +class PageBulkExportJobCronService extends CronService implements IPageBulkExportJobCronService {
executeJob (cronjob の実行対象) で実行される proceedBulkExportJob がキモ。それ以外はほとんど PageBulkExportService からの抽出。

PageBulkExportJob が中断された際に実行中の stream も停止する必要があるため、streamInExecutionMemo を追加 (PageBulkExportService では PageBulkExportJobManager が担っていた)

2024-12-03 12:21 UTC, yuki-takei requested changes

2024-12-03 12:21 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
> +  crowi: any;
Crowi 型を参照させてください

2024-12-03 12:21 UTC, yuki-takei commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
> +    this.userModel = mongoose.model<IUser>('User');
mongoose.model() によるモデルオブジェクト取得は、それを利用するメソッドの冒頭で実行してください

2024-12-03 12:46 UTC, merged