Feat/15822 158280 allow enabling disabling bulk export
weseek/growi pull request #9470
Opened 2024-12-08 05:00 UTC by arafubeatbox

## task
https://redmine.weseek.co.jp/issues/158280

2024-12-08 05:02 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-clean-up-cron.ts
> -    if (!isPageBulkExportEnabled) return;
crowi index.js から実行有無の場合分けをするように変更

2024-12-08 05:17 UTC, arafubeatbox commented on apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-clean-up-cron.ts
> +    // Execute cleanup even if isPageBulkExportEnabled is false, to cleanup jobs which were created before bulk export was disabled
有効になっていた時の PageBulkExportJob を cleanup するために、bulk export が無効にされていても cleanup cron job は実行する (一日一回実行のため問題ないと判断

2024-12-09 13:13 UTC, yuki-takei requested changes

2024-12-10 13:24 UTC, arafubeatbox commented on apps/app/src/server/service/config-loader.ts
> +  },
対応しました。
https://github.com/weseek/growi/pull/9470/commits/dea363219e0ada2eb0bcd3f6ea1e4c81b65e484d
https://github.com/weseek/growi/pull/9470/commits/03b7f64decb69351b5c1d7027278c9c732e41f71

2024-12-10 13:28 UTC, arafubeatbox commented on apps/app/src/client/components/Admin/App/AppSetting.jsx
> +          )}
isFixedIsBulkExportPagesEnabled が true の時 (apps/app/src/client/components/Admin/App/FileUploadSetting.tsx を参考に実装)
![ 2024-12-10 at 22 03 35](https://github.com/user-attachments/assets/4202bb16-15a6-4fb9-a929-1d58f0714ff5)

2024-12-10 14:53 UTC, arafubeatbox commented on apps/app/src/client/components/Admin/App/AppSetting.jsx
> +      </div>
> 有効にすることによる管理上のデメリットってあると思うので、もうちょっと詳細な注意事項も一緒に書くべきかなあ

対応しました: https://github.com/weseek/growi/pull/9470/commits/4bd1b3d8075ba6d41e95127a9a1de6a3faf95e1f

2024-12-11 13:11 UTC, yuki-takei commented on apps/app/src/server/service/config-loader.ts
> +  },
良いと思います

2024-12-11 13:13 UTC, yuki-takei approved these changes

2024-12-11 13:13 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/admin.json
> +    "page_bulk_export_warning": "エクスポート結果のダウンロード期限は24時間で、それを過ぎるとファイルシステムから削除されます。この間にページ数の多いエクスポートを連続で実行すると、ファイルシステムを圧迫する可能性があります。",
ダウンロード期限って24時間固定だったんだ
ちょっと短いような…金曜夜に仕掛けて帰宅したら月曜出社した時にはもう消えてる
カスタマイズできるとよいね(後続ストーリーでOK)

2024-12-11 13:13 UTC, merged