Feat/158980 158982 enable changing bulk export result download period
weseek/growi pull request #9482
Opened 2024-12-12 14:19 UTC by arafubeatbox

2024-12-12 14:39 UTC, arafubeatbox commented on apps/app/src/client/components/Admin/App/QuestionnaireSettings.tsx
最初アンケート設定のフォームを参考にしていましたが、アンケートフォームだけ他のフォームと異なり左詰めになっていて歪だったのに気づいたので直しました。

## before
![image](https://github.com/user-attachments/assets/80ec7c8b-8546-4a4c-966a-31c2a39a4ed0)

## after
![image](https://github.com/user-attachments/assets/05aae811-7e00-42d9-82ee-4ab06af02f83)

2024-12-15 04:28 UTC, arafubeatbox commented on apps/app/src/client/components/Admin/App/QuestionnaireSettings.tsx
変更内容は bootstrap の grid を使って整形しただけになります。

2024-12-16 11:25 UTC, yuki-takei requested changes

2024-12-16 11:25 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/admin.json
> +    "page_bulk_export_explanation": "一括エクスポートを有効にすると、ページメニューからそのページと配下ページのエクスポートが可能になります。エクスポート結果は設定された保存期間を過ぎるとファイルシステムから削除され、ダウンロードできなくなります。",
以下に変更

> すべてのユーザーが、ページメニューから選択したページとその配下ページをまとめてエクスポートできる機能を有効化します。エクスポートされたデータは保存期間経過後に自動的に削除されます。

2024-12-16 11:25 UTC, yuki-takei commented on apps/app/public/static/locales/ja_JP/admin.json
> +    "page_bulk_export_warning": "ページ数の多いエクスポートを連続で実行すると、ファイルシステムを圧迫する可能性があります。",
以下に変更

> ページ一括エクスポート機能は全ユーザーが利用可能です。システムリソースの維持のため、必要最小限の利用にご協力をお願いいたします。管理者の方は、この旨をユーザーの皆様にご周知ください。

2024-12-16 13:04 UTC, merged