feat: AiAssistantModel
weseek/growi pull request #9494
Opened 2024-12-17 08:38 UTC by miya

# Task
- [#159151](https://redmine.weseek.co.jp/issues/159151) [GROWI AI Next][特化型アシスタント] 新規作成モーダルから作成ボタンをクリックした時アシスタントデータが作成される
  -  [#159152](https://redmine.weseek.co.jp/issues/159152) Assistant model の実装

2024-12-17 10:11 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +    },
- 学習範囲
  - VectorStore に保存する権限の範囲を指定
  - アシスタント作成者が閲覧可能な範囲が指定できる

2024-12-17 10:11 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +      }],
Page mode を踏襲
https://github.com/weseek/growi/blob/df996cb20d7061d179c67cf0a0d89e537b6c8bcf/apps/app/src/server/models/page.ts#L137-L158

2024-12-17 10:11 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +  },
VectorStore model を踏襲
https://github.com/weseek/growi/blob/df996cb20d7061d179c67cf0a0d89e537b6c8bcf/apps/app/src/features/openai/server/models/vector-store.ts#L35-L39

2024-12-17 10:11 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +    },
VectorStore model を踏襲
https://github.com/weseek/growi/blob/df996cb20d7061d179c67cf0a0d89e537b6c8bcf/apps/app/src/features/openai/server/models/vector-store.ts#L25-L29

2024-12-17 10:11 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +};
VectorStore model 踏襲
https://github.com/weseek/growi/blob/df996cb20d7061d179c67cf0a0d89e537b6c8bcf/apps/app/src/features/openai/server/models/vector-store.ts#L42-L45

2024-12-17 17:30 UTC, yuki-takei requested changes

2024-12-17 17:30 UTC, yuki-takei commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +  instruction?: string
特化型アシスタントになったことで、実際使う時の instruction はシステム側で入れると思うんだよね
ナレッジアシスタントとかエディタアシスタントのそれぞれの役割になるように

ユーザーが指定できるのはサブの instruction になるので、additionalInstruction にしておいた方がいいかも

あと description も instruction も not optional でいいと思う。初期値は空文字列にすればいいので。

2024-12-17 17:30 UTC, yuki-takei commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +  creator: Ref<IUser>
owner にしよう

2024-12-17 17:30 UTC, yuki-takei commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +  pages: Ref<IPage>[]
pages って何用途だろ？
個別にページへの参照を追加できるというのも thread 作ったときに便利そうではあるが、vector store 利用との一貫性はないので今使い分けをするのかきちんと設計しておきたい

2024-12-17 17:30 UTC, yuki-takei commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +    },
名前変えたほうがいいかも。e-learning のためのフィールドと勘違いする。
かといって「実行ユーザー」というのが適当とも思わないんだけどね

あとこれは enum だけではなく UserGroup への参照が必要なのではないか？

2024-12-18 08:46 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +  creator: Ref<IUser>
修正済み

2024-12-19 03:11 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +  instruction?: string
修正済み

2024-12-24 07:06 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +    }],
VectorStore に保存する page の path

2024-12-24 07:06 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +  pages: Ref<IPage>[]
元々は vectroStore に保存するための page データを保存しておくためのものでしたが、冗長でしたので pagePath を保存するように修正しました

2024-12-24 07:07 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> +    },
- `ownerAccessScope` に変更しました
- grantedGroup と grantedUser フィールドを追加しました

2024-12-25 10:57 UTC, merged