feat: Implement AI Assistant creation api
weseek/growi pull request #9497
Opened 2024-12-18 07:08 UTC by miya

# Task
- [#159151](https://redmine.weseek.co.jp/issues/159151) [GROWI AI Next][特化型アシスタント] 新規作成モーダルから作成ボタンをクリックした時アシスタントデータが作成される
  -  [#159153](https://redmine.weseek.co.jp/issues/159153) アシスタントを作成するための API の実装

2025-01-09 07:36 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> -}
apps/app/src/features/openai/interfaces/ai-assistant.ts に移動

2025-01-09 07:36 UTC, miya commented on apps/app/src/features/openai/server/models/ai-assistant.ts
> -} as const;
[/Web会議室/20250107_GROWI AI Next スコープ決め](https://dev.growi.org/677ca716a9c646e269b936c8) でアシスタントのデータにこの情報は含めないということになったため削除

2025-01-09 07:36 UTC, miya commented on apps/app/src/features/openai/server/services/openai.ts
> +  }
- AiAssistantDocument の作成ロジック
- 特化型の VectorStore を作成するロジックは [特化型の VectorStore を作成できる](https://redmine.weseek.co.jp/issues/160044) で実装予定

2025-01-09 07:36 UTC, miya commented on apps/app/src/features/openai/server/routes/create-ai-assistant.ts
> +type ReqBody = Omit<AiAssistant, 'vectorStore' | 'owner'>
- `vectorStore` は OpenaiService で作成するため omit
- `owner` は req.user を入れるため omit

2025-01-14 07:25 UTC, yuki-takei requested changes

2025-01-14 07:25 UTC, yuki-takei commented on apps/app/src/features/openai/interfaces/ai-assistant.ts
> +} as const;
```
export const AiAssistantAccessScope = {
  PUBLIC_ONLY: 'publicOnly',
  OWNER: 'owner
  GROUPS: 'groups',
} as const;
```

publicOnly, owner の場合は grantedGroups は undefined、
groups の場合のみ grantedGroups に値が入ると思う。

そうすると grantedUsers は不要ではないか？

2025-01-14 07:25 UTC, yuki-takei commented on apps/app/src/features/openai/interfaces/ai-assistant.ts
> +}
```
{
  accessScope: AiAssistantAccessScope.public | AiAssistantAccessScope.owner
} |
{
  accessScope:  AiAssistantAccessScope.groups
  grantedGroups: IGrantedGroup[]
}
```
みたいにできないかな？
interface のまま定義できたかどうか自信ないけれど (type になっちゃうかも？)

2025-01-14 07:25 UTC, yuki-takei commented on apps/app/src/features/openai/server/routes/index.ts
> +    });
REST 的に post が create の意味を持つから、`/create-ai-assistant` は `/ai-assistant` 等、リソースを意味するものにしていいと思う

2025-01-16 01:31 UTC, miya commented on apps/app/src/features/openai/server/routes/index.ts
> +    });
修正しました

2025-01-16 02:13 UTC, miya commented on apps/app/src/features/openai/interfaces/ai-assistant.ts
> +}
以下のようにはできるみたいでした。提示していただいた例とは異なるので一旦そのままにしています。将来的にはあった方がいいかもしれません。

``` typescript
// 基本となるインターフェース（共通のプロパティ）
interface BaseAiAssistant {
  name: string;
  description: string;
  additionalInstruction: string;
  pagePathPatterns: string[];
  vectorStore: Ref<VectorStore>;
  owner: Ref<IUser>;
  grantedUsers?: IUser[];
  shareScope: AiAssistantShareScope;
}

// publicOnly または owner の場合の型
interface PublicOrOwnerAiAssistant extends BaseAiAssistant {
  ownerAccessScope: 'publicOnly' | 'owner';
  grantedGroups?: undefined; // undefinedを明示的に指定
}

// groups の場合の型
interface GroupsAiAssistant extends BaseAiAssistant {
  ownerAccessScope: 'groups';
  grantedGroups: IGrantedGroup[]; // 必須項目として定義
}

// 統合された型
export type AiAssistant = PublicOrOwnerAiAssistant | GroupsAiAssistant;
```

2025-01-16 02:13 UTC, miya commented on apps/app/src/features/openai/interfaces/ai-assistant.ts
> +} as const;
不要でしたので削除しました

2025-01-16 02:18 UTC, merged