support(jsdoc): add swagger document to g2g-transfer.ts
weseek/growi pull request #9509
Opened 2024-12-19 05:30 UTC by goofmint

- GET /_api/v3/g2g-transfer/files
- POST /_api/v3/g2g-transfer/
- POST /_api/v3/g2g-transfer/attachment
- GET /_api/v3/g2g-transfer/growi-info
- POST /_api/v3/g2g-transfer/generate-key
- POST /_api/v3/g2g-transfer/transfer

2024-12-20 14:40 UTC, yuki-takei commented
https://github.com/weseek/growi/pull/8810 で GrowiInfo モデルがリファクタされました。

`feat/opentelemetry` ブランチ向けに PR を出すか、または master ブランチにマージされるまでこのタスクはペンディングしてください。

2025-03-25 12:25 UTC, yuki-takei requested changes

2025-03-25 12:25 UTC, yuki-takei commented on apps/app/src/server/routes/apiv3/g2g-transfer.ts
> +   *      tags: [Export]
g2g-transfer は export とはまた別なので、一律 `GROWI to GROWI Transfer` と設定しておいてください

2025-03-25 19:23 UTC, goofmint commented on apps/app/src/server/routes/apiv3/g2g-transfer.ts
> +   *      tags: [Export]
変更しました

2025-03-26 06:31 UTC, merged