feat: 97800 159429 add shortcuts when editing
weseek/growi pull request #9512
Opened 2024-12-21 20:56 UTC by WNomunomu

2025-06-13 06:50 UTC, yuki-takei requested changes

2025-06-13 06:50 UTC, yuki-takei commented on packages/editor/src/client/stores/use-editor-settings.ts
このモジュールの改修はなぜ必要なの？
他の hook とコードが重複しているように見える

2025-06-13 06:50 UTC, yuki-takei commented on packages/editor/src/client/stores/use-editor-shortcuts.ts
各キーバインド、バラバラに実装してください (1 shortcut / 1 module)

2025-06-13 06:50 UTC, yuki-takei commented on packages/editor/src/client/stores/use-editor-shortcuts.ts
> +};
useInsertMarkdownElements のブロック版という認識
別の custom hook を export する module に切り出して

2025-06-23 10:51 UTC, WNomunomu commented on packages/editor/src/client/stores/use-editor-shortcuts.ts
> +  const makeCodeBlockExtension = useMakeCodeBlockExtension();
コードブロック化のショートカットは CodeMirror の keybind にできないので、Extension にしてます。理由もコメントとして記述しました。

2025-06-23 10:52 UTC, WNomunomu commented on packages/editor/src/client/stores/use-editor-shortcuts.ts
各キーバインドをそれぞれ1つの module に切り出しました。

2025-06-26 11:41 UTC, merged